### ISSUE TITLE
player.sendBlockChange( Location, BlockData ) & player.sendBlockChanges( Collection<BlockState> ) produce different client-side results.

### ISSUE THREAD

**Issue by tye-exe** [PaperSpigot/Paper#10010]
### Expected behavior

The block states / data sent to the client to match the values passed into the method, no matter which one i use.

Initial world state:
![image](https://github.com/PaperMC/Paper/assets/131195812/e3f22766-897d-4d94-9b96-23cdf90bdfb7)

Successful block changes sent with player.sendBlockChange() or player.sendBlockChanges():
![image](https://github.com/PaperMC/Paper/assets/131195812/61dc4bb0-f9a7-4983-bfb4-54c9daef431e)

Successful reverting the block changes sent with player.sendBlockChange() or player.sendBlockChanges():
![image](https://github.com/PaperMC/Paper/assets/131195812/a2e78e48-01ad-4371-b21a-d53d9e4a547c)

### Observed/Actual behavior

The block states sent to the client didn't match the states I passed into the method.

Initial world state:
![image](https://github.com/PaperMC/Paper/assets/131195812/e3f22766-897d-4d94-9b96-23cdf90bdfb7)

Successful block changes were initially sent with player.sendBlockChanges():
![image](https://github.com/PaperMC/Paper/assets/131195812/61dc4bb0-f9a7-4983-bfb4-54c9daef431e)

Garbled block states were sent to the client with player.sendBlockChanges():
![image](https://github.com/PaperMC/Paper/assets/131195812/6e154c73-388c-4bd5-91cb-3007303aafa4)

However, if player.sendBlockChange() is used while iterating over the collection, the correct block data is sent to the client:
![image](https://github.com/PaperMC/Paper/assets/131195812/a2e78e48-01ad-4371-b21a-d53d9e4a547c)

### Steps/models to reproduce

This code snippet is run & performs as intended to produce the [first changes](https://github.com/PaperMC/Paper/assets/131195812/61dc4bb0-f9a7-4983-bfb4-54c9daef431e):
```java
//List of blockStates to set to red_stained_glass.
List<BlockState> nearbyOutlines = member.getNearbyClaimOutlines(selectionRenderRadius);

//Sets all the block states to red_stained_glass.
for (int i = 0; i < nearbyOutlines.size(); i++) {
  BlockState state = nearbyOutlines.get(i);
  state.setType(Material.RED_STAINED_GLASS);
  nearbyOutlines.set(i, state);
}

player.sendBlockChanges(nearbyOutlines);
``` 

Running this code snippet after I've run the first one (I've only tested this with a long delay between the two), where I don't change the state from that of the default world, leads to [garbled block states](https://github.com/PaperMC/Paper/assets/131195812/6e154c73-388c-4bd5-91cb-3007303aafa4) being sent.
```java
//List of blockStates to set to revert.
List<BlockState> nearbyOutlines = member.getNearbyClaimOutlines(selectionRenderRadius);

player.sendBlockChanges(nearbyOutlines);
``` 

### Plugin and Datapack List

Running slash plugins produces this result: 
[FastAsyncWorldEdit](https://ci.athion.net/job/FastAsyncWorldEdit/615/artifact/artifacts/FastAsyncWorldEdit-Bukkit-2.8.3-SNAPSHOT-615.jar), [Mine](https://github.com/Mapty231/Mine), [spark](https://www.spigotmc.org/resources/spark.57242/download?version=489830), [SpawnFix](https://modrinth.com/plugin/spawnfix/version/1.3)

The links are to downloads for each plugin.
Running slash datapack list produces this result:
There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [file/Origins-GenesisMC[0_2_2] (world)]

The [file/Origins-GenesisMC[0_2_2] datapack is a reminant from (genesisMC)[https://modrinth.com/plugin/genesismc/version/mc1.20-v0.2.2]

### Paper version

\> version
[17:14:08 INFO]: Checking version, please wait...
[17:14:08 INFO]: This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)                                                                                                                                
You are running the latest version
Previous version: git-Paper-299 (MC: 1.20.2)

**Comment by electronicboy** [comment]
can you reproduce this using pure paper API code without other plugins installed?

**Comment by Owen1212055** [comment]
Yes, please test without FAWE.
(See https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1056 )

**Comment by OneLiteFeather** [comment]
I need help on this one as well to clarify it is a fawe or paper related issue. Not sure how to reproduce it without, can someone help?

**Comment by electronicboy** [comment]
your question makes 0 sense, if this is a paper bug it should be reproducable using pure paper API, if you have to involve FAWE to cause it, it's likely not us. Plugins like FAWE do low level modifications to the world, which is not covered by this API.

This is the only issue report I'm aware of relating to this, so I'm incling towards closing this as-is
