### ISSUE TITLE
Bug Enters All Portals Including Plugins Multiverse Core /mvtp

### ISSUE THREAD

**Issue by mineparticlemc** [PaperSpigot/Paper#10039]
### Expected behavior

**Look at the bug in that picture**
![Minecraft_ 1 20 2 17_12_2023 12_31_48 PTG](https://github.com/PaperMC/Paper/assets/129508879/183d3970-47cb-4f72-8c05-e5024ee69974)

### Observed/Actual behavior

**Watch This Video**
https://www.mediafire.com/file/8ab8yx8n3zrvvs1/Minecraft__1.20.2_-_Multiplayer_%25283rd-party_Server%2529_2023-12-17_12-39-21.mp4/file

### Steps/models to reproduce

Server Minecraft 1.20.4 / Server LifeSteal SMP **Aternos**

### Plugin and Datapack List

**Datapacks**
=[12:58:01 INFO]: There are 6 data pack(s) enabled: 
[vanilla (built-in)], [trade_rebalance (feature)], [file/armor statues v2.8.11 (MC 1.20-1.20.4).zip (world)], [file/armored elytra v1.0.9 (MC 1.20-1.20.4).zip (world)], [file/bukkit (world)], 
[file/custom villager shops v1.2.6 (MC 1.20-1.20.4).zip (world)]
[12:58:02 INFO]: There are no more data packs available

**Plugins**
=[12:59:40 INFO]: 
Server Plugins (38):
[12:59:40 INFO]: 
Paper Plugins:
[12:59:40 INFO]:  
- 
EconomyShopGUI
, 
Minepacks
[12:59:40 INFO]: 
Bukkit Plugins:
[12:59:40 INFO]:  
- 
AdvancedPortals
, 
AnimatedScoreboard
, 
BetterRTP
, 
*
ChatManager
, 
Citizens
, 
CoreProtect
, 
EasyWarp
, 
Economy
, 
Elevator
, 
Essentials
[12:59:40 INFO]:  
EssentialsChat
, 
GSit
, 
*
HealthBar
, 
LifeSteal-Smp-Plugin
, 
LoginSecurity
, 
LuckPerms
, 
Marriage
, 
MySpawn
, 
OpenInv
, 
PicoJobs
[12:59:40 INFO]:  
PlaceholderAPI
, 
PlayerHeads
, 
PvPManager
, 
RevampedLinks
, 
SkinsRestorer
, 
spark
, 
SuperVanish
, 
TabList
, 
TreeAssist
, 
*
TrollingPlus
[12:59:40 INFO]:  
Vault
, 
ViaBackwards
, 
ViaRewind
, 
ViaVersion
, 
WorldEdit
, 
WorldGuard

### Paper version

=[12:59:52 INFO]: 
Checking version, please wait...
[12:59:52 INFO]: 
This server is running Paper version git-Paper-330 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: de04cbc)
You are running the latest version
Previous version: git-Paper-329 (MC: 1.20.4)

### Other

 **I'm From Malaysia / Please Fix This**

**Comment by Warriorrrr** [comment]
Please reproduce this with no plugins first as it's likely a plugin issue, just entering a portal like in your video is not enough to reproduce the issue.
