### ISSUE TITLE
Should Paper revert PlayerDropItemEvent being called on playerdeath

### ISSUE THREAD

**Issue by QarthO** [PaperSpigot/Paper#10044]
### Observed/Actual behavior

PlayerDropItemEvent fires when a player actively drops items but ALSO fires when a player dies 

### Steps/models to reproduce

1. Put an item in your inventory
2. Die
3. Event is fired.

### Paper version

This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
You are running the latest version
Previous version: git-Paper-314 (MC: 1.20.2)

### Other

Since Paper 1.20.2 build 315 (specifically: https://github.com/PaperMC/Paper/pull/7650) the [PlayerDropItemEvent](https://jd.papermc.io/paper/1.20/org/bukkit/event/player/PlayerDropItemEvent.html) is also being fired when a player dies. 

The players are "technically" dropping items, however, this change breaks existing plugins that were previously performing actions on this event as they did not intend to also perform the action on death. 

The fix on the plugin-side is a super simple check: ``player#isDead()``... However, this does require all the plugins to update. Since this is just another build on 1.20.2, and not a big change, most server owners will (and have) just update, without knowing that it breaks plugins.

For example [GriefPrevention](https://github.com/TechFortress/GriefPrevention), an extremely popular plugin, uses this event to prevent players from dropping items while in combat, (canceling the event). Since before it wasn't being fired on player death there there was no thought to check if the player is dead. So now when a player dies in pvp combat, the event is canceled and all of their items are destroyed. Once again the plugin-fix is easy and already being implemented (can see [here](https://github.com/TechFortress/GriefPrevention/pull/2181/commits/90659fafd0d9b3820a300ee87d6a2d6bf60ddb07)). I'm sure there are lots of other plugins that use the event similarly and just like GP never checked if the player is dead... since it wasn't needed.

I believe there are 3 options

1. Leave as is, and the plugins that are impacted update immediately.
I don't like this, as this event change is so niche and not well documented and will 100% go unnoticed. Plugin developers will only notice this change after the damage has been done

2. Temporarily revert the changes, and possibly save for the next Minecraft update like 1.20.5 or 1.21
This gives time for plugin developers to do this fix. But more importantly, this will make sure server owners are updating their plugins, since most plugins break at major updates, forcing servers to update the plugins

3. Revert the change to what it was.
This will fix this problem all together. 

Option 3 seems like the simplest solution, but I'm leaning more towards option 2 as I do think PlayerDropItemEvent should be fired when a player dies considering all the same logic is being ran.

What are your thoughts?

**Comment by Machine-Maker** [comment]
I slept on it... and I think I want to just revert the event being fired. There already is a way to get all the drops, via the death event.
