### ISSUE TITLE
Monsters in powder snow sometimes take no damage

### ISSUE THREAD

**Issue by KioProject123** [PaperSpigot/Paper#10040]
### Expected behavior

Monsters in powder snow take freeze damage

### Observed/Actual behavior

They sometimes don't hurt
https://youtu.be/7Kb0lKcQ7Ac

### Steps/models to reproduce

1、just like in the video, build a testing site
2、set `nerf-spawner-mobs: true` in spigot.yml (Just to keep them from jumping around)
3、wait and see

### Plugin and Datapack List

blank server

### Paper version

This server is running Paper version git-Paper-330 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: de04cbc)
You are running the latest version

Paper-318 (MC: 1.20.2) also has this issue

### Other

Could it be caused by EAR?

**Comment by CodeByCam** [comment]
There definitely is something inconsistent with this. Left is Vanilla (1.20.4), and right is the latest stable version of Paper. For the purpose of consistency I didn't enable `nerf-spawner-mobs`. The Magma Cube's take _a lot_ longer to actually take damage in the Paper world (if at all). 

I've noticed:
- They always take the same amount of time to start shaking from the powdered snow effect.
- The damage doesn't start straight away like it does in Vanilla.
- The damage isn't consistent in Paper, sometimes they take a tick of damage and then the damage stops. In Vanilla once the damage starts ticking, it doesn't stop. 
-  Sometimes the damage just doesn't start at all in Paper.

[Here's a video of the comparison](https://streamable.com/dp8jz3)
![DKJdLhH](https://github.com/PaperMC/Paper/assets/41496198/84b5014f-9cde-4fe1-b25a-ba054bb86870)
