### ISSUE TITLE
Opening the container in adventure mode will fire PlayerInteractEvent twice simultaneously

### ISSUE THREAD

**Issue by KioProject123** [PaperSpigot/Paper#10048]
### Expected behavior

PlayerInteractEvent will only be fired once

### Observed/Actual behavior

PlayerInteractEvent will be fired twice simultaneously

Use the following plugins for testing
```
    @EventHandler(priority = EventPriority.MONITOR)
    public void onPlayerInteract(PlayerInteractEvent e) {
        e.getPlayer().sendMessage(e.getHand() + " " + Bukkit.getCurrentTick());
    }
```

In survival mode
![image](https://github.com/PaperMC/Paper/assets/61594596/38653ef9-201e-439c-8dc0-cb723a52d055)

In adventure mode
![image](https://github.com/PaperMC/Paper/assets/61594596/c3c375d4-e4ba-4451-a882-714bf0aac726)

### Steps/models to reproduce

Right click container in adventure mode

### Plugin and Datapack List

Only plugins for testing

### Paper version

 This server is running Paper version git-Paper-333 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 0b95298)
You are running the latest version

**Comment by Machine-Maker** [comment]
My instinct says this isn't a simple fix. The 2 events are different, they have different actions and they are triggered by 2 different packets, the use item and hand swing packet. I *think* if we remove one of them, some other adventure mode scenario isn't covered, but I can't remember or figure out through testing what that scenario is.

**Comment by Owen1212055** [comment]
See above. In general, there is no way to handle this interaction event nicely. Naturally, Minecraft has changed their interaction packet logic ages ago, so this event has to do a lot of "guestimating" which causes a lot of problems.

And if plugins DO use this behavior, not sure if this is even worth fixing? 
So with this given info, closing as wont fix.
