### ISSUE TITLE
Effects (Blindness and Darness) are not granted and are immediately removed 

### ISSUE THREAD

**Issue by NoahHHN** [PaperSpigot/Paper#10049]
### Expected behavior

Eating a suspicious stew with blindness should give you blindness for 8 seconds. 
Also the affect darkness should be reliable given to a player after a shriker got activated

### Observed/Actual behavior

Solely on papermc, after optaining theese effects they are immediately being removed by the server
You can see them for a short time (~50ms)

This makes advancements like "How did we get here?" impossible

### Steps/models to reproduce

Eat a suspicious stew with the effect blindness

### Plugin and Datapack List

Testing it on a completely fresh server aswell!

**PLugins:** _AntiPopup, InvSeePlusPlus, *SimpleSit, WorldEdit

There are 9 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [file/anti enderman grief v1.1.5 (MC 1.20-1.20.2) (world)], [file/bat membranes v1.0.6 (MC 1.20-1.20.2) (world)], [file/fast leaf decay v2.0.8 (MC 1.20-1.20.2) (world)], [file/name colors v1.0.3 (MC 1.20-1.20.2) (world)], [file/unlock all recipes v2.0.6 (MC 1.20-1.20.2) (world)], [file/more mob heads v2.12.2 (MC 1.20-1.20.2) (world)], [file/player head drops v1.1.5 (MC 1.20-1.20.2) (world)]_

### Paper version

git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
and
git-Paper-234 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: f613437)

**Comment by Machine-Maker** [comment]
Confirmed. ItemMeta strikes again!

**Comment by Machine-Maker** [comment]
If you wait a few minutes @NoahHHN a link will appear at the top of [this PR](https://github.com/PaperMC/Paper/pull/10050) where you can download a paperclip jar to test if the issue is fixed. I did test it and it seems to fix the issue. Please not that its a 1.20.4 version, so don't put the jar in your server if you don't want to update to 1.20.4.

**Comment by NoahHHN** [comment]
im sorry for not seing that one. Should i delete this issue?

**Comment by Machine-Maker** [comment]
Lol, no this issue is great. That linked is a pull request I just opened to fix the issue **after** you opened this issue.

**Comment by NoahHHN** [comment]
you are way to fast man
