### ISSUE TITLE
In crafter, the maximum stack is 1

### ISSUE THREAD

**Issue by PIKO8** [PaperSpigot/Paper#10052]
### Expected behavior

The maximum stack is 64(16 or 1 for some items)

### Observed/Actual behavior

The maximum stack is 1

### Steps/models to reproduce

It's quite difficult... (to explain the way that I used to enable experimental 1.21)
the easiest way (without editing level.dat in the world folder):
- Create a single-player world with experimental feature 1.21
- transfer the world to the server
- put a crafter
- try to put more than 1 item

### Plugin and Datapack List

Plugins: none
Datapacks: update_1_21 (feature)

### Paper version

This server is running Paper version git-Paper-334 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 47b2c18)
You are running the latest version

### Other

Video: https://drive.google.com/file/d/1kvjsZFsz6JVzrX__h8yocPmrng0Kic1E/view

I did not notice such an error on the spigot and bukkit server

**Comment by Black-Hole** [comment]
This is caused by CraftBukkit using a max stack size of 1:
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/nms-patches/net/minecraft/world/level/block/entity/CrafterBlockEntity.patch#22
