### ISSUE TITLE
ability to hit entities outside the worldborder

### ISSUE THREAD

**Issue by Symmettry** [PaperSpigot/Paper#10064]
### Is your feature request related to a problem?

i have a server with a moving border & it includes pvp. players can go outside the border which makes them invincible.
this is also kinda a bug since entities outside the worldborder can also attack players, it's just the players which cannot attack anything

### Describe the solution you'd like.

the ability for players to attack entities outside the worldborder

### Describe alternatives you've considered.

none

**Comment by CodeByCam** [comment]
Hey @Symmettry, thanks for your feature request but this really goes outside the scope of Paper. This would certainly need to be done via your own fork of Paper or a plugin.

**Comment by Symmettry** [comment]
it appears this seems to be more of a minecraft bug. players don't even send attack packets outside the worldborder.

**Comment by CodeByCam** [comment]
> it appears this seems to be more of a minecraft bug. players don't even send attack packets outside the worldborder. likely out of scope of a plugin unfortunately

Yeah, I believe that's just intended behaviour, though. You can still attack them with projectiles ((cross)bow & arrows), even though that's a [confirmed bug](https://bugs.mojang.com/browse/MC-53602). But you're right that you can't left click attack them.
