### ISSUE TITLE
1.20.4 arrow cast class exception

### ISSUE THREAD

**Issue by isInstance** [PaperSpigot/Paper#10079]
### Expected behavior

Launch projectile arrow should work:

Arrow arrow = skeleton.launchProjectile(Arrow.class);

this worked in 1.20.2

### Observed/Actual behavior

It throws this error:

java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_20_R3.entity.CraftArrow cannot be cast to class org.bukkit.entity.Arrow (org.bukkit.craftbukkit.v1_20_R3.entity.CraftArrow and org.bukkit.entity.Arrow are in unnamed module of loader java.net.URLClassLoader @6e2c634b)

which is super weird, also i made sure that I dont have any cb/nms imports, just paper api in maven.

### Steps/models to reproduce

Arrow arrow = skeleton.launchProjectile(Arrow.class);

### Plugin and Datapack List

N/A

### Paper version

This server is running Paper version git-Paper-"49f9f6f" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 49f9f6f)
You are 4 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-"250388d" (MC: 1.20.2)

**Comment by kennytv** [comment]
That's hilarious

**Comment by leoonsz** [comment]
Wasn't this fixed by CB in this commit? (https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/5876cca4429e584455b47e43dc8025e20ead16f3)

**Comment by kennytv** [comment]
Yes

**Comment by kennytv** [comment]
https://github.com/PaperMC/Paper/commit/e035fd70344ba8cd79eddf2d62ddd399fc6cbdf9
