### ISSUE TITLE
Strider is damaged outside lava

### ISSUE THREAD

**Issue by abulleDev** [PaperSpigot/Paper#10078]
### Expected behavior

Strider should not be damaged if they come out of lava

### Observed/Actual behavior

Strider came out of the lava and was damaged

### Steps/models to reproduce

you just need to summon strider in any dimension

### Plugin and Datapack List

nothing

### Paper version

[00:51:21 INFO]: Checking version, please wait...
[00:51:22 INFO]: This server is running Paper version git-Paper-344 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: ff7b9b0)
You are running the latest version

**Comment by StefanH-AT** [comment]
Turns out I was playing on this exact version for over 3 months lol. I was wondering why striders took damage
