### ISSUE TITLE
Inconsistent snowball behavior with vanilla minecraft in version 1.12.2

### ISSUE THREAD

**Issue by MrPixelized** [PaperSpigot/Paper#10074]
### Expected behavior

In vanilla minecraft 1.12.2, snowballs cause the "damage" effect and knockback. Knockback is also caused to entities like fireballs.

### Observed/Actual behavior

Snowballs do not cause knockback when using PaperMC 1.12.2.

### Steps/models to reproduce

Summon any entity and throw a snowball at it in PaperMC 1.12.2.

### Plugin and Datapack List

[13:20:25 INFO]: Plugins (0):

### Paper version

[13:17:47 INFO]: This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[13:17:47 INFO]: Unknown version

### Other

The vanilla minecraft server .jar as well as singleplayer worlds in 1.12.2 have behavior from which PaperMC diverges.

**Comment by MrPixelized** [comment]
Note that this breaks a lot of mechanics from pre-1.13 command block maps.

**Comment by DerEchtePilz** [comment]
I doubt anything will be done about this if this can't be reproduced in the latest version of Paper (either 1.20.4 experimental builds or the latest 1.20.2 build).
1.12.2 is extremely outdated and probably won't receive any updates.

**Comment by Warriorrrr** [comment]
If this is still reproducible on the latest version feel free to open a new issue, but as was already mentioned 1.12 is very old and also unsupported.
