### ISSUE TITLE
Bedrock players via Geyser can open protected doors on PlotSquared plots

### ISSUE THREAD

**Issue by masterhacka** [PaperSpigot/Paper#10073]
### Expected behavior

Click on any part of the door and with no permission nothing should happen. The door should keep closed.

### Observed/Actual behavior

Clicking on top of the doors is really opening them as a Bedrock player.

### Steps/models to reproduce

Clicking doors on others plots at the lower block is working like it should. But clicking the upper block of the door allows Geyser players to open and close any doors. This is not just an optical issues. All players can go physical through the opened door. Is there any way to fix this? Geyser is running on Waterfall. Subservers are running Paper 1.20.2 with PlotSquared 7.3.0.

### Plugin and Datapack List

PlotSquared

### Paper version

git-Paper-318 (MC: 1.20.2)

**Comment by masterhacka** [comment]
[https://github.com/GeyserMC/Geyser/issues/4358](https://github.com/GeyserMC/Geyser/issues/4358)

**Comment by Owen1212055** [comment]
Closing, see: https://github.com/GeyserMC/Geyser/issues/4358#issuecomment-1868390951

Pretty confident this is not a paper issue.
