### ISSUE TITLE
Can I fix some of my blocks breaking at hand-speed while doing it with the right tool, maybe? Or maybe you can?!

### ISSUE THREAD

**Issue by LoyalPineapple** [PaperSpigot/Paper#10077]
### Expected behavior

Hit cobblestone with diamond pickaxe, feel like I'm breaking it pretty fast

### Observed/Actual behavior

Hit cobblestone with diamond pickaxe, feel like I'm hitting it with my hand instead

### Steps/models to reproduce

Join my server, get diamond pickaxe, hit cobblestone, feel slow and weird.

### Plugin and Datapack List

Custom

### Paper version

318 (current latest 1.20.2 stable)

### Other

I'm on paper 318 (current latest 1.20.2 stable), and some of the blocks, when you break them with proper tools, they still break at hand-speed. It's funny cause it works just fine for 1.20.1 clients connecting through Via and back, but not for 1.20.2, 1.20.3 or 1.20.4. If i'm the author of all my other plugins, where should I look first to fix this? (They're pretty big). Btw maybe I can just intercept and set the "UpdateTags" packet using ProtocolLib? Seems to be maybe the culprit, because the client decides how long to break each block, right?

**Comment by Nacioszeczek** [comment]
The pickaxe works just fine for me. Reproduce the issue without plugins otherwise there's nothing for us to fix.

**Comment by hkfvbk** [comment]
Issue with viaversion. Update to latest should fix it
