### ISSUE TITLE
Skript repositories, dependencies error

### ISSUE THREAD

**Issue by Chxxchi** [PaperSpigot/Paper#10084]
### Expected behavior

![image](https://github.com/PaperMC/Paper/assets/152094468/89c3aff8-c0a1-4f5a-97f5-00ee3d633c44)
hey what is this ?????

![image](https://github.com/PaperMC/Paper/assets/152094468/e6a1ad0a-8c39-42c2-afd5-23c83bf29ae6)
![image](https://github.com/PaperMC/Paper/assets/152094468/98301cb4-3a21-4df3-b94e-b3b1f4213dfe)

i want solve this very much

### Observed/Actual behavior

![image](https://github.com/PaperMC/Paper/assets/152094468/89c3aff8-c0a1-4f5a-97f5-00ee3d633c44)

### Steps/models to reproduce

![image](https://github.com/PaperMC/Paper/assets/152094468/89c3aff8-c0a1-4f5a-97f5-00ee3d633c44)

### Plugin and Datapack List

![image](https://github.com/PaperMC/Paper/assets/152094468/89c3aff8-c0a1-4f5a-97f5-00ee3d633c44)

### Paper version

![image](https://github.com/PaperMC/Paper/assets/152094468/89c3aff8-c0a1-4f5a-97f5-00ee3d633c44)

**Comment by Warriorrrr** [comment]
Please fill out the issue template properly as we have no idea what you are doing, using the same screenshot everywhere is not very helpful.
