### ISSUE TITLE
Block breaking via command does not drop XP

### ISSUE THREAD

**Issue by MiraculixxT** [PaperSpigot/Paper#10080]
### Expected behavior

Breaking a block that drops XP on mining with `/setblock x y z air destroy` does drop XP or has the chance to drop XP. Same behavior like mining with a diamond pickaxe.

### Observed/Actual behavior

Breaking a block with named command does not drop any XP

### Steps/models to reproduce

Create a fresh paper server, place or find any block that drops XP on mining and enter the setblock command with destroy property. 

[YouTube Video Comparison](https://youtu.be/qgmaTxs__jE)

### Plugin and Datapack List

No plugins, no datapacks

### Paper version

This server is running Paper version git-Paper-346 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: e035fd7)
You are running the latest version
Previous version: git-Paper-309 (MC: 1.20.2)

**Comment by Owen1212055** [comment]
Prolly related to https://github.com/PaperMC/Paper/issues/8062
