### ISSUE TITLE
oops

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#10093]
### Expected behavior

something broke since 5~ commits ago:
Think this is culprit: https://github.com/PaperMC/Paper/pull/5678/files

### Observed/Actual behavior

Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "originals" is null
 	at org.bukkit.craftbukkit.v1_20_R3.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:67)
 	
 caused by https://github.com/PaperMC/Paper/pull/5678

### Steps/models to reproduce

org.bukkit.craftbukkit.v1_20_R3.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:67)

when calling nms copy

### Plugin and Datapack List

N/A

### Paper version

This server is running Paper version git-Paper-"2951732" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 2951732)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-"dc62150" (MC: 1.20.4)

**Comment by Owen1212055** [comment]
full stack trace?

**Comment by lynxplay** [comment]
Phew, well glad our testing wasn't for nothing.
Glad you were able to figure this out so quickly.
