### ISSUE TITLE
NBT string difference between 1.20.4 and 1.20.2

### ISSUE THREAD

**Issue by LucidAPs** [PaperSpigot/Paper#10102]
### Expected behavior

same string nbt data

### Observed/Actual behavior

items created from 1.20.4 look like this

{"text":"","extra":[{"text":"Soul","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"light_purple","bold":true}]}

items created from 1.20.2 look like this

{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"light_purple","text":"Soul"}],"text":""}

this difference has made a lot of plugins not recognize currency items from before the 1.20.4 update 

### Steps/models to reproduce

create an item and give it a custom name and lore using a 1.20.2 server and then do the same but with 1.20.4

### Plugin and Datapack List

no plugins

### Paper version

using build 361 for 1.20.4 and build 318 for 1.20.2

**Comment by electronicboy** [comment]
The lack of information on how it was given a custom name is exactly why I said that there was nothing to create an issue from here

**Comment by LucidAPs** [comment]
Using the default minecraft:give command, sorry i forgot to write it.

**Comment by electronicboy** [comment]
I fail to understand how that would cause the order to change unless whatever you're putting into the command changed

**Comment by LucidAPs** [comment]
Its true the issue is not with the server, i will figure out where it lies.
