### ISSUE TITLE
Player.teleport across worlds weirdness

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#10106]
### Expected behavior

Player.teleport should send the player immediately to the specified coordinates in the world.

### Observed/Actual behavior

it seems to send the player to the specified coordinates of their current world for a split second (visible chunks load) then to the coordinates in the intended world, this behaviour I expect is not intentional. 

### Steps/models to reproduce

player.teleport(new Location(Bukkit.getWorld("world that isnt current world"), -20000 + random.nextInt(40000), 118, -20000 + random.nextInt(40000)));

the destination in the other world being unloaded and ungenerated thus taking a while to generate exemplifies this behaviour

player will get teleported to the coordinates in their current world for a split second before being sent to the correct world.

### Plugin and Datapack List

N/A

### Paper version

This server is running Paper version git-Paper-"5e978d3" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 5e978d3)
You are 4 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-"2951732" (MC: 1.20.4)

**Comment by Owen1212055** [comment]
I can't seem to reproduce this, teleporting the player I do not see any visible "flash".
```
[14:30:09 INFO]: Location{world=CraftWorld{name=world},x=-10227.0,y=118.0,z=-8749.0,pitch=0.0,yaw=0.0}
[14:30:10 INFO]: Location{world=CraftWorld{name=world_nether},x=-12129.0,y=118.0,z=7047.0,pitch=0.0,yaw=0.0}
[14:30:12 INFO]: Location{world=CraftWorld{name=world},x=-16924.0,y=118.0,z=3809.0,pitch=0.0,yaw=0.0}
```

Switching worlds with teleportation and then printing to console each tick the player's location doesn't show any weirdness either. (In this case, there is no tick where the player's location is off)
