### ISSUE TITLE
`PlayerUntrackEntityEvent` is no longer called if untracked player/entity teleports to another world

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#10107]
### Expected behavior

The event will be called in any case, including if `event.getPlayer()` will untrack `event.getEntity()` (other `Player`), as before in Paper 1.20.1

### Observed/Actual behavior

The event is called only if `event.getEntity()` (other `Player`) was untracked due to movement/teleport far away from `event.getPlayer()` but **they are both in the same world**.

### Steps/models to reproduce

Join the game from two accounts (or ask a friend to help) and place both players in the same location, then teleport one of them to another world.

Test code:
```java
@EventHandler(priority = EventPriority.MONITOR)
public void handleEvent(PlayerUntrackEntityEvent theEvent) {
	Entity vEntity =
		theEvent.getEntity();

	if (vEntity.getType() == EntityType.PLAYER) {
		System.out.println("getPlayer: " + theEvent.getPlayer().getName());
		System.out.println("getEntity: " + vEntity.getName());
		System.out.println();
	}
}
```

### Plugin and Datapack List

Only test plugin w/o data packs

### Paper version

b365 (1.20.4)

### Other

I don't know if this issue occurs only if `event.getEntity().getType()` == `PLAYER` , or with any other type too

**Comment by Machine-Maker** [comment]
I cannot replicate that event being called in 1.20.1. Are you sure the untrack event was called for players moving to another world? I see the remove entity packet being sent, but I don't think the event is being called.

**Comment by molor** [comment]
> Are you sure the untrack event was called for players moving to another world?

Yes. But I may be wrong, in what version it was called — the issue was only noticed yesterday..
I'm used it since ~1.19, and I am sure that it was called in all cases before.
