### ISSUE TITLE
CustomModelData item tag removed when updated in the inventory

### ISSUE THREAD

**Issue by TheMegax** [PaperSpigot/Paper#10111]
### Expected behavior

The CustomModelData tag should be persistent for the item.

### Observed/Actual behavior

The tag is removed upon any update to that item slot.

### Steps/models to reproduce

Give yourself an item with the CustomModelData tag
> Example: `/give @s minecraft:honey_bottle{CustomModelData: 1b}`

Check that there is tag data present using Advanced Tooltips or `/paper dumpitem`
Move the item to another slot in your inventory
The CustomModelData tag is removed from the item.

### Plugin and Datapack List

No plugins.
Datapacks: Vanilla (built-in), file/bukkit (world)

### Paper version

This server is running Paper version git-Paper-365 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 1281f4f)
You are running the latest version

### Other

This issue seems to be related to #7631, but feels different as this is completely removing the tag and not reordering or changing the item tags in non-significant ways.
I've been able to reproduce this issue since at least 1.20.2, but there's a chance it's from even further back.
I haven't had issues with vanilla or unmodded Fabric servers using this feature, with command blocks either enabled or disabled.
Additionally, I haven't seen other tags from the item being removed such as the Display tag.

**Comment by Brokkonaut** [comment]
The source of the issue is that spigot does the check ```if (tag.contains(CraftMetaItem.CUSTOM_MODEL_DATA.NBT, CraftMagicNumbers.NBT.TAG_INT))``` instead of ```if (tag.contains(CraftMetaItem.CUSTOM_MODEL_DATA.NBT, CraftMagicNumbers.NBT.TAG_ANY_NUMBER))``` in org.bukkit.craftbukkit.inventory.CraftMetaItem when reading the custom model data, line 384

**Comment by lynxplay** [comment]
While certainly valid, I am unsure if fixing this is worth it.
You can fix this by literally just using `/give @s minecraft:honey_bottle{CustomModelData: 1}` and would be just fine.
The b suffix, indicating a byte value, would be lost as well in the current item meta system which would the same issue as #7631 and not quickly resolved either.

So even if we fix this, your item stacks would then be changed by the bug #7631 describes.
The way easier solution here is to just not suffix the number with a b.

I'll leave this open for further discussion however 👍

**Comment by Brokkonaut** [comment]
@lynxplay the problem is, that many downloadable maps use the byte tag, and so they will break when played on spigot/paper servers.

**Comment by lynxplay** [comment]
Yea, agreed. After some more discussions we'll fix this as best as possible: "Convert to an int" pretty much.
While not perfect, the bug is then "reduced" to https://github.com/PaperMC/Paper/issues/7631.

**Comment by lynxplay** [comment]
Partial fix was merged in 692db0c81d7637faedd055631b0774461c13d8e6, as stated above this means items spawned in this way will convert to `minecraft:honey_bottle{CustomModelData: 1}` once going through the item meta system.

This is then a duplicate of https://github.com/PaperMC/Paper/issues/7631.
The pushed commit however prevents that data from being lost (now it is just changed) so this issue is considered closed with a "duplicate in 7631" attachment :)
