### ISSUE TITLE
Add `ShulkerDuplicateEvent`

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#10129]
### Is your feature request related to a problem?

Yes! We want to make than one shulker can't summon more than 3 other shulkers when a shulker bullet hits him. But currently there's no way to get the "parent" shulker and, for example, allow or cancel spawning of new shulker based on parent's PDC value.

### Describe the solution you'd like.

Add cancellable `ShulkerDuplicateEvent`, that contain a `getParentShulker` method and, if it's easy to do, `getShulkerBullet`.

### Describe alternatives you've considered.

"Storing information about collisions"? (c) cat in Paper Discord

### Other

Sure you can use other names for the event and methods. I just used the first ones that came to mind.

Thanks!

**Comment by Doc94** [comment]
This cannot be solved using https://jd.papermc.io/paper/1.20/org/bukkit/event/entity/CreatureSpawnEvent.html with the Reason of https://jd.papermc.io/paper/1.20/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html#BREEDING ?

**Comment by molor** [comment]
> there's no way to get the "parent" shulker
