### ISSUE TITLE
If the DeathLootTable of the spawner's entity is invalid it will fps drop

### ISSUE THREAD

**Issue by 0-9** [PaperSpigot/Paper#10128]
### Expected behavior

![2024-01-04_22 44 28](https://github.com/PaperMC/Paper/assets/98388174/8ab09f01-b9d3-405c-a2d6-d2fb605e7b6b)

### Observed/Actual behavior

![2024-01-04_22 44 01](https://github.com/PaperMC/Paper/assets/98388174/a4adb7b4-a4e7-42f7-be7c-4b7976142e8f)

### Steps/models to reproduce

/give @p spawner{BlockEntityTag:{SpawnData:{entity:{id:"minecraft:allay",DeathLootTable:"^"}}}} 1
https://github.com/PaperMC/Paper/assets/98388174/86c812ca-a487-462c-a047-92cff55b5827

### Plugin and Datapack List

datapack: vanilla and file/bukkit (world)
plugins: none

### Paper version

This server is running Paper version git-Paper-373 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: b2a6d57)
You are running the latest version
Previous version: git-Paper-318 (MC: 1.20.2)

**Comment by electronicboy** [comment]
paper has 0 control over the client, so I'm not really sure how this is our issue

**Comment by kennytv** [comment]
You can only get spawners with custom nbt as an operator, at that point you have better ways of lagging or crashing clients, so this is a non-issue

**Comment by MiniDigger** [comment]
you should instead file a bug with mojang
