### ISSUE TITLE
make ResourceKeyInvalidException when placed this shulker box

### ISSUE THREAD

**Issue by 0-9** [PaperSpigot/Paper#10126]
### Stack trace

log: https://pastebin.com/raw/hCTZNtas

### Plugin and Datapack List

Datapack:vanilla,file/bukkit
Plugin:none

### Actions to reproduce (if known)

https://www.youtube.com/watch?v=cNlSxx07x2M
1. get /give @p shulker_box{BlockEntityTag:{LootTable:"^"}} 1
2. place shulker box

### Paper version

This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
You are running the latest version
Previous version: git-Paper-260 (MC: 1.20.2)

**Comment by electronicboy** [comment]
Yes, you created an invalid resource key, this is 100% expected behavior here, not a bug; don't create illegal data.
