### ISSUE TITLE
Mined tile drops despawning in a specific chunk section 

### ISSUE THREAD

**Issue by ShirubaKame** [PaperSpigot/Paper#10144]
### Expected behavior

When a block is mined- including shulker boxes as well as ores and blocks like stone and netherrack, they normally drop and don't despawn until the 5 minute timer runs out. As we have no plugins that affect drops- and have removed all plugins from the server during testing, the default timer should apply to dropped items.

### Observed/Actual behavior

Mined items are not dropping in a specific chunk *section* in our world. 
We don't know if it's happening in other locations. In this area, we've only been able to replicate the problem in this specific location. Unfortunately the location happens to be in the center of a base, which has caused the player to lose items like shulker boxes. We've done repeated testing- laying down rows of shulker boxes and random blocks like netherrack and mining them, and can replicate the problem reliably.

### Steps/models to reproduce

Enter the chunk, lay down mineable items/blocks, and mine them. This is a video of a test performed today, in which you can see netherrack and one shulker are lost:
https://drive.google.com/file/d/1Rpcsfcr6raDj-6sbNNf57NTigC9OwCnk/view?usp=sharing

I apologize for the jerky video. OBS doesn't play well with my computer. 

### Plugin and Datapack List

We have removed all plugins and datapacks during testing to better trace the issue. Apex hosting support has gone through the files as well, created a test world, and confirmed the issue. It was their suggestion that I join the discord, where members suggested opening this ticket. 
This is the output from the console:

07.01 19:30:19 [Server] INFO Server Plugins (0):
07.01 19:30:19 [Multicraft] ShirubaKame ran command: plugins
07.01 19:30:31 [Multicraft] ShirubaKame ran command: datapack list
07.01 19:30:31 [Server] INFO There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]
07.01 19:30:31 [Server] INFO There are no more data packs available

### Paper version

07.01 19:22:45 [Multicraft] ShirubaKame ran command: version
07.01 19:22:45 [Server] INFO Checking version, please wait...
07.01 19:22:46 [Server] INFO This server is running Paper version git-Paper-381 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 07b956e)
07.01 19:22:46 [Server] INFO You are running the latest version
07.01 19:22:46 [Server] INFO Previous version: git-Paper-373 (MC: 1.20.4)

### Other

The world seed is 1181250211274962761. It is in 1.20.4.
This world was created directly after the 1.18 update that changed terrain generation so dramatically. We've updated regularly since then with every full release. 

The current file was created as a new world from the existing seed and the files containing player data were extracted from the original and imported to replace bases and other player data.

The problem of vanishing mined items does not occur when the world is run in a full vanilla setting, without a server jar. 

One of the Support staff messages included this information (Michael is my husband's name):

"Hello Michael!

Before proceeding, I joined your server once again to test this as I'm really curious on what could possibly be doing this.
I did some tests, and found out that items actually despawn on certain "sections" of chunks.

Chunks are divided in 16×16×16 areas called sections, and I noticed the items are not despawning over a certain height. Here is a screenshot showing this:
https://gyazo.com/f01af297215d6d3bf13edb8309158f81

The items below the blue line (which is a different section) all despawned, but over the blue line, they never despawn asides from minecraft's natural 5 minute despawn timer."

He went on to say that this could be caused by section data not being properly saved. 

I'm not sure what other info would be helpful but I'll be glad to provide anything needed, including a copy of the world file if that would help. 

The precise coordinates are recorded in the testing video I've included. I put the F3 screen up at the end to provide any info that might be useful.

I can be reached at [redacted to avoid web scrapers] if there are any questions or further info needed. 

Thanks!
Mary Johnston

**Comment by Owen1212055** [comment]
Resolved after further looking through the world, not a paper issue.
