### ISSUE TITLE
Per-World Datapacks 2

### ISSUE THREAD

**Issue by Etanarvazac** [PaperSpigot/Paper#10147]
### Is your feature request related to a problem?

This was originally mentioned by **Prototype464** in issue #7347. It's been **_2 years_** since their inquiry into this. As they have stated, it would be great to make some datapacks per-world. For example, applies something like Terralith to a resource-only world. I will note the end goal here is well-put by **Prototype464** in their issue.

### Describe the solution you'd like.

The ability to use datapacks per-world on a server. For example, Terralith limited to a resource-only world.

### Describe alternatives you've considered.

Like **Prototype464**, I have been unsuccessful in finding a plugin for this.

**Comment by Machine-Maker** [comment]
This is slightly more feasible with the introduction of the configuration stage. That essentially means the player leaves the server and re-joins, but to the client it is just a loading screen.

No such API exists for putting a client back in that configuration phase as of yet and it can't be added very easily without reworking a lot of the changes craftbukkit has made over the years to how players are created. It's possible, but not tomorrow and probably not the next day.
