### ISSUE TITLE
"Decorated Pot" add proper events for it

### ISSUE THREAD

**Issue by CatTeaA** [PaperSpigot/Paper#10140]
### Is your feature request related to a problem?

[WorldGuard]'Decorated Pot' does not have the intended protection
Cannot prevent projectiles from destroying Decorated Pots
https://github.com/EngineHub/WorldGuard/issues/2054

### Describe the solution you'd like.

 it will need support from the server itself. likely worldguard will immediately protect it once spigot/paper/etc add proper events for

### Describe alternatives you've considered.

↑↑👆↑↑

### Other

https://github.com/EngineHub/WorldGuard/issues/2054
I'm now stopping others from breaking by modifying "projectilesCanBreakBlocks".

**Comment by Malfrador** [comment]
Hitting a decorated pot (or any of the other blocks mentioned) will call a ProjectileHitEvent. This allows you to get both the hit block and the projectile, and the projectile will provide the shooter. 

Is there anything that is missing that could be provided by having a specific event for breaking blocks with a projectile? It seems to me that the current ProjectileHitEvent would provide all the information a protection plugin needs, but maybe I am missing something.

**Comment by lynxplay** [comment]
Maybe EntityChangeBlockEvent I guess ?
Given the arrow changes the block. I presume WG would pick that up ?

**Comment by chasertw123** [comment]
Chorus Flower Block which has the same behavior does call EntityChangeBlockEvent. Though this looks like something that would be done upstream.

**Comment by BangXi** [comment]
Decorated Pot calls EntityChangeBlockEvent, which feels good.
The behavior of the Decorated Pot and the Chorus Flower is indeed somewhat similar.
But I don't know when the upstream will be able to add it.
Maybe paper can do that.

**Comment by lynxplay** [comment]
Upstream now calls the entity change block event, which should suffice for protection plugins.
The issue will be closed once we updated our upstream reference.

**Comment by BangXi** [comment]
Upstream has added related matters.
[292ec79e09e3b90358560dd9e571452c9da7500f](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/292ec79e09e3b90358560dd9e571452c9da7500f)
