### ISSUE TITLE
Vanilla whitelist uses different endpoint in latest MC version (1.20.4) - breaks support in all legacy versions 

### ISSUE THREAD

**Issue by jstnf** [PaperSpigot/Paper#10141]
### Expected behavior

Using /whitelist add <username> on an offline player adds that user to the whitelist.

### Observed/Actual behavior

Vanilla gives back error "That player does not exist"

### Steps/models to reproduce

Execute /whitelist add <player> in any Paper version besides 1.20.4

### Plugin and Datapack List

```
[18:04:18 INFO]: Server Plugins (0):
```

### Paper version

```
[18:03:41 INFO]: Checking version, please wait...
[18:03:42 INFO]: This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
```

### Other

It seems Mojang's policy is not to fix legacy versions of the game according to this bug post on this same issue: https://bugs.mojang.com/browse/MC-267771

The issue has to do with a change in the URL used in Mojang's authlib for bulk username lookups. 
The server outputs
```
[17:48:06] [main/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
```
for the environment in the latest version of the game. 

Therefore the new Usernames to UUIDs endpoint is `https://api.minecraftservices.com/minecraft/profile/lookup/bulk/byname`.

**Comment by Owen1212055** [comment]
It will be up to mojang to correct these endpoints, we are not really going to back port such fixes.

**Comment by prototype464** [comment]
What the hell? This is kind of a big issue.

**Comment by Georggi** [comment]
Seems like I was able to convince a mod to reopen the issue by pointing out that the issue is in the API (it was not clear from the bug report itself).
Since it affects all versions of Minecraft below 1.20.1, hopefully they will look to bring back that endpoint.

**Comment by lynxplay** [comment]
For anyone lurking, https://bugs.mojang.com/browse/MC-267771 is the opened issue.
But yea, not much we can do here outside of manually updating all older versions to use the new API layout.

**Comment by MiniDigger** [comment]
to be honest, I would rather have the web team focus on modernizing and stabilizing the api instead of maintaining legacy endpoints. if you need a working whitelist on those legacy versions you can just use a plugin.

**Comment by Georggi** [comment]
You could, but it doesn't just affect Paper, the issue is in both vanilla server and modded too. So now everyone needs to develop a plugin or a mod (vanilla can't do anything, except manually editing whitelist.txt). Whitelist is also the only blocker from random people joining.
I could develop something for my modded server, sure, but I am sure there are plenty people who don't even know what the problem is or where to write about it or how to fix it.
Besides, the broken version includes 1.20.1, that's not even close to legacy version.

**Comment by electronicboy** [comment]
apparently this should be fixed now
