### ISSUE TITLE
Death loot of players spread out way too much

### ISSUE THREAD

**Issue by LaserSlime** [PaperSpigot/Paper#10152]
### Expected behavior

https://youtu.be/agOU5IlBhx0

### Observed/Actual behavior

https://youtu.be/96dDjicjnL0

### Steps/models to reproduce

1. Fill your inventory with dirt (/give @p dirt 6400)
2. Go into third person with F5
3. Use /kill 
4. See items being spread out way too far

### Plugin and Datapack List

No plugins.

### Paper version

git-Paper-381 (MC: 1.20.4)

### Other

I'm pretty sure vanilla has a thing where if you die of fall damage after falling for very long it spreads out your items more. It seems like for some reason items are always spread out to the max right now even when you're not dying from fall damage at all.

**Comment by LaserSlime** [comment]
Expected behaviour was tested on spigot. I can test vanilla too if you want.

**Comment by LaserSlime** [comment]
Nevermind I was wrong. This might be a vanilla bug then. Like I said I think it's only supposed to be like this when you fall from very high and die of fall damage. I'm pretty sure that's how it worked in the past. Lots of players on my server complained about this change after I updated from 1.20.2 to 1.20.4.

**Comment by Machine-Maker** [comment]
As far as I can tell, this is a feature, not a bug. I found an issue reporting that items stopped flying farther away here: https://bugs.mojang.com/browse/MC-156766. It was then reported fixed, meaning that items are supposed to fly far away on player death regardless.

The reason you saw the change when you updated, is that we fixed a long-standing bug that craftbukkit/spigot created by **not** making the items spread far out.

Here is it in 1.3.2, spread out far just will a `/kill`. 
![image](https://github.com/PaperMC/Paper/assets/15055071/c70330b7-7b43-4d53-ae88-8cd56f4bccfc)


Do you have a source for why you think it's only supposed to be when you fall from a big height?

**Comment by LaserSlime** [comment]
Yeah I also tested older versions and it's the same there too. I could have sworn that items didn't always spread out as much. I guess both me and my players just misremembered? Seems like a weird coincidence but this wouldnt be the first time things go unnoticed for so long.

**Comment by Machine-Maker** [comment]
> I could have sworn that items didn't always spread out as much.

I mean if you haven't played pure vanilla for a long time, the drops have been clumped together on craftbukkit/spigot/paper for a long time, so you could've thought it was intentional.

Will close as works as intended.

**Comment by LaserSlime** [comment]
Yeah you're right. Just checked an old paper 1.19.4 and on there items dont spread as much. Must have been a spigot bug that was at some point fixed by paper.
