### ISSUE TITLE
`ItemMeta` keeping default NBT values

### ISSUE THREAD

**Issue by tal5** [PaperSpigot/Paper#10159]
### Expected behavior

For `ItemMeta` implmentations such as `BlockStateMeta` to not add default NBT data/have a way to clear that data.

Ideally `BlockStateMeta`/`ArmorStandMeta`/whatever other implementations have this issue could automatically exclude the NBT value if it's the default, but assuming that's impossible to do without breaking backwards-compatibility in some way, making the setters nullable/some `clear` method (maybe even one to automatically check and remove default values?) would also be helpful.

### Observed/Actual behavior

Certain `ItemMeta` implementations (such as `BlockStateMeta`/`ArmorStandMeta`) leave behind NBT data, even if it's the default values.
Which means that if you, for example, add some items into a chest item using `BlockStateMeta` then clear it to make it a "normal" chest again, it still won't stack with other chests.

### Steps/models to reproduce

Simple event handler to reproduce the issue:
```java
    @EventHandler
    public void on(PlayerInteractEvent event) {
        ItemStack chest = event.getItem();
        if (!(chest.getItemMeta() instanceof BlockStateMeta stateMeta)) {
            return;
        }
        Chest state = (Chest) stateMeta.getBlockState();
        switch (event.getAction()) {
            case LEFT_CLICK_AIR -> state.getInventory().addItem(new ItemStack(Material.STONE));
            case RIGHT_CLICK_AIR -> state.getInventory().clear();
        }
        stateMeta.setBlockState(state);
        chest.setItemMeta(stateMeta);
        event.getPlayer().getInventory().setItemInMainHand(chest);
    }
```
Left click with a chest a few times, then right click to clear, and it will still have the default block state left in it's NBT: `{BlockEntityTag:{Items:[],id:"minecraft:chest",x:0,y:0,z:0}}`.

### Plugin and Datapack List

```
> plugins
[19:29:09 INFO]: Server Plugins (2):
[19:29:09 INFO]: Bukkit Plugins:
[19:29:09 INFO]:  - Debuggery, PaperTestPlugin
```
```
> datapack list
[19:29:57 INFO]: There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]
[19:29:57 INFO]: There are no more data packs available
```

### Paper version

```
> version
[19:30:11 INFO]: Checking version, please wait...
[19:30:12 INFO]: This server is running Paper version git-Paper-382 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: a80d31b)
You are running the latest version
Previous version: git-Paper-350 (MC: 1.20.4)
```

### Other

I know the item property API is coming soon which will probably allow directly clearing this, but seeing as the `ItemMeta` API is staying & the item property API is still a little while away, would be nice to have some solution for this.
See also some [related discussion](https://discord.com/channels/289587909051416579/555462289851940864/1190312492396720278) on Discord.

**Comment by Machine-Maker** [comment]
We could add something to BlockStateMeta to clear the block state, which would just remove the `BlockEntityTag` entirely, but we don't control what is inside of that tag. That is just the full serialized BlockEntity. But doing that automatically doesn't seem feasible. Each BlockEntity type has it's own "default" nbt values so we'd have to create some way to know what the defaults were based on the type, and that is a massive pain to maintain.

**Comment by Owen1212055** [comment]
I agree with potentially clearing the block state.

However, I STRONGLY agree with Machine here. The concept of "default values" is flawed. With Item Property API, keeping that legacy behavior was very difficult... It is difficult to maintain yes.

The way ItemMeta does it has proven again and again to be very flawed. 😛

**Comment by tal5** [comment]
Yeah a way to clear these values would be great as well, mentioned the default value thing since `getBlockState` seems to return the default state even when the item doesn't have that NBT at all, so I assume it is available somewhere - but don't know how hacky are the internals there, so if a method to clear would be better that's good as well.
