### ISSUE TITLE
Update chain is triggered when BlockPlaceEvent is cancelled

### ISSUE THREAD

**Issue by Tamikaschu** [PaperSpigot/Paper#10151]
### Expected behavior

The Block Update Chain should not be triggered by other blocks placed when BlockPlaceEvent is cancelled.

### Observed/Actual behavior

The Block Update Chain is triggered by a block placed even though the BlockPlaceEvent is cancelled. This leads to some blocks breaking when set with worldedit or triggering redstone signals (e.g in protected areas with worldguard)

Belows case: The redstone torch can trigger the update chain of minecraft. It is an indirect block update and triggers the redstone comparator.

### Steps/models to reproduce

- build a machine like shown in the gif.
- cancel BlockPlaceEvent (or protect the area with worldguard)
- set a redstone torch
- (watch the blocks updating)
![278898982-d8dd1bf3-e975-443d-a94f-b0c167c0b69e](https://github.com/PaperMC/Paper/assets/98806122/a68e92f5-9694-4228-b2e5-930eecd3216a)

### Plugin and Datapack List

FastAsyncWorldEdit, floodgate, PlotSquared

### Paper version

This server is running Paper version git-Paper-264 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 230682d)
You are 54 version(s) behind
Download the new version at: https://papermc.io/downloads/paper

### Other

It may be worth taking a look into https://github.com/IntellectualSites/PlotSquared/issues/4210

**Comment by lynxplay** [comment]
Accepted, caused by the `onRemove` logic on the RedstoneTorchBlock being called when the original state is updated.

**Comment by ch4ika** [comment]
is there any news about this? will it be fixed?

**Comment by DevinGebauer** [comment]
same problem on my network
