### ISSUE TITLE
Guardian's still have Pathfinding/Self Movement without MobGoals

### ISSUE THREAD

**Issue by DapperManatee64** [PaperSpigot/Paper#10174]
### Expected behavior

When a mob's goals are entirely removed via ``Bukkit.getMobGoals().removeAllGoals(entity)``, they should have no target or pathfinding. The mob should sit idle until acted upon by an external force such as a player.

### Observed/Actual behavior

When a Guardian (or Elder Guardian) is out of water, they jump around. This happens when removeAllGoals is used on the mob. As a point of reference, this also happens when the mob is given slowness as well. The only way to prevent this jumping around from my testing is by using the setAI(false) method..however this prevents knockback on damage and a number of other mob-based gameplay mechanics.

### Steps/models to reproduce

Remove all the mob goals from a given Guardian or Elder Guardian
Spawn a Guardian or Elder Guardian (easiest through cmd or a Spawner Block)
Watch as the mob jumps around out of water, despite having no pathfinding

### Plugin and Datapack List

Only plugin is the one used to activate this mechanic

### Paper version

This server is running Paper version git-Paper-382 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: a80d31b)

**Comment by electronicboy** [comment]
removing the mob goals only removes the mob goals, it does not remove any custom AI logic that entities have hardcoded on them
