### ISSUE TITLE
Add a separate Y-value check for "despawn-ranges"

### ISSUE THREAD

**Issue by CatTeaA** [PaperSpigot/Paper#10177]
### Is your feature request related to a problem?

When the number of players reaches dozens of people, the high simulation distance cannot be afforded. My simulation distance is 5.
And then Monsters outside of simulation distance do not disappear randomly.
Peper has an option for this<Despawn Range (hard)>
Hopefully it would be nice to separate the Y-value checks separately.
For example, monsters can be configured to disappear outside of 128 from the player's Y value.The X and Z values disappear beyond 80.
(It is guaranteed that there is no need to modify the afk spots of the biological farm)
![image](https://github.com/PaperMC/Paper/assets/135555687/b45dc5b5-3d9d-4a0e-8fcf-c19cbe14461b)

This request is a bit like "tracking-range-y".
More granular configuration options will help a lot of people.
Hopefully someone will be able to create a PR for this.

### Describe the solution you'd like.

Add a separate Y-value check for "despawn-ranges"
despawn-ranges-y

### Describe alternatives you've considered.

https://hangar.papermc.io/Kyle/harderdespawn
I'm using this plugin right now.but only when the chunk is unloaded, the mob disappears. It helped me somewhat, but not much(It is even abused by players, and when the player encounters a monster fight, he quits the game and rejoins, and the monsters are all gone).
It would be nice if "despawn-ranges" could be configured with a Y value separately.
"despawn-ranges-y"

### Other

https://github.com/PaperMC/Paper/issues/9476
Thanks to electronicboy suggestion, I closed the previous Feature Request.
The previous Feature Request was a bit weird

**Comment by BangXi** [comment]
donation
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=3130528287251491409 skey=@crypt_9bab60fb_ef18e38fbdd8072df8af94e9339f319b mmweb_appid=wx_webfilehelper](https://github.com/PaperMC/Paper/assets/135555687/c28b2888-c954-416b-87b6-33db6d889e46)
