### ISSUE TITLE
Spigot hopper-amount not working for Composter

### ISSUE THREAD

**Issue by jacklollz2** [PaperSpigot/Paper#10170]
### Expected behavior
Setting hopper-amount to 10 makes the Composter added 10 times, or 20, or 30, etc.
### Observed/Actual behavior
It just adds by 1 like regular players.
### Steps/models to reproduce
Modify spigot.yml config, set hopper-amount to 10.
Place a Hopper above a Composter.
Fill the Hopper with Wheat Seeds.
Observe similar behavior to players, instead of 10x the speed.
### Plugin and Datapack List
None.
### Paper version
Current: git-Purpur-2124 (MC: 1.20.4)*
Previous: git-Purpur-2120 (MC: 1.20.4)
* You are running the latest version
### Other
For the life of me I could not find a way to report this to Spigot.

**Comment by zlataovce** [comment]
this is the Paper issue tracker, reproduce the issue on Paper or report it to Purpur

**Comment by jacklollz2** [comment]
Reproduced it on Paper.

**Comment by lynxplay** [comment]
I am rather sure this is a WAI.
The hopper will attempt to fill 10 items however the composter defines a maximum stack size of 1.
This could I guess be a feature request for a composter max stack size option, but this should certainly not live under the hopper value imo.

**Comment by jacklollz2** [comment]
This is a bug, it subtracted 10 items but only used 1, destroying items.

**Comment by Warriorrrr** [comment]
I'm not able to reproduce the bug you're seeing there, it's only subtracting one item at a time for me with no items being destroyed. As for changing the composters max stack size, that should go into a new feature request issue so that it can be looked at seperately, since this also seems like WAI to me.
