### ISSUE TITLE
BlockDropItemEvent has no items for item frame drop event

### ISSUE THREAD

**Issue by vanquesh** [PaperSpigot/Paper#10187]
### Expected behavior

When a block with an item frame on it is destroyed the item frame will also be destroyed. It is my understanding that this event is supposed to fire when that happens, and it does, but I expect the `event.getItems()` method to return an array containing the item frame that is being dropped.

### Observed/Actual behavior

The event fires twice, but the `event.getItems()` method returns an empty array both times.

### Steps/models to reproduce

- Place an item frame on a block
- Destroy the block
- Watch the item frame convert from an entity to a dropped item
- The event fires for block type AIR but the `getItems()` method returns an empty array

### Plugin and Datapack List

Custom plugin, no datapack

### Paper version

This server is running Paper version git-Paper-393 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: b48d737)

**Comment by Nacioszeczek** [comment]
The event fired for that is `HangingBreakEvent`.

**Comment by vanquesh** [comment]
Thank you @Nacioszeczek my bad
