### ISSUE TITLE
The Flying Ender Pearl will not trigger the ' EntityMoveEvent ' event

### ISSUE THREAD

**Issue by MC-XiaoHei** [PaperSpigot/Paper#10184]
### Expected behavior

Flying Ender Pearl triggers ' EntityMoveEvent ' event

### Observed/Actual behavior

The Flying Ender Pearl will not trigger the ' EntityMoveEvent ' event

### Steps/models to reproduce

Create a simple plugin and listen for ' EntityMoveEvent '
in kotlin, like this :
``` kotlin
@EventHandler
fun onPearlFly(event: EntityMoveEvent) {
    if (event.entity.type != EntityType.ENDER_PEARL) return
    println(event.to)
 }
```
Then enter the game, throw the Ender Pearl, println is not triggered

### Plugin and Datapack List

nothing

### Paper version

This server is running Paper version git-Paper-393 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: b48d737)
You are running the latest version

**Comment by Malfrador** [comment]
The EntityMoveEvent will only be called for Living Entities. This is mentioned in the Javadocs for the event.
The ender pearl is not a living entity, so it won't call the EntityMoveEvent.

**Comment by MC-XiaoHei** [comment]
thanks, but is there any way to monitor the flight of the ender pearl
