### ISSUE TITLE
Some (maybe all) flying entities don't call EntityMoveEvent when flying

### ISSUE THREAD

**Issue by leon0017** [PaperSpigot/Paper#10188]
### Expected behavior

Flying entities calling EntityMoveEvent while flying to a destination.

### Observed/Actual behavior

EntityMoveEvent was not called when a flying entity was going to a destination.

### Steps/models to reproduce

```java
// Make sure to register the listener.
@EventHandler
public void onEntityMove(EntityMoveEvent event) {
    if (event.getEntity().getType() == EntityType.PARROT) {
        Bukkit.broadcastMessage("Parrot moved.");
    }
}
```

In game, spawn a parrot and see the inconsistent result, the event may fire when the parrot moves along the ground, but not when flying.

### Plugin and Datapack List

No additional plugins except for the event listener.

### Paper version

[19:13:00 INFO]: Checking version, please wait...
[19:13:00 INFO]: This server is running Paper version git-Paper-"5e73c55" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 5e73c55)
You are 33 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-381 (MC: 1.20.4)

**Comment by Leguan16** [comment]
Cannot reproduce:


https://github.com/PaperMC/Paper/assets/59799222/4cc3269a-3b22-408e-b87c-166725befc49
