### ISSUE TITLE
Fix Tipped Arrow Lore

### ISSUE THREAD

**Issue by gravysauce481** [PaperSpigot/Paper#10196]
### Is your feature request related to a problem?

Custom tipped arrows have this annoying issue where they show the incorrect potion durations in the lore. The shown duration is the actual duration divided by 8. This is likely because a developer did the math to divide a potion duration by 8 when made into a tipped arrow for the lore, even though the supplied duration for a custom arrow is not actually divided.

### Describe the solution you'd like.

Make tipped arrows show the correct duration for potion effects.

### Describe alternatives you've considered.

Technically you could modify the lore using NBT, but tipped arrows lose their display data when shot so picked up arrows won't stack and be incorrect in duration.

### Other

![image](https://github.com/PaperMC/Paper/assets/88604108/b88d474a-e5e4-4177-bf20-6532af407fd7)
![image](https://github.com/PaperMC/Paper/assets/88604108/08cb1ae7-ddd3-4e0e-a065-320f79d9745f)

**Comment by TonytheMacaroni** [comment]
The client is responsible for rendering the tooltip lines, so it's up to Mojang to fix the issue. There's already an open issue for this our their tracker https://bugs.mojang.com/browse/MC-98310.

**Comment by gravysauce481** [comment]
Mhm I know about that issue, but I didn't realize it was client side. What if the server sent an "incorrect" value which is 8x the actual value? Since the duration displayed by the client has to be calculated from a value from the server.

**Comment by electronicboy** [comment]
then you screw up creative mode

**Comment by gravysauce481** [comment]
Custom potion  tipped arrows have a unique nbt tag though. which could be detected.

**Comment by electronicboy** [comment]
We are not manging the data sent to the client because then we effectively need to mess around to demangle it when the client sends it back to us, it's an entire rabbit hole which is not worth the effort for a visual issue

**Comment by gravysauce481** [comment]
I see, thanks for the response.
