### ISSUE TITLE
InventoryClickEvent is not fired if you hold down click

### ISSUE THREAD

**Issue by justlofe** [PaperSpigot/Paper#10208]
### Expected behavior

I’m writing a plugin for a functional block with an inventory and I’ve encountered a problem that when you hold down the mouse button on a slot, move it to another slot or behind the inventory, the click is simply not registered. This is not a visual bug and it works with any inventory

### Observed/Actual behavior

There is a showcase of problem: (https://youtu.be/SQjU9whcCIo)

### Steps/models to reproduce

1. Take item to cursor
2. Hold down mouse button on slot
3. Move the mouse away from the slot
4. Stop holding mouse button

### Plugin and Datapack List

![image](https://github.com/PaperMC/Paper/assets/97516390/cf07e6cd-37a0-4946-a05f-59f918cd1c5a)
![image](https://github.com/PaperMC/Paper/assets/97516390/b61900e9-a39b-461c-9cf8-78a9d53f7684)

### Paper version

This server is running Paper version git-Paper-405 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 3841722)

**Comment by dawon** [comment]
InventoryDragEvent might help you, but other than that I am afraid, it won't be possible, as those are still inventories, and being used as menus was not the original intention of Mojang....
