### ISSUE TITLE
EntityMoveEvent doesn't fire when riding an entity

### ISSUE THREAD

**Issue by JustDoom** [PaperSpigot/Paper#10209]
### Is your feature request related to a problem?

I was working on a plugin that requires me to listen to when an entity moves and I tested to see if it worked when a player rides it and it didn't fire the EntityMoveEvent for some reason

### Describe the solution you'd like.

I would like it to fire the EntityMoveEvent when riding an entity like a pig

### Describe alternatives you've considered.

It is possible to listen to the PlayerMoveEvent and check if they are riding the entity but it isnt as nice as having it in one method

**Comment by Leguan16** [comment]
Duplicate of #7791

**Comment by Malfrador** [comment]
The EntityMoveEvent fires when an entity that the server controls moves. Its called inside the `aiStep()` method. As soon as you mount an entity, that entity is no longer controlled by the server but instead completely under the control of the client and the server only validates that movement. The entity basically becomes a "player" as far as the server is concerned. 

So while this behaviour might be a bit confusing at first, it is working as expected. I don't think additionally calling an EntityMoveEvent here would make sense, the solution with the PlayerMoveEvent seems simple enough.

**Comment by JustDoom** [comment]
Yeah that makes sense
