### ISSUE TITLE
Reference `InventoryDragEvent` in `InventoryClickEvent` javadoc

### ISSUE THREAD

**Issue by imDaniX** [PaperSpigot/Paper#10211]
### Is your feature request related to a problem?

There's no info in `InventoryClickEvent` javadoc about `InventoryDragEvent` being called instead when player clicks and drags their cursor. Many developers with no experience with inventory API just don't know this behavior and there's no info about it in the documentation.

### Describe the solution you'd like.

Reference `InventoryDragEvent` in `InventoryClickEvent` javadoc mentioning the behavior. The `@see` tag would also be appreciated.

### Describe alternatives you've considered.

I'm just mentioning the event myself when there are any related issues.

**Comment by Machine-Maker** [comment]
Yeah, this is probably a good thing to do. Especially since craftbukkit breaks the drag behavior making the drag event fire if you move your mouse even one pixel between mousedown and mouseup.
