### ISSUE TITLE
Spark Crash On MacOS

### ISSUE THREAD

**Issue by cubevlmu** [PaperSpigot/Paper#10210]
### Stack trace

It is too long that github not allowed me to submit. so i upload the crash log file.
[Uploading hs_err_pid8459.log…]()

### Plugin and Datapack List

None datapacks either plugins. Original Paper Server.

### Actions to reproduce (if known)

I just download the lastest paper server (1.20.4) jar to my mac. I try to run it on my computer's java environment. After loading Spark (known from the server log), the app just crash and output the jvm crash log.
It seems to some native library crash the whole jvm.

### Paper version

the jar version is 1.20.4, the information i cpoied from your website
'''
paper-1.20.4-405.jar Recommended
7282462abd16751586ae389cc448fae25f6135e67f3f76781cdd451feab1b8ec
'''
i can't /version because the server even not start success.

**Comment by hehe1005566889** [comment]
sorry that just something wrong made by myself.
i apologize for this.
