### ISSUE TITLE
Texture loading Mod crashes Server 

### ISSUE THREAD

**Issue by ikuria** [PaperSpigot/Paper#10219]
### Expected behavior

Ignoring it?

### Observed/Actual behavior

Paper is crashing if Mojang has an active fail2ban on the server because of dossing attacks
It needs one player with a Chatmod and active Playerheads in it, textures can't loaded and the server is dead

### Steps/models to reproduce

Don't know

### Plugin and Datapack List

https://www.curseforge.com/minecraft/mc-mods/chat-heads

I think

### Paper version

Latest

### Other

Sorry no Log, because I get dossed for a full week now and I have other problems

**Comment by mbax** [comment]
If you're afraid of sharing the entire log, can you just provide the crash report file?

**Comment by ocelotpotpie** [comment]
User declined to provide more information when asked on Discord. Closing issue for now. Will re-open if we have more information to diagnose/troubleshoot the problem.
