### ISSUE TITLE
Server JAR detection in plugins folder

### ISSUE THREAD

**Issue by kashike** [PaperSpigot/Paper#10223]
We should properly detect server JARs that have been put in the `plugins` folder and ignore loading + warn that they are there.

**Comment by jstN0body** [comment]
What would be a good way to do this? My first thought was to look at the JAR manifest, but I don't know if that's the best strategy.

**Comment by jpenilla** [comment]
The vanilla server jar & paper bundler/paperclip both have a `version.json` file at the root of the jar. NeoForge & Fabric installers won't have those but not sure if that's in scope of the issue anyways.

**Comment by jstN0body** [comment]
That makes sense, but any thoughts on bukkit or spigot server jars?

**Comment by molor** [comment]
Why not just load only `jar`s that contain `(paper-)plugin.yml` file?

**Comment by jstN0body** [comment]
Paper already does that by default. However, there is no system to detect server jars in specific

**Comment by jstN0body** [comment]
![image](https://github.com/PaperMC/Paper/assets/49841276/df86d051-afb4-4f6d-9527-5d768bb6f00e)
Output when first starting the server.
![image](https://github.com/PaperMC/Paper/assets/49841276/f0fb0b1b-afe6-41d9-9190-f7c76b78ba56)
Output when reloading the server. (notice that worldedit reloads with no issue)

**Comment by Warriorrrr** [comment]
Merged in #10228
