### ISSUE TITLE
Add options to disable display entities ticking

### ISSUE THREAD

**Issue by galacticwarrior9** [PaperSpigot/Paper#10221]
### Is your feature request related to a problem?

Display entities tick, but this is unnecessary unless you need them as passengers.

### Describe the solution you'd like.

Separate options to disable ticking all four display entities (Display, TextDisplay, BlockDisplay and ItemDisplay) - and, if possible, interaction entities as well. 

### Describe alternatives you've considered.

I don't believe there are any. 

### Other

Someone proposed this on the Paper Discord last March, but I don't believe they followed through with making an issue.

![Image](https://i.gyazo.com/e2cb99098beb557a10d24d94af1b0584.png)
![Image 2](https://i.gyazo.com/8ecdc2deee53fdb86f0d49a46f7f41b2.png)

**Comment by kennytv** [comment]
I can't really think of a scenario where you would have enough display entities for this to become relevant where you also don't require their passenger/vehicle ticking functionality

**Comment by galacticwarrior9** [comment]
Custom crops, furniture, etc are our current use-cases. We are not using the display entities as passengers, nor do they have passengers.

**Comment by MiniDigger** [comment]
do you happen to have a profiler report?

**Comment by Brokkonaut** [comment]
In contrast to armor stands, which can be affected by collisions, gravity or flowing water, display entities do practically nothing in their tick method. Therefore, it really should not be necessary to prevent them from ticking.

**Comment by Darwin1546** [comment]
I had a 40k display entities in the world and tps drops to 10 just because they exists.  
Disabling ticking is most needed feature

**Comment by masmc05** [comment]
> I had a 40k display entities in the world and tps drops to 10 just because they exist. Disabling ticking is most needed feature

Don't forget that entities have other lags than just ticking, for example they need always to calculate who can see them, and if they need to update their data to players

Even if paper fully disables display entities ticking, 40k will still have a big impact on the server

**Comment by MiniDigger** [comment]
we need a proper profiler report.

**Comment by Malfrador** [comment]
[Spark report with 50k item displays](https://spark.lucko.me/6OB3nieCst)

As already suspected by some, the main issue (nearly 60% of tick time) seems to be the canSee checks and sending the updates to players, not the actual tick logic of the item display itself.
I am not against adding such an option, seems easy enough. But I don't think it will have the positive effects you are hoping for.

**Comment by Malfrador** [comment]
canSee is barely a real issue. The main performance loss comes just from tracking that many entities. 
You can improve that easily with a lower entity tracking range (spigot.yml). 50k entities at once also heavily slow the client down.
I really wouldn't blame the game there though - it's just way way more than it was ever designed for.
