### ISSUE TITLE
Unusual Death Behaviour (/gamerule doImmediateRespawn true)

### ISSUE THREAD

**Issue by vindognz** [PaperSpigot/Paper#10224]
### Expected behavior

When you die in vanilla, with immediate respawn enabled, you die, and instantly (or semi-instantly) respawn.

### Observed/Actual behavior

In my experience, you kinda fall through the floor for a few seconds prior to respawning.

### Steps/models to reproduce

Literally just enable immediate respawn, and die, i used fall damage, but /kill works as well.

### Plugin and Datapack List

ViaBackwards, ViaVersion, WorldEdit

There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]
There are no more data packs available

### Paper version

[14:15:15 INFO]: This server is running Paper version git-Paper-409 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 9e171ef)
You are running the latest version
Previous version: git-Paper-382 (MC: 1.20.4)

### Other

I was playing on 1.20.1 on the server so it might just be a viaversion thing.

**Comment by Warriorrrr** [comment]
Can't really reproduce this, likely just a case of chunks needing to load for a second for your server. If you were playing on 1.20.1 you should also put that as the version and not the latest one, as there are differences that would affect what you're describing between these versions.
