### ISSUE TITLE
paper-1.20.4-408 Unable to display server GUI information under windows

### ISSUE THREAD

**Issue by FR-N** [PaperSpigot/Paper#10220]
### Expected behavior

![Snipaste_2024-02-04_19-30-39](https://github.com/PaperMC/Paper/assets/92735765/0b16355b-2663-4600-9fca-85c65a77910d)
paper-1.20.4-407

### Observed/Actual behavior

![Snipaste_2024-02-04_19-27-34](https://github.com/PaperMC/Paper/assets/92735765/e6fe5d6e-9913-4fe1-b96a-1b3c24257436)
paper-1.20.4-408

### Steps/models to reproduce

Use the latest build and then enable the GUI interface

### Plugin and Datapack List

It shouldn't be necessary. The server does not have any plugins installed. This will happen if only the latest version is used.

### Paper version

[19:23:17 INFO]: Checking version, please wait...
[19:23:19 INFO]: This server is running Paper version git-Paper-408 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: c5d168c)
You are running the latest version

### Other

[2024-02-04-1.log](https://github.com/PaperMC/Paper/files/14156569/2024-02-04-1.log)
Here's the log.

**Comment by Leguan16** [comment]
can not reproduce.
![image](https://github.com/PaperMC/Paper/assets/59799222/e1e728f2-2891-48e0-b18a-d0914846506e)

**Comment by ZhangGuang3** [comment]
This is the server package I used for testing
https://1drv.ms/u/s!Aijj86QxAei8zgqLoNG_gmxoCBDB?e=B2cnc6

**Comment by ZhangGuang3** [comment]
![image](https://github.com/PaperMC/Paper/assets/92735765/8590af7f-8d7c-450b-9687-abed7714a215)
![image](https://github.com/PaperMC/Paper/assets/92735765/a2dfe397-f90a-4b49-904e-a1a703f7d8d9)
![image](https://github.com/PaperMC/Paper/assets/92735765/c3a5b1ce-cba2-485a-aad8-913ee12e6f7a)
This problem doesn't seem to happen necessarily, I also tested both versions back and forth several times before I had the problem
What a strange mistake
Here are the logs
[logs.zip](https://github.com/PaperMC/Paper/files/14157020/logs.zip)

**Comment by CodeByCam** [comment]
I've not been able to reproduce this myself either (see below) after trying multiple times on both versions. I'll close this for now but please reopen it if you can provide more information or steps to reproduce the issue!
Build 407:
![zdejl2n](https://github.com/PaperMC/Paper/assets/41496198/7a4fe99b-dc97-48ef-b6d3-6cef164cdc72)

Build 408:
![USMmViL](https://github.com/PaperMC/Paper/assets/41496198/ec273677-d83d-40a0-b0cc-19faa3756a0e)
