### ISSUE TITLE
force boolean param for player.spawnParticle

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#10232]
### Is your feature request related to a problem?

I want to send non forced particles to a player, world.spawnparticle has a force param but not the player.spawnparticle method.

### Describe the solution you'd like.

overload for force boolean parameter on player.spawnparticle

### Describe alternatives you've considered.

currently using NMS to send packet manually with force param false

**Comment by ch4ika** [comment]
Use Paper's ParticleBuilder.
