### ISSUE TITLE
books content is cut off

### ISSUE THREAD

**Issue by seema84** [PaperSpigot/Paper#10240]
### Expected behavior

Normally, the contents of books should not be cut off when switching from 1.20.1 to 1.20.4. I don't know with which version (1.20.2-1.20.4) this happens exactly. 

### Observed/Actual behavior

During the version change from 1.20.1 to 1.20.4, nbt data (presumably above a certain length) is truncated in books.

I have recreated it in Vanilla and it only happens in paper.
In Vanilla I optimised the worlds in the game and in paper with --forceUpgrade

As a result, I now have many books that are incorrect and incomplete.

### Steps/models to reproduce

1. create a book with a lot of nbt data on one page (using a book generator or manually)
2. update the version from 1.20.1 (Build-196) to 1.20.4 (Build-408)
3. compare the NBT data and the content of the book

### Paper version

Paper-408 (MC: 1.20.4)

### Other

I'm not sure whether it's really due to the length and from what length (that's a guess).
However, he now has many books that have lost data.
If necessary I could also upload nbt data.

**Comment by molor** [comment]
Some book limits probably will be changed in the next upstream update, https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/3c1b77871394b331b09a598d8d59fe8c0b771380

**Comment by BangXi** [comment]
https://github.com/PaperMC/Paper/commit/31699ae9a8f3a57491e9c9276cffa5a51e9a5f60

**Comment by Warriorrrr** [comment]
Could you try replicating this on build 423+? The issue should be fixed now
