### ISSUE TITLE
Possibility of ambiguous method calls inside `Damageable`

### ISSUE THREAD

**Issue by Thorinwasher** [PaperSpigot/Paper#10247]
### Expected behavior

In the entity argument for the method Damageable#damage(double, Entity), per documentation the entity parameter is nullable, I should therefore be able to pass null to that parameter.

### Observed/Actual behavior

The methodcall `Damageable#damage(double, null)` throws a compilation error, as the methods Damageable#damage(double, Entity) and Damageable#damage(double, DamageSource) are ambiguous.

### Steps/models to reproduce

N/A // API issue

### Plugin and Datapack List

N/A // API issue

### Paper version

commit 31699ae9a8f3a57491e9c9276cffa5a51e9a5f60

**Comment by kennytv** [comment]
Just use https://jd.papermc.io/paper/1.20/org/bukkit/entity/Damageable.html#damage(double) instead or pass `(Entity) null`
