### ISSUE TITLE
Implement Carpet's Accurate Block Placement Protocol for Spigot/Paper servers

### ISSUE THREAD

**Issue by Tom1817** [PaperSpigot/Paper#10270]
### Is your feature request related to a problem?

Currently it is not possible to use easyPlace tweak from Litematica fully on a paper server. The easyPlace tweak currently only allows placement of blocks that do not have a rotation i.e. cobblestone. Blocks that can be placed in multiple orientations e.g. fences/stairs/logs will not place correctly/at all.

### Describe the solution you'd like.

On my previous SMP, the below plugin was developed inhouse for 1.19.x which completely fixed the issue and re-enabled the full functionality of FlexibleBlockPlacement from Tweakeroo and easyPlace from Litematica.

https://github.com/DungeonDev/SpigotAccurateBlockPlacement

It would be amazing to have this plugin/it's functionality added in to Paper releases going forward. Many big SMPs use paper and easyPlace not working is a major downside to this. I don't know anything about plugin/mod development myself but someone I spoke to said that the plugin seems quite simple so shouldn't be too hard to replicate?

### Describe alternatives you've considered.

The only alternative to make easyPlace work on a server is to instead use a Fabric server with the Carpet mod. Masa has responded to questions about the incompatibility on Reddit and his explanation is as follows:

`So basically if your server doesn't have CarpetExtra with accurateBlockPlacement rule enabled, then the only Generic -> easyPlaceProtocolVersionsettings you can use are None or Slabs Only, otherwise you will just be placing ghost blocks for any blocks that have a rotation property or some other properties that are supported in the "accurate placement protocol".`

[Source (reddit)](https://www.reddit.com/r/litematica/comments/1025gtf/im_playing_on_a_server_and_the_easy_place_is_not/)

I also raised a support thread in his discord on this issue and the conclusion was, basically, someone needs to write a plugin to fix the issue in order for easyPlace to work on a paper server.

[Source (Discord)](https://discord.com/channels/169369095538606080/1183123719753834516)

**Comment by Owen1212055** [comment]
Would rather just have people use a plugin, tbh

**Comment by electronicboy** [comment]
There is generally very little inclination for us to build in support for mod specific features into the server, we'd need to commit to maintaining the support of something with a protocol that we generally have nothing to do with with no real connection to to see if stuff changes or keep on top of it, etc

**Comment by Tom1817** [comment]
Okay I understand that. Unfortunately that means someone will need to write and maintain a plugin and then people will have to seek it out once they encounter and diagnose the issue themselves.

Is there any way that the stance on this will change in the present/future or do I need to accept that it won't be added to paper?

**Comment by electronicboy** [comment]
it's not really a stance as much of a tragic reality that it's not entirely viable for us to support some protocol hack implemented by a random mod we have 0 control over, they could entirely rework their protocol next week and we'd all of a sudden start blowing up with 0 sane means to diagnose what is going on

**Comment by Tom1817** [comment]
Ah ok I see, that makes sense. In that case This issue/whatever this is can be closed, as far as I'm concerned (im not familiar with github sorry!)

Also I want to say thank you to you and the rest of the paper dev team for your work on paper over the years <3
