### ISSUE TITLE
Server Minecraft Error

### ISSUE THREAD

**Issue by golybenokk** [PaperSpigot/Paper#10271]
### Expected behavior

I'm creating my own Minecraft server. Everything was fine, there were no lags, etc. But my friend (helps me create a server) started having problems. If he puts anything into his inventory from a creative, he gets kicked with the error "packet processing error". (We have the same groups, we both have an op)

### Observed/Actual behavior

I'm creating my own Minecraft server. Everything was fine, there were no lags, etc. But my friend (helps me create a server) started having problems. If he puts anything into his inventory from a creative, he gets kicked with the error "packet processing error". (We have the same groups, we both have an op)

### Steps/models to reproduce

I'm creating my own Minecraft server. Everything was fine, there were no lags, etc. But my friend (helps me create a server) started having problems. If he puts anything into his inventory from a creative, he gets kicked with the error "packet processing error". (We have the same groups, we both have an op)

### Plugin and Datapack List

AuthMe, BetterRTP, ChatEx*, CoreProtect, DeluxeCombat, DeluxeMenus, DonatCase*, Essentials, EssentialsSpawn, HolographicDisplays, LuckPerms, MineResetLite, Multiverse-Core, MyCommand, NametagEdit, nkSalary*, PlaceholderAPI, PlayerPoints, ProtocolLib, Scoreboard-revision*, ShopGUIPlus, SkinsRestorer, TAB, Vault, ViaVersion, WorldEdit, WorldGuard, zAuctionHouseV3

### Paper version

[23:02:41 INFO]: Checking version, please wait...
[23:02:41 INFO]: This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Other

I'm creating my own Minecraft server. Everything was fine, there were no lags, etc. But my friend (helps me create a server) started having problems. If he puts anything into his inventory from a creative, he gets kicked with the error "packet processing error". (We have the same groups, we both have an op)

**Comment by electronicboy** [comment]
you might be able to enable debug in server.properties for more information, however, this is generally not the place for support, and that version of paper is no longer supported

**Comment by golybenokk** [comment]
да иди нахуй, ты какого хуя тему мою закрыл, мне помощь нужна
