### ISSUE TITLE
Expand Hopper BlockState API

### ISSUE THREAD

**Issue by Fusezion** [PaperSpigot/Paper#10274]
### Is your feature request related to a problem?

Hoppers have an nbt tag TransferCooldown which is the amount of ticks left between item transfers.
There's a spigot config setting to change the default behavior but no provided method to change it within the bukkit api.

### Describe the solution you'd like.

Expand the existing Hopper blockstate class to include a `Hopper#setTransferCooldown(int)` and `Hopper#getTransferCooldown()`

### Describe alternatives you've considered.

I've only been able to achieve this currently by changing the nbt tag manually, which is not a very efficient method in larger scales

**Comment by lynxplay** [comment]
Resolved by 99a641690abd3d3669249ce10243e0739a13af33
