### ISSUE TITLE
spigot.yml-"wither-spawn-sound-radius:"  Doesn't work

### ISSUE THREAD

**Issue by CatTeaA** [PaperSpigot/Paper#10272]
### Expected behavior

wither-spawn-sound-radius: 256
Only players within 256 blocks can hear the sound

### Observed/Actual behavior

wither-spawn-sound-radius: 256
I was 300 blocks away, but I still heard a voice

### Steps/models to reproduce

spigot.yml-wither-spawn-sound-radius: 256
Then test it

### Plugin and Datapack List

null

### Paper version

This server is running Paper version git-Paper-430 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 4939f87)
You are running the latest version

### Other

When I used spigot to test "wither-spawn-sound-radius:", it works
When I tested "wither-spawn-sound-radius:" with paper, it didn't work as expected

end-portal-sound-radius:
dragon-death-sound-radius:
Not tested......

**Comment by electronicboy** [comment]
The logic looks fine, I'd imagine that you've got `globalSoundEvents` gamerule (noting that these are per world) set to true

**Comment by BangXi** [comment]
> 逻辑看起来不错，我想你已经将游戏规则（注意这些是每个世界的）设置为 true`globalSoundEvents`

I don't seem to have changed these, and the rules remain default

**Comment by electronicboy** [comment]
which is true by default, and will override spigots config; This seems to work as intended

**Comment by BangXi** [comment]
> The logic looks fine, I'd imagine that you've got `globalSoundEvents` gamerule (noting that these are per world) set to true

I don't seem to have changed these, and the rules remain default

**Comment by BangXi** [comment]
> which is true by default, and will override spigots config; This seems to work as intended

I'm now using the directive /gamerule globalSoundEvents false
"wither-spawn-sound-radius:" works as expected

**Comment by BangXi** [comment]
the setting where the rules of the game take precedence over the spigot.yml-"wither-spawn-sound-radius"
Is paper the logic that was modified as intended?
![图片](https://github.com/PaperMC/Paper/assets/135555687/eaf1a11c-3eb9-4719-a5fa-2e35a99e7160)

**Comment by electronicboy** [comment]
Yes, paper modified the logic so that the gamerule would work as expected in order to align with vanilla

**Comment by BangXi** [comment]
> Yes, paper modified the logic so that the gamerule would work as expected in order to align with vanilla

Ok thanks
