### ISSUE TITLE
Entity#isTicking not acting as it should

### ISSUE THREAD

**Issue by ShaneBeee** [PaperSpigot/Paper#10299]
### Expected behavior

Entity#isTicking should return whether or not an Entity is ticking

### Observed/Actual behavior

It appears to return whether or not the chunk the entity is in is ticking.

### Steps/models to reproduce

I don't have proper steps to show this, because I've been testing via Skript and an addon for Skript I have created (written in Java using this API)

I want to show some visuals:
Ok, in this one the villager is standing in the Yellow Chunk.
Green = Chunk.LoadLevel#ENTITY_TICKING = All game logic is processed.
Yellow = Chunk.LoadLevel#TICKING = All game logic except entities is processed.
Red = Chunk.LoadLevel#BORDER = Most game logic is not processed, including entities and redstone.

The entity is not ticking, yet Entity#isTicking is returning true
(this can be seen in the scoreboard, where I'm using (ticking/total) for each type of entity.
You can see here there are 20 ticking villagers out of 20 total villagers, when in fact they're not actually ticking)
<img width="966" alt="Screenshot 2024-03-04 at 6 37 55 PM" src="https://github.com/PaperMC/Paper/assets/20008482/94754b5c-0a6d-4a75-a1fb-46e0dbf4e235">

If I move back a chunk, the villagers are in the RED zone, which they're definitely not ticking.
(This part is working as expected)
<img width="966" alt="Screenshot 2024-03-04 at 6 40 38 PM" src="https://github.com/PaperMC/Paper/assets/20008482/00f9a96b-c423-45f1-b4f6-d8241355a031">

### Plugin and Datapack List

[18:41:47 INFO]: Server Plugins (9):
[18:41:47 INFO]: Bukkit Plugins:
[18:41:47 INFO]:  - BeeConomy, PermissionsEx, RandomTeleport, SkBee, SkBriggy, Skript, skript-reflect, spark, Vault
> 

### Paper version

This server is running Paper version git-Paper-446 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 6ad63fb)

### Other

I noticed while peeking in Paper code, in the NMS Entity Class:
```java
public boolean isTicking() {
    return ((net.minecraft.server.level.ServerChunkCache) level.getChunkSource()).isPositionTicking(this);
}
```
It appears this method is checking if the chunk is ticking, not specifically the entity

I think a better option would be to check if the chunk load level at said entity is actually ENTITY_TICKING instead of TICKING (where entities are in fact not ticked)

**Comment by Sayankroy** [comment]
!assign

**Comment by F-hiller** [comment]
If I can still contribute to this issue, I'd love to solve the problem!
I was thinking of adding ‘ServerChunkCache#isPositionEntityTicking’ and using it in ‘Entity#isTicking’. Can I try this?

**Comment by jpenilla** [comment]
> If I can still contribute to this issue, I'd love to solve the problem! I was thinking of adding ‘ServerChunkCache#isPositionEntityTicking’ and using it in ‘Entity#isTicking’. Can I try this?

Sure! But it looks like the Paper EntityCommand also needs to be updated, and the changes here span multiple patches (MC-Utils, Moonrise, Paper command, Entity#isTicking). So this might not be the best change for a first-time contributor unless you're already very familiar with the patching process. Let me know if you still want to have a try, otherwise I can handle this.

**Comment by F-hiller** [comment]
@jpenilla Thank you for your reply. 
Due to my lack of understanding of the project, I didn't understand why we need an extension like ‘EntityCommand’, could you please explain it in a simple way? I thought I just needed to write the code like this so I could use 'NewChunkHolder#isEntityTickingReady'.
```java
public boolean isTicking() {
    // ServerChunk#isPositionEntityTicking uses NewChunkHolder#isEntityTickingReady
    return ((net.minecraft.server.level.ServerChunkCache) level.getChunkSource()).isPositionEntityTicking(this); 
}
```

**Comment by electronicboy** [comment]
`EntityCommand` is a class inside of paper, he's saying that if we patch this here, then that class, and potentially various others, should also be updated with that change
