### ISSUE TITLE
ALTERNATE_CURRENT incorrect event cancellation

### ISSUE THREAD

**Issue by Teslicek** [PaperSpigot/Paper#10292]
### Expected behavior

When placing `REDSTONE` next to a `SHORT_GRASS` (or any other flower) that is above a block that is not `GRASS_BLOCK` (such as `DIAMOND_BLOCK`) in a region, in which you do not have the permission to place blocks, you would expect the `SHORT_GRASS` to not be broken, as the plugin is cancelling the place event.

### Observed/Actual behavior

The `SHORT_GRASS` is broken even when the event has been cancelled by the plugin.

### Steps/models to reproduce

1. Download WorldGuard and WorldEdit
2. Set the `redstone-implementation` in paper config to `ALTERNATE_CURRENT`
3. Create any region
4. Inside the region, using WorldEdit, set `SHORT_GRASS` (or any other flower) above a block, such as `DIAMOND_BLOCK`
5. Make sure you do not have the permission to place blocks in the region
6. Place `REDSTONE` next to the `SHORT_GRASS`
7. The `SHORT_GRASS` will be destroyed

### Plugin and Datapack List

```
[11:17:22 INFO]: Server Plugins (2):
[11:17:22 INFO]: Bukkit Plugins:
[11:17:22 INFO]:  - WorldEdit, WorldGuard
```

### Paper version

```
[11:16:50 INFO]: This server is running Paper version git-Paper-436 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 850b736)
You are running the latest version
```

### Other

This bug only happens, when you use `redstone-implementation: ALTERNATE_CURRENT`, but when you use `VANILLA` as the value, it works normally.

I already contacted the developers of WorldGuard, but was told to report this bug to paper.

**Comment by Lulu13022002** [comment]
Affect the BlockPlaceEvent
