### ISSUE TITLE
PlayerTeleportEvent is not fired when entering an END_PORTAL

### ISSUE THREAD

**Issue by Nononitas** [PaperSpigot/Paper#10294]
### Expected behavior

The PlayerTeleportEvent should be fired if you enter an end portal as you get teleported

### Observed/Actual behavior

No event is getting fired

### Steps/models to reproduce

1. Make a plugin listening to the PlayerTeleportEvent
2. Kill the Enderdragon
3. Go to the portal 
4. Notice that event isn't getting fired

### Plugin and Datapack List

LuckPerms, Multiverse-Core, ProtocolLib, Vault, ViaBackwards, ViaVersion

### Paper version

git-Paper-436 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 850b736)

**Comment by electronicboy** [comment]
The event is not fired because the player is not teleported, as such, they're removed from the world and placed into a weird limbo state before they effectively respawn

**Comment by Nononitas** [comment]
So howdo I listen to when someones enter this portal and getting moved to limbo?

**Comment by electronicboy** [comment]
EntityInsideBlockEvent or EntityPortalEnterEvent

**Comment by Nononitas** [comment]
Thank you :D
