### ISSUE TITLE
Chunk getBlock method incorrect input checking for y coordinate

### ISSUE THREAD

**Issue by PureCadeMC** [PaperSpigot/Paper#10315]
### Expected behavior

The docs state that Chunk.getBlock(int x, int y, int z) requires a specific range of values for the inputs. For the Y coordinate, this is (world minHeight (inclusive) - world maxHeight (exclusive)).

Expected valid input should be from -64 (inclusive) to 320 (exclusive)

### Observed/Actual behavior

Calling Chunk.getBlock(int x, int y, int z) on a y value from -64 to -1 throws an IllegalArgumentException that 'y' is out of range. The error indicates "expected (0-256)".

I have not tested values 256-320.

### Steps/models to reproduce

Call Chunk.getBlock(int x, int y, int z) with a y value in the range -61 to -1.

### Plugin and Datapack List

N/A

### Paper version

1.20.4-450

**Comment by lynxplay** [comment]
Presumably a duplicate of https://github.com/PaperMC/Paper/issues/10104.

Make sure this is called in the overworld.
I'll keep the issue open, so please respond once you checked if this is a duplicate.

**Comment by PureCadeMC** [comment]
yes this is called in the overworld. And yes this looks like a duplicate. Closing now, I will follow that other issue for updates.

**Comment by Machine-Maker** [comment]
Well hold on, that issue was closed because it was "user error" in that they were calling methods for a world they *thought* was the overworld but was the nether which has different default min/max y values. So if that isn't the case for you, then this issue still applies
