### ISSUE TITLE
Server crash 

### ISSUE THREAD

**Issue by AlliSite** [PaperSpigot/Paper#10317]
### Stack trace

root@111150899~# java -version

openjdk version "1.8.0_312"

OpenJDK Runtime Environment (Temurin)(build 1.8.0_312-b07)

OpenJDK 64-Bit Server VM (Temurin)(build 25.312-b07, mixed mode)

root@111150899~# java -Xms128M -Xmx1536M -Dfml.queryResult=confirm -Dlog4j2.formatMsgNoLookups=true -Dterminal.jline=false -Dterminal.ansi=true -DIReallyKnowWhatIAmDoingISwear=true -Djdk.module.illegalAccess=deny -Duser.timezone=Europe/Moscow -jar -XX:+UseNUMA -XX:G1ReservePercent=10 -XX:G1HeapWastePercent=10 -XX:+OptimizeStringConcat -XX:+TieredCompilation -XX:+EliminateLocks -XX:+UseSuperWord -XX:+OptimizeFill -XX:LoopUnrollMin=4 -XX:LoopMaxUnroll=16 -XX:+UseLoopPredicate -XX:+RangeCheckElimination -Dfile.encoding=UTF-8 -XX:+DisableExplicitGC -XX:+UseFastJNIAccessors -XX:+UseParallelGC -jar server.jar nogui

Downloading original jar...

Error downloading original jar

java.io.FileNotFoundException: https://s3.amazonaws.com/Minecraft.Download/versions/1.12.2/minecraft_server.1.12.2.jar

at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1893)

at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1495)

at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)

at java.net.URL.openStream(URL.java:1093)

at com.destroystokyo.paperclip.Paperclip.run(Paperclip.java:83)

at com.destroystokyo.paperclip.Main.main(Main.java:14)

[Free-5 Daemon]: ---------- Detected server process in a crashed state! ----------

### Plugin and Datapack List

empty

### Actions to reproduce (if known)

- Server run

### Paper version

PaperSpigot 1.12.2

### Other

?

**Comment by electronicboy** [comment]
1.12.2 is unsupported, and this was already fixed in the latest 1.12.2 jar
