### ISSUE TITLE
[API] InventoryView missing setter for Components

### ISSUE THREAD

**Issue by ericlmao** [PaperSpigot/Paper#10329]
### Is your feature request related to a problem?

In `InventoryView`, there's no Component setter for the inventory title, and it still uses the (I assume) legacy method of `setTitle(String)` rather than `title(Component)`.

### Describe the solution you'd like.

Preferably something like this!

```java
for (HumanEntity viewer : inventory.getViewers()) {
    InventoryView view = viewer.getOpenInventory();

    TextComponent title = Component.text("My Inventory Title");
    view.title(title);
}
```

### Describe alternatives you've considered.

There isn't exactly any alternatives to my knowledge unless I'm missing something

**Comment by Lulu13022002** [comment]
Duplicate of https://github.com/PaperMC/Paper/issues/9189
