### ISSUE TITLE
For offline players : ScullMeta.setOwningPlayer() or ScullMeta.setOwnerProfile() doesn't work and PlayerTextures URL, of PlayerProfile, is reset

### ISSUE THREAD

**Issue by Pexep** [PaperSpigot/Paper#10322]
### Expected behavior

1. When we use ScullMeta.setOwningPlayer() or ScullMeta.setOwnerProfile() for offline players it should be display the player head's texture above the "PLAYER_HEAD" item.
2. The PlayerTextures url, in an offline player PlayerProfile, shouldn't be null.
3. When we set the PlayerTextures url, in an offline player PlayerProfile, it shouldn't be null few times after.

### Observed/Actual behavior

1. When we use ScullMeta.setOwningPlayer() or ScullMeta.setOwnerProfile() for offline players the texture displayed above the "PLAYER_HEAD" item is not the good one (I think that it's a default one).
2. The PlayerTextures url, in an offline player PlayerProfile, is null.
3. When we set the PlayerTextures url, in an offline player PlayerProfile, few times after the URL is null.

This means that offline players' head, displayed in some plugins' menus, are wrong.

### Steps/models to reproduce

Nothing special.

### Plugin and Datapack List

We don't want to exhibit the plugin list. If you really need it, we can give you in private.

### Paper version

Paper(307) 1.20.2-R07SNAPSHOT+

**Comment by electronicboy** [comment]
Unsupported version, and 99% of these things are generally down to input errors, we'd need reproduction code

**Comment by RSLuke** [comment]
It actually doesn't work as well on latest released paper #450
