### ISSUE TITLE
(Detailed) For offline players, ScullMeta.setOwningPlayer() or ScullMeta.setOwnerProfile() doesn't work

### ISSUE THREAD

**Issue by Pexep** [PaperSpigot/Paper#10325]
### Expected behavior

Set skull meta (using  setOwningPlayer or setOwnerProfile), with offline player or offline player's profile, should display the player head.

### Observed/Actual behavior

Set skull meta (using  setOwningPlayer or setOwnerProfile), with offline player or offline player's profile, doesn't display the good player head.

### Steps/models to reproduce

Here are two methode to reproduce the bug, use them to get ItemStack to place in menu : 
```java
public ItemStack getPlayerHead(UUID playerId){
	OfflinePlayer offlinePlayer = Bukkit.getOfflinePlayer(playerId);
	ItemStack item = new ItemStack(Material.PLAYER_HEAD);
	SkullMeta meta = (SkullMeta) item.getItemMeta();
	PlayerProfile ownerProfile = (PlayerProfile) offlinePlayer.getPlayerProfile();
	meta.setOwnerProfile(ownerProfile);
	item.setItemMeta(meta);

	return item;
}

public ItemStack getPlayerHead2(UUID playerId){
	OfflinePlayer offlinePlayer = Bukkit.getOfflinePlayer(playerId);
	ItemStack item = new ItemStack(Material.PLAYER_HEAD);
	SkullMeta meta = (SkullMeta) item.getItemMeta();
	
	meta.setOwningPlayer(offlinePlayer);
	item.setItemMeta(meta);

	return item;
}
```

### Plugin and Datapack List

We don't want to exhibit the plugin list. If you really need it, we can give you in private.

### Paper version

Paper(450) 1.20.4-R0.1SNAPSHOT+

### Other

We made [this issue before](https://github.com/PaperMC/Paper/issues/10322), but here, it's a more detailed and specific issue, with the last build and a reproduction code

**Comment by lynxplay** [comment]
I mean, you did not complete the profile.
The server does not store the skin urls in the player data. You'd need to request these from the API.

Am I missing something here? Why would this work?

**Comment by electronicboy** [comment]
The profile *will* be resolved when it's applied to the actual itemstack from my recollection, but, this has silently failed for years due to spigot making that operation occur async, the operation basically ends up failing to update the copied itemstack inside of the players inventory

**Comment by lynxplay** [comment]
The application logic is absolutely scuffed yea.
The proper way to run this is to pass the PlayerTexture through.
![image](https://github.com/PaperMC/Paper/assets/32834385/19c4774e-5c61-45f5-94e2-689e821baef3)

**Comment by Pexep** [comment]
Ok, I see. Thanks for your answers !
