### ISSUE TITLE
(Detailed) For offline players, the PlayerTextures URL, of PlayerProfile, is null and is reseting

### ISSUE THREAD

**Issue by Pexep** [PaperSpigot/Paper#10324]
### Expected behavior

1. The PlayerTextures url, in an offline player PlayerProfile, shouldn't be null.
2. When we set the PlayerTextures url, in an offline player PlayerProfile, it shouldn't be null few times after.

### Observed/Actual behavior

1. The PlayerTextures url, in an offline player PlayerProfile, is null.
2. When we set the PlayerTextures url, in an offline player PlayerProfile, few minutes after the URL is null.

### Steps/models to reproduce

Here is a method you can use to notice the bug :
```java
public void playerTexturesTest(){
	// Get players
	OfflinePlayer[] players = Bukkit.getOfflinePlayers();
	String playerList = "";
	for (OfflinePlayer player : players) {
		// For every players : Print texture url, update profile, update profile texture url, print texture
		new BukkitRunnable(){
			@Override
			public void run(){
				// Print current profile texture url
				String urlString = "null";
				if (player.getPlayerProfile().getTextures().getSkin() != null)
					urlString = player.getPlayerProfile().getTextures().getSkin().toString();
				Bukkit.getLogger().info("[PlayerTexturesTest] (" + player.getName() + ") Texture URL before update : " +  urlString);
					
				// Get an updated profile
				PlayerProfile updatedProfile = player.getPlayerProfile();
				try {
					updatedProfile = (PlayerProfile)player.getPlayerProfile().update().get();
				} catch (Exception e) {
					Bukkit.getLogger().warning("There was an error updating player profile for player with UUID " + player.getUniqueId() + ", see below for details.");
					e.printStackTrace();
				}

				// Update profile texture url (set texture at the updated profile one)
				OfflinePlayer newPlayerInstance = Bukkit.getOfflinePlayer(player.getUniqueId());
				newPlayerInstance.getPlayerProfile().setTextures(updatedProfile.getTextures());

				// Print updated profile texture url
				urlString = "null";
				if (newPlayerInstance.getPlayerProfile().getTextures().getSkin() != null)
					urlString = newPlayerInstance.getPlayerProfile().getTextures().getSkin().toString();
				Bukkit.getLogger().info("[PlayerTexturesTest] (" + newPlayerInstance.getName() + ") Texture URL after update : " + urlString);	
			}
		}.runTaskLaterAsynchronously(this, 200);
	}

	// Print null texture url every 5 seconds
	new BukkitRunnable(){
		@Override
		public void run(){
			// Print initial message
			Bukkit.getLogger().info("[PlayerTexturesTest] Make a point !");

			// Get players
			OfflinePlayer[] players = Bukkit.getOfflinePlayers();

			// For every players, print message if texture url is null
			for (OfflinePlayer player : players) {
				// If has no name or if is "CMI-Fake-Operator", no consideration
				if (player.getName() == null || player.getName().equals("CMI-Fake-Operator")) continue;

				// If has a skin, no consideration
				if (player.getPlayerProfile().getTextures().getSkin() != null)
					continue;

				// Print that the player hasn't skin
				Bukkit.getLogger().info("[PlayerTexturesTest] (" + player.getName() + ") Texture URL after few times : null");
			}
		}
	}.runTaskTimer(this, 300, 100);
}
```

### Plugin and Datapack List

We don't want to exhibit the plugin list. If you really need it, we can give you in private.

### Paper version

Paper(450) 1.20.4-R0.1SNAPSHOT+

### Other

We made [this issue before](https://github.com/PaperMC/Paper/issues/10322), but here, it's a more detailed and specific issue, with the last build and a reproduction code

Test result : 
If you see only `[PlayerTexturesTest] Make a point !` in console, it means that none url texture is null, otherwise, it displays players wich the url texture is null. Like that :
![Capture d'écran 2024-03-14 143740](https://github.com/PaperMC/Paper/assets/104359902/6b1acdc6-104a-4776-adb6-741432e534e7)

**Comment by lynxplay** [comment]
This is 100% expected.
Editing around in the offline player texture is not a persistent operation.
You are merely modifying the in-memory offline player instance.

Offline player instances are cached in a weak ref map. In your case, the garbage collector at some time just, well, garbage collects those instances, in which case your temporary modification of their player profile is also garbage collected away.
When you then call getOfflinePlayers again, the instances are re-created.

**Comment by electronicboy** [comment]
Nothing stops you from caching that data yourself if you need it. This is 100% a WAI

**Comment by Pexep** [comment]
Yeah, I think that we'll do that, thanks !
