### ISSUE TITLE
Completely break the Paper-only string duping machine？

### ISSUE THREAD

**Issue by CatTeaA** [PaperSpigot/Paper#10332]
### Is your feature request related to a problem?

At present, paper breaks the vanilla String duping behavior
But it wasn't completely fixed, and even now extends to paper's proprietary String duping machine

There is currently a PR
https://github.com/PaperMC/Paper/pull/9436

String duping can be fixed entirely, but I'd say if the option is set to false，Is it possible to revert String duping to vanilla behavior?
After all, there is already a paper-specific version of the String duping machine，I don't think it makes sense, it's better to be like vanilla, or completely fixed

### Describe the solution you'd like.

Merge this PR https://github.com/PaperMC/Paper/pull/9436
But when this option is set to false, String duping wants to be consistent with vanilla behavior.(In view of the fact that there is already a dedicated String duping machine for paper)

### Describe alternatives you've considered.

null

**Comment by BangXi** [comment]
My server is often asked by players if string can be copied?
I don't know how to answer
Because paper destroys the string duping of vanilla
But what if I say that the server prohibits String duping
In fact, there is also a String duping machine for paper
It's embarrassing

**Comment by electronicboy** [comment]
Paper fixes duplication issues where it is viable to do so, the linked fix however has a behavioral change which needed some more attention. This is a vanilla issue, however, there is an easier means to do the same thing, so why go to the lengths of making such a contraption vs what is needed in vanilla.

**Comment by BangXi** [comment]
> Paper fixes duplication issues where it is viable to do so, the linked fix however has a behavioral change which needed some more attention. This is a vanilla issue, however, there is an easier means to do the same thing, so why go to the lengths of making such a contraption vs what is needed in vanilla.

Major video sites, such as YouTube, are always happy to teach people how to build and use these facilities
So when a certain machine doesn't work, they ask questions.
The handling of String duping is a bit awkward at the moment
There are no corresponding configuration options, and there is no complete fix

Both TNT and sand duping have corresponding configuration options, which I also set to false，I can rightfully say no to the players
I'm just hoping that String duping can be fixed completely
Of course, the option switch can restore it to vanilla behavior, which seems to be the right choice as well，There are already a lot of similar options
