### ISSUE TITLE
Connection failed. Please try again or contact an administrator

### ISSUE THREAD

**Issue by connor33341** [PaperSpigot/Paper#10340]
### Expected behavior

Successful connection to server

### Observed/Actual behavior

Connection failed. Please try again or contact an administrator

### Steps/models to reproduce

https://github.com/PaperMC/Paper/assets/107011324/0309e72a-0479-4ad3-81bf-591f0bd73e81

### Plugin and Datapack List

Plugins:
 TCPShield, ViaBackwards, ViaVersion
Datapacks:
 There are 8 data pack(s) enabled: [vanilla (built-in)], [file/coordinates hud v1.2.2.zip (world)], [file/real time clock v1.1.2.zip (world)], 
 [file/unlock all recipes v2.0.3.zip (world)], [file/spawn v2.3.2.zip (world)], [file/homes v1.5.3.zip (world)], 
 [file/VanillaTweaks_c409864.zip (world)], [file/bukkit (world)]

### Paper version

[16:24:10 INFO]: This server is running Paper version git-Paper-454 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 99a6416)

### Other

I would simply want to know that causes this error and how to correct this.

**Comment by electronicboy** [comment]
This is generally not the place for support (nor do we support offline mode), and plugins like TCPShield will generally prevent direct connections as an aspect of their function

**Comment by connor33341** [comment]
You know, that would probably be the problem. I can’t believe that I overlooked that. But thanks for your time.
