### ISSUE TITLE
Ability to stop logging player IP addresses is not working

### ISSUE THREAD

**Issue by hervidero** [PaperSpigot/Paper#10343]
### Expected behavior

According to the documentation:
https://docs.papermc.io/paper/reference/global-configuration#logging_log_player_ip_addresses
This option to false would stop logging of player IP addresses to console and logs.

### Observed/Actual behavior

According to the documentation:
https://docs.papermc.io/paper/reference/global-configuration#logging_log_player_ip_addresses
This option to false would stop logging of player IP addresses to console and logs, but is stopped working after 1.20.x

### Steps/models to reproduce

Installed a fresh PaperMC instance with latest build, started, accepted EULA.
When trying to change the option:
```
logging:
  log-player-ip-addresses: true
```
This option is no longer available in the global config, adding it and set to false does not turn the function to stop logging off. It is just ignored.

### Plugin and Datapack List

none, just Velocity as a proxy

### Paper version

Checking version, please wait...
This server is running Paper version git-Paper-455 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 55ffcb1)
You are running the latest version

### Other

Behaviour changed between 1.19.4 and 1.20.2

**Comment by lynxplay** [comment]
The documentation is outdated. This config option is present in the vanilla game under the `log-ips` property in the `server.properties` file. Upgrading from old versions  would have migrated said value to the server.properties.

I'll close this issue on this repo and open a PR to remove it from the docs :+1:

**Comment by hervidero** [comment]
Ah, So I can now stop the logging from server.properties. Maybe add a note to the docs for users running older paper versions only ;)
I also run a few SMP's with an older paper version, and there it still works as exp[ected. Hence the bug report.
