### ISSUE TITLE
BlockFadeEvent triggered by player trampling farmland

### ISSUE THREAD

**Issue by NonSwag** [PaperSpigot/Paper#10373]
### Expected behavior

Only the respective PlayerInteractEvent should be called

### Observed/Actual behavior

When a player tramples farmland, the BlockFadeEvent is called.

### Steps/models to reproduce

Cancel the BlockFadeEvent and trample farmland

### Plugin and Datapack List

Paper Plugins:  CityBuild, Commander, Protect, Tweaks, VanillaBans, VanillaMSG
Bukkit Plugins: FastAsyncWorldEdit

There are 5 data pack(s) enabled: [trade_rebalance (feature)], [bundle (feature)], [vanilla (built-in)], [file/bukkit (world)], [file/tectonic.zip (world)]

### Paper version

This server is running Paper version git-Paper-463 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 45d1486)
You are running the latest version

**Comment by electronicboy** [comment]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/dc7d31b00d121c486660fafc9d6b4eb38e9db76d#nms-patches%2FBlockSoil.patch

This event call has existed for 6 years now, while not the best event for the operation, I'm not sure removing it is a good idea, especially as it covers missing usecases. Maybe a more accurate event could be substituted, but, this will likely not change
