### ISSUE TITLE
InventoryClickEvent firing twice with InventoryAction always equal to PLACE_ALL in CREATIVE

### ISSUE THREAD

**Issue by Xharos** [PaperSpigot/Paper#10377]
### Expected behavior

I expect to see the event firing only once with the proper InventoryAction in creative.
It works fine in survival/adventure/spectator.

### Observed/Actual behavior

The event is firing twice, that leads to an ItemStack duplication.
The event's action is always PLACE_ALL, even when i try other action (SWAP, DROP, HOTBAR etc..)

### Steps/models to reproduce

I'm not sure if it's the right place to report code problem for paper seeing the template.
In any case, here is the code to reproduce this issue :
```java
public class TestClickBug extends JavaPlugin {

    @Override
    public void onEnable() {
        Bukkit.getPluginManager().registerEvents(new Listener() {
            @EventHandler
            public void onPlayerJoin(PlayerJoinEvent event) {
                var player = event.getPlayer();
                player.getInventory().clear();
                player.getInventory().setItem(0, new ItemStack(Material.DIRT));
            }

            @EventHandler
            public void onClick(InventoryClickEvent event) {
                if (event.getWhoClicked() instanceof Player player) {
                    if (event.getClickedInventory() instanceof PlayerInventory) {
                        if (Objects.requireNonNull(event.getCurrentItem()).getType() == Material.DIRT) {
                            event.setCancelled(true);
                            player.sendMessage("Click action " + event.getAction() + " on player inventory detected");
                        }
                    }
                }
            }
        }, this);
    }
}
```

### Plugin and Datapack List

None, only the one above.

### Paper version

This server is running Paper version git-Paper-463 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 45d1486)
You are running the latest version
Previous version: git-Paper-462 (MC: 1.20.4)

Server launched through gradle with id("xyz.jpenilla.run-paper") version "2.2.0" plugin

### Other

Result after one click :
![image](https://github.com/PaperMC/Paper/assets/20248902/306b7203-2453-49ef-94e5-9f6f85ada32a)

When using :
```java
player.updateInventory();
```
just below cancelling the event cancel the duplication, but the event still fire twice. I don't think it's the right way to permanently force update the inventory.

Thanks in advance for investigating this issue

**Comment by Xharos** [comment]
I've found something interesting when debuging `event.getClick`.
The event is fired twice only in creative mode.

It works fine in survival, adventure and spectator mode.

**Comment by kennytv** [comment]
As a general note, creative mode is... *special* and doesn't care much for the server state and just throws whatever it has at the server instead. Hence it's also easy for it to start popping items out of nowhere - though that also means this will not happen for non-creative clients.

**Comment by Xharos** [comment]
You are indeed right about that.
https://www.spigotmc.org/threads/inventoryclickevent-called-twice.362292/#post-3329626
It was still the case 4 years ago.

My favorite code helper (chatgpt 😄) suggests to track the last player click time and act accordingly.

If there is no solution, I think this issue can be close.
Thanks

**Comment by Machine-Maker** [comment]
While I cannot replicate the "event firing twice bit", the duplication caused by cancelling the event is works-as-intended. The `InventoryClickEvent` is actually an `InventoryCreativeEvent` which is fired for a specific packet the client sends for any interacting with the **creative mode** inventory while in creative mode. It basically gives the client full control over all the items in all the slots. This packet doesn't contain any information about what kind of click or action it was as the client just sends packets to essentially update the inventory on the server with exactly what it thinks should exist. This is why its always PLACE_ALL because its hardcoded in the constructor for InventoryCreativeEvent.
