### ISSUE TITLE
Configurable Velocity disconnect message

### ISSUE THREAD

**Issue by Vrganj** [PaperSpigot/Paper#10372]
### Is your feature request related to a problem?

Players sometimes connect to an old IP they found in chat and get met with "This server requires you to connect with Velocity."
I'd like to configure the message, as very little players know what that means.

### Describe the solution you'd like.

I suggest a new field in the `messages` section of paper-global.yml that makes this configurable.
The code containing the message is found in `0774-Add-Velocity-IP-Forwarding-Support.patch`

### Describe alternatives you've considered.

I thought of using AsyncPlayerPreLoginEvent, but it seems that the disconnect happens before it's even called.

**Comment by electronicboy** [comment]
It's somewhat intentional that we don't allow replacing messages which are generally only visible due to lower than recommended security setups

**Comment by Vrganj** [comment]
I'm trying to avoid losing old players who had the IP saved before we even setup a proxy. Why would you consider this setup "lower than recommended"?

**Comment by electronicboy** [comment]
Because your backend instances should generally not be exposed to the public internet, velocity makes it safer but it is still a security risk, especially if you're running 3rd party plugins, etc
