### ISSUE TITLE
Server crush like every 4-6 hours

### ISSUE THREAD

**Issue by Govno123333** [PaperSpigot/Paper#10381]
### Stack trace

My server constantly crashes, I've already scoured Google looking for information on what it could be and haven't found anything. Please help, thanks in advance.
[2024-04-02-3.log](https://github.com/PaperMC/Paper/files/14829133/2024-04-02-3.log)

### Plugin and Datapack List

![image](https://github.com/PaperMC/Paper/assets/124210237/e4ae450b-67d2-474c-8cf5-03afcc224b45)

### Paper version

This server is running Paper version git-Paper-463 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 45d1486)
You are running the latest version
Previous version: git-Paper-451 (MC: 1.20.4)

**Comment by CodeByCam** [comment]
Hello Govno, 

This isn't actually a Paper issue, but an issue with one of your plugins. We also don't support offline mode servers (I note `SkinRestorer` being in your plugin list). [Here](https://docs.papermc.io/paper/basic-troubleshooting) are some helpful troubleshooting tips you can have a look through. 

Cheers!

**Comment by exzolink** [comment]
"If you see a world save or edit, then it means you did far more than your server can handle at once"
Increase server memory or remove voracious plugins (use Spark and Memory analyzer tool)
@Govno123333

**Comment by Govno123333** [comment]
> "If you see a world save or edit, then it means you did far more than your server can handle at once" Increase server memory or remove voracious plugins (use Spark and Memory analyzer tool) @Govno123333

the problem is its happening when i stay afk, i do nothing. And i have 12 GB RAM on my server, i think its enough memory.

**Comment by electronicboy** [comment]
The thing stalled due to disk IO, stuff like that is generally down to things messing with the disk externally, i.e. backups, etc; This is generally out of scope for the issue tracker
