### ISSUE TITLE
Eyes of Ender don't point to Strongholds outside the World Border

### ISSUE THREAD

**Issue by masterwyatt** [PaperSpigot/Paper#10391]
### Expected behavior

Eyes of Ender should point to strongholds regardless if they are outside the border because this is how it occurs in the vanilla game.

### Observed/Actual behavior

Eyes of Ender don't point to strongholds if they are outside the border, only if they're inside.

### Steps/models to reproduce

- Change the World Border Size to like 1000 (something out of the stronghold ring)
- Throw an Eye of Ender
- Now try changing the World Border to something within a stronghold like 4000 (You can also try aligning it to where a stronghold is)
- Throw an Eye of Ender and it will now point to it

### Plugin and Datapack List

No plugins affect this as it occurs even without any.

### Paper version

This server is running Paper version git-Paper-466 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: a203544)
You are running the latest version
Previous version: git-Paper-450 (MC: 1.20.4)

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Paper/blob/master/patches/server/0113-Bound-Treasure-Maps-to-World-Border.patch
this was generally an intentional change, in part because of treasure maps loading stupid numbers of chunks which made 0 sense when you couldn't get to them. not really away of the reason *why* you'd still want to target inaccessible parts of the world, however

**Comment by masterwyatt** [comment]
Yeah, that makes sense, I just think it could be a config option to configure whether you'd want that possible or not. At the moment I'm playing a challenge where we can increase the world border getting eventually to the stronghold, and I was just wanting to know how far it was so we knew how much we needed to grind. That's how I originally discovered this.

**Comment by Machine-Maker** [comment]
I think I'm fine with adding a configuration option for this. Or at least limiting this change directly to treasure maps instead of all "searching for structures" which includes other things like eyes of ender.

**Comment by masterwyatt** [comment]
Yea that sounds good!

**Comment by lynxplay** [comment]
Resolved thanks to @notTamion!
Update paper and set https://docs.papermc.io/paper/reference/world-configuration#environment_locate_structures_outside_world_border to true to locate structures outside of the worldborder.
