### ISSUE TITLE
isSprinting() and setSprinting() methods dont work correctly,

### ISSUE THREAD

**Issue by Dueris** [PaperSpigot/Paper#10407]
### Expected behavior

Im able to check if a player is sprinting, and set if they are sprinting.

### Observed/Actual behavior

Both do not work. If I check if the player is sprinting and I am sprinting, it returns false. it seems the client and server are somewhat out of sync when it comes to this, since after using setSprinting(boolean), the isSprinting() method is updated.

### Steps/models to reproduce

Just run either of those methods anywhere, it wont work correctly.

### Plugin and Datapack List

GenesisMC, playit-gg, SkinsRestorer, Terra

### Paper version

git-Paper-478 -- latest avalible on 4/10/2024: 4:35pm PST

**Comment by electronicboy** [comment]
This is likely just going to be the caveats of "player movement happens on the client"

**Comment by Dueris** [comment]
It seems this isn't the case. I tested with both paper and I tested(and I develop) canvas. It doesn't work on either

**Comment by Dueris** [comment]
However the client updates the server, so shouldn't it judge if the player is sprinting?

**Comment by Dueris** [comment]
What abt the PlayerMoveEvent?

**Comment by electronicboy** [comment]
it doesn't judge if a player is sprinting, as far as the server is concerned it just sees movement from the player. The question here is, does the client tell us if the player entered a sprinting state?

**Comment by TonytheMacaroni** [comment]
I've tried both `Player#isSprinting` and `Player#setSprinting`, and both methods seem to work fine. Are you testing this with a vanilla client?

> The question here is, does the client tell us if the player entered a sprinting state?

The client does communicate when it starts/stops sprinting using `ServerboundPlayerCommandPacket`.

**Comment by electronicboy** [comment]
I ended up finding the time to look,
So, the client does tell is when it enters/exits sprinting mode, it does add a modifier but also sets the general entity flag which is what isSprinting checks

<img width="852" alt="image" src="https://github.com/PaperMC/Paper/assets/1228900/f9f0c664-f75a-4a46-b532-aaa6b0ea55d0">

**Comment by Dueris** [comment]
It does seem to be an issue with the client after testing where the shared constant doesnt get updated. Sorry for the trouble
