### ISSUE TITLE
vanillaBiomeProvider calls the method it's in, causing the server to crash.

### ISSUE THREAD

**Issue by xeRicker** [PaperSpigot/Paper#10402]
### Stack trace

https://paste.gg/p/anonymous/86b2e3a03c464c0ca3536a398ca806e3

### Plugin and Datapack List

Here's my class that extends BiomeProvider and is causing the server to crash.
The crash happens in the getBiome(...) method because vanillaBiomeProvider() calls the method it's in.

https://paste.gg/p/anonymous/ddc00f4c8ca14b67993e71a46b98bc6c

### Paper version

```
[15:10:16 INFO]: Checking version, please wait...
[15:10:17 INFO]: This server is running Paper version git-Paper-478 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 5436d44)
You are running the latest version
Previous version: git-Paper-477 (MC: 1.20.4)
```

**Comment by xeRicker** [comment]
Bump. The issue still persists in the latest 1.21 version.

**Comment by jpenilla** [comment]
Please try the build attached to PR #11185
