### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment:

### ISSUE THREAD

**Issue by Raamze** [PaperSpigot/Paper#10401]
### Stack trace

https://paste.gg/p/anonymous/e5e8395390db40de8a7751cb1675426e

### Plugin and Datapack List

![image](https://github.com/PaperMC/Paper/assets/166499244/5ff5534f-d207-4250-86c2-0ecc71b6810a)
Easy Warp
epic Homes
ItemEdit
ItemTag
Openinv
ProtocolLib
Shopkeepers
SimpleTpa
SkinsRestorer
StoneDrop
Vane- admin, bedtime, core, enchantments, portals, trifles
voicechat-bukkit
worldedit- bukkit
worldguard- bukkit

### Paper version

paper-1.20.4-478

### Other

Everything was working perfectly before computer soft reset

**Comment by electronicboy** [comment]
Generally seems that microsoft broke something, running the server from a batch file should mitigate the issue

**Comment by Raamze** [comment]
I launch server by clicking at
![image](https://github.com/PaperMC/Paper/assets/166499244/e0177dee-9d1d-49af-9b6d-ede9c69deb3a)
Is that batch file or should i create start.bat?

**Comment by electronicboy** [comment]
The recommended approach is to create a start.bat in order to start the server with a real console

**Comment by Raamze** [comment]
It works. Thank you so much and have a nice day!
