### ISSUE TITLE
Client side version of PaperMC

### ISSUE THREAD

**Issue by thewanderingtraderm** [PaperSpigot/Paper#10417]
### Is your feature request related to a problem?

There is currently no way to run bukkit plugins client side

### Describe the solution you'd like.

A version of PaperMC that runs client side(like forge)

### Describe alternatives you've considered.

None

**Comment by Leguan16** [comment]
Paper is a server software and will always stay a server software. Making it client compatible would mean a lot of rewriting.

**Comment by notTamion** [comment]
You can always run a server locally. This also allows you to play with whatever client you want instead of needing to use the loader this would be written in.
