### ISSUE TITLE
Fix MC-249324

### ISSUE THREAD

**Issue by Leleawa** [PaperSpigot/Paper#10419]
### Is your feature request related to a problem?

I am running a server in China and I hope that players can enter the game with Chinese names, but they encountered an Internal Exception: java.lang.IllegalStateException: Invalid characters in username in username error when entering

### Describe the solution you'd like.

I hope the paper can create a feature in the configuration file that can switch this restriction on and off

### Describe alternatives you've considered.

Searching for plugins

### Other

![屏幕截图 2024-04-15 102249](https://github.com/PaperMC/Paper/assets/131422030/3c40d3de-1dce-4389-99c8-9c5183fce695)

**Comment by TetraTheta** [comment]
According to [official help page](https://help.minecraft.net/hc/en-us/articles/4408950195341-Minecraft-Java-Edition-Username-VS-Gamertag-FAQ), it is intended behabior.

> * Must have 3-16 characters
> * No Spaces are allowed between characters
> 
> Accepted characters: 
> 
> * A-Z (upper and lower case)
> * 0-9
> * The only special character accepted is _ (underscore)

Because of it, MC-249324 is closed as 'Resolved (Invalid)'.

**Comment by Nacioszeczek** [comment]
Nicknames can only contain a specific set of characters, as described above.

**Comment by Leleawa** [comment]
However, many players on the NetEase China version use Chinese names. This would result in them being unable to enter servers with versions ≥1.18.2.

**Comment by TetraTheta** [comment]
You can use plugins that provide 'nickname' feature for chinese _names_. I don't know how NetEase things work, but if they provide an API for getting chinese name, you can fetch and assign it to players automatically when they join your server.

**Comment by kennytv** [comment]
`perform-username-validation` under unsupported settings
