### ISSUE TITLE
Cannot invoke PlayerConnection

### ISSUE THREAD

**Issue by J0schlZ** [PaperSpigot/Paper#10425]
### Expected behavior

Since a while i'm developing a plugin which acts as Addon for the plugin TrainCarts.
The purpose is to send minecarts/trains and their passengers between servers in a bungeecord-network.
I didn't update it for a while and now i'm dealing with the following problem:

I'm using the `PlayerSpawnLocationEvent` to put the player into a minecart (`Entity.addPassenger(player)`) as soon as he joined the server.

### Observed/Actual behavior

Recently i get this error:

`java.lang.NullPointerException: Cannot invoke "net.minecraft.server.network.PlayerConnection.a(double, double, double, float, float)" because "this.c" is null`

Server-Log: https://pastebin.com/sDp4yxPP

**The player is placed in the minecart without any visible problems.**

### Steps/models to reproduce

Use a bidirectional portal and drive a train through the portal while sitting inside of the train.

### Plugin and Datapack List

Plugins: BKCommonLib, TrainCarts, CTCommons, TCPortals
https://ci.mg-dev.eu/job/BKCommonLib/
https://ci.mg-dev.eu/job/TrainCarts/
https://ci.craft-together-mc.de/view/TrainCarts%20-%20Addons/job/CT%20Commons/
https://ci.craft-together-mc.de/view/TrainCarts%20-%20Addons/job/TC%20Portals/

Involved lines of my code (TCPortals):
https://github.com/CraftTogetherMC/TC-Portals/blob/master/src/main/java/de/crafttogether/tcportals/portals/PortalHandler.java#L639
https://github.com/CraftTogetherMC/TC-Portals/blob/master/src/main/java/de/crafttogether/tcportals/listener/PlayerSpawnListener.java#L18

### Paper version

git-Paper-462 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 00fd87a)

**Comment by Machine-Maker** [comment]
The ServerGamePacketListenerImpl isn't set yet, it hasn't been created when the PlayerSpawnLocationEvent fires. This isn't a bug, you just can't use logic that replies on the `connection` field in `ServerPlayer` being set in that event.
