### ISSUE TITLE
oops

### ISSUE THREAD

**Issue by f1xx00rs** [PaperSpigot/Paper#10421]
### Stack trace

```
https://paste.gg/p/anonymous/8fad62fef9034ffeb1a3b925630335ae
```

### Plugin and Datapack List

projectkorra (addons - jedcore, spirits, projectaddons, spirits - the complete set), chatex, essentialsX, LP, crazycrates, gsit, brewery, tab, placeholderapi, coins

### Paper version

I can't start a server and paste output from /version, but minecraft version is 1.20.1

**Comment by electronicboy** [comment]
1.20.1 is unsupported
downgrading is unsupported
your paper config is invalid because you're using a paper config from a newer version of the software
