### ISSUE TITLE
BlockPistonExtendEvent doesn't fire when nothing is pushed

### ISSUE THREAD

**Issue by B1ue-Bandit** [PaperSpigot/Paper#10428]
### Expected behavior

BlockPistonExtendEvent should fire when a piston is activated.

### Observed/Actual behavior

The event does not fire when the piston pushes no blocks.

### Steps/models to reproduce

Listen for BlockPistonExtendEvent, trigger a piston which is set up to push air & observe nothing even though the piston clearly fires. The event doesn't fire when blocks aren't pushed.

### Plugin and Datapack List

No datapacks & no other plugins.

### Paper version

Paper version git-Paper-485 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 862299b)

### Other

When looking at the paper documentation the described behavior for BlockPistonExtendEvent is "Called when a piston extends" which doesn't seem to be the case if nothing is pushed.

**Comment by electronicboy** [comment]
BlockPistonEvent doesn't even have a handler list, so there is generally no way you're listening to that event
