### ISSUE TITLE
 Inventory.addItem does not add items, but adds to ItemStack in the argument

### ISSUE THREAD

**Issue by snowpegeon** [PaperSpigot/Paper#10433]
### Expected behavior

Items in Inventory are added, and the value of the first argument ItemStack remains unchanged.

### Observed/Actual behavior

The total number of items in Inventory remains the same, and the total number of ItemStacks passed in the argument is added to the total number when first passed.
The sample assumes transport from Chest to Hopper.

### Steps/models to reproduce

  @EventHandler
  public void onItemMove(InventoryMoveItemEvent event) {
   ItemStack item = event.getItem();
  Inventory inv = event.getSource();
  inv.addItem(item);
}

### Plugin and Datapack List

[21:02:13 INFO]: Server Plugins (2):
[21:02:13 INFO]: Bukkit Plugins:
[21:02:13 INFO]:  - Logger, StorageSign

### Paper version

[21:02:30 INFO]: Checking version, please wait...
[21:02:31 INFO]: This server is running Paper version git-Paper-485 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 862299b)
You are running the latest version
Previous version: git-Paper-454 (MC: 1.20.4)

### Other

Logger and StorageSign are both plugins that I am developing.
This text was written using translation software.

**Comment by electronicboy** [comment]
The InventoryMoveitemEvent is generally broken af in terms of behavior, and any fixes are likely going to generally be invasive or behaviorally breaking...

**Comment by electronicboy** [comment]
doubly so, you're trying to add the item that is already inside of the inventory to the inventory, such is generally going to cause undefined behavior, especially with this event being generally broken
