### ISSUE TITLE
Even if you update the information of the hopper's import source Inventory using InventoryMoveItemEvent, it is not reflected in the game.

### ISSUE THREAD

**Issue by snowpegeon** [PaperSpigot/Paper#10434]
### Expected behavior

The number of items set with Inventory.setItem will be reflected in the game for the inventory that can be obtained with InventoryMoveItemEvent.getSource().

### Observed/Actual behavior

Even if the internal variables are treated differently, when you check the game, the changed number is not reflected, and it only performs the normal operation of transporting items one by one to the hopper.

### Steps/models to reproduce

https://github.com/eventhandler
public void onItemMove(InventoryMoveItemEvent event) {
ItemStack item = event.getItem().clone();
Inventory inv = event.getSource();

item.setAmount(item.getAmount() + 1);
inv.setItem(0, item);
}

### Plugin and Datapack List

[21:02:13 INFO]: Server Plugins (2):
[21:02:13 INFO]: Bukkit Plugins:
[21:02:13 INFO]: - Logger, StorageSign

### Paper version

[21:02:30 INFO]: Checking version, please wait...
[21:02:31 INFO]: This server is running Paper version git-Paper-485 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: https://github.com/PaperMC/Paper/commit/862299b6a6588ff60db69dbc40e8514f9690d318)
You are running the latest version
Previous version: git-Paper-454 (MC: 1.20.4)

### Other

Logger and StorageSign are both plugins that I am developing.
This text was written using translation software.

**Comment by electronicboy** [comment]
The server generally does not care to validate the state you've modified inside of the scheduler, if you want to modify stuff, you'll have to do it yourself with the scheduler; Such is a fairly typical caveat for inventory related things, there is no real good solution here which doesn't break existing behavior/expectations for this (fairly broken) event

**Comment by electronicboy** [comment]
Chances are papers optimisations change behavior vs spigot here because there are some expectations, modifying the underlying inventory in the middle before the server performs its state modifications is going to create issues. Modifying the items that the server is trying to move is unsupported behavior here, there is a general expectation that the server is going to wipe your changes, and so you'd generally be better off using the scheduler to run after the event, this is likely not something we're going to throw time on.

**Comment by snowpegeon** [comment]
When I checked with a plugin (EventDebug) that allows you to check event calls, it appears that Hopper is only calling InventoryMoveItemEvent.
Let's talk about actual implementation, but which event can be used to make it possible?
Or is there currently no event implemented in Paper to make such changes?

**Comment by electronicboy** [comment]
There is no different event, modifying data as the server modifies it is unexpected behavior which we cannot support.

Maybe somebody else on the team will decide to invest some time into this, but, as it stands, what you're doing there is generally unsupported under the general "don't modify stuff as the server is doing so"

**Comment by snowpegeon** [comment]
is that so. Thank you for your reply.
I'm looking forward to seeing good results.
