### ISSUE TITLE
MBedwars problem

### ISSUE THREAD

**Issue by spybytf2** [PaperSpigot/Paper#10438]
### Expected behavior

Loaded addon

### Observed/Actual behavior

https://pastebin.com/Jvh8H5r5

### Steps/models to reproduce

Fix it pls

### Plugin and Datapack List

advancedlogin
eco
ecoarmor
essentials
libreforge
litebans
mbedwars
multiverse core
oldcombatmechanbics
spawn
viabackwards
viaversion
worldedit

### Paper version

[09:54:43 INFO]: This server is running Paper version git-Paper-488 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 908b814)
You are running the latest version
Previous version: git-Paper-485 (MC: 1.20.4)

**Comment by Machine-Maker** [comment]
The issue that plugin links to here has been resolved, so I'm not sure what its talking about. Also, your reproduction steps are not valid and the plugin is a premium closed-source plugin which makes replicating it impossible on our end. 

Try updating your plugins.
