### ISSUE TITLE
The lead turns into a ghost item when cancelling PlayerLeashEntityEvent

### ISSUE THREAD

**Issue by SpectreVoid** [PaperSpigot/Paper#10432]
### Expected behavior

That the lead do not turn into a ghost item.

### Observed/Actual behavior

That the item doesn't turn into a ghost item and having to update player inventory after cancelling the event in order for the item to not render as a ghost item.

### Steps/models to reproduce

Simply add this listener and just remove the if() clause. 

```
    @EventHandler
    public void onLeash(PlayerLeashEntityEvent event) {
        Player player = event.getPlayer();
        ItemStack itemStack = player.getInventory().getItemInMainHand();
        if(itemStack.hasItemMeta() && hookHandler.isHook(itemStack)) {
            event.setCancelled(true);
            //player.updateInventory();
        }
    }
```

### Plugin and Datapack List

Codex, MobArmory, Skyline

### Paper version

[00:03:02 INFO]: Checking version, please wait...
[00:03:02 INFO]: This server is running Paper version git-Paper-451 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: ab1afb0)
You are 34 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-485 (MC: 1.20.4)

**Comment by lynxplay** [comment]
Replicable 👍
