### ISSUE TITLE
[1.20.5] Re-add Item Data Lore Tag

### ISSUE THREAD

**Issue by Chris6ix** [PaperSpigot/Paper#10451]
### Is your feature request related to a problem?

Mojang has for whatever reason removed the `(+NBT)` item lore tag in 1.20.5 instead of just renaming it to `(+Data)`.
This makes it impossible to easily tell if, for example, a chest you have in your inventory has stuff in it or not.
Also with this weird change, Mojang created a new parity issue, as Bedrock has the `(+Data)` tag.

### Describe the solution you'd like.

When updating Paper to 1.20.5, instead of following Mojang, just rename `(+NBT)` to `(+Data)` instead of removing it.

### Describe alternatives you've considered.

/

**Comment by Owen1212055** [comment]
Probably better as a plugin, not sure if it’s our realm to readd removed features.

**Comment by Chris6ix** [comment]
But Paper "aims to fix gameplay and mechanics inconsistencies" and this is one?

**Comment by electronicboy** [comment]
This was rendered purely by the client, not the server; There is generally no way to support this which doesn't involve modifying items, which then creates issues with creative mode, etc

**Comment by kennytv** [comment]
![It's still there?](https://i.imgur.com/SkBtO8y.png)

**Comment by NoahvdAa** [comment]
I believe they're talking about this:
<img width="482" alt="image" src="https://github.com/PaperMC/Paper/assets/44026893/29d08b83-1baf-4ea4-8e7f-176444719d3b">

this was client side only, a better place to re-add this would be via a mod

**Comment by molor** [comment]
It's not client-side lol, `ItemStack#getLore().get(0).equals("(+NBT)")` on the server side returns `true` in `1.20.4`

**Comment by electronicboy** [comment]
```
$ grep -R "(+NBT)" *
src/main/java/net/minecraft/client/Minecraft.java:            var5.add(StringTag.valueOf("\"(+NBT)\""))
```

So, the value is purely added by the client as a side-effect from creative mode, it's not sourced from the server, and there is little inclination for us to hack it back in

**Comment by molor** [comment]
Oh, didn't think about that client is requesting the server for an item that already contain this lore. Okay, thanks!
