### ISSUE TITLE
Continious Comparator Update

### ISSUE THREAD

**Issue by PoweredDeveloper** [PaperSpigot/Paper#10458]
### Expected behavior

![2024-04-27_01 45 50](https://github.com/PaperMC/Paper/assets/115712692/46318fc9-6405-4b81-b297-517b0d998f5f)

Expected to see continiously updating comparator. In Vanilla it works just fine.

### Observed/Actual behavior

Comparator do not updating      ` => `      Quasi Connectivity just loosing it's properties

### Steps/models to reproduce

**Dropper:**
![2024-04-27_01 50 08](https://github.com/PaperMC/Paper/assets/115712692/5930291f-5d06-45ce-96b8-97ca5d80392d)

**Hopper:**
![2024-04-27_01 50 12](https://github.com/PaperMC/Paper/assets/115712692/b2314721-18e6-4d11-b752-4d2e0ac9c580)

### Plugin and Datapack List

No plugins, no datapacks

### Paper version

This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)
You are running the latest version
Previous version: git-Paper-454 (MC: 1.20.4)

### Other

Maybe you can add it as option to config

**Comment by Malfrador** [comment]
I am not able to get this to work in vanilla singleplayer 1.20.4. I placed the blocks like in your screenshot and filled the hopper and dropper with the same items. However, nothing happens. The comparator just stays powered all the time. 

Are there any additional steps required to get this to work? Is there anything else I should look for other than the power of the comparator?

**Comment by PoweredDeveloper** [comment]
Thats's not how it works. It should update comparator constantly. Like, when hopper tries to get item from dropper it updates dropper => comparator updates. The vanilla hopper logic marks the source inventory as changed even if no item is moved out of it. That causes comparator updates constantly. It not visible in game. I'll send a video.

**Possible solution:**
Add to the hopper pull method

`container.setChanged();`

**Comment by PoweredDeveloper** [comment]
_I accidentally closed an issue. Sorry_

**Comment by PoweredDeveloper** [comment]
https://www.youtube.com/watch?v=rboZSC-c73Q

**Comment by lynxplay** [comment]
Yea sorry it wasn't very clear what kind of update you meant.

The comparator block update issue is already tracked in #8441, thanks for the quick feedback, I'll close this as a duplicate then.
