### ISSUE TITLE
1.20.5 should be using mojang mappings?

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#10469]
### Expected behavior

1.20.5 should be mojang mappings

### Observed/Actual behavior

its spigot mappings

### Steps/models to reproduce

download latest 1.20.5 dev from website

### Plugin and Datapack List

N/A

### Paper version

N/A

**Comment by electronicboy** [comment]
Not sure what you're looking at but the patched paper jar that the bootstrapper dumps out is 100% mojang mapped

**Comment by electronicboy** [comment]
is this a jar that you actually downloaded or a jar that you compiled yourself?

**Comment by electronicboy** [comment]
Yea, that is not a jar downloaded from our site, you build the jar wrong
