### ISSUE TITLE
1.20.5 ItemFlags can lead to broken items

### ISSUE THREAD

**Issue by aerulion** [PaperSpigot/Paper#10473]
### Expected behavior

In 1.20.4 it was possible to use ` itemMeta.addItemFlags(ItemFlag.values())` to hide all item tooltips.

### Observed/Actual behavior

The item tooltips are still present, and the returned item will cause an error while chunk saving, entity saving or using /paper dump item: https://pastebin.com/raw/sWPARh80

### Steps/models to reproduce

Just get the "broken" item using something like
```
  @EventHandler(priority = EventPriority.MONITOR)
  public void listen(final @NotNull PlayerJumpEvent event) {
    final @NotNull ItemStack itemStack = new ItemStack(Material.DIAMOND_SWORD);
    itemStack.editMeta(itemMeta -> itemMeta.addItemFlags(ItemFlag.values()));
    event.getPlayer().getInventory().addItem(itemStack);
  }
```

### Plugin and Datapack List

Just a single test plugin.

### Paper version

This server is running Paper version git-Paper-10 (MC: 1.20.5) (Implementing API version 1.20.5-R0.1-SNAPSHOT) (Git: 37b3891)
You are running the latest version
Previous version: git-Paper-446 (MC: 1.20.4)

**Comment by lynxplay** [comment]
Accepted, machine is looking into it, should be a fast fix.

**Comment by Machine-Maker** [comment]
Just to note, doing this to an itemstack without also adding information for the tooltips to hide WILL NOT change the itemstack. In order for the hide to actually be saved, there must also be some data for it to hide. Except for the `HIDE_ADDITIONAL_TOOLTIP` which **IS** saved regardless.
