### ISSUE TITLE
1.20.5 #10 Remapping Failure Causes No Plugins To Load

### ISSUE THREAD

**Issue by ydal251** [PaperSpigot/Paper#10474]
### Expected behavior

When a plugin fails to remap the remainder continue to remap and load as normal

### Observed/Actual behavior

When a remapping failure occurs no plugins are loaded
![1 20 5_Remapping_Error](https://github.com/PaperMC/Paper/assets/37512518/39bb385d-650f-4886-ad77-1105b3f3c05f)

### Steps/models to reproduce

New Paper 1.20.5 Build 10 Server
Add Plugins one of which does not remap correctly
Boot server
No plugins are loaded
![1 20 5_Remapping_Error](https://github.com/PaperMC/Paper/assets/37512518/24815351-5d1b-4e67-9309-e7b24cf58489)

### Plugin and Datapack List

Without Remapping Error:
![1 20 5_Remapping_NoError](https://github.com/PaperMC/Paper/assets/37512518/a1ac9e5d-7aa7-47e4-820c-8b193241e1d9)

+ PAPIProxyBridge 1.5 (Will not remap)

### Paper version

![image](https://github.com/PaperMC/Paper/assets/37512518/4d4e7f72-df4e-4dd2-9cdc-f77420aa2b17)

### Other

Logs With Remapping Failure:
[RemappingFailure.log](https://github.com/PaperMC/Paper/files/15142547/RemappingFailure.log)

Logs Without Remapping Failure:
[NoRemappingFailures.log](https://github.com/PaperMC/Paper/files/15142548/NoRemappingFailures.log)

**Comment by kennytv** [comment]
`Duplicate entries detected` means a plugin (in this case PAPIProxyBridge) is shading classes multiple times, they should fix that/join paper-dev for help.

The version of PlaceholderAPI you are using also contains unsupported parsing code, though I think they fixed that in an update. The same applies to InventoryRollbackPlus and WanderingTrades. Make sure you are up to date (!) and if they still don't work, report it to the plugin authors: https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/

**Comment by lynxplay** [comment]
This is not about a failure in remapping, this is about the server not loading any other plugins afterwards.
