### ISSUE TITLE
Typo in Entity Tags

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#10611]
### Expected behavior

in BaseTag, the method isTagged(T) parameter name is "item" which is confusing, because it also applies to entity types now

### Observed/Actual behavior

N/A

### Steps/models to reproduce

N/A

### Plugin and Datapack List

N/A

### Paper version

This server is running Paper version git-Paper-"4491ac0" (MC: 1.20.5) (Implementing API version 1.20.5-R0.1-SNAPSHOT) (Git: 4491ac0)
You are 9 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-"37b3891" (MC: 1.20.5)

### Other

N/A

**Comment by lynxplay** [comment]
The term "Item" represents more than just minecraft items.
> [a distinct part in an enumeration, account, or series](https://www.merriam-webster.com/dictionary/item)

This is perfectly fine.
