### ISSUE TITLE
ItemFlags not being respected in 1.20.5/1.20.6

### ISSUE THREAD

**Issue by deadbeef-enc0de** [PaperSpigot/Paper#10628]
### Expected behavior

ItemFlags set on an ItemStack are persisted and respected

### Observed/Actual behavior

ItemFlags are only persisted and respected if the associated data is on the item.

example: Adding ItemFlag.HIDE_ENCHANTS does not get set/persisted if there are no enchantments on the ItemStack

### Steps/models to reproduce

1) Create and ItemStack
2) Set an itemFlag which the stack doesn't have data for (ie ItemFlag.HIDE_ENCHANTS)
3) Print out the set flags on the ItemStack

### Plugin and Datapack List

Every plugin running is private but here is the list
[09:12:59 INFO]: Server Plugins (4):
[09:12:59 INFO]: Bukkit Plugins:
[09:12:59 INFO]:  - EasyCommands, LocalMarket, RPG, YamlSaver

### Paper version

[09:13:07 INFO]: Checking version, please wait...
[09:13:08 INFO]: This server is running Paper version git-Paper-27 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) (Git: 937a67a)

### Other

I have a feeling that this is a result of the backend data changes potentially in minecraft itself.

If so please just comment and close and I will work around these issues in my plugins.

**Comment by emilyy-dev** [comment]
This is intended, see the last comment in #10473
