### ISSUE TITLE
Inefficient gameprofile lookups while using velocity's modern forwarding

### ISSUE THREAD

**Issue by bridgelol** [PaperSpigot/Paper#10648]
### Timings or Profile link

N/A

### Description of issue

Upon examining (after getting rate limited **lol**), I noticed paper nodes are making mojang api calls upon every player join which was interesting to me as velocity should forward all of this info.

Upon digging deeper I realized this is completely redundant.

ServerLoginPacketListenerImpl#callPlayerPreLoginEvents(GameProfile) gets called on all occasions, upon forwarding using velocity, or just generic standalone paper.

What's interesting is that the this call always gets executed even when it shouldn't need to.

![image](https://github.com/PaperMC/Paper/assets/29434554/e881482e-15d5-4eb1-b7b3-a2c98475bad0)
![image](https://github.com/PaperMC/Paper/assets/29434554/b610e114-2c80-4c7c-b6df-9dac097c8094)

This call ultimately results in either;
#1 The usercache needing to lookup this gameprofile again
#2 A mojang api call (this is the main issue, however saving some CPU usage in case #1 is also nice).

If you have 3 joint sub-servers on your velocity network that all run on the same public ip, it is pretty easy to get rate limited, as I discovered the hard way 👍 

What I recommend (and I will be creating a PR for this, however I'd first like some feedback to confirm I'm not entirely delusional and am missing a use case for this call while using velocity):

If this call was made with the origin of velocity modern forwarding **and** the AsyncPlayerPreLoginEvent didn't modify the player profile, we no longer execute this call.

### Plugin and Datapack List

not important

### Server config files

Not important

### Paper version

All

### Other

As you can see here https://github.com/PaperMC/Velocity/blob/368d1a7c1250b4138f683e64ebb6aadfe7a4b1b3/proxy/src/main/java/com/velocitypowered/proxy/connection/PlayerDataForwarding.java#L73

All necessary gameprofile properties are being forwarded

**Comment by electronicboy** [comment]
I think that the biggest question to me here is over the behavior of complete, if a profile is already completed, why is it doing lookups? I think that the class was generally designed in mind that the profile would be newly created from the API or server and just doesn't check that

**Comment by bridgelol** [comment]
> I think that the biggest question to me here is over the behavior of complete, if a profile is already completed, why is it doing lookups? I think that the class was generally designed in mind that the profile would be newly created from the API or server and just doesn't check that

Yup, I’ll push something in a minute

**Comment by bridgelol** [comment]
This is a one liner actually,

if (onlineMode && (!isCompleteFromCache || textures && !hasTextures())) {
should be
if (onlineMode && (!isCompleteFromCache || (textures && !hasTextures()))) {

**Comment by bridgelol** [comment]
In CraftPlayerProfile#complete(boolean, boolean)

**Comment by bridgelol** [comment]
> I think that the biggest question to me here is over the behavior of complete, if a profile is already completed, why is it doing lookups? I think that the class was generally designed in mind that the profile would be newly created from the API or server and just doesn't check that

https://github.com/PaperMC/Paper/pull/10650

**Comment by bridgelol** [comment]
https://github.com/PaperMC/Paper/pull/10651
