### ISSUE TITLE
Server not unloading chunks when saving is off

### ISSUE THREAD

**Issue by jensjeflensje** [PaperSpigot/Paper#10657]
### Expected behavior

When flying around alone on a server, I expect the chunks that I pass to eventually unload.

### Observed/Actual behavior

Once they're loaded, chunks never unload as shown by the `/paper chunkinfo` command. (inactive)
![image](https://github.com/PaperMC/Paper/assets/30746389/0f3cda8a-ba1d-4995-8ba6-7d65d2a2586e)

`/paper holderinfo` also shows the unloadable, but not unloaded chunks.
![image](https://github.com/PaperMC/Paper/assets/30746389/d9977e3a-4424-4b02-ac05-8369d272f11d)

Essentials `/gc` does show a normal count though (around 200 for 1 player)

### Steps/models to reproduce

What I did is:
- Create a new server with paper 1.20.4 build 496
- Execute `/paper chunkinfo` to get a baseline
- Execute `/save-off`
- Fly around in creative a little
- Execute `/paper chunkinfo` again to see the "inactive" count filling up without it ever going down. `/paper holderinfo` also shows some important info

Bonus: execute `/save-on` and watch the unloadable chunks actually get unloaded very quickly

### Plugin and Datapack List

Using none.

```
> datapack list
[14:56:32 INFO]: There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]
[14:56:32 INFO]: There are no more data packs available
```

```
> plugins
[14:56:46 INFO]: Server Plugins (0):
```

### Paper version

```
> version
[14:57:04 INFO]: Checking version, please wait...
[14:57:04 INFO]: This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)
You are running the latest version
```

**Comment by electronicboy** [comment]
This behavior is 100% intended by mojang, they don't unload chunks because they can't save them, and there's generally 0 expectation that chunks in a world session are going to be lost
