### ISSUE TITLE
not a server crash but a player getting kicked/banned of a server

### ISSUE THREAD

**Issue by chrismc128** [PaperSpigot/Paper#10656]
### Stack trace

```
paste your stack trace or a paste.gg link here!
```

### Plugin and Datapack List

paper 1.20.6 server 
kicked client minecraft 1.20.2
kicker client Forge 1.20.1 version of forge 47.1.46

### Actions to reproduce (if known)

load a crossbow with a specrtal arrow in paper server mc version 1.20.6 and shoot it at a player. the player will be arrow banned off the server

### Paper version

Unknown im not the owner

### Other

![image](https://github.com/PaperMC/Paper/assets/168901368/c229b548-3d26-4a4a-9955-32ce35f355ba)

**Comment by kennytv** [comment]
That's not a Paper issue, probably down due to outdated plugins
