### ISSUE TITLE
hide_attributes flag not working

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#10655]
### Expected behavior

Applying this attribute should hide weapon damage in tooltip

### Observed/Actual behavior

It doesn't

### Steps/models to reproduce

meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES)

### Plugin and Datapack List

N/A

### Paper version

This server is running Paper version git-Paper-"0db72ac" (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) (Git: 0db72ac)
You are running the latest version
Previous version: git-Paper-"8f7ac62" (MC: 1.20.5)

### Other

paper dumpitem gives this: minecraft:diamond_sword[hide_additional_tooltip={}]

_No response_

**Comment by Machine-Maker** [comment]
You have to actually set some attributes to hide. The way ItemFlag works has changed, for all except the "additional info" one, you actually have to set some data in order to have the hide flag actually do anything.

**Comment by electronicboy** [comment]
The hide attributes flag is stored on the attributes data, so, in order to handle this, you'd need to supply an attribute component, supplying an attribute component, however, will override any default attributes provided by the item itself, so, yes, you can do it, but, not without side effects

**Comment by electronicboy** [comment]
The ItemMeta does not expose the ability to do this via the API (and will be prone to removing it in certain cases). We cannot expose this ability due to the unintended side-effects, and have generally reverted spigots attempt at doing this because it breaks expectations.

**Comment by Machine-Maker** [comment]
Going to close this as WAI. Mojang really should add a way to hide attributes without having to copy over the default attributes for an item type. We have no interesting in maintaining a hacky fix where we implicitly do that copying over if someone sets the hide flag, and we don't want to keep upstream's broken fix that just deletes all implicit attribute modifiers for items.

**Comment by TroDerp** [comment]
> Going to close this as WAI. **Mojang really should add a way to hide attributes without having to copy over the default attributes for an item type.** We have no interesting in maintaining a hacky fix where we implicitly do that copying over if someone sets the hide flag, and we don't want to keep upstream's broken fix that just deletes all implicit attribute modifiers for items.

Should reconsider fixing this bug for the future MC version (whenever it comes), due to 25w04a changing how tooltips are hidden again and separating "show_in_tooltip" from the attribute component.
