### ISSUE TITLE
Shulkers loaded from bukkit yml have no nbt on contents

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#10666]
### Expected behavior

If you have an item with NBT within a shulker serialized into yaml, after deserialization the item should have nbt?

### Observed/Actual behavior

All items in the shulker are stripped of nbt (yikes)

### Steps/models to reproduce

Serialize itemstack to yml

### Plugin and Datapack List

N/A

### Paper version

This server is running Paper version git-Paper-"7ae2c67" (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) (Git: 7ae2c67)
You are running the latest version
Previous version: git-Paper-"0db72ac" (MC: 1.20.6)

**Comment by lynxplay** [comment]
Yea, we have been thinking about it for a while.
I don't think there is much saving we can do for you on any of these issues.

**Comment by Machine-Maker** [comment]
@ThrowerWay can you clarify what you mean by "an item with NBT"? I tested this by putting 2 stacks in an anvil and renaming them, then putting them in a shulker. after serializing to yaml and back, they still had the custom names. Did you mean actually "custom" nbt, like in the custom_data component?

**Comment by Machine-Maker** [comment]
Can you send some itemstacks serialized into yaml in 1.20.4 so I can test upgrading them?

**Comment by lynxplay** [comment]
Closing this as it has been without activity for 3 weeks.
