### ISSUE TITLE
Spawn eggs lose data after using them

### ISSUE THREAD

**Issue by Toseflo** [PaperSpigot/Paper#10663]
### Expected behavior

Spawn eggs shouldn't lose data after using them

### Observed/Actual behavior

Spawn eggs do lose data after using them

### Steps/models to reproduce

1. Give yourself a custom spawn egg, e.g. `/give @p chicken_spawn_egg[entity_data={id:"minecraft:cow"}]`. Make sure to only have one spawn egg in your hand. For more than one spawn egg, this doesn't happen
2. Use the spawn egg once and notice how a cow is spawned
3. Use the spawn egg a second time and it will now spawn a chicken

### Plugin and Datapack List

No plugins or data packs

### Paper version

This server is running Paper version git-Paper-40 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) (Git: 7401313)
You are running the latest version
Previous version: git-Paper-462 (MC: 1.20.4)

**Comment by lynxplay** [comment]
Replicable. Missing data restoration after consumption in ServerPlayerGameMode#useItemOn
