### ISSUE TITLE
HoverEvent.ShowItem not working in 1.20.5+

### ISSUE THREAD

**Issue by ShaneBeee** [PaperSpigot/Paper#10670]
### Expected behavior

I expect this method to work like on 1.20.4 where it would show all item modifications

### Observed/Actual behavior

When using the hover event to show item, the vanilla/base item is shown, and no modifications are show (ex: enchantments, display name).
<img width="288" alt="Screenshot 2024-05-06 at 9 32 07 AM" src="https://github.com/PaperMC/Paper/assets/20008482/901268f4-b0ec-4411-870a-408b4196f5d2">

### Steps/models to reproduce

Test Code:
```java
ItemStack itemStack = new ItemStack(Material.DIAMOND);
itemStack.editMeta(itemMeta -> {
    itemMeta.displayName(Component.text("Mr Diamond"));
    itemMeta.addEnchant(Enchantment.SHARPNESS, 3, true);
});
TextComponent letsSeeThatItem = Component.text("lets see that item");
BinaryTagHolder binaryTagHolder = BinaryTagHolder.binaryTagHolder(itemStack.getItemMeta().getAsString());
HoverEvent.ShowItem showItem = HoverEvent.ShowItem.showItem(itemStack.getType().key(), 1, binaryTagHolder);
TextComponent textComponent = letsSeeThatItem.hoverEvent(HoverEvent.showItem(showItem));
sender.sendMessage(textComponent);
```

### Plugin and Datapack List

```
[09:30:53 INFO]: Server Plugins (8):
[09:30:53 INFO]: Bukkit Plugins:
[09:30:53 INFO]:  - BeeConomy, RandomTeleport, SkBee, SkBriggy, Skript, skript-reflect, spark, Vault
```

### Paper version

 Paper version git-Paper-49 (MC: 1.20.6)

**Comment by NonSwag** [comment]
BinaryTagHolder doesnt work anymore, you should use ItemStack#asHoverEvent
![image](https://github.com/PaperMC/Paper/assets/54660361/6334d6a9-3148-4f82-9964-eed5df2f7b2e)
![image](https://github.com/PaperMC/Paper/assets/54660361/ecc911b8-57b9-4345-9ad7-bb254b12d50b)

**Comment by ShaneBeee** [comment]
oooo awesome, ok thank you!

**Comment by NonSwag** [comment]
No problem, had the exact same issue the day after release of paper 1.20.5.

**Comment by jpenilla** [comment]
Vanilla expects item components instead of a single nbt compound now. asHoverEvent will handle populating the component map for you.

**Comment by ShaneBeee** [comment]
I tried it, and it works perfectly :) thanks!
I guess you guys can close this issue.
