### ISSUE TITLE
AttributeModfiers is not removed when the player dies

### ISSUE THREAD

**Issue by sweetmeowcat02** [PaperSpigot/Paper#10684]
### Expected behavior

All modifiers added by /attribute are removed upon death

### Observed/Actual behavior

The modifiers added by /attribute to still exist after rebirth

### Steps/models to reproduce

1. run /attribute @s minecraft:generic.armor modifier add 1-0-0-0-0 "" 1 add_value
2. run /attribute @s minecraft:generic.armor modifier value get 1-0-0-0-0
3. run /kill @s
4. Respawn
5. Run again /attribute @s minecraft:generic.armor modifier value get 1-0-0-0-0

### Plugin and Datapack List

> plugins
[10:43:44 INFO]: Server Plugins (0):

> datapack list
[10:44:13 INFO]: There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]
[10:44:13 INFO]: There are no more data packs available

### Paper version

> version
[10:44:27 INFO]: Checking version, please wait...
[10:44:28 INFO]: This server is running Paper version git-Paper-55 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) (Git: 1b67e02)
You are running the latest version

**Comment by Malfrador** [comment]
Attributes being reset on death is considered a bug by Mojang: https://bugs.mojang.com/browse/MC-179940

Paper generally aims to fix bugs, especially if they are confirmed by Mojang but unfixed.

**Comment by Machine-Maker** [comment]
This is officially "works as intended" as Mojang have [fixed the linked issue](https://bugs.mojang.com/browse/MC-179940). Attributes are expected to be retained on player deaths.
