### ISSUE TITLE
Items loose attribute_modifiers component with only show_in_tooltip after interaction

### ISSUE THREAD

**Issue by Toseflo** [PaperSpigot/Paper#10686]
### Expected behavior

Moving an item in an inventory shouldn't change the item data

### Observed/Actual behavior

Moving an item with attribute_modifiers:{show_in_tooltip: 0b, modifiers:[]} removes the attribute_modifiers component and the tooltip will become visible

### Steps/models to reproduce

1. Use the command `/give @p netherite_chestplate[minecraft:attribute_modifiers={show_in_tooltip:0b,modifiers:[]}]` to give yourself a custom chestplate which hides the armor info
2. Pick the item up with your cursor and place it in the inventory again
3. Notice how the armor info will now be shown
4. You can use `/data get entity @s SelectedItem` to see that the attribute_modifiers component was deleted

### Plugin and Datapack List

No plugins or data packs

### Paper version

This server is running Paper version git-Paper-60 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) (Git: 4fd58a1)
You are running the latest version
Previous version: git-Paper-40 (MC: 1.20.6)

**Comment by Machine-Maker** [comment]
What is your intention when setting that value for the attribute data component? What are you expecting that to do?

**Comment by Toseflo** [comment]
I want to hide the custom tooltip from tools and weapons. The only working way I found so far in 1.20.6 was setting the attribute component like this, or is there another way?

**Comment by Machine-Maker** [comment]
> I want to hide the custom tooltip from tools and weapons. The only working way I found so far in 1.20.6 was setting the attribute component like this, or is there another way?

By setting the modifiers to an empty list like you are doing in your example, you aren't just hiding the attribute modifiers, you are removing any implicit ones. Various item types have implicit attribute modifiers and if the data component exists on the itemstack, those will be used over the implicit ones. And since you set it to an empty list, the stack will have no attributes at all.

**Comment by Toseflo** [comment]
This bug appears to be fixed for armor, but it still persists for tools and weapons. Here the used give commands:
`/give @p minecraft:diamond_pickaxe[minecraft:attribute_modifiers={show_in_tooltip:0b,modifiers:[]}]`
`/give @p minecraft:diamond_sword[minecraft:attribute_modifiers={show_in_tooltip:0b,modifiers:[]}]`
`/give @p minecraft:diamond_horse_armor[minecraft:attribute_modifiers={show_in_tooltip:0b,modifiers:[]}]`
These items have the same problem that the data changes after picking it up with the cursor and placing it again in the inventory.

`/give @p minecraft:shield[minecraft:attribute_modifiers={show_in_tooltip:0b,modifiers:[]}]`
Shields have an even weirder problem, which can be seen with `/data get entity @s SelectedItem`. After picking it up the first time, the attribute_modifiers component disappears and instead the panner_patterns component with an empty list appears. After picking the shield up a second time, this component also disappears.

**Comment by Machine-Maker** [comment]
> Shields have an even weirder problem, which can be seen with /data get entity @s SelectedItem. After picking it up the first time, the attribute_modifiers component disappears and instead the panner_patterns component with an empty list appears. After picking the shield up a second time, this component also disappears.

This is a separate, more complicated issue. You can open a new issue with this as the subject. It was not fixed in a61d58d
