### ISSUE TITLE
World border instantly kills players

### ISSUE THREAD

**Issue by NVGAT** [PaperSpigot/Paper#10687]
### Expected behavior

Player slowly loses health upon exiting the border, the damage gradually increasing with the distance traveled

### Observed/Actual behavior

Player dies instantly

### Steps/models to reproduce

Exit the world border by any means, in the following clip I used an Ender Pearl: https://youtube.com/clip/UgkxpLiVhNci-DqPA0DaZ_em7i99NGBNLSiR?si=q1sc3_W_-WuS4Ns3

### Plugin and Datapack List

BisectHosting, Chunky, Graves, InstantRestock, NationsDeathBan, ProtocolLib, ViaBackwards, ViaVersion, voicechat

### Paper version

Unsure, all I know is that it's an experimental 1.20.6 build.

**Comment by NoahvdAa** [comment]
Can't reproduce on the latest build, I slowly gain damage when I move more than five blocks from the border, and it increases when I get further away (until I walk into a second invisible wall), but there is definitely no insta-kill.

**Comment by NVGAT** [comment]
Update: I spoke to the server owner and it was just a poorly configured server. My apologies!
