### ISSUE TITLE
Connection timed out when spectating entity

### ISSUE THREAD

**Issue by xaanndeer** [PaperSpigot/Paper#10683]
### Expected behavior

Players can spectate entities without getting timed out.

### Observed/Actual behavior

Players that spectate entities, without sending other packets (commands e.g.) get timed out after ~30 seconds.

### Steps/models to reproduce

- Enter spectator mode
- Left-click target entity or use the /spectate command
- Wait ~30 seconds without sending any other packets to the server (commands e.g.)

### Plugin and Datapack List

- Plugins: None
- Datapacks: vanilla, file/bukkit, paper

### Paper version

Paper version git-Paper-54 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) (Git: f2512b1)

**Comment by Malfrador** [comment]
Can reproduce. Does not happen on Spigot or Vanilla.
