### ISSUE TITLE
Brushed block turning into sand doesn't register any block events?

### ISSUE THREAD

**Issue by SpectreVoid** [PaperSpigot/Paper#10698]
### Expected behavior

That the brushed block when turning from suspicious sand/gravel into sand/gravel that it fires the BlockBreakBlockEvent or a similar event. (Unsure if correct label / place. sorry if not)

### Observed/Actual behavior

Can't find any event fired when dusted block changes. 

### Steps/models to reproduce

Grab a dust and a suspicious block and have at it (: 

### Plugin and Datapack List

[03:21:54 INFO]:  - LuckPerms, Mastery, Vault

### Paper version

[03:22:08 INFO]: Checking version, please wait...
[03:22:08 INFO]: This server is running Paper version git-Paper-49 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) (Git: ac3a547)
You are 19 version(s) behind
Download the new version at: https://papermc.io/downloads/paper

**Comment by AlbusThePenguin** [comment]
https://github.com/PaperMC/Paper/pull/9898

**Comment by AlbusThePenguin** [comment]
I stand corrected. Sorry [https://github.com/PaperMC/Paper/pull/9898](url)
