### ISSUE TITLE
Brigadier: Cyclic command graph (through redirects) causes StackOverflowError

### ISSUE THREAD

**Issue by Rickyboy320** [PaperSpigot/Paper#10704]
### Expected behavior

Happy to see the Brigadier branch merged! I started experimenting with the migration of our command framework onto this, and found this issue when trying to register one of our self-referential commands.

The structure of the command is something like:

`/root child <arg> -> child`

much like how `/execute` in vanilla redirects to itself. This should be, to my knowledge, a valid registration.

See the detailed registration process in `Steps to reproduce`.

### Observed/Actual behavior

The unwrapping of the command tree causes a StackOverflowError:
https://pastes.dev/g3qbF994ZR

### Steps/models to reproduce

```java
plugin.getLifecycleManager().registerEventHandler(LifecycleEvents.COMMANDS, event -> {
            var root = Commands.literal("root").executes((ctx) -> 1).build();
            var arg = Commands.literal("child").redirect(root);

            root.addChild(arg.build());

            event.registrar().register(root);
        });
```

causes `StackOverflowError` in `event.registrar().register(root);`

### Plugin and Datapack List

My testing plugin. 
Contains more than the code above, but that _should_ not interfere with this step specifically.

### Paper version

This server is running Paper version git-Paper-69 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) (Git: 7e48f66)
You are running the latest version
Previous version: git-Paper-496 (MC: 1.20.4)

### Other

I think the caching of the rewritten nodes:
```java
converted.wrappedCached = pureNode;
pureNode.unwrappedCached = converted;
```
should be done _before_ processing children in `ApiMirrorRootNode#convertFromPureBrigNode`

**Comment by lynxplay** [comment]
Replicable, cached node instance is set after mapping over children, quick fix presumably is storing this before unwrapping children.

**Comment by Rickyboy320** [comment]
Thanks! Can confirm that this solves the issue.
