### ISSUE TITLE
Libraries loaded using `addURL(URL)` don't get remapped

### ISSUE THREAD

**Issue by frengor** [PaperSpigot/Paper#10713]
### Expected behavior

Libraries loaded calling `addURL(URL)` on the plugin class loader (for example, using a library like [Libby](https://github.com/AlessioDP/libby)) should be remapped if the plugin is spigot-mapped.

### Observed/Actual behavior

The classes of such libraries are not remapped. Consequently, the loaded libraries cannot access CraftBukkit or NMS classes.

### Steps/models to reproduce

I've created a test plugin available at <https://github.com/frengor/AddURLTest>. Steps to reproduce are present in the `README` together with the already built plugin.

### Plugin and Datapack List

None apart the plugin mentioned before.

### Paper version

[05:38:14 INFO]: This server is running Paper version git-Paper-71 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) (Git: 11c3963)
You are running the latest version
Previous version: git-Paper-64 (MC: 1.20.6)

### Other

The test plugin correctly works on Spigot servers, but not on Paper servers.

This issue was originally discovered while testing the spigot mapped version of [UltimateAdvancementAPI](https://github.com/frengor/UltimateAdvancementAPI) on Paper 1.20.6. UltimateAdvancementAPI uses [Libby](https://github.com/AlessioDP/libby) to load [CommandAPI](https://github.com/JorelAli/CommandAPI) at runtime, which then cannot access NMS and CraftBukkit classes since it isn't remapped.

**Comment by kennytv** [comment]
At that stage it is already too late to properly remap something via the normal system. libby could redirect to Spigot's maven dependency resolver where present to be properly integrated into the whole server ecosystem, or if it really needs to, call the remapper itself

**Comment by frengor** [comment]
The problem with using the `libraryLoader` class loader is that it is present (i.e. not null) only if the plugin declares libraries in its `plugin.yml`, however plugins using Libby usually don't declare any. On top of that, when using Libby in a library you have no control on libraries declared by the plugins which will depend on you.

From `LibraryLoader.createLoader(PluginDescriptionFile desc)`:
```java
if ( desc.getLibraries().isEmpty() )
{
    return null;
}
```

Could always initializing the `libraryLoader` field to a non-null class loader be enough? (in which case I could make a PR)
