### ISSUE TITLE
BlockPistonEvent doesn't have handlers list

### ISSUE THREAD

**Issue by AgarOther** [PaperSpigot/Paper#10723]
### Stack trace

[10:55:33 ERROR]: Error occurred while enabling SkyEleo v0.9-BETA (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event org.bukkit.event.block.BlockEvent. Static getHandlerList method required!

### Plugin and Datapack List

Using my own plugin with a test debug of BlockPistonEvent

### Actions to reproduce (if known)

1- Use BlockPistonEvent
2- Compile
3- Get this error

### Paper version

This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)
You are running the latest version
Previous version: git-Paper-493 (MC: 1.20.4)

### Other

After checking the BlockPistonEvent inside Paper, it seems no handlers list method are there. Meaning we can't listen to the event as the required method getHandlerList isn't coded in.

**Comment by Warriorrrr** [comment]
The blockpistonevent class is abstract, you need to listen to the [extend](https://jd.papermc.io/paper/1.20.6/org/bukkit/event/block/BlockPistonExtendEvent.html) and [retract](https://jd.papermc.io/paper/1.20.6/org/bukkit/event/block/BlockPistonRetractEvent.html) events that *extend* it.
