### ISSUE TITLE
Please synchronize SpigotMC commit: Fix regression preventing positivity.setDamage value from causing knockback for 0 damage events

### ISSUE THREAD

**Issue by LoliColleen** [PaperSpigot/Paper#10749]
### Expected behavior

SpigotMC fixed a bug in a recent commit, but PaperMC has not yet synchronized this fix. Wish PaperMC could sync up. Fixing the bug will affect some plugins to add knock back function to projectiles such as snowballs.

**Commit of the bug:**
`https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/2ea1e7ac2795f160ad7cdae1a7c21cc6c2bf4a32`

### Observed/Actual behavior

Preventing positivity.setDamage value from causing knockback for 0 damage events

### Steps/models to reproduce

```
@EventHandler(ignoreCancelled = true, priority = EventPriority.HIGHEST)
    public void onEntityDamageByEntity(EntityDamageByEntityEvent event) {
         event.setDamage(Math.max(event.getDamage(), 1));
    }
}
```
In older versions, these codes can make snowball able to cause knock back.
But a wrong change disable this.
So this commit can solve this problem.

### Plugin and Datapack List

In fact plugins and datapacks do not affect

> pl
[00:31:01 INFO]: Server Plugins (11):
[00:31:01 INFO]: Bukkit Plugins:
[00:31:01 INFO]:  - Carrot, FriendsAPIForPartyAndFriends, LuckPerms, Main, PlaceholderAPI, ProtocolLib, SkyBattle, Spigot-Party-API-PAF, UltimateManager, ViaBackwards
[00:31:01 INFO]:  ViaVersion

> datapack list
[00:31:16 INFO]: There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]
[00:31:16 INFO]: There are no more data packs available

### Paper version

[00:32:34 INFO]: This server is running Paper version 1.20.6-82-master@0ad09de (2024-05-18T20:25:01Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-69 (MC: 1.20.6)

**Comment by lynxplay** [comment]
We'll update the spigot upstream in due time, no need to open an issue for it :+1:

**Comment by LoliColleen** [comment]
By the way, the penultimate line of code here should be changed to return `originalDamage > 0`.
This is because we still need to consider whether the original damage is >0.
LivingEntity.java Line2386
```
if (event.getDamage(DamageModifier.BLOCKING) < 0) {
if (this instanceof ServerPlayer) {
CriteriaTriggers.ENTITY_HURT_PLAYER.trigger((ServerPlayer) this, damagesource, originalDamage, f, true);  // Paper - fix taken/dealt param order
f2 = (float) -event.getDamage(DamageModifier.BLOCKING);
if (f2 > 0.0F &&f2 < 3.4028235E37F) {
awardStat(Stats.DAMAGE_BLOCKED_BY_SHIELD, Math.round(originalDamage * 10.0F)); ((ServerPlayer) this). Awardstat (stats.damage_blocked_by_Shield, Math.round(Originaldamage * 10.0f));
}
}

if (damagesource.getEntity() instanceof ServerPlayer) {
CriteriaTriggers.PLAYER_HURT_ENTITY.trigger((ServerPlayer) damagesource.getEntity(), this, damagesource,  originalDamage, f, true);  // Paper - fix taken/dealt param order
}

return true;
} else {
return true;  // Paper - return false ONLY if event was cancelled
}
```
