### ISSUE TITLE
Hide attributes not working in 1.20.6

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#10744]
### Expected behavior

Hide attributes flag should hide attributes

### Observed/Actual behavior

Adding item flag for hide attributes still shows "when in main hand blah"

### Steps/models to reproduce

itemMeta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES)

Worked perfectly in 1.20.4
weirdly enough, works perfectly with viaversion on 1.20.6 client, so not a client problem

### Plugin and Datapack List

N/A

### Paper version

This server is running Paper version 1.20.6-DEV-master@5a9afbe (2024-05-18T13:33:02Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-"4fd58a1" (MC: 1.20.6)

**Comment by electronicboy** [comment]
This 100% works as intended, you can't have a hide attributes flag without defining the attributes, which would override all of the items default attributes
