### ISSUE TITLE
item duplicates just place an item in item frame and break it

### ISSUE THREAD

**Issue by xlotrz** [PaperSpigot/Paper#10745]
### Expected behavior

item duplicates just place an item in item frame and break it

### Observed/Actual behavior

item duplicates just place an item in item frame and break it

### Steps/models to reproduce

item duplicates just place an item in item frame and break it

### Plugin and Datapack List

item duplicates just place an item in item frame and break it

### Paper version

item duplicates just place an item in item frame and break it

### Other

item duplicates just place an item in item frame and break it

**Comment by kennytv** [comment]
Please follow the issue template
