### ISSUE TITLE
NPE while sending a resource pack with no prompt

### ISSUE THREAD

**Issue by Sylfare** [PaperSpigot/Paper#10741]
### Expected behavior

Server should be able to send the resource pack without prompt message: the `prompt` method from [ResourcePackRequest.Builder](https://jd.advntr.dev/api/4.17.0/net/kyori/adventure/resource/ResourcePackRequest.Builder.html) is nullable.

### Observed/Actual behavior

A `NullPointerException` is raised in the console instead
Stacktrace : https://paste.gg/p/anonymous/a3b051e274f44bd88b52e57245ea8104

### Steps/models to reproduce

[Example resource pack](https://github.com/PaperMC/Paper/files/15358352/example_pack.zip)
Copy this snippet in a test plugin:
```java
try {
    URI uri = new URI("https://github.com/PaperMC/Paper/files/15358352/example_pack.zip");
    String hash = "e7c726200efca2f0f1f22eebe927ce28e4ac3082";
    UUID uuid = UUID.nameUUIDFromBytes(hash.getBytes());

    event.getPlayer().sendResourcePacks(ResourcePackRequest.resourcePackRequest().packs(
            ResourcePackInfo.resourcePackInfo(uuid, uri, hash))
            // .prompt(Component.text("Hello"))
            .asResourcePackRequest());
} catch (URISyntaxException e) {
    e.printStackTrace();
}
```

### Plugin and Datapack List

Plugins:
```
[23:30:19 INFO]: Server Plugins (1):
[23:30:19 INFO]: Bukkit Plugins:
[23:30:19 INFO]:  - *ResourcePackSend
```
`ResourcePackSend` is my test plugin

Datapacks:
```
[23:45:36 INFO]: There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]
[23:45:36 INFO]: There are no more data packs available
```

### Paper version

```
[23:30:46 INFO]: This server is running Paper version 1.20.6-79-master@f175193 (2024-05-16T00:15:01Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
```

### Other

It works fine with a prompt message

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Paper/commit/d8d59e0cdeda3f7e9da337b6d489f306fc5e76c9 - I believe this was already patched?

**Comment by Sylfare** [comment]
Yes, it works properly! I was too slow to make my issue, oops :sweat_smile:
