### ISSUE TITLE
My custom localizednames on items are not recognized by any events?

### ISSUE THREAD

**Issue by LouisDerEchte** [PaperSpigot/Paper#10746]
### Expected behavior

My code is normaly supposed to do something and it did in every version (even 1.20.4) except of 1.20.6

### Observed/Actual behavior

Nothing happens not even a stacktrace

### Steps/models to reproduce

Item with localizedname

### Plugin and Datapack List

Only my own Plugin

### Paper version

1.20.6

**Comment by kennytv** [comment]
What is "your code", what is "something"? "1.20.6" is also not the full version info we need

**Comment by kennytv** [comment]
See https://jd.papermc.io/paper/1.20.6/org/bukkit/inventory/meta/ItemMeta.html#setLocalizedName(java.lang.String)

**Comment by LouisDerEchte** [comment]
@EventHandler
    public void onInteract(PlayerInteractEvent e){
        if(e.getPlayer().getLocation().getWorld().getName().equalsIgnoreCase("world")) {
            if (e.getPlayer().getInventory().getItemInMainHand() != null) {
                if (e.getPlayer().getInventory().getItemInMainHand().hasItemMeta()) {
                    if (e.getPlayer().getInventory().getItemInMainHand().getItemMeta().getLocalizedName().equals("settings.lobby")) {
                        e.getPlayer().openInventory(settings_inventory(e.getPlayer()));
                        e.setCancelled(true);
                    }
                }
            }
        }

    }

**Comment by LouisDerEchte** [comment]
Something like this

**Comment by LouisDerEchte** [comment]
`ItemStack settings = new ItemBuilder(Material.COMPASS).addEnchant(Enchantment.POWER, 1).addItemFlags(ItemFlag.HIDE_ENCHANTS).setDisplayname("§5§lMenü").setLocalizedName("settings.lobby").build();`

**Comment by electronicboy** [comment]
Spigot made setLocalizedName is NOOP, and made getLocalizedName return the display name. apparently, this is no longer a thing that's used by the client and so they dropped it

**Comment by LouisDerEchte** [comment]
So I'm no longer able to use it?

**Comment by electronicboy** [comment]
correct, it does nothing useful anymore

**Comment by LouisDerEchte** [comment]
> Spigot made setLocalizedName is NOOP, and made getLocalizedName return the display name. apparently, this is no longer a thing that's used by the client and so they dropped it

Since when tho?

**Comment by electronicboy** [comment]
In the 1.20.5 update
