### ISSUE TITLE
Underwater ruined portal chests don't spawn loot.

### ISSUE THREAD

**Issue by N1ghthauq** [PaperSpigot/Paper#10750]
### Expected behavior

Ruined portal chests should have random loot inside.

### Observed/Actual behavior

When a ruined portal chest is underwater, it doesn't generate loot.

### Steps/models to reproduce

Install paper 1.20.4, generate new chunks with ruined nether portal that has an underwater chest, open chest to see it is empty.

### Plugin and Datapack List

There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]
Server Plugins (0):

### Paper version

This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)

### Other

I checked to see if this behavior was present in spigot, or because of any plugins I had. The issue was only able to be reproduced in paper and purpur. Not sure if 1.20.4 is supported anymore. I tried my best to find a similar issue thread, but I am not adept at searching issues in github.

**Comment by Warriorrrr** [comment]
Can reproduce on 1.20.4 build 496 & 1.20.6 build 84

**Comment by Machine-Maker** [comment]
So, @Lulu13022002 discovered that this is caused by the fix that was added in https://github.com/PaperMC/Paper/pull/10375, specifically the first hunk in the added patch.
