### ISSUE TITLE
Armorstand disappear

### ISSUE THREAD

**Issue by BasArtsDEV** [PaperSpigot/Paper#10753]
### Expected behavior

I am on paper 1.20.6 on the latests versions (not sure of which exactly) trying to create an HideAndSeek plugin.
For this purpose, I use an invisible armorstand where I put the block on its head.

However, it just disappears when looking higher or getting further, ...

### Observed/Actual behavior

I really would like this bug to be fixed as fast as possible :)

### Steps/models to reproduce

Not sure but create an invisible armorstand with no gravity where you put a block on its head and teleport it below the ground to make the block touch the ground.
Then go around it and it should disappear :(

### Plugin and Datapack List

ArmorStandTools
FAWE

### Paper version

1.20.6 (not access to the /version) probably around build 80+

**Comment by Warriorrrr** [comment]
Does it only disappear visually when looking too far away from it? That doesn't sound much like an issue with the server, since the client controls that.

As a workaround you could use a block display entity instead of blocks on an armor stands head.

**Comment by Ducki0210** [comment]
It is not about the distance between you and the armorstand but just when you are looking, for example if you look above its head it disappear, it is just strange.

Also, I use falling block by default but I went to armorstand because you can remove the hitbox and edit attributes on it, which you can't do on falling block

**Comment by Malfrador** [comment]
When the center of an entities bounding box is outside of the player's screen, the entire entity will not be rendered (culled). This is just client behaviour to optimise entity rendering. When you put an armor stand into the ground, the center of its bounding box will be low enough for it to not be rendered when looking straight ahead. 

You should use [display entities ](https://jd.papermc.io/paper/1.20.6/org/bukkit/entity/Display.html) instead. They are not culled by default, and culling can be configured with the [API ](https://jd.papermc.io/paper/1.20.6/org/bukkit/entity/Display.html#setDisplayHeight(float)) and offer plenty of other advantages over armor stands, including not having a hitbox at all.

**Comment by Ducki0210** [comment]
Ok ty
