### ISSUE TITLE
org.bukkit.Material class does not exist

### ISSUE THREAD

**Issue by DCMill** [PaperSpigot/Paper#10769]
### Expected behavior

I expected to see no problems with importing the class and I didn't find any evidence as to they had removed the class completely.

### Observed/Actual behavior

what I saw was that there was an error saying : cannot find symbol.
![image](https://github.com/PaperMC/Paper/assets/77583400/d486ccce-6ff2-4f1a-9b57-ede93998696f)

### Steps/models to reproduce

Here is my code: 
`package org.mukund.smp;

import org.bukkit.entity.LightningStrike;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;

public class EchestListener implements Listener {

    @EventHandler
    public void onInvClick(InventoryClickEvent event) {
        Inventory inv = event.getInventory();

        if (inv.getType() != ((Player)event.getWhoClicked()).getInventory().getType()) {
            if (event.getRawSlot() < inv.getSize()) {
                ItemStack holding = event.getCursor();

                if (holding.getType() == Material.DRAGON_EGG) {
                    Integer slot = event.getSlot();

                    event.setCancelled(true);
                    event.setCursor(holding);
                    inv.setItem(slot, inv.getItem(slot));
                }
            }else if (event.isShiftClick()) {
                ItemStack clicked = event.getCurrentItem();
                if (clicked.getType() == Material.DRAGON_EGG) {
                    Integer slot = event.getSlot();

                    event.setCancelled(true);
                    inv.setItem(slot, inv.getItem(slot));
                }
            }
        }
    }
}
` and the main file:
`package org.mukund.smp;

import org.bukkit.plugin.java.JavaPlugin;
import org.bukkit.Material;
public final class Smp extends JavaPlugin {

    @Override
    public void onEnable() {
        // Plugin startup logic
        getServer().getPluginManager().registerEvents(EchestListener,this);
    }

    @Override
    public void onDisable() {
        // Plugin shutdown logic
    }
}
`

### Plugin and Datapack List

No other plugins or datapacks

### Paper version

N/A It is not on the server yet.

**Comment by powercasgamer** [comment]
Make sure your IDE is updated and that you're using at least Java 21.

**Comment by DCMill** [comment]
> Make sure your IDE is updated and that you're using at least Java 21.

I have checked that already I am using the latest version of both, but I am using java 21

**Comment by powercasgamer** [comment]
> > Make sure your IDE is updated and that you're using at least Java 21.
> 
> I have checked that already I am using the latest version of both, but I am using java 21

What version of IntellIJ are you using? Also share your build scripts (pom.xml/build.gradle(.kts)) using a paste site such as https://pastes.dev
