### ISSUE TITLE
Cat In Minecart Doesn't Prevent Opening Chests

### ISSUE THREAD

**Issue by LockeShor** [PaperSpigot/Paper#10762]
### Expected behavior

When a cat riding in a minecart is placed ontop of a chest, players should be prevented from opening that chest.

### Observed/Actual behavior

The chest Is still able to be opened, however this behavior is somewhat inconsistent. Sometimes opening the chest IS blocked, but this appears to only happen part of the time.

### Steps/models to reproduce

- Summon a cat
- Tame the cat
- Put it in a minecart
- move that minecart on top of a chest
- chest is able to be opened

### Plugin and Datapack List

Plugins: Viabackwards, ViaVersion
Datapacks: Vanilla, Bukkit

### Paper version

This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)
You are running the latest version

**Comment by CodeByCam** [comment]
G'day LockeShor! 

It's standard [vanilla behaviour](https://minecraft.wiki/w/Cat#Tamed_Cat) that a chest cannot be opened if a cat is _sitting_ on the chest, you can open a chest if the cat is standing on the chest (whether in a minecart or not).

I have been unable to reproduce opening a chest whilst a cat is sitting on top of it (in a minecart or not). Are you able to provide a video of this happening, please? Also, make sure you are running no plugins (including ViaVersion/Backwards) when you test this again.

**Comment by LockeShor** [comment]
Sorry, I was testing a larger game mechanic and the issue appears to be with how cats are treated when their owner is offline. However, it's the same behavior as on vanilla, so there is not issue. Thanks for the response!
