### ISSUE TITLE
spawnChunkRadius gamerule keeps resetting after server restart (again)

### ISSUE THREAD

**Issue by PovilasLT** [PaperSpigot/Paper#10775]
### Expected behavior

1.20.5 introduced new gamerule spawnChunkRadius that can manage how many of spawn chunks should be always loaded. When setting to 0, no spawn chunks should be loaded. This was marked as fixed on issue #10622 but still happens in latest build.

### Observed/Actual behavior

Gamerule keeps resetting back to 2 after each server restart.

### Steps/models to reproduce

1. Set gamerule to different setting than 2 (i.e. `/execute in minecraft:overworld run gamerule spawnChunkRadius 0` or `/gamerule spawnChunkRadius 0`
2. Restart the server
3. Check gamerule - it resets back to 2 (i.e. `/execute in minecraft:overworld run gamerule spawnChunkRadius` or `/gamerule spawnChunkRadius`

### Plugin and Datapack List

[23:17:10 INFO]: Bukkit Plugins:
[23:17:10 INFO]:  - antiRedstoneClock, ChestShop, Citizens, ClearLag, CMI, CMILib, DeluxeMenus, DeluxeTags, DropEdit2, Duels
[23:17:10 INFO]:  Factions, FastAsyncWorldEdit, Funkcijos, IllegalStack, InteractionVisualizer, LiteBans, LuckPerms, Multiverse-Core, OldCombatMechanics, PilisV2
[23:17:10 INFO]:  PlaceholderAPI, PlugManX, PvPManager, pvpstats, Quests, RoyaleEconomy, Sargyba, Sentinel, ServerTutorialPlus, ShopGUIPlus
[23:17:10 INFO]:  ShopGUIPlus-SellGUI, spark, TAB, TokenManager, TradeMe, UltimateDrugs, UpgradeableSpawners, Vault, ViaBackwards
[23:17:10 INFO]:  ViaVersion, VillagerTradeLimiter, WorldGuard, WorldGuardExtraFlags

### Paper version

This server is running Paper version 1.20.6-90-master@b149584 (2024-05-22T17:30:13Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version

**Comment by Machine-Maker** [comment]
Can you pastebin all of your paper config files? The `config/paper-world-defaults.yml`, and all of the `paper-world.yml` files in the world folders. 

At the same time, try deleting those files (after backing them up) and seeing if it happens when the server re-generates the default values.

**Comment by PovilasLT** [comment]
Weird. It keeps jumping back to 2 for me:
![image](https://github.com/PaperMC/Paper/assets/16564979/2615f711-8cfd-4183-860c-f43f7c5c7c25)

paper-world-defaults.yml: https://pastebin.com/PGncH5pZ
All paper-world.ymls just has `_version: 31` setting.

**Comment by Machine-Maker** [comment]
I can't replicate this. I setup the config's just like you, started the game, changed it to 0, and upon a restart, it remained 2. I feel like this is now possibly a host issue? Some file isn't getting changed or something.

**Comment by CatBang** [comment]
This issue is likely caused by Multiverse-Core. Please consider uninstalling it. The keepSpawnInMemory configuration option in Multiverse-Core is forcibly set to true every time it loads. Previously, this could be suppressed by the keep-spawn-loaded: false option in Paper, but since Paper version 1.20.5 and above, this option has been removed, and the lingering issue with Multiverse-Core has re-emerged
