### ISSUE TITLE
Incorrect action on InventoryClickEvent

### ISSUE THREAD

**Issue by lexiccn** [PaperSpigot/Paper#10771]
### Expected behavior

When swapping two items between an inventory ("clicked" slot) and hotbar (either by pressing hotbar key 1-9 or offhand key), `InventoryClickEvent#getAction` should give action `HOTBAR_SWAP` according to the documentation.

I am unsure if this is a case where the documentation is incorrect (behaviour has always been this way) or the outcome is incorrect (documentation was correct in previous versions).

I am also unsure if this is the case on Spigot or CraftBukkit as my plugins are designed only for Paper currently.

### Observed/Actual behavior

When both slots (hotbar and inventory slot clicked) have items in them, the action returned is `HOTBAR_MOVE_AND_READD` despite the actual behaviour being to swap the stacks.

When one slot is empty, the action returned is `HOTBAR_SWAP` which is correct.

When both slots are empty, the action returned is `NOTHING` which is correct.

### Steps/models to reproduce

Listen for InventoryClickEvent
Swap items between offhand and any inventory, or hotbar and any inventory, using the appropriate methods
Event#getAction returns the incorrect action (according to documentation)

This is tested in Survival mode. In Creative mode, there are further issues with it (returning PLACE_ALL, etc.) but this is due to (I assume unsupported) Creative mode issues.

### Plugin and Datapack List

No datapacks.

Plugins:
- AutoBrewers (plugin designed by me - this was tested by listening to InventoryClickEvent with no other function than to print the action)

### Paper version

This server is running Paper version 1.20.6-86-master@9bf4855 (2024-05-20T18:22:30Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)

### Other

Tested in Player Inventory, Chest Inventory, Custom Inventory (Chest type), Brewing Stand inventory

**Comment by Machine-Maker** [comment]
I'm not able to replicate this. Here is the setup I have. 
![image](https://github.com/PaperMC/Paper/assets/15055071/0b3d0d73-611d-4a83-9340-9a6b7c7c3306)
If I press `2` while the screen is as such (my cursor is over the logs), the action I get is `HOTBAR_SWAP`.

Are you using the vanilla client?

**Comment by Machine-Maker** [comment]
Ok, confirmed. Here is the bit of code that causes this. 
![image](https://github.com/PaperMC/Paper/assets/15055071/12013b8b-a4d5-4764-a6d6-9bf006ae8178)
This is all it does to determine if its a HOTBAR_SWAP or HOTBAR_MOVE_AND_READD. And you can see right there the check that the `clickedSlot`'s container is the same as the player's inventory. Which will fail for swaps to inventories outside the player's inventory.

**Comment by Machine-Maker** [comment]
WOW, so yeah, this is actually how it used to work. I loaded up a 1.6.4 singleplayer world, and tried swapping between my hotbar and a chest inventory. I hovered over the item in the chest's inventory, and pressed a hotbar slot, and it *doesn't* swap the items. It puts the item in the requested hotbar slot, but then just *readds* the item that was in the hotbar slot to the player's inventory.
