### ISSUE TITLE
Can't

### ISSUE THREAD

**Issue by Blizzmond** [PaperSpigot/Paper#10791]
### Expected behavior

Only the /teleport command works in the world you are in

### Observed/Actual behavior

Any type of plugin teleportation does not work

### Steps/models to reproduce

Unsure

### Plugin and Datapack List

<img width="506" alt="image" src="https://github.com/PaperMC/Paper/assets/68831580/31a156a1-e7c4-4edd-9968-03a3089a8d7d">

### Paper version

This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)
You are running the latest version

### Other

Whats the cause of this? I have disabled end and nether, I also tried disabling``disable-teleportation-suffocation-check: true``

**Comment by lynxplay** [comment]
We'd have to have this replicated without plugins installed as they might be messing with teleportation.
We cannot comment or offer support for third party plugins as we do not know what they change/run.
