### ISSUE TITLE
Server shuts down on startup

### ISSUE THREAD

**Issue by xKumorio** [PaperSpigot/Paper#10790]
фцвфцвцфвфцв

**Comment by xKumorio** [comment]
crash report https://paste.gg/p/anonymous/8e0fa9b3ae8f4ecb8dcf990281d9cf96

**Comment by xKumorio** [comment]
Server works fine on vanila server jar

**Comment by Warriorrrr** [comment]
What's the value of your spawnChunkRadius gamerule? It seems like it may be set above the maximum

**Comment by xKumorio** [comment]
> What's the value of your spawnChunkRadius gamerule? It seems like it may be set above the maximum

spawnChunkRadius: 64

**Comment by xKumorio** [comment]
Yes I changed the nbt spawnChunkRadius and that solved the problem

**Comment by Warriorrrr** [comment]
The maximum value is 32, as long as you keep it at that you won't have any issues
