### ISSUE TITLE
/minecraft:tp accepts no arguments

### ISSUE THREAD

**Issue by JasonHorkles** [PaperSpigot/Paper#10815]
### Expected behavior

`/minecraft:tp` should function the same as the regular `/tp`, `/teleport`, and `/minecraft:teleport` commands

### Observed/Actual behavior

The command doesn't allow any arguments

### Steps/models to reproduce

Type `/minecraft:tp` with any args after and see that it doesn't work

### Plugin and Datapack List

![image](https://github.com/PaperMC/Paper/assets/51760372/addf5d1e-cb3a-415a-876f-8ea328d711ee)

### Paper version

This server is running Paper version 1.20.6-115-master@9d6f2cc (2024-05-28T14:55:16Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-49 (MC: 1.20.6)

### Other

Doesn't happen in Spigot or further upstream and only started in 1.20.6 AFAIK

**Comment by CodeByCam** [comment]
Hey JasonHorkles, cheers for making this issue. I can reproduce this.

**Vanilla 1.20.6:**
`/teleport @s 100 100 100` and `/tp @s 100 100 100` work as intended.

**Paper 1.20.4 (build 496):**
- `/teleport @s 100 100 100` and `/tp @s 100 100 100` work as intended.
- `/minecraft:teleport @s 100 100 100` and `/minecraft:tp @s 100 100 100` work as intended.

**Paper 1.20.6 (build 115):**
- `/teleport @s 100 100 100` and `/tp @s 100 100 100` work as intended.
- `/minecraft:teleport @s 100 100 100` works as intended and `/minecraft:tp @s 100 100 100` **doesn't** work/accept arguments. The latter also doesn't provide any tab completable options like the former but still shows as a registered command:

![nxJ6Wha](https://github.com/PaperMC/Paper/assets/41496198/5c4957d6-09bc-4b00-9a52-38dc09698dcc)
![ecdlskQ](https://github.com/PaperMC/Paper/assets/41496198/5c88631f-8af4-4c7e-bc6d-70fcbcd2ec51)

**Comment by xaanndeer** [comment]
This seems to be an issue with all command aliases. Command `/msg` works fine until you use a namespaced alias like `/minecraft:tell`.

My suspicion is that the logic behind `LiteralArgumentBuilder.redirect(CommandNode)` isn't working as intended. This would also explain why my alternative in https://github.com/PaperMC/Paper/discussions/10809 isn't working as expected.
