### ISSUE TITLE
Player list name with wrong colors when using Kyori's components

### ISSUE THREAD

**Issue by Elikill58** [PaperSpigot/Paper#10830]
### Expected behavior

See this in player list name :
<img width="305" alt="image" src="https://github.com/PaperMC/Paper/assets/17381066/8f2ea13f-77bf-48f2-8067-c8ab522500e1">

### Observed/Actual behavior

When using `§x` color code (full string: `§x§f§f§0§0§0§0§x§f§f§0§0§0§0§lFONDATEUR§r §8▏ §x§f§f§0§0§0§0Elikill58`) :
<img width="315" alt="image" src="https://github.com/PaperMC/Paper/assets/17381066/85dd80e8-f85d-4a81-b9f6-91a2f6fec906">

When using `&#` (full string: `&#ff0000&#ff0000§lFONDATEUR§r §8▏ &#ff0000Elikill58`) :
<img width="580" alt="image" src="https://github.com/PaperMC/Paper/assets/17381066/682e111c-45b3-462a-8565-bd7b23ba0efc">

### Steps/models to reproduce

Use this string : `&#ff0000&#ff0000§lFONDATEUR§r §8▏ &#ff0000Elikill58` or `§x§f§f§0§0§0§0§x§f§f§0§0§0§0§lFONDATEUR§r §8▏ §x§f§f§0§0§0§0Elikill58`.
By using `player.setPlayerListName(name)` it's working, but with `player.playerListName(name)` I get the result showed before. I tried `player.playerListName(Component.text(name))` or `player.player.playerListName(PlainTextComponentSerializer.plainText().deserialize(name))` but both show same result.

### Plugin and Datapack List

My own, and no datapack

### Paper version

This server is running Paper version 1.20.6-124-master@0fcf3e3 (2024-05-29T22:05:27Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-393 (MC: 1.20.4)

### Other

I didn't check on older version than 1.20.6

**Comment by Machine-Maker** [comment]
the `playerListName(Component)` methods don't take a string. It's not supported behavior to put legacy color codes *inside* of a component. If you want to use legacy, not good, super old, lossy string format like the legacy color codes, you have to use the `LegacyComponentSerializer` and deserialize the string from there into a component.

**Comment by electronicboy** [comment]
by stuffing that stuff into a component, you're just relying on the vanilla text renderer, which does not support any of the community-derived hacks for RGB compatibility in legacy strings, and so it's just using the last text color you apply, as that's all it understands

**Comment by Elikill58** [comment]
> the `playerListName(Component)` methods don't take a string. It's not supported behavior to put legacy color codes _inside_ of a component. If you want to use legacy, not good, super old, lossy string format like the legacy color codes, you have to use the `LegacyComponentSerializer` and deserialize the string from there into a component.

Oh yes, I tested with wrong Serializer. I tested with Legacy one, and it's fixed thanks :)
