### ISSUE TITLE
NoSuchMethodError: org.bukkit.entity.Fireball.getAcceleration()

### ISSUE THREAD

**Issue by uprial** [PaperSpigot/Paper#10850]
### Expected behavior

The method from Spigot 1.20.6 exists according to the docs: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Fireball.html and is compatible with Paper 1.20.6

### Observed/Actual behavior

Server error:
java.lang.NoSuchMethodError: 'org.bukkit.util.Vector org.bukkit.entity.Fireball.getAcceleration()'

### Steps/models to reproduce

Run a server on the latest version of Paper: paper-1.20.6-130.jar

### Plugin and Datapack List

Reproducible on a bare installation of paper-1.20.6-130.jar

### Paper version

paper-1.20.6-130.jar

**Comment by Machine-Maker** [comment]
We haven't updated from upstream yet. However, Paper already exposed the fireballs acceleration (under the name Power), so you can just use that until we update from upstream.
