### ISSUE TITLE
Wandering trader causing server to crash

### ISSUE THREAD

**Issue by lands39** [PaperSpigot/Paper#10853]
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
https://paste.gg/p/anonymous/f5812767a5164748bb4d58397006bc78

https://paste.gg/p/anonymous/3109279d76b6486f9fc1102d646476b1

### Plugin and Datapack List

DeathMessages, eBackup

### Actions to reproduce (if known)

Unknown, this seems to happen at random in completely different parts of the map but it is consistently triggered by net.minecraft.world.entity.npc.EntityVillagerTrader

### Paper version

This server is running Paper version git-Paper-17 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: c287e92)
You are running the latest version

### Other

This has happened 3 times now; once last night before a regularly scheduled backup, once after i restarted the server so people could get on and just now while running /plugins and /version.

**Comment by Machine-Maker** [comment]
1.20 is super duper outdated and unsupported. Please update to a supported version in 1.20.4 or 1.20.6.

**Comment by lands39** [comment]
we're running 1.20 as this is before villager trades were nerfed and the general consensus is that everyone wanted 1.20. we will not be updating and would like a solution to this problem as its a recurring issue preventing people from playing.

**Comment by kennytv** [comment]
You mean the optional trade rebalance? That was added in 1.20.2 and is not part of the game by default. In any case, you're on your own on such an old version

**Comment by lands39** [comment]
1.20 isn't old, what about the major servers that still run 1.12.2? do you just, not support those servers? i'm not taking no as an answer.

**Comment by lynxplay** [comment]
Indeed, we are also not offering support to 1.12.2 servers!
This is a project ran by volunteers in their free time, maintaining more than one (maybe two versions) at the same time is not possible :+1:

**Comment by kennytv** [comment]
There's no reason not to update because the thing you're trying to avoid isn't actually a thing

**Comment by lands39** [comment]
in that case i'll go use server software wrote by people who will actually provide support, those from spigot said papermc was unstable on 1.20 anyways. if your software isn't stable and you choose not to support it, i will not be a user of this software and will take my business elsewhere.
