### ISSUE TITLE
Chat message validation failure

### ISSUE THREAD

**Issue by SamanthaWolf1315** [PaperSpigot/Paper#10868]
### Expected behavior

Not kicking you when u try to chat in the chat while in vanish sometimes

### Observed/Actual behavior

Kicking people while in vanish sometimes when trying to chat in the chat

### Steps/models to reproduce

install essentials x on ur server

go in vanish

try type in chat

it may only happen on modded clients not sure

### Plugin and Datapack List

![Screenshot 2024-06-11 163402](https://github.com/PaperMC/Paper/assets/79915432/5b5429b8-96d7-40af-a259-4ab6e809fc38)

![image](https://github.com/PaperMC/Paper/assets/79915432/0b24d373-2ef9-4c81-a037-9206f0d188e3)

### Paper version

![image](https://github.com/PaperMC/Paper/assets/79915432/113bf5e8-c052-489a-bc48-0e0a9dca1aaf)

### Other

this issue is very annoying it keeps happening to me and my friends on my server minecraft version is 1.20.6 never happened when we were running 1.20.4

**Comment by lynxplay** [comment]
I cannot replicate this with [latest EssentialsX](https://github.com/EssentialsX/Essentials/commit/3a6fdd9bf30463f68ba819f7583204ff963eb36c) and simply chatting while in vanish. Both the vanished account and the non vanished one remain on the server.

Can you provide any other replication steps? Maybe a smaller set of plugins on your end?
We cannot really do anything on paper when large plugins are involved and we don't have replication steps.

**Comment by SamanthaWolf1315** [comment]
I think this is only happening with people with modded clients as onw of my friends tested it on vanilla and it didnt kick them

**Comment by lynxplay** [comment]
Then that would be up to the modded clients to resolve, not paper.
I'll be closing this then, if you find an issue with the vanilla client and/or have more info, feel free to post them here and we can reopen this.
