### ISSUE TITLE
Option to disable stop sprint on attack doesn't fully works

### ISSUE THREAD

**Issue by Elikill58** [PaperSpigot/Paper#10870]
### Expected behavior

Don't lose the sprint when attack someone

### Observed/Actual behavior

Video that show the issue :
- https://youtu.be/nRIIGdGb5nE
- https://youtu.be/DTZHj8AqCAY
Note: the user on the video has the toggle sprint option activated

### Steps/models to reproduce

Set `disable-sprint-interruption-on-attack` to true, restart then attack someone

### Plugin and Datapack List

- no datapack
- one plugin: my own that manage permissions, messages etc but doesn't change pvp

### Paper version

This server is running Paper version 1.20.6-138-master@906df69 (2024-06-10T06:32:15Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.20.6-115-9d6f2cc (MC: 1.20.6)

**Comment by SamB440** [comment]
The actual sprinting interruption is client-side and a part of horizontal attack slowdown, that setting only affects the attribute I believe.

**Comment by Elikill58** [comment]
> The actual sprinting interruption is client-side and a part of horizontal attack slowdown, that setting only affects the attribute I believe.

So it cannot be fixed ?

**Comment by lynxplay** [comment]
I cannot really replicate this on a vanilla client. This is what I reproduce:

Config option set to false:
  Sprint: Hold + Press W twice + Attack: Stop sprinting
  Sprint: Hold + Press sprint key + Attack: Stop sprinting
  Sprint: Hold + Hold sprint key + Attack: Stop sprinting but start sprinting quickly after
  Sprint: Toggle + Press W twice + Attack: Stop sprinting
  Sprint: Toggle + Press sprint key once + Attack: Stop sprinting but start sprinting quickly after
Config option set to true:
   Sprint: Hold + Press W twice + Attack: Keep sprinting
  Sprint Hold + Press sprint key + Attack: Keep sprinting
  
I don't see how that is not what you'd expect this configuration option to do?

**Comment by lynxplay** [comment]
Yea, after digging through a bunch of client code, the issue was that I unfortunately tested this on a normal entity, not a player.

For some reason, the client implementation considers a RemotePlayer to always be "hurt" by an attack, when it does not do so for normal LivingEntitys.

Why that is the case, I have 0 idea. The option works for everything but players thanks to this somewhat shitty mechanic and there is nothing paper can do about it sadly.
I am unsure if this is even reportable to mojang, we should however 100% mention this in the docs.

**Comment by SamB440** [comment]
The sprint attacking stuff is basically https://bugs.mojang.com/browse/MC-69459

**Comment by lynxplay** [comment]
Mhm, yea I'll sadly have to close this as there isn't anything paper can do here.
Lets hope mojang fixes that or a mod exists to patch this.
