### ISSUE TITLE
Spawn player does not receive the effects update the regain their movement speed

### ISSUE THREAD

**Issue by RanMinecraft** [PaperSpigot/Paper#10907]
### Expected behavior

respawn player should not have any potion effects

### Observed/Actual behavior

spawn player does not receive the potion effects update the regain their movement speed
and drinking milk doesn't remove slow effects from the player.

### Steps/models to reproduce

player.addPotionEffect(new PotionEffect(PotionEffectType.SLOWNESS, 80, 5, true));
then /kill player 

### Plugin and Datapack List

testplugin

### Paper version

Paper-1.21-4

### Other

https://github.com/PaperMC/Paper/assets/69817107/a2a97edf-cf1e-4d91-b0fd-4922448c6050

**Comment by lynxplay** [comment]
Replicable as in "when dying, the player does not receive the attribtue update the regain their movement speed

**Comment by Budderman18** [comment]
this seems to effect other potion effects too, dying with strength makes it so you cant attack anything without at least a stone sword

**Comment by Malfrador** [comment]
Until this is fixed either by Paper or upstream, I have made a simple [plugin] (https://hangar.papermc.io/Malfrador/ResetAttributesOnDeath) to work around the issue.

**Comment by Doc94** [comment]
Well this not happen in upstream for what i check.
In upstream this seems to fix the issue https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/cdd05bc7faac70a5341ce9cd6524ac2ed0a80651#nms-patches%2Fnet%2Fminecraft%2Fworld%2Fentity%2FEntityLiving.patch but just for future effects if you still has a effect use this and die the effect its not removed unless you give the same effect again.

**Comment by electronicboy** [comment]
Yes, we're pending an upstream merge
