### ISSUE TITLE
Minecarts above set speed or velocity freeze until pushed

### ISSUE THREAD

**Issue by miroslav-pavlov** [PaperSpigot/Paper#10912]
### Expected behavior

Minecarts with players or chests move for more than 5 blocks

### Observed/Actual behavior

Minecarts with players or chests freeze after gaining set momentum until pushed by a player.

### Steps/models to reproduce

1. Create a Paper 1.21-6 server
2. Add and enable the data pack
3. Ignore the error message about an invalid recipe
4. Try using a minecart with a player or chest

### Plugin and Datapack List

Datapack: [Modified Darceno's minecarts](https://www.mediafire.com/file/uzkozyuvrns3quq/darcenos-minecarts-1.3-mirkris-fix-for-v1.21.zip/file) to work for 1.21
([Original datapack](https://modrinth.com/datapack/darcenos-minecarts))

### Paper version

This server is running Paper version 1.21-6-master@126f6d7 (2024-06-18T20:03:56Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version

**Comment by Malfrador** [comment]
I am able to reproduce this. For context, the datapack seems to teleport the minecart once a certain speed is reached:
```
execute as @s[scores={VanillaPlusCartsXSpeed=50..}] at @s if block ~1 ~ ~ #minecraft:rails[shape=east_west] run tp @s ~1 ~ ~
execute as @s[scores={VanillaPlusCartsXSpeed=..-50}] at @s if block ~-1 ~ ~ #minecraft:rails[shape=east_west] run tp @s ~-1 ~ ~
execute as @s[scores={VanillaPlusCartsZSpeed=50..}] at @s if block ~ ~ ~1 #minecraft:rails[shape=north_south] run tp @s ~ ~ ~1
execute as @s[scores={VanillaPlusCartsZSpeed=..-50}] at @s if block ~ ~ ~-1 #minecraft:rails[shape=north_south] run tp @s ~ ~ ~-1
```
This seems to cause the minecart to get stuck, not only loosing velocity but you are also unable to move it forward by pressing W until exiting and re-entering the minecart.
In vanilla the minecart continues moving just fine. 

The datapack also forceloads chunks with minecarts travelling through them which seems like a really bad idea. Datapacks that use functions like this one are in general not very performant. if you just want speed up Minecarts, it might be better to use a plugin like TrainCarts for this purpose.
