### ISSUE TITLE
Datapack logical world height properties ignored

### ISSUE THREAD

**Issue by BehrRiley** [PaperSpigot/Paper#10920]
### Expected behavior

World height increased from 384 to 448.

### Observed/Actual behavior

logical world height increase is ignored and is stuck at 384.

### Steps/models to reproduce

place a datapack with the file placed within `datapack_name\data\minecraft\dimension_type\overworld.json` with the properties `height` and `logical_height` changed in increments of 64:
```json
{
  "ambient_light": 0.25,
  "bed_works": true,
  "coordinate_scale": 1.0,
  "effects": "minecraft:overworld",
  "has_ceiling": false,
  "has_raids": true,
  "has_skylight": true,
  "height": 512,
  "infiniburn": "#minecraft:infiniburn_overworld",
  "logical_height": 512,
  "min_y": -64,
  "monster_spawn_block_light_limit": 0,
  "monster_spawn_light_level": {
    "type": "minecraft:uniform",
    "max_inclusive": 7,
    "min_inclusive": 0
  },
  "natural": true,
  "piglin_safe": false,
  "respawn_anchor_works": false,
  "ultrawarm": false
}
```
optionally, can change this for overworld_caves, the_end, and nether; results do not change

### Plugin and Datapack List

no plugins, only basic datapack with the one file listed above.

### Paper version

This server is running Paper version 1.21-9-master@4ea696f (2024-06-19T04:26:57Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-6-126f6d7 (MC: 1.21)

### Other

this pack feature works in 1.20.4, does not work in either 1.20.6 or 1.21 paper or spigot.
this pack feature works as expected in both singleplayer worlds and the vanilla multiplayer server versions for both 1.20.6 and 1.21.

**Comment by Malfrador** [comment]
I am unable to reproduce this with the overworld.json provided. I can build up to 448 just fine.

Make sure the datapack is in the correct place. It needs to be placed in the `datapacks` folder of your _main_ world. This will be "world" by default, or whatever you configured in server.properties as `level-name`. Datapacks in other worlds will not be loaded.

**Comment by BehrRiley** [comment]
i just started up with build 11 and it appears to just... work, now. i reformatted everything so i must have had something misplaced or something. thanks
