### ISSUE TITLE
Lava/water bucket, boats not work

### ISSUE THREAD

**Issue by TsuckermanDev** [PaperSpigot/Paper#10926]
### Expected behavior

These items cannot be used, lava cannot be placed, the boat does not appear

### Observed/Actual behavior

.

### Steps/models to reproduce

Trying to use one of these items

### Plugin and Datapack List

[00:33:01 INFO]: Bukkit Plugins: (9):
[00:33:01 INFO]:  - Chunky, Geyser-Spigot, HardAPI, Multiverse-Core, spark, Vault, ViaBackwards, ViaVersion, WorldEdit
(none of this conflicts)

### Paper version

1.21-15-master@2df432f (2024-06-19T19:19:30Z)

**Comment by lynxplay** [comment]
Cannot replicate, pls try to replicate this without plugins.

**Comment by TsuckermanDev** [comment]
oh sorry... The plugin is really to blame, thanks for the feedback
