### ISSUE TITLE
Failed to handle packet ServerboundSelectKnownPacks[knownPacks=[minecraft:core:1.21]], suppressing error java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by doggoleader** [PaperSpigot/Paper#10924]
### Expected behavior

It should let player to join server

### Observed/Actual behavior

It prevents player from joining server, showing the infinite "Logging to the server" on the client screen

### Steps/models to reproduce

Load server and try to join it and you see the error in the console

### Plugin and Datapack List

FastAsyncWorldEdit, WorldEdit, WorldGuard, my custom plugin (updated to 1.21 and not shown on stacktrace)

### Paper version

1.21 build(s) 4, 9, 14

### Other

Console stack trace: https://pastebin.com/LGeHgwjQ

**Comment by Machine-Maker** [comment]
In all likely hood, it's a problem with your custom plugin. Without knowing anything about what it does, I'm guessing to are adding stuff to registries incorrectly.

**Comment by doggoleader** [comment]
Hello! As for now, my custom plugin doesn't add any registries. Moreover, if you see the stack trace, there's no mention of any plugin besides paper core. But I'll try to start it without plugins tomorrow (I can't do it right now) and will let you know later

**Comment by doggoleader** [comment]
Well, seems like you are right that it's my plugin issue. However I don't really understand where's this issue happens as I haven't added anything new to the plugin when migrating from 1.20.4 to 1.21.

**Comment by lynxplay** [comment]
Feel free to ask in our [discord](https://discord.gg/papermc) :+1: 
Closing as a non paper issue then.
