### ISSUE TITLE
1.21: Effects disappear instantly

### ISSUE THREAD

**Issue by Kimiblock** [PaperSpigot/Paper#10946]
### Expected behavior

Effects obtained from e.g. enchanted golden apples should not immediately disappear

### Observed/Actual behavior

Effects disappear within a second

### Steps/models to reproduce

Build #21 (or previous builds) of Paper.

Eat an enchanted golden apple.

https://github.com/PaperMC/Paper/assets/61745317/9176e8ff-73d7-4230-afa0-8b34f7ce275a

### Plugin and Datapack List

Plugins:

- HuskHomes
- DeluxeMenus
- GriefPrevention
- LuckPerms
- Multiverse-Core
- NoCheatPlus
- PlaceholderAPI
- PlayerStats
- Vault
- WorldEdit

Datapacks:

- vanilla
- file/bukkit
- paper

### Paper version

This server is running Paper version 1.21-21-master@0a1b133 (2024-06-21T09:19:07Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-15-2df432f (MC: 1.21)

### Other

Nothing appears in logs. Running under Arch Linux, systemd service
```[tasklist]
### Tasks
```

**Comment by Malfrador** [comment]
I am unable to replicate this. Effects are being correctly applied when eating an golden apple (or using other items that give effects).

Closing this, as it is very likely a plugin issue. Make sure all of them are up-to-date for 1.21. Feel free to use the [Paper Discord](https://discord.gg/papermc) for further help.
If anyone is able to replicate this _without any plugins_ feel free to reply so the issue can be reopened.
