### ISSUE TITLE
Some Chunks not saving / reverting

### ISSUE THREAD

**Issue by Shaf106** [PaperSpigot/Paper#10942]
### Expected behavior

When I stop the server, all chunks should be saved

### Observed/Actual behavior

Some seemingly random chunks are not being saved correctly

### Steps/models to reproduce

edit multiple different chunks, save or stop server, reboot, some chunks should be left unchanged whilst others will be changed

### Plugin and Datapack List

DiscordSRV, Floodgate, Geyser-Spigot, SkinsRestorer
Vanilla (built-in), file/bukkit (world), paper (built-in)

### Paper version

Paper version 1.21-1-master@21c9a7c (also warns me for being 19 versions behind)

### Other

Pretty sure there was the same issue for the latest release of paper (not alpha)

**Comment by electronicboy** [comment]
You're using unstable builds, you should be updated frequently. This should have already been resolved in the past few builds.
