### ISSUE TITLE
Bukkit.getOfflinePlayer(uuid).getName() returns UUID instead of player name

### ISSUE THREAD

**Issue by ImOlli** [PaperSpigot/Paper#10954]
### Expected behavior

The Method getName() of an offline player should return their name not the uuid

### Observed/Actual behavior

The Method getName() returns the uuid as string

### Steps/models to reproduce

Create a plugin that calls Bukkit.getOfflinePlayer(uuid).getName()

### Plugin and Datapack List

Only the Plugin that calls Bukkit.getOfflinePlayer(uuid).getName() 

### Paper version

[13:25:23 INFO]: Checking version, please wait...
[13:25:23 INFO]: This server is running Paper version 1.21-25-master@19105a9 (2024-06-21T19:03:48Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version

**Comment by NoahvdAa** [comment]
Can't reproduce on [62ed302](https://github.com/PaperMC/Paper/commit/62ed302bf400a21b601bdb9382325eab31612f32):
```java
// Player that has joined before logs "NoahvdAa"
this.getLogger().info(Bukkit.getOfflinePlayer(UUID.fromString("7c4538b6-fa95-4bb5-982f-f42ba206d4f5")).getName());
// Player that hasn't joined before logs null
this.getLogger().info(Bukkit.getOfflinePlayer(UUID.fromString("436fdbb2-81d2-4e8b-aaed-75ab6058f77e")).getName());
```
Can you still reproduce this and if so, what do your config files and code look like?

**Comment by ImOlli** [comment]
@NoahvdAa 
I found my mistake, I accidentally called getOfflinePlayer() with the UUID as string.

So my plugin hat the following (wrong) code:
```java
Bukkit.getOfflinePlayer("a258b060-3096-48ce-81a7-80f94fe2fe58").getName()
```

I will close this issue. Thank you!
