### ISSUE TITLE
Exception log messages in bootstrap are dropped

### ISSUE THREAD

**Issue by Doc94** [PaperSpigot/Paper#10953]
### Expected behavior

If you make changes using the plugin bootstrap feature and cause a exception this messages are printed in logs

### Observed/Actual behavior

When you cause a exception in bootstrap that messages are not show and confuse users because the most of this throws cause the server to stop

### Steps/models to reproduce

You can use this plugin https://github.com/Doc94/PaperTestRegistryReflectionEnchantment where register a Enchantment but not use all the mandatory fields in builder causing Registry throws a exception

### Plugin and Datapack List

PaperTestRegistryReflectionEnchantment

### Paper version

[22:31:18 INFO]: Checking version, please wait...
[22:31:18 INFO]: This server is running Paper version 1.21-25-master@19105a9 (2024-06-21T19:03:48Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-19-2118196 (MC: 1.21)

### Other

This was talked in [discord](https://canary.discord.com/channels/289587909051416579/555462289851940864/1253394576694181888) and a fix comes from https://github.com/PaperMC/Paper/commit/2118196dd57f9b7100b2d15b552d3c00fc5a55fa but was reverted in https://github.com/PaperMC/Paper/commit/0a1b133c28bfa9b71cd23a10b42b521ad50aacb5 because that fix cause another issue

**Comment by lynxplay** [comment]
Resolved by https://github.com/PaperMC/Paper/pull/11172
