### ISSUE TITLE
Cats going invisible after teleporting to player

### ISSUE THREAD

**Issue by Seeloewen** [PaperSpigot/Paper#10965]
### Expected behavior

Cats should always be visible when teleporting to the player.

### Observed/Actual behavior

I noticed that sometimes, especially when teleporting across longer distances, cats are going invisible. You can still hear their steps and meows though.

https://github.com/PaperMC/Paper/assets/74246933/62fd2451-4714-41ef-b83f-33d98189637d

Video is taken after travelling several hundred blocks with an elytra while having 2 tamed cats. Before beginning the travel, they were visible. If you enable sound, you can hear the cats. This video was taken on Paper 1.21-49. Also had to scale the video down to 480p because it was a bit too large for GitHub.

https://github.com/PaperMC/Paper/assets/74246933/879f6ee7-5957-4bf2-a442-d38f9a4d44cc

Another video showing how relogging makes them appear again. Sorry for the quality, once again massively downscaled.

### Steps/models to reproduce

Unfortunately, this issue seems to be very inconsistent, but it seems to happen more often the greater the distance. Simply tame a cat, make it follow you and fly longer distances with an elytra or in creative. Sometimes, the cat will teleport to you and is visible and in some occations you will hear the steps and meows of the cat, but you don't actually see it. I made sure it wasn't in caves or anything, it's really invisible.

### Plugin and Datapack List

**Plugins:** Harbor (https://github.com/nkomarn/harbor) 
**Datapacks:** None
**Also tested without plugins, still an issue**

### Paper version

[16:26:03 INFO]: This server is running Paper version 1.21-27-master@76c2f16 (2024-06-22T18:19:36Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21-25-19105a9 (MC: 1.21)

**Update:** Still an issue as of 1.21-49.

### Other

I also tried the issue with different game clients including vanilla, doesn't change the outcome. Since it's an online host I am unable to manually update to the newest version of paper, that's why I'm one version behind.

**Comment by JasonHorkles** [comment]
I've noticed this issue with dogs as well. Not sure what the exact cause is since it's also random for me but rejoining the server often helps.

**Comment by Seeloewen** [comment]
> I've noticed this issue with dogs as well. Not sure what the exact cause is since it's also random for me but rejoining the server often helps.

Albright, thank you for confirming that the issue actually exists and I'm not just going insane. Do you have any idea if there's another workaround than just leaving? Reconnecting is inconvenient and takes some time on my server.

**Comment by JasonHorkles** [comment]
None that I've found so far

**Comment by nuttapillar** [comment]
The other day I could hear a dog barking next to me, but couldn't see it. I assume I had the same issue.

**Comment by deltaspirit1** [comment]
Im trying to build a creeper farm but I cant because my cats wont teleport to me. I cant even hear them.

**Comment by JasonHorkles** [comment]
Seems like a different issue

**Comment by Tsoccerguy3** [comment]
First to narrow the scope of this , turn on Hit-boxes to see if the entities are there and not phantom sounds from lag. No Hit-boxes , then no entities.

Hitboxes are regions that describe how much space an entity takes up, which can be shown by pressing the F3 + B keys. ‌ [Java Edition only] When they are shown, a white outline will be seen showing the location of the entity and the space it takes up.

**Comment by Seeloewen** [comment]
> First to narrow the scope of this , turn on Hit-boxes to see if the entities are there and not phantom sounds from lag. No Hit-boxes , then no entities.
> 
> Hitboxes are regions that describe how much space an entity takes up, which can be shown by pressing the F3 + B keys. ‌ [Java Edition only] When they are shown, a white outline will be seen showing the location of the entity and the space it takes up.

Just checked, no hitboxes are visible but I still here the sounds of the cats. I'll attach a video in the root of this thread.

**Comment by JasonHorkles** [comment]
When I had the issue with the dogs you could hear them right next to you and when you relogged then they would be right next to you

**Comment by Seeloewen** [comment]
> I tested and found the cat had fallen though ground or floor of builds but was nearby. upto 1 to 2 chunks away in cave or fallen though blocks. . Must be a setting to keep pets closer to you. Anyway they are there just not close to you

The cats are definitely still there. Relogging makes them appear again and they're right next to me. You can also hear the steps and meows very close to you. I've attached yet another video in the top message showing this behaviour.

**Comment by Tsoccerguy3** [comment]
I just stayed on and warped to a different place and the cat caught up. I did see the tag underground stuck in blocks .If a player teleports into solid rock, the command is //unstuck. The cat is teleporting into blocks sometimes. This is a bug getting the co-ord's wrong .  pretty sure

**Comment by JasonHorkles** [comment]
> I just stayed on and warped to a different place and the cat caught up. I did see the tag underground stuck in blocks .If a player teleports into solid rock, the command is //unstuck. The cat is teleporting into blocks sometimes. This is a bug getting the co-ord's wrong . pretty sure

That's a worldedit cmd m8

**Comment by JasonHorkles** [comment]
If you really want to eliminate the possibility that the coordinates are wrong, you can run `/tp @n[type=cat]`, but I'm pretty sure it's just not rendering for some reason

**Comment by Seeloewen** [comment]
> If you really want to eliminate the possibility that the coordinates are wrong, you can run `/tp @n[type=cat]`, but I'm pretty sure it's just not rendering for some reason

Running this command teleports me to the location where I heard the cat meow, which is usually close to me. Still, the cat is not visible.

**Comment by andrewkm** [comment]
I've experienced this on my end as well, just in a slightly different way. But definitely something wonky going on for long distances.

**Comment by Tsoccerguy3** [comment]
I created a block platform 4 x 4 , 1 block thick in the sky. /tp to that platform to get the cat to follow. I can hear the cat, but can not see it, so i begin placing blocks around the edge, 3 high and spiral inward placing blocks, until i found a spot where i could not place a block. The ghost cat is now in a hole 3 block deep. It has no hit-box or tag, but cries out when anvils are dropped in the hole. The cat is having a out of body experience , Its A.I is there but not its Physical hit-box or tag . This is reproducible and may effect other entities. I did not need to log off, just move from place to place and it soon caught up in its rendered form.

**Comment by Tsoccerguy3** [comment]
Kenny, This build 55 fixed the invisible cat other entities , but made all Citizens2 NPC's invisible. Not sure how to fix this . Anyway, rolling back to build 50 made NPC's visable again.

**Comment by andrewkm** [comment]
> Kenny, This build 55 fixed the invisible cat other entities , but made all Citizens2 NPC's invisible. Not sure how to fix this . Anyway, rolling back to build 50 made NPC's visable again.

Here on the other hand, it fixed every single issue we've had.
Perhaps report this to Citizens2. Don't just roll this fix back.
