### ISSUE TITLE
Could not create world config for world_nether

### ISSUE THREAD

**Issue by tonceDev** [PaperSpigot/Paper#10977]
### Stack trace

```
https://paste.gg/p/anonymous/55a25eca07ee43e788a91e0d4e253dfa
```

### Plugin and Datapack List

AdvancedBan, AntiCombatLog, AntiSeedCracker, BanAnnouncer, BanItem, BetterTeams, Chunky, EasyWhitelist, FAWE, ImageOnMap, InstantRestock, LoginSecruity, LuckPerms, MortisSpawnPoint, PlaceholderAPI, ProctoLib, SkBee, SkinsRestorer, skRayFall, Skript, spark, Spicord, TAB, Veinminer, ViaVersion, Vulcan

EZgap

### Paper version

1.20.4 Pufferfish - ver51 (i cant start server to get the ver)

**Comment by electronicboy** [comment]
We do not provide support for software that isn't ours, but, you apparently have a bad config file
