### ISSUE TITLE
Some players cannot attack any entities, seemingly due to no events being called

### ISSUE THREAD

**Issue by Budderman18** [PaperSpigot/Paper#10988]
### Expected behavior

attacking any entity runs all the necessary events needed

### Observed/Actual behavior

absolutely no events are ran when attacking enemies, meaning plugins cant do anything with it and you cannot damage or interact with anything that involves left-clicking (only affects certain players) (paintings and item frames can still be destroyed).

### Steps/models to reproduce

attack anything that isnt a painting or item frame, however not all players have this issue

### Plugin and Datapack List

no plugins needed

### Paper version

This server is running Paper version 1.21-37-master@dd49fba (2024-06-24T02:08:49Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-28-812701d (MC: 1.21)

### Other

https://github.com/PaperMC/Paper/assets/65318126/412d4e5c-a5a3-4a04-95ca-df574da9019e

Note: while the video does have plugins running on the server, it doesn't matter. I have tested on the same server with no plugins at all and the issue still occurs, hence why i didn't list any. Plugin making the chat messages is listening for both PlayerInteractEvent and EntityDamageByEntityEvent

**Comment by Machine-Maker** [comment]
> no plugins needed

Does this mean you can replicate this issue on a server with on plugins? If it **doesn't** mean that? Can you replicate this on a server with 0 plugins?

**Comment by Budderman18** [comment]
the other section underneath the video says i can reproduce without any plugins

**Comment by Budderman18** [comment]
update: in some worlds i can attack stuff, but it always does damage as if im holding nothing, regardles of what the damage of the weapond should do

**Comment by Budderman18** [comment]
im going to close this issue: it seems to be a side effect of an other issue. I will open a ticket for it in a few hours as i need to record it and dont have the ability to right now
