### ISSUE TITLE
Last slot in a donkey mule or llama is wrong inventory type

### ISSUE THREAD

**Issue by fantahund** [PaperSpigot/Paper#10981]
### Expected behavior

The last slot in a donkey or mule is counted as a PlayerInventory with slot 9. It should actually be a SaddledInventory with slot 16.
The same problem exists with llamas, depending on the strength of the llama, the slot ID of the last slot naturally differs.

### Observed/Actual behavior

Nothing... The slot id and inventorytyp is simply returned incorrectly by the API

### Steps/models to reproduce

check the last slot of a donkey/mule or llama inventory and display the SlotID and the Inventory Type. 

### Plugin and Datapack List

/

### Paper version

Checking version, please wait...
This server is running Paper version 1.21-37-master@dd49fba (2024-06-24T02:08:49Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version

**Comment by lynxplay** [comment]
Replicable, the nms internal is scuffed af regarding slots / indicies.
