### ISSUE TITLE
1.21 Crashing

### ISSUE THREAD

**Issue by shunceyb** [PaperSpigot/Paper#10989]
### Stack trace

```
https://paste.gg/p/anonymous/d83977b6d5ab47b092532b5a5403f42f
```

### Plugin and Datapack List

Plugins - AdvancedTeleport, DeathChest, floodgate, Geyser-Spigot, OpenInv
There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]

### Paper version

This server is running Paper version 1.21-37-master@dd49fba

**Comment by lynxplay** [comment]
Your server is overloaded and is killed by the watchdog.
We are still missing a set of performance patches in 1.21, which is why it is marked as experimental.
