### ISSUE TITLE
Exception during remap

### ISSUE THREAD

**Issue by Lorenzo0111** [PaperSpigot/Paper#10982]
### Expected behavior

Plugin should work normally

### Observed/Actual behavior

Received this [exception](https://paste.gg/p/anonymous/e3cf120715ac4f3c917ee968608ed8f6) while loading my plugin jar. I've attached it below
[RocketJoin-bukkit-2.4.2.zip](https://github.com/user-attachments/files/15972184/RocketJoin-bukkit-2.4.2.zip)

### Steps/models to reproduce

Just load my plugin 

### Plugin and Datapack List

RocketJoin

### Paper version

[15:38:53 INFO]: This server is running Paper version 1.21-37-master@dd49fba (2024-06-24T02:08:49Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-28-812701d (MC: 1.21)

**Comment by Lorenzo0111** [comment]
I've pushed my code [here](https://github.com/Lorenzo0111/RocketJoin/tree/dev/update)

**Comment by electronicboy** [comment]
your build setup is producing jars which have duplicate entries, the classes listed in that error are inside of the jar more than once

**Comment by lynxplay** [comment]
Feel free to head to our [discord](https://discord.gg/papermc) if you have more questions.
