### ISSUE TITLE
Links in chat are not clickable.

### ISSUE THREAD

**Issue by YonakaDev** [PaperSpigot/Paper#10987]
### Expected behavior

When you send a link, the link should be clickable.

### Observed/Actual behavior

When you send a link, the link  is not clickable.

### Steps/models to reproduce

Just use PaperMC and send a link.

### Plugin and Datapack List

Tested Plugins:
![image](https://github.com/PaperMC/Paper/assets/120589058/f689ec22-045e-41d9-8f42-7fee90b24fe5) 
![image](https://github.com/PaperMC/Paper/assets/120589058/6c4a28f3-7dbc-468c-9bdf-eb4cb8fc6b27)

tested on 2 servers

### Paper version

f4c7d37

**Comment by lynxplay** [comment]
This has not been the case for a couple of versions now and is intended behaviour (especially since signed messages were introduced in 1.19.x). You'll need to find a plugin that does this.
