### ISSUE TITLE
Drinking a bucket of milk consistantly creates ghost item

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#10984]
### Expected behavior

Drinking a bucket of milk from a cow makes the bucket empty

### Observed/Actual behavior

Drinking a bucket of milk from a cow makes it look like your still holding a bucket of milk on client, and lets you drink it. (not real bucket of milk)

### Steps/models to reproduce

drink a bucket of milk

### Plugin and Datapack List

Plugins: Tester
Datapacks [vanilla (built-in], [file/bukkit (world)], [paper (built-in)]

### Paper version

Paper version 1.21-37-master@dd49fba (2024-06-24T02:08:49Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

**Comment by powercasgamer** [comment]
Cannot reproduce on build 37.

**Comment by MiniDigger** [comment]
can you try recording a short video clip of what you are experiencing?

**Comment by lynxplay** [comment]
Closing this as it's stale and I cannot replicate this.
