### ISSUE TITLE
Shulker boxes when placed on ground are loosing staff

### ISSUE THREAD

**Issue by Tantrum90** [PaperSpigot/Paper#10992]
### Expected behavior

Items that are stored in the shoulker box to stay in the shoulker box when placed on ground

### Observed/Actual behavior

Items that are stored in the shoulker box are gone when the SB is placed on ground

### Steps/models to reproduce

Days ago I updated the server from 1.20.2 to 1.20.6... 
My players started to notice that the shulker boxes that they had in inventory when are placed on ground so thet can access them are presented empty. 

### Plugin and Datapack List

26.06 16:58:26 [Server] INFO Server Plugins (52):
26.06 16:58:26 [Server] INFO Bukkit Plugins:
26.06 16:58:26 [Server] INFO - AdvancedAntiVPN, ajParkour, AuthMe, BlockedWords, BottledExp, ChestSort, Citizens, CMILib, CoreProtect, DailyRewardsPlus
26.06 16:58:26 [Server] INFO DeadChest, DecentHolograms, Despicaleaderboards, DoorsReloaded, Essentials, EssentialsChat, FarmLimiter, floodgate, GEmote, Geyser-Spigot
26.06 16:58:26 [Server] INFO GriefPrevention, GSit, ImageFrame, InventoryRollbackPlus, LuckPerms, MOTD, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals
26.06 16:58:26 [Server] INFO NoEndCrystals, PlaceholderAPI, PlayerStats, *Playtimes, ProtocolLib, Shopkeepers, SkinsRestorer, sleep-most, Spartan, T2C-Alias
26.06 16:58:26 [Server] INFO T2C-OPSecurity, T2CodeLib, TabList, TicTacToe, TimeBar, TNTRun, Vault, ViaBackwards, ViaVersion, WorldEdit
26.06 16:58:26 [Server] INFO WorldGuard, WorldTime

### Paper version

26.06 16:57:41 [Server] INFO This server is running Paper version 1.20.6-147-ver/1.20.6@e41d44f (2024-06-17T19:24:35Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
26.06 16:57:41 [Server] INFO You are running the latest version
26.06 16:57:41 [Server] INFO Previous version: 1.20.6-129-0513374 (MC: 1.20.6)

**Comment by tantrum90** [comment]
> Please provide a playerdata file from a backup before updating from a player that had shulkers that lost items.

I will need some time to restore the backup and to extract the information

**Comment by tantrum90** [comment]
I founded out what is the problem and it is not connected to Paper. Sorry
