### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by tomasalias** [PaperSpigot/Paper#11009]
### Expected behavior

Working respawn button

### Observed/Actual behavior

Nether portal blocks respawn button

### Steps/models to reproduce

https://vm.tiktok.com/ZGes6jB34/

### Paper version

Vanilla

**Comment by electronicboy** [comment]
"vanilla" is not a valid paper version, a random tiktok video does not provide any information as to if this only affects single player or if this affects servers.
