### ISSUE TITLE
PluginRemapper: Can't remap obfuscated plugins

### ISSUE THREAD

**Issue by amadeusmz** [PaperSpigot/Paper#11005]
### Expected behavior

Plugin loaded normally.

### Observed/Actual behavior

IllegalStateException: Duplicate key  
Error logs as follow:  
https://mclo.gs/TbMmnRY

### Steps/models to reproduce

Runs paper build `#147` with a plugin in the following link:  
https://github.com/amadeusmz/RemapperTest/releases/tag/test  
The plugin load normally in papermc 1.20.4 (any build)  
This is a simple plugin that was obfuscated with proguard. The source code of the plugin is in the same Github repository.

### Plugin and Datapack List

Installed only that test plugin, and it wasn't loaded.

```
> plugins
[19:15:02 INFO]: Server Plugins (0):
```

### Paper version

```
> version
[19:15:15 INFO]: Checking version, please wait...
[19:15:15 INFO]: This server is running Paper version 1.20.6-147-ver/1.20.6@e41d44f (2024-06-17T19:24:35Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.20.6-2232-f1c87e4 (MC: 1.20.6)
```

**Comment by electronicboy** [comment]
Pretty sure that this is considered a "won't fix" due to these obfuscators breaking JVM spec

**Comment by jpenilla** [comment]
It's up to NeoForged whether they want to support this in AutoRenamingTool. This type of obfuscation doesn't provide any real benefit over standard obfuscation (a bytecode transformer to rename any conflicting fields would be quite simple to create, and from there mapping tools like Enigma would have no problem helping to name things). I would recommend either:
1) Build your plugin with paperweight-userdev (or simply mark the manifest if you don't use internals) so you can ship the Mojang-mapped plugin jar to users (that won't need remapping)
2) Disable the aggressive overloading option on ProGuard
