### ISSUE TITLE
Uexpected error while starting the server

### ISSUE THREAD

**Issue by pavelbat3** [PaperSpigot/Paper#11016]
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
![image](https://github.com/PaperMC/Paper/assets/99824228/221aebf3-7d3f-4875-8f73-cbb24aff112f)

### Plugin and Datapack List

no

### Actions to reproduce (if known)

no

### Paper version

1.21-42

**Comment by Warriorrrr** [comment]
1.21 requires java 21 or above, you are using java 17.
