### ISSUE TITLE
Crafters lead to duplication with custom crafting plugins

### ISSUE THREAD

**Issue by WillFP** [PaperSpigot/Paper#11029]
### Expected behavior

I would expect a CrafterCraftEvent to exist in order to hook into crafters. Failing this, I would assume there is a way to disable certain CraftingRecipes from working in crafters.

### Observed/Actual behavior

There is no such API and it is not possible to blacklist recipes from working in crafters.

### Steps/models to reproduce

Use a custom recipe plugin like EcoItems, CustomCrafting, or any plugin with custom item crafting / support for crafting recipes with stacked items (e.g. EcoItems, EcoArmor, etc.) and you will be able able to craft items without sufficient items.

### Plugin and Datapack List

eco and EcoItems. Both are open-source, the crux of the crafting logic for eco can be found [here](https://github.com/Auxilor/eco/tree/master/eco-core/core-plugin/src/main/kotlin/com/willfp/eco/internal/spigot/recipes)

### Paper version

1.21-38-master@1f5db50 (2024-06-27T20:15:58Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### Other

There doesn't seem to be any API in the works or any open PRs for this. If this is not planned or if it's not considered essential before 1.21 is considered stable, please tell me what would be considered as a PR so I can make it.

**Comment by Grabsky** [comment]
I can definitely see how important `CrafterCraftItemEvent` *is* for *many* servers. As stated by the OP, you can currently use crafters to get around `PrepareCraftItemEvent` logic, which many plugins use to eg. block custom items from being used in vanilla recipes.

Example:
```java
@EventHandler(ignoreCancelled = true)
public void onCraftPrepare(final PrepareItemCraftEvent event) {
    // Skipping calls when the input does not match any recipe.
    if (event.getRecipe() == null)
        return;
    // Iterating over all items in the inventory matrix and "cancelling" the result as soon as custom item is found as an ingredient.
    for (final ItemStack item : event.getInventory().getMatrix()) {
        if (item != null && item.hasItemMeta() && item.getItemMeta().getCustomModelData() == 7) {
            event.getInventory().setResult(null);
            return;
        }
    }
}
```

I feel like `CrafterCraftItemEvent` would be mandatory to solve that particular case, but addition of `PrepareCrafterCraftItemEvent` would also be nice. Looks like it has already been suggested on https://github.com/PaperMC/Paper/discussions/10972.
