### ISSUE TITLE
Every item can be enchanted with every enchantment

### ISSUE THREAD

**Issue by Tantrum90** [PaperSpigot/Paper#11023]
### Expected behavior

Only certain allowed items to be enchanted with allowed enchantments

### Observed/Actual behavior

Every item can be enchanted with every enchantment

### Steps/models to reproduce

Install latest Paper 1.21 #44

### Plugin and Datapack List

- N/A

### Paper version

05.07 22:14:22 [Server] INFO This server is running Paper version 1.21-44-master@8d91b85 (2024-07-04T18:56:20Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
05.07 22:14:22 [Server] INFO You are running the latest version
05.07 22:14:22 [Server] INFO Previous version: 1.21-43-be8ac7a (MC: 1.21)

### Other

<img width="488" alt="image" src="https://github.com/PaperMC/Paper/assets/171391033/d706c652-f5e8-408b-8d3f-ff212a8a2174">

<img width="488" alt="image" src="https://github.com/PaperMC/Paper/assets/171391033/c6c9900b-8fac-4c9e-b389-9f07cc882a0b">

**Comment by Malfrador** [comment]
Unable to reproduce in survival mode. If you are in creative mode, this is intended behaviour and also possible in vanilla.
