### ISSUE TITLE
Custom enchantments do not appear in the enchantment table.

### ISSUE THREAD

**Issue by HshMaker** [PaperSpigot/Paper#11034]
### Timings or Profile link

https://timings.aikar.co/dev/?id=1486df0306044b9c9f03f093383849c4

### Description of issue

I was following this guide.
[https://docs.papermc.io/paper/dev/registries](url)

Everything worked and custom enchantment content appeared in /enchant, but custom enchantment content did not actually appear in the enchantment table.

Are there still technical limitations? Or is it just not working in the first place?

Is there no way to just apply it separately as an event handler?

### Plugin and Datapack List

![image](https://github.com/PaperMC/Paper/assets/106089532/a9329823-12de-4fe0-a54e-34acc452af29)

That's all ;(

### Paper version

![image](https://github.com/PaperMC/Paper/assets/106089532/e829e872-95bb-490c-8214-963a8f04bdf7)

**Comment by lynxplay** [comment]
Known limitation, you'd need to add the enchantment to the https://jd.papermc.io/paper/1.21/io/papermc/paper/registry/keys/tags/EnchantmentTagKeys.html#IN_ENCHANTING_TABLE tag, which is currently not possible via code.

Alternatively, you could use a datapack to do it.
The PR #10993 is in the works for code-based tag modification tho.
