### ISSUE TITLE
Can no longer add ItemStack(Air) Ingredient in a Merchant Recipe

### ISSUE THREAD

**Issue by byquanton** [PaperSpigot/Paper#11030]
### Expected behavior

Villager Trade with "minecraft:air" Ingredient.

### Observed/Actual behavior

Having it fail since https://github.com/PaperMC/Paper/pull/10707 got merged.
https://github.com/PaperMC/Paper/blob/2fa5e0e0df6c2fa4ccb7ab80710d839dd8e0c5ce/patches/api/0470-Fix-issues-with-recipe-API.patch#L116

### Steps/models to reproduce

```java
Merchant merchant = Bukkit.createMerchant(title);
List<MerchantRecipe> recipes = new ArrayList<>();
MerchantRecipe merchantRecipe = new MerchantRecipe(new ItemStack(Material.DIRT), 99);
merchantRecipe.addIngredient(new ItemStack(Material.AIR));
recipes.add(merchantRecipe);
merchant.setRecipes(recipes);
player.openMerchant(merchant, true);
```

### Plugin and Datapack List

Only a plugin containing the code written in "steps to reproduce "

### Paper version

This server is running Paper version 1.20.6-148-ver/1.20.6@20f5165 (2024-07-02T15:37:33Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version

### Other

Introduced in https://github.com/PaperMC/Paper/pull/10707/

**Comment by lynxplay** [comment]
Yes, this is an intended change.
The network codecs no longer allow you to pass an air item as an ingredient.
Doing so will fail when the offers are sent to the client (hence the API protects you from this with a precondition check).

There is nothing the server can do about this change, even if we were to change the server side of things, the client would error and disconnect when receiving such a merchant offer.
