### ISSUE TITLE
paper 1.21 does not have Material

### ISSUE THREAD

**Issue by HshMaker** [PaperSpigot/Paper#11041]
### Expected behavior

I want to see this
![image](https://github.com/PaperMC/Paper/assets/106089532/a56d6f62-d10a-429a-9dd1-d060b7e13146)
but it's 1.20.1 paper

### Observed/Actual behavior

when i use 1.21 paper
![image](https://github.com/PaperMC/Paper/assets/106089532/89d9996e-aa65-4cbe-b6dd-344cd8f7616d)
I get some strange code...

i'm using kotlin but
java equal

### Steps/models to reproduce

i just want to use 1.21 Material

Is there anything else except waiting?

### Plugin and Datapack List

it's not server error

### Paper version

it's not server issue

**Comment by electronicboy** [comment]
Update your IDE

**Comment by HshMaker** [comment]
> Update your IDE

It's a library, so does that make a difference?

**Comment by electronicboy** [comment]
Yes, if your IDE doesn't understand classes from java 21, it will fail in unexpected manners

**Comment by HshMaker** [comment]
Ah, understand Thanks
