### ISSUE TITLE
EntityDamageByEntityEvent called more than should.

### ISSUE THREAD

**Issue by cb31455** [PaperSpigot/Paper#11044]
### Expected behavior

EntityDamageByEntityEvent should be called 1x per dmg received on player. if i know well (as experienced) maximum 1 instance of damage should taken by player per every half second no matter how many enemy attacks at the same time (at least this was till 1.21 / 8d91b85Prioritize vanilla commands in function parsing (#11011)). 

### Observed/Actual behavior

EntityDamageByEntityEvent called multiple times if more enemy attack even this happens when 1 attack does dmg only.

### Steps/models to reproduce

Let multiple enemies attack at the same time. 2 attacks registered / sec as received dmg, but EntityDamageByEntityEvent called way more times. This happens since 1.21 4d20922Updated Upstream (Bukkit/CraftBukkit/Spigot) (#11024) update.
I made a picture, where red numbers "dmg taken" calculated by EntityDamageByEntityEvent in my plugin. that 4 red number happened under 0.5 sec.
![bug](https://github.com/PaperMC/Paper/assets/36733395/7344b9e3-2bd6-4a6f-9c1b-ef6770b9ebe2)

### Plugin and Datapack List

Own plugin (ChipsTm), which worked nicely till patch 1.21 8d91b85Prioritize vanilla commands in function parsing (#11011)
Chunky. works fine.
Datapacks: vanilla, file/bukkit, paper

### Paper version

This server is running Paper version 1.21-47-master@62ed302 (2024-07-07T17:34:15Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-45-4d20922 (MC: 1.21)

**Comment by lynxplay** [comment]
Can you attempt to replicate this on [build 48](https://api.papermc.io/v2/projects/paper/versions/1.21/builds/48/downloads/paper-1.21-48.jar).

**Comment by lynxplay** [comment]
Okay found the issue 👍 Upstream issue, will look into a fix.

**Comment by lynxplay** [comment]
#11045 should fix this, until merged there is a server jar to test with on the PR.

**Comment by cb31455** [comment]
> #11045 should fix this, until merged there is a server jar to test with on the PR.

that test server jar working fine in this case (minimal testing)
