### ISSUE TITLE
No Damage Tick with absorption

### ISSUE THREAD

**Issue by TrueGame776** [PaperSpigot/Paper#11042]
### Expected behavior

Players taking regular damage, knockback and having the regular damage tick while being hit while having absorption hearts (from Golden Apples/Enchanted Golden Apples)

### Observed/Actual behavior

Players taking regular damage but having 0 knockback and no damage tick while being hit while having absorption hearts. Since it has no damage tick, it can be used to spam-click and destroy a full netherite helmet with 1 enchanted golden apple.

### Steps/models to reproduce

Two players: Player 1 and Player 2.
1. Make server be Paper 1.21 on Build 47
2. Make player 2 eat a Golden Apple/Enchanted Golden Apple (or anything that may give absorption, even custom coded items)
3. Attack player 2 using player 1 who has any item/weapon. Player 2 will not take knockback and not have a damage tick, but they will take damage (you can check this using a health indicator).
4. You can further see the no damage tick by having player 2 wear full netherite armor, while player 1 spam hits them after player 2 eats an absorption food.

### Plugin and Datapack List

Does not matter, tried on two different servers.

### Paper version

# Main server 1
This server is running Paper version 1.21-47-master@62ed302 (2024-07-07T17:34:15Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-17-666bc4d (MC: 1.21)
# Test server 2
This server is running Paper version 1.21-47-master@62ed302 (2024-07-07T17:34:15Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-44-8d91b85 (MC: 1.21)

**Comment by lynxplay** [comment]
Should be fixed in build 48 once out, thank you for the report!
