### ISSUE TITLE
Server main loop blocked when explosion occurs

### ISSUE THREAD

**Issue by KKW557** [PaperSpigot/Paper#11059]
### Stack trace

https://pastebin.com/YDWbF57g

### Plugin and Datapack List

No plugins and default datapacks

### Actions to reproduce (if known)

1. Start paper
2. Trigger an explosion (e.g. /summon tnt)

### Paper version

This server is running Paper version 1.21-57-master@0e02aa5 (2024-07-11T19:34:02Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-50-20889d0 (MC: 1.21)

### Other

openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Zulu21.34+19-CA (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Zulu21.34+19-CA (build 21.0.3+9-LTS, mixed mode, sharing)

**Comment by CodeByCam** [comment]
Hello @KKW557, 
I'm unable to reproduce this on the latest build of Paper. Can you please provide your entire `latest.log`?

**Comment by un-sc** [comment]
I found that when I left clicked on ender_crystal on Bedrock and it exploded, it would cause the server to crash, even if I didn't install any plugins.

https://mclo.gs/BnxFrIv

**Comment by EasyMochi** [comment]
I can confirm this behaviour, TNT and Creepers will cause the main thread to freeze

**Comment by CodeByCam** [comment]
> I found that when I left clicked on ender_crystal on Bedrock and it exploded, it would cause the server to crash, even if I didn't install any plugins.
> 
> [mclo.gs/BnxFrIv](https://mclo.gs/BnxFrIv)

I was able to reproduce it with end crystals: https://pastes.dev/R5uTf4yR9u.  I haven't been able to reproduce the crash with TNT or Creepers yet.

**Comment by EasyMochi** [comment]
That is odd, it happens consistently on my end, anytime a Creeper is about to explode, same goes with primed TNT. I reverted to build 50 and everything works fine.

**Comment by KKW557** [comment]
If there are unbreakable blocks (such as bedrock or barriers) within the explode range, the thread will freeze, is 100%

**Comment by electronicboy** [comment]
Yea, I was looking at the code, that confirms what I believe is the issue to me;

**Comment by EasyMochi** [comment]
I can also confirm that I had barriers next to the Creepers, so that makes sense

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Paper/pull/11061 - I don't have the gusto to check this with my current state

**Comment by CodeByCam** [comment]
> #11061 - I don't have the gusto to check this with my current state

Yep, this seems to have fixed the issue! 🥳
