### ISSUE TITLE
Unable turn a lodestone compass back into compass

### ISSUE THREAD

**Issue by TheGameratorT** [PaperSpigot/Paper#11051]
### Expected behavior

When removing the lodestone properties of a lodestone compass it should become a compass.

### Observed/Actual behavior

The compass remains a lodestone compass when trying to set it back to a compass.

### Steps/models to reproduce

```java
ItemStack compass = new ItemStack(Material.COMPASS, 1);
CompassMeta compassMeta = (CompassMeta)compass.getItemMeta();
compassMeta.setLodestoneTracked(false);
compass.setItemMeta(compassMeta);
player.getInventory().addItem(compass);

ItemStack compassFromInv = getPlayerCompass(player);
CompassMeta compassFromInvMeta = (CompassMeta)compassFromInv.getItemMeta();
compassFromInvMeta.setLodestone(null);
compassFromInvMeta.setLodestoneTracked(true);
compassFromInv.setItemMeta(compassFromInvMeta);

public ItemStack getPlayerCompass(Player player) {
    PlayerInventory inv = player.getInventory();

    for (int slot = 0; slot < inv.getSize(); slot++) {
        ItemStack stack = inv.getItem(slot);
        if (stack != null && stack.getType() == Material.COMPASS) {
            return stack;
        }
    }

    return null;
}
```

### Plugin and Datapack List

```
> plugins
[12:46:52 INFO]: Server Plugins (1):
[12:46:52 INFO]: Bukkit Plugins:
[12:46:52 INFO]:  - PlayerTracker
```

### Paper version

```
> version
[12:44:14 INFO]: Checking version, please wait...
[12:44:15 INFO]: This server is running Paper version 1.21-49-master@b0ef3ca (2024-07-09T15:22:17Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
```

### Other

The issue is not present in the latest Spigot as I figured the hard way only after having opened the issue.
https://hub.spigotmc.org/jira/browse/SPIGOT-7826

**Comment by Machine-Maker** [comment]
I think we are just missing some "resetLodestoneTracked" method. Calling setLodestoneTracked(false) shouldn't ever "clear" the lodestone from the compass, because that is still an untracked lodestone compass. If that method accepted null, that could be the 3rd state, but it doesn't.

**Comment by TheGameratorT** [comment]
That is why in Spigot when setLodestoneTracked(true) and setLodestone(null) the lodestone compass becomes a normal compass because, correct me if I am wrong, it's not possible to have a tracked compass without lodestone. But a "resetLodestoneTracked" does seem more intuitive.

**Comment by Machine-Maker** [comment]
It *is* possible to have a tracked compass without a location. That is a completely valid itemstack you can give yourself in vanilla minecraft.
