### ISSUE TITLE
Unknown command message doesn't work

### ISSUE THREAD

**Issue by Askarionn** [PaperSpigot/Paper#11053]
### Expected behavior

![image](https://github.com/PaperMC/Paper/assets/51824859/3865aacc-39d9-4c75-a27f-e8404f9e9635)

### Observed/Actual behavior

![image](https://github.com/PaperMC/Paper/assets/51824859/cf1972e4-e08d-465b-a0f0-dfe443eb8e5f)

### Steps/models to reproduce

Type any command that doesn't exist

### Plugin and Datapack List

0 plugins

### Paper version

This server is running Paper version 1.21-50-master@20889d0 (2024-07-10T16:28:03Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-47-62ed302 (MC: 1.21)

**Comment by Malfrador** [comment]
This is expected behaviour due to the server using the vanilla "Brigadier" system for commands, which handles unknown commands in a way that does no longer allow for a configurable message on the server. The Spigot config option does nothing (which probably should be documented).

**Comment by MiniDigger** [comment]
only way to change the message now would be a resource pack
