### ISSUE TITLE
Shulker Box PersistentDataContainer not retained when broken

### ISSUE THREAD

**Issue by KBD2** [PaperSpigot/Paper#11057]
### Expected behavior

When a Shulker Box is broken, the values in its persistent data container are in the dropped ItemStack's block state.

### Observed/Actual behavior

The values are not present.

### Steps/models to reproduce

- Set some key-value pair in a Shulker Box's PersistentDataContainer; I achieved this via a plugin command:
`
Block block = player.getTargetBlockExact(10);
if (block != null && block.getState() instanceof ShulkerBox box) {
  box.getPersistentDataContainer().set(new NamespacedKey("test", "thing"), PersistentDataType.STRING, "Hello");
  box.update();
}
`
  - This can also be achieved via setting the value in the PDC of the block state in a shulker box item, and then placing the box
- Use `/data get block <coordinates>` to verify the data has been written
- Break the block
- Use `/data get entity @e[type=item,distance=..6,limit=1] Item` to verify the data has not been kept.

### Plugin and Datapack List

- The plugin created to reproduce the issue.

### Paper version

This server is running Paper version 1.20.6-148-ver/1.20.6@20f5165 (2024-07-02T15:37:33Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.20.6-138-906df69 (MC: 1.20.6)

**Comment by Machine-Maker** [comment]
This is expected behavior. Block entities do not keep their NBT when they are broken. The same thing applies to other block entities. I don't think this was ever the behavior, so it's not a regression either.

**Comment by KBD2** [comment]
It's rather unintuitive then, as the opposite (placing a shulker box with values in the blockstate PDC of the item stack) works perfectly.

**Comment by Machine-Maker** [comment]
This has always been the case though. The point of the block entity tag in the stack's data components is to pre-fill the nbt of the block entity. There has never been any system for going in the opposite direction except for what the loot table copies in specific circumstances (chest name for instance).
