### ISSUE TITLE
0 damage sources don't apply knockback to players

### ISSUE THREAD

**Issue by Pitrex111** [PaperSpigot/Paper#11055]
### Expected behavior

When plugin sets damage value for EntityDamageEvent to 0 but doesn't cancell event. Player should still get knockback and arrows should be stuck in player.

### Observed/Actual behavior

Arrows bounce of players as if event was cancelled in previous versions and player reveive no knockback form 0 damage hits. (looks like it works for other mobs)

### Steps/models to reproduce

With extra plugin create listener and set 0 damage for each EntityDamageEvent. Normal mobs will still be knocked back on hits (while unkillable) but player will behave as event was cancelled instead. 

### Plugin and Datapack List

[10:26:34 INFO]: Server Plugins (13):
[10:26:34 INFO]: Bukkit Plugins:
[10:26:34 INFO]:  - *JoinFullServer, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, NoChatReports, *PermissionsEx, PexTabCompleter, ProtocolLib, *SimplePrefix-Reloaded, TreasureChestX
[10:26:34 INFO]:  *VoidWorld, WorldEdit, WorldGuard

[10:26:54 INFO]: There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]
[10:26:54 INFO]: There are no more data packs available

### Paper version

[10:27:38 INFO]: Checking version, please wait...
[10:27:38 INFO]: This server is running Paper version 1.21-50-master@20889d0 (2024-07-10T16:28:03Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-DEV-0a338e2 (MC: 1.21)

### Other

I can provide later in time video example if necessary. I tested previous builds and last one where knockback worked correctly was build 44, on build 45 the behaviour is already broken.

**Comment by Pitrex111** [comment]
I think it's weird as then player is handled diffrently as other entities, where 0 damage event still triggers. Mayble that's why snowballs don't apply knockback to players at this point in time?
But still this is an issue for me, as I rellied on this mechanic for my plugin where I rewrite damage system completelly. But maybe there could be some middle ground, as probably reverting a bug because of plugin regression is not the best solution. If EntityDamageEvent would get new method "void setFinalDamage(double damage)" that would override all damage reduction calculations and just reduce player health by set amount. Then I would not have to resort to setting damage inside event to 0 and then reducing player health.
Another method that would help me would be "void setProcessKnockbackAndArrowConsumption(boolean state)". Name to be discussed properly. And that method would force knockback on Players and make arrow actually hit him even when damage set is equal to 0. (There are still some instances that player receaves no actuall damage in my system but should be treated as hit by the enemy)
With those 2 cases I could reproduce my system without that bug in the most easy way, and without either of that I'll have to really think how to handle such case.

**Comment by lynxplay** [comment]
https://github.com/PaperMC/Paper/pull/11058 contains a test server jar, feel free to test it and see if the change correctly resolves your issue here.

**Comment by Pitrex111** [comment]
@lynxplay I tested it and can confirm that it resolves my issue
