### ISSUE TITLE
Written books with pages require author/title 

### ISSUE THREAD

**Issue by aurorasmiles** [PaperSpigot/Paper#11067]
### Expected behavior

Before https://github.com/PaperMC/paper/commit/4d20922b79f5b3976e240932d087357a3808fde4 creating a book with pages but without an author or title worked without issues

### Observed/Actual behavior

After that commit when creating a book that has pages but without an author or title it can no longer encode the component correctly
https://paste.enginehub.org/uQZTHfDcR

### Steps/models to reproduce

```java
ItemStack book = new ItemStack(Material.WRITTEN_BOOK);
BookMeta meta = (BookMeta) book.getItemMeta();
meta.addPages(Component.text("awawawa"));
book.setItemMeta(meta);
e.getPlayer().getInventory().addItem(book);
```

### Plugin and Datapack List

n/a

### Paper version

Paper version 1.21-62-master@5a503d7

### Other

It's a bit weird, because both `setTitle()` and `setAuthor()` are Nullable, and when the book doesn't have any pages it's fine to not set them, but as soon as you add pages to the book those become required

**Comment by Lulu13022002** [comment]
Good catch, a fix has been dropped in that commit wrongly and generally no codec error should happens anyway.
