### ISSUE TITLE
Incorrect remapping

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#11078]
### Expected behavior

Papers jar remapper incorrectly renames 
net.minecraft.server.level.ChunkMap$TrackedEntity
to
net.minecraft.server.level.ChunkTracker$TrackedEntity

"chunktracker" isn't mentioned in the paper jar, its called chunkmap, why is it remapping to chunktracker?
I was pulling my hair out for hours because of this weird error message:

java.lang.NoSuchFieldError: Class net.minecraft.world.entity.Entity does not have member field 'net.minecraft.server.level.ChunkTracker$TrackedEntity tracker'

in intellij it was referred to as chunkmap, dumping the fields at runtime its referred to as chunkmap, but for some reason in the remapped jars its referred to as chunktracker

How do i disable the paper jar remapper for a given plugin?

### Paper version

This server is running Paper version 1.21-DEV-master@34a2917 (2024-07-14T13:04:22Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21-63-2288e13 (MC: 1.21)

**Comment by lynxplay** [comment]
Known issue, happening when spigot and paper mappings share a name.

**Comment by lynxplay** [comment]
Wait are you using reflection? Or just plain code.

**Comment by lynxplay** [comment]
Then you need to specify your remapping namespace as detailed in the discord and forum announcement for the mappings change, otherwise paper will remap your plugin.
