### ISSUE TITLE
Ignoring absolute chunk 

### ISSUE THREAD

**Issue by alexinplanet** [PaperSpigot/Paper#11075]
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
https://pastebin.com/raw/ugmhWrUn

### Plugin and Datapack List

/plugins Itemsadder protocolib lonelibs

### Actions to reproduce (if known)

I changed server version to 1.20.4 to 1.20.1 and also changed spigot to paper. I backup the world file and paste it to the newer version of my server(1.20.1) and it's happened. 

### Paper version

/version  git-Paper-22 (MC: 1.20.1)

**Comment by powercasgamer** [comment]
1.20.1 is not supported and neither is downgrading.
