### ISSUE TITLE
1.20.4 plugins don't load

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#11074]
### Expected behavior

1.20.4 compiled plugins should load, as paper api should be somewhat backwards compatable? The breakages here are just become spigot renamed the enum, no NMS or internals are being used

### Observed/Actual behavior

java.lang.NoSuchFieldError: Class org.bukkit.enchantments.Enchantment does not have member field 'org.bukkit.enchantments.Enchantment PROTECTION_ENVIRONMENTAL'

java.lang.NoSuchFieldError: Class org.bukkit.potion.PotionEffectType does not have member field 'org.bukkit.potion.PotionEffectType INCREASE_DAMAGE'

### Steps/models to reproduce

Compile a 1.20.4 plugin and try to use on 1.21

### Plugin and Datapack List

N/A

### Paper version

1.21 34a2917dccd1a39888c85badd7cf7aad7c44ff61

**Comment by lynxplay** [comment]
Are you using paper-plugin.yml?

**Comment by lynxplay** [comment]
It does.

**Comment by electronicboy** [comment]
There is 0 promise that spigot will remap or mitigate every change mojang does internally, that is apparently one such case of them not remapping it

**Comment by electronicboy** [comment]
There are 0 promises that a plugin written on 1.8 will work on 1.21
