### ISSUE TITLE
Enchanting is completely broken after upgrading the world from 1.19.4 to 1.21

### ISSUE THREAD

**Issue by Deeptanil** [PaperSpigot/Paper#11089]
### Expected behavior

Enchanting to work as normal.

### Observed/Actual behavior

Wrong enchantments as seen in the attachment.
![xXHf47e](https://github.com/user-attachments/assets/b6d4ddce-82d6-45f9-b082-e41cc0568b5b)

### Steps/models to reproduce

Loading a world in 1.19.4
Upgrading it to the lastest.

### Plugin and Datapack List

Via version, via backward 

Afk detect, afk message, afk dum names, fast decay, unlock all recipes, coordinates hud, duraping, last death location, loyal items, 

### Paper version

This server is running Paper version 1.21-78-master@ef96a69 (2024-07-16T08:23:03Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-77-2cd8c46 (MC: 1.21)

### Other

Also not only in the enchanting table, even villagers are messed up. The curse books aren't red in color, instead the mending book is. There is probably another book that I have yet to see which is also red.

**Comment by electronicboy** [comment]
Are you testing in creative mode?

**Comment by kennytv** [comment]
That's not a Paper issue if you're on a different client version

**Comment by Deeptanil** [comment]
Haven't tested in creative.
I'm on the same client version.
