### ISSUE TITLE
Zombies dont break doors in paper 1.21 build #79

### ISSUE THREAD

**Issue by Alejomc26** [PaperSpigot/Paper#11096]
### Expected behavior

Zombie breaking wooden doors when trying to go to some place that is at the other side of the door

### Observed/Actual behavior

![2024-07-16_19 11 46](https://github.com/user-attachments/assets/af6bc64c-940d-4c3a-865e-427d9ff1bc9b)
already more than 1 minute and no zombie trying to break the door

### Steps/models to reproduce

Go to a house with a wooden door, place a zombie outdoors, go outside and close the door

### Plugin and Datapack List

nothing

### Paper version

Paper 1.21 build #79

**Comment by iainrosen** [comment]
Unable to replicate this issue in build 81 using `/summon zombie ~ ~ ~ {CanBreakDoors:1}` in hard difficulty. Zombie under these conditions can break down doors.

**Comment by CodeByCam** [comment]
Have also been unable to reproduce, @Alejomc26. Please ensure the difficulty is set to hard ([/difficulty](https://minecraft.wiki/w/Difficulty#World_settings)), as zombies breaking wooden doors only has a small chance of happening in [hard/hardcore mode](https://minecraft.wiki/w/Zombie#Breaking_doors).
