### ISSUE TITLE
I use PaperMC, suddenly the server shuts down, players enter and play, it shuts down after 5 minutes

### ISSUE THREAD

**Issue by DuozMAX** [PaperSpigot/Paper#11098]
### Stack trace

https://pastes.dev/WR0v3ujEpe : ERROR

https://pastes.dev/G2Bg24qSRs : latest.log

### Plugin and Datapack List

![hata](https://github.com/user-attachments/assets/ebe9b0d1-0ed2-4f59-9599-749d952576bb)

### Paper version

1.21-81-master@ceeb8c1

**Comment by Skyekc** [comment]
Friends who enter from Floodgate enter directly as normal users (.) there is no sign

**Comment by lynxplay** [comment]
You are 13 builds out of date, make sure to update. If you still run into this issue on build 94, let us know on the issue.

**Comment by lynxplay** [comment]
Have you been able to replicate this on latest paper?

**Comment by lynxplay** [comment]
Closing this as I consider it stale. If someone runs into this issue again on latets paper, post the issue here and we'll reopen the issue :)
