### ISSUE TITLE
ChunkLoadEvent and ChunkUnloadEvent never fire

### ISSUE THREAD

**Issue by joshuaprince** [PaperSpigot/Paper#11103]
### Expected behavior

ChunkLoadEvent and ChunkUnloadEvent should fire regularly as chunks load and unload.

### Observed/Actual behavior

Starting in Paper 1.21 build 84 (Moonrise changes), ChunkLoadEvent and ChunkUnloadEvent do not fire at all.

### Steps/models to reproduce

Test plugin:

```java
    @EventHandler
    public void onChunkLoad(ChunkLoadEvent event) {
        // Does not fire
        getLogger().info("Chunk load " + event.getChunk().getX() + " " + event.getChunk().getZ());
    }

    @EventHandler
    public void onChunkUnLoad(ChunkUnloadEvent event) {
        // Does not fire
        getLogger().info("Chunk UNload " + event.getChunk().getX() + " " + event.getChunk().getZ());
    }

    @EventHandler
    public void onChunkLoadPlayer(PlayerChunkLoadEvent event) {
        // Works as expected
        getLogger().info("Chunk load PLAYER " + event.getChunk().getX() + " " + event.getChunk().getZ());
    }

    @EventHandler
    public void onChunkUnLoadPlayer(PlayerChunkUnloadEvent event) {
        // Works as expected
        getLogger().info("Chunk UNload PLAYER " + event.getChunk().getX() + " " + event.getChunk().getZ());
    }

    @EventHandler
    public void onPlayerMove(PlayerMoveEvent event) {
        // Works as expected
        getLogger().info(event.getTo().getX() + " " + event.getTo().getY() + " " + event.getTo().getZ());
    }
```

### Plugin and Datapack List

No extra plugins or datapacks, test plugin only using an empty server folder.

### Paper version

Custom build from build 89 44c3dd0d with only test plugin changes

```
ver
[21:41:35 INFO]: Checking version, please wait...
[21:41:35 INFO]: This server is running Paper version 1.21-DEV (2024-07-18T04:41:18Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running a development version without access to version information
```

**Comment by MagmaGuy** [comment]
+1, independently tested this for build #89 after a bug report from a user. My local was on #57 and the problem was not present there. It's a big one, hope it will get fixed soon.

**Comment by CatBang** [comment]
If the situation is true, according to your description, it would lead to the failure of the server's WorldGuard world protection, which indeed seems to be quite serious.
[description](https://github.com/PurpurMC/Purpur/issues/1560#issuecomment-2235268382)
