### ISSUE TITLE
lootables broken?

### ISSUE THREAD

**Issue by Tizooo** [PaperSpigot/Paper#11119]
### Expected behavior

lootables working

### Observed/Actual behavior

lootables not working

### Steps/models to reproduce

use lootables (i used a custom end_city_treasure lootable)

### Plugin and Datapack List

21:52:20 [INFO] Server Plugins (61):
21:52:20 [INFO] Paper Plugins:
21:52:20 [INFO]  - CrazyCrates, mServerLinks, RoseStacker
21:52:20 [INFO] Bukkit Plugins:
21:52:20 [INFO]  - AdvancedEnchantments, ajLeaderboards, AntiRaidFarm, AuraSkills, ChatSentry, Chunky, ChunkyBorder, CommandWhitelist, CompactPurpur, CoreProtect
21:52:20 [INFO]  DecentHolograms, DoubleDoors, EntityDetection, Essentials, EssentialsDiscord, EssentialsSpawn, FarmControl, floodgate, Geyser-Spigot, GSit
21:52:20 [INFO]  InteractiveChat, InventoryRollbackPlus, InvSeePlusPlus, JetsAntiAFKPro, Lands, LiteBans, LoneLibs, LPC, LuckPerms, MiniMOTD
21:52:20 [INFO]  Multiverse-Core, NBTAPI, PlaceholderAPI, Plan, ProtocolLib, PvPManager, Quests, QuickShop-Hikari, SayanVanish, Shopkeepers
21:52:20 [INFO]  spark, TAB, Tebex, UltimateAutoRestart, UnifiedMetrics, UpgradeableSpawners, Vault, Vehicles, ViaBackwards, ViaVersion
21:52:20 [INFO]  voicechat, VotifierPlus, VotingPlugin, Vulcan, WorldEdit, zAuctionHouseV3, zMenu, ZNPCsPlus

21:52:43 [INFO] There are 5 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [file/ender_dragon-lootable (world)], [file/end_city_treasure-lootable (world)], [paper (built-in)]
21:52:43 [INFO] There are no more data packs available

### Paper version

21:53:01 [INFO] Checking version, please wait...
21:53:02 [INFO] This server is running Paper version 1.21-97-master@e71c1df (2024-07-19T11:57:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21-65-34a2917 (MC: 1.21)

### Other

zipped lootable i used. should add dragon head elytra and rods to the loot but doesent seem to work
[end_city_treasure-lootable.zip](https://github.com/user-attachments/files/16317302/end_city_treasure-lootable.zip)

**Comment by Tizooo** [comment]
use this command to spawn in a chest with the lootable faster :D

/setblock ~ ~ ~ minecraft:chest{LootTable:"minecraft:chests/end_city_treasure"}

**Comment by lynxplay** [comment]
The datapack is simply not updated to 1.21.
It is also incorrectly packaged, you have a top level folder named `end_city_treasure-lootable` in there.
Additionally, the folder is called `loot_table` not `loot_tables`.

With the respective changes, the below pack works fine for me in modifying the loot table 👍 
[end_city_treasure-lootable.zip](https://github.com/user-attachments/files/16319537/end_city_treasure-lootable.zip)
