### ISSUE TITLE
Lag delay to appear items on inventory when picked on the ground

### ISSUE THREAD

**Issue by ElPiigeon** [PaperSpigot/Paper#11120]
### Timings or Profile link

https://spark.lucko.me/wAeTTxWFDM

### Description of issue

Hello, I need help about a little lag in my 1.20.4 server. When i'm playing and pick up some items, these take seconds to appear in the inventory. I need to open my inventory and sometimes even click in the inventory to make appear the items picked.

### Plugin and Datapack List

 **Server Plugins (59):**
**Paper Plugins:**
EconomyShopGUI-Premium
**Bukkit Plugins:**
ActivityRewarder, AuraSkills, AutoBroadcast, BetterRTP, BetterStructures, BlueBridgeCore, BlueBridgeGP, BlueBridgeWG, BlueMap, BlueMap-BannerMarker
BlueMapFloodgate, BlueMapPlayerControl, Chunky, ChunkyBorder, CMILib, CommandPanels, CoreProtect, DeathChest, DecentHolograms, EliteMobs
Essentials, EssentialsChat, EssentialsSpawn, ExecutableItems, ExtraRecipes, floodgate, Geyser-Spigot, GPExtension, GPFlags, GriefPrevention
GSit, Hurricane, InteractionVisualizer, Jobs, JobsReborn-PatchPlaceBreak, LevelledMobs, LightAPI, LightAPI, Lootin, LuckPerms, 
nightcore, ODailyQuests, PlaceholderAPI, PlayerAuctions, PlayerStats, PLAZMER-ENGINE, ProtocolLib, RealScoreboard, SCore, SkinsRestorer, spark, Terra, ToolStats, Vault, ViaVersion, WorldEdit, WorldGuard

### Server config files

```
Paste configs or paste.gg link here!
```
https://paste.gg/p/anonymous/dc566dbe86a743ee944b3e4c83b94ae4 

### Paper version

> version
[09:35:59 INFO]: Checking version, please wait...
[09:36:00 INFO]: This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-493 (MC: 1.20.4)

**Comment by lynxplay** [comment]
Have you tested this behaviour without your plugins installed?
There is a lot of stuff on your server that could be doing things paper has 0 control over.

**Comment by ElPiigeon** [comment]
No i didn't test it without plugins and I do not know how to understand all the stats on spark test. I was wondering if there is clue about the lag, and what can do this type of lag

**Comment by lynxplay** [comment]
No, nothing that would relate to items specifically. Your tps seems fine. Given there isn't really much we can do on GitHub, I'll close this issue.

You can ask in our discord for support with it, maybe someone has ran into this issue before, but the GitHub tracker isn't really the best place to debug this.
