### ISSUE TITLE
Disabling timings doesn't disable timings

### ISSUE THREAD

**Issue by mja00** [PaperSpigot/Paper#11121]
### Expected behavior

Timings to not be enabled when the config is set to disable it.

### Observed/Actual behavior

Timings is still enabled

### Steps/models to reproduce

1. Download fresh server
2. Start server
3. See `Timings reset` at the end of startup
4. Check config to see if its disabed

### Plugin and Datapack List

None

### Paper version

[14:17:28 INFO]: This server is running Paper version 1.21-103-master@aa3b356 (2024-07-20T17:56:20Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-102-aa3b356 (MC: 1.21)

### Other

![Microsoft Edge 2024-07-20 at 14 17 47@2x](https://github.com/user-attachments/assets/82335924-d6a3-48bb-a8eb-0ff5952c162b)
![Microsoft Edge 2024-07-20 at 14 17 56@2x](https://github.com/user-attachments/assets/d7a531c6-c3d7-4b22-a4be-d8e1269547d0)

**Comment by electronicboy** [comment]
That message doesn't mean that it's enabled, just that some reset logic was ran, run `/timings report` to see if it's *actually* enabled or not

**Comment by mja00** [comment]
Ah, I assumed it being disabled would entirely disable it. Gotcha, thanks!
