### ISSUE TITLE
`ArmoredHorseInventory#setArmor` does not function properly

### ISSUE THREAD

**Issue by TonytheMacaroni** [PaperSpigot/Paper#11135]
### Expected behavior

Calling `ArmoredHorseInventory#setArmor` sets the body armor for horses/llamas.

### Observed/Actual behavior

No effect. Armor isn't set for horses, decor item isn't set for llamas.

### Steps/models to reproduce

A simple plugin with the following code:
```java
Player player = ...;

Location location = player.getLocation();
World world = player.getWorld();

// Spawns with no armor
world.spawn(location, Horse.class, horse -> {
    horse.customName(Component.text("Armor", NamedTextColor.GREEN));
    horse.getInventory().setArmor(ItemType.DIAMOND_HORSE_ARMOR.createItemStack());
});

// Spawns with armor
world.spawn(location, Horse.class, horse -> {
    horse.customName(Component.text("Equipment", NamedTextColor.GREEN));
    horse.getEquipment().setItem(EquipmentSlot.BODY, ItemType.DIAMOND_HORSE_ARMOR.createItemStack());
});
```
Reproduces the issue.

### Plugin and Datapack List

Just a test plugin with the code provided earlier in a command.

### Paper version

This server is running Paper version 1.21-107-master@aa36ae6 (2024-07-21T10:39:28Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-89-44c3dd0 (MC: 1.21)

### Other

Issue seems to stem from `CraftInventoryAbstractHorse#setItem` using a slot index of `HorseInventoryMenu.SLOT_BODY_ARMOR`, which has a value of `1`, but `AbstractHorse#getBodyArmorAccess` returns a `ContainerSingleItem`, which uses a slot index of 0.

**Comment by Lulu13022002** [comment]
This is related to https://github.com/PaperMC/Paper/pull/11028, getter doesn't work too. And it's a bit weird that the inventory size of the camel / llama without chest is 2 and not 1. The result of InventoryClickEvent#getSlot is inconsistent for those two cases too llama return 1 and camel return 0. It's also strange that getSaddle/setSaddle is exposed for the llama since they can't hold one.
