### ISSUE TITLE
HIDE_ADDITIONAL_TOOLTIP does not hide record (music disc) names. 

### ISSUE THREAD

**Issue by Navoei** [PaperSpigot/Paper#11141]
### Expected behavior

This item flag should prevent music discs from showing their name.

### Observed/Actual behavior

The record name is still visible in the lore. 

### Steps/models to reproduce

Create a command block where one runs a command to add the item flag. `HIDE_ADDITIONAL_TOOLTIP`.
Example command: `/give @s music_disc_blocks[hide_additional_tooltip={}]`

### Plugin and Datapack List

No plugins or data packs.

### Paper version

This server is running Paper version 1.21-107-master@aa36ae6 (2024-07-21T10:39:28Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-408 (MC: 1.20.4)

**Comment by electronicboy** [comment]
This is handled by the client, we have 0 control over this

**Comment by emilyy-dev** [comment]
You can set show_in_tooltip to false on the disc's JukeboxPlayable https://jd.papermc.io/paper/1.21/org/bukkit/inventory/meta/components/JukeboxPlayableComponent.html#setShowInTooltip(boolean)
