### ISSUE TITLE
End obsidian platform bug

### ISSUE THREAD

**Issue by nikoflora** [PaperSpigot/Paper#11142]
### Expected behavior

I expected the end obsidian platform to break blocks and drop them

### Observed/Actual behavior

I observed the end platform replace the blocks with air instead of breaking them

### Steps/models to reproduce

I was recreating Rayworks's cobblestone farm
https://www.youtube.com/watch?v=NxiaBSG4HjU

### Plugin and Datapack List

 Plugins: ImageFrame, SkinsRestorer, ViaBackwards, ViaVersion
 Datapacks: There are 33 data pack(s) enabled: [vanilla (built-in)], [file/Terralith_1.21_v2.5.4.zip (world)], [file/afk display v1.1.8 (MC 1.21.0).zip (world)], [file/anti creeper grief v1.1.8 (MC 1.21.0).zip (world)], [file/anti enderman grief v1.1.8 (MC 1.21.0).zip (world)], [file/anti ghast grief v1.1.8 (MC 1.21.0).zip (world)], [file/armored elytra v2.0.1 (MC 1.21.0).zip (world)], [file/back v1.3.8 (MC 1.21.0).zip (world)], [file/bukkit (world)], [file/cauldron concrete v3.0.1 (MC 1.21.0).zip (world)], [file/custom nether portals v2.3.11 (MC 1.21.0).zip (world)], [file/double shulker shells v1.3.8 (MC 1.21.0).zip (world)], [file/dragon drops v1.3.8 (MC 1.21.0).zip (world)], [file/durability ping v1.1.8 (MC 1.21.0).zip (world)], [file/ender chest always drops v1.0.0 (MC 1.21.0).zip (world)], [file/glass always drops v1.0.0 (MC 1.21.0).zip (world)], [file/graves v3.0.4 (MC 1.21.0).zip (world)], [file/homes v1.5.10 (MC 1.21.0).zip (world)], [file/more effective tools v1.0.2 (MC 1.21.0).zip (world)], [file/more mob heads v2.14.0 (MC 1.21.0).zip (world)], [file/multiplayer sleep v2.6.8 (MC 1.21.0).zip (world)], [file/player head drops v1.1.8 (MC 1.21.0).zip (world)], [file/timber v2.1.10 (MC 1.21.0).zip (world)], [file/tpa v2.3.8 (MC 1.21.0).zip (world)], [paper (built-in)], [file/Incendium_1.21_DIRECT_PORT_v5.4.0.zip (world)], [file/Nullscape_1.21_v1.2.7.zip (world)], [file/Structory_1.21_v1.3.5.zip (world)], [file/name colors v1.0.6 (MC 1.21.0).zip (world)], [file/real time clock v1.1.8 (MC 1.21.0).zip (world)], [file/spawn v2.3.8 (MC 1.21.0).zip (world)], [file/wandering trades v1.7.6 (MC 1.21.0).zip (world)], [file/chunk loaders v1.0.9 (MC 1.21.0).zip (world)]

### Paper version

This server is running Paper version 1.21-107-master@aa36ae6 (2024-07-21T10:39:28Z) (Implementing API version 1.21-R0.1-SNAPSHOT)\nYou are running the latest version\nPrevious version: 1.21-106-3a47518 (MC: 1.21)

**Comment by lynxplay** [comment]
Accepted, spigot is fucking around as per usual as they call `PortalCreateEvent` for this, which includes first storing all block changes and then applying them post event.
