### ISSUE TITLE
Wind burst enchantment on the mace doesn't work

### ISSUE THREAD

**Issue by NicoNex** [PaperSpigot/Paper#11156]
### Expected behavior

When the mace is enchanted with wind burst it should bounce the player back into the air when an enemy is hit.

### Observed/Actual behavior

The player simply falls onto the ground without bouncing back when they hit an enemy.

### Steps/models to reproduce

Enchant a mace with Wind Burst III and use it falling on an enemy.
I'm using a custom mace created with this command:

```
/give @p mace[custom_name='{"bold":true,"color":"blue","text":"Martellone del Valhalla"}',unbreakable={},enchantments={levels:{"minecraft:bane_of_arthropods":10,"minecraft:breach":10,"minecraft:density":10,"minecraft:smite":10,"minecraft:wind_burst":10}},attribute_modifiers=[{id:"entity_interaction_range",type:"player.entity_interaction_range",amount:10,operation:"add_value"},{id:"jump_strength",type:"generic.jump_strength",amount:3,operation:"add_value"},{id:"safe_fall_distance",type:"generic.safe_fall_distance",amount:1000,operation:"add_value"},{id:"step_height",type:"generic.step_height",amount:1,operation:"add_value"}]] 1
```

### Plugin and Datapack List

[18:09:31 INFO]: Server Plugins (7):
[18:09:31 INFO]: Bukkit Plugins:
[18:09:31 INFO]:  - BlueMap, eBackup, GSit, NexAuth, NexEngine, SkinsRestorer, voicechat

### Paper version

[18:08:52 INFO]: Checking version, please wait...
[18:08:52 INFO]: This server is running Paper version 1.21-109-master@5a5035b (2024-07-23T08:16:30Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-107-aa36ae6 (MC: 1.21)

**Comment by Kadeluxe** [comment]
Works fine

**Comment by NicoNex** [comment]
> Works fine

That's strange because in my vanilla local world the wind burst of the mace generated with the comment I provided works just fine, but in my paper server it doesn't work at all.

**Comment by Malfrador** [comment]
Unable to reproduce with the mace from the command provided, on a server without any plugins on build 109. Its a bit tricky to hit the mob with that much jump height, but it works when fine I manage to hit. 

Are you able to reproduce this without any plugins on the server?

**Comment by kohlrak** [comment]
I found this trying to find out what was going on with my wind charges not working very well... and while filing a bug report, i managed to delete everything and found it was not a paper bug. Deleting small parts of my world until i narrowed the problem down to playerdata..... and then i narrowed it down to my boots.... with blast protection...


https://bugs.mojang.com/browse/MC-272483

**Comment by NicoNex** [comment]
> I found this trying to find out what was going on with my wind charges not working very well... and while filing a bug report, i managed to delete everything and found it was not a paper bug. Deleting small parts of my world until i narrowed the problem down to playerdata..... and then i narrowed it down to my boots.... with blast protection...
> 
> https://bugs.mojang.com/browse/MC-272483

I confirm that this fixed my issue too, so I'm closing this issue.
