### ISSUE TITLE
thrown wind charges use tnt behavior and do explosion damage on collision 

### ISSUE THREAD

**Issue by canaro5** [PaperSpigot/Paper#11153]
### Expected behavior

no damage with knockback to nearby entities on collision

### Observed/Actual behavior

explosion damage to nearby entities on collision

### Steps/models to reproduce

1- host a minehut server on 1.21 with a difficulty higher than peaceful
2- grab a wind charge in creative
3- go in survival and throw the wind charge at your feet
4- death

### Plugin and Datapack List

Skript
SkBee
Multiverse
Essentials

### Paper version

This server is running Paper version 1.21-108-master@73a863b (2024-07-22T13:23:21Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-496 (MC: 1.20.4)

**Comment by kennytv** [comment]
Cannot reproduce

**Comment by Axiumyuyu** [comment]
I also found that wind charge will break blocks at where it explodeed, no matter how the game rule mobgriefing is.

**Comment by Malfrador** [comment]
Unable to reproduce. This likely is a plugin or Minehut issue.

**Comment by AtaraxianWist** [comment]
I don't actually know how to get ahold of the paper version information, but there shouldn't be any datapacks on my server and I have this exact same problem (the problem only occurs on the server, not in singleplayer, and is so far unresponsive to mod and config changes).
