### ISSUE TITLE
Spark Placeholders Don't work with Placeholder API without the Spark PAPI Extension 

### ISSUE THREAD

**Issue by Goinging** [PaperSpigot/Paper#11150]
### Expected behavior

Before spark switched over to being inside paper I had it downloaded and I was using the %spark_tps_5s% placeholder for tps in the DiscordSRV plugin. Before since spark was installed as a plugin its placeholders would automatically work with PAPI without downloading the spark extension. I was expecting this to not change. 

### Observed/Actual behavior

The placeholder did not work at all until I downloaded the spark Papi ecloud extension. 

### Steps/models to reproduce

1. Use a spark placeholder in a different plugin
2. It doesn't function

### Plugin and Datapack List

 Paper Plugins:
 PaperTweaks
Bukkit Plugins:
AdvancedRegionMarket, AntiPopup, AnvilColors, AuctionHouse, ChatFilter, ChestShop, CoreProtect, CustomCommands, DecentHolograms, DiscordSRV, eGlow, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit, GCore, Graves, GriefDefender, GSit, InteractiveChat. InteractiveChatDiscordSrvAddon, InventoryRollbackPlus, LastLoginAPI, LuckPerms, Orebfuscator, packetevents, Pl-Hide-Pro, PlaceholderAPI, *Playtimes, PremiumVanish. ProtocolLib, SimpleMsgPlugin, TAB, Tebex, UltimateAutoRestart, Vault, ViaBackwards, ViaVersion, voicechat, Vulcan, WorldGuard

 There are 5 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)], [file/armor_statues_v2.12.0 (world)], [file/stackable_shulker_boxes-1.1.0+1.21 (world)]

### Paper version

[20:24:05 INFO]: This server is running Paper version 1.21-107-master@aa36ae6 (2024-07-21T10:39:28Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.20.6-145-fe7043e (MC: 1.20.6)

**Comment by electronicboy** [comment]
This is not a bug, we as a server cannot inject into arbitrary plugins as a function

**Comment by MiniDigger** [comment]
in case anybody else finds this via google: the fix is downloading the papi spark extension
