### ISSUE TITLE
Player is spawning on the world spawn instead of their set spawnpoint

### ISSUE THREAD

**Issue by TrueAnalogNoise** [PaperSpigot/Paper#11178]
### Expected behavior

Players are respawning in their positions set with the /spawnpoint command

### Observed/Actual behavior

Players are respawning in the world spawn, with no option to change that

### Steps/models to reproduce

1. Set a spawnpoint on coordinates different than your world spawn, note them down
2. Use the kill command on yourself
3. Observe, where are you going to respawn, compare your current coordinates with the noted custom spawnpoint ones
For setting the spawnpoint, use the /spawnpoint

### Plugin and Datapack List

Plugins: CoreProtect, GSit, ImageMaps, Multiverse-Core, SkinsRestorer, SpigotFixTeamChatPlugin, WorldEdit, WorldEditSelectionVisualizer, WorldGuard
Datapacks: My own works, I can send them over if necessary

### Paper version

This server is running Paper version 1.21-106-master@3a47518 (2024-07-21T02:47:23Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are 5 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-365 (MC: 1.20.4)

### Other

The Paper version I'm using is the newest available in the server hosting I'm using, and I have no way of updating it myself

**Comment by Malfrador** [comment]
You got a plugin modifying the spawn point. Multiverse for example does that by default. 
Not a Paper issue.
