### ISSUE TITLE
Intergrated Spark command execution is being delayed

### ISSUE THREAD

**Issue by fi-xz** [PaperSpigot/Paper#11171]
### Expected behavior

Spark commands should be run right away when the user input is detected.

### Observed/Actual behavior

Spark command is actually taking some time when it's command first executed, regardless of any arguments or typo included in it's argument.

### Steps/models to reproduce

1. Launch a Paper server (latest)
2. Run any Spark command (ex: `spark tps`)
3. Run any Spark command again and you can see it's execution being delayed. Seems like it's not happening all executions.

### Plugin and Datapack List

Plugins:

```
> pl
[21:02:42 INFO]: Server Plugins (0):
```

Datapacks:

```
> datapack list
[21:02:58 INFO]: There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]
[21:02:58 INFO]: There are no more data packs available
```

### Paper version

```
> version
[21:03:25 INFO]: Checking version, please wait...
[21:03:26 INFO]: This server is running Paper version 1.21-109-master@5a5035b (2024-07-23T08:16:30Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
```

### Other
Seems like this issue is reproducible by many people. For reference here's the Discord message URLs on #paper-help channel:
https://discord.com/channels/289587909051416579/289587909051416579/1266299470430212107
https://discord.com/channels/289587909051416579/289587909051416579/1266347820634607689

**Comment by lynxplay** [comment]
Resolved by https://github.com/PaperMC/Paper/commit/e1462a925344bc038818dd88871af0139ee35958
