### ISSUE TITLE
Nether and End chunks stays loaded after player exits

### ISSUE THREAD

**Issue by NormalFall** [PaperSpigot/Paper#11192]
### Expected behavior

When no players are in the nether no chunks are loaded in the nether.

### Observed/Actual behavior

When the last player in the nether exits, the chunks stay loaded until another player enters the dimension.

### Steps/models to reproduce

Enter the nether then exit it. I used a hopper to check if the chunks are still loaded.

### Plugin and Datapack List

None

### Paper version

1.21-117-master@0246a9d (2024-07-29T00:51:10Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### Other

If this is intended behavior would it be possible to add an option to disable it?

**Comment by electronicboy** [comment]
isn't that just upstreams breaking of spawn chunks? using the gamerule in those worlds may deal with that?

**Comment by NormalFall** [comment]
I doubt that its spawn chunk related since I disabled it in paper-world-defaults.yml

**Comment by CatBang** [comment]
> I doubt that its spawn chunk related since I disabled it in paper-world-defaults.yml

since version 1.20.6+, the option "keep-spawn-loaded: false" seems to have been removed from Pape

In the Nether and End dimensions, enter '/gamerule spawnChunkRadius 0' to disable the spawning of chunks.

**Comment by NormalFall** [comment]
Tested it and the chunks are still loaded.

**Comment by electronicboy** [comment]
How are you checking that chunks are still loaded? Everything should of moved over to the game rule after we migrated over to using that, the only real remaining caveat would be plugins

**Comment by NormalFall** [comment]
I used [chunky](https://www.spigotmc.org/resources/chunky.81534/) to check if the chunk was loaded in ram. Always gave me yes. Then i removed chunky dropped items on the ground disconnected + waited 6 mins. All the item despawned.

**Comment by lynxplay** [comment]
I cannot replicate this.
Placed a command block in the nether, had it increment a scoreboard score.

As previously discussed here, if the spawnChunkRadius gamerule isn't 0 in the nether, the chunks will remain loaded.
However, once set to 0, the command block correctly stopped ticking.

Is there any other form of replication steps you can offer here so we can diagnose your issue?

**Comment by NormalFall** [comment]
Using your method made the command block unload in another chunk seems to have the same result as you. Maybe is was residue of the mods that was previously on the server.
