### ISSUE TITLE
Strange corruption

### ISSUE THREAD

**Issue by FewerElk** [PaperSpigot/Paper#11191]
### Stack trace

https://pastebin.com/Nk06BP3i

### Plugin and Datapack List

<img width="414" alt="image" src="https://github.com/user-attachments/assets/0ac306e1-6c86-4e91-8f7f-e3af3639eb6d">
<img width="414" alt="image" src="https://github.com/user-attachments/assets/ed574ef8-1d67-4ab5-89af-795f72446a4a">
(Sorry I am uploading screens because my server is not able to run commands actually)

### Actions to reproduce (if known)

Unknown 

### Paper version

This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)

### Other

The server is blocked in start state when loading a world that I think it is corrupted, but isn’t (the world came from a backup when it worked). I have to kill it to stop it. I had itemsadder and I thought it was the problem but if I remove it and rollback my worlds the issue is still here, so it isn’t (cf issue https://github.com/ItemsAdder/ItemsAdderBlocksInjector/issues/17)

**Comment by FewerElk** [comment]
So have I to upgrade to 1.20.4 ?

**Comment by electronicboy** [comment]
1.20.2 is not supported, downgrading worlds is not supported, and 1.20.4 is pretty much no longer supported either

**Comment by FewerElk** [comment]
So, what are the supported versions ?

**Comment by electronicboy** [comment]
1.21
