### ISSUE TITLE
Wrong assumption about locale being null in the login phase

### ISSUE THREAD

**Issue by metabrixkt** [PaperSpigot/Paper#11203]
### Expected behavior

`ClientboundLoginDisconnect#write(FriendlyByteBuf)` only falls back to `Locale.US` component codec if `buf.adventure$locale` is `null`

### Observed/Actual behavior

`ClientboundLoginDisconnect#write(FriendlyByteBuf)` uses `Locale.US` component codec even when `buf.adventure$locale` is ***not*** `null`

### Steps/models to reproduce

1. Follow [Paper's i18n guide](https://docs.papermc.io/paper/dev/component-api/i18n#resourcebundle): load translations for the custom kick message, e.g.
```properties
# example-plugin_en.properties
example-plugin.kick-message.potato=wen hardfork
```
```properties
# example-plugin_ja.properties
example-plugin.kick-message.potato=ウェン・ハードフォーク
```
2. Create and register a new `ChannelInitializeListener` (this interface is in the server artifact, but :man_shrugging:) that changes sets the channel's `adventure:locale` attribute to some arbitrary Minecraft locale that isn't `Locale.US` (fallback locale):
```java
ChannelInitializeListener listener = channel -> channel.attr(PaperAdventure.LOCALE_ATTRIBUTE).set(new Locale("ja", "JP")); 
ChannelInitializeListenerHolder.addListener(Key.key("example-plugin", "hacky-player-locale-listener"), listener);
```
3. Create a listener that kicks the player with that translation during the login phase, e.g. on `AsyncPlayerPreLoginEvent` or `PlayerLoginEvent`:
```java
@EventHandler(ignoreCancelled = true)
public void onPreLogin(@NotNull AsyncPlayerPreLoginEvent e) {
    e.disallow(
        AsyncPlayerPreLoginEvent.Result.KICK_OTHER,
        Component.translatable("example-plugin.kick-message.potato")
    );
}
```
4. Player is kicked with the reason `wen hardfork`, even though their channel has its `attribute:locale` is set to `ja_JP` locale

### Plugin and Datapack List

None, only the test plugin from "Steps/models to reproduce"

### Paper version

```
> version
[20:08:16 INFO]: Checking version, please wait...
[20:08:16 INFO]: This server is running Paper version 1.21-123-master@0a1be9a (2024-07-31T02:57:35Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-119-100d75a (MC: 1.21)
```

### Other

This happens because there is a wrong assumption made about the locale being `null` in the login phase in `ClientboundLoginDisconnectPacket#write(FriendlyByteBuf)`:
```java
private void write(FriendlyByteBuf buf) {
    // Paper start - Adventure
    // buf.writeUtf(Component.Serializer.toJson(this.reason, RegistryAccess.EMPTY));
    // In the login phase, buf.adventure$locale field is always null
    buf.writeJsonWithCodec(net.minecraft.network.chat.ComponentSerialization.localizedCodec(java.util.Locale.US), this.reason, FriendlyByteBuf.MAX_COMPONENT_STRING_LENGTH);
    // Paper end - Adventure
}
```

One possible fix would be this:
```diff
         // Paper start - Adventure
         // buf.writeUtf(Component.Serializer.toJson(this.reason, RegistryAccess.EMPTY));
         // In the login phase, buf.adventure$locale field is always null
-        buf.writeJsonWithCodec(net.minecraft.network.chat.ComponentSerialization.localizedCodec(java.util.Locale.US), this.reason, FriendlyByteBuf.MAX_COMPONENT_STRING_LENGTH);
+        java.util.Locale bufLocale = buf.adventure$locale;
+        buf.writeJsonWithCodec(net.minecraft.network.chat.ComponentSerialization.localizedCodec(bufLocale == null ? java.util.Locale.US : bufLocale), this.reason, FriendlyByteBuf.MAX_COMPONENT_STRING_LENGTH);
         // Paper end - Adventure
     }
 
```

_I understand that it's an internal API, but that doesn't mean that having an incorrectly working internal API is a good thing_

**Comment by electronicboy** [comment]
The assumption is correct until you hack internals, but, it's such a trivial fix that it's probably just worth dealing with, just, should probably be left as a note that in normal operation, it will be null

**Comment by lynxplay** [comment]
Yea, agree with cat (hence why I moved it to accepted).
Presumably 0 upkeep cost on our end for that diff. It is low priority however.
If you want to contribute such a change, feel free to!
