### ISSUE TITLE
1.21 CreatureSpawnEvent.SpawnReason.TRIAL_SPAWNER doesn't seem to work

### ISSUE THREAD

**Issue by mike3132** [PaperSpigot/Paper#11200]
### Expected behavior

I expect it to print the spawn reason as TRIAL_SPAWNER but it instead prints as DEFAULT
I am trying to modify creatures spawned only from trail spawners using `CreatureSpawnEvent.SpawnReason.TRIAL_SPAWNER`

### Observed/Actual behavior

If you try and use the event `CreatureSpawnEvent.SpawnReason.TRIAL_SPAWNER` in order to modify and detect mobs from trial spawners it doesn't work
https://youtu.be/bMdTV3X8DTw

### Steps/models to reproduce

You can see the code in this video https://youtu.be/bMdTV3X8DTw

### Plugin and Datapack List

https://prnt.sc/Vxx0HmcdJqOM

### Paper version

https://prnt.sc/Kyw29fNx3JCn

**Comment by lynxplay** [comment]
TrialSpawner needs to setup spawnedViaMobSpawner and spawnReason after recuseive load.
