### ISSUE TITLE
HIDE_DYE ItemFlag not working

### ISSUE THREAD

**Issue by RandomTomato** [PaperSpigot/Paper#11212]
### Expected behavior

Hello, when using the newest version of Paper applying DYE to armour with the flag HIDE_DYE doesn't seem to work anymore. Looking into other similar bugs I have seen there is an issue with HIDE_ATTRIBUTES which I don't think seems to affect this as using the code provided below does hide attributes but not the dye (see reference images). Any help would be much appreciated! Thanks 😁

**_Currently looks like this_**
![Image](https://i.imgur.com/NvxvWC4.png)

### Observed/Actual behavior

**_It should look like this_**
![Image](https://i.imgur.com/zFnol0e.png)

### Steps/models to reproduce

```
if (meta instanceof LeatherArmorMeta) {
  ((LeatherArmorMeta) meta).setColor(color);
}
// All other flags seem to work except HIDE_DYE
meta.setAttributeModifiers(material.getDefaultAttributeModifiers());
meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES, ItemFlag.HIDE_UNBREAKABLE, ItemFlag.HIDE_DYE, ItemFlag.HIDE_ENCHANTS);
```

### Plugin and Datapack List

[08:50:07 INFO]:  - AntiPopup, Builders-Utilities, Citizens, CrateReloaded, DailyRewardsPlus, DecentHolograms, Essentials, FastAsyncWorldEdit, HeadDatabase, Images
[08:50:07 INFO]:  ItemJoin, LiteBans, LuckPerms, ModelEngine, Multiverse-Core, PlaceholderAPI, PlayerParticles, PlayerVaults, ProtocolLib, ScavengedShoresAnvilGUI
[08:50:07 INFO]:  ScavengedShoresBuildingUtilities, ScavengedShoresCore, ScavengedShoresVoidGenerator, ScavengedShoresWanderingNPCs, SimplePets, TAB, Vault, WorldGuard

### Paper version

[08:49:33 INFO]: This server is running Paper version 1.21-124-master@df3b654 (2024-08-02T00:02:38Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-108-73a863b (MC: 1.21)

**Comment by lynxplay** [comment]
I am having trouble replicating this with the simple snippet of
```java
final ItemStack stack = ItemStack.of(Material.LEATHER_CHESTPLATE);
stack.editMeta(LeatherArmorMeta.class, l -> {
    l.setColor(Color.AQUA);
    l.setAttributeModifiers(stack.getType().getDefaultAttributeModifiers());
    l.addItemFlags(ItemFlag.HIDE_ATTRIBUTES, ItemFlag.HIDE_UNBREAKABLE, ItemFlag.HIDE_DYE, ItemFlag.HIDE_ENCHANTS);
});
```

The stack correctly hides the dye. Is there a chance any other plugin may be interfering?
Is some other logic messing with this?

**Comment by RandomTomato** [comment]
Hey! After doing some digging and using your snippet the HIDE_DYE flag now (must have been a change in 1.21?) needs to be set after the Color of the dyeable item is set. I must have missed this as it used to work that you could apply the flag whenever and then later set the color and it would still hide the line in the lore. 😅
