### ISSUE TITLE
"Failed to read console input" and "The handle is invalid" error in minecraft server

### ISSUE THREAD

**Issue by wwwaffle965** [PaperSpigot/Paper#11226]
### Stack trace

[latest.log](https://github.com/user-attachments/files/16559455/latest.log)

### Plugin and Datapack List

null

### Actions to reproduce (if known)

Start the server by using the  start.bat file which I downloaded from "how to make your own server" tutorial in internet and also using bukkit file to actually start and see the server logs.

### Paper version

git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4)

### Other

server worked well for 3days but it sent two error logs 
"Failed to read console input"
and
"The handle is invalid"
when I started today

**The .bat file** which is mentioned above includes 
_`java -Xms1G -Xmx1G -jar bukkit.jar pause`_ code 
but it sends the message **"Unable to access jarfile bukkit;.jar"**

**Comment by lynxplay** [comment]
1.20.4 is no longer supported, you may be best off seeking help in our [discord](https://discord.gg/papermc).
