### ISSUE TITLE
Not passing Pose changes on EntityPoseChangeEvent

### ISSUE THREAD

**Issue by AlepandoCR** [PaperSpigot/Paper#11248]
### Expected behavior

It seems like it should detect any pose changes on entities from the Pose enum (public enum Pose {
    STANDING,
    FALL_FLYING,
    SLEEPING,
    SWIMMING,
    SPIN_ATTACK,
    SNEAKING,
    LONG_JUMPING,
    DYING,
    CROAKING,
    USING_TONGUE,
    SITTING,
    ROARING,
    SNIFFING,
    EMERGING,
    DIGGING,
    SLIDING,
    SHOOTING,
    INHALING;)
    
    i think it should detect this changes on every mob that can produce them

### Observed/Actual behavior

im trying to detect a sniffer when diggint through this event

```
@EventHandler
    public void detectSnifferDig(EntityPoseChangeEvent event) {
        Bukkit.getLogger().info("Pose change: " + event.getEntity() + " " + event.getPose());
       if(event.getEntity().getPose().equals(Pose.DIGGING)){
        Bukkit.getLogger().info("Digging detected");
        }
    }
```

I added a general pose debugger just to check on every Pose change
the only outputs are whenever an entity dies
    
[02:03:43 INFO]: Pose change: CraftZombie DYING
[02:05:28 INFO]: Pose change: CraftBat DYING
[02:07:13 INFO]: Pose change: CraftBat DYING

I havent tried with all mobs but the only poses coming through are those

### Steps/models to reproduce

Just debug the EntityPoseChangeEvent and check por poseChanges aside from DYING

### Plugin and Datapack List

I just have FAWE and luckyperms bc its a dev server

### Paper version

This server is running Paper version 1.21.1-12-master@1798e94 (2024-08-12T07:48:10Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-126-7e44684 (MC: 1.21)

(same API version as my plugin)

### Other

I know i can do a loop to detect all loaded sniffers and if theyre digging, but itd be better with this event and also cleaner, IDK if im missunderstanding the usage of EntityPoseChangeEvent so im sorry in advanced if thats the case

**Comment by Lulu13022002** [comment]
The digging pose is not trigger by the sniffer only the warden. And even if it was your event would catch the previous pose (via Entity#getPose()) and not the new pose. You need to check Sniffer#getState however i don't think an event exists for this.

**Comment by AlepandoCR** [comment]
> The digging pose is not trigger by the sniffer only the warden. And even if it was your event would catch the previous pose (via Entity#getPose()) and not the new pose. You need to check Sniffer#getState however i don't think an event exists for this.

I see, thanks for the reply then, it could be greate if digging could also be recognized on the sniffer, as it is for some frog actions, idk if having this here would help to deliver the message or if i should create the suggestion
