### ISSUE TITLE
Server Out Of Memory

### ISSUE THREAD

**Issue by Atomosic** [PaperSpigot/Paper#11258]
### Stack trace

https://paste.ee/p/c25Cz

### Plugin and Datapack List

All plugins have been removed, no datapacks have been installed. 

### Actions to reproduce (if known)

I am unsure of how to reproduce this, I have seen it happen on two servers. 

Server 1) Running 1.21, started happening after some time and no changes, had 16 GB allocated.
Server 2) Started happening after updating from 1.21 to 1.21.1, had 10 GB allocated

### Paper version

Cannot run /version, as the server is unable to start at all. 
Should be build 13 of 1.21.1 

### Other

We have tried many steps, such as resetting the nether, removing all plugins, removing akiars flags, 

The only correlation between the two servers I've seen this on is world size, both are over 15 GB. 
We have limited info on this, as it does not seem to be a widespread issue. 

Servers are ran with Multicraft.

**Comment by Atomosic** [comment]
Our JVM flags: `-javaagent:jar/Log4jPatcher.jar -Dfile.encoding=UTF-8 -Dlog4j2.formatMsgNoLookups=true -DPaper.ignoreJavaVersion=true `

**Comment by electronicboy** [comment]
That was copied from your console, not the latest.log

`-XX:+HeapDumpOnOutOfMemoryError` can be used to generate a dump if it's an actual OOM and not some other weird limit, but, there is nothing useful here for us to diagnose

**Comment by Atomosic** [comment]
The information was sourced directly from the `latest.log` file rather than the console, although I understand the confusion given that I included the OOM error at the end. This error occurs because when the server runs out of memory, it can no longer append to the `latest.log`.

Please find the most recent `latest.log` attached, minus the memory error (which did appear in the server console). You can access it here: [link](https://paste.ee/p/dCK3z#Arf_BH9lcf5H16eZiReXPVT4VEmDaIjQ).

The server is currently unable to start with 16 GB of memory but does manage to start with 32 GB. This seems excessive, particularly for a Paper server.

Here is the [heap dump.](https://drive.google.com/file/d/1Fz1pL2grP5-aYPpXtpggnJ7lef5sbgRr/view?usp=share_link)

**Comment by electronicboy** [comment]
You have 6.2k force loaded chunks
