### ISSUE TITLE
Nether portal linking seems broken

### ISSUE THREAD

**Issue by NonSwag** [PaperSpigot/Paper#11263]
### Expected behavior

Nether portals should be linked
when going through the same portals multiple times, there should be no new portals generated but the same initial two 

### Observed/Actual behavior

After every time I went through a portal, a new one appeared at a different position

![image](https://github.com/user-attachments/assets/6dae9d71-12e3-4a0c-b759-c8a46fdfd516)
![image](https://github.com/user-attachments/assets/305dbb48-4d9b-46a3-8371-af26e5a5978e)

### Steps/models to reproduce

1. Place a nether portal
2. Step through it
3. Repeat two or three times

### Plugin and Datapack List

> pl
[22:30:33 INFO]: Server Plugins (0):

> datapack list
[22:30:35 INFO]: There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]
[22:30:35 INFO]: There are no more data packs available

### Paper version

> ver
[22:30:18 INFO]: Checking version, please wait...
[22:30:18 INFO]: This server is running Paper version 1.21.1-14-master@9ab644e (2024-08-14T12:52:20Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.1-13-7c9240f (MC: 1.21.1)

### Other

Works in vanilla

**Comment by NonSwag** [comment]
The issues lie within the paper-world-defaults.yml
I configured the search and create radius to 0 and forgot about it

![image](https://github.com/user-attachments/assets/4b07974e-103f-4072-8069-7cd33aa1a229)

**Comment by TestnAlpaca37** [comment]
soooo do i need to set it to 0?
