### ISSUE TITLE
Command Target Selector Incorrect

### ISSUE THREAD

**Issue by KKW557** [PaperSpigot/Paper#11269]
### Expected behavior

`/minecraft:tp @a @s`
`/minecraft:kill @e`
not work, the command should accept target selector, 1.21 is working but 1.21.1 broken

### Observed/Actual behavior

```
Incorrect argument for command
tp @a @s<--[HERE]

Selector not allowed
kill @e<--[HERE]
```

### Steps/models to reproduce

use any target selector in vanilla commands

### Plugin and Datapack List

paper only

### Paper version

This server is running Paper version 1.21.1-15-master@11b4ac7 (2024-08-14T19:34:08Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-130-b1b5d4c (MC: 1.21)

### Other

eg /kill PLayerName is work but target selector cant

**Comment by kennytv** [comment]
Cannot reproduce. Are you sure you don't have plugins installed?

**Comment by KKW557** [comment]
check again luckperms bug
