### ISSUE TITLE
getOfflinePlayer() crash method

### ISSUE THREAD

**Issue by CerialPvP** [PaperSpigot/Paper#11277]
### Stack trace

https://paste.gg/p/anonymous/e562b603a8dd47b0874e6aa6beb8e61a

### Plugin and Datapack List

![image](https://github.com/user-attachments/assets/eab30770-3084-4418-8b63-afef04fb7430)

### Actions to reproduce (if known)

(I used Skript to reproduce it (Skript has an offlineplayer function, which internally uses CraftServer#getOfflinePlayer(String), which is what we need.)

1. Simply spam `Bukkit.getOfflinePlayer("fsdfjksfkjsd")`, and enjoy the lag.

### Paper version

Current Purpur Version: 1.21.1-2286-366af80 (MC: 1.21.1)*
* You are 3 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Other

Every single server is vulnerable to this issue.
If a server has a plugin which has a command that uses CraftServer#getOfflinePlayer(String), then a player can spam the command, and crash the server.
A solution I have in mind to this issue is if your server isn't in a shared hosting, and instead hosted in a VPS or dedicated server, you can use [minecraft-cacher](https://github.com/Lucasmellof/minecraft-cacher) and make all outgoing Mojang API requests go through the minecraft-cacher web server.

**Comment by lynxplay** [comment]
If plugins ignore the large warning in the javadocs that these methods call induce network IO, that is on them.
It is a widely known fact to *not* complete profile requests on the main thread.

Solutions like caches can certainly be deployed by plugins, but that is not a feature paper can/should fix.
