### ISSUE TITLE
player.setSimulationDistance(1) doesn't work

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#11288]
### Expected behavior

player's should be able to have a tick view distance of 1, i.e the chunk they are in and all neighbouring chunks or a tick view distnace of 0, just the chunk they are in, 

### Observed/Actual behavior

it seems clamped somewhere to be a minimum of 2 chunks. Setting lower than 2 doesn't throw error or anything it just silently fails.

### Steps/models to reproduce

player.setSimulationDistance(1) (doesn't work) vs player.setSimulationDistance(2) (works)  

### Plugin and Datapack List

Just the plugin for testing player.setSimulationDistance()

### Paper version

This server is running Paper version 1.21.1-DEV-master@52ae4ad (2024-08-17T16:25:23Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are 8 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.1-DEV-7c9240f (MC: 1.21.1)

**Comment by Malfrador** [comment]
This is a limitation of how the chunk system works, the lowest possible for both the simulation-distance and the view-distance is 3 (chunk the player is in + 2). This is also documented in the [config docs.](https://docs.papermc.io/paper/reference/server-properties)
