### ISSUE TITLE
Wither spawn sound radius has no effect

### ISSUE THREAD

**Issue by PhantomCaptain** [PaperSpigot/Paper#11283]
### Expected behavior

Limited sound distance when a wither is spawned and a value is set in spigot.yml forwither-spawn-sound-radius. 

### Observed/Actual behavior

Wither spawning can be heard server-wide.

### Steps/models to reproduce

Set the value of wither-spawn-sound-radius to 32. Have another account 500+ blocks away. Spawn a wither. Run on a vanilla sever with 0 plugins.

### Plugin and Datapack List

VentureChat, DeluxeCommands, CommandCooldown, ServerListPlus, MOTD, ProtocolLib, packetevents.

### Paper version

This server is running Paper version 1.21.1-26-master@52ae4ad (2024-08-16T22:44:55Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT

**Comment by electronicboy** [comment]
I think that the configured radius is only taken into account when you have the global sounds or whatever it was called gamerule disabled

**Comment by PhantomCaptain** [comment]
Thanks will check this is set to false.

**Comment by PhantomCaptain** [comment]
> I think that the configured radius is only taken into account when you have the global sounds or whatever it was called gamerule disabled

Yes this is set and the sound continues.

**Comment by Machine-Maker** [comment]
I cannot replicate that. I have the `wither-spawn-sound-radius` set to 0 in `spigot.yml` and the gamerule `globalSoundEvents` set to false. Other players cannot hear it outside of the default range of 64 blocks. With the gamerule set to false, players in the same world within the 64 block radius (default to vanilla mc) will hear it.

**Comment by Spottedleaf** [comment]
Please verify that you have set the gamerule in the applicable dimensions, as /gamerule only affects the current world (overworld if ran from console).

**Comment by PhantomCaptain** [comment]
Command was run from the console and has since been rectified. Thank you
