### ISSUE TITLE
BlockDispenseEvent#setItem no longer removes the original item being dispensed

### ISSUE THREAD

**Issue by PlayfulPotato** [PaperSpigot/Paper#11281]
### Expected behavior

Using the method should replace the item being dispensed while still consuming the item that it was dispensing, this is the original behavior as it always has been.

### Observed/Actual behavior

The block (a dispenser in my case) shoots out the set item, while also still keeping the item that should have been replaced in its inventory.

### Steps/models to reproduce

Try attempting to set the item that a dispenser shoots out, it will both shoot out the new item and keep the old one.

### Plugin and Datapack List

Plugins (Both of which were created by me):
 - Celebratory
 - NotQuiteModded

Datapacks:
- vanilla (built-in)
- file/bukkit (world)
- paper (built-in)

### Paper version

This server is running Paper version 1.21.1-26-master@52ae4ad (2024-08-16T22:44:55Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-5-7d7f123 (MC: 1.21.1)

**Comment by Machine-Maker** [comment]
@PlayfulPotato what item type are you trying to dispense? Recently, we standardized this behavior because it was inconsistent across different items being dispensed. Some items didn't decrease the original stack if the item changed, some did.

**Comment by PlayfulPotato** [comment]
> @PlayfulPotato what item type are you trying to dispense? Recently, we standardized this behavior because it was inconsistent across different items being dispensed. Some items didn't decrease the original stack if the item changed, some did.

Is this in reference to what the original item, or what I am changing it to? 
Either way, the original item is a blaze rod, and the item I am trying to change it to is an ItemStack with air as the material to attempt to mimic the effect of the item actually being used, as it is a blaze rod with PDC being treated as a "custom item." Of course, if this is decided to be working as intended I definitely can just replicate the behavior more manually, but it becomes a bit more troublesome that way.

**Comment by Machine-Maker** [comment]
When did this work to begin with? I'm not seeing any recent diff to the relevant code for your example that would cause any changes. In fact, in my test on 1.18.2, setting the item to an air stack actually throws an exception and crashes the server. Setting it to a non-air item dispenses that non-air item and doesn't decrease the stack of blaze rods inside the dispenser.

**Comment by PlayfulPotato** [comment]
> When did this work to begin with? I'm not seeing any recent diff to the relevant code for your example that would cause any changes. In fact, in my test on 1.18.2, setting the item to an air stack actually throws an exception and crashes the server. Setting it to a non-air item dispenses that non-air item and doesn't decrease the stack of blaze rods inside the dispenser.

I misrembered how I was doing this that's my bad. I probably should have checked before responding with what I remember. What I actually would do is make an ItemStack with the same material as the one it was trying to dispense with a count of 0. Which is technically dangerous and not allowed, I know. But it allowed for easy replication of the dispenser firing something. Either way, I can just replicate the effect manually.

**Comment by Machine-Maker** [comment]
Going to close this then. I've got some API in the pipeline to allow for more control over the "result" of a dispense, like if an item should be consumed or not, but its still in development. Until then, just replicate the sound/particle effect.
