### ISSUE TITLE
Upgraded from 1.19.3 to 1.21.1 Ignored Advancement and cannot load unrecognized recipe

### ISSUE THREAD

**Issue by maxinetakeba** [PaperSpigot/Paper#11290]
### Expected behavior

No logs

### Observed/Actual behavior

![image](https://github.com/user-attachments/assets/725d608c-3215-4366-9d52-56c476be9a06)

### Steps/models to reproduce

Have a PaperMC on 1.19.3.
Upgrade to 1.21.1

### Plugin and Datapack List

`
> plugins
[06:20:24 INFO]: Server Plugins (2):
[06:20:24 INFO]: Bukkit Plugins:
[06:20:24 INFO]:  - DiscordSRV, GravesX
>`

### Paper version
`
>[06:20:40 INFO]: This server is running Paper version 1.21.1-15-master@11b4ac7 (2024-08-14T19:34:08Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are 18 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-431 (MC: 1.19.3)
`

### Other

I get the feeling that this is a repeat of https://github.com/PaperMC/Paper/issues/5995.

Just need to know if I need to worry or if I should roll back and upgrade slowly instead of a big jump.

I also know that I am 18 snapshots behind... but I imagine this isn't relevant(yes I will update 😉).

**Comment by Brokkonaut** [comment]
You can safely ignore those messages

**Comment by maxinetakeba** [comment]
> You can safely ignore those messages

Thanks.

Will mark as closed then.

**Comment by maxinetakeba** [comment]
>closing
