### ISSUE TITLE
Player#GetLocation() has empty direction.

### ISSUE THREAD

**Issue by iseal56** [PaperSpigot/Paper#11293]
### Expected behavior

Player#GetLocation()#GetDirection() reporting the correct direction

### Observed/Actual behavior

Player#GetLocation()#GetDirection() reports 0.0 yaw and 0.0 pitch, always.

### Steps/models to reproduce

https://github.com/user-attachments/assets/0d7a1418-96a6-4834-b685-42aa085e1314

### Plugin and Datapack List

Only my own plugin, [PowerGems](https://github.com/ISeal-plugin-developement/PowerGems)

### Paper version

This server is running Paper version 1.21.1-33-master@64c9ee6 (2024-08-17T21:46:09Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-13-7c9240f (MC: 1.21.1)

**Comment by kennytv** [comment]
Direction doesn't have yaw and pitch, it's an three dimensional vector

**Comment by iseal56** [comment]
Yeah, sorry for the error in the title. It returns an empty vector.

**Comment by kennytv** [comment]
It looks like you're looking down an axis, so `0, 0, 1` seems fine? maybe I'm missing something in the video

**Comment by iseal56** [comment]
Hold on, I'll make another video with me looking somewhere else. thats kind of a bad video because I'm working remotely and minecraft doesnt work well like this.

https://github.com/user-attachments/assets/e1689e45-6b9e-46bd-a761-5c71b1f9e1a6

Again, sorry if it's a problem with my code but i've been looking at this for a couple of days and couldnt find any issues (i know my code is bad)

**Comment by iseal56** [comment]
The issue does not seem to be reproducible on spigot 1.20.6. I'll try to test 1.20.1

**Comment by iseal56** [comment]
On spigot 1.21.1 (sorry for the typo earlier) the direction is correct when accessed, and then the head gets turned.

**Comment by Machine-Maker** [comment]
What event are you listening to where you are then checking the direction? I cannot reproduce this with a simple listener to `PlayerInteractEvent` and then printing out the `player.getLocation().getDirection()` to the stdout.

```java
    @EventHandler
    public void onEvent(PlayerInteractEvent event) {
        if (event.getHand() != EquipmentSlot.HAND) {
            return;
        }
        if (event.getItem() == null || event.getItem().getType() != Material.STICK) {
            return;
        }

        System.out.println(event.getPlayer().getLocation().getDirection());
    }
```
All of the logs show non-zero direction vectors.

**Comment by iseal56** [comment]
I've tested this with some other people, and it only seems to happen on the servers on my machine? Or my account? I have to look more into it, for now, you can close this.

**Comment by bergerkiller** [comment]
I just ran into this same issue, but it was because I was injecting a received (spigot name) PacketPlayInBlockPlace packet without setting the 1.21 introduced xRot/yRot fields. You don't list any of my plugins though, so I'm not sure if it's the same issue.
