### ISSUE TITLE
Chunk generators only affect the center chunk

### ISSUE THREAD

**Issue by KillerCreeper112** [PaperSpigot/Paper#11316]
### Expected behavior

The entire world should be all stone.

### Observed/Actual behavior

Only the center chunk (0, 0) was all stone. The other chunks that were generated did not seem like anything was changed through the custom chunk generator.

This image shows the result of using TestGen on a newly created world. To be clear, the ores, dirt, gravel, and water were not added in via the custom TestGen generator. But I believe that is working as intended because shouldGenerateDecorations is set to true so it adds vanilla's decorations after all the main generation was complete.
![image](https://github.com/user-attachments/assets/419a91d8-5442-4937-bf1e-2ac3b463a879)

This image shows the result when I edited the TestGen code to set diamond blocks instead of stone and all of the "should..." methods were set to false.
![image](https://github.com/user-attachments/assets/9af7c9e2-7c40-4885-89ca-15f3d623132f)

### Steps/models to reproduce

I created the world like so:
`new WorldCreator(worldName).generator(new TestGen()).createWorld();`

TestGen code:
https://pastebin.com/f1qsEXAY

### Plugin and Datapack List

LuckPerms, FastAsyncWorldEdit, ViaVersion, ViaBackwards, CustomPlugin

### Paper version

This server is running Paper version 1.21.1-40-master@2fdb2e9 (2024-08-21T01:35:33Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-130-b1b5d4c (MC: 1.21)

### Other

In this case, I was overriding the generateCaves method specifically because it is stated that it is the last step in generation. But I've also tried overriding generateSurface, generateBedrock, and generateNoise. All seemed to produce the same result.

**Comment by emilyy-dev** [comment]
`ChunkData#setBlock(int, int, int, Material)` takes x/z coordinates relative to the chunk [0-16), not absolute in the world as you are doing `int x = (chunkX << 4) + offsetX`.

**Comment by KillerCreeper112** [comment]
Oh man, I'm sorry. I even read that too and didn't think anything of it. Thank you!
