### ISSUE TITLE
Randomized structure seeds don't work

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#11319]
### Expected behavior

When you change the seed for portals or villages in spigot.yml, you shouldn't be able to find villages with chunk base and the world seed

### Observed/Actual behavior

Changing seed-village etc in spigot.yml has 0 effect

### Steps/models to reproduce

make a world with a 32 bit seed (i dont think the issue is because the world has a 32 bit seed, but just to be sure)
set seed-village in spigot.yml to anything you like
load the world on chunkbase and search for villages, teleporting to them will always have a village.

### Plugin and Datapack List

N/A

### Paper version

This server is running Paper version 1.21.1-DEV-master@b4bc512 (2024-08-18T22:23:43Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are 8 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.1-DEV-52ae4ad (MC: 1.21.1)

**Comment by Machine-Maker** [comment]
Well wait, you generated the world before setting the seed in spigot.yml?

**Comment by Machine-Maker** [comment]
I cannot replicate this. I created a world with the seed `-2037834715355701356`, teleported to the village at `/tp -976 ~ -512`, stopped the server, changed the village seed to `98238390`, started the server, and teleported to another *alleged* village (according to chunkbase) at `/tp 816 ~ -768`, and there was no village in sight.
