### ISSUE TITLE
Error when using datapacks for paper

### ISSUE THREAD

**Issue by ehgns1156** [PaperSpigot/Paper#11342]
### Stack trace

```
[paste your stack trace or a paste.gg link here!](https://paste.gg/p/anonymous/0f3dfd9ca8ab46a4b9f4adce840847b5)
```

### Plugin and Datapack List

X

### Paper version

[04:19:34 INFO]: Checking version, please wait...
[04:19:35 INFO]: Current: git-Purpur-1985 (MC: 1.19.4)*
Previous: git-Paper-550 (MC: 1.19.4)
* You are running the latest version

**Comment by Owen1212055** [comment]
Purpur 1.19.4 is not supported.
