### ISSUE TITLE
Performing username validation

### ISSUE THREAD

**Issue by miryaev** [PaperSpigot/Paper#11349]
### Expected behavior

When changing the value of "perform-username-validation" from true to false, I expected to see that when I try to log in with a Cyrillic nickname, I will successfully log in to the server and be able to play.

### Observed/Actual behavior

When I tried to log in, I saw the message "Failed to verify username!". I was not allowed to access the server, and I saw warnings in the console.

> [13:38:07 INFO]: Disconnecting Миряев (/95.131.78.56:55886): Failed to verify username!
> [13:38:07 WARN]: Exception verifying Миряев
> java.lang.IllegalArgumentException: The name of the profile contains invalid characters: Миряев
>         at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218) ~[guava-32.1.2-jre.jar:?]
>         at com.destroystokyo.paper.profile.CraftPlayerProfile.createAuthLibProfile(CraftPlayerProfile.java:274) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
>         at com.destroystokyo.paper.profile.CraftPlayerProfile.<init>(CraftPlayerProfile.java:41) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
>         at com.destroystokyo.paper.profile.CraftPlayerProfile.clone(CraftPlayerProfile.java:166) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
>         at com.destroystokyo.paper.profile.CraftPlayerProfile.asAuthlibCopy(CraftPlayerProfile.java:301) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
>         at net.minecraft.server.network.ServerLoginPacketListenerImpl.callPlayerPreLoginEvents(ServerLoginPacketListenerImpl.java:368) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
>         at net.minecraft.server.network.ServerLoginPacketListenerImpl$1.run(ServerLoginPacketListenerImpl.java:205) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
>         at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
> [13:38:07 INFO]: Миряев (/95.131.78.56:55886) lost connection: Failed to verify username!

### Steps/models to reproduce

- Download the core: Paper 1.20.6 b149 (latest version)
- Start the server and accept the Eula
1. Change the "perform-username-validation" value in the "config/paper-global.yml" file from true to false.
2. Start the server.
3. Log in to the server for example with a Cyrillic nickname.
- When trying to log in, we receive the message "Failed to verify username!"

### Plugin and Datapack List

> pl
[13:44:57 INFO]: Server Plugins (2):
[13:44:57 INFO]: Bukkit Plugins:
[13:44:57 INFO]:  - ViaBackwards, ViaVersion

### Paper version

> version
[13:35:18 INFO]: Checking version, please wait...
[13:35:18 INFO]: This server is running Paper version 1.20.6-149-ver/1.20.6@6e71f41 (2024-08-24T09:37:06Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version

**Comment by electronicboy** [comment]
This option disables the stricter character requirements that paper imposes on joining usernames, it does not disable mojangs own checks which are enforced in various places, you are still expected to conform to mojangs limitations here.

**Comment by miryaev** [comment]
Ok
