### ISSUE TITLE
Statistic#MINE_BLOCK increments multiple times for crops

### ISSUE THREAD

**Issue by Oribuin** [PaperSpigot/Paper#11340]
### Expected behavior

Breaking a single crop will make the statistic for global block increment by one.

### Observed/Actual behavior

When breaking crops, the global value statistic increments by 2-4 times every time they're broken but the material-unique statistic increments only once. 

Netherwart = 3
Carrot = 2
Wheat = 3
Beet = 2
Potato = 2

![VIsual Example](https://i.gyazo.com/923cd6db21bcad5b2664f44b3f472b45.gif)

### Steps/models to reproduce

Break crops in survival mode, watch the global statistic increase several times at once

### Plugin and Datapack List

PlaceholderAPI, ViaBackwards, ViaVersion

PlaceholderAPI is used to display the statistic easily and viaversion/viabackwards because i was on 1.20.4 client, although still it still persists without them.

### Paper version

> version
[16:27:49 INFO]: Checking version, please wait...
[16:27:50 INFO]: This server is running Paper version 1.21.1-52-master@e08e667 (2024-08-26T18:02:06Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-126-7e44684 (MC: 1.21)

**Comment by Machine-Maker** [comment]
I'm not sure I understand what you are saying for the "global" stat vs "material-unique" stat. I know that the API's `Statistic#MINE_BLOCK` should be checked with a material. So I don't know what would be the non-"material-unique" version of that stat. Can you provide some exact reproduction code that logs out the values that I can test out?

**Comment by Oribuin** [comment]
It's specifically using `Player#getStatistic(Statistic.MINE_BLOCK)`, Which should result in the total blocks mined by the player or atleast thats my understanding of it. 
```java
public class BlockListener implements Listener {

    @EventHandler(ignoreCancelled = true)
    public void onBreak(BlockBreakEvent event) {
        Player player = event.getPlayer();
        int totalBroken = player.getStatistic(Statistic.MINE_BLOCK);
        int brokenSpecific = player.getStatistic(Statistic.MINE_BLOCK, event.getBlock().getType());

        player.sendMessage(Component.text("Total Blocks Broken: x" + totalBroken));
        player.sendMessage(Component.text("Broken " + event.getBlock().getType().name() + ": x" + brokenSpecific));
    }

}

```

**Comment by Machine-Maker** [comment]
Yeah, that code will throw an exception on runtime. You cannot get the stat for MINE_BLOCK without providing a block type. It throws an exception otherwise. It seems to work fine otherwise. Closing as an invalid issue.
