### ISSUE TITLE
Calling "Player#spigot#respawn" in EntityDeathEvent after Logging Out Throws NPE

### ISSUE THREAD

**Issue by PulseBeat02** [PaperSpigot/Paper#11352]
### Expected behavior

I expected using the `player.spigot().respawn()` method to not throw a NPE regardless, and respawn the player regardless of their state. It seems that the `DimensionTransition` stuff is relatively new and probably not handled correctly somehow.

### Observed/Actual behavior

Instead, the server threw a NPE (https://paste.helpch.at/iritoqudur.css), complaining the following:
`java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.portal.DimensionTransition.pos()" because "dimensiontransition" is null`

### Steps/models to reproduce

1) Register an event listener for `PlayerQuitEvent`. In that event, kill the player by setting their health to 0f or `player.setHealth(0f)`
2) Register an event listener for `EntityDeathEvent`. In that event, check that the `Entity` is a `Player` and then use `player.spigot().respawn()` to attempt to respawn the player.
3) In-game, log out and check the error in console.

### Plugin and Datapack List

WorldEdit, Citizens, LuckPerms, [MurderRun](https://github.com/PulseBeat02/MurderRun) (my plugin)

### Paper version

```
[11:06:27 INFO]: Checking version, please wait...
[11:06:27 INFO]: This server is running Paper version 1.21.1-57-master@b483da4 (2024-09-01T18:09:05Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
```
(I am using the runServer task)

**Comment by Doc94** [comment]
But if the player "quit" you can respawn?
i mean the respawn can handle a check for online for avoid the NPE but not sure if use respawn in the context of player die in quit is valid too

**Comment by PulseBeat02** [comment]
> But if the player "quit" you can respawn? i mean the respawn can handle a check for online for avoid the NPE but not sure if use respawn in the context of player die in quit is valid too

I'm not sure, that's subjective. But imo it shouldn't throw an exception either way. I fixed it easily by marking the player when they log out and making sure to not call `player.spigot.respawn()` as the log out, but if another plugin (let's say some combat plugin) doesn't check this, it could run into this NPE. Also, this NPE is related to `DimensionTransition`, which is relatively new and I don't think this bug was there in previous versions. Thus, that's why I think it should be fixed (maybe like a simple null check for ex).

**Comment by Lulu13022002** [comment]
yep i seen that NPE while doing my previous pr. Would be better if spigot move that dimensionTransition check in the right place. I don't really like this api generally and the current respawn logic.
A more direct way to replicate this is just to kick the player in the respawn event.

**Comment by Doc94** [comment]
For futre maybe a better respawn method?
But currently i fix i think is just handle better the check for the respawn method for not call in this cases...
