### ISSUE TITLE
Redstone build breaks after updating paper to the newest 1.21 build

### ISSUE THREAD

**Issue by ParaliyzedEvo** [PaperSpigot/Paper#11356]
### Expected behavior

https://github.com/user-attachments/assets/11631436-11ca-4bfd-af5d-a2c39194590e

Timestamp: 0:27

### Observed/Actual behavior

The redstone build breaks and does not open or close properly as shown in the video.

### Steps/models to reproduce

1. Start a server using the latest paper build (paper-1.21-57)
2. Load into world and paste in the [schem](https://github.com/user-attachments/files/16842742/hidden.zip) file
3. Flick the lever that's on one of the side and you should see it doesn't work

### Plugin and Datapack List

Plugins:
PaperTweaks, TreasureMapsPlus, AntiRaidFarm, AntiVillagerLag, *BannerBoard, Chunky, ClaimChunk, ClearLag, ClearLagTimer, DecentHolograms, dynmap, EntityDetection, Essentials, EssentialsChat, EssentialsSpawn, floodgate, FreedomChat, Geyser-Spigot, Insights, LightAPI, LPC, LuckPerms, Magic, Maintenance, MiniMOTD, MobLimit, NametagEdit, NoEncryption, OpenInv, Otherside, PiggyBack, PlaceholderAPI, ProtocolLib, RandomTeleport, SimpleTpa, Skoice, spark, StaffPlus, TabTPS, TooManyGen, TreeAssist, Vault, VentureChat, ViaBackwards, ViaRewind, ViaVersion, WaystonesPlus, WorldEdit, WorldGuard

Datapacks:
[vanilla (built-in)], [file/banner-flags-v2-5 (world)], [file/bukkit (world)], [file/cavernous-r-v2-1-4 (world)], [file/From-The-Fog-1.20.5-1.20.6-v1.9.3-Data-Resource-Pack (world)], [file/towns-and-towers-1-13-2-version-1-20-x-1-21-x (world)], [file/Creatures+3.0 (world)], [file/Nullscape_1.21_v1.2.7 (world)], [file/Structory_1.21_v1.3.5 (world)], [file/Terralith_1.21_v2.5.5 (world)], [paper (built-in)]

### Paper version

[21:38:59 INFO]: Checking version, please wait...
[21:39:00 INFO]: This server is running Paper version 1.21.1-57-master@b483da4 (2024-09-01T18:09:05Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-39-3271119 (MC: 1.21.1)

### Other

No I did not put/update any plugins before updating the server to the newest version except adding piggyback, but I don't think that should interfere with redstone. Also I did add new datapacks regarding worldgen, but the chunk the build was in was already loaded and rendered so I don't think the datapacks did anything to it. Plugins and the datapacks I listed shouldn't (I hope?) mess with the redstone part of Minecraft as it worked before the paper update, but like I said I didn't update the plugins and the datapacks so I don't think it would be causing the issue listed. Also, I didn't change the configs before updating the server to the new paper build and only changed them back when the server was in 1.20.1. I hope this isn't just a me issue as I run the server locally on my machine and tps is sometimes behind, but I don't have any other way of running the server other than some free hosting that's probably worse than my hardware. If you need configs or any additional information, I would be glad to give you as soon as I can.

**Comment by Machine-Maker** [comment]
Which Redstone implementation are you using (set in the paper configs)?

**Comment by SpaceWalkerRS** [comment]
I tested the schematic in a Fabric environment, and it worked just fine with Vanilla, Eigencraft, and Alternate Current redstone.

**Comment by SpaceWalkerRS** [comment]
just tested the schematic on a fresh Paper server (no plugins) with all three implementations as well, worked with all 3 redstone implementations

**Comment by Machine-Maker** [comment]
Ok, gonna close as cannot reproduce then. It's probably a plugin or datapack messing with something. Try removing some and seeing if you can find the cause.

**Comment by ParaliyzedEvo** [comment]
> Ok, gonna close as cannot reproduce then. It's probably a plugin or datapack messing with something. Try removing some and seeing if you can find the cause.

Hmm if you cant reproduce it actually might be a plugin or datapack, but thanks for the help!
