### ISSUE TITLE
updated 1.21 feature is not applied

### ISSUE THREAD

**Issue by muse918** [PaperSpigot/Paper#11374]
### Expected behavior

Blocks that placed in End Platform drop items when End Platform generated

### Observed/Actual behavior

Blocks don't drop items

### Steps/models to reproduce

https://www.minecraft.net/en-us/article/minecraft-1-21-pre-release-1
https://minecraft.wiki/w/End_platform

place block in obsidian platform and re-enter end portal

### Plugin and Datapack List

Nothing

### Paper version

[18:21:51 INFO]: Checking version, please wait...
[18:21:52 INFO]: This server is running Paper version 1.21.1-69-master@925c3b9 (2024-09-07T20:43:21Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version

**Comment by lynxplay** [comment]
I cannot replicate this, blocks drop correctly for me.
Additionally, https://github.com/PaperMC/Paper/issues/11142 was already reported and fixed.

Do you have any other replication steps?

**Comment by muse918** [comment]
oops i made some mistake while checking bug.
I checked again, it worked correctly.
