### ISSUE TITLE
PlayerItemBreakEvent does not fire in 1.21.1

### ISSUE THREAD

**Issue by Darkmager** [PaperSpigot/Paper#11383]
### Expected behavior

Should Work in 1.21.1

### Observed/Actual behavior

does not work

### Steps/models to reproduce

check for player item break event

### Plugin and Datapack List

none

### Paper version

1.21.1-74-master@971a7a5

**Comment by kennytv** [comment]
Did you actually test this or only look at the Spigot issue?

**Comment by uRyanxD** [comment]
CraftBukkit fixed this 8 hours ago
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/ba21e94725b89670f6565070492c61c75fa02f33#nms-patches%2Fnet%2Fminecraft%2Fworld%2Fitem%2FItemStack.patch

> Did you actually test this or only look at the Spigot issue? Because I'm fairly sure we fixed this months ago

**Comment by kennytv** [comment]
Yeah, but we [fixed it in July](https://github.com/PaperMC/Paper/blob/971a7a5511b3c656b96a9be66ec9848915eb6d3d/patches/server/1033-Correctly-call-PlayerItemBreakEvent.patch#L4), as with many other upstream issues. Please do not open issues if you haven't tested it on Paper.
