### ISSUE TITLE
PlayerItemBreakEvent does not fire  in 1.21+ 

### ISSUE THREAD

**Issue by Darkmager** [PaperSpigot/Paper#11382]
### Expected behavior

Should Work in 1.21+ as it was working in 1.20

### Observed/Actual behavior

does not work

### Steps/models to reproduce

check for player item break event

### Plugin and Datapack List

none

### Paper version

1.21-2256-de2e7a7

### Other

recently spigot issued a fix
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/ba21e94725b89670f6565070492c61c75fa02f33#nms-patches%2Fnet%2Fminecraft%2Fworld%2Fitem%2FItemStack.patch

**Comment by Machine-Maker** [comment]
> 1.21-2256-de2e7a7

This is not a valid paper version. Also, 1.21 isn't supported.
