### ISSUE TITLE
Remove moving sound when multiple entities are at spawn

### ISSUE THREAD

**Issue by Elikill58** [PaperSpigot/Paper#11389]
### Expected behavior

No sound

### Observed/Actual behavior

When multiple players (in the video, 2 or 3) are at the same location without moving, there is the annoying moving sound.

**Sound ON**: https://www.youtube.com/watch?v=fZLvVHeJDxQ

### Steps/models to reproduce

Join multiple account on same server, spawned at same location (and keep them on same block)

### Plugin and Datapack List

Can be done without plugin

### Paper version

This server is running Paper version 1.21.1-76-master@e945cfe (2024-09-10T17:56:53Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version

### Other

I think this can be related to collisions. It appear with this option disabled.

**Comment by Malfrador** [comment]
Can reproduce. When collisions are disabled, standing inside another player causes the step sound to loop infinitely. 
Additionally, the `minecraft:walk_one_cm` increases for both players, despite standing still.
