### ISSUE TITLE
Setting itemstack amount to 0

### ISSUE THREAD

**Issue by JHarris12345** [PaperSpigot/Paper#11392]
### Expected behavior

In pre 1.21 if you create an item stack with amount 0 then it simply removes the item. But in 1.21 it throws an error. Is this ability to remove an item something that can return or is it gone for good? I use this method of setting the amount to 0 a lot for my "limited use" items that deplete after each use. So it's easy for me to just set the amount to currentUses - 1. Here's a screenshot of the error https://gyazo.com/19a00bb855851bcb4aeb99a951ff93b8

### Observed/Actual behavior

It should remove the item (like it used to) and not throw an error

### Steps/models to reproduce

Set an item's amount to 0

### Plugin and Datapack List

N/A

### Paper version

Any 1.21 ver

**Comment by JHarris12345** [comment]
It created an air item stack if you tried to make one with amount 0 in pre 1.21. I am just asking if it's possible to get this back in 1.21 as it was a nice feature and saves needing to change all the code xD

**Comment by electronicboy** [comment]
ItemStack type is immutable in vanilla, and the goal here is generally to confirm closer to vanilla archtypes here, especially with ItemMeta already having caused general issues around changing types, which will only get to become more fun as people dive into components for doing stuff
