### ISSUE TITLE
Items in lazy chunks continue to age until they despawn

### ISSUE THREAD

**Issue by Kroojel** [PaperSpigot/Paper#11404]
### Expected behavior

Items in lazy chunks should not age

### Observed/Actual behavior

The item age stays consistent until the chunks are fully loaded, then increases by how many ticks passed since the item last ticked

### Steps/models to reproduce

- Go into a non-spawn chunk
- /forceload add ~ ~
- throw an item 2 chunks away
  - If you would like to track the item do /data modify entity @n[type=minecraft:item] Health set value 10s
  - And to see the age /data get entity @n[type=minecraft:item,nbt={Health:10s}] Age
- go in the nether to unload the chunks (or far away)
- wait (or tick warp) 2000 ticks
- return to see the age update to be 2000 higher than it was 1 tick ago (if over 6000 the item will despawn as expected)

### Plugin and Datapack List

No plugins

No datapacks

### Paper version

This server is running Paper version 1.21.1-77-master@4ff58c4 (2024-09-12T18:05:09Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version

**Comment by lynxplay** [comment]
Replicable and apparently an "intentional change done by craftbukkit *a long long time ago*.
Does not mean that this behaviour is correct, but changes from 2013 are a bit before my time so will need some more team inputs.
