### ISSUE TITLE
My plugin stopped working

### ISSUE THREAD

**Issue by foxya27** [PaperSpigot/Paper#11411]
### Expected behavior

I have a self-written plugin UsefulWanderingTrader and it worked on Purpur 2306 version

### Observed/Actual behavior

![image](https://github.com/user-attachments/assets/d58e4291-6549-487c-8908-e8107f182bb7)

### Steps/models to reproduce

Install the plugin and start the server

### Plugin and Datapack List

![image](https://github.com/user-attachments/assets/91502bfb-906c-4a65-b10d-3977507a8f3e)

### Paper version

Current Purpur Version: 1.21.1-2306-bc7bcbb (MC: 1.21.1)*
* You are 2 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous: 1.21.1-2308-8332fa4 (MC: 1.21.1)

### Other

I had to go back to the previous version again for the plugin to work, this is not a PurPur mistake, they just made the last 2 versions upstream
![image](https://github.com/user-attachments/assets/9e21b342-0afa-4d9b-a808-b14ca89026d1)

**Comment by foxya27** [comment]
[UsefulWanderingTrader-1.4.0-SNAPSHOT.zip](https://github.com/user-attachments/files/17025747/UsefulWanderingTrader-1.4.0-SNAPSHOT.zip)
This plugin

**Comment by foxya27** [comment]
> Spigot made a type change inside of internals, use the API

Does this mean that the entire plugin will need to be rewritten?

**Comment by electronicboy** [comment]
No, not unless you're performing such digging into internals all over the place. The API already covers the ability to mess with game profiles and has for years.

**Comment by foxya27** [comment]
> No, not unless you're performing such digging into internals all over the place. The API already covers the ability to mess with game profiles and has for years.

**Comment by foxya27** [comment]
> No, not unless you're performing such digging into internals all over the place. The API already covers the ability to mess with game profiles and has for years.

I know that one of those lines causing error: 
Field profileField = skullMeta.getClass().getDeclaredField("profile");
profileField.setAccessible(true);
profileField.set(skullMeta,profile);
How to get the same result using API, without getting into skillMeta's class which (probably) causes error.

**Comment by electronicboy** [comment]
Please use the discord for support

https://jd.papermc.io/paper/1.21.1/org/bukkit/inventory/meta/SkullMeta.html#setPlayerProfile(com.destroystokyo.paper.profile.PlayerProfile)
