### ISSUE TITLE
ERROR com.mojang.authlib.GameProfile

### ISSUE THREAD

**Issue by GG-MD** [PaperSpigot/Paper#11428]
### Expected behavior

Read more here pls: https://github.com/PurpurMC/Purpur/issues/1590

### Observed/Actual behavior

-

### Steps/models to reproduce

-

### Plugin and Datapack List

-

### Paper version

-

**Comment by GG-MD** [comment]
ver: PurPur 1.21.1 latest build 2306-2310

**Comment by Machine-Maker** [comment]
This will not be fixed. The internal, **NOT API** field on CraftMetaSkull changed from a GameProfile to a ResolvableProfile. There has been API for many versions to set the skin for skulls, reflection should not be needed. Regardless of this fact, this is an internal, very not API change.
