### ISSUE TITLE
Within the WorldGuard protected area, attacking vehicles(Minecart & Boat) will trigger Knockback

### ISSUE THREAD

**Issue by CatTeaA** [PaperSpigot/Paper#11434]
### Expected behavior

Within the WorldGuard protected area, attacking while sprinting or using (Knockback:Enchantment) should not trigger Knockback

### Observed/Actual behavior

Attacking while sprinting or using (Knockback:Enchantment) both triggered Knockback and activated (Knockback:Enchantment)

### Steps/models to reproduce

placing a boat on land or in the water
attacking a boat with a weapon that has 'Knockback:Enchantment', or attacking a boat with an empty hand while sprinting

https://github.com/user-attachments/assets/24caf6b2-6909-410c-afc2-c588fbbcc4b8

### Plugin and Datapack List

worldedit-bukkit-7.3.6 , worldguard-bukkit-7.0.12-dist

### Paper version

This server is running Paper version 1.21.1-98-master@9b1ee0d (2024-09-24T02:24:07Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Other

Is there a missing related event?
I cannot confirm if this is due to WorldGuard; if it is, please feel free to disable it

**Comment by lynxplay** [comment]
Going to close this until https://github.com/EngineHub/WorldGuard/issues/2137 is triaged.
Our issue tracker isn't here for us to triage potential bugs in third party software.
If the WG issue ends up revealing a specific paper bug, feel free to comment here, we can reopen the issue.
