### ISSUE TITLE
Paper 121.1 build 104 and also Paper 121.1 build 105 crash on macOS 15 Sequoia on M1 Mac Mini (same result happens on M1 MacBook Air running macOS 15 Sequoia also)

### ISSUE THREAD

**Issue by CallMeTheArrow** [PaperSpigot/Paper#11443]
### Stack trace

[https://paste.gg/p/anonymous/50c82e07764046039b1e4a7a037a8dc8](https://paste.gg/p/anonymous/50c82e07764046039b1e4a7a037a8dc8)

### Plugin and Datapack List

None installed.

### Actions to reproduce (if known)

Download Paper JAR. can one 121.1 build 104 or build 105 - same result from either one. Java 23 is installed but tested it all the way back to Java 17 with identical results.  macOS 15 Sequoia is installed.  This is occurring on an Apple Silicon M1 Mac Mini with 8 GB of RAM. (Same issue tested and occurs also on an Apple Silicon M1 MacBook Air with 16 GB of RAM though as well). Run:  java -Xmx7G -Xms2G -jar server.jar nogui

Doesn't matter what you use for -XMx or -Xms values  - the result is the same.

### Paper version

121.1 build 104 or 121.1 build 105 - both have same result.

### Other

Java 23 is installed but tested it all the way back to Java 17 with identical results.  macOS 15 Sequoia is installed.  This is occurring on an Apple Silicon M1 Mac Mini with 8 GB of RAM. (Same issue tested and occurs also on an Apple Silicon M1 MacBook Air with 16 GB of RAM though as well).  Server starts, crashes within 3-5 minutes typically. Firewall is off.

**Comment by jpenilla** [comment]
What is the output of running `file $(which java)` from terminal

**Comment by CallMeTheArrow** [comment]
> What is the output of running `file $(which java)` from terminal

which java)
/usr/bin/java: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/usr/bin/java (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/bin/java (for architecture arm64e):	Mach-O 64-bit executable arm64e

**Comment by jpenilla** [comment]
Could you try with the macos aarch64 build from https://docs.aws.amazon.com/corretto/latest/corretto-21-ug/downloads-list.html?

**Comment by CallMeTheArrow** [comment]
> Could you try with the macos aarch64 build from https://docs.aws.amazon.com/corretto/latest/corretto-21-ug/downloads-list.html?

It works well with that Amazon Corretto version of Java, thank you! Not sure why it didn't work with Oracle's Java, strange.

**Comment by jpenilla** [comment]
I would guess the universal binary is somehow confusing Java when it tries to load native libraries, but regardless I'm glad that the aarch64 Corretto builds work properly. JVM crashes are mostly out of our control as a Java application, so I'll mark this issue as resolved.
