### ISSUE TITLE
Player Chat formatting not showing in client.

### ISSUE THREAD

**Issue by Hundr** [PaperSpigot/Paper#11470]
### Expected behavior

Have recently switched from spigot to paper server. Everything works except chat formatting. Have tried both CMI's chat and EssentialsXChat.
In the console the message is partially formatted properly, based on formatting settings within the desired chat plugin, except the prefix is being shown twice. Within the client it only shows the non-formatted message in White text. 

Everything works perfectly when I use the Spigot JAR.

### Observed/Actual behavior

Chat from players is not being displayed in the client properly.

### Steps/models to reproduce

switched from Spigot to Paper server.

### Plugin and Datapack List

PLUGINS:
[02:39:45 INFO]: Server Plugins (11):
[02:39:45 INFO]: Bukkit Plugins:
[02:39:45 INFO]:  - CMI, CMILib, Essentials, EssentialsChat, EssentialsSpawn, FastLeafDecay, Jobs, LuckPerms, Vault, VeinMiner
[02:39:45 INFO]:  voicechat

DATAPACKS:
[02:40:28 INFO]: There are 12 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [bundle (feature)], [file/No Enderman Griefing 1.20 (world)], [file/custom_crafting (world)], [file/universal dyeing (1.21) (world)], [file/harmine3 custom data (world)], [file/Unlock all recipes (world)], [file/coordinates_hud (world)], [file/Classic Fishing Loot v1.1.8 (world)], [file/Silence Mobs v1.2.2 (world)], [paper (built-in)]

### Paper version

This server is running Paper version 1.21.1-119-master@7cd4f2c (2024-10-03T15:19:34Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-114-ea00be3 (MC: 1.21.1)

### Other

Config files used
[config.zip](https://github.com/user-attachments/files/17268455/config.zip)

**Comment by electronicboy** [comment]
Paper has expanded the chat API in a manner that allows plugins to do fancier chat things and it's 100% on plugins on how they interact with that. having two plugins installed which handle that is asking for issues, essentials for example has a config option which is enabled by default last I knew which will put the players pre/suffix into the display name of the player, and so if you're using another chat plugin, you'd want to disable that.

For support, please use the discord.

**Comment by Hundr** [comment]
No. Only EssentialsChat is enabled. I was using CMI to test if it was a plugin issue.
The formatting gets applied in the console. Hence the screenshot.
Does not get applied in the Client.

**Comment by Hundr** [comment]
Furthermore, thanks for closing an issue that wasnt resolved.
