### ISSUE TITLE
new Enchancements datapack features bug

### ISSUE THREAD

**Issue by Saulencijus10** [PaperSpigot/Paper#11483]
### Expected behavior

when `max-level": 1,`it shold return `Enchancement-name`

### Observed/Actual behavior

So its nothing bad but `"max-level": 1,`  when enchancement put on item returns `Enchancement-name 1` 

### Steps/models to reproduce

in vanilla it works

### Plugin and Datapack List

only one datapack with only one feature - 1 Enchancement
plugins: Server Plugins (31): Bukkit Plugins:  - ArmorStandTools, AuctionHouse, AutoCraft, ChestShop, DecentHolograms, DimensionPause, Essentials, EssentialsChat, EssentialsDiscord, EssentialsDiscordLink,  EssentialsSpawn, ExcellentCrates, floodgate, FreedomChat, Geyser-Spigot, GriefPrevention, *HopperPipes, LockettePro, LuckPerms, nightcore,  ProtocolLib, SuperVanish, TAB, TextDisplay, UltimateAutoRestart, Vault, ViaBackwards, ViaVersion, voicechat, WorldEdit,  WorldGuard

### Paper version

latest

**Comment by Machine-Maker** [comment]
Please provide a link to the datapack so we can try to replicate this issue.

**Comment by Saulencijus10** [comment]
its custom made: [ce-v1.1.7.zip](https://github.com/user-attachments/files/17317395/ce-v1.1.7.zip)

**Comment by Machine-Maker** [comment]
I cannot replicate this issue. Are you using the vanilla client?

**Comment by Saulencijus10** [comment]
oh im using via version(backwards) in my serv and client 1.20.4 fabric(mods: allbright, optifine, simplevoicechat), can it be bcuz of viaversion?(backwards)

**Comment by Machine-Maker** [comment]
It probably is because of that. No idea how via handles translating custom enchantments to other versions that don't have custom enchantments. Test without any of those plugins and with a vanilla client (to be sure). I'm guessing that will fix your issue. We can re-open if it doesn't for some reason.
