### ISSUE TITLE
Water animals & ambient creatures instantly despawn

### ISSUE THREAD

**Issue by LucidAPs** [PaperSpigot/Paper#11485]
### Expected behavior

Shouldn't water animals and ambient creatures stay loaded for longer just like animals and monsters?

### Observed/Actual behavior

Is it normal that ambient , water_creature , water_ambient and underground_water_creature all instantly despawn when a players leaves far away? That doesnt happen with monsters and creatures, I tested it with default configs and no plugins with latest software 1.21.1-2324-e12a4de (MC: 1.21.1)

if it is normal then and not a bug then is there a way to stop it from happening?

### Steps/models to reproduce

Spawn a squid then fly away until the squid is no longer visible and immediately return.

### Plugin and Datapack List

No plugins or datapacks.

### Paper version

1.21.1-2324-e12a4de (MC: 1.21.1)

**Comment by CatBang** [comment]
Isn't this vanilla behavior? Perhaps you should try it out in single-player mode first.
https://www.paper-chan.moe/paper-optimization/#mobspawn
![Image](https://github.com/user-attachments/assets/c1ea6db6-9ff9-4751-9ff3-2adf1b7ac180)

**Comment by Malfrador** [comment]
This likely is vanilla behaviour.

However, you are using Purpur anyways as your build number gives away. Please do not open issues on the Paper issue tracker for software that isn't ours.
