### ISSUE TITLE
ItemStack.EMPTY leads to error in console

### ISSUE THREAD

**Issue by Folas1337** [PaperSpigot/Paper#11491]
### Expected behavior

No error

### Observed/Actual behavior

![Image](https://github.com/user-attachments/assets/20434bd1-be13-4893-8718-45ecd6a795e3)

This is a snippet of the code of the Axiom plugin by Moulberry.

It seems to currently lead to errors in the console that read like this: `[19:49:46 ERROR]: Tried to load invalid item: 'Item must not be minecraft:air'`

In the developer's own words: 
> This code here uses parse and falls back to ItemStack.EMPTY, but it does not prevent the ItemStack.LOGGER.error call in parse
> So if parseOptional is given a (valid) empty ItemStack, an error message will be erronously printed

I hope that's enough of an explanation of the bug, otherwise feel free to ask. 

### Steps/models to reproduce

I hope I explained it above?

### Plugin and Datapack List

I hope this isn't really required as we already narrowed it down to Axiom

### Paper version

```diff
  [Sat 09:42:06 INFO ] Checking version, please wait...
  [Sat 09:42:06 INFO ] This server is running Paper version 1.21.1-119-master@7cd4f2c (2024-10-03T15:19:34Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.1-118-fb76840 (MC: 1.21.1)```

### Other

_No response_

**Comment by Folas1337** [comment]
It was just going out this is a vanilla error message so I'll close this issue again.

**Comment by lynxplay** [comment]
The validity of empty itemstacks in the context of a CompoundTag representation is kind of up in the air.

Additionally, using internals isn't really on us? The exposed byte[] serialization methods in paper do not accept empty item stacks as input so, axiom is already doing something scuffed to get that compound tag in the first place.
The log message there is useful for other potentially malformed items, we cannot just remove it.

Given axiom already makes heavy use of [NMS for this](https://github.com/Moulberry/AxiomPaperPlugin/blob/cdcece8f883b9a55fdf0ec8707730c1d2ac00795/src/main/java/com/moulberry/axiom/persistence/ItemStackDataType.java#L42-L43), and the CODEC on ItemStack is public, I'd suggest a simplistic fix of


```diff
-        net.minecraft.world.item.ItemStack nmsStack = net.minecraft.world.item.ItemStack.parseOptional(MinecraftServer.getServer().registryAccess(), tag);
+        net.minecraft.world.item.ItemStack nmsStack = net.minecraft.world.item.ItemStack.CODEC.parse(
+            MinecraftServer.getServer().registryAccess().createSerializationContext(net.minecraft.nbt.NbtOps.INSTANCE),
+            tag
+        ).resultOrPartial().orElse(ItemStack.EMPTY);
```

**Comment by Folas1337** [comment]
> The validity of empty itemstacks in the context of a CompoundTag representation is kind of up in the air.
> 
> Additionally, using internals isn't really on us? The exposed byte[] serialization methods in paper do not accept empty item stacks as input so, axiom is already doing something scuffed to get that compound tag in the first place. The log message there is useful for other potentially malformed items, we cannot just remove it.
> 
> Given axiom already makes heavy use of [NMS for this](https://github.com/Moulberry/AxiomPaperPlugin/blob/cdcece8f883b9a55fdf0ec8707730c1d2ac00795/src/main/java/com/moulberry/axiom/persistence/ItemStackDataType.java#L42-L43), and the CODEC on ItemStack is public, I'd suggest a simplistic fix of
> 
> -        net.minecraft.world.item.ItemStack nmsStack = net.minecraft.world.item.ItemStack.parseOptional(MinecraftServer.getServer().registryAccess(), tag);
> +        net.minecraft.world.item.ItemStack nmsStack = net.minecraft.world.item.ItemStack.CODEC.parse(
> +            MinecraftServer.getServer().registryAccess().createSerializationContext(net.minecraft.nbt.NbtOps.INSTANCE),
> +            tag
> +        ).resultOrPartial().orElse(ItemStack.EMPTY);

Oh yeah Moulberry just acknowledged this is a vanilla bug and he'll take care of it. 

I appreciate you giving a suggestion towards the error as well, didn't necessarily want to take your precious time with this concern however 😅
