### ISSUE TITLE
Server crashes when pc wake up from iddle and monitor turns on (mouse, Cannot invoke "java.awt.PointerInfo.getLocation()" because "pi" is null)

### ISSUE THREAD

**Issue by cb31455** [PaperSpigot/Paper#11494]
### Stack trace

```
https://paste.gg/p/anonymous/5bff65bd350645aeb45bcafc11a07598
```

### Plugin and Datapack List

No plugin

### Actions to reproduce (if known)

cause: lg 32gn600-b monitor. it turns off ittself at iddle and make mouse dissapear. this cause the server sometimes crash, but now i got the message

### Paper version

This server is running Paper version 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version

**Comment by montlikadani** [comment]
There is an open issue on OpenJDK regarding this [JDK-6840067](https://bugs.openjdk.org/browse/JDK-6840067?jql=text%20~%20%22PointerInfo%22) which is unresolved and unconfirmed

**Comment by electronicboy** [comment]
Yea, We can probably catch it or something, 'tis an annoying one
