### ISSUE TITLE
Paper 1.8.8 not being identified as paper

### ISSUE THREAD

**Issue by 36479756** [PaperSpigot/Paper#11518]
### Expected behavior

Paper 1.8.8 will be identified as a paper version

### Observed/Actual behavior

![Image](https://github.com/user-attachments/assets/35251c2f-ad81-48a2-b7b4-9a4a6e7434a4)

### Steps/models to reproduce

create a paper 1.8.8 server and add plugin portal to the /plugin directory

### Plugin and Datapack List

CratesPlus, ChatPings, SkinsRestorer, LastLoginAPI, PluginPortal, Parties, ArmorStand-Limiter, Discord-Linker, TabTPS, Votifier, Essentials, EssentialsGeoIP, EssentialsAntiBuild, BetterRTP, EssentialsSpawn, EssentialsProtect, 

### Paper version

[16:53:27 INFO]: This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

[16:53:27 INFO]: Checking version, please wait...

[16:53:32 INFO]: Error obtaining version information

**Comment by lynxplay** [comment]
Paper 1.8.8 is no longer supported.

**Comment by MiniDigger** [comment]
additionally this is a plugin portal issue, not a paper one.
