### ISSUE TITLE
Configuration doesnt read keys with quotes

### ISSUE THREAD

**Issue by tlm9201** [PaperSpigot/Paper#11513]
### Expected behavior

```
[03:26:51 INFO]: [TestPlugin] Key: 0.1 Val: 5
[03:26:51 INFO]: [TestPlugin] Key: 0.2 Val: 10
[03:26:51 INFO]: [TestPlugin] Key: 1 Val: 20
```

### Observed/Actual behavior

```
[03:26:51 INFO]: [TestPlugin] Key: 0Val: MemorySection[path='0', root='YamlConfiguration']
[03:26:51 INFO]: [TestPlugin] Key: 1Val: 20
```

### Steps/models to reproduce

**1. Load up a test plugin with the following code**

```java
public final class TestPlugin extends JavaPlugin implements Listener {

    @Override
    public void onEnable() {
        getServer().getPluginManager().registerEvents(this, this);
        saveDefaultConfig();
        reloadConfig();
        getConfig().getValues(false).forEach((key, val) -> getLogger().info("Key: " + key + " Val: " + val));
    }

    @Override
    public void onDisable() {
        // Plugin shutdown logic
    }
}
```

**2. Use the following `config.yml`:**

```yaml
"0.1": 5
"0.2": 10
"1": 20
```

**3. Start the server and observe the output log**

### Plugin and Datapack List

TestPlugin

### Paper version

```
[21:27:56 INFO]: This server is running Paper version 1.21.1-128-master@d348cb8 (2024-10-21T16:23:24Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-120-227544c (MC: 1.21)
```

**Comment by electronicboy** [comment]
The issue here is that your keys have .'s in them, and so it's going to treat those in some form of manner as subkeys, you can change the character for the operator on the options configuration object from what I recall

**Comment by tlm9201** [comment]
> The issue here is that your keys have .'s in them, and so it's going to treat those in some form of manner as subkeys, you can change the character for the operator on the options configuration object from what I recall

But if the key is wrapped in quotes shouldn't the desired behavior be to treat it as one string and avoid doing anything beyond that?

**Comment by electronicboy** [comment]
every single call to the get methods are going to split on that key, even if it parsed them raw as-is, you'd never be able to read them

**Comment by electronicboy** [comment]
![Image](https://github.com/user-attachments/assets/15240796-cc3c-4c63-aae6-a2b7b956d904)

![Image](https://github.com/user-attachments/assets/75f98652-11bd-4bb2-9e30-55efb2f2053f)


There isn't any real way to fix this from our side. Even if we did fight with the thing to properly parse the keys, you wouldn't be able to access those values without fighting the thing or changing the separator anyway. You'd probably want to consider utilising a configuration library that properly deals with a node tree rather than relying on string manipulation for its accessing methods.
