### ISSUE TITLE
[1.21.3-6] Biome.name() fails: java.lang.IncompatibleClassChangeError: Found interface org.bukkit.block.Biome, but class was expected

### ISSUE THREAD

**Issue by globau** [PaperSpigot/Paper#11549]
### Expected behavior

`Biome.name()` should return the name of the biome.

### Observed/Actual behavior

`java.lang.IncompatibleClassChangeError: Found interface org.bukkit.block.Biome, but class was expected`

### Steps/models to reproduce

```
System.out.println(player.getLocation().getBlock().getBiome().name());
```

### Plugin and Datapack List

none

### Paper version

`This server is running Paper version 1.21.3-6-master@16d7d73 (2024-11-01T03:40:19Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)`

**Comment by lynxplay** [comment]
Are you using a paper-plugin.yml?

Paper plugins have never and will not be remapped until they are declared stable.
In the recent upstream update, we merged spigots move to an interface for Biome, Attribute and Fluid.
The paper plugin would need to be re-compiled against the newest paper-api artefact.

**Comment by globau** [comment]
> Paper plugins have never and will not be remapped until they are declared stable.

Thank you, I wasn't aware of this. Sorry about the noise.
