### ISSUE TITLE
[1.21.3] Player Perform Command API Failing

### ISSUE THREAD

**Issue by PulseBeat02** [PaperSpigot/Paper#11562]
### Expected behavior

I expected my command to be executed, but instead, there is no output in the console, and it seems that the command has not been executed. I used this snippet of code inside my plugin class to test the command execution when a player joins. It worked on Paper 1.21.1

```java
    Bukkit.getPluginManager().registerEvents(new Listener() {
      @EventHandler
      public void onPlayerJoin(final PlayerJoinEvent event) {
        final Player player = event.getPlayer();
        player.performCommand("say Hello World!");
      }
    }, this);
```

(As for a different but similar issue, I used Adventure components with text that runs a command when the player presses on it, and there is nothing that happens either. I'm not sure if this is the same issue or not)

### Observed/Actual behavior

There is nothing sent out into console, with no output sent out to the player. No error is displayed into the console either, and the implementation fails silently.

### Steps/models to reproduce

1) Register a quick `Listener` for Player join for executing a `say` command message
2) Join the server as any player
3) There is nothing displayed inside of chat

### Plugin and Datapack List

None besides the current plugin

### Paper version

```
[19:47:47 INFO]: Checking version, please wait...
[19:47:47 INFO]: This server is running Paper version 1.21.3-10-master@92131ad (2024-11-01T21:30:00Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.3-8-85c870e (MC: 1.21.3)
```

**Comment by MiniDigger** [comment]
see https://github.com/PaperMC/Paper/issues/11549#issuecomment-2451502641
