### ISSUE TITLE
Error with /tp

### ISSUE THREAD

**Issue by sh2kcs** [PaperSpigot/Paper#11576]
### Expected behavior

Normal /tp to any player

### Observed/Actual behavior

The player is not going anywhere and his entire interior in the house will disappear, all the whole blocks will disappear.
In the chat it said: Chat is disabled in the client settings

### Steps/models to reproduce

1. Start the server with paper
2. Just write /tp to any players and you will encounter this error.
(This error is not always, it appears sometimes)

### Plugin and Datapack List

AntiRaidFarm, arMarks, ArmorStandEditor, BalancedVillagerTrades, BanAnnouncer, BreweryX, ChatBubbles, Chatty, Chunky, CoreProtect CoreProtectTNT, DecentHolograms, DiscordSRV, ElytraFly, emotecraft, Essentials, GSit, InventoryRollbackPlus, InvSeePlusPlus, ItemEdit LibertyBans, LuckPerms, NormalSpit, packetevents, PL-Hide, Pl3xMap, PlaceholderAPI, PlasmoVoice, PLAZMER-ENGINE, Profiler ProtocolLib, PurpurExtras, pv-addon-broadcast, pv-addon-discs, pv-addon-groups, pv-addon-lavaplayer-lib, pv-addon-priority, pv-addon-sculk, pv-addon-spectator, pv-addon-whisper qTag, RPSign, RPTool, Sex, sHideTags, SkinsRestorer, Spicord, SuperVanish, TAB, TablePlays TemporaryWhiteList, Vault, ViaBackwards, ViaVersion, WanderingTrades, zv_skin
There are 5 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)], [file/CauldronConcretePowder [v1.1.0].zip (world)], [file/Simple Invisible Light 1.21.zip (world)]
There are no more data packs available

### Paper version

This server is running Paper version 1.21.3-11-master@a6df4c8 (2024-11-02T23:38:04Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-DEV-6fff957 (MC: 1.21.1)

**Comment by shiksyt** [comment]
https://pastes.dev/2lbEr6TDAa
Log

**Comment by MiniDigger** [comment]
> Chat is disabled in the client settings

consider enabling chat in the client settings, aka your minecraft settings ^^

**Comment by MiniDigger** [comment]
didn't see the second message, sorry, lol

**Comment by Leguan16** [comment]
> https://pastes.dev/2lbEr6TDAa Log

Can you send the whole log file please?

**Comment by shiksyt** [comment]
> > https://pastes.dev/2lbEr6TDAa Log
> 
> Can you send the whole log file please?

https://mclo.gs/kb4qscE

**Comment by rutgerkok** [comment]
Can confirm on build `1.21.3-14-master@fcb6c72 (2024-11-06T10:06:32Z)`, which is the latest at time of writing. Same error (`java.lang.IllegalArgumentException: Modifier is already applied on this attribute!`)

For me, it _only_ happens for cross-dimension teleports (tested and reproduced for both overworld -> nether and nether -> overworld) _and_ when teleporting from an area with a beacon with at least one active effect.

The player doesn't disconnect immediately. It feels very similar to an internet disconnect, in the sense that you can still walk, but you won't receive any updates from the world or chat. However, if you try to send a chat message, you do get back a response from the server that chat is disabled, and you suddenly start falling through the world. After a while, you'll disconnect with "No response" as the error message.

**Comment by D3dWiz** [comment]
Just to add some more context as I'm also experiencing this issue with every teleportation related plugin.
After trying to teleport the player gets stuck in a loading chunk without the ability to send commands/chat messages. I have the same error in my console.

The only way to teleport between worlds is by using the vanilla command `/minecraft:execute as @p in minecraft:[world] run minecraft:tp @p ~ ~ ~`

**Comment by BensaTV** [comment]
Still having this issue with the latest build.
