### ISSUE TITLE
[1.21.3] Run Command Components Failing

### ISSUE THREAD

**Issue by PulseBeat02** [PaperSpigot/Paper#11581]
### Expected behavior

Upon clicking on a chat component that allows the player to run a command, the command isn't executed at all. I am using Adventure components to send to the player directly.

### Observed/Actual behavior

There is no output to the command because the command does not even run at all. The implementation fails silently.

### Steps/models to reproduce

1) Copy and paste this simple Listener code for a plugin

```java
    Bukkit.getServer().getPluginManager().registerEvents(new Listener() {
      @EventHandler
      public void onPlayerJoin(final PlayerJoinEvent event) {
        event.getPlayer().sendMessage(Component.text("Click to say hi!")
                .clickEvent(ClickEvent.runCommand("say Hello World!")));
      }
    }, this);
```

2) Drop the plugin on the server
3) Join and click on the message
4) No "Hello World!" sent to the player

(Note: I've also tried `ClickEvent.runCommand("/say Hello World!")` with the slash at the beginning as well, and that doesn't work either)

### Plugin and Datapack List

None except for the current testing plugin

### Paper version

```
[14:31:13 INFO]: This server is running Paper version 1.21.3-12-master@c6aa61e (2024-11-04T17:51:59Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are running the latest version
```

**Comment by Malfrador** [comment]
It is not possible to run vanilla commands that send chat messages directly, such as `/say`, from click events. That is something Mojang intentionally disabled.

Does it work properly for other commands?

**Comment by PulseBeat02** [comment]
@Malfrador I just tried with using the `list` command and `gamemode` command while being opped with and without slash, and they didn't work for me still for some reason.

**Comment by Lumine1909** [comment]
> [@Malfrador](https://github.com/Malfrador) I just tried with using the `list` command and `gamemode` command while being opped with and without slash, and they didn't work for me still for some reason.

Since 1.19.1 Report & Ban Update, Vanilla minecraft has removed the support of any "signed chat" by "clickEvent".
Thus, "gamemode xxx" is considered a chat but not a command like "/gamemode xxx".
If you check your client log file, you may find a message like `[Render thread/ERROR]: Not allowed to run command with signed argument from click event: '/say xxx'`


```java
from net.minecraft.client.gui.screens.Screen (Mojang map)


else if (clickEvent.getAction() == ClickEvent.Action.RUN_COMMAND) {
	String string = StringUtil.filterText(clickEvent.getValue());
	if (string.startsWith("/")) {
		if (!this.minecraft.player.connection.sendUnsignedCommand(string.substring(1))) {
			LOGGER.error("Not allowed to run command with signed argument from click event: '{}'", string);
		}
	} else {
		LOGGER.error("Failed to run command without '/' prefix from click event: '{}'", string);
}

```

**Comment by Lumine1909** [comment]
If you need that feature for let player chat by click some component, you can register a custom command to let player chat on server side (Player#chat) and set this command in the run_command component.

**Comment by PulseBeat02** [comment]
I might be crazy, but when using `/gamemode creative` for the command while opped, it still doesn't work. There is no error in the server or the client logs. The following is my client log when I connected to my localhost testing server. I am using Fabulously Optimized from Prism Launcher, maybe that's why it doesn't work? I have no idea
```
[22:51:12] [Render thread/INFO]: Connecting to localhost, 25565
[22:51:15] [Render thread/INFO]: Reloading pipeline on dimension change: minecraft:overworld => minecraft:overworld
[22:51:15] [Render thread/INFO]: Destroying pipeline minecraft:overworld
[22:51:15] [Render thread/INFO]: Creating pipeline for dimension minecraft:overworld
[22:51:16] [Render thread/INFO]: Started 8 worker threads
[22:51:16] [Render thread/INFO]: [CHAT] Click to say hi!
[22:51:16] [Render thread/INFO]: [CHAT] PulseBeat_02 joined the game
[22:51:16] [Render thread/INFO]: Loaded 2 advancements
[22:51:16] [Render thread/INFO]: Stopping worker threads
[22:51:16] [Render thread/INFO]: Started 8 worker threads
```

I spam clicked the message in chat and there was nothing outputted, and there are no errors in the console either. I've made sure that I am operator too.

**Comment by PulseBeat02** [comment]
Nevermind, it was a client issue. Closing because of invalid
