### ISSUE TITLE
RecipeBook click ignores ExactChoice

### ISSUE THREAD

**Issue by LoneDev6** [PaperSpigot/Paper#11593]
### Expected behavior

Custom recipe to be selected correctly.

### Observed/Actual behavior

If you click on the recipe button you clearly see vanilla items added instead of the renamed Diamond.
This causes the recipe to not be selected correctly, instead the vanilla overlapping recipe gets used.

This happens both on Spigot (even on pre-1.21.3) and on Paper 1.21.3.
Paper 1.21.1 [implemented a fix](https://github.com/PaperMC/Paper/blob/ver/1.21.1/patches/server/0277-Improve-exact-choice-recipe-ingredients.patch) for that which wasn't introduced in 1.21.3.

I did some tests by logging client packets, using [this guide](https://wiki.vg/Debugging), and seems that 1.21.3 client doesn't send `[play:serverbound/minecraft:place_recipe]` (`ServerboundPlaceRecipePacket`) packet at all when clicking again on the recipe. It used to do that on 1.21.1, so this might now be fixable.

### Steps/models to reproduce

# 1.21.1
https://github.com/user-attachments/assets/b0cb5ba1-6503-4948-9f03-e8398100ece8

# 1.21.3
https://github.com/user-attachments/assets/5b3c61d5-236c-447c-8846-6abd77e8a299

Example code to reproduce the issue:

```java
Player player = Bukkit.getPlayer("LoneDev");
org.bukkit.inventory.ShapedRecipe recipe = new org.bukkit.inventory.ShapedRecipe(new NamespacedKey("test", "test_exact_choice"), new org.bukkit.inventory.ItemStack(Material.BARRIER));
recipe.shape( "ccc",  "xix",  "xix");
org.bukkit.inventory.ItemStack exact = new org.bukkit.inventory.ItemStack(Material.DIAMOND);
ItemMeta meta = exact.getItemMeta();
meta.setDisplayName("test item");
exact.setItemMeta(meta);
recipe.setIngredient('c', new RecipeChoice.ExactChoice(exact));
recipe.setIngredient('i', new RecipeChoice.MaterialChoice(Material.STICK));

org.bukkit.inventory.ItemStack aaa = exact.clone();
aaa.setAmount(32);
player.getInventory().addItem(aaa);

if(Bukkit.getRecipe(recipe.getKey()) != null)
    Bukkit.removeRecipe(recipe.getKey());
Bukkit.addRecipe(recipe); 
```

### Plugin and Datapack List

None

### Paper version

This server is running Paper version 1.21.3-14-master@fcb6c72 (2024-11-06T10:06:32Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are running the latest version

### Other

Opened an issue on Spigot jira too as this bug is reproducible also on Spigot.
https://hub.spigotmc.org/jira/browse/SPIGOT-7950

**Comment by Machine-Maker** [comment]
Was already gonna be fixed by https://github.com/PaperMC/Paper/pull/11546 so it’s a known issue. I’ll still leave this open tho until that’s merged.
