### ISSUE TITLE
Endless fireworks

### ISSUE THREAD

**Issue by sh2kcs** [PaperSpigot/Paper#11592]
### Expected behavior

The fireworks will end

### Observed/Actual behavior

When you reach 1-2 fireworks - they become infinite.
Video: https://imgur.com/a/uOawtS9

### Steps/models to reproduce

1. Start a server on Paper
2. Log in and issue GM 0
3. Try spending fireworks

### Plugin and Datapack List

AntiRaidFarm, arMarks, ArmorStandEditor, AuxProtect, BalancedVillagerTrades, BanAnnouncer, BreweryX, ChatBubbles, Chatty, CoreProtect CoreProtectTNT, DecentHolograms, ElytraFly, Essentials, GSit, InventoryRollbackPlus, InvSeePlusPlus, ItemEdit, LibertyBans, LuckPerms NoEmotecraft, NormalSpit, PL-Hide, Pl3xMap, PlaceholderAPI, PlasmoVoice, PLAZMER-ENGINE, Profiler, ProtocolLib, PurpurExtras  pv-addon-broadcast, pv-addon-discs, pv-addon-groups, pv-addon-lavaplayer-lib, pv-addon-priority, pv-addon-sculk, pv-addon-spectator, pv-addon-whisper, RPSign, RPTool Sex, SkinsRestorer, Spicord, SuperVanish, TAB, TablePlays, TemporaryWhiteList, Vault, ViaBackwards, ViaVersion WanderingTrades, zv_skin

### Paper version

This server is running Paper version 1.21.3-14-master@fcb6c72 (2024-11-06T10:06:32Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.3-13-42a1901 (MC: 1.21.3)

**Comment by shiksyt** [comment]
There is no error in the console.
Fireworks are spent on elytras

**Comment by codebycam** [comment]
Please reproduce without any plugins.

**Comment by codebycam** [comment]
Okay I actually felt an inclination to test this myself and can confirm that fireworks are infinite (on the latest version `1.21.3-14-master@fcb6c72`). I didn't do anything with creative mode either, I just joined a new world in survival mode, gave my player fireworks and they were infinite.

Video: https://github.com/user-attachments/assets/d5d61064-4562-4041-86a2-b9a1cf3e14e5

**Comment by NoahvdAa** [comment]
Probably caused by this:
https://github.com/PaperMC/Paper/blob/fcb6c72bc95ff62b9cd78dec457f485dafcc70a4/patches/server/0212-PlayerLaunchProjectileEvent.patch#L171-L176

Line 173 looks wrong

**Comment by kennytv** [comment]
@SergioK29 please do not post spam comments on issues and prs
