### ISSUE TITLE
[1.21.3] Anvil makes ghost items

### ISSUE THREAD

**Issue by Potothingi** [PaperSpigot/Paper#11591]
### Expected behavior

Using anvil will cause existing items to disappear.

### Observed/Actual behavior

When using anvil, existing items will not disappear and will remain as ghost items. (try Enchanted Book)

### Steps/models to reproduce

Try using the enchanted book with anvil.

### Plugin and Datapack List

Server Plugins (0):

There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]
There are no more data packs available

### Paper version

This server is running Paper version 1.21.3-14-master@fcb6c72 (2024-11-06T10:06:32Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are running the latest version

**Comment by shiksyt** [comment]
+1

**Comment by codebycam** [comment]
I can reproduce this. The ghost item in the first slot of the anvil vanishes if you interact with it or just close the anvil.
https://github.com/user-attachments/assets/e2109092-8eba-4e51-a0e2-8a37c83da064

**Comment by Doc94** [comment]
This come from upsteam (fixed) mostly is s sync issue where not sure why in this version when the data send to client its incomplete and you need resend the data when anvil create the final result item
