### ISSUE TITLE
call ItemStack#hasItemMeta cause NullPointerException

### ISSUE THREAD

**Issue by fyxrim** [PaperSpigot/Paper#11604]
### Expected behavior

no

### Observed/Actual behavior

no

### Steps/models to reproduce

![Image](https://github.com/user-attachments/assets/4518665d-0bf3-4ddd-965b-2500cf09dd33)
The issue occurs when clicking on an item, and an error is displayed.

### Plugin and Datapack List

![Image](https://github.com/user-attachments/assets/34076701-11b5-415d-bc3c-1f5c92c86ded)

### Paper version

![Image](https://github.com/user-attachments/assets/558bc64c-b5a9-490c-b643-d6ca6f776578)

### Other
![Image](https://github.com/user-attachments/assets/4098ac52-cb91-4a6c-a69d-e849997cb087)

Versions below 1.20 have no issues.
The author's Ultrabind plugin says there is no issue, but the server's Paper core has issues in versions above 1.21.

**Comment by lynxplay** [comment]
Could you provide the actual error from the console please?

**Comment by fyxrim** [comment]
> 您能否提供控制台的实际错误？



> Could you provide the actual error from the console please?

Provided

**Comment by fyxrim** [comment]
> Could you provide the actual error from the console please?

Provided

**Comment by lynxplay** [comment]
The error would imply something created a completely broken itemstack.
Is the plugin on github?

**Comment by PedroMPagani** [comment]
The last time I saw this on donutsmp, it was because I didn't have thread safety on the item accessing, so that might be why

**Comment by lynxplay** [comment]
> just calls the NBT-API to add an nbt tag
Could you try to create a minimal replicable public code base?
E.g. a simple plugin that just, in its onEnable, does what you just described and triggers the error?

**Comment by killerprojecte** [comment]
![Image](https://github.com/user-attachments/assets/693da692-c796-4c84-b01f-9edbae503124)

**Comment by electronicboy** [comment]
The error suggests that there is a null key inside of the unhandled tags map of CraftMetaItem, the game doesn't have a raw NBT tag anymore, but, also, this suggests that the library you're using is handling this improperly with mojangs rewriting of items in 1.20.something

**Comment by killerprojecte** [comment]
> The error suggests that there is a null key inside of the unhandled tags map of CraftMetaItem, the game doesn't have a raw NBT tag anymore, but, also, this suggests that the library you're using is handling this improperly with mojangs rewriting of items in 1.20.something

The only library used in the plugin to operate NBT is Item-NBT-API. However, by copying the same code into a blank plugin and running it, no errors will occur at all

**Comment by electronicboy** [comment]
well, you'd want to dump out the information stored on the item, make sure that the plugin is using the latest NBT API, etc, etc; all we can see is that the item has what looks like invalid data

**Comment by killerprojecte** [comment]
> well, you'd want to dump out the information stored on the item, make sure that the plugin is using the latest NBT API, etc, etc; all we can see is that the item has what looks like invalid data

I am indeed running the latest NBT-API. I tried to use nbt-api to output the item nbt for inspection. However, calling nbtapi after writing nbt and then reading it also produced an error.

**Comment by killerprojecte** [comment]
The source of the problem has been checked. This problem is probably caused by Paper-Remapper. This problem can be solved by replacing it with an independent NBTAPI plugin.

**Comment by electronicboy** [comment]
all I can guess is that the library was shaded in a manner that makes it incompatible (i.e. library expecting to run in a remapped env failing as it was shaded into a plugin that doesn't go through that, etc). Given that we have no means of accessing anything here, there is little that we can do or advise.
