### ISSUE TITLE
Experimental Minecart Datapack Issues

### ISSUE THREAD

**Issue by jellythefishie** [PaperSpigot/Paper#11608]
### Expected behavior

New minecart snapshot/datapack should have minecarts behaving smoothly down slopes at any given speed. Minecart hitboxes should not collide with certain blocks such as the block below a sloped rail

### Observed/Actual behavior

Minecart hitbox collides with blocks below sloped rails.
![Image](https://github.com/user-attachments/assets/222d3dee-0cce-4bbe-975b-33875ef15f23)
This causes minecart to slow down tremendously, even at default 8/bps speed whenever going down hills.

### Steps/models to reproduce

Turn on the experimental minecart features and ride down a hill. Works while in the cart, with cart variants and with an empty cart.

### Plugin and Datapack List

Aternos server using bukkit/paper setting. A small achievement datapack is put on the server, but likely affects nothing.

### Paper version

This server is running Paper version 1.21.3-25-master@1ef4c0e (2024-11-10T00:30:27Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)

You are running the latest version
Previous version: 1.21.1-128-d348cb8 (MC: 1.21.1)

### Other

Ive only tested this on the aternos bukkit/paper setting. I dont host my own server for reasons. I've tried vanilla, and now bukkit/spigot as well and they all work fine.

**Comment by Lulu13022002** [comment]
It seems that moonrise is outdated, mainly LazyEntityCollisionContext doesn't override the new getCollisionShape to pass to the proper delegate here a MinecartCollisionContext. And some assumption of a constant voxel shape in CollisionUtil#getCollisionsForBlocksOrWorldBorder are not true anymore.

**Comment by Spottedleaf** [comment]
Resolved in https://github.com/PaperMC/Paper/commit/c60af44a9438437208b3da94c2ef88bd2637506b
