### ISSUE TITLE
TextDisplay setViewRange doesn't seem to work

### ISSUE THREAD

**Issue by JHarris12345** [PaperSpigot/Paper#11619]
### Expected behavior

Setting the view range of a text display entity prevents it from being rendered to the client out of range

### Observed/Actual behavior

I create a text display entity and then set the view range to 2. However it can be viewed from ANYWHERE

### Steps/models to reproduce

- Create text display
- Set view range

### Plugin and Datapack List

N/A - Same with 0 plugins except my TextDisplay creator

### Paper version

This server is running Paper version 1.21.1-131-ver/1.21.1@84281ce (2024-10-31T17:43:44Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-DEV-393582c (MC: 1.21.1)

**Comment by JHarris12345** [comment]
Realised my mistake :D

**Comment by jaylawl** [comment]
> Realised my mistake :D

What was your mistake? I am currently having the same "issue" and can't figure out why it isn't accepting the view range value - or seemingly not make any difference ingame.

/edit:
Found the issue. Quoting from https://minecraft.wiki/w/Display:
```
view_range: Maximum view range of the entity. When the distance is more than <view_range>×<[entityDistanceScaling](https://minecraft.wiki/w/Options.txt#Java_Edition)>×64, the entity is not rendered. Defaults to 1.0.
```
It's a little confusing that this isn't documented at all within Paper. Despite a weird gut feeling I assumed that range value represents "distance in blocks". But i guess the underlying javadocs documentation is kept minimal on purpose.

**Comment by electronicboy** [comment]
The documentation generally documents the direct effects of stuff, i.e. setting a value on an entity sets it on an entity; it's not the role of a javadoc to explain all the consequential artefacts induced by different configurations/systems within the codebase of an implementation which isn't ours.

The server doesn't "track" entities outside of the configured range for clients, so it's not going to be sent to the client for it to be able to enact upon the value set on the entity
