### ISSUE TITLE
PotionEffectType.SATURATION does not apply the duration

### ISSUE THREAD

**Issue by Neil4909** [PaperSpigot/Paper#11627]
### Expected behavior

Saturation effect applied to player for 72000 ticks

### Observed/Actual behavior

Saturation effect applied to player for 0 ticks

### Steps/models to reproduce

```Java
//This one produces an instantaneous effect
player.addPotionEffect(new PotionEffect(PotionEffectType.SATURATION, 72000, 1, false, false, true));
//this produces an hour long duration effect
player.addPotionEffect(new PotionEffect(PotionEffectType.FIRE_RESISTANCE, 72000, 1, false, false, true));
```

### Plugin and Datapack List

CommandAPI, SkinsRestorer
vanilla, file/bukkit, paper

### Paper version

Current Purpur Version: 1.21.1-2329-803bf62 (MC: 1.21.1)*
* You are running the latest version

**Comment by lynxplay** [comment]
Cannot replicate this, you are also not running paper.
```java
