### ISSUE TITLE
Catch of FileNotFoundException left empty when calling `YamlConfiguration.loadConfiguration()` in plugin

### ISSUE THREAD

**Issue by reChords25** [PaperSpigot/Paper#11620]
### Expected behavior

When trying to load a `YamlConfiguration `from a file that does not exist, it should somehow tell the user (or dev when deveoping) that the YamlConfiguration did not load correctly.

### Observed/Actual behavior

While `IOException` and `InvalidConfigurationException` are handled (logged to the console) when trying to load a `YamlConfiguration` from a nonexistent file, the probably most important `FileNotFoundException` is not catched in any way visible to the user. Like that, you are not able to know whether your config loaded correctly sometimes. This is just because the catch-block for the `FileNotFoundException` is empty in the `YamlConfiguration` class.

![Image](https://github.com/user-attachments/assets/2387521e-1ce5-494b-be77-df79d7562229)

### Steps/models to reproduce

Just call `YamlConfiguration.loadConfiguration()` in a plugin of choice and pass a nonexistent file as parameter.

### Plugin and Datapack List

Plugin in development process, definitely not the cause.

### Paper version

This server is running Paper version 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version

### Other

I could not find a way to report bugs for Bukkit, so I just did it here. I know that YamlConfiguration is a class from Bukkit (org.bukkit.configuration.file.YamlConfiguration), but I hope there is a way to fix this and find out whether the configuration has loaded.

**Comment by electronicboy** [comment]
```
     * Any errors loading the Configuration will be logged and then ignored.
     * If the specified input is not a valid config, a blank config will be
     * returned.
```

That is the contract of the method, it's expected to fail silently if there is no configuration file, and I generally see no reason to change this 13 years later

**Comment by reChords25** [comment]
But how am I, as a "user", then supposed to find out whether my config loaded correctly? Sure, there are workarounds, but why work _around_ something when you can fix it :)?

**Comment by electronicboy** [comment]
Your statement makes 0 sense. This code is for developers to call, and this method does not consider a configuration file's lack of existence as a critical failure. It is a pretty typical expected state that a config file might not exist in various states, and it's on you as a developer to deal with this check if it does not conform to your expectations here.
