### ISSUE TITLE
Ender Chest Animations Do Not Play

### ISSUE THREAD

**Issue by tnn1nja** [PaperSpigot/Paper#11634]
### Expected behavior

Right-Clicking on an Ender Chest to access their inventory should play cause the BlockEntity to play an opening animation and sound.
Closing an Ender Chest inventory should cause the associated BlockEntity to play a closing animation and sound.

### Observed/Actual behavior

No Ender Chest animations or sounds play.

### Steps/models to reproduce

Interact with an Ender Chest

### Plugin and Datapack List

No plugins or datapacks loaded.

### Paper version

Paper 1.21.3 Build #36 (and before)

**Comment by NonSwag** [comment]
Can reproduce
