### ISSUE TITLE
Sheep/Bogged/Snowman "regrow wool/mushroom/pumpkin" methods

### ISSUE THREAD

**Issue by NonSwag** [PaperSpigot/Paper#11638]
### Is your feature request related to a problem?

With the deprecation of the bukkit `Shearable` API, we lost the ability to force regrow wool or mushrooms for sheep and bogged or "un-derp" snow golems

### Describe the solution you'd like.

Methods for those entities to regrow their "features"

### Describe alternatives you've considered.

Using the deprecated and marked for removal API from Bukkit

**Comment by electronicboy** [comment]
there is already API to derp snow golems; not sure what you mean by 'mushrooms for sheep'

**Comment by Machine-Maker** [comment]
Yeah, when upstream made their not-so-great Sheared interface, they moved the setSheared method from Sheep to it, so when we deprecated that new stuff, it left Sheep without a non-depreacted setSheared method. I think we should just re-add both isSheared and setSheared to just Sheep to go back to how it was before they moved it. Should be an easy PR for someone.

**Comment by NonSwag** [comment]
"Good First issue" funny
Just wanted to say that bogged would be left without a non deprecated method if we only re-add setSheared to sheep

**Comment by electronicboy** [comment]
Then one should be added to bogged too
