### ISSUE TITLE
Console colors no longer showing post Jline fix.

### ISSUE THREAD

**Issue by andrewkm** [PaperSpigot/Paper#11637]
### Expected behavior

Console colors to properly display.

### Observed/Actual behavior

No console colors.
Using LuckPerms as an example as I'm sure we're all aware of how it looks with colors on startup:
https://i.imgur.com/4zOacF1.png

### Steps/models to reproduce

- Use any build that includes the following commit: https://github.com/PaperMC/Paper/commit/d8b66dd93d760fcbbc295bfd9b1abfdf8239f2f5
- Use any build before that commit and no problems arise, colors work just fine.

Environment:
Paper 1.21.3-44-master@85bfdc0
Windows Server 2022 21H2 (OS Build 20348.2849)
Java 23.0.1 (64-Bit Server VM 23.0.1+11-39)

Startup line currently using:
`-Xms12288M -Xmx12288M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -Djdk.console=java.base -jar paper.jar --nogui`

PS: _I have tried with removing -Djdk.console=java.base and get same result. I have also tried with Java 21, same result._

### Plugin and Datapack List

On request.

### Paper version

Paper 1.21.3-44-master@85bfdc0

### Other

Let me know if you require further information.

**Comment by andrewkm** [comment]
> -Dnet.kyori.ansi.colorLevel=truecolor

Yes, adding this flag has fixed colors for us. 👍

**Comment by electronicboy** [comment]
We no longer include jansi, and looks like the ansi serialiser doesn't declare its own dep on that publically, and so it's just falling back to trying to detect based on the env. These types of detections always kinda suck as there is no good universal way to detect this kind of thing

**Comment by MiniDigger** [comment]
ok, so I spend a bit of time looking at this. cat is right that we no longer include jansi (as we don't need it).
however jansi changes the detection in adventure. it first tries to look at system properties, then env vars, then jansi. if no jansi is present, it assumes no color. however, jansis detection works similarly, has overrides as system properties and checks env vars, but if that doesn't find stuff, it falls back to 16 colors. so basically, just adding ansi changes the default adventure uses.
just shipping jansi for that seems like unnecessary bloat to me and I will be talked with the other adventure peeps to change the default.

**Comment by lynxplay** [comment]
Should be resolved now that we bumped to adventure 4.18 👍

**Comment by andrewkm** [comment]
Confirmed fixed. :)
