### ISSUE TITLE
Add more information to UnknownCommandEvent

### ISSUE THREAD

**Issue by NonSwag** [PaperSpigot/Paper#11639]
### Is your feature request related to a problem?

When working with the `UnknownCommandEvent` there is no safe way to detect whether a command failed because of syntax errors or because it doesn't exist, or the sender has no access to it

### Describe the solution you'd like.

Adding a method to check whether the command failed to parse or cannot be performed and maybe even the command instance

### Describe alternatives you've considered.

Checking if the command exists and whether the sender can perform that command (doesn't work reliably on brigadier commands)

**Comment by electronicboy** [comment]
"syntax errors or it doesn't exist" is generally considered the exact same thing by the brigadier dispatcher, I don't think that there is much that can be exposed here which wouldn't involve us trying to inject that sort of context, which has no real safe way of passing that info up anyways...

**Comment by Machine-Maker** [comment]
Every command that doesn't execute successfully is an unknown command. I could easily just make a command for which the values entered *did* successfully execute. There is no difference between an unknown command and invalid syntax.
