### ISSUE TITLE
Add `getOfflinePlayerIfCached(UUID)`

### ISSUE THREAD

**Issue by OoLunar** [PaperSpigot/Paper#11644]
### Is your feature request related to a problem?

#4687 allows us to easily search the `usercache.json` file, however there's no UUID overload for the method even though the `usercache.json` file saves the player's UUID.

### Describe the solution you'd like.

Adding an `getOfflinePlayerIfCached(UUID)` overload for the `getOfflinePlayerIfCached(String)` method.

### Describe alternatives you've considered.

Calling `getOfflinePlayer(UUID)`, however that has the possibility of making an HTTP request. As this method will be called upon extensively - though results could be cached - this isn't ideal.

**Comment by Abelkrijgtalles** [comment]
Made a pr, don't know why it wouldn't be merged. Seems like a good idea.

**Comment by emilyy-dev** [comment]
`Server#getOfflinePlayer(UUID)` does not make any HTTP requests like `getOfflinePlayer(String)` does, it will get or create an `OfflinePlayer` instance that might or might not be backed by an existing player.dat file for that UUID, for which you can check with `OfflinePlayer#hasPlayedBefore()`.

**Comment by lynxplay** [comment]
@OoLunar as emily said, we'd love to hear your usecase for this.
Cluttering API without a proper usecase is generally not in our interest, so it'd be great if you can give us a proper example :)
Otherwise I'll just close this issue as, yea, the uuid getters do not require a network request.
