### ISSUE TITLE
Wolf's having wolf armour causes them not to take fall damage

### ISSUE THREAD

**Issue by ImNoTrash** [PaperSpigot/Paper#11650]
### Expected behavior

Wolf wearing wolf armor takes damage after falling from height where fall damage can occur.

### Observed/Actual behavior

Wolf's armor is cracked or broken (depending on height) and wolf takes no damage after falling from height where fall damage can occur.

### Steps/models to reproduce

[https://medal.tv/games/minecraft/clips/j8XGbFaXmHQffCHIG?invite=cr-MSxqNk0sMTc0NjM1MjkxLA](url) --> vanilla
[https://medal.tv/games/minecraft/clips/j8XMNxWAELHhlW55D?invite=cr-MSxiV1EsMTc0NjM1MjkxLA](url)--> paper
On vanilla takes damage
On paper does not

### Plugin and Datapack List

BlueSlimeCore
EthernalCombat
InvSeePlusPlus
InvSeePlusPlus_Clear
InvSeePlusPlus_Give
Sethome
SimpleTpa
Spark
TeaWayStones
WorldEdit

### Paper version

1.21-63-master@2288e13

### Other

NIL

**Comment by Lulu13022002** [comment]
This happens to any damage technically, the wolf doesn't take the hit/knockback but the armor still get damaged.
Issue is that spigot returns false for some reason here: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/nms-patches/net/minecraft/world/entity/animal/EntityWolf.patch#55
