### ISSUE TITLE
Auth Feature

### ISSUE THREAD

**Issue by Mineblame16** [PaperSpigot/Paper#11657]
### Is your feature request related to a problem?

Paper I was thinking if u can add a toggle for an internal server auth if online mode is false .Could Please add that amzing Feature

### Describe the solution you'd like.

I want a simple auth system like the one that simpleauth plugin provides .

### Describe alternatives you've considered.

I never found the feature on any alternative

**Comment by lynxplay** [comment]
The only auth system paper is interested in is mojangs, which already works.
We do not plan on supporting any "alternative" authentication means.
