### ISSUE TITLE
Recipes not 100%

### ISSUE THREAD

**Issue by Shabbily** [PaperSpigot/Paper#11672]
### Expected behavior

not to be able to make soul camp fire

### Observed/Actual behavior

as you can see from the image attached the recipes state that I can make a soul camp fire however I do not have the items in my inventory to allow this to be made

### Steps/models to reproduce

when taking sticks out of my invent It was not coming up as a suggestion but when they are back in it re appeared.

### Plugin and Datapack List

<html>
<body>

AdvancedJobs | Directory | 4 KB | Oct 13 17:55 |  
-- | -- | -- | -- | --
  |   | AdvancedSkills | Directory | 4 KB | Nov 26 08:31 |  
  |   | AngelChest | Directory | 4 KB | Nov 25 14:46 |  
  |   | AntiNetherRoof | Directory | 4 KB | Oct 13 07:16 |  
  |   | AntiPopup | Directory | 4 KB | Jul 21 08:15 |  
  |   | AutomaticBroadcast | Directory | 4 KB | Nov 25 15:24 |  
  |   | BedrockOffhand | Directory | 4 KB | Aug 23 09:10 |  
  |   | BetterRTP | Directory | 4 KB | Nov 26 21:12 |  
  |   | BlueMap | Directory | 4 KB | Oct 14 21:30 |  
  |   | bStats | Directory | 4 KB | Aug 17 16:53 |  
  |   | ChatEmojis | Directory | 4 KB | Mar 11 2024 |  
  |   | Chunky | Directory | 4 KB | Aug 27 07:31 |  
  |   | Citizens | Directory | 4 KB | Nov 26 21:12 |  
  |   | CoreProtect | Directory | 4 KB | Nov 26 21:45 |  
  |   | DecentHolograms | Directory | 4 KB | Oct 13 07:17 |  
  |   | DiscordSRV | Directory | 4 KB | Nov 26 21:12 |  
  |   | EconomyShopGUI | Directory | 4 KB | Nov 20 06:01 |  
  |   | Essentials | Directory | 4 KB | Nov 26 21:11 |  
  |   | floodgate | Directory | 4 KB | Aug 19 13:23 |  
  |   | FreedomChat | Directory | 4 KB | Jul 28 20:49 |  
  |   | Geyser-Spigot | Directory | 4 KB | Nov 05 08:58 |  
  |   | GSit | Directory | 4 KB | Mar 11 2024 |  
  |   | InvSeePlusPlus | Directory | 4 KB | Oct 18 16:50 |  
  |   | Lands | Directory | 4 KB | Oct 19 09:17 |  
  |   | Lootin | Directory | 4 KB | Oct 20 13:54 |  
  |   | LuckPerms | Directory | 4 KB | Aug 20 07:58 |  
  |   | MiniMOTD | Directory | 4 KB | Nov 26 21:12 |  
  |   | MoreMobHeads | Directory | 4 KB | Aug 17 19:07 |  
  |   | MyDog | Directory | 4 KB | Nov 09 10:38 |  
  |   | OreAnnouncer | Directory | 4 KB | Oct 13 07:16 |  
  |   | PlaceholderAPI | Directory | 4 KB | Jun 10 21:28 |  
  |   | ProtocolLib | Directory | 4 KB | Nov 26 18:02 |  
  |   | QuickShop-Hikari | Directory | 4 KB | Oct 20 09:24 |  
  |   | SinglePlayerSleep | Directory | 4 KB | Sep 05 09:42 |  
  |   | Skript | Directory | 4 KB | Nov 26 00:08 |  
  |   | spark | Directory | 4 KB | Nov 25 22:59 |  
  |   | SuperiorSkyblock2 | Directory | 4 KB | Aug 05 21:12 |  
  |   | SuperVanish | Directory | 4 KB | Oct 15 07:41 |  
  |   | TAB | Directory | 4 KB | Oct 23 07:33 |  
  |   | Tebex | Directory | 4 KB | Nov 26 08:31 |  
  |   | Ultimate_BlockRegeneration | Directory | 4 KB | Oct 19 10:12 |  
  |   | Vault | Directory | 4 KB | Aug 17 16:54 |  
  |   | ViaBackwards | Directory | 4 KB | Jun 08 10:05 |  
  |   | ViaVersion | Directory | 4 KB | Jun 08 10:05 |  
  |   | voicechat | Directory | 4 KB | Jul 07 14:03 |  
  |   | Vulcan | Directory | 4 KB | Oct 14 17:11 |  
  |   | WildRTP | Directory | 4 KB | Oct 24 21:57 |  
  |   | WorldEdit | Directory | 4 KB | Sep 08 23:41 |  
  |   | WorldGuard

### Paper version

This server is running Paper version 1.21.3-59-master@9bc1471 (2024-11-24T19:21:01Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)

### Other

![Image](https://github.com/user-attachments/assets/d3639ec9-b297-4884-833e-fe379c67cf49)

**Comment by shiksyt** [comment]
+1

**Comment by kennytv** [comment]
That doesn't look like a 1.21.3 client - this isn't ViaVersion support
