### ISSUE TITLE
Break blocks really fast by swapping between a pickaxe that has efficiency on it

### ISSUE THREAD

**Issue by realduziy** [PaperSpigot/Paper#11686]
### Expected behavior

Blocks break very quickly, like keeping the attributes of the other item

### Observed/Actual behavior

Blocks breaking very quickly

### Steps/models to reproduce

The best way to explain this would be via the video that is provided.

https://www.youtube.com/watch?v=ETC3vLmF2-U

### Plugin and Datapack List

None

### Paper version

This server is running Paper version 1.21.3-74-master@47f2071 (2024-11-29T16:26:16Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are running the latest version

**Comment by NonSwag** [comment]
That is a vanilla issue. I think that has been known for years

**Comment by realduziy** [comment]
oh I did not even know this, internesting

**Comment by kennytv** [comment]
https://bugs.mojang.com/browse/MC-272517 not really fixable from the server unfortunately
