### ISSUE TITLE
LootGenerateEvent not called for vaults

### ISSUE THREAD

**Issue by Grabsky** [PaperSpigot/Paper#11680]
### Expected behavior

Opening a vault would call `LootGenerateEvent` with the correct loot-table key.

### Observed/Actual behavior

`LootGenerateEvent` is not triggered.

### Steps/models to reproduce

1. Print message to the console when `LootGenerateEvent` is called.
    ```java
    @EventHandler(ignoreCancelled = true)
    public void onVaultOpen(final @NotNull LootGenerateEvent event) { 
        System.out.println("LootGenerateEvent was called with loot-table: " + event.getLootTable().getKey());
    }
    ```
2. Open a vault.
3. See that no message is printed to the console.

### Plugin and Datapack List

![Image](https://github.com/user-attachments/assets/24a33ff6-80b7-4a00-b8d6-61a815c099b7)

### Paper version

This server is running Paper version 1.21.3-67-master@d38624b (2024-11-27T20:28:58Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.3-38-de6173b (MC: 1.21.3)

**Comment by Machine-Maker** [comment]
LootGenerateEvent should not be called for Vaults. The documentation specifically says `Called when a LootTable is generated in the world for an InventoryHolder.` Vaults don't have inventories and aren't InventoryHolders. What you want is a new event for more general loot table generation events. Something like [this](https://github.com/PaperMC/Paper/pull/9666). That PR is waiting on the improved LootContext API which is needed to better represent loot table contexts.

**Comment by Strokkur424** [comment]
Poking around in the internals a bit, I found out that opening a vault actually triggers a `BlockDispenseLootEvent ` instead:
```java
@EventHandler
public void blockDispense(BlockDispenseLootEvent event) {
    this.getLogger().info("BlockDispenseLootEvent:");
    event.getDispensedLoot().forEach(item -> {
        this.getLogger().info("  " + item.getAmount() + "x " + item.getType());
    });
}
```

Opening a vault yields the following output:
```
[23:47:24 INFO]: [Paper-Test-Plugin] BlockDispenseLootEvent:                                                                                                                                            
[23:47:24 INFO]: [Paper-Test-Plugin]   1x IRON_CHESTPLATE                                                                                                                                               
[23:47:24 INFO]: [Paper-Test-Plugin]   4x IRON_INGOT
[23:47:24 INFO]: [Paper-Test-Plugin]   2x IRON_INGOT
[23:47:24 INFO]: [Paper-Test-Plugin]   1x GOLDEN_APPLE
```

So I am not even sure if that is a bug

**Comment by Machine-Maker** [comment]
Oh, there you go ^, you can use BlockDispenseLootEvent in the meantime until a more general loot table event is added.

**Comment by Grabsky** [comment]
Thank you for clarification. Yes, `BlockDispenseLootEvent` is a great alternative. Once https://github.com/PaperMC/Paper/pull/11159 is merged it should be easy enough to get the loot-table key.

I can still see something like `VaultUnlockEvent` being an ultimate solution to that (It could have an advantage of being cancellable) but that's not what this issue was originally about; I will open a discussion about this instead.
