### ISSUE TITLE
About command /credit and /demo

### ISSUE THREAD

**Issue by Axiumyuyu** [PaperSpigot/Paper#11696]
### Is your feature request related to a problem?

Is it possible to modify command `/demo` and `/credits` output like changing its text and background ?

### Describe the solution you'd like.

Maybe it can be modified by client resource pack

### Describe alternatives you've considered.

Let server send custom packet by using plugin, then client use mod to handle those packets.

**Comment by Axiumyuyu** [comment]
In fact, I even have no idea about these commands, I tried vanilla server and single player game and didn't find these commands. I don't know where these commands from.

**Comment by MiniDigger** [comment]
try using https://github.com/Phoenix616/WhatPlugin

**Comment by Axiumyuyu** [comment]
I tried and it tells me that it's a vanilla command, I also find its namespace is `minecraft:`, but vanilla server doesn't contains these commands 

https://pastebin.com/fme5c5Ke

**Comment by Leguan16** [comment]
It is definitely not a Paper command either. Try using [binary search](https://docs.papermc.io/paper/basic-troubleshooting#finding-the-culprit) to find out which plugin adds that command.
