### ISSUE TITLE
Disabeling Explosion Optimisation does not disable all Optimisations

### ISSUE THREAD

**Issue by DanielSchmerber** [PaperSpigot/Paper#11697]
### Expected behavior

Disabeling "Explosion Optimisation" Should disable all Optimisations that impact behaviour.

### Observed/Actual behavior

```
 private float getBlockDensity(Vec3 vec3d, Entity entity) {
        if (!this.level.paperConfig().environment.optimizeExplosions) {
            return this.getSeenFraction(vec3d, entity, this.directMappedBlockCache, this.mutablePos); // Paper - collision optimisations
        }
        CacheKey key = new CacheKey(this, entity.getBoundingBox());
        Float blockDensity = this.level.explosionDensityCache.get(key);
        if (blockDensity == null) {
            blockDensity = this.getSeenFraction(vec3d, entity, this.directMappedBlockCache, this.mutablePos); // Paper - collision optimisations
            this.level.explosionDensityCache.put(key, blockDensity);
        }

        return blockDensity;
    }
```
Even when disabeling optimizeExplosions, the code uses the getSeenFraction function from PaperMC instead of the getSeenPercent from Mojang
The getSeenFraction caches the collisions boxes instead of calculating them new for every entity.

However some blocks (e.g PowederSnow) have different collision boxes depending on the state of the entity
The hitbox of a powdered snow turns solid if the Entity has a falldistance >2.5 blocks.

The optimised function does not mirror this behaviour

### Steps/models to reproduce

Two commandblocks that summon TNT in a loop, one falling on a chest with a powdersnow above, the other one on a fence

Vanilla behaviour: https://streamable.com/ry9kol

Paper behaviour: https://streamable.com/8qek9s

You can see, that in the paper explosions every TNT in the air is affected by the explosion, since the first call to getSeenFraction cached the collision state of the PowederedSnow for a TNT that was onground

### Plugin and Datapack List

No Plugins required

### Paper version

This server is running Paper version 1.21.3-76-master@27e4ddc (2024-11-30T10:07:53Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are running the latest version

**Comment by Spottedleaf** [comment]
Please provide the singleplayer world

**Comment by DanielSchmerber** [comment]
Sure here is the world i used
i simplified the setup to only require a button press to see the behaviour
https://mega.nz/file/ET4jzRBI#pL5MO3QHG0sOVvQ50roSfLsMsZ9ag3bc7y2UacnFYSg

**Comment by Spottedleaf** [comment]
Resolved by
- https://github.com/Tuinity/Moonrise/commit/3624d261f827deae3c32d57079565f69bf0e8c05
- https://github.com/Tuinity/Moonrise/commit/ca3d776562002cc01582e239da01589902cf0417
- https://github.com/PaperMC/Paper/commit/0f90942b1a59d36dffb57325066744b840decef1
