### ISSUE TITLE
Readdition of entity effect immune config

### ISSUE THREAD

**Issue by Dinoboy50** [PaperSpigot/Paper#11717]
### Is your feature request related to a problem?

Hello would it be possible to add a config option that allows mobs that are immune to effects (undead for poison/regen) and others.

This used to be an option in 1.20.4 im not sure when it was removed exactly but it is not present in 1.21.1.
My server somewhat relied on this config option to allow zombies to have the ability to use regeneration effect. There is no other way of allowing them to have regeneration unless you wanna use reflection/direct nbt

### Describe the solution you'd like.

Config option(s) for allowing mobs to use effects they would be immune to in vanilla

i have looked at the nms code and it looks to me all it would require is a conditional(s) for one method to check config option(s)

### Describe alternatives you've considered.

im not sure about alternatives, perhaps a method with (nbt) internally that can do this per mob, but that increases the work a bit. im perfectly happy having a config option

**Comment by TonytheMacaroni** [comment]
You can just modify the [respestive tags](https://minecraft.wiki/w/Tag#Entity_type_tags_2) with a datapack or the tag lifecycle event.

For example, look at `ignores_poison_and_regen`, `inverted_healing_and_harm`.

**Comment by Machine-Maker** [comment]
Not *all* registries, at the moment just `enchantment`, `game_event` and `painting_variant`. But you can modify all the tags you want using the tag lifecycle events.

**Comment by Dinoboy50** [comment]
EntityPotionEvent doesnt really help as applying the effect itself is impossible to zombies/undead

Also from what i can see under entity tags in the repestive tags list, there is no immune to healing/poison,  i do see immune to ozzing and infested though.

I dont see how both of these could solve the problem at this point

**Comment by Machine-Maker** [comment]
You can see examples and explanations in the javadocs. https://jd.papermc.io/paper/1.21.4/io/papermc/paper/tag/PostFlattenTagRegistrar.html
