### ISSUE TITLE
1.21.4 doesn't compile

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#11719]
### Expected behavior

Should compile from source, freshly cloned paper on windows 11

### Observed/Actual behavior

error: not a statement

https://pastebin.com/3JWjRA2W

### Steps/models to reproduce

Clone paper repo,
./gradlew applyPatches && ./gradlew createMojmapBundlerJar

### Plugin and Datapack List

N/A

### Paper version

d4630f1223ba8cef0f9767d22f70999f1292cbcf

**Comment by kennytv** [comment]
Your jdk is outdated/whack

**Comment by electronicboy** [comment]
Yea, that's outdated, https://bugs.openjdk.org/browse/JDK-8320145
