### ISSUE TITLE
Is Paper incompatible with the Essentials/EssentialsX Backup function?

### ISSUE THREAD

**Issue by VL4DST3R** [PaperSpigot/Paper#11725]
### Expected behavior

Backups of a paper server are being done successfully.

### Observed/Actual behavior

I recently realized (thankfully before any real data loss could occur) that all of the backups I create of my worlds via the Essentials/EssentialsX plugin "backup" function - which just executes a user defined script - results in maps that are incomplete or otherwise corrupted.

Here is an example of one such backup opened inside MCA Selector:
![Image](https://github.com/user-attachments/assets/a258d795-dca3-4d53-b18b-16a71bcc4fc3)
Notice how a good part of the chunks - those that actually have the most player activity - are missing entirely. If I open this world it will just regenerate those chunks as if nothing was there. Notice also how it seems to corrupt(?) the save at a *region* level, not chunk, as represented by MCA.

The only (unrelated) mention to Essentials that I could find here was [this apparently unrelated issue](https://github.com/PaperMC/Paper/issues/3337) so I'm not sure if I missed something or only I am affected/my script specifically is not playing well with paper.

I asked this here instead of their issue tracker because I believe it may have something to do with how paper handles file access. As I said this "function" of Essentials is just a glorified call to a bat script. The plugin AFAIK doesn't do anything besides announcing when it is disabling autosaving and running the script. In my case the one that I made simply zips the save folder someplace else and appends a timestamp to it.

I also know that Paper attempts to parallelize certain server aspects which in the past did not always play nice with some plugins like async worldedit, so maybe the chunk access is in the same situation as well? them being locked or modified while the backup is being made? so I wanted to ask for some advice about how to debug or address this.

### Steps/models to reproduce

n/a

### Plugin and Datapack List

n/a

### Paper version

Various versions throughout 1.19 to 1.21 (present), this is not a new or version specific issue, I just never looked properly into it.

**Comment by electronicboy** [comment]
Paper does not do blocking IO to write chunk/region data to the disk, it relies upon the host to deal with this aspect as it needs to, this does have some caveats. Windows is also generally a huge caveat here, many backup tools are written with the behavioral expectation of linux which doesn't have as much aggressive file locking mechanisms, and deals with non-blocking IO in a much more reliable manner.

You can reenable the blocking IO by setting `-DPaper.enable-sync-chunk-writes=true` in your startup flags, may require some quotes on that to mitigate windows oddball command processing. outside of that, live backups are generally not something that is entirely supported, while it does work with some degree of reliability with the correct setup/environment, you are always running on the line of unsupported behavior.

**Comment by VL4DST3R** [comment]
> You can reenable the blocking IO

How would this help here? Wouldn't it prevent any kind of backup at all then?

> live backups are generally not something that is entirely supported, [...] while it does work with some degree of reliability with the correct setup/environment

Can you give me some pointers about what this would entail? I would imagine I'm not the only paper server owner on windows that wants to do backups while the server is running. There are also plugins that supposedly do this in a more involved manner like [this](https://www.spigotmc.org/resources/server-backup-ingame-dropbox-ftp-backup-1-18-1-21-multithreaded.79320/) - whould this work better/at all with paper?

**Comment by electronicboy** [comment]
>> You can reenable the blocking IO
>
> How would this help here? Wouldn't it prevent any kind of backup at all then?

re-enabling blocking IO would tell the OS to write data NOW, rather than letting it sit around in memory, which might correct some issues caused by the writes being delayed, i.e. desynced region headers, etc

>> live backups are generally not something that is entirely supported, [...] while it does work with some degree of reliability with the correct setup/environment

> Can you give me some pointers about what this would entail? I would imagine I'm not the only paper server owner on windows that wants to do backups while the server is running. There are also plugins that supposedly do this in a more involved manner like [this](https://www.spigotmc.org/resources/server-backup-ingame-dropbox-ftp-backup-1-18-1-21-multithreaded.79320/) - whould this work better/at all with paper?

I cannot provide support for Windows; I do not recommend using plugins for backups, but Windows limitations mean that plugins are the only real option here, which comes with a whole host of caveats because Java does not always respond well to cases where it can't access files on windows in some weird edge cases.

**Comment by VL4DST3R** [comment]
Reading a bit on `sync-chunk-writes` inside server.properties left me a bit confused - I have it already set to true there, doesn't that mean this is already the case? `-DPaper.enable-sync-chunk-writes=true` overrides this behavior?

**Comment by electronicboy** [comment]
Paper disables that setting entirely because it went against the nature of async chunk saving, this option is pretty much only relevant on windows due to the differences in how it and most other OSes deal with non-sync'd IO
