### ISSUE TITLE
`PotionMeta#hasCustomName` compatability

### ISSUE THREAD

**Issue by tal5** [PaperSpigot/Paper#11732]
### Expected behavior

For `PotionMeta#hasCustomName` to return whether the `PotionMeta` has a custom name.

### Observed/Actual behavior

`PotionMeta#hasCustomName` seems to call `ItemMeta#hasCustomName` instead of the `PotionMeta` deprecated redirect, I assume because the override in `CraftMetaItem` takes priority?

### Steps/models to reproduce

Wrote a test plugin:
```java
ItemStack item = player.getEquipment().getItemInMainHand();
PotionMeta meta = (PotionMeta) item.getItemMeta();
player.sendMessage(meta.hasCustomName() + "|||||" + meta.getCustomName());
try {
    player.sendMessage(meta.getClass().getMethod("hasCustomName").toString());
}
catch (NoSuchMethodException e) {
    throw new RuntimeException(e);
}
return true;
```
On latest Spigot:
![Image](https://github.com/user-attachments/assets/6d5f97b7-543a-40fa-bda2-53f741134d61)
On latest Paper:
![Image](https://github.com/user-attachments/assets/bb23f66e-4976-4c5a-a641-62d71d34a2f9)
Item used: `/give @s minecraft:potion[minecraft:potion_contents={custom_name:"shadow_walk"}]`

### Plugin and Datapack List

```
> plugins
[21:39:16 INFO]: Server Plugins (2):
[21:39:16 INFO]: Bukkit Plugins:
[21:39:16 INFO]:  - Debuggery, SpigotTestPlugin
```
```
> datapack list
[21:40:00 INFO]: There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]
[21:40:00 INFO]: There are no more data packs available
```

### Paper version

```
> version
[21:40:31 INFO]: Checking version, please wait...
[21:40:31 INFO]: This server is running Paper version 1.21.4-14-master@b746d9d (2024-12-11T21:22:39Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.3-36-d8b66dd (MC: 1.21.3)
```

**Comment by lynxplay** [comment]
As  noted in #11788, we cannot fix `#hasCustomName` as that would break the newly introduced `#hasCustomName` method in ItemMeta.
It is an unfortunate break, but one we cannot fix.
The linked PR will correctly restore the getter and setter tho, so the workaround for this will simply be `#getCustomName != null`.

**Comment by lynxplay** [comment]
Looking at the PR, the getters and setters should be working as they are not implemented in CraftMetaItem.
So yea, see the above mitigation for this, and again sorry on the missing communication on this break, was a mistake on our part.
