### ISSUE TITLE
EULA file is not properly checked when created through CMD

### ISSUE THREAD

**Issue by Kichura** [PaperSpigot/Paper#11745]
### Expected behavior

Running `echo eula=true > eula.txt` and then `(path_to_java)\bin\java -jar paper-1.21.4-14.jar nogui` makes the server run properly.

### Observed/Actual behavior

When attempting to do the two commands above as explained in the expected behavior section, This is what you actually see:

![Image](https://github.com/user-attachments/assets/0fb93287-07c6-475a-9431-8eb9eb808d73)
_(ALT. Text: Paper Server asks end-user to agree to EULA when they already have through the `echo` command)_

### Steps/models to reproduce

1. Create a new Windows Server 2025 VM,
2. Get a brand new copy of Paper 1.21.4,
3. Get the latest temurin JDK 21 version,
4. Attempt to run the two commands,
5. Server should stop in the EULA text.

### Plugin and Datapack List

*(No plugins nor datapacks were used on this testing unit)*

### Paper version

`Paper 1.21.4-14`

### Other

The terminal shown onscreen has cmd active by writing `conhost` to the powershell prompt first as powershell didn't seem to like the java command properly, however i may be certain that either the terminal app is bad or something else is causing the eula file to not get properly checked by the server software. Updating to Java 24 resolves the OS metadata text but the EULA issue still persists there.

**Comment by electronicboy** [comment]
<img width="572" alt="Image" src="https://github.com/user-attachments/assets/76e09fea-ec6a-4f0b-9d75-e2034f82c084" />

windows echo is apparently leaky
