### ISSUE TITLE
PluginLoader not called when using Kotlin

### ISSUE THREAD

**Issue by JaroxCraft** [PaperSpigot/Paper#11755]
### Expected behavior

I had a LibrariesLoader class in Kotlin implementing the PluginLoader Inverface to load all required libraries. I had registered the loader correctly in the  paper-plugin.yml file and made sure everything else was correct. But it didn´t work. It didn´t even call the classloader function.

### Observed/Actual behavior

the PluginLoader was not invoked

### Steps/models to reproduce

Create a new paper plugin in kotlin and try to use a Loader

### Plugin and Datapack List

just my own plugin with the loader registered

### Paper version

This server is running Paper version 1.21.4-15-master@bb76819 (2024-12-15T09:48:21Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are running the latest version

### Other

However, when i took the exact same code in Java without changing anything, it worked completly fine.

**Comment by electronicboy** [comment]
did you have the kotlin stdlib shaded, etc?

**Comment by electronicboy** [comment]
Well, if there is no stdlib then you're going to be missing a lot of the fluff that kotlin injects, that's commonly why early stuff is done using Java, not sure what phase the loader runs
the lack of an exception is interesting but, not entirely surprising as the exception handling around plugin loading stuff is always *fun*

**Comment by JaroxCraft** [comment]
nevermind, I shaded it and everything worked

**Comment by Strokkur424** [comment]
@JaroxCraft would just be useful for you to know: If you write the PluginLoader class using Java, you can specify the dependencies for Kotlin and use Kotlin in the rest of your project safely

**Comment by JaroxCraft** [comment]
> @JaroxCraft would just be useful for you to know: If you write the PluginLoader class using Java, you can specify the dependencies for Kotlin and use Kotlin in the rest of your project safely

That's what i did, yes

**Comment by Strokkur424** [comment]
Ah okay great. You don't need to shade the kotlin stdlib in that case
