### ISSUE TITLE
Using `update` folder to migrate plugin from spigot to paper plugin

### ISSUE THREAD

**Issue by Wolf2323** [PaperSpigot/Paper#11750]
### Expected behavior

While migrating a plugin from a spigot plugin to a paper plugin, it should replace the previous jar in the `/plugins` folder when the new jar is placed in the `/plugins/update` folder.

### Observed/Actual behavior

The update is not performed at all.

### Steps/models to reproduce

Create a plugin with a `plugin.yml` and put it in the `/plugins` folder the create a second jar with a `paper-plugin.yml` and put it in the `/plugins/update` folder and restart the server.

### Plugin and Datapack List

```
[14:05:47 INFO]: Server Plugins (13):
[14:05:47 INFO]: Paper Plugins:
[14:05:47 INFO]:  - BetonQuestPlus
[14:05:47 INFO]: Bukkit Plugins:
[14:05:47 INFO]:  - BetonQuest, Citizens, DecentHolograms, EffectLib, Essentials, EssentialsSpawn, packetevents, PlaceholderAPI, ProtocolLib, Vault
[14:05:47 INFO]:  WorldEdit, WorldGuard
```
```
[14:06:37 INFO]: There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]
[14:06:37 INFO]: There are no more data packs available
```

### Paper version

```
[14:06:54 INFO]: Checking version, please wait...
[14:06:54 INFO]: This server is running Paper version 1.21.3-15-master@99f4bb2 (2024-11-08T11:34:49Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are 66 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.1-128-d348cb8 (MC: 1.21.1)
```

**Comment by Warriorrrr** [comment]
I wasn't able to reproduce this, I created two blank projects with mcdev, one with a plugin.yml, other with paper-plugin.yml with the same plugin name. The server moved the file in the update plugin to the plugin folder just fine.

Could you provide the (paper-)plugin.yml files you were experiencing this issue with?

**Comment by Wolf2323** [comment]
Of cause. My Old plugin.yml looks like this
```yaml
name: BetonQuestPlus
main: com.betonquest.betonquestplus.BetonQuestPlus
version: 1.0.0-DEV-UNOFFICIAL
api-version: 1.20.0
description: Additional Adventure Supplies
website: https://docs.betonquest.com/betonquestplus
author: BetonQuest Commercial
authors: [ Wolf2323 ]
depend:
  - BetonQuest
```

And my paper-pluigin.yml
```yaml
name: BetonQuestPlus
main: com.betonquest.betonquestplus.BetonQuestPlus
version: 1.0.0-DEV-UNOFFICIAL
api-version: 1.20.0
description: Additional Adventure Supplies
website: https://docs.betonquest.com/betonquestplus
author: BetonQuest Commercial
authors: [ Wolf2323 ]
dependencies:
  server:
    BetonQuest:
      load: BEFORE
      required: true
```

I only changed the depend(encies)

**Comment by Warriorrrr** [comment]
I copied those and tried again but still can't reproduce it, could you try reproducing this yourself on the latest experimental build?

**Comment by Wolf2323** [comment]
I will do right now ;)

**Comment by Wolf2323** [comment]
Ok, now I am confused, the issue is solved. I tested on the latest version and there everything works fine now, even if I checked multiple times when I had the issue. Thank you to look into this and sorry for the the you invested.

**Comment by Warriorrrr** [comment]
No worries, at least it's resolved now. While looking through the code I think I did see one thing that could be improved, so it wasn't for nothing
