### ISSUE TITLE
Sitting cat on a chest does not block redstone signal

### ISSUE THREAD

**Issue by Dariangab** [PaperSpigot/Paper#11760]
### Expected behavior

Chest with an item inside crestes a redstone signal to camporator. Sitting cat on this chest blocks the chest and redstone signal from it to comporator

### Observed/Actual behavior

Though sitting cat blocks the acces to chest, It does not block the redstone signal from this chest

### Steps/models to reproduce

1. Tame a cat
2. Put an item to the chest
3. Set a comporator applied to chest, chest gives redstone signal
4. Put a cat on the chest
5. Make cat sit/stand and cat despite it condition still gives redstone signal

### Plugin and Datapack List

Anticreeper, AuthMe, BooksNews, CoreProtect, ImageFrame, LPC, LuckPerms, Playtime, SkinsRestorer. TAB Voicechat

### Paper version

This server is running Paper version 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version

**Comment by Dariangab** [comment]
As i understand the problem is that somehow on server even the chests that are not accesible continue to create a redstone signal even with a hopper attached to it. https://www.youtube.com/watch?v=BudRgJyLPlA&ab_channel=2No2Name thats how it should have been worked, but it didnt

**Comment by Owen1212055** [comment]
As of 1.21.4, I cannot reproduce this issue.

Please try reproducing the issue on latest MC version! 😄 
![Image](https://github.com/user-attachments/assets/da587b66-1c51-489a-9142-5ab780bcd63d)
![Image](https://github.com/user-attachments/assets/2cc8c159-8b0e-4471-a834-445a2620084d)
