### ISSUE TITLE
Sound tag IDs are spelled incorrectly, please fix asap.

### ISSUE THREAD

**Issue by alexfry756** [PaperSpigot/Paper#11828]
### Expected behavior

in the /sound command there is an error with the sound. instead of the normal id of the sound tags it says "/sound craftsound{holder=reference{resourcekey[minecraft:sound_event / minecraft:ambient.basalt_deltas.additions]=soundevent[location=minecraft:ambient.basalt_deltas.additions, fixedrange=optional.empty]}}"

Up to version 15 of the kernel 1.21.4 paper such an error did not occur.

### Observed/Actual behavior

It should be like this: sound ambient_basalt_deltas_additions

and so on with all the sound tags.

### Steps/models to reproduce

-

### Plugin and Datapack List

AuthMe, Citizens, CMI, CMILib, DeluxeMenus, Interactions, PL-Hide, PlaceholderAPI, WorldEdit, WorldGuard

### Paper version

This server is running Paper version 1.21.4-41-main@d85d318 (2024-12-26T08:45:00Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.4-15-bb76819 (MC: 1.21.4)

**Comment by Doc94** [comment]
Looks like an issue with CMI and how they are adding sounds to the command suggestions.

**Comment by electronicboy** [comment]
Sound is not a vanilla/paper command, this is likely an artifact of spigots recent changes exposing a flaw in how whatever plugin is providing that command is exposing this stuff

**Comment by alexfry756** [comment]
The thing is that the plugin was updated before the changes to version 15 of the server core, and when I just reverted back to version 15 of the core, everything started working fine.

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Paper/commit/46c6f497c7e5e3f6d7ee9e226837d44211737590

is what what of induced this, the plugin is relying on broken implementation details, we can maybe fix this, I'd need to defer this to @Machine-Maker but, the plugin dev should really be the one to fix this

**Comment by kennytv** [comment]
Spigot has been warning about removing any assumptions of these enums being enums, that includes toString, so CMI needs to fix this in any case. Please also report it there

**Comment by alexfry756** [comment]
I wrote to the CMI plugin developer on github.. I hope to get rid of this problem as soon as possible❤️
