### ISSUE TITLE
Armadillo not taking damage from a campfire while rolled up,

### ISSUE THREAD

**Issue by YungRavv** [PaperSpigot/Paper#11837]
### Expected behavior

In vanilla a rolled up (scared due to a zombie being nearby) Armadillo would be shown taking damage while standing on a campfire, though it physically takes 0 damage. 

### Observed/Actual behavior

The rolled up armadillo isn't shown to take any damage from the campfire. 

Likely due to it technically taking 0 damage, therefore the animation or whatever is being skipped.

### Steps/models to reproduce

Armadillo on a regular campfire, in a 1x1, a zombie within a couple of blocks for the armadillo to roll up.

![Image](https://github.com/user-attachments/assets/776d6e0b-79b8-4cad-86f8-68e3a430d9fd)

### Plugin and Datapack List

![Image](https://github.com/user-attachments/assets/a3a66600-6679-48cf-a01d-342af3cf43d0)

![Image](https://github.com/user-attachments/assets/208acb01-fbfc-4dcb-8b0a-74dc5d9faee2)

### Paper version

This server is running Paper version 1.21.4-53-main@326c687 (2024-12-27T12:59:10Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

**Comment by Warriorrrr** [comment]
Issue was diagnosed in discord, turned out to be caused by another plugin
