### ISSUE TITLE
1.21.4 Build 41 and previous - Bundle and other recipes corrupt / mixed up in BedRock but not Java

### ISSUE THREAD

**Issue by dmyers7** [PaperSpigot/Paper#11833]
### Expected behavior

Recipes should make what they are coded for on Bedrock (iOS in this case).  The bundle recipe is simply string and leather.  Having those ingredients  normally unlocks the recipe and then allows you to make it.

### Observed/Actual behavior

In the Java client (MacOS desktop) everything appears to be working as expected.  Sting and Leather make a brown bundle and then adding die to the brown bundle or for that matter and other color bundle will change the color as expected.  Using a Bedrock client, all bundle recipes show changing its color from another single other color.  There is no recipe to create a simple brown bundle to start.  Interestingly the Shulker Shell recipe is a String and a piece of Leather.  There is no Shulker Shell in the Java version; only a Shulker Box.  I don't believe there is a recipe for the shell; it's only a dropped mob item from a Shulker.  I can't remove the Shulker Shell recipe as an op, so something is mixed up.  Of course a Shulker Shell is not made with Leather and String.  After making a Shulker Shell in Bedrock (with a rope and leather), I can drag and drop items into it as if it were a bundle (or shulker box?) but can't open it to retrieve the item.  There is no recipe to make a Shulker box, but there are recipes to color one like the bundle issue in Bedrock (Java is ok) .  Creating two shulker shells and a chest and combining them on a crafting table show that they should make a shucker box, but clicking on "craft" does not allow you to craft one into your inventory in Bedrock; Java is ok.

If I give myself a bundle the server gives me a shulker shell on Bedrock; Java receives a bundle.  Giving myself a shulker box and it works on both; Java I can open it as part of my inventory (more like a bundle), Bedrock I have to place it and open it but it works.

If I create my own world on my iPad (iOS Bedrock version), bundles are crafted as expected and work as expected.  It's only an issue when logging into my PaperMC server on iOS.

### Steps/models to reproduce

I gave myself all recipes in both bedrock and Java.  Had leather and string, but same if you give yourself some.  Follow through with the steps in actual behavior and see that the recipes misbehave. 

### Plugin and Datapack List

There are no additional plugins installed.

### Paper version

 latest 1.21.4 build 41

### Other

Running the latest iOS and Desktop clients and the latest 1.21.4 PaperMC server on a raspberryPi 4 4GB.

**Comment by Machine-Maker** [comment]
Paper doesn't support bedrock clients. You should try reporting this to the bridging system you are using (probably Geyser)
