### ISSUE TITLE
Picking up items caused an error.

### ISSUE THREAD

**Issue by fyxrim** [PaperSpigot/Paper#11846]
### Expected behavior

![Image](https://github.com/user-attachments/assets/a86827a1-6a11-4fe3-8c19-62b8d23171c5)
Versions below 1.20.1 don't have this issue, but now there is a problem in versions 1.21 and above. The author said it cannot be fixed. It is suggested to turn off Paper redirection, which will likely solve the issue.

### Observed/Actual behavior

no

### Steps/models to reproduce

no

### Plugin and Datapack List

![Image](https://github.com/user-attachments/assets/8a3a93d7-3a24-4ed5-83b5-8086bbc59bce)

### Paper version

![Image](https://github.com/user-attachments/assets/f87114b5-85f1-4f3b-9407-d968006b0a23)

**Comment by Strokkur424** [comment]
Pretty sure this is not a paper issue. Tell the author of that plugin to update their dependency to 1.21.3.
If they need help figuring it out, they are welcome to ask in the #paper-dev channel in the PaperMC Discord server

**Comment by NonSwag** [comment]
1. You are using Purpur, but this is the paper GitHub 
2.  The author of UltraBind just has to compile the plugin for 1.21.3
