### ISSUE TITLE
org.bukkit.attribute.Attribute.BURNING_TIME description spelling mistake

### ISSUE THREAD

**Issue by phant0m2290** [PaperSpigot/Paper#11862]
### Expected behavior

The description says ingition but it should be ignition
https://jd.papermc.io/paper/1.21.4/org/bukkit/attribute/Attribute.html#BURNING_TIME
![Image](https://github.com/user-attachments/assets/0b8b093e-faab-4b2b-8937-2a9b383413d3)

### Observed/Actual behavior

Spelling mistake. It says ingition

### Steps/models to reproduce

Open javadocs or sourcecode or whatever and look at the description of org.bukkit.attribute.Attribute.BURNING_TIME

### Plugin and Datapack List

N/A

### Paper version

paper-api:1.21.4-R0.1-SNAPSHOT

**Comment by x9nico** [comment]
I done a PR to fix it : https://github.com/PaperMC/Paper/pull/11864

**Comment by lynxplay** [comment]
Resolved by https://github.com/PaperMC/Paper/pull/11864
