### ISSUE TITLE
All-U-Want Mod

### ISSUE THREAD

**Issue by ItsHarry** [PaperSpigot/Paper#26]
Hello,

Apparently, it's possible to stack unstack-able items in Survival mode using a mod call All-U-Want which can be found here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288788-all-u-want-create-and-edit-items-entities-spawners

Any chance you could add a restriction in PaperSpigot to prevent this? Pretty sure it uses packet 47 to do this

Thanks

**Comment by Zbob750** [comment]
I'm having trouble reproducing this as anything other than a client-side issue.
The server never seems to believe the player's inventory has multiple items stacked and doesn't treat them as such.

**Comment by ItsHarry** [comment]
Extremely sorry for the time wasted, it appears I have been informed wrong by another user.
