### ISSUE TITLE
Whitelist issue.

### ISSUE THREAD

**Issue by YoloxPanda** [PaperSpigot/Paper#29]
Hey!

Im having some trouble via whitelisting players. So heres what happens. I whitelisted myself on the server and opped myself. but whenever i leave and try to reconnect it says Im not whitelisted.

whitelist.json http://gyazo.com/259d1b67137537dcdd5d704662635579

issue: http://gyazo.com/129a94801a2fd0b012dcba28e20c81f7

**Comment by Zbob750** [comment]
I tested without bungee and couldn't reproduce.
https://drive.google.com/open?id=0B5xdwK8OIEwGY25nTUF5N0J3T0k&authuser=0

Two others tested with bungee and also couldn't reproduce...

**Comment by YoloxPanda** [comment]
Hey!

weird, ill try to look into this a little bit more! thanks for clarifying this! :)

**Comment by Zbob750** [comment]
Closing as we cannot reproduce this given the information.
