### ISSUE TITLE
Tnt Problem

### ISSUE THREAD

**Issue by TheExceed** [PaperSpigot/Paper#30]
Ever since I downloaded the newest version, I have had this tnt problem.
Primed tnt will destroy other primed tnt, rendering tnt cannons useless.

**Comment by Zbob750** [comment]
Could you please provide additional information? I cannot reproduce this behavior.
Your current version (as seen in logs and /version), a link to your paper.yml and spigot.yml files (gist or hastebin please)
As well as any other details you deem pertinent? Thanks

**Comment by TheExceed** [comment]
https://youtu.be/tGFhbMnxR4g <- proof of occurence
http://prntscr.com/7ndtga <- version
http://pastebin.com/6s8gjJ98 <- spigot.yml
http://pastebin.com/zS3wjfKB <- paper.yml

Plugins (64): CapsLock, PlugMan, SimpleWarnings, NametagEdit, ColorsGUI, BanManager, kitspreview, DeluxeTags, RateOfXray, DeathMessages, SMC_IpCheck, Tablist, Titlebar, AsyncWorldEditInjector, CoreProtect, WorldEdit, HealthBar, GameModeInventories, ClearLag, Playerz, WorldBorder, Modifyworld, UnlimitedAnvil, Votifier, Multiverse-Core, ProtocolLib, NoCheatPlus, AsyncWorldEdit, IPWhitelist, Shopkeepers, BattleLevels, PermissionsEx, SimpleHelpTickets, CommandWatcher, Lottery, SMC_PermCommands, Multiverse-Portals, Vault, GAListener, PlayersNear, MassiveCore, HolographicDisplays, WorldGuard, SimpleTrails, PlayerVaults, ServerSigns, Multiverse-NetherPortals, afkTerminator, boosCooldowns, Essentials, SilkSpawners, WhatIsIt, EnjinMinecraftPlugin, floAuction, Factions, ArchonCrates, EssentialsSpawn, PvPManager, FBasics, Autorank, DeluxeChat, ObsidianDestroyer, DeluxeJoin, FactionChat

**Comment by TheExceed** [comment]
Still waiting for help ;c

**Comment by Zbob750** [comment]
[I am still unable to reproduce your issue.](https://drive.google.com/drive/folders/0B5xdwK8OIEwGfmlsaGMzaTlPT3Nvd3JBZXZNOUhsamQyX1lub3dqdmJQNjN0OWY3MjhpMjQ)

Please check that your plugins are not causing this behavior.

**Comment by TheExceed** [comment]
Any suggestion on what would cause this? Because like I said, upon updating to a newer version of paperspigot, that is when it started having problems.

**Comment by TheExceed** [comment]
#This option reduces the explosions of mass amounts of tnt, and reduces tnt lag
tnt:
  tnt-reducer: false

Well, didn't think clearlag would cause it, thanks for the help

**Comment by Zbob750** [comment]
Ah yes, we noticed that a while ago when someone asked us to look into how ClearLagg "helped" TNT issues. I should've noticed it and remembered that. Unfortunately I did not. Could've saved you some digging.

My bad. Glad you got it solved though! :)
