### ISSUE TITLE
unable to build spigot.jar

### ISSUE THREAD

**Issue by xion87** [PaperSpigot/Paper#31]
[INFO]
[INFO] --- maven-install-plugin:2.3:install (default-install) @ paperspigot ---
[INFO] Installing /root/PaperSpigot/PaperSpigot-Server/target/paperspigot-1.7.10                                              -R0.1-SNAPSHOT.jar to /root/.m2/repository/org/github/paperspigot/paperspigot/1.                                              7.10-R0.1-SNAPSHOT/paperspigot-1.7.10-R0.1-SNAPSHOT.jar
[INFO] Installing /root/PaperSpigot/PaperSpigot-Server/dependency-reduced-pom.xm                                              l to /root/.m2/repository/org/github/paperspigot/paperspigot/1.7.10-R0.1-SNAPSHO                                              T/paperspigot-1.7.10-R0.1-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] PaperSpigot-Parent ................................ SUCCESS [2.231s]
[INFO] Minecraft Server .................................. SUCCESS [4.419s]
[INFO] Minecraft Server Relocation ....................... SUCCESS [5.571s]
[INFO] PaperSpigot-API ................................... SUCCESS [14.630s]
[INFO] PaperSpigot ....................................... SUCCESS [37.500s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:04.692s
[INFO] Finished at: Mon Jul 06 10:25:40 CEST 2015
[INFO] Final Memory: 52M/1636M
[INFO] ------------------------------------------------------------------------
Unable to create paper spigot jar

**Comment by Zbob750** [comment]
Works fine here, and it should've worked fine for you based on that log.

Check to make sure the jar isn't hiding in Paper/PaperSpigot-Server/target/paperspigot-1.7.10-R0.1-SNAPSHOT.jar

**Comment by xion87** [comment]
yeah working great thank you  here
