### ISSUE TITLE
Knockback Issues

### ISSUE THREAD

**Issue by lukas81298** [PaperSpigot/Paper#32]
Hello,

about 2 weeks ago, I switched from Spigot to PaperSpigot 1.7.10. First, thank you for providing this great software.
Since I am using Paper, the knockback seems to be completely different to the one of the normal spigot. Some players almost get no knockback, while others get "normal" knockback. I do not mean the "Relog".
I tried it with the latest Spigot patch and everything was normal again.
Furthermore, I tried to start the server without any plugins, with a new world and I resettet all the configs.

**Comment by Zbob750** [comment]
I'll be trying to find a concrete way to test this tonight, hopefully I'll be able to reproduce it. Is there any other information you think may help?
