### ISSUE TITLE
Cant install on a hosted server from website.

### ISSUE THREAD

**Issue by Knight927** [PaperSpigot/Paper#33]
Hello. I am currently running 1.8 Spigot on my server hosted by CubedHosting . I want the 1.7 tnt physics but also want to stay in 1.8. SO when i try to instal it , it will say that it cant extract so it wont be a plugin into my server. Can someone please tell me how to install it? (Note) I am NOT running my server. It is hosted by a website called CubedHosting.

**Comment by Byteflux** [comment]
GitHub issues isn't a place to ask about usability. This is a place for reporting bugs in the software, not a place for asking how to use the software.
