### ISSUE TITLE
ChunkMap caching patch causing extreme lag

### ISSUE THREAD

**Issue by Go-ogle** [PaperSpigot/Paper#34]
After upgrading to the recent build #309 which introduced the 'ChunkMap caching' patch, players been complaining about serious lag issues. These lag issues are usually described as major lag spikes, bringing down their FPS to extremely low numbers every 10-15 seconds or so.

I noticed that the latest build; #310 contains improvements to said ChunkMap caching patch, has this issue been addressed in these improvements?

**Comment by Byteflux** [comment]
The most recent updates might have an impact yeah, give it a shot.

**Comment by Byteflux** [comment]
Oh, and double check memory usage too because this change means that loaded chunks will use up a bit more memory to cache the ChunkMaps.

**Comment by k3ldon** [comment]
some players informed to me after updates, lag from server side and from fps, this have relation? yesterday no problems

**Comment by Byteflux** [comment]
@k3ldon Try updating to the latest version. There's been some changes in the last few hours.

**Comment by k3ldon** [comment]
ok ty

**Comment by Go-ogle** [comment]
Just tried build #310 in a small test server, some users still suffered from the exact same symptoms mentioned before. Reverting to #308 has fixed this issue for now.

**Comment by Byteflux** [comment]
Alright, thanks for trying. I'll make this feature configurable, as it should be considering it's experimental.

If you don't mind, we would greatly appreciate if you did occasionally test new updates on your test server to see if you still experience issues.

Eventually it'd be nice to make this feature default as it greatly benefits server TPS (with no side effects when done properly)

**Comment by k3ldon** [comment]
my lastest test:
http://timings.aikar.co/?url=11884609
http://timings.aikar.co/?url=11885095

**Comment by Byteflux** [comment]
@k3ldon Your timings look perfect. No lag.

**Comment by k3ldon** [comment]
yeap but looks like my players have lag with the fps the first timing is #309 and second #310. how i can compile 308?
 java -jar PaperTools.jar rev 308?

**Comment by Go-ogle** [comment]
Here is the unofficial mirror for the PaperSpigot builds, just download the jar, no need to compile it: http://ci.minelink.net/job/PaperSpigot/194/

As for testing, with PaperSpigot being my new-found love for it's constant stream of new features I usually update to the newest build as soon as it's out anyway. I'd be happy to report any futures issues I find.

**Comment by k3ldon** [comment]
well with the last fix is not working... so im using build 308

**Comment by ijskobar** [comment]
The FPS lag is caused due to the client reaching maximum allocated memory, massive stutters occur until GC kicks in dropping the memory usage about 10%, repeating the processing a few moments later. The high memory usage appears to be caused by the client not unloading chunks with this patch enabled. Unlike MapChunkBulk, MapChunk's "Ground-Up Continuous" and "Primary Bit Mask" flag are not static, for the client to unload a chunk it has to receive a MapChunk packet with "Ground-Up Continuous" set to true and "Primary Bit Mask" set to 0
![Image](http://i.imgur.com/DG7aALA.png)

**Comment by Byteflux** [comment]
@ijskobar Thanks for the detailed report! Helped out a lot, I've pushed up a couple changes that should fix the unloading issue in addition caching (when enabled) will only work for whole chunk maps that represent the whole chunk (Ground-Up Continuous = True and Primary Bit Mask = 65535). Should help out a lot in MapChunkBulk mostly. Let me know if you're still experiencing issues in either the latest 1.7 or 1.8 versions.

**Comment by Go-ogle** [comment]
@Byteflux That's good to hear, I'll roll out the newest build to my test server now.

**Comment by Go-ogle** [comment]
After doing some tests, it seems like this issue has been fixed. Thanks for the hard work! @Byteflux :)
