### ISSUE TITLE
Using PaperSpigot player bugs

### ISSUE THREAD

**Issue by xion87** [PaperSpigot/Paper#35]
i have find these issue by using paperspigot:
- player sometimes see other players underground
- player sometimes see other players like 1 block from ground 
- eating golden apple sometimes bug on 1.8 client (work fine on 1.7 client)

I am using this on a kitpvp server...
 This server is running CraftBukkit version git-PaperSpigot-a55c8eb (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

**Comment by lukas81298** [comment]
I had those issues, too.

**Comment by Zbob750** [comment]
Thanks for the report, can you provide any more details?

```player sometimes see other players underground```
```player sometimes see other players like 1 block from ground```
```eating golden apple sometimes bug on 1.8 client (work fine on 1.7 client)```
Can you potentially describe exactly what it is you're seeing here? Perhaps a screenshot if that seems like it'd help?

Hopefully we'll be able to reproduce whatever it is you're seeing with this information

**Comment by ijskobar** [comment]
I think the first and second issue can be fixed by sending the absolute position the first time an entity is seen as done [here](https://github.com/OvercastNetwork/SportBukkit/blob/master/CraftBukkit/0097-Send-absolute-position-the-first-time-an-entity-is-s.patch). I personally haven't seen the third issue myself.

**Comment by Zbob750** [comment]
It seems to have resolved the issue for me, but I wasn't ever able to reproduce it consistently, so it could just be placebo. Please update to latest and try it yourselves. Hopefully that did it.
0bae6f35d8f147dc57e2a291b10722de4f6db336
