### ISSUE TITLE
Error, using latest version of paper spigot

### ISSUE THREAD

**Issue by xXBarchticXx** [PaperSpigot/Paper#36]
My console is continually spammed with this error ERROR Unable to fetch TPS results from spigot!
I asked peeps on irc but they told me that, that was the wrong place to ask including md_5. Please help :(

**Comment by Zbob750** [comment]
Discussed earlier in IRC, throwing it up here in case anyone else has a similar issue.
The plugin at fault here is [Dynamic Signs](https://www.spigotmc.org/resources/dynamicsigns.3566/). Unfortunately, this plugin uses reflection to get the MinecraftServer class and read the server's TPS. This is the literal heart of the server, and in our patch to further improve the server tick loop, we change the tick loop to the point that this author's method no longer works.
We do *not* consider this to be an issue of ours as the author is using reflection to access an NMS class, which we have not ever supported (nor has Spigot or CraftBukkit).
We provide an API to access the TPS in a more friendly and appropriate manner, the author seems disinterested in supporting Paper in any form.

Please note that this plugin's error is non-critical however, and both the server and the author's plugin will continue to function just fine (minus the author's TPS placeholder).

**Comment by Zbob750** [comment]
We still don't support plugins that do this, but it should be resolved in nearly all, if not all, cases with 1bf9f63750f08ddb468fb4270d10ccd8b8c54f1d

**Comment by xXBarchticXx** [comment]
Is 1bf9f63 the version string?

**Comment by xXBarchticXx** [comment]
Also it is not only dynamic signs it is also all of maximvdws plugins with the tps placeholder x)

**Comment by Zbob750** [comment]
Just make sure you're up-to-date and they should all work fine.
