### ISSUE TITLE
Preventing Sand being shot over Sky Limit.

### ISSUE THREAD

**Issue by Curtis3321** [PaperSpigot/Paper#38]
Hey,

I was wondering if you could create an addition to prevent Sand being shot over Sky Limit, this prevents roof raiding as it's currently extremely easy to create roof raiding cannons and they need to be nerfed. Thus I am suggesting Paper implementing an option to prevent blocks being shot over Sky limit.

**Comment by Techcable** [comment]
tnt-entity-height-nerf

**Comment by Curtis3321** [comment]
Yeah, I'm an idiot, sorry.
