### ISSUE TITLE
[info request] This fork is the same on hub spigot?

### ISSUE THREAD

**Issue by xion87** [PaperSpigot/Paper#42]
Hi i just want know if this is a indipendent fork that will keep to support 1.7/1.8 client server because i noticed there is paperspigot on spigot hub.... that support only 1.8...

**Comment by Techcable** [comment]
Yes, it is the same project. Changes and features from 1.8 are periodically ported to 1.8, and changes and features from 1.7 are periodically ported to 1.8.
Surprisingly, most development occurs on 1.7, because that's what Byteflux uses.

**Comment by xion87** [comment]
so i can continue to use your build.sh to have latest 1.7/1.8 updated?

**Comment by Techcable** [comment]
You can still use that to get the protocol hack version :)

**Comment by xion87** [comment]
thank you a lot for the reply and the information :)
