### ISSUE TITLE
What's going on with VanillaPaper?

### ISSUE THREAD

**Issue by phase** [PaperSpigot/Paper#5]
What's going on with it?

**Comment by Zbob750** [comment]
It's dead at the moment, unless someone wants to come up with a clean way to switch to a similar system like buildtools except basing it off of making the user run MCP and then apply patches on top of that.

As of now, I don't have the time or any plans to do so.

**Comment by phase** [comment]
I've been making a system to do basically that for my own server: https://github.com/Dimensions/Dimensions/blob/master/dim.sh#L27-32

You can use whatever bits and pieces of it that you need (*just know it's under the MIT License*).

**Comment by Zbob750** [comment]
Ah, excellent. That might be just what we need to bring it back to life.
Thanks for letting us know.

**Comment by phase** [comment]
Awesome! If you need any help, don't ask me. I barely know how it works. :P 
(*But I'd love to work on the project!*)
