### ISSUE TITLE
Delay in all input/output after teleportation.

### ISSUE THREAD

**Issue by mibby** [PaperSpigot/Paper#56]
When teleporting around (/spawn, /tp to players, etc.), there is noticeable delay in command input/output after the immediate teleportation. Ping on the tab window drops from 5 bars down to 3/4. This delay/lag does not occur on normal Spigot.

I presume this is caused when chunks are actively loading around the player. When it stops loading, the command goes through and all chat output catches up. Easiest way for me to test the delay/lag after teleportation is to tp somewhere (such as to a player) and then immediately type ```/tps``` or something in chat. It is always delayed until the chunks stop loading, even worse when tping to multiple people back-to-back in rapid succession.

Taggin @Zbob750 as reference to the issue discussed on IRC.

**Comment by Techcable** [comment]
Uh, minecraft is single threaded.
Chunks and commands can not happen at the same time.
If chunks start loading, nothing can happen (including packet processing), until that finishes.

**Comment by mibby** [comment]
I thought minecraft had an update a while back to make chat completely asynchronous. I could be mistaken.

Anyways, I contacted Z750 on the IRC prior to creating this ticket. He said this issue is a vanilla bug that has previously existed and made its round between vanilla, bukkit, and spigot, and that it is PaperSpigot's turn to fix it - or something along those lines. This delay / lag after teleportation is definitely something new I've noticed since switching over to Paper and something that does not happen with normal Spigot. Everything is instant after teleportation with normal spigot.

**Comment by Zbob750** [comment]
After further testing, every implementation based on the vanilla server (Spigot, CraftBukkit, Paper) has this delay.

I remember it being much more pronounced, it's not too bad so long as your server isn't under extreme load.

Further, the chat is async, however commands are not. So while you can continue to speak with your friends despite the issue, you cannot do anything that touches the main thread (commands like /tps).

**Comment by mibby** [comment]
Perhaps, but my server isn't under any load. It is stable at 19.99/20 TPS. Yet after every teleport, there is a distinct noticeable 3-5 second delay / lag until all chunks finish loading. Again, this does not seem to occur on normal Spigot so it leads me to believe something is broken in PaperSpigot.
