### ISSUE TITLE
Crash that I cant identify

### ISSUE THREAD

**Issue by Kesims** [PaperSpigot/Paper#6606]
### Stack trace

I dont really have stack trace, but I have a log and crash report:

```
Crash report: https://paste.gg/d5268aedabc8421aa9f9d7f9ae62524b
Server log: https://mcpaste.io/fdf3a08962a52a04
```

### Plugin list

AdvancedChests, AdvancedDevelopmentLibrary, AdvancedEnchantments, AnvilLot, ArmorStandEditor, AsyncWorldEdit, AuctionHouse, BentoBox, BungeeTabListPlus, ChatSentry, ChestShop, Citizens, CMI, CMILib, CommandNPC*, CommandSync*, CoreProtect, CraftingStore, CrateReloaded, CustomCrafting, DiscordSRV, dtlTraders, EpicBackpacks, FlightPlus, FoxStats, HackedCore*, HackedServer*, HeadZ, HolographicDisplays, InteractionVisualizer, InteractiveBoard, JetsAntiAFKPro, JetsHoppers, JetsMinions, JetsRepairTokens, KiteBoard, LightAPI, LoneLibs, MineableSpawners, MobFarmManager, Multiverse-Core, MysqlPlayerDataBridge, PermissionsEx*, PlaceholderAPI, ProtocolLib, SafariNet, SkinsRestorer, SkyFoxUtils, SponsoredSlots, SuperbVote, TabuuCore, TreeAssist, UltraCustomizer, Vault, VoidGen, VoidSpawn, Votifier, Voting, WolfyUtilities, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Actions to reproduce (if known)

Sadly I cant identify the problem :/ It seems random, sometimes server runs for multiple hours and than crashes, sometimes crashes when first player logs in after server start.

### Paper version

This server is running Paper version git-Paper-261 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 79e52a5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Feel free to contact me, even on Discord Kesims#0001, Ill do my best to provide all information needed! Thank you!

**Comment by Kesims** [comment]
Also I would like to mention that it is possible that its caused by JetsMinions plugin, but its just my theory.. There were some updates recently in the Jets plugin.. 

But still some plugin shouldnt crash server, right? So anyways this would be something worth finding out and/or fixing.

**Comment by Brokkonaut** [comment]
> But still some plugin shouldnt crash server, right? So anyways this would be something worth finding out and/or fixing.

Plugins can always crash the server when not using the api correctly (for example invalid async access) or accessing server internals.

**Comment by Kesims** [comment]
Another crash, it happened after player teleportation.

Crash report: http://hastebin.com/usicitiqog
Error before crash in log: https://hastebin.com/catodirija

Any ideas what that could be caused by? Or how could I prevent it?

**Comment by TheShermanTanker** [comment]
`I dont really have stack trace, but I have a log and crash report`
Small tip for if you encounter issues in the future: The stack trace is in the server log and crash report (But is much easier to find in the crash report)



> 
> 
> Another crash, it happened after player teleportation.
> 
> Crash report: http://hastebin.com/usicitiqog
> Error before crash in log: https://hastebin.com/catodirija
> 
> Any ideas what that could be caused by? Or how could I prevent it?

Similar issue to the original, I can't quite find out why teleportation causes it to crash though. Does it consistently crash whenever a Player teleports?

**Comment by Kesims** [comment]
Hello, it turned out the issue is caused by Minions, so its just plugin crashing the server when loading/unloading entities. Thanks for help anyways! :)

**Comment by Jet315** [comment]
For some reason code being ran in the EntitiesUnloadEvent caused a small chance for the server to crash (no idea why, ensured everything was sync, nor was there any heavy performance hitting code within the method) - The code took well <1ms to run everytime

My only solution was to add the entities to an array, and create a task that checks this array every second for changes, and then do the 'minion unloading' within this
