### ISSUE TITLE
Wrong entity passengers visual

### ISSUE THREAD

**Issue by Lorenzo0111** [PaperSpigot/Paper#6609]
### Expected behavior

I have a very strange problem: I'm working to an update for my vehicles plugin, I created an armorstand for each passenger and when the main one moves, with some math and vectors the other one goes with it.

I normally expect to see everything normal as in the image but it happens only from the main account because from the other I see myself without riding the armorstand (See image in the "What you actually saw.").

This is the code I think cause the bug:
```java
final Entity rider = e.getPassenger();
e.eject();
e.teleport(offset);
if (rider != null) {
    rider.teleport(offset); // offset can be any location
    e.setPassenger(rider);
}
```

I don't really know if this is a spigot/paper bug but I think yes because I tried with older versions like 1.12.2 and it seems to work

![Image 1](https://user-images.githubusercontent.com/69311874/133451890-87e90d08-112d-4812-a39b-b0aed0cda07e.png)

### Observed/Actual behavior

From the other account (the "rider" in the code) I see myself without riding the armorstand.

![Image 2](https://user-images.githubusercontent.com/69311874/133451898-8112ca89-6c49-4f7d-9196-81dad960e8df.png)

### Steps/models to reproduce

1. Run the code mentioned above
2. See from the player who is riding the armorstand the problem
3. See from the other account

### Plugin list

ProtocolLib and QualityArmoryVehicles2 (my plugin)

### Paper version

```
This server is running Paper version git-Paper-263 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 3069eae)
You are running the latest version
Previous version: git-Paper-257 (MC: 1.17.1)
```

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Lorenzo0111** [comment]
I'm not very sure but it may be caused from this https://bugs.mojang.com/browse/MC-202202

**Comment by Lorenzo0111** [comment]
Any news?

**Comment by electronicboy** [comment]
If there is no reply, there is generally no news

If this is MC-202202, (or, more so, the issues which have stemmed out of that issue), then it's a client issue and there is nothing we can do, otherwise this would require deeper code digging which is a non-trivial effort

**Comment by Lorenzo0111** [comment]
Is there any workaround for this?

**Comment by Lorenzo0111** [comment]
I've fixed by delaying of 5 ticks the e.setPassenger(rider); action
