### ISSUE TITLE
Make target-player-chunk-send-rate independent per player

### ISSUE THREAD

**Issue by MartijnMuijsers** [PaperSpigot/Paper#6610]
### Is your feature request related to a problem?

Some people have a low bandwidth and their ping becomes very bad on teleportation, the while after, and even while just walking around because every time chunks are sent the connection between them and the server throws a fit somewhere at the bottleneck.

Setting target-player-chunk-send-rate low resolves this, letting them play comfortably (since the network performs well if the throughput stays below the bottleneck bandwidth) but now everyone suffers from an unnecessarily low chunk sending rate.

### Describe the solution you'd like.

Add an API Player.setChunkSendRate to set an individual chunk send rate for players, this way we can develop plugins to manually or automatically override the chunk send rate for players with problematic bandwidth.

### Describe alternatives you've considered.

I have not found any alternative solutions to the issue that arose (some players getting very bad ping whenever a few too many chunks are sent).

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by 7wOv6ySCjo** [comment]
It seems to be a very good idea and I have come to the conclusion that it would be a good implementation.
