### ISSUE TITLE
Setting target-player-chunk-send-rate to 1.0 disables the limit

### ISSUE THREAD

**Issue by MartijnMuijsers** [PaperSpigot/Paper#6616]
### Expected behavior

When setting target-player-chunk-send-rate to 1.0, I expect the chunk send rate to be 1.

### Observed/Actual behavior

The chunk send rate is disabled (unlimited).

### Steps/models to reproduce

Start with the latest build (# 264 at time of writing), set target-player-chunk-send-rate to 1.0, and join. The chunks load at high speed (much much faster than setting target-player-chunk-send-rate to 2.0).

### Plugin list

None

### Paper version

Checking version, please wait...
This server is running Paper version git-Paper-264 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: ce7516d)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

**Comment by Owen1212055** [comment]
Can reproduce as of 1.19.1

**Comment by 7wOv6ySCjo** [comment]
Can reproduce as of 1.19.3

**Comment by Warriorrrr** [comment]
See https://github.com/PaperMC/Paper/pull/8834#issuecomment-1683670607
