### ISSUE TITLE
Cannot Load ItemStacks with some Material Types from config.yml.

### ISSUE THREAD

**Issue by Wyatt-James** [PaperSpigot/Paper#6618]
### Expected behavior

Loading a config YML file with the following lines:

```yaml
example_item:
  ==: org.bukkit.inventory.ItemStack
  type: CROSSBOW
  amount: 1
```
should not cause an error as this is a valid Material type, and changing the `type` tag to another valid Material should work as well.

### Observed/Actual behavior

when `config.load(configPath);` is called in the Test Plugin's onEnable() method, legacy material support is enabled, the server pauses for several seconds, and then the `config.yml` file fails to be parsed and throws an exception with the message: `java.lang.IllegalArgumentException: Material cannot be null`. Logs attached as a .log file. I also observed the same issue with `type: FIREWORK_ROCKET`, `STICK`, and `GLOWSTONE`. Strangely, the latter two did work in another plugin but not this one...

[error.log](https://github.com/PaperMC/Paper/files/7183343/error.log)

### Steps/models to reproduce

1. Build plugin mentioned in Plugin List section and place the JAR within your server's `plugins` folder.
2. Run the server

This also works under the latest Spigot version.

### Plugin list

A Test Plugin available on my GitHub [here](https://github.com/Wyatt-James/Paper-Issue-Test-Plugin)

My setup:
- Built with Java version: `openjdk 16.0.2 2021-07-20`
- Run with Java version: `openjdk 16.0.1 2021-04-20`

To compile, run `mvn package` and place the generated JAR within your `plugins` folder.

### Paper version

This server is running Paper version git-Paper-265 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 0680f4f)
You are running the latest version
Previous version: git-Paper-259 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Any work-around suggestions are welcome in the meantime as I need to use this feature soon in a plugin.

**Comment by electronicboy** [comment]
This sounds somewhat expected given that you're manually messing around with the data and are missing the version tag as a result of that...

**Comment by Wyatt-James** [comment]
I'm... frankly not sure what you mean.

**Comment by electronicboy** [comment]
You're defining an ItemStack, using an item type was added post DFU migration stuff, without a version tag, meaning version is defaulted to like 1 or something, which means you're trying to define an item into the serialised data which could not and would not have existed at that version number which is then passed through the data upgrade logic, and is somehow coming out on the other side managed? Which seems expected given that you're basically passing mangled data in

**Comment by Wyatt-James** [comment]
I'm not sure what you mean by a version tag.

**Comment by electronicboy** [comment]
data is versioned in minecraft and has been for years, post DFU, that detail was exposed in the ItemStack serialisation logic in order to properly be able to actually call into the DFU logic and upgrade stacks across versions

**Comment by electronicboy** [comment]
I do wonder if data converter is more sensitive to mangled data here, maybe try the post tuinity merge build?

**Comment by Wyatt-James** [comment]
I'm not sure what you mean by post tuinity merge build.

As for the ItemStack, I see now that if I save an ItemStack it writes a `v` tag, specifically `2730`, and that adding that to my config.yml fixes the issue. Do I need to throw that into every single ItemStack I add to avoid DFU kicking in and getting all confused or is there a more universal solution? Thanks.

**Comment by electronicboy** [comment]
Actually, I misremembered the logic, DFU comes into play later;

So, there is a bug here, upstream has broken deserialisation of legacy itemstacks (those without a v tag), as it tries to use a legacy material lookup but doesn't specify that it's doing a legacy material lookup, so, ofc fails

For modern items, you will need a data version, this is not a configuration mechanism and using it as such as really just asking for sore points like this

**Comment by Wyatt-James** [comment]
So are you suggesting that I implement my own loadItemStack function that handles meta and such on its own and just never think about this again? I could live with that.

**Comment by electronicboy** [comment]
Issue here is that you're trying to treat internal data representations as if they're designed and intended for usage as a configuration format, the logic here is for deserialisation of serialised objects, while ofc, that is presented in a human readable format, it does not have the typical failsafe and id10t checks that you'd expect in something designed to be configured and modified by humans, and is definitely not designed for being touched by people who are configuring plugins

ofc, that creates headaches as there is no standard, agreed upon way to how to define this in a configuration format, hence you end up with 200 plugins each with 200 different ways of expressing it
