### ISSUE TITLE
Crossing chunk borders produces a 1000ms lag spike

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#6621]
### Expected behavior

Crossing chunk borders should not freeze the client.

### Observed/Actual behavior

When crossing chunk borders in proximity to a tall mountain/building, the client freezes up for 1000ms recalculating light.

### Steps/models to reproduce

Cross a chunk border near a tall structure.

### Plugin list

Not applicable

### Paper version

This server is running Paper version git-Paper-263 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 3069eae)
You are 3 version(s) behind
Previous version: git-Paper-255 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

This problem has only existed since the 1.17 update.

**Comment by electronicboy** [comment]
Duplicate of #5089

**Comment by ghost** [comment]
@electronicboy This is not a duplicate of that issue as in 1.16.4 this problem didn't exist.

**Comment by e-im** [comment]
This issue did exist in 1.16, you may have just not experienced it.

**Comment by ghost** [comment]
> This issue did exist in 1.16, you may have just not experienced it.

@sulu5890 There was a patch that worked great and fixed the issue, I think it was removed in 1.17.

**Comment by electronicboy** [comment]
There was a mitigation for the issue which had its own set of issues, caused its own set of issues, and was not a real fix for the actual issue in hand, due to those and the size of the implications, it was dropped, there is plans to restore it with a config
