### ISSUE TITLE
Player heads display wrong skins in inventories or on armor stands

### ISSUE THREAD

**Issue by wm-b** [PaperSpigot/Paper#6623]
### Expected behavior

Player heads display the correct skins on armor stands and in inventories.

### Observed/Actual behavior

When one gets a player head of a player who has never joined the server before, the head's skin in one's inventory and when placed on an armor stand will always be either the default Alex or Steve head. The head will display the correct skin when placed on the ground, however.

### Steps/models to reproduce

Obtain a player head and observe it in your inventory or when placed on an armor stand.

### Plugin list

None. The issue is present on a server with no plugins.

### Paper version

This server is running Paper version git-Paper-266 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 0d19cd7)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by lynxplay** [comment]
Both 
`/summon armor_stand ~ ~ ~ {ArmorItems:[{},{},{},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:"Dinnerbone"}}]}`
and 
`/give @p minecraft:player_head{SkullOwner:"Dinnerbone"}`

result in the correct item stack for me, including the applied skin.
Could you provide more information as to how you are creating the faulty item stack ? (E.g. the command)

**Comment by electronicboy** [comment]
this is a side-effect of a patch upstream which prevents the server blocking the main thread to populate these skulls in many cases, tests can be a bit weird given that this info is cached at runtime, thus it's possible to hit the cache when testing, but, this issue is somewhat unavoidable without falling back to IO on the main thread, maybe there is some hackarounds for this type of thing but probs best avoided

**Comment by lynxplay** [comment]
Yea I ensured I was not hitting the cache through breakpoints. If you believe there isn't a really valid solution to this anyway, we might as well close this with a works-as-intended.

**Comment by wm-b** [comment]
The issue appears to be completely gone this morning. I'm not sure why or how, but it's now working on my public-facing server, my local machine's test server, and an additional public-facing server that isn't mine whereas it wasn't working on any of these yesterday.

I guess it's a non-issue then?

**Comment by lynxplay** [comment]
Okay :+1: I'll mark this as "works as intended" as cat already stated, the off-main thread completion of the game profile might be the reason but there isn't much we can do/we are expecting them and accept them as the alternative would be the completion on the main thread.
