### ISSUE TITLE
After update some commands append <chat=089ad807-e3d7-47a7-bb7e-c22c27669ae8>

### ISSUE THREAD

**Issue by antibitcoin** [PaperSpigot/Paper#6626]
### Expected behavior

Hi,
After updating to attached version some plugins like essentials, bkteleport started appending text with some uuids to commands, so if I do /delhome name it would excute /delhome name <chat=089ad807-e3d7-47a7-bb7e-c22c27669ae8> which result in an error messages saying you have typed invalid characters.

### Observed/Actual behavior

/delhome name  should delete home named name.

/delhome name will instead excute /delhome name <chat=089ad807-e3d7-47a7-bb7e-c22c27669ae8> and result on an error with invalid characters.

### Steps/models to reproduce

so far this is only on BkTeleport, I have contacted the dev and will link this thread to him.

### Plugin list

bkteleport
essentialsx
interactivechat
protocollib
vault
discordsrv
interactivechat discordsrv addon
chatex

### Paper version

This server is running Paper version git-Paper-266 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 0d19cd7)
You are running the latest version
Previous version: git-Paper-263 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
That's not a paper thing, 99.999999% chance that that is a plugin; interactive chat?

**Comment by antibitcoin** [comment]
> That's not a paper thing, 99.999999% chance that that is a plugin; interactive chat?

It might be interactive chat. thanks for the tip!
