### ISSUE TITLE
Cancelling BlockPlaceEvent for powdered snow keeps grass snowy

### ISSUE THREAD

**Issue by Warriorrrr** [PaperSpigot/Paper#6630]
### Expected behavior

The grass to not turn snowy.

### Observed/Actual behavior

The grass turned snowy, persists after relogging/restarting the server.

### Steps/models to reproduce

Reproducable using the following code:
```java
@EventHandler
public void onBlockPlace(BlockPlaceEvent event) {
	if (event.getBlock().getType().equals(Material.POWDER_SNOW)) {
		event.setBuild(false);
		event.setCancelled(true);
	}
}
```
After placing powdered snow, the grass will still be snowy (snowy: true in f3). I've confirmed this isn't just some visual/client sided thing by relogging/restarting the server.

### Plugin list

Reproducable without any plugins (except one to cancel the BlockPlaceEvent for powdered snow)

### Paper version

This server is running Paper version git-Paper-266 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 0d19cd7)
You are running the latest version
Previous version: git-Paper-"4d9b14e" (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by lynxplay** [comment]
I was capable of reproducing this on both paper and spigot.
The issue, at least based on my first few debugger runs, lies in the fact that block state capturing (and hence physic updates) are explicitly disabled for `SolidBucketItem`s (see ItemStack line 318). The was introduced [here by upstream](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/d1dbcebcd220d4e6fdb1db6c91ec32b64bb8a66c) as a fix for [SPIGOT-6653](https://hub.spigotmc.org/jira/browse/SPIGOT-6653).

**Comment by Warriorrrr** [comment]
Cancelling the BlockCanBuildEvent or PlayerInteractEvent events seems to work as a workaround for now, but there are some visual issues sometimes. The bucket will appear empty after cancelling the BlockCanBuildEvent, and grass can still look snowy sometimes.
