### ISSUE TITLE
WISH JDK17 Support

### ISSUE THREAD

**Issue by mrjesen** [PaperSpigot/Paper#6631]
### Is your feature request related to a problem?

no

### Describe the solution you'd like.

WISH JDK17 Support

### Describe alternatives you've considered.

   .

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by NotMyFault** [comment]
Paper already works on Java 17, if that was the question.

**Comment by Chew** [comment]
Duplicate of #6614
