### ISSUE TITLE
Possibility to use adventure component in Prompt#getPromptText()

### ISSUE THREAD

**Issue by aerulion** [PaperSpigot/Paper#6644]
### Is your feature request related to a problem?

When using the conversation api and dealing with prompts, it would be nice to be able to use the adventure component system to style the prompt text.

### Describe the solution you'd like.

Being able to alternative provide a component instead of a string when setting the prompt text.

### Describe alternatives you've considered.

Using LegacyComponentSerializer#legacySection() to serialize the component into a string.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Owen1212055** [comment]
See https://github.com/PaperMC/Paper/pull/6726#issuecomment-1327932473
