### ISSUE TITLE
Zombie villager Mob switches don't work - Mobs don't stay loaded in spawn chunks

### ISSUE THREAD

**Issue by Ryan7567** [PaperSpigot/Paper#6648]
### Expected behavior

I have a zombie villager mob switch on the boarder of the spawn chunks lazy chunks,  which worked perfectly fine for several months, until about a week ago. When the zombie villagers were pushed into the spawn chunk lazy chunks, all other mob cap hostile mobs ceased to spawn in the world due to the mob cap being filled since they were loaded in the spawn chunks.

### Observed/Actual behavior

However, about a week ago, no matter if the zombie villagers were fully in the spawn chunks, mobs still spawned all over the world. The zombie villagers still count towards the mob cap, as no hostile mobs spawn in the direct vicinity of them, however, when you go away from them, they should stay loaded in the spawn chunks, and count toward the mob cap, but they don't. Its not that the zombie villagers don't count towards the mob cap, its that the spawn chunks aren't keeping them loaded. and yes, I do have keep spawn loaded set to true.

### Steps/models to reproduce

Put 70 * number of players, (for me its 2, so 140, plus 5 extra), traded with zombie villagers in the spawn chunk lazy chunks and go far away. No mobs should spawn as the mob cap should be filled, but as you can see they still do, because the zombie villagers are no longer loaded when they should be.

I backed up my server world and tried it in vanilla single player and it worked perfectly fine.

### Plugin list

None

### Paper version

23.09 14:09:03 [Server] INFO This server is running Paper version git-Paper-276 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 1707c10)
23.09 14:09:03 [Server] INFO You are running the latest version
23.09 14:09:03 [Server] INFO Previous version: git-Paper-275 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by e-im** [comment]
For mob switches to work properly, two things will need to be changed in the configuration:

1. `count-all-mobs-for-spawning` must be enabled
1. `per-player-mob-spawns` must be disabled

Could you check that this is the case? If it is, would you mind sending a timings report via the `/timings report` command such that this can be more easily worked on?

**Comment by Ryan7567** [comment]
count-all-mobs-for-spawning was enabled but so was per-player-mob-spawns, after disabling it, the mob switch went back to working perfectly. Thank you very much for the help. Out of curiosity, do you know why it worked for about 6 months like that, however stopped working about a week ago? I haven't changed any config settings since originally setting them a year ago. No matter, thank you again for the assistance.

**Comment by jpenilla** [comment]
`per-player-mob-spawns` recently had it's default adjusted from `false` to `true`

**Comment by e-im** [comment]
Yes, per-player was previously defaulted to false, however just recently the default was changed to true. This was done to provide a much better and more expected (singleplayer-like) spawning for the majority of servers, however did have the drawback of causing hard to debug issues for the smaller number of servers like yours building mob switches.

**Comment by Ryan7567** [comment]
Well thank you very much for the help and explanation.
