### ISSUE TITLE
Expose some Starlight methods to add/remove lights

### ISSUE THREAD

**Issue by LoneDev6** [PaperSpigot/Paper#6649]
### Is your feature request related to a problem?

Yes, currently [LightAPI ](https://www.spigotmc.org/resources/lightapi-fork.48247/) doesn't work anymore because the light engine was changed to Starlight.

https://github.com/Qveshn/LightAPI/issues/32

### Describe the solution you'd like.

I'm not the developer of Starlight nor I know how the light engine of Minecraft works, but I think that exposing this method to the Paper API would allow us to add lights in specified spots of the world.
https://github.com/PaperMC/Paper/blob/cc6fd371b2d1ab2ad1df85789b143f04a17c1468/patches/server/0763-Rewrite-the-light-engine.patch#L1811
A removeLight method is also needed and It's important also to be able to set both sky and block lights.

I [got told](https://www.spigotmc.org/threads/lightapi-fork.278321/page-10#post-4237787) that Starlight developer has stated that they are not interested into exposing a similar method because Minecraft 1.17 added a "light" block. I explained why this is not a solution: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1182#issuecomment-921030173

### Describe alternatives you've considered.

I really have no alternative as we need an API method to access the light engine to add/remove lights.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by electronicboy** [comment]
Starlight cannot be exposed in the API, nor am I really fond of exposing
such low level mechanisms in the faux of it being stable API

**Comment by MiniDigger** [comment]
theres hardly a need for lightapi anymore since we now got a vanilla way to do it?

**Comment by LoneDev6** [comment]
> 
> Starlight cannot be exposed in the API, nor am I really fond of exposing such low level mechanisms in the faux of it being stable API


Interesting.. this may introduce some unexpected behaviour I think.


> 
> 
> theres hardly a need for lightapi anymore since we now got a vanilla way to do it?

I wish it was enought, but as I said:
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1182#issuecomment-921030173
For example we cannot make a specific location emit light without making it occupied by the `light` block itself as shown in the video.
Some plugins need to make their custom blocks emit light, currently it's not possible using `light` block itself.

**Comment by Brokkonaut** [comment]
> I really have no alternative as we need an API method to access the light engine to add/remove lights.

I think you could use reflection to access the methods.

**Comment by LoneDev6** [comment]
> 
> 
> > I really have no alternative as we need an API method to access the light engine to add/remove lights.
> 
> I think you could use reflection to access the methods.

Would be awesome, anyone can guide me on how to access the Starlight engine instance? I can't find exactly where to access it properly.

**Comment by LoneDev6** [comment]
https://www.spigotmc.org/resources/lightapi.4510/
