### ISSUE TITLE
Unable to start Paper-1.17.1-276

### ISSUE THREAD

**Issue by SlimeDog** [PaperSpigot/Paper#6650]
### Expected behavior

Clean start-up

### Observed/Actual behavior

Start-up failed. No logs recorded.

### Steps/models to reproduce

This is our standard parallel testing procedure
- Restore backup of Spigot instance.
- Replace spigot-1.17.1-3242 jar with paper-1.17.1-276 jar.
- Start server.

This process has worked successfully for years, up to paper-1.17.1-275.

### Plugin list

160+ -- we run a plugin testing server. Full list is available on request. It includes
- ProtocolLib
- PlaceholderAPI
- Multiverse-Core/Portal/Inventories
- Citizens/Denizen/Sentinel
- Skript

All very latest dev builds, updated several times a day.

### Paper version

Cannot be run, since the server fails to start, but `paper-1.17.1-276`

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by NoahvdAa** [comment]
How are you starting the server? Is nothing logged in the console?

**Comment by Machine-Maker** [comment]
There has to be some error somewhere, if there isn’t, there’s like no way to know what’s wrong.

**Comment by SlimeDog** [comment]
Normally I start in a (Linux) shell script. Starting manually:
> Error: Invalid or corrupt jarfile

- Downloaded 276 again
- Noted that JAR is different
- Started server normally
- All good

Mea culpa. I should have checked that. Apologies.

**Comment by MiniDigger** [comment]
worth noting that our download api includes hashes of the jars we serve, so you could build a little script that downloads and verifies the hash of the latest build on your server to avoid running into shit like this in the future

**Comment by SlimeDog** [comment]
Thanks.
