### ISSUE TITLE
adventure api

### ISSUE THREAD

**Issue by oRIOnTx** [PaperSpigot/Paper#6655]
### Expected behavior

Hi, pls update adventure-api on latest build. I use 1.16.5 paper

### Observed/Actual behavior

-

### Steps/models to reproduce

-

### Plugin list

-

### Paper version

latest

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
1.16.5 is no longer fully supported and will not receive any updates bar critical fixes

**Comment by oRIOnTx** [comment]
> 1.16.5 is no longer fully supported and will not receive any updates bar critical fixes

But, in latest build for 1.17 have same problem

**Comment by Proximyst** [comment]
Paper 1.17.1 is on Adventure 4.9.1. Is that not latest?
