### ISSUE TITLE
GameRule spectatorsGenerateChunks does Nothing.

### ISSUE THREAD

**Issue by Wyatt-James** [PaperSpigot/Paper#6657]
### Expected behavior

Chunks should not generate or load when gamerule spectatorsGenerateChunks is false.

### Observed/Actual behavior

Chunks load and generate as normal.

### Steps/models to reproduce

1. Create a new server with all default configs.
2. Join the server.
3. Set gamerule spectatorsGenerateChunks to false.
4. Set your gamemode to spectator.
5. Fly in any direction and observe the generating chunks.

### Plugin list

N/A

### Paper version

This server is running Paper version git-Paper-278 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d0a2193)
You are running the latest version
Previous version: git-Paper-266 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Java version: openjdk 16.0.1 2021-04-20

Works as intended on Spigot, running version:
- This server is running CraftBukkit version 3242-Spigot-6c1c1b2-d3cc412 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

**Comment by Chew** [comment]
Duplicate of stale issue #4805.

Not much was really discussed there, I think it was deemed an upstream issue.

**Comment by Wyatt-James** [comment]
Well it sure isn't upstream anymore because both Spigot 1.17 (version stated in issue) and Vanilla 1.17.1 (tested in singleplayer) work fine now.

**Comment by Wyatt-James** [comment]
Ah wait never mind, I see now that it generates but just doesn't show said chunks. Maybe at least mirror Vanilla/Spigot behavior?

**Comment by e-im** [comment]
This isn't a duplicate of the last, this is a new issue as of merging tuinity.

**Comment by HMU59** [comment]
Confirmed in 1.18.2, causing lag when spectators traveling fast.
Any update of devs please ?

**Comment by bribri69** [comment]
Hello,

Same problem today with 1.19 (build 39)

New server with default configs. 
Set SpectatorGenerateChunks to false.
Then, in spectator mode the chunk are generated...

Edit : tested now with last spigot build, works fine

**Comment by VL4DST3R** [comment]
Came here to report the same thing, i can still generate chunks just fine in spectator mode on build 81 (latest 1.19).

**Comment by Lotzyprod** [comment]
Confirmed this bug on Paper version git-Paper-196 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: ff67f1f)

**Comment by notTamion** [comment]
Is this still an issue? I personally am unable to reproduce it. When flying towards not generated chunks in spectator with the gamerule disabled they are not being generated

**Comment by Machine-Maker** [comment]
I too tested this and chunks were not being generated, was apparently fixed at some point.

**Comment by 456dev** [comment]
when i tested this, iirc the behaviour relating to keeping chunks loaded (speficially with entities) differed from vanilla, might need a new report?
