### ISSUE TITLE
Add player-max-concurrent-gens to paper config

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#6659]
### Is your feature request related to a problem?

I want to give players a big render distance but only for chunks that are already loaded, since elytra flying would generate alot of chunks and waste disk space.

### Describe the solution you'd like.

a player-max-concurrent-gens option to throttle the number of chunks generating around the player, so that if they are flying with elytra or moving fast with trident and rain the trail they leave behind is minimal.

### Describe alternatives you've considered.

Having a lower render distance, or turning down chunk loading speed (yuck)

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by deciduous-buffalo** [comment]
I opened a feature request to solve a similar problem, let me know what you think about this as well #6642
