### ISSUE TITLE
items to keep during PlayerDeathEvent don't keep their original slots

### ISSUE THREAD

**Issue by GabRayz** [PaperSpigot/Paper#6661]
### Expected behavior

When adding itemStacks to the list returned by PlayerDeathEvent#getItemsToKeep, if the item was already in the player's inventory, it should stay in the same slot. (Or at least it was the behaviour prior to 1.17)

### Observed/Actual behavior

Items added to the list are placed in the first slots of the inventory

### Steps/models to reproduce

- Listen for the PlayerDeathEvent
- Get the item from PlayerDeathEvent#getDrops
- Remove the item from PlayerDeathEvent#getDrops
- Add the item in PlayerDeathEvent#getItemsToKeep
- In game, place an item in any slot but the first one
- Die
- The item has moved to the first slot

### Plugin list

Only one plugin with only one class
```java
public final class KeepItemsBug extends JavaPlugin implements Listener {

    @Override
    public void onEnable()
    {
        // Plugin startup logic
        Bukkit.getPluginManager().registerEvents(this, this);
    }

    @Override
    public void onDisable()
    {
        // Plugin shutdown logic
    }

    @EventHandler
    public void onDeath(final PlayerDeathEvent event)
    {
        if (event.getDrops().isEmpty())
            return;
        ItemStack item = event.getDrops().get(0);
        event.getDrops().remove(0);
        event.getItemsToKeep().add(item);
    }
}
```

### Paper version

```
> version
[19:41:05 INFO]: Checking version, please wait...
[19:41:05 INFO]: This server is running Paper version git-Paper-278 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d0a2193)
You are running the latest version
```

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Being able to keep the item in the same place is really useful to make special items that cannot be moved by the player (for instance, a compass that opens a menu, or an item that displays information in his lore)

**Comment by stembauer2** [comment]
I have been able to reproduce 👍
