### ISSUE TITLE
Block Break packet is not being fired?

### ISSUE THREAD

**Issue by ricardormmx** [PaperSpigot/Paper#6662]
### Expected behavior

hi, i'm using protocollib's packet listener to listen the block break packet, but is not being detected. Other packets like the Use Item, work as expected.

### Observed/Actual behavior

I don't know if the packet is not being detected or is not being fired.

### Steps/models to reproduce

I recorded this video, i test on spigot and paper https://youtu.be/twyqkE3DKKQ

### Plugin list

Tester17, ProtocolLib

### Paper version

This server is running Paper version git-Paper-278 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d0a2193)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I can confirm that in version 175 (Paper) it worked correctly

**Comment by lynxplay** [comment]
Paper by default disables updating the responsible client about the block breaking duration, which also prevents the packet you are trying to listen to from being sent.
You can disable this (and hence listen to the packet) in the `paper.yml` under `settings.lag-compensate-block-breaking` by setting it to `false`.

Read more about this [here](https://paper.readthedocs.io/en/latest/server/configuration.html#lag-compensate-block-breaking).
