### ISSUE TITLE
Loading old ItemsStacks from a config fails (did work in build 256)

### ISSUE THREAD

**Issue by Brokkonaut** [PaperSpigot/Paper#6664]
### Expected behavior

A textured player head should load

### Observed/Actual behavior

I get a skeleton head

### Steps/models to reproduce

I have the following item stack definition in a config, when loading it i get a skeleton skull instead of a player head.

<pre>item:
 ==: org.bukkit.inventory.ItemStack
 type: SKULL_ITEM
 damage: 3
 meta:
   ==: ItemMeta
   meta-type: SKULL
   display-name: §ePoké Case
   ItemFlags:
   - HIDE_ENCHANTS
   - HIDE_ATTRIBUTES
   internal: H4sIAAAAAAAA/02PP07DMBxGf6AilcDIBbiBU9SgDh1QSlNH+UPdEBJv1HFJHLuENlFJBgbEwB24CBMzR+AC3IERszF80vv0pmcAGHC8KBsprzb3q0JyAwxNFd/UBd8eQr/mj3Wz4VsDAPb6cBDfyobDO29dRJMcZYkrWYst/aMFkiEW1Tlex+3SxhZW2s8urMQeMe+MSD4jJlNx5ymzWqpYMDVVmT1saEL+e+YN5sjXS0WWpx1GaTQtA3G9ow5RQRcUdHKJfCdF4Q0VfuSWvmBdoP6Y5KFDhC9ioX1HBR7SyZ1JRa7w2hyt5uMxwBHs40zH9HofL6efA+/n+fvt9evk4QngFz3HbMUOAQAA</pre>

Prevoiusly we used build 256 where the player head would load, now it does no longer work.

### Plugin list

does not apply

### Paper version

278

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Maybe https://github.com/PaperMC/Paper/commit/0d19cd7241ad0321d5301c45a7f35d0f61aaf0de broke it?

**Comment by electronicboy** [comment]
There is no material called skull in the game? Sounds like an invalid
config?

**Comment by electronicboy** [comment]
Nvm, misread the nbt, but, that's got a version tag, so, the linked commit
won't be it

**Comment by Brokkonaut** [comment]
oh sorry it had no version tag, i added it for testing (because the item could not be loaded) and forgot to restore the original config.

**Comment by Brokkonaut** [comment]
It is definitely the patch that breaks the loading of old itemstacks. removing it fixes the issue and if you look at it: the correct conversion to the new material is in line 498 (3 lines later)

if the conversion is done in that line where the patch does it, the damage value is ignored and so the new material is incorrect - it will only return the material with "damage" 0, and so in this case it creates a skeleton skull instead of the player head.

**Comment by electronicboy** [comment]
Funnily enough I was actually looking at this logic and came to the conclusion that my change there was actually probably misunderstood given that that method actually calls the upgrade logic which borks the output
