### ISSUE TITLE
Chunk loading/view distance

### ISSUE THREAD

**Issue by Portal2001** [PaperSpigot/Paper#6667]
### Is your feature request related to a problem?

yes, it may be fixes chunk loading lag and help plugins like chunky to be faster also to keep 1.18 in mind

### Describe the solution you'd like.

I think there should be a config in which we can set the view distance of 'y' coordinate up and down of a player. means instead of loading chunk in cylinder shape from bedrock to the high limit we can load in the sphere shape to decrease the load on the server by a player as the player cant go too fast down also not up according to the nerf of elytra. thank for reading

### Describe alternatives you've considered.

tried making plugin also used some other plugins but no one work as the paper has its own async

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by electronicboy** [comment]
Chunks are not stored in a manner where this even makes sense, the amount of extra tracking needed for this is far from trivial and would induce much more packet spam, don't think we're interested in this
