### ISSUE TITLE
Enderman Melon farm

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#6668]
### Expected behavior

Enderman Can carry watermelons

### Observed/Actual behavior

My player has built Enderman Melon farm
But Enderman will not move Melon
Is it a bug?

### Paper version

![擷取](https://user-images.githubusercontent.com/75075197/134817086-3b87b2e7-5827-4e6f-829f-7faf9168283f.PNG)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

https://user-images.githubusercontent.com/75075197/134817119-dfea85b0-5f3c-4d3d-9e5f-63ecf1ad1847.mp4

_No response_

**Comment by e-im** [comment]
Cannot reproduce. Enderman pick up melons fine.

Please try without plugins or datapacks.
