### ISSUE TITLE
Smithing Recipe copies NBT of input item

### ISSUE THREAD

**Issue by DevScyu** [PaperSpigot/Paper#6669]
### Expected behavior

Result item to use the NBT of the item defined as the result

### Observed/Actual behavior

Result item copies over the NBT from the input item

### Steps/models to reproduce

Create a custom recipe using the SmithingRecipe class and add it to the server.

### Plugin list

N/A

### Paper version

This server is running Paper version git-Paper-278 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d0a2193)
You are 1 version(s) behind
Previous version: git-Paper-255 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Machine-Maker** [comment]
That is a feature of the smithing table, it is an "upgrade" crafting table, so keeping the input NBT on the output is intended behavior. In the server impl, the recipe type is even called `UpgradeRecipe` not `SmithingRecipe` like the API calls it.

So this should probably be a feature request, not a bug report. A feature to add an option not to copy NBT

**Comment by DevScyu** [comment]
Sounds good to me.
