### ISSUE TITLE
Brewing Stand Recipe

### ISSUE THREAD

**Issue by DevScyu** [PaperSpigot/Paper#6670]
### Is your feature request related to a problem?

It would be very helpful to have a BrewingRecipe class instead of having to listen to inventory click events and modify it manually.

### Describe the solution you'd like.

A BrewingRecipe class similar to the other recipe classes

### Describe alternatives you've considered.

Alternative is to use InventoryClick events to force items into the slots and a clock to manually update the timer on the brewing stand.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Doc94** [comment]
Sounds good... i see a little in NMS/CB and this crafts not work in the same form like Cooking or Crafting (support for datapacks) use a specific class but looks like can have support here (but sound like many work)...

Recipes Storage:
- CB/NMS is ofuscated but have all methods for register and check this type of recipes:  net.minecraft.world.item.alchemy.PotionBrewer.java
- NMS Vanilla: net.minecraft.recipe.BrewingRecipeRegistry

This recipes define all type of crafts in the Brewer like what items can make a Splash or Lingering and upgrades.

**Comment by DevScyu** [comment]
This would be very useful to have if possible :+1:
