### ISSUE TITLE
Discounts for transactions with villagers are not applied properly

### ISSUE THREAD

**Issue by RondoYMT** [PaperSpigot/Paper#6674]
### Expected behavior

If you heal a zombified villager more than once, the final price will be 1

### Observed/Actual behavior

No matter how many times I was healed, the discount was only given once
The discount stopped at -6 and did not add down to -12...-18...-24....

### Steps/models to reproduce

Cure villagers from being zombified

### Plugin list

none

### Paper version

§fThis server is running Paper version git-Paper-280 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 3e3cea1)§r

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
There is an option in paper.yml to fix the villager discounts, disable this to go back to vanilla

**Comment by RondoYMT** [comment]
Thx :)
