### ISSUE TITLE
Library loader does not isolate dependencies [SPIGOT-6749]

### ISSUE THREAD

**Issue by A248** [PaperSpigot/Paper#6681]
### Expected behavior

Plugins should not see each others' libraries from the "library loader" feature, except in the case of dependencies between plugins.

### Observed/Actual behavior

If and only if a class in a library has already been loaded, other plugins can see the loaded class even when they do not depend on the plugin providing the library. This is incorrect behavior.

### Steps/models to reproduce

Refer to https://github.com/A248/SpigotLibraryLoaderReproducer

1. Build with maven, "mvn package"
2. Add the two plugins created by the reproducer build to the /plugins directory
3. Start the server
4. Observe log output

When run, the following output is observed:
* Short log: https://pastebin.com/pfieT0tm
* Full log: https://pastebin.com/794BF1aU

### Plugin list

The plugins from the reproducer

### Paper version

[18:14:18 INFO]: This server is running Paper version git-Paper-283 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 3e8fb21)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

This is a cross-report of [Spigot-6749](https://hub.spigotmc.org/jira/browse/SPIGOT-6749).

**Comment by lynxplay** [comment]
This was resolved in 72a31751659eeff26349dfa687431da49a91ea64 as upstream fixed their issue and paper now includes that fix :+1:
