### ISSUE TITLE
Villager 

### ISSUE THREAD

**Issue by zombihunterbonn** [PaperSpigot/Paper#6685]
### Is your feature request related to a problem?

Village residents do not eat food to mate

### Describe the solution you'd like.

.

### Describe alternatives you've considered.

.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Proximyst** [comment]
Fill the bug template properly with complete information.
