### ISSUE TITLE
Ability to disable climbing for LivingEntity

### ISSUE THREAD

**Issue by DevScyu** [PaperSpigot/Paper#6694]
### Is your feature request related to a problem?

I would like the ability to cancel players from being able to climb objects such as vines and ladders. After taking a look this seems to be controlled by the onClimbable function in LivingEntity.

### Describe the solution you'd like.

```java
player.setClimbing(false);
```

A function that would save to a variable if they have the ability to climb or not.

### Describe alternatives you've considered.

Alternatives would probably be reflection.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by adrian-kong** [comment]
correct me if i'm wrong, this is not doable since movement is clientside. even cancelling PlayerMoveEvent just teleports the player not exactly cancelling it. so if you want to do this, you would probably just teleport player on colliding with ladder.

**Comment by DevScyu** [comment]
> correct me if i'm wrong, this is not doable since movement is clientside. even cancelling PlayerMoveEvent just teleports the player not exactly cancelling it. so if you want to do this, you would probably just teleport player on colliding with ladder.

I thought the same but this doesn't seem to be the case since I can load up a limbo server using https://github.com/LOOHP/Limbo which has no vanilla mechanics, and ladders are not climbable. They act the same as other blocks and have no resistance when you rub against them.

**Comment by electronicboy** [comment]
comparing to "limbo" style servers is generally not a good idea as they don't always init'd data fully and consistently in a manner which is useful for actually testing clients

**Comment by kennytv** [comment]
That's because of block tags (which you would also have to resend in their entirety just to temporarily make a type of block cimbable/not climbable on the fly). It is otherwise not possible to prevent the client from climbing aside from cancelling move events, which basically just means teleporting back internally.
