### ISSUE TITLE
Double-mending using furnace XP

### ISSUE THREAD

**Issue by GrifterMage** [PaperSpigot/Paper#6708]
### Expected behavior

Removing an item from a furnace with mending tools in both mainhand and offhand mends a maximum total of 2*XP durability

### Observed/Actual behavior

In some circumstances, both mainhand and offhand tools can be mended for 2*XP durability

### Steps/models to reproduce

Mainhand and offhand tools are damaged:
![2021-10-02_12 12 26](https://user-images.githubusercontent.com/49353797/135729239-d5d14b6e-86aa-44ca-ae81-73140936b6bf.png)
![2021-10-02_12 12 29](https://user-images.githubusercontent.com/49353797/135729240-35d1acbc-56bb-4591-9792-ed8f85e0ad3f.png)

Furnace contains 960 XP, which should only repair a max of 1920 durability:
![2021-10-02_12 12 41](https://user-images.githubusercontent.com/49353797/135729241-8cb155d1-ca19-4ce2-8b91-aa8f0579c4f6.png)

Pulling item from furnace repairs mainhand pick for 1910 XP; offhand pick does not dip:
![2021-10-02_12 13 09](https://user-images.githubusercontent.com/49353797/135729242-7c586d2d-f934-4c63-880d-d88182f4d846.png)

Exiting the UI repairs offhand pick for 1920XP:
![2021-10-02_12 13 15](https://user-images.githubusercontent.com/49353797/135729244-fc53d3c1-763f-428b-a457-3e072373d7c0.png)

### Plugin and Datapack List

Plugins: ClearLag, CoreProtect, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, ExtraContexts, F3NPerm, LuckPerms, MinecraftAuth, Multiverse-Core, Multiverse-NetherPortals, PlaceholderAPI, TAB, Vault, WorldEdit, WorldGuard, WorldGuardExtraFlags

Datapacks: [vanilla (built-in)], [file/bukkit (world)]

### Paper version

This server is running Paper version git-Paper-297 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: e8830b2)\nYou are 3 version(s) behind\nPrevious version: git-Paper-299 (MC: 1.17.1)

### Other

I've tried different combinations of durability on items in main and offhand, and differing durability between the two and the damage on the tool not _exactly_ matching the amount of durability to be mended seems to greatly increase the odds of this happening. It's only happens with the mainhand item getting repaired first, then offhand item getting repaired when exiting the UI--if the offhand item is mended initially, it doesn't happen. The item in the main hand does not have to get repaired fully--it's still happened when the item in the main hand is not completely repaired.

Bug was discovered when server was running:
This server is running Paper version git-Paper-241 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 1276bd5)\nYou are 58 version(s) behind\nPrevious version: git-Paper-202 (MC: 1.17.1)

Server settings for XP orbs I can find:
paper.yml:
      experience-merge-max-value: -1

spigot.yml:
    merge-radius:
      exp: 3.0

**Comment by lynxplay** [comment]
I attempted the re-create this using the following setup on the currently latest paper version (a3dfe6dca5e2a5fadd232e9ea3425ec0841de2c3) and was not successful. For this, I chose the following setup:

1. `/data merge block ~ ~-1 ~ {Items:[{Slot:2b,id:"minecraft:gold_ingot",Count:1b}],RecipesUsed:{"minecraft:gold_ingot_from_smelting_raw_gold":1000}}`  >> which will result in 1000 exp, which map to 2000 repaired durability.
2. `/item replace entity @p weapon.offhand with netherite_sword{Damage:2030,Enchantments:[{id:"minecraft:mending",lvl:1s}]} 1`
3. `/item replace entity @p weapon.mainhand with netherite_sword{Damage:2030,Enchantments:[{id:"minecraft:mending",lvl:1s}]} 1`  >> which will place two netherite swords into the main/off hand respectively which have a single durability left.

I then proceeded to take the gold ingot out of the furnace I modified earlier. In each possible order (**main first, off after** and **off first, main after**) no duplication of the mending exp was observed over any of the tests I attempted.

Could you attempt to replicate this on the latest version of paper without any plugins ? 
Alternatively, if I failed something in my test setup, please let me know!

**Comment by GrifterMage** [comment]
After some more rigorous testing on a separate server, it looks like there's been an update on the Spigot end that fixed the issue since the version the bug was discovered on. I can replicate it on the original 241, but not 297 now. I was sure I confirmed it on that version, but maybe I was mistaken and accidentally left a full pick from the previous tests in my hand or something.

Regardless, it seems fine now, so closing.
