### ISSUE TITLE
Stacktrace upon input before init

### ISSUE THREAD

**Issue by jacobeva** [PaperSpigot/Paper#6714]
### Stack trace

```
java.lang.NullPointerException: Cannot invoke "org.bukkit.command.CommandSender.hasPermission(String)" because the return value of "net.minecraft.commands.CommandListenerWrapper.getBukkitSender()" is null at net.minecraft.commands.CommandDispatcher.lambda$new$0(CommandDispatcher.java:210) ~[patched_1.17.1.jar:git-Paper-243] at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:78) ~[patched_1.17.1.jar:git-Paper-243] at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:358) ~[patched_1.17.1.jar:git-Paper-243] at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:348) ~[patched_1.17.1.jar:git-Paper-243] at io.papermc.paper.console.BrigadierCommandHighlighter.highlight(BrigadierCommandHighlighter.java:28) ~[patched_1.17.1.jar:git-Paper-243] at org.jline.reader.impl.LineReaderImpl.getHighlightedBuffer(LineReaderImpl.java:3818) ~[patched_1.17.1.jar:git-Paper-243] at org.jline.reader.impl.LineReaderImpl.getDisplayedBufferWithPrompts(LineReaderImpl.java:3800) ~[patched_1.17.1.jar:git-Paper-243] at org.jline.reader.impl.LineReaderImpl.redisplay(LineReaderImpl.java:3700) ~[patched_1.17.1.jar:git-Paper-243] at org.jline.reader.impl.LineReaderImpl.doCleanup(LineReaderImpl.java:2427) ~[patched_1.17.1.jar:git-Paper-243] at org.jline.reader.impl.LineReaderImpl.cleanup(LineReaderImpl.java:2419) ~[patched_1.17.1.jar:git-Paper-243] at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:648) ~[patched_1.17.1.jar:git-Paper-243] at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418) ~[patched_1.17.1.jar:git-Paper-243] at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158) ~[patched_1.17.1.jar:git-Paper-243] at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141) ~[patched_1.17.1.jar:git-Paper-243] at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:113) ~[patched_1.17.1.jar:git-Paper-243]
```

### Plugin and Datapack List

[22:01:41 INFO]: Plugins (3): BlockLocker, ChunkLoader, Graves
[22:01:58 INFO]: There are 10 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/afk display v1.1.0.zip (world)], [file/armor statues v2.8.1.zip (world)], [file/chunk loaders v1.0.1.zip (world)], [file/custom nether portals v2.3.2.zip (world)], [file/fast leaf decay v2.0.3.zip (world)], [file/multiplayer sleep v2.4.3.zip (world)], [file/player head drops v1.1.0.zip (world)], [file/unlock all recipes v2.0.0.zip (world)]

### Actions to reproduce (if known)

Provide input to the papermc server before it is initialized, more information below.

### Paper version

This server is running Paper version git-Paper-243 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 20903fc)

### Other

This issue was migrated from https://github.com/Edenhofer/abs/issues/13 as per https://github.com/Edenhofer/abs/issues/13#issuecomment-932985755 due to the maintainer believing this to be an upstream issue with papermc. In effect, this script can sometimes provide the papermc server with commands via stdin before it is ready to process them (done! message), causing the above stack trace and preventing any further input to the server. However, the server still operates as normal besides this issue.
Please note the plugins and datapacks are NOT the cause of this issue.

**Comment by electronicboy** [comment]
confirmed, but, in the future when creating an issue, please use the *latest* version of Paper
