### ISSUE TITLE
Upgrading numeral block ID 36 to 1.17.1

### ISSUE THREAD

**Issue by terbin** [PaperSpigot/Paper#6720]
### Expected behavior

when upgrading very old region files to 1.17.1, **Block 36** gets translated to **minecraft:piston_extension**

### Observed/Actual behavior

when upgrading very old region files to 1.17.1 (from before Block 36 was removed) there is this warning:
```
[WARN]: [ca.spottedleaf.dataconverter.minecraft.versions.V102] Unknown legacy integer id (V102) 36
```

### Steps/models to reproduce

Upgrade old region files with numeral block ID 36 to 1.17.1

### Plugin and Datapack List

no plugins or datapacks

### Paper version

Paper 1.17.1 Build 304

### Other

Probably nothing to worry about for my world, once the pistons get updated they should work again.
It seems like that block is missing from the "translation list" though.

**Comment by electronicboy** [comment]
These are for items, not blocks; This doesn't seem like a bug, just a case of where DataConverter warns about unexpected data vs DFU which will remain silent in most cases

**Comment by terbin** [comment]
that block no longer exists in item form, so that makes sense.
thank you
