### ISSUE TITLE
Nether Portal spawns Entities in the wrong place

### ISSUE THREAD

**Issue by AllyreSoul** [PaperSpigot/Paper#6739]
### Expected behavior

It was expected that entities passing through a nether portal would appear at the corresponding portal in the nether.

### Observed/Actual behavior

The entities would instead spawn at the corresponding coordinate (overworld x/8, y, overworld z/8). This also applied in reverse from the nether to the overworld, in which case they would appear in (nether x * 8, y, and nether z * 8). This would cause entities and mobs to spawn in the air or in blocks and suffocate

### Steps/models to reproduce

1. Create a new world, and build a nether portal, go through it to generate a portal in the nether.
2. Make sure that the portal in the nether, scaled with the overworld portal is not the same coordinate (e.g 1, 7, 1 in the nether should NOT be at 8, 7. 8 in the overworld.)
3. Spawn entities, or throw items into the portal, and then go through the portal
4. The entities will be in the corresponding coordinate, instead of the portal (e.g. 8, 7, 8 in the overworld would spawn at 1,7,1 in the nether.)

### Plugin and Datapack List

I am running no plugins on my server.

### Paper version

This server is running Paper version git-Paper-313 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 7991c4b)
You are running the latest version
Previous version: git-Paper-311 (MC: 1.17.1)

**Comment by Machine-Maker** [comment]
Note to someone looking for a fix, look to e155002b317c6804a2a3e45c5eb05401060b5816 as a possible cause. Did mess with entities after nether portals
