### ISSUE TITLE
Kicked when deopping someone with enfore whitelist on

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#6741]

**Comment by defusing7** [comment]
I'd like to add that you are also kicked when you deop yourself, even if you explicitly added to the whitelist.

**Comment by NoahvdAa** [comment]
Can reproduce on Paper and vanilla. Seems like there is a [Mojira Issue](https://bugs.mojang.com/browse/MC-171420) for this already.

EDIT: This also happens when `/whitelist reload` is ran.
