### ISSUE TITLE
Confused Bug with minecraft commands 

### ISSUE THREAD

**Issue by EncryptSL** [PaperSpigot/Paper#6749]
### Expected behavior

Command must send back message about action.

Example when i send command /whitelist list in game must send list with users.

### Observed/Actual behavior

Actual behavior is commands sometimes no working, without reason. But when server is restarted, commands works.
But sometimes for one player or two players and another not.

But what is confused, commands works in console and sometimes too no.

### Steps/models to reproduce

https://www.youtube.com/watch?v=IcGA5I3vnvg
This video shows not working commands in game.

This screen can show working commands in console.
![image](https://user-images.githubusercontent.com/9441083/136564222-dd5a2146-2120-4003-8f5a-08abb8b67758.png)

### Plugin and Datapack List

Plugins, AmikaCore - Own custom, Chunky, ChunkyBorder, CoreProtect, dynmap, HostifyMonitor* - From hosting on data, ProtocolSupport

Datapacks: afk display, armor statues, double shulker shells, more mob heads, player head drops

### Paper version

```
15:20:55[INFO] Checking version, please wait...
15:20:55[INFO] This server is running Paper version git-Paper-320 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b470400)
You are running the latest version
Previous version: git-Paper-313 (MC: 1.17.1)
```

### Other

This only happens with Minecraft commands. But msg works and tell command.

**Comment by imDaniX** [comment]
Is the gamerule `sendCommandFeedback` set to true?

**Comment by ghost** [comment]
I can say that this bug is true, a few days ago I had this same problem, I gave a minecraft command and it only appeared on the console.

**Comment by EncryptSL** [comment]
@imDaniX When i set sendCommandFeedback on true, commands working, But this is very confused because i not disabled this function. 

This behavior i saw, think 3 or 5 days back, and now.

I cannot say if this is a true bug or not when @uRyanxD say this happend him too.

I wait what developers says on this behavior.

**Comment by ghost** [comment]
When it happened to me I had all the default settings.

**Comment by Machine-Maker** [comment]
If you can replicate this without plugins, I can only replicate this is the `sendCommandFeedback` gamerule set to false. Run (in each world) `/gamerule sendCommandFeedback true`, and see if you can still replicate it (without plugins/datapacks). Datapacks absolutely abuse this gamerule to hide command output. So replicating without datapacks is key

**Comment by EncryptSL** [comment]
Now in console with enabled sendCommandFeedback, 
Console not showing datapacks but in game yes.
![image](https://user-images.githubusercontent.com/9441083/136634774-838e56b7-3f9b-4609-9bc9-78b8b75195b6.png)

**Comment by electronicboy** [comment]
Can you reproduce without datapacks AND plugins? The literal only thing which controls if you get the success messages that I can see is the gamerule unless there is something hiding elsewhere, Don't think that this is a paper issue none the less given that it's just a typical send message (behind the gamerule check)

**Comment by EncryptSL** [comment]
Problem was in datapacks. When i removed all data packs. Problem was solved. But this is a confused because same datapacks on server i have more then 4 months. Before, everything works. Server only joke me :D. 

I think we can close.
