### ISSUE TITLE
Add a PlayerCriticalDamageEvent

### ISSUE THREAD

**Issue by arkozy** [PaperSpigot/Paper#6752]
### Is your feature request related to a problem?

There's no built-in method to check if a player's damage is critical.
 
### Describe the solution you'd like.

Here's an example of what will the event look like
```
@EventHandler
public void onCritical(PlayerCriticalDamageEvent event) {
     if(event.isCritical) {
          event.getPlayer().sendMessage("Critical Damage!!!");
     }
}
```
The event should be cancellable and have ```event.getPlayer()``` ,  ```event.getDamage()``` , ```event.setCritical()``` , and ```event.setDamage()```.

### Describe alternatives you've considered.

I tried making a method like this 
```
public boolean isCritical(Player player) {
     return !player.isOnGround
      && !player.hasPotionEffect(PotionType.BLINDNESS);
}
```
But sometimes it doesn't work or it's not very accurate.

### Other
This event will certainly be handy in some plugins like RPG-Based plugins when you do critical damage it will say "Crit!"

**Comment by lynxplay** [comment]
#6275 attempts to introduce the concept of a critical hit through a different API addition but might close this anyway if pulled.

**Comment by arkozy** [comment]
Hello, very new to making an issue but what do you mean by that?

**Comment by lynxplay** [comment]
> Hello, very new to making an issue but what do you mean by that?

I was just referencing a pull request that would potentially solve your request so that a) you can look at it/maybe give feedback and b) if that PR is pulled, this issue can be closed as well :+1:

**Comment by Wyatt-James** [comment]
I feel like having an entire event just dedicated to critical hits is a bit much and could become annoying to maintain. Wouldn't just having an isCritical() method for other damage events be enough?

**Comment by arkozy** [comment]
> I feel like having an entire event just dedicated to critical hits is a bit much and could become annoying to maintain. Wouldn't just having an isCritical() method for other damage events be enough?

oh yeah your right XD
