### ISSUE TITLE
Player::dropItem not work like expected

### ISSUE THREAD

**Issue by Doc94** [PaperSpigot/Paper#6760]
### Expected behavior

When use the method `player.dropItem(true)` the player drop the item (all stack) in hand.

### Observed/Actual behavior

When use the method the item drop but still show in hotbar, but if you click the item in hotbar then disapear.

### Steps/models to reproduce

Using player.dropItem in any cases.

### Plugin and Datapack List

Plugins: ConterCraft, CoreProtect, FastAsyncWorldEdit (WorldEdit), HackedCore*, HackedServer*, LibsDisguises, LuckPerms, PlugMan, ProtocolLib, SentryIntegration, spark

DataPacks: [vanilla (built-in)], [file/bukkit (world)], [file/VoidDimension-v1.2.zip (world)], [file/InfectionAdvancements-v.1.zip (world)], [file/FarmingLandDimension-v1.0.zip (world)], [file/BunnyBurrowDimension-v1.0.zip (world)]

### Paper version

Paper version git-Paper-325 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 4a0d935)

### Other

This working fine in 1.16.5, in the last version need use updateInventory for avoid glitch.

**Comment by HexedHero** [comment]
Can also confirm this is also broken on Spigot 1.17.1

**Comment by Machine-Maker** [comment]
Looking at the source, I almost feel like this is actually a vanilla issue, just wouldn't show up on a vanilla server because there's no way for the server to initiate a "drop" like that. Either way, this isn't the result of something upstream did so I'm gonna remove that label

**Comment by Owen1212055** [comment]
Can't reproduce as of 1.18.2
![image](https://user-images.githubusercontent.com/23108066/157344173-52cd41ba-64bf-4f9c-a012-d9202b979465.png)
(most recent drop code)

**Comment by lynxplay** [comment]
That code did not change from 1.17, and I can still properly reproduce this on latest.
Would you mind sharing your current setup code for this ?

**Comment by Owen1212055** [comment]
Whoops, I accidentally tested the fix for this.

Yes, can still reproduce this. :)
