### ISSUE TITLE
RGB Color only applies on lore after reconnect and on books only after signing it.

### ISSUE THREAD

**Issue by DanHCraft** [PaperSpigot/Paper#6764]
### Expected behavior

If I set the lore of an Item with a RGB-Color in it, with `ItemMeta::lore(List<Component> list)` or `ItemMeta::setLore(List<String>)`, then the Item shows the correct RGB-colorized text, after the `ItemStack::setItemMeta(ItemMeta meta)` call.

*Hint: Book => minecraft:writable_book*
Also if you listen to the BookEditEvent and you parse the color codes from the user, after you click done and reopen the book for editing the text is RGB-colorized.

### Observed/Actual behavior

*Hint: All RGB Colores that are used in the old implementations are formatted to `§x§r§r§g§g§b§b`. The new implementation is fromatted to `§#rrggbb`*

At the moment only the last hex-digit will transformed to a single char color code and not the the whole hex-color code.
i.e.: You have `&#a6f1faHallo`. This will tranfered to (not in real but for showing how it looks to the player): `&aHallo`.

ONLY if you reconnect with the ItemStack in your PlayerInventory then the rgb color with recognized coreectly and the text has the right.

If you reopen the Book for editing you see the same issue like in the lore. Only the last hex-digit will be translated to an color and only if you sign the book the full RGB-Color will be showen and here ONLY if you not use an Component from the Kyori Adventur API, but the old way with `BookMeta::setPages(List<String> list)`.

### Steps/models to reproduce

This is one of the implementations I tried:
```java
// ... command for editing lore ...
ItemMeta meta = item.getItemMeta(); // item from main hand of player.
Lore<Component> lore =  new LinkedList<>();
lore.add(Component.text(String.join(" ", args)));
meta.lore(lore);
item.setItemMeta(meta);
```
I also tried the old implementation with `ItemMeta::setLore(List<String> list)` and I also tried `LegacyComponentSerializer.legacyAmpersand().deserialize(String lineOfLore)`

Same with the BookMeta.

### Plugin and Datapack List
*Hint: FCN_Core and KnusperLib are my plugins.*

**/plugins:**
[18:18:45 INFO]:FastAsyncWorldEdit (WorldEdit), FCN_Core, KnusperLib, LuckPerms, Multiverse-Core, TabTPS, Vault, VaultChatFormatter*, WorldGuard

**/datapack list**
[18:19:53 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[18:19:53 INFO]: There are no more data packs available

### Paper version

This server is running Paper version git-Paper-325 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 4a0d935)
You are running the latest version
Previous version: git-Paper-320 (MC: 1.17.1)

### Other

For the Kyori Adventure Text API I used your version that is Version 4.8.1 and I also tried the latest one, Version 4.9.2.

**Comment by kezz** [comment]
Writable books don't support components, so the RGB codes won't work in the book itself.

**Comment by electronicboy** [comment]
> if you reconnect with the ItemStack in your PlayerInventory then the rgb color with recognized coreectly and the text has the right

You're not showing how you're creating that, but, that just screams that you're creating the components improperly and somehow some fix logic is running somewhere which is fixing your bad lore, etc
Storing color codes directly into components is bad practice and will create the exact behavior you've stated given that the client will just parse the last color it finds given that that rgb is not supported by the legacy renderer

Use the serialisers to create proper components

**Comment by DanHCraft** [comment]
As I mentioned ALREADY, I have tried it already, same behavoir.
With the book and the lore.

**Comment by electronicboy** [comment]
Please use the discord for further discussion on this and provide more info on what exactly is being inputted, etc, this just looks like you're improperly using the API and dealing with a bad output, I don't think that this is a paper issue

**Comment by kennytv** [comment]
Writable books don't support components, which means they don't support rgb, only written books do. Using legacy codes in components *works*, but completely goes against their intended use. Using Bukkit's disgusting rgb hack in legacy text is discouraged, and is not supported by adventure's default legacy deserializer since it is a non-standard format.
