### ISSUE TITLE
Add a way to get Player that called LightningStrikeEvent with Cause.TRIDENT

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#6781]
### Is your feature request related to a problem?

See https://github.com/EngineHub/WorldGuard/issues/1845

### Describe the solution you'd like.

1. Add method to LightningStrikeEvent#getSource() or similar that returns Player or null if this is a weather-related strike
2. Create subevent named like ChannelingStrikeEvent that called in that case and contains getter for the Player

### Describe alternatives you've considered.

Listen to trident launch event, store the Player and use it later in LightningStrikeEvent..?

### Other

I also think that currently there are no way to know who involved trident-related lighting strike, but if I'm wrong, please tell me. Thanks!

**Comment by electronicboy** [comment]
note for somebody who wants to implement this, the bolt already stores the "causing" player
