### ISSUE TITLE
PlayerItemFrameInsertItemEvent and PlayerItemFrameRemoveItemEvent

### ISSUE THREAD

**Issue by aerulion** [PaperSpigot/Paper#6783]
### Is your feature request related to a problem?

I'm trying to modify the item being placed inside an item frame. When using the PlayerInteractEntityEvent, I can check the used item, but that corresponds to the whole stack the player is holding, not just the single item which ends up being placed inside the frame, so modifying it changes the remaining items the player is holding.

### Describe the solution you'd like.

A relatively simple event, containing the item frame, the player who inserts the item, and the modifiable itemstack of the item which ends up being placed inside the frame. An event for removing an item from an item frame isn't needed in my use case, but would probably be nice to have for the sake of completeness.

### Describe alternatives you've considered.

My solution was to schedule a task a few ticks delayed after the interact event, checking and modifying the itemstack, which in my opinion isn't very efficient for such a simple problem.

**Comment by Doc94** [comment]
¿Maybe is better a event like `ItemFrameChangeEvent`? for cases like..

- Item Rotation
- Item put
- Item drop

all this is can be called in the interact method for the ItemFrame.

now im not sure if `EntityChangeBlockEvent` already handle this cases.

**Comment by Machine-Maker** [comment]
I don't think EntityChangeBlockEvent is currently called for that, nor should it. Item frames are not blocks, they are entities. I think an ItemFrameChangeEvent makes a lot of sense
