### ISSUE TITLE
Named friendly mobs despawning

### ISSUE THREAD

**Issue by Nemesees** [PaperSpigot/Paper#6800]
### Expected behavior

Named friendly mobs should not despawn (in this case they are pufferfish).

### Observed/Actual behavior

After playing like always, when I would return back to those pufferfish, some would be gone.

### Steps/models to reproduce

What I did was simply transport pufferfish with a bucket into a pond and then name them. After that, time needs to pass by (in my case it was probably almost a couple of weeks).

### Plugin and Datapack List

No plugins.
Datapacks: [vanilla (built-in)], [file/bukkit (world)]

### Paper version

This server is running Paper version git-Paper-100 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 70ea1b2)
You are 236 version(s) behind

### Other

I'm not sure if this could help, but I'm running my paper server from a raspberry pi 4, using Pinecraft. 

As for the OS, it's running Ubuntu server 21.04.

Since this is my first time posting an issue, please let me know if more information is required.

**Comment by Machine-Maker** [comment]
Ok, you need to update. see that **236** versions behind? see if your issue is resolved then.

**Comment by Nemesees** [comment]
From what I found, I just have to download the latest paperclip jar and replace it? Also sorry for my lacking knowledge, but this won't affect my world, right?

**Comment by e-im** [comment]
You are correct, however if possible it is always recommended to make a backup before updating. As this is a common question with no proper documentation, I've started working on docs for this which you can see [a draft of here](https://github.com/PaperMC/PaperDocs/blob/dec25c0ba42c38978d9dd1c6728d50b09eaa2fa9/source/server/update.rst).

**Comment by Machine-Maker** [comment]
I believe there was a commit in the last 236 builds to fix persistence for fish/axolotls so I'm gonna close this. comment here tho if it still happens on the latest build.
