### ISSUE TITLE
Logging out in end Puts you in the same coods but in the nether when logging in

### ISSUE THREAD

**Issue by GamerToTheMax** [PaperSpigot/Paper#6801]
### Expected behavior

When you log out in the end you should still be in the end

### Observed/Actual behavior

When you log out in the end it puts you in the same coodinates however in the nether

### Steps/models to reproduce

1. Make an end Portal
2. Enter the end
3. Log out
4. log in
5.And you should be in the nether

### Plugin and Datapack List

[17:26:18 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[17:26:18 INFO]: There are no more data packs available

[17:26:32 INFO]: Plugins (6): GSit, JDA*, MinecraftManhunt, SkinsRestorer, Sudo*, WorldEdit (Btw ive tried without the plugins and it still does it)

### Paper version

> version
[17:27:14 INFO]: Checking version, please wait...
[17:27:16 INFO]: This server is running Paper version git-Paper-336 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: eaee7a2)
You are running the latest version

**Comment by lynxplay** [comment]
I cannot reproduce this on eaee7a2473baa4e8a51fea63b2dcf0ff7bda31b3 running a fresh server install. 
Are you certain that this was reproduced without plugins properly ? 

I also do not know of a server setting that might cause this, especially a spawn in the nether as the server defaults to the overworld if the end dimension could not be found.

**Comment by GamerToTheMax** [comment]
Well ive tried everything

-updating the paper server
-removing all the plugins
-reseting the server.properties file
-made sure that the end is enabled

im not sure the world files has something to do with it but im not sure what to do

**Comment by lynxplay** [comment]
I am sadly unable to reproduce this whatsoever.
Additionally, we do not support servers supporting piracy through running in offline-mode.

If you a) can reliably reproduce this (instructions to reproduce this on a fresh install) and b) stopped supporting piracy of the game, feel free to comment on this issue/open a new issue with the updated instructions.
