### ISSUE TITLE
PathNavigation.createPath incorrectly remaps in Paper output jar

### ISSUE THREAD

**Issue by mcmonkey4eva** [PaperSpigot/Paper#6802]
### Expected behavior

`PathNavigation.createPath(...)` in the Mojang mappings should become `NavigationAbstract.a(...)`

### Observed/Actual behavior

`PathNavigation.createPath(...)` becomes `NavigationAbstract.createPath(...)` - ie, instead of remapping to `a`, it retains the original method name.

### Steps/models to reproduce

Compare a decompilation of a paper `patched_1.17.1.jar` to a spigot server jar I guess? This restrictive issue template is unhelpful for technical issues.

Actual origin is from trying to call the method. Works fine on Spigot, fails on Paper. Sample error messages seen:
`java.lang.NoSuchMethodError: 'net.minecraft.world.level.pathfinder.PathEntity net.minecraft.world.entity.ai.navigation.NavigationAbstract.a(net.minecraft.core.BlockPosition, int)'`
and `java.lang.NoSuchMethodError: 'net.minecraft.world.level.pathfinder.PathEntity net.minecraft.world.entity.ai.navigation.NavigationAbstract.a(double, double, double, int)'`

### Plugin and Datapack List

Issue originates while investigating an incompatibility between Denizen and Paper.

### Paper version

[04:19:38 INFO]: Checking version, please wait...
[04:19:39 INFO]: This server is running Paper version git-Paper-336 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: eaee7a2)
You are running the latest version
Previous version: git-Paper-266 (MC: 1.17.1)

### Other

Presumably related to https://github.com/PaperMC/Paper/blob/7d10cdea0358854138d0d0ada5e74c58c688dea7/patches/server/0074-EntityPathfindEvent.patch which adds new methods of the same name, this probably accidentally broke the automatic method renaming process.
EDIT: actually that commit also adds an `a(...)` method manually (with a different signature) for some reason which might be relevant to why the real `a(...)` isn't generated.

**Comment by jpenilla** [comment]
Duplicate of https://github.com/PaperMC/Paper/issues/6243, which was closed and referred to https://github.com/PaperMC/paperweight/issues/24. Personally I think having the issue open here on the Paper repo is more useful, so I'm leaving this one open. iirc there's actually more than one `createPath` method which has this issue, the solution is they need to be added to `build-data/reobf-mappings-patch.tiny` (also we should probably rename the `a` method we add, although it's unlikely to be unrelated to the issue)
