### ISSUE TITLE
Seed based search doesn't use custom structure seeds

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#6803]
### Expected behavior

Seed based search feature should use the spigot custom structure seeds 

### Observed/Actual behavior

They do not, changing spigot structure seeds will break treasure maps etc.

### Steps/models to reproduce

Change spigot structure seed.

### Plugin and Datapack List

N/A

### Paper version

This server is running Paper version git-Paper-"4a0d935" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 4a0d935)
You are 14 version(s) behind

This version is normal paper that i compiled with the chunk border lag patch since no-one accepted the PR.

**Comment by e-im** [comment]
This doesn't seem to be the case, how did you come to this conclusion?

Some things that may cause the behaviour you describe:
1. Having `seed-based-feature-search-loads-chunks` set to false
2. Changing spigot's structure seeds after you have already generated a portion of the world.

Please comment with more details as to how you have determined this to be the case.
