### ISSUE TITLE
setFrozen or freezetick similar to firetick

### ISSUE THREAD

**Issue by Boy0000** [PaperSpigot/Paper#6812]
### Is your feature request related to a problem?

Unlike with firetick, the freeze effect is only applied when inside powder snow for x ticks. Simply repeatedly setting the freezetick to max for a player doesnt solve it.

### Describe the solution you'd like.

Some way to specify that an entity is frozen, as if they were inside a powder snowblock with max freezetick.
There is already entity.isFrozen, but it only returns if it is frozen or not.

This would ofcourse not be removed when not in a powder snow block, and be a constant effect until it is "false"

### Describe alternatives you've considered.

Constantly setting the entities freezetick to max (doesnt work)
Sending a blockchange to the location of the entity

### Other

![136946145-73542c0f-9f03-4a20-b234-ffed604c8142](https://user-images.githubusercontent.com/62521371/138312993-b207a45f-c888-4aaf-a4d6-1ae71d4c17e3.gif)
When constantly setting freezeticks, this is the result.

**Comment by Machine-Maker** [comment]
For someone who looks into this, I think a TriState would be applicable here. To essentially override the default isFullyFrozen check with true, false, or not set, which falls back on the vanilla mechanics.
