### ISSUE TITLE
LivingEntity Pathfinder moveTo(LivingEntity entity, Double speed) implementation doesn't override LivingEntity behaviour

### ISSUE THREAD

**Issue by Jayryn** [PaperSpigot/Paper#6814]
### Expected behavior

Expected to see is the Pathfinder setting of a LivingEntity to the Location of another LivingEntity and to then start the Pathfinder.

### Observed/Actual behavior

The Pathfinder isn't set nor started for the LivingEntity and it does not move to the Location of a LivingEntity. Instead is ignores the setting of the Pathfinder completely.
Another test showed that the moveTo(Location location, Double speed) Pathfinder implementation worked correctly as intended.

### Steps/models to reproduce

**Example-code below**

1. Spawn a new LivingEntity [ LivingEntity entity = (LivingEntity) world.spawnEntity(Location location, EntityType type); ]
2. Remove all MobGoals for the LivingEntity [ Bukkit.getMobGoals().removeAllGoals(LivingEntity entity); ]
3. Set the new Pathfinder with moveTo(LivingEntity target, Double speed) method [ entity.getPatherfinder.moveTo(LivingEntity target, Double speed) ]
4. Print out the final Pathfinder destination [ System.out.println(entity.getPathfinder().getCurrentPath()).getFinalPoint()) ]
5. Watch for expected behavior

// Axolotl LivingEntity Example
    
    public void pathfinderTest(World world, Location location, LivingEntity target, Double speed){
        Axolotl entity = (Axolotl) world.spawnEntity(location, EntityType.AXOLOTL);
        Bukkit.getMobGoals().removeAllGoals(entity);
        entity.getPathfinder().moveTo(target, speed);
        System.out.println(Objects.requireNonNull(entity.getPathfinder().getCurrentPath()).getFinalPoint());
    }

### Plugin and Datapack List

/plugins - SystemAPI -> Selfcoded API with the Pathfinder implementation
/datapack list - [vanilla (built-in)], [file/bukkit (world)]

### Paper version

This server is running Paper version git-Paper-349 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9472d38)
You are running the latest version
Previous version: git-Paper-336 (MC: 1.17.1)

### Other

The moveTo(Location location, Double speed) Pathfinder implementation worked correctly as intended when tested.

// Axolotl LivingEntity Example
    
    public void pathfinderTest(World world, Location location, Location target, Double speed){
        Axolotl entity = (Axolotl) world.spawnEntity(location, EntityType.AXOLOTL);
        Bukkit.getMobGoals().removeAllGoals(entity);
        entity.getPathfinder().moveTo(target, speed);
        System.out.println(Objects.requireNonNull(entity.getPathfinder().getCurrentPath()).getFinalPoint());
    }

**Comment by lynxplay** [comment]
I attempted to recreate this issue using the following code:

```java
@EventHandler
public void on(PlayerInteractAtEntityEvent event) {
    if (event.getHand() != EquipmentSlot.HAND) return;
    if (!(event.getRightClicked() instanceof Axolotl entity)) return;

    Bukkit.getMobGoals().removeAllGoals(entity);
    entity.getPathfinder().moveTo(event.getPlayer().getLocation(), 0.5);

    Bukkit.broadcast(Component.text("final point:" + Objects.requireNonNull(entity.getPathfinder().getCurrentPath()).getFinalPoint().toString()));
    Bukkit.broadcast(Component.text("available goals:" + Arrays.toString(((CraftMob) entity).getHandle().goalSelector.availableGoals.toArray())));
    Bukkit.broadcast(Component.text("available targets:" + Arrays.toString(((CraftMob) entity).getHandle().targetSelector.availableGoals.toArray())));
}
```

which results in the following behaviour:

https://user-images.githubusercontent.com/32834385/138472501-7833b6f3-e866-4e97-9ebd-9aa2607ec416.mp4

Note that axolotls define their own pathfinding that priorities water, but the pathfinder is definitely ticked (as it is not part of either the goal or target api anyway, but rather part of the navigation stage).

Is this only an issue with the axolotl ? Have you attempted to run this with different entities ?

**Comment by Owen1212055** [comment]
It should be noted that removing goals from axolotls will not work because they do not use the goal system, rather the brain/memory system. I'm not sure we have api which covers that.

**Comment by lynxplay** [comment]
> It should be noted that removing goals from axolotls will not work because they do not use the goal system, rather the brain/memory system. I'm not sure we have api which covers that.

Afaik we do not right now, e.g. the need for #6336. However you should still be able to call the respective pathfinding metho shown above.
The brain of the entity might however interfere at some point.

//edit[0]: There is a *basic* API available to access memories in a brain, specifically  [getMemory](https://papermc.io/javadocs/paper/1.17/org/bukkit/entity/LivingEntity.html#getMemory(org.bukkit.entity.memory.MemoryKey)), tho this will not allow you to remove behaviours.

**Comment by Jayryn** [comment]
I have tried it with other entities which shows the same result as mentioned.

**Bug is independent from EntityType**

**Comment by Jayryn** [comment]
> I attempted to recreate this issue using the following code:
> 
> ```java
> @EventHandler
> public void on(PlayerInteractAtEntityEvent event) {
>     if (event.getHand() != EquipmentSlot.HAND) return;
>     if (!(event.getRightClicked() instanceof Axolotl entity)) return;
> 
>     Bukkit.getMobGoals().removeAllGoals(entity);
>     entity.getPathfinder().moveTo(event.getPlayer().getLocation(), 0.5);
> 
>     Bukkit.broadcast(Component.text("final point:" + Objects.requireNonNull(entity.getPathfinder().getCurrentPath()).getFinalPoint().toString()));
>     Bukkit.broadcast(Component.text("available goals:" + Arrays.toString(((CraftMob) entity).getHandle().goalSelector.availableGoals.toArray())));
>     Bukkit.broadcast(Component.text("available targets:" + Arrays.toString(((CraftMob) entity).getHandle().targetSelector.availableGoals.toArray())));
> }
> ```
> 
> which results in the following behaviour:
> 
>  0001-0897.mp4 
> Note that axolotls define their own pathfinding that priorities water, but the pathfinder is definitely ticked (as it is not part of either the goal or target api anyway, but rather part of the navigation stage).
> 
> Is this only an issue with the axolotl ? Have you attempted to run this with different entities ?

Issue is that as I mentioned the moveTo(Location location, Double speed) method works as intended, like you showed in the video. Problem is that if you switch the Location argument to the LivingEntity argument, the Axolotl or in generel the LivingEntity does not move to the desired LivingEntity.

**UPDATE: I may have another idea for testing. More information following.**

**Comment by lynxplay** [comment]
Looking at some debugger output, the `MoveToTargetSink` behaviour does seem to override the path after it has been activated.
Sadly you will not be able to remove that behaviour without a proper API for it :/

**Comment by Jayryn** [comment]
> :/

Still thanks for replying :)

**Comment by lynxplay** [comment]
> > :/
> 
> Still thanks for replying :)

As a current workout, waiting a few ticks (3 ticks worked out for me) seems to at least somewhat work as the behaviour was activated and does not re-apply its path for I believe 40 ticks?
I'll open a respective issue about this to document the feature request to be able to remove behaviours completely from an entity.
Once opened, this should probably be closed as "working as intended".

**Comment by Jayryn** [comment]
> > > :/
> > 
> > 
> > Still thanks for replying :)
> 
> As a current workout, waiting a few ticks (3 ticks worked out for me) seems to at least somewhat work as the behaviour was activated and does not re-apply its path for I believe 40 ticks? I'll open a respective issue about this to document the feature request to be able to remove behaviours completely from an entity. Once opened, this should probably be closed as "working as intended".

May I see your workaround code? Did you apply the waiting in an event?
I believe opening a requested feature document for this is a good idea.

**Comment by lynxplay** [comment]
```java
@EventHandler
public void on(BlockBreakEvent event) {
    final Axolotl entity = event.getPlayer().getWorld().spawn(event.getBlock().getLocation(), Axolotl.class);

    Bukkit.getScheduler().runTaskLater(PaperTestsuitePlugin.this, () -> {
        Bukkit.getMobGoals().removeAllGoals(entity);
        entity.getPathfinder().moveTo(event.getPlayer(), 0.5);
    }, 3);
}
``` 
This was my code for testing (Used the block break event as an easy to use event for spawning).

**Comment by Jayryn** [comment]
> ```java
> @EventHandler
> public void on(BlockBreakEvent event) {
>     final Axolotl entity = event.getPlayer().getWorld().spawn(event.getBlock().getLocation(), Axolotl.class);
> 
>     Bukkit.getScheduler().runTaskLater(PaperTestsuitePlugin.this, () -> {
>         Bukkit.getMobGoals().removeAllGoals(entity);
>         entity.getPathfinder().moveTo(event.getPlayer(), 0.5);
>     }, 3);
> }
> ```
> 
> This was my code for testing (Used the block break event as an easy to use event for spawning).

Thank you :)

**Comment by Machine-Maker** [comment]
Well its certainly not all LivingEntities, works fine with pigs. Made a command that did this
```java
Pig pig = player.getWorld().spawn(player.getLocation(), Pig.class);

Bukkit.getScheduler().runTaskLater(this, () -> {
    Bukkit.getMobGoals().removeAllGoals(pig);
    pig.getPathfinder().moveTo(player, 0.5);
    Pathfinder.PathResult pathResult = pig.getPathfinder().getCurrentPath();
    if (pathResult != null) {
        System.out.println(pathResult.getFinalPoint());
    }
}, 100L);
```
after 5 seconds, the pig walks right over to where I am.

EDIT: also works fine with Axolotls, so either I'm doing something wrong, or this isn't an issue.

**Comment by Jayryn** [comment]
> Well its certainly not all LivingEntities, works fine with pigs. Made a command that did this
> ```java
> Pig pig = player.getWorld().spawn(player.getLocation(), Pig.class);
> 
> Bukkit.getScheduler().runTaskLater(this, () -> {
>     Bukkit.getMobGoals().removeAllGoals(pig);
>     pig.getPathfinder().moveTo(player, 0.5);
>     Pathfinder.PathResult pathResult = pig.getPathfinder().getCurrentPath();
>     if (pathResult != null) {
>         System.out.println(pathResult.getFinalPoint());
>     }
> }, 100L);
> ```
> after 5 seconds, the pig walks right over to where I am.
> 
> EDIT: also works fine with Axolotls, so either I'm doing something wrong, or this isn't an issue.

Issue could be caused if the Pathfinder is applied to early. Maybe a delay of 3 ticks is key for applying this.

**Comment by Machine-Maker** [comment]
Yeah, looks like you have to wait for 2 ticks of the Axolot's brain before setting its moveTo location. So that means running a scheduled task in 3 ticks.
