### ISSUE TITLE
Shulkers Wont Split

### ISSUE THREAD

**Issue by DustyEh** [PaperSpigot/Paper#6815]
### Expected behavior

Shulkers Split sometimes upon taking damage (or hit by snowballs) creating more of them

### Observed/Actual behavior

Shulkers wont split no matter how many snowballs or how much you hit them

### Steps/models to reproduce

throw snow at shulker, this should eventually split it 

### Plugin and Datapack List

/plugin -  none
/datapack list - vinalla(built-in), file/bukkit(world)

### Paper version

This server is running Paper version git-Paper-349 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9472d38)
You are running the latest version

### Other

[Uploading Shulker Farm v4 WDL.zip…]()
https://www.youtube.com/watch?v=pFdLqTE1MzE&t=186s  (internet trash so can upload world but this is exactly what i made, i did a schematic of it)
thats the farm I made and noticed them not splitting

**Comment by rymiel** [comment]
Not sure where you got this info but shulkers only ["split" when hit by shulker *bullets* (of another shulker, or itself)](https://minecraft.fandom.com/wiki/Shulker#Post-generation), taking other damage only makes them teleport
