### ISSUE TITLE
EntityPlayer Memory Leak From playerGeneralAreaCache

### ISSUE THREAD

**Issue by pkt77** [PaperSpigot/Paper#6816]
### Stack trace

Here is a screenshot of the memory dump, after server has ran for 20 hours. Only 17 players were online at the time.
![image](https://user-images.githubusercontent.com/1795264/138389693-f8820590-615a-454a-93f7-7755173fc6ab.png)

### Plugin and Datapack List

ProtocolSupport is the only public plugin. The other is private.

### Actions to reproduce (if known)

I know this only started recently for 1.17 Paper
I believe this might be caused by autosave being off.

### Paper version

git-Paper-"5cab6d4" 1.17

**Comment by Proximyst** [comment]
Not a memory leak… the caches are used to know what to keep loaded.

**Comment by pkt77** [comment]
So they keep track of offline players? Seems like the worst cache ever...

**Comment by electronicboy** [comment]
1.17 isn't supported anymore, and I don't see where the actual leak you're pointing to is, nor are you showing a count of EntityPlayer instances; what you're looking at there is the block entity ticker

**Comment by pkt77** [comment]
Sorry, 1.17.1 (as you can see by the commit hash used) and if you look at the screenshot it says "Referenced Objects - 615"

**Comment by electronicboy** [comment]
Git hash doesn't point to anything in our repo

**Comment by pkt77** [comment]
Oh interesting it takes my private commits, thought it was taken from gradle.properties paperRef (which is 9472d38f3c05a9f833cac72368cf49eb419200a1)
Well I'll be removing [this patch](https://github.com/PaperMC/Paper/blob/master/patches/server/0792-Optimise-nearby-player-lookups.patch) until it's fixed.

**Comment by electronicboy** [comment]
that cache was ref'ing 6 objects

**Comment by pkt77** [comment]
okay, there's hundreds more...
![image](https://user-images.githubusercontent.com/1795264/138397775-89682087-4f0b-4b1c-a0f1-fdb1b190f4a9.png)

**Comment by electronicboy** [comment]
Oh, wait, I misread how that was representing data, too used to yourkits UI, I actually fail to see where those caches are actually updated during the runtime of the server

**Comment by electronicboy** [comment]
Oh, I see where it updates those, nvm; I have no idea how eclipse represents objects, are those 100% individual retained instances? does it show how many there are in total on the overall page? the logic that I can see looks generally fine so I don't exactly see on the surface where it wouldn't be updating that data

**Comment by pkt77** [comment]
There are a total of 620 EntityPlayers, 597 under this cache. The dump is obtained from `jmap -dump:live` and the option I used find them from the Histogram in the analyzer is "Merge shortest path to GC roots". I'm going to do some more debugging, see if I can replicate it with just me being left in the cache.

**Comment by MiniDigger** [comment]
you sure that its not some plugin that stores players in a list or something?

**Comment by pkt77** [comment]
> you sure that its not some plugin that stores players in a list or something?

Look at the screenshots, it says where they're being referenced from.

**Comment by Spottedleaf** [comment]
This heap dump needs to be passed to someone so they can actually review the contents, rather than sitting around and guessing.

**Comment by Warriorrrr** [comment]
If you can still reproduce this issue on the latest version, please take a new heap dump and attach it here. Closing for now due to the age of this.
