### ISSUE TITLE
Custom items bought from a villager can sometimes not be stacked

### ISSUE THREAD

**Issue by Koyorice** [PaperSpigot/Paper#6834]
### Expected behavior

Items traded with villagers can be stacked.

### Observed/Actual behavior

I used the paper server to make trades for villagers’ custom items, but the items obtained from the trades can sometimes be superimposed, and sometimes they can’t be superimposed.
I tested it in vanilla server or single player game but it can stack.

### Steps/models to reproduce

This is the instruction I use:
[3.txt](https://github.com/PaperMC/Paper/files/7408531/3.txt)
paper dumpitem:![paper dumpitem](https://user-images.githubusercontent.com/87787929/138662715-859b543e-ed0c-4793-b9f8-cc3420fa3171.png)

### Plugin and Datapack List

> plugins
[08:23:29 INFO]: Plugins (16): ChestCommands, CustomJoinItems*, DiscordSRV, Essentials, MysqlEcoBridge*, PDMSG*, PermissionsEx*, PexTabCompleter, PlaceholderAPI, PlayerSQL*, PlayerTitle, ProtocolLib, SimpleORM*, TimeCommands*, Vault, WorldEdit

### Paper version

> version
[08:27:42 INFO]: Checking version, please wait...
[08:27:42 INFO]: This server is running Paper version git-Paper-351 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: c66adfb)
You are running the latest version
Previous version: git-Paper-325 (MC: 1.17.1)

**Comment by blablubbabc** [comment]
Your enchantment levels should probably be of type short instead of integer. Eg. `Enchantments:[{"id":"minecraft:protection","lvl":10s}]`. There are situations in which Bukkit converts the data type of the enchantment level to the expected short data type. Items with different data types as their enchantment level won't stack in some situations.

**Comment by Machine-Maker** [comment]
Oh that makes sense, when I was testing this out, spawning in the items with command blocks and looking at the tags showed 10s instead of the 10 from the /summon command. So yes @YTiceice try blablubbabc's suggestion, and report back

**Comment by Koyorice** [comment]
Ok,I will try it
