### ISSUE TITLE
Add a getResultPotionData() method to the BrewEvent

### ISSUE THREAD

**Issue by GavvyDizzle** [PaperSpigot/Paper#6835]
### Is your feature request related to a problem?

Currently, in the BrewEvent the only way to get the potion is using getBasePotionData(). This method returns the potion data just before the new potion is created.

### Describe the solution you'd like.

A method getResultPotionData() that returns the result of the brew.

### Describe alternatives you've considered.

Running getBasePotionData() inside of a delayed task returns the resulting potion.

**Comment by Doc94** [comment]
I take this for try a PR in upstream (https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/pull-requests/945/overview) making a copy of the results potions and allow dev to modify the results.

i prefer make getResults because the brew can get 3 different results for any results slot.

**Comment by Doc94** [comment]
Ready in CB (thanks @lynxplay for the feedback).
https://github.com/PaperMC/Paper/pull/6848

**Comment by lynxplay** [comment]
Resolved by the last upstream update (https://github.com/PaperMC/Paper/commit/a284e40c70ce1779e59013f949ca7d2885f0ef56)
