### ISSUE TITLE
Potion Effect's particles still showing and effects happening when potion effect removed.

### ISSUE THREAD

**Issue by hugovdev** [PaperSpigot/Paper#6839]
### Expected behavior

No potion effect particles or effects.

### Observed/Actual behavior

Particles showing around the player and effects still there infinitely. (Does not show as an effect when opening the inventory)

### Steps/models to reproduce

1. Eat golden apple
2. Run code:
`for (PotionEffect pe : player.getActivePotionEffects()) player.removePotionEffect(pe.getType());`

### Plugin and Datapack List

Authme, FastLogin, DecentHolograms, ProtocolLib, SkinsRestorer, SlimeWorldManager, Spark, Custom Plugin

### Paper version

Paper version git-paper-353 (MC 1.17.1) (Implementing API version1.17.1-R0.1-SNAPSHOT) (Git: f2cb9cb)

**Comment by Machine-Maker** [comment]
I cannot replicate this with paper 1.18.1 and no plugins. If you can replicate this without plugins, please post more specific reproduction steps as neither golden apple types produced the results you described after clearing the effects.
