### ISSUE TITLE
Precise settings which mobs are counted towards the mob cap

### ISSUE THREAD

**Issue by Michmax** [PaperSpigot/Paper#6845]
### Is your feature request related to a problem?

In vanilla Minecraft, only certain mobs count towards the mob cap. 
For example, naturally spawned mobs, Withers, Shulkers, and zombified villagers that have been traded in advance **do** count towards  the mob cap, but nametagged mobs or mobs that have picked up loot **do not**.

Because these particular villagers, shulkers, and withers do not despawn, they are especially useful for building a mob switch.

As far as I know, Paper only offers the possibility to count all mobs to the cap or only naturally spawned mobs:
`count-all-mobs-for-spawning:`

A more precise setting option would be nice to create an experience closer to Vanilla.

### Describe the solution you'd like.

My suggestion would be a more precise specification in the Paper settings which mobs should count towards the mob cap
Example:
``` 
 count-all-mobs-for-spawning: false
 counted-mobs-for-spawning:
   natural spawned mobs: true
   spawner mobs: false
   nametaged mobs: false
   mobs-with-picked-up-loot: false
   wither: true
   traded zombified villagers: true
```

### Describe alternatives you've considered.

In order to get a mob switch up and running, I set the `count-all-mobs-for-spawning:` setting to "true". 
Unfortunately, name tagged mobs in the spawn chunks now count towards the mob cap when the switch is off, which affects some mob farms.

**Comment by Machine-Maker** [comment]
Yeah, this is mostly due to craftbukkits mangling of persistence over the many years. https://github.com/PaperMC/Paper/tree/fix/persistence goes a good way to fixing it, and if its not almost entirely fixed by that branch, it can be pretty easily.

**Comment by Feche** [comment]
Any news regarding this?

**Comment by romanobauaumann** [comment]
Yeah, this is the exact issue im also having at the moment. Im honestly shocked that not more people are having this issue. Does anyone have a fix for this? Like a plugin that specifically excludes nametagged mobs?
