### ISSUE TITLE
Pathfinder API option to allow pathing over rails

### ISSUE THREAD

**Issue by andrew121410** [PaperSpigot/Paper#6846]
### Is your feature request related to a problem?

Mobs in general don't path-find over rails. Seems quite odd that for example zombies act like there's an invisible wall in place

### Describe the solution you'd like.

There should a option in the API to allow pathing over rails.

### Describe alternatives you've considered.

Allow pathfinding over rails for all mobs

**Comment by yannicklamprecht** [comment]
That's a mechanic change. Should be on a per mob basis.

1. Either a flag to only enable rails `shouldPathfindOverRails` or a set of NamespacedKeys for dynamic overrides. There are multiple cases where the Path is blocked.
2. This boolean or set needs to be persisted on entity
3. The patch needs a solution where the chained ternary hell doesn't conflict that much



EDIT: After looking into it again, it more time consuming than expected. It could be implemented with a config globally, but not per mob instance. The one method playing the major part is not a instance method and basing the mob through the whole tree is much more effort here.
