### ISSUE TITLE
Buried Treasure generation is unreliable

### ISSUE THREAD

**Issue by MiraculixxT** [PaperSpigot/Paper#6847]
### Expected behavior

As soon as a treasure map is looted from a shipwreck, it should lead to a treasure, in the best case to a new one.
The marked location on the map should be the location of a buried treasure

### Observed/Actual behavior

As soon as a treasure map is looted from a shipwreck, it only leads to buried treasure in some cases. Often there is nothing at all to be found in this position. A /locate command then indicates that a treasure should be about 100 blocks away, which can only be found from time to time (instead of the chest the sand fell down)

![image](https://user-images.githubusercontent.com/82050017/139529192-d6541c05-079c-45d0-9f34-e747c1580270.png)
![image](https://user-images.githubusercontent.com/82050017/139529199-e4eec439-abc3-4504-9260-15ebeaff9e07.png)

### Steps/models to reproduce

1. Generate a new World with Paper
2. Locate a Shipwreck with a navigation Lootchest
3. Fly to the marked spot on the Map and search the chest
(Repeate Step 2 and Step 3 one or two times, this bug doesn't always happen)
4. If the chest isnt there, locate it with /locate burried_treasure
5. Look again, if a chest is there

### Plugin and Datapack List

**Datapacks:** vanilla (built-in) + bukkit(world)
**Plugins:** ViaVersion 4.0.1 + ViaBackwards 4.0.1
(Tested it without ViaVersion and ViaBackwards later, same result)

### Paper version

This server is running Paper version git-Paper-353 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f2cb9cb)
You are running the latest version
Previous version: git-Paper-334 (MC: 1.17.1)

### Other

The new World generation is handelt with my own Plugin, wich delete all loaded worlds, after restarting and restart again, to prevent a Playerdata Save error

**Comment by e-im** [comment]
I haven't been able to reproduce this on a completely fresh server with default world, however, `seed-based-feature-search-loads-chunks` in paper.yml will cause this behaviour when set to false. When this is set to false, maps (or the /locate command) will only take you to where a structure could have possibly been generated, without checking if it actually was generated there. With this behaviour (it is a bit unclear with your reproduction, but I *think* this is what you are saying with step 4) if you do `/locate` again, or, get another map, it will now lead you to a different location.

If that is set to true and you are able to reproduce this on a fresh paper server with no changes, would you be able to try this with `seed-based-feature-search` set to `false` in paper.yml? I would do this however I haven't been able to reproduce this on a default server.

**Comment by MiraculixxT** [comment]
I just create a completly new Server with the latest Paper build and try to reproduce it. Amazingly, this bug has not occurred again. I then went to the config file to check these two settings and both were true.
That confused me, which is why I went to the config of the server on which the bug occurred. There `seed-based-feature-search` was true but `seed-based-feature-search-loads-chunks` was false.
After changing the value to true, the bug did not appear again. Perhaps in an old paper build it was still the case that the default value was false?
Anyways, its solved, thank you

**Comment by e-im** [comment]
Yes, that's correct. It was defaulted to false for a couple of builds when it was first introduced. Note that nothing was actually wrong with generation, just locating the structure. Because of this, all new maps will work as intended, bringing you to the correct location.

Thanks for following up with this.
