### ISSUE TITLE
Problems with anti-xray when enabled - CHUNK loaded too late.

### ISSUE THREAD

**Issue by Incluuu** [PaperSpigot/Paper#6852]
### Expected behavior

When I enable the anti-xray feature in the paper file, the chunks on the server are loaded too late.

### Observed/Actual behavior

Other owner with the same problem: 
https://gist.github.com/stonar96/ba18568bd91e5afd590e8038d14e245e#gistcomment-3899149

![2021-10-31_11 24 42](https://user-images.githubusercontent.com/67196311/139578409-f0ac4cf7-d215-4019-a2e1-0b76f8b0f8b2.png)
![2021-10-31_11 24 57](https://user-images.githubusercontent.com/67196311/139578410-57d808c2-1faa-4a30-8d81-799f29824040.png)
![2021-10-31_11 25 14](https://user-images.githubusercontent.com/67196311/139578411-abbd8ca8-85fd-4663-8854-77ffd02245a3.png)

### Steps/models to reproduce

1. You need at least 40-50 players on the server.
2. Turn on anti-xray:

world-settings:
  default:
    anti-xray:
      enabled: true
      engine-mode: 1
      chunk-edge-mode: 2
      max-chunk-section-index: 3
      max-block-height: 64
      update-radius: 2
      lava-obscures: false
      use-permission: false
      hidden-blocks:
      - chest
      - coal_ore
      - deepslate_coal_ore
      - copper_ore
      - deepslate_copper_ore
      - diamond_ore
      - deepslate_diamond_ore
      - emerald_ore
      - deepslate_emerald_ore
      - gold_ore
      - deepslate_gold_ore
      - iron_ore
      - deepslate_iron_ore
      - lapis_ore
      - deepslate_lapis_ore
      - redstone_ore
      - deepslate_redstone_ore
      replacement-blocks:
      - stone
      - oak_planks
      - deepslate

  world_nether:
    anti-xray:
      max-chunk-section-index: 7
      max-block-height: 128
      hidden-blocks:
      - air
      - ancient_debris
      - bone_block
      - glowstone
      - magma_block
      - nether_bricks
      - nether_gold_ore
      - nether_quartz_ore
      - polished_blackstone_bricks
      replacement-blocks:
      - basalt
      - blackstone
      - gravel
      - netherrack
      - soul_sand
      - soul_soil

### Plugin and Datapack List

I tested without plugins.

### Paper version

Paper 1.17.1 # 356

**Comment by kennytv** [comment]
Please use our Discord for further assistance and provide all the necessary information as suggested here https://gist.github.com/stonar96/ba18568bd91e5afd590e8038d14e245e#gistcomment-3942083. If we identify this actually being an issue, we will reopen this, but to get to that, the Discord is best, first.

**Comment by Xayanix** [comment]
I can confirm this issue.

**Comment by MiniDigger** [comment]
please open a new issue if you can reproduce this on latest 1.18.2 with more detail.
