### ISSUE TITLE
Add getCurrentTaskID for Bukkit scheduler

### ISSUE THREAD

**Issue by HexedHero** [PaperSpigot/Paper#6856]
### Is your feature request related to a problem?

Currently, there is no way to get this without making a new empty task and getting its ID.

### Describe the solution you'd like.

Add some API to the Bukkit scheduler so we can get the ID for the last scheduled task.

### Describe alternatives you've considered.

Making an empty scheduled task and getting its ID which is very yucky

**Comment by e-im** [comment]
Do you have a particular use case/need in mind for this api?

**Comment by HexedHero** [comment]
> Do you have a particular use case/need in mind for this api?

Personally, I use this to check how many tasks have been run on the server, making sure I don't reach the overflow.

**Comment by Owen1212055** [comment]
The overflow issue has since been resolved.

**Comment by e-im** [comment]
Yeah, this is way too niche api for an implementation detail that has been mitigated and should not exist.
