### ISSUE TITLE
Optimization to make powered rails 3x faster

### ISSUE THREAD

**Issue by FxMorin** [PaperSpigot/Paper#6858]
### Is your feature request related to a problem?

Powered rails in Minecraft are slow, including paper. So its time they go brrrr

### Describe the solution you'd like.

I am suggesting that Paper adds an optimization which I created <https://github.com/fxmorin/carpet-fixes/blob/1.18/src/main/java/carpetfixes/mixins/blockFixes/PoweredRailBlock_fasterMixin.java>

How its faster:
The algorithm is pretty simple. Instead of using block updates, we pre-calculate all flat rails & give updates in the right order. That's it. xD

### Describe alternatives you've considered.

Vanilla, it sucks

### Other

Which can optimize powered rails turning on & off by 3x
Vanilla:
![Vanilla](https://user-images.githubusercontent.com/28154542/139955465-d514fd2b-e8ae-4200-a551-4b831b8514b2.png)
Optimization:
![Optimization](https://user-images.githubusercontent.com/28154542/140524455-4985f0b0-cada-41f7-8f26-e010a3bdb5f2.png)
)

**Comment by electronicboy** [comment]
~~https://github.com/fxmorin/carpet-fixes/blob/1.18/src/main/java/carpetfixes/mixins/optimizations/PoweredRailBlock_fasterMixin.java - marking as approved to prevent this going stale, not 100% where this lines up in the quest of the rest of the todo list, however~~
