### ISSUE TITLE
Add option to disable "x/y players sleeping" message.

### ISSUE THREAD

**Issue by artur9010** [PaperSpigot/Paper#6863]
### Is your feature request related to a problem?

Minecraft 1.17 added new feature - it sends a message to all players when player goes to the bed. That function ignores vanished players and that ones in creative mode which leaks the number of online administrations on the server.

![obraz](https://user-images.githubusercontent.com/4835677/140162416-1bc5c511-588f-4c0e-914d-4a06c5f4e316.png)

### Describe the solution you'd like.

Add option in config or gamerule to disable that message.

### Describe alternatives you've considered.

Welp, there is no option built-in in game server to disable that.

**Comment by MiniDigger** [comment]
isn't the proper fix here to have your vanish plugin modify the count displayed here?

**Comment by lynxplay** [comment]
As discussed in #6864, this should most likely be implemented by

- [ ] Implementing a world-based configuration option to disable the `sleep.skipping_night` or `sleep.players_sleeping` messages respectively.
- [ ] Implementing an API event(s) that is/are called when the server attempts to send these messages that allow plugins to modify the resulting message. These events should still be called if the configuration option disabled the messages but would then be pre-cancelled.

**Comment by xIGBClutchIx** [comment]
Any updates on this? Would love to be able to disable them as currently using a plugin for sleeping.

**Comment by ryantheleach** [comment]
I see no purpose in exposing it as a config option, there is a cost to ever increasing config sizes in terms of usability.

The default message under paper should reflect whether the player is considered for sleeping using the [existing API](https://papermc.io/javadocs/paper/1.18/org/bukkit/entity/Player.html#isSleepingIgnored()), which would solve the issues surrounding vanish / creative.

**Any** message sent to the actionbar should generate an event, if it does not already do so.

**Comment by Owen1212055** [comment]
Is this still something that is wanted? My attempts at PRing anything didn't really go far, and this is such a hyper specific thing. If you ever really want to change it you can just use a resource pack...

**Comment by notTamion** [comment]
Perhaps a simple setSendActionRow (or better name) method could be added to the PlayerEnter/LeaveEvents so plugins can disable it and if required, handle action bars manually.
