### ISSUE TITLE
breakNaturally() with Containers

### ISSUE THREAD

**Issue by schantastic** [PaperSpigot/Paper#6874]
### Expected behavior

Hey, I recently found a Bug when using the Block#breakNaturally() function in combination with containers!
Normally the container should drop all his content when using this function, but with 1.17.1 only the chest gets dropped!

### Observed/Actual behavior

Now, when you are using the Block#breakNaturally() function, only the chest drops and all stuff in there is gone ;D

### Steps/models to reproduce

1. Place a Chest and put stuff in there!
2. Use the Block#breakNaturally() function to break it!
3. Only the Chest will drop!

### Plugin and Datapack List

Any Plugin which uses this function in combination with Containers :D

### Paper version

This server is running Paper version git-Paper-370 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 29bb5a9)
You are running the latest version

### Other

Thanks for looking into the Problem ;D

**Comment by NotMyFault** [comment]
See https://github.com/PaperMC/Paper/pull/6854 for a Paper wip solution.

For the record: https://hub.spigotmc.org/jira/browse/SPIGOT-5751, https://hub.spigotmc.org/jira/browse/SPIGOT-6778 for upstream reports.
