### ISSUE TITLE
Thread dump

### ISSUE THREAD

**Issue by WindupYT** [PaperSpigot/Paper#6878]
### Stack trace

https://paste.gg/p/anonymous/414ce9cf6de946a4a72711125acbb95c

### Plugin and Datapack List

 AdvancedBan, BackOnDeath, BetterRTP, BuycraftX, ClearAll*, CoreProtect, DiscordSRV, EasyKits, Essentials, HealthPerKill*, HolographicDisplays, LPC, LuckPerms, nLogin, NoPortals*, OpenInv, ServersNPC, SkinsRestorer, StatsSB, TitleManager, ViaBackwards, ViaVersion, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldSpawn*

### Paper version

git-Paper-353 (MC: 1.17.1)

**Comment by electronicboy** [comment]
Your jvm is overloaded, please use the discord/irc for support
