### ISSUE TITLE
fast crafting and speed crafting not working correctly/at all

### ISSUE THREAD

**Issue by iSeitan** [PaperSpigot/Paper#6883]
### Expected behavior

when using shift click, holding the mouse button when stacking item in the crafting table, etc the system doesnt work
i have a video wich can show what i mean

### Observed/Actual behavior

the crafting system not working correctly

### Steps/models to reproduce

useing purpur 1423 1.17.1 just try to fast craft

### Plugin and Datapack List

ActionHealth, AdvancedChests, AngelChest, ArmedArmorStands, AureliumSkills, AutoMessage, AutoShulker, BattlePass, BetterTridents, Bookshelf, BuildersWand, BungeeGuard, BuycraftX, ChatBrawl, ChatInjector, ChestSort, Chunky, Citizens, CMILib, CoreProtect, DeluxeMenus, DiscordSRV, DisplayShops, dynmap, eco, EcoArmor, EcoBosses, EcoEnchants, EcoEnchantsGUI, EcoItems, EpicCraftingsPlus, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, FeatherBoard, GHolo, GSit, HackedCore*, HackedServer*, HeadDatabase, HeadsPlus, HoloMobHealth, HoloRemove*, InteractionVisualizer, InteractiveChat, InventoryRollbackPlus, InvUnload, Iris, JakesRTP, Jobs, KeepChunks, LagAssist, Lands, LibsDisguises, LoginStreak, LuckPerms, MeteoritesPro, Multiverse-Core, Multiverse-Portals, MVdWPlaceholderAPI*, MyCommand, MythicMobs, NetheriteShield, NexEngine, OpenInv*, PinPrompt, PL-Hide-Pro, PlaceholderAPI, Plan, PlayerProfiles, Playtimes*, ProtocolLib, PvPManager, Rankup, RealisticSeasons, RHLeafDecay, RPGHorses, SafariNet, SirBlobmanCore (SirBlobmanAPI, XSeries), spark, SSX-Connector*, Stratos, StratosNG, StreamingDrops, TAB, Talismans, TimeIsMoney, TradeSystem, Tweakin, UnenchanterRedux, Vault, Votifier, VotingPlugin, Wardrobe, WitherSound*, WorldEdit, WorldGuard, WorldGuardExtraFlags, zAuctionHouseV3

### Paper version

This server is running Purpur version git-Purpur-1423 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6cbba00 on ver/1.17.1)

### Other

https://user-images.githubusercontent.com/86061857/141319672-2b14485e-687c-4a7b-b21f-5b7d29fc19c0.mp4

**Comment by e-im** [comment]
1. This is the paper issue tracker
2. I can't reproduce this, please try without plugins on paper.
