### ISSUE TITLE
Crash while loading world

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#6884]
### Stack trace

https://paste.gg/p/anonymous/82532bfe65ac438da3364f6cd9ab4047

### Plugin and Datapack List

in crash

### Actions to reproduce (if known)

World load, but it was sync via Bukkit.getScheduler().runTask()

### Paper version

git-Paper-378 (MC: 1.17.1)

**Comment by lynxplay** [comment]
Can you please share a reproducible setup for this ?
I have attempted to recreate this issue locally (with an example setup like [this](https://pastebin.com/bB5NacCy)) and was not able to produce your pasted issue.

While this crash is to be expected when loading/unloading a world while the server is ticking the worlds (e.g. the redstone update logic I used in my example setup), the scheduler is ticked before the worlds hence your usage of it should properly prevent any concurrent modification exception.

**Comment by e-im** [comment]
Closing as cannot reproduce, leave a comment if you have been able to.
