### ISSUE TITLE
`Entity` does not implement `Sound.Emitter`

### ISSUE THREAD

**Issue by kezz** [PaperSpigot/Paper#6887]
### Expected behavior

For `Entity` to implement `Sound.Emitter`.

### Observed/Actual behavior

As seen in the Adventure patch, the `playSound` method with an emitter checks for entities, but `Entity` does not actually implement `Sound.Emitter`, meaning the method does not actually work when provided with an entity, instead throwing an exception.

### Steps/models to reproduce

N/A

### Plugin and Datapack List

N/A

### Paper version

N/A

**Comment by lynxplay** [comment]
For anyone giving this a shot, the [Emitter](https://jd.adventure.kyori.net/api/4.9.3/net/kyori/adventure/sound/Sound.Emitter.html) interface is purely used as a marker interface as of right now.

The server side of things is already implemented [here](https://github.com/PaperMC/Paper/blob/master/patches/server/0011-Adventure.patch#L2683), so a simple addition to the [adventure patch](https://github.com/PaperMC/Paper/blob/master/patches/api/0007-Adventure.patch) that updates the [Entity](https://papermc.io/javadocs/paper/1.17/org/bukkit/entity/Entity.html) interface to extend the [Emitter](https://jd.adventure.kyori.net/api/4.9.3/net/kyori/adventure/sound/Sound.Emitter.html) interface is enough to close this issue :+1:
