### ISSUE TITLE
Server crash related to an entity (player)

### ISSUE THREAD

**Issue by ricardormmx** [PaperSpigot/Paper#6893]
### Stack trace

https://paste.gg/p/anonymous/1a80f5f8cc564a30b6b8be0ed1069ce0

### Plugin and Datapack List

Plugins: BookDuplicationFix*, BuycraftX, ClearLag, Combate, eZProtector, HolographicDisplays, Horarios, IllegalStack, LiteBans, LuckPerms, PlaceholderAPI, PremiumVanish, ProtocolLib, ShopProtect, SkinsRestorer, Vault, WorldEdit, WorldGuard, ZottiClans, ZottiComandos, ZottiCrates, ZottiData, ZottiEconomy, ZottiEssentials, ZottiHalloween, ZottiKits, ZottiOptimizer, ZottiProtector, ZottiTab, ZottiTabList

Datapacks: none

### Paper version

This server is running Paper version git-Paper-377 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 3f17694)

### Other

This server is used as spawn. There is no nether or end world. It is a place of 600 x 600 blocks delimited by a border (world border). 
For a few months we have been dealing with this problem, we already tried to change the host, reset the player data, but the problem persists.
There are two other servers with the same setup, this is the only one with the problem.
We know what OutOfMemory means, but if you check the log you will see that a few seconds before the crash, only 4 of 19GB are being used. Is there a memory leak?
If you can see something that we are not considering, we would appreciate it if you share it with us. 
Cheers!

**Comment by e-im** [comment]
Thanks for the report-- would you mind attaching your spigot.yml? Thanks

**Comment by ricardormmx** [comment]
Sure. This is the file https://paste.gg/p/anonymous/8f632879e4c3465f8d0b2be9c76b7920

**Comment by e-im** [comment]
Looks like you've disabled the movement check by setting `moved-too-quickly-multiplier` to a couple thousand. That will allow people to cause this. Setting that back to default or something close will resolve the issue.

**Comment by ricardormmx** [comment]
I will try, thank you so much for your help

**Comment by e-im** [comment]
Leave a comment if you're still experiencing this with that changed, but setting a lower threshold should resolve this issue.
