### ISSUE TITLE
Memory Problem for servers

### ISSUE THREAD

**Issue by JdogOfficial** [PaperSpigot/Paper#6894]
### Timings or Profile link

https://timings.aikar.co/?id=44300b472b894daba068a32591550cef

### Description of issue

The newest paper jar for servers is producing a 100% memory for all servers even if they havent even had 1 block placed. Just instantly 100%

### Plugin and Datapack List

none

### Server config files

```
Paste configs or paste.gg link here!
```
Standard config for start up

### Paper version

This server is running Paper version git-Paper-381 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: db0bff9)

### Other

This is for our server hosting and instantly we had huge number of customers complain that their servers are lagging and that the memory is at 100% for all the servers, so we tested it and infact it was. with a brand new world its still showing 100%

**Comment by aurorasmiles** [comment]
If you don't know what the Xms flag does I very very very very much hope you don't run an actual hosting company.
Read up on https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/ and other information pages.

**Comment by JdogOfficial** [comment]
I dont run a hosting company myself I work for one. So I'm reporting the problem. Thanks for the info, no need to make assumptions buddy.

**Comment by Proximyst** [comment]
> I dont run a hosting company myself I work for one. So I'm reporting the problem. Thanks for the info, no need to make assumptions buddy.

We develop software, we're not a search engine. No need to make assumptions, buddy.
