### ISSUE TITLE
Add PlayerSpawnEntityEvent

### ISSUE THREAD

**Issue by aerulion** [PaperSpigot/Paper#6898]
### Is your feature request related to a problem?

I'm trying to modify the entities which can be spawned by players, according to certain player bound criteria, for example some nbt data of the item that was used to spawn the entity, or the level of the player.

### Describe the solution you'd like.

A generic event which covers all the entities that can be spawned by a player using an item. More specifically:
- All SpawnEggs
- Both ItemFrame variants
- All fish buckets
- Axolotl Bucket
- Armorstand
- Painting

I would also find the following methods very useful:
- getItemStack() → The ItemStack used to spawn the entity
- getEntity() → The Entity being spawned
- getPlayer() → The Player who spawned the entity
- getSpawnReason() → The SpawnReason, to more easily differentiate without necessarily checking the itemstack

### Describe alternatives you've considered.

Listening to the player interact event, and either cancelling it, and spawning the entity myself, or trying to match it to the next entity spawn event. Both ways aren't ideal in my opinion.

**Comment by Doc94** [comment]
Maybe is related to #6487 (?
but this only include a few cases...

**Comment by aerulion** [comment]
I guess they are somewhat related, but in my personal use case I would primarily check the item being used to spawn the mob, which in the case of mobs that need to be summoned via 'structures' could only be the last item used to complete the structure since all other blocks are already placed down. That wouldn't be as useful when implementing custom mob spawning mechanics, since it would only require the last item to be the 'custom' one in order to spawn the mob. But generally speaking, it would still be very useful to obtain the player who spawned the mob.

**Comment by reflqct** [comment]
Working on this

**Comment by aerulion** [comment]
> Working on this

Are you still working on this?
