### ISSUE TITLE
Add Player#setSaveData

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#6902]
### Is your feature request related to a problem?

We have a combined lobby+survival server, and currently, if player joined for the first time and then disconnects while in the lobby, their data, advancements and stats files will be deleted after some time in PlayerQuitEvent.

### Describe the solution you'd like.

I think that this isn't a not the safest and most beautiful way, so something like Player#setSaveData(boolean) will be better.

### Describe alternatives you've considered.

Create another proxy-server and disable data saving on it, maybe, or just leave everything as is.

**Comment by kennytv** [comment]
spigot.yml `players.disable-saving` and `stats.disable-saving`?

**Comment by molor** [comment]
> spigot.yml `players.disable-saving` and `stats.disable-saving`?

> We have a combined lobby+survival server, and currently, if player joined for the first time and then disconnects while in the lobby, their data, advancements and stats files will be deleted after some time in PlayerQuitEvent.

I don't need to disable saving for everyone without exception. Only for players that disconnected in some location. All this happens on one server and in same world.

**Comment by molor** [comment]
Example usage:

```java
@EventHandler (priority = EventPriority.MONITOR)
public void playerJoinEvent(PlayerJoinEvent event) {
	if (!event.getPlayer().hasPlayerdBefore()) {
		event.getPlayer().setSaveData(false);
	}
}

@EventHandler (priority = EventPriority.MONITOR)
public void lobbyLeaveEvent(PlayerTeleportEvent event) {
	if (!event.getPlayer().getSaveData() && !isInsideLobbyRegion(event.getTo())) {
		event.getPlayer().setSaveData(true);
	}
}
```

In that case, everyone who don't leave our lobby/welcome room on spawn before disconnection, will not be saved and every time will connect like a new player — this is exact what we needs. Thanks!

**Comment by drunderscore** [comment]
Why not just `PlayerSaveDataEvent` which is cancelable?

**Comment by molor** [comment]
I think that it's more easy to add just one boolean flag into the Player class and just don't call the save method instead of creating new event

**Comment by Machine-Maker** [comment]
I actually think the event is better here. Makes controlling when to save player data more manageable by the plugin. Not sure of the logic, but I'm in favor of an event over a boolean.

**Comment by Owen1212055** [comment]
Use ``Player#setPersistent(false)``
![image](https://user-images.githubusercontent.com/23108066/148292186-1236716d-f01e-4bbc-adb2-d86d70ee4d18.png)
