### ISSUE TITLE
spawning entitys in teams doesn't work

### ISSUE THREAD

**Issue by Shiagur** [PaperSpigot/Paper#6905]
### Expected behavior

You have a team already created, for example, a team called rabbit which hides the floating names.
You summon a rabbit and it appears and has no name floating above its head like it does in vanilla, because it spawned already in the team, without needing the /team join command.

### Observed/Actual behavior

The rabbit spawns with a name floating above its head and is not inside the team and has to be manually added.
The console gives out in yellow text:
"Unable to add mob to team "rabbit" (that team probably doesn't exist)"

### Steps/models to reproduce

You create a team: "/team add rabbit" and modify the name display: "/team modify rabbit nametagVisibility never"
Then you summon the rabbit: "/summon minecraft:rabbit ~ ~ ~ {RabbitType:99,Team:rabbit}"
OR
You place a mob spawner: "/setblock ~ ~ ~ minecraft:spawner{SpawnData: {RabbitType: 99, id: "minecraft:rabbit", Team: "rabbit"}, MaxNearbyEntities: 30s, MinSpawnDelay: 60s, id: "minecraft:mob_spawner", SpawnRange: 4s, MaxSpawnDelay: 100s, RequiredPlayerRange: 15s, SpawnCount: 5s, SpawnPotentials: [{Weight: 1, Entity: {Team: "rabbit", id: "minecraft:rabbit", RabbitType: 99}}], Delay: 43s}"

### Plugin and Datapack List

Plugins (0): 
There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]

### Paper version

This server is running Paper version git-Paper-386 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: e22a1a9)\nYou are running the latest version\nPrevious version: git-Paper-373 (MC: 1.17.1)

**Comment by electronicboy** [comment]
Have you tried the option in paper.yml to allow entities to be teamed?

**Comment by Shiagur** [comment]
The only setting related to teams I found in any of the setting files was save-empty-scoreboard-teams.
I didn't find anything else, so if it has to be added manually and doesn't get generated automatically, then I don't know about this setting.
Also, adding entities with the team command works as expected.

**Comment by e-im** [comment]
Enabling `allow-non-player-entities-on-scoreboards` will make this work as intended, although, perhaps the docs/default for that could be re-evaluated depending on how frequently this is used in datapacks or such.
