### ISSUE TITLE
Datapack causes  error Non [a-z0-9/._-] character

### ISSUE THREAD

**Issue by lynrayy** [PaperSpigot/Paper#6908]
### Expected behavior

Datapack nicely works in singleplayer world on the same (1.17.1) version

### Observed/Actual behavior

[time ERROR]: Non [a-z0-9/._-] character in path of location: minecraft:recipes/MystiCat/bell.json

### Steps/models to reproduce

I have capital letters in recipe key and pattern:

```
{
  "type": "minecraft:crafting_shaped",
  "pattern": [
    "SSS",
    " G ",
    "GNG"
  ],
  "key": {
    "s": {
      "item": "minecraft:stick"
    },
    "G": {
      "item": "minecraft:gold_ingot"
    },
    "N": {
      "item": "minecraft:gold_nugget"
    }
  },
  "result": {
    "item": "minecraft:bell"
  }
}
```

### Plugin and Datapack List

Custom datapack

### Paper version

This server is running Paper version git-Paper-386 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: e22a1a9)
You are running the latest version
Previous version: git-Patina-ver/1.16.5-"cb4db52" (MC: 1.16.5)

### Other

Paper should support capitalized letters in datapack recipes

**Comment by electronicboy** [comment]
The fact that vanilla allows that is just wrong, I'd be interested to see how the vanilla server handles that but that is infact a violation of the spec so the error is not exactly wrong

**Comment by lynrayy** [comment]
At least two external vanilla datapacks fail to launch due to capital letters in them. This is very dumb that it will not work on paper. I should open each file and manually change capital letters to uppercase letters? This is funny

**Comment by electronicboy** [comment]
If they're invalid vanilla shouldn't be loading them, we can consider making this on par with vanilla (We'd need to see where the error is actually coming from) but that is infact a violation of the spec and should be reported to the datapack authors too

**Comment by lynrayy** [comment]
Okay, I understand what the mistake is. The error is not in capitalized variables, but because the path contains capital letters. Fixed this and datapack now works. (it's stupid anyway because it's ok to use capitalized letters in vanilla)

**Comment by kashike** [comment]
The invalid part here is the *path*: `minecraft:recipes/MystiCat/bell.json` - `MystiCat` should be `mysticat`.

**Comment by lynrayy** [comment]
Thanks (I've already fixed that).
I still think paper should support capital letters in the path, just like vanilla.
