### ISSUE TITLE
Bugged GUIs

### ISSUE THREAD

**Issue by FrancyMak** [PaperSpigot/Paper#6910]
### Expected behavior

When GUIs are used, items should not buggy so frequently, in 1.17 every time you click a gui, the item stays in your hand.

### Observed/Actual behavior

When you click on an object in the gui, you have the option of moving it to your inventory and, in rare cases, using it.

### Steps/models to reproduce

L'ho evidenziato con:
Quests (https://www.spigotmc.org/resources/quests-1-8-1-17-set-up-goals-for-players.23696/)
BeautyQuests  (https://www.spigotmc.org/resources/beautyquests.39255/)
DeluxeMenus (https://ci.extendedclip.com/job/DeluxeMenus/119/)

https://streamable.com/nz5hvp

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/75610581/142717024-96d5c512-ab7b-440c-a4e5-8e77044719a4.png)

### Paper version

This server is running Paper version git-Paper-386 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: e22a1a9)
You are running the latest version

**Comment by electronicboy** [comment]
This is 100% up to plugins to handle properly, there's been many cases of plugins breaking the GUIs of other plugins, and many instances of plugins not handling various events in the server properly

If you can confirm that this is infact a paper issue, i.e. using a minimal test case, feel free to create a new issue, but, this seems out of the bounds of paper itself
