### ISSUE TITLE
Add option to disconnect all players on stopping before disabling plugins

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#6911]
### Is your feature request related to a problem?

Partially. Every time after I stop the server, all connected players was just freezes for 3-10 seconds and can't open chests, place blocks (they can place blocks on client side, but server just ignores this during shutdown), use bow etc.

### Describe the solution you'd like.

I think that this problem can solved if we have setting like `disconnect-everyone-before-shutdown`, which defaults to `false` to keep initial behavior, so any plugin can handle PlayerQuitEvent before it was disabled, and players don't need to wait and asking us a question like "it's my network lag or server crashed?!".

Also it's would be nice if the `stop` command had the ability to specify the reason why the server was stopped instead of using default bukkit's `shutdown-message`

### Describe alternatives you've considered.

Maybe this can be solved by plugin that overrides `stop` command and kicks everyone before calling Server#shutdown(), but I don't know is this possible and will Paper CTLR+C handler support it..

**Comment by olijeffers0n** [comment]
Hmm, I'm not sure im a fan of this as i feel some plugins may (ab)use the fact that when their onDisable method is called they can then get all online players and deal with any data accordingly. However i see what you mean about just using the PlayerQuitEvent.

**Comment by molor** [comment]
I think that if plugin works with player data, they save this data anyway: 1) after player quit, or 2) on disable if it uses cache, so it is unlikely that any data loss can occur here. Also we sometimes use the custom `kickall` command before shutdown, and this works without problems

**Comment by electronicboy** [comment]
kick all command is co-ordinated and not ran in the same tick as the server falling apart generally, an option can be added given that there is a good reason for this, but, dragons beware... :/
