### ISSUE TITLE
Sudden rise of TPS and server crash without any trace in logs

### ISSUE THREAD

**Issue by TyskiRycerz** [PaperSpigot/Paper#6919]
### Timings or Profile link

https://timings.aikar.co/?id=d43759ea6f8249f6817f059df75b764e

### Description of issue

I have not big (~10/15 players) survival server since october. Firstly, I was using hosting as server host, but after some time we encountered problems with sudden lags, tps dropping below 5 and then server crash. I moved to VPS but it didn't help, it still happens. I don't have any idea what could wrong :v Crashes are taking place once for like 3 hours when there are 10+ players on server. None of them are making lags with redstone mechanisms etc., it is just something from server

### Plugin and Datapack List

 Plugins (62): AAC5, AdvancedPortals, AngelChest, ArmoredElytra, ATopPlayers, BanItem, BeastTokens, ChestShop, ChestSort, Chunky, Citizens, CMILib, ColoredSigns, CombatLogX, CommandPanels, CoreProtect, CrateReloaded, CrazyEnchantments, EasyClearChat*, Essentials, EssentialsChat, EssentialsSpawn, eZProtector, FastAsyncWorldEdit (WorldEdit), GSit, HolographicDisplays, InfoBoardReborn*, Jobs, JoinText*, LuckPerms, MessageAnnouncer, Multiverse-Core, Multiverse-Portals, MVdWPlaceholderAPI*, PlaceholderAPI, PlayerWarps, PlayTime*, ProtectionStones, ProtocolLib, Quests, RandomTeleport, ServerMarket, ShopGUIPlus, SimpleRename, SirBlobmanCore (SirBlobmanAPI, XSeries), SkinsRestorer, SklepMC*, Skript, spark, SSX-Connector*, StaffChat, SuggestionBlocker, SuperVanish, TabList, TimeVote, TradeMe, UltimateTimber, Vault, VoidGen, VoxelSniper, WeatherVote, WorldGuard

There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]

### Server config files

```
server.properties: https://paste.gg/p/anonymous/3a2dc492cccb448fad4563c564b660e3
bukkit.yml: https://paste.gg/p/anonymous/b021310f91504c0186118664b25dfd71
spigot.yml: https://paste.gg/p/anonymous/cbe77b21299b40fcbff3843b635ddaae
paper.yml: https://paste.gg/p/anonymous/560f1198b46241159b8a6f0816bed455
```

### Paper version

Checking version, please wait...
[19:59:14 INFO]: This server is running Paper version git-Paper-790 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Tuinity-"935b901" (MC: 1.16.5)

**Comment by Chew** [comment]
1.16.5 is unsupported at this time. Please reproduce on the latest 1.17.1 build. Thank you!
