### ISSUE TITLE
Ender pearls not despawning upon owner death if lazy loaded

### ISSUE THREAD

**Issue by azzy-xyz** [PaperSpigot/Paper#6920]
### Expected behavior

If an ender pearl is in a non entity processing chunk, it should either forget the owner as if it's unloaded, or despawn upon the owner dying as if it's loaded.

### Observed/Actual behavior

When an ender pearl is in a non entity processing chunk and the owner dies, it doesn't despawn. It can still be used to teleport a player after the owner has died.

### Steps/models to reproduce

Build portal loader, place stasis chamber in the lazy loaded border around it, go far away to unload the chunks and die, go back and load the chunks, stasis chamber still works.

### Plugin and Datapack List

FastAsyncWorldEdit (WorldEdit)

### Paper version

This server is running Paper version git-Paper-388 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 22aaf91)
You are running the latest version
Previous version: git-Paper-386 (MC: 1.17.1)

**Comment by reflqct** [comment]
(edit: nvm this, i just saw the "lazy loaded" in title. this might still apply, but my apologies if it doesnt.)

After a quick glance at the code, it seems to be pre-implemented. There is a statement specifying that if the owner is dead the enderpearl will "discard", is this an issue on your end?
<img width="1223" alt="Screen Shot 2021-11-21 at 6 26 34 PM" src="https://user-images.githubusercontent.com/81465414/142750864-7291ec71-aa01-4960-b659-937b6e6ad8b0.png">
