### ISSUE TITLE
How about adding a Player#isFalling()

### ISSUE THREAD

**Issue by arkozy** [PaperSpigot/Paper#6921]
### Is your feature request related to a problem?

There is no built-in method to check if a player is falling.

### Describe the solution you'd like.

```
@EventHandler
public void onMove(PlayerMoveEvent e) {
   Player player = e.getPlayer();
    if(player.isFalling()) {
         player.sendMessage("You are falling!!!");
    }
}
```

The method should be fired when a player is falling from a 4 (or greater) block tall structure and should not be fired when the player is just jumping.

### Describe alternatives you've considered.

I've tried ```player.getVelocity().getY() < 0.0D``` but it also includes player's jump so this is not pretty good opinion for me

**Comment by Shevchik** [comment]
Player#getFallDistance exists

**Comment by reflqct** [comment]
^^ I think this feature isn't needed lots, just using `if (p.getFallDistance() > 0)` will work.

**Comment by MiniDigger** [comment]
as said by others this is covered already, but thanks for the suggestion!
