### ISSUE TITLE
player respawn

### ISSUE THREAD

**Issue by Obeeyyyy** [PaperSpigot/Paper#6923]
### Is your feature request related to a problem?

I want to respawn the player after death.
normaly you could do player.spigot().respawn() but using the paper api there is no .spigot() method for me.

Api Version: 1.17.1-R0.1-SNAPSHOT

### Describe the solution you'd like.

add the spigot() method

### Describe alternatives you've considered.

sending a packet

**Comment by electronicboy** [comment]
paper is a fork of spigot and thus that method 100% exists
Check your dependencies to ensure that bukkit isn't being pulled onto the classpath
