### ISSUE TITLE
Add Material#isDamageable()

### ISSUE THREAD

**Issue by reflqct** [PaperSpigot/Paper#6925]
### Is your feature request related to a problem?

Yes! I was trying to fix an issue for Paper and needed to find out whether a Material was damageable.

### Describe the solution you'd like.

I want a method that detects whether a Material is damageable.

### Describe alternatives you've considered.

Doing a very long if statement and going into ItemMeta. Neither of these seemed to work.

**Comment by Owen1212055** [comment]
How exactly did you check using item meta? You should be able to do a simple instanceof Damageable check on the item meta instance to see if it can be damaged.

**Comment by reflqct** [comment]
Ahh, I forgot there was a `instanceof` check silly me
