### ISSUE TITLE
Scoreboard rule "collisionRule" is not working between non-player entities

### ISSUE THREAD

**Issue by Siro256** [PaperSpigot/Paper#6928]
### Expected behavior

When collisionRule is never, all entities don't collide with each other.

### Observed/Actual behavior

Even though the collisionRule is never, non-player entities collide with each other.
(No collision occured between player and non-player entities.)

### Steps/models to reproduce

1. Create team
2. Set collisionRule to never
3. Spawn multiple entities
4. Add entities to team

### Plugin and Datapack List

Nothing

### Paper version

> version
[01:23:18 INFO]: Checking version, please wait...
[01:23:18 INFO]: This server is running Paper version git-Paper-388 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 22aaf91)
You are running the latest version

### Other

Reference video: https://www.youtube.com/watch?v=5XQ5ss0BO04

**Comment by NoahvdAa** [comment]
Do you have [allow-non-player-entities-on-scoreboards](https://paper.readthedocs.io/en/latest/server/configuration.html#allow-non-player-entities-on-scoreboards) set to true in paper.yml?

**Comment by Siro256** [comment]
> Do you have [allow-non-player-entities-on-scoreboards](https://paper.readthedocs.io/en/latest/server/configuration.html#allow-non-player-entities-on-scoreboards) set to true in paper.yml?

Oh, I missed that...I set to true and it worked. Thank you!
