### ISSUE TITLE
Item#setCanMobPickup isn't saved between chunk loads

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#6929]
### Is your feature request related to a problem?

We are using a plugin that adds money as items, and it works fine. These items may exist for months and even years, unlike normal items. On item creating, we call `Item#setCanMobPickup` with `false` on it, for example, to prevent zombies from picking it up. This solution works fine... until chunk was reloaded. After this, any mob can pick it up it and destroy with himself.

### Describe the solution you'd like.

I think that `Item#setCanMobPickup` need to be saved persistently inside item entity NBT data, to solve any problems like this one

### Describe alternatives you've considered.

Currently I'm listening to EntitiesLoadEvent, iterate over entity list and use setCanMobPickup(false) on needed entities again

**Comment by Machine-Maker** [comment]
Idk if this is a bug or a feature request. The original implementation of this never added methods for saving that value between "loads" of the item entity.

**Comment by molor** [comment]
> The original implementation of this never added methods for saving that value between "loads" of the item entity

I don't know about this, in that case it's a FR.
Currently I'm need to listen `EntitiesLoadEvent`, iterate over entity list and use `setCanMobPickup(false)` on needed entities again..

**Comment by lynxplay** [comment]
Yea, could you outline the feature request in a proper feature issue ?
I can also do so, but you may have some more motivation to add to it :+1:

**Comment by Owen1212055** [comment]
Because there wasn't much progress with the PR made for this issue, and because that this in the end causes a behavior change for api that has been around for a while I will be closing this issue.

I personally don't see an issue with just serializing these values yourself if you really need, however if this is something other people want feel free to comment on this issue and it can be reopened.

Thank you 😄
