### ISSUE TITLE
Items don't merge and don't despawn in non-ticking view distance chunks.

### ISSUE THREAD

**Issue by atuna2** [PaperSpigot/Paper#6934]
### Expected behavior

Dropped items should merge.
Dropped items should despawn.
Redstone mechanisms should not work in non-ticking chunks.

### Observed/Actual behavior

Dropped items don't despawn in non-ticking chunks
Dropped items don't merge in non-ticking chunks 
Redstone mechanisms is continue working in non-ticking chunks

Today I saw 147093 dropped carpets on my server. 
Because merge and despawn does not work in non-ticking view distance. 

### Steps/models to reproduce

I recorded a short videos, the mechanism dropping items to the ground.
If the player is nearby(video 1), the items is merge. In one minute, 164 objects were thrown to the ground. There are no problems here.
But if the player steps back 4 chunks into the zone of non-ticking chunks(video 2), the items do not merge and do not despawn. In one minute, 7,500 objects was dropped to the ground. 

video 1: https://youtu.be/sA6NaLha_VM
video 2: https://youtu.be/BNeGiO7PWTk

### Plugin and Datapack List

No plugins

### Paper version

Paper version git-Paper-388 (MC: 1.17.1)

### Other

Settings: 

server.properties
view-distance=3

Paper.yml
viewdistances:
no-tick-view-distance: 5

**Comment by electronicboy** [comment]
er.... I mean, duh?
They're not ticking, how do you expect them to do stuff?

**Comment by PaulBGD** [comment]
I've ran into this before, you can cause a lot of lag just by throwing items into non-ticking chunks that never despawn. It can lead to heavy lagspikes and insane memory use, might be worth looking into.

**Comment by atuna2** [comment]
@electronicboy But the redstone mechanism continues to work in non ticking. This is it OK? 
Have you watched the second video? NO.

**Comment by electronicboy** [comment]
redstone working is 100% expected given how redstone works, I don't think that there is much interest to add a few dozen "are we at a ticking level" checks all over redstone

**Comment by atuna2** [comment]
What about 7,500 ticking entities in non-ticking chunks? Is that ok too?

**Comment by electronicboy** [comment]
Stuff existing into non-ticking chunks is a non trivial issue, fixing this would be nice but best solution I have would be to just hard-enforce entity limits inside of chunks; There is a vanilla issue for that one, but, this issue report is flawed given the expectation that stuff will tick when it shouldn't

only caveat here is redstone which doesn't generally care, but, is somewhat of a non issue afaik

**Comment by atuna2** [comment]
I don't expect items will ticking. But it's ticking, in non-ticking chunks. I guess It's not ok.
https://youtu.be/BNeGiO7PWTk?t=112

**Comment by atuna2** [comment]
[22:40:14] [Render thread/INFO]: [CHAT] Total Ticking: 1360, Total Non-Ticking: 75
[22:40:14] [Render thread/INFO]: [CHAT]   1201 (0) : minecraft:item
[22:40:14] [Render thread/INFO]: [CHAT] * First number is ticking entities, second number is non-ticking entities
[22:43:59] [Render thread/INFO]: [CHAT] Server tick times (avg/min/max) from last 5s, 10s, 1m:
[22:43:59] [Render thread/INFO]: [CHAT] ? 18,2/8,1/95,6, 15,5/7,4/95,6, 12,2/5,6/95,6

[23:10:29] [Render thread/INFO]: [CHAT] Server tick times (avg/min/max) from last 5s, 10s, 1m:
[23:10:29] [Render thread/INFO]: [CHAT] ? 67,8/39,9/94,2, 68,0/39,7/97,1, 71,9/38,5/141,4
[23:10:34] [Render thread/INFO]: [CHAT] Total Ticking: 153926, Total Non-Ticking: 77
[23:10:34] [Render thread/INFO]: [CHAT]   153771 (0) : minecraft:item


https://timings.aikar.co/?id=b1a60c1e8698499f84d475ab105add14

**Comment by electronicboy** [comment]
if the entities are showing up as ticking, then they're in chunks in which are marked as ticking

**Comment by atuna2** [comment]
But why it don't despawn and merge?
