### ISSUE TITLE
Sudden rise of TPS and server crash without any trace in logs

### ISSUE THREAD

**Issue by TyskiRycerz** [PaperSpigot/Paper#6939]
### Timings or Profile link

https://timings.aikar.co/?id=6f69b6cf5b7b4a69b7075754bbf30ef3

### Description of issue

I have not big (~10/15 players) survival server since october. Firstly, I was using hosting as server host, but after some time we encountered problems with sudden lags, tps dropping below 5 and then server crash. I moved to VPS but it didn't help, it still happens. I don't have any idea what could wrong :v Crashes are taking place once for like 3 hours when there are 10+ players on server. I updated everything on 1.17 but it didn't really do anything

### Plugin and Datapack List

Plugins (62): AAC5, AdvancedPortals, AngelChest, AnnouncerPlus, ArmoredElytra, ATopPlayers, BanItem, BeastTokens, ChestShop, ChestSort, Chunky, Citizens, CMILib, ColoredSigns, CombatLogX, CommandPanels, CoreProtect, CrateReloaded, CrazyEnchantments, EasyClearChat*, Essentials, EssentialsChat, EssentialsSpawn, eZProtector, GSit, HolographicDisplays, InfoBoardReborn*, Jobs, LuckPerms, Multiverse-Core, MVdWPlaceholderAPI*, PlaceholderAPI, PlayerWarps, PlayTime*, ProtectionStones, ProtocolLib, Quests, RandomTeleport, ServerMarket, ShopGUIPlus, SimpleRename, SirBlobmanCore (SirBlobmanAPI, XSeries), SkinsRestorer, SklepMC*, Skript, spark, SSX-Connector*, StaffChat, SuggestionBlocker, SuperVanish, TabList, TimeVote, TradeMe, UltimateTimber, Vault, ViaBackwards, ViaVersion, VoidGen, VoxelSniper, WeatherVote, WorldEdit, WorldGuard

### Server config files

```
server.properties: https://paste.gg/p/anonymous/331d59441f5840cd8dd3d6cd348ac677
bukkit.yml: https://paste.gg/p/anonymous/2160510910cc4563bd8b374fa5a3e0f6
spigot.yml: https://paste.gg/p/anonymous/e0646d254fb24f9a8cb9d68d9f118cb6
paper.yml: https://paste.gg/p/anonymous/e1f40125656748e2b130565ac18fc479
```

### Paper version

[16:09:07 INFO]: Checking version, please wait...
[16:09:08 INFO]: This server is running Paper version git-Paper-388 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 22aaf91)
You are running the latest version

**Comment by electronicboy** [comment]
Issue tracker is for reporting bugs/issues, for support, please use the discord/forums/IRC
