### ISSUE TITLE
Zombified Piglin door-breaking-difficulty

### ISSUE THREAD

**Issue by irwell** [PaperSpigot/Paper#6942]
### Is your feature request related to a problem?

Zombified piglins cannot be prevented from breaking doors without also preventing the mechanic for normal zombies breaking doors. As zombies are hostile I feel that them breaking doors is a difficulty mechanic and so I don't want to disable this, but zombified piglins are neutral and are difficult to prevent the spawning of due to the portal spawn mechanic which we use in farms. The only additional 'difficulty' they give is breaking down lots of doors if you are AFK regularly.

### Describe the solution you'd like.

I would like to see the ability to change the door-breaking-difficulty of zombified piglins in the same way as for zombies and vindicators so I can disable the mechanic for them independently. This will prevent me from either replacing doors all the time or disabling the mechanic for all zombies.

### Describe alternatives you've considered.

I have considered plugins but feel that as zombies and vindicators are controlled by paper.yml it makes more sense to control zombified piglins in the same way. I have also considered disabling for zombies but don't want to lose the door breaking mechanic from a hostile mob.

**Comment by Doc94** [comment]
Not stale... Only need more rebases if is ready...
