### ISSUE TITLE
FlushConsolidationHandler

### ISSUE THREAD

**Issue by andreasdc** [PaperSpigot/Paper#6949]
### Timings or Profile link

-

### Description of issue

https://github.com/PaperMC/Paper/blob/master/patches/server/0310-Optimize-Network-Manager-and-add-advanced-packet-sup.patch
In this patch FlushConsolidationHandler is added by default. Can this make delay in receiving packets larger? How does this impact on that?

### Plugin and Datapack List

-

### Server config files

-

### Paper version

-

**Comment by electronicboy** [comment]
1) Well, yes, packets are going to be delayed in a sense before they're flushed (an expensive operation) from being sent by the server
2) I don't believe that there have been any real benchmarking of this but I don't believe any issues has arisen since this patch was added, and there is an option to disable it by default, given how tight the loop it it's very unlikely that this adds a substantial delay towards the sending of packets by the server

**Comment by andreasdc** [comment]
> 1. Well, yes, packets are going to be delayed in a sense before they're flushed (an expensive operation) from being sent by the server
> 2. I don't believe that there have been any real benchmarking of this but I don't believe any issues has arisen since this patch was added, and there is an option to disable it by default, given how tight the loop it it's very unlikely that this adds a substantial delay towards the sending of packets by the server

It would be nice to compare this, as this can make big difference in PVP.

**Comment by andreasdc** [comment]
@electronicboy @Chew can you reopen it to see delay between client and server with this feature enabled?

**Comment by andreasdc** [comment]
@electronicboy @Chew I think after enabling this accessing netty is way higher in profilers. Do you have benchmarks or comparisons?

**Comment by electronicboy** [comment]
No, we do not have benchmarks, but, the entire purpose of that thing is to consilidate flushes to avoid the expensive calls from being consistently made to batch them into a more efficient wakeup. There are caveats to this, hence the flag to disable the mechanism.
profilers have their own caveats in how they measure this stuff, so, would likely need to actually setup timers or something for such a method call.

**Comment by andreasdc** [comment]
> No, we do not have benchmarks, but, the entire purpose of that thing is to consilidate flushes to avoid the expensive calls from being consistently made to batch them into a more efficient wakeup. There are caveats to this, hence the flag to disable the mechanism. profilers have their own caveats in how they measure this stuff, so, would likely need to actually setup timers or something for such a method call.

What if I already consolidate flush? I think in this scenario this option makes it worse.
I think that's the problem, most of my packets are already consolidated.

**Comment by electronicboy** [comment]
that's not a scenario which is applicable to the vanilla server as-is

**Comment by andreasdc** [comment]
> that's not a scenario which is applicable to the vanilla server as-is

It's a good change to performance, is there a way to bypass it to already consolidated packets?

**Comment by electronicboy** [comment]
it doesn't know what is already consolidated (and maintaining a diff over the entire server of sendPacket calls is likely a non starter), you are, once again, more than welcome to disable that using the flag.

Either way, I see no need to further spam people with emails from this discussion.
