### ISSUE TITLE
Optimize getProtocolForPacket

### ISSUE THREAD

**Issue by andreasdc** [PaperSpigot/Paper#6951]
### Is your feature request related to a problem?

Slow packet sending

### Describe the solution you'd like.

Why don't we remove usage of getProtocolForPacket and set it to every packet once and then just take it? getProtocolForPacket and setProtocol are more expensive than sending actual packet/passing it to netty.

### Describe alternatives you've considered.

-

### Other

![image](https://user-images.githubusercontent.com/82218780/143946732-b896e639-4b5a-4a7a-99cb-8f2243e364f1.png)

_No response_

**Comment by electronicboy** [comment]
1.8 hasn't been supported in years

**Comment by andreasdc** [comment]
> rs

You have the same code in this part

**Comment by electronicboy** [comment]
if you're going to create issues for stuff which is still relevant, then create them with info from versions which are actually supported in which we can actually look at, without having to go through dozens of hoops. We do not care for reports based on info taken from stupidly old versions.
