### ISSUE TITLE
Slow packet sending

### ISSUE THREAD

**Issue by andreasdc** [PaperSpigot/Paper#6952]
### Timings or Profile link

-

### Description of issue

Why don't we remove usage of getProtocolForPacket and set it to every packet once and then just take it? getProtocolForPacket and setProtocol are more expensive than sending actual packet/passing it to netty.

I can provide more profilers and test if needed.

In this profiler I was alone on the server, when there are more players this is on top of profilers and in packet sending method.

### Plugin and Datapack List

-

### Server config files

-

### Paper version

This server is running Paper version git-Paper-277 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 397349e)
You are 111 version(s) behind
Previous version: git-Paper-196 (MC: 1.17.1)

### Other

![image](https://user-images.githubusercontent.com/82218780/143954116-7342e4af-88b6-4ed9-9b3d-ee5ea53952ee.png)

**Comment by electronicboy** [comment]
outdated, screenshots of spark reports are useless

**Comment by andreasdc** [comment]
Let me grab the newest version, how else can I check performance?

**Comment by electronicboy** [comment]
link the report so that we can actually analyse it?

**Comment by andreasdc** [comment]
> link the report so that we can actually analyse it?

Of course, give me couple minutes :)

**Comment by andreasdc** [comment]
> link the report so that we can actually analyse it?

https://spark.lucko.me/eZZrwBeyGf
This server is running Paper version git-Paper-388 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 22aaf91)
You are running the latest version
Previous version: git-Paper-277 (MC: 1.17.1)

**Comment by andreasdc** [comment]
@electronicboy why close?
