### ISSUE TITLE
Server freezes 15-30 seconds after startup

### ISSUE THREAD

**Issue by ajgeiss0702** [PaperSpigot/Paper#6959]
### Stack trace

n/a
server freezes with no stacktrace, crash logs, or anything

### Plugin and Datapack List

No plugins, completly fresh server

### Actions to reproduce (if known)

Start a fresh server (no old world, no plugins, etc)
Wait 15-30 seconds
Server cpu usage goes to 0-1% and no new connections are accepted. New connection attempts time out

### Paper version

This server is running Paper version git-Paper-10 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: c728c78)

### Other

Server is completly fresh, no plugins.

Running on (my own) pterodactyl panel, using the java 17 docker image.

**Comment by electronicboy** [comment]
> Running on (my own) pterodactyl panel

Everything you've described there sounds like you're hitting the containers memory limit, reduce Xmx

**Comment by ajgeiss0702** [comment]
Ah, yep that seems to be it. Thanks.
