### ISSUE TITLE
max-build-height does nothing

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#6963]
### Expected behavior

Players can't build above 255 blocks

### Observed/Actual behavior

Players still can build up to 319 blocks

### Steps/models to reproduce

Set `max-build-height` to 256 in server.properties;
Try to build

### Plugin and Datapack List

No plugins, built-in datapacks

### Paper version

This server is running Paper version git-Paper-8 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 2e28d75 on dev/1.18)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-384 (MC: 1.17.1)

### Other

Don't know is this a bug or this setting is just abandoned and it's works as intended

**Comment by electronicboy** [comment]
That option was removed by mojang a while ago last I recall

**Comment by molor** [comment]
Hmm, MC Wiki doesn't says this and it was not automatically removed from the properties file during server update, so strange, but OK

**Comment by MiniDigger** [comment]
it was removed in 1.17 iirc

**Comment by Chew** [comment]
It was removed in 20w49a, updated the wiki to reflect this.
