### ISSUE TITLE
1.18 - Debug log

### ISSUE THREAD

**Issue by josephjthomas** [PaperSpigot/Paper#6964]
### Expected behavior

No debug line, like in previous versions.

### Observed/Actual behavior

If you start your server, it prints `Starting org.bukkit.craftbukkit.Main` on top of your screen. To me it looks like some message for developers or if you debug the server, not something an end user needs.

### Steps/models to reproduce

Get the newest 1.18 build from the download page and start the server

### Plugin and Datapack List

No plugins

### Paper version

[Server thread/INFO]: Checking version, please wait...
Thread-12/INFO]: This server is running Paper version git-Paper-10 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: c728c78)
You are running the latest version
Previous version: git-Paper-8 (MC: 1.18)

**Comment by electronicboy** [comment]
That's the bootstrap saying what it's doing
