### ISSUE TITLE
Crash during fresh world generation on latest 1.18 build (Git: cd9fe9c)

### ISSUE THREAD

**Issue by HydrationMan** [PaperSpigot/Paper#6969]
### Stack trace

```
https://paste.gg/p/anonymous/fa1fd3e1023e4ddba6cb435fd83a5d4a
```

### Plugin and Datapack List

None

### Actions to reproduce (if known)

1. Attempt to run latest build without a world so it can generate one.
2. Crash while Preparing Level

### Paper version

Paper Version git-Paper-14 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT (Git: cd9fe9c)

### Other

This crash does not occur on (Git: effa3ba)

**Comment by e-im** [comment]
This is a known issue with reobf, for the moment revert to build 13 as a workaround. A proper fix will come soon

**Comment by HydrationMan** [comment]
Thanks

**Comment by e-im** [comment]
Fixed in build 15

**Comment by FrankHeijden** [comment]
Nice.
