### ISSUE TITLE
1.18 Update - Crash on world generation

### ISSUE THREAD

**Issue by PoofyKittens** [PaperSpigot/Paper#6971]
### Stack trace

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 12/1/21, 2:11 AM
Description: Exception initializing level

java.lang.IllegalAccessError: failed to access class net.minecraft.world.level.levelgen.SurfaceRules$i from class net.minecraft.data.worldgen.SurfaceRuleData$PaperBedrockConditionSource$1VerticalGradientCondition (net.minecraft.world.level.levelgen.SurfaceRules$i and net.minecraft.data.worldgen.SurfaceRuleData$PaperBedrockConditionSource$1VerticalGradientCondition are in unnamed module of loader java.net.URLClassLoader @5c29bfd)
	at net.minecraft.data.worldgen.SurfaceRuleData$PaperBedrockConditionSource$1VerticalGradientCondition.a(SurfaceRuleData.java:83)
	at net.minecraft.world.level.levelgen.SurfaceRules$LazyCondition.test(SurfaceRules.java:240)
	at net.minecraft.world.level.levelgen.SurfaceRules$TestRule.tryApply(SurfaceRules.java:365)
	at net.minecraft.world.level.levelgen.SurfaceRules$SequenceRule.tryApply(SurfaceRules.java:377)
	at net.minecraft.world.level.levelgen.SurfaceSystem.buildSurface(SurfaceSystem.java:197)
	at net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.buildSurface(NoiseBasedChunkGenerator.java:240)
	at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:125)
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.doWork(ChunkStatus.java:342)
	at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:273)
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$35(ChunkTracker.java:1245)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$37(ChunkTracker.java:1243)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:58)
	at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:91)
	at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:146)
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.data.worldgen.SurfaceRuleData$PaperBedrockConditionSource$1VerticalGradientCondition.a(SurfaceRuleData.java:83)
	at net.minecraft.world.level.levelgen.SurfaceRules$LazyCondition.test(SurfaceRules.java:240)
	at net.minecraft.world.level.levelgen.SurfaceRules$TestRule.tryApply(SurfaceRules.java:365)
	at net.minecraft.world.level.levelgen.SurfaceRules$SequenceRule.tryApply(SurfaceRules.java:377)
	at net.minecraft.world.level.levelgen.SurfaceSystem.buildSurface(SurfaceSystem.java:197)
	at net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.buildSurface(NoiseBasedChunkGenerator.java:240)
	at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:125)
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.doWork(ChunkStatus.java:342)
	at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:273)
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$35(ChunkTracker.java:1245)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$37(ChunkTracker.java:1243)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 625
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,-24), Section: (at 8,0,8 in 0,4,-2; chunk contains blocks 0,-64,-32 to 15,319,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 0 game time, 0 day time
	Level name: Sophie's World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: Paper
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:754)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:695)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:501)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18
	Minecraft Version ID: 1.18
	Operating System: Linux (amd64) version 5.8.0-63-generic
	Java Version: 17.0.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 283441152 bytes (270 MiB) / 859832320 bytes (820 MiB) up to 4194304000 bytes (4000 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD EPYC 7302 16-Core Processor
	Identifier: AuthenticAMD Family 23 Model 49 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 83291.77
	Virtual memory used (MB): 43317.25
	Swap memory total (MB): 51200.00
	Swap memory used (MB): 42.75
	JVM Flags: 2 total; -Xmx4000M -Xms0M
	CraftBukkit Information: 
   Running: Paper version git-Paper-14 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) true
   Plugins: { ServerRestart v2.3.0 ua.i0xhex.srvrestart.ServerRestart [i0xHeX], SignEdit v1.12.6 org.deltik.mc.signedit.SignEditPlugin [Deltik], GroupManager v2.9 (Phoenix) org.anjocaido.groupmanager.GroupManager [AnjoCaido, Gabriel Couto, ElgarL], Vault v1.7.3-b131 net.milkbowl.vault.Vault [cereal, Sleaker, mung3r], ProtocolLib v4.7.0-SNAPSHOT-b526 com.comphenix.protocol.ProtocolLib [dmulloy2, comphenix], WorldEdit v7.2.6-SNAPSHOT+5853-978bf5b com.sk89q.worldedit.bukkit.WorldEditPlugin [], Essentials v2.19.1-dev+39-f8ca1ba com.earth2me.essentials.Essentials [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally, drtshock, vemacs, SupaHam, mdcfe, JRoy, pop4959], EssentialsChat v2.19.1-dev+39-f8ca1ba com.earth2me.essentials.chat.EssentialsChat [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Okamosy, Iaccidentally, mdcfe, JRoy, triagonal], MineableSpawners v3.1.0 com.dnyferguson.mineablespawners.MineableSpawners [fergydanny], ServerlistMOTD vX-2020-09-05* cloud.bolte.serverlistmotd.Main [Strumswell], SinglePlayerSleep v1.13_2.13.46 com.github.joelgodofwar.sps.SinglePlayerSleep [JoelGodOfWar(JoelYahwehOfWar)], EssentialsSpawn v2.19.1-dev+39-f8ca1ba com.earth2me.essentials.spawn.EssentialsSpawn [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, SupaHam, mdcfe, DoNotSpamPls, JRoy], WorldGuard v7.0.5+3827266 com.sk89q.worldguard.bukkit.WorldGuardPlugin [], EssentialsDiscord v2.19.1-dev+39-f8ca1ba net.essentialsx.discord.EssentialsDiscord [mdcfe, JRoy, pop4959, Glare], TreeAssist v7.2.37 net.slipcor.treeassist.TreeAssist [slipcor, FriendlyBaron], GSit v[6.0.4.1] me.gsit.main.GSitMain [Gecolay],}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { RUNNABLE Server console handler: [java.base@17.0.1/java.io.FileInputStream.readBytes(Native Method), java.base@17.0.1/java.io.FileInputStream.read(FileInputStream.java:276), java.base@17.0.1/java.io.BufferedInputStream.read1(BufferedInputStream.java:282), java.base@17.0.1/java.io.BufferedInputStream.read(BufferedInputStream.java:343), java.base@17.0.1/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270), java.base@17.0.1/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313), java.base@17.0.1/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188), java.base@17.0.1/java.io.InputStreamReader.read(InputStreamReader.java:177), java.base@17.0.1/java.io.BufferedReader.fill(BufferedReader.java:162), java.base@17.0.1/java.io.BufferedReader.readLine(BufferedReader.java:329), java.base@17.0.1/java.io.BufferedReader.readLine(BufferedReader.java:396), net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:180), net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:143), net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:111)], TIMED_WAITING bStats-Metrics: [java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672), java.base@17.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182), java.base@17.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899), java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.1/java.lang.Thread.run(Thread.java:833)], WAITING Paper RegionFile IO Thread: [java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], TIMED_WAITING Paper Watchdog Thread: [java.base@17.0.1/java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:243)], RUNNABLE Netty Epoll Server IO #0: [io.netty.channel.epoll.Native.epollWait(Native Method), io.netty.channel.epoll.Native.epollWait(Native.java:192), io.netty.channel.epoll.Native.epollWait(Native.java:185), io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:290), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:347), io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986), io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74), java.base@17.0.1/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Craft Scheduler Thread - 0: [java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.1/java.lang.Thread.run(Thread.java:833)], WAITING Java2D Disposer: [java.base@17.0.1/java.lang.Object.wait(Native Method), java.base@17.0.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@17.0.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176), java.desktop@17.0.1/sun.java2d.Disposer.run(Disposer.java:145), java.base@17.0.1/java.lang.Thread.run(Thread.java:833)], RUNNABLE DestroyJavaVM: [], TIMED_WAITING process reaper: [java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.1/java.lang.Thread.run(Thread.java:833)], WAITING Finalizer: [java.base@17.0.1/java.lang.Object.wait(Native Method), java.base@17.0.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@17.0.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176), java.base@17.0.1/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:172)], RUNNABLE Worker-Main-1: [net.minecraft.world.level.levelgen.synth.NoiseGeneratorOctaves.a(NoiseGeneratorOctaves.java:153), net.minecraft.world.level.levelgen.synth.NoiseGeneratorOctaves.a(NoiseGeneratorOctaves.java:141), net.minecraft.world.level.levelgen.synth.NoiseGeneratorNormal.a(NoiseGeneratorNormal.java:87), net.minecraft.world.level.levelgen.NoiseSampler.a(NoiseSampler.java:337), net.minecraft.world.level.levelgen.NoiseSampler.a(NoiseSampler.java:274), net.minecraft.world.level.levelgen.NoiseSampler.a(NoiseSampler.java:155), net.minecraft.world.level.levelgen.NoiseSampler$$Lambda$5357/0x0000000801afa870.calculateNoise(Unknown Source), net.minecraft.world.level.levelgen.NoiseChunk$d.a(NoiseChunk.java:277), net.minecraft.world.level.levelgen.NoiseChunk$d.a(NoiseChunk.java:252), net.minecraft.world.level.levelgen.NoiseChunk.a(NoiseChunk.java:148), net.minecraft.world.level.levelgen.NoiseChunk$$Lambda$5360/0x0000000801afb350.accept(Unknown Source), java.base@17.0.1/java.util.ArrayList.forEach(ArrayList.java:1511), net.minecraft.world.level.levelgen.NoiseChunk.b(NoiseChunk.java:148), net.minecraft.world.level.levelgen.ChunkGeneratorAbstract.a(ChunkGeneratorAbstract.java:200), net.minecraft.world.level.levelgen.ChunkGeneratorAbstract.a(ChunkGeneratorAbstract.java:181), net.minecraft.world.level.levelgen.structure.WorldGenFeatureNetherFossil.a(WorldGenFeatureNetherFossil.java:40), net.minecraft.world.level.levelgen.structure.WorldGenFeatureNetherFossil$$Lambda$1914/0x0000000801173dc0.createGenerator(Unknown Source), net.minecraft.world.level.levelgen.feature.StructureGenerator.a(StructureGenerator.java:234), net.minecraft.world.level.levelgen.feature.StructureFeature.a(StructureFeature.java:36), net.minecraft.world.level.chunk.ChunkGenerator.a(ChunkGenerator.java:492), net.minecraft.world.level.chunk.ChunkStatus.lambda$static$2(ChunkStatus.java:51), net.minecraft.world.level.chunk.ChunkStatus$$Lambda$2384/0x000000080120f7e8.doWork(Unknown Source), net.minecraft.world.level.chunk.ChunkStatus.a(ChunkStatus.java:273), net.minecraft.server.level.PlayerChunkMap.lambda$scheduleChunkGeneration$35(PlayerChunkMap.java:1245), net.minecraft.server.level.PlayerChunkMap$$Lambda$5348/0x0000000801af8238.apply(Unknown Source), com.mojang.datafixers.util.Either$Left.map(Either.java:38), net.minecraft.server.level.PlayerChunkMap.lambda$scheduleChunkGeneration$37(PlayerChunkMap.java:1243), net.minecraft.server.level.PlayerChunkMap$$Lambda$5333/0x0000000801af6450.apply(Unknown Source), java.base@17.0.1/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150), java.base@17.0.1/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482), net.minecraft.server.level.ChunkTaskQueueSorter.b(ChunkTaskQueueSorter.java:58), net.minecraft.server.level.ChunkTaskQueueSorter$$Lambda$5346/0x0000000801af5c88.run(Unknown Source), net.minecraft.util.thread.ThreadedMailbox.g(ThreadedMailbox.java:91), net.minecraft.util.thread.ThreadedMailbox.a(ThreadedMailbox.java:146), net.minecraft.util.thread.ThreadedMailbox.run(ThreadedMailbox.java:102), java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136), java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.1/java.lang.Thread.run(Thread.java:833)], RUNNABLE Notification Thread: [], WAITING Log4j2-AsyncAppenderEventDispatcher-1-Async: [java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463), java.base@17.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434), java.base@17.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.1/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:420), org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatchAll(AsyncAppenderEventDispatcher.java:71), org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.run(AsyncAppenderEventDispatcher.java:63)], RUNNABLE Signal Dispatcher: [], RUNNABLE Reference Handler: [java.base@17.0.1/java.lang.ref.Reference.waitForReferencePendingList(Native Method), java.base@17.0.1/java.lang.ref.Reference.processPendingReferences(Reference.java:253), java.base@17.0.1/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:215)], TIMED_WAITING Craft Scheduler Thread - 2: [java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.1/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Common-Cleaner: [java.base@17.0.1/java.lang.Object.wait(Native Method), java.base@17.0.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@17.0.1/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140), java.base@17.0.1/java.lang.Thread.run(Thread.java:833), java.base@17.0.1/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)], TIMED_WAITING Craft Scheduler Thread - 1: [java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.1/java.lang.Thread.run(Thread.java:833)], WAITING Paper Async Chunk Task Thread #0: [java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], TIMED_WAITING Timer-0: [java.base@17.0.1/java.lang.Object.wait(Native Method), java.base@17.0.1/java.util.TimerThread.mainLoop(Timer.java:563), java.base@17.0.1/java.util.TimerThread.run(Timer.java:516)], WAITING Paper Async Chunk Urgent Task Thread: [java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], TIMED_WAITING Timer hack thread: [java.base@17.0.1/java.lang.Thread.sleep(Native Method), net.minecraft.SystemUtils$5.run(SystemUtils.java:651)], TIMED_WAITING WorldEdit Session Manager: [java.base@17.0.1/java.lang.Object.wait(Native Method), java.base@17.0.1/java.util.TimerThread.mainLoop(Timer.java:563), java.base@17.0.1/java.util.TimerThread.run(Timer.java:516)], RUNNABLE Server thread: [java.base@17.0.1/java.lang.Thread.dumpThreads(Native Method), java.base@17.0.1/java.lang.Thread.getAllStackTraces(Thread.java:1662), org.bukkit.craftbukkit.v1_18_R1.CraftCrashReport.get(CraftCrashReport.java:33), org.bukkit.craftbukkit.v1_18_R1.CraftCrashReport.get(CraftCrashReport.java:17), net.minecraft.SystemReport.a(SystemReport.java:65), net.minecraft.CrashReport.<init>(CrashReport.java:36), net.minecraft.CrashReport.a(CrashReport.java:242), net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:751), net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:695), net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:501), net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313), net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1201), net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316), net.minecraft.server.MinecraftServer$$Lambda$3915/0x00000008014286a8.run(Unknown Source), java.base@17.0.1/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Craft Scheduler Thread - 3: [java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.1/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING pool-4-thread-1: [java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672), java.base@17.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182), java.base@17.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899), java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.1/java.lang.Thread.run(Thread.java:833)],}
   
   Force Loaded Chunks: { Sophie's World: {},}
	Server Running: true
	Player Count: 0 / 69; []
	Data Packs: vanilla, file/bukkit
	Is Modded: Definitely; Server brand changed to 'Paper'
	Type: Dedicated Server (map_server.txt)

### Plugin and Datapack List

none

### Actions to reproduce (if known)

Delete world files, allow them to regenerate by starting server back up, boom, error.

### Paper version

"This server is running Paper version git-Paper-14 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: cd9fe9c)"

**Comment by darbyjack** [comment]
This was just fixed in the latest build. Wait for Build 15.

**Comment by e-im** [comment]
Duplicate of #6969
