### ISSUE TITLE
Add Mineshafts and Strongholds to the feature-seeds: Configuration

### ISSUE THREAD

**Issue by Vaultling** [PaperSpigot/Paper#6978]
### Is your feature request related to a problem?

Using a website like **https://www.chunkbase.com/** you can find **Mineshafts** and **Strongholds** if you were to crack the seed. There are 18 structure features but Spigot only has 16 options, no support to change seeds for Mineshafts or Strongholds. Even after changing all possible seed-x in spigot.yml and changing **generate-random-seeds-for-all:** to **true** it still won't work for the 2 options left out. 

### Describe the solution you'd like.

Add configurations to Paper to change the seed of Mineshafts and Strongholds (optional).

### Describe alternatives you've considered.

No alternatives known.

**Comment by rozalily** [comment]
This sounds like something that might belong in a plugin instead.

**Comment by Machine-Maker** [comment]
Why do you say that? Out of the 18 structure features, 16 of them have configurable seeds in the spigot.yml. And that was last updated during the 1.16.1 update. I’m guessing they either skipped them for an unknown reason, or they were added after and spigot just didn’t add them.

**Comment by Vaultling** [comment]
> This sounds like something that might belong in a plugin instead.

Not really. This has to do with how mineshafts and strongholds are generated. The idea is that you should be able to have a separate seed for the mineshafts and strongholds compared to the world seed. And since 16 out of the 18 are added why not complete it and make mineshafts and strongholds be able to have their own seeds too?

**Comment by Vaultling** [comment]
Any update on this?

**Comment by Pantera07** [comment]
A stronghold seed was added. Why haven't mineshafts and buried treasure seeds added yet?

**Comment by MiniDigger** [comment]
there is an open PR for that. To speed up processing of that PR, you could build it locally and test it and report your findings: https://github.com/PaperMC/Paper/pull/7398
