### ISSUE TITLE
Banner in hand of the other entity or drop the ground, Banner content style not display

### ISSUE THREAD

**Issue by xuancat0208** [PaperSpigot/Paper#6979]
### Expected behavior

Native:
![](https://i.imgur.com/Z2WVgnq.png)
Spigot:
![](https://i.imgur.com/yKqflTu.png)

### Observed/Actual behavior

Paper-11:
![](https://i.imgur.com/JQ47cQ1.png)
Paper-18:
![](https://i.imgur.com/CVJMFHm.png)

### Steps/models to reproduce

Make a styled flag and throw it on the ground

### Plugin and Datapack List

none

### Paper version

This server is running Paper version git-Paper-18 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 13a445c)
You are running the latest version
Previous version: git-Paper-11 (MC: 1.18)

**Comment by Fejm** [comment]
https://github.com/PaperMC/Paper/commit/e955cb5b26423496bb550504697ece7cae11d28f
