### ISSUE TITLE
Update `falling-block-height-nerf` and `tnt-entity-height-nerf`

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#6981]
### Expected behavior

Values < 0 is supported and works correctly

### Observed/Actual behavior

Values < 0 will disable these features, but the minimum world height since 1.17 can be -63 or even -2031 if this is a custom dimension with custom `min_y`.

### Steps/models to reproduce

Set `falling-block-height-nerf` or `tnt-entity-height-nerf` in paper.yml to -63

### Plugin and Datapack List

This is a reminder from Paper's discord channel, so I think that this is not needed

### Paper version

Experimental 1.18

### Other

Don't know how to add ability to disable these features because of negative heights instead of values < 0, maybe just use boolean `false` instead of a number

**Comment by kennytv** [comment]
As far as I can see that assumption is wrong? It's only disabled if the value is exactly 0

**Comment by lynxplay** [comment]
Validated this on a local setup :+1:  0 is the only value that disables this feature. The documentation however is still mentioning that `Values less than 1 will disable this feature.` I'll open a respective issue :+1:

**Comment by molor** [comment]
I don't understand how it's works. The description says `The height at which falling blocks will be removed from the server`. I set it to `0`  — seems that it was disabled. I'm set it to `-63` — falling blocks (in my case gravel) just drops as item every time at height >= (higher or equals, not lower!) -63. I'm set it to `8` — and behavior is the same like with -63, but slightly higher..

I think that server should remove falling block if it is _below_ the specified height, and not higher, as it works now. Or am I doing something wrong?

**Comment by lynxplay** [comment]
You are correct in the usage, the server removes falling blocks/tnt when they are above the threshold specified.
It was initially implemented to limit flying tnt/falling blocks from going too high in the world if I recall correctly ([in this commit](https://github.com/PaperMC/Paper/commit/a26fef50efb43a1b75d532c88b12a18d74c696f4)).
