### ISSUE TITLE
Slow wakeup calls to netty

### ISSUE THREAD

**Issue by andreasdc** [PaperSpigot/Paper#6982]
### Timings or Profile link

-

### Description of issue

Wakeups are 9% in profilers, is there a way to batch netty's wakeups?
FlushConsolidationHandler increased wakeups for 0.4%.

![image](https://user-images.githubusercontent.com/82218780/144292430-aa272daf-a51a-4c28-b926-3f0beeb44469.png)

### Plugin and Datapack List

-

### Server config files

-

### Paper version

This server is running Paper version git-Paper-388 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 22aaf91)
You are running the latest version
Previous version: git-Paper-277 (MC: 1.17.1)

**Comment by aurorasmiles** [comment]
Fill out the issue template. If you continue spamming useless issues we will ban you from the organisation.
