### ISSUE TITLE
Performance leak on netty wakeups

### ISSUE THREAD

**Issue by andreasdc** [PaperSpigot/Paper#6984]
### Timings or Profile link

https://spark.lucko.me/eZZrwBeyGf

### Description of issue

Wakeups are 9% in profilers, is there a way to batch netty's wakeups?
FlushConsolidationHandler increased wakeups for 0.4%.

I can provide more profilers and test if needed.

In this profiler I was alone with 1 player on the server, when there are more players this is on top of profilers and in packet sending method.

### Plugin and Datapack List

no plugins

### Server config files

default configs

### Paper version

This server is running Paper version git-Paper-388 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 22aaf91)
You are running the latest version
Previous version: git-Paper-277 (MC: 1.17.1)

**Comment by electronicboy** [comment]
1) Without micro benchmarking comparisons between with and without, nobody can say how much individual methods take. A profiler is 100% useless for method/micro benchmarking and thus, the profile report here is straight-up a waste of time

2) Yes, batching is technically doable but would require large amounts of work towards the way the entire servers networking is handled which is not feasible without basically breaking every plugin which relies on messing with server internals and would be an excessive maintenance debt on the project. This is a longterm goal of mine, but, is not feasible if we wish to maintain support with spigot, etc.

3) I'm not sure where you're looking to see that the flush consolidation handler is making the wakeup take longer, flush consolidation has nothing to do with the wakeup stuff?

4) I have 0 interest in spamming peoples emails with a constant back and forth over this. Unless you have conclusive *micro* benchmarks, everything here is akin to tryna shoot a dart at a target you're flying 10k ft over, and unless you actually have something actional, this is just a waste of time, I'm not a netty pro but I've yet to see anything here which lines up with all much of what you're saying and is actually something which can be worked upon given the architecture of the server and how netty works.
