### ISSUE TITLE
[1.18] Distant grass does not grow, while distant sheep still eat grass. 

### ISSUE THREAD

**Issue by Cirom** [PaperSpigot/Paper#6987]
### Expected behavior

Grass that sheep eat should grow back, as I imagine the distance for sheep calculations and the distance for block updates should be the same, like it is in Vanilla.

### Observed/Actual behavior

The grass did not grow back, leaving a rather large quantity of just surface dirt where sheep have been. Flying closer to the grass caused it to start growing back again.

### Steps/models to reproduce

I guess just stand far away from where there is sheep? 

The damage done by the sheep. Note that there were just five sheep, and they normally don't cause THIS much damage. They also don't cause this much damage when I stood close to them.
![2021-12-01_19 42 57](https://user-images.githubusercontent.com/6567772/144320251-cc3f52ac-e01a-4af6-a02f-3570a1addb32.png)

The location of the sheep
![2021-12-01_19 42 54](https://user-images.githubusercontent.com/6567772/144320246-15553f9d-3cde-401f-9511-aa11807b0c03.png)

The location of where I stood for about ~30 minutes to an hour. Wasn't really counting as I was troubleshooting other things at the time.
![2021-12-01_19 42 37](https://user-images.githubusercontent.com/6567772/144320239-4818c2bf-0ba4-493f-ada3-abd5b94f9899.png)

### Plugin and Datapack List

No plugins were loaded, and the only datapacks that were loaded were ones which modify crafting recipes.

### Paper version

Paper 1.18-19
Minecraft 1.18

**Comment by electronicboy** [comment]
This is a vanilla issue, 
chunks only tick when there is a player in range of them, entities tick when they're within a chunk marked as entity ticking

a plugin could probably easily mitigate this
