### ISSUE TITLE
[BUG] [ CRITICAL] All blocks below height 32 are deleted on --forceupgrade

### ISSUE THREAD

**Issue by Tsoccerguy3** [PaperSpigot/Paper#6988]
### Expected behavior

on upgrade from 1.17.1 to 1.18 using --forceupgrade , expect map conversion to 1.18 with new blocks generated below level 1 bedrock

### Observed/Actual behavior

All blocks below level 32 to the bedrock are deleted on entire map. Water is generated from level 2 to 21 , no blocks are generated below level 1 bedrock
![2021-12-01_16 48 40](https://user-images.githubusercontent.com/22108822/144321688-07cd7fa4-9456-4503-9bff-a347fe171622.png)

![2021-12-01_16 47 08](https://user-images.githubusercontent.com/22108822/144321684-60b50d7f-a7a2-4056-95cc-db94a0cc1425.png)

![2021-12-01_16 44 39](https://user-images.githubusercontent.com/22108822/144321673-2fbc9438-0ae3-4790-9c35-091d04ba0c37.png)
![2021-12-01_16 44 53](https://user-images.githubusercontent.com/22108822/144321680-68a32c2c-a8d9-4125-b2ab-4d5781aee9bb.png)
![2021-12-01_16 47 04](https://user-images.githubusercontent.com/22108822/144321683-7a1d8d5e-1e54-4d22-9534-772754a8d5db.png)

### Steps/models to reproduce

Run --forceupgrade to 1.18 from a 1.17.1 map , latest Paper and Spigot tested as well

### Plugin and Datapack List

[List_Files.txt](https://github.com/PaperMC/Paper/files/7637441/List_Files.txt)

### Paper version

Paper 1.18 build 20 or use latest compile from spigot . Paper may inheritBug from Spigot 

### Other

[level.zip](https://github.com/PaperMC/Paper/files/7637456/level.zip)
Level.dat from the 1.17.1 map to be converted Small sample map to be provided on request

**Comment by Tsoccerguy3** [comment]
[Tundra.zip](https://github.com/PaperMC/Paper/files/7637493/Tundra.zip)
sample 1.17.1 map before conversion to 1.18

**Comment by Machine-Maker** [comment]
~~Can you try this on spigot or vanilla?~~

**Comment by Tsoccerguy3** [comment]
The full custom server map is 16K x 16K blocks , The theme of the map is frozen Tundra like Iceland

**Comment by Malfrador** [comment]
Tried to reproduce this on Paper build 20 (with --forceUpgrade) as well as vanilla (Singleplayer, "Optimize World"). Both behaved the same.

I could not exactly reproduce the issue. All blocks below 32 are there, as they should be. But instead the entire world is moved down on the y-axis, with the water level ending up at y=20. 
![javaw_2021-12-01_23-30-18](https://user-images.githubusercontent.com/6106558/144325685-5b4601a0-b7c4-40f1-88e0-37a72e3eefcf.jpg)

And I really hope you have backups, those builds look very good.

**Comment by Tsoccerguy3** [comment]
The CUSTOM sample map provided is 3 region files . so if you login in single player it will naturally generate new vanilla regions . Ignore those newly generated region files. Our server map is 16 thousand blocks square and was custom created . Bedrock at level 1 , sea level 21 and land rises to a max of 32 blocks from bedrock. Run the sample 1.17.1 map through --forceupgrade in 1.18 and the blocks below 32 will be deleted and no block generated bedrock and below.

**Comment by Tsoccerguy3** [comment]
Our 1.17.1 Dynmap http://51.195.61.22:25576/# , look on Tundra map for the full map

**Comment by Tsoccerguy3** [comment]
Our server info and logon , https://www.planetminecraft.com/server/sanacraft/ , /warp Project , to see scale and levels of map. I expect that custom maps were not taken into consideration on conversion . This does not happen if the map is converted with single player in vanilla

**Comment by Malfrador** [comment]
Well, if the water-level at 21 is intentional, then I can't confirm the issue on Paper 20. I tried force-upgrading the sample world you provided twice now - All Blocks below y=32 are there and everything looks normal:
![javaw_2021-12-01_23-53-41](https://user-images.githubusercontent.com/6106558/144327241-22075d61-3e70-4980-8b2d-09fcf90b1c79.jpg)

Startup log from the upgrade also isn't showing anything unusual: https://paste.gg/p/anonymous/93bc37048fd3467caef5c19077920b6a

**Comment by Tsoccerguy3** [comment]
Maybe the world gen crapped out somewhere in this large map . I will go into spectator mode and go take a look around underneath .This will take a while .

**Comment by Machine-Maker** [comment]
Just to comment on my testing, I loaded up the Tundra world in a vanilla 1.17.1 server, went to the coordinates in these screenshots saw the buildings.

Then I logged out, swapped out the vanilla 1.17.1 jar with a vanilla 1.18 jar and ran it with `--forceUpgrade`, logged back in and 
everything was as it should be with caves generating below the floor of the water around the boats and whatnot.

**Comment by Tsoccerguy3** [comment]
Vanilla single play does a correct conversion so if you use the vanilla server it may also do a correct conversion . I only tested Paper and Spigot servers

**Comment by Malfrador** [comment]
Does on-the-fly conversion work, e.g. just loading the world without using --forceUpgrade?

Generally, I would discourage using forceUpgrade, it has broken things in the past and does not provide any benefits on Paper

**Comment by lynxplay** [comment]
> The CUSTOM sample map provided is 3 region files . so if you login in single player it will naturally generate new vanilla regions . Ignore those newly generated region files. Our server map is 16 thousand blocks square and was custom created . Bedrock at level 1 , sea level 21 and land rises to a max of 32 blocks from bedrock. Run the sample 1.17.1 map through --forceupgrade in 1.18 and the blocks below 32 will be deleted and no block generated bedrock and below.

I'd guess you generated your map using generator options ? If so, could you provide them. If not, how did you generate the map?

**Comment by Machine-Maker** [comment]
> Vanilla single play does a correct conversion so if you use the vanilla server it may also do a correct conversion . I only tested Paper and Spigot servers

I can't replicate this on Paper either. I downloaded the latest build of 1.17.1 Paper, loaded the world into it, went to the coordinates, all was fine. Then I swapped out the jar for 1.18 and ran with --forceUpgrade. After joining, all was fine with new generation below the water layer.

**Comment by Tsoccerguy3** [comment]
The Original map was generated in 1.16.5 with https://github.com/TerraForged/TerraForged . Then it was built on and updated over the last 2 years to 1.17.1 Paper. The settings used .
Forced sea level to 21 and limit max height of any land to 32 .

**Comment by Spottedleaf** [comment]
Please verify that you have _not_ used spigot for this process at all. I have a patch in paper that rewrites this process due to fact upstream has bugs in their process. One of which (not sure if fixed by them) can see causing some very fun problems with the new world height. But that problem doesn't exist on Paper. 

Secondly, please verify that you have NOT used a world-height modifying datapack for any terrain generated. The ONLY worldheights supported by Vanilla and Paper are the old [0, 255] world height and the new worldheight [-64, 319] (in certain versions ONLY). Nothing else at ALL is supported.

Since everyone testing this (including me) cannot reproduce, this will remain closed until it can be. If you can download the latest paper, run forceupgrade on the 1.17 world, and you still get these results, it can be re-opened.

**Comment by Tsoccerguy3** [comment]
Multiverse-Core-4.3.2-SNAPSHOT with CleanroomGenerator-2.0.3-SNAPSHOT , handles how world gen happens on our server . This was the problem . These need to be set to default generate settings and CleanroomGenerator needs to be disabled
