### ISSUE TITLE
Standardize configuration warnings/errors

### ISSUE THREAD

**Issue by e-im** [PaperSpigot/Paper#6998]
### Is your feature request related to a problem?

Warnings given for invalid configuration are very inconsistent, and sometimes nonexistent. This makes configuring the server harder. As of now it is [sometimes not clear that a message is from an invalid config at all](https://sirkillian.gg/i/4j324albit3s4n8u.png). This could easily be interpreted as "I have invalid data in my world" by some users.

### Describe the solution you'd like.

Standardize configuration log messages, make clear that they are from invalid configuration, if possible (depending on *how* the config is invalid) log exactly where in the config is invalid.

**Comment by rozalily** [comment]
I'm in favor of this, as I see a lot of plugin/mod author's time get wasted on cryptic error messages that are not even related to their plugin or mod. Anything that weakens the pipeline of "user makes a mistake setting up the server --> user tries to make it some random dev's problem" is a good feature in my opinion.
