### ISSUE TITLE
1.18 villagers won't spawn and animals spawn rate extremely low

### ISSUE THREAD

**Issue by uduntuntu** [PaperSpigot/Paper#7000]
### Timings or Profile link

https://timin.gs/?id=aaa30d6400594a5eb2aac985dcdd0ceb

### Description of issue

People are explored thousands of blocks and many villages. They haven't found any villager and sheeps have been extremely rare. I checked timings report and noticed that there was only zombie villagers in report whern searching "villager".

There have been dynmap fullrender ongoing, which have generated noticeable occasional lag spikes. Pebblehost 5,0 GHz server with 8 GB RAM.

### Plugin and Datapack List

[Server] INFO Plugins (4): BetterSleeping4, CoreProtect, dynmap, LuckPerms
[Server] INFO There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]

### Server config files

```
Paste configs or paste.gg link here!
```
https://p.kapsi.fi/?18028739d331b899#CS5MSUWiyTz6SdR4XJUTYMrzrxjQCyL8M4wNLF2HUizQ

### Paper version

[Server] INFO This server is running Paper version git-Paper-"956124f" (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 956124f)
[Server] INFO You are running the latest version
INFO Previous version: git-Paper-"0cd411e" (MC: 1.18)

**Comment by electronicboy** [comment]
Stuff like villagers are mostly added to the world during chunk generation, did you pregen the server? if so, any idea what version you pregen'd on?

**Comment by uduntuntu** [comment]
No I didn't. I just dropped current paper.jar and started server.

**Comment by Machine-Maker** [comment]
so I can't replicate this just plain generating a new 1.18 world, animals and villagers are fine. I'll try with converting a 1.17.1 world

**Comment by uduntuntu** [comment]
newly generated world. Just crashed twice when replacing 63x100 blocks with barrier.

**Comment by Machine-Maker** [comment]
> newly generated world. Just crashed twice when replacing 63x100 blocks with barrier.

This doesn't seem to have anything to do with the issue you reported here.

**Comment by e-im** [comment]
Both of these are done during world generation, with animals having extremely low natural spawns. You've likely disabled `spawn-npcs` and `spawn-animals` in server.properties (even though it is set to `true` in your paste) or similar-- cannot reproduce.
