### ISSUE TITLE
Antixray on paper.yml

### ISSUE THREAD

**Issue by comonier** [PaperSpigot/Paper#7005]
### Is your feature request related to a problem?

update it for negative camades 

### Describe the solution you'd like.

it is working only to camade 1 need upgrade it to work on camade -63

### Describe alternatives you've considered.

-

### Other

![image](https://user-images.githubusercontent.com/19571541/144610496-d3421d2a-c1ab-4ac4-ad6e-a7d807d46d6e.png)

**Comment by aurorasmiles** [comment]
See https://gist.github.com/stonar96/ba18568bd91e5afd590e8038d14e245e
Please join our Discord at https://discord.gg/papermc if you require further help
