### ISSUE TITLE
Villagers not sharing food

### ISSUE THREAD

**Issue by lennert05** [PaperSpigot/Paper#7008]
### Expected behavior

farmer villager sharing food with other villagers and breeding

### Observed/Actual behavior

villager looking at each other but not sharing

### Steps/models to reproduce

carrot farm with farmer villager and a stack of carrots and then wait till villager tries to share and nothing happens.

### Plugin and Datapack List

plugins: 
luckperms 5.3.86
essentialsXchat 2.19.1 dev 48
essentialsXprotect 2.19.1 dev 48
essentialsXspawn 2.19.1 dev 48

datapacks:
armorstatues 2.8.3
fast leaf decay 2.0.5
redstone rotation wrench 1.1.3
silence mobs 1.1.2
track raw statistics 1.5.1
track statistics 1.1.2

### Paper version

paper 1.18#25

### Other

Villagers are not in spawnchunks, mobGriefing gamerule is true.

**Comment by lynxplay** [comment]
Can you attempt to replicate this without any plugins, I have not been able to replicate this.
![image](https://user-images.githubusercontent.com/32834385/144684842-a6b9a259-52b5-4abe-90f2-6b5dc48ec4dc.png)


Note that food trading happens during gossiping which is mostly observed between the time `9000 - 11000`.

**Comment by lennert05** [comment]
Thank you for helping with the issue we have tried it again with a server restart and by afking for an hour by it and like you said we just didn't have enought patients and I think we must have fixed something by restarting the server.

So this issue can be closed thanks for the help again.
