### ISSUE TITLE
spectator mode teleport dosen't work

### ISSUE THREAD

**Issue by anberry87** [PaperSpigot/Paper#7015]
### Expected behavior

teleporting on spectator menu dosen't work

### Observed/Actual behavior

spectator should teleported to selected player

### Steps/models to reproduce

survival with no plugins, target player are both out of render and simulate distance of the spectator

### Plugin and Datapack List

none

### Paper version

1.18 - 24

**Comment by molor** [comment]
Can't reproduce on 1.18-32

**Comment by e-im** [comment]
What happens when you try to teleport? Is there anything in your logs? Is the spectator able to send chat messages/run commands?

**Comment by NoahvdAa** [comment]
Is your server behind Bungeecord/Waterfall? If you do, it's probably caused by SpigotMC/Bungeecord#3223.
