### ISSUE TITLE
Allow paper API to set player pose

### ISSUE THREAD

**Issue by WcaleNieWolny** [PaperSpigot/Paper#7016]
### Is your feature request related to a problem?

So, there is an api call to show the player position. But there is little to non control over player pose. I was trying to make a plugin heavily dependent on player swimming pose, so i googled it. After a short reaserch i found that there is no way to force a player pose other than sending a fake block packet. There is a setSwimming function but it does not work. There is a function in craftplayer to set pose. I used it in the past but even that set player position for 1 tick. There is curently no way to force player position.

### Describe the solution you'd like.

I would like to see some kind of api call that woudl set player position (just use setPose() from craftplayer). Optional i woudl like to see some kind of api call that woudl disable pose checking on every tick. Overall i think that it woudl make working with player possition mutch easier.

### Describe alternatives you've considered.

I used a packet modification that woudl send a swimming packet for other players on the server. However this solution did not change client hitbox serverside.

### Other

I woudl love some feedback on this. I coudl to try to implement this as PR. However i do not want to wase my time developing a feature that woudl not be implemented.

**Comment by WcaleNieWolny** [comment]
Since I did not revive any feedback I won't be implementing this.

**Comment by CDFN** [comment]
:(

**Comment by Chew** [comment]
This request was only open for a day, should leave it open long enough for someone to actually give feedback... (a lot of us are very busy)

**Comment by Phoenix616** [comment]
Someone please reopen this... don't see a reason why this should be closed or why a duplicate issue should be opened when this is written up quite well.

**Comment by WcaleNieWolny** [comment]
> Someone please reopen this... don't see a reason why this should be closed or why a duplicate issue should be opened when this is written up quite well.

Sure, if you think so I will reopen this.

**Comment by bluelhf** [comment]
This sounds like an useful API! I'd like to see this implemented :)

**Comment by LoaiDev** [comment]
This is used alot by other plugins outside the API so this could be really useful to implement

**Comment by WcaleNieWolny** [comment]
So, about that. I have implemented this using a ProtcolLib and I have found out that there is client side check for standing up. (Only for yourself) It might be tough to make an original player see it.

**Comment by Phoenix616** [comment]
Still not sure why API addition requests need to ever be marked stale...

**Comment by Chew** [comment]
If no one intends to attempt to implement it in a reasonable time (3 months) I'd be hard pressed to see if anyone ever will.

**Comment by Owen1212055** [comment]
See: https://github.com/PaperMC/Paper/pull/7318

**Comment by Chew** [comment]
Who didn't link it!

**Comment by LoaiDev** [comment]
I never understood why my pull request was not merged and hated by other members for just persisting the pose. instead of needing the plugin using the api to handle every entity load event to achieve the same result.

**Comment by electronicboy** [comment]
it's API, people disagreed on an aspect of the implementation, and rightly so; persisting stuff just because the API set it is pretty weird area and has wider implications on state that others might not be expecting over something that is usually never saved otherwise, we did present the option of adding a boolean to control that, but, generally people were busy, I was out dying, etc
