### ISSUE TITLE
Random errors crashing the server

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#7017]
### Stack trace

https://paste.gg/p/anonymous/9c08fa97ebdf42d59995d3729374e704

### Plugin and Datapack List

spark, my own plugin (only mysql and redis methods for discord verification)

### Actions to reproduce (if known)

none, happens randomly - even when being AFK

### Paper version

[09:40:47 INFO]: Checking version, please wait...
[09:40:48 INFO]: This server is running Paper version git-Paper-33 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 614ed1d)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-24 (MC: 1.18)

**Comment by Proximyst** [comment]
https://github.com/openjdk/jdk/blame/267c024eb52acd1611188dd5b1417b877ff3eafd/src/java.base/share/classes/java/util/random/RandomGenerator.java#L524
Your Java version is outdated... by many, many months.
