### ISSUE TITLE
Paper Server 1.18 experimental  Server Crash

### ISSUE THREAD

**Issue by H3ll5pawn** [PaperSpigot/Paper#7018]
### Expected behavior

mining /placing blocks in the nether.

### Observed/Actual behavior

while in the nether. if an item on your hotbar is removed through placing blocks and a stack running out or a tool breaking ect. the server crashes

### Steps/models to reproduce

break a tool while mining or place blocks until a stack is gone.

### Plugin and Datapack List

Plugins
World Border, Luckperms

Data Packs:
Vanilla Tweeks: afk display, coordinates hud, Double shulker shells, kill empty boats, More mob heads, multiplayer sleep, Player head drops, silence mobs, Track Raw statistics, Villager Death messages, Wandering Trades. 

### Paper version

This server is running Paper version git-Paper-15 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 4bfb8d7)
You are 21 version(s) behind
Download the new version at: https://papermc.io/downloads

installed through apex hosting console.

**Comment by NoahvdAa** [comment]
This is a known issue with build 15, update to the latest (36).

**Comment by H3ll5pawn** [comment]
Thank you! Appreciate the response!
