### ISSUE TITLE
Villager Collision Causes Massive Lagspikes

### ISSUE THREAD

**Issue by loocool2** [PaperSpigot/Paper#7032]
### Stack trace

https://paste.gg/2b01ae8f7e844e8e8a9d08701a5e9d5e

### Plugin and Datapack List

Plugins (14): ActualRAM*, Chunky, ChunkyBorder, CoreProtect, CrisTreeCapitator, DiscordSRV, DriveBackupV2, dynmap, LuckPerms, MOTD, spark, Stress, VeinMiner, Waystone

There are 12 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/VanillaTweaks_c769306.zip (world)], [file/custom nether portals v2.3.4.zip (world)], [file/fast leaf decay v2.0.5.zip (world)], [file/graves v2.8.5.zip (world)], [file/multiplayer sleep v2.6.2.zip (world)], [file/nether portal coords v1.1.2.zip (world)], [file/player head drops v1.1.2.zip (world)], [file/track raw statistics v1.5.1.zip (world)], [file/real time clock v1.1.2.zip (world)], [file/villager workstation highlights v1.1.2.zip (world)]

### Actions to reproduce (if known)

1. Go near some villagers 
2. Have them collide, or in my case, collide when sleeping
3. Wait a little bit, server begins to lag out

### Paper version

[14:31:30 INFO]: This server is running Paper version git-Paper-42 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: c3ff7e0)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-"6b072ee" (MC: 1.18)

### Other
Began to occur on build 41, issue does not occur after rolling back to build 40 

The build sent on discord fixed my issue, version is:
This server is running Paper version git-Paper-"6b072ee" (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 6b072ee)
You are running the latest version
Previous version: git-Paper-40 (MC: 1.18)

**Comment by electronicboy** [comment]
Update

**Comment by kennytv** [comment]
(but thanks for the report, will be used when the diff in question might be brought back)
