### ISSUE TITLE
Lectern broken hitbox

### ISSUE THREAD

**Issue by ssamjh** [PaperSpigot/Paper#7043]
### Expected behavior

Should be able to walk over or on a lectern.

### Observed/Actual behavior

See video: https://m.sjh.at/2021-12-06_18-07-00.mp4

Cannot walk across as the player is constantly teleported back.

### Steps/models to reproduce

Start server, place down lectern.

### Plugin and Datapack List

N/A

### Paper version

Paper version git-Paper-52 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: a50e273)

Also happening on 1.18.1:

Paper version git-Paper-68 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 1c779c2)

**Comment by Machine-Maker** [comment]
I confirmed this happens in 1.18, but doesn't happen after I removed both the following patches:
* `Highly optimise single and multi AABB Voxel Shapes`
* `Optimse collision checking in player move packet handler` <-- happens with just this patch removed too, but this patch relies on the one above

This doesn't happen in 1.17 with both of those patches applied

**Comment by cs8425** [comment]
Maybe this cause villager (Librarian) eat up lot of CPU? (pathfinding and can not move to target?)
I noticed that villager and `Minecraft::Behavior - assignprofessionfromjobsite` take ridiculous CPU time,
but if I break and replace lectern, it seems become OK.

timings:
https://timings.aikar.co/?id=920c8781ccde497fae58d8fe48af9673
The map was from 1.17, with lot of (~30) Librarian villager.

**Comment by Wesley51** [comment]
I was about to report an identical bug report. The same thing is happening to me on the latest version of 1.18-Experimental! (Currently build 58)

Video: https://youtu.be/Xte-PHmJnqE

**Comment by panchi64** [comment]
Can confirm it still happens on build 66 of 1.18

Video: [YouTube](https://youtu.be/mNAwY78A3AE)

**Comment by ALFR3D343** [comment]
And it still happens with build 73 of 1.18.1

**Comment by MWHunter** [comment]
https://github.com/PaperMC/Paper/blob/95d881f91681b2ff3a659578f42dd890f2b6ceec/patches/server/0825-Highly-optimise-single-and-multi-AABB-VoxelShapes-an.patch#L1472

Adding this code here should fix it
        if (maxX - minX < 1.0E-7D || maxY - minY < 1.0E-7D || maxZ - minZ < 1.0E-7D) {
            return empty();
        }

I just can't figure out how to use the patch system to PR it

**Comment by electronicboy** [comment]
Oh, interesting, I was looking at that patch last night a bit and was gonna, if I remembered (I totally forgot), to start looking deeper at what vanilla changed there

**Comment by NoahvdAa** [comment]
> I just can't figure out how to use the patch system to PR it

If you want help figuring out the patch system after reading the [contributing guide](https://github.com/PaperMC/Paper/blob/master/CONTRIBUTING.md), pop by the #paper-dev channel in [our Discord](https://discord.gg/papermc), we're happy to assist :)

**Comment by electronicboy** [comment]
Validated the fix, reverted back the vanilla check in the patch and attributed, thanks
