### ISSUE TITLE
Nether portal Teleport from Nether to normal world

### ISSUE THREAD

**Issue by ptrblauw** [PaperSpigot/Paper#7051]
### Expected behavior

Teleport from Normal World to Nether works fine
Teleport from Nether to Normal World teleports to my own created portal.

### Observed/Actual behavior

Teleport from Normal World to Nether works weird but after some sec i'm teleported to good portal.
Teleport from Nether to Normal World teleport to random new created portal in deep underground cave.

### Steps/models to reproduce

Paper server + No plugins (Vanilla), whitelist actived + anti-xray mode 

https://user-images.githubusercontent.com/93551960/144879923-f6daf70a-ca89-4891-87e5-46995a3cecc0.mp4

### Plugin and Datapack List

> plugins
[15:42:28 INFO]: Plugins (0):
> datapack list
[15:42:39 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[15:42:39 INFO]: There are no more data packs available
>

### Paper version

> version
[15:42:54 INFO]: Checking version, please wait...
[15:42:54 INFO]: This server is running Paper version git-Paper-54 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: b4a77a8)
You are running the latest version
Previous version: git-Paper-48 (MC: 1.18)
>

**Comment by e-im** [comment]
Your video isn't loading, but based on the description this would be a 

Duplicate of #6995

**Comment by ptrblauw** [comment]
Fixed Video.

**Comment by e-im** [comment]
Thanks-- you falling into the lava in the first bit is just the client ticking before it actually has the world. Returning and being in the cave would be #6995 

Thanks for the report regardless
