### ISSUE TITLE
[1.18] Simulation distance behaves differently than vanilla

### ISSUE THREAD

**Issue by Puremin0rez** [PaperSpigot/Paper#7054]
### Expected behavior

The various forms of ticking (block, fluid, entity, etc) to be respected when simulation distance is set (and behave closer to vanilla)

### Observed/Actual behavior

Some forms of ticking (such as fluids and redstone) happen regardless of simulation distance with Paper, which is not the same behavior as Vanilla.

### Steps/models to reproduce

I found it easier to demonstrate and explain the issue with voice over and a video

Vanilla behavior: https://www.youtube.com/watch?v=XY8AQFoaT0w

Paper behavior: https://www.youtube.com/watch?v=kABeLz6tcf8

### Plugin and Datapack List

No plugins or datapacks - all testing was done with a fresh instance of Vanilla and Paper.

### Paper version

This server is running Paper version git-Paper-55 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 0e25db2)

### Other

It looks like #7053 might address this issue? (edit: maybe not) I have not tested aforementioned PR.

It's also worth noting that it's quite odd that vanilla has the entity ticking and other forms of ticking be offset by a chunk from each other... I would expect simulation distance to apply to all forms of ticking equally just like leafs no-tick. I question if maybe Paper should make simulation distance behave better in this regard? (although if no-tick is coming back, might be pointless)

**Comment by Spottedleaf** [comment]
https://github.com/PaperMC/Paper/commit/758e2a7ee201ea2cdd446d2353437d2b4b03fb7d
