### ISSUE TITLE
Villager Breeder not working

### ISSUE THREAD

**Issue by samuelh-ta** [PaperSpigot/Paper#7056]
### Expected behavior

Villagers should breed when trading

### Observed/Actual behavior

They very very rarely do

### Steps/models to reproduce

Just make a villager breeder

### Plugin and Datapack List

Idk

### Paper version

idk

**Comment by Owen1212055** [comment]
Thanks for taking the time to fill out this report. This tells us nothing. Can you perhaps try filling in the fields with the relevant information? For example, paper version? (This can be retrieved via /version)

**Comment by e-im** [comment]
Please come by our [discord](https://discord.gg/papermc) for support.
