### ISSUE TITLE
Server Crash while pre-generating world 1.18

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#7057]
https://paste.gg/p/anonymous/a7c944d56f8d498dbfcb68f58b528848

**Comment by electronicboy** [comment]
You ran out of ram, potentially already a known issue in the pipeline, but, there is 0 info to go off here

**Comment by ghost** [comment]
thanks for the asnwer, is this issue related to my pc or a problem related to 1.18 experimental builds? Also when pregenerating a new world created using 1.18 this issue didn't happened, I don't know if this could help.

**Comment by electronicboy** [comment]
as I said, potentially an already known issue of which I think that there is a fix in the pipework for, but, there is not enough info here to say why it occurred and this is not the place for general support

**Comment by ghost** [comment]
got it
