### ISSUE TITLE
could not pass PlayerInteractEvent

### ISSUE THREAD

**Issue by Tithonius** [PaperSpigot/Paper#7065]
### Expected behavior

Using a chest sorting plugin called Vane, I expect to press a button next to a chest and the chest should get sorted.

### Observed/Actual behavior

an error in console and no result in game

[error.txt](https://github.com/PaperMC/Paper/files/7683989/error.txt)

### Steps/models to reproduce

after installing Vane and Paper, place a chest with a button next to it, and press the button. 

### Plugin and Datapack List

Paper, GriefDefender, Vane, Harbor

### Paper version

This server is running Paper version git-Paper-61 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 0e91b6a)
You are running the latest version
Previous version: git-Paper-47 (MC: 1.18)

### Other

Other client side mods that sort chests as well do not function, although they do not throw an error in the console

**Comment by electronicboy** [comment]
Speak to the plugin dev
