### ISSUE TITLE
Programmatic way to redstone-trigger blocks

### ISSUE THREAD

**Issue by jaylawl** [PaperSpigot/Paper#7073]
### Is your feature request related to a problem?

There currently is no non-hacky way to trigger blocks which may be triggered by redstone (or partially also by players clicking them).

For example:
- Making note blocks play
- Ringing bells
- Firing dispensers/droppers
- Powering pistons
- etc...

The `Powerable` class is not the solution to this. When using this and it's method `Powerable#setPowered`, the powered state is updated correctly - however doesn't work as one might intuitively expect, as it doesn't make the affected block do anything (note blocks don't play notes, bells don't ring, and so on...).

It seems like one always has to come up with workarounds for things like these, as per my previous research.

The method on the bottom of this class, for example, has to resort to simulating via usage of sound effects and packets: https://github.com/Vectole/Redstone-Bell/blob/master/redstone-bell/src/main/java/xyz/vectole/projects/redstonebell/OnInteractBell.java

### Describe the solution you'd like.

A simple method to trigger blocks.

For example: 
```
Block#trigger(boolean)
Block#toggle(boolean)
```

Which could simply silently fail in case it's not a block that has such functionality

The boolean could be a condition that checks for `Powered#isPowered` or to ignore it 

### Describe alternatives you've considered.

My current workaround is to place a redstone power source adjacent to the block i wish to trigger, for a duration of 0 ticks (immediatly revert back to the replaced block).

This works fine for "static" cases in which you know where things are powered. Using this dynamically is not an option though, because there may be other blocks adjacent to the power source, which may not be intended to be triggered.

**Comment by Chew** [comment]
I tried looking into this. It might be possible, but I just am not smart enough to figure it out 😂

**Comment by u9g** [comment]
would probably also be important to specify blockface

**Comment by electronicboy** [comment]
Issue here is that updates cascade, so, for the most part, this as-is is basically useless without something to act as a source or basically to hijack the logic for getting the power level to something else, I'm not even sure that a maintainable solution exists here
