### ISSUE TITLE
Feature Seed

### ISSUE THREAD

**Issue by HellRayka** [PaperSpigot/Paper#7077]
### Is your feature request related to a problem?

Protection against seed hacking

### Describe the solution you'd like.

A new open source project from the Plasmo team.
Matter is a fork of the Paper which adds one feature: Feature Seed with anti-hacking protection which is based
on the SecureSeed mod from Earthcomputer.
The generation of the landscape and biomes remains the same, but ores and structures are generated using 1024-bit seeds, instead
of the usual 64-bit seeds. This seed is almost impossible
to crack and there are no strange bindings between the generations
of different structures, like linking the generation of diamonds to clay.
Learn more: https://github.com/plasmoapp/matter

### Describe alternatives you've considered.

-

### Other

-

**Comment by Vaultling** [comment]
Yeah this would be great and if not then at least complete the current set of feature-seeds with the Mineshafts and Dungeons. I made an isssue about that here: #6978

**Comment by Chew** [comment]
We already have some forms of seed cracking prevention, there's already some config options with more proposed in the above issue. Closing as this is basically just an ad...
