### ISSUE TITLE
Build 1.17.1-399 crashes on one server after restore from backup

### ISSUE THREAD

**Issue by Thorkull** [PaperSpigot/Paper#7079]
### Stack trace

10.12 10:34:29 [Multicraft] Received start command
10.12 10:34:29 [Multicraft] Loading server properties
10.12 10:34:29 [Multicraft] Starting server!
10.12 10:34:29 [Multicraft] Loaded config for "Default Minecraft Server"
10.12 10:34:30 [Server] INFO Patching vanilla jar...
10.12 10:34:30 [Server] INFO Failed to read vanilla jar and patch file
10.12 10:34:30 [Server] INFO java.util.zip.ZipException: invalid stored block lengths
10.12 10:34:30 [Server] INFO at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
10.12 10:34:30 [Server] INFO at java.base/java.io.FilterInputStream.read(FilterInputStream.java:132)
10.12 10:34:30 [Server] INFO at io.papermc.paperclip.Paperclip.readFully(Paperclip.java:302)
10.12 10:34:30 [Server] INFO at io.papermc.paperclip.Paperclip.checkPaperJar(Paperclip.java:133)
10.12 10:34:30 [Server] INFO at io.papermc.paperclip.Paperclip.setupEnv(Paperclip.java:89)
10.12 10:34:30 [Server] INFO at io.papermc.paperclip.Paperclip.main(Paperclip.java:40)
10.12 10:34:30 [Multicraft] Server shut down (starting)
10.12 10:34:30 [Multicraft] Restarting crashed server in 5 seconds
10.12 10:34:30 [Multicraft] Stopping server!
10.12 10:34:32 [Multicraft] Looks like a crash, check the server console. Return value: 1
10.12 10:34:32 [Multicraft] Server stopped

### Plugin and Datapack List

BanManagerBukkit.jar
Brewery-3.1.jar
BungeeGuard.jar
ChestShop.jar
ConsoleSpamFix-1.8.6.jar
CoreProtect-20.1.jar
DriveBackupV2.jar
EssentialsX-2.19.0.jar
EssentialsXChat-2.19.0.jar
EssentialsXSpawn-2.19.0.jar
F3NPerm-2.7.1.jar
FastAsyncWorldEdit-Bukkit-1.17-418.jar
GriefPrevention.jar
HolographicDisplays.jar
LuckPerms-Bukkit-5.3.87.jar
MarriageMaster.jar
MCLink-Bukkit-0.3.2.17.jar
mcMMO.jar
RentIt-2.4.10.jar
SimplePortals-1.6.7.jar
spark.jar
TimeIsMoney-1.9.6.22.jar
Vault.jar
ViaVersion-4.1.1.jar
ViewDistanceTweaks-1.3.4.jar
worldguard-bukkit-7.0.6-dist.jar

### Actions to reproduce (if known)

Just switching paper from 1.17.1-398 to 1.17.1-399 causes the crash.

### Paper version

paper-1.17.1-399

### Other

Trying to patch for Log4Shell vulnerability, worked fine on all my other servers but this one just keeps crashing. Only two differences:

1) Some additional plugins on this server. I tried disabling them but no change. Also tried without any plugins, still crashing.
2) Due to an unrelated issue, I had to restore this world from backup yesterday. Originally it wouldn't load because file ownership on the world files was incorrect. I resolved that, but now it's getting the "invalid stored block lengths" on 399.

**Comment by electronicboy** [comment]
delete the cache folder and try again, otherwise your jar is bork

**Comment by Thorkull** [comment]
It was the .jar file, even though I copied the same file to each of our
server directories. Thanks!
