### ISSUE TITLE
EntityInsideBlockEvent should trigger for some more blocks

### ISSUE THREAD

**Issue by jaylawl** [PaperSpigot/Paper#7082]
### Is your feature request related to a problem?

https://papermc.io/javadocs/paper/1.17/io/papermc/paper/event/entity/EntityInsideBlockEvent.html

It appears that this event does not trigger when an entity is "using" ladders and i suggest that it should. I have tested this by spawning an armor stand above ladders, letting it fall down into the ladders and waiting for a System.out.println() in the event listener. Nothing happened

Additionally, vine type blocks would make sense here too - i think. Although i have not tested for those.

### Describe the solution you'd like.

Let EntityInsideBlockEvent fire for entities affected by ladder blocks (and maybe vines, too)

### Describe alternatives you've considered.

Sorry, I wouldn't know any 😮‍💨

**Comment by Owen1212055** [comment]
The thing about this is that these are two different things. 
Climbing is handled by a ``climbable`` block tag, and if a player is jumping near the block will cause them to go up. They aren't exactly "inside" the block like the event may suggest.

I would think that an alternative event would be better here?

**Comment by jaylawl** [comment]
> The thing about this is that these are two different things. Climbing is handled by a `climbable` block tag, and if a player is jumping near the block will cause them to go up. They aren't exactly "inside" the block like the event may suggest.
> 
> I would think that an alternative event would be better here?

Aye, sounds good to me too. :-)
