### ISSUE TITLE
Adding the Code of Conduct

### ISSUE THREAD

**Issue by FahimFBA** [PaperSpigot/Paper#7087]
### Is your feature request related to a problem?

No. As many repositories are adding the Code of Conduct in their root branch, and yours are missing currently. I thought about whether you want that or not. 

### Describe the solution you'd like.

If you like, then I can submit a PR including the Code of Conduct. Then, I would need a contact address (email address) that would get enlisted within the Code of Conduct file.

### Describe alternatives you've considered.

Not like that. I just thought that it might be possible that you haven't thought about having a Code of Conduct earlier.

**Comment by electronicboy** [comment]
We already have our community guidelines posted on the site?

**Comment by FahimFBA** [comment]
Oh, yeah. I just realized that. Anyway, then I guess I should close this issue now.
