### ISSUE TITLE
1.18 - 1.18.1 the problem from which the time loop appears

### ISSUE THREAD

**Issue by Lyten02** [PaperSpigot/Paper#7088]
### Timings or Profile link

https://youtu.be/RT7xDzlvyUQ

### Plugin and Datapack List

No plugin

### Server config files

```
Paste configs or paste.gg link here!
```

### Paper version

1.18.1

**Comment by NoahvdAa** [comment]
Please provide your actual logs and plugin list

**Comment by electronicboy** [comment]
Please fill out the issue properly, making sure to provide everything asked for. This is not a performance issue.

**Comment by Lyten02** [comment]
The problem appeared yesterday when I often restarted the server after that I exited the server did not turn off. And today, when I go to the server, it teleports me to the place where I left. After that, it stopped creating player data.
I thought that the problem was in the plugins and decided to remove them if: ProtocolLib, SkinsRestorer, LuckPerms-Bukkit-5.3.86, voicechat-bukkit-1.
18-2.1.20, CoreProtect-20.1

**Comment by Lyten02** [comment]
[latest.log](https://github.com/PaperMC/Paper/files/7697748/latest.log)
