### ISSUE TITLE
Getting achievements

### ISSUE THREAD

**Issue by CodenBeast** [PaperSpigot/Paper#7091]
### Expected behavior

I expect to only get the inital achievment get message per achievement.

### Observed/Actual behavior

But im actually getting the achievements several times, for the same achievement. Multiple times. For example monster hunter, Istn it iron pick, acquire hardware etc,

### Steps/models to reproduce

Join server, get achievement. Keep on playing, its a bit random, but stuff like doing the achievement again can trigger it. Sometimes you dont even have to do anything.

### Plugin and Datapack List

dynmap, secureserverbackup, serveressentials, ultimateautorestart, worldedit.

No datapacks.

### Paper version

This server is running Paper version git-Paper-66 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: dce79f3)
You are running the latest version
Previous version: git-Paper-349 (MC: 1.17.1)

**Comment by Machine-Maker** [comment]
Do you have `advancements.disable-saving` set to true in your spigot.yml?
or `players.disable-saving` in the spigot.yml set to true?

If not, try to replicate this without plugins as I can't replicate it myself

**Comment by e-im** [comment]
Unable to reproduce, see MM's comment.
