### ISSUE TITLE
Increased memory usage when loading old chunks

### ISSUE THREAD

**Issue by pop4959** [PaperSpigot/Paper#7094]
### Timings or Profile link

N/A

### Description of issue

For chunks generated in the latest version of Paper-1.17.1-399 and subsequently loaded using Paper-1.18.1-69, memory usage rapidly increases until the server crashes. This only happens the first time these chunks are loaded.

It is possible to reproduce this issue easily without any plugins installed, but it occurs much more quickly when using a plugin to load the chunks.

To reproduce (without any plugins):
- Create a world in 1.17.1 and generate some chunks. For my testing I loaded between -1000, -1000 and 1000, 1000.
- Load the world in 1.18.1 and get in-game. Using spectator mode, fly through all of the chunks.
- Memory usage increases until the server crashes. This will happen after just a few minutes with a 4GB heap allocated.

It's also convenient to have the server GUI open to view the memory graph as this is occurring:

![40a3bc6a-3c94-4cef-9d13-8f2e96b63706](https://user-images.githubusercontent.com/17698576/145698343-bc4b63e2-4082-4ee0-a53f-ddafafb1b3c6.png)

### Plugin and Datapack List

```
> plugins
[18:22:25 INFO]: Plugins (0):
> datapack list
[18:22:33 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[18:22:33 INFO]: There are no more data packs available
```

### Server config files

Default configuration for everything, except for level-seed (mentioned below).

### Paper version

```
> version
[18:26:18 INFO]: Checking version, please wait...
[18:26:19 INFO]: This server is running Paper version git-Paper-69 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 29bd57b)
You are running the latest version
Previous version: git-Paper-68 (MC: 1.18.1)
```

### Other

Used `level-seed=8190275241236263855` for consistent results while testing.

**Comment by electronicboy** [comment]
Im going bed, but, I had a "quick" look at a dump and proto chunks are 100%
spilling out somewhere, was seeing them running through the blender stuff

**Comment by Uharn** [comment]
i've been trying to alert the community for days about that issue! so YEAH i can confirm it!

**Comment by KaspianDev** [comment]
fixed in 22w03a
