### ISSUE TITLE
Paper Crash: Standing/flying in a certain biome/chunk.

### ISSUE THREAD

**Issue by Shorxy** [PaperSpigot/Paper#7095]
### Stack trace

https://pastebin.com/P1655NDY

### Plugin and Datapack List

![2021-12-12_03 55 57](https://user-images.githubusercontent.com/95992343/145699674-8bd364c8-efc1-46a2-b6c7-406417fcf0c7.png)
![2021-12-12_03 55 51](https://user-images.githubusercontent.com/95992343/145699697-6db05287-333d-467f-a4e3-bfa2035041f7.png)

### Actions to reproduce (if known)

go to Seed: [-3075197535731685342] and tp to -920 67 665 and start flying and moving around, that is how I was able to reproduce it. 

### Paper version

[23:05:25 INFO]: This server is running Paper version git-Paper-69 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 29bd57b)
You are running the latest version
Previous version: git-Purpur-1433 (MC: 1.18)

**Comment by jpenilla** [comment]
https://github.com/PaperMC/Paper/issues/7062 duplicate

update java
