### ISSUE TITLE
NetherPortal Memory problem

### ISSUE THREAD

**Issue by MrEDok** [PaperSpigot/Paper#7098]
### Description of issue

When entering a netherportal memory usage increase by ALOT 1-1.5 GB and this have cause some of the lag from GC and sometime Oldgen on the server.

in video: https://streamable.com/uw1k2n

when i spam /spark healthreport you can see that
before entering the portal memory is at 3GB and 0.5-1 seond before entering memory shot up to 4GB which seem very strange and when player running this type of "farm" obsidian farm which entering the portal over and over again it cause the server to lag and sometime OOM.

i have only test this on 1.17.1 and 1.18.1

### Plugin and Datapack List

Plugins (3): LagMonitor, spark, WorldEdit

### Server config files

```
Paste configs or paste.gg link here!
```

### Paper version

This server is running Paper version git-Paper-71 (MC: 1.18.1)

**Comment by electronicboy** [comment]
for stuff like this, you'd need to look at a heap dump, timing reports, etc, are useless

**Comment by MrEDok** [comment]
From some testing i did today i got this
Test info: all config are default, there only 2 player 1 is afk in overworld and 1 going throught the portal (have also tested to load the nether side with another player but the problem is still there)

![image](https://user-images.githubusercontent.com/57065626/146681308-41894f13-3fd8-436f-9d84-8c9dc50aa0cd.png)

[FARM] is obsidian farm which player going in and out of nether portal from ow-->nether-->ow-->nether in a loop


and heapdump on the largest object
![image](https://user-images.githubusercontent.com/57065626/146681319-675a1f76-e2e3-4f56-84fd-c01e9b8ed473.png)


this issue still happen on **This server is running Paper version git-Paper-81 (MC: 1.18.1)**

GClogs: 
[gc.log](https://github.com/PaperMC/Paper/files/7741102/gc.log)

**Comment by ghost** [comment]
Apparently this happens since version 1.8, based on: https://github.com/Poweruser/Minetick/blob/master/CraftBukkit-Patches/0017-Fix-Insane-Nether-Portal-Lag.patch

**Comment by PonyPC** [comment]
1.18.2 still have this problem
