### ISSUE TITLE
Falling through world when joining in loaded chunks. Chunks loaded by another player.

### ISSUE THREAD

**Issue by Anton-Murer** [PaperSpigot/Paper#7100]
### Timings or Profile link

https://timings.aikar.co/?id=2045fcad7e864387a48426a9c0cff852

### Description of issue

When I join a server where a friend of mine already loaded the chunks in the area I am spawning in, I fall through the world. I either get stuck in some blocks (I dont take damage), or I fall below bedrock level. After 15 - 30 seconds I actually spawn where I am supposed to join. When I join the server and I spawn in an unloaded Chunk (no other players nearby) the world loads instantly and I don´t experience any lag whatsoever. It doesn´t matter when other players are on the server its only important that they dont load the chunks I am spawning in. The issue doesn´t occur on a 1.17.1 paper server with the same settings (some settings changed because of 1.18). The issue also occurs when going to the nether but its not that bad and when joining the end you barly notice it.

### Plugin and Datapack List

Chunky, CoreProtect, OpenInv, sleep-most, PlayTimes, SpigotPing, WorldEdit, WorldGuard

Also recreated on a server without plugins

### Server config files

bukkit: https://paste.gg/p/anonymous/3843a8135e8449978e78879ba203f295
spigot: https://paste.gg/p/anonymous/730a3e009a6047d0833cbf062cbd87cd
paper: https://paste.gg/p/anonymous/9a34ccedd2544b05a94ea027c1f34d6f
server properties: https://paste.gg/p/anonymous/2d6ec25d50994681be7b96c597767423

### Paper version

This server is running Paper version git-Paper-71 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 91f3eda)
You are running the latest version
Previous version: git-Paper-66 (MC: 1.18)

### Other

![2021-12-12_15 36 12](https://user-images.githubusercontent.com/57632476/145716888-3a8f0ce9-5034-43e9-9f20-d01ec1244e84.png)

**Comment by electronicboy** [comment]
We have 0 control over this as this is 100% client sided

**Comment by electronicboy** [comment]
generally, ref #895
