### ISSUE TITLE
Random Crash during the day

### ISSUE THREAD

**Issue by johnsudaar** [PaperSpigot/Paper#7101]
### Stack trace

https://paste.gg/p/anonymous/9cd53671c16541658e809e9d0cf6c5ef

### Plugin and Datapack List

Plugins:
```
Balerion, CMILib, CustomNpcs, DisableKeepInventory, FastChunkPregenerator, GriefPrevention, HolographicDisplays, Jobs, LogBlock, MinewebBridge, Moderation, MysqlPlayerDataBridge, MysteryBox, OreAnnouncer, PassSleep, PlayerGameplay, [REDACTED], [REDACTED], [REDACTED], [REDACTED], [REDACTTED], [REDACTED]Economy*, [REDACTED], [REDACTED], ServerConfig, ShopManagement, ShulkerColor, spark, [REDACTED], TutorialKit, Vault, WorldEdit, WorldGuard, ZoneTps
```

Data Packs:
```
[vanilla (built-in)], [file/bukkit (world)]
```

### Actions to reproduce (if known)

Unknown

### Paper version

This server is running Paper version git-Paper-65 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 4e355c4)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-47 (MC: 1.18)

### Other

I redacted the name of some custom plugins that were in the list of plugins, if it's an issue, contact me.

I tried to teleport to the location of the cat entity after a reboot and there was 5 cats but nothing seemed wrong.

I'm available if you need more informations.

PS: Thanks a lot for your awesome work !

**Comment by Chew** [comment]
Your server took too long to tick. The cat probably got caught in the crossfire. Would recommend hopping onto [Discord](https://discord.gg/papermc), updating (as you are several builds behind now, including a minor update), and preparing a `/timings report` for us to inspect.
