### ISSUE TITLE
Resourcespacks not loading in 1.18.1

### ISSUE THREAD

**Issue by celophys** [PaperSpigot/Paper#7109]
### Expected behavior

When entering the server, it should ask you to install the resource pack

### Observed/Actual behavior

Unlike version 1.18, the resoucespacks do not loads in 1.18.1

### Steps/models to reproduce

Upload a texture to dropbox or google drive and put the direct download link in the server settings

### Plugin and Datapack List

None

### Paper version

paper-1.18.1-73

**Comment by Machine-Maker** [comment]
Have you declined the resource pack before? You might need to on your client go onto the server listing and edit it to prompt for resource packs again.

**Comment by NoahvdAa** [comment]
Dropbox and Google Drive don't provide *direct* links to downloads (read: without redirecting first), which is why the Minecraft client won't download them properly (it'll download the redirection page).

**Comment by Machine-Maker** [comment]
> Dropbox and Google Drive don't provide direct links to downloads (read: without redirecting first), which is why the Minecraft client won't download them properly (it'll download the redirection page).

I assumed they were using smth that works as they implied whatever they were doing worked in 1.18

**Comment by celophys** [comment]
I used this link for the texture, before updating paper to 1.18.1 it worked; https://www.dropbox.com/s/qfdesl4liw8avxd/CelophyServerPacks.zip?dl=1

**Comment by celophys** [comment]
And yes, i have edited the server listing, my users have the same problem with the file not downloading

**Comment by Chew** [comment]
Dropbox links work when you have `?dl=1` as shown above.

I also cannot reproduce this on a brand new Paper 1.18.1, build 73 server. 

![image](https://user-images.githubusercontent.com/8278263/145881983-213b6d74-eca2-4a4d-a6be-4d46ab1d1e6e.png)

Config:
```
resource-pack=https\://dropbox.com/s/qfdesl4liw8avxd/CelophyServerPacks.zip?dl\=1
```

**Comment by celophys** [comment]
yes I know, that's the link I use in the server properties file

**Comment by NoahvdAa** [comment]
> I assumed they were using smth that works as they implied whatever they were doing worked in 1.18

Gotcha, after re-reading the question I realized that the "Do you want to install the server pack" prompt doesn't appear, which should still happen even if the download link is invalid.

I also cannot reproduce this. When using the same resource-pack entry in server.properties as chew, the pack downloads fine for me in 1.18 and 1.18.1.

**Comment by electronicboy** [comment]
The server just sends a packet to the client with the URL and hash if provided, it's 100% on the client past that; check the client logs, etc

**Comment by celophys** [comment]
Ok thanks, i will try to resolve
