### ISSUE TITLE
Please update OSHI/Oshi-core to the latest version

### ISSUE THREAD

**Issue by MegaAlen** [PaperSpigot/Paper#7113]
### Is your feature request related to a problem?

Yes. Everytime i start up a server oshi-error comes up

### Describe the solution you'd like.

Update oshi/oshi-core to the latest version for paperspigot

### Describe alternatives you've considered.

-

### Other

-

**Comment by MegaAlen** [comment]
![Posnetek zaslona (178)](https://user-images.githubusercontent.com/4885205/145906700-cb4ba18e-8683-46f4-a3ed-34fa4112979c.png)

**Comment by MegaAlen** [comment]
I'm using latest version of Paper as of 13/12/2021. Latest version of Java 17 and latest version of Windows 10

**Comment by Machine-Maker** [comment]
Latest is not a version, what mc version, what build of that version?

**Comment by MegaAlen** [comment]
I'm using 1.18.1 version of MC, 1.18.1 #74 version of Paperspigot

**Comment by e-im** [comment]
Could you point to where oshi has fixed this? I don't see any issue/commit related to this on a version above what is currently used (5.8.2), although I may have missed something.

**Comment by e-im** [comment]
Closing due to lack of response

**Comment by MegaAlen** [comment]
Sorry for inactivity, I have been bussy with work. I will pinpoint some links for future references: :)

- https://bugs.mojang.com/browse/MC-228430
- https://github.com/oshi/oshi/issues/1661

**Comment by e-im** [comment]
Thanks-- but what you've linked there is already included in release 5.8.2 which is what paper (and Mojang) currently use. Generally, we try to stay consistent with Mojang, however, if there is any commit that does fix this issue in a future version then I don't see why it couldn't be bumped. I just don't think updating oshi will actually fix this issue

**Comment by MegaAlen** [comment]
Hi guys/developers/server owners!

If anyone is reading this I can confirm a bugfix! This is an issue with WINDOWS/MICROSOFT! 

I fixed this by following steps in this tutorial/guide: https://social.technet.microsoft.com/wiki/contents/articles/19374.windows-performance-monitor-unable-to-add-these-counters.aspx

You basically just need to add counters to your windows performance monitor!

Thank you for your cooperation and happy and peaceful holidays!
