### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by exca64** [PaperSpigot/Paper#7121]
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
https://paste.gg/p/anonymous/6a4e42c0a7ae453f932f5938391f860a

### Plugin and Datapack List

AuthMe, DeadChest, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, GriefPrevention, HolographicDisplays, LuckPerms, mcMMO, PluginManager, ProtocolLib, SkinsRestorer, TAB, Vault, WorldEdit, WorldGuard

### Actions to reproduce (if known)

Mostly loading chunks.

### Paper version

This server is running Paper version git-Paper-74 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 7f31095)

**Comment by Titaniumtown** [comment]
> AuthMe... SkinRestorer

**Comment by e-im** [comment]
Please post full logs to our [discord](https://discord.gg/papermc).
