### ISSUE TITLE
option to let entities going through nether portals load chunks and be temporarily exempt from despawning

### ISSUE THREAD

**Issue by hirata-estate** [PaperSpigot/Paper#7122]
### Is your feature request related to a problem?

Guardian farms that use a nether killing chamber currently don't work on my server (not specifically guardians)
They go through the portal, then immediately despawn.
I have tried going on the other side and afking there too (alongside an account in the overworld) which works, but no drops show up when I don't afk there. Going into spectator & enabling vanish shows that the entities go through the portal and despawn immediately.

### Describe the solution you'd like.

This configuration in paper.yml:
```
portals:
 load-on-entity-pass: true/false
 load-distance: int
 load-ticks: int
```
Load ticks being how long the chunks are loaded for.
Load distance is how many blocks & entities in a (load-distance) radius from the portal are loaded.

Exact behavior:
Entities going through a portal will temporarily load the chunks and not despawn for (load-ticks) ticks.

Potential optimizations?:
If a portal is being constantly loaded within 3 seconds (e.g. the guardians going through, dying, and another set coming through again) always load the portal and check in 15 second intervals whether it still gets loaded. Same concept as villager lobotomization in purpur.

### Describe alternatives you've considered.

I currently have not yet found an alternative to fix this.
Players currently use an alt account to afk on the other side too, if that counts.

### Other

If there is already an issue about this or a fix, please tell me as I couldn't find any when I checked.

**Comment by ghost** [comment]
This is usually down to player despawn ranges while others are in the nether. If someone happens to be further than 128 blocks from the kill chamber they despawn instead of dying, and the only thing you can do is have multiple accounts there, or choose to afk at times when you're alone. I don't really think this is a viable option, as you could also use a chunk loader.

**Comment by e-im** [comment]
If this behaviour is present on paper servers and not vanilla servers that would be a bug, so adding a feature to explicitly mitigate that does not make much sense. For a previous report of this, see #6632, although that was not reproducible. Would you be able to try on a fresh server with no plugins or datapacks installed and see if the same behaviour persists?

**Comment by ghost** [comment]
> If this behaviour is present on paper servers and not vanilla servers that would be a bug, so adding a feature to explicitly mitigate that does not make much sense. For a previous report of this, see #6632, although that was not reproducible. Would you be able to try on a fresh server with no plugins or datapacks installed and see if the same behaviour persists?

Ive tested this various times with Portal based Guardian farms, slime farms, ghast farms, and Gold farms. All work as intended, when you're alone farms work as intended, if a player is within 128 blocks all good, outside of that mobs despawn if the other player is > 128 blocks away. I think the OP was asking for an option to see if Paper could implement a check for if an entity goes through the portal, the chunk loads the area for x amount of time, then unloads, however if theres a stream of entities flying through which farms do, the chunk would stay loaded. He can reproduce this by either just creating a chunk loader, or doing what hes doing and afking with multiple accounts.

EDIT: could also use /forceload i guess

**Comment by e-im** [comment]
Duplicate of #6456
