### ISSUE TITLE
Increase the number of Map IDs from 32,768 for servers stuck on older versions of Minecraft.

### ISSUE THREAD

**Issue by strunberg** [PaperSpigot/Paper#7133]
### Is your feature request related to a problem?

Due to performance issues many servers can't update which opens the door to malicious  players potentially wiping map art by duping maps, which has happened many times in the past.

### Describe the solution you'd like.

https://youtu.be/jUEYVVdmcHU?t=253

### Describe alternatives you've considered.

None. It's a fundamental issue with the code but was eventually patched with a minecraft update, but servers are unable to update either due to performance related issues, or because players like older version of minecraft.

**Comment by electronicboy** [comment]
given that the server now uses ints and has for a few versions, am guessing this is not a feature request for a version of paper which is supported anymore
