### ISSUE TITLE
failed main thread check

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#7137]
### Expected behavior

Normal server shutdown

### Observed/Actual behavior

See https://paste.gg/p/anonymous/cea81e06151641859f447ee1c8149ca9

### Steps/models to reproduce

Start the server and after it begins plugins loading, but before it is finished, press CTRL+C, so the server will start shutdown immediately after it finishes loading and enabling

### Plugin and Datapack List

```
[17:55:05] Plugins (18): AutoMessage, Chunky, ChunkyBorder, CoreProtect, dynmap, Essentials, EssentialsGeoIP, EssentialsSpawn, LuckPerms, MobArena, NoCheatPlus, OpenInv, Orebfuscator, ProtocolLib, TitleManager, Vault, WorldEdit, WorldGuard
```
```
[17:54:21] There are 2 data packs enabled: [vanilla (built-in)], [file/Bukkit (world)]
[17:54:21] There are no more data packs available
```

### Paper version

```
[17:54:39] This server is running Paper version git-Paper-81 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 8c189d0)
You are running the latest version
```

**Comment by LangerFlorian** [comment]
I can't reproduce the issue, my observed behaviour:

**Before plugin loading:** immediate shutdown
**During/after plugin loading:** server continues loading plugins and shuts down cleanly (disabling plugins, saving players and world) 

Version: 1.18.1, Build 81
Plugins: dynmap

**Comment by molor** [comment]
Hmmm seems that this is world-related problem,
I can reproduce this with empty plugins folder too if press CTRL+C right after `> ` is appear in console window..

Unable to reproduce with new generated world, but the old world is from 1.17.1 and it loads fine, but the described exception appears

**Comment by molor** [comment]
I can reproduce this with this world. Press CTRL+C immediately after `Preparing level "sadness"` appears.
[sadnesss.zip](https://github.com/PaperMC/Paper/files/7739909/sadnesss.zip) (~7 MiB)

**Comment by electronicboy** [comment]
it's down to specific mobs which do specific things during loading, i.e. the wolf tryna work out who it's angry at
