### ISSUE TITLE
Paper does not use threads that it can use

### ISSUE THREAD

**Issue by maityyy** [PaperSpigot/Paper#7140]
### Is your feature request related to a problem?

If the server has 4 threads, paper will use only one. This is a huge loss in potential performance improvement.

### Describe the solution you'd like.

The problem is with this patch. In my opinion, it should be removed.
https://github.com/PaperMC/Paper/blob/master/patches/server/0783-Reduce-worldgen-thread-worker-count-for-low-core-cou.patch

### Describe alternatives you've considered.

It might be worth using all threads, but leaving 1 for the OS if there are more than 7.

**Comment by jpenilla** [comment]
https://github.com/PaperMC/Paper/issues/7139#issuecomment-997273599
