### ISSUE TITLE
unable to load unvisited chunks in 1.18 that were imported from 1.17

### ISSUE THREAD

**Issue by NeumimTo** [PaperSpigot/Paper#7144]
### Expected behavior

chunkCache.getChunkAtAsynchronously is unable to load chunks that were generated in 1.17 migrated to 1.18 but not yet visited by players ingame

### Observed/Actual behavior

The behavior in 1.17 was that it was able to load any existing chunk

### Steps/models to reproduce

```Java
 Bukkit.getScheduler().scheduleAsyncDelayedTask(plugin, () -> {
            

            ServerLevel serverLevel = toNMSWorld(world);
            ServerChunkCache chunkCache = serverLevel.getChunkSource();
            final CompletableFuture<Either<ChunkAccess, ChunkHolder.ChunkLoadingFailure>> future = chunkCache.getChunkAtAsynchronously(
                    center.getBlockX(), center.getBlockZ(), false, true);
            while (!future.isDone()) {
                        //
            }
            Either<ChunkAccess, ChunkHolder.ChunkLoadingFailure> result = future.join();
            result.left().ifPresent(chunkAccess -> {
                System.out.println("Chunk loaded " + chunkAccess.locX + ", " + chunkAccess.locZ);
            });
            result.right().ifPresent(chunkLoadingFailure -> {
                System.out.println(chunkLoadingFailure.toString());
            });
        });
```      

Run the code on a command, 
>On 1.17 generate world (-500 to 500 block area around spawnpoint will work, so make sure its somewhat larger)
>Migrate to 1.18
>Lets say your 1.17 world is 2000 blocks in radius. lets say we will test chunk x -1 z 120
>You run the command and get UNLOADED (chunk loading failure)
>Login
>Teleport to -16 100 1920
>Log off
>Run the code again and you get Chunk loaded -16 1920

### Plugin and Datapack List

mandatory field...

### Paper version

[22:53:41 INFO]: Checking version, please wait...
[22:53:41 INFO]: This server is running Paper version git-Paper-81 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 8c189d0)
You are running the latest version
Previous version: git-Paper-401 (MC: 1.17.1)

**Comment by kennytv** [comment]
1) don't do that asynchronously (even if the method itself there reschedules)
2) use api, or at least reproduce the issue with api; we do not offer support for random internal method that have very specific uses
