### ISSUE TITLE
unable to load unvisited chunks in 1.18 that were imported from 1.17

### ISSUE THREAD

**Issue by NeumimTo** [PaperSpigot/Paper#7145]
### Expected behavior

This is continuation from https://github.com/PaperMC/Paper/issues/7144 but reproduced with bukkit api

 getChunkAtAsync is unable to load chunks that were generated in 1.17 migrated to 1.18 but not yet visited by players ingame

### Observed/Actual behavior

The behavior in 1.17 was that it was able to load any existing chunk

### Steps/models to reproduce

```Java
CompletableFuture<Chunk> future = world.bukkit().getChunkAtAsync(center.getBlockX(), center.getBlockZ(), false, true);
        Bukkit.getScheduler().scheduleAsyncDelayedTask(plugin, () -> {
            while (!future.isDone()) {

            }
            Chunk result = future.join();
            System.out.println(String.valueOf(result));
        });
```       

Run the code on a command,

On 1.17 generate world (-500 to 500 block area around spawnpoint will work, so make sure its somewhat larger)
Migrate to 1.18
Lets say your 1.17 world is 2000 blocks in radius. and we will test chunk x -1 z 120
You run the command and get null (chunk loading failure)
Login
Teleport to -16 100 1920
Log off
Run the code again and you get a chunk instance

### Plugin and Datapack List

mandatory field ...

### Paper version

[22:53:41 INFO]: Checking version, please wait...
[22:53:41 INFO]: This server is running Paper version git-Paper-81 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 8c189d0)
You are running the latest version
Previous version: git-Paper-401 (MC: 1.17.1)

**Comment by kennytv** [comment]
The reason this doesn't work is that unvisited 1.17 chunks are indeed not fully generated, since it will have to go through proper generation steps and add new caves below y 0. So technically, this is not a bug but expected (and necessary) behavior. Either we need to add new API to check for this specifically or you need to find another way of checking if a chunk "exists" but is not fully generated

**Comment by kribjo** [comment]
Would this work if --forceUpgrade was used first?

**Comment by MiniDigger** [comment]
most likely, but we discourage usage of that as it comes with its own set of problems
