### ISSUE TITLE
Villager discounts only appear for player who cured the villager

### ISSUE THREAD

**Issue by braydofficial** [PaperSpigot/Paper#7148]
### Expected behavior

Every player should get the trading discount after a villager has been cured.

### Observed/Actual behavior

The villager discount only appears for the person who cured the villager. Other players see the original price. No matter how often you cure the villager. 

### Steps/models to reproduce

Infect a villager with a zombie, cure the zombie villager and check the discount. The discount appears if you cured the villager. For another player it will not appear.

### Plugin and Datapack List

Plugins (18): ABCoreLib, ABPresent, AnarchyStats, AntiNetherRoof*, AureliumSkills, ChestSort, CMILib, CoreProtect, CraftingStore, dynmap, KillCounter, LevelledMobs, LuckPerms, NexEngine, PlaceholderAPI, ProtocolLib, Vault, VaultChatFormatter*, CanrealAPI, CanrealSystem

There are 5 data packs enabled: [vanilla (built-in)], [file/treecapitator-v2-7-2.zip (world)], [file/BlazeandCaves Advancements Pack 1.13.zip (world)], [file/Terralith_v2.0.3_Seed_3600591652096326474.zip (world)], [file/bukkit (world)]

### Paper version

[21:52:38 INFO]: Checking version, please wait...
[21:52:39 INFO]: This server is running Paper version git-Paper-82 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 8c5be16)
You are running the latest version
Previous version: git-Paper-76 (MC: 1.18.1)

**Comment by e-im** [comment]
This is correct behaviour; if you would like it, you would need to implement it with a plugin or datapack.
