### ISSUE TITLE
/locate broken after 1.18.1 update on all chunks loaded before paper-82

### ISSUE THREAD

**Issue by thouu** [PaperSpigot/Paper#7158]
### Expected behavior

Run `/locate stronghold`.

### Observed/Actual behavior

If those coordinates of the chunks were loaded before paper-82, it will bring you to the wrong stronghold.

### Steps/models to reproduce

1. Run the command `/locate stronghold`
2. Navigate to the location
3. If the chunks were loaded before paper-82, there's no stronghold
[I made a video showing the issue here](https://youtu.be/oWAhJbe9M84)

### Plugin and Datapack List

`Plugins (13): AutoMessage, ChatCo*, CoreProtect, CustomJoin*, DiscordSRV, Harbor, LockettePro, ProtocolLib, SimpleTpa*, SuperVanish, TabList, Vault, VaultChatFormatter*`

### Paper version

```
> version
[20:38:45 INFO]: This server is running Paper version git-Paper-82 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 8c5be16)
You are running the latest version
Previous version: git-Paper-81 (MC: 1.18.1)
```

### Other

This also affects Eyes of Ender

The "all chunks before paper-82" is just a theory. I noticed this issue everywhere before I updated to paper-82, but after I updated to paper-82 this morning and loaded completely new chunks to test the bug, it didn't happen in those new chunks.

**Comment by Uharn** [comment]
I'm facing the same issue /locate stronghold and player strongold finding with enders eyes fails

**Comment by Vaultling** [comment]
I just tried /locate on paper-82 and it found the stronghold just fine. I haven't tried with the eyes. So this issue seem a bit inconsistent? Granted that was just a one time test.

**Comment by Bobcat00** [comment]
From my testing, the location of strongholds has changed from 1.17 to 1.18, so endereyes in 1.18 will point to the wrong location in chunks generated by 1.17.

**Comment by Chew** [comment]
Related to https://bugs.mojang.com/browse/MC-135996, I think I had this issue from 1.16 -> 1.17.

**Comment by adelando** [comment]
I just noticed a similar issue with /locatebiome command taking me to a totally wrong biome (/locatebiome Minecraft:grove) takes me to an deep ocean

**Comment by electronicboy** [comment]
Closing, this is a wider upstream issue which isn't really fixable here without forcefully loading chunks to double check what's actually in the world, given the wider performance implications of this
