### ISSUE TITLE
Suggestion: Method to get Voxel/Collision shape from BlockData

### ISSUE THREAD

**Issue by jaylawl** [PaperSpigot/Paper#7160]
### Is your feature request related to a problem?

Example:

I would like to iterate over `List<Material>` in order to check if all materials in this list are full blocks with a 1x1x1 (full block) collision shape. However i am unable to do so, because getting the collision shape is currently exclusive to [`Block#getCollisionShape`. https://papermc.io/javadocs/paper/1.17/org/bukkit/block/Block.html#getCollisionShape()](https://papermc.io/javadocs/paper/1.17/org/bukkit/block/Block.html#getCollisionShape())

Since one is unable to instantiate `Block`, that is a problem.

### Describe the solution you'd like.

It makes sense that getting the collision shape via `Material` is not a thing, because the former vary depending on the block state.

My suggestion is to implement this as:
```
BlockData#getCollisionShape
```

Note that the returned collision shape from `Block#getCollisionShape` is normalized to vector 0,0,0 anyway, so this doesn't need to be accounted for here either.

### Describe alternatives you've considered.

NMS lol

### Other

Thanks for coming to my TED talk

**Comment by kennytv** [comment]
Not really viable, collision boxes can depend on the position in the world and its surrounding blocks (independent from the actual block state)

**Comment by jaylawl** [comment]
> 

But all of that should be accounted for in BlockData

**Comment by kennytv** [comment]
What?

**Comment by jaylawl** [comment]
> What?

I guess i made my reply before you edited your response... bummer though.

What about adding a note in the java docs that the method may not return an accurate collision shape if the blockdata isnt associated with a block instance?

**Comment by MWHunter** [comment]
This isn't simple.  For example, the shape of scaffolding changes when holding scaffolding.

**Comment by electronicboy** [comment]
Issue is that the getShape methods rely on accessing various bits of various state info, I'm not sure that stable API can really be built around this without exposing more vanilla concepts inside of the API itself
