### ISSUE TITLE
Reset the players title message on join

### ISSUE THREAD

**Issue by HexedHero** [PaperSpigot/Paper#7161]
### Is your feature request related to a problem?

Currently, you can send a title (maybe action bar too) to a player with a very long time basically infinite, then the player can leave the server and join another or even go into single-player and the title persists with no way to fix it unless you restart the game or send the player a new title which is annoying and frustrating. Many players go idle on Hypixel for example and get the "Your idle" title and then leave to join another server and they end up having to restart the game since it persists over. Resetting the title or sending a blank title fixes this.

### Describe the solution you'd like.

Reset the players title/send a empty title on player join

### Describe alternatives you've considered.

A plugin? But it'll mess with any other plugin that wants to generally send a title on join.

**Comment by olijeffers0n** [comment]
The hypixel example seems irrelevant considering they don’t use paper. However, this seems like a generally good idea

**Comment by HexedHero** [comment]
> The hypixel example seems irrelevant considering they don’t use paper. However, this seems like a generally good idea

Nothing to do with what the server is running, it's a client issue that Paper could add a workaround for.

**Comment by olijeffers0n** [comment]
Ah - I see what you mean. Like when the player goes from Hypixel -> Paper Server. Yes this seems useful

**Comment by MWHunter** [comment]
Sounds like something Mojang should fix instead.

**Comment by Chew** [comment]
Of course they should fix it, but not instead. If it's something as trivial and low-maintenance as this I don't see why we shouldn't. If someone ends up making a report on Mojira, feel free to toss it here.

**Comment by Doc94** [comment]
Found the MOJIRA issue: https://bugs.mojang.com/browse/MC-55347

**Comment by Owen1212055** [comment]
See: https://github.com/PaperMC/Paper/pull/7196#issuecomment-1319513847
