### ISSUE TITLE
EntityKnockbackByEntityEvent not called if there's no source entity

### ISSUE THREAD

**Issue by vytskalt** [PaperSpigot/Paper#7169]
### Expected behavior

The event should be called even if there is no source entity for a TNT or a projectile.

### Observed/Actual behavior

Its not called if there's no source entity.

### Steps/models to reproduce

1. /summon tnt
2. The event wasn't called

However, if player primes the TNT with a flint and steel, then it is called.

### Plugin and Datapack List

Only test plugin which debugs the event.

### Paper version

This server is running Paper version git-Paper-85 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: df8d28a)
You are running the latest version

### Other

Related: #7168

**Comment by Chew** [comment]
Doesn't the name EntityKnockback*ByEntity*Event imply there should be a source? 🤔 

Unless I'm misunderstanding.

**Comment by vytskalt** [comment]
> Doesn't the name EntityKnockback_ByEntity_Event imply there should be a source? 🤔

Look at #7168 it should make more sense about what I mean

**Comment by Machine-Maker** [comment]
> Unless I'm misunderstanding.

You probably are, the event isn't called if TNT  is lit from a dispenser, even though its a tnt entity that caused the explosion (and subsequent knockback)

**Comment by vytskalt** [comment]
> > Unless I'm misunderstanding.
> 
> You probably are, the event isn't called if TNT  is lit from a dispenser, even though its a tnt entity that caused the explosion (and subsequent knockback)

Yes.

~~I don't know how this could be fixed though. Making #hitBy nullable would just make an incompatibility with old plugins.~~
nvm didn't read the javadocs right

**Comment by YHDiamond** [comment]
I seem to be having a similar issue where this event doesn't get triggered when fireballs explode that are spawned using player.launchProjectile, could it be the same issue?
