### ISSUE TITLE
Do not save generated but unchanged chunks setting. 

### ISSUE THREAD

**Issue by roboalex2** [PaperSpigot/Paper#7173]
### Is your feature request related to a problem?

I often run into the situation that my minecraft servermap wastes alot of storage currently (2TB). I can change that by using a tool like mcaselector to delete chunks that were hardly used but i am not really satisfied with that solution. Not having those chunks would also make it much easier to finde chunks generated in newer versions near spawn etc.

### Describe the solution you'd like.

I thougt a relatively easy solution/feature would be a setting that only allowes changed(blocks, entitys etc) chunks to be actually saved into the world files. 

One way to do it would be to simply create a hash for the chunks blocks directly after generation and compare that hash when the chunk is saved. If they are equal look if any important entitys are there and if there are none trash the chunk. 

This would have the benefit of alot less storage usage and more chunks from newer versions over time. 

### Describe alternatives you've considered.

mcaselector or trying to make it myselfe, but considering the way over my head world gen code i scrapped that idea.

**Comment by electronicboy** [comment]
This is not something that we're interested in given the various caveats around world generation which makes much of this stuff massively nuanced, determining what data should persist is pretty bleh in such cases and you're gonna basically have horrible chunk borders and such, it's just not a feature which could ever realistically be implemented in a world friendly manner
