### ISSUE TITLE
Bees age in beehive regardless of age lock

### ISSUE THREAD

**Issue by NaVAWU** [PaperSpigot/Paper#7180]
### Expected behavior

When an age lock is applied, the bee shouldn't be able to advance in age, regardless of being able to enter the beehive.

### Observed/Actual behavior

When an age lock is applied to a bee, and it is small, it will still age when inside the beehive. This causes them to grow up over night.

### Steps/models to reproduce

1. Spawn in an bee with age lock and a negative age.
2. Wait for the bee to enter the hive, and after the appropriate amount of time, the bee will come out having grown up.

### Plugin and Datapack List

Plugins:
- AdvancedNMotd
- Bluemap
- Chunky
- CoreProtect
- CreepersDontGrief
- DiscordSRV
- isSlimeChunk
- LuckPerms
- PingPlayer
- PlugMan
- ProtocolLib
- TurtlePlugin
- ViewDistanceTweaks
- Worldedit

Datapacks:
- AFewMoreTrapdoors
- OnePlayersleepV42
- VanillaTweaks
- Anti Enderman Grief
- Anti Ghast Grief
- Armor Statues
- Copper block recipe
- Copper block to ingots
- Custom nether portals
- Deepslate stairs
- Fast leaf decay
- More mob heads
- No junk zombies
- Player head drops
- Redstone rotation wrench
- Rope
- Spawning Spheres
- Terracotta Rotation Wrench
- Thunder Shrine
- Wandering Trades
- Light Craftable
- Rooted Dirt Craftable
- Leash Villager Datapack
- Coordinates Hub
- AFK Display

### Paper version

Paper version git-Paper-101 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 464b171)

**Comment by lynxplay** [comment]
Replicable on both paper's latest (464b1715bb8fb3c87b1f0f1f76d136b581794228) as well as spigots latest (3372-Spigot-8965a50-c59b0ca).

This should probably go into the patch created in #6466, or MM you could probably even include this in the same PR.

Note for anyone replicating this, bees do not age if their age entering the beehive is 0, so if you want to validate this, make sure to pick a bee with age lower or higher. Additionally, the bees age is updated after the `EntitySpawnEvent`, so you will have to delay your age logic by a tick if you use the plugin route.
