### ISSUE TITLE
Huge performance hit after upgrading from 1.17.1 to 1.18.1

### ISSUE THREAD

**Issue by AndreiSva** [PaperSpigot/Paper#7182]
### Timings or Profile link

N/A

### Description of issue

I run paper on a low power single core server and have had no problems running paper 1.17.* before, however, paper 1.18 is unusable and i couldn't connect even with a single client without constant timeouts.

I wonder if this is just a side effect of 1.18's increased world height limit or something that paper can take care of. Either way, I think this issue should be addressed.

### Plugin and Datapack List

None

### Server config files

Default Config

### Paper version

I was unable to load into the server long enough to successfully run the command but i have tested both paper-1.18.1-101.jar and paper-1.18.1-100.jar both with the same effect.

**Comment by LaurenceBarnes** [comment]
Well the fact that not all performance patches are ported from 1.17.1 to 1.18.1 yet might play a role

**Comment by electronicboy** [comment]
This is not the place for support, the game is also generally heavier now and missing some patches.
