### ISSUE TITLE
SIGSEGV

### ISSUE THREAD

**Issue by andy01745** [PaperSpigot/Paper#7184]
### Stack trace

```
https://paste.gg/p/anonymous/0d2bb4548130421f818371509f70d167
```

### Plugin and Datapack List

Chair, CoreProtect, Essentials, EssentialsChat, EssentialsSpawn, GriefPrevention, PermissionsEx*, spark, TreeFeller, Vault

No datapacks

### Paper version

This server is running Paper version git-Paper-101 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 464b171)

### Other

I have replaced the RAM on the system and confirmed that RAM was bad, Still happening, I was wondering if anyone else is having this issue.

**Comment by Fejm** [comment]
You still have bad ram

**Comment by Chew** [comment]
Yeah something's funky with your setup. Not a Paper issue. Maybe try aikar's flags? https://startmc.sh
