### ISSUE TITLE
/tp and /teleport Tab autocomplete don't work for the first argument

### ISSUE THREAD

**Issue by Pavlogal** [PaperSpigot/Paper#7185]
### Expected behavior

typing /tp or /teleport and pressing Tab should give you a list of possible arguments

### Observed/Actual behavior

nothing appears, even after typing the first letter from an online username and spamming Tab it doesn't respond. But only on the first command argument. The second argument works perfectly.

### Steps/models to reproduce

I investigated and this issue started appearing in paper builds 93-101. Just type /tp and you will see

### Plugin and Datapack List

tried with a clean brand new server with no plugins

### Paper version

tried in versions 90-101, 90-92 worked, broke in 93 and still hasn't been fixed

### Other

from what I've seen so far commands other than /tp and /teleport are not affected, needs more triage though

**Comment by NoahvdAa** [comment]
Can reproduce on build 101, even when `fix-target-selector-tag-completion` is set to false.

**Comment by Owen1212055** [comment]
There are currently two issues that are causing this. 
- The config is set up AFTER commands are initialized, this causes it to always be true.
- It seems (for whatever reason) specifying a custom auto-completion for teleport causes two ``ServerboundCommandSuggestionPacket`` to be sent, and although both are responded it seems the client just... nopes.. and decides not to suggest anything. A wild guess, but maybe it has to do with having two of the same type of suggestion here? There is an EntityArgument plural AND single type in the same next node.
![image](https://user-images.githubusercontent.com/23108066/147375844-8f9552c8-a1db-407f-8b7c-89f9881395dd.png)

Doing commands like ``/item modify entity @e[type=#minecraft:impact_e] armor.chest 5`` also seem to never cause the "(Invalid or unknown entity type tag)." message to appear.

**Comment by Machine-Maker** [comment]
> Doing commands like /item modify entity `@e[type=#minecraft:impact_e] armor.chest 5` also seem to never cause the "(Invalid or unknown entity type tag)." message to appear.

This was never supposed to change since its existing behavior and who knows if some datapack/plugin/command block setup required that.
