### ISSUE TITLE
Chunk is unloaded even when using PluginChunkTickets

### ISSUE THREAD

**Issue by 0utplay** [PaperSpigot/Paper#7191]
### Expected behavior

The chunk should stay loaded until the plugin chunk ticket is removed.

### Observed/Actual behavior

The chunk is kind of unloaded. When walking away from the chunk I stop receiving the message.
The ChunkUnloadEvent is never called for this chunk
![javaw_iqeOP2sNiM](https://user-images.githubusercontent.com/60936899/147394288-f7df4548-70fe-49ef-818d-1ab8b08a5a70.png)
![javaw_JgsFy5GCFf](https://user-images.githubusercontent.com/60936899/147394289-9269560e-3b41-429c-b2f1-c21bcb7af3e0.png)

### Steps/models to reproduce

- Set a plugin ticket on a chunk in the WorldLoadEvent using `World#addPluginChunkTicket(chunkX, chunkZ, plugin)`.
- Build a redstone clock that sends you a message.
![javaw_iqeOP2sNiM](https://user-images.githubusercontent.com/60936899/147394288-f7df4548-70fe-49ef-818d-1ab8b08a5a70.png)
![javaw_JgsFy5GCFf](https://user-images.githubusercontent.com/60936899/147394289-9269560e-3b41-429c-b2f1-c21bcb7af3e0.png)

- Leave the chunk and the render distance and check if you are still getting messages.

### Plugin and Datapack List

Plugins:
![javaw_c8yA45m0iR](https://user-images.githubusercontent.com/60936899/147394381-1f6130fb-c3f2-430b-82bf-395287d3ba62.png)
Datapacks:
 
![grafik](https://user-images.githubusercontent.com/60936899/147394389-511b77e0-27a8-4919-a526-bbb647de27e4.png)

### Paper version

![grafik](https://user-images.githubusercontent.com/60936899/147394395-2a3f5864-df76-44d0-bd17-d87c7ff6708a.png)

### Other

I also tried using `World#setChunkForceLoaded` but I get the same behavior

**Comment by electronicboy** [comment]
Chunks are ticked based on a player being near them, not just because they're "loaded"

**Comment by 0utplay** [comment]
So how am I supposed to load a chunk with any player nearby?
