### ISSUE TITLE
Mobs cannot walk over rails [Possibly Upstream] [1.18.1]

### ISSUE THREAD

**Issue by owenwastaken** [PaperSpigot/Paper#7198]
### Expected behavior

Mob pathfinding allowing hostile entities to walk over rails

### Observed/Actual behavior

When on the other side of a section of rails, entities will stand on the other side

### Steps/models to reproduce

Build a long track of rails, spawn a hostile mob and enter survival mode, then walk across the rail while it is chasing you

### Plugin and Datapack List

CoreProtect, dynmap, floodgate, Geyser-Spigot, InvSeePlusPlus

### Paper version

git-Paper-101 (MC: 11.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git:464b171)

### Other

I am unsure whether this is an upstream issue, or one caused by Paper.

**Comment by e-im** [comment]
works as intended https://bugs.mojang.com/browse/MC-33359
