### ISSUE TITLE
Server Impossible To Close If Cannot Find Display

### ISSUE THREAD

**Issue by laymanuel** [PaperSpigot/Paper#7199]
### Expected behavior

Server exits with thread death. Server kills itself.

### Observed/Actual behavior

Server hangs indefinitely. Must kill with `kill -9` or it will not close.

Server log: https://0bin.net/paste/CDTyMMjl#jkukW3Dpa+QCp-/9c38w3Ij1Zjiz3vM0xn5I0BAjvyX (it stay like this for 10+ minutes. I press ctrl+c and type kill command. None work but `kill -9`.
Jstack 1: https://0bin.net/paste/MA85TbZS#f5ZNhgOs1DXv2JfaiUszeecXnTa0RGvNacaQ3zDP1ql
Jstack 2: https://0bin.net/paste/EF02zdhS#L66LG1PzIUeVnmbXSvSh2vQ3ZlK-KsXYI0Ao4QveAG1

I take 2 jstack minutes apart for debug, they have same result.

### Steps/models to reproduce

Environment:
```
Linux banana 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

openjdk version "17" 2021-09-14 LTS
OpenJDK Runtime Environment Corretto-17.0.0.35.1 (build 17+35-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.0.35.1 (build 17+35-LTS, mixed mode, sharing)
```

1. run `export DISPLAY=banana:11.0`
2. ensure X server is installed
3. Download new paper jar
4. run paper jar without `--nogui` argument

### Plugin and Datapack List

None. Complete fresh server.

### Paper version

Server do not start, 1.18.1 build 101.

### Other

I do not know why this happen, why it hang. Because I run on physical machine it forced me to restart my computer to get out of it as it would not let me switch TTY. I next run in tmux to get jstack.

**Comment by electronicboy** [comment]
misconfigured environment caused an exception to be thrown which caused the process to exit;
Looks like the server shutdown thread logic blew up as it expected the server to have started and actually be ticking in order to shutdown safely, am not 100% sure how clean this would be to fix, would need deeper analysis on this logic

**Comment by Chew** [comment]
This doesn't even seem like an us issue since the GUI exists all the way up to vanilla (I believe). I'd call it a workaround, but you should really just be using `--nogui` regardless (I do even on a laptop)

**Comment by laymanuel** [comment]
This is not issue of server gui, it is exception thrown in this part of startup that causes this. Server gui is easiest way to reproduce.

**Comment by laymanuel** [comment]
I leave. Goodbye.
