### ISSUE TITLE
Minecraft Server Crashed

### ISSUE THREAD

**Issue by mirronake** [PaperSpigot/Paper#7201]
### Stack trace

https://paste.gg/p/anonymous/f347178b2b074f1d95e71c9ad3eeae47

### Plugin and Datapack List

Clearlag
CoreProtect-20.3
DiscordSRV-Build-1.24.0.
GSit-1.0.4
Harbor-1.6.3
InvSee++
RealScoreboard
SkinsRestorer
tabtps-spigot-1.3.11
UltimateAutoRestart+Build+48a
voicechat-bukkit-1.18.1-2.1.27

### Actions to reproduce (if known)

The server just shuts down and that's it.

### Paper version

git-Paper-97 (MC: 1.18.1)

**Comment by MiniDigger** [comment]
Looks like it fails while saving the world, is your server running on some kinda slow disk or something?

**Comment by mirronake** [comment]
I do not know which disk is installed for the server to work. I pay for hosting

**Comment by LoJoSho** [comment]
> I do not know which disk is installed for the server to work. I pay for hosting

Make sure your host is on SSD and not HDD. 

However, even when I run HDD, it still runs fine, so your host could just have really slow HDD which causes that problem. Or there is something that is slowing down the HDD somewhere on their machine. Contact your host about the problem, see what they can do.

**Comment by e-im** [comment]
This is more than likely not a paper issue, and unless you've got an abnormal watchdog configuration it looks like something has caused this incorrectly (clock leap?) although that shouldn't either. Please come by out [discord](https://discord.gg/papermc) for support.
