### ISSUE TITLE
My server keeps on crashing despite it having high tps. No one on discord could help me so I'm trying here.

### ISSUE THREAD

**Issue by AntyGreen** [PaperSpigot/Paper#7206]
### Stack trace

https://paste.gg/p/anonymous/5e5c8bfd056f4787a09a4eb92ec8a0a8

### Plugin and Datapack List

Plugins (8): AmkMcAuth, CoreProtect, DriveBackupV2, Essentials, ImageOnMap, OldCombatMechanics, Sk
insRestorer, Tweakin

datapacks: There are 12 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/anti ghast grief v1.1.2.zip
 (world)], [file/classic fishing loot v1.1.2.zip (world)], [file/double_door-datapack-v4.0.0.zip (world)], [file/durability ping
 v1.1.2.zip (world)], [file/gem villagers v4.3.5.zip (world)], [file/player head drops v1.1.2.zip (world)], [file/treasure gems 
v1.2.4.zip (world)], [file/villager workstation highlights v1.1.2.zip (world)], [file/wandering trades v1.5.1.zip (world)], [fil
e/graves v2.8.5.zip (world)]

### Actions to reproduce (if known)

The server most commonly crashes after less than 3 minutes when at least two players are on it.

### Paper version

Paper build 101 1.18.1

### Other

I have 28 gb of ram, 8 CPU cores, 80gb of SSD disk, these are my flags:
java -Xms24G -Xmx26G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -XX:InitiatingHeapOccupancyPercent=20 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar paper.jar nogui

these are my timings: https://timings.aikar.co/?id=9ebcdb6c23a24a6b9809d463c02d2407

**Comment by Owen1212055** [comment]
![image](https://user-images.githubusercontent.com/23108066/147421410-5e036f1f-deca-46b5-a05d-6958bb1e5326.png)
"No one on discord could help me so I'm trying here."
Piracy isn't supported.

**Comment by electronicboy** [comment]
This is an issue tracker, not a support desk
