### ISSUE TITLE
nether-ceiling-void-damage-height doesn't alter portal search 

### ISSUE THREAD

**Issue by sudofox** [PaperSpigot/Paper#7208]
### Expected behavior

Portals made above the nether roof should not be considered as valid targets as they'll instant kill any player who travel to them when nether-ceiling-void-damage-height is set to the roof - it should try for a different portal instead

### Observed/Actual behavior

Player exits above roof, takes void damage, dies, and so do their items.

### Steps/models to reproduce

Build portal on roof, then set nether-ceiling-void-damage-height=128

### Plugin and Datapack List

NoCheatPlus
IllegalStack
BanItem
Pistonchat

### Paper version

[01:27:22 INFO]: This server is running Paper version git-Paper-400 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 4ac995a on ver/1.17.1)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-398 (MC: 1.17.1)

**Comment by sudofox** [comment]
Er, did this get fixed(?)

**Comment by sudofox** [comment]
I've had several players get killed just by popping out an old portal onto the roof and I can't for the life of me figure out how to get this fixed in paper's current state. We're on the latest 1.17.1 build; not ready to update to 1.18.1 yet due to disk usage concerns.

I'll link them to this issue

**Comment by Jossamations** [comment]
I just got killed to spawn after flying over 1.5 million blocks on the way to a base. Please fix this.
![image](https://user-images.githubusercontent.com/23328833/158039723-52bf1541-b2d8-4c0f-a448-43e0ab90be7a.png)

**Comment by sudofox** [comment]
This isn't fixed, I don't think? The PR was not merged

**Comment by Machine-Maker** [comment]
I tested it twice, and so did @kennytv. Can you give reproduction steps? I created a portal on the ceiling with the void damage disabled, then I went through it to create a portal in the overworld. Then I enabled void damage at y=100, then I went into the portal and it didn't go to the portal on the ceiling.


EDIT: Now I see you edited your post. There were 2 PRs that fixed the issue, one was merged, the other closed.
