### ISSUE TITLE
Water behavior bug while dispensed from a Dispensor

### ISSUE THREAD

**Issue by xISHRAKx** [PaperSpigot/Paper#7209]
### Expected behavior

The water should be able to flow when its dispensed from a Dispenser.

### Observed/Actual behavior

After the water is dispensed from a Dispensor (vertical - facing up) the water is not flowing. While placing water manually is flowing like normal.

### Steps/models to reproduce

Place a Dispenser looking up, Put a Water in it And dispense it / Activate it. The water will not flow. We are using the latest beta/dev build.

### Plugin and Datapack List

Plugins: AdvancedNMotd, antiRedstoneClock, AntiSeedCracker, AuthMe, BlockedCmds*, Chunky, ChunkyBorder, Citizens, CMI, CMILib, CrazyCrates, GriefDefender, IllegalStack, LiteBans, LuckPerms, Matrix, mcMMO, Multiverse-Core, NeedOP, PlaceholderAPI, ProtocolLib, PvPToggle, QuickShop, Vault, Votifier, VotingPlugin, WorldEdit, WorldGuard

Datapacks: [vanilla (built-in)], [file/bukkit (world)], [file/elevators (world)], [file/veinminer-datapack-v3.0.1 (world)], [file/xp (world)], [file/FastLeafDecay (world)]

### Paper version

This server is running Paper version git-Paper-101 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 464b171)
You are running the latest version

### Other

We have tried recreating the problem in out side claim [as we are using a claims plugin] But the bug still happens.

**Comment by NoahvdAa** [comment]
Can't reproduce on e9947f8:

![image](https://user-images.githubusercontent.com/44026893/147460031-09f82ddc-9868-4560-b2d1-254f0742e77f.png)

**Comment by xISHRAKx** [comment]
> Can't reproduce on [e9947f8](https://github.com/PaperMC/Paper/commit/e9947f8145ea1fa87d995fbf7df4868a556e78db):
> 
> ![image](https://user-images.githubusercontent.com/44026893/147460031-09f82ddc-9868-4560-b2d1-254f0742e77f.png)

Is it in the dev release?

**Comment by Chew** [comment]
Please reproduce without plugins.
