### ISSUE TITLE
[Question] How to write a plugin in 1.18.x?

### ISSUE THREAD

**Issue by XIAYM-gh** [PaperSpigot/Paper#7210]
### Expected behavior

I want to make a plugin with paper 1.18.1 server

### Observed/Actual behavior

i can't find the class called "org.bukkit.plugin"

### Steps/models to reproduce

none :(

### Plugin and Datapack List

official paper jar

### Paper version

1.18.1 xd

### Other

I just can't find the JavaPlugin class
:(
can someone tell me how to find it?
thx

**Comment by kennytv** [comment]
Join the Discord for help with plugin dev

**Comment by XIAYM-gh** [comment]
emmm sorry about that, i can't use discord because i'm in China mainland

**Comment by electronicboy** [comment]
This is not the place for discussions, if you really must, use the forums or IRC, etc
This issue tracker sends emails out for every issue, etc, and we're not gonna flood peoples emails for something which is not an issue
