### ISSUE TITLE
Option to make certain tameable entities not tameable

### ISSUE THREAD

**Issue by aerulion** [PaperSpigot/Paper#7215]
### Is your feature request related to a problem?

I'm implementing custom mobs and trying to prevent certain entities from being tamed, for example certain wolves.

### Describe the solution you'd like.

I don't know if this is something that could be implemented easily, but it would be quite nice to have: 

- Tameable#setTameable(boolean tameable)
- Tameable#isTameable()

An entity which has the boolean set to false shouldn't even start the taming process and therefore not call the tame event, nor should it consume the item when right-clicked. (For example, bones in the case of the wolves.)

### Describe alternatives you've considered.

Listening to the EntityTameEvent and / or the PlayerInteractEntityEvent and cancelling the event. But that means I constantly have to listen to the events. Also, the "taming process" is different for certain mobs.

### Other

The alternative I described works for me, but in my opinion, it would still be easier to only set the value once. If this is something that can't be implemented easily, or just isn't worth the effort because it's a relatively niche problem, I'm completely okay with this request being declined ^^

**Comment by Machine-Maker** [comment]
If your custom entity extends nms's TamableAnimal, you should just be able to override the TamableAnimal#tame(Player) method and just not do anything.

EDIT: or if you wanted to catch plugins trying to set them to be tame, override the TamableAnimal#setTame(boolean) method

**Comment by Owen1212055** [comment]
>  Also, the "taming process" is different for certain mobs.

I'm curious, can you go into more detail about this?

**Comment by aerulion** [comment]
> If your custom entity extends nms's TamableAnimal, you should just be able to override the TamableAnimal#tame(Player) method and just not do anything.
> 
> EDIT: or if you wanted to catch plugins trying to set them to be tame, override the TamableAnimal#setTame(boolean) method

I should have been more specific about what I'm doing, I'm not implementing the entities on nms level, since I did not need it for now, and I'm trying to keep the code as simple as possible (no need for special serialization, etc.). It's more like spawning a renamed mob with a few attributes modified.

> I'm curious, can you go into more detail about this?

I just meant that some animals use different food items to tame, while a horse for example gets tamed just by riding it.

**Comment by Owen1212055** [comment]
> > If your custom entity extends nms's TamableAnimal, you should just be able to override the TamableAnimal#tame(Player) method and just not do anything.
> > EDIT: or if you wanted to catch plugins trying to set them to be tame, override the TamableAnimal#setTame(boolean) method
> 
> I should have been more specific about what I'm doing, I'm not implementing the entities on nms level, since I did not need it for now, and I'm trying to keep the code as simple as possible (no need for special serialization, etc.). It's more like spawning a renamed mob with a few attributes modified.
> 
> > I'm curious, can you go into more detail about this?
> 
> I just meant that some animals use different food items to tame, while a horse for example gets tamed just by riding it.

Ah yea it seems horses don't trigger this event, i'll see if I can get that implemented for you.

**Comment by Machine-Maker** [comment]
Why can't you just cancel EntityTameEvent?

**Comment by Owen1212055** [comment]
> Why can't you just cancel EntityTameEvent?

![image](https://user-images.githubusercontent.com/23108066/147603829-3e375602-ca32-460f-b474-f13c23a87f35.png)

~~It's not triggered for horses.~~ Never mind, it is. The ``RunAroundLikeCrazyGoal`` is responsible for this.

**Comment by Owen1212055** [comment]
Never mind, it is. The ``RunAroundLikeCrazyGoal`` is responsible for this.

**Comment by aerulion** [comment]
As I tried to describe in the 'Other' part, it would be more of a convenience feature and to reduce the use of listeners. Simply cancelling the EntityTameEvent would not cancel the consumption of the item used to tame the animal, which has to be checked manually. As I already said, I found a working solution, but I just thought this might be a useful thing to have if it could be done simply by setting a single boolean, but I can also understand if it is too specific and not worth implementing ^^

**Comment by e-im** [comment]
Unless anyone else has a strong opinion on this, I'm inclined just to say cancel the event(s) here as you described.

Thanks for the request, regardless.
