### ISSUE TITLE
Enchanted book has no CreativeModeTab

### ISSUE THREAD

**Issue by TheEpicco** [PaperSpigot/Paper#7217]
### Expected behavior

The enchanted book should have "CreativeModeTab.j" (combat tab).

### Observed/Actual behavior

The enchanted book has no CreativeModeTab in "net.minecraft.world.item.Items"

![missing_tab](https://user-images.githubusercontent.com/69150567/147623742-5c25b4c2-4c5c-4699-8a47-36ecdd083845.png)

### Steps/models to reproduce

Output of the following code is null:

`org.bukkit.craftbukkit.v1_18_R1.util.CraftMagicNumbers.getItem(org.bukkit.Material.ENCHANTED_BOOK).t()`

### Plugin and Datapack List

-

### Paper version

This server is running Paper version git-Paper-108 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 1931bb5)
You are running the latest version
Previous version: git-Paper-105 (MC: 1.18.1)

**Comment by electronicboy** [comment]
I fail to understand the issue here: From what I can see, mojang never defined that data on the item, so, ofc it's not gonna be set?

**Comment by Machine-Maker** [comment]
Some context for ^^^
![image](https://user-images.githubusercontent.com/15055071/147624440-ae6d123d-3df8-46d8-b747-bee0a256266b.png)

You can see that nether brick has a creative tab defined, but enchanted book doesnt

**Comment by electronicboy** [comment]
Yea, I can see that, but, I fail to see the issue here
is there a behavioral difference here due to some breakage vs vanilla internals, or is this literally a case of mojang didn't do something in the server?
if former, that should be fixed, if latter, that's mojangs impl choice here, not ours, and server internals are not API so we wouldn't bend over to try to maintain some consistency here between the API and the special casing of this area for the client itself

**Comment by Owen1212055** [comment]
This is certainly on purpose, there is no default enchanted_book in the creative inventory. All enchanted books in the creative inventory have some kind of enchantment.
![image](https://user-images.githubusercontent.com/23108066/147624555-51fc52c7-c4ef-423d-bb93-d957b15d92a2.png)

**Comment by Machine-Maker** [comment]
> Yea, I can see that, but, I fail to see the issue here

nah, I was backing you up. I wasn't disagreeing with anything

I don't think any functionality from the CreativeModeTab class is used on the server

**Comment by electronicboy** [comment]
Yea, this is basically a non-issue, if you're dealing with that data you're gonna have to special case it on your end if you're expecting different behavior, this is areas where there is some special casing and that data is basically irrelevant for them

**Comment by TheEpicco** [comment]
> This is certainly on purpose, there is no default enchanted_book in the creative inventory. All enchanted books in the creative inventory have some kind of enchantment. ![image](https://user-images.githubusercontent.com/23108066/147624555-51fc52c7-c4ef-423d-bb93-d957b15d92a2.png)

The tab is not displayed in the creative inventory
