### ISSUE TITLE
[1.18] BlockKey is broken on negative Y (Underflow)

### ISSUE THREAD

**Issue by tackleza** [PaperSpigot/Paper#7218]
### Expected behavior

BlockKey is broken on 1.18 on negative Y (Underflow)
since 1.18 because world gen can go below 0

### Observed/Actual behavior

When get block key at negative Y then convert back. it's return wrong Y
(Example: -1 become 1023)

![image](https://user-images.githubusercontent.com/3255203/147631365-83ca94a1-5222-4ad7-9e29-04654680251e.png)

### Steps/models to reproduce

Simple Code
```
Block block = player.getLocation().getBlock(); //Y=-1
Long key = block.getBlockKey();
Location location = block.getWorld().getBlockAtKey(key); //When convert back Y: Become 1023
```

### Plugin and Datapack List

None

### Paper version

Paper 1.18.1 #108

**Comment by kennytv** [comment]
Note that you're better off implementing your own block key method, giving y values more bits. We can't really provide such a method without breaking it every so often
