### ISSUE TITLE
/fixwater not finding blocks below y=0

### ISSUE THREAD

**Issue by HkB115** [PaperSpigot/Paper#7220]
### Expected behavior

/fixwater would replace an area of flowing water with source blocks of water

### Observed/Actual behavior

/fixwater would not find any flowing water below y=0 that needs replacing, but would work fine above y=0. This same issue might exist for /fixlava, but is untested.

### Steps/models to reproduce

Try to use /fixwater below y=0 on an area that needs to be filled with water that has an existing source block.

### Plugin and Datapack List

None/Vanilla

### Paper version

This server is running Paper version git-Paper-108 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 1931bb5)

**Comment by electronicboy** [comment]
On the basis that fixwater is not a paper command, am going to assume that this issue is filled out improperly and is irrelevant to us given that it's a plugin command anyways

**Comment by HkB115** [comment]
My bad. Had 2 tabs open and haven't had my coffee yet.
