### ISSUE TITLE
Add PlayerWashItemEvent

### ISSUE THREAD

**Issue by aerulion** [PaperSpigot/Paper#7221]
### Is your feature request related to a problem?

I'm trying to modify the item meta of an item which is being washed in a cauldron.

### Describe the solution you'd like.

Adding the PlayerWashItemEvent which provides access to:

- The "unwashed" ItemStack
- The resulting "washed" ItemStack
- The Player involved
- The cauldron used to wash the item

### Describe alternatives you've considered.

Figuring out the itemstack / hand used by listening to the CauldronLevelChangeEvent and PlayerInteractEvent and capturing the last cauldron interaction.

**Comment by electronicboy** [comment]
washed? o.O

**Comment by electronicboy** [comment]
https://minecraft.fandom.com/wiki/Cauldron#Removing_dye_from_items mfw

**Comment by aerulion** [comment]
I just named it washed because the 3 CauldronLevelChangeEvent.ChangeReasons related to items also end with _WASH

**Comment by Doc94** [comment]
hmm maybe can try make a PR.. but why a event and not use the interact event?

**Comment by Owen1212055** [comment]
That'd be great! The reason for it most likely is that the logic is a bit more special for each interaction type.

Leather (dyed stuff)
![image](https://user-images.githubusercontent.com/23108066/147704521-0470a5b0-844c-4c56-bcd8-07f9ca7280f9.png)
Banners
![image](https://user-images.githubusercontent.com/23108066/147704529-74c380ff-5ad2-4a3c-a29c-3e230a4810c0.png)
Shulker
![image](https://user-images.githubusercontent.com/23108066/147704542-8d148302-afa9-4f05-9f83-cbb33490cbc6.png)

**Comment by Doc94** [comment]
hmm maybe can be better improvement the lowerFillEvent for add this items (?

**Comment by Owen1212055** [comment]
> The "unwashed" ItemStack
> The resulting "washed" ItemStack

The issue with that is the event is called before the "washed" behavior, so it doesn't give you access to that. You'll pretty much have to put it between the washing item logic, and the player being given the item. You may need to capture/clone the item as well, as it seems some places mutate the item while others replace it.

**Comment by Doc94** [comment]
hmm the cases for this works very different... for dye items change a value.. for banner make 3 cases... and for shulker create a new item and copy all to the new xd
