### ISSUE TITLE
PlayerBucketEmptyEvent is cancelled but block beneath is updated

### ISSUE THREAD

**Issue by luizsusin** [PaperSpigot/Paper#7222]
### Expected behavior

The block clicked (Grass Block) shouldn't become snowy.

### Observed/Actual behavior

After cancelling the event when a player uses a POWDER_SNOW_BUCKET, the block clicked (Grass Block) still becomes snowy.

### Steps/models to reproduce

1. Use a Powder Snow Bucket on a Grass Block;
2. Cancel the event;
3. The snow block isn't placed, but the grass block becomes snowy.

### Plugin and Datapack List

https://gist.github.com/luizsusin/f0e010a896afcd33632272b52d17ae21

### Paper version

Although not using Paper, this might be a Paper issue. That's the unique reason I'm posting it here and not on Purpur repo.
I'm using Purpur, version git-Purpur-1465 (MC: 1.18.1), which uses Paper 1.18.1 build 108.

**Comment by NoahvdAa** [comment]
Duplicate of #6630

**Comment by luizsusin** [comment]
That's true. Sorry for reposting it. Closing it now.
