### ISSUE TITLE
Optional auto chunk loading

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#7225]
### Is your feature request related to a problem?

I just noticed a prevent-moving-into-unloaded-chunks option in paper.yml
If the world's auto chunk loading by player is disabled(Chunk can only be loaded by plugin code), we can specify the chunks that player can only interact and move in without listener check
It might be helpful for minigame/skyblock development

### Describe the solution you'd like.

Method in WorldInitEvent

### Describe alternatives you've considered.

disable-auto-chunk-load option in paper.yml

**Comment by electronicboy** [comment]
stuff loads chunks all across the board, and when stuff asks for a chunk, it gets a chunk, otherwise shit breaks

disabling the player ticket creation stuff, possible, but out of scope for this project
Disabling everything else from loading chunks? practically unviable
