### ISSUE TITLE
Option to have a nether / end only server

### ISSUE THREAD

**Issue by aerulion** [PaperSpigot/Paper#7226]
### Is your feature request related to a problem?

What I'm trying to achieve is relatively simple, namely having a server which only consists of a single nether world, or a single end world respectively for use in a bungee setup.

### Describe the solution you'd like.

Somehow being able to configure the above-mentioned behavior. Either by setting the environment for the "default" world, or being able to disable the overworld whilst enabling one of the other two world types.

### Describe alternatives you've considered.

- Having the overworld enabled, but without keeping any chunks loaded and enabling the nether / end world I need
- Copying a pre generated nether-world for use as the overworld, but that required tweaking the level.dat file
- Trying to modify the world generator for the overworld via a plugin, but I'm not sure if that is possible

### Other

Maybe I'm missing something stupidly simple, and this is already possible somehow. If that is the case, I'm sorry for bothering with this issue.

**Comment by Machine-Maker** [comment]
I feel like a plugin could handle this pretty easily right? setting spawn locations, preventing teleports, etc.

**Comment by aerulion** [comment]
Well, that would still mean to have the over-world loaded, and just never letting anyone enter the world, or am I misunderstanding what you meant? I just liked the idea of being able to disable the for example nether and end on servers I did not need them, and just having a single world loaded at all time (just 1 world folder, etc.) and thought it would be nice to do so on servers that require a nether environment for example.

**Comment by electronicboy** [comment]
Issue here is that everything is tied to the existence of an overworld in the server, i.e. it's where the server assumes it can access to save data, etc; am not sure if this is trivial or how viable this is, bearing in mind that you can disable spawn loading and, assuming nobody is in there, it for the most part doesn't exist

**Comment by Chew** [comment]
Too much sorta relies on the above, most if not all the data is stored in the main overworld data folder. You can probably get away with just not loading spawn chunks, or disabling entities in the main world. You can get pretty far with vanilla and `paper.yml` alone, but ultimately this has to be something done on your end as the maintenance cost would be too high for us for a seemingly small minority of users.

**Comment by aerulion** [comment]
Okay thats more or less what I thought regarding disabling the overworld, since playerdata files etc. are also stored in the folder. Because of that my first idea was to somehow being able to modify the environment of the overworld, and just generating it as a nether world. But the only way I was able to do so was by modifying the level.dat file and messing with the world generator data there. Would it maybe be possible to make that a bit easier accessible (for example by a config setting for overworld environment), or would it be against the general concept to have a "overworld" not being a overworld and possibly have negativ side effects?

**Comment by Fejm** [comment]
It's simple and trival. I made it in my private fork.
Find where deafult worlds are loaded and *force* overworld environment to be nether. You have to change this in more than one local variable as I remember, but everything is in one method. 

Server on start will print warning "unable to find spawn biome" but everything will work.

I'm using this in bungee network to get nether reset everyday without any lag.

**Comment by oOHiyoriOo** [comment]
why not just move `world_the_nether` to `world` ?

**Comment by aerulion** [comment]
> why not just move `world_the_nether` to `world` ?

Because that simply does not work. (At least in 1.17/1.18)
