### ISSUE TITLE
1.18 Joining Server Bug

### ISSUE THREAD

**Issue by NovusDevelops** [PaperSpigot/Paper#7233]
### Expected behavior

To join the server with items in the same spot.

### Observed/Actual behavior

When first joining my server using 1.18.1 PaperMC I'm first to put somewhere else sometimes with no items, then eventually teleported to my logout position and given my items. However, a few times me and my friends I who play the server have noticed you don't always teleport back and regain your items. Sometimes you must relog to do so. I noticed this from the beginning before any plugins were installed and any .yml files were modified. Being in this state of in the wrong position with no items before teleporting back is happening a majority of the time. The time-varying before being put in my right position and given my inventory. In this wrong position state, I'm able to open doors and when teleporting to the right position and being regiven my inventory I notice the doors I opened in the areas I shouldn't have first been put in when joining remain open. The teleporting is pretty random but stays in a relative area near my logout spot. Always finding air holes whether that's my slime farm, cave, or farm. **Also** sometimes this random teleport is replaced with being in a void of an absurd amount of time. The server is located in Canada really near me, with a ping of 20-30ms, CPU usage being at 20%, and RAM usage being 2GB/6GB so I do not believe it is a specs or latency problem. The time of being in the void is relatively the same as being in the wrong position(sometimes short, sometimes so long that I rejoin before I load in)

### Steps/models to reproduce

Join a server with 1.18 PaperMC

### Plugin and Datapack List

AureliumSkills, CoreProtect, dynmap, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, floodgate, Geyser-Spigot, GroupManager, LevelledMobs, NBTAPI, NotTooExpensive, PlaceholderAPI, PlugManX (PlugMan), ProtocolLib, SimpleNoCropTrample*, sleep-most, TAB, TopKills*, TopMiners, TubeTils, UltimateTimber, Vault

### Paper version

1.18.1

**Comment by MiniDigger** [comment]
does it happen without any plugins or proxies? (I notice you use geyser)

**Comment by e-im** [comment]
This generally sounds like a poor connection to the server, but as you mentioned in your initial report, yours seems fine. As mini said, please replicate without plugins.
