### ISSUE TITLE
Soul Sand Valley Fortress Spawn Nerfed

### ISSUE THREAD

**Issue by JAM8706** [PaperSpigot/Paper#7241]
### Expected behavior

In vanilla minecraft 1.18.1, a fortress in a soul sand valley has the usual spawn rates, so we expect to see the mob cap fill. I would expect the same from PaperMC.

### Observed/Actual behavior

 When on PaperMC (from current to as far back as I was willing to test) these spawn rates are linked to the soul sand spawn rates, so we max out around 10-15 in a Soul Sand Valley Nether Fortress.

### Steps/models to reproduce

go to any Soul Sand Nether Fortress to see poor spawn rates.

### Plugin and Datapack List

unknown

### Paper version

paper-1.18.1-120

### Other

This is best noted either in creative mode where you can float above the nether fortress to make it all spawn-able or by standing on the nether roof above the fortress. Trying to make a Wither Skull farm. This farm works in 1.18.1. Getting zero spawns in the actual fortress in Paper and getting 10 or so skeletons in the soul sand valley area. I know that this area should spawn because a blaze spawned there once and because the same structure spawns all mobs in vanilla.

**Comment by ghost** [comment]
Sounds like a mob cap thing tbh, Im running 1.18.1 git 121, on an updated 1.16.5 world with a wither skelly farm based on Shulkercrafts video here: https://www.youtube.com/watch?v=le_tTlKEbyw with a full auto sorter below for everything and I get more than enough spawns. Did you spawn proof at all? Its very likely what you're actually getting is mobs spawning up to 128 blocks from you, which is why there's so few there. My advice is look for a warped forest fortress, and see if you have the same issue. Warped forests are Desolate of most mobs except Endermen, and in the fortress Blaze's Zombified Piglins, skellys and Wither Skeletons, thus leading to more chances of Skeletons spawning in the fortress.

**Comment by JAM8706** [comment]
I was 60 blocks away from the Fortress when testing.

The issue is with the spawn mechanics in a Soul Sand Valley. Vanilla Minecraft suppresses spawns in a Soul Sand Valley. It does not however suppress spawns in a Fortress even if it is in a Soul Sand Valley. Because of this, I would expect to see nearly a full mob cap of Fortress mobs. Instead I see the 10 or so Soul Sand Valley mobs and that is it.
I know this farm works in 1.18.1, I have it working in my testing world.

https://www.youtube.com/watch?v=ixGwh1pJb9o&t=486s

PaperMC appears to be suppressing all mob spawns in the Soul Sand Valley including Fortress mobs. This means, when I'm the only player logged in, the mob count never goes above 15 when I expect to see a full mob cap of 70+ due to Fortress spawns.

To reiterate, the key here is a Fortress inside the Soul Sand Valley on PaperMC has significantly less spawn than a Fortress inside the Soul Sand Valley on Vanilla.

**Comment by ghost** [comment]
> I was 60 blocks away from the Fortress when testing.
> 
> The issue is with the spawn mechanics in a Soul Sand Valley. Vanilla Minecraft suppresses spawns in a Soul Sand Valley. It does not however suppress spawns in a Fortress even if it is in a Soul Sand Valley. Because of this, I would expect to see nearly a full mob cap of Fortress mobs. Instead I see the 10 or so Soul Sand Valley mobs and that is it. I know this farm works in 1.18.1, I have it working in my testing world.
> 
> https://www.youtube.com/watch?v=ixGwh1pJb9o&t=486s
> 
> PaperMC appears to be suppressing all mob spawns in the Soul Sand Valley including Fortress mobs. This means, when I'm the only player logged in, the mob count never goes above 15 when I expect to see a full mob cap of 70+ due to Fortress spawns.
> 
> To reiterate, the key here is a Fortress inside the Soul Sand Valley on PaperMC has significantly less spawn than a Fortress inside the Soul Sand Valley on Vanilla.

im not sure if it’s a default setting, there’s an option in paper.yml for despawn ranges, check them and see if they’re all registered as soft 32 hard 128, if not change it and try again. Some server providers like Bisect either auto change that, or it’s a default setting on paper, but that maybe the issue.

**Comment by Owen1212055** [comment]
There have been significant changes to persistence and how the mob counts have counted thanks to upstream reverting some changes it made to that system.

Do you still find the spawn rates to be lower than normal?

**Comment by lynxplay** [comment]
As no more information on this was provided for now 19 days, I am closing this issue.

If you still experience this issue on latest paper and can provide proper replication steps, feel free to just comment on this issue so we can reopen it :+1: However, as pointed out, this does feel like potentially being a result of a mob cap.
