### ISSUE TITLE
Endermite Despawn

### ISSUE THREAD

**Issue by cylian914** [PaperSpigot/Paper#7256]
### Is your feature request related to a problem?

Hi, so when building enderman farm with endermite i notice it despear even if its named

### Describe the solution you'd like.

can you add option to select whitch entity despawn when named pls

### Describe alternatives you've considered.

make endermite not depawnable when it rename

**Comment by electronicboy** [comment]
entities being named is not a criterion for if they despawn or not, whether they're marked as persistent is what controls that, or at least should, and this is behaviour which will not be changed

if entities marked as persistent are despawning, that would be a bug
