### ISSUE TITLE
Players report running mobs

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#7257]
### Expected behavior

Mobs move in their normal speed.

### Observed/Actual behavior

Mobs jump/run/teleport towards the player

### Steps/models to reproduce

1. spawn a mob
2. mob notices you
3. mob starts running towards you

### Plugin and Datapack List

AuthMe Reloaded because we are friends who has eachother's accounts and this is a survival server, it's there to protect our inventories
SkinsRestorer to change our skins
SuperVanish so as the server owner i can joke around
ProtocolLib so SuperVanish works.

### Paper version

This server is running Paper version git-Paper-125 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 503ac8f)
You are running the latest version
Previous version: git-Paper-120 (MC: 1.18.1)

### Other

Server runs 20-19TPS all the times and none of the players have bad connection.

**Comment by kennytv** [comment]
Don't report bugs by one random player without actually reproducing them yourself; here I can fairly confidently say it's not the case unless your server/client is lagging, you're looking at a baby zombie, or some plugins is doing something bad.

**Comment by MiniDigger** [comment]
also: I bet 5 bucks this is an offline mode server

**Comment by ghost** [comment]
All of us have Xbox Gamepass.
