### ISSUE TITLE
Players take damage falling from 2 block

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#7258]
### Expected behavior

Player does not take damage from 2 block falls

### Observed/Actual behavior

Players take damage from 2 block falls

### Steps/models to reproduce

1. Place two blocks underneath the player
2. make them walk out of the block (not jump)
3. player takes damage

### Plugin and Datapack List

No datapacks

AuthMe Reloaded because we are friends who has eachother's accounts and this is a survival server, it's there to protect our inventories
SkinsRestorer to change our skins
SuperVanish so as the server owner i can joke around
ProtocolLib so SuperVanish works.

### Paper version

This server is running Paper version git-Paper-125 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 503ac8f)
You are running the latest version
Previous version: git-Paper-120 (MC: 1.18.1)

**Comment by NoahvdAa** [comment]
Can't reproduce on build 125, not even when jumping

https://user-images.githubusercontent.com/44026893/147878442-c2d4759a-d042-4b19-a36c-5e181f6dd06f.mov

**Comment by ghost** [comment]
I'll be trying to reproduce the bug with the same player who reported it.

**Comment by kennytv** [comment]
Don't report bugs by one random player without actually reproducing them yourself

**Comment by RigidOfficial** [comment]
Observed this as well with two of my players as well as myself, fixed randomly after ~10-30 minutes, un-reproducible. The only thing that links them is that at some point during their session, they wore an elytra. A client-side fall damage packet suppressor did nothing against this, as far as I know kinetic damage from elytra impact is calculated on server, perhaps this is an issue with elytra damage calculation then?
