### ISSUE TITLE
Add ability to let ravagers avoid trees/leaves

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#7260]
### Is your feature request related to a problem?

Ye, we use WorldGuard's flag `ravager-grief` with value `DENY`, so ravagers can't break leaves and make a mess in the world.
But with that flag, they just stuck in front of the trees, constantly jumping, instead of pathfinding to the player like other raid mobs.

### Describe the solution you'd like.

Add a setting to paper.yml that changes ravager's pathfinding so they will avoid/escape trees/leaves.

### Describe alternatives you've considered.

I don't know, seriously. Probably you're the only who can fix this :c

**Comment by zJanny** [comment]
This also happens when setting the gamerule "RULE_MOBGRIEFING" to false.
