### ISSUE TITLE
FilteredText not being set via sign API

### ISSUE THREAD

**Issue by AoElite** [PaperSpigot/Paper#7266]
### Expected behavior

Whenever you set a sign's text via the API it should set the sign's FilteredText1-4 nbt as well as Text1-4.

### Observed/Actual behavior

Whenever you set a sign's text via the API it does not set the sign's FilteredText1-4 nbt but does Text1-4.

### Steps/models to reproduce

```java
Block block = //get sign
Sign sign = (Sign) block.getState();
sign.line(1, Component.text().append(Component.text("hello!")).color(NamedTextColor.BLACK).build());
sign.update();
```
You can examine the sign's NBT data and see that it's only changing the `Text1` field in the nbt json but the `FilteredText1` is not being changed.

This is a issue for players who have the filtering text option enabled as they will not be able to see the sign's text. I do not know how players have this filtered text feature enabled and neither do they. I've seen it happen for players using any type of client, vanilla, fabric, and lunar randomly. However they all have one thing in common; they are sending a settings packet to the server that says they have text filtering enabled. https://wiki.vg/Protocol#Client_Settings

### Plugin and Datapack List

[02:42:56 INFO]: Plugins (0):

[02:43:20 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]

### Paper version

[02:43:47 INFO]: This server is running Paper version git-Paper-407 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: bf23668 on ver/1.17.1)
You are running the latest version

**Comment by MiniDigger** [comment]
filtering can be enabled on child accounts, people should check their privacy settings in the xbox account settings.

have you checked if this is only a problem with the adventure method or does it also affect the normal bukkit method?

**Comment by AoElite** [comment]
Bukkit method has this issue as well.

**Comment by MiniDigger** [comment]
has or had, after that commit?

**Comment by kennytv** [comment]
had, because the update isn't done in the setLine/line methods but in one update method

**Comment by Flugelo** [comment]
save bro.

Do you intend to put the entities in async?

I realized that the only limitation of 1.18.1 is on entities that run on MainThread...

if they managed to put the entities in Async, I'm sure the server would run 10x better.

**Comment by TheShermanTanker** [comment]
> 

Blindly dumping things onto another thread is never going to help, if that was all it took to optimize logic flow Paper (and quite possibly Mojang) would've done it by now
