### ISSUE TITLE
io.netty.handler.codec.EncoderException

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#7267]
### Expected behavior

I can view the entity data.

### Observed/Actual behavior

See https://paste.gg/p/anonymous/50c4dcfb31e94df3bf26552dadd21832
I think that this can also happen with entity if it have large amount of NBT data (e.g. fully enchanted armor, huge written books, commands blocks with predefined commands, shulker boxes with another huge amount of enchanted items, ...) 

### Steps/models to reproduce

1/ Fill up your inventory with items described in `Actual behavior` or similar
2/ Type `data get entity @s`

### Plugin and Datapack List

```
> pl
[12:55:50] Plugins (0): _
> datapack list
[12:55:54] There are 1 data packs enabled: [vanilla (built-in)]]
[12:55:54] There are no more data packs available
>
```

### Paper version

```
> version
[12:56:33] Checking version, please wait...
[12:56:33] This server is running Paper version git-Paper-129 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: d0b8b1e)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-126 (MC: 1.18.1)
```

Ye it's `3 version(s) behind` but there's nothing changed in last 3 commits related to this issue.

### Other

![image](https://user-images.githubusercontent.com/19989717/147918198-c72ff764-5881-4baf-914a-6553341c7889.png)

**Comment by ocelotpotpie** [comment]
This seems like something in the inv with too much NBT data. Can you post the contents of the shulker box and check their NBT data?

**Comment by molor** [comment]
I have 4 sets of diamond armor enchanted with 
![image](https://user-images.githubusercontent.com/19989717/147922464-4ab3fada-233f-470a-8af6-90c3cda951af.png)
4 shulker boxes with same armor sets
![image](https://user-images.githubusercontent.com/19989717/147922519-fac36043-425f-424c-8301-6411e645c1a5.png)
And some command blocks with command inside
![image](https://user-images.githubusercontent.com/19989717/147922578-ce6b9471-cc2d-4605-8365-5355ea7a7045.png)
(just for `test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test`, I think this can be reproduced even without it)

There are my player.dat that you can open with NBT Explorer or (while on server) just disconnect, replace your playerdata/uuid.dat with it and join again:
[112cbc5a-75cd-4815-a27b-31417f88108d.zip](https://github.com/PaperMC/Paper/files/7801515/112cbc5a-75cd-4815-a27b-31417f88108d.zip)

**Comment by e-im** [comment]
The data is too big to fit into a chat message. While this is technically a bug, it's a real non-issue and pretty much a wontfix. Just either run commands like that from the console / don't try to get such huge data.
