### ISSUE TITLE
Option to disable marker entity ticking

### ISSUE THREAD

**Issue by aerulion** [PaperSpigot/Paper#7276]
### Is your feature request related to a problem?

I'm experimenting with the marker entities added in 1.17.

In my use case, I don't really see a point in ticking them and would love to have the option to disable the ticking, as it drastically reduces tick durations with large amounts of markers, at least if my simple test is valid:

1. Summon a large amount of markers (262,000 in my test)
2. Watch the TPS drop to ~8
3. Move far away until '/paper entity list' recognizes the marker as non-ticking entities
4. Watch the TPS instantly rise to 20 again

### Describe the solution you'd like.

Some method to disable marker ticking, either individually, or all together.

### Describe alternatives you've considered.

None that I could think of, as it isn't really a problem and more like an improvement.

**Comment by Spottedleaf** [comment]
is there a reason you need 200 thousand marker entities doing nothing on your sever?

**Comment by electronicboy** [comment]
I thought entity markers already didn't tick? o.O

**Comment by electronicboy** [comment]
Oh, they have 0 tick logic, just, everything ends up in there and so they're iterated over

**Comment by aerulion** [comment]
> is there a reason you need 200 thousand marker entities doing nothing on your sever?

No, of course not, that was more like a massively exaggerated test. But I don't really see the point of them affecting the TPS in any way, since they are just supposed to be markers

**Comment by aerulion** [comment]
In my earlier tests, having ~1200 Markers (which would be more realistic for my use-case) increased the tick duration from ~0,4 mspt to ~2-3 mpst on a completely empty server, which was relatively high in my opinion if they are supposed to do nothing

**Comment by aerulion** [comment]
> Oh, they have 0 tick logic, just, everything ends up in there and so they're iterated over

Wouldn't it be possible to completely exclude them from the tick list if a certain option is enabled? Or would that break something else (aside from the obvious, like not having correct values for the ticks the entity has lived) ?
