### ISSUE TITLE
Fire tick speed

### ISSUE THREAD

**Issue by ByteBeamer** [PaperSpigot/Paper#7277]
### Is your feature request related to a problem?

Griefing

### Describe the solution you'd like.

A config option to set fire tick speed.

### Describe alternatives you've considered.

Looking for another plugin without success.

### Other

I noticed fires on my server spread very quickly and would like to slow them down. I however do **not** want to disable fire spread entirely.

**Comment by zJanny** [comment]
Is [this](https://streamable.com/eszing) what you want? 
The default value is 30, and by lowering it you speed the fire up and slow it down when you increase the value.

I just noticed i cut the video with the value set to 60 quite short, [here](https://streamable.com/k07ju0) is the longer version to better see the diffrence.

**Comment by ByteBeamer** [comment]
Yes! This is exactly what I am looking for!

**Comment by ByteBeamer** [comment]
bump

**Comment by Chew** [comment]
Please don't bump the issue, especially since there's an open PR for this... just wait for it to be merged.

**Comment by ByteBeamer** [comment]
Sorry, this is my first issue
