### ISSUE TITLE
Add #setLogoutLocation(Location) and #getLogoutLocation() to OfflinePlayer

### ISSUE THREAD

**Issue by justEli** [PaperSpigot/Paper#7287]
### Is your feature request related to a problem?

It is not related to a problem. I think it would be useful to change the logout location of an offline player.

### Describe the solution you'd like.

Add two methods to `OfflinePlayer`:
- `void setLogoutLocation(Location)`
- `Location getLogoutLocation()`

### Describe alternatives you've considered.

If a Player on PlayerJoinEvent is directly teleported, it first loads (some) chunks of the place they spawned at, and then the place they get teleported to. That's inefficient.

**Comment by zJanny** [comment]
You can just teleport them to where they should spawn in the PlayerQuitEvent.

**Comment by justEli** [comment]
Yes that's true, but that doesn't work for what I want to do.

**Comment by kezz** [comment]
Have you not thought about using the `PlayerSpawnLocationEvent`?

**Comment by electronicboy** [comment]
can also use the spawn location events too, ninja... I'm not really sure this is something which we can implement safely in a manner which wouldn't block other plans

**Comment by justEli** [comment]
> Have you not thought about using the `PlayerSpawnLocationEvent`?

That should do. You can close the issue if you want. Didn't expect there to be such an event.
