### ISSUE TITLE
Worlds spewing "Recoverable errors when loading section" errors after importing map on Paper

### ISSUE THREAD

**Issue by chickenputty** [PaperSpigot/Paper#7289]
### Stack trace

Spewed Error: [https://paste.gg/p/anonymous/14a44c3536054244954e6c31f0a16597](https://paste.gg/p/anonymous/14a44c3536054244954e6c31f0a16597)

Stack Trace Error: [https://paste.gg/d5918d4810384507a179904c1a3d3d2f](https://paste.gg/d5918d4810384507a179904c1a3d3d2f)

### Plugin and Datapack List

Plugins (14): Arceon, Builders-Utilities, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncVoxelSniper, FastAsyncWorldEdit (WorldEdit), goBrush, goPaint, Multiverse-Core, PermissionsEx*, Vault, VoidGen, WorldGuard

### Actions to reproduce (if known)

Take a world from Minecraft Bedrock, use Chunker to convert it to 1.18, import this world using Multiverse Core into Paper. After teleporting to the world, the "Spewed Errors" happen. After saving the loaded world, the "Stack Trace Error" happens.

### Paper version

Paper version git-Paper-133 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 5e30e19)

### Other

Not exactly sure to report this to (Chunker or Paper/Spigot), but we are encountering errors when we take a Bedrock 1.18 world, convert it to Java 1.18, import it on Paper 1.18, and teleport to the map. Visually it does not appear to have any problems, but the main issue is with saving the map and loading it. Errors seem to spew out for for every block with that biome when you teleport to the world. When you save the world, the server freezes and a stack trace appears.

**Comment by MiniDigger** [comment]
the same happens if you load on spigot? does this also happen if you load it on vanilla? if so, there is nothing we can do and you should talk to chunker people.

**Comment by electronicboy** [comment]
The biomes, at least from what I've seen of your trace, are using the outdated names which where changed in the 1.18 dev cycle, this would seem that chunker needs updating for that

**Comment by chickenputty** [comment]
> The biomes, at least from what I've seen of your trace, are using the outdated names which where changed in the 1.18 dev cycle, this would seem that chunker needs updating for that

Thanks, it was this. Chunker resolved it! "Fixed discontinued 1.18 biomes incorrectly being translated."
