### ISSUE TITLE
Thread RCON Client /0:0:0:0:0:0:0:1 #5 failed main thread check: command dispatch

### ISSUE THREAD

**Issue by sudothefox** [PaperSpigot/Paper#7297]
### Expected behavior

No error.

### Observed/Actual behavior

Error: https://pastebin.com/2ahuDPuq

### Steps/models to reproduce

Use mcrcon to pass the command "stop" to the server via RCON.

### Plugin and Datapack List

Plugins (35): AFKPlus, AureliumSkills, BuycraftX, Chunky, CookieCore, CoreProtect, CustomMOTD, EnderDragonTweaks, Essentials, EssentialsChat, Exhaustion, Expeditions, GameruleManager, HolographicDisplays, JakesRTP, LibsDisguises, LiteBans, LuckPerms, LWC, LWCTrust, MythicMobs, PlaceholderAPI, PremiumVanish, ProtectedSpawners, ProtocolLib, RegexFilter, ShulkerPacks, squaremap, SquaremapPlayers, StaffChat, TabList, Vault, Votifier, Vulcan, WorldEdit

There are 3 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/svmc-datapack (world)]There are no more data packs available

### Paper version

This server is running Paper version git-Paper-134 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 55a1756)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-133 (MC: 1.18.1)

**Comment by e-im** [comment]
Have you been able to/would you be able to try reproducing this without plugins? From a glance, this all looks correct, and I can't reproduce.

**Comment by bdagenais2** [comment]
> Have you been able to/would you be able to try reproducing this without plugins? From a glance, this all looks correct, and I can't immediately reproduce.

One of the dumps I shared was without any plugins.
