### ISSUE TITLE
Paper Watchdog is frequently interfering with world pregeneration

### ISSUE THREAD

**Issue by Hex27** [PaperSpigot/Paper#7306]
### Expected behavior

World pregeneration should not trigger paper watchdog when minor freezes for chunk processing occur

### Observed/Actual behavior

Every single world generation plugin discord that I've been inside recommend turning paper watchdog off for pregeneration, as its a very common source of spam. It gets worse when paper watchdog falsely detects a server crash

I understand that the watchdog is supposed to identify sources of lag and prevent indefinite server hanging, and that watchdog partially activates due to world generation plugins as a whole being not-that-optimised, but I'm hoping that there could be some sort of compromise to allow world generation and world pregeneration more leeway when it comes to watchdog to prevent watchdog from interfering with world generation, especially with lower-spec servers.

### Steps/models to reproduce

Pick any world generation mod from spigot and run a pregeneration plugin like Chunky on a low-spec paper server. Watchdog will trigger and cause a hard crash in the worst case, and console spam in the best case.

Exact example steps to reproduce:
1. Run paper with very low ram on a very slow CPU (this is to force the bug to occur)
2. Add [TerraformGenerator](https://www.spigotmc.org/resources/terraformgenerator-alpha.75132/) and [Chunky](https://www.spigotmc.org/resources/chunky.81534/) to plugins
2. Start the server and run "chunky set 5000" and "chunky start"
3. Wait for paper watchdog errors, and an eventual paper watchdog termination

### Plugin and Datapack List

The "turn off paper watchdog" recommendation was found in Iris, Terra, EWG, RWG and TerraformGenerator discords. 

World pregeneration plugins don't seem to matter and all of them can cause the same problem (Chunky, WorldBorder etc).

### Paper version

All paper versions have this issue as its the same watchdog setting. Testing was done on the latest paper version as well.

This server is running Paper version git-Paper-141 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 7d7ae7b)

**Comment by electronicboy** [comment]
Paper doesn't know when you're pregenning, and disabling/neutering the watchdog here is not worth the time investment into figuring out how best to do it for this specific scenario which is generally a non issue anyways

there is no reason that plugins like Chunky couldn't tick the watchdog themselves to disable it from tripping
