### ISSUE TITLE
Client lag when somebody chats

### ISSUE THREAD

**Issue by rrvk** [PaperSpigot/Paper#7307]
### Timings or Profile link

https://timings.aikar.co/?id=4f101daedde14a79806a20a9514a6a7f

### Description of issue

When there isn't any chat for a bit (like 1-5 min) and then somebody chats there is a lag spike for everybody on the server. Then when people just keep talking there is no lag. 

But when it is silient for a bit and then somebody started to chat there is that lag spike again

### Plugin and Datapack List

```
> plugins
[16:06:50 INFO]: Plugins (0): 

> datapack list
[16:07:03 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[16:07:03 INFO]: There are no more data packs available
```

### Server config files

```
bukkit.yml: https://paste.gg/p/anonymous/b3779d2e256d40f2b50662315ea1ec0c
spigot.yml: https://paste.gg/p/anonymous/248b06a2a36e4090878190a06ec0fbef
paper.yml: https://paste.gg/p/anonymous/74fd942155764551881c9edd843508fd
```

### Paper version

```
> version
[16:08:11 INFO]: Checking version, please wait...
[16:08:12 INFO]: This server is running Paper version git-Paper-141 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 7d7ae7b)
You are running the latest version
Previous version: git-Paper-136 (MC: 1.18.1)
```

**Comment by NoahvdAa** [comment]
This is a known Mojang issue: [MC-247973](https://bugs.mojang.com/projects/MC/issues/MC-247973). I've made a [plugin](https://www.spigotmc.org/resources/nochatlagserver-fixes-chat-lag-spikes.99046/) or [client mod](https://modrinth.com/mod/nochatlag) as a temporary solution.

**Comment by rrvk** [comment]
Thanks, that workaround seems to work for me, i will close this issue then.

**Comment by molor** [comment]
(`Hide Matched Names: OFF` in `Chat Settings` probably fixes this issue too)

**Comment by NoahvdAa** [comment]
That only fixes half of the problem: the client attempting to find the player's UUID from the username. It'll still try to check the block for the sender UUID, unless it's nilled out, which normally happens when the server sends messages (but can be forced for every message by a plugin).
