### ISSUE TITLE
Add PostInventoryClickEvent

### ISSUE THREAD

**Issue by u9g** [PaperSpigot/Paper#7309]
### Is your feature request related to a problem?

Yeah, I'm interested in making a plugin that acts based on what the player clicked, after they do the click, like did they put on the last armor piece needed to have a full set of custom armor or did they just put an item into a slot? I have to basically recreate the logic if I want to see what happens after an InventoryClickEvent.

### Describe the solution you'd like.

Please add a `PostInventoryClickEvent`

### Describe alternatives you've considered.

Checking the inventory action, the slots involved, etc, but it's a lot of code for something that could be as easy as just a `PostInventoryClickEvent`.

### Other

I can code this if it's accepted as a feature request.

**Comment by lynxplay** [comment]
The https://papermc.io/javadocs/paper/1.18/com/destroystokyo/paper/event/player/PlayerArmorChangeEvent.html event exists and probably does exactly what you are looking for here.

Besides that I personally do not believe a `PostAnything` event Is a good idea to start with. The next feature request is a `PostBlockBreak` event etc. etc.

You should be perfectly fine using existing events or doing a little bit of local logic to figure out if the event does what you want.
Make sure to run on event priority monitor if you are not planning on modifying the event but only want to listen and respect other plugins changes.
