### ISSUE TITLE
gamerule mobGriefing Inconsistent across dimensions

### ISSUE THREAD

**Issue by EvilSupahFly** [PaperSpigot/Paper#7310]
### Expected behavior

I expect that when I issue `gamerule mobGriefing false` that it's disabled across all dimensions, period. Not just the dimension the issuing player or op is in at the time.

### Observed/Actual behavior

Issuing the command `gamerule mobGriefing false` only disables it for the dimension you're in at the time - typically, `minecraft:overworld` - requiring the command to be issued again in `minecraft:the_nether` and a third time in `minecraft:the_end`.

### Steps/models to reproduce

Start the papermc server, and check the status of `gamerule mobGriefing` in each of the three vanilla dimensions after changing it in only one of them.

### Plugin and Datapack List

Plugins: Chunky, WorldEdit
Datapacks: [vanilla (built-in)], [file/bukkit (world)]

### Paper version

This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)

### Other

It's a minor irritation, but nothing serious. I just don't know if anybody was aware before.

**Comment by jpenilla** [comment]
This is intentional, CraftBukkit makes gamerules per-world. You can use `/execute in [world_key] run gamerule ...` to avoid needing to teleport

**Comment by EvilSupahFly** [comment]
Oh...
