### ISSUE TITLE
Change timings' "ticking-distance" to simulation-distance on 1.18

### ISSUE THREAD

**Issue by voidpls** [PaperSpigot/Paper#7312]
### Is your feature request related to a problem?

Currently, the ticking-distance that timings receives on 1.18 servers is the view-distance, rather than the new simulation-distance. 

Patch in question:
https://github.com/PaperMC/Paper/blob/master/patches/server/0010-Timings-v2.patch
```
+        parent.put("worlds", toObjectMapper(MinecraftServer.getServer().getAllLevels(), world -> {
+            if (world.getWorld().getName().equals("worldeditregentempworld")) return null;
+            return pair(world.getWorld().getName(), createObject(
+                pair("gamerules", toObjectMapper(world.getWorld().getGameRules(), rule -> {
+                    return pair(rule, world.getWorld().getGameRuleValue(rule));
+                })),
+                pair("ticking-distance", world.getChunkSource().chunkMap.getEffectiveViewDistance())
+            ));
+        }));
```

### Describe the solution you'd like.

Send `simulation-distance`, instead of `view-distance`

### Describe alternatives you've considered.

Create a separate field for simulation-distance on 1.18 servers

**Comment by e-im** [comment]
a new field would be the way to go here rather than replacement. It would also be nice to have server.properties provided as a whole, but what should be redacted needs to be taken into consideration there (and, the current system for exclusion/redaction isn't very good with certain things hardcoded with other random options being in a config)

**Comment by voidpls** [comment]
Agreed, the lack of server.properties from the "Config" tab really cripples the ability to diagnose some config errors using Timings alone. In the meantime, a new `simulation-distance` field would be helpful.

**Comment by Doc94** [comment]
this is not already in https://github.com/PaperMC/Paper/blob/1358d1e9146ca80d0ff84a644c7796d20b39765c/patches/server/0858-Replace-player-chunk-loader-system.patch ?

**Comment by voidpls** [comment]
> this is not already in https://github.com/PaperMC/Paper/blob/1358d1e9146ca80d0ff84a644c7796d20b39765c/patches/server/0858-Replace-player-chunk-loader-system.patch ?

Yes, this has since been implemented as `no-ticking-distance`
