### ISSUE TITLE
Get CombinedID from Block or Material

### ISSUE THREAD

**Issue by LeonTheo02** [PaperSpigot/Paper#7314]
### Is your feature request related to a problem?

Currently when you want to send Packets for FallingBlocks they require a "CombinedID" as block data to set their material. The problem is that this ID can only be get via NMS and that causes problems on every update when methods are moved.

### Describe the solution you'd like.

Adding a "getCombinedID" method to either the Block or the Material class so that the CombinedID can be obtained without NMS.

### Describe alternatives you've considered.

Using NMS, but thats often not a very reliable solution.

**Comment by electronicboy** [comment]
No, registry IDs are not an API aspect
