### ISSUE TITLE
Add another overload for Player#sendBlockDamage with entityId

### ISSUE THREAD

**Issue by u9g** [PaperSpigot/Paper#7319]
### Is your feature request related to a problem?

You can only tick two different blocks at once if they have different entityIds.

### Describe the solution you'd like.

just add another overload that allows giving another entityid or some abstraction over that.

### Describe alternatives you've considered.

going to userdev.

**Comment by Owen1212055** [comment]
Will be Resolved by: https://github.com/PaperMC/Paper/pull/5840
So Dupe of: https://github.com/PaperMC/Paper/issues/5246

**Comment by lynxplay** [comment]
Indeed, thanks for the scouting <3.
Closing this as a duplicate of #5246
