### ISSUE TITLE
Player version bug

### ISSUE THREAD

**Issue by CerialPvP** [PaperSpigot/Paper#7337]
### Expected behavior

I expected to see that the command will reply with my actual version.

### Observed/Actual behavior

I was on 1.8, and it says in the screenshot that i'm on 1.17 (i tried everything, either using viaversion as an api, using Skript addons and more.)

### Steps/models to reproduce

1. Get Skript & Skript-reflect
2. Go to Skripts/scripts and put the file I am attaching below, and then type /mcversion <player>.
3. Join on 1.8
4. And here you g

I will attach what I am getting & the script.
(the green is the version, cyan is protocol version)
![image](https://user-images.githubusercontent.com/71380797/149502268-88228ba1-51d3-4cb9-a3b0-ea185c82976d.png)
![image](https://user-images.githubusercontent.com/71380797/149502301-6bb348c5-f41f-4b3b-bd80-3e37a8ac4461.png)

Since I can't upload .sk's into GitHub, i will just paste it in here.
`# Version checker skript
# You need skript-reflect to be installed for this to work

import:
	us.myles.ViaVersion.api.Via

function getVersion(p: player) :: string:
	set {_ver} to "%Via.getAPI().getPlayerVersion({_p})%"
	if {_ver} = "757":
		return "1.18/1.18.1"
	
	if {_ver} = "756":
		return "1.17.1"
	
	if {_ver} = "755":
		return "1.17"
	
	if {_ver} = "754":
		return "1.16.4/1.16.5"
	
	if {_ver} = "753":
		return "1.16.3"
	
	if {_ver} = "751":
		return "1.16.2"
	
	if {_ver} = "736":
		return "1.16.1"
	
	if {_ver} = "735":
		return "1.16"
	
	if {_ver} = "47":
		return "1.8-1.8.9"

# You can use this function to get a player's version

command /version <player>:
	usage: &6Usage: &7/version <player>
	permission: whatever.the.fuck.you.have
	permission message: whatever the fuck you have
	trigger:
		send "&6%arg 1%&7's version is &2%getVersion(arg 1)% &3(%Via.getAPI().getPlayerVersion(arg 1)%)"`

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/71380797/149502570-2697cd1b-0ac0-43e6-a0c9-9ff4332ebd08.png)

### Paper version

git-Paper-338 (MC: 1.17.1)

### Other

I am using MInehut

**Comment by MiniDigger** [comment]
paper doesn't allow old versions to join. as such, this is not a paper bug.
this might be a via bug, but you also use a client that is known to cause  insanely dum issues so via people will tell you to try with a vanilla client.
