### ISSUE TITLE
Paper break Datapack

### ISSUE THREAD

**Issue by Ilovelinux68** [PaperSpigot/Paper#7338]
### Expected behavior

Normally with this datapack custom entities should spwan when sanity is low

https://github.com/HingeDH/manic-public

### Observed/Actual behavior

With the command /function manic:commands/summon/"mobs"
I can spawn the mobs, but they don't spawn naturally.
I tested under spigot and the entities spawn very well under spigot with the same plugin the same map.

### Steps/models to reproduce

Install the data pack on a server, do not forget the resource pack
Wait until mental health is low
Waiting for the night
You can do the same thing on spigot
to see that the entities spawn wel

### Plugin and Datapack List

Plugin:
Plugins (24): LuckPerms, nLogin, Ascenseur, BlockLocker, PlaceholderAPI, spark, WorldBorder, HolographicDisplays, Votifier, zVoteParty, SkinsRestorer, LightAntiCheat, Vault, MyCommand, LPC, WorldEdit, ViewDistanceTweaks, Chunky, Essentials, RandomTP, WorldGuard, TAB, EssentialsSpawn, WorldGuardExtraFlags
datapack:
Datapack:
There are 10 data packs enabled: [vanilla (built-in)], [file/harderendcity1-18.zip (world)], [file/terralith-v2-0-4.zip (world)], [file/04-towns-and-towers-more-structures-add-on-e3230.zip (world)], [file/datapack-coloured-axolotl-bucket-e3470.zip (world)], [file/textures-coloured-axolotl-buckets.zip (world)], [file/bukkit (world)], [file/manicdp-0-2s5c.zip (world)], [file/Devons TRUE SURVIVAL Version 4.1.0.zip (world)], [file/ManicRP-0.2s5c.zip (world)]

### Paper version

This server is running Paper version git-Paper-152 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 78999b5)

### Other

I think Paper touches on Minecraft's features and that's why it doesn't work

**Comment by Ilovelinux68** [comment]
I want to specify I also tested without plugin!

**Comment by Machine-Maker** [comment]
I can't get them to spawn on a vanilla server. In survival mode with the mob spawning gamerule set to true, I had the datapack and resource pack loaded on a vanilla 1.18.1 server, I ran `/scoreboard players set @s manic.sanity 20` to lower the sanity to just 20 seconds left, and then `/scoreboard objectives setdisplay sidebar manic.sanity` to show it on the sidebar, when it hit 0, nothing started spawning around me.

**Comment by Ilovelinux68** [comment]
/scoreboard players set @s manic.sanity -78
Go down into the negative (-26 for example) put yourself in survival and wait.
As you can see on spigot it works
But not under paper
You can test by changing the startup jar and killing the entities
![2022-01-14_19 41 34](https://user-images.githubusercontent.com/62102461/149568272-90b675a8-93b7-4f7b-b9d1-3d80bde39a72.png)
![2022-01-14_19 42 29](https://user-images.githubusercontent.com/62102461/149568299-74aa47cb-de40-4cad-b0d2-49485ceba674.png)

**Comment by Lulu13022002** [comment]
I can't reproduce this, custom mobs spawn when sanity is low in cave
I get only the message:
"Unable to add mob to team "smithed.prevent_aggression" (that team probably doesn't exist)" because this datapack
needs the config option scoreboards.allow-non-player-entities-on-scoreboards set to true in order to work correctly.
I think paper should change the message when this flag is disabled but that's another issue.

**Comment by NoahvdAa** [comment]
Can't reproduce on 1.19.2 build 134 with `save-empty-scoreboard-teams` and `allow-non-player-entities-on-scoreboards` both set to `true`. After eating a lot of rotten flesh at night, I went insane and the Spook and Insomniac both showed up.

If you can still reproduce this issue on the latest build with both of the above-mentioned settings set to true, please comment on this issue or create a new one.
