### ISSUE TITLE
1.18.1 Chunk loading and generation too slow, players spawns into void for 30+ seconds

### ISSUE THREAD

**Issue by xgab05x** [PaperSpigot/Paper#7339]
### Timings or Profile link

https://timings.aikar.co/?id=e8573f7f3a1b4f99aa447cb894389adc

### Description of issue

hi, 1.18.1 chunk loading is too slow, i tried changing server version in 1.17 and the problem disappear. i also tried to reset worlds and all bukkit, spigot and paper configs, using default ones but nothing changes. I also tried removing all plugins and datapacks. 1.18.1 chunk generation is currently so slow that, when a player spawn, world doesn't load for 30-40 seconds and player falls into void. i experimented a 3500+ ping on chunk loading. how can i solve this issue?

### Plugin and Datapack List

ProtocolLib, Multiverse-core, Worldedit, luckperms

I also tried without any plugin but nothing changes

### Server config files

bukkit.yml, paper.yml and spigot.yml are default ones.
this is my server.properties:

#Minecraft server properties
#Fri Jan 14 17:07:09 UTC 2022
enable-jmx-monitoring=false
rcon.port=25575
enable-command-block=false
gamemode=survival
enable-query=false
level-name=world
motd=A Minecraft Server
query.port=25565
pvp=true
difficulty=easy
network-compression-threshold=-1
max-tick-time=60000
require-resource-pack=false
max-players=40
use-native-transport=true
online-mode=false
enable-status=true
allow-flight=false
broadcast-rcon-to-ops=true
view-distance=8
server-ip=
resource-pack-prompt=
allow-nether=true
server-port=25561
enable-rcon=false
sync-chunk-writes=false
op-permission-level=0
server-name=test
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=6
player-idle-timeout=5
debug=false
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=false
spawn-npcs=true
spawn-animals=true
snooper-enabled=true
function-permission-level=2
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
resource-pack-sha1=
spawn-protection=0
max-world-size=29999984

### Paper version

i tried: git-Paper-152 (MC: 1.18.1) and git-Paper-81 (MC: 1.18.1). Nothing changes

with 1.17.1 paper versions the problem disappear, but i need 1.18.1 on server

### Other

i tried also disabling bungeecord and tcpshield but nothing changes, i think it's a chunk generation problem

**Comment by DarkEyeDragon** [comment]
Chunks are a lot bigger in 1.18 so they take longer to generate, pre generating your world will improve it a lot but it'll never be as fast as it was before. It sucks but at least we get giant caves now

**Comment by xgab05x** [comment]
> Chunks are a lot bigger in 1.18 so they take longer to generate, pre generating your world will improve it a lot but it'll never be as fast as it was before. It sucks but at least we get giant caves now

spawn chunks are generated yet, currently the problem is on chunk loading, when i spawn i see chunks loading on top of me while i fall into void

**Comment by Decme** [comment]
This is a known issue. It will be vastly improved once the remaining Tuinity patches are ported to 1.18, mainly things like the chunk rate limiter.

In the meantime, if you're using anti-xray mode 2, switching to mode 1 does help considerably.

You can also reduce simulation distance and viewdistance even further, and make them match, then use the Fartherviewdistance plugin which has a chunk send limiter built in. I have 31 viewdistance using the plugin and my players no longer have ping issues.

**Comment by electronicboy** [comment]
closing, ref above comments and #6136
