### ISSUE TITLE
Add support for per-world datapacks

### ISSUE THREAD

**Issue by prototype464** [PaperSpigot/Paper#7347]
### Is your feature request related to a problem?

I made a very simple custom crafting recipe datapack for a world of mine in a server (Using the latest version of Paper, still 1.17.1 while I wait for plugin updates and the game version to have better stability.)

I tried to put the datapack in a subworld (In the datapacks folder of course, also using Hyperverse to manage multiworlds), but it would not load, and wasn't getting recognized. The datapack has a pack version, proper file structure, everything.

After looking it up, turns out that unless the datapack is in the main world's datapack folder, this will not work. The datapack is supposed to only be in this specific subworld, and not all worlds, which it will unfortunately be with the current behavior.

I also realized a datapack I'm planning on using when I upgrade, [Terralith 2.0](https://www.planetminecraft.com/data-pack/terralith-overworld-evolved-100-biomes-caves-and-more/), being in the main world, is going to affect all of the subworlds, which is also undesired behavior.

### Describe the solution you'd like.

A good solution would either be to allow the usage of datapacks in subworlds and load them per-world, in that world, and only in that world (or have an option to toggle behavior for this, since for a lot of worlds using the same datapack, this could be time consuming), or to have some kind of setting that acts as a whitelist while you have the datapack(s) in the main world folder (They'd be loaded with it if enabled), these would be toggled per-world within the settings (bukkit.yml, spigot.yml, paper.yml, etc.)

### Describe alternatives you've considered.

I would use a plugin for this, but I have literally no idea where to start looking, due to datapacks being seen as such a taboo by Paper and multiplayer in general, and because compatibility between datapacks and plugins has always been iffy.

**Comment by e-im** [comment]
Thank you for the suggestion; unfortunately, at this time, this is outside of the scope of Paper, especially given craftbukkit's already shaky at best datapack support.
