### ISSUE TITLE
Add `Context` heading to the bug report issue template

### ISSUE THREAD

**Issue by lokka30** [PaperSpigot/Paper#7348]
### Is your feature request related to a problem?

Whilst reporting #7301, I found that PaperMC's bug report issue template does not have an area to explain the context of the issue. This can provide vital information in how the bug occurred, the reason it happened, technical info, and so on.

### Describe the solution you'd like.

Simply adding a text box at the top to explain the context of the issue does it. Unsure whether it should be a required or optional field, feel free to comment your opinion.

### Describe alternatives you've considered.

In #7301, I just added the context to the top of the first box, and added a divider below it, like so:

⬇️ 

***

⬆️

**Comment by Chew** [comment]
This sorta falls under "Other" imo, context can go here since it's usually not crucial. All the context we need would be in "Steps to Reproduce" imo

**Comment by lokka30** [comment]
> This sorta falls under "Other" imo, context can go here since it's usually not crucial. All the context we need would be in "Steps to Reproduce" imo

I'd recommend taking a look at #7301 - here I had to include some technical information about the issue, but there was no 'context' area to put it in. Hope this example helps :)

**Comment by electronicboy** [comment]
info you provided for the context really shoulda been provided in the reproduction steps, like, nobody is gonna see that behavior outside of macOS and somebody who tried to skim fast may have missed the ret-con'd section, it also adds a section which isn't exactly needed as it's covered under the existing sections, IMHO

I am open for improvements to the templates, but, am not sure this is it, or that this aids in understanding how to fill it out much more and just would lead to duplicate into across sections or confusing people imho

**Comment by lokka30** [comment]
Perhaps the 'Additional information' section already encompasses this issue's aim.

**Comment by e-im** [comment]
I'd agree; the additional information/reproduction section is where stuff like this can go. Additionally, the sections don't need to be 100% adhered to, especially for issues with a self-evident cause/solution.
