### ISSUE TITLE
ItemStack#getI18NDisplayName doesn't provide the right name for potions

### ISSUE THREAD

**Issue by justEli** [PaperSpigot/Paper#7356]
### Expected behavior

According to the Docs, `ItemStack#getI18NDisplayName` should provide the exact display name of an item the way the client sees it:

> public String getI18NDisplayName()
> Gets the Display name as seen in the Client. Currently the server only supports the English language. To override this, You must replace the language file embedded in the server jar.

For potions, this is not true. For example, the method ran on a 'Potion of Fire Resistance' returns just 'Potion'. I noticed this because I am rewriting code from Spigot's component API to Paper's. This used to work fine on Spigot: 
```java
import net.md_5.bungee.api.chat.TextComponent;
import net.md_5.bungee.api.chat.TranslatableComponent;
import org.bukkit.Material;
import org.bukkit.craftbukkit.v1_17_R1.inventory.CraftItemStack;
import org.bukkit.craftbukkit.v1_17_R1.util.CraftMagicNumbers;
import org.bukkit.inventory.ItemStack;

ItemStack itemStack = ...;
Material material = itemStack.getType();
String i18nDisplayNameSpigot = new TextComponent(
    new TranslatableComponent(
        CraftMagicNumbers.getItem(material).j(CraftItemStack.asNMSCopy(itemStack)
    )
).toPlainText();

logger.info(i18nDisplayNameSpigot); // Output:  Potion of Fire Resistance
```

### Observed/Actual behavior

```java
import org.bukkit.inventory.ItemStack;

ItemStack itemStack = ...;

String i18nDisplayNamePaper = itemStack.getI18NDisplayName();
logger.info(i18nDisplayNamePaper); // Output:  Potion
```

### Steps/models to reproduce

See explanation above.

### Plugin and Datapack List

[20:57:52 INFO]: Plugins (26): AuctionHouse, BetterConcrete, ChestShop, Chunky, Coins, common, CoreProtect, CreepersTrimGrass, DoorsReloaded, dynmap, eBackup, GriefPrevention, GSit, Ill-Equipped, LuckPerms, network-utils, OpenInv, PlugManX (PlugMan), rules, SmoothSleep, survival, TradePlus, UltimateTimber, Vault, ViewDistanceTweaks, Votifier

no datapacks

### Paper version

[22:06:02 INFO]: §f§oChecking version, please wait...
[22:06:02 INFO]: §fThis server is running Paper version git-Paper-154 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 5c74af2)§r

**Comment by Machine-Maker** [comment]
I think that method should be deprecated probably? idk. But you should use translatable components as ItemStack implements translatable. `Component.translatable(itemStack)` gives you a component that when sent to a client, is displayed correctly.

And if for some reason, you need to serialize that to plain text (for discord, logging or some other purpose that doesn't involve sending it to a player), use `PaperComponents#plainTextSerializer`
