### ISSUE TITLE
Possibly fix MC-228420

### ISSUE THREAD

**Issue by FireController1847** [PaperSpigot/Paper#7357]
### Is your feature request related to a problem?

Yes; it is the bug reported in [MC-228420](https://bugs.mojang.com/browse/MC-228420).

### Describe the solution you'd like.

Providing some form of limiting of data sent to the client to allow players with slower internet connections to be able to connect onto servers with a higher view distance.

### Describe alternatives you've considered.

The only alternative at the moment is to decrease the server's view distance which unfortunately means players have to make requests with us to increase it if they'd like to temporarily have it increased (for various reasons).

### Other

I don't believe this is fixed in either Spigot or Paper, however I do believe it fits within the focus and guidelines behind Paper and would be a major optimization/bugfix, however I am unsure of the difficulty in which it would take to implement. I'm a developer myself and I'm aware this is a Mojang bug, and so I don't know the viability of this happening, and I'm honestly not sure what could be causing this. I'm not expecting it to be implemented by any means, however I figure there's no harm in making a request at the very least.

**Comment by e-im** [comment]
limiting like you describe was implemented in 1.17 but it has not yet been ported to 1.18 (although progress for that can be seen on the `dev/1.18-perf1` branch. Here are [the docs for it from 1.17](https://paper.readthedocs.io/en/latest/server/configuration.html#chunk-loading). Relevant pull request with builds: https://github.com/PaperMC/Paper/pull/7368

See #6136

**Comment by FireController1847** [comment]
Oh you're incredible! Awesome, thank you, I'll keep an eye on that. I feel kind of dumb for not finding this before even after my searching, I apologize for this.
