### ISSUE TITLE
Mobs can see you and deal damage through blocks

### ISSUE THREAD

**Issue by aaronfilarca** [PaperSpigot/Paper#7360]
### Expected behavior

They can't deal damage 

### Observed/Actual behavior

They deal damage and can even draw line of sight.

### Steps/models to reproduce

1. Make Paper server
2. Make a cage with 1x2x1 space inside it.
3. Add a half block on top of the inside of the cage and trapdoor so spiders wont escape
4. Spawn spiders
5. Allow the spiders to see you
6. Go into cover
7. Despair
8. Wait for a few seconds
9. Spiders can't hit you no more
10. Joy

### Plugin and Datapack List

Plugins (0): 

(We run Paper for the sake of performace improvements and bug fixes)

### Paper version

This server is running Paper version git-Paper-155 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 99cf01f)
You are running the latest version
Previous version: git-Paper-154 (MC: 1.18.1)

**Comment by Cwickks** [comment]
So it turns out you need to have line of sight by the spider by using slabs and trapdoors then immediately go into the tinted glass. They both draw line of sight in vanilla and in Paper. but in vanilla they don't deal damage.

**Comment by aaronfilarca** [comment]
So it really turns out that they both deal damage in vanilla and in paper if you let them see you first using slabs and trapdoors to keep them inside then go into cover but only for 3 seconds then they'll forget you and don't hit you. But they don't hit you if they didn't see you first.

**Comment by aaronfilarca** [comment]
So this is a Minecraft bug. But it will be nice if Paper fixes this. Please :)

**Comment by MiniDigger** [comment]
do you have a mojira for this?

**Comment by aaronfilarca** [comment]
> do you have a mojira for this?

https://bugs.mojang.com/browse/MC-2310

**Comment by Warriorrrr** [comment]
Should be fixed by vanilla in 1.20.2+
