### ISSUE TITLE
Unexpected behavior when teleporting in PlayerJoinEvent

### ISSUE THREAD

**Issue by kyngs** [PaperSpigot/Paper#7361]
### Expected behavior

I expect the Player to be teleported to the location when the player joins.

### Observed/Actual behavior

Everything works as expected until the player is joining for the first time. For some reason, my player#teleportAsync call get's overridden by default behavior (spawning the player in the default world). By the way, the result of player#teleportAsync is true and the same behavior can be observed when using standard player#teleport.

### Steps/models to reproduce

1. Create a PlayerJoinEvent listener.
2. Put a code to teleport the player to the desired location.
3. Print out the teleportation result, for debugging purposes.
4. Join in with a name that has never joined before and observe the result (not being teleported to the desired location).
5. Disconnect and join again. You will see, that you will get teleported correctly this time.

Code for async teleport

```java
    @EventHandler
    public void onJoin(PlayerJoinEvent event){
        event.getPlayer().teleportAsync(spawn).whenComplete((result, throwable) -> {
            System.out.println(result);
            if (throwable != null) throwable.printStackTrace();
        });
    }
```

Code for sync teleport

```java
    @EventHandler
    public void onJoin(PlayerJoinEvent event){
        try {
            System.out.println(event.getPlayer().teleport(spawn));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

### Plugin and Datapack List

[14:52:21 INFO]: Plugins (9): Chunky, CMILib, LuckPerms, MCCore, MCWrap, Multiverse-Core, Multiverse-NetherPortals, Residence, Vault
[14:52:38 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[14:52:38 INFO]: There are no more data packs available

### Paper version

[14:33:42 INFO]: Checking version, please wait...
[14:33:42 INFO]: This server is running Paper version git-Paper-155 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 99cf01f)
You are running the latest version
Previous version: git-Paper-82 (MC: 1.18.1)

### Other

I have found out, that when I wrap the entire thing in BukkitScheduler#runTask, it seems to work. Which would indicate that a PlayerJoinEvent is fired and then the default behavior occurs, ignoring the actions done in the event. This is the workaround I will be using for now.

**Comment by electronicboy** [comment]
The players place in the world should already be set at that point, can you reproduce without other plugins? 
Really you shouldn't be using the join event to do that but the `PlayerSpawnLocationEvent`

**Comment by kezz** [comment]
The join event is too early for teleporting. Perhaps use the spawn event?

**Comment by kyngs** [comment]
Thanks, I didn't know about that one, all the forum posts did it in playerjoin. Gonna test it.

**Comment by kyngs** [comment]
This is, weird... I observe the same behavior when Using PlayerSpawnLocationEvent
My code:

```java
    @EventHandler(priority = EventPriority.HIGHEST)
    public void onSpawn(PlayerSpawnLocationEvent event){
        event.setSpawnLocation(spawn);
    }
```
Is anyone else able to reproduce the issue?

**Comment by kyngs** [comment]
I wanted to be sure that another plugin wasn't causing the issue, so I removed all of them and only kept mine. And now it appears to be working, I will try to find out which plugin causes this and post an issue there.

**Comment by kyngs** [comment]
It seems that plugin Multiverse-Core is causing the issue, I will post it on their issue tracker.
