### ISSUE TITLE
Custom Chunk Source

### ISSUE THREAD

**Issue by mikuhl-dev** [PaperSpigot/Paper#7364]
### Is your feature request related to a problem?

A very common need for server developers is a way to create temporary worlds that do not need to be saved to the disk. Minecraft's usual world format is bloated with tons of data that is not needed for temporary worlds. A popular solution is a custom world format like Slime Worlds via [SlimeWorldManager](https://github.com/Grinderwolf/Slime-World-Manager). Although, developers might want to create their own way to load worlds that fit their use-case, especially when such a plugin has not been updated. To do so requires lots of NMS code, which the developer might not be comfortable with.

### Describe the solution you'd like.

Create a way for developers to implement their own source for chunks in a world.

### Describe alternatives you've considered.

I've tried generating a world with a custom ChunkGenerator, this works fine, but then you need to use a BlockPopulator to place entities. In BlockPopulator, its difficult to create entities from serialized states, as the chunk is not ready yet, using various NMS methods to deserialize entities and tile entities causes the server to hang forever.

### Other

I think It would be useful, along with this feature, to have more ways to deserialize things from the common string format, blocks are already doable without tile entities, and except for entities, and tile entities.

Blocks:
```
minecraft:stone
```

Blocks with state:

```
minecraft:oak_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
```

Blocks with state and entity:

```
minecraft:oak_sign[rotation=14,waterlogged=false]{Color:"black",GlowingText:0b,Text1:'{"text":"Hello Paper!"}',Text2:'{"text":""}',Text3:'{"text":""}',Text4:'{"text":""}',id:"minecraft:sign",x:5,y:64,z:-6}
```

Entity: (Snipped for brevity)

```
{AbsorptionAmount:0.0f,Pos:[20.344920126095396d,65.0d,15.445253028083819d],Rotation:[272.82205f,0.0f],id:"minecraft:creeper",...}
```

**Comment by electronicboy** [comment]
I just don't really see how this could work in the form of API given all of the limitations of bukkit, I don't see how data could be saved in a safe manner, given that bukkit doesn't cover that either, etc

this is also stupidly low level stuff of which I'm not sure if it would even be viable for us to maintain with the limitations of bukkit and the requirements of ensuring that everything can run through DFU when loaded, etc
