### ISSUE TITLE
Unable to change Xray engine mode to 1.

### ISSUE THREAD

**Issue by Justusbr0405** [PaperSpigot/Paper#7370]
### Expected behavior

Change xray engine mode from 2 to 1 after fully stopping server.. then starting again and it staying on xray engine mode 1

### Observed/Actual behavior

Change xray engine mode from 2 to 1 after fully stopping server.. then starting again and it resetting to xray engine mode 2..

### Steps/models to reproduce

Stop server fully, wait for it a little bit.. Then change xray engine mode from 2 to 1 inside paper.yml and save.. reboot after a bit and it just changes itself back..
Here is a video of me trying it on my panel: https://www.youtube.com/watch?v=Jaqkz4iJ1O0
(I am my own host.. this is not a host issue as i have my own server rack)
(Yes i also tried FTP using FileZilla.. no luck!)

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/97797608/149984269-cd697ffa-63ed-407d-a7a8-52d1476ba6d9.png)
![Uploading image.png…]()

### Paper version

![image](https://user-images.githubusercontent.com/97797608/149984298-3ba8e34e-bd78-4861-89b9-800beef695ab.png)
(I tried updating 2 times but to no luck so i gave up on thinking its my jar.. officially downloaded from paper as well)

### Other

I have tried so many things.. FTP.. Resetting my paper.yml.. Reinstalling paper 1.18
nothing.. For now no one seems to understand the bug or why and how its happening so i went here for support.
I also am my own host i do not have an external party with my hosts etc and do not expierence this resetting bug for any other setting then xray mode.

**Comment by e-im** [comment]
Cannot reproduce, please come by out [discord](https://discord.gg/papermc) or [forums](https://forums.papermc.io) for support.
