### ISSUE TITLE
Initializing Legacy Material Support Error if server is laggy

### ISSUE THREAD

**Issue by SebyHas** [PaperSpigot/Paper#7371]
### Expected behavior

To understand what it's the problem, why give this error when i have lag, what is the connection.

### Observed/Actual behavior

Thir error \/

### Steps/models to reproduce

Randomly, when server it's laggy give this error:
`18.01 17:38:17 [Server] ERROR [org.bukkit.craftbukkit.v1_18_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
18.01 17:38:23 [Server] WARN Can't keep up! Is the server overloaded? Running 6229ms or 124 ticks behind`

### Plugin and Datapack List

`Plugins (33): AuctionHouse, AuthMe, ChestShop, CMILib, ConsoleSpamFix, Essentials, EssentialsChat, EssentialsDiscord, EssentialsProtect, EssentialsSpawn, IllegalStack, Jobs, LuckPerms, LWC, PlaceholderAPI, PlayerWarps, ProtectionStones, ProtocolLib, Quests, SkBee, SkinsRestorer, SkQuery, Skript, skript-reflect, SuperbVote, TAB, UltimateAntiBot, Vault, ViaVersion, Votifier, WorldEdit, WorldGuard, zItemStacker`

### Paper version

This server is running Paper version git-Paper-160 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 919e594)
You are running the latest version

**Comment by electronicboy** [comment]
something trigged the initialization of the legacy data used for converting materials, etc, from outdated versions, enable debug in server.properties for a trace towards what caused it

**Comment by SebyHas** [comment]
18.01 19:07:35 [Server] ERROR [org.bukkit.craftbukkit.v1_18_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
18.01 19:07:35 [Server] WARN java.lang.Exception
18.01 19:07:35 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.legacy.CraftLegacy.<clinit>(CraftLegacy.java:260)
18.01 19:07:35 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.util.CraftMagicNumbers.toLegacyData(CraftMagicNumbers.java:225)
18.01 19:07:35 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.block.CraftBlock.getData(CraftBlock.java:155)
18.01 19:07:35 [Server] WARN at Quests-3.9.2.jar//com.leonardobishop.quests.bukkit.tasktype.type.MiningCertainTaskType.matchBlock(MiningCertainTaskType.java:171)
18.01 19:07:35 [Server] WARN at Quests-3.9.2.jar//com.leonardobishop.quests.bukkit.tasktype.type.MiningCertainTaskType.onBlockBreak(MiningCertainTaskType.java:95)
18.01 19:07:35 [Server] WARN at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor567.execute(Unknown Source)
18.01 19:07:35 [Server] WARN at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
18.01 19:07:35 [Server] WARN at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
18.01 19:07:35 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
18.01 19:07:35 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
18.01 19:07:35 [Server] WARN at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:400)
18.01 19:07:35 [Server] WARN at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:354)
18.01 19:07:35 [Server] WARN at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:289)
18.01 19:07:35 [Server] WARN at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1762)
18.01 19:07:35 [Server] WARN at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:34)
18.01 19:07:35 [Server] WARN at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:8)
18.01 19:07:35 [Server] WARN at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
18.01 19:07:35 [Server] WARN at net.minecraft.server.TickTask.run(TickTask.java:18)
18.01 19:07:35 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
18.01 19:07:35 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
18.01 19:07:35 [Server] WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)
18.01 19:07:35 [Server] WARN at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
18.01 19:07:35 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
18.01 19:07:35 [Server] WARN at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)
18.01 19:07:35 [Server] WARN at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
18.01 19:07:35 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
18.01 19:07:35 [Server] WARN at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)
18.01 19:07:35 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1268)
18.01 19:07:35 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
18.01 19:07:35 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
18.01 19:07:41 [Server] WARN Can't keep up! Is the server overloaded? Running 6067ms or 121 ticks behind

**Comment by SebyHas** [comment]
**sorry if I don't have to put it here, but now, with active debugging it also gives me this error:**

18.01 19:44:27 [Server] WARN java.lang.Throwable: Server stopped
18.01 19:44:27 [Server] WARN at io.papermc.paper.util.TraceUtil.dumpTraceForThread(TraceUtil.java:16)
18.01 19:44:27 [Server] WARN at net.minecraft.server.MinecraftServer.safeShutdown(MinecraftServer.java:1128)
18.01 19:44:27 [Server] WARN at net.minecraft.server.MinecraftServer.halt(MinecraftServer.java:1123)
18.01 19:44:27 [Server] WARN at net.minecraft.server.commands.StopCommand.lambda$register$1(StopCommand.java:17)
18.01 19:44:27 [Server] WARN at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
18.01 19:44:27 [Server] WARN at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177)
18.01 19:44:27 [Server] WARN at net.minecraft.commands.Commands.performCommand(Commands.java:291)
18.01 19:44:27 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45)
18.01 19:44:27 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
18.01 19:44:27 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897)
18.01 19:44:27 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchServerCommand(CraftServer.java:860)
18.01 19:44:27 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:507)
18.01 19:44:27 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:481)
18.01 19:44:27 [Server] WARN at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470)
18.01 19:44:27 [Server] WARN at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264)
18.01 19:44:27 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
18.01 19:44:27 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by electronicboy** [comment]
Well, yea, debug mode shows extra info around stuff, i.e. what shutdown the server.

> 18.01 19:07:35 [Server] WARN at Quests-3.9.2.jar//com.leonardobishop.quests.bukkit.tasktype.type.MiningCertainTaskType.matchBlock(MiningCertainTaskType.java:171)


is what caused the data to init, beyond that, this is not the place for support

**Comment by SebyHas** [comment]
ok, thanks, I sent a message to the author of this plugin, thanks a lot.
(**java:16 now i saw, a problem with control panel, thank you**)
