### ISSUE TITLE
Haste 2 (Beacon) combined with pickaxe efficiency 5 not working

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#7373]
### Expected behavior

Haste 2 (Beacon) combined with pickaxe efficiency 5 should enable players to instamine blocks around the beacon.

### Observed/Actual behavior

Pickaxe mining speed is only increased by the efficiency 5 buff NOT combined with the haste 2 buff

### Steps/models to reproduce

1. Get efficiency 5 pickaxe (/give @p diamond_pickaxe{Enchantments:[{id:efficiency,lvl:5},{id:unbreaking,lvl:3},{id:fortune,lvl:3},{id:mending,lvl:1}]} 1)
2. build beacon (https://minecraft.fandom.com/wiki/Beacon) and max the buffing
3. try to mine blocks around you

### Plugin and Datapack List

 Plugins (10): BlueMap, CreepersTrimGrass, CustomTime, LeadMe, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals,
 Slap-Pro, TreeFeller, WorldEdit

> datapack list
[20:47:26 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[20:47:26 INFO]: There are no more data packs available

### Paper version

You are 10 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-141 (MC: 1.18.1)

### Other

Just noticed, paper-141 is considered "only 10 versions behind" despite paper-162 available for download (Tue 18 Jan 2022 08:50:37 PM CET)

**Comment by Aurelien30000** [comment]
Can't reproduce, update to a more recent version of Paper and try without any plugin installed.

**Comment by Machine-Maker** [comment]
I concurr, cannot replicate. Make sure you are mining blocks that actually can be insta-mined with the haste 2 + eff 5 combo, as not all blocks can. Try with regular stone.

**Comment by ghost** [comment]
my bad. wasnt the server version either but one player who is the most-reliable actually made a mistake building the beacon. thank you

no bug / can be closed - sorry of inconvenience
