### ISSUE TITLE
Server crash on getting biome

### ISSUE THREAD

**Issue by markovav-official** [PaperSpigot/Paper#7375]
### Stack trace

[crash report](https://paste.gg/p/anonymous/a792f8f61089484b820a20970e7a6c9c)
[error log](https://paste.gg/p/anonymous/c286902786674d5c88b9f91f4ae62ae9)

### Plugin and Datapack List

Plugins (50): AuthMe, Chunky, CoreProtect, HeadDatabase, InventoryRollbackPlus, JellyActionBarController, JellyAPI, JellyAuthModule, JellyBansModule, JellyBorder, JellyBorderController, JellyChangeNick, JellyChat, JellyChatControl, JellyClans, JellyCleaner, JellyCustomAchievements, JellyDonations, JellyEventStream, JellyFly, JellyGameMoney, JellyHDBShop, JellyHomes, JellyLands, JellyLib, JellyMedia, JellyPlaceholderController, JellyPlayTime, JellyPluginManager, JellyRestart, JellyRubles, JellyShop, JellyTabCompleater, JellyTeleportations, JellyTempEvents, JellyTours, JellyTrade, JellyUtils, JellyVillagerController, JellyVisuals, JellyWhiteList, LuckPerms, Matrix, PlaceholderAPI, ProtocolLib, SkinsRestorer, TAB, WorldEdit, WorldEditSelectionVisualizer, WorldGuard
(All plugins with prefix 'Jelly' are self-written and I'm sure that error isn't related to them)

### Paper version

[17:07:27] [Server thread/INFO]: Checking version, please wait...
[17:07:32] [Thread-16/INFO]: This server is running Paper version git-Paper-163 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 4533821)
You are running the latest version
Previous version: git-Paper-154 (MC: 1.18.1)

**Comment by electronicboy** [comment]
`Class  does not implement`

the fact that there is no class name there screams that something is being filtered from your logs or there is some really horrible plugin installed messing with internals
