### ISSUE TITLE
Add a "Post" variation of CraftItemEvent with total quantity

### ISSUE THREAD

**Issue by viveleroi** [PaperSpigot/Paper#7383]
### Is your feature request related to a problem?

`CraftItemEvent` doesn't contain any final-tally information about the craft event. Because it's cancellable it acts more like a "Pre" event. In order to get a full count of how items a player crafted, I currently have to manually check for all of the scenarios a craft can occur. Clicking, shift-clicking, doing both holding matching and non-matching items, factoring available inventory space, etc. It's a nightmare.

### Describe the solution you'd like.

I would like some kind of "Post" CraftItem event, that has:

- The item crafted, probably via `ItemStack getItemStack`
- The total crafted, probably via `int getTotal()`

### Describe alternatives you've considered.

I've looked thoroughly into the API to see if I've missed any existing logic. I've looked at what other devs use and it's always some terribly complicated guessing logic - calculating how many they can make, calculating how many get made based on the way they're clicking, etc.

**Comment by Doc94** [comment]
hmm maybe can check in upstream (sorry) its strange why in SmithItemEvent they use the result item for the event and in CraftItemEvent not.. well in the two events the result are not set in the event...

EDIT: Why cant use CraftItemEvent::getRecipe::getResult?

**Comment by Machine-Maker** [comment]
> Why cant use CraftItemEvent::getRecipe::getResult?

That just gets the result from 1 craft of the recipe, like OP said 
> I currently have to manually check for all of the scenarios a craft can occur. Clicking, shift-clicking, doing both holding matching and non-matching items, factoring available inventory space, etc. It's a nightmare.

**Comment by tomcraft** [comment]
and the event is only called once, even for a "multiple-crafy" click
