### ISSUE TITLE
Non-item Materials have a shared cooldown instance (a null key on the player's cooldown map)

### ISSUE THREAD

**Issue by Machine-Maker** [PaperSpigot/Paper#7388]
### Expected behavior

Either some exception thrown when trying to set the Item cooldown `HumanEntity#setCooldown` for a non-item material.

### Observed/Actual behavior

No error, and all non-item Material's will share a null-key cooldown entry in a player's cooldown map.

### Steps/models to reproduce

Just give a player a cooldown for a non-item Material.
```java
player.setCooldown(Material.MOVING_PISTON, 20);
player.getCooldown(Material.FROSTED_ICE); // this should return whatever value you set for the non-item Material above
```

### Plugin and Datapack List

none

### Paper version

This server is running Paper version git-Paper-"dcca6cb" (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: dcca6cb)
You are running the latest version
Previous version: git-Paper-"83c89fc" (MC: 1.18.1)

### Other

I'm not sure what the best solution is here, probably to throw some sort of exception if you try to set the cooldown of a non-item Material. But I don't think the current behavior makes much sense at all.

**Comment by Doc94** [comment]
well based in cooldown used for right-click a item... then makes sense add another Preconditions for the material. but not sure if can for example.. use this for add a cooldown for put blocks?

Maybe can make a few things in upstream based in tests...

**Comment by electronicboy** [comment]
the entire system works off items in your inventory, so, I fail to see what a cooldown for blocks would even do given vanilla doesn't care about blocks?

**Comment by Machine-Maker** [comment]
My issue isn't that you can't have a cooldown for non-items, its just that behavior if you try doesn't really make some sense, so I think there should be a check against that behavior. This is just a result of the bad Material enum

**Comment by electronicboy** [comment]
I agree, if it silently allowed blocks in there even though it would do nothing, I wouldn't care, but, the thing only restricts items and goes into an "unknown" state when that occurs, in which is basically useless and misleading, really should shout about those cases rather than entering such a weird state as it will result in erroneous results when people try to do that stuff

**Comment by Doc94** [comment]
yeah material its really confuse for this things.. its more easy add the Preconditions based in the currently behavior.. if its not problem can make a PR for this in Upstream and make the javadocs more clear about what materials are valid for cooldown.

**Comment by Doc94** [comment]
well take this like yes (? xd

Created PR for handle non items: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/pull-requests/999/overview

![image](https://user-images.githubusercontent.com/3602279/150683773-531c373e-284d-4e9f-af4d-b9ab1c79a8c6.png)
![image](https://user-images.githubusercontent.com/3602279/150683891-a849f660-59d8-4339-a5b2-0a621c3874c0.png)

**Comment by broccolai** [comment]
> if its not problem can make a PR for this in Upstream

Why not PR it to Paper?

**Comment by Doc94** [comment]
> > if its not problem can make a PR for this in Upstream
> 
> Why not PR it to Paper?

a bad habit... its more easy for me in a few cases edit directly the method in upstream than make a patch for edit...
and think this type of things are better make in upstream than make the validation only here.
