### ISSUE TITLE
Server crashing after 12h everytime.

### ISSUE THREAD

**Issue by K0ulas** [PaperSpigot/Paper#7390]
### Stack trace

https://paste.gg/p/anonymous/845d3413fce64eccbc6c1bfa829cfb44

### Plugin and Datapack List

![obrázok](https://user-images.githubusercontent.com/62230253/150630318-3726088e-e793-4d58-9ba0-22adfd4e5edd.png)

### Paper version

Previous version: git-Paper-132 (MC: 1.18.1)

### Other

Okey This is my Start Up Paramater ->

java -Xms1536M -Xmx3072M -Xlog:gc*:logs/gc.log:time,uptime:filecount=5,filesize=1M -jar server.jar nogui

My friend told me that I have problem with my GC so I used this -Xlog:gc*:logs/gc.log:time,uptime:filecount=5,filesize=1M.
But still the server is shuting down.

I am using bungeecord with 2 servers (Lobby and survival).
Also the Lobby is not shutting down or crushing only Survival is doing it.

**Comment by electronicboy** [comment]
> The server has not responded for -64 seconds! Creating thread dump

Your JVM is stalling, you'll need to work out why

**Comment by K0ulas** [comment]
I already tryed. Thats why I am here.
Can you please help me?

**Comment by electronicboy** [comment]
The issue tracker is not for seeking support

**Comment by K0ulas** [comment]
Can you at least tell me where should I go?
Because When I was creating ticket there was an option for crash.

**Comment by electronicboy** [comment]
generally, on our discord, or the forums

**Comment by K0ulas** [comment]
alright, thanks for help.
