### ISSUE TITLE
suggestCommand in Books

### ISSUE THREAD

**Issue by AlmightyAnubis** [PaperSpigot/Paper#7391]
### Expected behavior

Closing Book and showing command in command line

### Observed/Actual behavior

Book does not get closed and the command is not suggested

### Steps/models to reproduce

1. Create a Component in a book
2. Add Click event with ClickEvent.suggestCommand(command)
3. Click the command 
4. nothing happens

### Plugin and Datapack List

my own plugin + viaVersion + viaBackward

### Paper version

[15:39:13 INFO]: Checking version, please wait...
[15:39:13 INFO]: This server is running Paper version git-Paper-169 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 60e46ab)

### Other

might be a spigot problem, but maybe a solution can be found her

**Comment by NoahvdAa** [comment]
This is intentionally not supported in vanilla, see [MC-70317](https://bugs.mojang.com/browse/MC-70317).
