### ISSUE TITLE
Create Entity#hideEntityByDefault

### ISSUE THREAD

**Issue by u9g** [PaperSpigot/Paper#7395]
### Is your feature request related to a problem?

I wanted to create an entity that is only shown to one player, but I can still change and resend. Unfortunately, the only way to do that is to manually run Entity#hideEntity on every player on the server, and any that log on after the entity is spawned.

### Describe the solution you'd like.

I would like there to be a Entity#hideEntityByDefault which means you have to run Entity#showEntity if you want to show the entity to a player, rather than the other way around of show by default

### Describe alternatives you've considered.

Digging through nms to hide the packets for entities players cant see, manually adding to the entity's hide list (but this becomes a lot when you have a ton of entities spawned that each require adding to their hidden list when a new player spawns, etc)

**Comment by Machine-Maker** [comment]
I think this makes sense. Just a non-persistent boolean on nms Entity.

**Comment by Machine-Maker** [comment]
Done by upstream in https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/fb50924403915ad24e9389361a10dfbf53c1e696
