### ISSUE TITLE
Default Spawn in END world are not the exit portal

### ISSUE THREAD

**Issue by Doc94** [PaperSpigot/Paper#7397]
### Expected behavior

In Vanilla/Spigot the default spawn in END worlds is the Exit Portal to OVERWORLD.

### Observed/Actual behavior

The coords are random not point to the portal or the obsidian base, point to a random location.
![image](https://user-images.githubusercontent.com/3602279/150707939-72af1564-3e0d-4f7f-b971-f0456d72b1be.png)

### Steps/models to reproduce

- Download Paper
- Generate a new world
- Check level.dat in the generated world_the_end for the spawnX,Y,Z

### Plugin and Datapack List

Nothing in plugins.
![image](https://user-images.githubusercontent.com/3602279/150707599-65d9f379-19b9-4aa3-bcf1-74e4b5c1e0c8.png)

### Paper version

This server is running Paper version git-Paper-175 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 9490475)
You are running the latest version
Previous version: git-Paper-243 (MC: 1.17.1)

### Other

In 1.17 this not happen. for any reason when try a command like `/execute in minecraft:the_end run tp MrDoc94 0 61 0` when teleport the portal its generated where i teleport (the coords in level.dat)

**Comment by Machine-Maker** [comment]
In vanilla, there's only 1 spawn point in the overworld. There isn't really the concept of a "spawn point" in the nether or end dimension. In fact, the /setworldspawn command in vanilla doesn't do anything if used in a world other than the main overworld.

**Comment by Doc94** [comment]
hmm then its better use for "spawn location" (in END worlds) the portal or the default spawn (not sure why the same cords) no?

i create the issue because in 1.17 the worldSpawn was the portal then in my case i dont need get the dragon battle for get the portal location to spawn...

**Comment by electronicboy** [comment]
spawn point and exit portals are two separate things, I don't think it is really our job to break that distinction and potentially break the many potential setups relying on such a distinction being the case

**Comment by Doc94** [comment]
yeah... not sure why this start to happen.. because in test in spigot and this inconsistence not happen, but maybe need check another thing...

**Comment by Machine-Maker** [comment]
Yeah, so there is a difference in behavior. something paper does changes the spawn from 0, <y value of top block>, 0

**Comment by Machine-Maker** [comment]
I cannot replicate this anymore... can you @Doc94 ? And if so, can you give me the seed?

**Comment by Doc94** [comment]
> I cannot replicate this anymore... can you @Doc94 ? And if so, can you give me the seed?

i try with the seeds where have the issue and now the spawn in level.dat its the exit of the portal then in teory looks fixed for a "random" commit.

Closed unless i find this issue again...
