### ISSUE TITLE
Likely a memory leak

### ISSUE THREAD

**Issue by voodootje0** [PaperSpigot/Paper#7401]
### Timings or Profile link

https://timings.aikar.co/?id=6db9e97031bf42e4919f668a0a8450aa

### Description of issue

As you can see on https://spark.lucko.me/HLNiyPKS5w, there are a lot of instances for chunk-related data. 
There are only 62 players online, with 11.5k active chunk instances loaded with 6 view-distance.

All the spikes in here https://prnt.sc/26iifxq, seems like it's garbage collecting. 

If we can help by proving more details, please let me know

### Plugin and Datapack List

If this is needed, please let me know.

### Server config files

If this is needed, please let me know.

### Paper version

https://github.com/PaperMC/Paper/tree/9a47cf18340c276555c873c04d171831b0bb580b

### Other

I am aware that we're not using the latest version, but I saw something in the discord channel that there is a known leak in the issue tracker, but I am unable to find that one.

**Comment by electronicboy** [comment]
Nothing in there indicates any form of tangible leak that we could spot just with such info

**Comment by voodootje0** [comment]
@electronicboy What details can I provide to help fix this issue?

On 1.17 builds it didn't even use 1/3th of the memory, so I am pretty sure there must be a leak in the latest version.

**Comment by electronicboy** [comment]
We need reasonable proof that there is a leak, modern versions of the game using more memory is hardly new, not to mention various other changes between versions, etc

We don't have the time nor commitment to spend time going back and forth, you need to actually start looking into heap dumps, etc, and we're not going to waste our time looking into dumps of everybody who thinks that they have a leak

**Comment by MiniDigger** [comment]
additionally, this is a much better fit for our #paper-help discord channel.

>  I saw something in the discord channel that there is a known leak in the issue tracker

not sure what that was referring to, but there was a leak in early 1.18 builds, you not using the most up-to-date version doesn't make it easier for us to help.
