### ISSUE TITLE
Lag compensate day/night cycle

### ISSUE THREAD

**Issue by FixTheAdmin** [PaperSpigot/Paper#7402]
### Is your feature request related to a problem?

I have a large server running 12 to 15 tps consistently. Many large servers choose to accept slightly lower tps in order to allow more players to join. 

### Describe the solution you'd like.

Make day/night cycle independent of current tps. Should work similarly to the block break lag compensation patch.

### Describe alternatives you've considered.

I have not considered any alternative work around at this time.

**Comment by electronicboy** [comment]
Skipping ticks has many wider implications, I don't think that this is viable or even sane to do

**Comment by FixTheAdmin** [comment]
Is that reasoning not applicable to the current block break lag compensation patch? It seems to work fine.

**Comment by electronicboy** [comment]
breaking a block and maintaining the entire state of the world is entirely different areas of scope and concern.

**Comment by FixTheAdmin** [comment]
Alright, thanks for the quick response

**Comment by electronicboy** [comment]
in retrospect, i might be dum, there are one or two things which depended on the world time still from what I recall, but, that may have just been pretty animations, i semi recall there being some issues from changing the world time but that was many years ago, so, who knows
