### ISSUE TITLE
When a minecart is pushed up underneath a hopper with a piston it falls to the base of the piston

### ISSUE THREAD

**Issue by RasmusKD** [PaperSpigot/Paper#7407]
### Expected behavior

![image](https://user-images.githubusercontent.com/59487370/150919692-2e4ca93a-a4e5-4a29-8e08-9d0ca8d98203.png)

### Observed/Actual behavior

This bug was introduced in paper-1.18-44, This behaviour is still present in the lastest version of paper.
![image](https://user-images.githubusercontent.com/59487370/150919813-ea52aa35-0913-4a1e-aec7-cff9052e4e73.png)

### Steps/models to reproduce

Have a piston and a hopper with 1 block space inbetween, add a minecart on a rail and remove the rail, then power the piston.

### Plugin and Datapack List

None

### Paper version

This server is running Paper version git-Paper-44 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 6b072ee)
You are 22 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-43 (MC: 1.18)

This behaviour is still present in the lastest version of paper, i just traced it back to the build when it occured for the first time.

**Comment by Owen1212055** [comment]
This is no longer an issue as of 1.20.2, most likely due to the collision optimization patch rewrite.
