### ISSUE TITLE
Foxes stalling the server

### ISSUE THREAD

**Issue by Kyrobi** [PaperSpigot/Paper#7410]
### Timings or Profile link

https://timin.gs/?id=36fa84071a42439a9e1d641eb2b07c3c

### Description of issue

From the brief information provided by the people on Discord, it seems like foxes are causing sync chunk load.

Don't know if it's any relevance to this issue: https://github.com/PaperMC/Paper/issues/6045

### Plugin and Datapack List

Plugins (45): AdvancedReplay*, ArmorStandEditor, ChatControlRed, ColoredAnvils, CoreProtect, CraftingStore, CynagenCooldown, CynagenJoinTime*, CynagenWorldLoader*, DelayedCommand, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, FarmLimiter, FurryFilter*, GlobalMarketChest, GriefPrevention, GriefPreventionFlags, GSit, HeadDatabase, InventoryRollbackPlus, LiteBans, LuckPerms, mcMMO, MorphRedeem, OpenInv, OreAnnouncer, PlaceholderAPI, Plan, PlugMan, ProCosmetics, ProtocolLib, QuickShop, Shopkeepers, spark, StaffChat*, SuperbVote, TAB, Vault, Votifier, Vulcan, VulcanReplay, WorldEdit, WorldGuard

### Server config files

Bukkit: https://www.toptal.com/developers/hastebin/erusucujex.yaml
Spigot: https://www.toptal.com/developers/hastebin/wutehoxasu.yaml
Paper: https://www.toptal.com/developers/hastebin/ovurejeduy.yaml

### Paper version

This server is running Paper version git-Paper-"fad2a45" (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: fad2a45 on dev/1.18-perf1)
Error obtaining version information
Previous version: git-Paper-"6f7d569" (MC: 1.18.1)

### Other

Dump: https://www.toptal.com/developers/hastebin/oheyoduwis.md

**Comment by MiniDigger** [comment]
not related to foxes, you have players flying around and sync loading chunks
