### ISSUE TITLE
Dying when flying into not yet generated chunks with elytra and riptide.

### ISSUE THREAD

**Issue by VatraXD** [PaperSpigot/Paper#7412]
### Expected behavior

Not dying, that's for sure.

### Observed/Actual behavior

Dying as soon as I fly into a not generated chunk.
> Player experienced kinetic energy.

### Steps/models to reproduce

- Wear an elytra
- Use Riptide 3 on a trident
- Fly into any not yet generated chunk while going fast enough to die from impact.

### Plugin and Datapack List

None

### Paper version

This server is running Paper version git-Paper-176 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: b164899)
You are running the latest version

### Other

Video of the issue: https://streamable.com/6wpxs4

**Comment by VatraXD** [comment]
^^^^

**Comment by kennytv** [comment]
Now that's hilarious

**Comment by Astralchroma** [comment]
Maybe try enabling the setting that prevents the player from entering unloaded chunks?

**Comment by VatraXD** [comment]
> Maybe try enabling the setting that prevents the player from entering unloaded chunks?

Don't see how that would fix the problem, as this isn't happening in vanilla, where you can fly into not yet generated chunks to your hearts content.

**Comment by dbrighthd** [comment]
I'm having the same issue

**Comment by VatraXD** [comment]
Just checking in, will this ever be fixed?
Thanks.

**Comment by drunderscore** [comment]
It is labeled as "accepted", and is hilariously not correct, so yes it will be fixed. When... could be whenever.

**Comment by electronicboy** [comment]
This is an open source project with a long list of stuff to do; if somebody can provide stack traces towards where the damage comes from, that would be beneficial, or you could submit a PR fixing the issue
