### ISSUE TITLE
VehicleBlockCollisionEvent not working

### ISSUE THREAD

**Issue by AoElite** [PaperSpigot/Paper#7413]
### Expected behavior

VehicleBlockCollisionEvent should fire when colliding with a block in a vehicle such as a boat.

### Observed/Actual behavior

VehicleBlockCollisionEvent does not fire when colliding with a block in a vehicle.

### Steps/models to reproduce

```java
 //yes the class is a listener and registered
 @EventHandler
    public void onVehicleCollision(VehicleBlockCollisionEvent event) {
        Block block = event.getBlock();
        block.setType(Material.AIR);
    }
```
Get in a boat and run into a block. It should turn into air but it doesn't.    

### Plugin and Datapack List

[11:00:47 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[11:00:47 INFO]: There are no more data packs available

[11:01:49 INFO]: Plugins (1): TestPlugin

TestPlugin only contains the code above.

### Paper version

[10:59:51 INFO]: This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)
You are running the latest version
Previous version: git-Paper-358 (MC: 1.17.1)

**Comment by Machine-Maker** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-5463

**Comment by AoElite** [comment]
According to that it's been broke for years. I'd also like to mention the VehicleEntityCollisionEvent is also jank. It works like 25% of the time.

**Comment by Doc94** [comment]
yeah i tested this yesterday... with Striders run a few times and the most cases the collition block is "LAVA".. like in the JIRA report maybe its better deprecate the event.. or make a rework.

**Comment by aflyingpumpkin** [comment]
This appears to be the same problem as #4163

**Comment by aurorasmiles** [comment]
Duplicate of #4163
