### ISSUE TITLE
Setting lore does not set the good one in some conditions

### ISSUE THREAD

**Issue by PapiCapi** [PaperSpigot/Paper#7416]
### Expected behavior

I expected the lore to be the same as the one i set.

### Observed/Actual behavior

When setting the lore using ItemMeta#setLore , it modifies some lines.

### Steps/models to reproduce

- Give yourself this item : 
/minecraft:give @p iron_sword{display:{Name:'{"text":"Zirakinbar, l\'épée de légende","color":"yellow","bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false}',Lore:['{"text":"[i][i][i][i][i][i][i][i][i][i]","color":"aqua","bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":true}','{"text":"Aussi connue sous le nom","color":"aqua","bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false}','{"text":"de corne d\'argent elle aurait","color":"aqua","bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false}','{"text":"appartenu à un grand héros.","color":"aqua","bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false}','{"text":"Fine et légère elle permet des","color":"aqua","bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false}','{"text":"attaques rapides et efficaces","color":"aqua","bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false}','{"text":"Ma...","color":"aqua","bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false}','{"text":"...Pré...","color":"aqua","bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false}','{"text":"...cieuse...","color":"aqua","bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false}','{"text":"[i][i][i][i][i][i][i][i][i][i]","color":"aqua","bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":true}']},Unbreakable:1b,Enchantments:[{id:"minecraft:sharpness",lvl:5s},{id:"minecraft:fire_aspect",lvl:2s},{id:"minecraft:looting",lvl:3s},{id:"minecraft:sweeping",lvl:10s}],AttributeModifiers:[{AttributeName:"generic.attack_speed",Name:"generic.attack_speed",Amount:2.0d,Operation:0,UUID:[I;1807658896,-2007414740,-1655877500,190673671],Slot:"mainhand"},{AttributeName:"generic.max_health",Name:"generic.max_health",Amount:6.0d,Operation:0,UUID:[I;-1108933111,1215844083,-1212248360,332683411],Slot:"mainhand"},{AttributeName:"generic.attack_damage",Name:"generic.attack_damage",Amount:6.0d,Operation:0,UUID:[I;265954431,489114710,-1680559162,-698734434],Slot:"mainhand"}]} 1

- Create a plugin and call this function on the item :
```
private ItemStack simulateWhatsHappening(ItemStack initialItem) {
		System.out.println("simulating trash ....");
		
		System.out.println("initialItem: "+ initialItem);
		ItemStack item = initialItem.clone();
		ItemMeta itemMeta = item.getItemMeta();
		List<String> lore = itemMeta.getLore();
		
		if ( lore == null )
			lore = new ArrayList<>();
		
		lore.add("§eObjet actuellement dans l'HDE");
		lore.add("§emis en troc par vous-même");
		
		itemMeta.setLore(lore);
		item.setItemMeta(itemMeta);
		
		System.out.println("after setlore 1 : "+ item);
		
		ItemMeta newMeta = item.getItemMeta();
		List<String> newLore = newMeta.getLore();
		newLore.remove(newLore.size()-1);
		newLore.remove(newLore.size()-1);
		newMeta.setLore(newLore);
		item.setItemMeta(newMeta);
		
		System.out.println("after setlore 2 : "+ item);
		
		System.out.println("end trash ....");
		return item;
	}
```

- You can see that there are now some clickevents in the for the lines at the end ( The ones where there are dots before and after a word ).

### Plugin and Datapack List

ArmorStandTools, AsyncWorldEdit, Bank, Brisures*, ChatCore, ChatItem, ChatPing, ChestCommands, Citizens, CitizensText, ClaimableRewards, CMILib, Core, CoreProtect, CrazyCrates, EffectItems, EffectLib, Essentials, EssentialsChat, EssentialsSpawn, gradle-test, HolographicDisplays, HotelDesEchanges, LoadForce, Log4jFix, LootBoxPlugin, LuckPerms, MayorRegions, ModPerms, ModReq*, Multiverse-Core, ObsidianToLava, OnTime, OpGuard*, Plan, PlanningsEvents, PlugMan, ProtocolLib, Realistic_World, RichTop, SchematicMover, Shopkeepers, spark, SpawnChecker, SpawnSelector, StaffCore, TAB, Vault, ViaBackwards, ViaVersion, VoidGen, VoteMoncube, VoxelSniper, WGEFixer, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Paper version

This server is running Paper version git-Paper-175 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 9490475)

However, the same bug is happening in 1.17.1 build 408

**Comment by kezz** [comment]
I'll admit it's pretty hard to work out what on earth your issue is here, but I think I've managed to grasp it (although it would be very helpful if you just provided the expected/actual lore lines, in a formatted pastebin).

The legacy serializer will insert click events around text that is recognised as a link. This was to maintain backwards compatibility with CB/Spigot behavior that automatically makes links clickable as well. So, I'm not sure you'd experience different behaviour running the same code on CB/Spigot. I suppose it's possible they could not use link detection in this context(?) although I doubt it.

Regardless, legacy methods are deprecated for a reason. I can't see much care or attention being put into fixing this regardless. You would absolutely be better off not using these deprecated legacy methods to begin with.

**Comment by PapiCapi** [comment]
Ok, i'm sorry, i think a screenshot will be better : 
As you can see, now, my item has, in the lore, some click events that i didn't add myself. My issue could be summarized with that sentence
![Screenshot_2](https://user-images.githubusercontent.com/49530141/151389202-4f8948f7-a756-402c-a413-92c4c9719340.png)
.

For Spigot, i really don't know.

Concerning the deprecated part, i saw on your discord someone that was not very happy concerning the components and someone of the Paper team replied that it wasn't really an issue to use those deprecated methods because they should do the same job as the others.
I'm sorry if it's not the case or if i misunderstood what they were talking about

**Comment by kezz** [comment]
Right, so what I'm saying is that using the legacy methods automatically detects URLs and makes them clickable with added click events. This is not an issue or bug, it's an intentional feature that you will also find in Spigot.

**Comment by PapiCapi** [comment]
Well, there is still an issue because i don't see any URL in "...Pré..." . Plus, at every set lore, it changes and takes the last dot out of the click event and text.
The more, how a click event in an item lore could be useful ?

**Comment by kezz** [comment]
Well, idk what cursed regex is used for detecting URLs, but it's definitely triggering with that. As for why this feature exists, I'm not sure tbh. I believe this is just a side effect of the same legacy serializer being used for everything. As I said before, you'd find the same behaviour upstream as well.

**Comment by e-im** [comment]
conversion from component -> legacy string-> component is not, never has been, and can not be guaranteed to be clean. Use the component methods as referenced in the deprecation notice.
