### ISSUE TITLE
spigot.yml players.disable.saving not working!

### ISSUE THREAD

**Issue by DevJoey** [PaperSpigot/Paper#7418]
### Expected behavior

If i using plain spigot, the playerdata is not saved! But if i use this on paper still .dat files will be created!

### Observed/Actual behavior

It still saves playerdata in <mainworld>/playerdata

### Steps/models to reproduce

1. Create a fresh paper server
2. Go to spigot.yml and set players.disable-saving to true
3. Start the server
4. Join the server
5. Look in world/playerdata and they are still files

### Plugin and Datapack List

No plugins!

### Paper version

[21:58:50 INFO]: Checking version, please wait...
[21:58:50 INFO]: This server is running Paper version git-Paper-177 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 2e99e5e) You are running the latest version

**Comment by electronicboy** [comment]
need valid output of /version

**Comment by DevJoey** [comment]
> need valid output of /version

Updated!

**Comment by electronicboy** [comment]
I tested on latest dev build and can't reproduce

**Comment by DevJoey** [comment]
I deleted all files (The complete Server) and now its also working on 1.18.1. I think my cloud is copying a wrong spigot.yml. On 1.16.5 (Outdated Version) this option is completely not working with paper.

**Comment by electronicboy** [comment]
so, not an issue in supported versions
in unsupported, may still have been in paper.yml, but 🤷
