### ISSUE TITLE
Water is static even in its flow

### ISSUE THREAD

**Issue by LyFl0w** [PaperSpigot/Paper#7421]
### Expected behavior

The water should stop flowing when the statics source is removed. 

### Observed/Actual behavior

The water flow remains after removing the main water source.

### Steps/models to reproduce

Step 1: place a bucket of water
Step 2: remove the water source

### Plugin and Datapack List

ArmorStandTools, Builders-Utilities, FastAsyncWorldEdit, FastAsyncVoxelSniper, goBrush, goPaint, HeadDatabase, Multiverse-Core, WorldEditSUI

### Paper version

Paper version git-Paper-177 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git:2e99e5e)
Previous version: git-Paper-175 (MC: 1.18.1)

**Comment by LyFl0w** [comment]
![2022-01-30_11 21 24](https://user-images.githubusercontent.com/91786781/151696129-4e6f4b9b-f4a5-4632-8eb7-88fa1268b1ca.png)

**Comment by kennytv** [comment]
Most likely not a Paper issue. Either plugin related or your server isn't responding/ticking properly. Remove your plugins (the most likely contenders are BuilderUtilities and FAWE) and if it still doesn't work, join our Discord to get help there
