### ISSUE TITLE
Big Dripleaf's forced growth does not work

### ISSUE THREAD

**Issue by LyFl0w** [PaperSpigot/Paper#7422]
### Expected behavior

The old dripleaf head must be replaced with the stem of the new head.

### Observed/Actual behavior

The old head is not replaced by the stem.

### Steps/models to reproduce

Step 1 : place a big dripleaf.
Step 2 : place a a big dripleaf on the dripleaf.

### Plugin and Datapack List

ArmorStandTools, Builders-Utilities, FastAsyncWorldEdit, FastAsyncVoxelSniper, goBrush, goPaint, HeadDatabase, Multiverse-Core, WorldEditSUI

### Paper version

Paper version git-Paper-177 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git:2e99e5e)
Previous version: git-Paper-175 (MC: 1.18.1)

### Other

![2022-01-30_11 40 27](https://user-images.githubusercontent.com/91786781/151696318-f009ff8c-003b-4548-8501-9ae35d54c7f7.png)

**Comment by LyFl0w** [comment]
why ?

**Comment by kennytv** [comment]
See https://github.com/PaperMC/Paper/issues/7421#issuecomment-1025116694
