### ISSUE TITLE
Create a world-generation-distance for worldgen specific world distance.

### ISSUE THREAD

**Issue by ryantheleach** [PaperSpigot/Paper#7435]
### Is your feature request related to a problem?

In 1.18 the new fog makes previous builds masked / uglier.
So for smaller servers with excess resources, it can be prudent to *increase* the view distance to restore aesthetics.

However, raising view-distance has an exponential impact on ram, which is usually ok for low player counts.

However when doing world-generation, it can **quickly** bring a server to it's knees, since MC generally tends to be CPU constrained.

### Describe the solution you'd like.

Creating a world-generation-distance configuration option, which only generates chunks if the chunks are inside that distance to the player.

This would give better performance without affecting normal gameplay too much, and without the downsides of pre-generating the world.

This would also likely have a better impact for players elytra flying through new terrain, if the distance is quite small.

### Describe alternatives you've considered.

Pregenerating my map, at the expense of disk space on a shared host, (Which with plugins such as dynmap / bluemap, which currently have no restrictions on chunk life timers, can quickly use your fair share of the hosts diskspace, which would likely mean foregoing having the map).

Additionally pre-generation has the downside of forcing map expansion each update, or making a new world, or a map-reset.

**Comment by ryantheleach** [comment]
Another alternative I just came up with.

The ability to pre-generate chunks to an explicit cache, so they could be copied when generation would happen.

1. This would allow chunk generation to the cache to be done in the background, or when no players are present.
2. This would allow the cache to be purged, when a new minecraft update releases terrain changes, without having to prune based on chunk inhabited time using manual processes.
3. This could potentially be an entry-point for async world gen at some point.

**Comment by kennytv** [comment]
Just use a plugin like https://www.spigotmc.org/resources/clearfog.98448/. The second alternative you described doesn't make sense and generation is already partially happening off-main

**Comment by ryantheleach** [comment]
Thanks for linking the plugin kenny, but I think you may have closed the issue a little pre-maturely.

Just because my initial problem can be fixed by lying to the client about the view-distance, that has it's own downsides of seeing a flat cut-off. I'd also worry about how it affects client side mods such as [bobby](https://www.curseforge.com/minecraft/mc-mods/bobby). 

I'm not an expert, but the original idea seems simple enough to implement, but maybe it's harder than what I'm thinking?

I realize the second idea is overkill, but could have different applications.
