### ISSUE TITLE
Paper verifying usernames even when it's set to false in the config

### ISSUE THREAD

**Issue by ziggykac** [PaperSpigot/Paper#7437]
### Expected behavior

Paper not verifying usernames when perform-username-validation is set to false in paper.yml.

### Observed/Actual behavior

Paper verifies usernames and kicks bedrock players joining with geyser/floodgate with the error message: "Failed to verify username"

### Steps/models to reproduce

(This instruction is based on installing Geyser because that's how I notice it)

Set up waterfall and paper servers

Install geysermc and floodgate on waterfall, and floodgate with the same config and key on the paper servers

https://geysermc.org/

Set perform-username-validation to false in paper.yml

Try to join with bedrock edition

### Plugin and Datapack List

On the lobby paper server:
Chatcontrol, Citizens, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit, floodgate, Luckperms, PlaceholderAPI, ProtocolLib, SuperVanish, Vault, ViaVersion, WorldGuard

### Paper version

This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)
You are running the latest version
Previous version: git-Paper-404 (MC: 1.17.1)

### Other

I've got paper servers connected to a waterfall proxy, even when I've set verify usernames to false in the config and I've installed floodgate on the paper servers bedrock players can't join and get an "Failed to verify username!" error message. 
This doesn't happen when I replace the paper servers with spigot, so therefore I'm pretty sure it's a paper issue.

**Comment by drakon64** [comment]
What Floodgate build are you running? This might be related to a change that Mojang made yesterday which was fixed in newer Floodgate builds.

**Comment by ziggykac** [comment]
Thanks so much, really sorry yeah that was the issue. Did update floodgate yesterday but I guess it was before the update, tysm
