### ISSUE TITLE
Add `Player#setGameMode(GameMode, GameMode)`

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#7439]
### Is your feature request related to a problem?

No, I just think that this can make our code nicer and easier.

### Describe the solution you'd like.

The second argument is used to change the previous game mode of the player, while the first (new game mode) may be the same as current — in that case, only the default selection in `[F3]`+`[F4]` will be changed on client side.

The second argument is also needs to be Nullable, because `Player#getPreviousGameMode()` can return null — in that case it's should work the same way as `Player#setGameMode(GameMode)`.

### Describe alternatives you've considered.

Currently we doing this:
```
Player#setGameMode(previous GameMode)
Player#setGameMode(actual GameMode)
```

But this looks a little ugly, to be honest.
I think that making one "universal" method and use it instead will be quite convenient.

### Other

Why we need this? In join event, we put player in "waiting" room and changing their game mode to adventure, then after some time player will be teleported back to the world and their game mode will be restored.

**Comment by Doc94** [comment]
i dont understand the request...
- Player join to the server in Survival Mode (default gamemode)
- Change to Adventure for the wait room
- Return to a location and set the previous gamemode (Survival)

But getPreviousGameMode is null because not consider the first gamemode?
not?

**Comment by molor** [comment]
Waiting room is not only for players who has not played before, everyone spawns in it after join

**Comment by Doc94** [comment]
then what its the issue? i mean later of the wait room the player can return to the old gamemode not?

**Comment by electronicboy** [comment]
I fail to understand why, the previous gamemode is an implementation aspect and I'm not sure that we should be exposing it in the API so vulgarly

**Comment by molor** [comment]
@Doc94, it's isn't an issue, just a FR to add new method that changes both GameModes at once or sets only previous without setting current (and without calling PlayerGameModeChangeEvent twice for our case described in "alternatives I'm considered"). I just think it will be more convenient this way, but if the Paper devs thinks otherwise, just close this issue, I will understand and end with it ~

electronicboy, probably I don't quite understand you, but if this issue is stupid, you can close it.

**Comment by lynxplay** [comment]
I mean, am I getting something wrong or are you just trying to "restore" a previous gamemode.
The only reason you would would actually have to use the "previous gamemode" is the ability for OPs to use the gamemode changer menu ?

Anything you can just persist the "pre-game" gamemode in either a plain `Map<UUID, GameMode>` or the PDC for that matter.

//edit[0]: Saving the gamemode through a different system (like mentioned) would also have the advantage of being sure nothing else changes gamemodes while in the game. You'd be de-coupled from the barely defined implementation detail of the players previous gamemode.

**Comment by molor** [comment]
> The only reason you would would actually have to use the "previous gamemode" is the ability for OPs to use the gamemode changer menu ?

Yes. Saving previous mode is not a problem, the problem is tell it to the player without changing current mode.

**Comment by lynxplay** [comment]
> Why we need this? In join event, we put player in "waiting" room and changing their game mode to adventure, then after some time player will be teleported back to the world and their game mode will be restored.

Seems pretty irrelevant for your usecase, concerning as both the gamemode picker and quick gamemode change are only for players with permissions, which afaik is the only place the last gamemode matters to the client.

However further discussion seems rather unfruitful here, I'll mark it as a low priority (concerning cat seems to share the opinion of this being a rather questionable API addition for reasons previously mentioned). If someone wants to open a PR for it before stale-bot claws its teeth into it, so be it.

**Comment by molor** [comment]
It's not so important to waste time on it in that case, but thanks to everyone for reply.
