### ISSUE TITLE
Portal linking in 1.18 or here we go again

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#7440]
### Expected behavior

Two portals teleports player from one to another and nice-versa.

### Observed/Actual behavior

First portal in overworld creates a new one in the nether every time after player going through it.

### Steps/models to reproduce

1/ Start the server with worlds seed `1086598968070924447`
2/ Join the game
3/ CTRL+C, CTRL+V this to the server console:
```
execute in minecraft:overworld run tp @a -854 66 -623 -90 0
execute in minecraft:overworld run setblock -852 64 -622 minecraft:obsidian
execute in minecraft:overworld run setblock -852 64 -623 minecraft:obsidian
execute in minecraft:overworld run setblock -852 64 -624 minecraft:obsidian
execute in minecraft:overworld run setblock -852 64 -625 minecraft:obsidian
execute in minecraft:overworld run setblock -852 65 -622 minecraft:obsidian
execute in minecraft:overworld run setblock -852 66 -622 minecraft:obsidian
execute in minecraft:overworld run setblock -852 67 -622 minecraft:obsidian
execute in minecraft:overworld run setblock -852 68 -622 minecraft:obsidian
execute in minecraft:overworld run setblock -852 65 -625 minecraft:obsidian
execute in minecraft:overworld run setblock -852 66 -625 minecraft:obsidian
execute in minecraft:overworld run setblock -852 67 -625 minecraft:obsidian
execute in minecraft:overworld run setblock -852 68 -625 minecraft:obsidian
execute in minecraft:overworld run setblock -852 68 -623 minecraft:obsidian
execute in minecraft:overworld run setblock -852 68 -624 minecraft:obsidian
execute in minecraft:overworld run setblock -852 65 -623 minecraft:fire

```
4/ Go though the portal to the nether
5/ In the nether, go back to overworld though the portal. You spawned far away from the initial portal;
6/ Use command: `tp @s -854 66 -623 -90 0`
7/ Go though the portal to the nether again
8/ Observe the new portal near to previous
... probably can be repeated multiple times

![image](https://user-images.githubusercontent.com/19989717/152440174-30265046-e3f7-4bf5-83a7-9ef1b6d8b060.png)

### Plugin and Datapack List

```
> plugins
[01:32:25] Plugins (0)
> datapack list
[01:32:39] There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[01:32:39] There are no more data packs available
```

### Paper version

```
> version
[01:33:17] Checking version, please wait...
[01:33:18] This server is running Paper version git-Paper-185 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 46ed080)
```

**Comment by Phoenix616** [comment]
Does it happen at other locations too? This might just be a case where these coordinates and the world generation just results in the portals getting created in places where they link differently depending on the direction. Pretty common in the game imo.

**Comment by electronicboy** [comment]
theres instances of this on mojira going back years in all fun and interesting ways

**Comment by berlincount** [comment]
might relate to #6995 and #7419 and could have been broken instead of fixed by #7438

**Comment by molor** [comment]
> Does it happen at other locations too?

It seems that no, and I am surprised how one particular player on my server was so lucky to find this location..

**Comment by berlincount** [comment]
Further confirmation of bugginess on other seeds confirmed 🤷🏼‍♂️

**Comment by berlincount** [comment]
I’m not sure this and other portal bugs are fixed, we’re still seeing some … maybe related to https://github.com/PaperMC/Paper/issues/7389 ?
