### ISSUE TITLE
TNT break block 36 will not drop items

### ISSUE THREAD

**Issue by nikissXI** [PaperSpigot/Paper#7444]
### Expected behavior

when TNT break the block 36, it will drop correctly.

### Observed/Actual behavior

I made a stone maker machine, but tnt break the block 36 (cobble stone) will not drop cobble stone.
![image](https://user-images.githubusercontent.com/31379266/152637285-e026fd22-f956-4fc4-934d-92d2eb2545d5.png)

### Steps/models to reproduce

no steps

### Plugin and Datapack List

not install

### Paper version

paper-1.18.1-#186

**Comment by Machine-Maker** [comment]
> but tnt break the block 36 (cobble stone) will not drop cobble stone

I don't really understand what the "36" means here. TNT breaks stone and drops cobble when I test it.

**Comment by aerulion** [comment]
My guess is that the old numerical block id is meant, with 36 being the LEGACY_PISTON_MOVING_PIECE. In this case probably referring to a cobblestone which is currently being moved by a piston.

**Comment by nikissXI** [comment]
> My guess is that the old numerical block id is meant, with 36 being the LEGACY_PISTON_MOVING_PIECE. In this case probably referring to a cobblestone which is currently being moved by a piston.

yes!yes!that's it, do you know how to fix it ?

**Comment by nikissXI** [comment]
> > but tnt break the block 36 (cobble stone) will not drop cobble stone
> 
> I don't really understand what the "36" means here. TNT breaks stone and drops cobble when I test it.

is "the LEGACY_PISTON_MOVING_PIECE"

**Comment by lynxplay** [comment]
Can you provide a world download to replicate this ?
Specifically one that you tested to work in vanilla and which does not work on paper.

**Comment by lynxplay** [comment]
Closing this one after now more than a week of no response. If you can provide a world download for us to replicate this later one, feel free to just post it on the issue and I can reopen the issue for you :)
