### ISSUE TITLE
Phantoms don't spawn in custom dimensions

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#7448]
### Expected behavior

All mobs in custom overworld dimensions will spawn like in main overworld.

### Observed/Actual behavior

All mobs spawns, except for phantoms.

### Steps/models to reproduce

We're using this world.json:
```json
{
	"type": "minecraft:overworld",
	"generator": {
		"type": "minecraft:noise",
		"seed": -31455,
		"settings": "minecraft:overworld",
		"biome_source": {
			"type": "minecraft:multi_noise",
			"preset": "minecraft:overworld"
		}
	}
}
```

1/ tp to this world, e.g. `execute in ... run tp 0 91 0`
2/ don't sleep or die for three in-game days (or just be sure that `time since rest` statistic is > 1d)
3/ set night
4/ go to survival and stay in one high place (to avoid damage from other monsters)

### Plugin and Datapack List

No plugins.
And there are only Bukkit built-in datapack.

### Paper version

```json
{"currentVersion":"git-Paper-186 (MC: 1.18.1)"}
```

### Other

game rule `doInsomnia` = true.

I can confirm that this is a vanilla bug, not Spigot or Paper. But Paper already fixed a lot of bugs in the game (many thanks to the devs for their work) much faster than Mojang did, so I hope that this problem could not be an exception too :c

**Comment by molor** [comment]
Maybe overworld-like worlds created by API are also affected (e.g. by plugins like MultiVerse), but I can't check this now.

**Comment by Machine-Maker** [comment]
Worlds created via bukkit's world creator with the `NORMAL` environment will have phantoms spawn in them, but only the vanilla overworld will if other dimensions come from datapacks.

In `MinecraftServer#loadWorld0(String)` there is a check on the dimension key where if its the overworld, it creates the ServerLevel with the correct spawners, otherwise none.

**Comment by molor** [comment]
Something like `use-normal-spawners-on-custom-worlds` in paper.yml would be very useful in that case :c
