### ISSUE TITLE
Changing PlayerItemMend's repairAmount doens't change repair:experience ratio

### ISSUE THREAD

**Issue by rafaelsms** [PaperSpigot/Paper#7449]
### Expected behavior

Changing the event's `repairAmount` would change the experience to repair amount ratio.

For example, given an experience orb with value 10, this event would have `repairAmount = 20`: if I change it to 10, I expect it to consume the same 10 experience but changing the repair amount.

### Observed/Actual behavior

No matter what the value of `repairAmount` given, NMS' recursion on `repairPlayerItems` (on Experience Orb entity) will always give the same repair amount, making this event a bit useless.

For instance, if I set `repairAmount` to 2 no matter what the initial value is, it would consume 1 experience from the orb, and recursion would call the event again until all the experience is consumed on the same 2:1 ratio.

### Paper version

`This server is running Paper version git-Paper-187 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 0cc2503)`

### Other

```java

public class MendingNerfListener implements Listener {

    private final @NotNull JavaPlugin plugin;

    public MendingNerfListener(@NotNull JavaPlugin plugin) {
        this.plugin = plugin;
    }

    @EventHandler(priority = EventPriority.HIGHEST, ignoreCancelled = true)
    private void nerfMending(PlayerItemMendEvent event) {
        plugin.getServer()
              .sendMessage(Component.text("id = %d experience = %d, repair amount = %d, item = %s with %d".formatted(
                      event.getExperienceOrb().getEntityId(),
                      event.getExperienceOrb().getExperience(),
                      event.getRepairAmount(),
                      event.getItem().getType().name(),
                      ((Damageable) event.getItem().getItemMeta()).getDamage())));
        //if (!plugin.getConfiguration().isMendingNerfed()) {
        if (false) { // replace with true for normal behaviour
            return;
        }
        event.setRepairAmount(Math.min(event.getRepairAmount(), 2));
    }

    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
    private void checkNerf(PlayerItemMendEvent event) {
        plugin.getServer()
              .sendMessage(Component.text("=> id = %d experience = %d, repair amount = %d, item = %s with %d".formatted(
                      event.getExperienceOrb().getEntityId(),
                      event.getExperienceOrb().getExperience(),
                      event.getRepairAmount(),
                      event.getItem().getType().name(),
                      ((Damageable) event.getItem().getItemMeta()).getDamage())));
    }
}
```

**Edit:** I noticed how my understanding of Mending was wrong and updated the issue accordingly (I believe it stills needs changing)

**Comment by Machine-Maker** [comment]
@rafaelsms does [this PR](https://github.com/PaperMC/Paper/pull/7382/files) fix your issue? It lets you set the durabilityToXp function to whatever you want inside the event.

**Comment by rafaelsms** [comment]
> @rafaelsms does [this PR](https://github.com/PaperMC/Paper/pull/7382/files) fix your issue? It lets you set the durabilityToXp function to whatever you want inside the event.

Yes it does fix it! Thank you
