### ISSUE TITLE
Dynamic Spawn Rate

### ISSUE THREAD

**Issue by HellRayka** [PaperSpigot/Paper#7455]
### Is your feature request related to a problem?

Most likely with a performance problem

### Describe the solution you'd like.

Why not add a feature so that the spawn rate is adjusted automatically depending on the number of players, which would be set in the config? For example at night spawn rate will be big, which will not use the performance of the server, as at night online is small and most of the player afk on the farms, and during the day online is high and the load on the server is large.

### Describe alternatives you've considered.

did not found any solutions to this request

**Comment by electronicboy** [comment]
This is more in the realms of a plugin given how to do this would just be a massive scope balloon for the project for something which would be way too opinionated
