### ISSUE TITLE
pls add server languages

### ISSUE THREAD

**Issue by Bubbelwubbel** [PaperSpigot/Paper#7457]
### Is your feature request related to a problem?

No

### Describe the solution you'd like.

Being able to change the server language helps everyone. Germans may want a German server, Polish people want Polish, etc.

### Describe alternatives you've considered.

idk

### Other

Changing the server language is also possible in the Bedrock Edition with PowerNukkit and PocketMine-MP.

**Comment by electronicboy** [comment]
The server doesn't bundle any other language files than english and we have no sane means to include them and don't wanna have to mess around to do so, ask mojang

**Comment by Bubbelwubbel** [comment]
okay

**Comment by NoahvdAa** [comment]
(Also a duplicate of #3257)
