### ISSUE TITLE
EntityExplodeEvent does not fire if gamerule "mobGriefing" is set to false

### ISSUE THREAD

**Issue by jaylawl** [PaperSpigot/Paper#7460]
### Expected behavior

The event to fire when any entity explodes

### Observed/Actual behavior

The event does not fire for creepers (did not test for other entities yet)

### Steps/models to reproduce

```
public class EntityExplodeEventTestListenerimplements Listener {

    public EntityExplodeEventTestListener() {
    }

    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = false)
    public void onEntityExplode(EntityExplodeEvent event) {

        System.out.println("onEntityExplode");
    }

}
```

### Plugin and Datapack List

Nothing installed that could possibly interfere with that test code

### Paper version

This server is running Paper version git-Paper-399 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d4318a6 on ver/1.17.1)
You are 9 version(s) behind
Download the new version at: https://papermc.io/downloads

### Other

Thank you

**Comment by lynxplay** [comment]
Is there any additional setup you are using to replicate this ? I am unable to replicate this bug with the specified version and a simple test plugin looking like this:
```java
public final class TestPlugin extends JavaPlugin implements Listener {
    @Override
    public void onEnable() {
        this.getServer().getPluginManager().registerEvents(this, this);
    }

    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = false)
    public void on(final EntityExplodeEvent event) {
        Bukkit.broadcast(Component.text("An entity is exploding!"));
    }
}
```

**Comment by jaylawl** [comment]
Bruh i just figured it out... you got me thinking there and i am 100 % certain i have no plugins interfering with any of that, as i was trying to figure this out on a test server where is just throw on (self-made) plugins im currently trying to get to work.

The only things different from a fresh vanilla server are gamerules and maybe some minor config tweaks.

Turns out it was the `mobGriefing` gamerule. I had that set to `false`, now that i set it `true` the event is now firing upon a creeper exploding.

So... that's a bug, i guess? :-D

This may  also  be why #2315 could not be reproduced

**Comment by Machine-Maker** [comment]
I'm not sure it is a bug, the Entity/BlockExplodeEvent(s) are specifically only called if the explosion affects blocks. (if its Explosion$BlockInteraction doesn't equal `NONE`)

**Comment by jaylawl** [comment]
> I'm not sure it is a bug, the Entity/BlockExplodeEvent(s) are specifically only called if the explosion affects blocks. (if its Explosion$BlockInteraction doesn't equal `NONE`)

If that's the case, the documentation should reflect that. As of now it says:

https://papermc.io/javadocs/paper/1.17/org/bukkit/event/entity/EntityExplodeEvent.html
```
Called when an entity explodes
```

**Comment by lynxplay** [comment]
Probably inclined to agree that (at least judging from the event name and the documentation) I'd expect this event to trigger even if no damage is dealt as the entities still explode.

Whether that may be solved by clarifying or by actually changing behavior is up for discussion I guess.

**Comment by Doc94** [comment]
Yeah this issue is very old...  i try make a PR for upstream but still waiting...
because in teory the event is for entityexplode....
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/pull-requests/887/overview

**Comment by ryantheleach** [comment]
I'm restating my comments seen on upstreams bukkit PR.

Basically my thoughts are that the EntityExplosionEvent should always fire, but have an empty block list if blocks are going to be unaffected. This would allow cancelling the explosion animations that the game performs in various situations.

In addition, it's probably wise that EntityExplosionEvent has some form of listing / filtering the entities that are going to be affected inside the explosion. 

The game rule mobGriefing is not technically limited to block damage, and it's likely that Mojang will add Paintings, ArmorStands, and other 'building' entities to a tag that will get ignored if mobGriefing is on in the future.

The Mojira community considers it a bug: https://bugs.mojang.com/browse/MC-1673

For now, I think all that needs to happen is the event always fires, with an empty block list if the explosion is configured to break no blocks, + some JD changes.

At some point in the future, if it's discovered that entity filtering is already in effect in some situations, then an affectedEntity list should be added.

**Comment by Doc94** [comment]
> I'm restating my comments seen on upstreams bukkit PR.
> 
> Basically my thoughts are that the EntityExplosionEvent should always fire, but have an empty block list if blocks are going to be unaffected. This would allow cancelling the explosion animations that the game performs in various situations.
> 
> In addition, it's probably wise that EntityExplosionEvent has some form of listing / filtering the entities that are going to be affected inside the explosion.
> 
> The game rule mobGriefing is not technically limited to block damage, and it's likely that Mojang will add Paintings, ArmorStands, and other 'building' entities to a tag that will get ignored if mobGriefing is on in the future.
> 
> The Mojira community considers it a bug: https://bugs.mojang.com/browse/MC-1673
> 
> For now, I think all that needs to happen is the event always fires, with an empty block list if the explosion is configured to break no blocks, + some JD changes.
> 
> At some point in the future, if it's discovered that entity filtering is already in effect in some situations, then an affectedEntity list should be added.

thanks for the comment, im making again a few changes in my PR for handle better this... sounds better trigger in all cases but modify a little the blocks affected for avoid breaking plugins.

**Comment by Machine-Maker** [comment]
[Didn't upstream implement this through this](https://papermc.io/javadocs/paper/1.18/org/bukkit/generator/BiomeProvider.html)?
