### ISSUE TITLE
Bug or inconclusive documentation on CreeperIgniteEvent

### ISSUE THREAD

**Issue by jaylawl** [PaperSpigot/Paper#7461]
### Expected behavior

https://papermc.io/javadocs/paper/1.17/com/destroystokyo/paper/event/entity/CreeperIgniteEvent.html

Expecting this event to fire anytime the fuse of a creeper is ignited.

### Observed/Actual behavior

The event fires when a creeper is manually ignited, via right-clicking on it with a flint and steel item. It does not fire when a creeper "naturally fuses" by approaching the targeted player and being within the minimum range.

### Steps/models to reproduce

    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = false)
    public void onCreeperIgnite(@NotNull CreeperIgniteEvent event) {

        System.out.println("CreeperIgniteEvent");
}

### Plugin and Datapack List

Nothing installed that could possibly interfere with that test code

### Paper version

This server is running Paper version git-Paper-399 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: https://github.com/PaperMC/Paper/commit/d4318a6ebca2a3f2859ca0ef1b274192633c7d5e on ver/1.17.1)
You are 9 version(s) behind
Download the new version at: https://papermc.io/downloads

### Other

If this is intentional behaviour of the event, please either update the documentation to reflect this behaviour, or add the firing of this event for the latter case mentioned earlier.

Thank you

**Comment by Machine-Maker** [comment]
Putting aside the poor grammar/typo in 
```
Called when a Creeper is ignite flag is changed (armed/disarmed to explode).
```
That is an accurate description of when this event is called. The wiki, while not always accurate, can be used for in depth information about [various nbt values for entities](https://minecraft.fandom.com/wiki/Creeper#Data_values).

**Comment by jaylawl** [comment]
Yeah, i agree that it's technically accurate. And one couldn't name this `PlayerIgniteCreeperEvent` because, of course, this flag can also be changed by code or NBT commands. All i'm advocating for is at least to just add a small note to the documentation, so that the next guy that comes along and messes with it, doesn't have to spend the half hour figuring out that it is not what they thought it was and doesn't end up creating a github issue thinking it may be a bug.

https://img-9gag-fun.9cache.com/photo/a0Z7mKL_460swp.webp

**Comment by ryantheleach** [comment]
If there is an event that occurs instead, when a creeper fuses on a player, it should probably be linked to in the JavaDocs.
