### ISSUE TITLE
Make Cat and Wolf implement Colorable, add master coloring event

### ISSUE THREAD

**Issue by jaylawl** [PaperSpigot/Paper#7477]
### Is your feature request related to a problem?

Instances of `Cat` and `Wolf` and colorable just like `Sheep` and `Shulker`, however they dont implement `Colorable`. And despite both sharing a collar to be colored, they don't share an interface like "`ColorableCollar`" or something of the likes.

### Describe the solution you'd like.

1. Make `Cat` and `Wolf` implement the `Colorable` class
2. Make `Colorable#getColor()` an alias of `Cat/Wolf#getCollarColor`
3. Make `Colorable#setColor()` an alias of  `Cat/Wolf#setCollarColor`
4. If points 1-3 are out of the question -> `ColorableCollar` interface for `Cat` and `Wolf`

5. Add a master color change event for players changing the colors of entities ingame, for example: `PlayerDyeEntityEvent`, of which the existent `SheepDyeWoolEvent` should be a sub class. This new event should fire whenever a player changes the color of an entity.
6. And if possible, a parent event for `PlayerDyeEntityEvent` -> `EntityChangeColorEvent`, for whenever the color of an entity is changed, which would also include shulkers.

To clarify, the intended hierarchy of new coloring events, from parent -> child:
```
EntityEvent -> EntityChangeColorEvent -> PlayerDyeEntityEvent -> SheepDyeWoolEvent
```

### Describe alternatives you've considered.

Right now when i want to check for a cat or wolf having their collar color changed, you gotta do real hacky jazz via PlayerInteractEvent. Need i say more?

### Other

Thank you

**Comment by electronicboy** [comment]
CollarColor and Color are two separate tags so definitely against tryna combine the two together even at an API level

**Comment by jaylawl** [comment]
> CollarColor and Color are two separate tags so definitely against tryna combine the two together even at an API level

In what way are they different other than the naming of things?

**Comment by electronicboy** [comment]
because vanilla seperates them and I don't think that we should be reverting that aspect in the API as it sets long standing expectations in terms of API contacts here in which I don't think is safe to set long term

**Comment by jaylawl** [comment]
Time to request Mojang to change that in vanilla then 😄

**Comment by Machine-Maker** [comment]
Can add a `Collarable` interface probably.

Would prob confused some people seeing `Colorable` and `Collarable`

**Comment by Machine-Maker** [comment]
Also, when do shulkers change color (other than if the API changes it)?

**Comment by jaylawl** [comment]
> Also, when do shulkers change color (other than if the API changes it)?

afaik only via API. In hindsight I only included them because i was thinking about color too much

**Comment by Machine-Maker** [comment]
I'm not sure an EntityChangeColorEvent is needed, the only place I see an entity's "color" (wool or collar) changing is the "Wololo" attack from evokers changing blue sheep into red sheep. Otherwise, its just the API and players, and adding an event just for when the API changes something isn't really done. There has to be other places too.
