### ISSUE TITLE
Antixray does not work below Y level 0

### ISSUE THREAD

**Issue by SleepyScallop** [PaperSpigot/Paper#7481]
### Expected behavior

Xray to work below 0

### Observed/Actual behavior

Can xray below 0

### Steps/models to reproduce

Go under y=0 in 1.18 and start xraying freely

### Plugin and Datapack List

INFO Plugins (34): AsyncWorldEdit, BettaCore, BottledExp, Brewery, ChestProtect, ChestShop, Citizens, CMI, CMILib, CoreProtect, CrateReloaded, DenyTravel, DisableElytra, DiscordRoleSync*, EchoPet, FrostyVotes, HeadDatabase, IncreasedSpawners, ItemFrameShops, Jobs, Lands, LuckPerms, mcMMO, PersonalChest, PlayerParticles, ProtocolLib, PWarp, Spartan, SupportMe, TradeSystem, Vault, Votifier, WorldEdit, WorldGuard

no datapacks

### Paper version

16.02 04:29:50 [Server] INFO Checking version, please wait...
16.02 04:29:51 [Server] INFO This server is running Paper version git-Paper-"c50fc3a" (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: c50fc3a)
16.02 04:29:51 [Server] INFO You are running the latest version
16.02 04:29:51 [Server] INFO Previous version: git-Paper-"a8f2d67" (MC: 1.18.1)

**Comment by lynxplay** [comment]
Please ensure your x-ray config contains deepslate as a replacement block as stone does not generate below y 0

**Comment by SleepyScallop** [comment]
> Please ensure your x-ray config contains deepslate as a replacement block as stone does not generate below y 0

Trying this now

**Comment by SleepyScallop** [comment]
I am using engine mode 2, does that make a difference?

**Comment by lynxplay** [comment]
Specifically engine mode 2 requires replacement blocks to add the fake ores.

**Comment by SleepyScallop** [comment]
Thanks! Adding deepslate to it fixed it. So many servers you can xray under y level 0 on.

**Comment by SleepyScallop** [comment]
> Specifically engine mode 2 requires replacement blocks to add the fake ores.

Im seeing all the blocks i have hidden as replacement blocks in engine mode 2, i only have 3 blocks in replacement blocks and they arent whats being used?

**Comment by SleepyScallop** [comment]
anti-xray:
      lava-obscures: false
      update-radius: 2
      use-permission: false
      max-block-height: 128
      hidden-blocks:
      - iron_ore
      - copper_ore
      - deepslate_iron_ore
      - deepslate_coal_ore
      - deepslate_copper_ore
      - gold_ore
      - deepslate_gold_ore
      - redstone_ore
      - deepslate_redstone_ore
      - emerald_ore
      - deepslate_emerald_ore
      - raw_copper_block
      - raw_iron_block
      - lapis_ore
      - deepslate_lapis_ore
      - diamond_ore
      - deepslate_diamond_ore
      - mossy_cobblestone
      - spawner
      - chest
      - cobweb
      - oak_fence
      - rails
      - enderchest
      - obsidian
      - ancient_debris
      - bone_block
      - glowstone
      - magma_block
      - nether_bricks
      - nether_gold_ore
      - nether_quartz_ore
      - polished_blackstone_bricks
      replacement-blocks:
      - stone
      - oak_planks
      - deepslate
      enabled: true
      engine-mode: 2

**Comment by lynxplay** [comment]
In engine mode 2, the replacement blocks are used to be "replaced" by your hidden blocks. E.g. engine mode 2 replaces a lot of the replacement blocks with ores etc to make it harder to xray.

THat is the general nature of engine mode 2, spam a bunch of fake hidden blocks to drown out the real ones.
Engine mode 1 does it the other way -> replace hidden blocks to basically hide everything and make it look like no ores exist.

**Comment by SleepyScallop** [comment]
> In engine mode 2, the replacement blocks are used to be "replaced" by your hidden blocks. E.g. engine mode 2 replaces a lot of the replacement blocks with ores etc to make it harder to xray.
> 
> THat is the general nature of engine mode 2, spam a bunch of fake hidden blocks to drown out the real ones. Engine mode 1 does it the other way -> replace hidden blocks to basically hide everything and make it look like no ores exist.

engine-mode: 1 isn't perfect because only ores that are completely covered by solid blocks can be hidden. This means that ores exposed to air in caves, for example, are still visible. If i blocked air would that make my server lag?

**Comment by lynxplay** [comment]
Generally iirc we recommend against air used in xray.
Besides a plain "try out different things and workout what works best for you" there is also [our discord](https://discord.gg/papermc) for further support so we can keep the issue tracker as on-topic as possible👍

**Comment by SleepyScallop** [comment]
> Generally iirc we recommend against air used in xray. Besides a plain "try out different things and workout what works best for you" there is also [our discord](https://discord.gg/papermc) for further support so we can keep the issue tracker as on-topic as possible👍

I have found a setting that seems to produce a more pleasing result without filling every piece of stone almost.
https://ibb.co/LYPYGRN

Thanks for the help, i will join the discord if i have further questions!
