### ISSUE TITLE
Chunk regen from paper doesnt work with custom worldgenerator

### ISSUE THREAD

**Issue by supermem99** [PaperSpigot/Paper#7482]
### Expected behavior

if i want to regenerate my chunks with the api using lands, it should be generated like all custom generators not only like the default generator.

### Observed/Actual behavior

Lands uses you paper api for chunk regeneration to regenerate unclaimed chunks.
![Screenshot_2](https://user-images.githubusercontent.com/32147021/154320278-decd32c9-02fa-4e3b-88a5-13d352de525d.png)
This will happen:
![Screenshot_1](https://user-images.githubusercontent.com/32147021/154320639-7f6cf849-e526-423a-a7c4-22931051e1ab.png)
 

### Steps/models to reproduce

1. Install Lands
2. claim and unclaim the same chunk.
3. Chunk will be generated with default terrain. (default world generator)

### Plugin and Datapack List

cleaninstall with fawe and worldguard, lands

### Paper version

This server is running Paper version git-Paper-187 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 0cc2503)
You are 11 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-177 (MC: 1.18.1)

**Comment by electronicboy** [comment]
what custom world generator? is this reproducible with a setup we can actually support? I'd assume /regen is afflicted

**Comment by jpenilla** [comment]
Cannot reproduce, method works fine for default and custom generators in my testing. I would guess either your seed changed at some point, or you generated that terrain in an older version of the game.

**Comment by Gerrygames** [comment]
World#regenerateChunk is not compatible with the depcrecated custom world generator API. You need to migrate to the new API.

**Comment by jpenilla** [comment]
> World#regenerateChunk is not compatible with the depcrecated custom world generator API. You need to migrate to the new API.

This is not the case.

**Comment by supermem99** [comment]
I am using Terra. https://github.com/PolyhedralDev/Terra

**Comment by kennytv** [comment]
That doesn't matter. Lands very likely does not use Paper API for this.

**Comment by supermem99** [comment]
Thank you for help... not.
Lands told me its the issue of terra(customworldgenerator) and you paper tell me that its not supported?

why should i go around every servergithubs??  That is your fault not from them.

**Comment by electronicboy** [comment]
feel free to hold the attitude or take it elsewhere, you're not entitled to support

lands is not supported by us, nor is terra, we can't exactly comment on either of them, especially not lands, and terra is its own set of fun which we can't really provide support for. If there is an issue with that API (which would, in turn, be an issue with how generation in general works thus more an issue), I'd much rather it come as an issue report from the terra devs rather than this issue given that I doubt anybody here wants to spend hours pulling this apart on a whim
