### ISSUE TITLE
Failed to start thread - pthread_create (EAGAIN)

### ISSUE THREAD

**Issue by rentexgfx** [PaperSpigot/Paper#7485]
### Stack trace

That crash error can't be logged.

Crash message:
`
>....[170.468s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.`
https://i.imgur.com/AgM99Km.png

### Plugin and Datapack List

**Plugins (59):** AdvancedPortals, AntiCooldown, AuctionHouse, BanItem, BeastTokens, BeastWithdraw, BuycraftX, ChatManager, ChatReaction, ChestShop, CleanroomGenerator, CMI, CMIEInjector*, CMILib, CombatLogX, CrazyCrates, CrazyEnvoy, DeluxeSellwands, eco, EcoArmor, Ersatz*, HolographicDisplays, HopperImprovements*, LiteBans, LuckPerms, Multiverse-Core, NoTrades, PlaceholderAPI, PlayerKits, PlugManX (PlugMan), ProtocolLib, SecuredNetwork, ServersNPC, ShopGUIPlus, SirBlobmanCore (SirBlobmanAPI, XSeries), SkinsRestorer, skRayFall, Skript, skript-placeholders*, SkStuff*, skUtilities*, spark, StaffPlus, SuperbVote, SuperiorSkyblock2, TAB, TempFly, TubeTils, UltimateAutoRestart, UltraCustomizer, Vault, VoidTeleport, Votifier, WildChests, WildStacker, WildTools, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Actions to reproduce (if known)

//

### Paper version

[17:32:46 INFO]: Checking version, please wait...
[17:32:47 INFO]: This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)
You are running the latest version
Previous version: git-Paper-399 (MC: 1.17.1)

### Other

So this crash happens time to time and when it happen, server is unresponsible to console commands except for "kill" button.

My friend set that "limit" for threads/processes to like couple of millions but no effect. 
Screenshot of error is on top of issue.

Server specs:
OVH Rise
32GB DDR4 2666MHz
Ryzen 5 3950x
300GB SSD Raid

(Using Aikar GC startup parameters)

I'm not sure that is because of Paper but I still want you to try to help me :)

**Comment by electronicboy** [comment]
You hit some form of resource limit and the OS refused to create new threads, you're gonna need to work out where the limit is and what's being hit

for support, please use the discord or forums
