### ISSUE TITLE
Advanced Portals Effects

### ISSUE THREAD

**Issue by xXIOSCARIXx** [PaperSpigot/Paper#7489]
### Expected behavior

Teleport effects after being teleported through a portal to another world

### Observed/Actual behavior

No teleport effect

### Steps/models to reproduce

Effects stopped working after updating to #203, going back to #200 effects are working again

### Plugin and Datapack List

AdvancedPortals, ClearLag, CMILib, ConsoleSpamFix, CoreProtect, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), GadgetsMenu, HolographicDisplays, Jobs, JukeBox, LaunchPad, Multiverse-Core, Multiverse-Inventories, NoteBlockAPI, PermissionsEx*, PlotSquared, PlugMan, ProtocolLib, RandomTeleport*, ServerListPlus*, ShopGUIPlus, TitleManager, Vault, ViaBackwards, ViaVersion, WorldGuard

### Paper version

This server is running Paper version git-Paper-200 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: f5b9e07)

**Comment by Machine-Maker** [comment]
You're gonna have to be more specific and give actually reproduction steps. I can't see a difference between vanilla and paper when a player in survival mode goes through a nether portal.

Make sure you can reproduce whatever issue you are having without plugins.

**Comment by xXIOSCARIXx** [comment]
The title says Advanced Portals.. the plugin.

The effects created by that plugin when traveling to a different world through a portal (plugin made portal, not vanilla one) dont work on newer versions, but they do work on paper build #200

**Comment by Machine-Maker** [comment]
Well, I'd report the issue there then. I don't know that plugin, or what it does, or how it does. I don't think anything related to creating particles was changed, but if they were using some non-api stuff, that might've changed. 

EIther way, report it there, and then if its a paper issue, the mod author can come back here and report it as such.
