### ISSUE TITLE
Chunk load problem

### ISSUE THREAD

**Issue by ttt0** [PaperSpigot/Paper#7494]
### Timings or Profile link

https://timings.aikar.co/?id=42c6b76b2e9747c3a9787b38dc3828d9#timings

### Description of issue

Chunks load very slowly, it gets worse when the world changes, it opens later, but it loads very slowly at first

This happens after 40 50 players There is no problem when there are 20 30 people

I also want to say that when a player or I change the world, the ping of the person who changed the world goes up to 300 400 and drops back to 30 40

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/66686400/154839562-0a1588b3-3055-462c-83a2-a9208961d77d.png)

![image](https://user-images.githubusercontent.com/66686400/154839567-be73a4a3-716b-488d-a4b8-a9551b6b3983.png)

### Server config files

```
Spigot.yml: https://paste.gg/p/anonymous/75ac2940829c492ba5bad98b8ee0b585
paper.yml https://paste.gg/p/anonymous/96f902dd615f45dabc8df850945b8a1b
server.properties.yml: https://paste.gg/p/anonymous/88886c9d08934d5bb70eda7b5d1af617
```

### Paper version
![image](https://user-images.githubusercontent.com/66686400/154841391-3d9bdd10-48f8-4c16-8bb8-057f7e38300a.png)

### Other

https://www.youtube.com/watch?v=CimfTkVZyN0
You can see the problem in more detail here.

My hosting information

AMD Ryzen 7 3700X 3.8-4.4 Ghz / 8 Core 16 Threads 64GB DDR4 500GB M2 NVME dedicated server

**Comment by electronicboy** [comment]
latency increase during world switching is somewhat expected given how mojangs ping counter works, that's basically unavoidable

You can configure how hard paper tries to load chunks in the `chunk-loading` section, do note that flooding the client with chunks too hard, especially with anti x-ray, will increase the latency on switching worlds, etc
