### ISSUE TITLE
Add Permission for F3+N and F3+F4 (Vanilla OP System DISABLED)

### ISSUE THREAD

**Issue by socksprox** [PaperSpigot/Paper#7496]
### Is your feature request related to a problem?

Somehow: I would like to switch between gamemodes with F3+N and F3+F4 like in vanilla minecraft

Info: PurpurMC a for of paper has this already implemented and there is a Plugin for it on SpigotMC (F3NPerm)

### Describe the solution you'd like.

Add a Permission for F3+N and F3+F4 so that i can acces this like in vanilla minecraft

### Describe alternatives you've considered.

(FOrk of Paper) Purpur
(Plugin on SpigotMC) F3NPerm

### Other

-

**Comment by e-im** [comment]
Stuff like this is generally outside the scope of Paper, as you mention this can be accomplished with a plugin ([f3nperm](https://www.spigotmc.org/resources/f3nperm.46461/)).

To more directly address your issue: it will behave "like in vanilla minecraft" - you just have to op yourself.

additionally, more stuff than this is done client-side based on op level, command blocks being one.
