### ISSUE TITLE
Chunk Viewdistance option not working anymore lol

### ISSUE THREAD

**Issue by 0x484** [PaperSpigot/Paper#7497]
### Expected behavior

Being able to set a certain view distance in Config

### Observed/Actual behavior

The view distance being set to 12 or 10 no matter what number I put in

### Steps/models to reproduce

Start a Paper server on the newest version I guess

### Plugin and Datapack List

None (Tested without any Plugins)

### Paper version

Paper version git-Paper-205 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 36a1650)

**Comment by electronicboy** [comment]
not sure what you mean by "not working"
iirc, the patch which makes the server respect the clients VD is now back, the client will show up to its own view distance, no further, and won't show anything past the servers view distance if that's lower than the clients VD

**Comment by 0x484** [comment]
Oh thanks. I have done some tests an it seems that the Simulation Distance is the same as the normal one. Or at least the chunks are loaded. This is a Server with view distance set to 1 and Simulation distance set to 32 (With only one player)
![image](https://user-images.githubusercontent.com/93775214/154861912-48143796-3b7f-4b42-8ecc-48edf9718c0d.png)

**Comment by electronicboy** [comment]
the simuation distance affects how far the "simulation" occurs, the vd controls how many chunks are sent to the client, this sounds to me to be working as expected
