### ISSUE TITLE
Mobs are not despawning

### ISSUE THREAD

**Issue by MoWobbler** [PaperSpigot/Paper#7498]
### Expected behavior

Mobs should despawn when the server restarts or when a player is far enough away from the mob

### Observed/Actual behavior

Mobs do not despawn when the server restarts or when a player is far enough away from the mob

### Steps/models to reproduce

1) Start a new testing server on paper-1.17.1-408
2) Join the server
3) Either spawn some mobs or find some mobs that normally despawn
4) Stop the server while near the mob/mobs you found
4) Start the server
5) Log back in and the mobs will still be there

### Plugin and Datapack List

None

### Paper version

This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)

**Comment by electronicboy** [comment]
this is likely a mixture of a long standing issue with some of CBs changes and misconfiguration of the server, i.e. hard despawn ranges need to be within the view distance

Closing as 1.17 is basically ES/EOL and ^
