### ISSUE TITLE
whet paper1.18.1≥202 Multiverse-Core work abnormality

### ISSUE THREAD

**Issue by shuiqing2046** [PaperSpigot/Paper#7499]
### Expected behavior

Make  Multiverse-Core work fin

### Observed/Actual behavior

paper1.18.1 ≥ 202 can create a new custom world, but cannot load the old one.
paper1.18.1 ≤ 201 can reload the old custom world

### Steps/models to reproduce

paper1.18.1 ≥ 202 can create a new custom world, but cannot load the old one.
paper1.18.1 ≤ 201 can reload the old custom world

### Plugin and Datapack List

Plugins (2): Multiverse-Core, ProtocolLib

### Paper version

This server is running Paper version git-Paper-207 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: b757019)
You are running the latest version

### Other

Multiverse-Core producer said:

it looks to be a paper bug
build 202 introduced various performance improvements. looks like one of them is causing this
not sure which since I don't have time to look into it
it would be best to open a bug report on their github

error log:
https://paste.ubuntu.com/p/CvQwGf7Qfd/

**Comment by electronicboy** [comment]
your sim distance config is invalid, min value is 2; as was discussed on discord

**Comment by shuiqing2046** [comment]
> 您的 sim 距离配置无效，最小值为 2；正如在discord上讨论的那样

？？？
simulation-distance=3

**Comment by electronicboy** [comment]
your simulation distance is set to 1, please check your configs, including spigot.yml

**Comment by shuiqing2046** [comment]
> your simulation distance is set to 1, please check your configs, including spigot.yml

Perfect. Thank you.
