### ISSUE TITLE
World Save Issue When 'world' and 'overworld' are Both Loaded.

### ISSUE THREAD

**Issue by ScruffySnub** [PaperSpigot/Paper#7502]
### Expected behavior

When the server stops, player and entity data should be saved to the appropriate world even with 4+ loaded.

Console would read something like
Saving world data [world] world type: overworld
Saving world data [nether] world type: nether
Saving world data [the_end] world type: the_end
Saving world data [overworld] world type: overworld

### Observed/Actual behavior

Stopping the server with both 'world' and 'overworld' loaded (world is the 'primary' folder and loads on server start) causes the server to save the data for world to overworld, and not store the other data anywhere.

Console reads something like
Saving world data [overworld] world type: overworld
Saving world data [nether] world type: nether
Saving world data [the_end] world type: the_end

there was no line in the log during the shutting down process that referred to just 'world', for some reason it's just taking 'overworld' instead as if it were the 'primary' folder.

### Steps/models to reproduce

Name the default world 'world'.
Use any plugin to load an additional world after the server has started called 'overworld'.
Stop the server.

For more obvious indications the error has occurred, stop the server while a player is 'world' and when the server restarts they will be at the same coordinates in 'overworld' instead. In a few instances, I saw 'overworld' but interacted with blocks as if it were 'world'- I could move through some blocks even with collision on and there was lots of air that did the opposite, also breaking or placing blocks would change the 'target' block to a different material (I'm assuming it was the corresponding material from that location in the other world folder).

This bug was instantly fixed when I changed the name of the 'overworld' folder to 'surfaceworld'. When I changed it back, it broke again.

### Plugin and Datapack List

Initially I found this error using a Denizen script to load the additional worlds (my only plugin), but later double-checked that the same issue happens regardless of what is used to load and teleport to additional worlds.

### Paper version

[15:11:46 INFO]: Checking version, please wait...
[15:11:47 INFO]: This server is running Paper version git-Paper-207 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: b757019)
You are running the latest version
Previous version: git-Paper-177 (MC: 1.18.1)

**Comment by electronicboy** [comment]
issue here is that the "world" is the overworld, so it's gonna cause a conflict here, really we need to prevent loading any world called overworld

**Comment by jpenilla** [comment]
I would guess this is also an issue when you try to create a world named `the_nether`, `the_end`, or if you attempt to use a name which will result in the same dimension location as a datapack-added dimension.
