### ISSUE TITLE
The .mca in poi can't unload with world unload

### ISSUE THREAD

**Issue by PengLx** [PaperSpigot/Paper#7504]
### Expected behavior

The file that in poi can be unloaded with the world unload.

### Observed/Actual behavior

When I unload a world, the .mca in poi are still be loaded.
It cause I can move the file from poi.
I have test it in spigot and it was work as me expected.

### Steps/models to reproduce

Create a world and create some file that storage in poi.
and unload that world

### Plugin and Datapack List

Plugins (52): PlaceholderAPI, Lib1711, TrChat, NBTAPI, WkKit, LightAPI, LuckPerms, LoneLibs, ProtocolLib, LibsDisguises, SimpleORM, ServerTours, Vault, SimpleLogin, GemsEconomy, PlayerPoints, WorldSystem, PlayerSQL, CloudMc, Multiverse-Core, FastAsyncWorldEdit (WorldEdit), PWarp, RolCards, WorldGuard, Brewery, MythicMobs, FarmFrenzy, Citizens, MythicCrucible, AdvancedCrates, ModelEngine, SoulPoints, dtlTradersPlus, MythicLib, ProMCCore, BattlePass, MMOItems, TimeStatsBonus, Adyeshach, Breaker, Chemdah, Patch0, ItemsAdder, ShopGUIPlus, TrMenu, WolfyUtilities, TrHologram, CustomCrafting, QuickShop, AttackModify, ProSkillAPI, MythicExtension

### Paper version

paper-1.18.1-207

**Comment by molor** [comment]
Can confirm, probably this issue prevents me from creating a backup of world folder after `save-off` and `save-all` commands while the server is running because OS still reports that some files are used/locked (also maybe that happens on windows only)

**Comment by PengLx** [comment]
> Can confirm, probably this issue prevents me from creating a backup of world folder after and commands while the server is running because OS still reports that some files are used/locked (also maybe that happens on windows only)`save-off``save-all`

I have tested and can confirm it was not loaded by saving

**Comment by electronicboy** [comment]
save-off, save-all is irrelevant here, disabling saving doesn't make the server stop touching worlds there, there's still the region file cache and such which maintains open file handles, etc

as for the POIs, I think this kinda goes back to a wider issue here, I don't think that the close logic actually deals with closing this stuff properly, but, it could be stuck just waiting to flush out, vanilla itself has never handled world data well, especially POIs

**Comment by PengLx** [comment]
> save-off, save-all is irrelevant here, disabling saving doesn't make the server stop touching worlds there, there's still the region file cache and such which maintains open file handles, etc
> 
> as for the POIs, I think this kinda goes back to a wider issue here, I don't think that the close logic actually deals with closing this stuff properly, but, it could be stuck just waiting to flush out, vanilla itself has never handled world data well, especially POIs

OK, thank you. I'll wait patiently for you to solve this problem

**Comment by lynxplay** [comment]
Documenting this, I am expecting we can build a PR on this sooner than later.
https://github.com/PaperMC/Paper/blob/36f0c1b3cc1037f50dc2abe0f2319eab0c4be4b7/patches/server/0019-Asynchronous-chunk-IO-and-loading.patch#L3481-L3485
The changes to the SectionStorage make its close method a noop, a super call here fixes the issue, however with how many changes the chunk system has, I'll circle back with leaf on this before we propose a fix.
