### ISSUE TITLE
ItemMeta cannot be cast to BlockStateMeta?

### ISSUE THREAD

**Issue by dsevvv** [PaperSpigot/Paper#7508]
### Expected behavior

In the past, I have casted the ItemMeta of a SPAWNER ItemStack into a BlockStateMeta, with no issue.

### Observed/Actual behavior

When trying to do the same with an ANVIL ItemStack I am greeted with https://mcpaste.io/c29b474fa7e8991c

### Steps/models to reproduce

try casting the ItemMeta of an ANVIL ItemStack into a BlockStateMeta.

### Plugin and Datapack List

my own plugin

### Paper version

This server is running Paper version git-Paper-214 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: bfa50ad)
You are running the latest version
Previous version: git-Paper-197 (MC: 1.18.1)

**Comment by lynxplay** [comment]
Anvils do not represent/ are not block states / tile entities. You cannot cast their item meta hence.
