### ISSUE TITLE
Chunk loading issue

### ISSUE THREAD

**Issue by agoniaprivat** [PaperSpigot/Paper#7518]
**### EDIT: Found issue.
After disabling anti xray in config, chunks started to load normally.**

### Timings or Profile link

https://timings.aikar.co/?id=d476456b4aaf4c8ca24ed672c0f3608f

### Description of issue

Chunkloading issue.
**See video:**
https://youtu.be/K1UkjId1PT4
https://youtu.be/anKwcsswMa8

Same happens in nether, overworld is working a lot better but it still loading pretty slow.
Rain does not appear in nether, only the_end.

### Plugin and Datapack List

![2022-02-28_17 30 52](https://user-images.githubusercontent.com/50961682/156020591-ca109b51-1f58-48a4-b49e-a58d6ae4b7ba.png)
Downloaded something called "EndBiomeFixer" yesterday as an plugin, did no change. It was the same without it.

No datapacks.

### Server config files

https://paste.gg/p/anonymous/54736da352304d7e8c2bf7b2370f8d04

### Paper version
This server is running Paper version git-Paper-216 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 30cb7d0)

### Other

With a few players online, it does not load for a very long time. With around 40 players online, it loads extremely slow.

**Comment by agoniaprivat** [comment]
EDIT/UPDATE:
Problem found; After disabling anti xray in config, chunks started to load normally.

**Comment by ttt0** [comment]
I suggest you to set "max-concurrent-sends: 2" to 10, so I solved this error
