### ISSUE TITLE
Allow using MiniMessage in '...-message' configuration options

### ISSUE THREAD

**Issue by NoahvdAa** [PaperSpigot/Paper#7520]
### Is your feature request related to a problem?

Since [Paper 1.18.2 will include Adventure 4.10.0](https://github.com/PaperMC/Paper/commit/9a73213f888b0dd9e4d3777068095747c6cd563d), MiniMessage will now also be included in Paper. Allowing the use of MiniMessage in the message config options would allow people to use hex colors with ease and use other features not available in the legacy text format, such as translatable components and clickable/hoverable text.

### Describe the solution you'd like.

A new config option (e.g. `messages.use-minimessage`), that when set to true serializes the messages in bukkit.yml, spigot.yml and paper.yml using MiniMessage instead of with the legacy ampersand serializer.

### Describe alternatives you've considered.

Creating gradients with legacy color codes (yuck)
<img width="400" alt="image" src="https://user-images.githubusercontent.com/44026893/156169204-23ed0016-6a45-462f-9f9d-de3edcad695f.png">

**Comment by e-im** [comment]
Implemented with configuration refactor.
