### ISSUE TITLE
Update to 1.18.2

### ISSUE THREAD

**Issue by ChrissW-R1** [PaperSpigot/Paper#7521]
### Is your feature request related to a problem?

Yesterday the bugfix version 1.18.2 of Minecraft was released.

### Describe the solution you'd like.

Please update to the newest Minecraft / Bukkit / Spigot version.

### Describe alternatives you've considered.

The update of the upstream projects is required.

**Comment by lynxplay** [comment]
We are already working on the update, we are certainly aware it was released.
Feel free to follow our progress on our [discord](https://discord.gg/papermc)'s `-1-18-2` channel.
