### ISSUE TITLE
Iron Golem Spawner Spawn Issue

### ISSUE THREAD

**Issue by LeeTheTech** [PaperSpigot/Paper#7525]
### Expected behavior

Iron golems spawn outside of walls and glass.

### Observed/Actual behavior

Sometimes iron golems spawn in glass and walls.

### Steps/models to reproduce

Use a command block to change the spawner to a normal iron golem spawner and wait with walls and glass setup near it.

### Plugin and Datapack List

No plugins.

### Paper version

1.18.1 build 216

### Other

This has been a issue for quite some time, this isn't vanilla behavior and can be really annoying for players who build these type of farms.

**Comment by Machine-Maker** [comment]
![2022-03-01_20 39 36](https://user-images.githubusercontent.com/15055071/156296193-9bbddf6a-02e6-4ca7-b69c-9e908180ec8d.png)

Been sitting like this for a while, iron golems only spawn in the clear area, never inside a wall block.

**Comment by ghost** [comment]
Can second @Machine-Maker 's reply, the only time they glitched into walls was when they tried to spawn on a block next to the wall, and that was rare. 

EDIT: Will also point out the wall spawning happens even with Villagers on an iron farm if the spawnable block is right next to the farm, the Golems can suffocate in the walls.

**Comment by andrew121410** [comment]
When I made an iron farm couple days ago I noticed that iron golems when they spawn right next to a glass wall (2 block high) they could go through the wall.

**Comment by ghost** [comment]
> When I made an iron farm couple days ago I noticed that iron golems when they spawn right next to a glass wall (2 block high) they could go through the wall.

Is it possible you can provide a video? It is possible its just reading a spawnable block and attempting to spawn the Golem there, which is completely normal behaviour, even from Vanilla MC. I use a layer of glass if I build next to the spawn area, as its not a spawnable block.

**Comment by aurorasmiles** [comment]
Since there has been no reply by the author for the past couple of months, and people have not been able to replicate this issue, I'll be closing it for now.
