### ISSUE TITLE
Iron Golem Spawning not synchronized

### ISSUE THREAD

**Issue by Old-Qrow** [PaperSpigot/Paper#7528]
### Expected behavior

When villagers panic, all villagers should attempt to spawn a golem every 5 seconds. This timer should be synchronized globally, such that multiple groups of panicking villagers separated by at least 10 blocks should all spawn golems at the same time

.

### Observed/Actual behavior

Villager panic spawning does not appear to be synchronized, so at most, only two groups spawn golems at a time. Sometimes only one golem spawns, and it's not always the same groups of villagers each time.

### Steps/models to reproduce

The farm was recreated in vanilla survival using the exact same farm. Etho hopper clock triggers a pulse every 40 seconds into a pulse extender that keeps the pillager raised for roughly 5 seconds. Each villager stall is 11 blocks away from its orthagonally adjacent neighbors.

https://user-images.githubusercontent.com/100750190/156304087-c648cbe8-4f97-4667-beda-a3be2552e0ff.mp4

### Plugin and Datapack List

Plugins: CoreProtect, DiscordSRV, InventoryRestore, LuckPerms, NoMobGreifing, SimpleVotes, Votifier

Datapacks: ArmorStatues, Double Shulker Shells, DragonDrops, SilenceMobs, More Mob Heads, Track Raw Statistics

### Paper version

This server is running Paper version git-Paper-"30cb7d0" (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 30cb7d0)
You are running the latest version
Previous version: git-Paper-"7d7ae7b" (MC: 1.18.1)

**Comment by ghost** [comment]
Correct me if im wrong, but shouldnt it be 20 blocks apart? Thats how I do my custom design, and it works fine. All 6 platforms spawn a golem every 30 seconds. can you upload a copy of the world download? That way we could test the design and see if its just an issue with the farm, or an actual server issue.

**Comment by Old-Qrow** [comment]
The area should be a 20 x 20 x 20 cube centered on the villagers, so the range extends out from each group of villagers 10 blocks. As long as they're at least 10 blocks apart (mine are 11), everything should work.

You can download the world here: https://drive.google.com/file/d/1JHKNQeCPfQ22lg0mrUVoNQ9G42MVKGYi/view?usp=sharing

Coords for the iron farm are -180,120

**Comment by ghost** [comment]
Had to request access to get the download, waiting for you. I have a design with 6 floating platforms, two in each set, 20 blocks apart in height, with no spawnable blocks in the 10 block range, only redstone I have is at the base, my Iron farm works on the latest paper version, all 6 platforms spawn as expected in Vanilla, so honestly not sure where your issue is based.

**Comment by Old-Qrow** [comment]
Sorry about the access. You should be able to access the download now.

**Comment by ghost** [comment]
> Sorry about the access. You should be able to access the download now.

Hmm, The wiki even states 16 block radius around each box of villagers, which is why I do 20, but im downloading now to take a look, will edit the comment with my findings. If you wanna take a look yourself, the link for the Wiki is https://minecraft.fandom.com/wiki/Tutorials/Iron_golem_farming

**Comment by Old-Qrow** [comment]
The 16 block range in the wiki page you linked is referring to the last time villagers have seen an iron golem, not how close they are to other villagers. That's why the golems get dropped out of the farm. I've linked a screenshot from the Villager wiki page explaining the mechanics at play. 

Coincidentally, when golems spawn, all villagers within 16 blocks of the spawning villagers will reset their timers, but just highlights the original bug I was reporting. If they spawn on a global cooldown, every set of villagers in my farm should spawn together just like the Vanilla example in my video shows, then they reset themselves. The Paper server villagers are clearly not spawning on a global cooldown, since some of them generate iron golems, and then reset the others that are within 16 blocks.

That also explains why there's no problem with your farm, because if your villagers are outside of the 16 block reset bubble, it doesn't matter if they're not spawning golems on a global cooldown or not.

![image_2022-03-05_084209](https://user-images.githubusercontent.com/100750190/156885841-c6a0fa8a-9fb7-47a6-8bb9-203f8ee0ea55.png)

**Comment by ghost** [comment]
> The 16 block range in the wiki page you linked is referring to the last time villagers have seen an iron golem, not how close they are to other villagers. That's why the golems get dropped out of the farm. I've linked a screenshot from the Villager wiki page explaining the mechanics at play.
> 
> Coincidentally, when golems spawn, all villagers within 16 blocks of the spawning villagers will reset their timers, but just highlights the original bug I was reporting. If they spawn on a global cooldown, every set of villagers in my farm should spawn together just like the Vanilla example in my video shows, then they reset themselves. The Paper server villagers are clearly not spawning on a global cooldown, since some of them generate iron golems, and then reset the others that are within 16 blocks.
> 
> That also explains why there's no problem with your farm, because if your villagers are outside of the 16 block reset bubble, it doesn't matter if they're not spawning golems on a global cooldown or not.
> 
> ![image_2022-03-05_084209](https://user-images.githubusercontent.com/100750190/156885841-c6a0fa8a-9fb7-47a6-8bb9-203f8ee0ea55.png)

Well from looking at your farm, Its 100% villager spacing. Using the end you left empty, I altered the spacing of the beds, and you'll need to make a bigger water system, but its spacing for sure. For example, This is one side, and you're still getting Golems on the other, even though I removed two sets of beds to make correct space for the one side. Not a paper related issue at all.
![2022-03-05_14 31 22](https://user-images.githubusercontent.com/80531493/156887800-0918cd10-4b72-4f0b-b09b-f735629f2378.png)
.

EDIT: Tested on both Vanilla and Spigot / Paper, 100% just his spacings, not Paper related. on Vanilla his world download has the same result, until I alter the farm to the correct dimensions

**Comment by aurorasmiles** [comment]
Since this seems to be an issue with the farm design and not an actual bug, this issue will be closed.
