### ISSUE TITLE
Changing blocks in onDisable will indefinitely pause the watchdog thread during a crash.

### ISSUE THREAD

**Issue by Warriorrrr** [PaperSpigot/Paper#7544]
### Expected behavior

The block to be set, and the watchdog thread to not stay paused.

### Observed/Actual behavior

The watchdog thread pauses indefinitely, and the plugin that attempted to set the block never finishes shutting down.

### Steps/models to reproduce

Reproducible using the code in this gist: https://gist.github.com/Warriorrrr/41345003f00f2482f3abde0335761ca3

The 'changed block' message will never be logged as the thread gets paused after the setType. (latest.log attached below)

### Plugin and Datapack List

No plugins aside from the one used to replicate.

### Paper version

This server is running Paper version git-Paper-224 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 42a9c37)
You are running the latest version

### Other

[latest.log](https://github.com/PaperMC/Paper/files/8189240/latest.log)
[jstack.txt](https://github.com/PaperMC/Paper/files/8189177/jstack.txt)

Watchdog thread from the jstack:
![image](https://user-images.githubusercontent.com/50800980/156853672-6533a5f5-9b72-4e53-b370-2a5c9d8edc3a.png)

**Comment by kennytv** [comment]
Can you retest on the latest Paper version?

**Comment by Warriorrrr** [comment]
Retested on version 234, bug still occurs.

**Comment by lynxplay** [comment]
Replicable with the provided example plugin.
The server hangs as the block mutation requests a chunk which is completed on the mainThreadProcessor which, after a long tick time out, dies prior to the execution of the setBlock method.

**Comment by Warriorrrr** [comment]
I've been looking into this issue a bit myself today, and it seems like throwing an exception if the current thread is the watchdog thread before it tries to complete it on the mainThreadExecutor fixes the issue. Would this be worth PRing, or is there possibly a better solution?
