### ISSUE TITLE
Custom datapack biomes in nether not generating

### ISSUE THREAD

**Issue by Infini-PLEX** [PaperSpigot/Paper#7547]
### Expected behavior

The biomes will generate

### Observed/Actual behavior

The biomes dont generate

### Steps/models to reproduce

install a datapack that generates custom biomes

### Plugin and Datapack List

CoreProtect, dynmap, Essentials, EssentialsChat, Factions, FastAsyncWorldEdit (WorldEdit), FastChunkPregenerator, LuckPerms, Multiverse-Core, ProtocolLib, Vault
[vanilla (built-in)], [file/anti enderman grief v1.1.2.zip (world)], [file/armor statues v2.8.3.zip (world)], [file/bukkit (world)], [file/cauldron concrete v2.0.5.zip (world)], [file/chunk loaders v1.0.3.zip (world)], [file/classic fishing loot v1.1.2.zip (world)], [file/confetti creepers v2.2.2.zip (world)], [file/count mob deaths v1.1.2.zip (world)], [file/custom nether portals v2.3.5.zip (world)], [file/double shulker shells v1.3.2.zip (world)], [file/durability ping v1.1.2.zip (world)], [file/fast leaf decay v2.0.5.zip (world)], [file/larger phantoms v1.2.3.zip (world)], [file/more mob heads v2.9.4.zip (world)], [file/nether portal coords v1.1.2.zip (world)], [file/player head drops v1.1.2.zip (world)], [file/silence mobs v1.1.2.zip (world)], [file/spectator conduit power v1.1.2.zip (world)], [file/spectator night vision v1.1.2.zip (world)], [file/timber v2.1.4.zip (world)], [file/track raw statistics v1.5.2.zip (world)], [file/track statistics v1.1.3.zip (world)], [file/unlock all recipes v2.0.3.zip (world)], [file/villager death messages v1.2.3.zip (world)], [file/villager workstation highlights v1.1.2.zip (world)], [file/xp management v1.1.2.zip (world)], [file/coordinates hud v1.2.2.zip (world)], [file/datapack (world)], [file/anti creeper grief v1.1.2.zip (world)], [file/anti ghast grief v1.1.2.zip (world)], [file/armored elytra v1.0.5.zip (world)], [file/incendium-v5-0-2a.zip (world)], [file/real time clock v1.1.2.zip (world)], [file/terralith-v2-1-1a.zip (world)], [file/thunder shrine v1.1.2.zip (world)], [file/wandering trades v1.5.1.zip (world)]
Important: [vanilla (built-in)], [file/incendium-v5-0-2a.zip (world)]

### Paper version

[13:12:50 INFO]: This server is running Paper version git-Paper-225 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 1d7a6a0)
You are running the latest version
Previous version: git-Paper-224 (MC: 1.18.2)

**Comment by electronicboy** [comment]
which pack? have you tested in vanilla as iirc there was some oddball issues there too, at least in the past

**Comment by ghost** [comment]
> which pack? have you tested in vanilla as iirc there was some oddball issues there too, at least in the past

Judging from the list, Incendium Modifies the nether and adds new biomes / changes, which is what he's referring to.

**Comment by jpenilla** [comment]
duplicate https://github.com/PaperMC/Paper/issues/6880
