### ISSUE TITLE
PR #6592 TabCompleteEvent not being called

### ISSUE THREAD

**Issue by TauCu** [PaperSpigot/Paper#7563]
### Expected behavior

TabCompleteEvent to be called when suggesting root nodes, too.

### Observed/Actual behavior

TabCompleteEvent is not called.

### Steps/models to reproduce

1) create a listener on TabCompleteEvent that prints when invoked
2) as the client, send a ServerboundCommandSuggestionPacket to the server for root nodes

### Plugin and Datapack List

[18:02:39 INFO]: Plugins (2): CommandBlocker, LuckPerms

[18:02:46 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[18:02:46 INFO]: There are no more data packs available

### Paper version

[17:45:51 INFO]: Checking version, please wait...
[17:45:53 INFO]: This server is running Paper version git-Paper-216 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 30cb7d0)
You are running the latest version
Previous version: git-Paper-234 (MC: 1.18.2)

### Other

This issue is in relation to the patches in PR #6592

**Comment by electronicboy** [comment]
the client tells us nothing when it's trying to complete a root node, so we have literally 0 means of handling this on the server

**Comment by TauCu** [comment]
Then how would one prevent specific commands from being sent to a client?

**Comment by electronicboy** [comment]
by defining perms properly for commands so that the server doesn't send them using the filtering logic already built into the server, or using the command definition event and removing them there

**Comment by VaxPex** [comment]
by being a gay

**Comment by TauCu** [comment]
Many closed source plugins lack good verbosity when it comes to commands and many of them have many alias for a specific command cluttering the commands on your server. Due to the popularity of creating commands programmatically you can't just edit the plugin.yml anymore.

I can't seem to find a CommandDefinitionEvent and wouldn't this remove the command entirely for all users, including people you may wish to use/see this command?

Perhaps it would be a better idea to upgrade the PlayerCommandSendEvent and respect changes made there?

**Comment by Machine-Maker** [comment]
This is what cat was talking about I think. https://github.com/PaperMC/Paper/blob/master/Paper-MojangAPI/src/main/java/com/destroystokyo/paper/event/brigadier/AsyncPlayerSendCommandsEvent.java It’s fired when the command tree is sent to one player, and you can modify what is sent.
