### ISSUE TITLE
Custom world generator string problem

### ISSUE THREAD

**Issue by schneidermr** [PaperSpigot/Paper#7565]
### Expected behavior

If I use a custom generator string by world generation, the server should use it.

### Observed/Actual behavior

It looks like the new version of the paper skips the custom world generator string. Everything working fine with the 1.18.1 version.

### Steps/models to reproduce

`new WorldCreator("demo").generatorSettings("{\"structures\": {\"structures\": {}}, \"layers\":[{\"block\":\"minecraft:bedrock\",\"height\":1},{\"block\":\"minecraft:dirt\",\"height\":48},{\"block\":\"minecraft:grass_block\",\"height\":1}],\"biome\":\"plains\"}")`

### Plugin and Datapack List

The same result without any plugins

### Paper version

paper-1.18.2-237

**Comment by SirYwell** [comment]
From the [Javadocs](https://papermc.io/javadocs/paper/1.18/org/bukkit/WorldCreator.html#generatorSettings(java.lang.String)):

> Currently only [WorldType.FLAT](https://papermc.io/javadocs/paper/1.18/org/bukkit/WorldType.html#FLAT) uses these settings [...]

The default WorldType is `NORMAL`, therefore it behaves as specified if you don't set the type to `FLAT`.

**Comment by schneidermr** [comment]
Then I wasn’t clear enough 🙂
The problem is, the server generates simply a basic flat land (1 grass, 2 dirt and 1 bedrock block) regardless my generator string

**Comment by SirYwell** [comment]
Then you should probably share all the relevant code. From what you've provided so far, everything works as expected.

**Comment by schneidermr** [comment]
`String WORLD_GENERATION_STRING = "{\"structures\": {\"structures\": {}}, \"layers\":[{\"block\":\"minecraft:bedrock\",\"height\":1},{\"block\":\"minecraft:dirt\",\"height\":48},{\"block\":\"minecraft:grass_block\",\"height\":1}],\"biome\":\"plains\"}";

WorldCreator creator = new WorldCreator(worldName);

creator.environment(World.Environment.NORMAL);

creator.generateStructures(false);

creator.type(WorldType.FLAT);

creator.generatorSettings(RegionGenerator.WORLD_GENERATION_STRING);

World result = creator.createWorld();`


Please be noted "**Everything working fine with the 1.18.1 version.**"

**Comment by SirYwell** [comment]
With that code, I get an error in console: `[15:52:36 ERROR]: Not a registry ops`. This is most likely an issue with Spigot too and should probably be fixed there.

**Comment by electronicboy** [comment]
Not a registry ops generally implies that the generation settings have changed between versions and thus that info needs updating

**Comment by schneidermr** [comment]
I hope so but I don’t understand how does it work with the previous build (1.18.1). Based on semantic versioning the new one contains only patch.

**Comment by electronicboy** [comment]
Mojang doesn't follow sementic versioning with their data schemas.

**Comment by Machine-Maker** [comment]
I believe what you want to do, is change the "structures.structures" empty object, to an empty array called "structures_override". But as said before, mojang does not follow semantic versioning with data schemas. This was changed in 1.18.2-pre1.

**Comment by Machine-Maker** [comment]
Ok, so I looked some more into it, and this is [actually a vanilla issue](https://bugs.mojang.com/browse/MC-195468), that re-appeared recently I think.
