### ISSUE TITLE
JFR command not working

### ISSUE THREAD

**Issue by BloodEko** [PaperSpigot/Paper#7566]
### Expected behavior

The ``/jfr start`` command was added in minecraft 1.18 and should start profiling.

### Observed/Actual behavior

It says ``Failed to start JFR profiling`` and prints in the console ``Could not find default flight recorder config at /flightrecorder-config.jfc`` While on spigot it works without problems. 

It seems that the ``flightrecorder-config.jfc`` is a required ressource at the classpath. But which is missing in the generated ``server/versions/1.18.2/paper.jar`` which can be observed with 7zip.

### Steps/models to reproduce

Use the ``/jfr start`` command.

### Plugin and Datapack List

None.

### Paper version

This server is running Paper version git-Paper-237 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: b55ba19)

### Other

The issue exists on both 1.18.1 and 1.18.2.

**Comment by NoahvdAa** [comment]
Issue should be reopened since paperweight hasn't been updated yet.

**Comment by lynxplay** [comment]
Will be resolved once paper updates to paperweight 1.3.6 (and that is released)

**Comment by jpenilla** [comment]
https://github.com/PaperMC/Paper/commit/c449f6a1f712b81b50e250a2e258ef3e37fd6b9b
