### ISSUE TITLE
suggest /restart cannot run in command blocks

### ISSUE THREAD

**Issue by HowardZHY** [PaperSpigot/Paper#7567]
### Is your feature request related to a problem?

Hacker clients can get written cmd-block with /restart in creative mod and activate it.
And the server will restart !

### Describe the solution you'd like.

permission level of /restart should be 4 (op and console only)

### Describe alternatives you've considered.

idk

**Comment by underscore11code** [comment]
If hackers can get sufficient permissions to place & modify command blocks, you have bigger problems than them restarting your server.

**Comment by electronicboy** [comment]
The server already prevents normies from placing command blocks in the world, you can also just use a a command block override in commands.yml to point restart, etc, to an invalid command or whatever

**Comment by HowardZHY** [comment]
https://minecraft.fandom.com/wiki/Permission_level
if /restart can even run with permit level 1 OP (change in ops.json) , that MUST be an PROBLEM

**Comment by HowardZHY** [comment]
The permission level of CMD-Block is 2 ,and /restart is as fatal as level 4 cmd /stop

**Comment by kennytv** [comment]
If a hacker can place *and activate* a command block with written text, you have *a lot* more problems than just them stopping your server. This won't happen unless you somehow open yourself up to be vulnerable and is otherwise not an issue

**Comment by electronicboy** [comment]
craftbukkit doesn't really care so much about op levels given that a fully fledged perm system was added long before mojang added their own op level system, and so many things just blatantly disregard that entire system, commands registered in bukkit, .e.g /restart, are NOT given op levels, as that mechanism is not really exposed in the API at all last I checked, and so nothin cares to look;and, what's more important, the op level or the perm?

This would basically be a complex issue to solve in the scheme of things that would break as much as it fixed, it's 100% on you to secure your server and restrict the utilisation of things on the server that you don't want people doing. You can't open up a security hole and then expect us to try to mitigate it based around your own false understanding of how much of this works.
