### ISSUE TITLE
Whenever I log out in creative and log back in I get put in survival

### ISSUE THREAD

**Issue by joejoe135791** [PaperSpigot/Paper#7571]
### Expected behavior

Log out in creative, log back in and still in creative mode

### Observed/Actual behavior

I log out in creative, log back in and I'm in survival

### Steps/models to reproduce

Logging out of the server and logging back in

### Plugin and Datapack List

Aurelium skills beta 1.2.10
Core protect 20.4
Dungeons xl 0.18 pre-02
Floodgate-spigot
Geyser-spigot
Gwarp
Items xl 1.0.3
Kumandras economy
Mcmmo
Multiverse core 4.3.1
Protocol lib
Spigot ping 3.0
Themis 0.12.2
Vault
World edit 7.2.10

### Paper version

Paper version 1.18.2-237

**Comment by NoahvdAa** [comment]
I'm 99% sure this is a feature of MultiVerse, try to reproduce without it

EDIT: Also make sure `force-gamemode` is set to false in server.properties

**Comment by joejoe135791** [comment]
> I'm 99% sure this is a feature of MultiVerse, try to reproduce without it

It could be but this all happened after I updated my paper version to 1.18.2, multiverse core had worked just fine previously, I can try it though

Edit: I tried removing multiverse core and it didn't do anything, force gamemode is disabled

**Comment by joejoe135791** [comment]
> I'm 99% sure this is a feature of MultiVerse, try to reproduce without it
> 
> EDIT: Also make sure `force-gamemode` is set to false in server.properties

I made sure that force gamemode is disabled, it was not multiverse core as I removed it and its still happening

**Comment by joejoe135791** [comment]
I am going to reset the server.properties file and hope it fixes itself

**Comment by joejoe135791** [comment]
It was an error with the server.properties file, I reset the properties file and it's working as expected
