### ISSUE TITLE
allow-nether  not working

### ISSUE THREAD

**Issue by Hajatoby** [PaperSpigot/Paper#7572]
### Expected behavior

Hey :D Is it normal that the function "allow-nether false" in server.properties doesn't work? I'm using the latest build of 1.18.2 and it doesn't work there... regardless of whether it's true or false, the nether remains activated 

### Observed/Actual behavior

The function does not work. You can't turn off the nether 

### Steps/models to reproduce

Server.properties
allow-nether false

### Plugin and Datapack List

![Screenshot_4](https://user-images.githubusercontent.com/50121920/157747303-06877cd4-4746-47ae-97ba-5b412747ed28.png)
![Screenshot_5](https://user-images.githubusercontent.com/50121920/157747310-2e2f2498-d94e-4e61-b643-5c6856a381de.png)

### Paper version

This server is running Paper version git-Paper-237 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: b55ba19)

**Comment by snoozz** [comment]
I have exactly the same problem, but in version 1.18.1
The same applies to allow end. Also has no function

**Comment by lynxplay** [comment]
>  Ich habe genau das gleiche Problem, allerdings in der Version 1.18.1
Gleiches gilt für allow-end. Hat ebenfalls keine Funktion

Quick heads up, this issue tracker is in English :+1:

**Comment by Machine-Maker** [comment]
I mean, I just tried it right now, and I step into a nether portal, and don't go to the nether. The `/execute in` command also doesn't list `mincraft:the_nether` as an option.

Replicate this without plugins, and be more specific about what you expect to happen. What does "turn off the nether" look like to you? what does "the nether remains activated" mean?

**Comment by Hajatoby** [comment]
Well, Allow-nether specifies that you can decide whether the nether should be allowed or not. And no matter if true or false it doesn't matter if true or false.
This also occurs on my test server without a plugin.

As someone else has already written, the problem also occurs with the 1.18.1 version.

**Comment by Hajatoby** [comment]
If you set it to false, nether portals, among other things, should no longer have any function and so on

**Comment by Machine-Maker** [comment]
I've set allow-nether to false, and nether portals don't work. They still light and everything, but you can't go through them. Try running the `/execute in minecraft:the_nether run tp 0 50 0` command and see if it works.

I'm literally just starting a new server, stopping it, setting `allow-nether` in server.properties to false, then starting the server again, and that command doesn't work.

If you delete or move your `world_nether` folder from the server root, it doesn't regenerate when you start the server again either. So I'm not sure how the nether could be "activated" if the literal region files that define the nether aren't needed for the server to start.

**Comment by electronicboy** [comment]
the setting controls if the nether world loads or not, setting that to false, I can confirm that the only dimensions which loaded was the overworld and the end, do note that if you load a nether world after that it may in fact cause it to link up given how the logic works there from what I recall

**Comment by Hajatoby** [comment]
I noticed it because I don't want portals to be created or spawned randomly because we have a citybuild server with PlotSqaured.

So I would like to keep it short and sweet that the world Nether will remain but no more portals can be created or that they no longer have a function.

The above command works for me regardless of whether it is True or False

**Comment by electronicboy** [comment]
do you have a custom world which uses the nether dimension type?

**Comment by snoozz** [comment]
So I can only confirm what he says, I have the exact same problem. could it be because I updated the server from version 1.16.5 to version 1.18.1? Should I/we delete the server.propertys and have them recreated?

**Comment by Hajatoby** [comment]
No, I have the standard Nether world, i.e. the world created by paper.
world_nether

**Comment by Machine-Maker** [comment]
> The above command works for me regardless of whether it is True or False

On a server with 0 plugins, and 0 data packs?

**Comment by Hajatoby** [comment]
Yes!

**Comment by electronicboy** [comment]
recreating that file would have 0 effect if the setting is set properly, can you provide logs or something? cos, as I said, the thing determines if the nether world is loaded or not, test vanilla server here does infact not load the nether world

**Comment by Hajatoby** [comment]
I haven't tried whether the world is created or not.
Since I set it to false during operation, the portals no longer work.

I want players to be able to get into the nether but not through portals.

Is there possibly the possibility that in future Paper versions a function could be installed where you can deactivate portals separately? such as through multiverse?

**Comment by electronicboy** [comment]
You can already do that with plugins

**Comment by snoozz** [comment]
So I have a hard time with logs because I only updated my server yesterday and there are still too many errors in general because some plugins are still causing problems. If so, Toby would have to do that. I'm still in the middle of editing my server.

**Comment by Hajatoby** [comment]
I have now done this with Multiverse-Core but I think it would be easier if this could be added to Paper as many have had problems with the portals.
It would be just an idea or rather a wish of many users.

Would be great but doesn't have to happen :D

**Comment by electronicboy** [comment]
we already have enough "for for 10 people" config options, part of the goal of the API is that we let plugins deal with that stuff rather than having a 1k line config for paper

**Comment by Machine-Maker** [comment]
> Since I set it to false during operation, the portals no longer work

wait so it is working? `allow-nether` turns off loading of the dimension. And it works just fine on a brand new 1.18.2 server. Like electronicboy said, its up to a plugin if you want to have the world still loaded but disable nether portals.


EDIT: And lets be clear, you are restarting the server after changing `allow-nether`? not reloading, actually stopping and then restarting.

**Comment by snoozz** [comment]
It doesn't work for me either and I've restarted my server 10 times since then. But I know that it was definitely possible to switch off the portals, although that was a few versions earlier.

**Comment by snoozz** [comment]
And what I can also confirm is that it works on a newly created server without plugins. So if I set Allow-nether to false, you won't be teleported. Then it's probably a plugin

**Comment by electronicboy** [comment]
allow-nether prevents the nether from loading, if that's not working you'll need to check your plugins, etc

OPs issue appears to be resolved nor can we reproduce, closing
