### ISSUE TITLE
Read-only World

### ISSUE THREAD

**Issue by lizelive** [PaperSpigot/Paper#7577]
### Is your feature request related to a problem?

I want to host multiple copies using same world file, one writeable one not writeable.

### Describe the solution you'd like.

Allow opening world as read-only

### Describe alternatives you've considered.

File-system insanity to that send writes into the void.

**Comment by Chew** [comment]
This entails a lot, are you wanting just blocks to not move? Are you wanting all state to be frozen? Are you wanting entities frozen?

**Comment by electronicboy** [comment]
The amount of work for this for such a niche usecase is untenable to the project at this time, especially with the state of vanilla code for handling much of this stuff
