### ISSUE TITLE
Add a way to zombify villagers via the API

### ISSUE THREAD

**Issue by Kay313** [PaperSpigot/Paper#7578]
### Is your feature request related to a problem?

If you want a Villager e.g. if you click an item on the villager, the villager turns into a zombie villager.

### Describe the solution you'd like.

It would be good if there was a function like .setZombify(true or false)

### Describe alternatives you've considered.

I haven't found a way how to do this.

**Comment by Doc94** [comment]
The convert its like a new entity with shared data... then not sure about the method setZombify, maybe can be like Villager#zombify() and ZombieVillager#cure() (maybe with a paramter for who zombify or who cure if necesary)

**Comment by MiniDigger** [comment]
what makes this kinda meh is that they are separate entities, so calling these methods would kill the entity, which is really confusing to the user. a way around that could be returning the new entities.

**Comment by Doc94** [comment]
> what makes this kinda meh is that they are separate entities, so calling these methods would kill the entity, which is really confusing to the user. a way around that could be returning the new entities.

yeah this.. but not sure how can be better.. when check NMS the "code" for convert a Villager in Zombie is in the Zombie class. then maybe can help a static method for helper and use this in the Villager for convert...

**Comment by Doc94** [comment]
ok i forget ZombieVillager has a method for set the conversion time then the only left thing is the zombify method...

**Comment by Doc94** [comment]
Method added in Upstream: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/fc460d1bb8d5f2bc9ff07dad1b7b402eed06d7c4

**Comment by Machine-Maker** [comment]
whoops, not in paper yet. close when that happens.

**Comment by NoahvdAa** [comment]
Can be closed, upstream was updated in 1cfd363.

**Comment by lynxplay** [comment]
Resolved by 1cfd363d326102b77b278c9ff96968794ac1f8a0
