### ISSUE TITLE
randomly appeard invisible armorstand entity blocks building

### ISSUE THREAD

**Issue by Matze1224** [PaperSpigot/Paper#7583]
### Expected behavior

Blocks can be placed everywhere.

### Observed/Actual behavior

There are very few places where you can't place a block. If you point on it, the block below isn't marked and you can attack it like any mob with the hitmarker and sound. You will also get problems if your head is inside the "air" where you can't do something because your head is inside the entity.

Behavior keeps the same if you load the world via singleplayer. No hitboxes are shown.

### Steps/models to reproduce

Player who discovered this said he was building there, removing, building and after some time he wasn't able to place a block there anymore. Appears to happen "randomly".

To see the problem, I've uploaded the world: [testworld_server_2022-03-12_papermc-bug.zip](https://github.com/PaperMC/Paper/files/8237808/testworld_server_2022-03-12_papermc-bug.zip) (removed unnecessary regions to trim overworld size from 2,2GB to ~10MB)

There are following known positions with this problem in the given world:
431 / 91 / 645    (*you see the gap in the wall*)
433 / 109 / 639    (*on top of the roof of the tower*)

### Plugin and Datapack List

```
> plugins
[15:19:26 INFO]: Plugins (4): Harbor, MatrixSpigotBridge, ServerBackup, UltimateChairs
> datapack list
[15:19:34 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[15:19:34 INFO]: There are no more data packs available
```

The [UltimateChairs](https://www.spigotmc.org/resources/ultimatechairs-1-8-1-16-1-17-1-18.80434/)-version at the time was 1.4.2, which [had an known bug](https://www.spigotmc.org/threads/ultimatechairs-1-8-1-16-1-17-1-18.446472/page-4#post-4379254) with 1.18.2 paper versions. It's now updated to the fixed 1.4.3.

### Paper version

```
This server is running Paper version git-Paper-241 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: ea1efef)
You are running the latest version
Previous version: git-Paper-237 (MC: 1.18.2)
```

**Problem occurred at the "previous version" in the text; updated as a counter-messure.**

### Other

I've mitigated the issue by running an NBT editor for this world (I've used [NBTExplorer](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac)), going to `entities/r.0.1.mca` - `Chunk [26, 8]` and deleting both entities which appears to be invisible:

![overview](https://user-images.githubusercontent.com/37954743/158022749-14f80e91-e177-467a-a83b-972beb25cb33.png)
![detailed](https://user-images.githubusercontent.com/37954743/158022725-62959faa-2f0e-4543-a260-e8a3b41e286c.png)

I've updated paper and the troubling UltimativeChairs plugins (fix wasn't available at the time of occurrence) to the newest version and will remove these armorstand entities manually. I could happened because of the UltimativeChairs bug which I hope so. I keep my head up if this happens again.

For me, I'm happy if it doesn't happen again (which we will see), but wanted to let you know about this if this might be a more general problem. I would suspect the UltimateChair bug first - but happy to be proven wrong.

**Comment by lynxplay** [comment]
The server does not randomly spawn invisible armorstands. Like you theorized, this sounds very much like an ultimate chair bug as they might be using invisible armorstands to allow players to sit.
Unless you can replicate this without plugins, I will be closing this.
