### ISSUE TITLE
Color problem in console for Bukkit.broadcast()

### ISSUE THREAD

**Issue by x9nico** [PaperSpigot/Paper#7590]
### Expected behavior

It should set in colors my broadcasts. There, it don't want to set the colors in console

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/8091015/158067019-62145747-a52b-4e70-921f-f64acfab71a2.png)
![image](https://user-images.githubusercontent.com/8091015/158067052-90676e5b-b80c-4385-acaf-8c4684d76de2.png)

### Steps/models to reproduce

Make a broadcast in your code, like this:
`Bukkit.broadcast(Component.text(PvPBoxPlugin.getInstance().getConfig().getString("reset_map_announce").replace("&", "§").replace("{time}", Integer.toString(time))));
`

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/8091015/158067078-8003f95a-b248-4044-bdaf-bdf3a2cbead9.png)
PvPBox is a custom plugin

### Paper version

[16:30:54 INFO]: This server is running Paper version git-Paper-247 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 1358d1e)
You are running the latest version
Previous version: git-Paper-232 (MC: 1.18.2)

### Other

It does that bug from I updated to build 247, it don't affect the 232.

_No response_

**Comment by NoahvdAa** [comment]
You should not mix adventure components and legacy formatting (§). Either deserialize your legacy messages using the [LegacyComponentSerializer](https://jd.adventure.kyori.net/text-serializer-legacy/4.9.1/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializer.html) (or use minimessage instead of legacy), or use the legacy method, [Bukkit#broadcastMessage](https://papermc.io/javadocs/paper/1.18/org/bukkit/Bukkit.html#broadcastMessage(java.lang.String)). This will cause the proper behaviour, as shown below:

```java
Bukkit.broadcast(Component.text("§cE")); // WRONG
Bukkit.broadcast(Component.text("E", NamedTextColor.RED));
Bukkit.broadcastMessage("§cE");
```
results in (e's without § are colored)
```
[17:11:36 INFO]: §cE
[17:11:36 INFO]: E
[17:11:36 INFO]: E
```

**Comment by x9nico** [comment]
> You should not mix adventure components and legacy formatting (§). Either deserialize your legacy messages using the [LegacyComponentSerializer](https://jd.adventure.kyori.net/text-serializer-legacy/4.9.1/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializer.html) (or use minimessage instead of legacy), or use the legacy method, [Bukkit#broadcastMessage](https://papermc.io/javadocs/paper/1.18/org/bukkit/Bukkit.html#broadcastMessage(java.lang.String)). This will cause the proper behaviour, as shown below:
> 
> ```java
> Bukkit.broadcast(Component.text("§cE")); // WRONG
> Bukkit.broadcast(Component.text("E", NamedTextColor.RED));
> Bukkit.broadcastMessage("§cE");
> ```
> 
> results in (e's without § are colored)
> 
> ```
> [17:11:36 INFO]: §cE
> [17:11:36 INFO]: E
> [17:11:36 INFO]: E
> ```

And how can I use NamedTextColor with the '&' ? It's in a config file for me :/

**Comment by electronicboy** [comment]
you use the legacy component serialiser to deserialise a legacy string into a component if you wanna have components, or there is minimessage for a modern "rich" representation of components

**Comment by NoahvdAa** [comment]
If you want to use legacy ampersands, the easiest solution would be to use the LegacyComponentSerializer like this:
```java
Bukkit.broadcast(LegacyComponentSerializer.legacyAmpersand().deserialize("&cMy message here"));
```
or, you could use minimessage instead:
```java
Bukkit.broadcast(MiniMessage.miniMessage().deserialize("<red>My message here"));
```

🥷 ninja'd by cat

**Comment by x9nico** [comment]
> If you want to use legacy ampersands, the easiest solution would be to use the LegacyComponentSerializer like this:
> 
> ```java
> Bukkit.broadcast(LegacyComponentSerializer.legacyAmpersand().deserialize("&cMy message here"));
> ```
> 
> or, you could use minimessage instead:
> 
> ```java
> Bukkit.broadcast(MiniMessage.miniMessage().deserialize("<red>My message here"));
> ```
> 
> 🥷 ninja'd by cat

It works. Thanks!
