### ISSUE TITLE
Console color 'fix' breaks console colors

### ISSUE THREAD

**Issue by tim-savage** [PaperSpigot/Paper#7596]
### Expected behavior

Colored text in console. Was working fine before build 244. I'm using Apple Terminal.app with xterm-256color emulation and solarized dark theme. No wrapper used, beyond a simple shell script. Tested by executing jar without script, and behavior is same, ie: no color just dimmed text.

Server is running on Ubuntu 20.04, up to date.

Java --version
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 17.0.2+8-Ubuntu-120.04, mixed mode, sharing)

### Observed/Actual behavior

Colored text now renders as dimmed text.

### Steps/models to reproduce

Launch paper in an Apple Terminal.app, observe output from plugins that have colored text in console. Warn level messages are colored, but nothing else, just dimmed text where colors used to be.

### Plugin and Datapack List

[18:08:22 INFO]: Plugins (17): Essentials, EssentialsGeoIP, HomeStar, LodeStar, LuckPerms, Multiverse-Core, ProClaim, RoadBlock, SavageDeathBan, SavageDeathChest, SavageDeathCompass, SavageGraveyards, spark, SpawnStar, Vault, WorldEdit, WorldGuard

### Paper version

> version
[18:11:03 INFO]: Checking version, please wait...
[18:11:03 INFO]: This server is running Paper version git-Paper-249 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: c8e49cc)
You are running the latest version
Previous version: git-Paper-248 (MC: 1.18.2)

### Other

Perhaps a config setting to allow admins to choose which version of color console rendering to use, as I assume this fix is working for some people, likely using a different terminal program than myself.

**Comment by Machine-Maker** [comment]
its not "plugins that have colored text in console". This plugin works just fine on build 249
<img width="573" alt="image" src="https://user-images.githubusercontent.com/15055071/158083579-078fecc2-a526-4d33-9c61-4ac9a0c3564d.png">

This is most likely a plugin issue, with plugins incorrectly using legacy color codes inside of loggers instead of sending them to the console command sender.

**Comment by tim-savage** [comment]
> its not "plugins that have colored text in console". This plugin works just fine on build 249
> <img alt="image" width="573" src="https://user-images.githubusercontent.com/15055071/158083579-078fecc2-a526-4d33-9c61-4ac9a0c3564d.png">

Super. I'm glad it's working for you. Are you using the same terminal emulator as me? Because this is what I see, for both plugin and server messages:
![Screen Shot 2022-03-13 at 6 22 16 PM](https://user-images.githubusercontent.com/1920234/158083657-95d5d2b5-dc83-46cb-9649-63e054511d6a.png)

**Comment by Machine-Maker** [comment]
Try toggling the `use-rgb-for-named-colors` setting in `paper.yml`

**Comment by tim-savage** [comment]
That did the trick, 
![Screen Shot 2022-03-13 at 6 30 15 PM](https://user-images.githubusercontent.com/1920234/158083959-2b91b151-fcde-4916-86f6-c975c070c3f2.png)

Setting:
use-rgb-for-named-colors: false

Thank you!

**Comment by Machine-Maker** [comment]
> Setting:
use-rgb-for-named-colors: false
Thank you!

yeah, looks like the default Terminal.app doesn't support rgb colors. My b for assuming it was a plugins fault. That same change did expose bad plugins doing the wrong thing with colors in the console.

**Comment by tim-savage** [comment]
I know many recommend iTerm over Apple's Terminal, but it just doesn't feel right for me, and I prefer Terminal, despite a few shortcomings. I'm just glad there's a setting to change paper's behavior. I glanced at the docs before reporting, but must have missed this setting.

**Comment by mrfloris** [comment]
> I know many recommend iTerm over Apple's Terminal, but it just doesn't feel right for me, and I prefer Terminal, despite a few shortcomings. I'm just glad there's a setting to change paper's behavior. I glanced at the docs before reporting, but must have missed this setting.

I use iTerm, and it's always been a bit flaky with paper + hex colors in console, but the 246 build really improved on everything, I just upgraded to 249 and it's all messed up again. Missing colors, randomly underlines, wrong type of colors from the looks of it even in certain plugin onEnable msgs. 
<img width="677" alt="Screenshot 2022-03-14 at 15 44 27" src="https://user-images.githubusercontent.com/28841349/158196172-3a78dc9e-74ee-4f29-b48b-a4011e4c9eab.png">

Going back to 247 makes it all 'pretty' again. 
macOS Catalina with iTerm

Terminal.app, build 249 ~ better, but randomly things are unlined as well. 
<img width="431" alt="Screenshot 2022-03-14 at 15 45 40" src="https://user-images.githubusercontent.com/28841349/158196462-3b58fc81-a876-41ca-857e-6593e8a42c6a.png">

**Comment by tim-savage** [comment]
> I use iTerm, and it's always been a bit flaky with paper + hex colors in console, but the 246 build really improved on everything, I just upgraded to 249 and it's all messed up again. Missing colors, randomly underlines, wrong type of colors from the looks of it even in certain plugin onEnable msgs.
> 
> Going back to 247 makes it all 'pretty' again. macOS Catalina with iTerm
> 
> Terminal.app, build 249 ~ better, but randomly things are unlined as well.

That does look odd. Check that you've got terminfo declared as xterm-256color, and text encoding UTF-8. I'm going to send you an email so we can take this conversation out of the issue tracker, and see if we can solve your issue.

**Comment by Brokkonaut** [comment]
I can confirm the issue with colors, no colors in console on latest debian. "use-rgb-for-named-colors: false" fixes colors in some messages, but not in all

**Comment by Dymeth** [comment]
Seems like this issue should be reopened.

Actual for
`Linux version 5.4.0-66-generic (buildd@lgw01-amd64-039) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021`
with
`Paper version git-Paper-265 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 993f828)`

This issue affects two things:
1) Showing color codes like `§3` as simple text for some plugins:
`[HeadDatabase] §bUsing §3"ru_Ru.lang" §btranslated by §6MenaR`
2) Wrong colors of messages (including Bukkit/Spigot/Paper messages):
![image](https://user-images.githubusercontent.com/21080646/159177067-cc98d1c6-c2e0-4ab2-ab02-6f02f20ad43c.png)

Moreover, i was unable to test the `use-rgb-for-named-colors: false` parameter from `paper.yml`:
1) It's missing from paper.yml generated by default 
2) Not sure what config section this parameter should be. Tried root section and `settings` section - ineffectually

**Comment by Chew** [comment]
I was unintentionally able to reproduce this myself, all colors seemed fine except for when I ran `/plugins`. Went from 1.17.1 to 1.18.2.

**Comment by Machine-Maker** [comment]
#### Addressing problem 1
Plugins which have message that contain the `§` character are most likely incorrectly using those legacy section color codes inside a **Logger** which is an unsupported use (Loggers should log exactly what you send them, not try to parse some obscure color codes). You should be able to just send legacy colors to the ConsoleCommandSender if you want to send colors to the console (but pls use components).

#### Addressing problem 2

The setting is `use-rgb-for-named-text-colors` and it is there in the default paper.yml. Its full path is `settings.loggers.use-rgb-for-named-text-colors`. If that doesn't fix that grayed out text, let us know.

**Comment by Dymeth** [comment]
> #### Addressing problem 1
> Plugins which have message that contain the `§` character are most likely incorrectly using those legacy section color codes inside a **Logger** which is an unsupported use (Loggers should log exactly what you send them, not try to parse some obscure color codes). You should be able to just send legacy colors to the ConsoleCommandSender if you want to send colors to the console (but pls use components).
> 
> #### Addressing problem 2
> The setting is `use-rgb-for-named-text-colors` and it is there in the default paper.yml. Its full path is `settings.loggers.use-rgb-for-named-text-colors`. If that doesn't fix that grayed out text, let us know.

Thank you, `use-rgb-for-named-text-colors: false` solved second problem.
For the first problem, I will contact the developers of the problematic plugins
