### ISSUE TITLE
Hello, this is a thread relating to TNT duping and allow-piston-duplication in config and how there should be 3 different versions of this feature.

### ISSUE THREAD

**Issue by GlitchTime** [PaperSpigot/Paper#7597]
### Is your feature request related to a problem?

In 1.15.2, build #358 the feature allow-piston-duplication was added. Many servers still use this patch, however, some might want to only enable TNT duping or carpet duping instead of them all.

### Describe the solution you'd like.

I would like the Paper Devs to add 3 different versions of this feature for the duplication of TNT, carpets and rails separately each one having it's own config.

### Describe alternatives you've considered.

I have no real alternatives to this problem.

### Other

![image](https://user-images.githubusercontent.com/101536350/158094081-7a3d3919-17a5-4b3c-b5ad-47c91452cc01.png)

**Comment by electronicboy** [comment]
this has been brought up a few times, we generally have 0 interest in investing any time into those options, hence the unsupported aspect
