### ISSUE TITLE
Cauldrons not filling from rain

### ISSUE THREAD

**Issue by p2r3** [PaperSpigot/Paper#7605]
### Expected behavior

While it's raining, a cauldron is expected to slowly fill up as long as nothing's obstructing it. In a full real-life day, at _least_ a single full cauldron is expected.

### Observed/Actual behavior

I ran a skyblock world with two cauldrons in an otherwise empty chunk, with a player loading said chunks for over 48 real-life hours. Both cauldrons remained dry the entire time. Gamerule randomTickSpeed was set to 15.

### Steps/models to reproduce

Create an empty singleplayer world using a custom flat world preset with only 1 layer of air. Copy this world to a Paper server, and place a cauldron at Y=128 in an otherwise empty chunk. No matter how long you wait, the cauldron will remain dry.

### Plugin and Datapack List

Plugins:
- Dynmap (https://www.spigotmc.org/resources/dynmap%C2%AE.274/)
- ProtectTheDirt (https://github.com/cosrnic/ProtectTheDirt)

Datapacks:
- `vanilla` (built-in)
- `file/bukkit` (world)

### Paper version

This server is running Paper version git-Paper-235 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e0b3f3f)
You are 15 version(s) behind
Download the new version at: https://papermc.io/downloads

**Comment by aurorasmiles** [comment]
Height doesn't seem to matter, I was able to replicate that on build 250 as well.
Works fine on Spigot

**Comment by lynxplay** [comment]
Also able to replicate this. For more details on the cause of this, see #7606
