### ISSUE TITLE
Item amount bug

### ISSUE THREAD

**Issue by andreasdc** [PaperSpigot/Paper#7607]
### Expected behavior

Amount of itemstack stay the same.

### Observed/Actual behavior

Itemstack amounts are getting smaller.

### Steps/models to reproduce

Source code:

public class Test extends JavaPlugin implements Listener {
    
    private ItemStack item;
    
    public void onEnable() {
        Bukkit.getPluginManager().registerEvents(this, this);
        item = new ItemStack(Material.STONE, 64);
    }
    
    @EventHandler
    public void on(PlayerJoinEvent e) {
        e.getPlayer().getInventory().addItem(item);
    }
    
    @EventHandler
    public void on(PlayerCommandPreprocessEvent e) {
        e.getPlayer().getInventory().addItem(item);
    }

}

1. Join the server.
2. Given item (stone) split to couple items.
3. Execute any command.
4. Original item will have smaller amount.

### Plugin and Datapack List

Test plugin

### Paper version

 This server is running Paper version git-Paper-252 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 2d3e8f7)

**Comment by electronicboy** [comment]
unsupported version

**Comment by andreasdc** [comment]
> unsupported version

 This server is running Paper version git-Paper-252 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 2d3e8f7)
You are running the latest version

Bug is still on the newest version too.

**Comment by electronicboy** [comment]
Not really sure how much this is a bug, this is 100% the expected behavior internally ignoring some of the potential item conversions, clone the stack before you give it to them

**Comment by andreasdc** [comment]
> Not really sure how much this is a bug, this is 100% the expected behavior internally ignoring some of the potential item conversions, clone the stack before you give it to them

All right 😎
