### ISSUE TITLE
Incorrect item frame position

### ISSUE THREAD

**Issue by Kapitowa** [PaperSpigot/Paper#7608]
### Expected behavior

Work of plugin BoardGames on spigot 1.18.2 (correct item frame position)
![image](https://user-images.githubusercontent.com/62211966/158487305-d723f3b8-3026-46ae-a377-136dab967c5d.png)

This server is running CraftBukkit version 3462-Spigot-ffceeae-2c47af0 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)
You are running the latest version

### Observed/Actual behavior

Work of plugin BoardGames on paper 1.18.2
![image](https://user-images.githubusercontent.com/62211966/158487449-43da8218-6ead-4132-9073-a1b080dc3eb8.png)

### Steps/models to reproduce

Install plugin and place board with item frames and maps.

### Plugin and Datapack List

Plugins (43): AdminBank, AdvancedChests, AntiCooldown, BattlePass, BoardGames, Chatty, ChestSort, CMI, CMIEInjector*, CMILib, DailyShop, DeluxeCoinflip, DynamicShop, ExoticGarden, ExtraGear, LimitCreative, LuckPerms, MoneyHunters, Multiverse-Core, NexEngine, PlaceholderAPI, PlayerAuctions, PlugMan, ProtocolLib, RealisticSeasons, ShopGUIPlus, SkinsRestorer, Slimefun, spark, TabTPS, TokenManager, TradePlus, TubeTils, Vault, ViaBackwards, ViaVersion, ViewDistanceTweaks, VoidGen, WGExtender, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags

### Paper version

This server is running Paper version git-Paper-252 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 2d3e8f7)
You are running the latest version

**Comment by electronicboy** [comment]
We can't provide support around premium plugins
