### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by vapid-asd** [PaperSpigot/Paper#7619]
### Expected behavior

Server is crashing when i change gamemodes idk why

### Observed/Actual behavior

Server is crashing when i change gamemodes idk why

### Steps/models to reproduce

Server is crashing when i change gamemodes idk why

### Plugin and Datapack List

Server is crashing when i change gamemodes idk why

### Paper version

Server is crashing when i change gamemodes idk why

### Other

Server is crashing when i change gamemodes idk why

**Comment by lynxplay** [comment]
Please open a proper issue with reproduction steps, plugin lists, paper version and the error from the servers logs.
