### ISSUE TITLE
Moving/splitting items in inventory changes NBT data

### ISSUE THREAD

**Issue by BakiDance** [PaperSpigot/Paper#7631]
### Expected behavior

Moving an item with custom NBT in your inventory, splitting the stack, etc, should still allow it to re-stack to the original item amount. Simply moving the item or splitting the stack shouldn't change any properties of the item.

### Observed/Actual behavior

Spawning an item with custom NBT causes the item to no longer stack with itself if the item is moved from its original slot, or the stack is split. 

### Steps/models to reproduce

Reference commands: Give/Clear
```
minecraft:give @p blaze_powder{CustomModelData:24,AttributeModifiers:[{AttributeName:"generic.movement_speed",Amount:0.04,Name:"generic.movement_speed",UUID:[I;-122215,35359,134753,-70718]}],display:{Name:'[{"text":"[ ","italic":false,"color":"#fc9538"},{"text":"ᴇꜱꜱᴇɴᴄᴇ ᴏꜰ ᴛᴏᴘᴀᴢ","color":"#fac410"},{"text":" ]"}]',Lore:['[{"text":"Description:","italic":false,"color":"#fac410"}]','[{"text":" • ","italic":false,"color":"#fac410","bold":true},{"text":"An ancient relic that","color":"#ffea9b","bold":false},{"text":"","color":"dark_purple","bold":false}]','[{"text":" • ","italic":false,"color":"#fac410","bold":true},{"text":"provides the wielder","color":"#ffea9b","bold":false},{"text":"","color":"dark_purple","bold":false}]','[{"text":" • ","italic":false,"color":"#fac410","bold":true},{"text":"with Topaz powers.","color":"#ffea9b","bold":false},{"text":"","color":"dark_purple"}]','[{"text":"","italic":false,"color":"dark_purple"}]','[{"text":"ʀᴀʀᴇ ᴄʀᴀꜰᴛɪɴɢ ɪɴɢʀᴇᴅɪᴇɴᴛ","italic":true,"color":"gray"}]']},Enchantments:[{id:fire_aspect,lvl:5}],HideFlags:3} 10
```

```
minecraft:clear @p blaze_powder{CustomModelData:24,AttributeModifiers:[{AttributeName:"generic.movement_speed",Amount:0.04,Name:"generic.movement_speed",UUID:[I;-122215,35359,134753,-70718]}],display:{Name:'[{"text":"[ ","italic":false,"color":"#fc9538"},{"text":"ᴇꜱꜱᴇɴᴄᴇ ᴏꜰ ᴛᴏᴘᴀᴢ","color":"#fac410"},{"text":" ]"}]',Lore:['[{"text":"Description:","italic":false,"color":"#fac410"}]','[{"text":" • ","italic":false,"color":"#fac410","bold":true},{"text":"An ancient relic that","color":"#ffea9b","bold":false},{"text":"","color":"dark_purple","bold":false}]','[{"text":" • ","italic":false,"color":"#fac410","bold":true},{"text":"provides the wielder","color":"#ffea9b","bold":false},{"text":"","color":"dark_purple","bold":false}]','[{"text":" • ","italic":false,"color":"#fac410","bold":true},{"text":"with Topaz powers.","color":"#ffea9b","bold":false},{"text":"","color":"dark_purple"}]','[{"text":"","italic":false,"color":"dark_purple"}]','[{"text":"ʀᴀʀᴇ ᴄʀᴀꜰᴛɪɴɢ ɪɴɢʀᴇᴅɪᴇɴᴛ","italic":true,"color":"gray"}]']},Enchantments:[{id:fire_aspect,lvl:5}],HideFlags:3} 10
```

----

1. Run the give command for the item.
2. Move the item stack to a new slot.
3. Run the give command again. Notice how the *old* stack will no longer stack with the new stack.

Alternatively:
1. Run the give command for the item.
2. Move the item stack to a new slot.
3. Run the give command again. Like the previous steps, this will create two stacks that should be identical, but aren't. Without moving any items, run the clear command twice. The command will only succeed on the stack that was not moved.

### Plugin and Datapack List

Plugins: None

Datapacks (default): [vanilla (built-in)], [file/bukkit (world)]

### Paper version

[18:18:03 INFO]: This server is running Paper version git-Paper-264 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: a686ff5)
You are running the latest version
Previous version: git-Paper-216 (MC: 1.18.1)

### Other

I tested this with the same steps in vanilla singleplayer and was unable to reproduce this issue.

I tested this on a different server running with essentials, and while the bug is present there, too, similar items generated with Essential's give command format do not seem affected by this issue. 

Example:
```
give * nether_brick 16 name:&#4237d3[_&#6e5afaᴇꜱꜱᴇɴᴄᴇ_ᴏꜰ_ɪʀɪᴅɪᴜᴍ&#4237d3] lore:&#FDC65CDescription:&5|&#FDC65C_&l•&r_&#FFF1A5An_ancient_relic_that&5|&#FDC65C_&l•_&#FFF1A5provides_the_wielder|&#FDC65C_&l•_&#FFF1A5with_Iridium_powers.|&7&oʀᴀʀᴇ_ᴄʀᴀꜰᴛɪɴɢ_ɪɴɢʀᴇᴅɪᴇɴᴛ
      durability:1 itemflags:HIDE_ENCHANTS
```

In my testing, I believe the issue is due to item enchantments and attributes. I'm able to reproduce this with a much simpler command such as:

```
/give @p blaze_powder{display:{Name:'[{"text":"ᴇꜱꜱᴇɴᴄᴇ ᴏꜰ ɪʀɪᴅɪᴜᴍ","italic":false,"color":"#4237d3"}]',Lore:['[{"text":"This does a thing, if we\'re lucky!","italic":false}]']},Enchantments:[{id:unbreaking,lvl:1}],HideFlags:3} 1
``` 

Here's a video where I run through the list above, as well as some additional tests with the "simple" command:
 https://youtu.be/Tr-iumfwMfE

**Comment by Machine-Maker** [comment]
Can you give yourself the item, don't move it, select it in your hotbar, and run `/paper dumpitem`? Then do the same after you've moved it and it can't stack anymore. Then post both of those outputs here. They should print out in the console as well as in a message to your player.

**Comment by BakiDance** [comment]
Wow, I wish I knew about this command sooner. Here's the output using this command as the reference:
```
/minecraft:give @p blaze_powder{display:{Name:'[{"text":"ᴇꜱꜱᴇɴᴄᴇ ᴏꜰ ɪʀɪᴅɪᴜᴍ","italic":false,"color":"#4237d3"}]',Lore:['[{"text":"This does a thing, if we\'re lucky!","italic":false}]']},Enchantments:[{id:unbreaking,lvl:1}],HideFlags:3} 1
```

Without moving the item:
```
{HideFlags: 3, display: {Name: '[{"text":"ᴇꜱꜱᴇɴᴄᴇ ᴏꜰ ɪʀɪᴅɪᴜᴍ","italic":false,"color":"#4237d3"}]', Lore: ['[{"text":"This does a thing, if we\'re lucky!","italic":false}]']}, Enchantments: [{id: "unbreaking", lvl: 1}]}
```
After moving the item:
```
{display: {Name: '[{"text":"ᴇꜱꜱᴇɴᴄᴇ ᴏꜰ ɪʀɪᴅɪᴜᴍ","italic":false,"color":"#4237d3"}]', Lore: ['[{"text":"This does a thing, if we\'re lucky!","italic":false}]']}, HideFlags: 3, Enchantments: [{id: "minecraft:unbreaking", lvl: 1s}]}
```

**Comment by Machine-Maker** [comment]
Can you then do one more after generating it via essentials? without moving the stack.

It looks like its just re-ordering the nbt tags, so the item isn't actually different, it just won't stack cause nbt compound key order matters.

**Comment by BakiDance** [comment]
Okay, I just tested it again with Essentials. This is with `use-nbt-serialization-in-createkit` set to false.

The command:
```
give * blaze_powder 1 name:&#4237D3ᴇꜱꜱᴇɴᴄᴇ_ᴏꜰ_ɪʀɪᴅɪᴜᴍ lore:This_does_a_thing,_if_we're_lucky!
      durability:1 itemflags:HIDE_ENCHANTS,HIDE_ATTRIBUTES
```

produces:

```
{display: {Name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#4237D3","text":"ᴇꜱꜱᴇɴᴄᴇ ᴏꜰ ɪʀɪᴅɪᴜᴍ"}],"text":""}', Lore: ['{"extra":[{"text":"This does a thing, if we\'re lucky!"}],"text":""}']}, HideFlags: 3, Enchantments: [{id: "minecraft:unbreaking", lvl: 1s}]}
```

However, there is no difference between the stacks when split. (This isn't true when use-nbt-serialization-in-createkit is set to true, but that isn't surprising here. )

**Comment by BakiDance** [comment]
Not that it's important to this issue, but just to add context: I was trying to create a simple command block thing that gave custom items, then removed them with the associated `minecraft:clear` command, and I couldn't figure out why the clear command failed occasionally when it worked in single player.

If I use the re-ordered NBT structure (after splitting the stack and running /paper dumpitem) for the give and clear commands, it works as expected after that. So, thank you! It's an extra step, but at least I can get this working now.

**Comment by Machine-Maker** [comment]
@BakiDance ok so the clear command doesn't care about the order, but it DOES care about the content. and you need to fully qualify everything, and make sure everything is the correct type. There were 3 issues with your original command
1. In the Enchantments tag, the `lvl` is a short (type of number), so you have to do `lvl: 5s` to make sure its a short tag.
2. Again in the Enchantments tag, the `id` needs to be `minecraft:fire_aspect`.
3. In the Attributes tag, the `AttributeName` needs to be `minecraft:generic.movement_speed`.

Once you make those 3 changes, the clear command will clear the moved item (then you just have to make those same changes to the NBT of the item in the give command, and the clear command will work on both)

**Comment by BakiDance** [comment]
Ah, I see. Thanks a ton!

**Comment by Machine-Maker** [comment]
I've marked this issue as accepted and "for: future" because the root cause of this issue has to do with how bukkit creates and then re-applies instances of ItemMeta and its not a simple fix at this moment. Leaving it open because we do plan on addressing this issue (and other issues ItemMeta has caused) in the future.

**Comment by lynxplay** [comment]
No longer applicable in 1.20.6 and above, as item data as now stored in data components 👍
