### ISSUE TITLE
EAR culls ticks for items pushed over ice, breaking fast sorters in the Nether when out of player activation misc range

### ISSUE THREAD

**Issue by petersv5** [PaperSpigot/Paper#7637]
### Expected behavior

Item stacks pushed by a piston + slime over blue ice take about 10 seconds to dissipate their momentum. This is frequently used to make high capacity sorters in the Nether by moving the items over hopper filters. 

### Observed/Actual behavior

Once an item stack is more than 10 seconds old and out of player misc activation range the items start behaving erratically with a significnat desync between server and client. The item stacks stop short of their normal range after the 10 seconds. 

### Steps/models to reproduce

I use a test path of 1 glazed terracotta and 33 blue ice blocks in a line with a piston+slime at the terracotta end. Bumping a stack of items with the piston+slime makes them reach the end if the stack is younger than the 10s EAR immunity or the entire track is within the player activation range (misc category). Otherwise the items reach far shorter.

### Plugin and Datapack List

Reproduced without any plugins

### Paper version

This server is running Paper version git-Paper-265 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 993f828)
You are running the latest version
Previous version: git-Paper-259 (MC: 1.18.2)

### Other

I can thing of two approaches off the top of my head: 
- Increase the immunity to tick culling after an EntityItem is pushed by a piston from 0.5s to 10s or make it configurable
- Increase immunity to tick culling when on ice. The default 0.5s is sufficient for non-slippery surfaces. This is more in line with how water streams are currently handled.

**Comment by petersv5** [comment]
I have a patch for the raising-immunity-after-piston-push, but can make either of these solutions, depending on guidance.

**Comment by MiniDigger** [comment]
thanks for looking into this, I think the second option makes more sense consistency wise

**Comment by petersv5** [comment]
I'll wait a day or two if there are any other opinions, then I'll send a patch. 

For the second option I plan to add a short amount of immunity if the entity has momentum and is on any of the ice types.

**Comment by petersv5** [comment]
Perhaps the best would be to reuse the logic from ItemEntity.tick(): 
   this.getDeltaMovement().horizontalDistanceSqr() > 9.999999747378752E-6D
I.e. the server keeps ticking the ItemEntity as long as it has momentum left?

**Comment by petersv5** [comment]
I created pr #7644 for the fix.

**Comment by petersv5** [comment]
I have verified that the bug was resolved after this push.
