### ISSUE TITLE
Chunks not loading 

### ISSUE THREAD

**Issue by andy01745** [PaperSpigot/Paper#7642]
### Expected behavior

Seeing the chunks loading.

### Observed/Actual behavior

Players not seeing chunks loading.  after restarting the server it seems to go away then a player finds another area having the same problem. I am not sure if this is a paper issue or a problem with Minecraft 1.18.1. I do not see any errors in the console and all players are seeing the same.  

### Steps/models to reproduce

![image](https://user-images.githubusercontent.com/84942293/159192581-4c1e209f-a8cb-49d0-8b43-8d0ad2c1f7d3.png)

Players where just flying the world and found that the chunks have stopped loading in some areas. 

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/84942293/159192671-f4051d17-0513-44c0-855e-950bbf43629e.png)
![image](https://user-images.githubusercontent.com/84942293/159192685-f078f831-515f-4534-b503-2a16417a4738.png)

I have sent screen shots of the Plugins and datapacks

### Paper version

1.18.1

![image](https://user-images.githubusercontent.com/84942293/159192713-85aa81b8-a85d-409e-a355-2045a2674ff0.png)

**Comment by linsaftw** [comment]
Having the same issue here.

**Comment by electronicboy** [comment]
1.18.1 is unsupported, and most issues like these are down to having the chunk-loading settings too low for the number of players, etc

**Comment by linsaftw** [comment]
> 1.18.1 is unsupported, and most issues like these are down to having the chunk-loading settings too low for the number of players, etc

This issue happens on 1.18.2 too. Sometimes chunks act weird and aren't sent to players.

**Comment by electronicboy** [comment]
then find an issue report for that version or create one, issue was created for an unsupported version for an issue which can often be mitigated by config as I said, so double check that too.

**Comment by andy01745** [comment]
turns out the issue is to do with the anti-xray in the paper config, after turning it off fixed the issue.
