### ISSUE TITLE
Invisible Player/Stuck on Loading Terrain.. after leaving server on death screen and trying to rejoin

### ISSUE THREAD

**Issue by Snewmy** [PaperSpigot/Paper#7647]
### Expected behavior

I think this is obvious here

### Observed/Actual behavior

When a player dies, and clicks titlescreen instead of respawn, or gets kicked, they attempt to join again and are stuck on "Loading terrain.." and invisible in-game, but says they logged in. Only way around it is to delete their player data completely so they can login again.

### Steps/models to reproduce

Player dies
Dont click respawn
leave server
attempt to join again

### Plugin and Datapack List

No plugins.

### Paper version

[18:31:14 INFO]: This server is running Paper version git-Paper-267 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e7d928a)
You are running the latest version
Previous version: git-Purpur-1596 (MC: 1.18.2)

### Other

Edit: only happens in modded clients, vanilla clients will allow you to rejoin to the respawn screen.

**Comment by Impactic48** [comment]
I have this same issue on my server where players are getting the "Loading Terrain" screen when joining the server after dying while teleporting or leaving after they died. 

I haven't been able to replicate it but that's what the players said what happened right before they encountered this issue. The only way to fix it is to delete the player data completely in the world file (Their UUID's DAT file) and then they can rejoin with no problems at all. (I'm using a 1.18.1 Purpur build 1566 but if this is happening on Paper then it's probably a downstream issue).

I will update this comment if I'm able to replicate it in my future testing.

**Comment by electronicboy** [comment]
This was an issue in pre release paper builds but was fixed, are you sure that these people are on *vanilla* clients?

**Comment by Snewmy** [comment]
> This was an issue in pre release paper builds but was fixed, are you sure that these people are on _vanilla_ clients?

Just tested now. It doesnt happen on vanilla clients apparently. Using Iris+Shaders it does.

**Comment by Malfrador** [comment]
Sodium issue for reference: https://github.com/CaffeineMC/sodium-fabric/issues/1225
Seems to be Paper only.

**Comment by kennytv** [comment]
There's this extremely cool mod that unborks it with Sodium https://modrinth.com/mod/forcecloseworldloadingscreen/ if you enable the extra option. 
@Impactic48 1.18.1 is not supported, your fix is to just update

**Comment by Impactic48** [comment]
> There's this extremely cool mod that unborks it with Sodium https://modrinth.com/mod/forcecloseworldloadingscreen/ if you enable the extra option. @Impactic48 1.18.1 is not supported, your fix is to just update

Yeah, I'm updating to 1.18.2 within a day and recommend this mod to those who are having an issue on Fabric in 1.18.2. Also, is this Mod going to be a temporary fix for this issue or will this get patched in the coming updates on 1.18.2?

**Comment by ZephaniahNoah** [comment]
> There's this extremely cool mod that unborks it with Sodium https://modrinth.com/mod/forcecloseworldloadingscreen/ if you enable the extra option. @Impactic48 1.18.1 is not supported, your fix is to just update

This mod did not solve the issue for me. But disabling all mods and fabric did work.
EDIT: Apparently I don't have to disable all mods, just sodium.

**Comment by SushiSplash** [comment]
I might have figured out the issue. The deathTime on the playerdata file is set to over 20 for some reason and it doesn't get reset if you don't respawn. I changed my own playerdata file and set my own deathTime to less than 20 and it works fine again. I dug into the problem and saw that players/entities with a deathTime over 20 are bugged and don't get loaded properly.

**Comment by lynxplay** [comment]
Closing this as it works on vanilla clients. Additionally, I was not able to replicate this (even with sodium and without kennys mod) on 1.19.2.
