### ISSUE TITLE
Entity's id changing (lol)

### ISSUE THREAD

**Issue by odanielmeinicke** [PaperSpigot/Paper#7654]
### Expected behavior

i have a possible issue... but i cannot replicate it, i dont know how to do that.

When i unload a chunk (i think) the armor stands in the chunk changes the entity id.

If a have a `List<ArmorStand>` that list will be broken, the entities on the List contains a different entity id of the entities in the chunk, but i can change the equipments, name, and others...

I really have no idea how to recreate this problem. Sorry for the little information, but it's happening frequently and I was wondering if anyone has reported something similar.

### Observed/Actual behavior

When i unload a chunk (i think) the armor stands in the chunk changes the entity id

### Steps/models to reproduce

idk

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/87931201/159583556-a1f910c7-ff3d-4e26-a34e-b319236098fc.png)

### Paper version

Paper version git-Paper-267 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e7d928a)

**Comment by tomcraft** [comment]
This is not a bug. 
The entity id is not the same as the entity uuid. The entity id is a simple int incremented for each entity spawned/loaded into the world. So unloading then loading a chunk again will result in entity unload then load back with a different id, but same uuid. And obviously the reference to the instance of the entity is not the same between chunk loads, so depending on what you are doing, you may not store the instance of your entity the way you are doing it right now.

**Comment by odanielmeinicke** [comment]
> This is not a bug. The entity id is not the same as the entity uuid. The entity id is a simple int incremented for each entity spawned/loaded into the world. So unloading then loading a chunk again will result in entity unload then load back with a different id, but same uuid. And obviously the reference to the instance of the entity is not the same between chunk loads, so depending on what you are doing, you may not store the instance of your entity the way you are doing it right now.

yeah but if i do something like that:

```java
    @EventHandler
    private void armorStandInteract(PlayerArmorStandManipulateEvent e) {
        ArmorStand buggedEntity = BUGGEDENTITY-HERE
        if (e.getRightClicked() == buggedEntity) {
            // do
        }
    }
```

doesn't works

**Comment by tomcraft** [comment]
that's what i explained with `the reference to the instance of the entity is not the same between chunk loads`. The object is not the same because entity has been removed from chunk at unload and then an other was recreated during chunk load. It is effectively """the same""" but its a whole different instance. 

So you can't == them and the old variable is now outdated and will not reflect to the newly respawned entity.

**Comment by odanielmeinicke** [comment]
> that's what i explained with `the reference to the instance of the entity is not the same between chunk loads`. The object is not the same because entity has been removed from chunk at unload and then an other was recreated during chunk load. It is effectively """the same""" but its a whole different instance.
> 
> So you can't == them and the old variable is now outdated and will not reflect to the newly respawned entity.

Thats make sense, thank you!

I will try create a `List<UUID>` instead `List<ArmorStand>` and check if have any results

**Comment by tomcraft** [comment]
This will resolve your issue, beware that getting a not loaded entity will return `null`. For future support, please use the #paper-dev channel on PaperMC Discord server.
