### ISSUE TITLE
Event for various actionbars

### ISSUE THREAD

**Issue by jho5245** [PaperSpigot/Paper#7656]
### Is your feature request related to a problem?

it isnt related to any problems but I want to edit some action bars in specific player related events!

### Describe the solution you'd like.

for examples of it is when player rides an entity with action bar 'press (sneak key) to dismount' and placing blocks above world height limit action bar 'the build height limit is 320'
there could be more action bars but i have only these ideas now.

I want to edit these action bars! may an event is acceptble in my opinion like 'BlockPlaceLimitEvent' and already existing event EntityMountEvent with #message(Component) method

### Describe alternatives you've considered.

i tried PlayerInteractEvent for build height limit action bar and just sending another action bar when player rides an entity, overriding original action bar.
but hope to use better event listening!

**Comment by Machine-Maker** [comment]
Are either of your examples sent from the server at all? They might be entirely client-sided. In which case to edit them you’d either need to do a resource pack, or send your own action bar to override them which might appear janky as one gets replaced with another in a fraction of a second.

**Comment by Machine-Maker** [comment]
So I looked into this some more, the `press (key) to dismount` is entirely client-sided, the server does not send that anywhere. The build limit msg however is sent by the server. So I suppose there might be some need to modify it. What I would do however, is listen to the chat packets sent to a player that are of the action bar type, and are translatable components with the correct message. 

I supposed this can stay open if more people aren't opposed to a general chat packet event, but that's what it would be, an event that fires anytime the chat packet is sent to a player. And I don't think that is something we should have.
