### ISSUE TITLE
Incorrect client-side item frame position in some situations

### ISSUE THREAD

**Issue by JLyne** [PaperSpigot/Paper#7658]
### Expected behavior

Item frames should be displayed on the client in the the same position as they are on the server.

### Observed/Actual behavior

In some situations, the client side position of a newly placed item frame will not match the server. Reconnecting to the server or other means of resending the chunks will show the correct position again.

### Steps/models to reproduce

Here's a small plugin which reproduces the issue: https://github.com/JLyne/ItemFrameBugTest. This plugin spawns 4 item frames 1 block off the ground adjacent to a 2 block high pillar, which triggers the issue.

1. Start a server with a flat world called "world"
2. Join as soon as it's ready and fly to 0, 4, 0
3. Item frames will spawn after 10 seconds or so
4. Observe their incorrect position
5. Reconnect to the server
6. Observe their correct position

The spawned item frames should look like this:
![image](https://user-images.githubusercontent.com/4615316/160031157-0a5c9f64-6898-47fb-b5c4-5fe647aa6b0c.png)

But will likely look like this until you reconnect:
![image](https://user-images.githubusercontent.com/4615316/160031169-1ad147e4-e272-4286-8585-31c3fd7006db.png)

### Plugin and Datapack List

Issue occurs without additional plugins or datapacks

### Paper version

This server is running Paper version git-Paper-267 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e7d928a)
You are running the latest version
Previous version: git-Paper-264 (MC: 1.18.2)

### Other

Could not reproduce on a freshly built 1.18.2 Spigot.

**Comment by Owen1212055** [comment]
Might be a result of: https://github.com/PaperMC/Paper/blob/master/patches/server/0866-Fix-Entity-Position-Desync.patch

Will test to see, thanks for reporting!
