### ISSUE TITLE
Opening a new inventory on inventory click creates fake item

### ISSUE THREAD

**Issue by nathanfranke** [PaperSpigot/Paper#7661]
### Expected behavior

There is no phantom/false/fake item on the client.

### Observed/Actual behavior

When the client re-opens their inventory, a false item is still on their cursor.

### Steps/models to reproduce

https://user-images.githubusercontent.com/14253836/160112581-5e4836e2-80a0-481f-b9c0-72166f977c49.mp4

### Plugin and Datapack List

Only one plugin, a custom test plugin.

```kt
class Test : JavaPlugin(), Listener {
	override fun onEnable() {
		server.pluginManager.registerEvents(this, this)
	}

	@EventHandler
	fun onInventoryClick(event: InventoryClickEvent) {
		if (event.currentItem?.type == Material.STONE) {
			event.whoClicked.openInventory(server.createInventory(event.whoClicked, 27))
			event.isCancelled = true
		}
	}
}
```

### Paper version

This server is running Paper version git-Paper-267 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e7d928a)
You are running the latest version

**Comment by electronicboy** [comment]
https://papermc.io/javadocs/paper/1.18/org/bukkit/event/inventory/InventoryClickEvent.html
