### ISSUE TITLE
Color Formatting in Console broken

### ISSUE THREAD

**Issue by Chris6ix** [PaperSpigot/Paper#7662]
### Expected behavior

Colors look normal?

### Observed/Actual behavior

Sometimes the color formatting just doesnt work at all and so the color codes just stay infont of the message like this:
![Screenshot 2022-03-23 231354](https://user-images.githubusercontent.com/65610536/160198475-49f8a2fe-4a2c-4333-aeff-525cab4a3e94.png)
Some of the colored text gets underlined (although the item/prefix doesn't have underline in name)...here are some examples:

![Screenshot 2022-03-23 233137](https://user-images.githubusercontent.com/65610536/160198988-71b1e7a3-eab0-4c4a-9d89-64904e61c64d.png)
![Screenshot 2022-03-23 233159](https://user-images.githubusercontent.com/65610536/160198995-8ab80782-47ca-486f-9b64-35ee5ced9241.png)
Sometimes this underlining looks very weird:
![Screenshot 2022-03-22 235323](https://user-images.githubusercontent.com/65610536/160199068-5b5618af-b880-448f-af43-9d516ebb4de4.png)

### Steps/models to reproduce

I'm not really sure...maybe:
-Kick a player from the server?
-Assign yourself to a group (Using Luckperms) and write something in chat?
-Give yourself an item with a custom name and kill somebody with it?

### Plugin and Datapack List

Plugins (49): ArmoredElytra, BackToTheRoots*, BetterConcrete, BetterTridents, BigDoors, Bookshelf, BreakingSlab, ClientDetector, CommandCooldown, DeluxeMenus, Duels, DynamicShop, dynmap, Essentials, EssentialsChat, ExecutableItems, FlyPerms, GSit, HolographicDisplays, HoloMobHealth, HomeGUI, InteractionVisualizer, JoinRules, KittenForever, LightAPI, LinkedPortals, LinksPlus, LuckPerms, Multiverse-Core, Multiverse-Inventories, NotTooExpensive, PL-Hide, PlaceholderAPI, PlayerPortal, PlayerWarps, Playtimes*, ProtocolLib, QuickShop, RotationWrench, SCore, SilkSpawners, TAB, UltimateCatcher, UltimateTimber, UltraCosmetics, Vault, WorldEdit, WorldEditSelectionVisualizer, WorldGuard

There are 3 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/Chris6ix_Custom_Server_datapack.zip (world)]
There are no more data packs available

### Paper version

[21:57:13 INFO]: Checking version, please wait...
[21:57:13 INFO]: This server is running Paper version git-Paper-267 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e7d928a)
You are running the latest version
Previous version: git-Paper-216 (MC: 1.18.1)

### Other

The issue with the underlining was there since quite a long time ago, but it did not really bother me that much, but now even normal color codes sometimes look broken...

**Comment by e-im** [comment]
Duplicate of #7596 for the underline/not working, and #7590 for legacy colour codes.

Resolutions for each on the respective issues.

**Comment by Chris6ix** [comment]
@sulu5890 
Well, I have no idea what #7590 is talking about and the "fix" in #7596 to toggle `use-rgb-for-named-text-colors` in `paper.yml` did absolutely nothing...some messages still look like this no matter how the setting is toggled:
![image](https://user-images.githubusercontent.com/65610536/160426882-87727c0d-64c4-40d3-99e1-2477343cb3cf.png)
This problem was not there before I updated to 1.18.2...

**Comment by Machine-Maker** [comment]
@Chris6ix that setting is not supposed to fix your issue. Your issue is a plugin using legacy color codes in an unsupported way. 

That setting in paper.yml is for people using terminal emulators that don’t support rgb colors.
