### ISSUE TITLE
Higher minecart velocities

### ISSUE THREAD

**Issue by tancred423** [PaperSpigot/Paper#7667]
### Is your feature request related to a problem?

On our server we'd like to have faster minecarts. With the current plugins such as MinecartSpeedPlus and EasyCart you only can set the multiplier to 4 max even if the plugin itself allows for more. So if I set the multiplier to e.g. 10, it will still only be 4.

As MinecartSpeedPlus only allows for a maximum of 4, I modified the code to allow for more, but even then, the maximum is still 4, which lead to me thinking it might be a "fix" on Paper's side.

### Describe the solution you'd like.

Is there any way to work around that and allow for even faster minecarts in Paper?
A config entry for "I know what im doing, give me speeeeed" would be fine if higher speeds are not suitable for everyone.

### Describe alternatives you've considered.

Any plugin that allows for setting a new max speed of minecarts will hit this wall. Except for changing the Server into a vanilla or Spigot one, I don't see any alternative.  I even made my own edit of MinecartSpeedPlus as I said and logged the values of Cart#getMaxSpeed(). This property will actually be set to whatever I want, but in-game it will never exceed 32m/s (multipler: 4). :/

### Other

I know this is rather a question than a feature request. Hope it is fine too and if this is not Paper related, maybe you can help anyway or have some idea? Thanks in advance.

**Comment by Lmaxplay** [comment]
The reason the cap is there is to prevent extreme server-lag (as any values that high will cause performance issues)

**Comment by tancred423** [comment]
Hi thanks for your answer. I understand the reason, but is there some way around it for people who are willing to take the risk?

**Comment by electronicboy** [comment]
issue here is in part that carts are weird, vehicle movement is also heavily handled by the client so am not sure what all is attainable here

**Comment by LaurenceBarnes** [comment]
Did you ever hear of [TrainCarts](https://www.spigotmc.org/resources/traincarts.39592/) ? It has much more sophisticated code than the plugins you mentioned in that issue and allows extremely high speeds, by default up to 100 blocks per second, even more is possible. Works on paper and forks. Only downside is that it allows for more complex train systems, but is that really a downside?

**Comment by bergerkiller** [comment]
Minecrafts physics dont allow for speeds over 0.4, because it only follows rail movement for a single block. It would just derail. A complicated plugin like Traincarts is required, which does actual track walking on top of performing multi-step movement operations.

Why the limit of 4 though? TC by default limits to 5 (but is configurable), and that has mostly to do with avoiding a server crash because of rapid chunk loading. Maybe those plugins had similar reasoning.

**Comment by tancred423** [comment]
That's really useful information. Thanks to all of you! I will take a look at train carts. A bit sad native minecarts are the way they are xD

**Comment by LaurenceBarnes** [comment]
> Why the limit of 4 though? 

Pretty sure the multiplier in these plugins is considering the default speed being 1, so it should translate to 1.6 in TrainCarts measurement :p
