### ISSUE TITLE
MC-246262 possible

### ISSUE THREAD

**Issue by Lmaxplay** [PaperSpigot/Paper#7669]
### Expected behavior

There isn't a patch in PaperMC to my knowledge fixing https://bugs.mojang.com/browse/MC-246262 (Searched through bug and pull requests, empty handed)

### Observed/Actual behavior

IDK

### Steps/models to reproduce

https://bugs.mojang.com/browse/MC-246262

### Plugin and Datapack List

Not applicable

### Paper version

Not applicable

### Other

Not applicable

**Comment by MiniDigger** [comment]
did you actually encounter that bug on a paper server?

**Comment by Lmaxplay** [comment]
I have had lag issues in certain chunks, or even crashes when corrupt chunk data is read

**Comment by Brokkonaut** [comment]
For lags you should post the timings and for crashes the stack trace. and if possible a way to reproduce the issues.

The bug you referenced is not about lags and not about corrupt chunks but about server deadlocks.
