### ISSUE TITLE
Blowing up large amounts of blocks does not drop anything

### ISSUE THREAD

**Issue by AlmightyAnubis** [PaperSpigot/Paper#7671]
### Expected behavior

Drop the Items blown up

### Observed/Actual behavior

Nothing Drops

### Steps/models to reproduce

1. Build a Blast Chamber, using the piston Push Block trick to blow up many blocks (up to 300) at the same time for high TNT Efficiency
2. Test it and see, that nothing drops

https://user-images.githubusercontent.com/62308030/160396103-a068ca04-706c-4680-90fb-317f9c03470d.mp4

### Plugin and Datapack List

Plugins (29): BungeeTabListPlus, CoreProtect, CraftBook, DataHandler*, FastAsyncWorldEdit (WorldEdit), IPWhitelist*, Lootboxes, LuckPerms, NBTAPI, Plan, PreventPortBypass*, SimpleFTPServer*, SkQuery, Skript, skript-reflect, Skyblock_Biome_Changer, Skyblock_Generator, Skyblock_Machinery, Skyblock_Mob_Fixes, SkyblockChallengeExtension, SkyblockDatabaseManager, SQLibrary*, Vault*, ViaBackwards, ViaVersion, VoidGen, VoidGenerator, Votifier, XConomy

There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]

### Paper version

This server is running Paper version git-Paper-268 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e2f743d)\nYou are running the latest version\nPrevious version: git-Paper-267 (MC: 1.18.2)

### Other

I testet it in small scale. Blowing up blocks with TNT works and blowing them up while moving also works (tested with ancient debris, wich can only be exploded while moving and it worked). But on a large scale nothing droped. Maybe to many Items spawn at one, but I don't really know, what causes the bug.

https://user-images.githubusercontent.com/62308030/160395905-7027846e-a5b6-4036-8910-b408beff4ef2.mp4

I checked on similar issues and I found none, that is describing, what I found. Some described, that moving blocks can't be destroyed, but this is not the case her. Thanks for any help

**Comment by e-im** [comment]
Cannot reproduce on a fresh server. tested with [this world](https://www.mediafire.com/file/ms9dgccdv0e1buz/240_block_blast_chamber_ilmango.zip/file) (grabbed from [here](https://www.youtube.com/watch?v=ACaEa-TE1E8)).

Are you able to attempt reproduction of this issue on a server without plugins? If so please upload a world/schematic for your exact setup.

**Comment by aurorasmiles** [comment]
Since @e-im was not able to reproduce this, and the original reporter did not answer for a couple of months, this issue will be closed for now.
