### ISSUE TITLE
spectatorsGenerateChunks gamerule not being respected on 1.18.2

### ISSUE THREAD

**Issue by TheIdiotGamer** [PaperSpigot/Paper#7674]
### Expected behavior

The gamerule spectatorsGenerateChunks is not working on the latest version (1.18.2) of Minecraft, when running Paper. Previously, the gamerule has worked fine on Paper. It also works normally on Vanilla and Spigot.

### Observed/Actual behavior

When loading up Vanilla or Spigot 1.18.2, the chunks did not generate. But when I loaded up the server with Paper, they did generate when I flew out in Spectator mode. I only changed the .jar file, and **touched nothing else**.

### Steps/models to reproduce

Make sure spectatorsGenerateChunks is set to false.

-Load any server on Spigot, gamerule works normally
-Load any server on Paper, gamerule does not work, all spectators can generate chunks even when the gamerule is set to false

### Plugin and Datapack List

Plugins (17): ActionHealth, DiscordSRV, HolographicDisplays, ImageMaps, Multiverse-Core, OpenInv, PandorasBox, PB_SneakCancel, PlaceholderAPI, ProtocolLib, Skript, TAB, TabTPS, TeamManager, ViewDistanceTweaks, WorldEdit, WorldResourcepacks

There are 5 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/ClassicGames (world)], [file/cloudwolf_nphhpn_entity_hit (world)], [file/PandorasBox (world)]

### Paper version

This server is running Paper version git-Paper-268 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e2f743d)

You are running the latest version

### Other

I did a scan of the Paper settings, and could not find anything useful in there, but this could just be me missing the setting. If that's the case, sorry!

**Comment by e-im** [comment]
Duplicate of #6657
