### ISSUE TITLE
/locate not working for structures

### ISSUE THREAD

**Issue by Steve0Jr** [PaperSpigot/Paper#7675]
### Expected behavior

expected to see the coordinates of the structure being locating

### Observed/Actual behavior

![2022-03-28_19 16 07](https://user-images.githubusercontent.com/55672210/160513002-131c0f44-462a-4c96-a9b8-c4f8c3cf262b.png)

### Steps/models to reproduce

/locate Village

/locate village

### Plugin and Datapack List

28.03 19:19:18 [Server] INFO Plugins (53): 

AutoRestart*, Bookshelf, ChestCommands, Citizens, CMILib, CommandItems, CoreProtect, CrazyEnchantments, CubCustomDrops, DeluxeTags, EconomyShopGUI, EnchantmentsExtractor*, Essentials, EssentialsChat, EssentialsDiscord, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, ExecutableBlocks, ExecutableItems, GriefPrevention, InteractiveChat, ItemEdit, Jobs, LoresRemastered, LuckPerms, MCCore*, mcMMO, MessageFilter*, MiniMOTD, MOTD, Multiverse-Core, MythicMobs, OpenInv, PlaceholderAPI, PlayerVaults, PlayTime*, PlugMan, ProtocolLib, SCore, Shopkeepers, SimpleSit*, SkillAPI, SlimeIndicator, spark, TabList, Vault, VeinMiner, ViaBackwards, ViaVersion, WaxIndicator, WorldEdit, WorldGuard

### Paper version

28.03 19:18:44 [Server] INFO This server is running Paper version git-Paper-268 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e2f743d)
28.03 19:18:44 [Server] INFO You are running the latest version
28.03 19:18:44 [Server] INFO Previous version: git-Paper-225 (MC: 1.18.2)

### Other

n/a

**Comment by Steve0Jr** [comment]
i only just found out it wasnt working after not being on my server for a week.. havent encountered this before tbh

**Comment by Machine-Maker** [comment]
That just looks like a syntax mistake on your part.

**Comment by Machine-Maker** [comment]
Yeah, “village” isn’t a valid argument for the locate command. See https://minecraft.fandom.com/wiki/Commands/locate
