### ISSUE TITLE
CauldronLevelChangeEvent not fired by rain on most level changes

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [PaperSpigot/Paper#7677]
### Expected behavior

When it rains CauldronLevelChangeEvent should be fired with [NATURAL_FILL](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/CauldronLevelChangeEvent.ChangeReason.html#NATURAL_FILL)

### Observed/Actual behavior

But acctually its not in latest builds. At least most of them. After running a while i was able to catch changes, but only between 1 and 2 level of water in cauldron. So its not fired after appearing water in it and after remaning changes.
### Steps/models to reproduce

Make it rain, place cauldrons, wait for them to fill and check if CauldronLevelChangeEvent is fired

### Plugin and Datapack List

Plugins (3): PlugMan, SkyUtils, WildStacker

### Paper version

> version
[21:43:54 INFO]: Checking version, please wait...
[21:43:54 INFO]: This server is running Paper version git-Paper-270 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fa68bb1)
You are running the latest version

**Comment by Machine-Maker** [comment]
Can reproduce, and I see the issue.
