### ISSUE TITLE
Wither skeleton pathing is different when target entity is on chests

### ISSUE THREAD

**Issue by MBrinks2239** [PaperSpigot/Paper#7682]
### Expected behavior

When a wither skeleton paths to an entity on chests I except it to path the same as vanilla. See video for an example
Spigot :

https://user-images.githubusercontent.com/44466724/161136487-b329e71b-adb5-47cb-b097-d2ee39ee793d.mp4

### Observed/Actual behavior

The wither skeleton did see the golem, but somehow pathing made him stop at the nether portal without jumping.
Paper:

https://user-images.githubusercontent.com/44466724/161136669-432f4b17-3fa0-4680-8f7c-73252c4573a3.mp4

Also, when there is a full platform around this structure the wither skeletons will also prefer to gather near the side instead of using the stairs and enter the nether portal.

When the chests below the golem are replaced with full blocks the skeletons path like normal.
Paper:

https://user-images.githubusercontent.com/44466724/161137535-d19fae1a-089a-4b09-a6af-861a8f6ec8ac.mp4

### Steps/models to reproduce

Paste this nbt in a world (Make sure to enable paste entities, so the golems are there). Enter the nether portals to generate the nether and make them available for the skeletons.
Use the buttons to summon wither skeletons and examine the difference in behaviour.
[farm.zip](https://github.com/PaperMC/Paper/files/8392690/farm.zip)

### Plugin and Datapack List

None
(Vanilla and craftbukkit build-in datapacks)

### Paper version

This server is running Paper version git-Paper-274 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 04c7b16)
You are running the latest version
Previous version: git-Paper-273 (MC: 1.18.2)

### Other

Here is a overview:
On the left there are full blocks under the golem, on the right there are chests.

Spigot: 

https://user-images.githubusercontent.com/44466724/161139884-3cd88cc2-6549-4f91-b80d-91a400367a7f.mp4

Paper:

https://user-images.githubusercontent.com/44466724/161140014-d8ceff66-e971-4a85-9b3e-2fca16f27d79.mp4

**Comment by molor** [comment]
I'm also currently experiencing problems due to this issue when use mob pathfinders..
