### ISSUE TITLE
e.getBlock().getLocation().getBlockX() may be off.

### ISSUE THREAD

**Issue by MCCbena** [PaperSpigot/Paper#7685]
### Expected behavior

I wanted to get the same coordinates that I see in F3.

### Observed/Actual behavior

After placing the block at -12 63 -4, -13 63 -4 is retrieved at e.getBlock().getLocation().

### Steps/models to reproduce

![image](https://user-images.githubusercontent.com/77214617/161265529-8255472b-6267-4977-8fc6-a8895fdce765.png
This occurs when the above code is written and executed.
Plugin version is 1.16.5.

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/77214617/161265851-971e2a65-69aa-435d-9908-7c9f0ef37545.png)
![image](https://user-images.githubusercontent.com/77214617/161265928-bb6ddf7f-856d-4f1c-aa5d-11d2d5cf614e.png)

### Paper version

This server is running Paper version git-Paper-274 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 04c7b16)
You are running the latest version

### Other

https://user-images.githubusercontent.com/77214617/161266041-660b494f-f757-4f74-a55b-bef1c81a7708.mp4

Something similar happens with teleportation.

**Comment by Machine-Maker** [comment]
I can't replicate this 
![image](https://user-images.githubusercontent.com/15055071/161363652-9b77cf0e-9b98-4370-9341-4d535283104c.png)

In this image the block the player is standing on was just placed. the last log shows the right coords and the F3 screen shows the right block coords (+1 on the Y cause the player is above). As far as I can tell, my code there should be the same as yours. If you can produce better reproduction steps, this can be re-opened.
