### ISSUE TITLE
Teams with no players assigned to them are deleted on server restart

### ISSUE THREAD

**Issue by JosephMA007** [PaperSpigot/Paper#7686]
### Expected behavior

Teams should persist on server restart even if there are no entities/players assigned to them.

### Observed/Actual behavior

Teams with no entities/players in them are deleted on server restart.

### Steps/models to reproduce

1. Start a Paper server
2. Run these commands:
3. /team add test1
4. /team add test2
5. /team join test2 TestPlayer
6. /team list
7. /stop
8. Start the Paper server again
9. Run these commands:
10. /team list
11. Observe that the team test1 does not exist anymore because it has no entities/players

### Plugin and Datapack List

No additional plugins or datapacks are installed.

### Paper version

> version
[10:16:18 INFO]: Checking version, please wait...
[10:16:19 INFO]: This server is running Paper version git-Paper-274 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 04c7b16)
You are running the latest version

**Comment by NoahvdAa** [comment]
Make sure `save-empty-scoreboard-teams` isn't set to `false` (default) in paper.yml.

**Comment by JosephMA007** [comment]
Thanks that config value fixed my issue.
