### ISSUE TITLE
GUI 1.18.2 item and skull issues. 

### ISSUE THREAD

**Issue by SwordOfSouls** [PaperSpigot/Paper#7689]
### Expected behavior

![2022-04-02_10 23 50](https://user-images.githubusercontent.com/82922881/161394193-a928ebdb-6279-4ddd-bd2a-4b1823da8ec2.png)
This is from 1.18.1.
Skull textures work along with the items actions, nbt data, and name/lore.

### Observed/Actual behavior

![2022-04-02_10 38 47](https://user-images.githubusercontent.com/82922881/161394706-6d45867d-47e7-4eb2-b100-f0b9377962a6.png)
This is from 1.18.2

### Steps/models to reproduce

This is using the plugin: [link](https://www.spigotmc.org/resources/ultimategui-%E2%9C%85-1-13-1-18-%E2%AD%90advanced-gui-creation-%E2%9E%A4ingame.98630)
and running the /gui command

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/82922881/161394724-cf2c518f-6c74-49dc-a1a4-4b8fffde6e2a.png)

### Paper version

This server is running Paper version git-Paper-276 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: ea2c81e)
You are running the latest version
Previous version: git-Paper-216 (MC: 1.18.1)

**Comment by Machine-Maker** [comment]
We can't provide support for premium plugins. If you can give reproduction steps that do not involve a premium plugin, this can be re-opened.

**Comment by SwordOfSouls** [comment]
> 

If needed I can provide a license as I am the owner of the plugin.

**Comment by electronicboy** [comment]
We'd need minimal reproduction code or something, we're not really in the art of tryna tear apart plugins to work out what's going sideways
