### ISSUE TITLE
Add option to override EnderDragon origin / target location

### ISSUE THREAD

**Issue by aerulion** [PaperSpigot/Paper#7693]
### Is your feature request related to a problem?

I'm currently working on a project, which requires multiple simultaneous EnderDragon fights (not a real DragonBattle, just killing a "manually" spawned entity). Since the EnderDragon pathfinding is hardcoded to be centered around [0,0] the easiest solution for me was just loading multiple worlds. But now I'm trying to expand on the whole concept, and it would be easier to just have multiple arenas in the same world instead of loading a new world for each fight. But that would require having multiple EnderDragons with different origin locations.

### Describe the solution you'd like.

Some possibility to define an override for the origin / target location of an EnderDragon entity.

Maybe something like:

- EnderDragon#setOrigin(@ Nullable Location origin)

which would override the default origin. Setting this value to null could restore the default behavior. (Which is targeting the EndPodiumFeature if I understood the dragon phase pathfinding correctly)

### Describe alternatives you've considered.

Modifying the pathfinding on my own and recreating default behavior, since I want 1:1 default AI, just not centered at [0,0].

**Comment by Doc94** [comment]
The dragon call a `getHeightmapPos(Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, new BlockPos(EndPodiumFeature.END_PODIUM_LOCATION));` in many places.. for the entity and for phases... maybe can make a logic for set a origin in all this cases...

PD: Nice tag
![image](https://user-images.githubusercontent.com/3602279/161406461-56c590a7-b267-4091-82f9-6ac03e79623a.png)
