### ISSUE TITLE
Player data loading issue. Stuck on Loading Terrain

### ISSUE THREAD

**Issue by ZephaniahNoah** [PaperSpigot/Paper#7697]
Recently a player on my server was unable to join. They would get stuck on the Loading Terrain screen and never got into the server. After messing around with the settings I discovered that deleting their player data allowed them to log in. I assumed the data was corrupt. But it happened again. Then I thought it might be some kind of network problem so I tried replacing my player data with theirs and I had the same issue. There are no errors in the server log. But maybe the player data file will be useful:
(file deleted)

### Observed/Actual behavior

Stuck on `Loading Terrain` screen after logging in.

### Steps/models to reproduce

Join a server which has the player data I posted.

### Plugin and Datapack List

NametagHide
NerfPhantoms
NoEndermanGrief
SkinsRestorer
SuperChairs
VanillaTweaks (recipes datapack [https://vanillatweaks.net/picker/crafting-tweaks/](https://vanillatweaks.net/picker/crafting-tweaks))

### Paper version

git-Paper-277

**Comment by Cryptite** [comment]
It's worth noting that I've had this happen before too, however in my plugin I "mess" with player data like health. For us the player had 0 health and was considered quasi-dead and thus were stuck at Loading Terrain until I force-killed them or set their player health back to >0 and had them relog.

If it helps, anyway.

**Comment by Netherwhal** [comment]
Possibly related to https://github.com/PaperMC/Paper/issues/7647

**Comment by e-im** [comment]
Yes, that's correct. Please attempt reproduction on a vanilla client.

Duplicate of #7647
