### ISSUE TITLE
My Server is Crashing with certain player

### ISSUE THREAD

**Issue by DiktatorAladeen** [PaperSpigot/Paper#7698]
### Stack trace

Factions server
https://paste.gg/p/anonymous/aa49cbcf104f45f4ad47a0f8bb3e7918
Survival server
https://paste.gg/p/anonymous/8f213f4f2b86499d94365ffa818299bd

### Plugin and Datapack List

Survival 
![image](https://user-images.githubusercontent.com/34982264/161616691-357221bf-eea0-4268-90f3-65047dc13245.png)

Factions 
![image](https://user-images.githubusercontent.com/34982264/161617333-eff19171-64d9-4bb0-9714-4ac5c1c8d4d5.png)

### Actions to reproduce (if known)

After this issues server is crashing ( Factions and Survival). Same player is in every error.

### Paper version

Survival 
![image](https://user-images.githubusercontent.com/34982264/161616937-df403302-a29e-4657-92f8-240d5a0d1718.png)

Factions 
![image](https://user-images.githubusercontent.com/34982264/161617379-bb3c7515-eeff-4b67-8283-21bd121d8a2c.png)

**Comment by kennytv** [comment]
1.16 hasn't been supported for a long while, Tuinity hasn't been updated for an even longer while, and you're outdated even with that. On the 1.18 server you're *extremely* outdated as well.

**Comment by e-im** [comment]
For 1.18 update, that's been fixed
