### ISSUE TITLE
My Server is crashing again after updating

### ISSUE THREAD

**Issue by DiktatorAladeen** [PaperSpigot/Paper#7699]
### Stack trace

https://paste.gg/p/anonymous/c5d5189bc9a24d6392d52c0fba2f9481

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/34982264/161622977-70d689d6-ccb9-4dbf-8cdc-49b9ae581017.png)

### Paper version

After updating to latest 1.18.1 paper still crash is happening? Help please

**Comment by electronicboy** [comment]
1.18.1 is unsupported
