### ISSUE TITLE
New profile creation logic breaks the plugins

### ISSUE THREAD

**Issue by r4nx** [PaperSpigot/Paper#7700]
### Expected behavior

Recently merged [pull request](https://github.com/PaperMC/Paper/pull/7558) that alters the profile creation has broken the UUID generation in offline mode, for example in WorldGuard. I couldn't investigate it much as WorldGuard is quite a big plugin, but I guess the problem is that it tries to get the UUID from the lowercase nickname - before the fix it was the same as the real one, now it differs.

I agree that it definitely shouldn't be so and this is a plugin issue, I [reported](https://github.com/EngineHub/WorldGuard/issues/1896) it to WorldGuard, but my previous issue was closed just for being related to offline mode, so it's very likely the maintainer will close this one too.

Hence, maybe some compatibility workaround should be implemented?

### Observed/Actual behavior

Absolutely different offline UUIDs are generated for some plugins

### Steps/models to reproduce

Using Paper >= 263

### Plugin and Datapack List

`Plugins (17): AuthMe, Chunky, CoreProtect, Essentials, EssentialsChat, EssentialsSpawn, Harbor, LuckPerms, MoneyFromMobs, NoCheatPlus, ProtocolLib, SafeTrade, SkinsRestorer, Vault, WorldBorder, WorldEdit, WorldGuard`

`There are no more data packs available`

### Paper version

```
This server is running Paper version git-Paper-274 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 04c7b16)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-271 (MC: 1.18.2)
```

**Comment by r4nx** [comment]
@Owen1212055 @Machine-Maker I reverted the problematic commit in my [fork](https://github.com/r4nx/Paper/tree/fix/offlinemode-uuids), at least until the fix is provided. Should I create a pull request?

**Comment by Owen1212055** [comment]
> @Owen1212055 @Machine-Maker I reverted the problematic commit in my [fork](https://github.com/r4nx/Paper/tree/fix/offlinemode-uuids), at least until the fix is provided. Should I create a pull request?

The thing is this behavior is undocumented in this method, and this seems to be only an issue for offline mode.... so....

**Comment by lynxplay** [comment]
Well the general issue does come from the fact that the `createProfile(String)` method now only forwards to the player profile on an exact name match to allow plugins to properly create these custom profiles. 

E.g. before the PR in question, calling `Bukkit.createProfile("lynxplay")` while I (with the username `LynxPlay` am online) would yield simply my active player profile, preventing plugins from renaming me to `lynxplay` if they wanted to. While the `PlayerProfile#setName(String)` method used to be a way around this, mutating the profile afterwards to achieve a rename, the method is now marked for removal (see #7471 as to why).

Reverting the PR would only reintroduce the bug that was resolved by it in the first place so I would also advise against it.
Instead we might want to provide another overload to the `createProfile` that takes a boolean parameter to toggle whether https://github.com/PaperMC/Paper/blob/f8e8d6c3cd8bfd48d9df5d8877619b81c88c1e88/patches/server/0138-Basic-PlayerProfile-API.patch#L665 should use the `toLowerCase` version of the names or not.

**Comment by electronicboy** [comment]
I was thinking to just toLower() and then create a method to forcefully create a new profile, ignoring the cache

**Comment by lynxplay** [comment]
Yea or that way around, might be nicer in terms of backwards compat ^ I'll open a PR if you have your hands busy
