### ISSUE TITLE
Add a way to change what drops from an Arrow entity

### ISSUE THREAD

**Issue by u9g** [PaperSpigot/Paper#7707]
### Is your feature request related to a problem?

I'd like to make custom arrows, so I need to be able to change what the item is when picking them up.

### Describe the solution you'd like.

```java
((Arrow) entity).setItemStack()
```

### Describe alternatives you've considered.

I have literally no idea

**Comment by Xemorr** [comment]
Couldn't you use this event: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerPickupArrowEvent.html
and then give the player the item you want to give them.

**Comment by u9g** [comment]
> Couldn't you use this event: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerPickupArrowEvent.html
> and then give the player the item you want to give them.

Yes I realized this later, but then you have to add a way to identify the arrow that the player threw so you can listen for that same arrow later, rather than just adding a setter so you can just easily add what the arrow drops when spawning the arrow.

**Comment by Xemorr** [comment]
Yeah it wouldn't be too hard to track you can just use PersistentData but you're right that would be the more elegant solution if it's just not being exposed by the API.

**Comment by Machine-Maker** [comment]
@u9g can you listen to PlayerPickupArrowEvent and change the itemstack there? it just seems odd to add a whole separate field for pickup item.
