### ISSUE TITLE
Allow specifying force for Entity#launchProjectile

### ISSUE THREAD

**Issue by u9g** [PaperSpigot/Paper#7708]
### Is your feature request related to a problem?

I want to be able to shoot arrows myself as if the player shot them, so it would be nice to be able to cancel the `EntityShootBowEvent` and fire it myself, that way I can shoot the arrow (or more arrows) then have the entity object after. The problem is though that theres no way to specify force on Entity#launchProjectile, which would be needed to actually make it seem like the player sent the arrow.

### Describe the solution you'd like.

I would like a new overload that allows specifying force: `Entity#launchProjectile(Class<?> projectile, float force)`, force being the 0-1 number given from the EntityShootBowEvent.

### Describe alternatives you've considered.

once the arrow is spawned, I can multiply it’s velocity by the “force” then set that as the new velocity

**Comment by Doc94** [comment]
the force its used for speed and crits (and when can shot a projectile), in teory this can be handled with the methods for projectiles not?

**Comment by u9g** [comment]
> the force its used for speed and crits (and when can shot a projectile), in teory this can be handled with the methods for projectiles not?

Can you give more info? Not really sure what you mean

**Comment by Doc94** [comment]
if talk abot arrows in EntityShootBowEvent the force value its used for speed and set if the arrow has crits or not (if force == 1) then not sure why the launchProjectile need this value if for set crits or speed/velocity the projectile object has methods for set this when the projectile its created.

**Comment by Owen1212055** [comment]
Seems useful. Will possibly work on implementing in future, unless someone else wants to.

**Comment by Wyrdix** [comment]
I checked in the code, I don't know why but when you launch a projectile, the speed is currently a magic value.
So even though adding the parameter is easy, I don't know how to handle it.

The only idea I have is that the parameter is a coefficient multiplied by the current value, and the default parameter is one.
