### ISSUE TITLE
user issued server with gamemode

### ISSUE THREAD

**Issue by vapid-asd** [PaperSpigot/Paper#7716]
### Expected behavior

just to change gamemodes like normal

### Observed/Actual behavior

when i change gamemodes on my server couple of times it just says killed and when the server crashes i gets me back in time when i changed the gamemode

### Steps/models to reproduce

no

### Plugin and Datapack List

litterly no plugins no nothing

### Paper version

its 1.18.2 some version deleted it from my server pc so idk

### Other

i dont really have anything else to tell you

**Comment by Machine-Maker** [comment]
Can you provide a stack trace? or the latest.log file after this happened?

**Comment by vapid-asd** [comment]
> Can you provide a stack trace? or the latest.log file after this happened?

as i said i deleted paper from my pc but i can tell you what it said in the console

**Comment by kennytv** [comment]
We're not going to find a mystical issue with 0 info given. At the very least we need the version output and the stack trace.

**Comment by vapid-asd** [comment]
rip then
