### ISSUE TITLE
Dont working Paper jar

### ISSUE THREAD

**Issue by t4ebrian** [PaperSpigot/Paper#7717]
### Stack trace

Error:
Unable to initialize main class org.bukkit.craftbukkit.Main
Caused by: java.lang.NoClassDefFoundError: joptsimple/OptionException

### Plugin and Datapack List

No plugins or datapacks

### Paper version

1.18.2

### Other

When i create jar file (./gradlew createReobfBundlerJar) and start them, i get an error.
java -jar -Xmx1G -Xms1G paper-server-1.18.2-R0.1-SNAPSHOT-mojang-mapped.jar nogui

**Comment by electronicboy** [comment]
that is not the runnable server jar, you need the bundler jar from the root projects build output

**Comment by t4ebrian** [comment]
What should I do?

**Comment by electronicboy** [comment]
you run the bundler jar inside of the root projects build/libs folder, as said

**Comment by t4ebrian** [comment]
Sorry, I didn't finish reading

**Comment by t4ebrian** [comment]
Thanks.
