### ISSUE TITLE
Unregistering com.sk89q.worldedit.bukkit.BukkitServerInterface from WorldEdit

### ISSUE THREAD

**Issue by BrianILMangiaNteLLa** [PaperSpigot/Paper#7721]
### Stack trace

[15:52:37 ERROR]: java.lang.ThreadDeath
[15:52:37 INFO]: Stopping server
[15:52:37 INFO]: [GWarp] The Plugin was successfully disabled.
[15:52:37 INFO]: Unregistering com.sk89q.worldedit.bukkit.BukkitServerInterface from WorldEdit
[15:52:37 INFO]: Saving players

### Plugin and Datapack List

DeluxeHub 3.5.1
GWarp
LuckPerms 5.4.9
MultiverseCore 4.3.1
PlaceholderAPI 2.11.1
SkinsRestorer
TAB 3.1.1
TitleManager 2.3.6
ViaVersion 4.2.1
WorldEdit 7.2.8
WorldGuard 7.0.6
znpc

### Paper version

root@mc:~/Lobby# /version
-bash: /version: No such file or directory

### Other

during the plugin configuration I stopped the server with this error

**Comment by electronicboy** [comment]
That's not an error, nor is the message from paper, nor is it telling you to run /version on the terminal but inside of mc, or get the version from the logs

**Comment by BrianILMangiaNteLLa** [comment]
> That's not an error, nor is the message from paper, nor is it telling you to run /version on the terminal but inside of mc, or get the version from the logs

is paper 1.18-66
