### ISSUE TITLE
Infint

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#7728]

**Comment by electronicboy** [comment]
have you tested this against vanilla? This just looks like the quirks of practically every realtime physics simulator

**Comment by defusing7** [comment]
> have you tested this against vanilla? This just looks like the quirks of practically every realtime physics simulator

I just tried it in vanilla and it works there as well

**Comment by Owen1212055** [comment]
Can't reproduce as of 1.19.1

If you can still replicate this, please leave a comment and this will be reopened.
