### ISSUE TITLE
Villagers pathing to bed they can not reach

### ISSUE THREAD

**Issue by TheFireOcean** [PaperSpigot/Paper#7735]
### Expected behavior

Villagers do not path to bed positioned on top of 5 fence posts

### Observed/Actual behavior

Villagers attempt to path to the bed and end up entity cramming causing me to lose all my villagers

### Steps/models to reproduce

1. Place a bed on top of a 5 block tall fence post
2. Place some villagers around with no other beds
3. (Optional) place some villagers in a pit with slabs and stonecutters
4. Villagers will try to path to the bed at night and the ones in the pit with stonecutters entity cram
![scuffed](https://user-images.githubusercontent.com/67860543/163505526-847fc3ee-11bd-48be-a693-9f87c664a227.png)

### Plugin and Datapack List

AntiCreeper, CustomEnchants, Jail, Warp, CommandLog, CoreProtect, WhitelistMessage, DeathCoords, DiscordSRV, Essentials, LPC, LuckPerms, OpenInv, SpigotPing, WorldEdit, WorldGuard

### Paper version

git-Paper-230 (MC:1.18.2) (API verison 1.18.2-R0.1-SNAPSHOT) (Git:1e12cf8)

**Comment by Malfrador** [comment]
I can not reproduce this on the latest build (287) without plugins.
![javaw_RvDv6xNPgw](https://user-images.githubusercontent.com/6106558/163601160-8c325e3c-d3b7-4bbb-ac91-0ffcccc80ee8.jpg)
The villagers, as expected, completely ignore the beds on top of 5 fence posts. 

I would recommend updating to the latest build and if its still happening there its either a plugin issue or some configuration change that causes this behaviour

**Comment by lynxplay** [comment]
I am also failing to reproduce this on latest paper, even with a single fence under the bed villager path finding properly skips unreachable beds for me. If you have an example world to share or further reproduction steps, please share them and reopen this issue :+1:
