### ISSUE TITLE
Add way to temporary change allow-status value of server.properties

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#7736]
### Is your feature request related to a problem?

We want to make the server "broadcasts itself" (responds to ping requests) only during specified time (e.g. night), but players can join the game at any time. Currently I can't find how to do that without restarting the server after changing its properties.

### Describe the solution you'd like.

Add something like `Server#setAllowStatus(boolean value)` that can temporary ignore any incoming ping requests if `value` = true (same as if the `allow-status` setting in `server.properties` is set to false).

It's temporary because the `value` will be reset to default after server restart.

### Describe alternatives you've considered.

Change the server.properties file every time and restart the server,
or use NMS/override ping handler (? if that's possible — tell me please from where I can start inspecting the source)

### Other

I think this can be useful not only for my case, but also, for example, during a bot attack to make the server visually "down" for attacker.

**Comment by kennytv** [comment]
Bots don't need a status response to know that your server is online. For what you described you want, you can just cancel the `PaperServerListPingEvent` with the same outcome.

**Comment by molor** [comment]
> PaperServerListPingEvent

Never know that it's cancellable, thank you o:
