### ISSUE TITLE
When player joins his cords are shown in console

### ISSUE THREAD

**Issue by Ewtiz** [PaperSpigot/Paper#7738]
### Expected behavior

cords are not show in console when player joins server

### Observed/Actual behavior

when player joins his cords are shown in console.

### Steps/models to reproduce

-

### Plugin and Datapack List

AuthMe, BetterSleeping4, Brewery, ColoredAnvils, CoreProtect, floodgate, Geyser-Spigot, GSit, LuckPerms, OreAnnouncer, Playtimes*, RHLeafDecay, SkinsRestorer, SurvivalInvisiframes, TAB, WorldEdit

### Paper version

62dcff3

### Other

just help

**Comment by electronicboy** [comment]
Not a bug, if you wanna remove it, use a log filter

**Comment by Ewtiz** [comment]
> Not a bug, if you wanna remove it, use a log filter

ik its not a bug, but i couldnt find any info how to do this. Help me please?

**Comment by electronicboy** [comment]
Please use the discord for help/support, the issue tracker is not a discussion/forum; plugins like ConsoleSpamFixer or a custom log4j config can filter that type of stuff out
