### ISSUE TITLE
Using scoreboard teams and setting the prefix will result in an error

### ISSUE THREAD

**Issue by victorpyra** [PaperSpigot/Paper#7739]
### Expected behavior

I've created a scoreboard team (/team add 10000Admin) and modified the prefix of it (/team modify Admin prefix "Admin | ". 
Later I joined the team and wanted to join the server but this error came up. (https://pastefy.ga/us1DYJhK)

### Observed/Actual behavior

The problem lays craftbukkits file handling. They're using the displayname instead of the player profile name.
I also reported this on the discord in #paper-dev so you're maybe able to get more information if you're in need. 

https://media.discordapp.net/attachments/555462289851940864/964630441229422632/unknown.png

### Steps/models to reproduce

I've created a scoreboard team (/team add 10000Admin) and modified the prefix of it (/team modify Admin prefix "Admin | ". 
I also joined the team and tried to join on the server. On join the exception is thrown 

https://discord.com/channels/289587909051416579/555462289851940864/964625072541286430

### Plugin and Datapack List

> pl
[23:07:04 INFO]: Plugins (1): PlaceholderAPI
> datapack list
[23:07:14 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[23:07:14 INFO]: There are no more data packs available
>

(eventhough they are unneccessary as the behavior appears also on spigot alone)

### Paper version

> version
[23:06:01 INFO]: Checking version, please wait...
[23:06:01 INFO]: This server is running Paper version git-Paper-287 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: a9f252e)
You are running the latest version
Previous version: git-Purpur-1085 (MC: 1.16.5)
>

### Other

https://media.discordapp.net/attachments/555462289851940864/964630441229422632/unknown.png
here you can directly fix the error, just change from displayname to the profile name and I think the error would be fixxed.

**Comment by victorpyra** [comment]
lynxplay showed me the commit where it was added in spigot, so it may be useful for you
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/aa3a2f276709f54b43796d0a94bad7a6cd087d55

**Comment by lynxplay** [comment]
Resolved by c6e631aacb3a418e39a59d22a73deb404be6fe94.

For documentation purposes, the initial reproduction steps were missing the fact that you had to disable stat-saving in the spigot.yml.
