### ISSUE TITLE
Copper oxide rate

### ISSUE THREAD

**Issue by HexedHero** [PaperSpigot/Paper#7742]
### Is your feature request related to a problem?

Currently, there is no way to speed up the copper oxidizing rate

### Describe the solution you'd like.

Add a copper oxide rate similar to grass spread tick rate in paper.yml

### Describe alternatives you've considered.

Disgusting chunk loop, get all blocks and tick manually

**Comment by Doc94** [comment]
Hmmm i try to see this but the example "grass spread tick" not allow speed up the grass spread.. only make more slow... for make speed in this things maybe can be good modify tickChunk in ServerLevel but not sure...

**Comment by Machine-Maker** [comment]
Copper weathering is actually pretty involved. Its not just a random tick chance, it depends on adjacent weathered copper blocks, how weathered they are, and then some chance based on that. I *think* an event for all "change-over-time" blocks might be useful in some form.

**Comment by Doc94** [comment]
> Copper weathering is actually pretty involved. Its not just a random tick chance, it depends on adjacent weathered copper blocks, how weathered they are, and then some chance based on that. I _think_ an event for all "change-over-time" blocks might be useful in some form.

yeah but with only change randomtick the copper oxide very fast.. i dont fully understand the logic i try put some debugs for understand but... https://paste.gg/p/anonymous/f7486c32661c4fd6af57fd97f87ce06c
