### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by Defirca** [PaperSpigot/Paper#7744]
### Timings or Profile link

None

### Description of issue

Hello, I'm having a problem, I'm using your kernel, but the server is crashing 3 times already!

### Plugin and Datapack List

Plugin and sborka:
https://disk.yandex.ru/d/K7ZgYxtMCw-B2A

### Server config files

```
Paste configs or paste.gg link here!
```
https://disk.yandex.ru/d/ACJ_li_tV9g1pw

### Paper version

1.12.2

### Other

.........

**Comment by e-im** [comment]
1.12 isn't supported, as noted on the downloads page.
