### ISSUE TITLE
Update the Workaround for MC-162253 to 1.18.2

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#7745]
### Is your feature request related to a problem?

Crossing chunk borders causes tremendous lag in areas with large height differences. Essentially, the cause is that in some odd situations, the client re-calculates the light maps for multiple chunks, locking up for some time (depending on the chunk's complexity). 

### Describe the solution you'd like.

This can be avoided by force-sending the light maps with the chunks at the right time. This has a slight bandwidth increase however there are optimizations in place to reduce the bandwidth overhead as much as possible and the feature can be configured within the paper config if people want to disabled. This patch is ideal as there are no apparent plans from mojang to fix this issue which has been open for many years. 

There is a patch for this already (https://github.com/PaperMC/Paper/pull/6266) however it has not been updated since 1.17, it has broken due to how chunk sections work changing. I have spent a few hours attempting to get it working on 1.18 but it is above me unfortunately, someone smarter than me with good knowledge of the game may be able to port this.

### Describe alternatives you've considered.

Asking every player to use starlight fabric, this is unfeasible due to the widespread usage of 3rd party clients such as lunar, badlion, optifine etc.

**Comment by Brokkonaut** [comment]
I updated it some time ago, if you want to use or test it: https://gist.github.com/Brokkonaut/bd5555cc396350745dca7fbc94f92ba7

For me it looks like it works, but no warranties whatsoever.

**Comment by cdnmodule** [comment]
> I updated it some time ago, if you want to use or test it: https://gist.github.com/Brokkonaut/bd5555cc396350745dca7fbc94f92ba7
> 
> For me it looks like it works, but no warranties whatsoever.

Hi, this patch doesn't seem to work when i tested it, sorry.
