### ISSUE TITLE
Libdeflate on paper?

### ISSUE THREAD

**Issue by andreasdc** [PaperSpigot/Paper#7746]
### Is your feature request related to a problem?

=

### Describe the solution you'd like.

Support libdeflate.

### Describe alternatives you've considered.

-

### Other

Does Paper use libdeflate? I saw that it has better performance than zlib.

**Comment by Camotoy** [comment]
`[17:59:30 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.` yea

**Comment by andreasdc** [comment]
> `[17:59:30 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.` yea

Using Java 11 compression from Velocity.
Using Java cipher from Velocity.

**Comment by Machine-Maker** [comment]
I don't know like anything about how that native loader from velocity works, but I assume you have to have libdeflate installed on your machine for the server to be able to use it.

**Comment by andreasdc** [comment]
> I don't know like anything about how that native loader from velocity works, but I assume you have to have libdeflate installed on your machine for the server to be able to use it.

I can't find anything about how to install it on linux.

**Comment by andreasdc** [comment]
Using libdeflate (Linux x86_64) compression from Velocity.
Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.

Is that how it's supposed to look? :)
