### ISSUE TITLE
Add ItemStack#damage

### ISSUE THREAD

**Issue by HexedHero** [PaperSpigot/Paper#7755]
### Is your feature request related to a problem?

Currently, the only way of simulating damage to an ItemStack is by
- Calling the PlayerItemDamageEvent, passing the damage you want to do
- Check if the PlayerItemDamageEvent was cancelled and continue if not
- Adding the processed damage from the PlayerItemDamageEvent to ItemStack
- Check if the ItemStack's current damage is equal to or great than the ItemStack's max durability and continue if so
- Set the ItemStack to AIR and play particles/sounds to simulate it breaking.

### Describe the solution you'd like.

Add an ItemStack#damage method to tell and have Bukkit handle the amount of damage you want to deal to the ItemStack similar to how [Player#breakBlock](https://papermc.io/javadocs/paper/1.18/org/bukkit/entity/Player.html#breakBlock(org.bukkit.block.Block)) works for block-breaking instead of manually calling each event.

### Describe alternatives you've considered.

Doing the messy above.

**Comment by Doc94** [comment]
Maybe im wrong but things about particles for break item its cliend-side... NMS not has any different logic for add damage to item, its like using the ItemMeta for add damage.
