### ISSUE TITLE
Server crash because of invalid blockstate property on attached_melon_stem

### ISSUE THREAD

**Issue by YanisBft** [PaperSpigot/Paper#7764]
### Stack trace

https://paste.gg/p/anonymous/48eda05347494fd2b272bd6f0e0dc940

### Plugin and Datapack List

**Plugins:**
LuckPerms, VoidGen, BlockLocker, AutoMessage, HolographicDisplays, BuycraftX, Votifier, Pl3xMap, ProtocolLib, pAcPI, CommandHook, WeatherVote, PACDonjons, VoxelSniper, AdvancedNMotd, HideAndSeek, Vault, SpamExclude, PACFirstPlayed, WorldEdit, CustomTab, Essentials, PACBirthday, Multiverse-Core, AsyncWorldEdit, DiscordSRV, EssentialsProtect, EssentialsChat, SuperbVote, EssentialsSpawn, PACUtilities, CoreProtect, WorldGuard, Citizens, CitizensGUI, GriefPrevention, WGEF-Reborn, PACProfile, Magic, GPEvents

**Datapacks:**
[13:42:54 INFO]: There are 5 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/peaceandcube (world)], [file/ete_pirates_2021 (world)], [file/paques2022 (world)]
[13:42:54 INFO]: There are no more data packs available

### Actions to reproduce (if known)

Not known

### Paper version

[13:35:15 INFO]: This server is running Paper version git-Paper-308 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 5b85ee3)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-301 (MC: 1.18.2)

### Other

As of this issue, we experienced this crash twice, the first one being after we updated Paper to build 301 from build 294. We never had such a crash before.
Also, we didn't updated any plugins for a little while.

**Comment by Owen1212055** [comment]
Seeing as though nobody else has reported this issue, I am gonna close this. It seems like something got into a very invalid state as it doesn't really make sense that this could occur.

If you experience this issue again please feel free to report, and we can reopen this issue. 😄
