### ISSUE TITLE
call PlayerAnimationEvent when a spyglass is closed

### ISSUE THREAD

**Issue by u9g** [PaperSpigot/Paper#7766]
### Is your feature request related to a problem?

I want to be able to do something when a player closes their spyglass. If I just listen to right click with the spyglass, I get the open of the spyglass, but not necessarily the close.

### Describe the solution you'd like.

Add a SPYGLASS_CLOSE to the PlayerAnimationType enum, tghen call the PlayerAnimationEvent when it happens

### Describe alternatives you've considered.

using a protocol listener

### Other

it's very clear what the close packet looks like: ![abc](https://i.imgur.com/4rPK8iK.png) (the close is the block_dig packet)

**Comment by Doc94** [comment]
Hmmm maybe can be better a event like PlayerToggleScopingEvent for when the player start scoping and finish?
Using the methods in the Spyglass item (because the item has the method when start using and finish)

**Comment by u9g** [comment]
would also be nice to have a similar event for stop eating a golden apple, because that sends the same packet to tell the server the player stopped eating

**Comment by Doc94** [comment]
> would also be nice to have a similar event for stop eating a golden apple, because that sends the same packet to tell the server the player stopped eating

yeah this its a method in item.. called when the packet for release item... but maybe this things can be like a PlayerToggleActiveItem (? and in this events add all this cases... for stop/release try to use item... but not all items have a "animation" for the ActiveItem...

**Comment by u9g** [comment]
Also shield deactivation

**Comment by yannicklamprecht** [comment]
Looks like that can be closed now.
