### ISSUE TITLE
Add Event in Paper API about PacketPlayInSteerVehicle

### ISSUE THREAD

**Issue by TheCalypso** [PaperSpigot/Paper#7770]
### Is your feature request related to a problem?

Hello, the addition that I propose would be in the API paper. In newer versions of Minecraft, clients send a packet called PacketPlayInSteerVehicle. It allows to detect when a player presses a key on his keyboard when he is on a vehicle. We ask you if it would be possible to add an event in order to be able to use it more easily. In our case we would like to use it to be able to more easily control the movement of an entity in our different projects.

We want to extend control of an entity when we're on it. For example we could make a MarioKart like :)

### Describe the solution you'd like.

In order to be able to better access this package, we think it would be wise to add it as an event in the API provided by Paper. This event would be a listen on this packet.

You can find the corresponding code in the PacketPlayerInSteerVehicle class in package minecraft.network.protocol.game .

### Describe alternatives you've considered.

We have already tried to use Protocolibs, only the use of the latter adds a dependency to a plugin.

### Other

Thank you very much for your attention.

Good end of the day to you!

**Comment by lynxplay** [comment]
Previous attempt at implementing this in #7274. If anyone is attempting to implement this, the discussion in there might be useful for you.

**Comment by TheCalypso** [comment]
Thank you for your answer. I don't see what is causing concern in the conversation you sent. Why has this feature not been implemented?

**Comment by lynxplay** [comment]
The author decided against it. I don't know if they simply did not want to deal with the critique or what exactly their reasoning was. As mini said, and I agree with his assessment, there is definitely a usecase for this.

We are just waiting for someone to pick up the torch basically. If you want to, feel free to open it yourself and move the PR forward! Any kind of questions we will be happy to help you.

//edit[0]: For help, just hop by on our discord if you want to PR this :+1:

**Comment by TheCalypso** [comment]
Great thank you, I'll see what I can do. But it is true that the people who answered may lacked a little flexibility in their words, it's a shame. Finally we will try to add this functionality because we think it can really be used for developers wanting to control entities.

**Comment by lynxplay** [comment]
Glad to hear you want to try it 👍  I am sure we can get cat to share his thoughts on a "better suited for proper API over different mechanisms exposed in the game" if he wants to chime in on it if that was the major issue in the last PR.

**Comment by TheCalypso** [comment]
I'm so glad you offered to help me and to see that you are open to discussion! Thanks again, I'm thinking of contacting you directly on Discord to avoid putting too many messages in this conversation.

**Comment by electronicboy** [comment]
My commentary was on the current impl of the event which I was generally arguing for a change of or consideration towards alternatives, not against the raw concept itself

1) as said, events generally fire before mutation in the server, not, packet in > server does stuff > event fired with 0 context towards if anything happened elsewhere
The event fired after the servers state was mutated in a manner which failed to expose any of the servers state mutation, and generally falls against normal expectations of events, i.e. that they fire before mutation

2) I question if a better mechanism for this may exist, i.e. a custom move controller API, to allow plugins to take more control over this, listening to raw packets or a custom move controller has been the goto for handling this for years within the plugin space

**Comment by TheCalypso** [comment]
Of course I understand. In our case we want to capture when a player presses his jump (or other action) key when he is on an entity. In this case we only saw the possibility of being able to listen to this packet. If you have another method than this one, I am interested in some examples.

We don't want to modify the packet but read it.
