### ISSUE TITLE
Can not nametag tamed cats.

### ISSUE THREAD

**Issue by hpr778** [PaperSpigot/Paper#7772]
### Expected behavior

When you right-click a nametag on a cat it should be renamed.

### Observed/Actual behavior

When you right-click on a cat with a nametag, the nametag is used up but that cat remains untamed.

### Steps/models to reproduce

Rename a nametag and right-click on a cat.

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/42947632/165554089-9fa0bdb0-2589-4c43-aacd-30e7acfc4b8c.png)
![image](https://user-images.githubusercontent.com/42947632/165554103-5da15b1c-5e19-4217-8a43-fb72dadffdf3.png)
![image](https://user-images.githubusercontent.com/42947632/165554203-4438d0dd-3125-463b-a524-01052d83a6f8.png)

### Paper version

This server is running Paper version git-Paper-311 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: d70ac03)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-278 (MC: 1.18.2)

### Other

It's only tamed cats the issue is happening with.

**Comment by e-im** [comment]
This isn't an issue on a fresh server. Please reproduce without plugins and/or come by our [Discord](https://discord.gg/papermc) (`#paper-help` channel), [forums](https://forums.papermc.io), or [IRC](https://webchat.esper.net/?channels=paper-help) for support.
