### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by ThatOneJay** [PaperSpigot/Paper#7778]
### Stack trace

https://pastebin.com/y3hWm5G1

### Plugin and Datapack List

Plugins (7): Chunky, ClickSort, DiscordSRV, Harbor, LuckPerms, MiniMOTD, voicechat
3 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/afk display v1.1.2.zip (world)]

### Actions to reproduce (if known)

Unknown

### Paper version

git-Paper-287 (MC: 1.18.2)

### Other

Saw the plugin DiscordSRV in the log, and following what it said at the top I showed DiscordSRVs support team. They don't believe it is because of their plugin.

**Comment by electronicboy** [comment]
Looks like your JVM was stalling out before watchdog ended up tripping out, Id suggest seeking support on the discord
