### ISSUE TITLE
mysql connector has outdated protobuf-java dependency which cause conflicts with the new one.

### ISSUE THREAD

**Issue by portlek** [PaperSpigot/Paper#7782]
### Expected behavior

protobuf-java dependency shouldn't be added in the libraries.list
![image](https://user-images.githubusercontent.com/12835420/166124586-dbeb22d2-28c5-4dfa-a8d4-0152360c0f45.png)

### Observed/Actual behavior

libraries.list has 3.11.4 version of protobuf-java which has not GeneratedMessageV3#isStringEmpty(Object) method, so that cause NoSuchMethodException when someone use gRPC on the paper server.

### Steps/models to reproduce

no need to reproduce it just has outdated protobuf-java dependency that cause conflicts with gRpc.

### Plugin and Datapack List

only my custom plugin which uses gRPC and protobuf-java.

### Paper version

1.18.2

### Other

my suggestion would be excluding the protobuf-java from the mysql-connector-java dependency. or just update the mysql dependency.

**Comment by electronicboy** [comment]
We should probably update the mysql driver, people have already dealt with the 5.x > 8.x series bump by now, and these smaller patches shouldn't be an issue, but, really, you should be relocating stuff within your own jars, we can't generally just bump dependencies willy nilly due to general expectations around versioning within the API

This is not really a bug

**Comment by portlek** [comment]
excluding it would be the permanent solution tho

**Comment by electronicboy** [comment]
I'm not sure if removing dependencies from libraries is the proper mechanism for this type of stuff.

**Comment by lynxplay** [comment]
Closing this (similar to the water fall issue). Yes a bump to the driver is possible but not something that is considered a bug on our end. 
Make sure to relocate your dependencies to avoid this :+1:
