### ISSUE TITLE
Plugin API request: Entity target reason for piglins/brutes targeting you due to Bastion chests/gold

### ISSUE THREAD

**Issue by pixelprizm** [PaperSpigot/Paper#7784]
### Is your feature request related to a problem?

When I open a chest in a bastion, piglins try to target me and create an `EntityTargetEvent`.  But `EntityTargetEvent#getReason()` returns `CLOSEST_PLAYER` when this happens, which is the same as when they target me just for getting close.

I want to disable piglins from attacking a player while walking around, but I still want them to attack the player if they open a chest.

As far as I know there is no way to know whether the piglins and brutes are targeting you because you opened a chest or because you are just nearby.

### Describe the solution you'd like.

Create a new `EntityTargetEvent.TargetReason` value called `DEFEND_BASTION` which would be the reason when piglins and brutes target you due to you opening a chest or breaking a gold block in a bastion.

I recommend this reason name since it's similar to the existing `DEFEND_VILLAGE` reason, but any name would be fine.

### Describe alternatives you've considered.

I considered simply allowing all `EntityTargetEvent`s from piglins targeting players, but that isn't granular enough.  I want to make an experience where the player is only attacked if they provoke an enemy, and opening a chest in a bastion should count as provoking, but walking through a bastion should not count as provoking.

### Other

If someone can direct me to a point in the code to change, I would be happy to submit a PR for this!

**Comment by Doc94** [comment]
Hmmm i see in NMS and not sure how handle this...

When a player open a chest its not like another things where its set a "target", first based in gamerule set a MemoryKey for ANGRY_AT and later the StartAttacking Behavior in Piglin use this ANGRY_AT for set the final target... then not sure how can be handled... if save another data for know the reason when ANGRY_AT is set or what...
