### ISSUE TITLE
Random/Unexpected Player Deaths

### ISSUE THREAD

**Issue by rezz506** [PaperSpigot/Paper#7785]
### Expected behavior

Expected to see the cause for death (Fell from high place, etc.). 

### Observed/Actual behavior

Players on server have complained about "random unexplained deaths" & claim that when sometimes sprinting, jumping, and/or falling (height that should not kill a player) players will be randomly killed. There is a death message displayed of '{DISPLAYNAME} has died'

### Steps/models to reproduce

Have only been able to reproduce once, all other times have been random. 

Had a player jump off a ledge into a body of water (from a height that WOULD normally kill a player minus the water) - they then died. The message displayed was not "fell from a high distance" but was " xxx has died" 

### Plugin and Datapack List

CoreProtect
EssentialsX
EssentialsXChat
EssentialsXDiscord
EssentialsXProtect
EssentialsXSpawn
IllegalStack
PlaceholderAPI 
Sleepmost
Spartan
TAB
UltraPermissions
Vault
worldedit
worldguard

![Plugins](https://user-images.githubusercontent.com/33408027/166319886-4a4ad6f7-56b2-4e85-8f93-58c529557351.PNG)

### Paper version

1.18.2 b317

**Comment by kennytv** [comment]
That's most likely down to one of your plugins/the anticheat
