### ISSUE TITLE
Recipes added via Bukkit.addRecipe() are shown to client after crafting, not after getting materials

### ISSUE THREAD

**Issue by u9g** [PaperSpigot/Paper#7794]
### Expected behavior

clients should be send the unlock recipes packet once they get the materials to make a recipe

### Observed/Actual behavior

clients are only sent the unlock recipes packet once they use the recipe once

### Steps/models to reproduce

1. Add a new recipe, using Bukkit.addRecipe()
2. give yourself the materials
3. watch in horror as you dont get the achievement banner in the top right
4. craft the recipe
5. watch yourself get the achievement you should have gotten at step 3

### Plugin and Datapack List

No datapacks, one plugin for the example in the steps to reproduce

### Paper version
```
version
[01:54:17 INFO]: Checking version, please wait...
[01:54:18 INFO]: This server is running Paper version git-Paper-323 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 2515bc4)
You are running the latest version
```

**Comment by Machine-Maker** [comment]
> clients should be send the unlock recipes packet once they get the materials to make a recipe

you have an incorrect understanding about how recipes are revealed. Each recipe is a hidden advancement with the criteria for unlocking it, like having and item, or being in water, or whatever. So when you add a new recipe, you either need to have the player discover it, or add an advancement that rewards it.

**Comment by Leguan16** [comment]
> So when you add a new recipe, you either need to have the player discover it, or add an advancement that rewards it.

Mustn't you have discovered the items needed to craft it and not the item you want to craft itself?

**Comment by electronicboy** [comment]
> Each recipe is a hidden advancement with the criteria for unlocking it, like having [an] item

You either hard "discover" the recipe, or have an advancement which "discovers" it
