### ISSUE TITLE
BlockBreakEvent executes when it shouldn't

### ISSUE THREAD

**Issue by orange2222222222** [PaperSpigot/Paper#7796]
### Expected behavior

BlockBreakEvent shouldn't happen when a player in creative mode punches a block with a sword

### Observed/Actual behavior

BlockBreakEvent was executed by a creative mode player punching block with a sword

### Steps/models to reproduce

Register a event handler with BlockBreakEvent

Go in creative mode
Hold a sword, and left click a block that can be mined with a sword (and drops something)

The event handler is called and plugins will have problems

### Plugin and Datapack List

No datapacks,

A private plugin with only a BlockBreakEvent handler.
Skript (with no skripts yet),
ViaVersion

### Paper version

[05:45:51 INFO]: This server is running Paper version git-Paper-283 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: f8e8d6c)
You are 46 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-133 (MC: 1.18.1)

### Other

I'm pretty sure this is because paper thinks the block should be broken, when it's not because the player is holding a sword in creative mode

**Comment by Machine-Maker** [comment]
Doesn't it fire in a cancelled state? If so, you can ignore it by properly using the EventHandler annotation


EDIT: yes it does, just confirmed it. this is WAI.

**Comment by orange2222222222** [comment]
Hi, may you please specify what you mean by "Doesn't it fire in a cancelled state?"

**Comment by orange2222222222** [comment]
oh, i just understood, sorry I didn't know ignoreCancelled was a thing :(
