### ISSUE TITLE
Player's itemOnCursor always return air

### ISSUE THREAD

**Issue by StayCake** [PaperSpigot/Paper#7797]
### Expected behavior

![image](https://user-images.githubusercontent.com/36215887/167293370-9da52faa-312f-4c93-b6dc-324544390cc7.png)
It should return Item when helding item on cursor while opening inventory.

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/36215887/167293500-d8526eaa-ee84-47cb-b8ee-525309feb897.png)
It keeps return air even holding items 

### Steps/models to reproduce

Calls EntityPickupItemEvent while holding item on cursor in inventory.

### Plugin and Datapack List

Onlyone [self-made]
plugman
[No Datapack]

### Paper version

![image](https://user-images.githubusercontent.com/36215887/167293516-0bdbe01c-963a-46d5-aab3-022b92865fc1.png)

**Comment by electronicboy** [comment]
I'm calling it: creative mode. Test in a sane mode, i.e. survival

**Comment by Machine-Maker** [comment]
Yep, getItemOnCursor returns the correct value in survival mode, or in creative mode while not in the creative inventory. A quick explanation, while in creative mode in the creative mode inventory, when you click on an item to put it in your cursor, that item is destroyed as far as the server can tell, and when you place it back down, its "created". there was no in-between. creative mode can create and destroy items at will, so the inventory works differently there.
