### ISSUE TITLE
Can not enter the server after using the title screen button in death screen

### ISSUE THREAD

**Issue by YuxuanZuo** [PaperSpigot/Paper#7807]
### Expected behavior

Could enter the server after using the title screen button in death screen.

### Observed/Actual behavior

Client stucks at "Loading terrain..." screen after using the title screen button in death screen when trying to rejoin the server.

### Steps/models to reproduce

1. Killing the player
2. Click "Title screen" button in death screen
3. Rejoin the server

### Plugin and Datapack List

None

### Paper version

This server is running Paper version git-Paper-331 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 18f0f8d)
You are running the latest version

**Comment by jpenilla** [comment]
https://github.com/CaffeineMC/sodium-fabric/issues/1225

**Comment by Doc94** [comment]
This was reported too in Upstream not sure if is the same issue https://hub.spigotmc.org/jira/browse/SPIGOT-7009
In Upstream the issue is if you disconnect in a normal chunk and no players are in this chunk when reconnect like the chunk not load or not sure....

**Comment by YuxuanZuo** [comment]
> This was reported to in Upstream not sure if is the same issue https://hub.spigotmc.org/jira/browse/SPIGOT-7009 In Upstream the issue is if you disconnect in a normal chunk and no players are in this chunk when reconnect.

Looks like the same issue

**Comment by NoahvdAa** [comment]
That issue was fixed by Paper in [178802a](https://github.com/PaperMC/Paper/commit/178802ab94714d68c0833f53fbc9de0764ab0f8b), sodium doesn't like the empty chunk that is being sent.

**Comment by e-im** [comment]
Are you able to reproduce this on a vanilla client? That shouldn't be the same issue

**Comment by YuxuanZuo** [comment]
> Are you able to reproduce this on a vanilla client? That shouldn't be the same issue

No, It is work on vanilla servers

**Comment by e-im** [comment]
Yes, fhabks. Are you able to reproduce on a vanilla **client** (with a paper server)? That is a client without any mods

**Comment by YuxuanZuo** [comment]
> Are you able to reproduce on a vanilla **client** (with a paper server)? That is a client without any mods

Forgive me for not seeing it clearly, I just tried it and it can join the server correctly now

**Comment by YuxuanZuo** [comment]
So this is a bug of sodium right?

**Comment by jpenilla** [comment]
Yes. The aforementioned spigot issue is a different thing and is not an issue on Paper.
