### ISSUE TITLE
"Feels like home" Advancement only works in the default Overworld not Bukkit created Overworlds

### ISSUE THREAD

**Issue by HexedHero** [PaperSpigot/Paper#7809]
### Expected behavior

The "Feels like home" advancement should work with all Overworlds.

### Observed/Actual behavior

Only works with the default "world" overworld but if you use the Bukkit API to create another Overworld the Advancement cannot be achieved in that world.

### Steps/models to reproduce

Create a new Overworld and attempt to get the Advancement.

### Plugin and Datapack List

N/A

### Paper version

[19:26:49 INFO]: This server is running Paper version git-Paper-333 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 9fd870d)

**Comment by Machine-Maker** [comment]
I’d have to look at the exact advancement scheme, but I’m guessing this is works as intended as it checks that the dimension is “minecraft:overworld”

**Comment by Machine-Maker** [comment]
Yes, this is WAI. The advancement checks if the dimension is `minecraft:overworld`. There is only one overworld, the dimension with that key. Everything else is, well, something else. And the achievement is `Take a Strider for a loooong ride on a lava lake in the Overworld`. Overlord with a capital O, proper noun, means The overworld, not a world that looks like it.
