### ISSUE TITLE
Replacing server files without using data packs

### ISSUE THREAD

**Issue by HIRO0132** [PaperSpigot/Paper#7811]
### Is your feature request related to a problem?

I wanted to remove the open water added in 1.16. I searched for a plugin for that.
And I found a plugin ported from Vanilla Tweaks.
But it dropped a bow that was both infinite and mending.
But everywhere you look, the data pack says it has a performance impact.
I want to replace fishing.json on the server file

### Describe the solution you'd like.

An option for developers to disable hash checking on the server's files or run the server .jar read-only instead of displaying a warning in the log and not supporting it.

### Describe alternatives you've considered.

https://www.spigotmc.org/threads/teaks-tweaks-1-17-1-18.514737/
https://www.planetminecraft.com/data-pack/allow-afk-fishing-farm-in-1-16/

**Comment by Machine-Maker** [comment]
Datapacks that modify loot tables or recipes and stuff are totally fine. Its just data packs that make use of command functions, running sometimes hundreds of commands per tick that have a performance impact.

**Comment by HIRO0132** [comment]
Thank you for answering.  If so, try using a data pack
