### ISSUE TITLE
API Feature to set the targets of the heads on the wither setAlternativeTargets()

### ISSUE THREAD

**Issue by DevJoey** [PaperSpigot/Paper#7812]
### Is your feature request related to a problem?

Yes, if i want to make that a wither forgets me after targetting me using setTarget(null), it only affect the center head. The other 2 heads are still attacking me. Im seeing this as an API bug, because calling a method on an entity, have to change the behavior of the WHOLE entity and not only of 1 head. Mojang pls... why are you creating a creature with 3 heads, its cringe :)

### Describe the solution you'd like.

It would be nice, if a method gets added to the Wither to modify the targets of all heads.

### Describe alternatives you've considered.

Making setTarget(null) on the wither changing the targets of all heads to null and not only the middle head.

**Comment by Doc94** [comment]
This can be closed by upstream https://github.com/PaperMC/Paper/commit/73bd35d07624fde87498e6e5151b2a13baae25b1

**Comment by lynxplay** [comment]
Indeed 👍 resolve by the upstream update doc linked.
