### ISSUE TITLE
Bukkit/Spigot Plugin not loading

### ISSUE THREAD

**Issue by myxxmikeyxx** [PaperSpigot/Paper#7813]
### Expected behavior

To be able to use any bukkit plugin. 
This plugin works fine on bukkit and on spigot.

### Observed/Actual behavior

When the bedwars plugin is loading it is giving this error:
`[10:51:37 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.Location org.bukkit.Location.deserialize(java.util.Map)' of class org.bukkit.Location for deserialization`
I assume it is just because that does not exist on paper but exist on bukkit and spigot.

### Steps/models to reproduce

Download paper 1.18.2 version 333
Install the plugins bellow

### Plugin and Datapack List

Screaming BedWars - [Link](https://dev.bukkit.org/projects/screamingbedwars/files) [Link2](https://www.spigotmc.org/resources/screaming-bedwars-1-9-4-1-18-2.63714/)

Other plugins installed:
Cleanroomgenerator
EssenitalsX
floodgate
geyser
LuckPerms
Multiverse
Placeholder api
Viabackwars
Viaversion
worldedit

### Paper version

1.18.2-333

### Other

Here is the console errors
[error.log](https://github.com/PaperMC/Paper/files/8680183/error.log)

**Comment by lynxplay** [comment]
Can you please provide the entire error, the method should have provided more. If you can, simply provide as much of the server log as possible through a pastbin like https://paste.gg.

**Comment by lynxplay** [comment]
My bad, I missed the error log there. Thank you :+1: We will look into this.

**Comment by lynxplay** [comment]
Well from the looks of it, the file `sign.yml` in the plugins data folder is storing signs with a world that is not loaded when the plugin attempts to load in the locations. Does the plugin (with this exact config) work on spigot ? It seems more like a world is simply missing (maybe not loaded by multiverse).

**Comment by myxxmikeyxx** [comment]
So when I run this on spigot it loads the worlds info after the luckperms loads but on paper for some reason it isn't loading them.

**Comment by myxxmikeyxx** [comment]
For some reason on pterodactyl it didn't write over the existing multiverse file so it was missing all my worlds to load. 
The problem is even after changing the file it is not working still. I think multiverse is not able to load the worlds for some reason but I am not sure why. It loads fine on spigot and it loads the worlds before bedwars but it sometimes does have to load it after but it has not broken.

**Comment by electronicboy** [comment]
provide the full log

**Comment by myxxmikeyxx** [comment]
here is a tar.gz file with my server files in it. I am running  java17 
[Download Link](https://drive.google.com/file/d/1OL2C8RG1qt__vpSMVpHQgUXJXyRKBwWM/view?usp=sharing)

**Comment by lynxplay** [comment]
Concerning that this is highly specific to the plugins used and no more input was posted since May, I am closing this.
If you still have this issue, try to contact the plugin author of ScreamingBedwars to hopefully have a somewhat replicable setup for us.

Also obviously try to replicate this on the latest version.

If you still have this issue, feel free to comment and I/some other team member can reopen this issue for you :)
