### ISSUE TITLE
Hopper minecart can't move items in hopper under it

### ISSUE THREAD

**Issue by Tomajjs** [PaperSpigot/Paper#7814]
### Expected behavior

I expected that the hopper minecart will drop it's content into hopper under it.
Picture:
![2022-05-12_19 26 18](https://user-images.githubusercontent.com/98232518/168133641-328b046e-940c-49f9-8781-c2e6957ec571.png)

### Observed/Actual behavior

Instead of the items going from minecart to the hopper, hopper & rail broke and put it inside it.

### Steps/models to reproduce

1. Place hopper
2. At that hopper place rail
3. Place at that rail hopper minecart
4. Throw item in it
Short video:

https://user-images.githubusercontent.com/98232518/168134253-27d8cab7-9fff-478a-8fa7-2114317f76b0.mp4

### Plugin and Datapack List

It's private survival server.
### Plugins
CoreProtect, HolographicDisplays, OpenInv, SkinsRestorer, WorldEdit, WorldGuard.
### Datapacks
Vanilla (built-in), afk display, armor statues, bukkit, fast leaf decay, more mob heads, nether portal coords, player head drops, real time clock, spawning spheres, villager death messages, villager workstation highlights, wandering trades

### Paper version

There's nothing in console.

This server is running Paper version git-Paper-333 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 9fd870d)
You are running the latest version

### Other

idk u want to hear here. I guess it's some patch that is implemented into paper.

**Comment by Machine-Maker** [comment]
Yeah, I cannot reproduce this on Paper 1.18.2. Please replicate this with no plugins or data packs and then this issue can be reopened.

**Comment by tatteaid** [comment]
> Yeah, I cannot reproduce this on Paper 1.18.2. Please replicate this with no plugins or data packs and then this issue can be reopened.

Same, tested it both on the latest release as well as git-Paper-333. Couldn't replicate the issue.

**Comment by Tomajjs** [comment]
oh ok ill try
