### ISSUE TITLE
Player Position Updates even when one is offline on 1.18.2

### ISSUE THREAD

**Issue by rissoru1592** [PaperSpigot/Paper#7816]
### Expected behavior

Expected Behavior:
When one log outs after a coordinate, the next time he logs in should log in from the coordinate(Log in from air, in this case)

### Observed/Actual behavior

When one is on air and logs out, the player position updates even though they are offline.  

### Steps/models to reproduce

In paper server(1.18.2) when in mid air and log off, the next time they log back, they would be at the ground and taking fall damage(Same for lava, if you are above lava dropping towards lava and log off, after a while when you log back the player dies)
Video explanation - https://youtu.be/M5DA7bVeso4 

### Plugin and Datapack List

> plugins
[16:34:55 INFO]: Plugins (0):

(Done in console)

### Paper version

> version
[16:35:28 INFO]: Checking version, please wait...
[16:35:29 INFO]: This server is running Paper version git-Paper-333 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 9fd870d)
You are running the latest version

**Comment by mmvanheusden** [comment]
That's simply the loading screen that covers the fall

**Comment by lynxplay** [comment]
Indeed, the majority of this movement you are missing out on is hidden behind the loading screen.
If you want to skip it (if possible) you can look at mods like https://github.com/kennytv/kennytvs-epic-force-close-loading-screen-mod-for-fabric.
