### ISSUE TITLE
Console colors no longer working

### ISSUE THREAD

**Issue by ShaneBeee** [PaperSpigot/Paper#7818]
### Expected behavior

I expect the colors in the console to work as they did before

This is an example of what the console SHOULD look like (as seen on Spigot)

<img width="818" alt="Screen Shot 2022-05-13 at 1 12 08 PM" src="https://user-images.githubusercontent.com/20008482/168382887-0c6b2f22-adc7-4c26-9aae-cc8f01c3b86d.png">

### Observed/Actual behavior

I see that colors seem to be stripped from console messages

example:

<img width="866" alt="Screen Shot 2022-05-13 at 1 09 28 PM" src="https://user-images.githubusercontent.com/20008482/168382329-2737d88b-f618-44da-8d59-b9cad8334d84.png">

### Steps/models to reproduce

Just load the server, you shall notice colors put out by plugins are just grey

### Plugin and Datapack List

[13:07:36 INFO]: Plugins (3): SkBee, Skript, skript-reflect

No datapacks

### Paper version

Paper version git-Paper-333 (MC: 1.18.2)

### Other

Running on macOS 12.3.1
Java version:
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)

**Comment by lynxplay** [comment]
//edit, wrong issue. Duplicate of #7596

**Comment by e-im** [comment]
This is an issue with the apple terminal. iterm2 or another terminal emulator will not encounter this issue. Try toggling `use-rgb-for-named-colors` in paper.yml as a workaround.
