### ISSUE TITLE
Ability to set an item dropped on `HangingBreakEvent`

### ISSUE THREAD

**Issue by imDaniX** [PaperSpigot/Paper#7820]
### Is your feature request related to a problem?

I need to drop a specific item when a specific item frame is being broken.

### Describe the solution you'd like.

A method `setDroppedItem` on `HangingBreakEvent` which sets the item to drop. Probably with an option to drop nothing if provided item is null (or, to be on brighter side, has type `AIR`?)

### Describe alternatives you've considered.

Caching the location on `HangingBreakEvent` and checking it on `ItemSpawnEvent`; or completely cancelling the event and handling the removal myself. Both sounds to me as junky workarounds.

**Comment by electronicboy** [comment]
We don't really have the context of this here either

**Comment by Doc94** [comment]
You try with this event? https://papermc.io/javadocs/paper/1.18/io/papermc/paper/event/player/PlayerItemFrameChangeEvent.html
this is the most cases for the ItemFrame like the "removed" related when get the item for drops or another cases.

**Comment by imDaniX** [comment]
> We don't really have the context of this here either

So, item frame dropping code is too disconnected from the event firing?

> You try with this event? https://papermc.io/javadocs/paper/1.18/io/papermc/paper/event/player/PlayerItemFrameChangeEvent.html this is the most cases for the ItemFrame like the "removed" related when get the item for drops or another cases.

It doesn't fire when an item frame itself gets removed tho. I don't think it's applicable in my situation.

**Comment by electronicboy** [comment]
ganging break is a generic event, which calls off into other logic which determines what if anything drops, etc; I don't see how it would attach to those at all given how that works at all, we couldn't tell you if/what will drop, etc

**Comment by Machine-Maker** [comment]
Can you cancel the event and then remove it yourself and handle drops as such? Some hanging things drop multiple items vs just 1. Paintings and leashknots can only drop 1, but item frames may drop 2.

**Comment by CodeByCam** [comment]
Hey @imDaniX, have you had the chance to try out Machine-Marker's suggestion?

**Comment by imDaniX** [comment]
> Hey @imDaniX, have you had the chance to try out Machine-Marker's suggestion?

Yup, that's basically what I did. [See here](https://github.com/imDaniX/InvFrame/blob/3354e0ee1758e9f33dcdf21bfcd7c7ae6f06b26f/src/main/java/me/imdanix/frame/InvFramePlugin.java#L82).
