### ISSUE TITLE
Particle BLOCK_CRACK, BLOCK_DUST and FALLING_DUST create wrong instance

### ISSUE THREAD

**Issue by Fenmore** [PaperSpigot/Paper#7826]
### Expected behavior

When calling instances of the Particle enum, Particle.BLOCK_CRACK should not referr to the same instance as Particle.LEGACY_BLOCK_CRACK.

### Observed/Actual behavior

```
Particle.valueOf("BLOCK_CRACK") 273422219
Particle.valueOf("LEGACY_BLOCK_CRACK") 277700568
Particle.LEGACY_BLOCK_CRACK 277700568
Particle.BLOCK_CRACK 277700568
```
Looking at the hash values of these procedures, it turns out, that calling Particle.BLOCK_CRACK actually creates a LEGACY_BLOCK_CRACK instance.
Same for BLOCK_DUST and FALLING_DUST to their LEGACY counterpart.

### Steps/models to reproduce

```
System.out.println("Particle.valueOf(\"BLOCK_CRACK\") " + Particle.valueOf("BLOCK_CRACK").hashCode());
System.out.println("Particle.valueOf(\"LEGACY_BLOCK_CRACK\") " + Particle.valueOf("LEGACY_BLOCK_CRACK").hashCode());
System.out.println("Particle.LEGACY_BLOCK_CRACK " + Particle.LEGACY_BLOCK_CRACK.hashCode());
System.out.println("Particle.BLOCK_CRACK " + Particle.BLOCK_CRACK.hashCode());
```

### Plugin and Datapack List

/

### Paper version

This server is running Paper version git-Paper-333 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 9fd870d)
You are running the latest version
Previous version: git-Paper-400 (MC: 1.16.4)

**Comment by electronicboy** [comment]
did you set the api-version in your plugin properly?

**Comment by Fenmore** [comment]
That fixed it. Thank you for this extremely fast answer. =)
