### ISSUE TITLE
GUI console shows legacy formatting codes

### ISSUE THREAD

**Issue by Malfrador** [PaperSpigot/Paper#7827]
### Expected behavior

No formatting codes in the GUI console

### Observed/Actual behavior

Legacy formatting codes show up in the GUI console
![javaw_757B4jeypg](https://user-images.githubusercontent.com/6106558/168511743-3e216bff-464d-44d2-b005-9a2861aedf48.png)

### Steps/models to reproduce

1) Run Paper by double-clicking the .jar
2) Produce a vanilla message in chat, for example by joining the server.

### Plugin and Datapack List

none

### Paper version

This server is running Paper version git-Paper-334 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 8d1de8d)
You are running the latest version
Previous version: git-Paper-71 (MC: 1.18.1)

### Other

Tested on vanilla, they do not show up there.

**Comment by lynxplay** [comment]
I cannot replicate this on the latest version. Please re-open this issue if you are capable of reproducing it on latest.

**Comment by Malfrador** [comment]
Same issue on build 379. 

I also just tried running the server on WSL2. Same result, but instead of a space a � character is displayed. 
Disabling/enabling ``use-rgb-for-named-text-colors`` changes nothing.

I don't think this is important at all, the GUI is kinda meh anyways. But its not happening on vanilla so I made an issue.

**Comment by lynxplay** [comment]
Ah I see what you mean, yeah I can reproduce this on 1.18.2. I'll reopen this for now, with a low priority. As you already said, GUI is definitely not the highest of priorities here and it appears the GUI is simply not capable of properly rendering these colour codes.

Or to be more specific, the gui in spigots case just filters out any form of ANSI colour coding, however the regex seems broken for hex-ansi codes.
