### ISSUE TITLE
Implement fix for bug MC-150224 (Rabbits can occasionally get stuck on the edges of blocks)

### ISSUE THREAD

**Issue by LichLord91** [PaperSpigot/Paper#7832]
### Is your feature request related to a problem?

This is a request to implement a fix for bug : [MC-150224](https://bugs.mojang.com/browse/MC-150224)

Observed Behavior:
Rabbits can occasionally get stuck on the edges of blocks.

Steps to Reproduce:
Build the setup as shown in the attachment below. [setup.png](https://bugs.mojang.com/secure/attachment/459479/459479_setup.png)
Summon multiple rabbits on any of the diamond blocks.
Switch into survival mode and approach the rabbits so that they will run away from you.
Pay close attention to the behavior of the rabbits as they try to jump over blocks.
Take note as to whether or not rabbits can occasionally get stuck on the edges of blocks.

### Describe the solution you'd like.

Expected Behavior:
Rabbits would not occasionally get stuck on the edges of blocks.

### Describe alternatives you've considered.

n/a

**Comment by HexedHero** [comment]
Fixing this would most likely break some vanilla behaviour so this is more of a thing Mojang needs to fix.

**Comment by LichLord91** [comment]
Closing

**Comment by augustsaintfreytag** [comment]
To anyone looking for a fix for rabbits getting stuck until Mojang eventually addresses this, I built a mod that detects if rabbits get stuck in a jump loop and gives them a nudge.

https://modrinth.com/mod/rabbit-behavior-fix
