### ISSUE TITLE
1.18.2 illegalStateException when player with a UTF-8 nickname join server

### ISSUE THREAD

**Issue by RuofengX** [PaperSpigot/Paper#7834]
### Expected behavior

I update my server to 1.18.2 build today. One of my player failed joining the server today. I am running offline mode, and his nickname is "情绪稳定", which is in chinese characters. He use windows system maybe.

This is the screenshot he provided:
![图片](https://user-images.githubusercontent.com/40327863/169546072-195ee520-8ac5-4eb6-8de6-463ad006ec90.png)

**raw log in console**

```
[21:11:34 INFO]: com.mojang.authlib.GameProfile@c042137[id=<null>,name=������������,properties={},legacy=false] (/10.0.4.12:43010) lost connection: Internal Exception: java.lang.IllegalStateException: Invalid characters in username
```

### Observed/Actual behavior

-

### Steps/models to reproduce

join the (offline-mode)game with some chinese character as player's name.

### Plugin and Datapack List

[22:16:37 INFO]: Plugins (9): AuthMe, Boom, CoreProtect, DeadChest, LiveRecorder*, LuckPerms, ProtocolLib, TimeMachine*, UltimateTimber

### Paper version

**version info**
```
> version
[22:12:57 INFO]: Checking version, please wait...
[22:12:58 INFO]: This server is running Paper version git-Paper-339 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 9b492cf)
You are running the latest version

### Other

If any further infomation needed, please notice me. Thanks for maintaining this project!

**Comment by kennytv** [comment]
That's the (Vanilla) server intentionally checking for invalid characters for security reasons

**Comment by Dreeam-qwq** [comment]
> That's the (Vanilla) server intentionally checking for invalid characters for security reasons

However, if you use mojang's seurticity check, the `0828-Validate-usernames.patch` is useless now for 1.18.2...

**Comment by electronicboy** [comment]
You basically have the option of either vanillas security check or papers more restrictive security check, the patch does however allow for plugins to bypass the check using an internal field, which would allow you to replace the built-in checks with your own plugin; We have 0 inclination to disable vanillas checks

**Comment by RuofengX** [comment]
> You basically have the option of either vanillas security check or papers more restrictive security check, the patch does however allow for plugins to bypass the check using an internal field, which would allow you to replace the built-in checks with your own plugin; We have 0 inclination to disable vanillas checks

Thanks for reply, does that mean I could write a plugin to disable the vallina name check? If so, could you please provide the api doc link?
