### ISSUE TITLE
Vanilla permission like ```minecraft.debugstick.always``` set to false but server operators have the permission

### ISSUE THREAD

**Issue by astro-angelfish** [PaperSpigot/Paper#7844]
### Expected behavior

The server operators should not have vanilla permission which default value is false.

### Observed/Actual behavior

The server operators have the vanilla permission which default value is false.

### Steps/models to reproduce

1. Run /op <your game name>
2. Execute groovy code
```groovy
Bukkit.getPlayer("Your game name").sendMessage("default ${Bukkit.pluginManager.getPermission("minecraft.debugstick.always").default}");
```
3. You should receive a line like ```default false```
4. Then execute groovy code
```groovy
Bukkit.getPlayer("Your game name").sendMessage("has permission? -> ${me.hasPermission(Bukkit.pluginManager.getPermission("minecraft.debugstick.always"))}")
```
5. You should receive a line like ```has permission? -> true``` which is incorrect.

### Plugin and Datapack List

```
Plugins (2): CodeBoxRuntime, fuck*
There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
There are no more data packs available
```

### Paper version

```
This server is running Paper version git-Paper-341 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc1752f)
You are running the latest version
Previous version: git-Paper-101 (MC: 1.18.1)
```

### Other

Groovy code for the test:
```groovy
package moe.orangemc.fuck

import org.bukkit.Location
import org.bukkit.block.Block
import org.bukkit.block.BlockFace
import org.bukkit.entity.Entity
import org.bukkit.entity.EntityType
import org.bukkit.entity.ItemFrame
import org.bukkit.entity.Player
import org.bukkit.plugin.java.JavaPlugin
import org.bukkit.util.BlockIterator
import org.bukkit.util.Vector
import org.bukkit.Bukkit

import javax.imageio.ImageIO
import java.awt.Color
import java.awt.image.BufferedImage
import java.awt.image.RenderedImage
import java.nio.file.Files

class Fuck extends JavaPlugin {
    int width = -1;
    int height = 0;
    List<List<ItemFrame>> itemFrames = new ArrayList<>()

    def unit(Player me) {
            me.sendMessage("default ${Bukkit.pluginManager.getPermission("minecraft.debugstick.always").default}")
        me.sendMessage("has permission? -> ${me.hasPermission(Bukkit.pluginManager.getPermission("minecraft.debugstick.always"))}")
    }

}
```
Direct code caused the bug: https://github.com/PaperMC/Paper/blob/3a43821c382ed99b3e64892381c263a23e9cc56a/patches/api/0152-Performance-Concurrency-Improvements-to-Permissions.patch#L42-L49
We are still looking for the original code caused the bug.

**Comment by Machine-Maker** [comment]
You link to the `Performance Concurrency Improvements to Permissions` patch doesn't look to the the case of this. That change does the same thing, just using 1 `Map#get` instead of 1 `Map#get` *and* 1 `Map#containsKey`.

I think this is actually Works as Intended. The `minecraft.debugstick.always` permission is a child permission of `minecraft` which defaults to `OP` which means all ops have that perm and its child perms.

EDIT:
Just to add on, it *might* be a bug if `minecraft.debugstick.always` shouldn't be considered a child perm of `minecraft`. If that is the case, then that's the bug. Not that the default returns false while hasPermission returns true.

**Comment by electronicboy** [comment]
My brain is semi fried;
1) as said by MM, it's just converting two lookups into a singular get rather, thus 1/2ing the work there
2) the default is 100% correct, the default is set to false, however, this is the default of the perm which doesn't consider applied inheritance, it just considers the default for the perm

3) as is being discussed on contrib, 

The default perm is registered as false, which is correct; the perm isn't granted by default, HOWEVER; the nature of it being a child of the root "Minecraft" node means that if you're op'd, it will inherit that perm, thus, the perm system is working 100% as expected here; Only thing is is the behavioral change for the debug stick with the override perm makes it work in cases for op's where it wouldn't usually this inducing a behavioral break vs vanilla

**Comment by mbax** [comment]
For reference, the issue is in what is presently upstream's 0087-Add-creative-mode-NBT-permissions.patch

```java
DefaultPermissions.registerPermission(ROOT + ".debugstick.always", "Gives the user the ability to use the debug stick in all game modes", org.bukkit.permissions.PermissionDefault.FALSE, parent);
```
