### ISSUE TITLE
/stop log

### ISSUE THREAD

**Issue by ava852546** [PaperSpigot/Paper#7858]
### Stack trace

```
https://paste.gg/p/anonymous/7a62c79a6ee74f628b69bda2dbb5c229
```

### Plugin and Datapack List

https://cdn.discordapp.com/attachments/963124069283282954/980874195267375124/unknown.png?size=4096

### Actions to reproduce (if known)

use /stop 

### Paper version

This server is running Paper version git-Paper-352 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: af3b377)
You are running the latest version
Previous version: git-Paper-350 (MC: 1.18.2)

**Comment by Machine-Maker** [comment]
Those reproduction steps are not helpful at all. Plenty of servers run /stop all the time. The stack trace mentions vault, luck perms, world edit. If you can reproduce an error on stop without plugins, this can be re-opened. If you want support for any of the plugins I listed, luck perms and world edit both have their own support discord.
