### ISSUE TITLE
Crash on world loading

### ISSUE THREAD

**Issue by Nononitas** [PaperSpigot/Paper#7859]
### Stack trace

https://pastebin.com/hLPvGsfy

### Plugin and Datapack List

https://i.postimg.cc/Jzk1ytrB/grafik.png

### Paper version

This server is running Paper version git-Paper-350 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 3f7fbe3)
You are 2 version(s) behind

### Other

Sometimes if a world gets loaded via bukkits WorldCreator (because they are not loaded from Bukkit)
the error occurs and crashes the whole server.
The world are on 1.17.1, 1.17.1 converted to 1.18.2 or also 1.18.2 .

**Comment by Nononitas** [comment]
Still happening on paper 1.19 
https://pastebin.com/rVrJLxd8

The world is a 1.19 world that is getting loaded via Bukkits WorldCreator

**Comment by electronicboy** [comment]
Having looked over such issues over the years, I literally do not see how this could happen, and the odd few that we did manage to isolate turned out to be a plugin screwing with internals, so, this is at the very least a stupidly low priority issue to me given that for the majority part, nobody else can reproduce this

**Comment by lynxplay** [comment]
Can you still replicate that with the latest 1.19.2 builds ? Concerning how little context we have here (e.g. plugins screwing with internals) it is pretty hard to replicate this or move forward with anything.

**Comment by Nononitas** [comment]
I will try give me a week

**Comment by Owen1212055** [comment]
Unfortunately I am unable to reproduce any issue that is similar to this, additionally your plugin list has expired so it's hard to tell if something else is interfering here.

Please feel free to comment whenever you are able to provide any information and this issue will be reopened.
Thank you! 😄
