### ISSUE TITLE
CreatureSpawnEvent is called infinitely

### ISSUE THREAD

**Issue by Lonewolf-12138** [PaperSpigot/Paper#7879]
### Expected behavior

I am sorry for my poor english, so please forgive me to talk with you with h ehelp of some tools(Google Translate).
This event will no longer be called after the monster has reached the limit.I have tested spigot and it is no problem.

### Observed/Actual behavior

I canceled the event and spawned the mobs using the MythicMobs plugin. Thousands of mobs have been spawned, but the event is still being called

### Steps/models to reproduce

public void onEntitySpawn(CreatureSpawnEvent e){
  LivingEntity entity = e.getEntity();
  e.setCancelled(true);
  MythicBukkit.inst().getMobManager().spawnMob(monsterName, entity.getLocation());
}

### Plugin and Datapack List

[02:47:13 INFO]: Plugins (10): CalendarEvent, CMILib, Essentials, EssentialsProtect, EssentialsSpawn, LonelyWorld, MythicMobs, ProtocolLib, RandomEvents, Residence

### Paper version

[02:38:02 INFO]: This server is running Paper version git-Paper-378 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 4b27254)

**Comment by electronicboy** [comment]
Mobs spawned by plugins do not count towards the spawn limit on paper, you can change this by setting `count-all-mobs-for-spawning` to true in paper.yml

**Comment by PedroMPagani** [comment]
You also want to make sure that the .spawnMob from MythicBukkit isn't spawning calling that event somehow, maybe indirectly, otherwise you would be having that in an infinite loop. ( Just a guess.)
