### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#7882]
Out of date

**Comment by MrSweetAnanasek-MrXLimitowany** [comment]
bukkit.yml and other have this bug...

**Comment by electronicboy** [comment]
This is an encoding issue, make sure that your files are saved as unicode

**Comment by MrSweetAnanasek-MrXLimitowany** [comment]
>  issue, make sure that your files are saved as

Um... mammam is set to UTF-8 so it should work as normal. Only in mc changes these characters to ⍰

File:

Serwer został wyłączony. Prosimy spróbować ponownie później. Życzymy miłego dnia.

Minecraft:

Serwer zosta⍰ wy⍰⍰czony. Prosimy spróbowa⍰ ponownie pó⍰niej. ⍰yczymy mi⍰ego dnia.

**Comment by aurorasmiles** [comment]
Works fine for me as well. This is a file encoding issue.
