### ISSUE TITLE
Mobs fire when out of sight

### ISSUE THREAD

**Issue by Austinthemighty** [PaperSpigot/Paper#7889]
### Expected behavior

Mobs should not fire at you when you can not see them.

### Observed/Actual behavior

Mobs like ghast and blazes will fire at you when they are out of view distance.

### Steps/models to reproduce

spawn in a few ghast and walk just far enough where they disappear, make sure to be in survival

### Plugin and Datapack List

Plugins: DriveBackupV2, floodgate, Geyser-Spigot, squaremap, squaremap-banners, squaremap-signs, squaremarker, ViaVersion, WebConsole

datapacks: [vanilla (built-in)], [file/bukkit (world)], [file/confetti creepers v2.2.2.zip (world)], [file/graves v2.8.5.zip (world)], [file/durability ping v1.1.2.zip (world)], [file/multiplayer sleep v2.6.2.zip (world)], [file/fast leaf decay v2.0.5.zip (world)], [file/VanillaTweaks_c440965.zip (world)], [file/VanillaTweaks_c809445.zip (world)], [file/VanillaTweaks_c163303.zip (world)]

### Paper version

Paper-1.18.2-375

**Comment by nwb99** [comment]
I've had this issue for a while but I figured it was because I changed my settings lower to help with performance... Glad it isn't just me

**Comment by e-im** [comment]
You can raise `entity-tracking-range` in spigot.yml to be able to see entities from a further distance

**Comment by lynxplay** [comment]
Closing this, as this is generally a non-issues. Just because you cannot see an entity does not mean an entity does not see you on the server side of things and can target you.

As laid out by sulu, the entity tracking range values allow you to configure in what distance entities are synced.
