### ISSUE TITLE
[dev/1.19] netty-transport-native-epoll-4.1.76.Final-linux-x86_64.jar missing in libraries/

### ISSUE THREAD

**Issue by velnias75** [PaperSpigot/Paper#7904]
### Stack trace

```
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.papermc.paperclip.Main.main(Main.java:26)
Caused by: java.lang.IllegalStateException: io/netty/netty-transport-native-epoll/4.1.76.Final/netty-transport-native-epoll-4.1.76.Final-linux-x86_64.jar not found in our jar, and no original jar provided
        at io.papermc.paperclip.FileEntry.extractFile(FileEntry.java:78)
        at io.papermc.paperclip.Paperclip.extractEntries(Paperclip.java:217)
        at io.papermc.paperclip.Paperclip.extractFiles(Paperclip.java:188)
        at io.papermc.paperclip.Paperclip.extractAndApplyPatches(Paperclip.java:153)
        at io.papermc.paperclip.Paperclip.setupClasspath(Paperclip.java:72)
        at io.papermc.paperclip.Paperclip.main(Paperclip.java:28)
        ... 5 more
```

### Plugin and Datapack List

`Plugins (6): Luegenpresse, PangaeaBlocks, PinkBull, RainManNG, SEC, XItemsRemover`

### Actions to reproduce (if known)

On Linux (*Ubuntu Focal 20.04*):

* `./gradlew runReobf` to get a run directory
*  in this `run` dirrectory in a console: `/opt/graalvm-ce-java17-22.1.0/bin/java -Xmx1536M -jar ../build/libs/paper-bundler-1.19-R0.1-SNAPSHOT-reobf.jar nogui`

### Paper version

`Paper version git-Paper-"da80273" (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: da80273 on dev/1.19)`

### Other

Manually copying the `jnetty-transport-native-epoll-4.1.76.Final-linux-x86_64.jar`  into `libraries/io/netty/netty-transport-native-epoll/4.1.76.Final/` got the server to start.

**Comment by jpenilla** [comment]
Should be fixed by `https://github.com/PaperMC/paperweight/commit/c4d0c5cb24e9382bbd92fea1cebe9c6be7ea4686`, which is in paperweight 1.3.7-SNAPSHOT. There's a couple more things I need to check and test before doing a paperweight release, so if you need a 1.19 bundler/paperclip use the paperweight snapshot for now.

**Comment by velnias75** [comment]
Now even my workaround doesn't work anymore 😭 Same stacktrace.

Tried `./gradle cleanCache` and building anew with `--refresh-dependencies`

**Comment by lynxplay** [comment]
Building using the paperweight 1.3.7-LOCAL-SNAPSHOT works fine for me. Are you properly using the paperweight snapshot ?

**Comment by velnias75** [comment]
Just building as it is delivered by git

**Comment by electronicboy** [comment]
There are known issues with paperweight and 1.19, requiring a newer version of paperweight

**Comment by lynxplay** [comment]
You will, as jmp pointed out, build it using the current paperweight snapshot.
For this

1. Clone paperweight (`git clone git@github.com:papermc/paperweight.git`)
2. Install paperweight into your local maven repo using `gradle publishToMavenLocal`
3. Use the snapshot in paper:
```patch
diff --git a/build.gradle.kts b/build.gradle.kts
index 8ad25ffdc..3d8185efe 100644
--- a/build.gradle.kts
+++ b/build.gradle.kts
@@ -5,7 +5,7 @@ plugins {
     java
     `maven-publish`
     id("com.github.johnrengelman.shadow") version "7.1.2" apply false
-    id("io.papermc.paperweight.core") version "1.3.6"
+    id("io.papermc.paperweight.core") version "1.3.7-LOCAL-SNAPSHOT"
 }
 
 allprojects {
diff --git a/settings.gradle.kts b/settings.gradle.kts
index 18cf95a32..8e9e0cad1 100644
--- a/settings.gradle.kts
+++ b/settings.gradle.kts
@@ -2,6 +2,7 @@ import java.util.Locale
 
 pluginManagement {
     repositories {
+        mavenLocal()
         gradlePluginPortal()
         maven("https://repo.papermc.io/repository/maven-public/")
     }
```

**Comment by velnias75** [comment]
> There are known issues with paperweight and 1.19, requiring a newer version of paperweight

Ups, missed to read that paperweight wasn't released. I hust woke up a few minutes before :-)

**Comment by velnias75** [comment]
Now it works :-D Thanks! 👍🏻

**Comment by jpenilla** [comment]
fixed https://github.com/PaperMC/Paper/commit/3690440aaa5a65a0b3248f862f31723329dbe8e5
