### ISSUE TITLE
Server locked itself, everything works except I can no longer place/break blocks anywhere

### ISSUE THREAD

**Issue by PiTiLeZarD** [PaperSpigot/Paper#7918]
### Expected behavior

That everything keeps working the way it was? I didn't change anything I'm not sure what did it

### Observed/Actual behavior

I can no longer break or place blocks anywhere (I tried the spawn protection thingy but I'm op anyway and nothing does it)

### Steps/models to reproduce

I don't actually know that :/ I played yesterday no worries, this morning it didn't work. I also played a backup that worked. (backup is old so I'd rather fix it if possible)

### Plugin and Datapack List

None

### Paper version

I had 339 but I updated to 379 and it didn't fix it.

### Other

I'm on 11000 days running which I thought was an odd coincidence but I couldn't find anything anywhere about that number being a limit of some sort. I'm also able to punch cows, mobs, open doors, smelt thing basically everything seems to work but I can't break blocks :/ Any help would be gratefully received!

**Comment by Machine-Maker** [comment]
Are you in adventure mode?

**Comment by e-im** [comment]
Thanks for reaching out! Unfortunately, the issue tracker is not the best place to get support and is only for bugs, which this doesn't seem like it is. 
Please come by our [Discord](https://discord.gg/papermc) (`#paper-help` channel), [forums](https://forums.papermc.io), or [IRC](https://webchat.esper.net/?channels=paper-help) for support.

**Comment by PiTiLeZarD** [comment]
> Are you in adventure mode?

yes

**Comment by PiTiLeZarD** [comment]
> Thanks for reaching out! Unfortunately, the issue tracker is not the best place to get support and is only for bugs, which this doesn't seem like it is. Please come by our [Discord](https://discord.gg/papermc) (`#paper-help` channel), [forums](https://forums.papermc.io), or [IRC](https://webchat.esper.net/?channels=paper-help) for support.

sorry about that, I'll get on discord then, cheers!
