### ISSUE TITLE
1.19 experimental 5 join error

### ISSUE THREAD

**Issue by JaTiTV** [PaperSpigot/Paper#7924]
### Stack trace

https://paste.gg/p/JaTiTV/5be11bc64afd43da9651457600678020

### Plugin and Datapack List

Plugins (8): F3NPerm, LoreEditor, LuckPerms, NBTAPI, T2C-LuckyBox, T2CodeLib, Vault, XConomy

### Actions to reproduce (if known)

i have the problem with 2 accounts that this error comes. with 3 others it works. Both the experimental-4 / experimental-5

i also tried it with a complete freshly installed server without polugins. Same problem

### Paper version

[15:42:46 INFO]: This server is running Paper version git-Paper-"02b5ec4" (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 02b5ec4 on dev/1.19)
Error obtaining version information
Previous version: git-Paper-"9b6fb2f" (MC: 1.19)

**Comment by Machine-Maker** [comment]
Did you try restarting your game? like closing the client and the launcher and then re-opening it?

**Comment by electronicboy** [comment]
This looks like literally nothing to do with us, your auth key has expired

**Comment by JaTiTV** [comment]
yes we have it is 2 different pcs and we have restarted them ourselves

**Comment by electronicboy** [comment]
We have 0 control over this, your client sent a key which according to the servers clock has already passed; Either you need to fully restart, or, check the system clock on the server
