### ISSUE TITLE
Chunk Reset

### ISSUE THREAD

**Issue by Gouuu0** [PaperSpigot/Paper#7927]
### Expected behavior

Chunk should not reset randomly when we load them

### Observed/Actual behavior

Sometimes when you load a chunk on paper, it reset and put this message in the console : (in red)

![unknown-8](https://user-images.githubusercontent.com/90638609/173108533-f316e17d-63c9-46e3-bc46-8d52e910a36b.png)

This happen even when the chunk is not loaded for the first time after an upgrade or going from spigot to paper for example. Just disconnecting and reconnecting can reset the chunk.

### Steps/models to reproduce

Unload and reload the chunk, you can also disconnect and reconnect and the chunk will sometimes reset. The issue can be clearly seen in the logs

### Plugin and Datapack List

None

### Paper version

Experimental 5

**Comment by Owen1212055** [comment]
Was this world created on the previous experimental? Are you able to reproduce this on a newly generated world?

**Comment by electronicboy** [comment]
This is not experimental 5

**Comment by Brokkonaut** [comment]
It is version 4a51a54... - that is the version before the light fix
