### ISSUE TITLE
Adventure colors prevent formatting tags from closing in console

### ISSUE THREAD

**Issue by BillyGalbreath** [PaperSpigot/Paper#7939]
### Expected behavior

Closing formatting tags in console message stops the formatting, even when using colors.

Without colors:
![image](https://user-images.githubusercontent.com/332527/173176839-8d7b9e07-7e90-494b-aadf-348c9d1c5a9e.png)

With colors:
![image](https://user-images.githubusercontent.com/332527/173176922-05f56318-94c5-4663-ab3a-7266b8356d49.png)

### Observed/Actual behavior

Closing formatting tags in console message does not stop the formatting, but only when using colors.

Without colors:
![image](https://user-images.githubusercontent.com/332527/173176877-f4a6220a-56f9-4f4e-9d16-70595d50924f.png)

With colors:
![image](https://user-images.githubusercontent.com/332527/173176859-006fde7e-f255-486a-ad6e-043b1c3246b9.png)

### Steps/models to reproduce

```java
Bukkit.getConsoleSender().sendMessage(
    MiniMessage.miniMessage().deserialize("<red>Testing <bold>some</bold> <i>minimessage</i>")
);
```

This gets around the problem, but is inconvenient.
```java
Bukkit.getConsoleSender().sendMessage(
    MiniMessage.miniMessage().deserialize("<red>Testing</red> <red><bold>some</bold></red> <red><i>minimessage</i>")
);
```

### Plugin and Datapack List

Only a test plugin with the above mentioned code.

No datapacks.

### Paper version

I'm assuming since first build adventure was added in.

### Other

The fix mentioned in https://github.com/PaperMC/Paper/issues/7938 does not solve this issue, thus I made it a separate issue.

**Comment by lynxplay** [comment]
This is the result of the HexFormattingConverter not properly implementing legacy colour coding when translating to ansi colours.
Whoever wants to fix this, the implementation should be rather straight forward.

In legacy colours, which is what the HexFormattingConverter uses as an intermediate format between components and ansi coloured text, colours reset any form of existing formatting when applied. (Seen implemented [here](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/util/CraftChatMessage.java#115). The HexFormattingConverter however simply does not respect this quirk of legacy colours and hence simply adds the correct ansi code for defined colour without previously resetting decorations like underlined or itallic.
