### ISSUE TITLE
1.19 failed to bind port

### ISSUE THREAD

**Issue by Blzd87** [PaperSpigot/Paper#7946]
### Stack trace

https://gist.github.com/1bc7cf96782e65de661b1014bcd48b34

### Plugin and Datapack List

SafariNet-1.15.36-SNAPSHOT.jar
SaveDeathDrops.jar
SkinsRestorer.jar
SpecializedCrates.jar
Statz-1.6.2.jar
TAB-3.1.1-pre1.jar
Tether-2.3.0-SNAPSHOT.jar
TogglePvP.jar
UltimateChairs.jar
UltimateTimber-2.3.2.jar
Vault.jar
VoidGen-2.2.jar
WorldBorder.jar
worldedit-bukkit-7.2.10.jar
worldguard-bukkit-7.0.7-dist.jar
WorldGuardExtraFlags.jar
AntiBow.jar
AreaShop.jar
ArmorStandTools.jar
AsyncWorldEdit-3.9.4.jar
Autorank_5.1.3.jar
BestTools-2.2.0.jar
BetterRTP-3.4.2-2.jar
Brewery-3.1.jar
ChatManager_3.7.7.jar
ChestSort-13.0.5.jar
Clearlag.jar
CMILib1.2.0.0.jar
CMILib1.2.0.1.jar
CoreProtect-21.2.jar
CreativeItemControl-4.2.4.jar
DeathMessages-1.4.12.jar
DoorsReloaded-1.3.1.jar
Elevator.jar
EpicSpawners-7.2.7.jar
EssentialsX-2.19.4.jar
EssentialsXAntiBuild-2.19.4.jar
EssentialsXChat-2.19.4.jar
EssentialsXProtect-2.19.4.jar
EssentialsXSpawn-2.19.4.jar
gdhooks-bukkit-0.7-DEV11.jar
griefdefender-bukkit-2.2.0.jar
Harbor-1.6.3.jar
HeadDatabase-4.16.1.jar
HolographicDisplays.jar
Jobs5.0.3.0.jar
KixsAutoAnnouncer-1.3.3.jar
LightBlockZ.jar
Lottery.jar
LuckPerms-Bukkit-5.4.21.jar
mcMMO.jar
MineChess.jar
Mjolnir-1.3.4.jar
MobFarmManager2.0.1.0.jar
Multiverse-Core-4.3.1.jar
Multiverse-Inventories-4.2.2.jar
Multiverse-Portals-4.2.1.jar
NexEngine_2.0.4.jar
OpenInv.jar
PlaceholderAPI-2.11.1.jar
PlayerKits.jar
PlayerWarps 6.13.2.jar
ProtocolLib.jar
QSFindItemAddOn-1.9.2.jar
QuickShop-5.1.0.7.jar
realestate-bukkit-1.5.0-pre6.jar

### Paper version

paper-1.19-3 build

**Comment by electronicboy** [comment]
> Cannot assign requested address

Invalid configuration, the IP address you set in the config is not available on the machine

**Comment by Blzd87** [comment]
> > Cannot assign requested address
> 
> Invalid configuration, the IP address you set in the config is not available on the machine

omg I can't believe i missed that one simple thing.

Build loads now. but not without heaps of errors. but i assume most of those errors are still getting ironed out.
