### ISSUE TITLE
Add method to update title when inventory is open

### ISSUE THREAD

**Issue by broken1arrow** [PaperSpigot/Paper#7950]
### Is your feature request related to a problem?

right now I need code it self for every minecraft version (so need use nms). 

### Describe the solution you'd like.

I made my own solution or suggestion here. Make pull is not easy (i will take weeks or years to even try set it up). 

Ether way player is not needed if it set in the class before.

```java

import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.serializer.gson.GsonComponentSerializer;
import net.minecraft.network.chat.IChatBaseComponent;
import net.minecraft.network.protocol.game.PacketPlayOutOpenWindow;
import net.minecraft.world.inventory.Containers;
import org.bukkit.craftbukkit.v1_18_R2.entity.CraftPlayer;
import org.bukkit.entity.Player;

public class Inventoryupdate {

	public void updateTitle(Player player, String text) {

		IChatBaseComponent icbc = IChatBaseComponent.ChatSerializer.b("'" + text + "'");
		final int windowid = ((CraftPlayer) player).getHandle().bV.j;
		final Containers<?> container = ((CraftPlayer) player).getHandle().bV.a();
		PacketPlayOutOpenWindow windowPacket = new PacketPlayOutOpenWindow(windowid, container, icbc);
		((CraftPlayer) player).getHandle().b.a(windowPacket);
	}
	public void updateTitle(Player player, Component message) {
		IChatBaseComponent icbc = IChatBaseComponent.ChatSerializer.a(GsonComponentSerializer.gson().serialize(message));
		final int windowid = ((CraftPlayer) player).getHandle().bV.j;
		final Containers<?> container = ((CraftPlayer) player).getHandle().bV.a();
		PacketPlayOutOpenWindow windowPacket = new PacketPlayOutOpenWindow(windowid, container, icbc);
		((CraftPlayer) player).getHandle().b.a(windowPacket);
	}
}

```

### Describe alternatives you've considered.

I needed code it my self and to cover several minecraft versions I need do like this https://pastebin.com/91XdRiFw. I know I could import every minecraft version exist, instead to what I use here.

### Other

Video on how it works: https://youtu.be/QR6pZ7fJQFA I have run this async also with no issue (some cases you need run it async).

**Comment by Doc94** [comment]
Update the title of inventory open? like `HumanEntity#getOpenInventory#updateTitle(String title)`?

**Comment by broken1arrow** [comment]
> Update the title of inventory open? like `HumanEntity#getOpenInventory#updateTitle(String title)`?

is that a thing or a suggestion were it should be added?

**Comment by Doc94** [comment]
> > Update the title of inventory open? like `HumanEntity#getOpenInventory#updateTitle(String title)`?
> 
> is that a thing or a suggestion were it should be?

nono.. a suggest for any who wanna open a PR... or maybe i can check.. but things with packets its hard to use...

**Comment by lynxplay** [comment]
Might make more sense to simply add an overload to `openInventory` that classifies if the opened inventory should allocate a new menu id.

**Comment by broken1arrow** [comment]
> > > Update the title of inventory open? like `HumanEntity#getOpenInventory#updateTitle(String title)`?
> > 
> > 
> > is that a thing or a suggestion were it should be?
> 
> nono.. a suggest for any who wanna open a PR... or maybe i can check.. but things with packets its hard to use...

Yeah trust me, when working with this I get all sorts of strange behaviours. Specially when set wrong inventory size (it then take over players inventory if size is bigger an the container inventory). 

But the code I provide is 100% working. But not battle tested on 100 different servers. 

So everything you need is added in my code, but you perhaps want do change how you import the methods?

**Comment by broken1arrow** [comment]
> Might make more sense to simply add an overload to `openInventory` that classifies if the opened inventory should allocate a new menu id.

You get new id when open a inventory (server restart reset it). if you talked about window id.

**Comment by nopjar** [comment]
Personally, I think that's a cool feature. I will open a PR and the Paper Team will then decide if they want it or not.

**Comment by nopjar** [comment]
Okay this is a little bit more tuff than I thought. At least as long as we want the new title to take its place in the server as well so a `InventoryView#title()` returns the updated title. If we just want to send the packet itself this is no problem.

**Comment by broken1arrow** [comment]
> Okay this is a little bit more tuff than I thought. At least as long as we want the new title to take its place in the server as well so a `InventoryView#title()` returns the updated title. If we just want to send the packet itself this is no problem.

How I use it I only send the packet. I don't think on the title method, but for me is it fine if it only send a update packet.

**Comment by broken1arrow** [comment]
> Personally, I think that's a cool feature. I will open a PR and the Paper Team will then decide if they want it or not.

Yeah if you use gradients (recommend then use method a in ChatSerializer , because b don´t support colors same way). Is not hard to use that method (it support json directly (but need convert it to string)). 

So you can then animate the title with gradients or other things.

**Comment by Warriorrrr** [comment]
This was implemented by upstream in https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/ecfa559ae8821e3e2677fe168b536333f71149aa, adding component methods is currently tracked by #9189.

**Comment by broken1arrow** [comment]
> This was implemented by upstream in https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/ecfa559ae8821e3e2677fe168b536333f71149aa, adding component methods is currently tracked by #9189.

So spigot does update the api with new functions. So this will update the title while the inventory is open?

**Comment by Warriorrrr** [comment]
If the inventory supports it, yeah
