### ISSUE TITLE
Plugins update feature doesn't work on 1.19.

### ISSUE THREAD

**Issue by mmattbtw** [PaperSpigot/Paper#7956]
### Expected behavior

The expected behavior is that the plugins in the `/plugins/update` folder get updated/moved into `/plugins/`. At the end `/plugins/update` should be empty.

### Observed/Actual behavior

Nothing was changed, `/plugins/` were still the old plugins and `/plugins/update` was not empty.

### Steps/models to reproduce

1. Put outdated plugins in `/plugins`
2. Put new updated plugins in `/plugins/update`
3. Restart server
4. Observe that `/plugins/update` is not empty.

### Plugin and Datapack List

Plugins: `AntiAC, DeathChestPro, DiscordSRV, dynmap, Essentials, EssentialsChat, FoundDiamonds, GriefPrevention, LiteBans, LiveStats*, Logger, LuckPerms, OreAnnouncer, Orebfuscator, PlugManX (PlugMan), ProtocolLib, sleep-most, TAB, TPPets*, Vault, ViaBackwards, ViaVersion, WorldEdit`

Datapacks: `There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]`

### Paper version

```This server is running Paper version git-Paper-7 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 90050ff)
You are running the latest version
Previous version: git-Paper-358 (MC: 1.18.2)
```

### Other

I already asked in `#paper-help` and someone told me to submit an issue, sorry if there is this is a duplicate issue I searched `plugins update` in GitHub and nothing came up :p

**Comment by lynxplay** [comment]
I cannot replicate this with a simple self-written setup on Paper version git-Paper-7 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 90050ff).

Did one of your plugins change its name (in the `plugin.yml`) ? That is the metric the updated paper logic goes by when looking for an update for your plugin in the `plugins/update` folder.

If you have an example we can replicate, e.g. an outdated and new jar, please provide them so I can attempt to replicate it.

**Comment by mmattbtw** [comment]
One I used was ViaVersion

New: https://ci.viaversion.com/job/ViaVersion/611/artifact/build/libs/ViaVersion-4.3.1.jar
Outdated (4.2.1): https://github.com/ViaVersion/ViaVersion/releases/download/4.2.1/ViaVersion-4.2.1.jar

**Comment by lynxplay** [comment]
Thanks for sharing the jars.
They worked perfectly fine for me through the update process, I cannot replicate your issue. Looking through the patch history, it was not *really* touched by the update at all, no new changes were added.

Can you still replicate this on your server with ViaVersion ?
If so, we should take this back to discord and I can look into it with you, but I am afraid I will have to close this as cannot-reproduce.

**Comment by mmattbtw** [comment]
Just going to jump in here to provide the solution:

The actual problem was that the plugins folder and everything in it was owned by the `root` user, and the server was running under the `minecraft` user, so that's why it couldn't replace the plugin. `chown -R minecraft plugins/` solved it 👍
