### ISSUE TITLE
Error with auto-migrating the config

### ISSUE THREAD

**Issue by Code-Josh** [PaperSpigot/Paper#7957]
### Expected behavior

No error in the console

### Observed/Actual behavior

After updating i have got the Error:
[23:46:40 ERROR]: [io.papermc.paper.configuration.serializer.collections.MapSerializer] Could not deserialize value 128 into class io.papermc.paper.configuration.WorldConfiguration$Entities$Spawning$DespawnRange at [entities, spawning, despawn-ranges, hard]
[23:46:40 ERROR]: [io.papermc.paper.configuration.serializer.collections.MapSerializer] Could not deserialize value 32 into class io.papermc.paper.configuration.WorldConfiguration$Entities$Spawning$DespawnRange at [entities, spawning, despawn-ranges, soft]
twice at startup.
I didnt saw any other error. Everything alse worked just Fine.

### Steps/models to reproduce

I have updated from paper version 1.18.2-379 to paper version 1.19-7. After auto-migrating the config, I have had this missing twice in the console every time I start it. Simply quite at the beginning and then quite at the end. I didnt changed the config after the auto-migrating

### Plugin and Datapack List

Plugins (8): Essentials, EssentialsChat, EssentialsSpawn, LuckPerms, ServerBackup*, Vault, WorldEdit, WorldGuard
There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]

### Paper version

git-Paper-7 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 90050ff)
Previous version: git-Paper-378 (MC: 1.18.2)

### Other

paper.yml(before update):
[paper.yml.txt](https://github.com/PaperMC/Paper/files/8886918/paper.yml.txt)

Error Log(after Update):
[2022-06-12-16.log](https://github.com/PaperMC/Paper/files/8886911/2022-06-12-16.log)

Config After Update:
[paper-world-defaults.yml.txt](https://github.com/PaperMC/Paper/files/8886910/paper-world-defaults.yml.txt)
[paper-global.yml.txt](https://github.com/PaperMC/Paper/files/8886919/paper-global.yml.txt)

**Comment by Machine-Maker** [comment]
Can you post your paper.yml before updating? it looks like you tried to but I don't see the link to it.

**Comment by Code-Josh** [comment]
yes i had to edit the files

**Comment by Machine-Maker** [comment]
I'm not sure how your config ended up in such a state, but just go ahead and delete the offending lines. In `paper-world-defaults.yml` delete `entities.spawning.despawn-ranges.hard` and `entities.spawning.despawn-ranges.soft`. They are now per-category as you can see by the surrounding lines.

**Comment by Code-Josh** [comment]
No more error messages are shown after I deleted them. I just tried to replicate the error again and it always comes out the same. Strange but thanks

**Comment by Machine-Maker** [comment]
Yeah, those extra `hard` and `softs` should've been removed way back when your config moved from version 23 to a higher version. So not sure what happened there. I feel like its just a one-off problem. If more people come with the issue, we can add something to remove those extra bits.
