### ISSUE TITLE
Filter plugin.yml's libraries for existing libs

### ISSUE THREAD

**Issue by velnias75** [PaperSpigot/Paper#7961]
### Is your feature request related to a problem?

In `plugin.yml` you can define libraries to get downloaded and installed into the `libraries` folder.
I have a plugin that uses this feature to load the `adevnture-api` which is already included in `paper`.

### Describe the solution you'd like.

It would be nice to have a way to avoid such *doubled* libraries.

### Describe alternatives you've considered.

**none**

**Comment by Andre601** [comment]
Isn't this related to #7955?

**Comment by MiniDigger** [comment]
its related but different. 
#7955 is allowing the dev to have a different entry point with different settings, one of the benefits would be not downloading libs that paper provides.
this issue here suggests to do that automatically without the dev needing to do anything

**Comment by electronicboy** [comment]
I'm not fond of the notation of having what would potentially be a hardcoded list of libs not to allow loading

**Comment by Andre601** [comment]
Same.
It would make sence on one side, but also require more maintenance for devs here.

**Comment by Owen1212055** [comment]
Functionality-wise, #8108 will cover this by being able to use the plugin loader system which allows you to dynamically add libraries during runtime. This will allow you to do any sort of checks if the library already exists.

**Comment by Owen1212055** [comment]
Resolved by https://github.com/PaperMC/Paper/pull/8108
