### ISSUE TITLE
High Ping Issues...

### ISSUE THREAD

**Issue by SaumyaKhobragade** [PaperSpigot/Paper#7964]
### Timings or Profile link

https://timings.aikar.co/?id=51bd0a7056084d7b82ffc3e4ce7a72bf

### Description of issue

My server, when it was 1.18, gave me a ping of 30 - 40. But now when I switched to 1.19, it is giving me a ping of 250 - 400. I tried restarting, even checked my internet...
![image](https://user-images.githubusercontent.com/78600365/173333787-26687953-f50c-40e0-a071-c323fa7d27fb.png)

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/78600365/173333946-5c8653cb-fea0-4021-9354-004d652607fb.png)
![image](https://user-images.githubusercontent.com/78600365/173334015-e9b6693d-6340-4dfe-9966-a33c263dd32b.png)

Plugins: Plugins (5): DiscordSRV floodgate, Geyser-Spigot, GriefPrevention, LoginSecurity

Datapacks: There are 4 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/SpawnEggCrafting (1).zip (world)], [file/extrarecipes-e3351 (1).zip (world)] There are no more data packs available.

### Server config files

bukkit.yml: https://paste.gg/p/anonymous/fc907d075fb24b319a2c47dba04e7b90

spigot.yml: https://paste.gg/p/anonymous/834e40d03aa94d549c6610147648d90a

paper-global.yml: https://paste.gg/p/anonymous/6f2afa345b094ccd9b850c4e6a131573

paper-world-defaults.yml: https://paste.gg/p/anonymous/01b907b5fe4e4979a98966c66345b608

server.properties: https://cdn.discordapp.com/attachments/912335716300750909/985856405749788712/unknown.png
 and https://cdn.discordapp.com/attachments/912335716300750909/985856453590011904/unknown.png

### Paper version

This server is running Paper version git-Paper-8 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: e4f5e1c)
You are running the latest version
Previous version: git-Paper-379 (MC: 1.18.2)

**Comment by gamer50082** [comment]
is it possible for u to send a .zip or .rar file of the whole server for me to test

**Comment by gamer50082** [comment]
also it could be the ping bug since purpur a fork also gave me the same info

**Comment by SaumyaKhobragade** [comment]
I actually can't swnd the files, the server size has reached 4 to 5 gbs...

**Comment by SaumyaKhobragade** [comment]
A ping bug?

**Comment by gamer50082** [comment]
like its showing a wrong ping outside but on-game u get good ping

**Comment by gamer50082** [comment]
have u tried to add ping plugins to show u ur ping ingame

**Comment by gamer50082** [comment]
u should test plugin ping checker to verify this is a bug

**Comment by SaumyaKhobragade** [comment]
I check from TAB plugin and ya the ping is still high...

**Comment by gamer50082** [comment]
oh then idk
