### ISSUE TITLE
Unable to read interact client packet.

### ISSUE THREAD

**Issue by eindaniels** [PaperSpigot/Paper#7965]
### Expected behavior

Clear Chat (The Error message pops out from the Chat)

### Observed/Actual behavior

![Lunar Client (1 19-4d6392e_master) 13 06 2022 13_39_31](https://user-images.githubusercontent.com/101058306/173347750-09f44a9a-342e-405a-b5c4-93cd1ba3d060.png)

### Steps/models to reproduce

It pop out from the Chat but I dont know how to make that.

### Plugin and Datapack List

Citizens, Holographicdisplay, Essentialsx

### Paper version

git-Paper-8 (MC: 1.19)

**Comment by kennytv** [comment]
That's one of your plugins
