### ISSUE TITLE
Fatal Crash at Runtime

### ISSUE THREAD

**Issue by theiamgeek** [PaperSpigot/Paper#7972]
### Expected behavior

The server should start.

### Observed/Actual behavior

The server crashes and burns with a `org.spongepowered.configurate.serialize.CoercionFailedException: [entities, behavior, pillager-patrols, spawn-delay, per-player] of type java.lang.Boolean: Failed to coerce input value of type class java.lang.String to boolean` exception (see attached logfiles).
[paper-1.19-10_exception_on_load.log](https://github.com/PaperMC/Paper/files/8893485/paper-1.19-10_exception_on_load.log)
[crash-2022-06-13_18.12.08-server.txt](https://github.com/PaperMC/Paper/files/8893493/crash-2022-06-13_18.12.08-server.txt)

### Steps/models to reproduce

I am using an existing map coming over from paper 1.18.2-366. Running GraalVM Community version 22.1.0.

### Plugin and Datapack List

CustomTime version 2.1.1
Datapacks (output from Spigot): `There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]There are no more data packs available`

### Paper version

1.19-10

Would include full-text output as requested but the server will not completely finish starting.

### Other

Subbing in Spigot version `This server is running CraftBukkit version 3525-Spigot-56be6a8-8f097b9 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT)` starts without issue.

**Comment by electronicboy** [comment]
bad paper config, please provide your original config file and the new ones

**Comment by theiamgeek** [comment]
> bad paper config, please provide your original config file and the new ones

I don't seem to have a paper.yml file at all anymore. l must have cleaned it up while fiddling around with different server distros yesterday.

Why wouldn't it be generating a new one on first start?

![image](https://user-images.githubusercontent.com/64332557/173421754-16c53a8c-fe67-4441-ac40-9feee4ed5c38.png)

This is the paper.yml I was using on 1.18.2 that I pulled from a server backup:
[paper.yml.txt](https://github.com/PaperMC/Paper/files/8893610/paper.yml.txt)

After restoring the copy of paper.yml linked just above to the server's directory, I get the following crash:
[paper-1.19-10_exception_on_load-1.log](https://github.com/PaperMC/Paper/files/8893649/paper-1.19-10_exception_on_load-1.log)
[crash-2022-06-13_18.45.00-server.txt](https://github.com/PaperMC/Paper/files/8893653/crash-2022-06-13_18.45.00-server.txt)

**Comment by electronicboy** [comment]
configs are in the config folder

**Comment by theiamgeek** [comment]
> configs are in the config folder

Ahhh. They've been moved!
[paper-world-defaults.yml.txt](https://github.com/PaperMC/Paper/files/8893684/paper-world-defaults.yml.txt)
[paper.yml.txt](https://github.com/PaperMC/Paper/files/8893685/paper.yml.txt)

**Comment by electronicboy** [comment]
So, basically, your original config was bad, `          per-player: fals` for the pillager-patrols setting, you'll need to fix your config manually

**Comment by theiamgeek** [comment]
> So, basically, your original config was bad, ` per-player: fals` for the pillager-patrols setting, you'll need to fix your config manually

Opps. Sorry for opening what I guess is an entirely invalid issue. Thanks for catching that, I guess the old config handler was far more forgiving than the new one.

I guess at the very least, this might give you all an idea of where some more descriptive error messages might be needed.

Thanks for all you do for this project!
