### ISSUE TITLE
Teams are automatically deleting

### ISSUE THREAD

**Issue by LahmacunDurenMaydanoz** [PaperSpigot/Paper#7978]
### Expected behavior

When a team is created with "/team" , if the server is shut down before someone joins that team, that team will be deleted when the server is restarted. Normally, all teams must be registered, even if they are not members.

### Observed/Actual behavior

All empty teams are deleted when you return to the game

### Steps/models to reproduce

Create multiple teams with "**/team**" eg 3 or more  and join one. Then save and close the server **"/stop"** , when you open it again, all empty teams will be deleted except the team you joined.

### Plugin and Datapack List

No plugin
No datapack

### Paper version

This server is running Paper version git-Paper-13 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: b844286)
You are running the latest version

**_Same bug applies to 1.18.2_**

 This server is running Paper version git-Paper-385 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: ef5d95f on ver/1.18.2)
You are running the latest version

### Other

use-vanilla-world-scoreboard-name-coloring: false or true     does not affect the problem

Same bug applies to **1.18.2** and **1.19**

**Comment by kennytv** [comment]
Same thing happens in Vanilla

**Comment by NoahvdAa** [comment]
Do you have `save-empty-scoreboard-teams` set to false by any chance?

**Comment by LahmacunDurenMaydanoz** [comment]
Thank you it worked, but why is it set to false by default?
---
Solution for those who have the same problem
For 1.18.x Change the `save-empty-scoreboard-teams` setting to `true` in `paper.yml` file.
For 1.19, You need to make the same settings in the `paper-global.yml` file in the `config` file instead of the paper.yml file.

**Comment by kennytv** [comment]
Presumably with the intention of cleaning up the mess a lot of scoreboard plugins leave behind
