### ISSUE TITLE
Add a method to Player which sends a chat message FROM the Player with a Component parameter. 

### ISSUE THREAD

**Issue by accLarson** [PaperSpigot/Paper#7982]
### Is your feature request related to a problem?

No, my suggestion is not related to a problem. `Player#chat` [link](https://jd.papermc.io/paper/1.19/org/bukkit/entity/Player.html#chat(java.lang.String)) does not accept a Component (accepts a string only) but the methods provided by Kyori Adventure allow a developer to convert a Component into a String maintaining many but not all of the component tags parsed. 

### Describe the solution you'd like.

Simplify the process of having a `Player` send a chat message provided in a Adventure Component format. Allow developers to pass a component directly to some Player method. Possibly overload `Player#chat`, possibly a new method `Player#chatMessage`

### Describe alternatives you've considered.

I've not considered any alternatives. It is already possible to convert `Component` objects to a `String` equivalent including most formatting tags built into Adventure.

**Comment by Machine-Maker** [comment]
That method is meant to simulate receiving a chat packet from the client. The client **also** doesn't send components, only strings. So I don't think it makes sense to have a Component version. The javadocs even mention it will also run commands. I'm not sure how that works with a component. 

If you want to send a message as a player, you can use the sendMessage methods with an Identity parameter (although on 1.19 these do literally nothing, as chat signing is not supported, and all messages are system messages).

**Comment by accLarson** [comment]
Thanks for the response. 
Which object type has a #sendMessage method with an identity parameter? Certainly not Player#sendMessage unless I'm misunderstanding.

**Comment by electronicboy** [comment]
the sendMessage methods have such a thing, however with modern MC that's going to become useless; sending a chat message out from a player as a component is also generally seemingly on the wayward of not being supported

**Comment by accLarson** [comment]
So the only way to send a component to chat from a player is to first use adventure utilities to convert it to a String? (assuming the component only has basic text formatting color, italics, etc)

**Comment by electronicboy** [comment]
Yes, players can't chat with components, mojangs logic doesn't support pulling in components for basic chat, the only thing that have close to that requires a signed chat message, and even there it also expects to have the plain text string

**Comment by accLarson** [comment]
Okay, thank you for the quick responses.
