### ISSUE TITLE
Glowberry is 100% yielding

### ISSUE THREAD

**Issue by Owlchemist** [PaperSpigot/Paper#7984]
### Expected behavior

According to the wiki, a vine should have 1 in 9 chance to get a glowberry per block.

### Observed/Actual behavior

In paperMC, every block of growth of every vine is getting a glowberry.

### Steps/models to reproduce

Go into creative mode, give yourself a glowberry under food category, and place a whole bunch along any ol' ledge, then wait for a few minutes for them to grow in.

### Plugin and Datapack List

For my test world, I was not using any plugins or datapacks.

### Paper version

[14:13:50 INFO]: This server is running Paper version git-Paper-14 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 48f7a1a)
You are running the latest version
Previous version: git-Paper-8 (MC: 1.19)

**Comment by chickeneer** [comment]
I have confirmed the bug. Looking into the code side of it now.

**Comment by chickeneer** [comment]
https://github.com/PaperMC/Paper/blob/master/patches/server/0796-Fix-kelp-modifier-changing-growth-for-other-crops.patch#L28

This line is the issue. 0.11F is the desired default. The spigot config has a default of 100, so overall ends up with a value of (2200%). The spigot config has to be an integer, so no current way to set it low enough to return default mechanics. Will be sending in a PR shortly to have the 100 operate by the default expected mechanics.
