### ISSUE TITLE
Add an option to enable vanilla bugs like rail manufacturing machine and sand manufacturing machine

### ISSUE THREAD

**Issue by heipiao233** [PaperSpigot/Paper#7990]
### Is your feature request related to a problem?

Sometimes we want to play Paper plugins and redstone together.

### Describe the solution you'd like.

Add an option to disable these bug fix patches.

### Describe alternatives you've considered.

I don't know.

**Comment by kennytv** [comment]
Dupes are dupes and dupes get fixed, see https://github.com/PaperMC/Paper/issues/3854
