### ISSUE TITLE
[Paper 1.19] Issue with logic

### ISSUE THREAD

**Issue by Galiiusz** [PaperSpigot/Paper#7991]
### Expected behavior

Capital letters in alt-item-despawn-rate causes problem for paper spigot. It worked on 1.18, now it doesn't.

![obraz](https://user-images.githubusercontent.com/107580468/173904281-b9006c71-d171-4a50-bbac-5f2221922671.png)

### Observed/Actual behavior

Removed items from alt-item-despawn-rate

### Steps/models to reproduce

Use capital letters for name of items in alt-item-despawn-rate

### Plugin and Datapack List

Clean version without any plugins or datapacks

### Paper version

1.19

### Other

1.18 version of alt-item-despawn-rate which doesn't work on 1.19
`    alt-item-despawn-rate:`
      `enabled: true`
      `items:`
        `COBBLESTONE: 300`
        `DIRT: 300`
        `SAND: 300`

Lowercase in 1.19 works fine:

`      items:`
        `cobblestone: 300`
       ` dirt: 300`
       ` netherrack: 300`
       ` sand: 300`

**Comment by electronicboy** [comment]
This specifically is not a bug, I said to open a report if you had a conversion issue on the existing tracking issue for such things

upper case is not valid here, as it was migrated over to using mojangs names/keys for stuff, as opposed to using bukkit names
