### ISSUE TITLE
1.19 Paper shows an error for 1.18

### ISSUE THREAD

**Issue by jacobvdl** [PaperSpigot/Paper#7996]
### Expected behavior

Running Paper 1.19 without java 17 should show this error: Minecraft 1.19 requires running the server with Java 17 or above. Download Java 17 (or above) from https://adoptium.net/

### Observed/Actual behavior

The server actually shows 1.18 instead: Minecraft 1.18 requires running the server with Java 17 or above. Download Java 17 (or above) from https://adoptium.net/

### Steps/models to reproduce

Start a paper 1.19 server with an older java version.

### Plugin and Datapack List

Not to do with plugins.

### Paper version

git-Paper-18 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 17c1c6c)

**Comment by electronicboy** [comment]
This is not a versioned string, not sure if it's something we particularly care about but this would be a paperclip issue
