### ISSUE TITLE
Keep Inventory does not work if a player dies in the Nether

### ISSUE THREAD

**Issue by SynthwaveFox** [PaperSpigot/Paper#7999]
### Expected behavior

When a player dies with keepInventory enabled, they should keep their items.

### Observed/Actual behavior

When a player dies in the Nether with keepInventory = true, their items are dropped and destroyed.

### Steps/models to reproduce

Load up a world
Turn on the Keep Inventory gamerule
Enter the nether
Lose all your health, your items should drop and you will not respawn with them.

### Plugin and Datapack List

Essentials, EssentialsChat

### Paper version

This server is running Paper version git-Paper-18 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 17c1c6c)
You are running the latest version
Previous version: git-Paper-379 (MC: 1.18.2)

### Other

We have confirmed with my other server users that inventory items are kept when dying in the Overworld, but not in the Nether. We haven't tested The End yet.

**Comment by electronicboy** [comment]
Gamerules are per world in craftbukkit
