### ISSUE TITLE
Can't open doors while goat horn is cooling down

### ISSUE THREAD

**Issue by Crnojevic** [PaperSpigot/Paper#8005]
### Expected behavior

I expected the door to open and stay open.

### Observed/Actual behavior

The door opens momentarily before closing again.

### Steps/models to reproduce

Use a goat horn, while it's cooling down you can't interact with doors.

[Video](https://www.youtube.com/watch?v=Jc6cmLlKf98)

### Plugin and Datapack List

None.

### Paper version

This server is running Paper version git-Paper-24 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: dd61319)
You are running the latest version

**Comment by chickeneer** [comment]
Extra information here (Haven't checked the code yet). The issue is specifically when you are holding the goat horn. Meaning that if you switch your main hand - you can interact with the door and what-not.
Door is a simple example, but applies to pretty much all block interactions

**Comment by Machine-Maker** [comment]
Yeah, this happens because craftbukkit fires the PlayerInteractEvent in a cancelled state (setting useInteractedBlock to DENY) **if** the current item is on cooldown. I suspect you have a similar problem after using an enderpearl.
