### ISSUE TITLE
Default to https for chat hyperlinks when unspecified with option to use vanilla http behavior.

### ISSUE THREAD

**Issue by mibby** [PaperSpigot/Paper#8011]
### Is your feature request related to a problem?

Is it possible to append https to hyperlinks by default instead of http when it is not specified?

When you click on a link in chat such as ``website.com``, minecraft seems to append http to the beginning so it opens as a link. However my website is https. When you click ``Yes`` to open the link in-game, it doesn't redirect to the site properly in the browser. When manually typing the short address in the browser, not specifying http or https to the shortened url properly redirects fine to https. Just when clicking from in-game, it appends http which breaks the link from working. I would have to extend the url displayed in-game to use https which adds length bloat. Forcing minecraft to always https instead of http when unspecified would be ideal.

With 1.19, doesn't it make sense to be updated? I'm not sure why the default client isn't https'ing. If it's possible to change this behavior and override default links to this, it would be preferable. Http seems outdated and is redundant needing to manually extend all urls with https appended.

### Describe the solution you'd like.

Overriding default behavior so links without http/https specified default to https.

### Describe alternatives you've considered.

Deleting Mojang from the internet.

**Comment by deceptivelyjosh** [comment]
A properly configured website should redirect to HTTPS itself.
It is bad practice to assume a website supports it because if it doesn’t you’re simply left with an error screen and a confused end-user.

**Comment by mibby** [comment]
You're right, however I do not have access to the web servers my site is hosted on. Besides, what website isn't SSL in current year where defaulting to http is preferred over https?

Firefox automatically redirects http to https which is good.
Chrome / Edge does not. Which is where I'm running into this issue with users not being able to access the link from in-game.

Because I don't have access to that web server, the only alternative is manually specifying the protocol in the link which makes it extra verbosey in the display _or_ relying on the client to use a modern redirect by default.

**Comment by electronicboy** [comment]
1) This logic is part of some legacy craftbukkit crud
2) As already said, not all websites support HTTPS, those that do should have redirects and HSTS setup, SSL is not a requirement for many things on the web, and forcefully breaking URLs which have worked for years seems like a pretty shoddy thing to do over something which for the most part literally doesn't matter

**Comment by zachduda** [comment]
> You're right, however I do not have access to the web servers my site is hosted on. Besides, what website isn't SSL in current year where defaulting to http is preferred over https?
> 
> Firefox automatically redirects http to https which is good. Chrome / Edge does not. Which is where I'm running into this issue with users not being able to access the link from in-game.
> 
> Because I don't have access to that web server, the only alternative is manually specifying the protocol in the link which makes it extra verbosey in the display _or_ relying on the client to use a modern redirect by default.

Sounds like you need to fix your website, rather than Paper Spigot pushing an update that could break millions of other sites. As other people have mentioned, a properly configured website will redirect successfully from HTTP to HTTPS and set an HSTS policy within the browser that forces HTTPS to that site for all future requests. The only con of redirecting HTTP to HTTPS is a ~150ms delay on the very first request made.  Despite it being 2022, many websites still rely on the HTTP protocol to function.

**Comment by mibby** [comment]
> Sounds like you need to fix your website, rather than Paper Spigot pushing an update that could break millions of other sites.

Unfortunately Enjin is very non-compliant when it comes to their support department and is something I've had for over a decade now. I'm just kicking the can as long as I can since I'm dependent on their API for a few features until I can move to a more independent framework.

Even if default behavior remained http but the possibility through an option or flag to force https was added, I think it would be nice to have in edge cases such as this. I at least know every link my community shares or has hyperlinked around in announcements / login messages supports HTTPS so I'm not as dependent on needing legacy HTTP to function I suppose.

If this is something Paper does not wish to pursue, I understand.

**Comment by Brokkonaut** [comment]
If you need it just for your server and your domain why not just use the chat event to modify chat messages that players send on your server that contain that specific domain with the https variant?

**Comment by mibby** [comment]
Closing as I found a workaround to my problem and don't want to burden Paper devs with a very niche feature implementation.
