### ISSUE TITLE
Custom End worlds without DragonBattle...

### ISSUE THREAD

**Issue by Jeppa** [PaperSpigot/Paper#8017]
### Expected behavior

Just like default end, custom ends should have a DragonBattle...

### Observed/Actual behavior

Custom ends don't have a DragonBattle...  (no portal, dragon etc)

### Steps/models to reproduce

Just enter a custom end world...

### Plugin and Datapack List

none

### Paper version

paper-1.19-20

### Other

If not already planned, please add the patch from spigot tp paper...
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/c882f38ea98a6610df2b351aadd16901cd8e06b3

**Comment by Doc94** [comment]
This is already in queue by https://github.com/PaperMC/Paper/pull/8015
