### ISSUE TITLE
Add option to disable being kicked for "out of order chat"

### ISSUE THREAD

**Issue by galacticwarrior9** [PaperSpigot/Paper#8019]
### Is your feature request related to a problem?

A number of players on my 1.19 server are being persistently kicked for having "out of order chat" with the message '`multiplayer.disconnect.out_of_order_chat`'; some have been kicked over five times in five minutes. This is generating a great amount of annoyance. 

### Describe the solution you'd like.

It would be preferable if there was an option to simply ignore the out-of-order message and inform console/the sender instead, so that disruption to players can be minimised while I pinpoint the cause(s) of this occurring in the first place. 

### Describe alternatives you've considered.

I imagine that the *ideal* solution to this would be finding out why the chat is being sent out-of-order in the first place. But as I mentioned, it would be nice if I have the option to disable the kick while I investigate the matter and await fixes from plugin developers if this is being caused by plugins. And if this is caused by players' system times being out of sync as some have suggested, then a solution from our end may not be possible and it would be preferable for us to inform these players without disrupting their gameplay.

**Comment by Machine-Maker** [comment]
Can you run `/ver` and post the version of Paper you are running?

**Comment by codeHusky** [comment]
Also experiencing the same issue for a lot of players. Issue occurs on ~git-Paper-12~ git-Paper-28 (MC: 1.19) and occurs inconsistently with commands and chat messages for some players. Having a way to disable this check would be ideal as it appears to be broken

**Comment by electronicboy** [comment]
Update, afaik this has already been patched, no need for a disable switch.

**Comment by codeHusky** [comment]
@electronicboy Copied incorrect thing, that was my previous version.
Current version is git-Paper-28 (MC: 1.19)

**Comment by electronicboy** [comment]
I don't think that there is much interest from us in terms of disabling this, we'd much rather fix it, given that this could have wider implications in the future adding a moot switch IMHO would be dumb; A plugin could easily prevent this kick in the meantime, if somebody else on the team wants to re-open this, go ahead, but, I'd personally rather this be isolated down and seen if this is a plugin or a server issue still

**Comment by codeHusky** [comment]
Currently using a custom solution to disable the kick - the attempted kick does completely block executing some commands for the people affected though. Currently a pretty intrusive issue and doesn't seem to be specific to any plugin (people getting kicked for essentialsX /bal, CrashClaim /claims, chat messages (with essentialsX chat), etc.) doesn't seem to be consistent whatsoever with any plugin or particular plugin feature.

**Comment by Astralchroma** [comment]
I am going to confirm that this is a major issue, I have had a handful of players getting disconnected for this, my responce has been to go to https://time.is to check if time is desynced, and to tell Windows to resync if it is, for some this has helped, but for others it has not. However plugins are 100% at least partially to blame for this, I have plotsquared running on my server (albeit a slightly outdated version), using the plot chat channel in that plugin wil result in an instant disconnect. However some of this can also be blamed on the server, I removed the custom chat used by my server, so its now using vanilla chat, yet the issue persists.

**Comment by Astralchroma** [comment]
Here is the version if you need it.

![Screenshot from 2022-06-19 09-50-34](https://user-images.githubusercontent.com/49043380/174473219-11b05c39-d7f9-46bb-a907-76b43cbdb5bf.png)

**Comment by codeHusky** [comment]
@electronicboy after some additional testing I didn’t experience this issue on my Ethernet-linked desktop on my server, but I’ve been having the issue occur frequently on my same account on wifi on my laptop. It might be somewhat latency or packet loss based but I’m not super sure. It doesn’t have any consistent plugin-specific behavior though so I don’t believe this is due to any plugin in specific (I’m only using pretty basic plugins atm anyhow).

regardless this should likely be reopened as an issue regarding this new check so that it can be handled as a bug. It’s extremely intrusive and attempts to kick people doing regular things on my server, as well as others.

**Comment by codeHusky** [comment]
Still occurs on Paper git-Paper-32 1.19

**Comment by electronicboy** [comment]
are you using a proxy or something?

**Comment by Astralchroma** [comment]
I run 2 Paper servers behind a Velocity instance, both are updated every day or so.

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Velocity/issues/756

**Comment by 56738** [comment]
I've added some logging to this:
```
[13:02:18] [Netty Epoll Server IO #0/INFO]: sent at 2022-06-27T13:03:40.657Z
[13:02:18] [Server thread/INFO]: [user] » [message]
[13:03:05] [Netty Epoll Server IO #0/INFO]: sent at 2022-06-27T13:03:05.783Z
[13:03:05] [Netty Epoll Server IO #0/WARN]: 2022-06-27T13:03:05.783Z is before 2022-06-27T13:03:40.657Z
[13:03:05] [Netty Epoll Server IO #0/WARN]: [user] sent out-of-order chat: '/replace 0 1'
[13:03:05] [Server thread/INFO]: [user] issued server command: //replace 0 1
```
The user sent a message with an incorrect (future) timestamp. Then, their OS apparently synchronized the clock and the next message was sent with the correct (earlier) timestamp. This means that (in my case) it's not caused by plugins, proxies or network conditions. The client is simply sending incorrect information.

I believe this is something Mojang needs to fix. Until they do, I don't see any proper solution except just disabling the kick for now.

**Comment by electronicboy** [comment]
don't particularly wanna disable the thing, I do think that maybe some leeway should be added to account for this, I have been tryna speak to mojang about this type of issue specifically

**Comment by Muirer** [comment]
> I don't think that there is much interest from us in terms of disabling this, we'd much rather fix it, given that this could have wider implications in the future adding a moot switch IMHO would be dumb; A plugin could easily prevent this kick in the meantime, if somebody else on the team wants to re-open this, go ahead, but, I'd personally rather this be isolated down and seen if this is a plugin or a server issue still

I can't find that plugin.

**Comment by partydev** [comment]
Using Velocity 3.1.2-SNAPSHOT (git-e8bf6ab5-b161) and Paper-44, I was getting kicked for most messages I sent to my server. My system clock was 1 second behind the server's clock.

**Comment by kennytv** [comment]
The server time has no relevance here, this can only happen when a) a plugin is being dumb or b) your client local time jumped backwards (or in your case possibly Velocity needing changes)

**Comment by partydev** [comment]
Understood, didn't know if it mattered because I have not looked over the code that throws this. Is there a reason why this kick occurs when chat reporting is not implemented yet? I can see the reasoning behind enforcing this for when it matters with chat reporting, but for now?

**Comment by electronicboy** [comment]
temp measures are never temp measures, especially when it comes to stupid stuff like this; I do think that adding maybe some fudge factor might be worth it, just for the sake of people getting booted by opertune clock resyncs, and logging some level of info (last + curr message times), but, people should really be solving their own side of stuff here

**Comment by electronicboy** [comment]
Maybe, like 30-60 seconds, if prior to previous message, cancel the packet and send the sender a message to say that their sender was lost due to a clock desynchronising?

Prevents the kick, gives some info of what the server saw, and lets them relog to mitigate the issue (or whatever)

I don’t really like this, but, maybe at least this way we can prevent some of the kicks for some of the issues, but, this is not something we can really fix, and just preventing a kick is just masking the issue here

**Comment by Strahilchu** [comment]
Still having this issue :/

**Comment by electronicboy** [comment]
if using velocity we're currently working on a fix, if using anything else, there is not much we can do about this without inducing mangled state elsewhere especially with the changes in 1.19.1

**Comment by msmanui** [comment]
This is still a thing with latest paper and velocity.
