### ISSUE TITLE
Can't shift trade with villager

### ISSUE THREAD

**Issue by Nononitas** [PaperSpigot/Paper#8020]
### Expected behavior

Trading works like excepted

### Observed/Actual behavior

You don't get the traded target items and your offered items become ghost items

### Steps/models to reproduce

Shift click on a trade offer
Shift-click the item you want to get
Video: https://youtu.be/gT1lYAMgjZk

### Plugin and Datapack List

Nothing installed

### Paper version

This server is running Paper version git-Paper-28 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: b0eb4e0)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-373 (MC: 1.18.2)

**Comment by Crnojevic** [comment]
> ### Plugin and Datapack List
> Nothing installed
> 

I can see multiple mods installed just by looking at your video...

**Comment by Leahcimkrob** [comment]
We have the some problem with Chests an workbench

**Comment by Chew** [comment]
Mods aren't plugins or datapacks, but do try without just in case...

Also, please update, just in case :)

**Comment by Nononitas** [comment]
Same bahaivour with vanilla client

**Comment by AlexReaction** [comment]
I can't reproduce this with the current version and the version that you are using. Tested both with a vanilla client. Are you sure that you used a vanilla client?

**Comment by Nononitas** [comment]
I found the problem, a proxy plugin is causing the issue. I really didn't expect that.
Thanks anyway for your time :)
