### ISSUE TITLE
Add missing structure seed customizations.

### ISSUE THREAD

**Issue by EterNityCH** [PaperSpigot/Paper#8025]
### Is your feature request related to a problem?

Upstream Spigot has options for structure seeds in Spigot.yml; however the list is incomplete and are missing critical structures such as Mineshafts, Ancient City & Bastion Remnant.

Mineshafts are like rats, they are already everywhere so it isnt really the focus here.

However, Bastion Remnants and the newly introduced **Ancient City** are not available. They contains some of the best loots and adding back the option to enable server owner to customize the seed would be epic!

ATTN: @kennytv :ayaya:

### Describe the solution you'd like.

Adds on the missing structure seed options onto Spigot.yml

### Describe alternatives you've considered.

Automatically random them with the generate-random-seeds-for-all option on paper-world-defaults.yml but, for the sake of consistency, and to avoid the future need to fix when Spigot adding them back; it's probably better to just adding them below Spigot.yml

**Comment by electronicboy** [comment]
```
[05:43:28] [Server thread/INFO]: did not find seed match for: ancient_cities s: 20083232
[05:43:28] [Server thread/INFO]: did not find seed match for: buried_treasures s: 0
[05:43:28] [Server thread/INFO]: did not find seed match for: mineshafts s: 0
```

I did a thing yesterday to see what all was unhandled by spigot

**Comment by NoahvdAa** [comment]
#7398 handles 2/3
