### ISSUE TITLE
Enchantments over the vanilla maximum level break the item

### ISSUE THREAD

**Issue by ImDaMilan** [PaperSpigot/Paper#8026]
### Expected behavior

With some plugins (I haven't tested it in Paper without plugins, one example is EnchantmentSolution) putting a vanilla enchantment with a level greater than the vanilla maximum level will break the item, causing it to be nearly useless, for example, putting Sharpness VII on a netherite sword will make it deal only 2 hearts / 4 damage, which is a lot lower than a netherite sword even without Sharpness, this only occurs on Paper, it works properly on Spigot and Bukkit.

### Observed/Actual behavior

Putting Sharpness VII will make the sword deal 4 damage, when it should be dealing 12, things like this happen with all vanilla enchantments, such as Protection, etc.

### Steps/models to reproduce

1. Install a plugin that allows increasing maximal level for enchantments (in my case - EnchatmentSolution https://www.spigotmc.org/resources/enchantment-solution.59556/ ), I used Paper 1.19 23, and 29, it didn't work on either version.

2. Edit the vanilla maximal enchantment levels in the config.yml and enchantments.yml.

3. See it for yourself in-game, trying to kill a pig with a Sharp VII netherite sword takes 4 crits.

### Plugin and Datapack List

https://www.spigotmc.org/resources/enchantment-solution.59556/
ProtocolLib
ChestSort
SimpleVoiceChat
CrashAPI

### Paper version

Checking version, please wait...
[08:46:50 INFO]: This server is running Paper version git-Paper-29 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 9797f08)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-23 (MC: 1.19)

**Comment by lynxplay** [comment]
I cannot replicate this with my plain attempts. Both a netherite_sword enchanted to level 7 sharpness using the plugin API, as well as one spawned in with a plain vanilla give command (`/give @p netherite_sword{Enchantments:[{id:"minecraft:sharpness",lvl:7s}]}`) deal 12 hearts of damage to a pig, while one without an enchantment only deals 8.

The sharpness formula is $\frac{level}{2} + \frac{1}{2}$.
The 12 damage hence is expected, as $8 + \frac{7}{2} + \frac{1}{2} = 12$.

Please replicate this without plugins or with small proof-of-work plugins.
Code bases like [EnchantmentSolution](https://github.com/crashtheparty/EnchantmentSolution) are too large to quickly test with or full ensure that nothing in the plugin itself is causing the issue.

If you can, feel free to re-open this issue (or if you cannot, just write a comment and I'll reopen it for you) :+1:
