### ISSUE TITLE
SIGSEGV DataPaletteHash, DataPaletteBlock$c and DataPaletteLinear

### ISSUE THREAD

**Issue by DiscowZombie** [PaperSpigot/Paper#8032]
### Stack trace

https://paste.gg/p/DiscowZombie/7a79101cd70846eda45cdfbea17abf15

### Plugin and Datapack List

**Plugins (4) :**
- TCPShield
- Litebans
- LuckPerms
- spark

**Datapack (0) :** /

### Actions to reproduce (if known)

It looks like the problem is not configuration-related. I've changed several configuration files (bukkit.yml, paper-global.yml, paper-world-defaults.yml), changed the GC (from G1 to ZGC) and changed the OpenJDK distribution (from eclipse-temurin to Zulu) under Java 17.0.3 and Java 18.0.1 - the issue still occurs.

Also, I have tested all of the aforementioned combinations under both latest Paper 1.18.2 build and latest 1.19 build, and the issue occurred in all cases.

We have faced this issue for days now, but we wanted to be sure to gather loads of data before contacting you. The server used for the tests generally host 120 players (120 fully slots). The crash occurs within a timeframe of some minutes (~10 mn) to some hours (~4 hours), depending on how players are split.

We did our tests with a pre-generated world (pre-generation done with Chunky on half of the tests ; and a self-made plugin on the other half) from -5000 to 5000 in each direction, with the nether and the end dimension disabled and the world seed is 8840837546793968439 (but we think it doesn't matter). We were unable to determine which chunk(s) produce(s) this issue, but we guess that not all are affected because the server can sometimes stay online for hours even if a lot of players moved.

### Paper version

This server is running Paper version git-Paper-32 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 4c9317c)
You are running the latest version
Previous version: git-Paper-31 (MC: 1.19)

### Other

The linked dump (https://paste.gg/p/DiscowZombie/7a79101cd70846eda45cdfbea17abf15) is the most informative we were able to obtain. I've read the _Server thread_ stack call to find out were the execution stopped.
The call flow seems to be :
- ChunkSerializer#saveChunk (Spigot class name: [ChunkRegionLoader](https://nms.screamingsandals.org/1.19/net/minecraft/world/level/chunk/storage/ChunkSerializer.html))
- ChunkSerializer#makeBiomeCodec
- PalettedContainer#codec
- PalettedContainer#write
- HashMapPalette#idFor
And then I think the code responsible for the SIGSEGV is :
```java
@Override
public int idFor(T object) {
    int i = this.values.getId(object);
    if (i == -1) {
        // Paper start - Avoid unnecessary resize operation in CrudeIncrementalIntIdentityHashBiMap and optimize
        // We use size() instead of the result from add(K)
        // This avoids adding another object unnecessarily
        // Without this change, + 2 would be required in the constructor
        if (this.values.size() >= 1 << this.bits) {
            i = this.resizeHandler.onResize(this.bits + 1, object);
        } else {
            i = this.values.add(object);
        }
        // Paper end
    }

    return i;
}
```
especially the `this.resizeHandler.onResize` call.

We know its very unlikely for a java call to produce a segmentation error like that, but our investigation since days led us to think that this code was responsible for the problem.

I linked two more dumps below, thoses two are harder to read, but they report a similar segmentation issue, and the address at offset _stackpointer + 3_ report respectively an issue with the classes _net/minecraft/world/level/chunk/DataPaletteBlock$c_ and _net/minecraft/world/level/chunk/DataPaletteLinear_. 

Dumps :
- https://paste.gg/p/DiscowZombie/1786013e5d8942149b71f55bcbb17b51
- https://paste.gg/p/DiscowZombie/38653f643c0b42bab516da65a19972e3

**Comment by electronicboy** [comment]
Java code pretty much cannot induce a segmentation fault unless it was messing with low level data, but, that more more be a native library vs java code; The fact that it happened in the GC tasks is generally a sign of memory issues on the host, where chunk data is one of the hugest memory allocators on the server, it's not too uncommon for that stuff to just magically hit the wrong place, etc

I would heavily suggest letting a mem tester run a few cycles over the memory

**Comment by DiscowZombie** [comment]
Thank a lot for your advice, the memtest has reported 51 errors ! The RAM was completely changed, and now everything seems to work fine.
