### ISSUE TITLE
Tp out of Worldborder with Enderpearl

### ISSUE THREAD

**Issue by Chris6ix** [PaperSpigot/Paper#8033]
### Expected behavior

Not teleporting outside the worldborder

### Observed/Actual behavior

When throwing Enderpearl, you get teleported outside the worldborder

### Steps/models to reproduce

1.Tp to the Worldborder
2.Throw an Enderpearl at it
3.Get teleported outside the Worldborder

### Plugin and Datapack List

Plugins (55): ArmoredElytra, AutoTotem, BackToTheRoots*, BetterConcrete, BetterTridents, BigDoors, Bookshelf, BreakingSlab, ClientDetector, CommandCooldown, DeluxeMenus, Duels, DynamicShop, dynmap, Essentials, EssentialsChat, ExcellentEnchants, ExecutableItems, ExtraGameRules, FlyPerms, GSit, HolographicDisplays, HoloMobHealth, InteractionVisualizer, JoinRules, KittenForever, LevelledMobs, LightAPI, LinkedPortals, LinksPlus, LuckPerms, Multiverse-Core, Multiverse-Inventories, NexEngine, NotTooExpensive, PL-Hide, PlaceholderAPI, PlayerPortal, PlayerWarps, Playtimes*, ProtocolLib, QuickShop-Hikari, RotationWrench, SCore, SilkSpawners, TAB, UltimateCatcher, UltimateTimber, UltraCosmetics, Vault, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags, XpBottles

There are 3 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/Chris6ix_Custom_Server_datapack.zip (world)]
There are no more data packs available

### Paper version

This server is running Paper version git-Paper-386 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 072f54c on ver/1.18.2)
You are running the latest version
Previous version: git-Paper-379 (MC: 1.18.2)

### Other

I'm not sure if this is a bug or if it's intended, but it's definitely not ok...

**Comment by lynxplay** [comment]
Duplicate of [MC-53602](https://bugs.mojang.com/browse/MC-53602). 
I personally don't think there is any point in us fixing this, it is already on low priority on the mojang bug tracker, but I will leave the issue open for a core team/developer member to potentially close if they agree with my judgement.

**Comment by Chris6ix** [comment]
Mojang did it. They fixed it in Snapshot 24w33a after only 10 years. I never thought I would still be alive to witness this glorious day.
