### ISSUE TITLE
/locate bug

### ISSUE THREAD

**Issue by carabax** [PaperSpigot/Paper#8034]
### Expected behavior

Showing the desired coordinates of the biome.

### Observed/Actual behavior

When using the /locate structure command, an error occurs and the server is forcibly stopped (crash).

### Steps/models to reproduce

For example: /locate structure minecraft:mineshaft_mesa

### Plugin and Datapack List

There are no plugins, **the server is clean**.

### Paper version

This server is running Paper version `git-Paper-32 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 4c9317c)`

**Comment by electronicboy** [comment]
Not crash info, and probably the long standing issue where Minecraft literally loads up to 10k chunks in the process of doing that
