### ISSUE TITLE
Markers spawned from spawn eggs spawn one block lower than they should

### ISSUE THREAD

**Issue by ava-ankenbrandt** [PaperSpigot/Paper#8038]
### Expected behavior

On vanilla servers, spawning a marker from a spawn egg spawns it directly on top of the block selected.

### Observed/Actual behavior

On a paper server, the marker spawns one block lower—on the bottom face of the block selected.
Note that this only happens when you right-click on the top face of a block—all other faces work as intended.

### Steps/models to reproduce

To reproduce easily, you can use a command like this:
`/give @p tropical_fish_spawn_egg{display:{Name:'{"text":"Game Start Button Marker","italic":false}'},EntityTag:{id:"minecraft:marker",Tags:["gameStartButton"]}} 1`
This gives you a spawn egg that will spawn a tagged marker for mapmaking purposes.

Next, put this command in a repeating command block to visualize the markers with particles.
`execute as @e[type=marker] at @s run particle minecraft:ash ~ ~ ~ 0.01 0.01 0.01 0 10 force`

Then, use the spawn egg on the top of a block. The marker will spawn inside that block—on its bottom face instead of its top face.

Try the same thing in vanilla and you'll see that the marker spawns on the top face of the block as expected.

### Plugin and Datapack List

Worldedit.

### Paper version

This server is running Paper version git-Paper-33 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 147a2b7)
You are running the latest version

**Comment by Machine-Maker** [comment]
This seems to be an issue with paper's collision improvements. Specifically in `EntityType#getYOffset` the Shapes#collide call is returning -2 when in vanilla it returns -1. It looks like the isEmpty check in `AABBVoxelShape#collide` is returning the maxDist whereas in vanilla, the empty check is different.

**Comment by Owen1212055** [comment]
Resolved in https://github.com/PaperMC/Paper/pull/8733, will be closed when 1.20 is completed.
