### ISSUE TITLE
EntityBreedEvent does not fire for turtles

### ISSUE THREAD

**Issue by mfcfbro** [PaperSpigot/Paper#8040]
### Expected behavior

When breeding a turtle, org.bukkit.event.entity.EntityBreedEvent should be called as it is for all other animals at the time of breeding.

### Observed/Actual behavior

The event is never triggered when breeding turtles.

### Steps/models to reproduce

Use this snippet and try to breed turtles.
```
@EventHandler
  public void onBreed(EntityBreedEvent e){
    e.setCancelled(true);
    Bukkit.broadcastMessage("Breed");
  }
```

### Plugin and Datapack List

This can be replicated with no plugins or datapacks installed.

### Paper version

This server is running Paper version git-Paper-34 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: e52499e)
You are running the latest version
Previous version: git-Paper-33 (MC: 1.19)

**Comment by Machine-Maker** [comment]
So while I think an event should exist for this, it doesn't look like EntityBreedEvent is the one. That event requires an entity offspring, and that doesn't exist for turtles, it just changes one of the turtles into a turtle with an egg.

**Comment by Brokkonaut** [comment]
How about the name EntityMateEvent and use this for turtles and frogs?

**Comment by Lulu13022002** [comment]
You have right, i have updated my PR including frogs

**Comment by mfcfbro** [comment]
Thanks @Lulu13022002! You did this patch super fast. I'm excited to see it added.
