### ISSUE TITLE
Zombie break door configuration unreliable

### ISSUE THREAD

**Issue by lilshortcake** [PaperSpigot/Paper#8047]
### Expected behavior

The setting for configuring at what difficulties zombies should be able to break doors should work so that each difficulty listed should turn the game mechanic on, so that zombies can break doors on easy or any other difficulty you want.
Even if left default, the zombies should break doors.
The config should also not revert this one setting on it's own.

### Observed/Actual behavior

Zombies do not break doors at all on any difficulty setting whatsoever.
I managed to get them to break on easy one time after hours of testing,

however,

the /config/paper-world-defaults.yml file reverted this one specific setting back to default all on it's own. No other settings were touched, so that even if I can manage to get zombies to break down doors again, it's only a matter of time until the config is reverted.

### Steps/models to reproduce

I'm using bisecthosting for my server, running Paper version git-Paper-36 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT)

Go to a village.
Go into creative.
Spawn a bunch of zombies in the village.
Go into survival, zombies should aggro.
Run into a house and close the door behind you.
Zombies should follow you to the door, but no matter how many times you do it, they will never break down the door.

### Plugin and Datapack List

Plugins (4): AntiFarm, AsyncWorldEdit, IronGolemTarget, WorldEdit
No datapacks

### Paper version

git-Paper-36 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 5593f4e)

**Comment by Machine-Maker** [comment]
I think this is "Works as Intended". Zombies breaking doors depends on more than just difficulty. It also depends on the regional difficulty where the zombie was spawned, and even then there is only a chance that the zombie will be able to break doors. In vanilla, on hard difficulty, Zombies can only have a max 10% chance (depending on regional difficulty) of being able to break doors. The settings for breaking door difficulty just bypasses the general difficulty checks, it does nothing to change the probability that the zombie will be able to break doors in the first place.

**Comment by lilshortcake** [comment]
> I think this is "Works as Intended". Zombies breaking doors depends on more than just difficulty. It also depends on the regional difficulty where the zombie was spawned, and even then there is only a chance that the zombie will be able to break doors. In vanilla, on hard difficulty, Zombies can only have a max 10% chance (depending on regional difficulty) of being able to break doors. The settings for breaking door difficulty just bypasses the general difficulty checks, it does nothing to change the probability that the zombie will be able to break doors in the first place.

o ok. I'll have to just make a plugin then to increase the probability of them breaking doors.

**Comment by Machine-Maker** [comment]
> I'll have to just make a plugin then to increase the probability of them breaking doors

Yes a plugin could easily do this, listening to the creature spawn event and overriding the flag.
