### ISSUE TITLE
Bees are getting stuck in hives when leaving and dying

### ISSUE THREAD

**Issue by Spencer7171** [PaperSpigot/Paper#8056]
### Expected behavior

Bees should exit hives without getting stuck partially in the hive and taking suffocation damage.

### Observed/Actual behavior

Bees are getting stuck in hives when exiting, taking suffocation damage and dying. It is not constant, but it happens often enough to be an issue
![2022-06-26_03 38 26](https://user-images.githubusercontent.com/10209688/175808789-cf7373c1-c754-4bb4-9298-dc6e0a2b14fa.png)
.

### Steps/models to reproduce

Place down a campfire, surround it with trapdoors or any full block(aside from ones that could damage the bees such as magma blocks), put a bee hive or nest with bees on top. As seen in the attached screenshot
![2022-06-26_03 04 46](https://user-images.githubusercontent.com/10209688/175808866-14e2a7b9-7384-41b7-8c0c-98d1ecbb0562.png)
.

### Plugin and Datapack List

Plugins = CoreProtect, FastLeafDecay

### Paper version

This server is running Paper version git-Paper-36 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 5593f4e)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-27 (MC: 1.19)

**Comment by NoahvdAa** [comment]
Looks like this is a duplicate of #7290 for 1.19

**Comment by electronicboy** [comment]
Duplicate of #7290
