### ISSUE TITLE
Sculk Blocks Not Dropping XP

### ISSUE THREAD

**Issue by PerryJ97** [PaperSpigot/Paper#8062]
### Expected behavior

When a player breaks or uses TNT lit by a flint and steel, or uses a wither, to destroy Sculk, XP should be dropped

### Observed/Actual behavior

No XP is dropped when breaking Sculk in either of the three methods above

### Steps/models to reproduce

Place a sculk block down, use TNT and flint and steel or a wither to destroy sculk, no xp will drop

### Plugin and Datapack List

ArmourStandTools, Elevator, Essentials, EssentialsSpawn, f3NPERM, FarmProtect, MoreMobHeads, PowerlessLamps, TreeAssist, ViaVersion, WorldEdit

Vanilla-Built-in, Bukkit-World, Anti-Enderman Grief, AntiGhast, CustomNetherPortals, DoubleShulkerShells, NetherPortalCoordinates, SIlenceMobs

### Paper version

Git-Paper-8 MC:1.19

1.19-RO.1-SNAPSHOT GIT: E4f5e1c

35 versions behind on minehut

### Other

NA

**Comment by Owen1212055** [comment]
Can reproduce, working on this.

**Comment by lynxplay** [comment]
Indeed replicable, at least partially.

Manual breaking of the block through a pickaxe still yields experience.
Indirect breaking does not. This is a spigot issue, specifically see the non-vanilla implementation in https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/nms-patches/net/minecraft/world/level/block/DropExperienceBlock.patch. 

While manual, player block breaks do properly call on spigot's added `getExpDrop` method, indirect block breaks do not.

This issue expands to redstone ore and spawners too.
