### ISSUE TITLE
Villager trade caused player kick

### ISSUE THREAD

**Issue by DarkChromaMC** [PaperSpigot/Paper#8071]
### Expected behavior

The player should not be kicked when attempting to trade with a villager.

### Observed/Actual behavior

The player is kicked when interacting with a villagers trade.

### Steps/models to reproduce

Install the latest paper jar.
Trade with the villager. (I have provided the worldedit schematic of the villager. Simply use **//paste -e** to replicate the issue.
Worldedit Schematic: [villager.schem-2022-06-29T065154Z.tar.gz](https://github.com/PaperMC/Paper/files/9007986/villager.schem-2022-06-29T065154Z.tar.gz)

Video: https://user-images.githubusercontent.com/68839442/176371039-72644496-268c-408b-b772-b60ffb4d18da.mov

)

### Plugin and Datapack List

No plugins installed.

### Paper version

This server is running Paper version git-Paper-40 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 0d79b86)
You are running the latest version

### Other

This bug occurs on both lunar and vanilla Minecraft.

**Comment by DarkChromaMC** [comment]
https://user-images.githubusercontent.com/68839442/176371151-b5922e9e-874e-4ea2-811c-4cb73333e54a.mov

**Comment by Doc94** [comment]
Can you provide your latest.log? i test in a fresh server and not get any error with vanilla client and the villager provided.

https://user-images.githubusercontent.com/3602279/176454339-24eee447-ec7e-4d07-85f7-c47908c46cd0.mp4

**Comment by Machine-Maker** [comment]
Yeah, gonna reiterate what Doc94 said, please provide your latest.log (or the log that contains the player getting kicked). That should provide more info, and determine if a plugin is responsible for this (most likely).

**Comment by DarkChromaMC** [comment]
Hi, I have found the issue is due to the velocity protocolize plugin and possibly also the serverGUI velocity plugin. Hence, why no spigot plugins installed, still resulted in this bug, and testing on a fresh server didn't yield the error.
