### ISSUE TITLE
Request for a fix/bug-bounty for MC-148993

### ISSUE THREAD

**Issue by Kruize1** [PaperSpigot/Paper#8083]
### Is your feature request related to a problem?

This Vanilla Bug in Minecraft https://bugs.mojang.com/browse/MC-148993

This bug essentially breaks Spectator Mode and there's been no fix in sight for several years.

I often spectate players on my server, and this has existed for 4 years, going on 5 years now, and has been an extreme pain for me.

### Describe the solution you'd like.

I'm humbly requesting, if Paper could please make a fix for this bug and, if possible, give the solution to Mojang so this can be fixed for the community.

I'm even willing to donate money or even offer a bug fixing bounty for this.

### Describe alternatives you've considered.

The only thing we can do is just wait indefinitely, for many years, for a fix that will never happen.

**Comment by scarfacered** [comment]
I think this is a client side issue, Sodium fixes this.

**Comment by molor** [comment]
Yes, it's client issue; But it's can be "fixed" from server side/avoided with a plugin that will be reset spectator target at some interval, e.g. `entity = getSpectatorTarget()`, `setSpectatorTarget(null)` and `setSpectatorTarget(entity)`. It's works like the client pressed CTRL+A

**Comment by Lulu13022002** [comment]
It should be fixed clientside because we can't just spam some packet just for a bug. Also we need to send only the packet and don't use these functions because Paper has added some event related to this action. And plugin don't want to receive a PlayerStart/StopSpectatingEntityEvent just for a bug fix

**Comment by NoahvdAa** [comment]
As others have said, the best solution for this is a client-side fix. You can a mod like [Spectater](https://github.com/LazuriteMC/Spectater) or [thorium](https://github.com/PotassiumMC/thorium/) (shameless self plug) for this. If you don't want to install a client mod for some reason, you can use [this plugin I made](https://github.com/NoahvdAa/SpectatorSendChunks/releases/tag/1.0.0). It uses the method described by molor, but does have a bunch of side effects which you can check out [here](https://github.com/NoahvdAa/SpectatorSendChunks/tree/1.0.0#side-effects).

Finally, as for Paper fixing this, I'm not sure if there's a non-janky fix on the server that is worth the effort. A few things come to mind like always setting the player's position to that of the entity they're spectating, or loading chunks at the player's "camera" entity, but these solutions would probably end up causing behavioral changes and would also take a fair bit of time to test and develop, for something that can easily be fixed on the client (or with a slightly shitty workaround).

**Comment by molor** [comment]
Another server-side solution/plugin that fixes that w/o any side effects (I hope): [Specentre](https://github.com/molor/Specentre/)

**Comment by e-im** [comment]
Closed based on everything above. Client issue, you can workaround it with a plugin.
