### ISSUE TITLE
Limit entity spawning based on y-cords

### ISSUE THREAD

**Issue by AhmetDS** [PaperSpigot/Paper#8088]
### Is your feature request related to a problem?

As entities are clearly laggy, we want it to be minimized. Although we have per player entity spawn, its chunk based. When dealing with low entity limits, its most likely to spawn underground, an unreachable place, and lower player's experience. And low entity limits are necessery on a big survival server. 

### Describe the solution you'd like.

Mob spawns are limited to a view area/y-coord of the player which allows a better distribution and lowers the numbers of entities without a visible effect for the user.

### Describe alternatives you've considered.

None.

**Comment by imDaniX** [comment]
I feel like it should rather be controlled by a plugin. Although, resolving #5076 might help with performance in this case.

**Comment by Owen1212055** [comment]
Agreed, it is better for you to have a plugin that allows you to fine-tune mob spawning like this.
However, if you still feel that this would be useful to have on paper feel free to comment on this issue and it can be reopened. 😄
