### ISSUE TITLE
Seed for Sound

### ISSUE THREAD

**Issue by TheLimeGlass** [PaperSpigot/Paper#8091]
### Is your feature request related to a problem?

In 1.19 Mojang added a long field to the sound packets labeled `seed` this is for that random variation that sounds have, so now we can control which seed variant to use, or to just be able to stop the random seed that sound currently has.

Probably like an addition to the playSound in the Player entity.

### Describe the solution you'd like.

like an addition to the playSound in the Player entity with a long field attached

`playSound(Location loc, Sound sound, SoundCategory category, float volume, float pitch, long seed)`

Of course with backwards compatibility keeping the old methods.

### Describe alternatives you've considered.

Using NMS packet handling, but having it added to the API would be awesome.

**Comment by kezz** [comment]
API already exists for this in Adventure 4.12.0-SNAPSHOT - will be available when that releases and Adventure is bumped (see https://github.com/KyoriPowered/adventure/pull/770).
