### ISSUE TITLE
Goat dropping a Goat Horn does not trigger EntityDropItemEvent

### ISSUE THREAD

**Issue by cksmith51** [PaperSpigot/Paper#8093]
### Expected behavior

Goat dropping a Goat Horn triggers EntityDropItemEvent

### Observed/Actual behavior

Goat dropping a Goat Horn does not trigger EntityDropItemEvent

### Steps/models to reproduce

Listen on EntityDropItemEvent, have some sort of print message that triggers if the entity is a goat and the item is a goat horn.
Then, summon a screaming goat (they ram faster), stand still in survival mode in front of stone, and dodge the goat when it rams. It should drop a horn when it hits the wall, and if the event is triggered, should print the message.

### Plugin and Datapack List

ApolloUHC (my custom plugin), ProtocolLib

### Paper version

This server is running Paper version git-Paper-48 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 385f313)

**Comment by lynxplay** [comment]
Can replicate, the logic simply does not call the event here. See `net.minecraft.world.entity.animal.goat.Goat#dropHorn`

**Comment by cksmith51** [comment]
Thanks for the quick action!

**Comment by cksmith51** [comment]
Update: Not seeing the goat changes pushed through as I am still seeing the event not trigger on a goat losing its horn

**Comment by lynxplay** [comment]
Concerning that kenny just merged the PR, I would say you probably don*t have the right paper version ?

**Comment by cksmith51** [comment]
@lynxplay I updated to the latest version to test it, but looking at the PR, it doesn't have any changes for goat in it, just Dolphin and Fox

**Comment by lynxplay** [comment]
The event properly calls for me. Please make sure you are actually running latest. The PR by Machine Maker did not fix your issue but a) fixed a bunch of others and b) laid the ground work my PR build on.

**Comment by cksmith51** [comment]
When I typed my messages #50 was not done yet I suppose. I see it now. Thanks.
