### ISSUE TITLE
Item NBT data gets reset if the data is too big

### ISSUE THREAD

**Issue by RedishKitter** [PaperSpigot/Paper#8098]
### Expected behavior

I've been messing with a plugin to generate some pixelart onto itemlore with some fancy resourcepack stuff. This makes the lore/description INCREDIBLY long, like 500+ characters. Seemingly, this is fine, it displays as intended; however once I move or interact with the item in my inventory, it's entire data gets reset. 

That being said, smaller images seem to work fine with no issues, which is why I'm assuming it has to be some issue with the data being too long.

I know this isnt an issue with base minecraft, since I tested it in singleplayer and a vanilla server and it worked fine there.

The expected behavior would be that it stays on the item permanently without any issues.

 

### Observed/Actual behavior

Items NBT gets reset once I mess around with the item in my inventory. Sometimes it's instant, other times it takes a bit of spamming to get it to disappear.

### Steps/models to reproduce

Just spawn the item in, and watch it happen in game.

https://user-images.githubusercontent.com/81716791/177322140-4d1b1602-1f5f-4851-98b3-69bb57e020fc.mp4

### Plugin and Datapack List

This was tested without any plugins running in the server.

### Paper version

[06:35:05 INFO]: Checking version, please wait...
[06:35:06 INFO]: This server is running Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)
You are running the latest version

### Other

[latest.log](https://github.com/PaperMC/Paper/files/9046005/latest.log)
This log just contains me opening the server and typing the `/paper dumpitem` commands. I write a message before each command saying what the item is.

If you'd like a download of the world with the items, I can upload that for you as well.

**This doesnt happen in vanilla singleplayer, or vanilla minecraft server based off my tests**

**Comment by electronicboy** [comment]
paper global, `item-validation` is probs what you're looking for

**Comment by RedishKitter** [comment]
> paper global, `item-validation` is probs what you're looking for

Oh wow that fixed it. Thank you so much!
