### ISSUE TITLE
Sign is empty after breaking when event is cancelled

### ISSUE THREAD

**Issue by Tackoozle** [PaperSpigot/Paper#8101]
### Expected behavior

The sign should not be empty.

### Observed/Actual behavior

So when I break a sign and the event (blockbreakevent or playerinteractevent) is cancelled, for example with worldguard, the sign is empty.
After updating the sign (Sign#update) with a plugin or relogging the text is visible again.

### Steps/models to reproduce

- place a sign with text
- try to break the sign
- cancel BlockBreakEvent or PlayerInteractEvent
- watch the text disappear

### Plugin and Datapack List

Worldguard, WorldEdit

### Paper version

> version
[19:45:16 INFO]: Checking version, please wait...
[19:45:16 INFO]: This server is running Paper version git-Paper-50 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: c879064)
You are running the latest version
Previous version: git-Paper-267 (MC: 1.18.2)

**Comment by Owen1212055** [comment]
Fixed by https://github.com/PaperMC/Paper/pull/8053

**Comment by Tackoozle** [comment]
Oh, didnt see that one.. :/

**Comment by Owen1212055** [comment]
> Oh, didnt see that one.. :/

No worries! There isn't currently an issue open for this.
