### ISSUE TITLE
Zombies Not Spawning Re-inforcements

### ISSUE THREAD

**Issue by PerryJ97** [PaperSpigot/Paper#8106]
### Expected behavior

Zombies when taking environmental damage should spawn reinforcements

### Observed/Actual behavior

No zombie reinforcements are spawned when taking environmental damage

### Steps/models to reproduce

build a long platform facing north or south, build another smaller platform seperate and made of magma blocks. Spawn zombies on the magma blocks, when the zombies take damage reinforcements should spawn however do not

### Plugin and Datapack List

Armourstandtools, elevator, Essentials, Essentials Spawn, F3NPerm, Farm Protect, Powerless Lamps, Tree Assist, ViaVersion, World Edit

### Paper version

1.19-R0.1-snapshot

**Comment by PerryJ97** [comment]
I forgot to mention, I am using a villager in order for the zombies whom are taking enviromental damage to have a target to lock onto. I  am in hard mode and Mobspawning gamerule is true

**Comment by lynxplay** [comment]
Running the farm gnembon zombie farm (https://www.youtube.com/watch?v=n8_uN03GD_0) on the latest version of paper yields expected results.

Additionally, summoning a modified zombie (`/summon zombie ~ ~ ~ {Attributes:[{Name:zombie.spawn_reinforcements,Base:10}]}`) and having them chase me through magma blocks also spawns in reinforcements.

I guess attempt to replicate this without plugins ?
If you can replicate it without plugins, feel free to comment and we should look into building a minimal setup to replicate this.
For now I am closing this as cannot reproduce.

**Comment by PerryJ97** [comment]
So i have reproduced this without any plugins, my server is running on minehut so perhaps this is something to do with the error?

**Comment by lynxplay** [comment]
Presumably attempt to do this with a zombie with high reinforcement chance (see my debug command above). Last ingredient needed would be that you have valid spawn spaces for zombies. E.g dark, etc. The algorithm for finding spawn points for reinforcements is pretty unintuitive to say the least, the location has to be at least 7 blocks in X,y and z axis from the zombie and max 40.
