### ISSUE TITLE
Client side Allay bug when blocking permission to take items.

### ISSUE THREAD

**Issue by BambuiZepelin** [PaperSpigot/Paper#8110]
### Expected behavior

Untrusted players in a claimed land will not be able to interact with the allays.

(NOT A PLUGIN ISSUE) This is simply just a client-side issue.

### Observed/Actual behavior

After setting up the flags in GriefDefender (correctly of course and even asked the community to test this and they confirmed this is an issue on their and + had tested this on two other test servers) untrusted players can still interact with allays, to them it appears like they can take their items and give them other instead. On the server-side none of these actions are happening and the allays are untouched.

### Steps/models to reproduce

- Set up a new paper server.
- Add Grief Defender and Luckperms plugin.
- Run the server once
- Run this command: /lp group default permission set griefdefender.user.* true
- Stop the server
- Add the following under the /plugins/GriefDefender/presets/minecraft.conf under the user.definitions section (around line 1057).
```
                allay-interact {
                    contexts=[
                        "gd_claim_default=user"
                    ]
                    default-value=false
                    enabled=true
                    icon {
                        enchanted=false
                        id="minecraft:allay_spawn_egg"
                        title="&6Allay-Interact"
                    }
                    permissions=[
                        "flag=interact-entity-secondary, target=minecraft:allay, source=minecraft:player"
                    ]
                }
```
- Start the server or restart it
- Create a claim with one user account
- Summon some allays inside that claim and give them some diamonds (preferably in a cage of 5x5 to reach them easily)
- Join with another account. (They will not be trusted by default)
- With the second account you can now still take items from the allays. Even more, you can give them new items.

### Plugin and Datapack List

[15:06:18 INFO]: Plugins (2): GriefDefender, LuckPerms

### Paper version

[15:06:33 INFO]: This server is running Paper version git-Paper-52 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 6ea73e7)
You are running the latest version

### Other

I have contacted the owner of the plugin and he himself said that there aren't flags for this and this is an issue on Paper's end.

**Comment by lynxplay** [comment]
After first marking this as a feature request, in my honest opinion this should be done through the PlayerInteractEntity event.

This does work server side properly, however the client predicts the allay's inventory change which means a cancelled event would still yield an allay holding an item on the client side. The item can be "taken away" by the player, however this simply does not yield an item.

**Comment by BambuiZepelin** [comment]
Indeed on a second look, it does seem to be a visual bug on the client's side.

**Comment by lynxplay** [comment]
Do you want to reword this issue so we can used to track it, or do you want me to close this and simply open a new one.

**Comment by BambuiZepelin** [comment]
I have updated the ticket. Hope this information is more useful.

**Comment by lynxplay** [comment]
Yes thanks :) It should be a *technically* easy fix, however it is rather ugly fix as the server needs to sync the allays equipment after a cancelled interaction (thanks mojang for predicting this client side).

**Comment by Owen1212055** [comment]
Fixed by upstream: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/ead719a65bf1202e32a4d81442a8bde1a62c07fd
