### ISSUE TITLE
Mobs on the same team with friendly fire set to false still attack each other

### ISSUE THREAD

**Issue by 834000** [PaperSpigot/Paper#8113]
### Expected behavior

Two mobs which would normally attack each other added to the same team with friendly fire set to false will no longer attack each other. 

### Observed/Actual behavior

Two mobs added to a team with friendly fire set to false will still attack each other.

### Steps/models to reproduce

Create a new team and modify it so that friendly fire is set to false
`/team add team1`
`/team modify team1 friendlyFire false`

Spawn in two mobs that would normally target each other, in this example, a Zoglin and Zombified Piglin.
Add these two mobs to the team you created earlier
`/team join team1 @e[type=minecraft:zoglin]`
`/team join team1 @e[type=minecraft:zombified_piglin]`

Despite friendly fire being set to false, the Zoglin will still attack the Zombified Piglin causing the Piglin to fight back.

### Plugin and Datapack List

> plugins
[12:29:04 INFO]: Plugins (0):

> datapack list
[12:29:14 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[12:29:14 INFO]: There are no more data packs available

### Paper version

> version
[12:30:23 INFO]: This server is running Paper version git-Paper-56 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 41238a4)
You are running the latest version

### Other

There is no difference if the mobs are added to the team after being spawned in or if they are spawned in as part of a team using a command like
`/summon minecraft:villager ~ ~ ~ {Team:team1}`

This is because using `/summon` to summon a mob already on a team will consistently results in an error stating:
`[12:00:00 WARN]: Unable to add mob to team "team1" (that team probably doesn't exist)`
Even if the team you are attempting to spawn the mob on does indeed exist.

**Comment by electronicboy** [comment]
https://docs.papermc.io/paper/reference/world-configuration#allow-non-player-entities-on-scoreboards - just to note, you need to enable that option on paper due to an old mitigation for performance issues caused by plugins, etc

**Comment by Laarryy** [comment]
As there is 1-month no response from original issue maker, I'm going to assume that this is solved by enabling the above-mentioned option. Please respond if this is *not* the case and you still need help with this issue, and I'll open it back up.
