### ISSUE TITLE
markers dont update position while riding other entities

### ISSUE THREAD

**Issue by Strongis13** [PaperSpigot/Paper#8118]
### Expected behavior

When summoning a moving entity with a marker as a passenger, the marker should constantly update to the location of the entity it is riding

### Observed/Actual behavior

Passenger markers do not update their position while riding other entities, causing them to stay in the position they were spawned at

### Steps/models to reproduce

In vanilla: https://youtu.be/9YN98lzqCoM
commands used:
-tag @e[type=minecraft:snowball,tag=!modsnowball] add snowball1
-execute as @e[type=snowball,tag=snowball1] at @s run summon snowball ~ ~ ~ {Tags:["modsnowball"],Passengers:[{id:"minecraft:marker"}]}
-data modify entity @e[tag=modsnowball,limit=1] Motion set from entity @e[tag=snowball1,limit=1] Motion
-kill @e[type=snowball,tag=snowball1,limit=1]
-execute at @e[type=marker] run particle glow ~ ~ ~ 0 0 0 0 10 force

In paper 1.19: https://youtu.be/bUXehZ7mh-Q
commands used:
-same as vanilla

### Plugin and Datapack List

There are no plugins or custom datapacks

### Paper version

> version
[21:13:55 INFO]: Checking version, please wait...
[21:13:56 INFO]: This server is running Paper version git-Paper-58 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: e294802)
You are running the latest version
Previous version: git-Paper-39 (MC: 1.19)

### Other

Adding a config option to disable #7299 may fix this issue

**Comment by lynxplay** [comment]
Paper actively removes the marker entity from the ticking list as an optimisation.
This either might be worth to add a configuration option for or just straight up remove said optimisation.
Really up to whoever opens the PR and the reviewers 👍

**Comment by piratecody** [comment]
Currently working on a fix to add a config option to enable/disable this optimization

**Comment by Owen1212055** [comment]
> Currently working on a fix to add a config option to enable/disable this optimization

I assume you are not working on this anymore? Is someone else able to take over?

**Comment by piratecody** [comment]
> > Currently working on a fix to add a config option to enable/disable this optimization
> 
> I assume you are not working on this anymore? Is someone else able to take over?

I have the fix written, but I've been busy and haven't had a chance to commit & PR. Should have some time this weekend.

**Comment by piratecody** [comment]
PR in progress 
https://github.com/PaperMC/Paper/pull/8372

**Comment by Machine-Maker** [comment]
Closed by https://github.com/PaperMC/Paper/pull/9034
