### ISSUE TITLE
Custom Sounds do not respect location when using Player#playSound

### ISSUE THREAD

**Issue by Blast-MC** [PaperSpigot/Paper#8121]
### Expected behavior

Expected to play like normal /minecraft:playsound command with custom sounds. If a player is too far away from the sound (16 blocks for <= 2 volume, 16 * volume for > 2), it should not play to the client.

### Observed/Actual behavior

Sound plays at full volume no matter how far away the sound is. Unlike the /minecraft:playsound command, it does not check if the player is close enough to actually hear it.

### Steps/models to reproduce

Add a sound via a resource pack (can just be client sided, server doesn't need to have CDN setup)
create command:
```
public class TestSoundCommand implements CommandExecutor {
	@Override
	public boolean onCommand(@NotNull CommandSender sender, @NotNull Command command, @NotNull String label, @NotNull String[] args) {
		if (!(sender instanceof Player player))
			return true;
		Location loc = player.getLocation().clone().add(100, 0 ,0);
		player.playSound(loc, "minecraft:custom.sound", SoundCategory.MASTER, 2, 1);
		return true;
	}
}
```
Run the command

### Plugin and Datapack List

PlaygroundPlugin v1.0.0 (just above test)

### Paper version

This server is running Paper version git-Paper-58 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: e294802)
You are running the latest version
Previous version: git-Paper-41 (MC: 1.19)

### Other

Using World#playSound does work as expected, but unfortunately, I can't use this as I have a volume setting for each player.

**Comment by kezz** [comment]
Are you sure you're not tripping up on [MC-146721](https://bugs.mojang.com/browse/MC-146721)?

**Comment by Blast-MC** [comment]
That seemed to be it. Converting to mono fixed the issue.
