### ISSUE TITLE
Allow ignoring Looting/Fortune on EntityDeathEvent/BlockBreakEvent respectively

### ISSUE THREAD

**Issue by u9g** [PaperSpigot/Paper#8134]
### Is your feature request related to a problem?

Yeah, I want fortune to usually work except for to not work on gravel.

### Describe the solution you'd like.

No idea.

### Describe alternatives you've considered.

No idea.

**Comment by Doc94** [comment]
The events are called later of all this logic... Not sure if loottables can handle this...

**Comment by u9g** [comment]
Closing as this is possible, see https://forums.papermc.io/threads/disabling-looting-fortune-for-certain-blocks-or-entities.419/ for how
