### ISSUE TITLE
Custom Brand Name

### ISSUE THREAD

**Issue by ArtyomKor** [PaperSpigot/Paper#8135]
### Is your feature request related to a problem?

I want to create my own private server and I want F3 to display its name.

### Describe the solution you'd like.

Function to change brand name

### Describe alternatives you've considered.

Tell me what kind of file contains brand name

**Comment by Malfrador** [comment]
https://www.spigotmc.org/resources/f3name-edit-your-server-brand-in-debug-screen.58997/
That can be easily done using a plugin.

And its not really nice in my opinion - you are using free software, at least give the devs some credit for making that software.

**Comment by Doc94** [comment]
If you dont wanna a plugin you can use this for create a fork and add a patch with this change https://github.com/PaperMC/paperweight-examples

**Comment by ArtyomKor** [comment]
> If you dont wanna a plugin you can use this for create a fork and add a patch with this change https://github.com/PaperMC/paperweight-examples

Which file contains the brand name?

**Comment by Doc94** [comment]
> > If you dont wanna a plugin you can use this for create a fork and add a patch with this change https://github.com/PaperMC/paperweight-examples
> 
> Which file contains the brand name?

Follow the example, the 3 types of fork show a example where rename the server name, if you need help its better go to the discord/forum

**Comment by lynxplay** [comment]
Agree with Doc here. Please use our discord/forums for further help. See https://papermc.io/community for any relevant links to these platforms.
