### ISSUE TITLE
Redstone wire going up blocks does not update when powered

### ISSUE THREAD

**Issue by LucynGoosey** [PaperSpigot/Paper#8138]
### Expected behavior

when the redstone is already powered and you connect a higher level piece of redstone to a lower level, the higher piece of redstone should have its texture update.

### Observed/Actual behavior

The redstone on the higher blocks textures do not update, however, their behavior does. [
![image](https://user-images.githubusercontent.com/87942896/178784774-e613085d-e03e-4465-b2f6-2ab83c6cf49e.png)
](image)

### Steps/models to reproduce

place a block and put redstone on top of it

power the redstone

place redstone next to the block that would normally change the direction it points

watch the bug happen

### Plugin and Datapack List

AnvilColor, ColoredSigns, CoreProtect, DiscordSRV, dynmap, Dynmap-GriefPrevention, Essentials, EssentialsChat, EssentialsSpawn, FakeLeaveAndJoin, GriefPrevention, GSit, GuestMode, HasteBoost, PermissionsEx, PetMaster, PortalHelper, SafeSpectate, SmoothSleep, StaffChat, TalkingBot, Vault, ViaBackwards, ViaVersion, WorldBorder, WorldEdit, Wrenchable

### Paper version

1.19-58

**Comment by lynxplay** [comment]
Which redstone engine are you using ? I can only replicate this on eigencraft, both vanilla and alternate-current function properly in my tests.

**Comment by SpaceWalkerRS** [comment]
It appears to be an issue with the recent update to the Eigencraft patch. Indirect shape updates are omitted which leaves a redstone dust block that you placed in a powered position in an incorrect state. I will PR a fix.
