### ISSUE TITLE
Add the new 1.19 Chat Preview feature to the API

### ISSUE THREAD

**Issue by NiaSwift** [PaperSpigot/Paper#8140]
### Is your feature request related to a problem?

It's not really a problem, it's just that currently we have to use packets for the new feature, and I would like to use it without using packets.

### Describe the solution you'd like.

Add something like tab completion, but with chat previews to the API 

### Describe alternatives you've considered.

Can't think of any ¯\_(ツ)_/¯

**Comment by lynxplay** [comment]
We are aware that API around signed message and previews is missing.
WIth how actively mojang is still developing the system in the 1.19.1 pre-releases, adding an API now would not make much sense.

Beyond that we are also dependent on spigot and adventure.

I am uncertain that keeping an issue open for this is useful. I can ensure you that this API is on the teams mind.

**Comment by Astralchroma** [comment]
~~I assume Paper has not done this yet because they are waiting to see what Spigot does, as well as waiting for Adventure to update to support the changes made by 1.19. Additionally somethings may end up changing 1.19.1, so they are *probably waiting on that*.~~

@lynxplay You beat me too it by like 20 seconds. :/

**Comment by NoahvdAa** [comment]
Upstream has added the [AsyncPlayerChatPreviewEvent](https://jd.papermc.io/paper/1.19/org/bukkit/event/player/AsyncPlayerChatPreviewEvent.html), and Paper now also has the [AsyncChatDecorateEvent](https://jd.papermc.io/paper/1.19/io/papermc/paper/event/player/AsyncChatDecorateEvent.html), both of which can now be used to preview and decorate chats. :)
