### ISSUE TITLE
Gamerule spectatorsGenerateChunks doesnt work as expected

### ISSUE THREAD

**Issue by pilot22** [PaperSpigot/Paper#8143]
### Expected behavior

Once set to false, spectators shouldn't be able to generate chunks

### Observed/Actual behavior

Spectators still can generate chunks whether the gamerule is set to true or not

### Steps/models to reproduce

Define the gamerule like that: /gamerule spectatorsGenerateChunks false
Set your gamemode to spectator, move around the map and you'll see that as a spectator you still generate chunks

### Plugin and Datapack List

Plugins:
`[INFO] Plugins (5): BlockLocker, Chunky, CoreProtect, InvSeePlusPlus, ServerTap`

Datapacks:
`[INFO] There are 6 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/dungeons-v1-8-0-terralith.zip (world)], [file/nullscape-v1-2a.zip (world)], [file/terralith-v2-3-2a.zip (world)], [file/towns-and-towers-structure-add-on-1-8-1.zip (world)]`

### Paper version

 Paper version git-Paper-58 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: e294802)

### Other

@Machine-Maker told me that this gamerule was known to be bugged on papermc

**Comment by lynxplay** [comment]
Duplicate of #6657 (which itself was a duplicate of #4805, but stale bot came for it).

Generally this is a long standing issue that is known, just tricky to implement with the large changes paper does to the chunk loading system.

**Comment by VL4DST3R** [comment]
> Duplicate of #6657 (which itself was a duplicate of #4805, but stale bot came for it).
> 
> Generally this is a long standing issue that is known, just tricky to implement with the large changes paper does to the chunk loading system.

Will we ever see a fix for this? Or is there any plugin that can prevent generating new chunks on already existing worlds? It kinda ruins it if you want to visit older worlds in spectator without interfering with the world itself.

**Comment by electronicboy** [comment]
it's a stupidly low priority issue of which is pretty complex in nature due to the OTT chunk system which is in the middle of being replaced

**Comment by VL4DST3R** [comment]
This chunk system change will also affect the issue at hand in any way? (i.e. address it?)

**Comment by electronicboy** [comment]
No idea if that is a priority for that system
