### ISSUE TITLE
Eigencraft doesn't fire BlockRedstoneEvent for redstone wire sometimes

### ISSUE THREAD

**Issue by bergerkiller** [PaperSpigot/Paper#8146]
### Expected behavior

When switching the redstone-implementation to EIGENCRAFT it still fires BlockRedstoneEvent events for changes in redstone wire, so that redstone-sign activation still works.

### Observed/Actual behavior

BlockRedstoneEvent is omitted. Seemingly randomly so. It seems to skip the redstone wire directly adjacent to the lever activating it.

### Steps/models to reproduce

Listen for BlockRedstoneEvent and log all the blocks that come by. Tracking of it is done here: https://github.com/bergerhealer/TrainCarts/blob/master/src/main/java/com/bergerkiller/bukkit/tc/controller/global/SignController.java#L273

Switch config/paper-world-defaults.yml:
```redstone-implementation: EIGENCRAFT```

BlockPhysicsEvent is still fired, which saves functionality for paper. But it's not efficient to keep using that for activating signs.

Image shows an example setup to debug this problem. Log all updates. You will see that a block redstone update event is fired for the diamond-wires but not the gold wires.
![ScreenShot_2022-07-16 16-09-48](https://user-images.githubusercontent.com/957601/179358339-9f5b1459-c3eb-4bcf-b2a5-894328b24178.png)

Example logging of BlockRedstoneEvent:
```
Left example:
UPDATE: CraftBlock{pos=BlockPosition{x=63, y=5, z=244},type=LEVER,data=Block{minecraft:lever}[face=floor,facing=west,powered=false],fluid=net.minecraft.world.level.material.FluidTypeEmpty@5d6219a}
<<< x=62 is missing here >>>
UPDATE: CraftBlock{pos=BlockPosition{x=61, y=5, z=244},type=REDSTONE_WIRE,data=Block{minecraft:redstone_wire}[east=side,north=none,power=0,south=none,west=side],fluid=net.minecraft.world.level.material.FluidTypeEmpty@5d6219a}
UPDATE: CraftBlock{pos=BlockPosition{x=60, y=5, z=244},type=REDSTONE_WIRE,data=Block{minecraft:redstone_wire}[east=side,north=none,power=0,south=none,west=side],fluid=net.minecraft.world.level.material.FluidTypeEmpty@5d6219a}

Right example:
UPDATE: CraftBlock{pos=BlockPosition{x=61, y=5, z=242},type=LEVER,data=Block{minecraft:lever}[face=floor,facing=west,powered=false],fluid=net.minecraft.world.level.material.FluidTypeEmpty@5d6219a}
<<< x=60 is missing here >>>
```

### Plugin and Datapack List

BKCommonLib, Traincarts
https://ci.mg-dev.eu/job/BKCommonLib/1340/
https://ci.mg-dev.eu/job/TrainCarts/1153/

### Paper version

This server is running Paper version git-Paper-61 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: cd215af)

### Other

This issue is directly affecting me, because some paper forks optimize out the block physics events entirely (understandably). As the issue lies with paper that the block redstone event isn't fired, I'm not sure if I take it up with them or address it with paper.

To me at least, the block redstone event not being fired looks like a bug in and of itself.

This issue only occurs with EIGENCRAFT. Not VANILLA or ALTERNATE_CURRENT

**Comment by D-VR** [comment]
Should be fixed by https://github.com/PaperMC/Paper/pull/8148 now

**Comment by bergerkiller** [comment]
Can confirm the problem is now fixed. Thanks for the quick fix!
