### ISSUE TITLE
Server error and crash

### ISSUE THREAD

**Issue by JniZiousZ** [PaperSpigot/Paper#8153]
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
![image](https://user-images.githubusercontent.com/82430958/179434950-0a026726-a507-44ad-8fc1-14e0dc7aa672.png)

### Plugin and Datapack List

![2022-07-17_18 48 48](https://user-images.githubusercontent.com/82430958/179434728-fd894ca2-1f50-499e-8972-5a44a5879ee9.png)

### Actions to reproduce (if known)

I was playing on the server while prloading chunks and the server sends errors and crashes

### Paper version

This server is running Paper version git-Paper-61 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: cd215af)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads

**Comment by Machine-Maker** [comment]
Can you link the full crash report? I need to see what each thread is doing. I'm guessing some plugin is doing something bad.

**Comment by e-im** [comment]
This issue tracker is just for bugs or feature requests and is not designed for support. Please come by our [Discord](https://discord.gg/papermc) (`#paper-help` channel), [forums](https://forums.papermc.io), or [IRC](https://webchat.esper.net/?channels=paper-help) for support.
