### ISSUE TITLE
Goat Horn API

### ISSUE THREAD

**Issue by qixils** [PaperSpigot/Paper#8157]
### Is your feature request related to a problem?

There is seemingly no class or method in the API to get the Type of a Goat Horn 

### Describe the solution you'd like.

Create a new subclass of ItemMeta which exposes a getter and setter for the goat horn "instrument" type

### Describe alternatives you've considered.

Janky NMS or NBT hacks? idk

**Comment by lynxplay** [comment]
Upstream already has a PR for this in the works, tho it has been a while since that PR has seen any progress.
The issue is valid, however I don't know if implementation in paper makes much sense as upstream is clearly aware of the issue.

**Comment by Laarryy** [comment]
We can close this issue; we're not going to fix it ahead of upstream given that upstream has plans to do it. If this is an issue in the distant future or upstream decides that they no longer want to do it, we can address it then! Thanks for reporting it, and make sure to keep an eye upstream for the addition you need.

**Comment by qixils** [comment]
still missing :-(

i say we reopen this just so @Owen1212055 can close it in their item prop PR ;)

**Comment by Owen1212055** [comment]
Item api will be VERY far future. Generally api like that moves slowly so it's prolly not worth reopening.

**Comment by JustEli** [comment]
Upstream implemented `MusicInstrumentMeta` yesterday, now we need to wait on Paper to apply it
