### ISSUE TITLE
Paper.yml disappeared on 1.19

### ISSUE THREAD

**Issue by JunSuner** [PaperSpigot/Paper#8159]
### Expected behavior

Paper.yml being
![image](https://user-images.githubusercontent.com/79354637/179755366-222f1d9f-0b15-445d-a176-7e352dc43c3f.png)

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/79354637/179757949-0c6e6dcf-5ec6-4910-97a7-e09ce3b195ba.png)

### Steps/models to reproduce

I don't understand this. sorry

### Plugin and Datapack List

[21:10:06 INFO]: Plugins (0):

### Paper version

[21:10:21 INFO]: Checking version, please wait...
[21:10:22 INFO]: This server is running Paper version git-Paper-66 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: b7faa65)
You are running the latest version

### Other

Please help me solve this problem. Players on my server want to use a bug to copy items, but Paper disables it. Many people say that they should use paper.yml modifies the configuration, but after version 1.19, paper.yml is missing.

I try to use Spigot, but its optimization is really poor.

**Comment by NoahvdAa** [comment]
In 1.19, paper.yml has been split into two files, both in the config directory. In paper-global.yml you will find configuration that changes behavior of the whole server, and in paper-world-defaults you will find configuration that can be overridden on a per world basis. See https://docs.papermc.io/paper/per-world-configuration for more information on overrides. The function of server.properties, bukkit.yml, and spigot.yml remains unchanged for this time.

**Comment by JunSuner** [comment]
Thanks!
