### ISSUE TITLE
tadpoles from frogspawn missing spawnreason

### ISSUE THREAD

**Issue by Tackoozle** [PaperSpigot/Paper#8164]
### Expected behavior

There should be a spawnreason when tadpoles are spawned from frogspawn.

### Observed/Actual behavior

When tadpoles are spawned from frogspawn they will be spawned with the spawnreason default on the CreatureSpawnEvent

### Steps/models to reproduce

-

### Plugin and Datapack List

-

### Paper version

> paper version
[17:07:32 INFO]: Checking version, please wait...
[17:07:32 INFO]: This server is running Paper version git-Paper-66 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: b7faa65)
You are running the latest version

**Comment by NoahvdAa** [comment]
Not sure if Paper could/should add a new SpawnReason for this, since it could conflict with what upstream decides to name it (some of upstream's names tend to be illogical and thus unpredictable, meaning we would have two enum values for the same thing).

**Comment by Doc94** [comment]
> Not sure if Paper could/should add a new SpawnReason for this, since it could conflict with what upstream decides to name it (some of upstream's names tend to be illogical and thus unpredictable).

Yeah for avoid this conflict in enum maybe its better make a PR in upstream?

**Comment by lynxplay** [comment]
I mean, I don't see much sense in a new spawn reason here anyway. I presume this would simply be part of the https://jd.papermc.io/paper/1.19/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html#EGG spawn reason, as that is what turtles use ? Depends on whether you wanna think of tadpoles as eggs I guess xD

**Comment by Doc94** [comment]
> I mean, I don't see much sense in a new spawn reason here anyway. I presume this would simply be part of the https://jd.papermc.io/paper/1.19/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html#EGG spawn reason, as that is what turtles use ? Depends on whether you wanna think of tadpoles as eggs I guess xD

ohhh i forget this.. then i can make a PR here using this. (unless upstream wanna create a new but i think this is not the case then)

**Comment by Tackoozle** [comment]
sounds good to me :) thank you guys!
