### ISSUE TITLE
Shift on shulker mob

### ISSUE THREAD

**Issue by YeahUniversal** [PaperSpigot/Paper#8166]
### Expected behavior

Normal shift

### Observed/Actual behavior

When shulker closed shift doesn't have any animation and you walk faster than normal.

### Steps/models to reproduce

idk.

### Plugin and Datapack List

No plugins.

### Paper version

> version
[22:56:24 INFO]: Checking version, please wait...
[22:56:25 INFO]: This server is running Paper version git-Paper-68 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: a76a1ab)
You are running the latest version
Previous version: git-Paper-66 (MC: 1.19)

### Other

when sneaking on shulker mob it breaks sneak.

**Comment by e-im** [comment]
Please fill out the issue template (specifically reproduction steps). However, based on the description I have failed to reproduce anything here. Please come by our [Discord](https://discord.gg/papermc) (`#paper-help` channel), [forums](https://forums.papermc.io), or [IRC](https://webchat.esper.net/?channels=paper-help) for support.
