### ISSUE TITLE
Unable to correctly identify the system version!

### ISSUE THREAD

**Issue by zhicheng233** [PaperSpigot/Paper#8169]
### Expected behavior

I use system version is Windows 11 But Paper identify it is Windows 10!
It's not very a serious problem,But I think that should be fixed~

### Observed/Actual behavior

I use system version is Windows 11 But Paper identify it is Windows 10!
It's not very a serious problem,But I think that should be fixed~

### Steps/models to reproduce

Run Paper on Windows11

### Plugin and Datapack List

null

### Paper version

> version
[09:12:54 INFO]: Checking version, please wait...
[09:12:56 INFO]: This server is running Paper version git-Paper-66 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: b7faa65)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads

**Comment by Camotoy** [comment]
This isn't a Paper bug, it's a Java bug that was fixed in Java 18 or 19.

**Comment by e-im** [comment]
It's been backported a bunch as well. reference [JDK-8274840](https://bugs.openjdk.org/browse/JDK-8274840)
