### ISSUE TITLE
Paper #77 giving error when looking up user profile

### ISSUE THREAD

**Issue by Greymagic27** [PaperSpigot/Paper#8181]
### Stack trace

```
https://paste.gg/p/anonymous/3b2418690ff54ec3b35618923db07b9f
```

### Plugin and Datapack List

Plugins (32): AutomaticInventory, BrandBlocker, CommandHook, CoreProtect, CoreProtect-AntiXray, DiscordSRV, dynmap, EnderSurfer*, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, floodgate, FoundDiamonds, Geyser-Spigot, IslandGenerator, LuckPerms, mcMMO, MinecartSpeedPlus*, Multiverse-Core, OpenInv, PerWorldInventory, Plan, ProtocolLib, spark, StackableItems, Vault, Votifier, VotingPlugin, WorldEdit

There are 17 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/anti enderman grief v1.1.3.zip (world)], [file/anti ghast grief v1.1.3.zip (world)], [file/armored elytra v1.0.6.zip (world)], [file/custom villager shops v1.2.3.zip (world)], [file/durability ping v1.1.3.zip (world)], [file/fast leaf decay v2.0.6.zip (world)], [file/gem villagers v4.4.0.zip (world)], [file/larger phantoms v1.2.4.zip (world)], [file/player head drops v1.1.3.zip (world)], [file/silence mobs v1.1.3.zip (world)], [file/track raw statistics v1.5.3.zip (world)], [file/track statistics v1.1.4.zip (world)], [file/treasure gems v1.2.6.zip (world)], [file/villager death messages v1.2.4.zip (world)], [file/wandering trades v1.6.0.zip (world)]

### Paper version

This server is running Paper version git-Paper-77 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 44b6869)
You are running the latest version
Previous version: git-Paper-72 (MC: 1.19)

### Other

This is a player who hasn't joined in a while

**Comment by electronicboy** [comment]
> Name and ID cannot both be blank

invalid skull lookup, generally induced by plugins, etc, creating bad skulls
