### ISSUE TITLE
entity in the end portal come out 0.5 blocks off

### ISSUE THREAD

**Issue by jamespglines** [PaperSpigot/Paper#8182]
### Expected behavior

I send entity through end portal, it comes out in center of middle block of end platform.

### Observed/Actual behavior

Entity comes off not at `.50` but at `.00` exact x z coord

### Steps/models to reproduce

send falling block (this is block so easy to see) through portal with x/z and +y velocity (easy with slime block or plugin). set up wall in end for falling block to hit, see it hits inbetween two blocks (ignoring y)

try vanilla, see it hits only one block (x/z)
try old version of paper, see it hits only one block

### Plugin and Datapack List

none

### Paper version

git-Paper-77 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 44b6869)

### Other

I try ALL the versions until it breaks (it works before). 
it start with build 48 (Git: 385f313a)

**Comment by Machine-Maker** [comment]
Yeah, if it starts where you say, its probably https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/991aeda1218e72e9237942071e7ea55cc77b541c

**Comment by Doc94** [comment]
> Yeah, if it starts where you say, its probably https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/991aeda1218e72e9237942071e7ea55cc77b541c

yeah... i make the PR related to a issue about the decimals and for the portal i move the logic for the 0.5 for make plugins know the correct coords but i forget its usless use `blockposition1.offset(0.5D, 0, 0.5D)` if the blockposition1 remove the decimals added... only need replace the blockposition class for another thing (testing) for avoid lose this... not sure if handle this here with a patch or try fix my change in upstream...

**Comment by Doc94** [comment]
This can be fix now since https://github.com/PaperMC/Paper/commit/345a6a620524ee18db251da2bbb48ff32864be2f
