### ISSUE TITLE
Command selector feedback not correct

### ISSUE THREAD

**Issue by TheFruxz** [PaperSpigot/Paper#8184]
### Expected behavior

The command /op @a should make everybody an operator and should say that in the output

### Observed/Actual behavior

It repeatedly told, that the executer was made to an operator

### Steps/models to reproduce

- Get multiple players on your server
- Do /op @a
- Look at the feedback

### Plugin and Datapack List

none

### Paper version

This server is running Paper version git-Paper-58 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: e294802)
You are 20 version(s) behind

**Comment by Machine-Maker** [comment]
This is specific to the /op & /deop commands. The command still functions as expected (changing all selected targets' op statuses), just the feedback is incorrect. Tracked as vanilla bug [MC-253721](https://bugs.mojang.com/browse/MC-253721).
