### ISSUE TITLE
player.getInventory().removeItem() skips equipment slots

### ISSUE THREAD

**Issue by AlessioGr** [PaperSpigot/Paper#8209]
### Expected behavior

Using player.getInventory().removeItem() removes as much as possible from the item even if it's in the off-hand or hat slot.

### Observed/Actual behavior

Using player.getInventory().removeItem() removes as much as possible from the item unless it's in the off-hand or hat slot. Then, the item is skipped / not removed.

### Steps/models to reproduce

Call player.getInventory().removeItem() and have an item in your off-hand / hat slot

### Plugin and Datapack List

[01:28:48 INFO]: Plugins (8): Citizens, Essentials, EssentialsChat, EssentialsSpawn, MythicMobs, NotQuests, PlaceholderAPI, Vault

### Paper version

This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)

### Other

This method should remove items from equipment slots as well, since other methods like player.getInventory().getContents() search equipment slots as well. This inconsistency lead to a bug in my plugin.

**Comment by electronicboy** [comment]
This is intentional and changing this would violate the behavior of upstream, `removeItemAnySlot` appears to exist which will do all

**Comment by AlessioGr** [comment]
> This is intentional and changing this would violate the behavior of upstream, `removeItemAnySlot` appears to exist which will do all

What about either deprecating removeItem, or at least specifically mentioning that it skips other slots in the javadocs? Best to warn people about that if you want to leave it that way, as you really wouldn't expect it to behave that way (since other Inventory methods do consider equipment slots), thus causing bugs

**Comment by lynxplay** [comment]
Generally agree that this should warrant at least a mention in the javadocs of https://jd.papermc.io/paper/1.19/org/bukkit/inventory/Inventory.html#removeItem(org.bukkit.inventory.ItemStack...).

A simple statement that it will only remove items found in the main storage of the inventory, excluding things like armor or extra content should be enough, with a reference to the removeItemAnySlot method.

I will mark this as low priority, but if you want to put work towards that, feel free to open a PR for this :)
The change should live in the patch introducing removeItemAnySlot.
