### ISSUE TITLE
Player cannot move

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#8215]
### Expected behavior

Player can move when using keys

### Observed/Actual behavior

player cannot move

### Steps/models to reproduce

1) Install paper 1.19.1 (tested on release 91 and 97)

2) launch a server

3) join the server

4) you can't walk

### Plugin and Datapack List

plugins : TCPShield

datapacks : none

### Paper version

> version
[02:56:19 INFO]: Checking version, please wait...
[02:56:19 INFO]: This server is running Paper version git-Paper-97 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: fd557b7)
You are running the latest version
Previous version: git-Paper-62 (MC: 1.19)

### Other

Other player couldn't move while i could. I'm logged in the server using LOCALHOST while other players where using the TCPShield proxy.

The issue don't happen on paper 1.19, and supposidelly happen regardless of gamemode, operator status or potion effects

**Comment by electronicboy** [comment]
logs? if there's nothing there there's not really much for anybody to go off here

**Comment by ghost** [comment]
unfortunatly, it leaves no log, if it was the case i would have included it. I'm really sorry for that

**Comment by ghost** [comment]
i asked members to screen record it so i can include it

**Comment by ghost** [comment]
here's a video showing the issue. Sorry for the bad quality, the player couldn't do better due to bad computer.

I have to specify that the server where it happen got a plugin added in the meanwhile regarding chat related stuff, so nothing that should interfere with the movements of a player.

[https://www.youtube.com/watch?v=lcKthVAVkOU](https://www.youtube.com/watch?v=lcKthVAVkOU)

**Comment by MWHunter** [comment]
You said you had a single plugin?

**Comment by ghost** [comment]
the issue still happen with or without the plugin. After checking, some players got their attribute GENERIC_MOVE_SPEED set to 0.

It explain why it dont create logs (it's a supported value), but still dont explain why some players got it set to 0 and some didn't (i just learned that one player haven't got the issue too)

**Comment by electronicboy** [comment]
Stuff like that is generally down to plugins messing with those values for various reasons and them not having been reset properly, you'd probably want to get something like a skript or a small plugin to reset those values when people login

**Comment by ghost** [comment]
That's what i'm going to do, thank you for your time and the quick answers and sorry for the somewhat pointless issue
