### ISSUE TITLE
Console not show colors for messages modify by AsyncChatEvent#render

### ISSUE THREAD

**Issue by Doc94** [PaperSpigot/Paper#8220]
### Expected behavior

Before 1.19.1 the chat in console show with format and color

### Observed/Actual behavior

Currently if the message contains colors show a legacy format like this.
![image](https://user-images.githubusercontent.com/3602279/182248664-d5e1655f-d37e-40b3-9ce9-fecd9c5b4189.png)

### Steps/models to reproduce

```java
@EventHandler(priority = EventPriority.HIGH)
    public void onChat(AsyncChatEvent event) {
        event.renderer((source, sourceDisplayName, message, viewer) -> {
            MiniMessage miniMessage = Core.getMM();

            String prefix = RanksSystem.getPrefixUser(source);
            String nationName = LandsSystem.getNationName(source);
            String nationNameWithColor = LandsSystem.getNationNameWithColor(source);
            boolean isNationOwner = LandsSystem.isNationOwner(source.getUniqueId(), nationName);
            String suffix = nationName.isBlank() ? "" : " [" + nationNameWithColor + ChatColor.RESET + "]";

            Component componentPrefix = PlainTextComponentSerializer.plainText().deserialize(prefix);
            if (!prefix.isBlank()) {
                componentPrefix = componentPrefix.hoverEvent(PlainTextComponentSerializer.plainText().deserialize("Esta en el grupo de " + ChatColor.stripColor(prefix)));
            }

            Component componentSuffix = PlainTextComponentSerializer.plainText().deserialize(suffix);
            if (!nationName.isBlank()) {
                componentSuffix = componentSuffix.hoverEvent(PlainTextComponentSerializer.plainText().deserialize("Esta en la Nación " + nationName));
            }
            if (isNationOwner) {
                componentSuffix = componentSuffix.append(PlainTextComponentSerializer.plainText().deserialize(" ۩").hoverEvent(PlainTextComponentSerializer.plainText().deserialize("Dueño de la Nación " + nationName)));
            }

            Component componentPlayer = null;
            try { // Because if any fails dont throw because this
                componentPlayer = Component.text()
                        .append(componentPrefix)
                        .resetStyle()
                        .append(PlainTextComponentSerializer.plainText().deserialize(source.getName()).color(RanksSystem.getColorUser(source)).hoverEvent(source))
                        .append(componentSuffix)
                        .build();
            } catch (Exception e) {
                e.printStackTrace();
            }

            // return the final component
            return Component.text()
                    .append(componentPlayer != null ? componentPlayer : source.displayName())
                    .append(miniMessage.deserialize(" <gradient:#D8B4FE:#9333EA>>></gradient> "))
                    .append(miniMessage.deserialize(PlainTextComponentSerializer.plainText().serialize(message))) // dont remember why make this
                    .build();
        });
    }
```

#### Plugins
AdvancedBan, ArmorStandEditor, BanAnnouncer, BetterBanner*, ChunkTP*, Chunky, ConterCraft, ConterSubsHelper, CoreProtect, DiscordWhitelister, EasyBackup, EasyBackupCore, InventoryRollbackPlus, Lands, LibsDisguises, LiteEco*, LuckPerms, Maintenance, OpenInv, PlugManX (PlugMan), ProtocolLib, SellGUI, spark, Spicord, TradeSystem, Vault, WorldEdit

#### DataPacks
There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]

### Paper version

This server is running Paper version git-Paper-101 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: ceef4b9)
You are running the latest version

### Other

i dont test in another things if this happen.

**Comment by zml2008** [comment]
You're mixing legacy with components here -- you need to properly deserialize any legacy string using LegacyComponentSerializer to bring legacy styling into the component data model.

**Comment by Machine-Maker** [comment]
Yeah, it does look that way. You are putting legacy strings inside components. Don't do that.

**Comment by Doc94** [comment]
Okay i never know how use correctly this.. i change the `PlainTextComponentSerializer.plainText().serialize` (in what cases is the PlainTextComponentSerializer?) to `LegacyComponentSerializer.legacySection().deserialize` and now in chat i see the message but with not colors not sure if this is the correct behaviour.
![image](https://user-images.githubusercontent.com/3602279/182264812-7c4c5dee-793d-4fc7-a385-40c419efca83.png)
![image](https://user-images.githubusercontent.com/3602279/182264835-38a8398f-7fb3-4bf7-bd7b-2ca8020d9dc2.png)

**Comment by Aurelien30000** [comment]
It seems that console does not show colors at all. My setup should be fine, even if I'm using legacy events to format the message internally. Message is fine in preview and chat, but not in console.

https://youtu.be/vhvGWrTQL3g

Used code:

```java
@EventHandler
public void onAsyncPlayerChatEvent(AsyncPlayerChatEvent event) {
    handleChat(event);
}

@EventHandler
public void onAsyncPlayerChatEvent(AsyncPlayerChatPreviewEvent event) {
    handleChat(event);
}

private void handleChat(AsyncPlayerChatEvent event) {
    final Player player = event.getPlayer();
    final String message = event.getMessage();
    String formattedName = "Internal formatting...";
    event.setFormat(formattedName + message);
}
```

**Comment by lynxplay** [comment]
I am going to close this as WAI.
With the changes done in https://github.com/PaperMC/Paper/pull/7937, the only supported way to output colour to the console is the component logger. Legacy colour codes are no longer respected.

The signed message system introduced in 1.19 also only logs the plain signed content in the first place.
