### ISSUE TITLE
Strange behaviour at World#getChunkAtAsync

### ISSUE THREAD

**Issue by masmc05** [PaperSpigot/Paper#8226]
### Timings or Profile link

https://timings.aikar.co/?id=5fb5d1fe14d5471f8c5590ea919beeca https://spark.lucko.me/nAXQobDe09

### Description of issue

first of all, this method still makes main thread get the chunk syncronously, as you can see in the spark report, it doesn't touch any plugin code, but still locks main thread, also at the stop of the server, a StackOverflowError is thrown
https://pastebin.com/daHKEXNs
if you need my code, it's 
```java
world.getChunkAtAsync(x >> 4,z >> 4).thenAccept(chunk -> {
                Runnable run = () -> {
                    Block blockAt = world.getBlockAt(x, y, z);
                    blockAt.setType(Material.CHEST);
                    var chest = (Chest) blockAt.getState();
                    if (lootTable != null) chest.setLootTable(lootTable);
                    chest.getPersistentDataContainer().set(key, PersistentDataType.BYTE, (byte) 1);
                    chest.getPersistentDataContainer().set(this.region, PersistentDataType.STRING, protectedCuboidRegion.getId());
                    chest.update(true);
                };
                if (Bukkit.isPrimaryThread()) run.run(); //had issues in past, to be sure it doesn't happen
                else Bukkit.getScheduler().runTask(this, run);
            });
```
the rest of the code is executed on an own scheduled executor, tried to get help on discord and nobody could help
the sent code is executed only once per second, and that's enough for the server to have around 5-10 tps (while the generation may be ~50 cps on my pc, where theoretically should be enough 1-5 cps)
            

### Plugin and Datapack List

plugins: spark, TresureChests (own plugin), WorldEdit, WorldGuard
no datapacks

### Server config files

```
Paste configs or paste.gg link here!
```
https://paste.gg/p/anonymous/65c25d0afed34091921133f3f8c31cd6
it's all defaults, but may look if you want

### Paper version

This server is running Paper version git-Paper-102 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: e0486ae)
You are running the latest version

**Comment by masmc05** [comment]
also an important note, all executions happen on unloaded chunks on new map (so first time may generate them) still doesn't think this is a reason to block main thread, but may help

**Comment by PedroMPagani** [comment]
Why are you calling world.getBlockAt if you already have the chunk? -> That's not a specific answer to your question of course, but its still, why not use the chunk ref you already got. From the spark report its also clear that your issue is in your bukkit SYNC runnable, and not the .getChunkAtAsync, and instead in the exact .setType!
If you want to see it by yourself, debug the amount of blocks you're setting, save the current tick before you execute that process, and then see the amount of blocks you're setting!

**Comment by PedroMPagani** [comment]
And also another thing I've noticed, if the .getChunkAtAsync does not generate the chunk unless you specify it so, I've noticed that in one my jobs, where around 10k chunks were supposed to be generated, but none of them were, because it only loads the chunk, a reason for locking the main thread can be your .setType too, if the chunks are unloaded (or dont exist), they will generate again in the .setType in the main thread!

(If I am right, this is a good reason to update paper-api docs)

**Comment by masmc05** [comment]
not using the chunk but world because it doesn't matter, the block is just a reference to coordinates and world, it doesn't contain any other information, you can check yourself https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/block/CraftBlock.java
so the effect will be the same, doesn't matter even if the chunk is unloaded when i get the block
about the fact that it's generating it could be, i'll test it, but strange that setType called by me isn't present in stacktrace

**Comment by PedroMPagani** [comment]
It does matter for performance tho, you have the reference already there, why not use it?
Look at the server thread usage by your plugin, or even, execute the same process without your bukkit sync runnable.

Also, if you're looking for performance and these chunks are mostly not loaded, you should instead change the types asynchronously, it would improve the performance a lot and you wouldn't have to load them sync, as I said, getChunkAtAsync could be not loading the chunk, you should check that to see if this true.

**Comment by masmc05** [comment]
1. 
![image](https://user-images.githubusercontent.com/63639746/182476589-d60269ef-0e3b-4f9b-b8e7-4561f841aa4a.png)
![image](https://user-images.githubusercontent.com/63639746/182476599-1401e431-3377-4498-8a8a-59cf8d705ffc.png)
you can see there that the chunk is loaded and full of different blocks even before any of my code is executed
2. taking a block from a chunk is more performance expensive in my code than from the world (even if in a few nanoseconds), you can check that with paperweight
3. also found the issue, made it into this https://spark.lucko.me/Uovg9QSxhT , it was because i was requesting the highest block at a coordinate before loading the chunk from async, now it's fine

**Comment by PedroMPagani** [comment]
That's right, did not notice.
Weird behavior, #getChunkAtAsync not save any file whatsover of the chunk if its not generated. So the chunks were loading sync at first. You should be careful with your bukkit runnables sync, if you inject too much of them at the same time the server is going to crash, specially when dealing with blocks.
