### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by qarbon1** [PaperSpigot/Paper#8227]
### Stack trace

```
https://paste.gg/p/anonymous/885844fd7ba0443f8ba08547769711fa
```

### Plugin and Datapack List

Datapack: https://paste.gg/p/anonymous/424e14773d1e4683b36ada33a700af77
Plugins: https://paste.gg/p/anonymous/1fd3cabfe4534842aa125f363e99042f

### Paper version

https://paste.gg/p/anonymous/14490643361d415ea6bcf627920af167

**Comment by kennytv** [comment]
1.17 is no longer supported
