### ISSUE TITLE
Players get lost connection by "message validation failure"

### ISSUE THREAD

**Issue by Doc94** [PaperSpigot/Paper#8228]
### Expected behavior

Players chat and use whisp like tell,msg

### Observed/Actual behavior

In random moment all players lost conection by
![image](https://user-images.githubusercontent.com/3602279/182415454-60d89340-4bf9-461a-a154-dc373b983171.png)

### Steps/models to reproduce

I found one case if you cancel a PlayerCommandPreprocessEvent with a chat related command (like tell) the next message send by the user cause all players lost conection.

#### Plugins
AdvancedBan, ArmorStandEditor, BanAnnouncer, BetterBanner*, ChunkTP*, Chunky, ConterCraft, ConterSubsHelper, CoreProtect, DiscordWhitelister, EasyBackup, EasyBackupCore, InventoryRollbackPlus, Lands, LibsDisguises, LiteEco*, LuckPerms, Maintenance, OpenInv, PlugManX (PlugMan), ProtocolLib, SellGUI, spark, Spicord, TradeSystem, Vault, WorldEdit

#### DataPacks
There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]

### Paper version

This server is running Paper version git-Paper-101 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: ceef4b9)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-98 (MC: 1.19.1)

**Comment by kennytv** [comment]
Fixed cancelling the preprocess event in https://github.com/PaperMC/Paper/commit/c032050ad824d8aa60219e8a9a84262c20f200d7
