### ISSUE TITLE
PacketEvents / Chat plugin incompability

### ISSUE THREAD

**Issue by KaspianDev** [PaperSpigot/Paper#8231]
### Expected behavior

Message should be sent.

### Observed/Actual behavior

Players get kicked with message below:
![image](https://user-images.githubusercontent.com/34658474/182598575-2e9ea527-f983-45ba-930c-896bb2326bee.png)

### Steps/models to reproduce

I made a plugin jar that reproduces the issue easily [here](https://github.com/KaspianDev/paper-issue)

so
1. Install plugin above
2. Install a chat plugin (tested on essentialxchat and LPC)
3. Start the server
4. Join and send a message, you will get kicked

### Plugin and Datapack List

[13:39:52 INFO]: Plugins (3): LPC, LuckPerms, PE

[13:40:03 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[13:40:03 INFO]: There are no more data packs available

### Paper version

[13:51:22 INFO]: This server is running Paper version git-Paper-104 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: 7044a9c)
You are running the latest version

### Other

Just wanted to add, this does not happen on spigot, which is why i assume its related to paper.

Edit: its related to this line https://github.com/KaspianDev/paper-issue/blob/master/src/main/java/paper/bug/pe/PacketEventsListener.java#L13

**Comment by lynxplay** [comment]
A) please provide the original stacktrace which should be included (see https://github.com/retrooper/packetevents/blob/5717b6050e2fe496f477950b4322480e8af64419/api/src/main/java/com/github/retrooper/packetevents/util/PacketEventsImplHelper.java#L54).

B) Has this been brought up with the author ? You are diving deep into server internals here and opening an issue on paper before discussing this with the author seems less than ideal.

**Comment by kennytv** [comment]
Not a Paper issue.

**Comment by lynxplay** [comment]
Or that way 😛

**Comment by retrooper** [comment]
PS. has been solved.
