### ISSUE TITLE
messages are duplicated

### ISSUE THREAD

**Issue by haroldrc** [PaperSpigot/Paper#8238]
### Expected behavior

non-duplicate messages
chat IC
![image](https://user-images.githubusercontent.com/29206120/182824833-864029a9-dfb7-4502-9097-be3b8644dcc8.png)

console
![image](https://user-images.githubusercontent.com/29206120/182824892-c5ff6735-ee07-493e-b699-1caeb4b5d467.png)

### Observed/Actual behavior

duplicate messages

### Steps/models to reproduce

write in chat

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/29206120/182824648-86e0f6fe-6daf-459b-a6d0-cd5478137a81.png)
![Uploading image.png…]()

### Paper version

 This server is running Paper version git-Paper-104 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: 7044a9c)

**Comment by Astralchroma** [comment]
The issue is probably caused by a plugin. Also SkinsRestorer :eyes:.

**Comment by Machine-Maker** [comment]
As Peter-Crawley said, try and replicate this without plugins installed.

**Comment by e-im** [comment]
Please come by our [Discord](https://discord.gg/papermc) (`#paper-help` channel), [forums](https://forums.papermc.io), or [IRC](https://webchat.esper.net/?channels=paper-help) for support.
