### ISSUE TITLE
The request is about nether portal search, and preventing players entering the roof in a better way for old servers.

### ISSUE THREAD

**Issue by TheForgTN** [PaperSpigot/Paper#8246]
### Is your feature request related to a problem?

This would be a more pleasent way, to prevent players entering the nether roof on servers, where nether roof where enabled back in time.

### Describe the solution you'd like.

The request is about nether portal search, and generating a new portal if, an existing found above the max Y height (aka abow roof).

it could be an option like 

max-nether-portal-search-height: 

or it might would be even better if the server doesn't even search for a portal in the nether above a given height

### Describe alternatives you've considered.

The void damage is a great way (actually I would use both), but on a server where, there are existing portals, it's like a gambling, if you got yourself on the roof, well thats annoying.

**Comment by Owen1212055** [comment]
I really feel that this could be easily achieved with something like a plugin.

**Comment by BigCrazyOfficial** [comment]
This could be achieved more easily by making portals above this limit invalid locations for entering the nether. ~~which I just made a PR for hey isn't that convenient~~

**Comment by Machine-Maker** [comment]
I don't think this is a concern anymore. You will not travel to or create portals above the bedrock roof if the void damage is enabled, even if the portal existed before that option was enabled.
