### ISSUE TITLE
Add an option that just does not kick player for invalid signatures.

### ISSUE THREAD

**Issue by lerokko** [PaperSpigot/Paper#8266]
### Is your feature request related to a problem?

Different kinds of chat messages /me, regular or whispers kick players. Be it using a chat plugin or just the vanilla chat. Which messages are affected changes from build to build but in the latest now every message sent into chat is affected.

### Describe the solution you'd like.

t. Would it be against the spirit to add the blunt big mallet method of. "I have secure profiles disabled , please do not kick players for any invalid signatures on messages."
I am really wanna continue using my 8 year old legacy chat plugins and DGAF about the new reporting (In fact, I do not want it (opinion)) so for backwards compatibility sake, just and option to wave everything and put messages in a format that every client swallows them and does not get kicked.

### Describe alternatives you've considered.

secure-profiles is already turned off.

**Comment by electronicboy** [comment]
No, we will not allow things to send invalid signatures, there is generally no argument for it
if you wanna disable signed chat in general, use a plugin
