### ISSUE TITLE
Its give my errors like this 

### ISSUE THREAD

**Issue by Siamkarlsson** [PaperSpigot/Paper#8268]
### Stack trace

```
(https://paste.gg/p/anonymous/3219c1f23d694e679fe6b10254e562ef/files/b4e1b14f9705497fbd76704431dd10ba/raw)
```

### Plugin and Datapack List

much 

### Paper version

1.19.2 #116

**Comment by electronicboy** [comment]
You have many dozen corrupted files on your server, ranging from region files to plugins; if you require support, please use the discord or forums, but, generally, you're gonna need to track down the busted data and either store it from a backup or remove it
