### ISSUE TITLE
Falling Block defaulting to stone

### ISSUE THREAD

**Issue by Tim355Code** [PaperSpigot/Paper#8269]
### Expected behavior

Using this command:
`/summon minecraft:falling_block ~ ~ ~ {Time:-999999999,NoGravity:1,Invulnerable:1,BlockState:{Name:command_block,Properties:{facing:up}}}`
I expected to see a falling block which looks like a command block. This works in singleplayer.

### Observed/Actual behavior

However, I instead saw a falling block which looks like Stone.

### Steps/models to reproduce

/summon minecraft:falling_block ~ ~ ~ {Time:-999999999,NoGravity:1,Invulnerable:1,BlockState:{Name:command_block,Properties:{facing:up}}}

### Plugin and Datapack List

Plugins (5): Essentials, FastAsyncVoxelSniper, FastAsyncWorldEdit (WorldEdit), Multiverse-Core, SkinsRestorer

There are 3 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/Tim_Ms_test_pack]
Tim_Ms test pack is my own datapack which has nothing to do with falling blocks.

### Paper version

This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
You are running the latest version
Previous version: git-Paper-334 (MC: 1.17.1)

### Other

This also affects structure blocks.

**Comment by Lulu13022002** [comment]
It's not an issue see the filter-nbt-data-from-spawn-eggs-and-related option in per world config

**Comment by lynxplay** [comment]
Indeed ^ Lulu beat me to it.
Paper actively filters these NBT values out, you can configure using https://docs.papermc.io/paper/reference/world-configuration#filter-nbt-data-from-spawn-eggs-and-related
