### ISSUE TITLE
get player's additional chat completions

### ISSUE THREAD

**Issue by UsainSrht** [PaperSpigot/Paper#8271]
### Is your feature request related to a problem?

Player class has `addAdditionalChatCompletions` and `removeAdditionalChatCompletions` methods
I made an emoji list
I have addEmojis function which adds the emojis to the completions
I'd like to have resetEmojis function too but how do I know what to remove from completions?

### Describe the solution you'd like.

My solution is adding `getAdditionalChatCompletions` method which gives the player's additional completions.

### Describe alternatives you've considered.

`setAdditionalChatCompletions` method

**Comment by electronicboy** [comment]
The server doesn't retain this information, the general expectation is that you'd track this stuff yourself

**Comment by UsainSrht** [comment]
Aight
