### ISSUE TITLE
Cancelling AsyncPlayerChatEvent causes players to be kicked

### ISSUE THREAD

**Issue by SnickoDeadMC** [PaperSpigot/Paper#8275]
### Expected behavior

Cancelling the AsyncPlayerChatEvent event should not send any messages (like in pre 1.19 builds)

### Observed/Actual behavior

Cancelling the AsyncPlayerChatEvent event will cause players to be kicked when sending any chat message, with kick message: "Chat message validation failure.".

### Steps/models to reproduce

Cancel the AsyncPlayerChatEvent event and attempt to send a message.

### Plugin and Datapack List

This is a custom plugin we use for chat. No other notable plugins.

### Paper version

1.19.2 #119

**Comment by NoahvdAa** [comment]
Can't reproduce using the following snippet:
```java
@EventHandler
public void asyncplayerchat(AsyncPlayerChatEvent e) {
    e.setCancelled(true);
}
```
![](https://i.noah.pm/9ISf7W.gif)

**Comment by olijeffers0n** [comment]
> Cancel the AsyncPlayerChatEvent event and attempt to send a message.

Maybe you have to send a message in the event listener? Idk that's how I read it

**Comment by lynxplay** [comment]
Please provider proper reproduction steps here. As Noah stated, this does not seem to be the case on a normal setup.
Technically I'd close this at this point, however with how fresh the signed message support is, I'd be happier if you could give us more information on this, preferably a proper reproduction code snippet.

**Comment by mibby** [comment]
I'm running into this same issue. Getting reports from players that shopping for items and specifying a number they wish to purchase in chat is causing kicks with the same ``Chat message validation failure`` message. Using the QuickShop plugin which _does_ use ``AsyncPlayerChatEvent`` to cancel chat messages.

https://github.com/PotatoCraft-Studio/QuickShop-Reremake/blob/master/src/main/java/org/maxgamer/quickshop/listener/ChatListener.java#L39-L52

This also occurs with WorldGuard if the region is flagged to block player chat. Whenever someone is in the region flagged ``send-chat: DENY`` and tries to chat, everyone gets kicked but the person who had their message cancelled.

https://github.com/EngineHub/WorldGuard/blob/0165175a2ebda5985d0f8cab273cad2b65777ead/worldguard-bukkit/src/main/java/com/sk89q/worldguard/bukkit/listener/WorldGuardPlayerListener.java#L139-L168

In both cases, it _doesn't_ kick the person doing the action but _does_ end up kicking everyone else. So for testing, you would need two clients.

**Comment by andy01745** [comment]
I am having the same issue 
![image](https://user-images.githubusercontent.com/84942293/183833263-160be545-d70c-4b66-b881-28a36f3fdf7b.png)


Here is more info: 

![image](https://user-images.githubusercontent.com/84942293/183834059-cce73ddd-91a0-4cd0-b5e6-040765c43d0d.png)

**Comment by kennytv** [comment]
Fixed it based on the limited information provided; if this still happens, please open a new issue with a full list of plugins, and if it's a private one, we still need the actual code of the chat listeners. Ideally in form of minimal reproduction steps with just one plugin that causes it

**Comment by andy01745** [comment]
Thank you. I figured out that it is to do with one of these. 
![image](https://user-images.githubusercontent.com/84942293/183864592-08522027-324c-4c9a-9b03-f09fecf6c2e7.png)

After updating them all the issue has been fixed and also whatever you changed. @kennytv

**Comment by james090500** [comment]
Just commenting to say this has definitely fixed an ongoing issue I've had and been unable to pin down. Fantastic job on the fix thank you so much.

**Comment by mibby** [comment]
@kennytv https://github.com/PaperMC/Paper/commit/954b3fb7d5215acba1c736ba88174a9de3642ce4 This doesn't seem to fix the issue for me with the QuickShop plugin. Players entering a number in chat when shopping and having the message cancelled still end up kicking everyone _but_ the person who entered the message.

Same with WorldGuard region with chat blocked, except it doesn't kick everyone, only some people.

**Comment by tygh89071388** [comment]
> @kennytv This doesn't seem to fix the issue for me with the QuickShop plugin. Players entering a number in chat when shopping and having the message cancelled still end up kicking everyone _but_ the person who entered the message.
> 
> Same with WorldGuard region with chat blocked, except it doesn't kick everyone, only some people.

me too
waterfall-1.19-500
paper-1.19.2-125  

edit:
chat format plugin multichat-1.9.7

**Comment by KaspianDev** [comment]
Y'all make sure to be on latest TAB, they had bug kicking players. I couldn't reproduce it with essentials, essentials chat, antipopup and tab
(Under velocity proxy)

**Comment by mibby** [comment]
> Y'all make sure to be on latest TAB

I was able to reproduce this with TAB disabled, as well as latest source commit in my environment. I'm in the process of cloning everything for testing to see if I can reproduce locally or find if there is a conflict somewhere.

**Comment by mibby** [comment]
After diving deep into narrowing down the problem, this seems to have everything to do with using AntiPopup when connecting behind a proxy.

Waterfall dev 500
**Plugins; None**

config.yml
```
enforce_secure_profile: false
online_mode: true
```

Paper dev 125 (1.19.2)
**Plugins;**
EssentialsX 2.20.0 dev 1409
https://ci.ender.zone/view/All/job/EssentialsX
WorldEdit dev 6244
WorldGuard dev 2204
https://builds.enginehub.org/
Vault dev 23
https://ci.codemc.io/view/All/job/ThirdParty/job/Vault/
Multiverse-Core dev 870
http://ci.onarandombox.com/job/Multiverse-Core/
QuickShop 5.1.0.9
https://www.spigotmc.org/resources/quickshop-reremake-1-19-ready-multi-currency.62575/
AntiPopup (latest commit - https://github.com/KaspianDev/AntiPopup/commit/81091603cf7dbaa921b9bafdabbf0c495bda12b3)
https://github.com/KaspianDev/AntiPopup/actions/runs/2817682753

server.properties
```
enforce-secure-profile=false
online-mode=false
```
spigot.yml
```
bungeecord: true
```

* Login through Waterfall -> Paper server
* Try chatting in a region flagged ``send-chat: DENY``.
* ``Chat message validation failure`` kicks happen.

Alternatively;

* Login through Waterfall -> Paper server
* Try purchasing from a chest shop that requires you to specify how many items you wish to buy in chat
* ``Chat message validation failure`` kicks happen.

When _removing_ AntiPopup from the server, very oddly for some reason, you are required to restart the server **twice** to clear whatever it did to block messages. This is probably why removing it is causing some confusion when testing and the kicks still happens.

* Stop Server
* Remove / disable AntiPopup from Paper plugins folder
* Start Server
* Login Waterfall -> Paper
* Kicks still happen if chatting in disabled region
* Stop Server
* Start Server
* Login Waterfall -> Paper
* Kicks no longer happen.

Similarly, if you do _not_ use a proxy to login and have standard online mode / no bungeecord forwarding settings in the Paper environment, you _can_ use AntiPopup on the server to disable the tooltip warning for non secure chat perfectly fine. (For if supporting older versions.) It does not cause the kicking when chat is cancelled by plugins. 

The kicking issues are _entirely_ related to using AntiPopup on a Paper server behind a Proxy. Hope this helps narrow down the problem if it's a plugin issue or something possibly going on with the proxy.

---

ChatControl-Red causing kicks whenever someone chats now is from the same issue and only when connecting behind a proxy while using AntiPopup.

**Comment by KaspianDev** [comment]
I'll investigate it further with waterfall, please move all messages related to antipopup to my discord server or GitHub issues
