### ISSUE TITLE
Feature seed config conversion error spam: Could not deserialize key ... into net.minecraft.core.Holder

### ISSUE THREAD

**Issue by Phoenix616** [PaperSpigot/Paper#8277]
### Stack trace

One of many errors:
```
[23:33:35] [Server thread/ERROR]: [io.papermc.paper.configuration.serializer.collections.MapSerializer] Could not deserialize key prototype_ore_dirt into net.minecraft.core.Holder<net.minecraft.world.level.levelgen.feature.WorldGenFeatureConfigured<?, ?>> at [feature-seeds, features]
```

Full log:
[latest.log](https://paste.gg/p/anonymous/0f89fda268d042f6bc64ab9cdff98d47)

### Plugin and Datapack List

None, but [this legacy paper.yml config](https://paste.gg/p/anonymous/ba8f2d35a2124ff0a27d0e0ec2e62e9d) to be converted.

### Actions to reproduce (if known)

1. Insert [this config](https://paste.gg/p/anonymous/ba8f2d35a2124ff0a27d0e0ec2e62e9d) which was generated with the `worlds.default.feature-seeds.generate-random-seeds-for-all` option in some previous version (don't know when for sure)
2. Start server with 1.19.2 b123
3. Observe errors on first start on config conversion (seeds are converted into new per-world config file even though the error is printed)

### Paper version

git-Paper-123 (MC: 1.19.2)

### Other

Error seems to be due to (invalid/outdated) keys in the config. Those were created with an older Paper version though. Updating from a feature seed config generated on latest 1.18.2 does not exhibit those errors though.

Questionable if it's worth hiding these if they really are invalid now as the user might want to know about them. Just a bit of annoying/scary spam if one wants to convert dozens of multiverse worlds like in my case...

**Comment by Machine-Maker** [comment]
I just don't know what the best thing to do is. We could just ignore invalid ones completely, or remove invalid ones.

**Comment by Machine-Maker** [comment]
I think these should def be displayed. It is invalid and just leaving or ignoring invalid input isn't a good thing here.
