### ISSUE TITLE
Server sticking see ss

### ISSUE THREAD

**Issue by Qula2d** [PaperSpigot/Paper#8278]
### Expected behavior

See
![Screenshot_2022-08-11-19-24-00-569](https://user-images.githubusercontent.com/96001831/184149808-5a45d7fe-d345-4cbf-a14c-48bc4ec73e53.jpeg)

### Observed/Actual behavior

Help me
![Screenshot_2022-08-11-19-24-00-569](https://user-images.githubusercontent.com/96001831/184149898-756cd808-4424-4fd0-8d24-0c5b48db1999.jpeg)

### Steps/models to reproduce

I am unable to understand issu

### Plugin and Datapack List

41

### Paper version

All latest 1.19.2

### Other

Same
![Screenshot_2022-08-11-19-24-00-569](https://user-images.githubusercontent.com/96001831/184150055-7c2ab708-a4b3-4e99-852b-6130ee46208c.jpeg)

**Comment by electronicboy** [comment]
for support, please use the discord/forums/IRC; the thing stalls while loading PAPI, so general advice would be to try without plugins or maybe speak to your host

**Comment by kennytv** [comment]
Please follow the issue template properly.
