### ISSUE TITLE
InventoryClickEvent gives InventoryAction.NOTHING when getting a custom result from an anvil

### ISSUE THREAD

**Issue by Xeonmeister** [PaperSpigot/Paper#8279]
### Expected behavior

So i have a plugin where you can put a knowledge book in an anvil and it gets all the enchantments from the second item put in, so the result is the green book with the second item's enchants. With the PrepareAnvilEvent i set this new enchanted knowledge book as the result and i set a custom repair cost in the anvilinventory.

In theory when i get the item out of  the anvil i should get InventoryAction.PICKUP_ALL from the InventoryClickEvent, i should not be able to take the book out if i dont have enough levels and if i do then the levels should be taken.

### Observed/Actual behavior

Even though i hear the anvil sounds when i take the result out i get InventoryAction.NOTHING from InventoryClickEvent, my experience remains untouched and i can take the result out even if i dont have enough levels. The knowledge book that i get from the anvil remains in the inventory, so it's not just visual, i really get the result from the anvil.

When the knowledge book result is taken from the anvil it seems like it removes the levels from the player but after teleportation or any xp change (killing a mob or picking up any xp source) it shows the correct xp value.

### Steps/models to reproduce

In the PrepareAnvilEvent check if the first item is a knowledge book and if the seconds item has any enchants.
If this is true then set the result to be a knowledge book with the second item's enchants.
(I think this is optional) Set a custom repair cost.
Check the InventoryAction when you get the item out of the anvil. You get the item but it says it's inventoryAction.NOTHING.

### Plugin and Datapack List

"my plugin using the PrepareAnvilEvent", Protocollib, Multiverse, VoidGen, Vault, WorldEdit, Squaremap

### Paper version

git-Paper-125 (MC: 1.19.2)

**Comment by lynxplay** [comment]
I fail to replicate this with the following setup code:
```java
@EventHandler
public void on(final PrepareAnvilEvent event) {
    final ItemStack firstItem = event.getInventory().getFirstItem();
    if (firstItem == null || firstItem.getType() != Material.KNOWLEDGE_BOOK) return;

    final ItemStack secondItem = event.getInventory().getSecondItem();
    if (secondItem == null) return;

    final ItemMeta itemMeta = secondItem.getItemMeta();
    if (itemMeta == null) return;

    final var result = firstItem.clone();
    result.addUnsafeEnchantments(itemMeta.getEnchants());
    event.setResult(result);
    event.getInventory().setRepairCost(2);
}

@EventHandler
public void on(final InventoryClickEvent event) {
    event.getWhoClicked().sendMessage(Component.text(event.getAction().name()));
}
```

As expected I am yielded the InventoryAction.PICKUP_ALL action when clicking the result item out of the inventory.

If you can provide proper replication logic (java code) that works on a plain paper server without other plugins that may potentially mess with stuff, please post them on the issue and I can reopen it for you if I can replicate your issue with your provided code.

**Comment by Lulu13022002** [comment]
I can reproduce with the same code (without the repair cost modified) using
a KNOWLEDGE_BOOK and an enchanted item (non standard book but on a custom item enchanted)
for example with /give @p stone{Enchantments:[{id:aqua_affinity,lvl:1}]} 1
```Java
 @EventHandler
    public void e(PrepareAnvilEvent e) {
        ItemStack firstSlot = e.getInventory().getFirstItem();
        if(firstSlot != null && firstSlot.getType() == Material.KNOWLEDGE_BOOK) {
            ItemStack secondSlot = e.getInventory().getSecondItem();
            if(secondSlot != null && !secondSlot.getEnchantments().isEmpty()) {
                ItemStack result = firstSlot.clone();
                result.addUnsafeEnchantments(new HashMap<>(secondSlot.getEnchantments()));
                e.setResult(result);
            }
        }
    }

    @EventHandler
    public void e(InventoryClickEvent e) {
        if(e.getAction() != InventoryAction.NOTHING) return;
        getLogger().info(e.getAction() + " " + e.getCursor());
        //Thread.dumpStack();
    }
```

**Comment by lynxplay** [comment]
Alright thanks :+1: I'll look into it

**Comment by lynxplay** [comment]
Alright, thanks for looking into this. This is actually a works as intended (see #7783).
By default the anvil recipe is denied, (introduced [here](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/b5559f8c4d6a23db218c1071f95e9314c82d4010). Listeners that want to create a custom result have to properly "allow" it by giving some cost that is >= 0.

**Comment by Lulu13022002** [comment]
But the javadoc in PrepareAnvilEvent#setResult should mention that probably ?

**Comment by lynxplay** [comment]
Possibly ? I mean, feel free to PR that into the https://github.com/PaperMC/Paper/blob/master/patches/api/0054-Fix-upstream-javadocs.patch

**Comment by Lulu13022002** [comment]
So i think this issue is a cannot reproduce finally ^^, i have just failed to test that properly cause they get the item unlike me
