### ISSUE TITLE
BossMania conflicts with paper sometimes and then other times doesn't

### ISSUE THREAD

**Issue by cjhickson647** [PaperSpigot/Paper#8304]
### Expected behavior

BossMania has no issue spawning in bosses in unloaded chunks at it loads the chunks before spawing them.

### Observed/Actual behavior

Sometimes it works no issue. Other times when the server starts an issue pops up saying Could not pass event ChunkLoadEvent to BosMania v1.8.22. And it spams the console that until I force kill the server with task manager.

### Steps/models to reproduce

Install latest version of BossMania v1.8.22. Create a boss, custom spawn it at a block in the world. Restart the server a couple times.

### Plugin and Datapack List

 Plugins (26): AcceptTheRules, AuctionHouse, BossMania, Brewery, Chunky, ClearLag, CustomCrafting, Essentials, EssentialsProtect, EssentialsSpawn, EvoDragons, ExecutableItems, FreedomChat, GriefPrevention, GrimAC, InventoryRollbackPlus, LiteEco*, LuckPerms, Mobz, MythicMobs, SCore, Terra, Vault, WolfyUtilities, WorldEdit, WorldGuard

Plugins are not the issue, I've removed countless plugins and readded them back.

### Paper version

This server is running Paper version git-Paper-130 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 4ba43fe)
You are running the latest version
Previous version: git-Paper-125 (MC: 1.19.2)

### Other

[2022-08-15-26.log](https://github.com/PaperMC/Paper/files/9347524/2022-08-15-26.log)
If you need a copy of the BossMania plugin, I can provide it.

**Comment by electronicboy** [comment]
Plugin is somehow inducing chunk loads inside of chunk load events, we can't really diagnose issues around paid software

**Comment by cjhickson647** [comment]
The plugin author says "Tell them that the plugin just checks if a location is located inside that chunk that has been just loaded"
![image](https://user-images.githubusercontent.com/77416223/184789034-a1f3da4e-e637-4244-9203-9e84ff641b8e.png)

**Comment by electronicboy** [comment]
And the way they look to be doing thag will induce chunk loads of unloaded chunks inside of the chunk load event, papers chunk system improvements loads chunks fast enough that plugins doing this can induce massive issues due to how mojangs logic works; tell them to compare the locations x/z rather than calling getChunj

**Comment by cjhickson647** [comment]
They say thanks!

**Comment by cjhickson647** [comment]
New issue, they fixed it but they didn't? Do you know what going on here?
[2022-08-17-2.log.gz](https://github.com/PaperMC/Paper/files/9363934/2022-08-17-2.log.gz)

**Comment by cjhickson647** [comment]
Also I was told if you said the plugin used too much memory to tell you it only ran 1 operation.
![image](https://user-images.githubusercontent.com/77416223/185172695-d9e5028f-417e-472d-875c-f4c4e2b9a661.png)

**Comment by electronicboy** [comment]
They still have the exact same issue as before, don't call getChunk on potentially unloaded chunks in the ChunkLoadEvent.
