### ISSUE TITLE
getDisplay() method of Advancement from the Spigot API does not work

### ISSUE THREAD

**Issue by Tennessene** [PaperSpigot/Paper#8305]
### Expected behavior

Using this method should work and not put out [errors](https://github.com/PaperMC/Paper/files/9347523/error.txt). Paper promises to retain full compatibility with the Spigot API, but this does not allow that. It works on a Spigot server, but it doesn't on a Paper one.

### Observed/Actual behavior

It did not execute the code successfully and printed out errors in the console

### Steps/models to reproduce

1. Write a plugin with PlayerAdvancementDoneEvent that tries to get the display of an advancement like so or [download mine](https://github.com/PaperMC/Paper/files/9347534/HaloBattles-1.0.zip)):
`@EventHandler
    public void onSlotChange(PlayerAdvancementDoneEvent e) {
        Bukkit.broadcastMessage(e.getAdvancement().getDisplay().getTitle()); // OR Bukkit.broadcastMessage(e.getAdvanc
ement().getDisplay().getDescription());
    }`
2. Run the vanilla command /advancement revoke @s everything
3. Run the vanilla command /advancement grant @s only minecraft:story/shiny_gear (it doesn't matter what advancement you put as the last argument)
4. The plugin won't be able to print out the display name of the advancement and it will cause the console to print out the errors I gave above

### Plugin and Datapack List

Plugins (9): Chunky, HaloBattles (my custom plugin that caused this problem on Paper), PlugManX (PlugMan), ProtocolLib, UpdateChecker (another custom plugin), ViaBackwards, ViaRewind, ViaVersion, WorldEdit

### Paper version

This server is running Paper version git-Paper-130 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 4ba43fe)

**Comment by electronicboy** [comment]
This is a known abi break which there ain't too much we can do about without causing more issues

**Comment by Tennessene** [comment]
I could work around it for what I'm using it for, but this really should be fixed somehow. Again, you guys said that Paper would retain compatibility for the Spigot API:

![image](https://user-images.githubusercontent.com/61335841/184787339-b94d65fb-2476-43c8-8a35-9d716b2fe6d9.png)

I mean why do you guys put that there if it really doesn't retain compatibility. Can you add "mostly" or "nearly full" (might sound better) before retains, because it's kind of misleading

**Comment by electronicboy** [comment]
Because we maintained compatability for years until people started mirroring the odd bit of work here and there that has existed in paper for a good while upstream, this is a fairly recent breakage in the scheme of the website, etc

We still retain 99.999% compatibility, but aren't going to remove our own API or break paper plugins for methods which would be deprecated on addition to Paper

**Comment by Tennessene** [comment]
I see. I wasn't trying to criticize, but it was a little misleading
