### ISSUE TITLE
Bukkit#broadcastMessage doesn't make urls clickable

### ISSUE THREAD

**Issue by rexlManu** [PaperSpigot/Paper#8309]
### Expected behavior

urls are clickable

### Observed/Actual behavior

In latest spigot 1.19.2 urls are clickable when sent with Bukkit#broadcastMessage(String message)

In paper this doesn't work anymore.

### Steps/models to reproduce

```
event.getPlayer().sendMessage("https://example.com"); // clickable
Bukkit.broadcastMessage("https://example.com"); // not clickable

// in vanilla spigot, both messages are clickable
```

### Plugin and Datapack List

irrelevant

### Paper version

every paper version with advencture until now

**Comment by sovtec** [comment]
Mabye you can use the minimessage format

**Comment by rexlManu** [comment]
> Mabye you can use the minimessage format

Yes but the functionality is different from spigot and paper. That is the reason why i reported it here

**Comment by Machine-Maker** [comment]
Similar to https://github.com/PaperMC/Paper/pull/6254, we aren't interested in adding functionality which "changes" a string automatically. Instead links should be turned into click events on components by plugins themselves instead of some automatic system.
