### ISSUE TITLE
ServerChunkCache#getChunk doesn't use ServerChunkCache#getChunkFuture when possible

### ISSUE THREAD

**Issue by masmc05** [PaperSpigot/Paper#8313]
### Expected behavior

When a plugin written for spigot, which without finished hangar is hard to tell if plugin has better support for paper api, wants to get chunk asyncronously, to automatically redirect to proper paper async api

Since with vanilla/spigot you won't get the chunk immediatly because of waiting for main thread, i don't think calling async api and waiting for it will be worse

### Observed/Actual behavior

The vanilla behaviour of redirecting the request to main thread to use exacltly same method isn't overriten, and it blocks main thread by waiting for async chunk load

### Steps/models to reproduce

1. have a simple spigot plugin that has some heavy async tasks
2. have enough player so these heavy tasks will happen more often, and less possibilities to find which is the problematic plugin
3. see that because it loads chunks using spigot methods, the main thread is blocked without a good reason 

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/63639746/185605151-60b3bfe7-2707-45b2-aae2-5f76657f62a5.png)
![image](https://user-images.githubusercontent.com/63639746/185605194-d3e7e7c7-29ed-464b-9da5-a275638712c4.png)
(drafts are just custom loot tables)

### Paper version

Current: git-Purpur-1762 (MC: 1.19.2)*
Previous: git-Mirai-24 (MC: 1.19.2)
* You are running the latest version

(the problematic code isn't overriden there, but i'm sure you can undertand that without my explanation)

### Other

here you can see the vanilla redirect of request to main thread, and i don't understand why isn't used async chunk api
![image](https://user-images.githubusercontent.com/63639746/185605344-4bfe1cc4-142e-42df-8ab9-67db53aa195f.png)
an example of spark where is impossible to tell which plugin loads chunk async with spigot methods
![image](https://user-images.githubusercontent.com/63639746/185605468-cd774fc4-fdf5-4d9e-b779-f105f1a6c234.png)
the method i think could be used instead of vanilla redirect (which is in the same class)
![image](https://user-images.githubusercontent.com/63639746/185605941-b12c6614-9cd4-435d-ba76-28908538f0d0.png)

I think there may be a reason why that wasn't overwritten, but couldn't get a good explanation on discord

**Comment by kennytv** [comment]
Minecraft internal methods are not API, and that method obviously does not return a future but immediately wants a chunk object. If people want to make use of Paper's asynchronous chunk loading, they have to use Paper API.

**Comment by PedroMPagani** [comment]
Just like 2 other devs answered in the discord. contact the plugin developers that are touching chunks, and you might have your blocks solved.

**Comment by masmc05** [comment]
hmm, ok, so that was the reason
Then why not in Word#getChunk, or at least could you add a flag there that will show in console the stacktrace of the caller to easier find the cause plugin?

**Comment by PedroMPagani** [comment]
Can you send your spark report, someone might be able to find what's calling it.

**Comment by masmc05** [comment]
> Can you send your spark report, someone might be able to find what's calling it.

The support for offline mode servers aren't great that's why i didn't want to send it
https://spark.lucko.me/V1gX4UvdLj
if i run the spark the server starts to have a lot worse performance drop, so still trying to find it without it, but if the situation will continue to be that bad then i'll get a proper profiler, but already have some suspections so untill we don't clear suspections we'll try that way

**Comment by PedroMPagani** [comment]
MobFarmManager is your source of lag, you're not wrong, people judge offline mode too much living in a country where a Minecraft account is just a lunch, while for others it might be 20% of the avg incoming.

**Comment by PedroMPagani** [comment]
I've figured the issue by looking at your sources in the spark, and that's the one calling getChunk,

**Comment by masmc05** [comment]
yeah, that's another issue that we're fixing, if that was the issue, then it'll be good, but it shouldn't be for the other 50% lags which are for calling from async

**Comment by PedroMPagani** [comment]
There's no main lag from calling from async, the representation you've showed comes from async tasks, that's just cpu usage spark also collects, the actual lag come from 2 sources in your spark report, Better structures and MobFarmManager, I am literally telling you the truth!

**Comment by PedroMPagani** [comment]
I mean, there would be lag yes, but in your case its not whats happening

**Comment by PedroMPagani** [comment]
If there are async calls, you can find all that out using /spark profiler --thread *, that will show all the threads usage, and then send here, and we can find out

**Comment by electronicboy** [comment]
I tried looking at this a good few years ago before many dozen refactors of this system by mojang and paper; last I looked, doing this properly was far more effort involved than I cared to deal with for an unsupported use case, looks like it's easier now, but, plugins just shouldn't be touching this stuff async, and the fact that stuff exists to prevent them blowing the server up entirely is really just a nicety at best;

There is "main lag" from stuff calling that off the main thread, it literally just defers a sync getChunkAt over to the main thread, thus turning a sync load off the main thread to a sync load on the main thread

**Comment by PedroMPagani** [comment]
Yep, I saw that after my answer, anyways, the lag comes from that source.

**Comment by masmc05** [comment]
> I tried looking at this a good few years ago before many dozen refactors of this system by mojang and paper; last I looked, doing this properly was far more effort involved than I cared to deal with for an unsupported use case, looks like it's easier now, but, plugins just shouldn't be touching this stuff async, and the fact that stuff exists to prevent them blowing the server up entirely is really just a nicety at best;
> 
> There is "main lag" from stuff calling that off the main thread, it literally just defers a sync getChunkAt over to the main thread, thus turning a sync load off the main thread to a sync load on the main thread

even ignoring bad plugins, it's a bit sad, i wish in future there will be a better support for async read only operations, so some sort of CAS synchronization could be done by plugins, by preparing the sync operation data in async, and in sync just testing the actuality of found data (so when a plugin for example wants to spawn a structure and finds a place, it could search for it in async, and in sync only test if found spot is still eligible, and place the structure there)
