### ISSUE TITLE
Anti X-Ray not working below Y = 0

### ISSUE THREAD

**Issue by Dweezy750** [PaperSpigot/Paper#8314]
### Is your feature request related to a problem?

Anti X-Ray is currently wokring to Y = 0, but dont below.

### Describe the solution you'd like.

Since 1.18 with the new chunks, we've Y = -64 and Xray needs to cover this range, also.

### Describe alternatives you've considered.

-

### Other

-

**Comment by NoahvdAa** [comment]
Did you add the new deepslate blocks that generate <0 to your config? See [this guide](https://docs.papermc.io/paper/anti-xray) for a template that has them included.

**Comment by lynxplay** [comment]
Please provide your paper configuration. I'd take a wild guess and say that deepslate is not in your replacement blocks.

**Comment by Dweezy750** [comment]
Here's a screenshot flying on y = -4, see above, xray working fine, but stops working on y = 0

https://snipboard.io/aqYyGW.jpg

CONFIG:
    anti-xray:
      max-block-height: 128
      use-permission: false
      lava-obscures: false
      enabled: true
      engine-mode: 2
      max-chunk-section-index: 3
      update-radius: 2
      hidden-blocks:
      - copper_ore
      - deepslate_copper_ore
      - gold_ore
      - deepslate_gold_ore
      - iron_ore
      - deepslate_iron_ore
      - coal_ore
      - deepslate_coal_ore
      - lapis_ore
      - deepslate_lapis_ore
      - mossy_cobblestone
      - obsidian
      - chest
      - diamond_ore
      - deepslate_diamond_ore
      - redstone_ore
      - deepslate_redstone_ore
      - clay
      - emerald_ore
      - deepslate_emerald_ore
      - ender_chest

**Comment by lynxplay** [comment]
that configuration is missing the crucial part both noah and I were referencing. The `replacement-blocks`.
Please post the entirety of your anti-xray configration

**Comment by Dweezy750** [comment]
replacement-blocks:
      - stone
      - oak_planks
      - dirt

**Comment by lynxplay** [comment]
Well there you go. As stated, you need to add deepslate. Please checkout the guide noah linked to properly  setup your xray.
For any further support, please see our [discord](https://discord.gg/papermc) #paper-help channel.
