### ISSUE TITLE
[1.19.2] Angered Zombified piglins are stuck when disconnect/reconnect

### ISSUE THREAD

**Issue by soyouzpanda** [PaperSpigot/Paper#8317]
### Expected behavior

When Zombified piglins are mad at you, and you disconnect and reconnect, all angered zombified piglins must still be angered and following you.

### Observed/Actual behavior

WhenWhen Zombified piglins are mad at you, and you disconnect and reconnect, a lot of them don't move or follow you (are they still angered ?).

### Steps/models to reproduce

- Build gold farm (for example Ilmango's gold farm)
- Run the farm by hitting a zombified piglin
- Wait ~10-15 seconds (to be sure)
- Disconnect and reconnect to the server
- Watch

### Plugin and Datapack List

Slimefun
Chunky
SfChunkInfo
EcoPower
ExtraGear
ElectricSpawners
SFCalc
LiteXpansion
spark
ExtraHeads
PrivateStorage
Galactifun
SimpleStorage
SlimyRepair
DyedBackpacks
InfinityExpansion
Networks
SlimefunWarfare

### Paper version

git-Paper-"2da891f" (MC: 1.19.2)

### Other

I've already experienced this issue without plugin, and in a spigot server with the same plugins, there is no issue.

**Comment by lynxplay** [comment]
I downloaded an example piglin farm from [here](https://www.youtube.com/watch?v=mZWlTU4gz3o). While the stated behaviour occurs on paper, some piglins basically loosing aggression and just standing around, this also happens to me when testing this on a vanilla client as a singleplayer map as well as on latest spigot.

Can you provide the exact example setup (either through a world_nether or a schematic, whatever suites you best).

**Comment by soyouzpanda** [comment]
I'm sorry I forgot to mention that you need to hit zombified piglin another time (after reconnecting).
However my new tests ([here](https://www.youtube.com/playlist?list=PLNz6AfbqK6b80FG2PU-VJVjrg6Bhzgsxt)) showed me that it was the CraftBukkit's fault, so I need to report the issue to spigotmc.
