### ISSUE TITLE
Wroldedit regen fail

### ISSUE THREAD

**Issue by Finsterofficial** [PaperSpigot/Paper#8319]
### Expected behavior

I used //regen on the entire end island and the console spits this error:
[10:14:07 ERROR]: Could not dispatch event: com.sk89q.worldedit.event.platform.CommandEvent
@7f7823cd to handler EventHandler{priority=NORMAL}

### Observed/Actual behavior

The command clearly failed and in chat told to see console for error details

### Steps/models to reproduce

Select the entire end island area and its surroundings then //regen with worldedit

### Plugin and Datapack List

'anti creeper grief v1.1.3.zip'
'anti enderman grief v1.1.3.zip'
'anti ghast grief v1.1.3.zip'
'armor statues v2.8.4.zip'
'back v1.3.3.zip'
'bat membranes v1.0.4.zip'
 bukkit
'cauldron concrete v2.0.6.zip'
'chunk loaders v1.0.4.zip'
'confetti creepers v2.2.3.zip'
'custom nether portals v2.3.6.zip'
'double shulker shells v1.3.3.zip'
'dragon drops v1.3.3.zip'
'durability ping v1.1.3.zip'
'fast leaf decay v2.0.6.zip'
'homes v1.5.4.zip'
'more mob heads v2.10.1.zip'
'multiplayer sleep v2.6.3.zip'
'pillager tools v1.1.3.zip'
'player head drops v1.1.3.zip'
'real time clock v1.1.3.zip'
'spawn v2.3.3.zip'
'timber v2.1.5.zip'
'tpa v2.3.3.zip'
'track statistics v1.1.4.zip'
'unlock all recipes v2.0.4.zip'
'villager workstation highlights v1.1.3.zip'
'wandering trades v1.6.0.zip'
'xp management v1.1.3.zip'
All datapacks from vanilla tweaks

Plugins:
ImageMaps.jar  
worldedit-bukkit-7.2.12.jar
Geyser-Spigot.jar 
LuckPerms-Bukkit-5.4.41.jar 
AntiXRay-1.9.0.jar   
BanManagerBukkit.jar  
DiscordSRV-Build-1.25.1.jar
EnderPlayers.jar

### Paper version

Currently running paper 1.19.2 a47301e

**Comment by lynxplay** [comment]
Concerning you have not provided any meaningful log to work off of, I will close this as invalid.
Issues with world edit should be reported to world edit. If you can provide the entire error log and paper is actually causing an issue down the line, I'll reopen this for you, but for now I will close this.
