### ISSUE TITLE
WorldCreator#keepSpawnLoaded(TriState) doesn't return back the builder

### ISSUE THREAD

**Issue by CDFN** [PaperSpigot/Paper#8321]
### Expected behavior

WorldCreator#keepSpawnLoaded(TriState) returns back builder so we can do more actions on it and eventually create world.

### Observed/Actual behavior

WorldCreator#keepSpawnLoaded(TriState) returns void which disallows fluent world creation via 1 builder.

### Steps/models to reproduce

```kt
            WorldCreator.name(req.realmUUID)
                .generateStructures(false)
                .generator(generator)
                .keepSpawnLoaded(TriState.FALSE)
                // oops can't do anything more, this returned void
```

### Plugin and Datapack List

---

### Paper version

Paper API 1.19.2

**Comment by electronicboy** [comment]
Already known, need to consider if we do the abi break and deal with
mitigations in 1.18 if we do

**Comment by Owen1212055** [comment]
Yeah that's a bit unfortunate, do we want to do some kind of deprecation here or just leave this as is?

**Comment by Machine-Maker** [comment]
Can we fix this with the Commodore remapping? Just rewrite old plugins that are expecting void return type

**Comment by Owen1212055** [comment]
I mean yeah I assume we could.

**Comment by electronicboy** [comment]
Yea, that's been my plan, just been kinda tryna take some time off, but I
wanna change the type in 1.18.2, as that's the version it was added iirc,
then we can have the bytecode hackery sit around for a few versions and not
have to worry about maintaining it for too long given all builds are care
would be abi compat
