### ISSUE TITLE
Windows 11: Server loading hangs for 2 mins at "Disabling further attempts to query Paging File."

### ISSUE THREAD

**Issue by kangarko** [PaperSpigot/Paper#8322]
### Expected behavior

I expect the server to start within a reasonable timeframe like the good old 1.8.8.

### Observed/Actual behavior

On Java 16+ it takes 2 minutes to boot the server:

![a](https://i.imgur.com/SJLzac1.png)

I have a dualboot Windows 7 + Windows 11. The older Windows 7 is unaffected (running the same Java version, see image above).

### Steps/models to reproduce

For the reference, I am using the following startup script below. I tried using the recommended Aikar flags to no change.

```
java -Xms4G -Xmx4G -jar paperclip.jar nogui
pause
```

### Plugin and Datapack List

Irrelevant, tried to remove all plugins to no help, this hang is happening before the Notchian server starts booting if I am not mistaken.

### Paper version

This server is running Paper version git-Paper-132 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: a76998d)

### Other

It appears that the problem has already been reported multiple times to no avail.

https://bugs.mojang.com/browse/MC-228430
https://bugs.mojang.com/browse/MC-253901
https://bugs.mojang.com/browse/MC-228885

I tried resetting my performance counters as per https://docs.microsoft.com/en-us/troubleshoot/windows-server/performance/manually-rebuild-performance-counters to no help also.

**Comment by kangarko** [comment]
Funnily enough, this does NOT happen each time. It typically does not happen the second time I boot the server after closing it (https://i.imgur.com/OaIFVDK.png).

Oddly enough it seems that it starts to happen when the server was closed for a longer time.

Again, never had any issues on Win7, Win10, only recently started to happen on Win11. Happy to provide more info upon request.

**Comment by e-im** [comment]
Did you run any sort of "debloater" script? That is where I have seen this happen most often. However, you are correct in your assessment that this is happening before the server really starts to start. there is not much that paper can do about this, bar removing the usage of oshi which will not happen.

**Comment by kangarko** [comment]
Yes I have turned off some win11 services. If anyone knows what service needs to run for this not to hang I'd be thankful :)

**Comment by e-im** [comment]
I'm not sure. There are a few issues on the [oshi issue tracker](https://github.com/oshi/oshi/issues?q=is%3Aissue+failed+to+update+counter) citing all sorts of different causes. If you figure it out, please do leave a comment. Closing this though is there is nothing for paper to change with this.
