### ISSUE TITLE
Exception generating new chunk

### ISSUE THREAD

**Issue by LordManzana** [PaperSpigot/Paper#8327]
### Stack trace

```
https://pastebin.com/Jgn9eCW7
```

### Plugin and Datapack List

ActionHealth, AdvancedPortals, ajParkour, AuthMe, BetterRTP, BotSentry, ChatItem, ChatManager, Citizens, CleanroomGenerator, ConsoleSpamFix, CustomCommands, DailyBonus, DecentHolograms, DeluxeMenus, DiscordSRV, DoubleJump, dynmap, EnchantmentLock, Essentials, FarmLimiter, FastAsyncWorldEdit (WorldEdit), FastChunkPregenerator, FastLogin, GamePoints, GCore, Geyser-Spigot, GSit, HeadsInventory, HeadsPluginAPI, InfiniteScoreboard, InventoryRollbackPlus, KeepChunks, LeaderHeadsRevamped, LuckPerms, Minepacks, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, NexEngine, Paintball, PlaceholderAPI, PlugManX (PlugMan), ProCosmetics, ProtocolLib, ResourceWorld, ServerListPlus*, SkinsRestorer, sleep-most, SlotMachine, StreamingDrops, TNTRun_reloaded, UltimateAutoRestart, UltimateClaims, UltimateTimber, Vault, ViaBackwards, ViaRewind, ViaVersion, Vouchers, WorldBorder, WorldGuard, WorldGuardExtraFlags

[vanilla (built-in)], [file/bukkit (world)]

### Actions to reproduce (if known)

Randomly crashes, can't force reproduce.

### Paper version

This server is running Paper version git-Paper-132 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: a76998d)
You are running the latest version
Previous version: git-Paper-111 (MC: 1.19.1)

### Other

Seems related with:
https://github.com/PaperMC/Paper/issues/7006

But as mentioned, my world have 30k border limit by default:
https://i.imgur.com/Q89QfXJ.png

Here latest logs near crash:
https://pastebin.com/SKujRgLk

**Comment by mikimasn** [comment]
skill issue

**Comment by LordManzana** [comment]
> skill issue

What?

**Comment by mikimasn** [comment]
S K I L L 
I S S U E

It works for me

**Comment by mikimasn** [comment]
Looks like this is not a paper issue
you should make issue on github of plugin that makes this problem(propably FastChunkPregenerator)

**Comment by LordManzana** [comment]
That error appeared before add fast chunk pregenerator, but now it appear more constantly, like 2 times per day (previous versions like 1 each 2-3 days). So I guess it not comes from the plugin you say / KeepChunks.

In addition, fastChunk only works when no players ingame.

I have an rtp plugin, a year ago the related issue seemed to talk about random teleports to a destination far from spawn point, but that's not the case since my rtp it's limited to 2k blocks.

**Comment by Owen1212055** [comment]
A buried treasure map  seems to be generating a chunk very far away, which is loading chunks but then failing due to chunk generation. How far are you allowing chunks to generate here...?

**Comment by LordManzana** [comment]
@Owen1212055 I guess you're asking for that:
At server.properties:
simulation-distance=4
view-distance=7

Spigot.yml
view-distance: default

paper-world-defaults:
delay-chunk-unloads-by: 10s
max-auto-save-chunks-per-tick: 8
prevent-moving-into-unloaded-chunks: true
treasure-maps.enabled: true

Let me know if you're asking for a different settings

**Comment by Owen1212055** [comment]
I recommend removing plugins until you find which plugin is loading chunks like this. Errors like these are usually caused by chunks being generated far away, far enough to where stuff starts to break.
