### ISSUE TITLE
Failed to load datapacks, can't proceed with server load

### ISSUE THREAD

**Issue by nickkeane** [PaperSpigot/Paper#8328]
### Stack trace

https://paste.gg/p/anonymous/ac0e511dd8b14a8dbef630ad69d4a7d0

### Plugin and Datapack List

Plugins (0):
Unknown or incomplete command, see below for error
datapack list<--[HERE]

### Actions to reproduce (if known)

1. Install MC Server Soft.
2. Create a PaperMC Server instance with Paper MC1.19.2 Build 132 jar.
3. Start the server.

### Paper version

This server is running Paper version git-Paper-132 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: a76998d)
You are running the latest version

### Other

It's inconsistent. Sometimes it crashes with the above errors, sometimes it starts fine.

**Comment by lynxplay** [comment]
We cannot comment on third party software, especially if it does not even seem to be open source.
Please reproduce this on a plain server setup or report it to mc server soft.

```bash
Unknown or incomplete command, see below for error
datapack list<--[HERE]
``` 

is also not a very descriptive list of datapacks. I'll presume you don't have any installed ?
I'd highly suggest getting in touch with mc server soft about this first, as they seem to apply on top of paper (tho again, I am guessing here, their https://github.com/mcserversoft org does not contain any source code for the software.

If you can replicate this on plain paper or the mc server soft maintainers believe this to be an actual paper error after checking their source, feel free to comment here and I'll be glad to reopen the issue for you an look into it deeper.
