### ISSUE TITLE
papers config no-permission message comes back a different message than the one you set

### ISSUE THREAD

**Issue by bungeebees** [PaperSpigot/Paper#8329]
### Expected behavior

doing a command you dont have permission for  should be the message you set in papers config

also running an unknown command should be what is set in spigots config

### Observed/Actual behavior

the message sent is "Uknown or incomplete command, see below for error"

the message sent for an unknown command is also "Uknown or incomplete command, see below for error"

### Steps/models to reproduce

run an unknown command or a command you dont have permission for as a player in a 1.19.2 paper server. 

it sends the configured message when you run an unknown command in the console.

### Plugin and Datapack List

none

### Paper version

paper-1.19.2-132

### Other

this problem only happens on a paper 1.19.2 server, 1.19 does not do this

**Comment by lynxplay** [comment]
Replicable. This is related to [#8223](https://github.com/PaperMC/Paper/issues/8223) and is a consequence of the large change upstream did to command handling. As we are still figuring out whether we want to move closer to vanilla or revert back to the bukkit command system, this issue should be addressed once either of those options were chosen and implemented :+1:

**Comment by Machine-Maker** [comment]
This should be fixed by #8232
