### ISSUE TITLE
Villagers passing through extended pistons

### ISSUE THREAD

**Issue by HalD63** [PaperSpigot/Paper#8330]
### Expected behavior

I have a villager trading hall where I use pistons to keep villagers and push them up and down towards a zombie. I would expect the villagers to stand on the extended piston so they are in line with the workstations.

### Observed/Actual behavior

Villagers pass through the piston when it extends and fall back down to the lower level.

### Steps/models to reproduce

It is consistently happening to all of our villagers, so I guess would just put a villager on a piston where they can't move, extend it upwards and watch them fall.

### Plugin and Datapack List

Dynmap
AFK DIsplay
Anti Enderman Griefing
Armor Statues
Custom Nether Portals
Double Shulker Shells
Dragon Drops Elytra
Fast Leaf Decay
Kill Empty Boats
Larger Phantoms
More Mob Heads
Multiplayer Sleep
Name Colors
Player Head Drops
Silence Mobs
Spectator Night Vision
Tag
Track Raw Statistics
Track Statistics
Unlock All Recipes
Villager Job Fix
Wandering Trades (Hermit Edition)

### Paper version

This server is running Paper version git-Paper-133 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 0bf8790)
You are running the latest version
Previous version: git-Paper-111 (MC: 1.19.1)

**Comment by lynxplay** [comment]
I cannot replicate this whatsoever. Can you provide a proper example setup on a latest paper server without plugins ?
E.g. schematic/world download.
Here is my simple test in action:

https://user-images.githubusercontent.com/32834385/186995393-42a9d811-550c-495b-99ed-2f9bf371fcf9.mp4

**Comment by Owen1212055** [comment]
I will be closing this issue as we have been unable to reprodeuce this. Please feel free to comment on this issue if you are able to reproduce it again on the latest version.

Thank you! 😄
