### ISSUE TITLE
Warn the developer when attempting to teleport an entity that has passengers

### ISSUE THREAD

**Issue by Teamplayer** [PaperSpigot/Paper#8331]
### Is your feature request related to a problem?

Recently I ran into an issue where teleportation of a player did not work. This issue was very hard to isolate as the issue only occurred consistently only for some players sometimes across multiple servers. The bottom line is that this issue was caused by a cosmetics plugin that had an entity ride the player to give cosmetics, and apparently the Bukkit API will not teleport entities that have passengers. This issue took multiple days to isolate and resolve, and I'm sure I'm not the only one who's ran into this issue.

### Describe the solution you'd like.

Log a warning in console whenever a teleport is going to be ignored due to the fact that the target entity has passengers on it. I feel this is inline with other warnings that get logged to help developers diagnose issues of improper API usage: ex. warnings that warn of attempting to teleport entities off main thread.

### Describe alternatives you've considered.

When a teleport is blocked due to the entity target having passengers, a teleport event is not fired. Because of this, it would be impossible to implement this functionality into a plugin.

The other alternative to this is for the Paper API to allow entities with passengers to be teleported. As far as I'm aware though, the Bukkit team intentionally made this restriction to prevent some weird bugs. From the limited discussions I've read about this, you are able to teleport entities with passengers using NMS code, but it can cause issues. For these reasons, I don't recommend that Paper allow entities with passengers to be teleported.

**Comment by electronicboy** [comment]
https://jd.papermc.io/paper/1.19/org/bukkit/entity/Entity.html#teleport(org.bukkit.Location,org.bukkit.event.player.PlayerTeleportEvent.TeleportCause,boolean,boolean)

1) teleport returns a boolean as to if it was allowed, there's no "result" type thing to let you specifically see *why* it failed, but, you can see that it did fail
2) Paper lets you disable the check, nms has generally allowed teleporting entities with passengers for years now, see portals, this API has been pretty well tested now afaik
