### ISSUE TITLE
Add a method to prevent the creation of the paper.yml-README.txt file.

### ISSUE THREAD

**Issue by RealTriassic** [PaperSpigot/Paper#8332]
### Is your feature request related to a problem?

Currently, this file is created in your server's files even if you have fully acknowledged the location of the new configuration files. This is really annoying, especially if you are looking to keep your server files clean.

### Describe the solution you'd like.

Possibly allow users to add a Java flag to their servers to prevent the creation of this file, or, even better, only generate the `paper.yml-README.txt` file once and then once it is deleted by the user, do not re-generate it anymore.

### Describe alternatives you've considered.

I have tried opening a feature request on Purpur's GitHub repository about this, but ended up realizing that this should be brought up to Paper directly.

**Comment by electronicboy** [comment]
I mean, theres no real way to check if a file was created or not, I guess we could maaaybe move it to around where the config folder itself is created, will probably miss a few people, but, god knows

**Comment by RealTriassic** [comment]
Maybe have a configuration option in paper-global.yml that when set to true prevents the creation of the file? Not sure if adding a whole new configuration option to paper-global.yml just for this is a good idea, but it would work as a solution.

**Comment by Brokkonaut** [comment]
Maybe only create it when config/paper-global.yml did not exist on server start. So it will be created only once but if you delete it it will not be recreated.

**Comment by Lulu13022002** [comment]
Yes i prefer that, Brokkonaut, a config option doesn't make sense, generally a config option is to tweak things but here people will just turn on/off one time and never change that option again later. It's not like one day you wake up and say hum this file has really miss me...

**Comment by Insprill** [comment]
#8334 should resolve this.
