### ISSUE TITLE
Static getHandlerList method required!

### ISSUE THREAD

**Issue by DasShorty** [PaperSpigot/Paper#8348]
### Expected behavior

Plugin should run perfect without any problems

### Observed/Actual behavior

The BlockPistonEvent has no HandlerList. Therefore i got an IllegalPluginAccessException 

### Steps/models to reproduce

Use the BlockPistonEvent in a Paper Plugin

### Plugin and Datapack List

ServerTechnology (own), TheNewEconomy, Vault

### Paper version

This server is running Paper version git-Paper-138 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 09904fd)
You are running the latest version
Previous version: git-Paper-136 (MC: 1.19.2)

**Comment by electronicboy** [comment]
You cannot listen to BlockPistionEvent, you need to listen to one of the sub classes which has a handler list

**Comment by DasShorty** [comment]
thanks :)
