### ISSUE TITLE
Furnaces with a smelt speed modifier do not smelt items

### ISSUE THREAD

**Issue by Aaron2550** [PaperSpigot/Paper#8350]
### Expected behavior

Furnaces that had their smelt speed multiplier set should still smelt items.

### Observed/Actual behavior

The speed multiplier gets applied but once the arrow "loading bar" is at 100%, no item is consumed from the input slot and no Item is put out to the output slot

### Steps/models to reproduce

- Get Paper
- Write small test-plugin
- Start Server
- Place Furnace
- Try to smelt stuff
- Observe Problem

### Plugin and Datapack List

No Plugins or Datapacks, except for my test-plugin which sets the smelt speed multiplier in a BlockPlaceEvent Listener:

```java
@EventHandler(ignoreCancelled = true, priority = EventPriority.MONITOR)
public void onBlockPlace(BlockPlaceEvent event) {
  if (event.getBlockPlaced().getState() instanceof Furnace furnaceBlock) {
    furnaceBlock.setCookSpeedMultiplier(0.5);
    furnaceBlock.update();
  }
}
```

### Paper version

This server is running Paper version git-Paper-138 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 09904fd)
You are running the latest version

### Other

See #4697

![javaw_Xz4BGtGR5H](https://user-images.githubusercontent.com/24834067/188610549-e2ce808b-3ef2-480e-b450-23b36a052713.gif)

**Comment by Machine-Maker** [comment]
I can't replicate this. I put that bit of code into a plugin, started the server with it, placed a furnace, put a stack of cactus in the input and 1 coal in the fuel slot, and that one piece of coal smelted exactly 4 cactus. which is what's expected if you cut the speed in half.

**Comment by Aaron2550** [comment]
I can't either. I must be going insane...
