### ISSUE TITLE
Log4j Custom Config feature

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#8352]
### Is your feature request related to a problem?

Iwanted to disable some logging for mongodb java driver and had to do some hacking overriden of their Loggers class to get it done.

### Describe the solution you'd like.

I would like a parameter that I can specify at server start which will tell where the log4j xml file is and use it instead of the one in the paper jar.

### Describe alternatives you've considered.

I tried overriding the log4j xml programmaticlly with `ConfigurationBuilder<BuiltConfiguration>` and `Configurator.reconfigure(builder.build());` which causes some issues with looping logs.

**Comment by electronicboy** [comment]
that already exists in L4J, `-Dlog4j.configuration=` before -jar
