### ISSUE TITLE
Non-player entities cannot be added to a team

### ISSUE THREAD

**Issue by onLaait** [PaperSpigot/Paper#8355]
### Expected behavior

All entities can be added to a team.

### Observed/Actual behavior

Only players can be added to a team.

### Steps/models to reproduce

1. Summon some entities.
2. Create a team (`/team add red`), and add all entities to the team (`/team join red @e`).
3. Check who are on the team (`/say @e[team=red]`).

### Plugin and Datapack List

none

### Paper version

Can confirm in both 1.18.2 and 1.19.2

This server is running Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)
This server is running Paper version git-Paper-139 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 36a5f15)

**Comment by lynxplay** [comment]
Ensure to enable https://docs.papermc.io/paper/reference/world-configuration#allow-non-player-entities-on-scoreboards either in your default world configuration or in a specific world configuration.

This is off by default to improve collision checks.

If setting said value to true does not solve your issue, feel free to comment and I'll reopen the issue :+1:
