### ISSUE TITLE
Internal Exception: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null

### ISSUE THREAD

**Issue by anthony114669** [PaperSpigot/Paper#8357]
### Expected behavior

not be kicked out

### Observed/Actual behavior

getting kicked out
error: Internal Exception: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null

### Steps/models to reproduce

just playing

### Plugin and Datapack List

Internal Exception: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null

### Paper version

1.19.2

### Other

Internal Exception: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null

**Comment by Owen1212055** [comment]
This tells us nothing. Please fix your issue report to include the proper information and it will be reopened.

Information like plugins used is very important, as it can tell us if a plugin is causing an error like this to occur.
