### ISSUE TITLE
IntelliJ reporting transitive vulnerable dependency by using paper-api

### ISSUE THREAD

**Issue by TheFruxz** [PaperSpigot/Paper#8362]
### Expected behavior

No vulnerability warning

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/28064149/190630199-7fa51050-c35f-4643-856a-967f11048d5c.png)
IntelliJ is posting a warning, that the paper-API contains a vulnerable dependency

### Steps/models to reproduce

- add implementation of paper-api `io.papermc.paper:paper-api:1.19.2-R0.1-SNAPSHOT` to your build.grade(.kts) file
- let IDEA rethink the situation
- done

### Plugin and Datapack List

-/-

### Paper version

current version pulled from https://papermc.io/repo/repository/maven-public/

**Comment by electronicboy** [comment]
This is 100% expected given that upstream doesn't have a policy for updating libraries, and we can't fix this without inducing API breaks
