### ISSUE TITLE
#saveminecraft

### ISSUE THREAD

**Issue by lukasz4444** [PaperSpigot/Paper#8380]
### Is your feature request related to a problem?

Microsoft forced to the game chat chat reporting system.

### Describe the solution you'd like.

Make support for old versions like 1.17 or 1.16

### Describe alternatives you've considered.

Remove chat reporting functionality from minecraft 1.19 and up server jar.

### Other

**Please don’t ignore this straight away.**

**Comment by lukasz4444** [comment]
nice 5 minutes and closing it without reason good to now that you don't care about game you are making engine right now.

Like seriously you are not supporting old versions but instead papermc support the traitor 1.19 and sure every new version that will came out later.

**Comment by lynxplay** [comment]
Feel free to read through #8043 and other issues that follow the exact same request of yours.
Our stance has been documented there rather well. The forums also have a thread somewhere in regards to this.
