### ISSUE TITLE
Structure loading adding entity effects async

### ISSUE THREAD

**Issue by Pdamian96** [PaperSpigot/Paper#8381]
### Stack trace

Hello
I have recently been running a Server and after a few days, when people we're exploring a little faster, the server crashed multiple times when a person was at a certain chunk and would continue to crash the server when logging in. I could fix this with teleporting them out which would fix it most of the time. I didnt really know where else to post this but here and I would like to know what could cause this. Thanks in advance.

Pastebin: https://pastebin.com/Vp2AmSKz

### Plugin and Datapack List

Plugins:
Chunky
Slimefun (Including Addons)

Datapacks:
Dungeons Now Loading
Incendium
Terralith

### Paper version

Version: git-Paper-142 (Git ef0e5a6)

**Comment by Owen1212055** [comment]
This in general is just due to the structure system adding an effect to an entity async.
