### ISSUE TITLE
How to fix that？

### ISSUE THREAD

**Issue by RecanLive** [PaperSpigot/Paper#8384]
### Timings or Profile link

https://timings.aikar.co/dev/?id=aac312c311d94a3eac683334a811e783

### Description of issue

An error message occurs when the player enters the gates of hell

### Plugin and Datapack List

Plugins (8): CoreProtect, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, LuckPerms, SkinsRestorer, WorldEdit

### Server config files

bukkit.yml
https://paste.gg/p/anonymous/025cd24977a6422da71bcb6bb01b4c54
spigot.yml
https://paste.gg/p/anonymous/2376ea24d87c42d9b5c0989a07199a99
paper-global.yml
https://paste.gg/p/anonymous/b460e904ea154a6bb73d8787b47db277
paper-world-defaults.yml
https://paste.gg/p/anonymous/58d476cdbcab4f4da9eb1102f239598e
server.properties
https://paste.gg/p/anonymous/091c84c0f40c4ea28c4300e478840e29

### Paper version

Previous version: git-Purpur-1735 (MC: 1.19)

### Other

https://paste.gg/p/anonymous/c0fcaffa29914c6a893d09001d5ac9d5

**Comment by electronicboy** [comment]
Please use the discord/forums for support, 1.19 is also not supported, update.

**Comment by RecanLive** [comment]
> Please use the discord/forums for support, 1.19 is also not supported, update.

So should I upgrade to the latest version to fix this? 

But I want to continue using version 1.19 which exactly caused the error

**Comment by electronicboy** [comment]
The issue tracker is not the place to seek support

Your server took too long to tick, likely in part because you're using weak/underspec'd hardware, there is nothing here to suggest a paper issue; and even if there was a paper issue, you would not get support for it running an old version

**Comment by RecanLive** [comment]
> The issue tracker is not the place to seek support
> 
> Your server took too long to tick, likely in part because you're using weak/underspec'd hardware, there is nothing here to suggest a paper issue; and even if there was a paper issue, you would not get support for it running an old version

thanks
