### ISSUE TITLE
DISPENSE_EGG condition isnt used for CreatureSpawnEvent

### ISSUE THREAD

**Issue by DaRacci** [PaperSpigot/Paper#8389]
### Expected behavior

When a dispenser summons an entity because it had an egg in it this should set the events reason to DISPENSE_EGG.

### Observed/Actual behavior

When the event is fired the events reason is the generic SPAWNER_EGG reason.

### Steps/models to reproduce

1. Egg in dispenser
2. Trigger dispenser

### Plugin and Datapack List

Only a plugin to observe the event.

### Paper version

Current: git-Tentacles-"215faae" (MC: 1.19.2)*
Previous: git-Tentacles-"0bba12b" (MC: 1.19.2)
You are running the latest version

### Other

the server version is my fork of purpurmc, however i had a look at the code from just papermc and it seems like the issue persists

**Comment by PedroMPagani** [comment]
I've tested this in the latest paper and I can confirm the Enum seems to be the wrong value.

**Comment by lynxplay** [comment]
I can also replicate this. This is an issue on spigot as well (which they lost all the way back in [1.13-pre7](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/421c1728c81e2f729dff88da2ac96535d2b8e5e8#nms-patches/DispenserRegistry.patch)).

Should be a somewhat straight forward fix that expands the existing `spawn` methods on `n.m.w.e.EntityType` to allow for entity spawning from an item stack with specific spawn reasons and then updating the spawn calls in the `n.m.c.d.DispenseItemBehavior` type.

I wonder if it would make sense to merge these changes into a general "call correct spawn reasons" patch (or something along those lines) with the existing https://github.com/PaperMC/Paper/blob/master/patches/server/0917-Add-SpawnReason-to-Tadpoles-spawned-by-Frogspawn.patch patch.
