### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AVuTuVA** [PaperSpigot/Paper#8393]
### Expected behavior

:)

### Observed/Actual behavior

https://pastebin.com/daNS5VX7

### Steps/models to reproduce

They are not there, the players played and the error is on the entire console

### Plugin and Datapack List

._.

### Paper version

Paper #174

**Comment by DIDIRUS4** [comment]
+1

**Comment by lynxplay** [comment]
I mean, looks mostly like you are getting ruined by a treasure map, which are known to be rather slow as they look for a treasure in quite a large radius on the main thread (this took longer than 10 seconds on your machine), The watchdog then prints an error to notify you that something took too long.

You can disable treasure maps in our configs.

As this chunk system is rather new, I won't pretend that I am fully versed with it yet so I can't tell you if this is caused at all by the new system or if this is a normal "well sorry treasure maps are just slow af" issue.

**Comment by AVuTuVA** [comment]
This was not the case with the old chunk system, this error appeared after the new chunk system.

**Comment by BillyGalbreath** [comment]
> This was not the case with the old chunk system, this error appeared after the new chunk system.

I guarantee this did not start happening with the new chunk system..

https://github.com/PaperMC/Paper/issues/8089
https://github.com/PaperMC/Paper/issues/7963
https://github.com/PaperMC/Paper/issues/7945
https://github.com/PaperMC/Paper/issues/7664
https://github.com/PaperMC/Paper/issues/7660
https://github.com/PaperMC/Paper/issues/7269
https://github.com/PaperMC/Paper/issues/4356
https://github.com/PaperMC/Paper/issues/4349
https://github.com/PaperMC/Paper/issues/4289
https://github.com/PaperMC/Paper/issues/4258
https://github.com/PaperMC/Paper/issues/4228
https://github.com/PaperMC/Paper/issues/4191
https://github.com/PaperMC/Paper/issues/4118
https://github.com/PaperMC/Paper/issues/4110
https://github.com/PaperMC/Paper/issues/4086
https://github.com/PaperMC/Paper/issues/4038
https://github.com/PaperMC/Paper/issues/4019
https://github.com/PaperMC/Paper/issues/3993
https://github.com/PaperMC/Paper/issues/3619
https://github.com/PaperMC/Paper/issues/3614
https://github.com/PaperMC/Paper/issues/3536
https://github.com/PaperMC/Paper/issues/2955
https://github.com/PaperMC/Paper/issues/2950
https://github.com/PaperMC/Paper/issues/2896
https://github.com/PaperMC/Paper/issues/2792
https://github.com/PaperMC/Paper/issues/2781
https://github.com/PaperMC/Paper/issues/2668
https://github.com/PaperMC/Paper/issues/2312
https://github.com/PaperMC/Paper/issues/2191
https://github.com/PaperMC/Paper/issues/1810

**Comment by AVuTuVA** [comment]
https://pastebin.com/U7j4dYBe Is this also related to the treasure map?

**Comment by lynxplay** [comment]
Yes

**Comment by BillyGalbreath** [comment]
> https://pastebin.com/U7j4dYBe Is this also related to the treasure map?

Check lines 46, 55-57, 71-72. It's putting a treasure map in a lootable chest.

**Comment by lynxplay** [comment]
Generally tho, your server is simply overloaded trying to find the treasure. Concerning it does not appear to be a deadlock as you  do have the "running behind message". So yea, this looks like a plain overloaded server issue with respect to treasure maps just being very very slow.

**Comment by lynxplay** [comment]
After a few local tests in regards to far away treasure maps, the server does not seem to deadlock.
I'll close this issue as a duplicate of, well, all the ones billy mentioned.

If this indeed is a new issue to the rewrite of the chunk system, I am sure we will receive similar issues down the line, at which point I'll reference these new issues here to keep you guys up to date :+1: 

For now, disabling treasure maps would be my recommended strategy to mitigate these overloads.

**Comment by Pantera07** [comment]
https://github.com/PaperMC/Paper/blob/master/patches/removed/1.18/No%20longer%20needed/0525-Seed-based-feature-search.patch
I think 'seed-based-feature-search' is still necessary, but moved to 'No longer needed'.

Currently, the only solution is to disable treasure-maps.
```
  treasure-maps:
    enabled: false
```

**Comment by electronicboy** [comment]
Mojang adopted parts of that, at least iirc, they may have screwed with stuff since; and the patch in general no longer applies; and the entire system is more arse to deal with now to even apply such patches
