### ISSUE TITLE
ChatColor at the console appears as gray no matter what color is used

### ISSUE THREAD

**Issue by zhro** [PaperSpigot/Paper#8394]
### Expected behavior

Color is expected to be present, as it is in Spigot.

### Observed/Actual behavior

Color appears gray when *any* color is used.

### Steps/models to reproduce

```
Bukkit.getConsoleSender().sendMessage(ChatColor.RED + "RED WORDS!");
Bukkit.getConsoleSender().sendMessage(ChatColor.GREEN + "GREEN WORDS!");
Bukkit.getConsoleSender().sendMessage(ChatColor.YELLOW + "YELLOW WORDS!");
Bukkit.getConsoleSender().sendMessage(ChatColor.BLUE + "BLUE WORDS!");
```

### Plugin and Datapack List

No plugins are used, other than a test plugin that outputs for testing.

### Paper version

This server is running Paper version git-Paper-176 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: f7d16f6)
You are running the latest version

### Other

Here is what it looks like at the Paper console:

![image](https://user-images.githubusercontent.com/4738876/192406795-9a7081a9-ce0f-4c78-8a06-22d46bdd5224.png)

Here is what it looks like from the Spigot console:

![image](https://user-images.githubusercontent.com/4738876/192407032-168648c8-4d6a-4eed-9a23-efe1838668e8.png)

**Comment by electronicboy** [comment]
iirc, this is pretty much always a weird environment issue which can be fixed by flipping https://docs.papermc.io/paper/reference/global-configuration#use-rgb-for-named-text-colors

**Comment by zhro** [comment]
Setting `use-rgb-for-named-text-colors` to `false` fixed this for me, and colors appear as expected.

What is the purpose of this option? I use Mintty for my terminal emulator. Is the default method of displaying colors incompatible with my terminal? My TTY type is set to `xterm-256color`.

**Comment by electronicboy** [comment]
Your console doesn't support rgb colors, and so the default assumption towards supporting RGB fails, looks like we can maybe improve the detection here, hm...

https://github.com/fusesource/jansi/blob/master/src/main/java/org/fusesource/jansi/AnsiConsole.java#L405

**Comment by lynxplay** [comment]
I'll mark this as a low priority issue as there are steps we can and should take here to prevent this from happening more often.

//edit: or at the very least look into improvements.

**Comment by pop4959** [comment]
@zhro Are you still able to produce this issue on the latest version of Paper 1.20.1 or newer? Paper has a new ANSI serializer which has improved terminal environment detection.

**Comment by lynxplay** [comment]
Closing this as the issue generally was improved by the change to the ansi serializer nor has this issue been active.
