### ISSUE TITLE
Add PlayerInventoryChangeEvent

### ISSUE THREAD

**Issue by Spliterash** [PaperSpigot/Paper#8403]
### Is your feature request related to a problem?

I want to track any changes to the player's inventory in my plugin. Of course, you can partially intercept ItemDrop, ItemPickup, InventoryClickEvent and so on, but even so, I can’t intercept Inventory#setItem calls from other plugins. The only way to solve the problem at the moment is a timer that will check for changes every tick.

### Describe the solution you'd like.

I suggest adding a PlayerInventoryChangeEvent that will be called every time the inventory has changed in some way, like drop, pickup, check pickup, and set from other plugins. This would solve a lot of problems for me

### Describe alternatives you've considered.

Like i say before, is a timer that will check for changes every tick.

**Comment by dawon** [comment]
Something like #7321 ?

**Comment by Spliterash** [comment]
Yes, this is it
