### ISSUE TITLE
Show a stack trace when one plugin loads a class from another plugin which isn't a (soft)depend

### ISSUE THREAD

**Issue by bergerkiller** [PaperSpigot/Paper#8407]
### Is your feature request related to a problem?

It's a pain in the butt sometimes to figure out where from a class is loaded, especially when it involves injection frameworks

### Describe the solution you'd like.

Log a stack trace when "Loaded class {0} from {1} which is not a depend or softdepend of this plugin." is logged

### Describe alternatives you've considered.

Modifying paper myself, dotting printlns all over the plugins code to find when it happens

**Comment by lynxplay** [comment]
Should probably just be part of server.properties debug or something?

**Comment by electronicboy** [comment]
too verbose for server.properties, imho; I could support a system property though

**Comment by bergerkiller** [comment]
Yeah something like that. Could even be a startup flag. I'd just really like to see what's doing it :)

**Comment by lynxplay** [comment]
True, yea a flag would work well here.
