### ISSUE TITLE
Raid factories no longer work since version paper 176

### ISSUE THREAD

**Issue by RedcosmosMC** [PaperSpigot/Paper#8415]
### Expected behavior

The factories worked very well before never having any problems

### Observed/Actual behavior

Factories no longer work, raids no longer trigger.
The gamerules raids has been verified

### Steps/models to reproduce

Here is the model made
https://www.youtube.com/watch?v=QZ9Dhzq4zlI
It worked very well before paper 176

### Plugin and Datapack List

Datapack : [vanilla (built-in)], [file/bukkit (world)], [file/Blank Datapack (world)], [file/anti enderman grief v1.1.3.zip (world)], [file/player head drops v1.1.3.zip (world)], [file/AllMobHeads_V7.2.zip (world)], [file/armor_statues_v2.9.2.zip (world)]

Plugins (5): Chunky, CoreProtect, GravityControl, SuperVanish, WorldEdit

### Paper version

1.19.2 paper 182

### Other

Sorry my english is not perfect (I'm french)

I did a rollback of the paper version but it still does not work... I have test in paper 160

I have been using paper for several years, thank you for your work!

**Comment by lynxplay** [comment]
I cannot replicate this.
Loading in the world on paper 173 provided in the linked video worked.
Upgrading to latest (188) yielded a still working raid farm for me.

Is there any other replication steps here ?

Paper did indeed have issues with raid farms, however that was resolved in https://github.com/PaperMC/Paper/commit/8a7dd613487ea3abe0180fdf95ecaadbaa2144a6 or build 182.

**Comment by RedcosmosMC** [comment]
Ok, bug is fix !
Thx for you work
