### ISSUE TITLE
Inconsistence with Custom Enchantment beetween ItemStack and ItemMeta

### ISSUE THREAD

**Issue by Doc94** [PaperSpigot/Paper#8426]
### Expected behavior

The `ItemStack#getEnchantmentLevel` are equal to `ItemStack.ItemMeta#getEnchantmentLevel` if used with custom enchantments (extended from org.bukkit.enchantments.Enchantment)

### Observed/Actual behavior

The `ItemStack#getEnchantmentLevel` only works with Enchantments from vanilla and `ItemStack.ItemMeta#getEnchantmentLevel`  return the level correctly

### Steps/models to reproduce

- Create a Enchantment extended from org.bukkit.enchantments.Enchantment and register using org.bukkit.enchantments.Enchantment.registerEnchantment (i know the javadocs say not use this...)
- Use the methods provided by the API to get the level for the two forms directly in item and itemmeta

### Plugin and Datapack List

Plugins (15): ConterCraft, ConterSubsHelper, CoreProtect, gProtector, Lands, LibsDisguises, LiteEco, LuckPerms, PlugManX (PlugMan), ProtocolLib, SellGUI, SentryIntegration, spark, Vault, WorldEdit

### Paper version

This server is running Paper version git-Paper-189 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: ec76e36)
You are running the latest version
Previous version: git-Paper-174 (MC: 1.19.2)

### Other

Related to https://github.com/PaperMC/Paper/commit/62680d5f83467590ad26cc976ee48b9b2dda3d13 , really not sure if maybe my method (working since many versions) is correct or exists better methods...

**Comment by Lulu13022002** [comment]
This isn't really fully part of the API without doing a hacky reflection on the acceptingNew field from the Enchantment or is there another way ? But yes i can add the support for that i'm just curious.

**Comment by Doc94** [comment]
> This isn't really fully part of the API without doing a hacky reflection on the acceptingNew field from the Enchantment or is there another way ? But yes i can add the support for that i'm just curious.

i follow a old tutorial many versions ago... then currently not sure if exists a better form for make this and maybe move to this or request a api for this (like with the custom potion recipes make by MachineMaker)

**Comment by Machine-Maker** [comment]
I think you are missing a step to actually register custom enchantments. You should also create a custom nms enchantment type and register that to the internal nms enchantment registry. I think both methods should work as expected then.

**Comment by Machine-Maker** [comment]
Going to close this for now. Custom enchantments are not supported API. And you can fix this by registering custom enchants with the NMS enchantment registry.
