### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by LightningMan204** [PaperSpigot/Paper#8433]
### Stack trace

```
paste your stack trace or a paste.gg link here!
```

### Plugin and Datapack List

Invsee , DiscordSRV, EssentialsX, Worldedit

### Paper version

1.18.2

### Other

After sometime playing it crashes and times out instantly and then on the console it shows [DO NOT REPORT THIS TO PAPER THIS IS NOT A BUG OR CRASH] But on aternos it shows that it has crashed.
Can you do something for it?

**Comment by electronicboy** [comment]
1) You've provided no useful information
2) 1.18.2 is no longer supported

**Comment by lynxplay** [comment]
See our discord for potential support, however, as cat said, 1.18.2 is no longer supported.
