### ISSUE TITLE
Cobweb and items.

### ISSUE THREAD

**Issue by icemails** [PaperSpigot/Paper#8442]
### Expected behavior

When i drop an item in cobweb it should need 26 seconds to fall down

### Observed/Actual behavior

The item fall instant through the cobweb.

### Steps/models to reproduce

Place a cobweb and drop an item in it.

### Plugin and Datapack List

Happens even without plugins.

### Paper version

paper-1.19.2-199

**Comment by NoahvdAa** [comment]
![image](https://user-images.githubusercontent.com/44026893/194703641-e8eb5365-723b-4398-a09d-20c86b22b9db.png)
Can't reproduce on 77a50b9 using default settings, what do your config files look like?

**Comment by Owen1212055** [comment]
Thanks for your report, however, because your issue couldn't be reproduced your issue will be closed.
Feel free to comment if you are still experiencing this issue, and please provide some more information (as specified above).

Thank you 😄
