### ISSUE TITLE
I can't run my server

### ISSUE THREAD

**Issue by monor2233223** [PaperSpigot/Paper#8452]
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
idk

### Plugin and Datapack List

no plugins no datapack 
i can run it!!

### Actions to reproduce (if known)

idk

### Paper version

1.16.5

**Comment by lynxplay** [comment]
1.16.5 is an outdated version we don't offer support for.
You also did not supply any logs..

**Comment by electronicboy** [comment]
Unsupported version, nor is this the place for support
