### ISSUE TITLE
PlayerDeathEvent problem

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#8465]
### Expected behavior

getKiller() should return a Player when the killer is a Player.
but getKiller() Always return null.

here is my code 

```java
    @EventHandler
    public void onDeath(PlayerDeathEvent event){
        Player player = event.getEntity().getPlayer();
        Player killer = event.getEntity().getKiller().getPlayer();
        new BukkitRunnable() {
            @Override
            public void run() {
                player.spigot().respawn();
                player.setGameMode(GameMode.SPECTATOR);
                player.getKiller().setSpectatorTarget(player);
                system.out.print(player.getKiller().getName())
            }
        }.runTaskLater(PlayboxUHC.getInstance(),20);
    }
```

### Observed/Actual behavior

the spectator target will return a nullPointer on getKiller()

### Steps/models to reproduce

Account #1 kills Account #2
Done

### Plugin and Datapack List

WorldEdit + PLAYBOXUHC -> (My Own Plugin) 

### Paper version

You are running the latest version
Previous version: git-Paper-191 (MC: 1.19.2)

**Comment by NubeBuster** [comment]
```java
            @EventHandler
            public void onDeath(PlayerDeathEvent event) {
                Player player = event.getEntity().getPlayer();
                Player killer = event.getEntity().getKiller().getPlayer();
                new BukkitRunnable() {
                    @Override
                    public void run() {
                        player.spigot().respawn();
                        player.setGameMode(GameMode.SPECTATOR);
                        killer.setSpectatorTarget(player);
                        System.out.print(killer.getName());
                    }
                }.runTaskLater(PlayboxUHC.getInstance(), 20);
            }
```
Try this. You were not using the 'killer' variable in your BukkitRunnable. This means that the killer of the player may have changed after the 20 ticks.

**Comment by Machine-Maker** [comment]
@Nubebuster is correct. The killer is reset when the player respawns, so in your runnable that runs 1 second later, the killer is null. Use the local variable `killer` that you created.

Closing as invalid.
