### ISSUE TITLE
Dying above nether roof in gamemode specatator

### ISSUE THREAD

**Issue by fredagsguf** [PaperSpigot/Paper#8472]
### Expected behavior

That i don't die in spectator when above nether roof and the option: nether-ceiling-void-damage-height is set to 128

### Observed/Actual behavior

I die in gamemode spectator when above nether roof, this used to be different before.

### Steps/models to reproduce

set nether-ceiling-void-damage-height to 128
go into gamemode specatator
go above nether roof

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/46964809/195979089-7ecce839-0cc9-4c58-947a-3d49fecd955f.png)

### Paper version

Purpur-1814.

Purpur doesn't change anything about the nether roof so i assume this should go to paper.

**Comment by kennytv** [comment]
You're not using (latest) Paper.
