### ISSUE TITLE
Citizens NPC‘s disappearing

### ISSUE THREAD

**Issue by ScuroK** [PaperSpigot/Paper#8476]
### Expected behavior

NPC‘s created by the citizens plugin should not disappear on chunk unload.

### Observed/Actual behavior

Some NPC's are invisible while some are fine. It does not matter what mob type they are. For example: one villager shows up while another villager does not.
If i create a new npc its there. after i teleport away or restart the server its gone. the affected NPC's will still show up under /npc list. it seems like the plugin thinks they are there.

Some users report that this issue started to occure after paper changed the chunk handling (version 174).

### Steps/models to reproduce

- Create NPC (for example mob) outside the spawn region (dont keep chunks in memory)
- teleport away or restart

### Plugin and Datapack List

- Multiverse Core
- Citizens

### Paper version

Paper version git-Paper-214 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: ec00f99)
You are running the latest version

### Other

Citizens Reports:

https://github.com/CitizensDev/Citizens2/issues/2918

https://github.com/CitizensDev/Citizens2/issues/2919

**Comment by ScuroK** [comment]
EDIT : if i create the NPC inside of a spawn chunk and keep the spawn chunks in memory it does not occure. So it seems definitely related to unloading/loading chunks.

**Comment by ScuroK** [comment]
EDIT 2 : It does not happen with player NPCs only with mob type NPCs

**Comment by Astralchroma** [comment]
Report the bug to citizens not paper
https://github.com/CitizensDev/Citizens2

**Comment by Chew** [comment]
There already seems to be 2 reports on citizens and they were asked to come here.

**Comment by ScuroK** [comment]
The way paper handles chunks different than spigot is also quite new. There is a good chance this should be fixed by paper in order to prevent future bugs and conflicts.

**Comment by fullwall** [comment]
> There already seems to be 2 reports on citizens and they were asked to come here.

(by a user, not by the developers)

**Comment by ScuroK** [comment]
> > There already seems to be 2 reports on citizens and they were asked to come here.
> 
> (by a user, not by the developers)

so what is your take on this?

**Comment by ScuroK** [comment]
Fixed by citizens

**Comment by ScuroK** [comment]
Closed
