### ISSUE TITLE
Crash WatchDog. Server not respond

### ISSUE THREAD

**Issue by iTroodon** [PaperSpigot/Paper#8487]
### Stack trace

https://pastebin.com/ALthn5S6

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/109700752/197080488-ff06f36e-9bff-49a7-8757-28d089d99682.png)

### Actions to reproduce (if known)

We are in the server and it just stop responding

### Paper version

![image](https://user-images.githubusercontent.com/109700752/197080517-16e8d8df-933b-48f3-bf2f-348154a9cd70.png)

### Other

I am connecting a vps with a vultam host 1.18.2 the vps is viaversion 1.8/1.19 and when They connect by the vps to the vultam its goes lag and server crash

**Comment by electronicboy** [comment]
Unsupported version, nor is this the place for support; You also have a plugin doing network IO on the main thread

**Comment by iTroodon** [comment]
Wait but plugin in the server or in the bungee?

**Comment by electronicboy** [comment]
From the server, that you pulled the logs from

```
[13:09:27] [Paper Watchdog Thread/ERROR]: java.base@17.0.2/java.net.InetSocketAddress.getHostName(InetSocketAddress.java:366)
[13:09:27] [Paper Watchdog Thread/ERROR]: PebbleAntiVPN.jar//pebbleantivpn.evnets.PlayerQuit.onDisconnect(PlayerQuit.java:20)
```
