### ISSUE TITLE
Crash: players left for 20000+ blocks

### ISSUE THREAD

**Issue by Andrew-Rayand** [PaperSpigot/Paper#8508]
### Stack trace

https://paste.gg/p/anonymous/22480055bbac47dfb1bc3a5cb267532d

### Plugin and Datapack List

Plugins (40): AntiPopup, AureliumSkills, AutoMessage, Chunky, Citizens, CMI, CMIEInjector*, CMILib, DeluxeAnnounce, DeluxeMenus, dynmap, floodgate, Geyser-Spigot, GSit, HeadDatabase, HolographicDisplays, HolographicExtension, ItemJoin, LoginSecurity*, LuckPerms, Minepacks, Multiverse-Core, NBTAPI, PlaceholderAPI, ProtocolLib, RealisticSeasons, RPChat, ServerSigns, ServerTours, ShopGUIPlus, SkinsRestorer, STN-Studios-API*, SupremeBanks, TAB, UltimateAutoRestart, Vault, Vehicles, WorldEdit, WorldEditSUI, WorldGuard

### Actions to reproduce (if known)

A server crash or freeze occurs when players move 20,000+ blocks from spawn and the center of the map. There are 4-6 players on the server.

### Paper version

Paper version git-Paper-237 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 25cd3ee)

**Comment by Warriorrrr** [comment]
A player used a treasure map which caused tons of chunks to generate while searching for a structure, change the [treasure-maps.find-already-discovered.loot-tables](https://docs.papermc.io/paper/reference/world-configuration#treasure-maps) option to false to make it search already generated structures or set enabled to false.

**Comment by Andrew-Rayand** [comment]
> A player used a treasure map which caused tons of chunks to generate while searching for a structure, change the [treasure-maps.find-already-discovered.loot-tables](https://docs.papermc.io/paper/reference/world-configuration#treasure-maps) option to false to make it search already generated structures or set enabled to false.

Thanks, changed the setting to false. Let's see what changes.

**Comment by Owen1212055** [comment]
See https://github.com/PaperMC/Paper/issues/8393

As stated by Warriorrrr, this is just the result of a treasure map loading a huge amount chunks and crashing the server.
