### ISSUE TITLE
Paper Updater Broke

### ISSUE THREAD

**Issue by rishabhk571** [PaperSpigot/Paper#8519]
### Stack trace

```
https://paste.gg/p/anonymous/cf638e4b0de64a39aa63ea6e4266cf56
```

### Plugin and Datapack List

AureliumSkills, BuildersWand, Citizens, CMILib, DailyRewards, DeluxeHub, DiscordSRV, EconomyShopGUI, EpicHoppers, Essentials, ExcellentCrates, floodgate, Geyser-Spigot, HolographicDisplays, HolographicExtension, HoloRemove*, IridiumSkyblock, Jobs, LuckPerms, Maintenance, Matrix, MyPet, NexEngine, PlaceholderAPI, PlayerWarps, ProtocolLib, SCore, SecurityLog, Sellwand, SilkSpawners, SimpleScore, SkinsRestorer, SuperbVote*, UltimateAntiBot*, Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, Webvotelogger, WorldEdit, WorldGuard

### Actions to reproduce (if known)

It just happened today when i restarted my server, it gave me this output and crashes everytime

### Paper version

I currently can't run /version because my server is not starting

But This is jar file of my server,jar - <redacted by @lynxplay, server jar contaminated by malware>

### Other

umm nothing else to say

**Comment by lynxplay** [comment]
Your server appears to be infected by malware. See https://discord.com/channels/289587909051416579/492517675680006144/1025095841687535667 for our announcement regards that and possible steps to take from here 👍 

//edit
In general, head to our discord for more support in regards to this. The github issue tracker is not really the place for it.
