### ISSUE TITLE
Problem between depend and LibraryLoader

### ISSUE THREAD

**Issue by highright1234** [PaperSpigot/Paper#8526]
### Expected behavior

Working smoothly

### Observed/Actual behavior

Throw LinkageErrror,
```
java.lang.LinkageError: loader constraint violation: when resolving method 'void io.github.highright1234.librarydebugdebug.TestKommand.register(io.github.monun.kommand.PluginKommand)' the class loader 'HaraSample-0.0.1.jar' @65a3baf of the current class, io/github/highright1234/harasample/HaraSample$onEnableAsync$3, and the class loader 'LibraryDebug.jar' @343a97a5 for the method's defining class, io/github/highright1234/librarydebugdebug/TestKommand, have different Class objects for the type io/github/monun/kommand/PluginKommand used in the signature (io.github.highright1234.harasample.HaraSample$onEnableAsync$3 is in unnamed module of loader 'HaraSample-0.0.1.jar' @65a3baf, parent loader java.net.URLClassLoader @7dc5e7b4; io.github.highright1234.librarydebugdebug.TestKommand is in unnamed module of loader 'LibraryDebug.jar' @343a97a5, parent loader java.net.URLClassLoader @7dc5e7b4)
```

### Steps/models to reproduce

description of kommand
- kommand uses kotlin
pom.xml
```
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib</artifactId>
      <version>1.6.21</version>
      <scope>runtime</scope>
    </dependency>
```

These plugins use kommand ( library name ) with libraries function in plugin.yml 
HaraSample depend on LibraryDebug

when HaraSample use function in LibraryDebug with kommand class
it throw LinkageError

actually you can think to remove libraries property in HaraSample

but in these case are different
- LibraryDebug is using kotlin
- HaraSample wanna use kommand
- Boom, it doesn't work :)
( it happend on 2021 but i cannot found repository and log )
HaraSample can load kommand but, 
cannot use a LibraryDebug function with the Kotlin classes.

the solution is modify plugin.yml in LibraryDebug.jar
although it is not smart and it's tiresome to administrators
this is only thing what i found

### Plugin and Datapack List

```Plugins (2): HaraSample, LibraryDebug*```

HaraSample: Just Sample plugin for Test,
plugin.yml:
```
depend:
 - LibraryDebug
libraries:
---- Just ignore them
 - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.4.0
 - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.4.0
 - io.github.monun:tap-core:4.7.1
 - io.github.monun:invfx-core:3.2.0
 - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4
 - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10
 - org.jetbrains.kotlin:kotlin-reflect:1.7.10 
 ----
 - io.github.monun:kommand-core:2.14.0
api-version: 1.19
```
LibraryDebug:  same
```
libraries:
  - io.github.monun:tap-core:4.7.2 // don't care this
  - io.github.monun:kommand-core:2.14.0
```

### Paper version

This server is running Paper version git-Paper-246 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: aaf5e39)
You are running the latest version
Previous version: git-Paper-139 (MC: 1.19.2)

### Other

System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.4.1+1) Host: Linux 5.10.102.1-microsoft-standard-WSL2 (amd64)

**Comment by electronicboy** [comment]
This is 100% expected, the library loading system does not share classes, and to do so would be a behaviorally breaking bug, and so this is pretty much purely 100% typical classloader semantics; both plugins have the library in their classpath, and both are loading them from their own classloaders, and so when you try to interact between the two, it's going to fail, as they're two separate classes.

Only way to fix this is to have only one of the plugins load that library, and have the other to pull it through a depend

**Comment by highright1234** [comment]
I just want it to resolve the dependence between these plugins.

```
HaraSample's libraryloader:
 - kotlin

LibraryDebug's libraryloader:
  - kotlin
  - kommand
```
to
```
HaraSample's libraryloader:                 <-
 - kotlin                                     ㅣ
                                              ㅣ
LibraryDebug's libraryloader:                 ㅣ
  - kommand
```
i want something like this

actually plugin's classloader and libraryloader's classloader is similar to that

**Comment by electronicboy** [comment]
That would be a *breaking* behavioral change here which serves no sane purpose other than a specific (broken) usecase
