### ISSUE TITLE
Spawned mob create a warning when killed

### ISSUE THREAD

**Issue by PapiCapi** [PaperSpigot/Paper#8528]
### Expected behavior

Not seeing any warning.

### Observed/Actual behavior

I see this warning when i kill it : 
`[EntityLookup] Failed to remove entity EntityZombie['Zombie'/1610, uuid='fc249f3c-bdfc-4c49-bc06-338f60aa1e89', l='ServerLevel[askyblock]', x=5411.00, y=122.00, z=7829.00, cpos=[338, 489], tl=153, v=true, removed=KILLED] by uuid, current entity mapped: null`
or 
`[EntityLookup] Failed to remove entity EntityZombie['Zombie'/1641, uuid='aedbb38a-f6ac-4414-924b-eb21ec95d6b2', l='ServerLevel[askyblock]', x=5408.70, y=122.00, z=7830.26, cpos=[338, 489], tl=80, v=true, removed=DISCARDED] by uuid, current entity mapped: null`

### Steps/models to reproduce

Create a plugin with this class to reproduce and see the warning .
[Reproduce.zip](https://github.com/PaperMC/Paper/files/9896577/Reproduce.zip)

### Plugin and Datapack List

AfkTitle, AntiAFK*, AntiDecoCombat, ArmorStandTools, Bank, BentoBox, BlockLocker, BlockVillagersEnteringBoats, ChatCore, ChatItem, ChatPing, ChestCommands, Citizens, CitizensText, Core, CoreProtect, CrazyCrates, DeACoudre, Donjon, Essentials, EssentialsChat, EssentialsSpawn, EventDropper, FarmLimiter, FastAsyncWorldEdit (WorldEdit), ForceIgnore, GadgetsMenu, Grades, HolographicDisplays, IllegalStack, Insights, InvPerWorld, KitsSkyblock, LuckPerms, MinewebBridge, ModPerms, ModReq*, MoncubeCore, Multiverse-Core, NoCollision, OnTime, OpenInv, OpGuard*, Plan, PlanningsEvents, PlugMan, PreventEnderChestUseBug, ProtocolLib, PVPControl, RotationWrench, SchematicMover, Shopkeepers, Skript, spark, StaffCore, TAB, TokenManager, UltimateStacker, Vault, ViaBackwards, ViaVersion, VoidGen, VoteMoncube, WGEFixer, WorldGuard, WorldGuardExtraFlags

### Paper version

This server is running Paper version git-Paper-245 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: b743144)

**Comment by Machine-Maker** [comment]
Well, I'm guessing the issue is that you are spawning the entity, which gets assigned a new UUID and numeric ID. Then you are loading the entity data from some byte array (which I'm guessing has a new uuid in it). So the entity's uuid changes, then when you go to kill it, the server doesn't know about the new uuid.

I can't know for sure, until I see the human-readable representation of that byte-array.

**Comment by PapiCapi** [comment]
Here is the output of the Compound : 
`{AbsorptionAmount:0.0f,Air:300s,ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],ArmorItems:[{},{},{},{}],Brain:{memories:{}},Bukkit.Aware:1b,Bukkit.updateLevel:2,CanBreakDoors:1b,CanPickUpLoot:1b,DeathTime:0s,DrownedConversionTime:-1,FallDistance:0.0f,FallFlying:0b,Fire:-1s,HandDropChances:[0.085f,0.085f],HandItems:[{},{}],Health:20.0f,HurtByTimestamp:0,HurtTime:0s,InWaterTime:-1,Invulnerable:0b,IsBaby:0b,LeftHanded:0b,Motion:[0.0d,-0.0784000015258789d,0.0d],OnGround:1b,Paper.Origin:[5409.5d,122.0d,7830.5d],Paper.OriginWorld:[I;-1671409889,-860076839,-1856180946,662936201],Paper.ShouldBurnInDay:1b,Paper.SpawnReason:"SPAWNER_EGG",PersistenceRequired:0b,PortalCooldown:0,Pos:[5409.5d,122.0d,7830.5d],Rotation:[111.33551f,0.0f],Spigot.ticksLived:28,UUID:[I;-64708804,-1107538871,-1140444273,1621761673],WorldUUIDLeast:-7972236457865405815L,WorldUUIDMost:-7178650808031099687L,entity_type:"minecraft:zombie"}`

(and as you said, there is already an UUID) but i don't know how to prevent the assignation of the new UUID. Have you got any ideas ?

**Comment by electronicboy** [comment]
Remove the uuid from the compound you load
