### ISSUE TITLE
Support pprof

### ISSUE THREAD

**Issue by sfxworks** [PaperSpigot/Paper#8535]
### Is your feature request related to a problem?

No

### Describe the solution you'd like.

Hi there. I would like the ability to use Grafana Phlare to gain a flame graph of servers. In order to do this, server cores need to provide a profiling data endpoint. In Paper's case, this would be jpprof https://grafana.com/docs/phlare/latest/operators-guide/configure-agent/language-support/jvm/

### Describe alternatives you've considered.

I have considered hiring a developer to make a plugin, though I feel that this would best be served at the core of paper as an enable/disable config option. 

### Other

I'm no java developer, but according to their documentation:

> If you’re using gradle, add the following dependency to your build.gradle:
```
dependencies {
// ....
    implementation 'com.grafana:jpprof:0.1.0'
//...
}
```

**Comment by montlikadani** [comment]
This must be done in a plugin, they're having a free API to generate such graphs of your server. This is useless to implement in the server itself. Also [Spark](https://spark.lucko.me/docs/misc/About-spark-metrics) fulfills your requirements as Spark author added graph support for some statistics: https://github.com/lucko/spark-viewer/pull/50

**Comment by electronicboy** [comment]
This type of stuff is easily implemented in a plugin which doesn't require us to bundle various libraries in the server which would otherwise create headaches for plugin Devs, and us, due to how libraries are needed to be managed.
