### ISSUE TITLE
Players don't see scoreboard updates if they're respawning as the event happens

### ISSUE THREAD

**Issue by conure512** [PaperSpigot/Paper#8536]
### Expected behavior

You should be able to update the values/visibility of a scoreboard display slot at any time, and all players should see these effects.

### Observed/Actual behavior

If a player is in the middle of respawning when a scoreboard update happens, that update will not carry over to their screen.

### Steps/models to reproduce

Create any scoreboard objective. Put it in a display slot (sidebar is easiest). Give a player a value in that objective, so that their score appears in the display slot.

Then, using a plugin, listen for PlayerRespawnEvents and update that scoreboard objective whenever one is detected. The player that's respawning will continue to see the values displayed in the slot from before they respawned. This also applies if the update is to clear the display slot; all other players will see the slot disappear, while the respawning player will continue to see it.

### Plugin and Datapack List

Only my own plugin and datapack that I'm writing, which do not (to my knowledge) do anything that causes this behavior.

### Paper version

This server is running Paper version git-Paper-256 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: e30b082)
You are running the latest version
Previous version: git-Paper-255 (MC: 1.19.2)

**Comment by Lulu13022002** [comment]
Have you also tried the PlayerPostRespawnEvent, bc the bukkit event is called in a weird place between death and live, and doesn't keep some change for the respawned player

**Comment by Machine-Maker** [comment]
I'm going to mark this as "works as intended" for the reason Lulu13022002 said. The `RespawnPlayerEvent` is fired when the player is not in the actual list of players on the server (which is why they don't get those scoreboard updates, as they are sent to all players on the server). Use the `PlayerPostRespawnEvent` which is fired after the player is added back to the server.
