### ISSUE TITLE
Observable plugin loading

### ISSUE THREAD

**Issue by DaRacci** [PaperSpigot/Paper#8538]
### Is your feature request related to a problem?

So i recently found myself needing to know not when a plugin has enabled, but when it has loaded.
So basically I'm more or less asking if this is a feature which would be accepted as a PR before making one as i would be able to create one myself.

### Describe the solution you'd like.

Likely a method which takes a Consumer of the plugin which is loading, this would be called just after the onLoad method.

### Describe alternatives you've considered.

I've tried finding a way to listen to the logger and wait for the log message for loading plugin but couldn't find a way of implementing this.

**Comment by TetraTheta** [comment]
Isn't `depend` and `softdepend` can handle this? If you use either of them, your plugin will be loaded after given plugin is loaded.  
If you need to distinguish between `STARTUP` or `POSTWORLD` in `load`, you can just look into `plugin.yml` of your _dependency_ plugin.  

Both `depend` and `softdepend` are indicating server to load your plugin after given plugins, not explicitly allowing access to code of the given plugins.

The only thing you should consider is 'circular dependency'. If I remember correctly, if circular dependency is detected, which plugin should be loaded first will be determined randomly. I'm not sure, but I remember there was PR about plugin loader and it would warn about circular dependency. I don't know the current state of the PR.

**Comment by DaRacci** [comment]
This would work normally, however where i found myself having this issue is i can register my plugin as a soft depend but since I'm using a special integration loader class from the core plugin i wrote it doesn't have the softDepend which means when it needs to call the onLoad event for the integration loader, it well obviously can only do that unless the plugin is already loaded at time of registration or once it receives the enable event.

**Comment by TetraTheta** [comment]
Sorry if I understood your intention wrong, but I guess your situation is like this:

* Core plugin:
  * Should be loaded before 'child plugins'
  * Should access classes of 'child plugins'
* Child plugins:
  * Should be loaded after 'core plugin'
  * Should be loaded when 'core plugin' access its classes

In this case, using [`ServerLoadEvent`](https://jd.papermc.io/paper/1.19/org/bukkit/event/server/ServerLoadEvent.html) can be used. Since this event is called when either the server startup (or reload) has completed, all plugins were either loaded or disabled (or make server shutdown). So in this case, you can check if child plugins were loaded and access it.

If this is what you want, you can define `ServerLoadEvent` in core plugin and access child plugins with any way you want, like reflection.

**Comment by DaRacci** [comment]
I believe that may actually be exactly what i needed, however wouldn't there be no way to register this as if this is called only after all plugins have loaded and before they have begun enabling, wouldn't i be unable to register a listener for this?

**Comment by TetraTheta** [comment]
Maybe you can create custom class which extends `Map<JavaPlugin, boolean>`(or `Map<String, boolean>`) which also have `PropertyChangeSupport` in it at core plugin. (`Map` doesn't have event related thing in default)

So, when child plugin loads, it should be able to access core plugin's custom map object and insert itself into the custom map. And it will trigger event that core plugin is listening to. Then you can do what you want.

I breifly searched about 'java map change event' in Google and found [some codes](https://stackoverflow.com/q/9846365). I didn't test them but I think it is worth a try.

PS. I also found [`ObservableMap<K,V>`](https://docs.oracle.com/javase/8/javafx/api/javafx/collections/ObservableMap.html) which does same I guess.

**Comment by DaRacci** [comment]
I'll give it a shot and see what i can come up with, I've already got an Observable map class which will finally get some use then

**Comment by DaRacci** [comment]
Thanks for the suggestion on that event, while not the most elegant has resolved the issue and allowed me to do what i was aiming to do.
