### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gary81013** [PaperSpigot/Paper#8549]
### Stack trace

```
https://pastebin.com/13d8iJxh
https://pastebin.com/qU5QC8ZC
```

### Plugin and Datapack List

![1](https://user-images.githubusercontent.com/43038433/200681634-65b23add-492f-42c5-87e7-1ae0856a5a8e.PNG)
![2](https://user-images.githubusercontent.com/43038433/200681656-d1c15609-e769-4100-904e-f5e8d86608bc.PNG)

### Paper version

this server is running paper version git-paper-263 (mc: 1.19.2) (implementing api version 1.19.2-r0.1-snapshot) (git:3ac1a8d)
you are running the latest version
previous version: git-paper-255 (mc:1.19.2)

**Comment by electronicboy** [comment]
You have something on your server modifying entity data off the main thread

**Comment by gary81013** [comment]
> You have something on your server modifying entity data off the main thread

Sorry to bother you... how can I fix this?

**Comment by electronicboy** [comment]
You'd need to work out what plugin is doing it, only thing we can recommend is start yanking plugins
