### ISSUE TITLE
Hex color codes in spigot.yml

### ISSUE THREAD

**Issue by ImYuv1** [PaperSpigot/Paper#8551]
### Expected behavior

Someone know how can i put some hex color codes in my spigot.yml? i triend with **&** but didn't work

![image](https://user-images.githubusercontent.com/84510917/200957117-284400c1-2184-42c8-8c00-ec98e6f85048.png)

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/84510917/200957151-05416295-429e-47d4-8f20-7e01d251fbc4.png)

### Steps/models to reproduce

Im usic paper spigot 1.17.1

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/84510917/200957527-52708f4f-9dab-432f-aaba-128ed7c76ae0.png)

### Paper version

1.17.1

**Comment by electronicboy** [comment]
one would guess, use & instead, that way the spigot parser actually maybe cares to parse it, outside of that; this is not the place for support

**Comment by ImYuv1** [comment]
my bad, don't have much experience using github...

**Comment by lynxplay** [comment]
Feel free to pop by our discord [https://discord.gg/papermc](https://discord.gg/papermc) for support :+1: 
What cat meant is that the github issue tracker is for issues in the server software that the paper team and community work on to fix. The discord is the right place to ask questions and get help etc.

**Comment by ImYuv1** [comment]
All right, i'll try on discord, thank you very much.
