### ISSUE TITLE
Entity data such as metadata and mob goals cleared on chunk unload

### ISSUE THREAD

**Issue by LunarsWorldLLC** [PaperSpigot/Paper#8557]
### Expected behavior

Mobs should store metadata when chunk becomes unloaded

### Observed/Actual behavior

entity data such as metadata and mob goals get cleared when player leaves chunk. I tried listening to unload chunk event and it seems like the entities lost their data before the event is fired.

### Steps/models to reproduce

above

### Plugin and Datapack List

above

### Paper version

[above](https://api.papermc.io/v2/projects/paper/versions/1.19.2/builds/265/downloads/paper-1.19.2-265.jar)

**Comment by electronicboy** [comment]
replication code or something?

Also, things like custom mob goals are not persistent, there is no real logic to "clear" anything here afaik, it's purely just a GC matter

**Comment by LunarsWorldLLC** [comment]
the data should not be cleared before the chunk unload event is called

`package me.rag.papertest;

import com.destroystokyo.paper.entity.ai.GoalType;
import org.bukkit.Bukkit;
import org.bukkit.entity.Entity;
import org.bukkit.entity.LivingEntity;
import org.bukkit.entity.Mob;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.entity.CreatureSpawnEvent;
import org.bukkit.event.world.ChunkUnloadEvent;
import org.bukkit.plugin.java.JavaPlugin;

import java.util.Arrays;

public class PaperTest extends JavaPlugin implements Listener {

    @Override
    public void onEnable() {
        getServer().getPluginManager().registerEvents(this, this);
    }

    @EventHandler
    public void onSpawn(CreatureSpawnEvent event) {
        Entity entity = event.getEntity();
        if (event.getSpawnReason() == CreatureSpawnEvent.SpawnReason.SPAWNER_EGG) {
            Bukkit.broadcastMessage("Old Mob Goals " + entity.getType().name() + ":" + Bukkit.getServer().getMobGoals().getAllGoals((Mob) event.getEntity()).size());
            for (GoalType types : GoalType.values()) {
                Bukkit.getServer().getMobGoals().removeAllGoals((Mob) event.getEntity(), types);
            }
            Bukkit.broadcastMessage("New Mob Goals " + entity.getType().name() + ":" + Bukkit.getServer().getMobGoals().getAllGoals((Mob) event.getEntity()).size());
        }
    }

    @EventHandler
    public void onUnloadEvent(ChunkUnloadEvent event) {
        // This event doesn't get called so idk how to remove mobs with no GoalTypes
        // The mobs randomly lose Metadata and GoalType data when player teleports away from them (I don't believe chunk is being unloaded)
        Arrays.stream(event.getChunk().getEntities())
                .filter(entity -> event instanceof LivingEntity)
                .map(entity -> "Unloaded Mob Goals " + entity.getType().name() + ":" + Bukkit.getServer().getMobGoals().getAllGoals((Mob) entity).size())
                .forEach(Bukkit::broadcastMessage);
    }

`}``

**Comment by spookymgmt** [comment]
> replication code or something?
> 
> Also, things like custom mob goals are not persistent, there is no real logic to "clear" anything here afaik, it's purely just a GC matter

Did you add the "Needs triage" tag? Or did I lol sorry my bad confused

**Comment by Owen1212055** [comment]
Try using the EntityRemoveFromWorldEvent
But in general, goals like this being removed when the entity is deleted is expected.

**Comment by Owen1212055** [comment]
See the explanation above.

Mob goals are not saved with the entity, so you need to make sure to properly re add it when the entity is readded. 
Not really sure what you mean by metadata. But note, that is only cleared when the server is restarted. If you want a persistent "metadata" like system use the PersistentDataContainer.

Closing as this is in general intentional.
