### ISSUE TITLE
Dragon bossbar's name is not reset when it is respawned

### ISSUE THREAD

**Issue by greatericontop** [PaperSpigot/Paper#8558]
### Expected behavior

When a dragon is respawned, the purple bossbar should default to saying "Ender Dragon" (or the equivalent in another language).

### Observed/Actual behavior

The dragon keeps its name from an earlier dragon fight, even though the dragon itself does not have that name.

### Steps/models to reproduce

1. Go to the end and run this command `/data merge entity @e[type=ender_dragon,limit=1] {CustomName: "1234"}` to change the name of the dragon.
2. Kill the dragon and respawn it.
3. Observe how the respawned dragon bossbar still says "1234" instead of "Ender Dragon"

![image](https://user-images.githubusercontent.com/79880061/201434493-f6e8ef9c-fb8f-44bf-a0b7-98d905ef0915.png)

### Plugin and Datapack List

I tested this with no plugins and only the default datapacks `vanilla (built-in)` and `file/bukkit (world)`.

### Paper version

```
This server is running Paper version git-Paper-265 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 117579c)
You are running the latest version
```

### Other

This was also discussed in the Paper discord: https://canary.discord.com/channels/289587909051416579/555462289851940864/1040038818683822181

> EndDragonFight#L438, updateDragon method
>
> It updates the name if a custom name exists, but doesn't reset the name back to the default if the name doesn't exist
>
> i.e. there should be an
> ```
> else {
>     this.dragonEvent.setName(Component.translatable("entity.minecraft.ender_dragon"));
> }
> ```

**Comment by Machine-Maker** [comment]
Is this also a vanilla issue? If so, either the reporter or someone else should also open a Moira ticket and link it here as well to track it.

**Comment by greatericontop** [comment]
Yes, it's a thing in vanilla as well. https://bugs.mojang.com/browse/MC-257487
