### ISSUE TITLE
Named Mobs despawning

### ISSUE THREAD

**Issue by DonRohan** [PaperSpigot/Paper#8568]
### Expected behavior

Named Mobs will not despawn

### Observed/Actual behavior

Named Mobs despawn, sometimes even when in range

### Steps/models to reproduce

- name mob
- wait
- mob gone

### Plugin and Datapack List

Plugins: ViewDistanceTweaks, Worldedit
Datapacks: anti-creeper grief, anti enderman grief, anti ghast grief, armored elytra, bat membranes, cauldron concrete, double shulker shells, dragon drops, fast leaf decay, more mob heads, player head drops, multiplayer sleep, silence mobs, name colors (all Datapacks are downloaded from vanillatweaks)

### Paper version

This server is running Paper version git-Paper-201 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 57555b8)
You are 69 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-174 (MC: 1.19.2)

### Other

Server hosted by ZAP-Hosting

**Comment by Machine-Maker** [comment]
How are you "naming" the mob? Are you talking about just using a name tag? Or is this naming the mob via some plugin?

**Comment by DonRohan** [comment]
naming the mob with a nametag

**Comment by Machine-Maker** [comment]
Can you reproduce this on a completely empty paper server? No plugins or data packs and on the latest version of paper? You are ~70 version out of date.

**Comment by Machine-Maker** [comment]
I can't replicate it on an empty paper server. I spawned 2 skeletons, nametagged one of them, flew 500 blocks away, and then back. One despawned, the other didn't. 


I'm closing this for now as unreproducible. If you can provide more detailed reproduction steps, let us know.
