### ISSUE TITLE
sleeping villager is picking up food

### ISSUE THREAD

**Issue by fluffeliger** [PaperSpigot/Paper#8569]
### Expected behavior

The Villager keeps sleeping or he is standing up to get the food

### Observed/Actual behavior

The Villger is getting the food with the sleeping animation activated

### Steps/models to reproduce

Place Bed, Get Villager to sleep in it
Drop Food next to it (i used carrots)

### Plugin and Datapack List

DecentHolograms, FastAsyncWorldEdit (WorldEdit), LuckPerms, StoneKid, WorldGuard

StoneKid - my own plugin - not working with any kind of entities

### Paper version

This server is running Paper version git-Paper-270 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: e22dacf)
You are running the latest version
Previous version: git-Paper-263 (MC: 1.19.2)

### Other

In Vanilla he is standing up

**Comment by Machine-Maker** [comment]
Double reported here: https://hub.spigotmc.org/jira/browse/SPIGOT-7183

**Comment by lynxplay** [comment]
I'll mark this as accepted. It only really works while the villager is still partially on the bed. The second they move too far, at least in my testing, the animation properly changes.

As no functionality is really impacted here I also have given this the low tag.

**Comment by Lulu13022002** [comment]
Seems to be a vanilla bug: https://bugs.mojang.com/browse/MC-157464
