### ISSUE TITLE
Add API for NMS LivingEntity yBodyRot

### ISSUE THREAD

**Issue by colton-boi** [PaperSpigot/Paper#8571]
### Is your feature request related to a problem?

Making a shooter game and need the body rotation to calculate more specific hitboxes. Can also be used in other situations and I can't think of any reason not to add it.

### Describe the solution you'd like.

Any way to get the body rotation of living entities (and set it)

### Describe alternatives you've considered.

Using NMS

**Comment by Owen1212055** [comment]
> (and set it)

What's the point of this? I don't think this would be synchronized with clients anyways. Is this for your "calculation"?

**Comment by colton-boi** [comment]
> What's the point of this?

There is a method for it in the NMS docs, why not add it to the paper API? I'm pretty sure it should work or why would NMS have it.
