### ISSUE TITLE
Failed to clone 'work/BuildData' a second time, aborting

### ISSUE THREAD

**Issue by alazeprt** [PaperSpigot/Paper#8582]
### Expected behavior

Successfully cloned Paper in Github Desktop

### Observed/Actual behavior

Cloning into 'D:\slatt的桌面\Java\Paper'...
remote: Enumerating objects: 102959, done.        
remote: Counting objects: 100% (178/178), done.        
remote: Compressing objects: 100% (154/154), done.        
remote: Total 102959 (delta 52), reused 128 (delta 24), pack-reused 102781        
Receiving objects: 100% (102959/102959), 60.16 MiB | 154.00 KiB/s, done.
Resolving deltas: 100% (89203/89203), done.
Submodule 'work/BuildData' (https://hub.spigotmc.org/stash/scm/spigot/builddata.git) registered for path 'work/BuildData'
Submodule 'work/Bukkit' (https://hub.spigotmc.org/stash/scm/spigot/bukkit.git) registered for path 'work/Bukkit'
Submodule 'work/CraftBukkit' (https://hub.spigotmc.org/stash/scm/spigot/craftbukkit.git) registered for path 'work/CraftBukkit'
Submodule 'work/Spigot' (https://hub.spigotmc.org/stash/scm/spigot/spigot.git) registered for path 'work/Spigot'
Cloning into 'D:/slatt的桌面/Java/Paper/work/BuildData'...
fatal: unable to access 'https://hub.spigotmc.org/stash/scm/spigot/builddata.git/': The requested URL returned error: 500
fatal: clone of 'https://hub.spigotmc.org/stash/scm/spigot/builddata.git' into submodule path 'D:/slatt的桌面/Java/Paper/work/BuildData' failed
Failed to clone 'work/BuildData'. Retry scheduled
Cloning into 'D:/slatt的桌面/Java/Paper/work/Bukkit'...
fatal: unable to access 'https://hub.spigotmc.org/stash/scm/spigot/bukkit.git/': The requested URL returned error: 500
fatal: clone of 'https://hub.spigotmc.org/stash/scm/spigot/bukkit.git' into submodule path 'D:/slatt的桌面/Java/Paper/work/Bukkit' failed
Failed to clone 'work/Bukkit'. Retry scheduled
Cloning into 'D:/slatt的桌面/Java/Paper/work/CraftBukkit'...
fatal: unable to access 'https://hub.spigotmc.org/stash/scm/spigot/craftbukkit.git/': The requested URL returned error: 500
fatal: clone of 'https://hub.spigotmc.org/stash/scm/spigot/craftbukkit.git' into submodule path 'D:/slatt的桌面/Java/Paper/work/CraftBukkit' failed
Failed to clone 'work/CraftBukkit'. Retry scheduled
Cloning into 'D:/slatt的桌面/Java/Paper/work/Spigot'...
fatal: unable to access 'https://hub.spigotmc.org/stash/scm/spigot/spigot.git/': The requested URL returned error: 500
fatal: clone of 'https://hub.spigotmc.org/stash/scm/spigot/spigot.git' into submodule path 'D:/slatt的桌面/Java/Paper/work/Spigot' failed
Failed to clone 'work/Spigot'. Retry scheduled
Cloning into 'D:/slatt的桌面/Java/Paper/work/BuildData'...
fatal: unable to access 'https://hub.spigotmc.org/stash/scm/spigot/builddata.git/': The requested URL returned error: 500
fatal: clone of 'https://hub.spigotmc.org/stash/scm/spigot/builddata.git' into submodule path 'D:/slatt的桌面/Java/Paper/work/BuildData' failed
Failed to clone 'work/BuildData' a second time, aborting

Would you like to retry cloning Paper ?

### Steps/models to reproduce

Cloning Paper with Github Desktop

### Plugin and Datapack List

nothing

### Paper version

nothing

**Comment by electronicboy** [comment]
Spigots repo is returning an error...
