### ISSUE TITLE
Datapack world height changing getHighestBlockAt

### ISSUE THREAD

**Issue by lexiccn** [PaperSpigot/Paper#8586]
### Expected behavior

world.getHighestBlockAt returning the correct location

### Observed/Actual behavior

Inconsistent behaviour!

min Y at 0 would offset the location by +64
min Y at -16 would offset the location by +16

However while changing this I got completely different results depending on the chunk I was in; but consistent within that chunk
- ex. one chunk would give me -32 offset, one would function perfectly after removing the datapack and restarting - this would repeat even leaving, unloading and returning to the chunk

### Steps/models to reproduce

Install a datapack modifying overworld to have different min Y value
Height did not seem to affect anything whether I set it to add up to 256, or 320 - although more testing was done with it set to add to 256 (f.e 384 with -64)

### Plugin and Datapack List

Plugins:
Test plugin I wrote specifically for this; teleporting the player to the highest at their location
Datapack:
Datapack that modifies min Y/Height of Overworld and Overworld_Caves

### Paper version

This server is running Paper version git-Paper-258 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: ab1c072)

Out of date now but reproduced on more up to date server; I don't have time to re-test all over with new one so hopefully it's good enough as this.

### Other

Inconsistent behaviour across chunks; however the inconsistent chunk was one that would have been loaded through many restarts and tests, and the one behaving as intended when removing the datapack was not loaded until after I removed the datapack for the first time

**Comment by Machine-Maker** [comment]
I think we discussed on discord, not realizing that you weren't deleting and regenerating the world in between changing the worldgen datapack. That isn't really a supported behavior, changing worldgen after parts of the world have already been generated.
