### ISSUE TITLE
cancelling EntityExplodeEvent does not stop tnt from destroying item entites

### ISSUE THREAD

**Issue by aimjel** [PaperSpigot/Paper#8588]
### Expected behavior

Cancelling the EntityExplodeEvent should not destroy item entities.

### Observed/Actual behavior

Destroys the item entities.

### Steps/models to reproduce

Cancel the EntityExplodeEvent then place TNT, throw an item next to it and ignite the TNT.

### Plugin and Datapack List

No plugins, default data packs

### Paper version

git-Paper-281 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (GIT: 55a16d8)

**Comment by Machine-Maker** [comment]
I believe this is WAI (Works as Intended). Cancelling the EntityExplodeEvent doesn't prevent any entity from taking damage. Stand right next to the explosion in creative mode and you will take damage. You probably want to cancel the ExplosionPrimeEvent instead.

**Comment by Owen1212055** [comment]
See the comment above. The EntityExplodeEvent represents the logic for handling blocks being broken.
The ExplosionPrimeEvent is used to cancel the explosion in its entirety.
