### ISSUE TITLE
Ram MAX out

### ISSUE THREAD

**Issue by MG141** [PaperSpigot/Paper#8598]
### Stack trace

https://pasteio.com/xd0ZszcWnHO5

### Plugin and Datapack List

cannot run due to server not starting up

### Actions to reproduce (if known)

Installing releases from 27.11.2022 - 28.11.2022

### Paper version

1.19.2-297

**Comment by electronicboy** [comment]
Please use the discord for support; There is not enough info here for anything to go off, save-all is slow and generally looks like the thing stalled writing out to the disk
