### ISSUE TITLE
When using EntityDeathEvent, there is not ability to customize the drops.

### ISSUE THREAD

**Issue by nicolasvac** [PaperSpigot/Paper#8603]
### Is your feature request related to a problem?

If you use the event `EntityDeathEvent`, you only have the method to see the drops `getDrops()`

### Describe the solution you'd like.

There should be a method to set the drops, like `setDrops(List<ItemStack> drops)`, in order to allow plugins maker to have customizable drops as a reward.

### Describe alternatives you've considered.

There are no alternative methods, other than clearing the drops with a runnable task and then dropping what you want, which is super inefficient.

**Comment by electronicboy** [comment]
The List is mutable, is it not?

**Comment by Machine-Maker** [comment]
Yes
