### ISSUE TITLE
setVelocity not working "properly" on y axis

### ISSUE THREAD

**Issue by KianBrose** [PaperSpigot/Paper#8620]
### Expected behavior

When setting the vector that will be used during setVelocity 
Vector(x,y,z)
Setting the value y should affect how the player is accelerated in that specific axis

### Observed/Actual behavior

When setting the vector that will be used during setVelocity 
Vector(x,y,z)
values X and Z work as expected, but Y has "odd behavior":
https://cdn.discordapp.com/attachments/555462289851940864/1050210729019592793/Screen_Recording_2022-12-07_at_18.40.49.mp4
This video shows how when jumping on the first sponge, a vector velocity of (5,0,0) is applied which properly launches the player towards +x
On the second sponge however, it attempts to set velocity to (0,5,0) which as you saw does basically nothing

I have tested several values, 0.1 0.5 1 2 50 200 and they all behave the same, basically no change at all

I have tried delaying the setVelocity by a couple of ticks after the event, but the issue remained the same

### Steps/models to reproduce

Have an eventlistener `event: PlayerJumpEvent`

Acquire player from event `val player_holder = event.player`

Create vector `val destination_vector:Vector = Vector(0.0,0.5,0.0)`

Apply set velocity `player_holder.velocity = destination_vector`

### Plugin and Datapack List

None, this is the only event running on the server, no datapacks either

### Paper version

This server is running Paper version git-Paper-305 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 407a445)

**Comment by KianBrose** [comment]
Note: This issue seems to ONLY be caused inside the PlayerJumpEvent

**Comment by Owen1212055** [comment]
In general setting velocity in certain areas like that will produce some unknown behavior. In this case, setting it in the jump event causes some issues, as seen in the video.

Generally, I'd recommend doing things like this a tick later.
