### ISSUE TITLE
Paper Watchdog Thread/ERROR

### ISSUE THREAD

**Issue by Chucky891** [PaperSpigot/Paper#8621]
### Stack trace

[2022-12-08-3.log.gz](https://github.com/PaperMC/Paper/files/10186039/2022-12-08-3.log.gz)

### Plugin and Datapack List

![plugins](https://user-images.githubusercontent.com/93062201/206465225-3b49c05d-da0f-4aae-b2fd-1dfec2d75b0f.JPG)
![plugins 2](https://user-images.githubusercontent.com/93062201/206465234-a4e4f1ee-fd34-4bdc-9f2f-1a798f1f002c.JPG)

### Paper version

1.19.2

**Comment by FriwiDev** [comment]
As far as I can tell you set your timeout for not-responding by the server thread to 0 seconds - according to the log. This value should be higher, as else your server is shut down as soon as it halts for a short time. For the rest your server just seems to be overloaded as far as the log goes. To find the culprit consider taking a timings report. Btw: You should be careful with posting logs on the internet. Your log contains the ip addresses of your users, which violates GDPR in the EU.

**Comment by electronicboy** [comment]
Your server took too long to tick, that's all we can say; generally looks like the JVM stalled.
Please use the discord/forums for support
