### ISSUE TITLE
The server does not provide the plugin with the libraries that are specified in plugin.yml

### ISSUE THREAD

**Issue by demkom58** [PaperSpigot/Paper#8633]
### Expected behavior

When I'm putting plugin that contains geantyref 1.3.13 in the libraries block of plugin.yml, Server downloads it and **uses exact same versions** for that plugin. 

_In general, it would be nice if I could specify the minimum version._

### Observed/Actual behavior

When I'm putting plugin that contains geantyref 1.3.13 in the libraries block of plugin.yml, Server downloads it and **uses an older version that already exists and is not compatible** with my plugin (in that case geantyref 1.3.11).

### Steps/models to reproduce

To reproduce you can use my demo plugin: [lib-fail-demo.zip](https://github.com/PaperMC/Paper/files/10197682/lib-fail-demo.zip)

In general:

1. Create project with common dependency that already used in server core
2. Specify in your plugin.yml version that is newer than already used
3. Use some method or classes that doesn't exists in older version
4. Ta-da. Error: https://pastebin.com/raw/dK7TwDuE

### Plugin and Datapack List

Only this one: [lib-fail-demo.zip](https://github.com/PaperMC/Paper/files/10197682/lib-fail-demo.zip)

### Paper version

[21:40:52 INFO]: Checking version, please wait...
[21:40:53 INFO]: This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version

**Comment by zml2008** [comment]
Paper already uses geantyref internally (and eventually in api), so you can't use another version in your plugin without relocating

**Comment by jpenilla** [comment]
This could probably be "fixed" for libraries only used in the server, but for libraries exposed to the API there's nothing to be done, you need to shade and relocate. Allowing this for libraries not exposed to the API would be a super low-priority thing if we decide to do that.

**Comment by electronicboy** [comment]
This isn't really fixable, especially within the bounds of how classloaders and java works. The only "fix" for this would be to change classloade priorities but changing that stuff often creates its own issues of which are generally untenable to resolve. 

The library and the version you've asked for IS there, it is added to the classloader, but, the servers classes are prioritised over plugins, and changing that sementic will cause other issues due to plugins often being borked around this stuff (just, generally getting away with it by luck)

**Comment by demkom58** [comment]
I got the point. But, in what way it is in public api? Here ([link](https://pastebin.com/raw/q9qWy9xC)) is list of available dependencies that comes with `io.papermc.paper:paper-api:1.19.2-R0.1-SNAPSHOT` from `https://repo.papermc.io/repository/maven-public/`.

**Comment by electronicboy** [comment]
it's not public API, nobody said that it is?

**Comment by demkom58** [comment]
> it's not public API, nobody said that it is?

Okay, maybe I misunderstood. Thanks for the detailed answer.
