### ISSUE TITLE
camels doing a weird teleportation thing whenever player tries to ride it.

### ISSUE THREAD

**Issue by Hikutaatti** [PaperSpigot/Paper#8640]
### Expected behavior

I right click the camel to ride it and just go around casually as I desire to.

### Observed/Actual behavior

Whenever I click a camel, I get teleported in the "y" direction to either -47000 or 36000. I can not ride it at all, the camel doesnt move with my inputs. When I shift to exit the camel, I get teleported back to where I should have been.

### Steps/models to reproduce

Create a world in singleplayer 1.19.3.
Make sure to apply the 1.20 datapack and the bundles datapack.
Once world is generated, exit from there and put the world to a server from your saves folder.
Next step is to find and ride a camel. No matter if natural or console generated.

### Plugin and Datapack List

No plugins were present. No extra datapacks were present apart from the ones mentioned.

### Paper version

This server is running Paper version git-Paper-314 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 812efd3)
You are running the latest version
Previous version: git-Paper-310 (MC: 1.19.3)

**Comment by EterNityCH** [comment]
ATTN: @Owen1212055

**Comment by mja00** [comment]
I'm able to reproduce this on the test server using both saddled camels around the spawn area.

**Comment by Hikutaatti** [comment]
I find this extremely weird. No idea what might have even caused it. Maybe something involving horses or other rideable entities.

**Comment by MWHunter** [comment]
![netcode](https://user-images.githubusercontent.com/49797025/206863993-792ac507-7fa4-4138-b59a-d37b331a2b11.png)

Netcode enthusiast here, either you or mojang are fucking up this variable most likely as it isn't capped and controls positioning on the camel.  It's also a long variable so it can go EXTREMELY high.

**Comment by mja00** [comment]
Tested by increasing `LastPoseTick` to `999999` and I was able to introduce the bug on any Camel. The number appears to increase every time the Camel sits down.

**Comment by kennytv** [comment]
It'd be good if someone created a ticket with the findings on bugs.mojang.com. We don't plan on officially supporting or fixing experimental features as they're not meant to be used in worlds you plan on keeping past this update

**Comment by mja00** [comment]
I've reported this upstream since I was able to reproduce it there: [https://bugs.mojang.com/browse/MC-258430](https://bugs.mojang.com/browse/MC-258430)

**Comment by Owen1212055** [comment]
This is also based on world time, so for old worlds, camels will cause this behavior.

**Comment by BillyGalbreath** [comment]
This is caused by Paper, not a vanilla issue.

**Comment by Owen1212055** [comment]
See the vanilla issue, this can certainly occur on vanilla too.

**Comment by NoahvdAa** [comment]
Reopening this, the view bugging out when the LastPoseTick is lower than the game time is a vanilla issue, but the fact that this can happen in cheatless gameplay is caused by Paper, specifically [this patch](https://github.com/PaperMC/Paper/blob/eec64a4e057c4eeec42d92cbaaee0eefb5c38081/patches/server/0538-Guardian-beam-workaround.patch) (as pointed out by billy in the purpur discord).

**Comment by Owen1212055** [comment]
It was noted in the bug report that this can occur if the server is running for +24 hours too. Is that wrong on the issue report then?
