### ISSUE TITLE
Boat#getStatus() throws NPE if called before the entity is ticked

### ISSUE THREAD

**Issue by Machine-Maker** [PaperSpigot/Paper#8661]
### Expected behavior

No error

### Observed/Actual behavior

throws an error

### Steps/models to reproduce

Spawn a boat entity and call getStatus (or just toString) on it right after.

Error is because the boat status on the nms entity isn't set until the first call of tick(). that doesn't happen until later.

### Plugin and Datapack List

none

### Paper version

1.19.3 323

### Other

Not sure what the best fix is. There is a getStatus() method that is called at the top of tick() to determine the status, but idk if it safe to call that before the entity is ticking. Could just pick a status to return as default if its null and document that.

**Comment by Doc94** [comment]
i dont notice this when added the method... maybe can be force a status (with `HANDLE#getStatus` ) when the instance is created or this is the same issue?
the other thing can be add a `#hasStatus` and add docs for check this before to get the status? but this only happen in the first instance...

**Comment by Warriorrrr** [comment]
Resolved by #9115
