### ISSUE TITLE
WorldCreator creates world as super flat, when specified as normal.

### ISSUE THREAD

**Issue by BigScary** [PaperSpigot/Paper#8664]
### Expected behavior

World should be normal type - plains, mountains, deserts, rivers, etc.

### Observed/Actual behavior

World is super flat.

### Steps/models to reproduce

I've been using this code to create a world weekly for a few years. I started having this problem after the update to 1.19.3 this morning.

WorldCreator creator = new WorldCreator("sampleWorld").type(WorldType.NORMAL).environment(Environment.NORMAL).generateStructures(true);
this.plugin.sampleWorld = this.plugin.getServer().createWorld(creator);

I fully deleted my world and re-created it with this, but it's super flat mode instead of normal. My only WILD GUESS is that it might be related to my default world's mode, which is super flat.

### Plugin and Datapack List

Lots, but I have not changed anything in the transition from 1.19.2 to 1.19.3. I only updated the server JAR.

### Paper version

This server is running Paper version git-Paper-325 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 0148283)

### Other

It should be unrelated, but I have specified minecraft:normal in server.properties.

Clarifying - my default world is super flat because it was created that way 3 years ago. My current SETTING in server.properties is minecraft:normal. And the code above specifies normal to the world creator. I expected the new world would be normal, but it is instead super flat.

I'm stuck in a big way because my players need this additional world for resources.

**Comment by Machine-Maker** [comment]
Yeah this is because of [this upstream commit](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/eecb4c0dc069b91ea5be52ca8fa831ecde666c19).

> My current SETTING in server.properties is minecraft:normal.

Changing this setting once the main level.dat file has been created has no effect.

**Comment by BigScary** [comment]
> Yeah this is because of [this upstream commit](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/eecb4c0dc069b91ea5be52ca8fa831ecde666c19).
> 
> > My current SETTING in server.properties is minecraft:normal.
> 
> Changing this setting once the main level.dat file has been created has no effect.

Thanks for having a look and responding. I'm a little confused by your answer, though. Are you saying this is somehow expected and by design? I am keeping my default world in place, and deleting + recreating a SECOND overworld.

**Comment by Machine-Maker** [comment]
@BigScary in a few minutes a download link will appear on https://github.com/PaperMC/Paper/pull/8666 in the top post. Download that and try it out on your server and see if the issue is fixed.
