### ISSUE TITLE
Using PrepareAnvilEvent results in deprecation warning

### ISSUE THREAD

**Issue by blablubbabc** [PaperSpigot/Paper#8671]
### Expected behavior

No deprecation warning.

### Observed/Actual behavior

Deprecation warning:
[Server thread/WARN]: [Shopkeepers] "Shopkeepers v2.16.4-SNAPSHOT+ad3832a1" has registered a listener for org.bukkit.event.inventory.PrepareInventoryResultEvent on method "void com.nisovin.shopkeepers.shopcreation.CreateListener.onPrepareAnvilEvent(org.bukkit.event.inventory.PrepareAnvilEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [nisovin, blablubbabc].

### Steps/models to reproduce

Running a plugin that registers for the PrepareAnvilEvent event should be sufficient.

### Plugin and Datapack List

Shopkeepers

### Paper version

This server is running Paper version git-Paper-328 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: c919e94)

### Other

I have not reproduced this myself. It was originally reported here: https://github.com/Shopkeepers/Shopkeepers/issues/820

There have been some relevant changes here: https://github.com/PaperMC/Paper/pull/8663/files

This deprecated Bukkit's `PrepareInventoryResultEvent` in favour of Paper's own `PrepareResultEvent` (not sure why this was required though).
And at the same time this removed the dedicated HandlerList from the `PrepareAnvilEvent` and have plugins implicitly register for the now deprecated `PrepareInventoryResultEvent` instead. The same applies to other similar 'PrepareX' events.

**Comment by Machine-Maker** [comment]
I thought warning was set to false by default.... like the `@Warning` annotation defaults to false
