### ISSUE TITLE
Explosions do not launch projectiles

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#8682]
### Expected behavior

I expected tnt to launch arrows with a tnt blast in a direction

### Observed/Actual behavior

The arrows ignore the tnt blast and continue with their normal trajectory.
(The arrows even landed on the tnt entity then passed straight through it)

### Steps/models to reproduce

Ignite the tnt and drop an arrow by pulling away the block that an arrow has landed on.

### Plugin and Datapack List

N/A (Didn't use any)

### Paper version

This server is running Paper version git-Paper-338 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 6625db3 on ver/1.19.3)

**Comment by Machine-Maker** [comment]
This is the test I used but I could not replicate this. Can you provide more concrete reproduction steps. 
https://user-images.githubusercontent.com/15055071/208198732-2a8f3be6-f63e-4d27-9996-4a712c116053.mov

As you can see in the video, the arrow was pushed by the tnt explosion.

**Comment by 9neutronstar9** [comment]
It must be a me issue, it works in single player but not in paper

**Comment by lynxplay** [comment]
I'll be closing this issue as we don't seem to be able to replicate it. If anyone finds replication steps, feel free to post them here so I can reopen the issue :)
