### ISSUE TITLE
FlatWorld Unsupported

### ISSUE THREAD

**Issue by NoChillFM** [PaperSpigot/Paper#8688]
### Expected behavior

Using Multiverse to create a super flat world or I import a flat world from singleplayer into papermc 1.19.3 to have a normal flat world.

### Observed/Actual behavior

World generated by plugin wasn't a flat world, but a normal world. Flat world imported from singleplayer has about 50 chunks that are flat, but after that, it's generated a regular world around it, that's without multiverse interfering.

### Steps/models to reproduce

Create flatworld in 1.19..3
Upload to server 
Load into flat world

### Plugin and Datapack List

Plugins (31): BungeeGuard, ClearLag, ClearLagTimer, CrashAPI, CrisTreeCapitator, DecentHolograms, EnchantmentSolution, Essentials, EssentialsChat, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MyPet, NoChatReports, OfflineGrowth, OnePlayerSleep*, OreRegenerator, PlaceholderAPI, PlayerWarps, QuickShop, RHLeafDecay, Spawnx, TabList, UltimateClaims, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard

Datapacks: [vanilla (built-in)], [file/bukkit (world)]

### Paper version

This server is running Paper version git-Paper-330 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 1c535f9)
You are 11 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-220 (MC: 1.19.2)

**Comment by Machine-Maker** [comment]
Update to latest
