### ISSUE TITLE
Skin layer Dissapears after death

### ISSUE THREAD

**Issue by Argoswilliams57** [PaperSpigot/Paper#8689]
### Expected behavior

Alright so I was playing on my Paper MC 1.19.3 server when I died my skin layers Dissapeared and my Internet was still good but my skin layer disappeared 
I tried everything nothing worked I hope you fix this issue

### Observed/Actual behavior

My skin layer Dissapeared after death 

### Steps/models to reproduce

Install a paper software and run the server without any plugins or Datapacks
Then try to die in your paper mc 
server 
See if you lose your Skin layer 
Same steps I did 7 times still happening in 1.19.3

### Plugin and Datapack List

No datapacks and plugins were installed 

### Paper version

Paper mc version 1.19.3

### Other

That was Only the issue and stupid Bug Costed my Friendship with my friend please fix this As soon as possible

**Comment by Machine-Maker** [comment]
This can also affect "score". Anything that uses synched entity data which is supposed to be restored in a respawn in ServerPlayer#restoreFrom

**Comment by Stabilizer360** [comment]
Right thanks so much for replying but Ok

**Comment by Stabilizer360** [comment]
But pleas I know it will affect score and all kind of stuff fix this issue
as soon as possible
Good bye

**Comment by Owen1212055** [comment]
Fixed by upstream in: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/d67777f8baf92e1dd1bb3a17221abd51dc336600
