### ISSUE TITLE
new method for comparing itemstacks

### ISSUE THREAD

**Issue by Jakush** [PaperSpigot/Paper#8698]
### Is your feature request related to a problem?

I mean, if someone doing "custom" items (just enchants,name,lore for example), and don't want to make item as unbreakable, you must make your method to compare strings because isSimilar also checks for durability.

### Describe the solution you'd like.

I think, it would be best to add new method `boolean isSimilar(ItemStack itemStack, boolean ignoreDurability);`, if it will be true, it will ignore item durability.

### Describe alternatives you've considered.

I had to check every possible thing probably in ItemStack in ItemMeta, if item has displayname, then if displayname is equals to another, if item has lore and if it equals to another, if it has enchants and also if enchants are same as on another itemstack.

**Comment by lynxplay** [comment]
You should really identify custom items by a PDC entry.

**Comment by RETAMROVEC** [comment]
Its not real custom item, it is just for example: NETHERITE SWORD, with enchant sharpness 6 and lore.

**Comment by RETAMROVEC** [comment]
I mean, you can do PDC entry, but this would be cool and also you can have one more method what can be very useful.

**Comment by Doc94** [comment]
Hmm not sure how can be a "builder" for a custom comparator... For give the user define what need compare (name, lore, enchants, durability)

**Comment by Malfrador** [comment]
A few years ago, we had an item filtering plugin that removed certain items (all diamond sword, all swords with sharpness 2) etc. 
For that a method like this would have been useful. 
Assuming the implementation would avoid the downsides of using ItemMeta. 

But it definitely shouldn't be used for custom items and is generally a very niche use case imo.

**Comment by Cryptite** [comment]
This exists at the nms level: `ItemStack.isSameIgnoreDurability`

**Comment by RETAMROVEC** [comment]
Yeah, but i don't like NMS, and also i have problems with importing it in my gradle project.

**Comment by Doc94** [comment]
> This exists at the nms level: `ItemStack.isSameIgnoreDurability`

yeah but CraftBukkit not use the NMS for the isSimilar its most like..

```java
@Override
    public boolean isSimilar(ItemStack stack) {
        if (stack == null) {
            return false;
        }
        if (stack == this) {
            return true;
        }
        if (!(stack instanceof CraftItemStack)) {
            return stack.getClass() == ItemStack.class && stack.isSimilar(this);
        }

        CraftItemStack that = (CraftItemStack) stack;
        if (handle == that.handle) {
            return true;
        }
        if (handle == null || that.handle == null) {
            return false;
        }
        Material comparisonType = CraftLegacy.fromLegacy(that.getType()); // This may be called from legacy item stacks, try to get the right material
        if (!(comparisonType == getType() && getDurability() == that.getDurability())) {
            return false;
        }
        return hasItemMeta() ? that.hasItemMeta() && handle.getTag().equals(that.handle.getTag()) : !that.hasItemMeta();
    }
```

**Comment by lynxplay** [comment]
Really unsure how nice that works in the API and how much benefit this offers compared to just writing this yourself in a simple utility. 

The current ItemStack#equal logic (and CraftItemFactory#equals(ItemMeta, ItemMeta)) do all this comparison using 
a) a copy of the current item meta (ItemStack#getItemMeta is invoked =>. a clone of the item meta is created)
b) without converting to the NMS layer so we could not just use an existing NMS method.

We'd have to extract out the durability check in CraftMetaItem#equalsCommon for this, create *another* comparison method and then invoke that.
Concerning that the existing logic already includes a item meta cloning call, I don't see much difference in just a simple helper method that just sets the damage to 0 on the item meta clone created.

With regards to the fact that the current implementation of ItemStack#equals does include the downsides of cloning item meta, I think it is a lot more beneficial to write a proper `Predicate<ItemMeta>` that only compares exactly what you want to compare. And if that includes more than [Malfrador](https://github.com/Malfrador)'s example of enchantments, e.g. display name and lore, you are very much in custom item stack territory which should be handled through the PDC.

**Comment by RETAMROVEC** [comment]
I mean, probably this would work but this will help beginners much, because it is not very beginner friendly. This would be easier and perfomance saver (maybe, i couldn't say).

**Comment by lynxplay** [comment]
That is exactly my point, this would not save performance, the server rn does an item meta clone as well (which is the only "heavy" part). I agree that this is more beginner friendly but also, slippery slope into using such a method for custom items when you really shouldn't.

If I am being honest, I can barely see a point where this method would be used for anything outside custom items.
 - If you just want to delete any stone sword with sharpness, you'd also have to disregard any potential display name which players could set through an anvil.
 - If you care for any stone sword, just compare the material.
 - If you care for a stone sword with a specific name but any damage, either that name is unobtainable (e.g. coloured) and its a custom item or its user set, which, this would be the one thing I can see this being useful for.
 
 I can obviously just be biased tho here. I think I communicated my opinion on this clearly so other members of the team will hopefully chime in soon to give input as well :) Maybe I am just missing a good usecase.

**Comment by RETAMROVEC** [comment]
Okay.

**Comment by Machine-Maker** [comment]
I don't want to go down this road of offering an equals method with a boolean to ignore one thing. What happens when someone wants a method that ignores display name, or ignores lore, or attributes, or a part of an itemmeta? We'd end up with 50 equals methods.

**Comment by RETAMROVEC** [comment]
Okay, thanks for answer!
