### ISSUE TITLE
net.minecraft.world.level.SpawnerCreature.a()

### ISSUE THREAD

**Issue by deathendless** [PaperSpigot/Paper#8699]
### Timings or Profile link

https://spark.lucko.me/Xj1dsUG98p

### Description of issue

How to fix this problem
https://spark.lucko.me/Xj1dsUG98p

### Plugin and Datapack List

AureliumSkills-Beta1.3.12, beautyquests-0.20.1-SNAPSHOT, BeehivesPro, Chunky-1.3.38, Citizens-2.0.30-b2759, CMI-9.3.0.1, CMILib1.2.4.1, Codex, CustomCrops-2.1.1-all, CustomFishing-1.2.11-all, CustomNameplates-2.1.5-all, DailyReward-1.13+, DeluxeMenus-1.13.6-Release, Denizen-1.2.5-b1775-REL, economy-1.0, ExcellentCrates-4.1.1, ExcellentShop-4.3.1 , FarmLimiter,  fastasyncvoxelsniper-2.8.0, FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-332, Gunging_Ootilities_Plugin-v1.10.9_2022.12.08-066dev, HeadDatabase-4.17.0-, HolographicDisplays, images-2.2.8, etc

### Server config files

```
Paste configs or paste.gg link here!
```

### Paper version

git-Paper-307 (MC: 1.19.2)

**Comment by electronicboy** [comment]
That generally means that you have something preventing your server from
meeting the mob spawn caps, i.e. plugins preventing spawns
