### ISSUE TITLE
Player#getInventory().addItem() does not add to offhand slot

### ISSUE THREAD

**Issue by partydev** [PaperSpigot/Paper#8700]
### Expected behavior

When picking up an item from the ground in vanilla, if the player is holding a partial stack in their offhand, the picked up item will fill that partial stack in their offhand.

Using Player#getInventory().addItem(), the item should be added to the partial stack in their offhand, similar to the item pickup behavior in vanilla.

### Observed/Actual behavior

When picking up an item from the ground, if the player is holding a partial stack in their offhand, the picked up item will fill that partial stack in their offhand.

Using Player#getInventory().addItem(), the item does not fill that partial stack and instead goes into their inventory. If their inventory is full, the item disappears and is added to the returned hashmap.

### Steps/models to reproduce

Hold 1 dirt in your offhand. Use Player#getInventory().addItem(ItemStack(Material.DIRT, 1)) to add 1 dirt to your inventory. The dirt will go into the incorrect slot. Repeat with a full inventory and a 1 item stack dirt in your offhand. The item will not be added and will be added to the returned hashmap.

### Plugin and Datapack List

None other than the test plugin.

### Paper version

Paper-346

**Comment by PedroMPagani** [comment]
This behavior also seems to be applied for .remove

**Comment by Brokkonaut** [comment]
I don't think that this is a bug. From the Inventory javadoc:

> Note that whilst [iterator()](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/Inventory.html#iterator()) deals with the entire inventory, add / contains / remove methods deal only with the storage contents.

**Comment by Owen1212055** [comment]
Yeah, that's unfortunately just the result of decisions made in the past.
We cannot change this without "breaking" behavior.

**Comment by partydev** [comment]
What do you define as the storage contents of an inventory? The offhand slot is part of the storage content if you define it as a slot that gets filled up when picking up items. I understand the reasoning of not wanting to "break" behavior, but that seems inconsistent with Paper's actions of the past. Leaving bugs and inconsistencies in for the sake of maintaining backwards compatibility.
