### ISSUE TITLE
MC location limit issue

### ISSUE THREAD

**Issue by CreativityAtItsBest** [PaperSpigot/Paper#8701]
### Timings or Profile link

https://timings.aikar.co/dev/?id=351f974b01bb4fefb0bea17176ab4156#timings

### Description of issue

If you go to around 30m x and 30m z, the server tps will drop instantly from 20 to around 1, and once you go back to a more reasonable location it goes back to 20 tps. (Unsure if it's a paper issue or a plugin issue, but likely paper as I see no plugins causing lag in timings)

### Plugin and Datapack List

BuycraftX, ChatControl, DeluxeMenus, Factions, InventoryRollbackPlus, ItemEdit, LiteBans, LuckPerms, MinehutPlugin, Multiverse-Core, OpenInv, PlaceholderAPI, PvPManager, Shopkeepers, Skript, spark, SuperVanish, TradePlus, Vault, ViaVersion, VoxelSniper, Vulcan, WorldEdit, WorldGuard

vanilla, bukkit, composs (custom datapack)

### Server config files

Paste.gg is down as of now

bukkit.yml: https://pastebin.com/ZKce57Tm
spigot.yml: https://pastebin.com/J1Yd1fY0
paper-global.yml: N/A
paper-world-defaults.yml: N/A
server.properties: https://pastebin.com/9h06bVk5

### Paper version

This server is running Paper version git-Paper-215 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 236a296)
You are 92 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-177 (MC: 1.18.1)

### Other

I took a timings report at 0,0 and a timings report at 30m,30m and they came out the same (except for the TPS and TPS loss part), meaning it probably isn't a plugin/datapack issue, but rather a server one.
My server is quite laggy, but the TPS is 20 when not at the border.

**Comment by electronicboy** [comment]
We'd need a report from a sampler, such as spark or yourkit, etc, but given going that far our generally creates many jssues with the games logic, especially with stuff like the generation code which could easily create such issues, this is probably a "don't care" type of deal

**Comment by PedroMPagani** [comment]
> ### Timings or Profile link
> 
> https://timings.aikar.co/dev/?id=351f974b01bb4fefb0bea17176ab4156#timings
> 
> ### Description of issue
> 
> If you go to around 30m x and 30m z, the server tps will drop instantly from 20 to around 1, and once you go back to a more reasonable location it goes back to 20 tps. (Unsure if it's a paper issue or a plugin issue, but likely paper as I see no plugins causing lag in timings)
> 
> ### Plugin and Datapack List
> 
> BuycraftX, ChatControl, DeluxeMenus, Factions, InventoryRollbackPlus, ItemEdit, LiteBans, LuckPerms, MinehutPlugin, Multiverse-Core, OpenInv, PlaceholderAPI, PvPManager, Shopkeepers, Skript, spark, SuperVanish, TradePlus, Vault, ViaVersion, VoxelSniper, Vulcan, WorldEdit, WorldGuard
> 
> vanilla, bukkit, composs (custom datapack)
> 
> ### Server config files
> 
> Paste.gg is down as of now
> 
> bukkit.yml: https://pastebin.com/ZKce57Tm
> spigot.yml: https://pastebin.com/J1Yd1fY0
> paper-global.yml: N/A
> paper-world-defaults.yml: N/A
> server.properties: https://pastebin.com/9h06bVk5
> 
> ### Paper version
> 
> This server is running Paper version git-Paper-215 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 236a296)
> You are 92 version(s) behind
> Download the new version at: https://papermc.io/downloads
> Previous version: git-Paper-177 (MC: 1.18.1)
> 
> ### Other
> 
> I took a timings report at 0,0 and a timings report at 30m,30m and they came out the same (except for the TPS and TPS loss part), meaning it probably isn't a plugin/datapack issue, but rather a server one.
> My server is quite laggy, but the TPS is 20 when not at the border.

You should remove all the plugins first, and then see if it lags.

**Comment by CreativityAtItsBest** [comment]
Whilst I was making this I realized it was outdated, and I'm going to update it now. There was lots of errors with generation past 30m, 30m (i noticed this after using a plugin to teleport past the limit, almost instantly crashed the server with generation issues).
Makes sense it would lag trying to generate, and I saw lots of glitchy blocks past the border.

This could be an issue if one were to try flying to a worldborder on the server and just lagging it, as it doesn't crash afaik.

**Comment by CreativityAtItsBest** [comment]
> 
The plugins likely aren't the issue, because when I checked the timings and even spark, it never showed anything using high tick % or high server thread, meaning it was a MC/Paper issue.

**Comment by PedroMPagani** [comment]
> > 
> The plugins likely aren't the issue, because when I checked the timings and even spark, it never showed anything using high tick % or high server thread, meaning it was a MC/Paper issue.
> 

You still havent proven it's not the plugins, they'll never fix it or consider unless you remove all the plugins and the behavior still happens, then when you're in the LATEST, and proved that it's a paper issue, they'll probably fix.
You need to stop saying that it's "probably not" and be certain,for this remove all the plugin jars and see if it lags..

**Comment by Owen1212055** [comment]
I can't reproduce this, please try testing this WITHOUT data packs and plugins. If you are still able to reproduce, please feel free to provide some insight using a profiler (such as spark or youtkit) as mentioned above.

Thank you for your report, however. 😄
