### ISSUE TITLE
ItemMeta's ignoreLevelRestriction isn't completely wholesome anymore

### ISSUE THREAD

**Issue by DeadMaster121** [PaperSpigot/Paper#8706]
### Expected behavior

`ItemMeta#addEnchant(Enchantment.LOOT_BONUS_BLOCKS, 500, true);` does ignore the level restriction, although it limits it till 255.

[Paper 170 - This issue is still present on the latest version, although this is the version that made it limited to 255]
![2022-12-21_11 32 06](https://user-images.githubusercontent.com/34813557/208898745-a8f246a6-5e23-444c-9ada-1aff36e9c770.png)

### Observed/Actual behavior

[Paper 169]
![2022-12-21_11 30 47](https://user-images.githubusercontent.com/34813557/208899708-b6dfdf93-c00c-4433-8c1e-2e351cc71ecc.png)

### Steps/models to reproduce

1. `ItemMeta#addEnchant(Enchantment.LOOT_BONUS_BLOCKS, 500, true);` 
2. Output the level of the enchant
3. Use your eyes to look at the output to realize it's limited at 255

### Plugin and Datapack List

[11:57:22 INFO]: Plugins (1): Test

```
package test.test;

import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.plugin.java.JavaPlugin;
import org.jetbrains.annotations.NotNull;

public final class Test extends JavaPlugin implements CommandExecutor {

    @Override
    public void onEnable() {
        getCommand("test").setExecutor(this);
    }

    @Override
    public boolean onCommand(@NotNull CommandSender sender, @NotNull Command command, @NotNull String label, @NotNull String[] args) {
        final Player rPlayer = (Player) sender;
        final ItemStack itemStack = rPlayer.getInventory().getItemInMainHand();
        final ItemMeta itemMeta = itemStack.getItemMeta();

        itemMeta.addEnchant(Enchantment.LOOT_BONUS_BLOCKS, 500, true);
        itemStack.setItemMeta(itemMeta);

        sender.sendMessage("Level = " + itemStack.getEnchantmentLevel(Enchantment.LOOT_BONUS_BLOCKS));
        return true;
    }
}
```

### Paper version

```
[12:03:42 INFO]: This server is running Paper version git-Paper-348 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 94373f0)
You are running the latest version
Previous version: git-Paper-170 (MC: 1.19.2)
```

[For proof that the issue is still present on the Paper-348]
![2022-12-21_12 03 28](https://user-images.githubusercontent.com/34813557/208901158-be6b24e1-f970-4139-8d26-7f66c280f08d.png)

### Other

It appears that @Lulu13022002's PR https://github.com/PaperMC/Paper/pull/8373 began to cause this issue.

**Comment by Doc94** [comment]
Yep i confirm is the #8373 the "issue" mostly this patch make NMS handle the level in get method and internally when the level is get NMS make a "clamp" beetwen 0 and 255 in the EnchantmentHelper class.
![image](https://user-images.githubusercontent.com/3602279/208903387-8e9141a7-80a5-4ba9-9cd3-829f7c33a3c2.png)

**Comment by Lulu13022002** [comment]
Vanilla cut the enchantment level to 255 max. If you use item meta bypass then you should reuse that to get the right level.

**Comment by Doc94** [comment]
> Vanilla cut the enchantment level to 255 max. If you use item meta bypass then you should reuse that to get the right level.

maybe we can consider add this "notes" to the javadocs? this is the second thing where the info about the enchant beetween ItemStack and ItemMeta has diff (the first was for a deprecated method for custom enchants and get the level).

**Comment by electronicboy** [comment]
Javadocs generally shouldn't be noting down implementation details

This is not really a bug, you're hitting the implementation details of the
game, ignore limit only applies to the defined max enchantment limit, it
doesn't vow to bypass the limits of the internal data types
