### ISSUE TITLE
Paper server hangs whilst loading

### ISSUE THREAD

**Issue by olijeffers0n** [PaperSpigot/Paper#8717]
### Stack trace

```
Console output:
https://paste.ollieee.xyz/cizolupemu.yaml
```

### Plugin and Datapack List

Plugins are not loaded yet

### Actions to reproduce (if known)

It is just my development server, updated to the latest build to test.

### Paper version

Latest, cannot get the output

### Other

Tested on Spigot, works fine... Just slower cause it isn't Paper.

**Comment by Peter-Crawley** [comment]
Is this the same as https://github.com/PaperMC/Paper/issues/6020

**Comment by lynxplay** [comment]
presumably yea

**Comment by olijeffers0n** [comment]
You can close if its a duplicate then, wasn't aware there was another issue 😄

**Comment by olijeffers0n** [comment]
To keep this in sync with discord, I can replicate this on every server start and this my stack:

https://paste.ollieee.xyz/suvexoyari.csharp

**Comment by Owen1212055** [comment]
Dupe of https://github.com/PaperMC/Paper/issues/6020
