### ISSUE TITLE
Allow components in getCommand()#setUsage()

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#8721]

**Comment by Machine-Maker** [comment]
I believe the upcoming brigadier API will resolve this issue. We probably won't backport Component support to legacy commands when that happens.

https://github.com/PaperMC/Paper/pull/8235

**Comment by Owen1212055** [comment]
That is correct.

Legacy Commands will still have to manually define usage. (using legacy text, as there's no reason to use colors here anyways?)
However, the modern brig commands will use the autogenerated usage that brig provides

**Comment by defusing7** [comment]
I agree that there is no needs to use colors here. I thought this was the same as the "usage:" in the plugin.yml that would be sent when I returned false but it actually is just for the /help command.
