### ISSUE TITLE
At first I thought it was geyser but they say it's paper

### ISSUE THREAD

**Issue by Batman2741** [PaperSpigot/Paper#8723]
### Expected behavior

Bedrock players able to join through geyser

### Observed/Actual behavior

Here is a log
https://mclo.gs/80spR6N

### Steps/models to reproduce

Simply joining on bedrock 

### Plugin and Datapack List

Shown in previous posted log file

### Paper version

Shown in log file

**Comment by Machine-Maker** [comment]
This probably isn't a Paper issue. If its not a geyser issue, its an issue with a plugin not updating how entity metadata was changed in 1.19.3

**Comment by Camotoy** [comment]
While anything is possible, I highly doubt this is a Geyser issue as well.

**Comment by Batman2741** [comment]
The reason I first thought it was geyser is bc about 20 people were in the geyser discord with the same issue and when I put the logs in the bot said to check with paper

**Comment by Batman2741** [comment]
It appears to be a conflict with protocol lib

**Comment by electronicboy** [comment]
afaik, this was generally traced to either outdated versions of PL, or plugins messing with internals

**Comment by Batman2741** [comment]
> afaik, this was generally traced to either outdated versions of PL, or plugins messing with internals

It was on the latest version I even tried just it and geyser they just seem to conflict
