### ISSUE TITLE
Config option feature-seeds.generate-random-seeds-for-all is unused

### ISSUE THREAD

**Issue by Joo200** [PaperSpigot/Paper#8737]
### Expected behavior

The config option `feature-seeds.generate-random-seeds-for-all` should be used to generate random seeds for every feature.

### Observed/Actual behavior

That config option is added by https://github.com/PaperMC/Paper/blob/master/patches/server/0004-Paper-config-files.patch
but it's not used by the configurable feature seeds patch: https://github.com/PaperMC/Paper/blob/master/patches/server/0745-Configurable-feature-seeds.patch

### Steps/models to reproduce

Toggle option generate-random-seeds-for-all.

### Plugin and Datapack List

none

### Paper version

Commit 90750a6591cce9afda52093951ab1f4e438b64de

**Comment by Machine-Maker** [comment]
The option works fine for me? I set it to true and the seeds are generated in each individual world folder's config file. Can you confirm this?

**Comment by JOO200** [comment]
Uhh wait, I found my issue. Yes, it works fine now. Thanks
