### ISSUE TITLE
Mobs cannot join teams

### ISSUE THREAD

**Issue by Cakequester** [PaperSpigot/Paper#8742]
### Expected behavior

The mob joins the team successfully.

### Observed/Actual behavior

Console says "Unable to add mob to team "(whatever your team is named)"! (That team probably doesn't exist!)"

### Steps/models to reproduce

Just summon a mob with a team.

### Plugin and Datapack List

MinehutCosmetics, MinehutPlugin, SkQuery, skRayFall, Skript, ViaBackwards, ViaVersion.

### Paper version

git-Paper-346

### Other

Affects all mobs but not players.

**Comment by NoahvdAa** [comment]
Do you have `allow-non-player-entities-on-scoreboards` set to `true` in the per world config? It's set to off by default.

**Comment by lynxplay** [comment]
Concerning you have not provided the information asked for, I'll consider this fixed on your end by updating your config.
If this was not the case, please comment on the issue and someone will reopen it :)
