### ISSUE TITLE
Ability to modify the colour of flash particles

### ISSUE THREAD

**Issue by galacticwarrior9** [PaperSpigot/Paper#8743]
### Is your feature request related to a problem?

In the vanilla game, flash particles (`Particle.FLASH`) are spawned when a firework detonates and are coloured depending on the firework's colour. However, to my knowledge, there is no way to modify the colour of flash particles spawned via the API.

### Describe the solution you'd like.

A way to modify the colour of flash particles in the various `spawnParticle` methods — perhaps  by adding an equivalent of `Particle.DustOptions` for them.

### Describe alternatives you've considered.

Spawning coloured fireworks and detonating them on the same tick, but this is a messy solution and the fireworks are briefly visible to players with higher pings.

**Comment by Owen1212055** [comment]
This is a client limitation and is not possible.
