### ISSUE TITLE
My server often auto crash for no reason!Can anyone help me find out what's the issue?

### ISSUE THREAD

**Issue by BarryAllen-Arrow** [PaperSpigot/Paper#8746]
### Stack trace

```
https://paste.gg/p/anonymous/580e6c23141f4f6ba93bb0edcc7e8a0c
```

### Plugin and Datapack List

AdvancedTeleport, AureliumSkills, AuthMe, BottledExp, ChatManager, ChestsPlusPlus, Chunky, ChunkyBorder, CMILib, CoreProtect, dynmap, Essentials, EssentialsChat, EssentialsSpawn, floodgate, Geyser-Spigot, Images, LuckPerms, LWC, MobsToEggs, Multiverse-Core, Multiverse-Portals, Not-Too-Expensive, PlaceholderAPI, PlayerAuctions, QuickShop, ServerBackup, SkinsRestorer, Slimefun, TimeIsMoney, UTitleAuth, Vault, ViaBackwards, ViaRewind, ViaVersion, VillagerEssentials*, WorldEdit, WorldGuard, XSpawners

### Paper version

This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)
You are running the latest version

**Comment by NoahvdAa** [comment]
We no longer support 1.18 (or offline mode for that matter).
Additionally, this issue tracker is for bugs in the server software, not for diagnosing performance issues. You should head to [the Discord](https://discord.gg/papermc) for those kinds of issues (do note that we also only support 1.19.3 there).
