### ISSUE TITLE
Packet Rate kick reason

### ISSUE THREAD

**Issue by jacklollz2** [PaperSpigot/Paper#8747]
### Is your feature request related to a problem?
When players get kicked from a packet rate override limit, it doesn't tell me what limiter triggered the kick.
### Describe the solution you'd like.
I would like the console to output which packet rate override trigger occurred.
### Describe alternatives you've considered.
Plugin use, but it's not as efficient as the built in packet limiter.

**Comment by Doc94** [comment]
What is the message when are kicked?

**Comment by jacklollz2** [comment]
> What is the message when are kicked?

No, I am looking for the console to output which override was triggered.
For example, if I create an override for ServerboundSetCreativeModeSlotPacket and make it so that players get kicked by this packet, it just says "Kicked for exceeding packet rate limit", but I want to know in the console exactly which override triggered.

**Comment by Doc94** [comment]
okay i think this is related to this patch https://github.com/PaperMC/Paper/blob/d5f1ffc2e6928a6728f91ab2ad2e020b105eab7f/patches/server/0713-Add-packet-limiter-config.patch

not sure if is better and another logger (info/warn) for tell in console what is the packet or add this info to the kick message (this broke the vanilla thing)

**Comment by jacklollz2** [comment]
> okay i think this is related to this patch https://github.com/PaperMC/Paper/blob/d5f1ffc2e6928a6728f91ab2ad2e020b105eab7f/patches/server/0713-Add-packet-limiter-config.patch
> 
> not sure if is better and another logger (info/warn) for tell in console what is the packet or add this info to the kick message (this broke the vanilla thing)

It is no bug, I just want to see info on the trigger
I made it kick people intentionally, I just want to see the cause rather than vague info

**Comment by NoahvdAa** [comment]
Resolved in b1696788d61ddc338bd2e61fac3b43ff60c432e1 (#9292)
