### ISSUE TITLE
Barrel Config Rows Size

### ISSUE THREAD

**Issue by Euphillya** [PaperSpigot/Paper#8759]
### Is your feature request related to a problem?

Chests and double chests are entities displayed on Minecraft game clients, and a surplus of chests makes the FPS drop hyper low until it is no longer playable.

### Describe the solution you'd like.

Barrels are full blocks, and as such, are displayed on the game client like any other block. Adding a configuration that would allow to change the size of the barrels could solve this problem.

### Describe alternatives you've considered.

We have no storage block that is a full block.

**Comment by lynxplay** [comment]
In my honest opinion that is far far away from what paper aims to do and I personally do not believe this should be implemented.

While I don't think it is nicely possible with a plugin (see the hard coded return value in BarrelBlockEntity#getContainerSize), I don't think papers goal is such vanilla breaking behaviour, even if it is as a config option.
Obviously I do not speak for everyone, so I'll leave this issue open for further discussion and input :+1

**Comment by Malfrador** [comment]
Maybe instead of adding a config option, API to set the size of a barrel (or other containers) could be added. 
That would leave plugins with the responsibility to deal with the consequences of this.

It technically is already possible to make larger barrels using the API by just opening a virtual chest inventory instead of the barrel and storing the items somewhere else (e.g. the PDC of the barrel). But having API to do this directly certainly would be nicer.

**Comment by electronicboy** [comment]
Mutating size of arbitrary containers would have other side effects, I don't see any advantage to maintaining the burden of something like this when a plugin could do this trivially and not have to deal with the risky caveats of modifying internal data expectations

**Comment by Owen1212055** [comment]
See above, in general you should just handle modifying these containers yourself using a plugin. 
This would be an unnecessary burden.

**Comment by SoSeDiK** [comment]
Just FYI, [Purpur has this feature implemented](https://purpurmc.org/docs/Configuration/rows) if you really need it and want a simple solution.

Although keep in mind that this is not supported by Paper, and for any further support you'll have to ask the Purpur community if you switch.
