### ISSUE TITLE
MC-4, again?

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#8763]
### Expected behavior

Items should be in sync. I can not pick up some items nor can i burn them.

### Observed/Actual behavior

[https://www.xbox.com/play/media/7YFVCMG73Q](https://www.xbox.com/play/media/7YFVCMG73Q)

### Steps/models to reproduce

See my video.

### Plugin and Datapack List

04.01 23:36:54 [Server] INFO Plugins (27): AntiNetherRoof*, BlueMap, Chunky, CoreProtect, Essentials, EssentialsChat, EssentialsSpawn, GSit, ImageMaps, InventoryRollbackPlus, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, LiteBans, LuckPerms, MiniMOTD, Pl-Hide-Pro, PlaceholderAPI, ProtocolLib, SlimeChunkChecker, SuperVanish, TAB, Vault, Vulcan, WorldEdit, WorldGuard, WorldGuardExtraFlags

+ Datapacks
https://ibb.co/RYNyzT4

### Paper version

04.01 23:40:20 [Server] INFO This server is running Paper version git-Paper-368 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: de5b1da)
04.01 23:40:20 [Server] INFO You are running the latest version
04.01 23:40:20 [Server] INFO Previous version: git-Paper-366 (MC: 1.19.3)

**Comment by ham1255** [comment]
it seems people are able to confirm reproduction on https://bugs.mojang.com/browse/MC-4

**Comment by jurohn** [comment]
> It may be caused by this patch #8756

I experience this bug since this update indeed.
