### ISSUE TITLE
Linking Nether Portals - 1.19.3

### ISSUE THREAD

**Issue by rwagner76** [PaperSpigot/Paper#8769]
### Expected behavior

Portals linked by location x,z should link to each other, not to nearby portal at different y value.
Lower y value portal is taking precedence even though both pairs of portals have proper x/z.

### Observed/Actual behavior

One pair of portals works properly back/forth (the one with lower y value portal in the nether). The second pair works one way, but going back through leads to 1st pair of portals.

In my example, base portal and chunk loader portal are close to each other, but at acceptable distance (see screenshot).

### Steps/models to reproduce

Originally, base portal was directly on the nether roof. Base portals worked fine.
Chunk loader portal from nether would work as expected.
Chunk loader portal from overworld -> nether would lead to the base portal.

I raised the y value of the base portal on the nether roof by 2 to so it was the same height as the chunk loader portal. This solved the problem and both pairs of portals link properly.

![2023-01-07_12 28 41](https://user-images.githubusercontent.com/20705388/211165531-4860ac7f-4c3d-4cd7-a2f0-46a77385939a.png)

### Plugin and Datapack List

GravityControl
OnePlayerSleep

### Paper version

This server is running Paper version git-Paper-366 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 8d7d927)
You are 5 version(s) behind
Download the new version at: https://papermc.io/downloads

### Other

Based on a search, this seems similar to issue #6995

**Comment by Warriorrrr** [comment]
The portal with the lower y value taking priority is intended behavior, in vanilla the list of possible portal candidates is first sorted by distance and then by height. I also reproduced this on both paper and vanilla, and the results were what you described in the observed/actual behavior both times.
