### ISSUE TITLE
 The server crashes a couple of times a day

### ISSUE THREAD

**Issue by traprek** [PaperSpigot/Paper#8785]
### Stack trace

Crash log here: 

https://hastebin.com/razubupupi.yaml

### Plugin and Datapack List

0

### Actions to reproduce (if known)

0

### Paper version

 git-Paper-794 (MC: 1.16.5)

### Other

Plugins 75

**Comment by electronicboy** [comment]
You're using a version of paper which is no longer supported, and didn't even fill out the template properly (nor is this generally the place for support)
