### ISSUE TITLE
Please help with server crash

### ISSUE THREAD

**Issue by traprek** [PaperSpigot/Paper#8788]
### Stack trace

Some player somehow crashes the server, I don't understand how

More information https://hastebin.com/nacixuwayi.yaml

Timings report just done https://timings.aikar.co/dev/?id=ff04083c3391414980fa0dbd6979de26

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/122567996/212478529-468fa728-c23e-411e-bf66-4d5f28784cfc.png)

### Actions to reproduce (if known)

no

### Paper version

![image](https://user-images.githubusercontent.com/122567996/212478547-5ee8d350-a269-4085-9a31-784580031281.png)

### Other

Tuinity 1.16.5
Java 16
Debian 11

There was also such a crash on regular Paper and Purpur

**Comment by kennytv** [comment]
1.16 is no longer supported
