### ISSUE TITLE
CraftMinecartHopper, CraftMinecartTNT and CraftMinecartMobSpawner is final

### ISSUE THREAD

**Issue by MelonHell** [PaperSpigot/Paper#8794]
### Expected behavior

```java
public class CraftMinecartHopper...
public class CraftMinecartTNT...
public class CraftMinecartMobSpawner...
```
like all other entity classes

### Observed/Actual behavior

```java
public final class CraftMinecartHopper...
public final class CraftMinecartTNT...
final class CraftMinecartMobSpawner...
```

### Paper version

1.19.3 #378

### Other

because of this, there is no way to inherit these three classes, which is very strange, given that all other entity classes are public and non final

**Comment by MiniDigger** [comment]
those are internal classes, not api, you should not touch them, they may change at any time.
