### ISSUE TITLE
NoteBlocks are not working or are bugging with redstone

### ISSUE THREAD

**Issue by kaktus-1** [PaperSpigot/Paper#8826]
### Expected behavior

That the noteblock makes a sound

### Observed/Actual behavior

It's difficult.

When you place a repeater bevor it it makes no sound.
When you combine it with redstone it makes a sound when the signal goes OFF but not on on.
When you just use a button near it, it is not working.
But when you put that button above a block nearby the noteblock it makes a sound on signal ON and OFF.

Its just weird.

There are a lot of more combinations, I made two screens and added them to "Steps / models to reproduce"

### Steps/models to reproduce

The left one is not working, the right one is working:
![image](https://user-images.githubusercontent.com/56768074/216131418-e9d53d2b-4691-4522-b4a6-51b03a33dac4.png)

When you place a redstone between then its working
![image](https://user-images.githubusercontent.com/56768074/216131533-ef5b15ea-d866-48ad-a44a-01bf37d36265.png)

I guess there are quite more combinations when its working and when not.

### Plugin and Datapack List

None, tested on empty server

### Paper version

This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version
Previous version: git-Paper-388 (MC: 1.18.2)

**Comment by lynxplay** [comment]
Using default configs and no plugins, I cannot replicate this. Did you change anything in the configs ?
![image](https://user-images.githubusercontent.com/32834385/216134566-a10388c7-a94d-465a-8875-cd3b2ddadc5e.png)

**Comment by XNonymous-N2** [comment]
Yeaa its working now. No comment about that
