### ISSUE TITLE
NMS Missing implementation of method

### ISSUE THREAD

**Issue by IkeVoodoo** [PaperSpigot/Paper#8849]
### Expected behavior

No exceptions

### Observed/Actual behavior

The following exception

```java
[08:51:01 ERROR]: Error occurred while enabling ModPack v1.0.0-SNAPSHOT (Is it up to date?)
java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract int getIdFor(java.lang.Comparable)' of abstract class net.minecraft.world.level.block.state.properties.IBlockState.
        at io.papermc.paper.util.table.ZeroCollidingReferenceStateTable.loadInTable(ZeroCollidingReferenceStateTable.java:70) ~[paper-1.19.3.jar:git-Paper-399]
        at net.minecraft.world.level.block.state.StateHolder.populateNeighbours(StateHolder.java:146) ~[?:?]
        at net.minecraft.world.level.block.state.StateDefinition.<init>(StateDefinition.java:67) ~[?:?]
        at net.minecraft.world.level.block.state.StateDefinition$Builder.create(StateDefinition.java:151) ~[?:?]
        at net.minecraft.world.level.block.Block.<init>(Block.java:211) ~[paper-1.19.3.jar:git-Paper-399]
```

### Steps/models to reproduce

This exception is a bit difficult to reproduce, so bear with me:

- Create a class that extends the NMS block
- Gather a Properties object for said block like so

```java
CraftBlockData data = (CraftBlockData) Material.JACK_O_LANTERN.createBlockData();
var nmsMaterial = data.getState().getMaterial(); // Used var, don't know the non-moj naming
Propreties properties = Properties.of(nmsMaterial);
```

- Use the properties object in the super() constructor of Block

### Plugin and Datapack List

Fresh server, only the plugin I am using to test NMS

### Paper version

This server is running Paper version git-Paper-399 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: f2f9e8c)
You are running the latest version
Previous version: git-Paper-384 (MC: 1.19.3)

### Other

Based off of
https://github.com/BananaPuncher714/DimensionalBlocks

**Comment by Machine-Maker** [comment]
I'm almost certain that extending the nms Block to create a custom block is very unsupported.

**Comment by IkeVoodoo** [comment]
I am extending `net.minecraft.world.level.block.state.properties.Property` however there is no method with the same signature.

What more context would you need?

**Comment by kennytv** [comment]
The general gist of diving into Vanilla internals is that you should be able to work your way through them somewhat on your own. This is not a Paper issue, so if you want more help, the paper-dev channel on our Discord is a better place for that.

**Comment by IkeVoodoo** [comment]
@kennytv The issue is very much a paper issue, for simply switching out the jar to a spigot jar (latest from BuildTools) the issue resolved itself.

**Comment by mfnalex** [comment]
How is it not a paper issue when
1. It only happens on Paper, while on Spigot it works fine
2. The first class in the stacktrace is a PaperMC class
?

**Comment by kennytv** [comment]
Internals are not API. Again, if you want to use internals, you need to actually understand what you're going into (or in this case, basic Java).
