### ISSUE TITLE
#8849

### ISSUE THREAD

**Issue by IkeVoodoo** [PaperSpigot/Paper#8850]
### Expected behavior

Issue should've been resolved as a bug by paper, since

1. The issue is only reproducible on Paper
2. The first line of the stack trace is from a paper package (io.papermc)

### Observed/Actual behavior

Issue was closed as Paper issues are apparently not paper's problem

### Steps/models to reproduce

1. Go to https://github.com
2. Log-In or Sign Up
3. Go to https://github.com/PaperMC/Paper/issues/new
4. Open an issue detailing an error
5. Wait until the issue gets closed as not a Paper issue

### Plugin and Datapack List

None

### Paper version

Stone Paper

**Comment by kennytv** [comment]
Please refrain from opening more issues on this. If you want help, join our Discord.
