### ISSUE TITLE
/timings report

### ISSUE THREAD

**Issue by Draghonir** [PaperSpigot/Paper#8852]
### Stack trace

https://pastes.dev/C7JDdyAXEc

### Plugin and Datapack List

<img width="635" alt="Capture d’écran 2023-02-15 210954" src="https://user-images.githubusercontent.com/107469643/219141791-7e804e58-63f4-4b18-ab15-fbe85ce88aeb.png">

### Actions to reproduce (if known)

/timings report doing crash server kick everyone and restart

### Paper version

Papermc #399

**Comment by electronicboy** [comment]
stuff like this is often down to something modifying the jar unexpectedly, i.e. attempting to start a copy of paper in the background when paper is already running; outside of that, unless there's more info further up in the logs, can't really say; Oshi blew up loading somehow

**Comment by Draghonir** [comment]
I think i got corrump in library, 

Is there a way to repair the library?
