### ISSUE TITLE
java.lang.ThreadDeath

### ISSUE THREAD

**Issue by ImYenil** [PaperSpigot/Paper#8869]
### Expected behavior

It is happening when opening the server

### Observed/Actual behavior

It is happening when opening the server

### Steps/models to reproduce

X

### Plugin and Datapack List

X

### Paper version

paper 1.19.3 build 406

### Other

console log: https://pastebin.com/qruVRV4C

**Comment by electronicboy** [comment]
need to see the *full* log, if that's the full log, eer...

**Comment by ImYenil** [comment]
> need to see the _full_ log, if that's the full log, eer...

It's full logs

**Comment by electronicboy** [comment]
That is pretty much impossible to be your full latest.log file
Theres nothing here for us to work off, suggest using the discord for support

**Comment by ImYenil** [comment]
> That is pretty much impossible to be your full latest.log file Theres nothing here for us to work off, suggest using the discord for support

https://pastebin.com/NjwBYjVA
