### ISSUE TITLE
Paper breaks AsyncWorldEdit

### ISSUE THREAD

**Issue by Bobcat00** [PaperSpigot/Paper#8870]
### Expected behavior

I expect plugins that worked with build 404 to continue working in build 406.

### Observed/Actual behavior

Log file errors: https://pastebin.com/FrGgyVws

### Steps/models to reproduce

Start the server with Paper 406 and WorldEdit/AsyncWorldEdit.

### Plugin and Datapack List

Plugins (44): ActionBarAPI, AltDetector, AsyncWorldEdit, AsyncWorldEdit-ActionBarAPI, AutoBot, BetterSeen, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, FarmLimiter, FreedomChat, GriefPrevention, GriefPreventionBlockedCommands, ImageMaps, IronDoors, LimitDrops, LuckPerms, MemCheck, MinecartCollisions, MobArena, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, NoCheatPlus, Orebfuscator, PlotSquared, PlotWelcome, Prism, ProtocolLib, PwnFilter, SignURLs, SilkSpawners, SilkSpawnersShopAddon, TabListPing, Vault, ViaBackwards, ViaRewind, ViaVersion, ViaVersionStatus, WallClock, WorldEdit, WorldGuard, xInventories

### Paper version

This server is running Paper version git-Paper-406 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 7baf427)

### Other

ActionBarAPI 1.5.4a
AsyncWorldEdit-ActionBarAPI 3.9.4
AsyncWorldEdit 3.9.4
WorldEdit 7.2.13+6283-46576cc
WorldGuard 7.0.7+216b061

**Comment by Owen1212055** [comment]
Yeah no, what this is doing is 100% not supported. It is injecting a fake plugin into the plugin system.

https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEdit-Utils/src/main/java/org/primesoft/asyncworldedit/utils/ClassLoaderHelper.java

This is obviously not supported, as it uses reflection first of all. This will be up to the plugin author to manage.
