### ISSUE TITLE
Unsafe method to get a block state network ID

### ISSUE THREAD

**Issue by Camotoy** [PaperSpigot/Paper#8905]
### Is your feature request related to a problem?

One of the hurdles we have at Geyser is retrieving block state network IDs from the server. We want to use the server to get this data, so we don't have to cache every chunk for ourselves. However, the missing link is that the server has no exposure for the integer network ID of any given block state.

### Describe the solution you'd like.

Preferably, a method in UnsafeValues to grab the network ID of a given block state would indicate that the method is not for normal use, while ensuring some form of long-term usage for plugins that want to use the method.

### Describe alternatives you've considered.

Currently we accomplish this through one of three tactics:
- Reflection (could break in the future; isn't as performant)
- NMS (NMS)
- Using BlockData#getAsString and performing a reverse lookup with an internal list of block states (a lot of unnecesary hoops)

### Other

As much as I'd want to jump on a PR to shove a method into UnsafeValues, *maybe* it should be made more generic for other level objects attached to a network/registry ID?

**Comment by kennytv** [comment]
For this it is usually advised to use internals with the userdev gradle plugin, as you wouldn't be able to use unsafevalues on lower versions anyways.
