### ISSUE TITLE
Update folder stopping plugins from updating and loading

### ISSUE THREAD

**Issue by OakLoaf** [PaperSpigot/Paper#8915]
### Expected behavior

Plugins in the update folder will replace those in the plugins folder and then load correctly

### Observed/Actual behavior

When I start my server all plugins that are trying to be loaded from the update folder will fail to update, with the error message: `The process cannot access the file because it is being used by another process`
These plugins will also fail to load.

### Steps/models to reproduce

Run a server with any amount of plugins in, put a plugin that is in your plugins folder into your update folder, run the server.

### Plugin and Datapack List

I have tried this on a fresh server with a single plugin, I have tried this with a range of plugins all of which show the same behaviour.

### Paper version

I tested this out on multiple versions and found that the issue started happening in version 405, it did not happen in 404 or before.

### Other

I am using Windows 10 if that is helpful

**Comment by CoolDCB** [comment]
> Same #8879

Ahh, didn't spot that, I'll go ahead and close this then
