### ISSUE TITLE
Config option to stop server if plugins failed to load

### ISSUE THREAD

**Issue by Astralchroma** [PaperSpigot/Paper#8916]
### Is your feature request related to a problem?

If a critical plugin fails to load, such as a claim protection plugin, but the server continues to start anyway and allows players to join this would put the server in a state where players are able to do things they otherwise wouldn't

### Describe the solution you'd like.

A "required-plugins" config option which has a list of plugin names which the server will stop in the event they fail to load
Additionally it would be nice to just specify "*" to require that all plugins load

### Describe alternatives you've considered.

I have attempted to put together a PR for this but I have ran into issues with the config not yet being available during paper plugin bootstrapping, if someone wants to help with this, that would be great

**Comment by XanderWander** [comment]
Is this only during startup, what in the case that a plugin is unloaded by plugman for example, or doesn't load after a reload?

**Comment by Peter-Crawley** [comment]
both reloading and plugman are already unsupported so it doesnt matter
regardless the server would still stop if the plugins fail to load regardless of why that plugin was loaded

**Comment by Brokkonaut** [comment]
I would prefer to have this for all plugins by default, maybe with some startup option as opt-out or so

**Comment by SlimeDog** [comment]
We manage this with [RequiredPlugins](https://www.spigotmc.org/resources/67281/).

**Comment by electronicboy** [comment]
and if that plugin somehow happen chance blows up?
afaik, this is something that aikar has in his emc fork that he wanted to port over given that it's useful for ensuring that important stuff loads; while yea, you could have a plugin that implements this, it's not 100% fool proof
