### ISSUE TITLE
Map, Block deleting it self

### ISSUE THREAD

**Issue by MsEDok** [PaperSpigot/Paper#8922]
### Expected behavior

Map stay the same and nothing happening

### Observed/Actual behavior

https://streamable.com/tql0sm

### Steps/models to reproduce

Generate everything new on paper and tp to worldborder and fly along outside the border 

### Plugin and Datapack List

Server Plugins (0)

### Paper version

This server is running Paper version git-Paper-425 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: ad3e1bc)

**Comment by MsEDok** [comment]
> high coords are generally unsupported and asking for weird issues, this looks potentially like a weird high coord + chunk gen derp but can only say so much without a seed, etc

Freshly generated world with paper.
Seed: random (tested multiple time with random seed and the problem still there)
Seem to happening along the ocean floor 

https://streamable.com/lge1k8

**Comment by kennytv** [comment]
Actually hilarious, can reproduce. Probably not much of a high priority though given that it happens outside of border at the very edge of everything, only right where you can't fly into it anymore even in spectator mode
