### ISSUE TITLE
[Suggestion] Ability to disable offline mode warning for bungeecord/velocity servers.

### ISSUE THREAD

**Issue by ItzSave** [PaperSpigot/Paper#8928]
### Is your feature request related to a problem?

This is not related to any issue more or less a quality of life request.

### Describe the solution you'd like.

I'd like the ability to disable the offline mode warning message or have it automatically disable if you enable bungeecord in the spigot.yml or paper configuration file.

### Describe alternatives you've considered.

There are really no alternative messages as the message is sent before any plugins load so there is no way to hide it.

### Other

This is really more or less a complaint about it. It's a very minor but can be annoying at times. Not many people read stuff like that anyways so I don't really think it stops many questions regarding it.

**Comment by mja00** [comment]
The main use of the message currently is to tell when a server is connected to a proxy, hence why Velocity is now mentioned in the message when enabled, so removing it completely would make it hard to tell when someone is using a proxy, therefore masking issues that may be caused by one.

**Comment by ItzSave** [comment]
> The main use of the message currently is to tell when a server is connected to a proxy, hence why Velocity is now mentioned in the message when enabled, so removing it completely would make it hard to tell when someone is using a proxy, therefore masking issues that may be caused by one.

This is something I had not considered honestly but perhaps some other type of notice could be put in place instead of a warning message? Something just saying server is in offline mode with bungeecord enabled?

**Comment by MiniDigger** [comment]
the warning still has a purpose since the setup needs to be configured correctly to be secure
