### ISSUE TITLE
1.12 Original Jar Download Failure

### ISSUE THREAD

**Issue by CameronMunroe** [PaperSpigot/Paper#8929]
### Expected behavior

Have PaperMC download the original jar.

### Observed/Actual behavior

Downloading original jar...
Error downloading original jar
java.io.IOException: Server returned HTTP response code: 403 for URL: https://s3.amazonaws.com/Minecraft.Download/versions/1.12/minecraft_server.1.12.jar

### Steps/models to reproduce

Start up a fresh build of paperMC running version 1.12. 

### Plugin and Datapack List

N/A

### Paper version

1.12

### Other

We have a couple of options IMO.

* Remove the build from the API / Release since it is currently broken.
* Forward the download request to a cached copy.

**Comment by Machine-Maker** [comment]
1.12 is unsupported. You can download the jar yourself and put it inside the cache folder.
