### ISSUE TITLE
Statistic Statistic.MINE_BLOCK is not incremented when drops are turned off via BlockBreakEvent#setDropItems(false)

### ISSUE THREAD

**Issue by CatalysmRL** [PaperSpigot/Paper#8931]
### Expected behavior

The MINE_BLOCK statistic should be incremented regardless of whether it drops items or not

### Observed/Actual behavior

The statistic is not incremented when drops are turned off for the block.

### Steps/models to reproduce

I created a simple plugin that turns off drops on BlockBreakEvents and messages the player their current MINE_BLOCK statistic

### Plugin and Datapack List

Plugins: Only the custom made one described as above to test the behaviour
Datapacks: vanilla, bukkit

### Paper version

This server is running Paper version git-Paper-431 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: e574412)
You are running the latest version
Previous version: git-Paper-327 (MC: 1.19.3)

### Other

The statistic is also not incremented in creative mode (where also blocks do not drop items upon breaking them). Not sure if this is intended behaviour or also subject to be patched.

**Comment by lynxplay** [comment]
Replicable and caused by https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/nms-patches/net/minecraft/server/level/PlayerInteractManager.patch#245

It seems intentional.
A fix seems a bit bleh, as the method `Block#playerDestroy` is an override target by specific block types, hence passing a parameter directly would not work out too nicely.

**Comment by Machine-Maker** [comment]
> It seems intentional.

mm, I don't think its intentional, I think its an unintentional byproduct of an intentional change to allow configuring whether blocks drop or not.

**Comment by lynxplay** [comment]
I mean, that would be a rather aggressive oversight, but oh well :sweat: 
I don't think it should be expected behaviour if that is what my statement made it sound like.
