### ISSUE TITLE
Warns disabler

### ISSUE THREAD

**Issue by Energobro** [PaperSpigot/Paper#8932]
### Is your feature request related to a problem?

Paper has a built-in anti-cheat that gives a lot of warnings to the console

### Describe the solution you'd like.

Add disabling the built-in anti-cheat or at least some of its functions to the paper's config, because seriously, there is not much sense from the built-in anti-cheat, and warnings are pouring into the console. A reasonable solution would be to put in the config the disabling of warnings in the console and the anti-cheat itself or some of its functions

### Describe alternatives you've considered.

-

### Other

![image](https://user-images.githubusercontent.com/61550676/222733763-8d0e34ab-5ab5-4250-a294-c56c18ed5428.png)

**Comment by Warriorrrr** [comment]
Warning messages are logged for good reason, and we'd rather not add a config option that could make debugging harder. If you want to filter out specific lines from your console, it's recommended to use any of the many log filter plugins out there.
