### ISSUE TITLE
Canceling BlockExplodeEvent only cancels the explosion particles

### ISSUE THREAD

**Issue by akdukaan** [PaperSpigot/Paper#8934]
### Expected behavior

The respawn anchor should still be there
Explosion particles should not be seen
Explosion damage should not be dealt

### Observed/Actual behavior

The respawn anchor is gone
Explosion particles are not seen
Explosion damage is dealt

### Steps/models to reproduce

1. Make a plugin that just cancels BlockExplodeEvent and load it into your server
```
public final class ExplosionCanceler extends JavaPlugin implements Listener {

    @Override
    public void onEnable() {
        getServer().getPluginManager().registerEvents(this, this);
    }

    @EventHandler
    public void cancelExplosion(BlockExplodeEvent event) {
        event.setCancelled(true);
    }
}
```
2. Place a respawn anchor in the overworld.
3. Right click on the respawn anchor while holding a glowstone block to charge it.
4. Right click on the respawn anchor with an empty hand to make it explode.

### Plugin and Datapack List

LuckPerms, ExplosionCanceler

### Paper version

1.19.3-431

### Other

Bug exists on Spigot 1.19.3 too

**Comment by Machine-Maker** [comment]
I think this is all "Works as Intended".

The BlockExplodeEvent is only supposed to manage the blocks that will be destroyed as a result of the explosion, not the entity damage. As for the respawn anchor being destroyed, it is deleted before the explosion even starts, so its not broken as a result of the explosion.

You can take a look at the interact event for trying to stop the explosion early, and various entity damage events.

If someone has a compelling argument against that, this can be re-opened.
