### ISSUE TITLE
Armor stand is invulnerable when set invisible

### ISSUE THREAD

**Issue by AnttiMK** [PaperSpigot/Paper#8943]
### Expected behavior

An armor stand to be destroyable regardless of gamemode when it is invisible, but only destroyable in creative mode when it is invulnerable.

### Observed/Actual behavior

Didn't test other cases than these two, but
1. When set invisible, the armor stand is immediately invulnerable to being destroyed, regardless of the player's gamemode
2. When set invisible AND invulnerable, the armor stand is only invulnerable to being destroyed after a server restart (before the restart, the stand can be destroyed in creative mode as expected)

### Steps/models to reproduce

1. Spawn an armor stand and call `setInvisible(true)` -> observe armor stand to be unbreakable in all gamemodes
2. Spawn an armor stand, call `setInvisible(true)` and `setInvulnerable(true)` -> observe armor stand to be unbreakable in survival, but breakable in creative mode
3. Spawn the armor stand as in step 2 and restart the server -> observe armor stand to be unbreakable in all gamemodes

### Plugin and Datapack List

Test plugin to spawn armor stands as described in the steps above:

```java
@Override
public void onEnable() {
    Bukkit.getScheduler().runTaskLater(this, () -> {
        World world = getServer().getWorld("world");
        ArmorStand invisible = world.spawn(new Location(world, 0, 120, 0), ArmorStand.class, CreatureSpawnEvent.SpawnReason.CUSTOM);
        invisible.setAI(false);
        invisible.setGravity(false);
        invisible.setInvisible(true);

        ArmorStand invulnerable = world.spawn(new Location(world, 2, 120, 0), ArmorStand.class, CreatureSpawnEvent.SpawnReason.CUSTOM);
        invulnerable.setAI(false);
        invulnerable.setGravity(false);
        invulnerable.setInvulnerable(true);

        ArmorStand both = world.spawn(new Location(world, 4, 120, 0), ArmorStand.class, CreatureSpawnEvent.SpawnReason.CUSTOM);
        both.setAI(false);
        both.setGravity(false);
        both.setInvisible(true);
        both.setInvulnerable(true);
    }, 20 * 5L);
}
```

### Paper version

This server is running Paper version git-Paper-442 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 5cc78f2)
You are running the latest version

### Other

 If possible, in the future, I'd like there to be an option (eg. `setUnbreakable(boolean)`) to set whether the armor stand can be broken at all, regardless of gamemode (aka. only with `/kill`).

**Comment by Machine-Maker** [comment]
I was messing with this after you brought it up in the discord, and my steps to produce the issue were slightly different. If I spawned an ArmorStand with just `setInvisible(true)` I could break it until I reloaded the server.


Before I fixed the issue, in your example, I could break all 3 armor stands right after they were created. After I relogged, I could only break the non-invisible one.
