### ISSUE TITLE
Circular plugin loading

### ISSUE THREAD

**Issue by Teleriann** [PaperSpigot/Paper#8964]
### Expected behavior

Turn on server with plugins normally.

### Observed/Actual behavior

After starting the plugin, there is just couple of lines of log, and then server shut downs. There is the error: https://pastebin.com/Zv7dQP46

### Steps/models to reproduce

As you can see in log, main plugins that are causing this problem are Multiversecore, CMI, CMIlib and superiorskyblock, when i remove superiorskyblock from plugins folder, server starts just fine.

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/71602218/224692081-ed760c67-b29d-4320-93e6-ce06351e78bb.png)

### Paper version

Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)

### Other

I do not really know what to add, i guess that this is some Paper problem, it is possible that Im just doing something wrong, thanks <3.

**Comment by Brokkonaut** [comment]
It is an error in one of the plugins mentioned in the message, probably SuperiorSkyblock2. They will have to fix it.

Until they have fixed it you can use the server startup option "-Dpaper.useLegacyPluginLoading=true", but this can cause additions problems.

See here: https://docs.papermc.io/paper/reference/paper-plugins#cyclic-plugin-loading
