### ISSUE TITLE
Add ServerLoadEvent w/ LoadType.EARLY_STARTUP

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#8965]
### Is your feature request related to a problem?

Currently I'm trying to add additional worlds similar to vanilla ones, that available before the server will call `enablePlugins(PluginLoadOrder.POSTWORLD)`. 
There's an  `WorldLoadEvent` but it's throws CME if I try to create a new world.
There's an `ServerLoadEvent` but it's called immediately after every plugins was done `onEnable`.

### Describe the solution you'd like.

Just add new `LoadType.EARLY_STARTUP` and `server.getPluginManager().callEvent(new ServerLoadEvent(LoadType.EARLY_STARTUP))` before `server.enablePlugins(PluginLoadOrder.POSTWORLD)`.

So if any custom plugin will call `Server#getWorld(String/NamespacedKey)` in self `onEnable`, for example to check if it's configuration file contains valid/existing world names/ids, `getWorld` will return my custom world too, not the vanilla one only.

### Describe alternatives you've considered.

I don't know how to do this differently. Maybe use data packs w/ custom dimensions instead of API.. They are loaded immediately after main vanilla world — exactly what I'm needed

### Other

It seems to me that you are unlikely to implement this, but if you do, at least in my case it will solve a lot of problems..

**Comment by maestro-denery** [comment]
generally, follow updates on https://docs.papermc.io/paper/dev/getting-started/paper-plugins . Paper plugins add the `PluginBootstrap` class which allows you to load much earlier, (even before the point when the bukkit API isn't initialized) but for now there is no event / listener API for that. (It is in development) I guess you use NMS instead of WorldCreator because you want to add custom dimensions types or something like that? There will be support for that as well at some point.

**Comment by molor** [comment]
> I guess you use NMS instead of WorldCreator because you want to add custom dimensions types or something like that? There will be support for that as well at some point.

No, only Bukkit API and its WorldCreator. Custom dimensions mentioned in "alternatives" — if Paper team don't add any way/method to load/create World immediately after server loads vanilla worlds, I'll have to use CD because there's nothing else left :c

**Comment by molor** [comment]
Wait, calling `createWorld` in WorldLoadEvent no longer throw an CME о:
idk what I'm changed in my code but in the morning the behavior was different

So I'm closing this, but I think having an event that's called _before_ any plugin gets enabled is still a good idea. If some1 interested in it, tell me and I reopen & rewrite this FR.

Sorry for wasting your time
