### ISSUE TITLE
Creative Beehive Drops

### ISSUE THREAD

**Issue by MaybeStrange1** [PaperSpigot/Paper#8968]
### Expected behavior

When I break a beehive in creative it doesn't drop the beehive.

### Observed/Actual behavior

When I broke the beehive it dropped the beehive with the amount of bee's in it.

### Steps/models to reproduce

I found a beehive i let it fill up and have bee's in it then I broke it to be a bully and it dropped bees in it and everything.

### Plugin and Datapack List

Only paper.

### Paper version

2c485d1 aka 1.19.4

**Comment by mja00** [comment]
This happens in vanilla now, so it appears to be intended behavior now.
