### ISSUE TITLE
Paper fails to load plugins with dependencies through API

### ISSUE THREAD

**Issue by MetallicGoat** [PaperSpigot/Paper#8971]
### Expected behavior

When a plugin tries to load another plugin (from some location outside of the plugins folder) the plugin's dependencies should be checked against the plugins that are currently loaded on the server, and be permitted to enable if present.

### Observed/Actual behavior

When a plugin tries to load another plugin (from some location outside of the plugins folder) paper says the dependencies of the plugin being loaded are missing (even if they are not) and fails to enable the plugin. 

### Steps/models to reproduce

1. Create a plugin that can load another plugin from an addons folder
2. Create another plugin that depends on the first plugin
3. Place the second plugin in the first plugins addon folder
4. Load the second plugin from the addons folder (through a command or something) using Bukkit.getPluginManager().loadPlugin(file)
5. You will receive an error like this https://pastebin.com/DLYc6Q6n

### Plugin and Datapack List

- MBedwars (Our plugin)
- ExtraSpectialItems (The plugin being loaded from an addons folder of MBedwars)
- PlaceholderAPI

### Paper version

[23:40:59 INFO]: This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36) You are running the latest version
Previous version: git-Paper-399 (MC: 1.19.3)

### Other

We have been using this API for close to a year now, and was working great until a fairly recent Paper update. I believe the API was broken in Paper's move to their own plugin system, as it works fine on the latest spigot version. Let me know if you would like me to test anything, or need more detailed info. Thanks everyone!

**Comment by electronicboy** [comment]
plugin managers have never been supported, it would be 100% on them to try to coax themselves back into working;

loading plugins dynamically is a weird one, we can't really expose this too well given the entire new lifecycle system;

also, hotswapping is generally the preferred method for development where viable; otherwise, design the server so that it's fast to restart, or reload "properly"; data driving the server is ofc going to have a whole host of caveats on this entire setup, especially as we try to catch up with mojang here.

**Comment by Owen1212055** [comment]
Thanks for bumping this, I’ll try to look into this a bit more here. As the issue in question doesn’t deal with plugman at all.

**Comment by MrEAlderson** [comment]
> plugin managers have never been supported, it would be 100% on them to try to coax themselves back into working;
> 
> loading plugins dynamically is a weird one, we can't really expose this too well given the entire new lifecycle system;
> 
> also, hotswapping is generally the preferred method for development where viable; otherwise, design the server so that it's fast to restart, or reload "properly"; data driving the server is ofc going to have a whole host of caveats on this entire setup, especially as we try to catch up with mojang here.

Plugin loading and unloading is a part of the official Spigot API.

**Comment by electronicboy** [comment]
Unloading is not

**Comment by Owen1212055** [comment]
This has been reopened as the fix has been reverted due to some issues introduced. For those that aren’t using any paper plugins, they can continue to use this build with no issue.

**Comment by tantrum90** [comment]
The same issue appeared again in 1.21

**Comment by MetallicGoat** [comment]
I believe I have noticed it as well. I need to confirm though

**Comment by Owen1212055** [comment]
Stack traces? How are you experiencing this?

**Comment by tantrum90** [comment]
until I switched to 1.21 everything was fine, now i am receiving the same/similar error as before the fix. The plugin that I am using can't load the dependences, and I need to move it directly to the plugin folder.

https://paste.gg/p/anonymous/55efe5617af34aaaae9f598fcc915cb6

**Comment by tantrum90** [comment]
@Owen1212055  is there any way this to be solved again?

**Comment by Owen1212055** [comment]
Can you please send me your jars / the plugins you are trying to load on my discord? Contact me via `owen.zip` 
@tantrum90

**Comment by youge-grass** [comment]
Bumping because it is still not working in 1.21.5 :3
