### ISSUE TITLE
Bedrock issue?

### ISSUE THREAD

**Issue by Oddengineers** [PaperSpigot/Paper#8978]
### Expected behavior

Normal POV with nothing infront of screen

### Observed/Actual behavior

only on bedrock character do i see this image Java character everything is fine
![Bedrockissue](https://user-images.githubusercontent.com/125910938/225428249-6c6066e7-cbfb-4426-878d-6d3b58322873.png)

### Steps/models to reproduce

downloaded experimental [paper-8977.zip](https://nightly.link/PaperMC/Paper/actions/artifacts/600577214.zip) started server joined with Java no issues. Joined with bedrock get the image above

### Plugin and Datapack List

Essentials, EssentialsChat, floodgate, geyser-spigot,geyserupdater, milestonerewards

### Paper version

This server is running Paper version git-Paper-"d44cca7" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: d44cca7 on HEAD)
Error obtaining version information
Previous version: git-Paper-448 (MC: 1.19.3)

**Comment by lynxplay** [comment]
Concerning that paper does not support bedrock this seems very much like a plugin issue..
I'll be closing this for now unless one of the plugin authors involved in creating this is able to track down the issue to a concrete paper server issue.

**Comment by infernostars** [comment]
This is most likely an issue with GeyserMC, not paper. You should report it to them at [their issues page](https://github.com/GeyserMC/Geyser/issues).

**Comment by lynxplay** [comment]
Yea, please talk to them first :sweat_smile: this certainly is not part of the standard vanilla loop that paper provides, so there is not much we can do here without a technical analysis of whatever project/plugin causes/is responsible for this screen in the first place.

**Comment by Oddengineers** [comment]
Understood I've reported it to them just what i saw when i first logged on with the bedrock character thought it might have been related somehow. Thank you for the quick responses though really appreciate it.

**Comment by Oddengineers** [comment]
ended up being a resource/texture pack issue
