### ISSUE TITLE
No event called for hitting / left clicking an interaction entity

### ISSUE THREAD

**Issue by Boy0000** [PaperSpigot/Paper#8980]
### Expected behavior

Would assume either EntityDamageByEntity or PlayerInteractEntityEvent would be called when a player hits an Interaction entity.
Perhaps EntityDamage isnt correct as it isnt damaged, but PlayerInteractEntityEvent makes sense to fire, same way it does for other entities.
Yes the entity is set to be responsive.

### Observed/Actual behavior

Events arent fired

### Steps/models to reproduce

1. Listen to PlayerInteractEntityEvent or similar event
2. Spawn an interaction entity, which is responsive
3. Hit and nothing is fired

### Plugin and Datapack List

- LuckPerms, Oraxen, PlugManX, ProtocolLib

### Paper version

This server is running Paper version git-Paper-"a2918a5" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: a2918a5 on dev/1.19.4)

### Other

PrePlayerAttackEntityEvent is fired, but the above events makes sense to be fired aswell, like they do for other entities.
Atleast when it is not responsive

https://user-images.githubusercontent.com/62521371/225463475-8fb31560-82da-458e-8c05-d544f65aaabe.mp4

**Comment by Machine-Maker** [comment]
[Upstream added](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/cef8bd993373b452866f66c39bc31b95a293570d) the damage event being called for the Interaction entity but it hasn't been pulled in yet. Most of that change is fine, but I disagree with changing the damage source that is applied to the advancement trigger.

**Comment by Boy0000** [comment]
Yeah latest Spigot fixes this. Saw Upstream was now added to the 1.19.4 PR, but yet to test it.
I would assume it works aswell though
