### ISSUE TITLE
Ability to hide tile entity content

### ISSUE THREAD

**Issue by masmc05** [PaperSpigot/Paper#8982]
### Is your feature request related to a problem?

Yes, we want to improve loot tables of vanilla structures, but because player receives full information about the chest, it can see loot from far away, making it very easy to seek good loot and ignore already looted chests

### Describe the solution you'd like.

![image](https://user-images.githubusercontent.com/63639746/225608016-a4d8c8f7-3990-45ea-850e-1b41b5587732.png)
this is a method in BlockEntity, and it can be used to easily add such functionality, hiding vanilla loot table and the items from chest, maybe other data too from other blocks

### Describe alternatives you've considered.

Create a bukkit snapshot of the block using that nbt, and run an event, and allow plugins to modify the data that players will see

**Comment by MiniDigger** [comment]
the patch in question: https://github.com/PaperMC/Paper/blob/master/patches/server/0847-Sanitize-Sent-BlockEntity-NBT.patch#L41
should prolly use a config option under the obfuscation section, just like for item meta

**Comment by Owen1212055** [comment]
Wait a minute... when is this actually the case? Container entities don't send their loot tables over the network under any circumstances.

**Comment by masmc05** [comment]
oh, feels like it, even checked with a mixin that client didn't receive it, sorry that didn't check that before that
```java
@Mixin(ClientboundLevelChunkPacketData.class)
public class PacketMixin {
    @Shadow @Final
    public List<ClientboundLevelChunkPacketData.BlockEntityInfo> blockEntitiesData;

    @Inject(method = "getBlockEntitiesTags", at = @At("HEAD"))
    public void handle(ClientboundLevelChunkPacketData.BlockEntityTagOutput blockEntityTagOutput, int i, int j, CallbackInfo ci) {
        for (var blockEntityInfo : this.blockEntitiesData) {
            if (blockEntityInfo.type == BlockEntityType.CHEST) {
                var nbt = Optional.ofNullable(blockEntityInfo.tag).map(Tag::getAsString).orElse("null");
                Minecraft.getInstance().gui.getChat().addMessage(Component.literal(nbt));
            }
        }

    }
}
```
seems like every check always returns null
