### ISSUE TITLE
1.19.4 summoning a text_display entity writes an error to console but summons it correctly

### ISSUE THREAD

**Issue by Hugo5000** [PaperSpigot/Paper#8984]
### Expected behavior

Not Write an error to console

### Observed/Actual behavior

Writes the following to console when executing the command stated below:

```
[15:51:09 INFO]: hugo5000 issued server command: /summon minecraft:text_display ~ ~ ~ {text:'{"text":"Text"}'}
[15:51:09 ERROR]: Display entityNot a string
[15:51:09 INFO]: [hugo5000: Summoned new Text Display]
```

summons the entity fine, just the error that I am confused about

### Steps/models to reproduce

run the following command:
`/summon minecraft:text_display ~ ~ ~ {text:'{"text":"Text"}'}`

### Plugin and Datapack List

none and none

### Paper version

This server is running Paper version git-Paper-"fe88107" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: fe88107 on dev/1.19.4)
Error obtaining version information
Previous version: git-Paper-413 (MC: 1.19.3)

**Comment by kennytv** [comment]
Can you try this on a vanilla server and create a mojira ticket as well if it happens there? I'm pretty sure that's a vanilla issue - but fixed on Paper now

**Comment by Hugo5000** [comment]
Yes, it seems to be a vanilla issue, I'll open a ticket there then.
