### ISSUE TITLE
entity without saving in the world

### ISSUE THREAD

**Issue by MelonHell** [PaperSpigot/Paper#8989]
### Is your feature request related to a problem?

When creating plugins, you have to use packet entities or delete entities when the server is turned off, which remain when the server is stopped incorrectly

### Describe the solution you'd like.

Ability to spawn entities that will not be saved in the world

### Describe alternatives you've considered.

see "Is your feature request related to a problem?"

**Comment by tal5** [comment]
https://jd.papermc.io/paper/1.19/org/bukkit/entity/Entity.html#setPersistent(boolean)?
