### ISSUE TITLE
[1.19.4] PlayerAdvancementDoneEvent triggered for unlocking recipes

### ISSUE THREAD

**Issue by Vankka** [PaperSpigot/Paper#8994]
### Expected behavior

(This) Event shouldn't be triggered for "unlocking" (discovering?) recipes

### Observed/Actual behavior

PlayerAdvancementDoneEvent is triggered for unlocking recipes

### Steps/models to reproduce

Minimal reproduction plugin:
```
public final class Untitled extends JavaPlugin implements Listener {

    @Override
    public void onEnable() {
        getServer().getPluginManager().registerEvents(this, this);
    }

    @EventHandler
    public void onPlayerAdvancementDone(PlayerAdvancementDoneEvent event) {
        Advancement advancement = event.getAdvancement();
        AdvancementDisplay display = advancement.getDisplay();
        getLogger().info(advancement.getKey().toString());
        getLogger().info(display != null ? display.getTitle() : "display is null");
    }

}
```

outputs;
```
[22:15:02 INFO]: [untitled] minecraft:recipes/tools/stone_shovel
[22:15:02 INFO]: [untitled] display is null
[22:15:02 INFO]: [untitled] minecraft:recipes/building_blocks/cobblestone_slab
[22:15:02 INFO]: [untitled] display is null
[22:15:02 INFO]: [untitled] minecraft:recipes/building_blocks/stone
[22:15:02 INFO]: [untitled] display is null
[22:15:02 INFO]: [untitled] minecraft:recipes/decorations/cobblestone_wall_from_cobblestone_stonecutting
[22:15:02 INFO]: [untitled] display is null
[22:15:02 INFO]: [untitled] minecraft:recipes/building_blocks/cobblestone_stairs
[22:15:02 INFO]: [untitled] display is null
[22:15:02 INFO]: [untitled] minecraft:story/mine_stone
[22:15:02 INFO]: [untitled] Stone Age
```

### Plugin and Datapack List

see above

### Paper version

```
[22:19:36 INFO]: Checking version, please wait...
[22:19:36 INFO]: This server is running Paper version git-Paper-452 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 02bc2ec)
You are running the latest version
Previous version: git-Paper-446 (MC: 1.19.3)
```

### Other

Have **not** tested to see if this happens on Spigot

**Comment by Machine-Maker** [comment]
This is works as intended. Unlocking recipes is done via advancements being completed.

**Comment by JRoy** [comment]
You're just now noticing this because Mojang changed the key for recipes and your code in DiscordSRV is looking for the old key. 

In the future please test your code across multiple versions/review your codebase before assuming its a bug in the server. 

https://github.com/DiscordSRV/DiscordSRV/blob/43c6e75d27fd98c87c379a44c265a0d7ffd24ede/src/main/java/github/scarsz/discordsrv/listeners/PlayerAdvancementDoneListener.java#L72-L76

**Comment by GreemDev** [comment]
Thank you JRoy for showing us where it's wrong in *our* code, we couldn't have possibly found it ourselves

**Comment by JRoy** [comment]
> Thank you JRoy for showing us where it's wrong in _our_ code, we couldn't have possibly found it ourselves

You're the ones who reported it here as if it were a bug, doing no testing or debugging on your own code or even Spigot; So I figured I'd take the whole two minutes it took for me to find that issue and help a fellow plugin developer out. This time my services are free but next time I will charge my regular hourly rate. Wonderful weather we're having!

**Comment by Vankka** [comment]
> Mojang changed the key for recipes 

Seems that the 1.19.4 change logs don't even mention that

> In the future please test your code across multiple versions/review your codebase before assuming its a bug in the server.

Fair point. I just found it really confusing that unlocking recipes is linked to advancements (I didn't even know until now), that along with Paper still being in "experimental" stage led me to believe this might've been a bug caused by the update.

Please disregard GreemDev's behavior, his involvement with the project is limited and I do really wish he hadn't butted in here unnecessarily.

Apologies
