### ISSUE TITLE
Achievement "Uneasy Alliance" not unlocking with non-standard overworld

### ISSUE THREAD

**Issue by RaptorInternals** [PaperSpigot/Paper#9010]
### Expected behavior

The "Uneasy Alliance" achievement should unlock and be added to the player's list of completed achievements.

### Observed/Actual behavior

The achievement does not unlock and remains locked, even after fulfilling the requirements.

### Steps/models to reproduce

* Join a server running PaperMC with a non-standard overworld (e.g. a custom world generator or a modded world).
* Play through the game until you reach the point where you can unlock the "Uneasy Alliance" achievement.
* Fulfill the requirements for the achievement (kill a Ghast while it is in the Overworld).

### Plugin and Datapack List

* Multiverse-Core
* Multiverse-Portals
* Multiverse-NetherPortals

### Paper version

This server is running Paper version git-Paper-462 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 83948f6)
You are running the latest version
Previous version: git-Paper-448 (MC: 1.19.3)

### Other

* Other achievements seem to unlock normally on servers with non-standard overworlds.
* The strict-advancement-dimension-check gamerule has been checked and set to false on the affected server.

**Comment by Machine-Maker** [comment]
I really don't like changing this. There is only `overworld`. All other worlds are decided `not` the overworld. No other world has the key `minecraft:overworld` so no other world is the overworld. There might be another world that looks like the overworld, but it only **looks** like it.

**Comment by RaptorInternals** [comment]
While it is true that the `minecraft:overworld` dimension key is only used for the main Overworld dimension, it's important to consider that there are many mods and custom world generators that can create non-standard Overworld-like dimensions. These dimensions may look and function similarly to the main Overworld dimension, but they are still separate dimensions in Minecraft's code.

As a result, players may expect to be able to unlock achievements such as "Uneasy Alliance" in these non-standard Overworld-like dimensions, especially if they have set the `strict-advancement-dimension-check` gamerule to `false`. It can be frustrating for players to encounter a bug where they are unable to unlock an achievement, even if they have completed the requirements in a dimension that functions similarly to the main Overworld.

Furthermore, other advancements and achievements, such as "We Need to go Deeper" or "Free the End", can be earned in non-standard dimensions, even though they require specific biomes or structures that may not naturally generate in those dimensions. This inconsistency can lead to confusion and frustration for players.

Overall, while it may not be strictly necessary to change the behavior of the `strict-advancement-dimension-check` gamerule, it would be a quality-of-life improvement for players to be able to earn achievements in non-standard Overworld-like dimensions if they have fulfilled the requirements.

**Comment by electronicboy** [comment]
"like" is not "is", while mojangs inconsistency on implementing restrictions is somewhat fun, it's not really a justification to break the meaning of things; this is already easily fixable through tweaking the vanilla datapack to mitigate this, which is the only supported solution here

There is very little interest on our side to try to wrangle what a dimension means in datapacks, as that sort of stuff often creates more issues than it solves in the long run, especially if we actually want to strive towards proper datapack support, we can't just arbitrarily break the behavior of the thing
