### ISSUE TITLE
spreadplayers command doesnt spread players

### ISSUE THREAD

**Issue by basweijenberg** [PaperSpigot/Paper#9019]
### Expected behavior

If i use the /spreadplayers command in chat or with a command block it should teleport entities in a given range (for example '/spreadplayers ~ ~ 0 1000 false @a' should spread all player entities in a 1000 block radius)

### Observed/Actual behavior

The command teleports entities to location 0 0 0

### Steps/models to reproduce

using the command '/spreadplayers ~ ~ 0 1000 false @a' or with any other parameters results in the entities teleporting to 0 0 0 always

### Plugin and Datapack List

tested with and without plugins and datapacks results in the same behaviour every time

### Paper version

This server is running Paper version git-Paper-466 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 7af4cd3)
You are running the latest version
Previous version: git-Paper-448 (MC: 1.19.3)

### Other

i first went to the @paper-help channel on discord to confirm this issue with other people and user @pug#1070 also tested and reported the same issue

**Comment by takatalvi** [comment]
This was an issue in CraftBukkit, I reported it to the Spigot team and they just fixed it today. Paper needs to update based on Spigot and it should be fine.

**Comment by Doc94** [comment]
> This was an issue in CraftBukkit, I reported it to the Spigot team and they just fixed it today. Paper needs to update based on Spigot and it should be fine.

You can wait for https://github.com/PaperMC/Paper/pull/9018

**Comment by takatalvi** [comment]
> 

Thank you!

**Comment by takatalvi** [comment]
> > This was an issue in CraftBukkit, I reported it to the Spigot team and they just fixed it today. Paper needs to update based on Spigot and it should be fine.
> 
> You can wait for #9018

Thank you!
