### ISSUE TITLE
My friend cant load into my falixnodes MC server

### ISSUE THREAD

**Issue by EstherL1ght** [PaperSpigot/Paper#9032]
### Expected behavior

I tried OPing him and whitelisting him but none would work

### Observed/Actual behavior

it gave me this error message 

"[00:55:00] [Server thread/INFO]: Allan0513[/75.81.91.31:54162] logged in with entity id 1264 at (-575.4380739115202, 63.0, -396.32269617630755)"

And the entity ID Varied

### Steps/models to reproduce

.

### Plugin and Datapack List

.

### Paper version

.

### Other

.

**Comment by electronicboy** [comment]
There is no information to go off here, the discord is also the better place for support
