### ISSUE TITLE
Player#hideEntity/Player#hidePlayer and Entity#setVisibleByDefault on player should allow not removing player's name from player list

### ISSUE THREAD

**Issue by GliczDev** [PaperSpigot/Paper#9045]
### Is your feature request related to a problem?

I think it'd be very useful for only hiding players without removing them from player list

### Describe the solution you'd like.

Something like:
`player.hideEntity(plugin, player2, false)`
`player.hidePlayer(plugin, player2, false)`
`player2.setVisibleByDefault(false, false)`

### Describe alternatives you've considered.

\-

**Comment by KabanFriends** [comment]
I needed this, it's quite annoying that bukkit API has extra packet sending to hide the player from tablist

**Comment by J-ak-e** [comment]
I very much agree with the above mentioned suggestions.

**Comment by JMBoy01** [comment]
Hi, I made some changes to the code and I think it works, but idk until i can test it... maybe anyone who can help?

**Comment by XxGoldenbluexX** [comment]
I expected [Player.hideEntity()](https://jd.papermc.io/paper/1.20/org/bukkit/entity/Player.html#hideEntity(org.bukkit.plugin.Plugin,org.bukkit.entity.Entity)) to keep player listed in tab. I tried working around this using [Player.listPlayer()](https://jd.papermc.io/paper/1.20/org/bukkit/entity/Player.html#listPlayer(org.bukkit.entity.Player)), however you can't list hidden players. (I am getting IllegalStateException("Player cannot see other player")). If someone have a workaround until this is worked on, i would be glad to take it.

**Comment by Hy3z** [comment]
> I expected [Player.hideEntity()](https://jd.papermc.io/paper/1.20/org/bukkit/entity/Player.html#hideEntity(org.bukkit.plugin.Plugin,org.bukkit.entity.Entity)) to keep player listed in tab. I tried working around this using [Player.listPlayer()](https://jd.papermc.io/paper/1.20/org/bukkit/entity/Player.html#listPlayer(org.bukkit.entity.Player)), however you can't list hidden players. (I am getting IllegalStateException("Player cannot see other player")). If someone have a workaround until this is worked on, i would be glad to take it.

Hi, would @XxGoldenbluexX idea be aligned with the principle (mentionned by @Machine-Maker) that ```hidePlayer``` behavior should not be changed  ?  Do some plugins really use ```Player.hideEntity``` expecting it to hide a player from the tab list? If so, then would adding another function ```Player.hidePlayer(Plugin plugin, Player player,  boolean hideFromList)```  (while keeping the original ```Player.hidePlayer(Plugin plugin, Player player)```)  do the job?
