### ISSUE TITLE
1.19.4 translation text fallback feature does not work

### ISSUE THREAD

**Issue by KabanFriends** [PaperSpigot/Paper#9049]
### Expected behavior

The translation text should fallback to the text set in the `fallback` field, when the translation for the key is missing

### Observed/Actual behavior

The server shows the translation key, and does not fallback.

### Steps/models to reproduce

1. Run `/tellraw @a {"translate":"some.translation.key","fallback":"Hello"}`
2. See the text in chat

### Plugin and Datapack List

None

### Paper version

```
This server is running Paper version git-Paper-471 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: d5abb94)
```

**Comment by KabanFriends** [comment]
Looks like fallback is already implemented in adventure (like 2 days ago)
This is probably just a problem of waiting for new adventure version

**Comment by lynxplay** [comment]
Yea the translator does not forward the fallback, fixed in https://github.com/KyoriPowered/adventure/commit/fbe91f9477030914797fa1f0d6197865780238ed 👍 
Indeed a "wait for new adventure release" issue, but a good tracking issue nonetheless.
