### ISSUE TITLE
Beehives from tree growth don't contain any bees

### ISSUE THREAD

**Issue by Warriorrrr** [PaperSpigot/Paper#9051]
### Expected behavior

The hive to contain bees, a hive should have a minimum of at least 2 bees (see the BeehiveDecorator class)

Vanilla:
![image](https://user-images.githubusercontent.com/50800980/227789610-fe8c9d74-753f-4c4d-9fff-da5214915ff5.png)

### Observed/Actual behavior

No bees in these trees

![image](https://user-images.githubusercontent.com/50800980/227789086-4abe0e5d-2af3-4cd4-88bd-7614a7626437.png)

### Steps/models to reproduce

1) Place down any flower
2) Place an oak sapling adjacent to this flower
3) Use bone meal on the sapling until it becomes a tree
4) Repeat steps 2 & 3 until you get lucky and get a tree with a hive
5) Run /data get block and observe that there aren't any bees in the hive

### Plugin and Datapack List

No plugins/datapacks, fresh server

### Paper version

This server is running Paper version git-Paper-471 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: d5abb94)
You are running the latest version

### Other

While searching for existing issues I found #2893 which seems to be the same issue as this, but that was fixed by upstream 3 years ago.

https://hub.spigotmc.org/jira/browse/SPIGOT-5537
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/6515ea4957c5ebc8b88e3f7581a8a4dbb55fecb1#src/main/java/org/bukkit/craftbukkit/block/CapturedBlockState.java

**Comment by Machine-Maker** [comment]
I cannot replicate this issue using `/place feature minecraft:fancy_oak_bees` which should place a tree with a beehive 100% of the time. Using the `/data get block <x> <y> <z>` showed
![image](https://user-images.githubusercontent.com/15055071/227793138-4fa9bf20-53cf-42b7-9231-7825c42079dc.png)

It's possible it only happens with non forced generation? Will test further, but if you could test with the command and see what you results are, that would be great.

**Comment by Warriorrrr** [comment]
Placing the tree via that command gives me the same results as you:
![image](https://user-images.githubusercontent.com/50800980/227793575-89f144c7-18af-40e2-96f3-47115c20c735.png)

Also quickly tested oak_bees_005 and that gave me bees too, so it's only non forced generation that's affected here

**Comment by Machine-Maker** [comment]
Confirmed, this is caused by [upstream breaking it here](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/39462a898595280d1a1c6197c2ad66082434ba80#nms-patches/net/minecraft/world/item/ItemStack.patch).
