### ISSUE TITLE
ClickType#isShiftClick returns true for ClickType.CONTROL_DROP (Ctrl + Q)

### ISSUE THREAD

**Issue by YeanlingAugur** [PaperSpigot/Paper#9054]
### Expected behavior

Expectation is that `isShiftClick` returns `false` for the Ctrl + Q InventoryClickEvent as it is not, in fact, a Shift Click.

### Observed/Actual behavior

`isShiftClick` returns `true` for the Ctrl + Q InventoryClickEvent.

### Steps/models to reproduce

View the result of InventoryClickEvent#getClick#isShiftClick when the Ctrl + Q action is performed to drop a whole stack. It will return true.

### Plugin and Datapack List

N / A

### Paper version

This server is running Paper version git-Paper-473 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: fbf74ba)
You are running the latest version

**Comment by electronicboy** [comment]
thus would probably be best directed upstream given that this has been the behavior for 10 years more or less

**Comment by Machine-Maker** [comment]
Resolved by bf92f3e4db44d17dab7411b0a5474a6b2fabc3b5
