### ISSUE TITLE
Comparator don't get updated as it should. 

### ISSUE THREAD

**Issue by Jake-CJ** [PaperSpigot/Paper#9066]
### Expected behavior

https://youtu.be/BudRgJyLPlA

This is a player online detector powered by cat. 

### Observed/Actual behavior

The comparator don't get updated as it should be in the vedio

### Steps/models to reproduce

Tame a cat and leash it to top of a slab on top of a chest, put a hopper below it doesn't matter where the hopper pointing. Put 5 dummy item into the hopper and put 1 dummy item which is different from the 5 you put in the hopper. Lastly put a comparator reading the input from chest. By  standing up the cat you should get a signal from the comparator. 

### Plugin and Datapack List

GeyserMC and floodgate

### Paper version

This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)

### Other

![2023-03-28_212304](https://user-images.githubusercontent.com/90301656/228352033-e24a6911-400c-46f7-8eb5-1cfc280213cf.png)

**Comment by Machine-Maker** [comment]
Confirmed. This has to do with the hopper optimizations patch.

**Comment by Jake-CJ** [comment]
Anyway to deal with this issue?
