### ISSUE TITLE
NBT Tag mix after restart 

### ISSUE THREAD

**Issue by Bagietas** [PaperSpigot/Paper#9078]
### Expected behavior

When restarting server nbt tag should remain the same, but it's not.

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/121623949/229212629-c2d47f5d-c1a2-47f4-8e52-2144158653c9.png)

The first one is before restart and second one is after.

### Steps/models to reproduce

**1. Set nbt tag to item with color** 
**2. Restart server**
**3. Check NBT Tags**

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/121623949/229213646-b381aadf-e5b8-4c6c-9678-8bf7753d7fa2.png)
![image](https://user-images.githubusercontent.com/121623949/229213859-8b696d99-7275-4b57-a4ec-243f5a3b312e.png)
It's my own plugin, code for setting name attached.

### Paper version

[21:39:33 INFO]: This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version

**Comment by electronicboy** [comment]
This is 100% expected due to the code to migrate legacy text stored in items to valid components. stop creating invalid components (i.e. using legacy colors)
