### ISSUE TITLE
cant combine items with anvil

### ISSUE THREAD

**Issue by KeksNino** [PaperSpigot/Paper#9092]
### Expected behavior

the item combined with the enchantment

### Observed/Actual behavior

with gamemode 1 you could open the anvil. i also tested it with * permissions and it didnt work

### Steps/models to reproduce

combine item with an enchantment or repair

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/87879013/229569826-c5fa0c39-afdc-4d9f-a1d8-a4cb87f19856.png)
but there was also another guy that had the same issue without any plugins: https://github.com/PaperMC/Paper/issues/869#issue-253491464

### Paper version

git-paper-307 (mc: 1.19.2) (Implementing API version 1.19.2-R0-1-SNAPSHOT) (Git: 476ef25)

**Comment by Doc94** [comment]
Hi, a few things about...
- You test this in lasts versions (previous versions not has support)
- What items are you try to combine?
- You test this with not plugins?

The most important is the first about the server version.

**Comment by pop4959** [comment]
Can't reproduce this on the latest version of Paper without plugins installed. Items combine as expected, retaining enchantments from the anvil.
