### ISSUE TITLE
Version update from 1.19.3 to 1.19.4

### ISSUE THREAD

**Issue by Faeren0327** [PaperSpigot/Paper#9101]
### Stack trace

```
Hy,

I have a docker container which updates always to the latest version.
Last time it tried to update from 1.19.3 to 1.19.4 it crashed because of world update error.
Then I reverted the version to 1.19.3 and tried to startup my server and I got some chunk version mismatch error. (see details attached)

What should I do? How can I repair my world?

Thank you!

Best regards,
Mate


```
[mateminecraft.csv](https://github.com/PaperMC/Paper/files/11161618/mateminecraft.csv)

### Plugin and Datapack List

No plugin

### Paper version

1.19.3

### Other

2023-04-05T17:17:53.616345578Z,stdout,[17:17:53 WARN]: java.lang.RuntimeException: Server attempted to load chunk saved with newer version of minecraft! 3337 > 3218

**Comment by electronicboy** [comment]
If you see the pins in the paper-help channel, there is a way to bypass that check, but the only option that is supported is to restore a backup.
