### ISSUE TITLE
Team colors don't show when player sends message

### ISSUE THREAD

**Issue by mouro001** [PaperSpigot/Paper#9105]
### Expected behavior

The chat should display the team color on the name of the player
![image](https://user-images.githubusercontent.com/8522686/230730399-23a84de5-6ed7-48c6-b89c-eae669ecea5f.png)

### Observed/Actual behavior

It doesnt:
![image](https://user-images.githubusercontent.com/8522686/230730298-06570016-6308-4103-b28a-d023690befa1.png)
It shows the right color when a player joins the server and on the tab menu, but it doesn't on chat messages.

### Steps/models to reproduce

1. Install Paper for 1.19.4 (tried with build 499)
2. Create a team `/team add test`
3. Join the team `/team join test`
4. Apply the color to the team `/team modify test color aqua`
5. Open TAB menu to see changes
6. Send message in chat

### Plugin and Datapack List

> datapack list
[16:53:05 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[16:53:05 INFO]: There are no more data packs available
> plugins
[16:53:14 INFO]: Server Plugins (0):

![image](https://user-images.githubusercontent.com/8522686/230730749-48308a6a-5d44-4506-941f-e57900ebbe0b.png)

### Paper version

> version
[16:54:16 INFO]: Checking version, please wait...
[16:54:17 INFO]: This server is running Paper version git-Paper-499 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 29b17a8)
You are running the latest version

### Other

This was found after a player reported not seeing the colors after using the Vanilla Tweaks data pack "Name Colors".
It also was reported before: #5307 and it was marked as resolved.

**Comment by e-im** [comment]
Enable `use-vanilla-scoreboard-name-coloring` in the paper world config.
