### ISSUE TITLE
Removed player entities can run commands 

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#9109]
### Expected behavior

Commands should not be processed for removed player entitites

### Observed/Actual behavior

Commands are processed for removed player entitites

### Steps/models to reproduce

In "handleChatCommand" method of "ServerGamePacketListenerImpl" the "tryHandleChat" method is checked to see if the player is allowed to run the command:
` if (this.player.isRemoved() || this.player.getChatVisibility() == ChatVisiblity.HIDDEN) { // CraftBukkit - dead men tell no tales`

however, this tryHandleChat method is ran on the netty threads, then it runs:
```
 this.server.submit(() -> {
       this.performChatCommand(packet, (LastSeenMessages) optional.get());
       this.detectRateSpam("/" + packet.command()); // Spigot
});
```

The problem here is apparent, if the player logs out after the "tryHandleChat" check but before the next tick, 
once the command is processed, they can run a command as an offline player.

The implications of this are very bad and real, there are several dupes relating to this, notably with https://www.spigotmc.org/resources/auctionhouse.61836/.
Any plugin that has commands which remove items from a player's inventory is vulnerable, simply spamming said command with the right timing will get you kicked for spam while running the command at the same time, see video: https://youtu.be/ylELA8i8Kbc

There is already a plugin fixing this, which uses the following, but this problem should really be fixed upstream:
```
 @EventHandler(priority = EventPriority.HIGHEST)
    public void onSendCommand(PlayerCommandPreprocessEvent e) {
        if (!e.getPlayer().isOnline() || e.getPlayer().isDead()) {
            e.setCancelled(true);
        }
    }
```

### Plugin and Datapack List

N/A

### Paper version

Affects paper 1.19.4 [501] (latest)

**Comment by lag-packet** [comment]
Has anyone taken a look or has this been fixed yet in recent versions?
