### ISSUE TITLE
1.19: No longer possible to edit ClientboundSystemChatPacket's component

### ISSUE THREAD

**Issue by kangarko** [PaperSpigot/Paper#9128]
### Expected behavior

In the previous Minecraft version, one could use libraries such as ProtocoLib to edit the chat message packet before it's being sent.

### Observed/Actual behavior

ClientboundSystemChatPacket has now a "private final" adventure content field. Since both this field, and Adventure's approach is immutable (calling content(String) method on the TextComponent field found in the packet's class produces a new copy instead of setting the field), there is no way (or I am wrong?) to edit the packet's chat message content before it's sent.

My proposal is simply removing the final modifier from the adventure content field in the ClientboundSystemChatPacket class. If I am wrong, please let me know a way for developers using packets to modify the content of a system chat message.

### Steps/models to reproduce

N/A

### Plugin and Datapack List

ProtocolLib

### Paper version

Paper build 510

**Comment by Camotoy** [comment]
Reflection can certainly still be used to modify `private` `final` fields in Java 17.

Example: https://github.com/ViaVersion/ViaVersion/blob/master/bungee/src/main/java/com/viaversion/viaversion/bungee/platform/BungeeViaInjector.java

**Comment by emilyy-dev** [comment]
Reflectively setting fields is illegal if the owning class is a record, which is the case of the system chat packet, attempting to do so will throw an IllegalAccessException.

**Comment by electronicboy** [comment]
the class is a record, meaning that fields are implicitly final; We're not going to convert those classes back into a normal class, best advice will be to just replace the packet with your own

**Comment by kangarko** [comment]
Thanks for the clarification. I don't have experience replacing packets like this. If there is a reference or an example somewhere I'd appreciate you forward me to it, but I understand if this is out of your scope of support.
