### ISSUE TITLE
Players hidden using player.hidePlayer are still visibile in autocomplete for  vanilla commands

### ISSUE THREAD

**Issue by Maxi130** [PaperSpigot/Paper#9130]
### Expected behavior

That the player is not shown as an option for players to select.
![2023-04-13_15 40 40](https://user-images.githubusercontent.com/130671511/231777068-6e05225b-1ad6-40ce-8542-f61fa24706a0.png)

### Observed/Actual behavior

The player is seen in autocomplete even when hidden.
![2023-04-13_15 32 24](https://user-images.githubusercontent.com/130671511/231774999-2ce687a7-b26c-4af4-9d3a-96b0ae616b2b.png)
![2023-04-13_15 32 44](https://user-images.githubusercontent.com/130671511/231775011-98a75681-b871-486b-bf20-be6981de0aee.png)

### Steps/models to reproduce

1. Hide the player using player.hidePlayer
2. Open the chat and type /minecraft:w (or /w).

### Plugin and Datapack List

Plugins:
- My plugin (not public currently)

Datapacks:
- None

### Paper version

[15:35:11 INFO]: This server is running Paper version git-Paper-510 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bd35d60)
You are running the latest version
Previous version: git-Paper-"e574412" (MC: 1.19.3)

### Other

According to electronicboy#8869 it should be based of the tab list. (Where the user is hidden)
According to phoenix616 (or whoever controls the webhook) it is most likely due to a change in the Minecraft command system.

**Comment by Maxi130** [comment]
> If im not wrong is the normal behaviour, the hide is mostly for hide visual the entity (because now is hideEntity)

It also hides it from the tab list and people in the discord told me it was a bug.

**Comment by Maxi130** [comment]
Accidentally closed it, I'm new to GitHub.

**Comment by Maxi130** [comment]
> > If im not wrong is the normal behaviour, the hide is mostly for hide visual the entity (because now is hideEntity)
> 
> It also hides it from the tab list and people in the discord told me it was a bug.

I also forgot to mention, it also hides it when autocompleting in chat, without using a command.

**Comment by Maxi130** [comment]
> If im not wrong is the normal behaviour, the hide is mostly for hide visual the entity (because now is hideEntity)

I just looked into the code and it uses hideEntity as you said, but shouldn't hidden Entities also be hidden from auto complete (when looking at them, it autocompletes)

The code also specificfly hides the player from the player list. (Sends a PlayerInfoRemovePacket)
See unregisterEntity

For me it just looks like a missing detail, that the command auto complete doesn't check the hiddenEntities list.
![image](https://github.com/PaperMC/Paper/assets/130671511/9f9b1552-d5bf-4087-8f18-b1da328b70ed)

**Comment by Machine-Maker** [comment]
You can fix this by turning off `fix-target-selector-tag-completion` in `paper-global.yml` until a fix is implemented.

**Comment by Maxi130** [comment]
> You can fix this by turning off `fix-target-selector-tag-completion` in `paper-global.yml` until a fix is implemented.

Thanks, I will try this tomorrow.
How does this solution work?

**Comment by Machine-Maker** [comment]
> it disables a fix for a vanilla bug where entity selector type tags don't properly provide suggestions. You can see a better description [here](https://github.com/PaperMC/Paper/pull/9245#issuecomment-1572667397).

**Comment by Maxi130** [comment]
> > How does this solution work?
> 
> It disables a fix for a vanilla bug where entity selector type tags don't properly provide suggestions. You can see a better description [here](https://github.com/PaperMC/Paper/pull/9245#issuecomment-1572667397).

Ah that makes sense.

**Comment by Maxi130** [comment]
I updated my server to the latest stable version and it doesn't seem to be fixed.
`[10:29:38 INFO]: This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
You are running the latest version
Previous version: git-Paper-510 (MC: 1.19.4)`
Is that normal?

**Comment by MiniDigger** [comment]
it was fixed in 1.20
