### ISSUE TITLE
Paper does not consider fallbacks of translatable Components for server logs

### ISSUE THREAD

**Issue by dawon** [PaperSpigot/Paper#9133]
### Expected behavior

When translation for a specific translation key is not available, but there is a fallback, it should be used in server logs.

### Observed/Actual behavior

The translation key is displayed instead of the fallback message

### Steps/models to reproduce

The simplest way to reproduce is just a plugin with an event

```java
    @EventHandler
    public void onPlayerQuit(PlayerQuitEvent e) {
        e.quitMessage(Component.translatable("test.quit.message", "Bye %s!"));
    }
```

When the player quits, the console should contain: "Bye John!" but there is "test.quit.message" instead.

### Plugin and Datapack List

only the test plugin

### Paper version

This server is running Paper version git-Paper-511 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 8d040fa)
You are running the latest version

### Other

Adventure-side fix should be already included in Paper, but there probably needs to be fixed something in Paper as well. see KyoriPowered/adventure#895

**Comment by dawon** [comment]
> The paper flattener found in PaperAdventure pre-maps translatable components and hence needs updating ^
> Should be a rather simple fix to include the fallback in case no mapping can be found in the servers language or a registered global translator.

Aha! Will do the PR, thank you for pointing me in the right direction, was having a hard time finding the right spot!

**Comment by LemonCaramel** [comment]
> > The paper flattener found in PaperAdventure pre-maps translatable components and hence needs updating ^
> > Should be a rather simple fix to include the fallback in case no mapping can be found in the servers language or a registered global translator.
> 
> Aha! Will do the PR, thank you for pointing me in the right direction, was having a hard time finding the right spot!

If you don't mind, can I open a pull request?

**Comment by dawon** [comment]
![image](https://user-images.githubusercontent.com/7982418/232020016-a7d26d71-29eb-4515-903e-c79e7ab175c5.png)
 Apparently, we came up with almost the exact same solutions independently, I was just testing it whether it works and it seems so, so if you want, go ahead.

**Comment by LemonCaramel** [comment]
> ![image](https://user-images.githubusercontent.com/7982418/232020016-a7d26d71-29eb-4515-903e-c79e7ab175c5.png) Apparently, we came up with almost the exact same solutions independently, I was just testing it whether it works and it seems so, so if you want, go ahead.

Oh, you've already finished the work. It would be nice if you could open it.

**Comment by dawon** [comment]
> > ![image](https://user-images.githubusercontent.com/7982418/232020016-a7d26d71-29eb-4515-903e-c79e7ab175c5.png) Apparently, we came up with almost the exact same solutions independently, I was just testing it whether it works and it seems so, so if you want, go ahead.
> 
> Oh, you've already finished the work. It would be nice if you could open it.

Thank you! :-) Created #9134
