### ISSUE TITLE
Switch my old world to 1.19.4 

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#9145]
### Timings or Profile link

https://pastes.dev/2CNGt7lv9W

### Description of issue

 ok step 1. creating world 1.12.2 and make this command:
![image](https://user-images.githubusercontent.com/108226177/232432525-69d16c10-3ae5-47ab-ac39-d4e77e255751.png)

 step 2. deleting all (not world) and install paper 1.19.4

 step 3. join - got error https://pastes.dev/2CNGt7lv9W
 and it can down tps

So maybe you can help me and update you paper to get fix. using -forceupgrade 

### Plugin and Datapack List

.

### Server config files

.

### Paper version

.

**Comment by electronicboy** [comment]
This is a vanilla issue as mojang doesn't clean up advancements they remove

**Comment by F3F5** [comment]
so yeah, how i can fix?

**Comment by electronicboy** [comment]
There's nothing to fix, removed advancements will be removed; if you wanna
suppress the messages, use a log filter; otherwise, you'd need to convince
mojang to handle this properly

**Comment by Regomy** [comment]
yes yes add it very strange suggestion!!!

**Comment by F3F5** [comment]
> 

ok thanks so much,
it's a pity that it also affects the tps

**Comment by olijeffers0n** [comment]
I doubt this affects the TPS that much. Either way, this is not a Paper problem
