### ISSUE TITLE
Datapacks nt working

### ISSUE THREAD

**Issue by Nicolol1234** [PaperSpigot/Paper#9153]
### Expected behavior

That the datapack (https://www.planetminecraft.com/data-pack/sanguine-5603305/ and https://www.planetminecraft.com/data-pack/manic-5338125/) don't work, or partially

When I run "/function sanguine:commands/blood_moonstart", it should start a bloodmoon, but nothing happen

Note: i set ```save-empty-scoreboard-teams```, ```allow-non-player-entities-on-scoreboards``` and
 ```use-vanilla-world-scoreboard-name-coloring``` to true

### Observed/Actual behavior

nothing happen

### Steps/models to reproduce

Install those datapacks
Wait for a bloodmoon or to be insane (with manic)

### Plugin and Datapack List

Plugins:
- Spark

Datapacks:
[vanilla (built-in)], [file/bukkit (world)], [file/manic-datapack (1).zip (world)], [file/sanguine-datapack (1).zip (world)], [bundle (feature)], [update_1_20 (feature)]

### Paper version

This server is running Paper version git-Paper-514 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: dd216c1)
You are running the latest version

**Comment by NonSwag** [comment]
Can't reproduce.
I got the same behavior on my paper server as in single player.
But I realized you have a typo in your command
> /function sanguine:commands/blood_moonstart

It should be: `/function sanguine:commands/blood_moon/start`
maybe that's the problem.

**Comment by Owen1212055** [comment]
See the comment linked above
