### ISSUE TITLE
[Paper Plugins] Allow downloaded maven dependencies to access plugins URLClassLoader

### ISSUE THREAD

**Issue by JakeNijssen** [PaperSpigot/Paper#9157]
### Is your feature request related to a problem?

I have been trying out the new Paper plugin system for a bit now, and I like it. However, I have stumbled against a couple of significant issues. My diagnosis for my issues (Which I shall list here), is that the plugin can access the library classloader, but not vice versa. Here's what made me think that:

- Flyway, many developers who manage SQL databases with migration shall know this dependency, now when last I tried adding my own FlywayLoggerFactory(To make it prevent spam in the console), I just did this:
`Flyway flyway = Flyway.configure().loggers("io.quicksource.worldwar.db.FlywayLoggerFactory")
                    .dataSource(String.format("jdbc:postgresql://%s/%s", config.host(), config.database()),
                            config.username(), config.password()).load();
            flyway.migrate();`
now here is the problem, Flyway won't be able to locate my class, and thus throws a ClassNotFoundException.
- Cloud Command Framework, a bit simpler example, when using the `@CommandContainer` annotation alongside the annotation processor, CCF will store the path to your classes using command containers inside META-INF in the plugin jar. However when using `AnnotationParser::parseContainers` it will never find those, as it doesn't recognize the plugin jar.

I think I can go way deeper into this, but for the new dependency system to be a proper solution in comparison with ye old shading, I believe these are some issues that need ironing out.

### Describe the solution you'd like.

A way for the dynamically loaded libraries to have access to extending plugin classloaders. 

### Describe alternatives you've considered.

Shading obviously, but thats the whole concept this new Paper plugin feature tries to avoid.

**Comment by electronicboy** [comment]
not really fixable as then you'd have the plugin classloader accessing the library classloader which would access the plugin classloader, and now you have a loop. What you generally can do is set the current context classloader for the thread, or ask the developers of that library to expose a means to set the classloader to fetch resources from

**Comment by Owen1212055** [comment]
See Cat's comment, in general it's better for APIs to have a way to pass classloaders when needed. As in general, causing a loop like this is not ideal.. and in general we want to maintain a sort of isolation if possible.
