### ISSUE TITLE
https://github.com/PaperMC/Paper/pull/9129 Causes unkown/missing dependency errors

### ISSUE THREAD

**Issue by nickhid** [PaperSpigot/Paper#9164]
### Expected behavior

Expected Paper to identify and load dependencies correctly.

### Observed/Actual behavior

When attempting to start a server with EssentialsX along with EssentialsX modules, Paper is unable to identify EssentialsX as a satisfied dependency. 
Issue persists on dev and stable branch of EssentialsX.

`23.04 00:26:35 [Server] [ERROR] [LegacyPluginLoadingStrategy] Could not load 'plugins/EssentialsXSpawn-2.20.0-dev+56-fd49b70.jar' in folder 'plugins'
23.04 00:26:35 [Server] [INFO] org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [Essentials]. Please download and install these plugins to run 'EssentialsSpawn v2.20.0-dev+56-fd49b70'.
23.04 00:26:35 [Server] [INFO] at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:115) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at io.papermc.paper.plugin.entrypoint.strategy.LegacyPluginLoadingStrategy.loadProviders(LegacyPluginLoadingStrategy.java:200) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at java.lang.Thread.run(Thread.java:831) ~[?:?]
23.04 00:26:35 [Server] [ERROR] [LegacyPluginLoadingStrategy] Could not load 'plugins/EssentialsXChat-2.20.0-dev+56-fd49b70.jar' in folder 'plugins'
23.04 00:26:35 [Server] [INFO] org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [Essentials]. Please download and install these plugins to run 'EssentialsChat v2.20.0-dev+56-fd49b70'.
23.04 00:26:35 [Server] [INFO] at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:115) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at io.papermc.paper.plugin.entrypoint.strategy.LegacyPluginLoadingStrategy.loadProviders(LegacyPluginLoadingStrategy.java:200) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at java.lang.Thread.run(Thread.java:831) ~[?:?]
23.04 00:26:35 [Server] [ERROR] [LegacyPluginLoadingStrategy] Could not load 'plugins/EssentialsXAntiBuild-2.20.0-dev+56-fd49b70.jar' in folder 'plugins'
23.04 00:26:35 [Server] [INFO] org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [Essentials]. Please download and install these plugins to run 'EssentialsAntiBuild v2.20.0-dev+56-fd49b70'.
23.04 00:26:35 [Server] [INFO] at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:115) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at io.papermc.paper.plugin.entrypoint.strategy.LegacyPluginLoadingStrategy.loadProviders(LegacyPluginLoadingStrategy.java:200) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]
23.04 00:26:35 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-"8e3009e"]`

### Steps/models to reproduce

Update to Paper-517
Install EssentialsX
Install any additional EssentialsX module
Observe issue

### Plugin and Datapack List

ClearLag, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsSpawn, floodgate, Geyser-Spigot, GriefPrevention, LuckPerms, Shopkeepers, Vault, WorldEdit

Issue persists on a reduced server with just Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsSpawn installed.

### Paper version

Issue observed on git-Paper-517

Issue resolved by reverting to git-Paper-516

**Comment by Owen1212055** [comment]
Please provide a /paper dumpplugins

**Comment by Owen1212055** [comment]
Oh, and can you try please using the modern plugin loader (remove the legacy loading strategy flag).

**Comment by nickhid** [comment]
@Owen1212055 Looks like removing the Legacy flag resolves the issue. Thanks!

Definitely good to call this breakage out. (I know https://docs.papermc.io/paper/reference/paper-plugins specifically says Legacy loading may not be supported in the future, but it seems some Hosting services have this flag on by default and even gated behind customer service tickets).

**Comment by Owen1212055** [comment]
Yeah, I was a bit worried if hosts has this pre-enabled. 

This level of breakage isn't intended, I would recommend trying to see if this issue is resolved with the paper jar located at [this PR](https://github.com/PaperMC/Paper/pull/9165).

**Comment by nickhid** [comment]
No error with paper-paperclip-1.19.4-R0.1-SNAPSHOT-reobf and -Dpaper.useLegacyPluginLoading=true
