### ISSUE TITLE
PathFinder#stopPathFinding does nothing

### ISSUE THREAD

**Issue by KillerCreeper112** [PaperSpigot/Paper#9170]
### Expected behavior

When using mob.getPathFinder().stopPathFinding(), it should, as the description states:
"Instructs the Entity to stop trying to navigate to its current desired location"

### Observed/Actual behavior

The mob still path finds to the end point of its current path.

### Steps/models to reproduce

`PolarBear bear = world.spawn(location, PolarBear.class);
        new BukkitRunnable(){
            @Override
            public void run() {
                bear.getPathfinder().stopPathfinding();
            }
        }.runTaskTimer(this, 0L, 20L);`

### Plugin and Datapack List

- CustomPlugin

### Paper version

This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)
You are running the latest version
Previous version: git-Paper-447 (MC: 1.19.3)

### Other

In the example, I am using a polar bear but I have also tested zombies, husks, and skeletons.

**Comment by electronicboy** [comment]
Are you sure that the thing didn't restart navigating?

**Comment by Owen1212055** [comment]
Cannot reproduce, ensure that the entity isn't trying to recalculate its path. The code given in the reproduction steps works fine for me.

Please reopen however if you are still able to reproduce this issue. 😄
