### ISSUE TITLE
Entities dont get teleported via gateway when riding in minecart

### ISSUE THREAD

**Issue by TureBentzin** [PaperSpigot/Paper#9172]
### Expected behavior

Like Vanilla the gateway should work normal:

Video (provided by Jokni): https://cdn.discordapp.com/attachments/289587909051416579/1101915124022919238/2023-04-29_19-56-25.mp4 (expected behavior)

### Observed/Actual behavior

Video (provided by Jokni): https://cdn.discordapp.com/attachments/289587909051416579/1101915053629915146/2023-04-29_19-51-03.mp4 - observed behavior

### Steps/models to reproduce

Follow the video for reproduction on vanilla and on paper.

Alternative:

1. Go into the "end"
2. place or locate a gateway
3. Force an entity (riding in a cart) into the gateway

### Plugin and Datapack List

We could not figure out any correlation between datapacks or plugins (tests where done with and **without** them) 

### Paper version

git-Paper-521 (MC: 1.19.4)

### Other

Thanks to "Icen" for reporting the issue

**Comment by lynxplay** [comment]
Presumably related to #6658

**Comment by lynxplay** [comment]
Would have to re-evaluate if https://github.com/PaperMC/Paper/issues/3297 still applies.
Beyond that, this seems intended.

**Comment by TizoCraft** [comment]
just had the same issue would be great to get a fix for it!

**Comment by brwnie** [comment]
In testing I've found that if I remove server patch:

0409-Ensure-safe-gateway-teleport.patch

Results in entities in minecarts getting teleported through end gateways just fine

**Comment by TureBentzin** [comment]
@kickash32 - author of the patch

That might be caused by the cards wrongfully indicating in the `canChangeDimension` that they can't use the portal. I'm on mobile right now so its hard to debug this method right now.

**Comment by brwnie** [comment]
Looks like that function (canChangeDimensions) checks if the entity is not a passenger and is not a vehicle

**Comment by TureBentzin** [comment]
Then that would be the "issue". We could remove the check but I expect this to have consequences. If we decide that ditching the vehicle check would be ok I will pr this in.

**Comment by brwnie** [comment]
I tried reproducing: I placed a cat (the entity) on my head, crawled to the end gateway using trapdoors, and was able to /home succesfully using EssentialsX. 

>     Place an entity on your head.
>     Enter an end gateway using trapdoors.
>     Try a command like /home from EssentialsX and watch it fail.

After /home the cat was no longer on my head, but going through the end gateway again it was there pre /home.

Video: https://www.youtube.com/watch?v=ilSD0W3tAjY

Some background on my interest in this issue: As part of one of the advancements of Minecraft 'How did we get here' it involves having every effect applied at once. 

Using an end gateway in vanilla way makes it much easier to get a Shulker close to the end portal to eventually get in the overworld, with this not working it may mean a 1000+ block journey or a fustrating experience getting the shulker into the gateway without it being a passenger

**Comment by lynxplay** [comment]
Initial draft of a potential fix available at #9521.
I have enabled a build job for the PR so you can grab the paper plugin if you want to try the fix.

This should properly allow entities to teleport via end gateways if they are used as vehicles.

**Comment by brwnie** [comment]
> Initial draft of a potential fix available at #9521. I have enabled a build job for the PR so you can grab the paper plugin if you want to try the fix.
> 
> This should properly allow entities to teleport via end gateways if they are used as vehicles.

Thanks @lynxplay, I tried the fix and Shulkers in Minecarts go through fine now.

I did observe with this that if a player is in a Minecart, it almost 'softlocks' them before entering the gateway. If the player quits and rejoins they respawn through the gateway OK. If a player is not in a Minecart (crawls through) they go through OK.

**Comment by lynxplay** [comment]
iirc this is a vanilla bug ? At least I can replicate that in vanilla.

**Comment by Xavom** [comment]
I did some testing and found that this bug came about in version **git-Paper-449 (MC: 1.19.4)**.
This bug did not exist in version **git-Paper-448 (MC: 1.19.3)**.

**Comment by PeterL07590759** [comment]
> In testing I've found that if I remove server patch:
> 
> 0409-Ensure-safe-gateway-teleport.patch
> 
> Results in entities in minecarts getting teleported through end gateways just fine

How to remove server patch?

**Comment by Nacioszeczek** [comment]
> > In testing I've found that if I remove server patch:
> > 0409-Ensure-safe-gateway-teleport.patch
> > Results in entities in minecarts getting teleported through end gateways just fine
> 
> How to remove server patch?

Please use our [Discord](https://discord.gg/papermc) or [forums](https://forums.papermc.io/forums/) for support and not the GitHub issues.

**Comment by LoaiDev** [comment]
Any updates on this issue? it seems that the fix pull request was closed and the issue discussion just died. I can confirm that this is still an issue and not the vanilla behaviour.

**Comment by lynxplay** [comment]
After rebasing the PR, the minecart deadlock seems fine now :+1:
I'll reopen the PR for testing.

**Comment by lynxplay** [comment]
Merged the fix in :+1: 
If any of you run into the previously mentioned deadlock that existed in 1.18, please open an issue!
We have not been able to replicate that, so believe the patch is safe to merge as there is also no indiciation for that deadlock to appear again under the new chunk system.
