### ISSUE TITLE
Ghasts Teleporting through Nether Portals cause significantly more lag than other Entities.

### ISSUE THREAD

**Issue by PoiiohPoii** [PaperSpigot/Paper#9173]
### Timings or Profile link

https://spark.lucko.me/ooh5SoyreL

### Description of issue

Ghasts that teleport through a nether portal cause significant amounts of lag.
Normally this does not occur under default paper settings.

### Plugin and Datapack List

Spark

### Server config files

(https://paste.gg/p/anonymous/775877fe088745df8d268f29027ac95d)

### Paper version

This server is running Paper version git-Paper-521 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bcec5b1)
You are running the latest version
Previous version: git-Pufferfish-"f3011e9" (MC: 1.19.4)

### Other

Seems to scale significantly as the server is put under more load.

Video of the lagspike happening on a superflat world, with an MSPT near 0: https://streamable.com/bszsx5

This also seems to be specific to ghasts. Cows, creepers & other mobs cause nearly no lag

**Comment by MCMDEV** [comment]
Same here

**Comment by Teslicek** [comment]
Same here. Causing 400ms lag spikes with ghast farms.

**Comment by welove69** [comment]
I'm also having this issue,1.20.1

**Comment by CodeByCam** [comment]
Hey @PoiiohPoii, can you please provide a new spark report?

**Comment by lynxplay** [comment]
We'd certainly be happy for more spark reports yea 👍

**Comment by welove69** [comment]
https://github.com/PaperMC/Paper/issues/9585#issuecomment-1690702638
This archive seems to replicate this phenomenon as well
Reaching its destination in the archive, the ghost returns to the Overworld from the Nether
The system I use is Windows 11 Pro

**Comment by welove69** [comment]
https://github.com/PaperMC/Paper/assets/135555687/3245f6c0-32fa-4294-b536-2db4fca621ec

https://spark.lucko.me/QlUlf6Jzcj

Paper's Nether portal itself seems to cause a large lag, and the ghast generation speed is slower, so it will constantly unload and load the portal, a veritable lag machine.
But sometimes after the server on my other machine restarts, this lag disappears, it may be which thread is wrong, from time to time, I don't know, but I can be sure that spigot will not have such a big lag, because I have tried many times, can not be reproduced, may be because I use Windows 11, maybe I should not use this system to set up the server.
Just my assumption, probably not helpful with this, but I did get stuck with this problem for a few months.

**Comment by welove69** [comment]
After I switched to Windows 11 to Ubuntu 22.3, the lag spike disappeared, and I was also confused, it will only happen on Windows 11

**Comment by GoldenEdit** [comment]
https://spark.lucko.me/w27OFfDZub - On Linux

**Comment by CodeByCam** [comment]
Thanks for the info @GoldenEdit. Are you able to provide a zip of a world (or part of) with the farm you have please?

**Comment by GoldenEdit** [comment]
> Thanks for the info @GoldenEdit. We're aware of this issue and will hopefully be able to improve the performance around VoxelShape. Are you able to provide a zip of a world (or part of) with the farm you have please?

When reproducing this I was only running a quick test by spawning Ghasts directly into the portal.

I may be able to provide you with a WorldEdit schematic of one of the farms on a server I manage, let me know if you would like that. 

This issue happens anytime a ghast enters a nether portal, so any farm that uses an overworld killing chamber causes lag to servers.

**Comment by CodeByCam** [comment]
> > Thanks for the info @GoldenEdit. We're aware of this issue and will hopefully be able to improve the performance around VoxelShape. Are you able to provide a zip of a world (or part of) with the farm you have please?
> 
> When reproducing this I was only running a quick test by spawning Ghasts directly into the portal.
> 
> I may be able to provide you with a WorldEdit schematic of one of the farms on a server I manage, let me know if you would like that.
> 
> This issue happens anytime a ghast enters a nether portal, so any farm that uses an overworld killing chamber causes lag to servers.

Yeah that's fair enough, and I've been able to reproduce it with just the spawning into a portal too, but actually having a farm would be handy to test it. A schematic for the Overworld & Nether side would be fine too!

**Comment by Warriorrrr** [comment]
Can no longer reproduce the large lag spike in 1.20.2 thanks to leaf's collision optimisations
