### ISSUE TITLE
Ender Dragon death noise plays everywhere

### ISSUE THREAD

**Issue by Mobmaker55** [PaperSpigot/Paper#9182]
### Expected behavior

When the Ender Dragon is killed, only those on the main End island should hear the death noise.

### Observed/Actual behavior

When the Ender Dragon is killed, the (rather loud) death noise is played to everyone in any dimension, which is rather unsettling to those who are doing other things in the Overworld and did not know someone was fighting an Ender Dragon.

### Steps/models to reproduce

1) have someone in the End attacking an Ender Dragon
2) have someone in another dimension (e.g. the Overworld)
3) The person in the End kills the Ender Dragon
4) Every single person in the server hears the death noise

### Plugin and Datapack List

None
![image](https://user-images.githubusercontent.com/45888585/236110419-c9c26304-b9bf-45c4-aa68-db4f5d847d5f.png)

### Paper version

This server is running Paper version git-Paper-524 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 9846d0d)
You are running the latest version
![image](https://user-images.githubusercontent.com/45888585/236110448-c269cac4-66a4-4c26-b50c-73e98ca84e4c.png)

### Other

This is consistent across two different Paper servers running different versions.

**Comment by electronicboy** [comment]
This has a fun history; Spigot made it global, and then paper made it per world, and then made it global again if a radius isn't set

Given that it looks like vanilla has set on making it per world, we should probably just drop our patch which allows it to be global again; n the meantime, you can set a radius in spigot.yml for the dragon death radius

**Comment by Machine-Maker** [comment]
I believe this is addressed by https://github.com/PaperMC/Paper/pull/8727

**Comment by masmc05** [comment]
why not just `/gamerule globalSoundEvents false`?
