### ISSUE TITLE
Make crafts persistent across resource reloads (like plugin load)

### ISSUE THREAD

**Issue by masmc05** [PaperSpigot/Paper#9187]
### Is your feature request related to a problem?

Yes, a plugin load, `/minecraft:reload` (do not confuse with `/reload` or `/bukkit:reload`), `/datapack enable`, `/datapack disable` etc triggers a resource reload, which removes all plugin recipes

Right now we also need a resource reload because we dynamically add commands with our custom scripts, which triggers a resource reload (otherwise registered commands to command map won't apply to players)

This may also be an issue, idk, not sure

### Describe the solution you'd like.

Save bukkit recipes, and reapply them after each recipe reload

### Describe alternatives you've considered.

Nag every author of plugins to reapply recipes after resource reloads, which no plugin supports (didn't see any)

**Comment by masmc05** [comment]
oh, there was even an event where you wrote about this, seems like a duplicate of an old issue i couldn't find

**Comment by Machine-Maker** [comment]
Yeah, use the [ServerResourcesReloadedEvent](https://jd.papermc.io/paper/1.19/io/papermc/paper/event/server/ServerResourcesReloadedEvent.html) instead. We want recipes to be the same as vanilla, and they are also reset on a `/minecraft:reload`.
