### ISSUE TITLE
Method for Sculk Catalyst spreading Sculk

### ISSUE THREAD

**Issue by Romindous** [PaperSpigot/Paper#9198]
### Is your feature request related to a problem?

As far as I've looked and asked, there isn't yet an API method for making a sculk catalyst spread sculk. Usually this happens when a mob dies and tries to drop XP, which is handled by a NMS method (attached).
![nms](https://user-images.githubusercontent.com/64203160/236980707-40a57462-4eca-4d77-a4e6-3906f2e9d9fd.png)

### Describe the solution you'd like.

It would be nice to have a method in the SculkCatalyst block data class that would take in a location and experience points, and attampt to spread sculk from a catalyst. Something like SculkCatalyst#growSculk(Location at, int exp);

### Describe alternatives you've considered.

You can probably do it the boring way, by picking random blocks in an area and seeing if the material matches Tag.SCULK_REPLACEABLE, and replacing afterwards, but that's not gonna look natural, is it?

### Other

![image](https://user-images.githubusercontent.com/64203160/236981631-2fbe5fdf-fd49-4102-9330-2bfefb55c72e.png)

**Comment by Romindous** [comment]
Yep, go for it, Im updating my code for 1.20 rn, so im prob not gonna get to this in a while xD

**Comment by sumitdethe27** [comment]
I want to work on this
