### ISSUE TITLE
Memory leak when using Bukkit#unloadWorld with save=false

### ISSUE THREAD

**Issue by janrabek** [PaperSpigot/Paper#9199]
### Timings or Profile link

You don't see any info abouit that leak in any timings.

### Description of issue

When unloading worlds using Bukkit#unloadWorld with save=false they get removed from CraftServer#worlds but they still retain in the memory (especially ChunkTaskSchedulers):
<img width="770" alt="Bildschirmfoto 2023-05-09 um 13 05 15" src="https://github.com/PaperMC/Paper/assets/20094418/fc3c37fc-cc75-478b-8616-adc0a3e99f3d">

In this screenshot you see there are officially only 6 worlds loaded:
<img width="850" alt="Bildschirmfoto 2023-05-09 um 13 06 00" src="https://github.com/PaperMC/Paper/assets/20094418/b2211949-3aec-4324-b33e-a387d47fd851">

This is a massive issue, as you don't know this through timings but only through testing.

Also one guy in the Spigot forum had the same issue:
https://www.spigotmc.org/threads/how-to-fix-memory-leak-unload-world.588677/

### Plugin and Datapack List

Doesn't matter

### Server config files

Doesn't matter

### Paper version

<img width="570" alt="Bildschirmfoto 2023-05-09 um 13 09 02" src="https://github.com/PaperMC/Paper/assets/20094418/79ac512d-7764-4e9d-934d-7a987aec5acd">

**Comment by qlow** [comment]
We observed that this issue only happened after updating to 1.19.*

**Comment by lynxplay** [comment]
I am having trouble replicating this.
The test code
```java
@EventHandler
public void on(final PlayerDropItemEvent event) {
    event.setCancelled(true);
    if (test == null) {
        test = Bukkit.createWorld(WorldCreator.name("test").keepSpawnLoaded(TriState.TRUE));
        event.getPlayer().sendMessage(Component.text("Loaded custom world `test`"));
        event.getPlayer().teleport(test.getSpawnLocation());
    } else {
        event.getPlayer().teleport(Bukkit.getWorld(NamespacedKey.minecraft("overworld")).getSpawnLocation());
        Bukkit.unloadWorld(test, false);
        event.getPlayer().sendMessage(Component.text("Unloaded custom world `test`"));
    }
}
```

was used to load and unload the world named "test" numerous times, while 
```bash
jmap -dump:live,file=./server.hprof "$(jcmd | grep 'craftbukkit.Main' | cut -d' ' -f1)"
```
was used to create the heap dump. Notably this command only collects live objects, e.g. those that are still referenced.
I end up with exactly three `ChunkTaskScheduler` instances as expected.

I might be missing something tho, so this issue needs further triage.
It would be great if you can replicate this a) on latest and b) ensure that only live objects are captured as the GC may not have collected the now unloaded world at your point of capture.

Beyond that, spigot references for this issue are rather useless, paper rewrites pretty much the entire system there :sweat_smile:

**Comment by Kryniowesegryderiusz** [comment]
> Hey, I'm very sorry, it was a memory leak of FastAsyncWorldEdit. The save parameter didn't fix it, I only believed this was the issue because of the Spigot thread.
> 
> Best regards Jan

Im sorry to dig up this thread, but could you maybe do some follow up? I have similar issue, but updating FAWE doesnt seem to help :c

**Comment by OneLiteFeather** [comment]
@Jan can you provide more information about the plugins you were using with fawe on https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/2278 ? That might help as well.

**Comment by OneLiteFeather** [comment]
> @OneLiteFeather wrong @jan.

My bad, it doesn't really differenciate between on the phone.
