### ISSUE TITLE
`Block#setBiome` is inconsistent

### ISSUE THREAD

**Issue by SirSalad** [PaperSpigot/Paper#9204]
### Expected behavior

It's expected that every `Block#setBiome` call is reflected on the server

### Observed/Actual behavior

Inconsistent behavior in what's set

### Steps/models to reproduce

Test plugin: [https://github.com/SirSalad/set-biome-issue/blob/main/src/main/java/io/github/sirsalad/setbiomeissue/SetBiomeIssuePlugin.java](https://github.com/SirSalad/set-biome-issue/blob/main/src/main/java/io/github/sirsalad/setbiomeissue/SetBiomeIssuePlugin.java)
Note: Relog or send a `ClientboundLevelChunkWithLightPacket` to see the reflected changes

Result of `/test TAIGA`:
Note: It is not shown in the image, but the border is inconsistent across all y levels

![image](https://github.com/PaperMC/Paper/assets/73862843/d8c544fe-ab48-4345-8b1e-99e75dbeeebf)

### Plugin and Datapack List

```
> pl
[10:08:57 INFO]: Server Plugins (1):
[10:08:57 INFO]: Bukkit Plugins:
[10:08:57 INFO]:  - set-biome-issue
```

### Paper version

```
> ver
[10:08:56 INFO]: Checking version, please wait...
[10:08:57 INFO]: This server is running Paper version git-Paper-528 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: efd47e3)
You are running the latest version
Previous version: git-Paper-522 (MC: 1.19.4)
```

**Comment by jpenilla** [comment]
This isn't a bug, it's just how biomes work, see the doc for getComputedBiome for a little more info

**Comment by Leguan16** [comment]
Also, the heck is that on the right?

**Comment by lynxplay** [comment]
Closing this, see jmp's comment :+1:
