### ISSUE TITLE
ChunkTaskScheduler: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by kohlerpop1** [PaperSpigot/Paper#9215]
### Stack trace

```
https://paste.gg/p/anonymous/b439cdfde82543d0af8d1b1dd97f4ccf
```

### Plugin and Datapack List

[14:50:10 INFO]:  Plugins (30): AntiPopup, ArmorStandTools, BungeeTabListPlus, CMI, CMIEInjector, CMILib, Chunky, Citizens, DecentHolograms, DiscordSRV, EpicHeads, EtheraCentral, FastAsyncWorldEdit, Kuai, LibsDisguises, LuckPerms, MVdWPlaceholderAPI, ModelEngine, Multiverse-Core, MythicMobs, PlaceholderAPI, ProtocolLib, Schemy, ServerUtils, Settlements, SideQuests, Vault, VoidGen, VoxelSniper and spark

### Actions to reproduce (if known)

Shut down server and it does this!
I synchronously access a non-empty queue to run tasks for a specific world on shutdown. But the error of this is still not coming from my plugin so I figured I should report it!

### Paper version

1.19.4-534

**Comment by electronicboy** [comment]
We can’t accept stack traces from software that isn’t ours, I’d also want to know if you have any data packs or not

**Comment by kohlerpop1** [comment]
We have no datapacks. We are a plugins only server. I know that the software running the code is not yours, but the stacktrace contains no reference to my plugin so I just wanted to make sure that there was also not a trivial unknown bug on the paper side.

**Comment by electronicboy** [comment]
stacktraces from software that isn't ours is useless because we don't know what all has changed between us and them

All I can generally say is that that behavior from the fastutil collection is pretty much the normal "something is messing with me concurrently"

**Comment by kohlerpop1** [comment]
> stacktraces from software that isn't ours is useless because we don't know what all has changed between us and them
> 
> All I can generally say is that that behavior from the fastutil collection is pretty much the normal "something is messing with me concurrently"

Ok. Thanks for letting me know!
