### ISSUE TITLE
§ Section Sign Exception

### ISSUE THREAD

**Issue by TiffApps** [PaperSpigot/Paper#9236]
### Expected behavior

I coded a recursive `/tpall` command that uses MiniMessage to add a click component to ask for confirmation to the sender first (code below).
Paper should allow the use of the section sign `§` instead of throwing an exception, with maybe a warning at most (in some config/properties: `warn-about-legacy-usage-of-section-sign=true` by default, with whatever better name someone will come up with).

### Observed/Actual behavior

The exception:
![image](https://github.com/PaperMC/Paper/assets/33839996/42e2ef7d-3f65-41de-820e-afb1e302bc51)

### Steps/models to reproduce

Reproduction:

```java
  /**
   * Builds a string that can be parsed by MiniMessage to add a run command click component to a piece of text.
   *
   * @param command The command to run.
   * @param text    The text that should have a click component added to it.
   * @return String that can be parsed by MiniMessage
   */
  public static String buildClickCommand(String command, String text) {
    String clickText = "<click:run_command:/%s>" + text + "<reset>";
    return clickText.formatted(command.replace("/", ""));
  }
  
@Override
  public void handle(CommandSenderAdapter sender, String[] args) {
    final PaperCommandSenderAdapter paperSender = (PaperCommandSenderAdapter) sender;
    final Player player = ((Player) paperSender.getCommandSender());
    final int len = args.length;
    final String keyword = "§confirm";

    if (len >= 1) {
      if (args[len - 1].equalsIgnoreCase(keyword)) {
        for (Player target : Bukkit.getOnlinePlayers()) {
          target.teleport(player.getLocation());
        }
        return;
      }
    }
    sendMessage(sender,
        buildClickCommand("tpall " + String.join(" ", args) + " " + keyword, "Are you sure?")
        );
  }
```

### Plugin and Datapack List

LuckPerms, Utilities (custom Essentials), PluginCore (custom)

### Paper version

This server is running Paper version git-Paper-540 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: f9f9079)
You are running the latest version
Previous version: git-Paper-527 (MC: 1.19.4)

### Other

**_NB:_** This is only about the wrong exception thrown when `§` is used outside of its legacy color code usage, not about how I could do an anti-player filter more efficiently etc... I don't really care as it's not that much of an issue with the very few people who would have the tpall permission + a modified client to allow typing the section sign + would know this cmd would work with a confirm keyword as well. And it would only need to bypass a simple click.

**Comment by electronicboy** [comment]
This is not an exception thrown by Paper, this is an exception thrown by the serialiser in use (MiniMessage), as you're doing something which is explictly blocked by the serialiser as it's generally deemed bad practice and just creates an inconsistency data wise which mojang, we, and adventure, do not intend to support

if you want to allow legacy characters inside of your own inputs, you'll have to handle that yourself

**Comment by TiffApps** [comment]
Hello @electronicboy, I opened this issue after discussing it with a member of the development team on Discord, @Machine-Maker, who reckoned it is an issue: https://discord.com/channels/289587909051416579/555462289851940864/1113179308941385768.

My bad for opening the issue here and not in MiniMessage though, I didn't know it had its own repo as I thought it was directly part of Paper and Velocity.
I don't understand why would it create an inconsistency  though, as it has nothing to do with color codes, could you explain it to me if it doesn't bother you too much?
We can also continue this conversation on the Discord if you wish: `tiffaa` (new Discord username system, tagless)

**Comment by electronicboy** [comment]
derp; I missed it being part of the run command thing, so, that would be an issue with MM which is part of the adventure repo; but, last I knew, section symbols in commands/chat by the client wil cause a disconenct
