### ISSUE TITLE
Items get removed after dropping fast

### ISSUE THREAD

**Issue by deneonet** [PaperSpigot/Paper#9238]
### Expected behavior

After dropping 36 stacks of dirt fast using STRG+Q, I should get 36 stacks of dirt when picking up.

### Observed/Actual behavior

After dropping 36 stacks of dirt fast using STRG+Q, I only got 19 stacks of dirt when picking up.

### Steps/models to reproduce

https://vimeo.com/831662732?share=copy

### Plugin and Datapack List

No plugins ( Server plugins (0): )

### Paper version

This server is running Paper version git-Paper-540 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: f9f9079)
You are running the latest version
Previous version: git-Paper-527 (MC: 1.19.4)

### Other

Only happens in creative mode and only happens when dropping these items fast.

**Comment by molor** [comment]
iirc this issue is present even in 1.12.2

**Comment by drunderscore** [comment]
I'm 99% sure this is vanilla behavior whilst in creative.

**Comment by Machine-Maker** [comment]
Yes, please confirm that this happens in a non-creative-mode inventory

**Comment by sxngsxm** [comment]
> I'm 99% sure this is vanilla behavior whilst in creative.

I just checked and yes in survival mode it works fine.

**Comment by molor** [comment]
Maybe https://bugs.mojang.com/browse/MC-116618?

**Comment by molor** [comment]
> it's a vanilla bug

There's https://github.com/PaperMC/Paper/blob/master/patches/server/0893-Fix-a-bunch-of-vanilla-bugs.patch
So I think some1 may fix this issue if you reopen it

**Comment by electronicboy** [comment]
It's a client synchronisation issue more or less, it's likely not something that can be reliably patched in the server with how creative mode works (the client is the one mostly in control here)

**Comment by sxngsxm** [comment]
> It's a client synchronisation issue more or less, it's likely not something that can be reliably patched in the server with how creative mode works (the client is the one mostly in control here)

So they need to rework the creative mode to get it fixed?
