### ISSUE TITLE
LivingEntity#setBodyYaw (Paper API) is misleading / lacking information

### ISSUE THREAD

**Issue by KabanFriends** [PaperSpigot/Paper#9247]
### Expected behavior

The API sounds like it can set the body rotation of a living entity at any time.

### Observed/Actual behavior

The API does not seem to be working like I expected in most cases.
The only thing that can change body yaw of a living entity is the spawn entity packet, so it might do something different when calling the API right after spawning one, but I have not tested that yet.

### Steps/models to reproduce

1. Read the API documentation for LivingEntity#setBodyYaw: https://jd.papermc.io/paper/1.19/org/bukkit/entity/LivingEntity.html#setBodyYaw(float)
2. Think how it should work, according to its description

### Plugin and Datapack List

None

### Paper version

This server is running Paper version git-Paper-545 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bacbf86)

### Other

Extra information should be added to the documentation of LivingEntity#setBodyYaw to make it clear what it's actually supposed to do.

**Comment by Malfrador** [comment]
![javaw_ja7EDkopvi](https://github.com/PaperMC/Paper/assets/6106558/53383534-6ac1-4c6b-a1b2-f35434665ca8)
Can't reproduce. Code:
```
 Mob mob= (Mob) player.getTargetEntity(10);
 Bukkit.getServer().getMobGoals().removeAllGoals(mob);
 mob.setBodyYaw(player.getBodyYaw());     
 ```
 
 You need to make sure that the Mob does not have an AI goal that turns it around, that will override the yaw value.
 Entity rotation is an (optional) part of the entity move packet, its not just set on spawn.

**Comment by KabanFriends** [comment]
I see
