### ISSUE TITLE
A dragon cannot teleport through portals and gateways

### ISSUE THREAD

**Issue by fredypawww** [PaperSpigot/Paper#9248]
### Expected behavior

In the vanilla world, a dragon can teleport through portals and gateways. Please fix this mechanic so that the dragon can teleport through the portals and gateways

### Observed/Actual behavior

On paper, the dragon does not teleport through portals and gateways

### Steps/models to reproduce

0:00 - Paper
3:23 - Vanilla
https://youtu.be/ohmC5o5RpRE

### Plugin and Datapack List

Server Plugins (0):

There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
There are no more data packs available

### Paper version

This server is running Paper version git-Paper-545 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bacbf86)
You are running the latest version

### Other

The original video from which I took the idea: https://www.youtube.com/watch?v=g_-_oSr4l_w

**Comment by Machine-Maker** [comment]
The Ender Dragon teleporting via end gateways is a bug confirmed in vanilla, as shown in [this mojira issue](https://bugs.mojang.com/browse/MC-86836). Paper fixes bugs in vanilla gameplay, and as such, this is works-as-intended.
