### ISSUE TITLE
PaperMC Server logo is outdated

### ISSUE THREAD

**Issue by olijeffers0n** [PaperSpigot/Paper#9259]
### Is your feature request related to a problem?

The logo.png file is outdated when compared to current paper branding

### Describe the solution you'd like.

Update the `logo.png` file to match other paper logos

### Describe alternatives you've considered.

N/A

**Comment by NoahvdAa** [comment]
For anyone looking to tackle this, the logo is located in `Paper-Server/src/main/resources/logo.png` and originally added in [this patch](https://github.com/PaperMC/Paper/blob/d8e07590e30e81b855312c6d00b34e8155da0920/patches/server/0572-Improve-ServerGUI.patch#L53), which should be [modified](https://github.com/PaperMC/Paper/blob/d8e07590e30e81b855312c6d00b34e8155da0920/CONTRIBUTING.md#modifying-patches) to include the new logo.

**Comment by Lulu13022002** [comment]
The forum is also affected

**Comment by Bidhan-Poudel** [comment]
Is the problem still present? Is anyone working on resolving it?

**Comment by lynxplay** [comment]
A PR is open here https://github.com/PaperMC/Paper/pull/9264

**Comment by SARINURCAH** [comment]
i waiting for this isue resolved
