### ISSUE TITLE
Deprecate duplicated gliding boost method

### ISSUE THREAD

**Issue by imDaniX** [PaperSpigot/Paper#9260]
### Is your feature request related to a problem?

Currently there's two almost identical methods for giving player a boost while gliding:
Spigot's [`HumanEntity#fireworkBoost(ItemStack)`](https://jd.papermc.io/paper/1.19/org/bukkit/entity/HumanEntity.html#fireworkBoost(org.bukkit.inventory.ItemStack))
Paper's [`Player#boostElytra(ItemStack)`](https://jd.papermc.io/paper/1.19/org/bukkit/entity/Player.html#boostElytra(org.bukkit.inventory.ItemStack))

### Describe the solution you'd like.

Deprecate one of those in favor of other.

### Describe alternatives you've considered.

Well, I can just ignore one of those I guess.

**Comment by Machine-Maker** [comment]
They do have a *slightly* different implementation. Paper's `#boostElytra` has a precondition that they `#isGliding` method returns true. Spigot's has no such check. So which one should be deprecated partially depends on which is more "correct".
