### ISSUE TITLE
When the Y-axis coordinate of the overworld nether portal is raised, the lag is doubled.

### ISSUE THREAD

**Issue by CatTeaA** [PaperSpigot/Paper#9265]
### Timings or Profile link

After the  raises the Y-axis of nether portal, the lag is particularly obvious, which is caused by the search and pairing process between overworld and nether.

### Description of issue

If we create a nether portal at X:2000 Y:64 Z:2000 and into nether. Nether will generate a new portal. Then we return to the overworld, destroy the original nether portal at Y:64, and create a new one at Y:250 (above its place).  We will return to the previously generated portal (this behavior is very reasonable) when we enter this portal again. Now, when we use the portal to push the entity from nether back to the overworld, the entity will be sent to that portal we created in Y:250, but the difference is that it creates a lag three or four times stronger than before, Guess it's a lag in portal pairing process between two dimensions.

I have provided a demo video for this as a reference
https://youtu.be/ENtWeoR8svo

### Plugin and Datapack List

No plugins ( Server plugins (0): )

### Server config files

By default, there are no modifications

### Paper version

his server is running Paper version git-Paper-547 (MC: 1.19.4)

### Other

https://youtu.be/ENtWeoR8svo

**Comment by welove69** [comment]
1.20,It will still appear
