### ISSUE TITLE
Commands.yml bug

### ISSUE THREAD

**Issue by Askarionn** [PaperSpigot/Paper#9275]
### Expected behavior

I should be able to remove "icanhasbukkit" command from commands.yml

### Observed/Actual behavior

Everytime I remove that command from commands.yml file it's re-added after a server server. The only way is to completely disable the aliases thing by adding "[]" (aliases: []) but I don't want to disable it cause I'm using it for other aliases.

### Steps/models to reproduce

Remove   icanhasbukkit: - version $1- and add any other alias

### Plugin and Datapack List

-

### Paper version

I already reported to Pufferfish but they said to report it to upstream (Paper)

[03:35:34 INFO]: This server is running Pufferfish version git-Pufferfish-70 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 19c244b on HEAD)

**Comment by TheMeinerLP** [comment]
I can replecate that. Looks so, bukkit adds everytime the entry

**Comment by electronicboy** [comment]
This is generally a limitation of how bukkits yamlconfig stuff works

**Comment by electronicboy** [comment]
Also, do note that it would be {} to represent an empty map, IIRC it's not a list

**Comment by electronicboy** [comment]
yes, which I said is a limitation of how bukkits command system works

**Comment by TheMeinerLP** [comment]
I think is not a limitation. More like wrong implementation

**Comment by lynxplay** [comment]
Even more annoying here is that this logic lives in both the initSettings block as well as the main craft server parsing.
