### ISSUE TITLE
Paper load order breaking economy plugins

### ISSUE THREAD

**Issue by AlexanderStangier** [PaperSpigot/Paper#9278]
### Expected behavior

Economy plugins register in Vault and Plugins using economies have vault as a dependency. This always worked fine without the economy plugin itself being a dependency

### Observed/Actual behavior

The Economy Plugin registers in Vault after some other plugins. Therefore those plugins can not get the vault economy and do not work

### Steps/models to reproduce

Use Vault, an Economy Plugin and any plugins using Vault economy. On Server startup look at the load order and the plugins being disabled

### Plugin and Datapack List

/

### Paper version

Paper 1.19.4 - 549

**Comment by Machine-Maker** [comment]
Can you give a specific example? I just tried [this economy plugin](https://www.spigotmc.org/resources/liteeco-simple-economy-plugin-1-18-x-1-19.101934/) and Vault, and everything seemed to load fine.

**Comment by Phoenix616** [comment]
Imo this is just those plugins not using Vault properly. There is no guarantee regarding load order for plugins depending on Vault. So either plugins registering their own Vault Economy service provider need to load **before** vault (not after) and plugins depending on Vault need to make sure to listen for the ServiceRegisterEvent in case any Economy service provider is enabled after them. (E.g. [see ChestShop's Vault adapter](https://github.com/ChestShop-authors/ChestShop-3/blob/master/src/main/java/com/Acrobot/ChestShop/Listeners/Economy/Plugins/VaultListener.java#L88-L93))

**Comment by AlexanderMoebius** [comment]
The problem is in the economy plugin.
It just showed up due to changes but is not a problem in paper.

Thanks for the quick answer nevertheless.
