### ISSUE TITLE
If the server is shut down while a player is participating in a game, the player may not be able to participate the next time the server is started up.

### ISSUE THREAD

**Issue by creeper-0910** [PaperSpigot/Paper#9299]
### Expected behavior

Users should be able to log in normally.

### Observed/Actual behavior

If the server is shut down while a player is participating in a game, the player may not be able to participate the next time the server is started up.

### Steps/models to reproduce

Stacktrace: https://pastebin.com/hQqbVRg3
I am not sure if this problem is reproducible, but I will post the work I did before the problem occurred.
1.Set "keep-spawn-loaded" to "false".
2.Set "view-distance" to "80"(This is because other players have told us that the drawing distance is too short).
3.Restarted the server with users joined.

### Plugin and Datapack List

|Plugin||
| --- | --- |
||AllowToConnect v1.0.0|
||CoreProtect v21.3|
||CustomWelcome v1.4|
||HiddenArmor v1.1.0|
||Geyser-Spigot v2.1.1-SNAPSHOT|
||floodgate v2.2.2-SNAPSHOT (b59-2278589)|
||DiscordSRV v1.26.2|
||LunaChat v3.0.16|
||PlaceholderAPI v2.11.3|
||ProtocolLib v5.0.0|
||spark v1.10.41|

### Paper version

```
[18:00:28] [Server thread/INFO]: Checking version, please wait...
[18:00:29] [Thread-42/INFO]: This server is running Paper version git-Paper-4 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: 2ffb704)
You are running the latest version
```

### Other

This error occurred only once, and then this message was displayed only once on the client side.
![image](https://github.com/PaperMC/Paper/assets/56744841/bcdfc47d-72df-4814-97f9-6656136da335)
Could be the same problem as https://github.com/PaperMC/Folia/pull/63 .

**Comment by lynxplay** [comment]
Are you running this behind a proxy ?

**Comment by creeper-0910** [comment]
I am not sure if it can be called a proxy, but I use a service called playit.gg.
