### ISSUE TITLE
Camel keeps rotating when a saddle is put on.

### ISSUE THREAD

**Issue by PapaBigMac69** [PaperSpigot/Paper#9302]
### Expected behavior

Camel is controllable by the player.

### Observed/Actual behavior

A rotating camel.

### Steps/models to reproduce

https://github.com/PaperMC/Paper/assets/99443917/0222bd6d-3be2-4895-9eea-cb2447d780b1

### Plugin and Datapack List

 Plugins: CoreProtect, floodgate, ForcePack, Geyser-Spigot, GeyserUpdater, teleportScroll, Vault, ViaVersion, WorldEdit
 
Datapacks:  [vanilla (built-in)], [file/bukkit (world)]

### Paper version

This server is running Paper version git-Paper-8 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: 3722877)

**Comment by CodeKid0** [comment]
Have you tried it without any plugins?

**Comment by PapaBigMac69** [comment]
Hi @CodeKid0 

I have also tried it without plug-ins,

I figured (considering the players in the video are bedrock players) it might be related to the GeyserMC/Floodgate , But it also happens to Java players with no plug-ins enabled.

**Comment by PapaBigMac69** [comment]
Give me a minute , I am currently checking again. I will let you know the results

**Comment by PapaBigMac69** [comment]
It's the GeyserMC that's messing it up.

thanks for your quick reply.
