### ISSUE TITLE
Add sign side to Player#sendSignChange

### ISSUE THREAD

**Issue by KabanFriends** [PaperSpigot/Paper#9303]
### Is your feature request related to a problem?

Player#sendSignChange is currently missing sign side

### Describe the solution you'd like.

Add sign side parameter to Player#sendSignChange

### Describe alternatives you've considered.

Directly send packets via NMS 💀

**Comment by Owen1212055** [comment]
Whoever wants to take a stab at this, feel free. 😄

**Comment by Infynyty** [comment]
Hey, I'd like to contribute, but I'd be my first time here, so please bear with me :)
Would it be better to add new methods that include the sign side as an argument in the `Player` interface to keep backwards compatibility or should the current methods be modified? In that case should deprecated methods also be updated?

**Comment by Owen1212055** [comment]
> Hey, I'd like to contribute, but I'd be my first time here, so please bear with me :)
> Would it be better to add new methods that include the sign side as an argument in the `Player` interface to keep backwards compatibility or should the current methods be modified? In that case should deprecated methods also be updated?

You would want to add new methods, and most likely deprecate the old ones.

**Comment by yannicklamprecht** [comment]
It doesn't just use the sendBlockUpdate instead.

**Comment by yannicklamprecht** [comment]
> er, I don't think that this could ever work as what is hoped here? the entire sign TE is sent, unless I'm missing something here
> 
> all I could see is basically adding a 2nd param for the backsides components

The TE is sent everytime. The other sendSignChange methods do instantiate a TE in impl.

**Comment by yannicklamprecht** [comment]
> Yea, but you can't just send _a_ side is what I mean, it sends the TE update packet; not really sure adding a Side param makes too much sense as it won't work as expected if you're expecting it to just update a side as seen by the client

Ah missunderstood you. Yes, the opposite site will be send empty, right.

**Comment by Infynyty** [comment]
> The long term goal should be to deprecate the sendSignChange method in favour of the sendBlockUpdate which can handle multiple blockentity types.

That seems like a cleaner solution. Adding new methods now that waxing and sign sides have been added would create a lot of different parameters. Passing a `Sign` as an argument would be shorter, but then it is really just `sendBlockUpdate` with extra steps. 
So, should the old `sendSignChange` methods be deprecated and refer to  `sendBlockUpdate` instead or is there still a case to update the methods?

**Comment by Machine-Maker** [comment]
Yeah, I can't immediately see a use for sign's having their own methods to send per-client changes. Especially with the ability to create new TileState at will via the BlockData interface for a material now, I think they all should just be deprecated and users pointed to the sendBlockUpdate

**Comment by Gameoholic** [comment]
Just looking through the `good first issue` label to find something for myself, is it possible to close this as `Player.sendSignChange` has been marked as deprecated therefore this has been solved?

**Comment by lynxplay** [comment]
Yea thanks for noticing that :) Indeed, the sendBlockUpdate method allows to define a sign with specific text on a specific side!
