### ISSUE TITLE
Material

### ISSUE THREAD

**Issue by Leonlp9** [PaperSpigot/Paper#9306]
### Expected behavior

If i run this code for some materails i get the output AIR

### Observed/Actual behavior

AIR

### Steps/models to reproduce

@EventHandler
    public void onItemDrop(PlayerDropItemEvent event) {
        ItemStack droppedItem = event.getItemDrop().getItemStack();
        Material droppedMaterial = droppedItem.getType();
       
 droppedMaterial is air here
       
    }

### Plugin and Datapack List

My own Plugin

### Paper version

Paper 20 Build 3

**Comment by lynxplay** [comment]
Make sure to specify your api-version in your plugin.yml to "1.20" (quoted)
