### ISSUE TITLE
Riptide tridents stop in midair when trying to speed up

### ISSUE THREAD

**Issue by coolmandude545** [PaperSpigot/Paper#9312]
### Expected behavior

When using an elytra and a riptide 3 trident in the rain, you should be able to pull back on the trident to speed up as many times as you would like.

### Observed/Actual behavior

On a paper server when doing the aforementioned things above, pulling back the trident to get in the air while it rains works fine, however when pulling again in the air to boost, it freezes the character flying. When pulling back again when frozen, it works, but then again when trying to boost after that, it freezes again.

### Steps/models to reproduce

1. Wear an elytra
2. Have a trident with the riptide enchantment
3. Wait for it to rain
4. Try using the trident multiple times in a row to boost yourself while flying with the elytra when its raining

Video below:
https://github.com/PaperMC/Paper/assets/73292633/c2af36ad-df3c-4f74-ab53-14401251a82a

### Plugin and Datapack List

outdated dynmap
simple voice chat 

### Paper version

This server is running Paper version git-Paper-9 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: 3722877)
You are running the latest version
Previous version: git-Paper-540 (MC: 1.19.4)

**Comment by electronicboy** [comment]
client movement is pretty much 100% on the client, have you tested this against a vanilla server?

**Comment by coolmandude545** [comment]
Yes, tested on both a 1.20 vanilla server and singleplayer world, works fine on both of those but not on a server running Paper for whatever reason

**Comment by imDaniX** [comment]
Can confirm on Paper with no plugins. Every other time gives "moved too quickly" warning into the log.
```
[05:09:43 WARN]: imDaniX moved too quickly! 2.907210111618042,-2.6009438843054653,-0.5458955764770508
[05:09:52 WARN]: imDaniX moved too quickly! -1.424834237358823,0.21434377373904567,5.119234433538054
[05:09:56 WARN]: imDaniX moved too quickly! -1.6184461023764811,0.04072162030610116,-4.499069877046772
[05:10:05 WARN]: imDaniX moved too quickly! -3.9332469836393784,3.1024033161953355,3.4506526093413754
> version
[05:10:25 INFO]: Checking version, please wait...
[05:10:25 INFO]: This server is running Paper version git-Paper-10 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: f4dfdcb)
You are running the latest version
```
Got no problems on vanilla.
