### ISSUE TITLE
Flight with trident and elytra is constantly triggering "moved too quickly!" while raining

### ISSUE THREAD

**Issue by no10884** [PaperSpigot/Paper#9318]
### Expected behavior

Not to be so aggressive preventing flight movement.
Wasn't so harsh before migrating from 1.19

### Observed/Actual behavior

Stops me in middle of flight every time when I try to use trident second time to get more speed while raining

### Steps/models to reproduce

Get trident with Riptide
Get Elytra
Wait for rain
Try to spam Riptide charge

### Plugin and Datapack List

 Plugins:
 AntiEndermanGrief, 
 AntiRaidFarm, 
 *LoginSecurity, 
 LuckPerms, 
 *LunarFreeCam, 
 SkinsRestorer, 
 UltimateAutoRestart
 
 No data packs:
 There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]

### Paper version

git-Paper-9 (MC: 1.20)
1.20 Build 9

### Other

Same config as my 1.19
_allow-flight_ is set to _true_ as before in server.properties

https://youtu.be/9nr0r6IESAA

**Comment by no10884** [comment]
Sorry, I was checking previous bug reports, but somehow missed this one
https://github.com/PaperMC/Paper/issues/9312

**Comment by Owen1212055** [comment]
Closing in favor of https://github.com/PaperMC/Paper/issues/9312
