### ISSUE TITLE
Add missing structure seed customizations for trail ruins

### ISSUE THREAD

**Issue by savant27** [PaperSpigot/Paper#9324]
### Is your feature request related to a problem?

Upstream Spigot has options for structure seeds in Spigot.yml; however the list is incomplete and are missing trail ruins.

However, trail ruins are not available. They contains some of the best 1.20 features and adding back the option to enable server owner to customize the seed would be epic!

### Describe the solution you'd like.

Adds on the missing structure seed options onto paper-world.yml

### Describe alternatives you've considered.

Spigot could do the same in spigot.yml

**Comment by Machine-Maker** [comment]
It'll be added into the spigot config cause that's where paper has added the reset of them. No point in splitting them up.

**Comment by savant27** [comment]
> that works, I was unfamiliar with where they had been added previously
