### ISSUE TITLE
HELP - The server has not responded for 10 seconds! Creating thread dump

### ISSUE THREAD

**Issue by tokarvitaliy** [PaperSpigot/Paper#9341]
### Stack trace

The server started to crash, how can I fix it?

```
https://paste.gg/p/anonymous/d3faca7b85ae4839be848dabcecc6b46
```

### Plugin and Datapack List

![image](https://github.com/PaperMC/Paper/assets/111071842/67b51e38-a4b6-40d6-a37c-19d58a8cb3a9)

![image](https://github.com/PaperMC/Paper/assets/111071842/2a17a17c-e24f-4aa5-bd2a-bba305304e72)

![image](https://github.com/PaperMC/Paper/assets/111071842/92dddb9f-f370-45f7-a480-daa0bbd11ea0)

### Paper version

purpur-1.16.5-1171.jar

**Comment by electronicboy** [comment]
1.16.5 is no longer supported by us; For support with others software, you'd also need to go to them for support
