### ISSUE TITLE
PlayerInteractEvent double-firing bug.

### ISSUE THREAD

**Issue by Paneedah** [PaperSpigot/Paper#9356]
### Expected behavior

The event should only be fired once for each hand (which I should be able to counter with a simple check).

### Observed/Actual behavior

When I listen to the `PlayerInteractEvent` it seems to double-fire only under specific conditions.
I'm using paper 1.20.1, running latest 1.20.1 server-jar (`git-Paper-31 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a226f44)`).

If I do the following, it works perfectly fine and only fires once.
```java
    @EventHandler
    public void onPlayerInteract(PlayerInteractEvent e) {
        final Player player = e.getPlayer();
        final EquipmentSlot hand = e.getHand();

        if (hand == EquipmentSlot.OFF_HAND)
            return;

        player.sendMessage("Hey there!");
    }
```

However, doing the following will for whatever reason double-fire the event:
```java
    @EventHandler
    public void onPlayerInteract(PlayerInteractEvent e) {
        final Player player = e.getPlayer();
        final EquipmentSlot hand = e.getHand();

        if (hand == EquipmentSlot.OFF_HAND)
            return;
        
        player.sendMessage("Creating new world. Please wait..");
        World world = Bukkit.createWorld(new WorldCreator("Test_World"));
        player.teleport(world.getSpawnLocation());
        player.sendMessage("Teleported to new world.");
    }
```
It acts a little strange, as I initially get 2 messages saying "Creating new world. Please wait..", as if the second one is fired before the first one completes world creation, then I get two of the "Teleported to new world." messages.

Here is the ACTUAL code I am using. I am trying to make a world when a player right-clicks with a stick.
![image](https://github.com/PaperMC/Paper/assets/76911089/606a62e7-ca8e-43e4-8736-ca9463102f13)

This is the output I get:
![image](https://github.com/PaperMC/Paper/assets/76911089/65345893-973f-4861-a1fd-0dc2fe5c420a)

Yes, I have verified that the event is not being dual-registered. Can be verified since it doesn't double-fire without the world creation.

### Steps/models to reproduce

- Listen to the PlayerInteractEvent
- Return if it's the off-hand
- Create a world
- Teleport to the world's spawn location.
- Send debug messages to verify that it's double-firing.

### Plugin and Datapack List

Plugins:
- ProtocolLib
- Citizens

Datapacks: N/A

### Paper version

[22:41:36 INFO]: This server is running Paper version git-Paper-31 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a226f44)
You are running the latest version
Previous version: git-Paper-"d5a7f90" (MC: 1.19.4)

**Comment by Paneedah** [comment]
Update: Seems to be a client issue. Not sure if you guys can do anything, but the client sends the USE_ITEM packet twice in this instance.

**Comment by Paneedah** [comment]
Update on the bug report:
I have verified that a way around this issue is by running `Bukkit#createWorld()` with a tick delay.
![image](https://github.com/PaperMC/Paper/assets/76911089/4214f919-d0e5-4982-a38f-e7c7d2192cf9)
![image](https://github.com/PaperMC/Paper/assets/76911089/a82b1585-043f-4cfd-8c3d-eaee94b8e892)

Not too sure why this is the case, though.

**Comment by Owen1212055** [comment]
I can't seem to reproduce this.

**Comment by Boy0000** [comment]
I am able to reproduce this on all builds following https://github.com/PaperMC/paper/commit/275173e53860489decc8c005dd130fedfd1621a5

Clip too big to embed so here:
https://www.youtube.com/watch?v=7tjHxDgOGz8

**Comment by Owen1212055** [comment]
This in general two issues being mentioned here. The one mentioned by @Boy0000 was fixed.

The issue here is due to the teleportation of the player. The underlying issue is the fact that stuff like left click air doesn't exist, it relies on the swing arm packet to "simulate" an interaction. However, when teleporting the player, you change their direction. And this direction is used to calculate if an interaction should be simulated.

Because you teleport the player and they usually face air, this will simulate a left click air. 

So sadly, this is not possible to fix and is a result of the hacky backwards compatibility for this event. In general, I would steer away from those click types.
