### ISSUE TITLE
getDamager() in EntityDamageByBlockEvent not returning respawn anchor.

### ISSUE THREAD

**Issue by xMrAfonso** [PaperSpigot/Paper#9370]
### Expected behavior

The getter should return the block that exploded, in this case, the respawn anchor.

### Observed/Actual behavior

It returns null, meaning, the event potentially gets called only after the block already disappeared which means it's just air. 

### Steps/models to reproduce

- Listen to PlayerDeathEvent
- Get the lastDamageCause
- Convert it into EntityDamageByBlockEvent
- Get the damager

### Plugin and Datapack List

Plugins: BBounties (My plugin), FastAsyncWorldEdit (WorldEdit), LuckPerms, Multiverse-Core, PlaceholderAPI, ProtocolLib, spark, Vault, ViaVersion

### Paper version

This server is running Paper version git-Paper-40 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: d6d4c78)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-550 (MC: 1.19.4)

**Comment by Doc94** [comment]
But the block involved was not destroyed then the damager can results in air not?

not sure how this mean to work with blocks causing explosiones like beds or the respawn

**Comment by Machine-Maker** [comment]
We could do something similar to how we handled BlockExplodeEvent, in that we add a BlockState snapshot of the block before the damage is applied (and before it's exploded) to the EntityDamageByBlockEvent?
