### ISSUE TITLE
`ArrowBodyCountChangeEvent` is called every tick

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#9371]
### Is your feature request related to a problem?

`ArrowBodyCountChangeEvent` is called every tick if entity has > 30 arrows in his body because of "hard limit" for 30 arrows in `LivingEntity.java -> tick()`. This continues until arrow count becomes =< 30.

I doubt it has a bad effect on server performance, but I think it's bad anyway.

### Describe the solution you'd like.

- Add methods like `LivingEntity#setArrowsInBodyLimit(integer)`/`integer getArrowsInBodyLimit()` (30 by default) so `removeArrowTime` will be calculated correctly if arrow count is > 30 and <= limit.

or...
- Add methods like `LivingEntity#setRemoveNextArrowInBodyTime(integer)`/`integer getRemoveNextArrowInBodyTime()` which (exposes `removeArrowTime` and) can be used, for example, in `ArrowBodyCountChangeEvent` to "delay" its next call.

or... add both?

### Describe alternatives you've considered.

Manually calculate `removeArrowTime` every tick in `ArrowBodyCountChangeEvent` and just cancel the event if we think that it's too early to remove next arrow.

**Comment by Machine-Maker** [comment]
Can't you just cancel the ArrowBodyCountChangeEvent?

**Comment by molor** [comment]
Didn't know about that event. Yeah, it solves the (old) issue title.

But... I think it's bad that the event will be called literally **every tick** if arrow count is > 30.
I have updated the issue.

**Comment by Machine-Maker** [comment]
I think there might be a use for an "override" to prevent the natural decrease of arrows or stingers, yeah.
