### ISSUE TITLE
net.minecraft.ReportedException: Exception ticking world

### ISSUE THREAD

**Issue by cagoshian** [PaperSpigot/Paper#9373]
### Stack trace

https://paste.gg/p/anonymous/ebc3bffaf1a2419eb3f837b799edda36

### Plugin and Datapack List

- SkinsRestorer

### Paper version

This server is running Paper version git-Paper-43 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 3756f5b)
You are running the latest version
Previous version: git-Paper-40 (MC: 1.20.1)

**Comment by electronicboy** [comment]
Update paper

**Comment by kennytv** [comment]
That stacktrace is from build 40, not build 42
