### ISSUE TITLE
TrimPattern methods / comparisons

### ISSUE THREAD

**Issue by Romindous** [PaperSpigot/Paper#9376]
### Is your feature request related to a problem?

Not necessarily, it is a request to expand on an interface that in my opinion, lack some methods. org.bukkit.inventory.meta.trim.TrimPattern is not an enum, and thus, doesn't have some vital methods, such as .toString(), .name(), and a static .valueOf(String name).

### Describe the solution you'd like.

Add the methods that would allow for easier work with the given interface: 
.toString() - sould return trim pattern name, ex > "COAST",
.name() - sould return trim pattern name, ex > "COAST",
.equals(Object o) - should return the result of the object type / trim name / trim material comparison,
.trimMaterial() - should return the Material, from which the pattern is derived, 
    ex > Material.COAST_ARMOR_TRIM_SMITHING_TEMPLATE
static .valueOf(String name) - would return the trim pattern from the name, or null, if no name is matched.

### Describe alternatives you've considered.

One could, theoretically, make a HashMap or BiMap to relate the name / TrimPattern in own plugin, however, doing that every time is... rather tedious....

### Other

![image](https://github.com/PaperMC/Paper/assets/64203160/5945ad5b-8696-4a65-9f43-fe358629e826)
![image](https://github.com/PaperMC/Paper/assets/64203160/8c770caa-6bfd-4264-9652-ab2c36d3ccc1)

**Comment by Romindous** [comment]
Oh, and since the interface extends Keyed, it would be nice to make a .getByKey(NamespacedKey key)

**Comment by emilyy-dev** [comment]
The "name" is the key, not a string, you can get an instance from the key via the `Registry.TRIM_PATTERN`, it is not an enum and should not be treated as such. As for `toString`/`equals`, those would exist in the implementation (those methods cannot be defined in an interface), I can see the appeal of having a functional `toString` for debugging purposes (anything user-facing should use the resource key instead), but `equals` should already works as intended as there is only ever one instance per key

**Comment by Machine-Maker** [comment]
Yeah, the only thing that is missing from the list of things you suggested is a method to get the Material for the trim. Everything else should not exist, and won't be added by Paper. Use the `Registry.TRIM_PATTERN` to get instances by a key.

**Comment by Romindous** [comment]
Oh, ok, kinda forgot Registry exists now, that clears things up! Thanks a lot!
