### ISSUE TITLE
StackOverflowError with paper classloaders

### ISSUE THREAD

**Issue by RobotHanzo** [PaperSpigot/Paper#9386]
### Stack trace

https://paste.gg/p/anonymous/e685faacdcae4c288011c17ec97dd94d

### Plugin and Datapack List

```
Server Plugins (30):
Paper Plugins:
 - ExcellentCrates, NexEngine
Bukkit Plugins:
 - ajLeaderboards, BetterPrefix, BossBarHealth, BuycraftX, Citizens, CloudNet-Bridge, CloudNet-LuckPerms-Addon, DecentHolograms, FastAsyncWorldEdit, FeatherBoard
 FlyPerms, GKCore, GKMagic, GKReplay, GKRoom, JumpPads, LibsDisguises, LuckPerms, MVdWPlaceholderAPI, PlaceholderAPI
 PlugManX, ProMCCore, ProSkillAPI, ProtocolLib, spark, Vault, WorldBorder, WorldGuard
```

No datapacks installed, the major plugins are self-made

### Actions to reproduce (if known)

- Create a paper plugin (one with paper-plugin.yml)
- Load dependencies that expect a default classloader (in this case, MongoDB driver which calls Kotlin reflection somewhere)
- StackOverflowError happens

### Paper version

Paper version git-Paper-43 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 3756f5b)

### Other

It appears that this issues has been reported on the Discord already, but not tracked within GitHub issues, so I created it.
The discussion starts here:
https://canary.discord.com/channels/289587909051416579/555462289851940864/1121086442039418920

A potential fix that was mentioned by Moulberry is to remove `", group=" + this.group +` from the toString method, however this might remove necessary information

**Comment by MiniDigger** [comment]
while I agree that the toString should be fixed, this is also an issue in your plugin, you are trying to serialize a plugin class loader into your DB, that seems very wrong

**Comment by RobotHanzo** [comment]
> while I agree that the toString should be fixed, this is also an issue in your plugin, you are trying to serialize a plugin class loader into your DB, that seems very wrong

It doesn't look like that from the database dashboard? Can you point out which line indicates this behavior?
