### ISSUE TITLE
TPS drops down to 15 with default paper spawning settings, high amount of events

### ISSUE THREAD

**Issue by dandud100** [PaperSpigot/Paper#9393]
### Timings or Profile link

https://timings.aikar.co/dev/?id=cf3a557c91e04708ae62c2a72095144d

### Description of issue

I got extreme lags with the default mob spawning settings, i lowered the monsters and it got better.

I thought this is a myworlds issue, but the plugin developer suggested, that i should report this here because "myworlds just uses papers builtin entity pre-spawn event so theres nothing I can do about it".

### Plugin and Datapack List

MyWorlds, BKCommonLib

### Server config files

default generated

### Paper version

This server is running Paper version git-Paper-46 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 206dd3a)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-45 (MC: 1.20.1)

**Comment by electronicboy** [comment]
Are you restricting mob spawns? If so, that’s the issue; vanilla tries *really* hard to try to reach the mob spawn target, so much so that preventing spawns will cause issues; there are some ideas on how to mitigate it to some degree, but, there’s little means for a real fix for this which isn’t basically peddling around that target

**Comment by dandud100** [comment]
> Are you restricting mob spawns? If so, that’s the issue; vanilla tries _really_ hard to try to reach the mob spawn target, so much so that preventing spawns will cause issues; there are some ideas on how to mitigate it to some degree, but, there’s little means for a real fix for this which isn’t basically peddling around that target

Can you tell me which config part you mean exactly?

**Comment by dandud100** [comment]
[NHOnDXh2yu.sparkprofile.zip](https://github.com/PaperMC/Paper/files/11872987/NHOnDXh2yu.sparkprofile.zip)

**Comment by bergerkiller** [comment]
> Are you restricting mob spawns? If so, that’s the issue; vanilla tries _really_ hard to try to reach the mob spawn target, so much so that preventing spawns will cause issues; there are some ideas on how to mitigate it to some degree, but, there’s little means for a real fix for this which isn’t basically peddling around that target

Can't mob spawning be backed off for a couple seconds when spawning is denied? In a timings report he sent me that event was triggered 10s of thousands of times a tick. it's ridiculous.

**Comment by Warriorrrr** [comment]
There was an open PR that implemented mob spawning back-off, but it was closed due to being inactive and still having a few todo's from what I recall

**Comment by dandud100** [comment]
> There was an open PR that implemented mob spawning back-off, but it was closed due to being inactive and still having a few todo's from what I recall

This is it i think: https://github.com/PaperMC/Paper/pull/5460
