### ISSUE TITLE
Sniffer hatching spawn reason missing

### ISSUE THREAD

**Issue by Tackoozle** [PaperSpigot/Paper#9397]
### Expected behavior

When a sniffer is hatching, the spawnreason should be SpawnReason.EGG, like turtles.

### Observed/Actual behavior

Currently, the spawnreason is DEFAULT

### Steps/models to reproduce

Place a snifferegg, let it hatch, and debug the CreatureSpawnEvent

### Plugin and Datapack List

-

### Paper version

> version
[20:48:06 INFO]: This server is running Paper version git-Paper-48 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: b34d4ec)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-81 (MC: 1.19)

**Comment by Doc94** [comment]
This is included in https://github.com/PaperMC/Paper/pull/9288

**Comment by Tackoozle** [comment]
Oh :D
I will close it then.
