### ISSUE TITLE
Written Books not property showing target selectors, nbt data, and scoreboard values.

### ISSUE THREAD

**Issue by Chump-the-Lump** [PaperSpigot/Paper#9416]
### Expected behavior

I expected that target selector tags in a book text would display as they do in vinella.

### Observed/Actual behavior

Rather then showing the entities it shows the selector or if using nbt or score tags, nothing at all

### Steps/models to reproduce

Run the command 

/give @s written_book{title:"",author:"",pages:['[{"text":"All players: "},{"selector":"@a"},{"text":"\\nYour holding a:  "},{"nbt":"SelectedItem.id","entity":"@s"}]']} 1

### Plugin and Datapack List

A custom-made plugin that manages resource packs and worlds and a minigame data pack, the problem persists with both disabled

### Paper version

This server is running Paper version git-Paper-55 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: e4b40dd)
You are running the latest version
Previous version: git-Paper-18 (MC: 1.20.1)

**Comment by Machine-Maker** [comment]
You have to enable them in the paper configuration. See https://docs.papermc.io/paper/reference/global-configuration#resolve-selectors-in-books. They are disabled by default because they can be abused any player in creative mode.

**Comment by Chump-the-Lump** [comment]
I did not realize that was a thing. Sorry for the miss report.
