### ISSUE TITLE
Stacktrace: network.protocol.game.PacketPlayInTeleportAccept - Paper 1.20.1 Build #58

### ISSUE THREAD

**Issue by yzz17** [PaperSpigot/Paper#9421]
### Stack trace

```
https://paste.gg/p/anonymous/aa445ecbad4040bb82d727e4bd1249d7
```

### Plugin and Datapack List

I create a new server, to trace the cause, so the answer is none :S

### Actions to reproduce (if known)

1. create a server
2. put the server in off-line mode (properties file)
3. wait random ticks, or exit and enter the server (It's strange that sometimes it doesn't happen)

### Paper version

Paper 1.20.1 Build #58

### Other

I'm not quite sure how to replicate it, sometimes when logging into the server, just before the {player} login message, can be observed Stacktrace, I came to think that it was teleportation because of the essentials x plugin, but not, This problem had already published, but they were already closed due to lack of communication from the person who reported it.

I would appreciate your help, I'll stay tuned :)

**Comment by electronicboy** [comment]
We don't support offline mode, and this generally looks to be caused by
something installed on the server mangling the networking systems state

**Comment by yzz17** [comment]
I apologize, thanks :)

**Comment by electronicboy** [comment]
I recall that we did diagnose and find the solution for this for one person months ago, but, idk what all was said; not do I have the means to diagnose this myself, something is causing the network manager to be thrown into the wrong state, and I think it was something stupid like a bad config or a borked JVM install

**Comment by yzz17** [comment]
very interesting, I have installed, jre1.8.0_351 and jdk-20 ?  what versions do you use?

**Comment by electronicboy** [comment]
A play packet shouldn't exist when the connection is still listening for handshakes; I can't say exactly what your issue is, i can't test it because I don't have hardware which is really useful for testing much right now

**Comment by yzz17** [comment]
Hey, even so, I thank you very much, at least I can try different installations to see if something happens, and I will gladly share everything that is necessary, I should not be the only one with the problem today or in the future

**Comment by yzz17** [comment]
LOL... I can't see the error anymore in jdk 17 , uninstall (jre1.8.0_351, jdk-20) , Is it possible that the file downloaded in "cache" does not support jdk 20? Well I have no idea but it has a solution, I appreciate your time

**Comment by yzz17** [comment]
speak very soon, jdk 17 it didn't make a difference, I will keep trying

**Comment by yzz17** [comment]
well, for that person who is reading this in the future.... try even on another pc... nothing yet
