### ISSUE TITLE
Chunk band don't work on 1.20.1

### ISSUE THREAD

**Issue by ParaliyzedEvo** [PaperSpigot/Paper#9422]
### Expected behavior

Chunk bans working

### Observed/Actual behavior

Chunk bans not working

### Steps/models to reproduce

1. Make chunk bans on paper 1.19.4 or before
2. Update it to 1.20.1
3. Turn on chunk ban
4. Doesn't work

### Plugin and Datapack List

BannerBoard, ClaimChunk, DecentHolograms, dynmap, Essentials, EssentialsChat, EssentialsSpawn, LightAPI, LPC, LuckPerms, Magic, Maintenance, MiniMOTD, NametagEdit, NoEncryption, PlaceholderAPI, ProtocolLib, SimpleTpa, SkinsRestorer, Skoice, spark, StaffPlus, VentureChat, ViaBackwards, ViaRewind, ViaVersion, Waystones, WorldEdit, WorldGuard

[vanilla (built-in)], [file/bukkit (world)], [file/New-Desert-Temple (world)], [file/New-End-Cities (world)], [file/New-Igloo (world)], [file/New-Ocean-Ruins (world)], [file/Timber v5.1.6 (world)], [file/banner-flags-v1-4 (world)], [file/towns-and-towers-1-10 (world)], [file/extrarecipes-e3351 (world)]

### Paper version

git-Paper-18 (MC: 1.20.1)

### Other

Pretty much I need the chunk bans for the server prison and its a very important security feature.

**Comment by ocelotpotpie** [comment]
This is not a feature Paper plans to add, sorry.

**Comment by MWHunter** [comment]
can you add a config option for this feature?

**Comment by MiniDigger** [comment]
bug fixes arent a feature, they are a bug fix. we dont provide config options for bug fixes, especially if they are security releated.
