### ISSUE TITLE
Player Interact Sign Event for Dyeing and Glowing

### ISSUE THREAD

**Issue by DaMarine** [PaperSpigot/Paper#9423]
### Is your feature request related to a problem?

Using the existing logic of PlayerInteractEvent makes it incredibly complicated to determine which side of a sign the player interacted with, when using dyes or ink sacs. 

Issue #9293 / PR https://github.com/PaperMC/Paper/pull/9300 addressed a similar issue for the purposes of editing signs, but did not address this use case, and the original issue reporter even noted this use case in the PR before merging: https://github.com/PaperMC/Paper/pull/9300#issuecomment-1586080271

### Describe the solution you'd like.

A event that triggers when a player tries to dye a sign, or use an ink sac on it, with a way to get which side of the sign is being clicked.

### Describe alternatives you've considered.

As before with #9293, the only alternative I see is via NMS.

**Comment by DaMarine** [comment]
@KabanFriends this is the case that you referenced in https://github.com/PaperMC/Paper/issues/9300#issuecomment-1586080271_

**Comment by lynxplay** [comment]
https://github.com/PaperMC/Paper/pull/9388 should presumably fix this for you once merged.

**Comment by Machine-Maker** [comment]
@DaMarine can you confirm that the method being added in #9388 does address your issue? Its basically a way to get the side of a sign that a location is "facing".

**Comment by DaMarine** [comment]
@Machine-Maker can confirm, that's the exact change I'm after!
