### ISSUE TITLE
Beacon radius crash

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperSpigot/Paper#9424]
### Stack trace

```
https://pastebin.com/tDPtS60Q
```
It has something to do with a beacon having an extremely large radius for entity lookup, since Mojang has not added a limit I was hoping paper could add one to prevent players from crashing the server

### Plugin and Datapack List

LuckPerms, PlotSquared, FastAsyncWorldEdit, LibsDisguises, ProtocolLib, Panilla

### Paper version

This server is running Paper version git-Paper-57 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 437e8da)

**Comment by Machine-Maker** [comment]
Fixed in https://github.com/PaperMC/Paper/commit/48ea66e97fdc464dc1e766b60bcbfcc0f4fd8491
