### ISSUE TITLE
Please fix preventing entities from accessing nether portals  1.20.1

### ISSUE THREAD

**Issue by hed516** [PaperSpigot/Paper#9425]
Please fix preventing entities from accessing nether portals

**Comment by lynxplay** [comment]
Please elaborate as to what you mean with "please fix Block NonPlayers In Nether Portal".
Preferably in an understandable manner so we can look into it.

**Comment by hed516** [comment]
Please fix preventing entities from accessing nether portals

**Comment by kennytv** [comment]
Properly fill out the issue template with *all* the information asked of you, otherwise we cannot help you,
