### ISSUE TITLE
Please fix preventing entities from accessing nether portals 1.20.1

### ISSUE THREAD

**Issue by hed516** [PaperSpigot/Paper#9426]
### Is your feature request related to a problem?

Please fix preventing entities from accessing nether portals 1.20.1

### Describe the solution you'd like.

Please fix preventing entities from accessing nether portals 1.20.1

### Describe alternatives you've considered.

Please fix preventing entities from accessing nether portals 1.20.1

**Comment by kennytv** [comment]
Once again, please fill the issue template (the bug one) with the information we ask of you. Please do not open another without doing so
