### ISSUE TITLE
getHandlerLists only returns listener for EntityRemoveFromWorldEvent

### ISSUE THREAD

**Issue by IoIxD** [PaperSpigot/Paper#9432]
### Expected behavior

As with Spigot, I should be able to use the following code to retrieve every event that I can listen in on, which is useful for making plugins like my Paprika plugin that allows Lua code to be bound to Minecraft; I'm currently working on another plugin that allows for full on shared libraries to be used.

        RegisteredListener registeredListener = new RegisteredListener(this, (listener, event) -> onEvent(event), EventPriority.NORMAL, MAINCLASS, false);
        for (HandlerList handler : HandlerList.getHandlerLists())
            handler.register(registeredListener);

I would expect, say, BlockBreakEvent to be fired when I break a block.

Going back to the Paprika plugin, I'm actually reusing the code I wrote in that, and that plugin worked. I'm currently unable to see if this works in a previous version of PaperMC because of troubles getting an older version of Java; if nobody can reproduce this, then tomorrow I will search for the version in question.

### Observed/Actual behavior

The only event that's getting passed is EntityRemoveFromWorldEvent.

```
[20:42:44 INFO]: [BlackBox] EntityRemoveFromWorldEvent
[20:42:58 INFO]: [BlackBox] EntityRemoveFromWorldEvent
[20:43:02 INFO]: [BlackBox] EntityRemoveFromWorldEvent
[20:43:02 INFO]: [BlackBox] EntityRemoveFromWorldEvent
```

### Steps/models to reproduce

1. Make a new plugin
2. Make a class uses HandlerList.getHandlerLists().
3. Make the function that gets passed into it print any event names that we see.

### Plugin and Datapack List

Only my own.

```
> plugins
[20:47:29 INFO]: Server Plugins (1):
[20:47:29 INFO]: Bukkit Plugins:
[20:47:29 INFO]:  - BlackBox
>
```

### Paper version

```
This server is running Paper version git-Paper-60 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: f2c1e13)
You are running the latest version
Previous version: git-Paper-79 (MC: 1.17)
```

### Other

My [library loader code can be found here](https://github.com/BlackBoxMC/blackbox/blob/master/src/main/java/net/ioixd/blackbox/Bridge.java)

**Comment by IoIxD** [comment]
Bug replicated in both Bukkit and Spigot somewhat (although in both of them, more then 1 event is sent) which makes me think it's my code. But again, this exact code worked for my plugin that allows lua to be used.

**Comment by Machine-Maker** [comment]
So the HandlerList for an event is only added to the global list of HandlerList when the class has its static initializer run. If that class is *never* loaded by a classloader, it's HandlerList will never exist.

**Comment by IoIxD** [comment]
How are you suggesting I fix my code?

**Comment by Machine-Maker** [comment]
If you want to register a listener for every event, I would use classgraph to get all subtypes of Event on the classpath and make sure each of those is loaded. *Then* get all the HandlerLists.

**Comment by IoIxD** [comment]
Well that sucks. This method worked on 1.18.2, what changed?

**Comment by Machine-Maker** [comment]
I'm not sure anything did. Perhaps you were getting all the HandlerLists later in startup or while the server was running and more event classes had been loaded? 

Either way, what I said was true then as it is now. The HandlerList for an event doesn't exist anywhere until that Event class is statically initialized, and there is no guarantees made when that might happen for any event. The EntityAdd/RemoveFromWorldEvent certainly is going to be one of the earlier ones as entities are added and removed all the time.

**Comment by IoIxD** [comment]
While wrestling with Gradle to add this dependency to this project, I remembered that the Lua plugin reloads its handlers three seconds after loading because I encoutnered this exact bug. You are correct here.
