### ISSUE TITLE
Connections via Server Address and Velocity Server

### ISSUE THREAD

**Issue by No-Eul** [PaperSpigot/Paper#9438]
### Is your feature request related to a problem?

I wanted to support both connection through my domain as well as the Velocity lobby server using the plugin that interact with the player NPCs. So I have personally implemented this feature and I want it to be officially added.

### Describe the solution you'd like.

* Add `proxies.velocity.allow-direct-connection` config in `config/paper-global.yml` file
  * This is a boolean value, the default is `false`, which a server owner can enable if necessary.
  * If it is `true`, the clients can connect to the Paper server without connecting to the Velocity server.

### Total Configuration Specification
```yml
# config/paper-global.yml
proxies:
  velocity:
    allow-direct-connection: false
```

### Describe alternatives you've considered.
Before making this suggestion, I implemented and tried this feature myself by modifing server or by making [the mod](https://modrinth.com/mod/fabroxy). like this:

### Before Implementation
```java
// Nested Class GlobalConfiguration.Proxies.Velocity in io/papermc/paper/configuration/GlobalConfiguration.java
public class Velocity extends ConfigurationPart {
    // ...
}
```
```java
// void handleCustomQueryPacket(ServerboundCustomQueryPacket) in net/minecraft/server/network/ServerLoginPacketListenerImpl.java
// Paper start - Velocity support
if (io.papermc.paper.configuration.GlobalConfiguration.get().proxies.velocity.enabled && packet.getTransactionId() == this.velocityLoginMessageId) {
    net.minecraft.network.FriendlyByteBuf buf = packet.getData();
    if (buf == null) {
        this.disconnect("This server requires you to connect with Velocity.");
        return;
    }
    // ...
}
// ...
```

### After Implementation
```java
// Nested Class GlobalConfiguration.Proxies.Velocity in io/papermc/paper/configuration/GlobalConfiguration.java
public class Velocity extends ConfigurationPart {
    // ...
    public boolean allowDirectConnection;
}
```
```java
// void handleCustomQueryPacket(ServerboundCustomQueryPacket) in net/minecraft/server/network/ServerLoginPacketListenerImpl.java
// Paper start - Velocity support
if (io.papermc.paper.configuration.GlobalConfiguration.get().proxies.velocity.enabled && packet.getTransactionId() == this.velocityLoginMessageId) {
    net.minecraft.network.FriendlyByteBuf buf = packet.getData();
    if (buf == null) {
        if (GlobalConfiguration.get().proxies.velocity.allowDirectConnection) {
            this.state = ServerLoginPacketListenerImpl.State.KEY;
            this.connection.send(new ClientboundHelloPacket("", this.server.getKeyPair().getPublic().getEncoded(), this.challenge));
        } else this.disconnect("This server requires you to connect with Velocity.");
        return;
    }
    // ...
}
// ...
```

**Comment by emilyy-dev** [comment]
Wouldn't this bypass user authentication which is handled by the proxy? It would be trivial to point your domain to a proxy server and that proxy to the Minecraft server, and have it all set with the secret tokens etc

**Comment by lynxplay** [comment]
[Forced hosts](https://docs.papermc.io/velocity/configuration#forced-hosts-section) should be doing pretty much exactly what you want here ?

But yea, as emily pointed out, this sounds rather dangerous for the login logic of the paper server as it would have to split between its own logic and the velocity logic based on the connection.

**Comment by electronicboy** [comment]
The server would basically have to ensure that it handles both paths

But, I don't think that there is much interest from us to support such a
thing, we already have enough issues with people not understanding how
proxy stuff works, this honestly only sounds to just create more confusion
and require us to support two separate Auth flows for a niche upon niche
use case when better alternatives generally already exist

**Comment by emilyy-dev** [comment]
Closing for the same reasons outlined in #9511
