### ISSUE TITLE
Add a way to get event cause in PlayerOpenSignEvent

### ISSUE THREAD

**Issue by KabanFriends** [PaperSpigot/Paper#9439]
### Is your feature request related to a problem?

PR #9300 which adds `PlayerOpenSignEvent` was merged recently.
But it looks like there is currently no way to get if the player has just placed a new sign, or editing an existing sign.
This makes the event usage very limiting, since I think many plugin developers would want to only disable sign editing.

### Describe the solution you'd like.

Store how the sign menu was opened (by placing a new sign or by editing existing one) in the event, and add an API method to get  the event type (idk how it should be named)

### Describe alternatives you've considered.

Currently I am patching NMS code in a Paper fork to only remove sign editing

**Comment by molor** [comment]
+1 vote for this. Currently I'm using a "workaround" (check if all lines on sign are empty, then this is a "new" sign).

Related FR from me: https://hub.spigotmc.org/jira/browse/SPIGOT-7412
I think both of these `Cause`s can be added to both of these events.
