### ISSUE TITLE
Decorated pot appears when cancelling any recipe

### ISSUE THREAD

**Issue by DatapackMaster** [PaperSpigot/Paper#9444]
### Expected behavior

As the title suggests, if you attempt to make any recipe on the crafting table and cancel it by removing the ingredients, a decorated pot appears.

Plugins: BlueSlimeCore, CombatLogX, GrimAC, LifeSteal-Smp-Plugin, LuckPerms, Orebfuscator, ProtocolLob, ViaBackwards, ViaVersion

Steps to reproduce: Follow the link below and copy what the video does.

https://github.com/PaperMC/Paper/assets/104522934/1146d829-4964-4ed6-a022-129525442c82

This was discovered in a multiplayer server.

### Observed/Actual behavior

An empty decorated pot appeared on the crafting output when cancelling a crafting recipe.

### Steps/models to reproduce

https://github.com/PaperMC/Paper/assets/104522934/1146d829-4964-4ed6-a022-129525442c82

### Plugin and Datapack List

BlueSlimeCore, CombatLogX, GrimAC, LifeSteal-Smp-Plugin, LuckPerms, Orebfuscator, ProtocolLob, ViaBackwards, ViaVersion

### Paper version

This server is running Paper version git-Paper-43 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 3756f5b)
You are 19 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-37 (MC: 1.20.1)

**Comment by MiniDigger** [comment]
please try reproducing without plugins

**Comment by lynxplay** [comment]
Given the fact that this very much looks plugin induced, I can not replicate this whatsoever on latest paper I'll be closing this. If you find replication steps on *latest* paper without plugins, feel free to post them here so I can reopen the issue :)
