### ISSUE TITLE
`ProfileBanList` uses deprecated `PlayerProfile`

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#9449]
### Expected behavior

Every profile-related method works with `com.destroystokyo.paper.profile.PlayerProfile`.

### Observed/Actual behavior

Every profile-related method works with `org.bukkit.profile.PlayerProfile`.

### Steps/models to reproduce

Use the new Ban API from https://github.com/PaperMC/Paper/pull/9440.

### Plugin and Datapack List

N/A

### Paper version

```
git-Paper-63 (MC: 1.20.1)
```

### Other

Upstream commits:

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/648196070e5a1f035c3691870c691c20e44b3439
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/0a0fc3beec07e313acfb72062b27165b7aebc3d1
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/37a60b454f6c7b24495e2e839c12b83a503d46a8
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/9421320fcb21e5df1742e42763114fa20794e6f6

**Comment by AuroraLS3** [comment]
Possibly related exception when calling `Player#isBanned`

```
java.lang.ClassCastException: class com.destroystokyo.paper.profile.CraftPlayerProfile cannot be cast to class org.bukkit.craftbukkit.v1_20_R1.profile.CraftPlayerProfile (com.destroystokyo.paper.profile.CraftPlayerProfile and org.bukkit.craftbukkit.v1_20_R1.profile.CraftPlayerProfile are in unnamed module of loader java.net.URLClassLoader @4f8e5cde)
   org.bukkit.craftbukkit.v1_20_R1.ban.CraftProfileBanList.isBanned(CraftProfileBanList.java:79)
   org.bukkit.craftbukkit.v1_20_R1.ban.CraftProfileBanList.isBanned(CraftProfileBanList.java:17)
   org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.isBanned(CraftPlayer.java:1631)
   Plan-5.5-build-2391.jar//com.djrapitops.plan.gathering.domain.BukkitPlayerData.isBanned(BukkitPlayerData.java:53)
.... 
```
https://github.com/plan-player-analytics/Plan/issues/3098

**Comment by Machine-Maker** [comment]
Yes, I think that issue would be fixed by the linked PR as well.

**Comment by mikeprimm** [comment]
Seeing likely identical issue through the OfflinePlayer for isBanned():

`java.lang.ClassCastException: class com.destroystokyo.paper.profile.CraftPlayerProfile cannot be cast to class org.bukkit.craftbukkit.v1_20_R1.profile.CraftPlayerProfile (com.destroystokyo.paper.profile.CraftPlayerProfile and org.bukkit.craftbukkit.v1_20_R1.profile.CraftPlayerProfile are in unnamed module of loader java.net.URLClassLoader @446cdf90)
	at org.bukkit.craftbukkit.v1_20_R1.ban.CraftProfileBanList.isBanned(CraftProfileBanList.java:79) ~[paper-1.20.1.jar:git-Paper-64]
	at org.bukkit.craftbukkit.v1_20_R1.ban.CraftProfileBanList.isBanned(CraftProfileBanList.java:17) ~[paper-1.20.1.jar:git-Paper-64]
	at org.bukkit.craftbukkit.v1_20_R1.CraftOfflinePlayer.isBanned(CraftOfflinePlayer.java:111) ~[paper-1.20.1.jar:git-Paper-64]
	at org.dynmap.bukkit.DynmapPlugin$BukkitServer.isPlayerBanned(DynmapPlugin.java:321) ~[Dynmap-3.6-SNAPSHOT-spigot.jar:?]
	at org.dynmap.WebAuthManager.checkLogin(WebAuthManager.java:110) ~[Dynmap-3.6-SNAPSHOT-spigot.jar:?]
`
Not sure if PR will or will not address that, but looks promising.

**Comment by electronicboy** [comment]
What would be nice is to have reputable people to test this; I don't have
the hardware capable to do that

**Comment by Izocel** [comment]
Same error here its worked fine before newest 1.20
I have an event listener onPlayerLogin that trie to cast ``` `final Player loginPlayer = event.getPlayer(); ``
With org.bukkit.entity.Player

**Comment by Doc94** [comment]
> Same error here its worked fine before newest 1.20 I have an event listener onPlayerLogin that cast:
> 
> ```java
> final Player loginPlayer = event.getPlayer();
> ```
> 
> With org.bukkit.entity.Player
> 
> Then the stack throw the exception when:
> 
> ```java
> if (loginPlayer.isBanned()) {}
> ```

you can test the build PR in https://github.com/PaperMC/Paper/pull/9450 for check if that PR fix the issue.

**Comment by AuroraLS3** [comment]
I'm getting someone ask about this error every 4 hours and it's driving me insane

**Comment by Izocel** [comment]
Do we know if its a mistake from source or their is a change comming up ?

**Comment by Izocel** [comment]
good job guys ;) thanks for quick fix
