### ISSUE TITLE
[Feature] Better Offuscation

### ISSUE THREAD

**Issue by Texbio** [PaperSpigot/Paper#9451]
### Is your feature request related to a problem?

Currently obfuscation hides alot of stuff (attributes, lore, item-name, item-damage, enchantments) but I want it to hide more if possible.

### Describe the solution you'd like.

If possible, I want only CustomModelData to show and nothing else.

**People are able to use nbt inspectors** to see PublicBukkitValues and see if an item is unbreakable or not still.

### Other

current paper-world-defaults.yml

  obfuscation:
    items:
      hide-durability: true
      hide-itemmeta: true
      hide-itemmeta-with-visual-effects: false

new paper-world-defaults.yml?

  obfuscation:
    items:
      hide-durability: true
      hide-itemmeta: true
      hide-textures: false
      hide-itemmeta-with-visual-effects: false
      hide-other: true

**Comment by Machine-Maker** [comment]
To be clear, the current system doesn't hide that info from the user who has the item, it hides info from other clients that need to know those specific items are in specific slots (hands, armor) of a client to display things on the player model. 

I think those things are already hidden within that system right?

**Comment by Texbio** [comment]
I used a second minecraft account to verify usinf the mods ‘meteor client’ and ‘NBT Tooltip’ to copy and see this nbt data on a paper server. 

As posted above, some of the extra data like PublicBukkitValues were not hidden to the one using the mods.

**Comment by Machine-Maker** [comment]
Oh you are right. I thought we implemented it using a whitelist system instead of a blacklist. Yeah, some more things can probably be added to it.
