### ISSUE TITLE
Actionbar fade in and fade out

### ISSUE THREAD

**Issue by Jakush** [PaperSpigot/Paper#9452]
### Is your feature request related to a problem?

I would like to have this added, so you can make actionbars pretty, it could have a nice animations.

### Describe the solution you'd like.

Solution could be having a new method `Player#sendActionBar(Component message, long fadeIn, long stay, long fadeOut)`, and the time would be in ticks.

### Describe alternatives you've considered.

I tried to look for something, but I only found a command from Minecraft and the command's name is /title. There you can set how long should `fadeIn, fadeOut and stay` be here by /title <player> times <fadeIn> <stay> <fadeOut>. And then you can send actionbar with that properties by command /title <player> actionbar <message>

**Comment by Malfrador** [comment]
The client only supports fadeIn, stay and fadeOut for the title. The actionbar will always fade out after 60 ticks. Its a [bug](https://bugs.mojang.com/browse/MC-106167 )since the actionbar exists.

**Comment by Jakush** [comment]
So there is not a way how we could manage this to work?

**Comment by Malfrador** [comment]
No, not possible without modifying the client. 
If you want the actionbar to stay longer, just send the same actionbar again every 2 seconds using a repeating task.

**Comment by Jakush** [comment]
I can do that, but I would like to have when it fades in or out

**Comment by Machine-Maker** [comment]
Yeah, that isn't possible to control how long the fade in or fade out takes from the server.
