### ISSUE TITLE
Server won't start if Java version contains slash

### ISSUE THREAD

**Issue by gphg** [PaperSpigot/Paper#9456]
### Expected behavior

it runs normally.

### Observed/Actual behavior

it won't run, even before the server console fired up.

### Steps/models to reproduce

1. get Java version that has dot on the version. In my case it was:
```
$ java -version
openjdk version "17-internal" 2021-09-14
OpenJDK Runtime Environment (build 17-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 17-internal+0-adhoc..src, mixed mode)
```
2. download latest paper jar and run it normally.

### Plugin and Datapack List

nil

### Paper version

latest version. `1.20.1` and `build#64`.

### Other

![image](https://github.com/PaperMC/Paper/assets/46024870/5fe4cbf8-774c-4ca5-bc91-b683caac850c)

**Comment by SirYwell** [comment]
Looks like your JDK is violating the specification of the [`java.specification.version`](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/System.html#java.specification.version) property.

**Comment by MiniDigger** [comment]
upstream added a check to block unofficial jdk builds, use an official build

**Comment by gphg** [comment]
Thanks. I updated the title.
