### ISSUE TITLE
Proxy commands cause 'Chat message validation failure' kick

### ISSUE THREAD

**Issue by Travja** [PaperSpigot/Paper#9463]
### Expected behavior

I would expect for proxy commands not to interfere with how the Paper server handles execution.

### Observed/Actual behavior

When running Paper behind a Bungee or Waterfall proxy, proxy commands (like `/server`) cause issues with chat messages to fail validation somewhere and kick the player with a 'Chat message validation failure' message.

### Steps/models to reproduce

- Set up a Bungee/Waterfall proxy.
- Set up a Paper server behind the proxy. No plugins necessary on either the proxy or the server.
- Join the network and send a chat message.
- Perform the `/server` command or any other proxy-side command.
- Send another chat message
- Get kicked -- Chat message validation failure.

### Plugin and Datapack List

No plugins. No datapacks. Fresh, clean install.

### Paper version

This server is running Paper version git-Paper-68 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 5de0f8a)

It should also be noted that I have seen this in 1.19.4 as well.

### Other

*This does no occur in regular Spigot.

I've been digging around patches/Paper source code. I haven't really been able to determine what precisely is happening. At first I thought it might be trying to log to the lastSeenMessages on these proxy commands but it doesn't appear to be interacted with in that scenario.

The actual act of kicking appears to happen in the ServerGamePacketListenerImpl#unpackAndApplyLastSeen method, but I'm unsure exactly why this workflow produces such an issue.

** Using FreedomChat does resolve this issue, so this works as a temporary workaround.

**Comment by TheFruxz** [comment]
We also had issues with chat messages and random kicks with messages like that. We use Velocity on our server, but it does not affect everyone.

**Comment by electronicboy** [comment]
Paper restores the chat system to working how it should, hence why you don't see this kick; as before, I'm fairly convinced this is a proxy issue and not a paper issue

**Comment by Travja** [comment]
md-5 doesn't seem to think [much can be done on the bungee side.](https://github.com/SpigotMC/BungeeCord/issues/3486#issuecomment-1630207360) I'm not sure what options exist here. It does seem interesting to me that this issue is present even with `enforce-secure-profile` set to false on the server.

**Comment by electronicboy** [comment]
This is not a paper issue, this is a bungee issue; my understanding is that they're defining commands improperly, as this does not happen under velocity

paper actually has the chat reporting system working, which is why we're vunerable to this and spigot is not

**Comment by Ghost-chu** [comment]
> This is not a paper issue, this is a bungee issue; my understanding is that they're defining commands improperly, as this does not happen under velocity
> 
> paper actually has the chat reporting system working, which is why we're vunerable to this and spigot is not

Paper brings back the chat reporting system but that definitely broke compatibility with BungeeCord/WaterFall, and unfortunately there are tons of plugins that don't support Velocity, which prevented me from moving to Velocity so I had to keep using BungeeCord/WaterFall.

I think Paper should add a configuration section for disabling the chat reporting system or make a patch to WaterFall (The program is apparently still being maintained). 

It's definitely a bad thing if players are always kicked with the default configuration and without any significant server-side alert or documentation. It confused users and brings the unstable and bad experience to end users.

**Comment by electronicboy** [comment]
We're not disabling the system, that's a firm stance we've got

afaik, this is patchable in waterfall, but, I don't have functional hardware to be able to look into that

**Comment by rrvk** [comment]
I am using paper and waterfall but i dont have these issues when i type /server <name>

**Comment by electronicboy** [comment]
if you jump servers using the command it doesn't matter, as mojang will reset the chain and stuff when the login packet is sent to the client, thus mitigating the issue

**Comment by Travja** [comment]
Per md-5,
> I don't see what bungee can do about this or what can be done aside from disabling chat validation on the server.
> 
> You can't have a proxy and strict chat validation - as soon as a message or command is intercepted by the proxy (eg, as a result of using a proxy command), the validation is broken. That's by design and the purpose of the validation system.
> 
> The only thing bungee could do is also send the command to the backend server, which would result in an unknown command error on the server every time a proxy command is used. This is obviously undesirable and doesn't solve the event cancellation issue.

So from the looks of things, it doesn't look like there is interest in making adjustments from the Bungee side, or the Paper side--which means the only real "solution" in this case is to use a third party plugin to completely disable chat verification by intercepting chat packets.

**Comment by electronicboy** [comment]
This is working fine for velocity

**Comment by Travja** [comment]
How does Velocity handle things differently that still allows commands to be run/intercepted at the proxy-level, but still inform the server without actually _running_ them on the server?

**Comment by Outfluencer** [comment]
> This is working fine for velocity

how? If the server has chat validation enabled and the proxy is dropping a chat packet, should the server not kick the player as it is intended because the proxy is modifing or change the order of the chat messages?

**Comment by Outfluencer** [comment]
Or is there any security issue on mojangs site that velocity is abusing internally?

**Comment by electronicboy** [comment]
Because arguments don't need to be signed unless the server requires it is my understanding

**Comment by AlexanderMoebius** [comment]
Are there any news regarding this issue?

**Comment by electronicboy** [comment]
Nope, and I don't have a computer usable for working and testing so this
probably won't work for a while, best advice would be to use a plugin to
strip all incoming signature stuff id guess in the meantime

**Comment by electronicboy** [comment]
This issue has been mitigated for velocity, fwiw

**Comment by electronicboy** [comment]
And for waterfall
