### ISSUE TITLE
I couldn't start a server when I update it to 1.20 in termux

### ISSUE THREAD

**Issue by Tsaitou7361** [PaperSpigot/Paper#9471]
### Stack trace

```bash
$ java -jar paper-1.20.1-65.jar nogui
Starting org.bukkit.craftbukkit.Main
Unsupported Java detected (17-internal). You are running an outdated, pre-release version. Only general availability versions of Java are supported. Please update your Java version.
```
This is in command line, it didn't made any logs.
Java version is openjdk-17/stable, now 17.0-27 aarch64

### Plugin and Datapack List

I tried running with no any plugins, datapack is **FZ survival pack**

### Actions to reproduce (if known)

running server in termux with newest java version of pkg

### Paper version

1.20.1-65

**Comment by lynxplay** [comment]
Can you provide the output of `java --version` in your session ? From the looks of it you are using a java version that spigot (and hence paper) does not allow. Related to #9456

**Comment by TsaiTou2926** [comment]
openjdk version "17-internal" 2021-09-14
OpenJDK Runtime Environment (build 17-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 17-internal+0-adhoc..src, mixed mode)

**Comment by TsaiTou2926** [comment]
I installed newest java version in termux..
