### ISSUE TITLE
add an option,Monsters outside the simulated distance is instantly despawned

### ISSUE THREAD

**Issue by CatTeaA** [PaperSpigot/Paper#9476]
### Is your feature request related to a problem?

There is no need for monsters outside the simulated distance to exist, as they will not be ticked.
When the simulated distance is 5, the player moves, and the map saves many monsters because they do not disappear outside the simulated distance.
When the simulation distance is less than 8 (Within 128 tiles),Monsters outside of simulation distance do not disappear randomly
Spigot offers an option<Mob Spawn Range>also determines the maximum size of a farm as no mobs will spawn outside of this defined range(chunks).
This seems to have a problem that,Players move,if a monster appears outside the simulated distance, the monster will not disappear.
Peper has an option for this<Despawn Range (hard)>Creatures beyond this range disappear immediately.(the range limit applies both horizontally and vertically,[block ranges]) But block ranges and chunks ranges can never be a perfect fit, Beyond the simulated distance, option:Despawn Range (hard) will be invalidated, the creature will always exist

### Describe the solution you'd like.

add an option,Monsters outside the simulated distance is instantly despawned

### Describe alternatives you've considered.

Would like to add an additional option to Despawn Range (hard) with chunks ranges as the range
Any entity that falls outside the chunks ranges is instantly despawned.
(It is guaranteed that there is no need to modify the afk spots of the biological farm). <Y.>

### Other

There is no need for monsters outside the simulated distance to exist, as they will not be ticked.
When the simulated distance is 5, the player moves, and the map saves many monsters because they do not disappear outside the simulated distance.

**Comment by welove69** [comment]
> 生物生成范围与生物生成分离，当所有这些都已经可配置时，永远不会有这样做的选项？这听起来像是导致问题的配置错误

yes，The simulation distance is less than 8 and if the player has moved，The monster will be outside the simulated distance and will not disappear randomly

**Comment by electronicboy** [comment]
So, you need to configure the hard despawn ranges accordingly, there is probably some tweaks to be made to how the chunk system handles how the ticking levels work, but, this option is purely a configuration option issue on your side; theres no means that an extra set of hard despawn range option would fix anything here; the mobs outside of the sim chunks aren't ticking, and so their hard despawn logic doesn't work; you need to remove them *before* they hit that state

**Comment by welove69** [comment]
> 因此，您需要相应地配置硬 despawn 范围，可能需要对块系统如何处理滴答级别的工作方式进行一些调整，但是，此选项纯粹是您这边的配置选项问题;没有办法额外的一组硬重生范围选项可以解决这里的任何问题;模拟游戏块之外的生物没有滴答作响，因此他们的硬重生逻辑不起作用;您需要在它们达到该状态_之前_删除它们

sorry,Peper has an option for this<Despawn Range (hard)>
But check Y, I don't want to affect Y, it's best to use chunks ranges as the range
(It is guaranteed that there is no need to modify the afk spots of the biological farm)

**Comment by electronicboy** [comment]
so, best option really would be to add an option to let the y check essentially be configurable, rather than trying to marry two systems together senselessly?

**Comment by welove69** [comment]
> 因此，最好的选择真的是添加一个选项，让 Y 检查基本上是可配置的，而不是试图毫无意义地将两个系统结合在一起？
Yes, yes, I use translation software, thank you for understanding
thank you

**Comment by welove69** [comment]
> 因此，最好的选择真的是添加一个选项，让 Y 检查基本上是可配置的，而不是试图毫无意义地将两个系统结合在一起？

be to add an option to let the y check essentially be configurable, or Any entity that falls outside the chunks ranges is instantly despawned, It seems to be all good

**Comment by welove69** [comment]
I sorted out my language again
<Mob Spawn Range> are (chunks ranges)
<simulated distances> are (chunks ranges)
<Despawn Range (hard)> are (block ranges)
When the Despawn Range (hard) value is greater than the simulated distances, the creature will always exist
Decrease this value below vanilla default means that the afk spots on mob farms would also need to be adjusted within the new as the range limit applies both horizontally and vertically.
A new option,Any entity that falls outside the chunks ranges is instantly despawned.
Perfect fit for < Mob Spawn Range > and < simulated distances>

**Comment by welove69** [comment]
<Mob Spawn Range> are (chunks ranges)
<simulated distances> are (chunks ranges)
<Despawn Range (hard)> are (block ranges)
When the Despawn Range (hard) value is greater than the simulated distances, the creature will always exist
Decrease this value below vanilla default means that the afk spots on mob farms would also need to be adjusted within the new as the range limit applies both horizontally and vertically.
A new option,Any entity that falls outside the chunks ranges is instantly despawned.
Perfect fit for < Mob Spawn Range > and < simulated distances>

**Comment by welove69** [comment]
> I sorted out my language again Mob Spawn Range are (chunks ranges)
> 
> simulated distances are (chunks ranges)
> 
> Despawn Range (hard) are (block ranges)
> 
> When the Despawn Range (hard) value is greater than the simulated distances, the creature will always exist Decrease this value below vanilla default means that the afk spots on mob farms would also need to be adjusted within the new as the range limit applies both horizontally and vertically. A new option,Any entity that falls outside the chunks ranges is instantly despawned. Perfect fit < Mob Spawn Range > and < simulated distances> can be adjusted at will

Or add an option
Monsters outside the simulated distance disappear instantly
Because monsters outside the simulated distance do not disappear randomly
Prevent monsters from always remaining outside the simulated distance

**Comment by welove69** [comment]
> I sorted out my language again Mob Spawn Range are (chunks ranges)
> 
> simulated distances are (chunks ranges)
> 
> Despawn Range (hard) are (block ranges)
> 
> When the Despawn Range (hard) value is greater than the simulated distances, the creature will always exist Decrease this value below vanilla default means that the afk spots on mob farms would also need to be adjusted within the new as the range limit applies both horizontally and vertically. A new option,Any entity that falls outside the chunks ranges is instantly despawned. Perfect fit < Mob Spawn Range > and < simulated distances> can be adjusted at will

Or add an option
Monsters outside the simulated distance disappear instantly
Because monsters outside the simulated distance do not disappear randomly
Prevent monsters from always remaining outside the simulated distance

**Comment by welove69** [comment]
> ### 您的功能请求是否与问题相关？
> 当模拟距离小于8（128格以内）时，模拟距离外的怪物不会随机消失 Spigot提供了一个选项还可以确定农场的最大大小，因为在此定义范围（块）之外不会生成生物。这似乎有一个问题，如果怪物出现在模拟距离之外，怪物不会消失。佩珀对此有一个选择<重生范围（硬）>超出此范围的生物会立即消失。（范围限制适用于水平和垂直，[块范围]）但是方块范围和块范围永远不可能完美契合，超出模拟距离，在重生范围（硬）内，生物将永远存在
> 
> ### 描述您想要的解决方案。
> 添加一个选项，模拟距离外的怪物瞬间重生
> 
> ### 描述您考虑过的替代方案。
> 想向“重生范围（硬”）添加一个附加选项，并将块范围作为范围 任何超出块范围的实体都会立即消失。 （保证不需要修改生物农场的afk点）。<Y.>
> 
> ### 其他
> 模拟距离之外的怪物不需要存在，因为它们不会被勾选。当模拟距离为5时，玩家移动，地图保存了许多怪物，因为它们不会消失在模拟距离之外。



> ### 您的功能请求是否与问题相关？
> 当模拟距离小于8（128格以内）时，模拟距离外的怪物不会随机消失 Spigot提供了一个选项还可以确定农场的最大大小，因为在此定义范围（块）之外不会生成生物。这似乎有一个问题，如果怪物出现在模拟距离之外，怪物不会消失。佩珀对此有一个选择<重生范围（硬）>超出此范围的生物会立即消失。（范围限制适用于水平和垂直，[块范围]）但是方块范围和块范围永远不可能完美契合，超出模拟距离，在重生范围（硬）内，生物将永远存在
> 
> ### 描述您想要的解决方案。
> 添加一个选项，模拟距离外的怪物瞬间重生
> 
> ### 描述您考虑过的替代方案。
> 想向“重生范围（硬”）添加一个附加选项，并将块范围作为范围 任何超出块范围的实体都会立即消失。 （保证不需要修改生物农场的afk点）。<Y.>
> 
> ### 其他
> 模拟距离之外的怪物不需要存在，因为它们不会被勾选。当模拟距离为5时，玩家移动，地图保存了许多怪物，因为它们不会消失在模拟距离之外。

Re-edit

**Comment by welove69** [comment]
https://hangar.papermc.io/Kyle/harderdespawn
It seems to be achievable，But it's best if the option is provided by paper

**Comment by welove69** [comment]
https://hangar.papermc.io/Kyle/harderdespawn
If this feature becomes built-in to paper, it will be a great help for users to manage their servers!

**Comment by welove69** [comment]
> 因此，最好的选择真的是添加一个选项，让 Y 检查基本上是可配置的，而不是试图毫无意义地将两个系统结合在一起？

Hey, recently paper merged a PR and it feels great
  tracking-range-y:
    animal: default
    display: default
    enabled: false
    misc: default
    monster: default
    other: default
    player: default

Could you add a similar option for despawn-ranges(hard), which would be helpful for low simulation distances?
It would feel great

**Comment by welove69** [comment]
When the number of players reaches dozens of people, the high simulation distance cannot be afforded
add an option to let the y check essentially，there is no need to modify the afk spots of the biological farm

**Comment by electronicboy** [comment]
yes, we know, it's on the todo list for consideration.

**Comment by welove69** [comment]
> The [harderdespawn](https://hangar.papermc.io/Kyle/harderdespawn) plugin seems like it does exactly what you're asking, it removes mobs on chunk unload immediately, which allows you to keep the despawn ranges the same.

Yes I know, I'm using this plugin right now, but only when the block is unloaded, the mob disappears, the bio farm is long term afk, and it may still not work well
Despawn Range (hard)
best option really would be to add an option to let the y check essentially be configurable
