### ISSUE TITLE
Server#createExplorerMap() uses deprecated StructureType

### ISSUE THREAD

**Issue by Zymo5221** [PaperSpigot/Paper#9477]
### Expected behavior

org.bukkit.generator.structure.StructureType or/and org.bukkit.generator.structure.Structure in Server#createExplorerMap()

### Observed/Actual behavior

Deprecated org.bukkit.StructureType in the Server#createExplorerMap() method

### Steps/models to reproduce

Try using the org.bukkit.generator.structure.StructureType or org.bukkit.generator.structure.Structure in Server#createExplorerMap()

### Plugin and Datapack List

N/A

### Paper version

[21:30:27 INFO]: Checking version, please wait...
[21:30:27 INFO]: This server is running Paper version git-Paper-72 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a3c760e)
You are running the latest version
Previous version: git-Paper-71 (MC: 1.20.1)

**Comment by Machine-Maker** [comment]
Will be fixed by an existing PR https://github.com/PaperMC/Paper/pull/8643. As there was no open issue for it before, this can stay open.
