### ISSUE TITLE
Custom plugin loaders are broken.

### ISSUE THREAD

**Issue by IoIxD** [PaperSpigot/Paper#9479]
### Expected behavior

I made [a plugin](https://github.com/BlackBoxMC/blackbox) that lets me used Rust instead of Java for plugins. In order for this to be complete, I had to dig deep and make a custom plugin loader so that the loaded plugins would actually appear as plugins.

Through the help of people on the Spigot forums, I was able to get everything working, but only on Spigot itself. On paper, some issues are observed.

Well when I went to go test this to reproduce some errors I'd encountered earlier, I realized that my plugin loader class just wasn't being registered at all.

    pm = Bukkit.getServer().getPluginManager();
    pm.registerInterface(BlackBoxPluginLoader.class);

Later, when I call pm.loadPlugin (which I need to do manually because Spigot usually hasn't loaded in everything by the time I'm loading this one) null is returned.

Previously, I was also getting an error about my plugin not having "getPluginMeta" which is a thing that is only in Paper, and the error should be ignored; I can't actually put that in if I want Spigot compatibility.

### Observed/Actual behavior

The plugin should load, blocks should be unbreakable because of the libblock_break_event plugin, and there should be a timer in the console thanks to example code in the libmc_classic_mode plugin.

### Steps/models to reproduce

- [Download the plugin](https://github.com/BlackBoxMC/blackbox/releases/tag/v0.0.0)
- Compile any of the example libraries in the [Rust bindings](https://github.com/BlackBoxMC/blackbox-rs/tree/master/examples), or [download this pre-compiled one for Linux](https://github.com/IoIxD/IoIxD/blob/main/libmc_classic_mode.so), and put them in your plugins folder.
- Run the plugin.

### Plugin and Datapack List

```
> plugins
[18:59:18 INFO]: Server Plugins (1):
[18:59:18 INFO]: Bukkit Plugins:
[18:59:18 INFO]:  - BlackBox
> datapack list
[18:59:31 INFO]: There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]
[18:59:31 INFO]: There are no more data packs available
>
```

### Paper version

> This server is running Paper version git-Paper-72 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a3c760e)

**Comment by Owen1212055** [comment]
This is intentional, those methods are marked for removal and are not functional. 
This came with significant refactors due to the paper plugin system.

**Comment by IoIxD** [comment]
Wait, if they'll never be supported, why does `/plugins` show "Bukkit:" before the current plugins?

**Comment by Owen1212055** [comment]
> Wait, if they'll never be supported, why does `/plugins` show "Bukkit:" before the current plugins?

That’s because WE basically implemented our own loading system. These systems are deeply interconnected however. 

The big issue is now plugins need to be registered before the server even starts, which people using the custom plugin loader… isn’t ideal since they need a plugin manager instance. (Which happens after the server started)

**Comment by IoIxD** [comment]
I see.
This doesn't help me unless I can somehow have my plugin support Paper's system without Spigot complaining about missing Paper classes when it tries to load my plugin. Still interesting.

**Comment by IoIxD** [comment]
Your system involves overriding a "classloader" function that just returns objects that return Java jars, and then passes it into functions that aren't overridable. This isn't usable for my case.

I understand the system is incomplete, try and let me know when making a PluginLoader that can load non-java plugins is possible.

**Comment by Owen1212055** [comment]
I mean, it's not going to be possible. Again, plugins can only be registered before the server even starts, it's not possible for us to reimplement this API with what we are trying to achieve here.

**Comment by electronicboy** [comment]
I have nothing against adding something for this, but it would require a chunk of effort to get a system able to inject stuff even earlier within the system, which, given that we've not actually really seen an implementation of this system in the wild which got much usage, we weren't exactly able to cater for this sort of setup, especially with the requirements of bootstrapping stuff *much* earlier into the JVM

**Comment by IoIxD** [comment]
Forgive me for not understanding but, if a custom plugin loader can't support non-Java plugins, what's the point? Why would you want to create a custom plugin loader if you can't do anything that the existing one doesn't do?

**Comment by IoIxD** [comment]
Oh wait, you mean YOUR api will be removed in the future?
I thought you meant the legacy Spigot one my bad.

**Comment by electronicboy** [comment]
The legacy spigot one will be removed, as the system doesn't conform to the needs of needing to load stuff much earlier in the startup process; The existing plugin loader stuff means that you'd miss the ability to do a good chunk of stuff which over time will become more critical to the server;

in order to support custom plugin types, we'd probably need to find a way to have some way for stuff to hook in even earlier, so that they can provide their own plugin providers or something; I don't have a functionable enough PC to begin investigating this sorta stuff though, easy option I'd imagine would probably be to just have a folder of plugin provider jars or something, rather than tryna hook it too deeply into the current thing, but, idk what all would need to change, I don't think anybody knew that anybody was maintaining anything that used this API

**Comment by IoIxD** [comment]
It might be worth mentioning that I'm actually not the only one. The person on spigotmc.org who helped me with this [linked me to a plugin for Python plugins that does the same thing](https://github.com/pyplugins/pyplugins/blob/5bd1d3bd3773b5536dce7e3e2aaeea3179dee6aa/src/main/java/com/dmytrohoi/pyplugins/PythonLoader.java#L74-L92).

I'm willing to implement work arounds so that some of the same features can be done in Paper without this functionality. It'll just suck to do because I've spent several weeks on this plugin and I was hoping that the simplest solution to many problems would be viable. But if I want Paper compatibility then I suppose it's not.

**Comment by IoIxD** [comment]
Also worth noting that I was on board the idea  of writing an entirely seperate main class for spigot support. If you did add a feature I could use, then I'd probably take it.
