### ISSUE TITLE
Stacktrace Error: Array index out of range: -1

### ISSUE THREAD

**Issue by SilverDFlame** [PaperSpigot/Paper#9481]
### Stack trace

https://pastebin.com/AwatpK6h

### Plugin and Datapack List

Server Plugins (0):
Bukkit PLugins (0):
There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]

### Actions to reproduce (if known)

Edit paper-global.yaml:
```
chunk-system:
  gen-parallelism: default
  io-threads: 2
  worker-threads: 4
```
Update from git-Paper-54 to git-Paper 72

### Paper version

Paper version git-Paper-72 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a3c760e)

### Other

Global Config at time of issue:
https://pastebin.com/NFNjvFBG

@SnifferSniffEvent on Discord in the [#paper-help](https://discord.com/channels/289587909051416579/289587909051416579/1129121988133273610) channel suggested resetting chunk-system threads back to -1

This seems to have fixed the issue and allowed the server to boot up.

**Comment by Warriorrrr** [comment]
The stacktrace pastebins seem to have expired, could you re-upload them?

**Comment by SilverDFlame** [comment]
Closing issue as pastebins were wiped, and original stack traces were lost when server failed. Thanks to all the community members who initially tried to help me in Discord.
