### ISSUE TITLE
API for handling fake player entities

### ISSUE THREAD

**Issue by Romindous** [PaperSpigot/Paper#9487]
### Is your feature request related to a problem?

The issue right now, is that there's no acknowledgement in the Spigot or Paper API, of the fact that player entities can be actually created, in NMS (direct server code).

As of now, the only way to create a player entity is to make a new EntityPlayer, either directly or through super() in an extending class. Afterwards, an efficient way to display said entity to other players on the server is to use packets, including ClientboundPlayerInfoUpdatePacket, PacketPlayOutNamedEntitySpawn, PacketPlayOutRelEntity..., and PacketPlayOutEntityEquipment.

However, if you want to make it move, interact with other entities, etc..... This is where the fun begins.... since EntityPlayer does not and cannot have pathfinder goals, as the entity is meant to be controlled by a player.

### Describe the solution you'd like.

There are several ways to go about this. First of all, It would be nice if you could World.spawn(Location, EntityHuman.class), which would create said EntityPlayer and return it's CraftBukkit copy.

However, I think it would be worth to think about making a new entity class that implements Mob and EntityHuman. If there would be a way to assign pathfinder goals (as Paper already has an API for that) to this new entity, the fun part of the problem would be solved.

I haven't dug too deep into Craft(Entity) stuff, so im not sure which option would be more viable.

### Describe alternatives you've considered.

The alternative I am using right now is pretty interesting. To get a player entity, that "looks to be" moving, have a custom ai, etc, I would:
1) Create a new instance of EntityPlayer, lets call it the "bot" entity.
2) Spawn a second entity (i use a Husk, its pretty comfortable).
3) Set the bot entity's position to the Husk.
4) Assign whatever pathfinder goals you want to the Husk, such as movement, damage, etc.
5) When a player gets into the world, or loads the chunk with the Husk, intercept packets thru io.netty.channel.ChannelPipeline, and stop any outgoing packets from the Husk, such as PacketPlayOutSpawnEntity, PacketPlayOutEntityMetadata, etc.
6) At the same time, send the player the bot entity packets, mentioned in the issue description.
7) Send Entity Move packets whenever the Husk moves, so the bot entity keeps up, and then remove the bot entity, if something happens to the Husk (unloaded, killed, etc)

If you have any questions, pls ask, I can share code or elaborate further if needed!

### Other

![image](https://github.com/PaperMC/Paper/assets/64203160/12d57e43-742f-43e0-87d6-05ce25105bba)

**Comment by yannicklamprecht** [comment]
Do you want a fake player that is static only or one that can have pathfinding and mobgoals?

**Comment by XxGoldenbluexX** [comment]
That would be awesome

**Comment by gepron1x** [comment]
Is this really a papermc scope?

**Comment by electronicboy** [comment]
I just have no idea if theres a desire for us to maintain something as internal as this, especially when plugins with libraries already exist which achieve this and much more, and wouldn't rely on us having to maintain what are essentially a hack for a niche number of users
