### ISSUE TITLE
Limit join adress

### ISSUE THREAD

**Issue by DaniGTA** [PaperSpigot/Paper#9498]
### Is your feature request related to a problem?

No

### Describe the solution you'd like.

By default, players can connect to a Minecraft server using any address. For example:

mc.myserver.com:25565
1.1.1.1:25565

However, I want to restrict access to only "mc.myserver.com" or specify multiple IPs or addresses. This limitation is necessary to prevent bots from attempting to connect from various sources.

### Describe alternatives you've considered.

Searched for a plugin that can do that didnt find any.

**Comment by lynxplay** [comment]
I mean, this sounds like the job of a firewall, not the service running behind it.

**Comment by electronicboy** [comment]
This would be so trivial to do in a plugin, it makes little sense for us to maintain such a feature
