### ISSUE TITLE
Crashing when tnt is lighten up above end portal

### ISSUE THREAD

**Issue by Futurelandsmc** [PaperSpigot/Paper#9501]
### Stack trace

https://pastebin.com/ZEYbqWqd

### Plugin and Datapack List

BetterRTP, BuycraftX, CoreProtect, DecentHolograms, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, floodgate, Geyser-Spigot, GrapplingHook, GriefPrevention, GSit, LPC, LuckPerms, MotdChanger, NametagEdit, PlaceholderAPI, ProtocolLib, SilkSpawners_v2,  SkinsRestorer, *SLogin, SmoothTimber, Vault, ViaVersion, WorldEdit, WorldGuard .

Data packs
[vanilla (built-in)], [file/bukkit (world)]

### Actions to reproduce (if known)

server crashes when a tnt get dropped in end portal / when it reaches end from normal world. ( Eg you light up a tnt by placing it above end portal )

### Paper version

This server is running Paper version git-Paper-82 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: b533905)

**Comment by lynxplay** [comment]
I am having trouble replicating this at least on a clean install of paper. I know we chatted about this on discord for a while, but know the potential cause of this, can you and the players that were sending the tnt though replicate this without plugins ?

**Comment by lynxplay** [comment]
Given you have yet to provide the stacktrace asked for that does not use plugins, I'll close this.
Generally, there seem to be a plethora of issues in regards to ticking the entity scheduler after an entity was removed, e.g. #9515. 

If you can replicate this without plugins, please provide it here and I'll happily reopen it :)
