### ISSUE TITLE
Add `getAddress` to `RemoteServerCommandEvent`

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#9503]
### Is your feature request related to a problem?

Yea. I'm using this event for external command logging and I think it's absurd that it's impossible to get what client issued it.

### Describe the solution you'd like.

Add `getAddress` that returns `InetSocketAddress` of a remote client in the event.

### Describe alternatives you've considered.

I don't know.

**Comment by molor** [comment]
(please..)

**Comment by Warriorrrr** [comment]
Done by upstream in https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/533d2c446bb423cb256003114d312b9b364963d5
