### ISSUE TITLE
PLAY_ONE_MINUTE statistic doesn't work as scoreboard objective

### ISSUE THREAD

**Issue by jakelamtn** [PaperSpigot/Paper#9507]
### Expected behavior

I set up an objective where the criteria is the PLAY_ONE_MINUTE statistic, it should track a players playtime (in ticks, bad name)

### Observed/Actual behavior

It stays at 0 (or whatever you initialize it to)

### Steps/models to reproduce

Set an objective with the statistic. 
Query the score.

### Plugin and Datapack List

LuckPerms and Votifier

### Paper version

This server is running Paper version git-Paper-83 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: c793bd9)
You are running the latest version
Previous version: git-Paper-9 (MC: 1.20)

### Other

I was able to use other statistics like crouch and fly distances as objective criteria, and they worked fine.

**Comment by lynxplay** [comment]
The server generates keys for the statistics based on the enum name, which simply completely breaks the mapping between the bukkit and nms layer as PLAY_ONE_MINUTE is actually named play_time internally.

Generally a terribly scuffed system, https://github.com/PaperMC/Paper/pull/5691 might be a long term solution, for the short term, the keys should probably be explicitly defined on the enum instead of using the name.

**Comment by lynxplay** [comment]
I don't have the time today to look into this, but a short term solution over the stat api rewrite, would probably be something along the lines of
```patch
diff --git a/src/main/java/org/bukkit/Statistic.java b/src/main/java/org/bukkit/Statistic.java
index 4ce888688..d4a89b68a 100644
--- a/src/main/java/org/bukkit/Statistic.java
+++ b/src/main/java/org/bukkit/Statistic.java
@@ -22,7 +22,7 @@ public enum Statistic implements Keyed {
     /**
      * Name is misleading, actually records ticks played.
      */
-    PLAY_ONE_MINUTE,
+    PLAY_ONE_MINUTE(Type.UNTYPED, NamespacedKey.minecraft("play_time")), // Paper - use correct key.
     TOTAL_WORLD_TIME,
     WALK_ONE_CM,
     WALK_ON_WATER_ONE_CM,
@@ -101,6 +101,13 @@ public enum Statistic implements Keyed {
         this(Type.UNTYPED);
     }
 
+    // Paper start - specify namespaced key for incorrectly named enum constants
+    private Statistic(/*@NotNull*/ Type type, NamespacedKey key) {
+        this.type = type;
+        this.key = key;
+    }
+    // Paper end - specify namespaced key for incorrectly named enum constants
+
     private Statistic(/*@NotNull*/ Type type) {
         this.type = type;
         this.key = NamespacedKey.minecraft(name().toLowerCase(Locale.ROOT));
```

**Comment by lynxplay** [comment]
Until fixed, you can create the criteria via `Criteria.create("minecraft.custom:minecraft.play_time")`.
