### ISSUE TITLE
Proxy option to add server-adress which inclides port 

### ISSUE THREAD

**Issue by Tizooo** [PaperSpigot/Paper#9512]
### Is your feature request related to a problem?

If secret key gets leaked (which can happen in many ways) your server gets griefed or more

### Describe the solution you'd like.

Hey i would love to see a option similar to server-ip in server.properties named something like server-adress where we can put in the ip and port of our proxy. This way if using modern forwarding for example you can setup the server-adress option to point to your proxy so if your secret key gets leaked you still would have a second firewall protecting you. This would be good for gameservers etc where you cant use iptables or similar. 

### Describe alternatives you've considered.

Plugins. But most are outdated or harder to use

**Comment by lynxplay** [comment]
I mean, exact same reasons response as to https://github.com/PaperMC/Paper/issues/9498.
This is trivial to develop via a plugin.

**Comment by electronicboy** [comment]
1) None of the API around that stuff has changed in years, so I really doubt that any such plugin would not work
2) This is such a fake assurance of security, especially as the primary usecase for this sort of setup is going to be on shared hosts where you have multiple people sharing the same IP address

I don't think this is in any of our interests to try to maintain such false sense of security
