### ISSUE TITLE
EntityMountEvent does not fire, VehicleEnterEvent fires incorrectly

### ISSUE THREAD

**Issue by KioProject123** [PaperSpigot/Paper#9514]
### Expected behavior

EntityMountEvent fires and VehicleEnterEvent doesn't fire when player mounts mob

### Observed/Actual behavior

After version `#63 c0936a71bd762a5a87425a24cfb9daff7418a4d4`.
Riding a mob will not fire EntityMountEvent, but will fire VehicleEnterEvent.
Leaving a mob will fire both EntityDismountEvent and VehicleExitEvent simultaneously.
Use horses when testing.
![image](https://github.com/PaperMC/Paper/assets/61594596/aeae9ff9-f8c7-4785-b266-dfd643fa663b)

At version `#62 4356758b645f3d4d91268ac40cd3b682eb3faecf`.
Riding a mob will fire both EntityMountEvent and VehicleEnterEvent.
Leaving a mob will fire both EntityDismountEvent and VehicleExitEvent simultaneously.
Use horses when testing.
![image](https://github.com/PaperMC/Paper/assets/61594596/34c58c6f-b668-49a4-8001-0f4ceaaa01dd)

### Steps/models to reproduce

1. Write a plugin to listen to EntityMountEvent, VehicleEnterEvent, EntityDismountEvent and VehicleExitEvent.
2. Ride a horse.

### Plugin and Datapack List

Use a blank server

### Paper version

[22:40:50 INFO]: Checking version, please wait...
[22:40:52 INFO]: This server is running Paper version git-Paper-83 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: c793bd9)

**Comment by KioProject123** [comment]
This should have been repaired upstream（ https://github.com/PaperMC/Paper/pull/9485 ）
`Spigot Changes:
3374045a SPIGOT-7431: Fix EntityMountEvent returning opposite entities`

But not sure if the problem that riding mobs will fire VehicleEnterEvent and VehicleExitEvent should be fixed.

**Comment by Machine-Maker** [comment]
> EntityMountEvent fires and VehicleEnterEvent doesn't fire when player mounts mob

Your "Expected Behavior" doesn't seem to jive with the issue that the behavior before was that both events fire for mounting and dismounting.

**Comment by Machine-Maker** [comment]
@KioProject123 I cannot replicate your results where only one event fires for horses. I added all 4 listeners, and when I clicked on a horse, it printed both the VehicleEnterEvent and EntityMountEvent and dismounting fired VehicleExitEvent and EntityDismountEvent.

Can you verify that only this exact setup of listeners produces the results you said?
```java
@EventHandler
public void onEvent(EntityMountEvent event) {
    System.out.println(event.getEventName());
}

@EventHandler
public void onEvent(VehicleEnterEvent event) {
    System.out.println(event.getEventName());
}

@EventHandler
public void onEvent(EntityDismountEvent event) {
    System.out.println(event.getEventName());
}

@EventHandler
public void onEvent(VehicleExitEvent event) {
    System.out.println(event.getEventName());
}
```

**Comment by KioProject123** [comment]
> @KioProject123 I cannot replicate your results where only one event fires for horses. I added all 4 listeners, and when I clicked on a horse, it printed both the VehicleEnterEvent and EntityMountEvent and dismounting fired VehicleExitEvent and EntityDismountEvent.
> 
> Can you verify that only this exact setup of listeners produces the results you said?
> 
> ```java
> @EventHandler
> public void onEvent(EntityMountEvent event) {
>     System.out.println(event.getEventName());
> }
> 
> @EventHandler
> public void onEvent(VehicleEnterEvent event) {
>     System.out.println(event.getEventName());
> }
> 
> @EventHandler
> public void onEvent(EntityDismountEvent event) {
>     System.out.println(event.getEventName());
> }
> 
> @EventHandler
> public void onEvent(VehicleExitEvent event) {
>     System.out.println(event.getEventName());
> }
> ```

I made a mistake. I use the following way to test:
>     @EventHandler
>     public void onEvent(EntityMountEvent event) {
>         event.getEntity().sendMessage("EntityMountEvent");
>     }
Because of `SPIGOT-7431`, this message was actually sent to the horse.
This should be fixed in the next upstream update, which is here https://github.com/PaperMC/Paper/pull/9485

**Comment by Machine-Maker** [comment]
Ok, so the issue doesn't have anything to do with events not firing that fired before, but just that the entities returned changed.

**Comment by lynxplay** [comment]
Should have been fixed by the upstream update.
If something is still off, feel free to comment, we'll happily reopen the issue :)
