### ISSUE TITLE
 Problem

### ISSUE THREAD

**Issue by Spartan302** [PaperSpigot/Paper#9516]
### Timings or Profile link

no

### Description of issue

The reason is that the server does not take more than 11 GB of RAM, although there are more and the servers lag very much, since the kernel does not take more than 11 GB of RAM, what is the reason for this and how to fix it

### Plugin and Datapack List

no 

### Server config files

```
Paste configs or paste.gg link here!
```
а

### Paper version

1.20.1

**Comment by electronicboy** [comment]
1. Memory is memory, throwing more memory at the thing is not going to
change much if your bottleneck is elsewhere, i.e. generally the CPU
2. This is not the place for support, please use the discord/forums
