### ISSUE TITLE
PlayerInteractEvent does not fire when looking too close to a hitbox

### ISSUE THREAD

**Issue by KillerCreeper112** [PaperSpigot/Paper#9523]
### Expected behavior

PlayerInteractEvent should get called when right/left clicking _near_ an entity's hitbox.

### Observed/Actual behavior

PlayerInteractEvent does not get called when right/left clicking within a certain distance of an entity's hitbox.
See the images provided for examples:

EntityDamageEvent gets called (intended): https://pasteboard.co/3LB6DTB1Kj7n.png
PlayerInteractEvent gets called (intended): https://pasteboard.co/cbXF7wv5Y4K0.png
PlayerInteractEvent does not called (not intended): https://pasteboard.co/UkKbxpqkJGaS.png

### Steps/models to reproduce

1. Using the code provided below, I spawned an entity like so: /summon husk ~ ~ ~ {NoAI:1b}
I've also tried it with mobs with AI (no AI makes it easier to test) which produce the same result. I believe it just needs to be an entity with a hitbox.

2. Then punch or right click around and PlayerInteractEvent should get called until you put your cursor near an entity's hitbox.
```

@EventHandler
    public void onPlayerArmSwing(PlayerArmSwingEvent event) {
        Bukkit.broadcast(Component.text("arm"));
    }

    @EventHandler
    public void onPlayerInteractAtEntity(PlayerInteractAtEntityEvent event) {
        Bukkit.broadcast(Component.text("interact at entity"));
    }
    
    @EventHandler
    public void onEntityDamageByEntity(EntityDamageEvent event) {
        Bukkit.broadcast(Component.text("hit"));
    }
    
     @EventHandler
    public void onPlayerInteract(PlayerInteractEventevent) {
        Bukkit.broadcast(Component.text("interact"));
    }
```

### Plugin and Datapack List

- CustomPlugin

### Paper version

This server is running Paper version git-Paper-17 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: c287e92)
You are running the latest version
Previous version: git-Paper-12 (MC: 1.20)

### Other

You can check these images to see exactly what I mean.

EntityDamageEvent gets called (intended): https://pasteboard.co/3LB6DTB1Kj7n.png
PlayerInteractEvent gets called (intended): https://pasteboard.co/cbXF7wv5Y4K0.png
PlayerInteractEvent does not called (not intended): https://pasteboard.co/UkKbxpqkJGaS.png

**Comment by electronicboy** [comment]
try updating, 1.20 is dead

**Comment by KillerCreeper112** [comment]
Oh I thought I was on the latest.

**Comment by KillerCreeper112** [comment]
Updating resolved the issue.
This server is running Paper version git-Paper-90 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 383f0ed)
You are running the latest version
Previous version: git-Paper-17 (MC: 1.20)
