### ISSUE TITLE
The locate command hasn't been updated/merged

### ISSUE THREAD

**Issue by LinearBotSystems** [PaperSpigot/Paper#9524]
### Expected behavior

get some output like :
The nearest minecraft:shipwreck is at  [-5522 ,~, 1455]

### Observed/Actual behavior

Too many arguments.
/locate [player] 

### Steps/models to reproduce

/locate structure minecraft:shipwreck

### Plugin and Datapack List

Worldedit,Worldguard ,mcMMO, Multiverse

### Paper version

This server is running Paper version git-Paper-91 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: d8b8f61)
You are running the latest version
Previous version: git-Paper-83 (MC: 1.20.1)

### Other

In 1.19 some commands were merged into /locate . 
    /locate structure <structure>
    /locate biome <biome>
    /locate poi <poi>

While the old commands were removed . The new weren't merged/ added to /locate

**Comment by electronicboy** [comment]
Not a paper issue, you have a plugin replacing the vanilla command

**Comment by kidwellj** [comment]
Comments above aren't massively helpful or explicit - so to be clear it's worth being aware that WorldGuard duplicates the /locate command, which is a problem, but you can simply specify in this scenario that you want to use the minecraft version of the command and bypass the WorldGuard version: `/minecraft:locate biome minecraft:savanna`. 

H/t here: https://github.com/EngineHub/WorldGuard/issues/2013#issuecomment-1615977690
