### ISSUE TITLE
Death screen does not appear again when a player reconnects

### ISSUE THREAD

**Issue by Zjaun** [PaperSpigot/Paper#9526]
### Expected behavior

When a player dies and disconnects/quits the server/world, and reconnects/joins again, the death screen must be displayed.

### Observed/Actual behavior

The death screen does not appear to the player and they seem to be stuck forever (cannot teleport, cannot kill).

### Steps/models to reproduce

1. The server must be at least 1.20.1 (not tested in 1.20, bug is not present in 1.19.4 below)
2. Kill a player
3. Kick, disconnect, or go to the main menu while the death screen is still present
4. Rejoin
5. Bug

https://github.com/PaperMC/Paper/assets/91415509/9e7e8bbf-cd29-4ff7-a29f-e405a9ece039

### Plugin and Datapack List

![Screenshot 2023-07-23 194214](https://github.com/PaperMC/Paper/assets/91415509/1576b118-eb27-4c71-8cd6-9a4a681bd44c)

### Paper version

> version
[19:43:04 INFO]: Checking version, please wait...
[19:43:05 INFO]: This server is running Paper version git-Paper-95 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: aa93dcf)
You are running the latest version

**Comment by Owen1212055** [comment]
<img width="2036" alt="Screenshot 2023-07-23 at 1 28 07 PM" src="https://github.com/PaperMC/Paper/assets/23108066/7c36133e-62c2-40ed-9b4a-5972817afa5e">
I'm not able to reproduce this, are other people able to experience this?

**Comment by Zjaun** [comment]
Setting this as closed; the issue persists when [FastLoad](https://modrinth.com/mod/fastload) is installed on the client.

**Comment by Owen1212055** [comment]
Thank you! 😄
