### ISSUE TITLE
Option to disable game mechanic modification

### ISSUE THREAD

**Issue by ilgrandeanonimo** [PaperSpigot/Paper#9527]
### Is your feature request related to a problem?

An inconvenience that many users find in paper is that it modifies some game mechanics. 

### Describe the solution you'd like.

That's why I think an option that disables everything that modifies the game.

### Describe alternatives you've considered.

Else a page on the site where it says how to set up the server to make it as close as possible to a vanilla server would be handy and useful.

**Comment by electronicboy** [comment]
Most game mechanic modifications are bug fixes and mechanical changes derived from the work required for plugins; by default, the server should be as close to vanilla as can be

outside of that, theres very little interest in creating such documentation, we've asked for help with it for years and have gotten no biters
