### ISSUE TITLE
Server crashed for unknown reason

### ISSUE THREAD

**Issue by ch4ika** [PaperSpigot/Paper#9528]
### Stack trace

https://paste.gg/p/anonymous/e1865f57c6b9414dbdf8dfc1c32cfc4c

### Plugin and Datapack List

datapacks: vanilla, file/bukkit

### Paper version

This server is running Paper version git-Paper-95 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: aa93dcf)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Purpur-2016 (MC: 1.20.1)

**Comment by Owen1212055** [comment]
Definitely the case, please see if you can reproduce without plugins. If so, feel free to leave a comment.
