### ISSUE TITLE
Make a PaperConfigBuilder for Worlds created via Plugin

### ISSUE THREAD

**Issue by Doc94** [PaperSpigot/Paper#9536]
### Is your feature request related to a problem?

Currently i wanna create a world with specific paper config via plugin.

### Describe the solution you'd like.

Make a PaperWorldConfigurationBuilder for create a custom set of config and include that in the World Creator.

### Describe alternatives you've considered.

Like said the electrical cat in discord the alternative is create the world copy a paper config into the directory and unload/reload the world for handle this.

**Comment by Machine-Maker** [comment]
Can't you copy the config you want into the directory that the world will use and then create it? I don't think it deletes anything already in the directory.

**Comment by Doc94** [comment]
> Can't you copy the config you want into the directory that the world will use and then create it? I don't think it deletes anything already in the directory.

i really dont test that.. but if directory exists this not handle a issue or any?

**Comment by lynxplay** [comment]
I do not like this feature request. There is a reason config for now is not exposed to the API, it is pretty much implementation detail, nothing in there is backwards compatible and I'd really not want to start setting that expectation by exposing it to some form of world creator API.

I think MMs suggestion here is correct. You can compute the world folder name (well by its name) . E.g. something like
```java
final YamlConfiguration yamlConfiguration = new YamlConfiguration();
yamlConfiguration.set("_version", 30); // The version of the config this plugin is developed against, allows paper to run migrations.
yamlConfiguration.set("entities.behavior.disable-creeper-lingering-effect", true);
final Path configPath = Bukkit.getWorldContainer().toPath().resolve(test.name()).resolve("paper-world.yml");
if (!Files.exists(configPath)) {
    try {
        Files.createDirectories(configPath.getParent());
        Files.writeString(configPath, yamlConfiguration.saveToString());
    } catch (final IOException e) {
        throw new RuntimeException("Failed to write world config for world", e);
    }
}
``` seems to work just fine for me.

I'll be closing this as this works, is as version agnostic (honestly, even more given we can run migrations for you here) than an API would be and does not require us to expose the configuration to the API layer.
