### ISSUE TITLE
block.breakNaturally() disable block item drop

### ISSUE THREAD

**Issue by bkgktp** [PaperSpigot/Paper#9547]
### Is your feature request related to a problem?

<img width="1367" alt="image" src="https://github.com/PaperMC/Paper/assets/101702786/c45f0935-77ff-43b1-95e5-67c628251007">
When I artificially break blocks with this method, I want a setting that will only leave block particles. it should just be able to simulate breaking a block and not drop any items, just add the value "vanillaDrop=boolean".

### Describe the solution you'd like.

Just a simple setting to prevent it from dropping items in block.breakNaturally().

### Describe alternatives you've considered.

To use this feature, I create a specific BlockState value and a globalBlockId value for each block data by using the `StateTypes.NOTE_BLOCK.createBlockState()` method from the _PacketEvents_ library, so I can simulate breaking of note blocks and various blocks.

<img width="1222" alt="image" src="https://github.com/PaperMC/Paper/assets/101702786/34036a5f-196b-4882-882b-f2bd23f17016">

### Other

<img width="432" alt="image" src="https://github.com/PaperMC/Paper/assets/101702786/9e4a8b1d-79bf-496d-acb0-32f6175309a9">

**Comment by bkgktp** [comment]
Sorry I didn't specify above that I am using globalID with package 2001, here is an example to simulate block particles.

```
    private void breakBlock(Location location) {
        PacketContainer packet = protocolManager.createPacket(PacketType.Play.Server.WORLD_EVENT);

        packet.getIntegers().write(0, 2001);
        packet.getBlockPositionModifier().write(0, new BlockPosition(location.toVector().getBlockX(), location.toVector().getBlockY(), location.toVector().getBlockZ()));
        packet.getIntegers().write(1, this.getBlockStateId());
        packet.getBooleans().write(0, false);

        try {
            for (final Entity entity : location.getWorld().getNearbyEntities(location, 16, 16, 16))
                if (entity instanceof Player viewer)
                    protocolManager.sendServerPacket(viewer, packet);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

**Comment by Machine-Maker** [comment]
this feels really against the whole concept of break block naturally. You aren't breaking it naturally then. If you want to play break particles, can't you already do that with API and sending a custom particle?

**Comment by bkgktp** [comment]
this does not work for BlockState. @Machine-Maker

**Comment by Machine-Maker** [comment]
Then I think that is the correct feature request. It should accept BlockData there, but doesn't currently, only Material.

**Comment by bkgktp** [comment]
When will this feature be added to the library? @Machine-Maker

**Comment by pop4959** [comment]
> When will this feature be added to the library? @Machine-Maker

An alternative method of doing this will be added via https://github.com/PaperMC/Paper/pull/9548 when merged.

**Comment by bkgktp** [comment]
#9548 I see that claim numbered has been corrected. So how can I make the block artificially break without dropping any items, how does that solve my problem and how can I use it? @pop4959

**Comment by Machine-Maker** [comment]
Use the `STEP_SOUND` effect with the block data after you set the type of the block. That will change the block while playing the effect.

**Comment by bkgktp** [comment]
block.getWorld().playEffect(block.getLocation(), Effect.STEP_SOUND);

I don't quite understand, what data should I enter in the data section? Will it break the block proper to BlockData? can you send me a sample? @Machine-Maker

**Comment by Machine-Maker** [comment]
You need to supply the BlockData for the block you want to break as data
