### ISSUE TITLE
Methods inherited from Audience in Player class aren't detected

### ISSUE THREAD

**Issue by giopera** [PaperSpigot/Paper#9549]
### Expected behavior

Actually i expect to be able to use all the methods from the Audience interface on a Player object that on the JavaDocs are listed as inherited
![immagine](https://github.com/PaperMC/Paper/assets/89829281/d6eaed74-093a-4ce0-a17a-83a50b906f9f)

### Observed/Actual behavior

My IDE and also the maven cli command return to me an error where they can't find any suitable method for sendActionBar.
`[ERROR] /home/giopera06/PoliceCore/src/main/java/me/policecore/listeners/ManetteEvent.java:[62,14] cannot find symbol`
`[ERROR]   symbol:   method sendActionBar(net.kyori.adventure.text.TextComponent)`
`[ERROR]   location: variable p of type org.bukkit.entity.Player`
![immagine](https://github.com/PaperMC/Paper/assets/89829281/534d5602-cada-4d48-8245-7b5d0dcd4dbb)
Also all the sendMessage methods with the TextComponent aren't working

### Steps/models to reproduce

I don't know what happened, i only know that it happened after I've updated the maven libraries from my IDE 

### Plugin and Datapack List

I'm not running on a server

### Paper version

I'm not running on a server but the version of the dependency is 1.16.5-R0.1-SNAPSHOT

**Comment by lynxplay** [comment]
Hi thanks for reaching out!
The github issue tracker is not really a place to nicely discuss a build tool problem in an outdated version.
I'll close this an invalid, please head to the #paper-dev discord channel on our [discord](https://discord.gg/papermc) for some help here, I am sure someone is capable of helping you there :)
