### ISSUE TITLE
how to disable villagers respawning(despawning)?

### ISSUE THREAD

**Issue by DanRick001** [PaperSpigot/Paper#9550]
### Expected behavior

my players are facing the problem of respawning(despawning) villagers in their homes

### Observed/Actual behavior

sometimes my player's villagers respawning(they have their houses with villagers. they trade with them)

### Steps/models to reproduce

idk

### Plugin and Datapack List

![2023-07-29_20 41 31](https://github.com/PaperMC/Paper/assets/104103241/597d991d-f6b8-41b3-8e62-58e9e755c793)

### Paper version

1.16.5-R0.1-SNAPSHOT

**Comment by electronicboy** [comment]
Unsupported version of paper, nor is this the place for support
