### ISSUE TITLE
Server crashes when using plugin (GriefPrevention) on Paper server but not on Spigot server.

### ISSUE THREAD

**Issue by GregorSomething** [PaperSpigot/Paper#9551]
### Expected behavior

Server should not crash when sending primed tnt through end portal and using GriefPrevention plugin (did not crash Spigot server).

### Observed/Actual behavior

Server crashes on Paper server.

### Steps/models to reproduce

1. Get end portal
2. Send a primed tnt through it, when GriefPrevention is enabled (defaut config)
3. Server crashed ([https://pastebin.com/XCUpWv8J](https://pastebin.com/XCUpWv8J))

### Plugin and Datapack List

[10:28:14 INFO]: Server Plugins (1):
[10:28:14 INFO]: Bukkit Plugins:
[10:28:14 INFO]:  - GriefPrevention

### Paper version

This server is running Paper version git-Paper-100 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: f402f89)

### Other

[Plugin download page](https://dev.bukkit.org/projects/grief-prevention/files)

**Comment by alek4032** [comment]
We just experienced the same, multiple times in a row. Same plugins, same method.

**Comment by lynxplay** [comment]
Replicable yea, we are passing the already retired entity scheduler to the freshly created tnt instance in the end dimension.

**Comment by lynxplay** [comment]
Resolved by 408a9050baf29341b877a7bebff0939442d818d0
