### ISSUE TITLE
Damage from a falling dripstone is inaccurate

### ISSUE THREAD

**Issue by xKomer** [PaperSpigot/Paper#9555]
### Expected behavior

When you wear a helmet in Minecraft, damage from a falling anvil or a falling pointed dripstone should be reduced by 1/4. However, because vanilla Minecraft doesnt reduce the damage by 1/4 since a few version ago (which is not intended, i guess), i at least expected it to be the same amount of damage, when you are wearing only boots and when you are wearing only a helmet.

The first Screenshot is after getting hit by a dripstone while only wearing boots, max Health is 100, so the damage was 11.712 health. Second screenshot is only wearing a helmet and getting the same damage.

Third screenshot is while wearing everything except a helmet and getting 5.1953 damage. Fourth screenshot is wearing everything except for boots and getting 5.1953 damage, too.

Those Screenshots are from my Singleplayer test.

![2023-07-31_08 00 18](https://github.com/PaperMC/Paper/assets/141004145/8129ecc1-bad6-4747-88ce-fde492b02c94)
![2023-07-31_08 00 59](https://github.com/PaperMC/Paper/assets/141004145/0ffa16ea-6aa9-4f17-a69b-d4c05c8c970c)
![2023-07-31_08 01 17](https://github.com/PaperMC/Paper/assets/141004145/daa201e1-b296-4bf4-8fdf-82600bb1cf84)
![2023-07-31_08 01 43](https://github.com/PaperMC/Paper/assets/141004145/1b630175-9309-49d2-9f3f-9b549eb1e42a)

### Observed/Actual behavior

When i tested a plugin, where i wanted to rewrite the damage system of minecraft a little bit, i saw that a I get more damage when I wear a helmet than just boots. But this only happened with pointed Dripstone. Anvils, on the other hand, had the reduced damage that Vanilla minecraft doesnt have anymore. This is a weird behaviour, because i expected anvils and pointed dripstone to be treated exactly the same.

The first Screenshot is after getting hit by a dripstone while only wearing boots, the damage was 11.712. Second screenshot is only wearing a helmet and getting 11.784 damage (0.072 more!)

Third screenshot is while wearing everything except a helmet and getting 5.1953 damage. Fourth screenshot is wearing everything except for boots and getting 6.6424 damage (which is 1.4471 health more damage, nearly a heart!)

Those Screenshots are from my Server. The "What it should be"-damage is what it would be if you first multiplied the damage by 0.75 when wearing a helmet, then applying all of the other rules (damage-reduction by armor). Formula is correct i think, at least it outputs the right damage when getting hit by an anvil.

![2023-07-31_07 56 04](https://github.com/PaperMC/Paper/assets/141004145/7e5a0a4f-bf69-4534-aab7-78575d5bc842)
![2023-07-31_07 55 48](https://github.com/PaperMC/Paper/assets/141004145/9a03964f-ac11-4f08-8dac-6bfd7040eace)
![2023-07-31_07 57 19](https://github.com/PaperMC/Paper/assets/141004145/27ec9083-a7a5-4eb3-b32f-6cee6e5299e5)
![2023-07-31_07 57 09](https://github.com/PaperMC/Paper/assets/141004145/fa196d41-0b38-49e0-8757-4f4b2fd7d368)

### Steps/models to reproduce

You dont need a Plugin to test it, because the command "/data get entity <player>" outputs the health of a player too, but a Plugin might be more comfortable. I used a Plugin on the Server and got the damage amount by writing: `double finalDamge = EntityDamageEvent.getFinalDamage();`

### Plugin and Datapack List

Plugins i currently have installed on the server:

villagernomending.jar (Plugin i made myself, preventing Villager from giving the Mending trade)
NotTooExpensive.jar (Plugin to remove the 40 Level limit in the anvil)
Gsit-1.4.6.jar
Graves-4.9.jar
enchantmentsoverhaul.jar (The Plugin i am writing currently, which i tested when finding the bug)

### Paper version

git-Paper-97 (MC: 1.20.1)

**Comment by Lulu13022002** [comment]
The reason for the falling dripstone to not behave like the anvil is due to when the damagemodifer are added into the map. If you see where the event is prepared (CraftEventFactory#handleLivingEntityDamageEvent) the DamageModifer.HARD_HAT is not updated for falling stalactite, Bukkit explicitely only allow anvil and falling block to handle the 1/4 reduction instead of checking with the DAMAGES_HELMET type tag (to also include the falling stalactite damage type).

So in really there are two issues here (one fixed by spigot and another one introduced by spigot (more or less a reintroduction of the vanilla bug for falling stalactite)).

**Comment by Lulu13022002** [comment]
Fixed in https://github.com/PaperMC/Paper/commit/0b1b1fe067444c5e879313e017da0ffd5d6b826d
