### ISSUE TITLE
Unable to set a spwner's spawned type to `null`

### ISSUE THREAD

**Issue by tal5** [PaperSpigot/Paper#9561]
### Expected behavior

For setting the type to null on a spawner that has type set to remove the spawner's type.

### Observed/Actual behavior

Setting it to null and then calling the `update` method doesn't seem to affect it, and it continues to spawn the type it previously had set.

### Steps/models to reproduce

Tested with the following code on a spawner that has an entity type set.
```java
CreatureSpawner spawner = (CreatureSpawner) block.getState();
spawner.setSpawnedType(null);
spawner.update();
```
The spawner kept it's type, even though it should have been removed.

### Plugin and Datapack List

```
> plugins
[17:47:23 INFO]: Server Plugins (2):
[17:47:23 INFO]: Bukkit Plugins:
[17:47:23 INFO]:  - Debuggery, PaperTestPlugin
```
```
> datapack list
[17:47:37 INFO]: There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]
[17:47:37 INFO]: There are no more data packs available
```

### Paper version

```
> version
[17:48:01 INFO]: Checking version, please wait...
[17:48:02 INFO]: This server is running Paper version git-Paper-100 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: f402f89)
You are running the latest version
Previous version: git-Paper-99 (MC: 1.20.1)
```

### Other

Interestingly it did seem to work with `getState(false)`:
```java
CreatureSpawner spawner = (CreatureSpawner) block.getState(false);
spawner.setSpawnedType(null);
```
But we are aiming for Spigot compatibility until the hard-fork happens, and the original code should have worked either way as far as I can see.

**Comment by electronicboy** [comment]
if your intent is to retain compat with spigot, have you tested with spigot? Stuff like this is generally down to the somewhat flawed implementation of how the state stuff is handled which is generally all handled by upstream

**Comment by tal5** [comment]
Yeah, you're right - opened an [issue upstream](https://hub.spigotmc.org/jira/browse/SPIGOT-7446) for this.
