### ISSUE TITLE
minecart stuck strangeness while running on powered_rail

### ISSUE THREAD

**Issue by thechosecat** [PaperSpigot/Paper#9565]
### Expected behavior

the minecart should just run to the end with no stuck

### Observed/Actual behavior

the minecart just stuck and than run away for about 0.5~1 Second (the position that minecart will stuck i have used GOLD BLOCK to mark it,you can se it in the video below)

### Steps/models to reproduce

bug video here
https://cdn.discordapp.com/attachments/996242655501619310/1136571135107027014/bug.mp4

### Plugin and Datapack List

> plugins
[16:08:01 INFO]: Server Plugins (0):
> datapack list
[16:08:05 INFO]: There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]
[16:08:05 INFO]: There are no more data packs available

### Paper version

> version
[16:08:25 INFO]: This server is running Paper version git-Paper-100 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: f402f89)
You are running the latest version
Previous version: git-Paper-83 (MC: 1.20.1)

**Comment by lynxplay** [comment]
There really isn't much to go off of here.
Can you provide the world this occured in ?

**Comment by thechosecat** [comment]
sure, how can i send the world to you?
google dirve ok?

**Comment by lynxplay** [comment]
Yea, upload the world as a zip or tarball *somewhere*, be that google drive or maybe it is small enough to just be uploaded directly to github :+1:

**Comment by thechosecat** [comment]
the factory is at World  X:7495 y:185 z:-4053
world here
https://drive.google.com/file/d/1bSx9vtRtOk60oxwKvjxbjFSWrDBaQwuq/view?usp=sharing

**Comment by thechosecat** [comment]
put some itmes that can cooked (64x3) in the tube to start the machine :D

**Comment by lynxplay** [comment]
Is this issue consistent for you ? I can barely replicate it, only seeing a slow down once while watching the machine for about 15 mins.

**Comment by thechosecat** [comment]
yes every time i put the itmes in the pipe,the minecart will slow down at that two block

**Comment by thechosecat** [comment]
i have record a new video now, as you can se i try three times,and it stuck for two times
https://cdn.discordapp.com/attachments/996242655501619310/1136633852295651458/2023_08_03_20_15_06_685.mp4

**Comment by pop4959** [comment]
Given it a try as well, sent about 20 minecarts and hasn't once got stuck

**Comment by thechosecat** [comment]
that,s weird,do you sent the minecarts by throwing items to the pipe or just place a new minecraft on the rail?
it looks like it will onely stuck when sent the minecarts by throwing items to the pipe

**Comment by pop4959** [comment]
Throwing items in as shown in your video

**Comment by lynxplay** [comment]
Given we have yet to be able to find a proper reproduction steps for this issue, I'll be closing.
If anyone has reliable reproduction steps for this issue, feel 100% free to comment them here and we will reopen investigation into the issue, for now this simply seems not really fixable if we cannot even get it to happen on our end 👍
