### ISSUE TITLE
Change the player who sends the message from Bungeecord to Paper

### ISSUE THREAD

**Issue by LyFl0w** [PaperSpigot/Paper#9566]
### Expected behavior

The player who sends the message from bungeecord is supposed to be the same when the message is read from Paper.

### Observed/Actual behavior

The player who is supposed to send the message becomes replaced by the player who has his nickname in the Bungeecord message.

### Steps/models to reproduce

![wtf](https://github.com/PaperMC/Paper/assets/91786781/44ce8208-da05-419c-b7ed-e64f39434b79)
![wtf3](https://github.com/PaperMC/Paper/assets/91786781/184f43ff-6c53-4385-88ce-4daefb354d1e)
![wtf4](https://github.com/PaperMC/Paper/assets/91786781/5689dadd-158f-4f01-9106-5dfcf9eafa21)

### Plugin and Datapack List

HeadDatabase, ProtocolLib, QuillCraftCore, QuillCraftLobby.
vanilla (built-in), file/bukkit (world).

### Paper version

This server is running Paper version git-Paper-100 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: f402f89)
You are running the latest version
Previous version: git-Paper-96 (MC: 1.20.1)

**Comment by LyFl0w** [comment]
I don't know if the problem comes from Paper, Spigot or Bungeecord.

**Comment by electronicboy** [comment]
You're sending the message using the server class, which means that it's going to use a random players connection to send the message over. If you wanna ensure that it's sent from a specific player, send it from them

**Comment by LyFl0w** [comment]
Aaaah, I didn't know it did that. 
But unfortunately there's a problem when I try to send data from the ProxiedPlayer.
Other players have had the same problem as me https://www.spigotmc.org/threads/solved-proxied-player-senddata-help.38126/#post-437564
Should I report the error to bungeecord?
