### ISSUE TITLE
paper crash reason

### ISSUE THREAD

**Issue by coolshing** [PaperSpigot/Paper#9576]
### Stack trace

```
[paste your stack trace or a paste.gg link here!](https://paste.gg/p/anonymous/a2d5b413d116419dbb38242755d40dbe)
```
why reason to cause this error? Is it plugins problems? or paper core?

### Plugin and Datapack List

 Server Plugins (84):
Paper Plugins:
 Minepacks
 Bukkit Plugins:
AntiCreeperGrief, BetterCommandSpy, BetterReports, BigDoors, BigDoorsOpener, BlockLocker, ccRides, ChestSort, ClearLag, CMI
*CMIEInjector, CMILib, CommandPanels, CoreProtect, CrazyAuctions, CustomAdvancements, CyberWorldReset, DeathMessages, DiceFurniture, DiscordSRV
  DriveBackupV2, Elevator, ExcellentCrates, ExcellentEnchants, ExecutableItems, ExtraFireworks, F-Command, FastAsyncVoxelSniper, FastAsyncWorldEdit, FishingLife2
  FlareTokens, FurnitureLib, HolographicDisplays, InteractionVisualizer, InteractiveChat, InteractiveChatDiscordSrvAddon, KarmaAPI, LibsDisguises, LiteSignIn, Logger
 LuckPerms, MCEEW, MobMoney, MobsToEggs, Multiverse-Core, Multiverse-Inventories, MythicMobs, NametagEdit, NexEngine, NoteBlockAPI
Orebfuscator, PerWorldPlugins, PlaceholderAPI, *PlayerBTH, PlayerNPC, PlayerPoints, PlayerWarps, PlugManX, ProCosmetics, ProtectionLib
 ProtocolLib, QuickShop, RealisticSeasons, Residence, SCore, Shain, Shopkeepers, SkBee, SkQuery, Skript
*skript-placeholders, skript-yaml, Skulls, SlimeChunkChecker, spark, TimeIsMoney, TradeSystem, TreasureChestX, TreeAssist, Vault
VeinMiner, ViaVersion, Vulcan

### Paper version

[12:53:34 INFO]: CMI 插件版本: 9.5.1.3 SqLite-> 9.6.2.3
[12:53:34 INFO]: CMILib: 1.2.5.5 -> 1.4.0.4
[12:53:34 INFO]: Server: Paper(447) 1.19.3-R0.1-SNAPSHOT
[12:53:34 INFO]: CMI economy: enable Vault: 1.7.3-b131(CMIEInjector) CMI Chat: enable
[12:53:34 INFO]: Modules -> 57 enabled 1 disabled: votifier
[12:53:34 INFO]: --------------------------------------------------

**Comment by lynxplay** [comment]
You are
a) running an outdated version of paper we do no longer support
b) your server seems overloaded as the hologram plugin is causing a watchdog trigger.

This is not a problem with paper, your server simply isn't strong enough to support whatever the plugins are doing (or the plugins are the cause of the lag, who knows). Beyond that, GitHub issues isn't the place to discuss this. Feel free to ask on our discord for help, however make sure to run a supported version, e.g. 1.20.1.
