### ISSUE TITLE
The entity-per-chunk-save-limit does not work for boats

### ISSUE THREAD

**Issue by CatTeaA** [PaperSpigot/Paper#9583]
### Expected behavior

entity-per-chunk-save-limit can limit the number of boats

### Observed/Actual behavior

[16:33:57 ERROR]: [MapSerializer] Could not deserialize key oak_boat into net.minecraft.world.entity.EntityTypes<?> at [chunks, entity-per-chunk-save-limit]

### Steps/models to reproduce

  entity-per-chunk-save-limit:
    oak_boat: 24

### Plugin and Datapack List

null

### Paper version

paper  1.20.1 build#108

### Other

I can limit Minecart in the same way
If it's due to a format mistake in my operation, you can always close the issue

**Comment by welove69** [comment]
This is also to prevent some players from maliciously piling up Boats and causing server lag

**Comment by lynxplay** [comment]
oak_boat is not an entity type.
There is `boat` and `chest_boat` respectively.
Can you try configuring those ?

**Comment by welove69** [comment]
> boat



> oak_boat不是实体类型。分别有和有。您可以尝试配置这些吗？`boat``chest_boat`

Thank you for the answer, following your method, now solved
