### ISSUE TITLE
Nether portal often causes lag, 1000MSPT

### ISSUE THREAD

**Issue by CatTeaA** [PaperSpigot/Paper#9585]
### Timings or Profile link

https://spark.lucko.me/DHEE75WDg6

### Description of issue

![spark1](https://github.com/PaperMC/Paper/assets/135555687/4f97a8d4-b4c9-43cd-a9f7-b2bdbc405c76)
I've been troubled by this problem for a long time, but I can't analyze the reason
Sometimes it appears, sometimes it lags slightly, and I don't know what went wrong
Can you analyze it
https://github.com/PaperMC/Paper/issues/9265
This answer is a bit incoherent. I'm not sure if the two are related

### Plugin and Datapack List

spark

### Server config files

```
Paste configs or paste.gg link here!
```
https://spark.lucko.me/DHEE75WDg6

### Paper version

This server is running Paper version git-Paper-108 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: d6d2b6f)
You are running the latest version

### Other

![Base Profile Screenshot 2023 08 08 - 01 22 38 80](https://github.com/PaperMC/Paper/assets/135555687/7a2534aa-5d18-40da-803a-8c1c777dbc99)

Just let the creatures use the portal
When there is a player next to the Overworld portal, the lag will not appear

**Comment by welove69** [comment]
https://spark.lucko.me/lIrwqTGILS
This is another server's report

**Comment by electronicboy** [comment]
Because the thing induced io on the main thread in order to figure out where to  deal with the portal, pretty sure there is already duplicates about this, but it's generally not something you can fix without breaking behaviour

**Comment by welove69** [comment]
> 因为事情在主线程上诱导了io，以便找出在哪里处理门户，所以可以肯定已经有重复项，但这通常不是您可以在不破坏行为的情况下修复的内容

https://github.com/PaperMC/Paper/assets/135555687/d214cef9-fb41-487c-a54c-403db8fd11f3

I didn't have a noticeable lag when using spigot and vanilla, and MSPT reached 1000 when using paper
Pay attention to the piston

**Comment by Huge-mistake** [comment]
So I boldly assume, this should be a paper problem?
Can this issue be reopened

**Comment by electronicboy** [comment]
Would need a spark report showing all threads, but, generally this just
boils down to portals sucking of which there is little we can do, vanilla
will load the other side in its own in some cases, so hard to compare
behaviour directly

**Comment by welove69** [comment]
![QQ截图20230808092058](https://github.com/PaperMC/Paper/assets/135555687/7a180f79-ca0e-4a83-9384-f3a1dc205509)

**Comment by electronicboy** [comment]
No, as I said, it needs to show all threads. It’s doing io from the main thread, that’s the obvious part, I wanna know what the chunk systems threads are doing.

**Comment by welove69** [comment]
> chunk systems

Can you tell me what I should do
I don't know how to do it    >_<

**Comment by welove69** [comment]
I provide a server-side archive that can reproduce the lag phenomenon, which contains the control groups of paper and spigot, I hope you can help analyze it
https://mega.nz/file/57cnHISZ#i7VDdEJf6xwok93Y2i7KIkxu8byvxVeMFDY85qLlqR4

**Comment by welove69** [comment]
Paper and Spigot are both the latest versions

**Comment by welove69** [comment]
Sorry, I'm reporting this issue again.
I have this on both computers, they are both Windows 11, and the probability of occurrence is very high.
After I switched Windows 11 to Ubuntu 22.3, the lag spike disappeared, and I was also confused, it will only happen with Windows 11.
The CPU models are i5 11400F and i5 12400
The system uses Ubuntu 22.3, and the lag phenomenon does not occur

**Comment by Huge-mistake** [comment]
Some quick googling revealed that jdk.internal.misc.Unsafe.park is an internal Java function which causes the program to halt temporarily until some condition is met. In this case, it seems like some incident is doing some background calculations asynchronously which interfere with the event loop for Minecraft, causing the tick to be halted until it finishes. As for which incident, it is impossible to say without a much deeper dive
