### ISSUE TITLE
Farm with portal mechanic stopped working

### ISSUE THREAD

**Issue by primemb** [PaperSpigot/Paper#9593]
### Expected behavior

They are some farms that work with the nether portal, on these farms, Entity must teleport from nether to the overworld and walk throw another portal and back to the nether. This problem happend after i update my paper it worked fine before. Can it be related to this commit maybe : https://github.com/PaperMC/paper/commit/408a9050baf29341b877a7bebff0939442d818d0

### Observed/Actual behavior

Right now entity despawn immediately after teleport to over world

### Steps/models to reproduce

This is one of the farms that worked that way : https://www.youtube.com/watch?v=uBpMwXVn6iY

### Plugin and Datapack List

- AngelChest, *DragonEggRespawn, Essentials, EssentialsSpawn, FeatherBoard, GDHooks, GriefDefender, GSit, HeadsPluginAPI, *LoginSecurity LuckPerms, PlaceholderAPI, SafariNet, Shop, SkinsRestorer, spark, Spartan, UltimateAutoRestart, Vault, voicechat
WorldEdit

### Paper version

This server is running Paper version git-Paper-116 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 4179b8f)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-95 (MC: 1.20.1)

**Comment by lynxplay** [comment]
Please replicate this without plugins. The change in question should not really have affected anything beyond plugins cancelling the EntityPortalExitEvent

**Comment by primemb** [comment]
ok i downloaded World on my pc and i did some research and find out these kind of farms only works when there is no other player on over world when i play solo it worked fine and Entity not despawn but when there is someone on over world and basically more than 128 blocks away they despawn so can someone explain how despawn works and why when there is no one on the overworld entity not despawn and farms work fine ? is there any way to make these farms work
