### ISSUE TITLE
custom player head lose textures

### ISSUE THREAD

**Issue by JellyRoad** [PaperSpigot/Paper#9612]
### Expected behavior

https://github.com/PaperMC/Paper/assets/73968499/87ec6571-97c0-442c-8568-c9938a325fb9

### Observed/Actual behavior

https://github.com/PaperMC/Paper/assets/73968499/ff81df22-113e-4f89-977b-f204f2838613

### Steps/models to reproduce

start paper server 
stop the server
go to server files
open world folder
open datapacks folder
put Decapitation.zip into datapacks folder
[Decapitation.zip](https://github.com/PaperMC/Paper/files/12352691/Decapitation.zip)
start srver
summon warden and kill him
pick up head that he drop
try to open inventory/place head

### Plugin and Datapack List

![obraz](https://github.com/PaperMC/Paper/assets/73968499/f19c883f-5e25-4c3d-a9f0-45fb12ba77be)

### Paper version

This server is running Paper version git-Paper-126 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a73ed95)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Purpur-2035 (MC: 1.20.1)

### Other

Data for heads
in first slot normal head (how it shuld look like)
in second slot broken head

/setblock -1 76 24 minecraft:chest[facing=south,type=single,waterlogged=false]{Items:[{Count:1b,Slot:0b,id:"minecraft:player_head",tag:{SkullOwner:{Id:[I;1553579158,176833303,-1716217748,-1737146209],Name:"Warden",Properties:{textures:[{Signature:'{"italic":false,"color":"yellow","text":"Warden Head"}',Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzk1OWFlMDJlMzVjYmM0NzQzZTZlNzAyZmRhNjk4MGJhZDJlOTgwNDk0MDNjMTY5OTYyODZlYjQxMmY5NDY4OSJ9fX0="},{Signature:"tdp.511:sounds/warden",Value:"TDP511_V1"},{Signature:'{"text":"Player Kill","color":"#11BB11","italic":false}',Value:'{"text":"Obtained from:","color":"#888888","italic":false}'},{Signature:"tdp.511:sounds/warden",Value:"TDP511_V1"}]}},display:{Lore:['{"text":"Obtained from:","color":"#888888","italic":false}','{"text":"Player Kill","color":"#11BB11","italic":false}'],Name:'{"italic":false,"color":"yellow","text":"Warden Head"}'}}},{Count:1b,Slot:1b,id:"minecraft:player_head",tag:{SkullOwner:{Id:[I;1553579158,176833303,-1716217748,-1737146209],Name:"Warden",Properties:{textures:[{Signature:"tdp.511:sounds/warden",Value:"TDP511_V1"}]}},display:{Lore:['{"text":"Obtained from:","color":"#888888","italic":false}','{"text":"Player Kill","color":"#11BB11","italic":false}'],Name:'{"italic":false,"color":"yellow","text":"Warden Head"}'}}}]}

**Comment by Owen1212055** [comment]
Can reproduce, this is caused byhttps://github.com/PaperMC/Paper/blob/master/patches/server/0427-Clean-up-duplicated-GameProfile-Properties.patch 

This patch should probably be removed.

**Comment by JamieIsGeek** [comment]
@Owen1212055 would you just say remove the patch entirely?
