### ISSUE TITLE
Feature Request: Enhanced Handling of ConfigurationSection Data Retrieval

### ISSUE THREAD

**Issue by nicecraftz** [PaperSpigot/Paper#9617]
### Is your feature request related to a problem?

My feature request is not related to a problem and is indeed my first feature request here also on GitHub so please don't destroy me ahah. 

### Describe the solution you'd like.

Currently, the ConfigurationSection class provides a get() method for retrieving data, which returns an object. However, I've encountered some challenges while working with this method, as handling the returned object can be quite complex and inconvenient.

To address this, I've been considering a potential refactor that could significantly improve this situation. My proposal involves extending the get() method to accept a parser interface that would allow users to specify how the default YAML string representation of the data should be translated into the desired object type.

Here's a basic outline of the proposed solution:

```java
public interface ConfigObjectParser<T> {
    T parse(String value);
}
```

With this change, users would be able to register their custom parsers and then call the modified get() method as follows:

`T parsedObject = configurationSection.get("path.to.value", customParser);`

### Describe alternatives you've considered.

The alternative is to stick with our kind of older methods to manage "Deserialization", currently i do it like this.

```java
public static CommandAction fromConfig(ConfigurationSection section) {
        return new CommandAction(
                section.getStringList("commands"),
                section.getInt("delay"),
                section.getBoolean("killer-required")
        );
    }
```

**Comment by electronicboy** [comment]
> My proposal involves extending the get() method to accept a parser interface that would allow users to specify how the default YAML string representation of the data should be translated into the desired object type

Except that information literally no longer exists at this point

**Comment by nicecraftz** [comment]
but then we would have to keep the old-fashioned way system that would make the boilerplate code still exist I don't know if I made myself correct, it is sure a hard task but an actual revisitation of the configuration system of Bukkit would be loved.

**Comment by lynxplay** [comment]
The alternative is a configuration library like [configurate](https://github.com/SpongePowered/Configurate).
I agree that the existing bukkit configuration API is not as indepth and powerful as it might need to be at times, but I don't see a point in us trying to design and maintain another configuration library when there is already a collection of external tools for this.

Configurate is already used internally, so technically does not need to be shaded. We talked about promoting it to the API layer before, but have not finalised those plans at this point.

**Comment by nicecraftz** [comment]
would be cool to provide it to the API layer and deprecate the old configuration system as now it doesn't provide that much of a use anymore for complex jobs.

**Comment by electronicboy** [comment]
I don't think that there is really a way forward here, the configuration system is not tied to yaml, and there's no storage of the information that would even be required to make this a thing, you'd basically need to load it into a Node tree of some form, which, in the abstract sense, already exists with ConfigurationSection

The entire point of the bukkit configuration system was to provide a simple-to-use mechanism for loading a yaml file from the disk without having to learn snake or stuff like gson, etc; exposing configurate is on the todo list once we get yaml comment support into it.

For years I've always recommended loading your configuration stuff into a POJO, as then you don't need these get type methods past loading it, so the lack of "magic" isn't a thing
