### ISSUE TITLE
LightUpdateEvent

### ISSUE THREAD

**Issue by Senne98** [PaperSpigot/Paper#9618]
### Is your feature request related to a problem?

I want detect the location of a light update, but I don't think there is a way to do this at the moment (I also asked the discord).

### Describe the solution you'd like.

An event that would trigger when a light udate happens, it should contain the location of the light update, and maybe the previous block and skylight values.

### Describe alternatives you've considered.

I am currently trying do detect it with block place/brake event, but if I don't want to check a verry large area around the broken block, it's not perfect.

**Comment by olijeffers0n** [comment]
This event would be called so much that it would tank your server's performance. Generally a bad idea IMO

**Comment by Senne98** [comment]
True, but the only other way I can think of is far worse and I would be able to end most event calls with one check.

**Comment by electronicboy** [comment]
Except we'd still need to create said events, and likely deal with extra
buffering due to how these systems work in order to produce useful results,
etc

Given the shockingly small usecases for this, this is probably a no go,
stuff like the physics event are problematic as is, we don't need something
that could throw like a hundred events because somebody broke or placed a
torch

**Comment by Cryptite** [comment]
> True, but the only other way I can think of is far worse and I would be able to end most event calls with one check.

This sounds like an x/y problem. What are you really trying to do and why would you need light updates to detect it?

**Comment by Senne98** [comment]
Would it be possible to call one event when a block is broken/placed with a list of the affected blocks. Would that be better.

**Comment by Nacioszeczek** [comment]
Due to what cat said and there being no other feedback, closing this as a won't fix,
thank you for the request though!
