### ISSUE TITLE
Added piglin and hoglin zombification settings

### ISSUE THREAD

**Issue by BackSam6348** [PaperSpigot/Paper#9619]
### Is your feature request related to a problem?

It would be nice to add an option to set Piglin or Hoglin not to zombify in the overworld to paper-world-defaults.yml.

### Describe the solution you'd like.

Add the config value

entities:
    behavior:
        # true or false
        zombify-piglins-and-hoglins: false # default : false

### Describe alternatives you've considered.

Add the config value

entities:
    behavior:
        # true or false
        zombify-piglins-and-hoglins: false # default : false

### Other

Nothing

**Comment by Warriorrrr** [comment]
I think such a feature would be best suited for a plugin, since cancelling the [EntityTransformEvent](https://jd.papermc.io/paper/1.20/org/bukkit/event/entity/EntityTransformEvent.html) for piglins and hoglins is only a few lines.

**Comment by Machine-Maker** [comment]
Well even beyond that, the better way would be to set all Hoglin and Piglin as immune to zombification via `Hoglin#setImmuneToZombification` and `PiglinAbstract#setImmuneToZombification`.

Or you could use a datapack and modify the overworlds generation settings to set it as piglin safe. There are several solutions to this issue already, so I think a setting is redundant.
