### ISSUE TITLE
Infinite treasure chest loot?

### ISSUE THREAD

**Issue by BigScary** [PaperSpigot/Paper#9622]
### Expected behavior

Each player should be able to loot each world-generated chest at most once. After emptying the loot from the chest the first time, that player should see the chest as empty for subsequent re-opens. This is the behavior I saw for many years, until I updated the server to a new version a few days ago.

### Observed/Actual behavior

After I updated my server recently, players reported that they were able to loot the same world-generated treasure chests repeatedly. Each time they opened the chest, it would again have treasure even after they taken it all to their inventory after the previous opening. They could do this as many times as they liked. I disabled the auto-replenish lootables feature in a panic, but this was almost 48 hours after the update. =(

### Steps/models to reproduce

My config. This has not changed in years, and we have not had this problem until a few days ago when I updated to Paper-126.

lootables:
  auto-replenish: true
  max-refills: -1
  refresh-max: 1s
  refresh-min: 1s
  reset-seed-on-fill: true
  restrict-player-reloot: true
  restrict-player-reloot-time: disabled

### Plugin and Datapack List

Lots of plugins. None are new, none were recently reconfigured.

### Paper version

This server is running Paper version git-Paper-126 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a73ed95)
You are 4 version(s) behind

**Comment by Machine-Maker** [comment]
Fixed on the latest version. Update.
