### ISSUE TITLE
Latest build download

### ISSUE THREAD

**Issue by kangarko** [PaperSpigot/Paper#9624]
### Is your feature request related to a problem?

Is there a way to always fetch the latest Paper build for a given Minecraft version?

Using the URL provided at https://github.com/PaperMC/Paper/issues/2661 no longer works.

Thanks,
Matej

### Describe the solution you'd like.

N/A

### Describe alternatives you've considered.

N/A

**Comment by electronicboy** [comment]
No

**Comment by kangarko** [comment]
Thanks. I'm trying to create a run file to always start with the latest Paper, see the example that works fine but it's set to a specific build below. 

I did read the docs but could not find an example there. It'd be really nice if you could help me with this and then post it to our documentation because I have seen many people ask for it.

```
@echo off

REM Set the URL to the latest paperclip.jar version
set "jar_url=https://api.papermc.io/v2/projects/paper/versions/1.20.1/builds/131/downloads/paper-1.20.1-131.jar"

REM Set the name of the downloaded file
set "downloaded_file=paperclip.jar"

REM Download the paperclip.jar file using curl
curl -o "%downloaded_file%" "%jar_url%"

REM Check if the download was successful
if %errorlevel% neq 0 (
    echo Error downloading %jar_url%
    exit /b
)

REM Start the Java application using the downloaded paperclip.jar
java -Xms4G -Xmx4G -jar "%downloaded_file%" nogui

pause
```

-Matej

**Comment by Leguan16** [comment]
its intended to not provide docs on how to auto download latest builds since its intended for only people who know what they are doing. You have to figure things out yourself. The API page should provide enough details on how to get the latest build.

**Comment by MiniDigger** [comment]
just curl this https://api.papermc.io/v2/projects/paper/versions/1.20.1/, get the last entry in the array and then use that to build the url.

generally, for development setups (I assume dev setup since its winows), we recommend the run task gradle plugin which makes it all pretty painless, since it also automatically starts your plugin with the server without you havent to copy it over and maintains a cache of the paperclip jar nicely locally:
https://github.com/jpenilla/run-task

**Comment by kangarko** [comment]
> just curl this https://api.papermc.io/v2/projects/paper/versions/1.20.1/, get the last entry in the array and then use that to build the url.
> 
> generally, for development setups (I assume dev setup since its winows), we recommend the run task gradle plugin which makes it all pretty painless, since it also automatically starts your plugin with the server without you havent to copy it over and maintains a cache of the paperclip jar nicely locally: https://github.com/jpenilla/run-task

Thank you Mini!




> its intended to not provide docs on how to auto download latest builds since its intended only for people who know what they are doing. You have to figure things out yourself. The API page should provide enough details on how to get the latest build.

I understand the reasoning, but I believe Minecraft network owners are mostly not developers. Many can't code and just want to have the latest version, not fiddle with a script. It should be made simple to get it by Paper team. I don't believe it would overload your support more if properly documented and with a disclaimer. Just a friendly feedback.

**Comment by Leguan16** [comment]
no, because if a corrupt build manages to the release branch it could break and destroy a lot of servers.

**Comment by Leguan16** [comment]
> we recommend the run task gradle plugin which makes it all pretty painless, since it also automatically starts your plugin with the server without you havent to copy it over and maintains a cache of the paperclip jar nicely locally:
> https://github.com/jpenilla/run-task

only issue I have is that it doesn't properly shut down if I click stop/rerun wich is just bruh.

**Comment by MiniDigger** [comment]
> > we recommend the run task gradle plugin which makes it all pretty painless, since it also automatically starts your plugin with the server without you havent to copy it over and maintains a cache of the paperclip jar nicely locally:
> > [jpenilla/run-task](https://github.com/jpenilla/run-task)
> 
> only issue I have is that it doesn't properly shut down if I click stop/rerun wich is just bruh.

that doesnt sound right, paper should gracefully shut down, consider opening an issue on the plugin to investigate
<hr>

us not providing a latest endpoint also has technical reasons, it simplifies our caching setup (we are currently serving more than a terabyte of jars per day) and prevents people from downloading the same jar over and over again.
but yes, as leguan16 said, production servers should never auto update, new paper or plugin updates should always be verified on a test server first. just like any software.

**Comment by Leguan16** [comment]
> > > we recommend the run task gradle plugin which makes it all pretty painless.
> > only issue I have is that it doesn't properly shut down if I click stop/rerun wich is just bruh.
> 
> that doesnt sound right, paper should gracefully shut down, consider opening an issue on the plugin to investigate
will do once i get home from vacation

**Comment by kangarko** [comment]
I made my own endpoint. Whom can I contact regarding approval? It's cached with 6 hours expiration time and I store the jar on my own server not to overload yours.

**Comment by lynxplay** [comment]
As laid out a) in this issue b) in https://github.com/PaperMC/bibliothek/issues/74, we are not interested in a latest endpoint.
Feel free to maintain an endpoint for yourself to download latest, we are not going to promote one to the public api as laid out before in https://github.com/PaperMC/bibliothek/issues/74.

**Comment by MiniDigger** [comment]
Nobody should I cer use any 3rd party download link for obvious security issues. Only jars obtained from PaperMCs webservices are verified and not malicious. Rehosting the jars because you don't want to write a onliner in bash isn't a good idea, but we can't stop you, just make sure to follow our license.
