### ISSUE TITLE
Zombified Piglins Spawned from Nether Portals Do Not Count Towards the Mob Cap

### ISSUE THREAD

**Issue by funnyboy-roks** [PaperSpigot/Paper#9626]
### Expected behavior

The zombified piglin should count towards the hostile mobcap when spawned from a nether portal in the overworld.

### Observed/Actual behavior

The zombie pigman does not count towards the hostile mob cap.

### Steps/models to reproduce

- Clear a large perimeter with `/fill ~-128 -64 ~-128 ~128 300 ~128 air` to prevent other mobs from adding to the hostile mobcap
- (I additionally used `/fill ~-128 -64 ~-128 ~128 -64 ~128 black_stained_glass` to have a floor to build on)
- Create a few nether portals in the overworld (more portal blocks = better, since more pigmen will spawn)
![image of nether portals](https://github.com/PaperMC/Paper/assets/70620591/4d873290-8f88-4f87-abd8-5ea118e04a27)
- Wait for a pigman to spawn
![image of nether portals removed to see that there are pigmen](https://github.com/PaperMC/Paper/assets/70620591/50a1487a-f38c-4b64-8709-626dd6873db9)
- Check mobcaps with `/paper mobcaps`
- See that there are no mobs under the monster mob cap
![image of empty monster mobcap](https://github.com/PaperMC/Paper/assets/70620591/c64e24b8-dea5-4a18-ab69-c54f152b76d2)

### Plugin and Datapack List

This happens on a plain Paper install with no plugins or datapacks (apart from the Vanilla and Bukkit packs)

### Paper version

```
> version
[13:14:55 INFO]: Checking version, please wait...
[13:14:55 INFO]: This server is running Paper version git-Paper-131 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 307d05b)
You are running the latest version
```

**Comment by Nacioszeczek** [comment]
The mobcaps counts mobs only spawned naturally or during chunk generation while zombified piglins are spawned by the portal, which isn't considered a natural spawn therefore this works as intended.

You can change this behavior and count all mobs by changing the per-world setting `count-all-mobs-for-spawning` to `true`.

If you need any further help feel free to reply here, use our [Discord](https://discord.gg/papermc) or [forums](https://forums.papermc.io/forums/).
