### ISSUE TITLE
lag-compensate-block-breaking option not working on 1.20.1

### ISSUE THREAD

**Issue by mcdoeswhat** [PaperSpigot/Paper#9634]
### Expected behavior

break a block and it drops immediately
not affected by server tps

### Observed/Actual behavior

the block break is affected by server tps

### Steps/models to reproduce

```java
 @EventHandler
    public void onTick(ServerTickStartEvent event){
        try {
            Thread.sleep(80);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
```

write the following code,and break a block

### Plugin and Datapack List

[18:50:59 INFO]: Bukkit Plugins: (2):
[18:50:59 INFO]:  - TestPlugin, spark

### Paper version

 This server is running Paper version git-Paper-144 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 00a68b1)

**Comment by JamieIsGeek** [comment]
This isn't really useful, we don't know what the expected behaviour you think should happen from the number 1. You don't say what is actually broken, only some random server versions.

**Comment by mcdoeswhat** [comment]
> 
![FKK90NA{U2{S$U(8)EFJIJO](https://github.com/PaperMC/Paper/assets/20266201/018d695c-4ed9-4a77-84a9-55158d77a81e)

**Comment by lynxplay** [comment]
The patch was removed in the 1.19 update. The fact that the docs still show it is a bug.

**Comment by mcdoeswhat** [comment]
> The patch was removed in the 1.19 update. The fact that the docs still show it is a bug.

but the option is still in the config

**Comment by lynxplay** [comment]
Yes, an oversight during the removal. I'll open respective PRs to remove the option from the configuration and docs. Sorry for the confusion.

**Comment by lynxplay** [comment]
Both paper and the docs have been updated.
Given that leaf seems to have implemented it on folia again, we might consider readding this back in the future, but for now the patch and the option to enable it are removed :+1:
