### ISSUE TITLE
Bukkit.dispatchCommand does not launch a ServerCommandEvent 

### ISSUE THREAD

**Issue by PapiCapi** [PaperSpigot/Paper#9644]
### Expected behavior

Bukkit.dispatchCommand should launch a ServerCommandEvent as when typing in the console.

### Observed/Actual behavior

It doesn't launch the event.

### Steps/models to reproduce

Use Bukkit.dispatchCommand in a plugin and listen for the ServerCommandEvent. 

### Plugin and Datapack List

Server Plugins (84):
[18:26:56 INFO]: Bukkit Plugins:
- AdvancedAchievements, AfkTitle, *AntiAFK, AntiDecoCombat, AreaShop, ArmorStandTools, ASReplace, BlockLocker, BlockVillagersEnteringBoats, ChatCore
 ChatItem, ChatPing, ChestCommands, ChestShop, Citizens, CitizensText, CMILib, *CompteGroupe, CoreProtect, CrazyAuctions
CrazyCrates, CreateRank, *DabCore, DeACoudre, EffectItems, Essentials, EssentialsChat, EssentialsSpawn, FarmLimiter, FastAsyncVoxelSniper
FastAsyncWorldEdit, *Fe, ForceIgnore, GadgetsMenu, Grades, HolographicDisplays, IllegalStack, Insights, Jobs, LevelKeeper
Lift, LoadForce, LobbyPlayerCounter, LuckPerms, MayorRegions, MinewebBridge, MobEggDrops, ModPerms, *ModReq, MoncubeCore
Multiverse-Core, MyPet, *NaruseAPI, NoCollision, OnTime, OpenInv, *OpGuard, Plan, PlanningsEvents, PlayerHeads
PlugManX, PreventEnderChestUseBug, ProtocolLib, SchematicMover, ScoreboardHelper, *SecondThreadAPI, Shopkeepers, Skript, spark, TAB
TokenManager, Vault, Vehicles, VehiclesFlags, ViaBackwards, ViaVersion, *VillesSemi, VoidGen, VoteMoncube, WGEFixer
WorldBorder, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags

### Paper version

This server is running Paper version git-Paper-158 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: fcc5f23)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-393 (MC: 1.19.3)

### Other

I did not mark this issue as a feature request because in my opinion, it should launch an event.

**Comment by lynxplay** [comment]
After further consideration, I think this is not worth calling.
The event is cancellable so calling it and potentially cancelling a plugin run command could break way to many plugin to plugin interactions that rely on commands being executed.

E.g. right now plugin A might have to interact with a currency plugin B that does not have a public API.
For this plugin A calls dispatchCommand to execute a respective currency removal from plugin B.
Calling the event here means plugins could potentially cancel the command, leaving plugin A to believe it removed currency from plugin B, while in reality is has not happend.

We would need a new event here that is not cancellable, which preferably comes after brigadiars integration into the API. For now I will close this as not feasible during a regular release cycle as breaking plugins like this is simply not a smart idea.
