### ISSUE TITLE
BlockPhysicsEvent not always being cancellable

### ISSUE THREAD

**Issue by PapiCapi** [PaperSpigot/Paper#9647]
### Expected behavior

BlockPhysicsEvent should always be cancellable. 

### Observed/Actual behavior

With a plugin cancelling all BlockPhysicsEvent, no physics should be "played". 
Now, the physics cancelled are only those when you break a block below another one. If you try placing sand where it could fall, it will even if it shouldn't.

See this video for better understanding : https://youtu.be/I8pPa0my7lk

### Steps/models to reproduce

Create a plugin cancelling physics
Try to place a block of sand where it could fall
The block of sand falls even if it shouldn't

### Plugin and Datapack List

Server Plugins (4):
Bukkit Plugins:
- FastAsyncWorldEdit, Multiverse-Core, PlayersWorlds, WorldGuard

PlayersWorlds is my testing plugin.

### Paper version

This server is running Paper version git-Paper-163 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 6f30f08)

**Comment by electronicboy** [comment]
don't have the means to look, but this would more scream like a case of "the event didn't fire where I expected it to", a common issue for the physics event, rather than it not cancelling properly (Pretty sure that that would be impossible in its current state)

**Comment by lynxplay** [comment]
Falling blocks literally schedule a tick on their onPlace.
The event, as cat said, isn't called and cannot really be called there either.
You can use the EntityChangeBlockEvent to prevent the falling sand block from spawning in the first place, but in my honest opinion this is a wont fix.
