### ISSUE TITLE
ClickEvent.callback does not work for non-op players

### ISSUE THREAD

**Issue by Sytm** [PaperSpigot/Paper#9651]
### Expected behavior

When any player clicks on a message with a callback click event the callback should be called normally.

### Observed/Actual behavior

When sending a non-op player a component with an callback click event attached to it the player will only receive a message that the command could not be found (because he has no permission for `/paper` and therefore not for `/paper callback`) `Unknown command. Type "/help" for help.`

### Steps/models to reproduce

```java
// Player should not be op or have permissions by a plugin here
player.sendMessage(Component.text("test").clickEvent(ClickEvent.callback(clicker -> player.sendPlainMessage("You clicked me!"))))
```

### Plugin and Datapack List

My plugin and no additional datapacks

### Paper version

[23:26:28 INFO]: Checking version, please wait...
[23:26:28 INFO]: This server is running Paper version git-Paper-164 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 6813244)
You are running the latest version
Previous version: git-Paper-100 (MC: 1.20.1)

**Comment by lynxplay** [comment]
Relatively easily resolved by updating how the PaperCommand constructor register its permissions (allowing subcommand to overwrite the PermissionDefault and then having callback pass TRUE instead of OP)

**Comment by Sytm** [comment]
I am just about to actually do exactly that :)
