### ISSUE TITLE
Provide method to get sapling in a StructureGrowEvent

### ISSUE THREAD

**Issue by sovdeeth** [PaperSpigot/Paper#9653]
### Is your feature request related to a problem?

Following #6464. `event.getLocation().getBlock()` returns AIR during StructureGrowEvents involving trees. Prior to this PR, it would return the sapling that the tree grew from. It appears that there is no way to figure out what sapling was involved in a StructureGrowEvent without using TreeType and mapping all types to the correct sapling.

### Describe the solution you'd like.

A method of accessing the type of sapling (or other original block) that a structure grew from. 

### Describe alternatives you've considered.

event.getLocation().getBlock() is AIR
event.getBlocks() only contains an AIR block at the sapling location
Using TreeType and mapping all types to the correct sapling manually seems to be the only option available.

**Comment by Machine-Maker** [comment]
Yeah, I think that was an unintended regression, that the block doesn't show the sapling. So that is the fix done in the linked PR.
