### ISSUE TITLE
How to disable editing "signboard"

### ISSUE THREAD

**Issue by pkki** [PaperSpigot/Paper#9656]
### Is your feature request related to a problem?

Chest protection plugin signs would be rewritten.

### Describe the solution you'd like.

I want to disable sign editing in version 1.20.

### Describe alternatives you've considered.

there's no way to try

**Comment by Nacioszeczek** [comment]
You need to wax the signs yourself or the protection plugin should make them non-editable [through API](https://jd.papermc.io/paper/1.20/org/bukkit/block/Sign.html#setWaxed(boolean)).
Please use our Discord or forums in the future for questions.
