### ISSUE TITLE
The "Rewrite chunk system" has some minor issues with Windows

### ISSUE THREAD

**Issue by CatTeaA** [PaperSpigot/Paper#9680]
### Timings or Profile link

https://spark.lucko.me/6l14r2WOJ3
https://spark.lucko.me/DRmVgNvR2c
https://spark.lucko.me/PHhlxPAc0f
https://spark.lucko.me/QD18kGNAjN

### Description of issue

I've always been bothered by the occasional lag in Nether portals
I spent two days sifting through the versions
Eventually locating to paper-1.19.2-174, which added the Rewrite chunk system, was a feat
But on Windows systems, there seems to be some lag issues,Lag doesn't happen on Ubuntu(Linux)
When I use paper-1.19.2-173 (without the Rewrite chunk system), the lag doesn't happen
I've been troubleshooting the cause for months, maybe I shouldn't be using Windows
The system used in the test was Windows 11 Pro
I provided a video,Emphasize again(Lag doesn't happen on Ubuntu)

https://github.com/PaperMC/Paper/assets/135555687/2b189f0d-d37c-47fb-a422-1b3d8211d8f0

### Plugin and Datapack List

null

### Server config files

```
Paste configs or paste.gg link here!
```
default

### Paper version

paper-1.20.1-169--->paper-1.19.2-174.jar

**Comment by underscore11code** [comment]
You are running an unsupported version of Minecraft (1.19.2). Additionally, please follow the issue template in the future with regards to plugin/datapack list, config files, paper version, and profiler link.

**Comment by welove69** [comment]
> 您正在运行不受支持的 Minecraft 版本 （1.19.2）。此外，请以后按照有关插件/数据包列表、配置文件、纸质版本和分析器链接的问题模板进行操作。

I said paper-1.20.1-169 is affected as such, please don't close

**Comment by welove69** [comment]
> You are running an unsupported version of Minecraft (1.19.2). Additionally, please follow the issue template in the future with regards to plugin/datapack list, config files, paper version, and profiler link.

Paper version
paper-1.19.2-174.jar------>paper-1.20.1-169

**Comment by Warriorrrr** [comment]
This issue is similar to the one you have opened before but no extra info was provided, additionally there's another issue already opened for lag from nether portals.

**Comment by welove69** [comment]
> This issue is similar to the one you have opened before but no extra info was provided, additionally there's another issue already opened for lag from nether portals.

I know, but I've spent a long, long, long time narrowing it down here, and I'm not a professional in this area, so please understand

**Comment by welove69** [comment]
paper-1.20.1-169:
https://spark.lucko.me/6l14r2WOJ3

paper-1.19.2-173:
https://spark.lucko.me/DRmVgNvR2c

paper-1.19.2-174:
https://spark.lucko.me/PHhlxPAc0f

Although the issue has been closed, I hope that the paper team will also pay attention to this issue, which is greatly appreciated.

**Comment by welove69** [comment]
paper-1.20.1-169:   (ubuntu)
https://spark.lucko.me/QD18kGNAjN

**Comment by electronicboy** [comment]
We really have little care about windows, it's well known that file Io is much slower on that platform, and unless something shows that the issue is elsewhere, there's little we can do other than advising to maybe try to toy with the number of Io workers.

Outside of that, we'd need a trace showing all server threads when that occurs, which I'm pretty sure across the GitHub and discord, I've asked enough times that I no longer care with how much my head is spinning.

**Comment by welove69** [comment]
I've found that this problem seems to be avoided as long as the server command window is not minimized.
It should be caused by the poor disk policy of Windows background calls.
The Rewrite chunk system is good, it loads quickly, it's a lag caused by windows policy.

**Comment by welove69** [comment]
> We really have little care about windows, it's well known that file Io is much slower on that platform, and unless something shows that the issue is elsewhere, there's little we can do other than advising to maybe try to toy with the number of Io workers.
> 
> Outside of that, we'd need a trace showing all server threads when that occurs, which I'm pretty sure across the GitHub and discord, I've asked enough times that I no longer care with how much my head is spinning.

Sorry to bother you, I would like to ask "trace showing all server threads", how should I provide it? I tried Google, but there are so many answers, I don't know which one is needed, forgive my ignorance

Image Name                     PID Session Name        Session#    Mem Usage
========================= ======== ================ =========== ============
System Idle Process              0 Services                   0          8 K
System                           4 Services                   0      1,180 K
Registry                       188 Services                   0     65,476 K
smss.exe                       668 Services                   0      1,256 K
csrss.exe                      856 Services                   0      6,040 K
wininit.exe                    956 Services                   0      7,588 K
csrss.exe                      964 Console                    1      6,336 K
services.exe                   432 Services                   0     10,732 K
lsass.exe                      756 Services                   0     23,004 K
winlogon.exe                   860 Console                    1     12,424 K
svchost.exe                   1132 Services                   0     26,140 K
fontdrvhost.exe               1160 Services                   0      4,508 K
fontdrvhost.exe               1168 Console                    1      9,920 K
svchost.exe                   1268 Services                   0     15,468 K
svchost.exe                   1312 Services                   0      9,216 K
svchost.exe                   1412 Services                   0     17,104 K
dwm.exe                       1428 Console                    1     85,752 K
svchost.exe                   1456 Services                   0      5,516 K
svchost.exe                   1484 Services                   0      8,192 K
svchost.exe                   1552 Services                   0      8,440 K
svchost.exe                   1560 Services                   0      8,936 K
svchost.exe                   1568 Services                   0     11,528 K
svchost.exe                   1660 Services                   0     17,540 K
svchost.exe                   1692 Services                   0     17,252 K
svchost.exe                   1724 Services                   0      6,024 K
svchost.exe                   1804 Services                   0     11,216 K
svchost.exe                   1924 Services                   0     14,764 K
svchost.exe                   1144 Services                   0      9,260 K
HipsDaemon.exe                1360 Services                   0    130,996 K
svchost.exe                   2116 Services                   0      8,584 K
svchost.exe                   2228 Services                   0      8,076 K
svchost.exe                   2352 Services                   0     16,968 K
svchost.exe                   2376 Services                   0      9,720 K
svchost.exe                   2424 Services                   0      7,428 K
svchost.exe                   2468 Services                   0     17,900 K
svchost.exe                   2488 Services                   0     10,500 K
svchost.exe                   2540 Services                   0      8,532 K
NVDisplay.Container.exe       2596 Services                   0     50,744 K
svchost.exe                   2656 Services                   0     23,868 K
svchost.exe                   2680 Services                   0      6,120 K
svchost.exe                   2688 Services                   0     12,524 K
svchost.exe                   2696 Services                   0      9,080 K
svchost.exe                   2760 Services                   0      9,380 K
svchost.exe                   2768 Services                   0      8,144 K
svchost.exe                   2952 Services                   0      7,156 K
dasHost.exe                   3004 Services                   0     20,244 K
usysdiag.exe                  3068 Services                   0      2,116 K
NVDisplay.Container.exe       3144 Console                    1     65,908 K
WmiPrvSE.exe                  3244 Services                   0      9,796 K
wsctrlsvc.exe                 3316 Services                   0      9,084 K
svchost.exe                   3384 Services                   0     14,296 K
svchost.exe                   3452 Services                   0      7,836 K
svchost.exe                   3504 Services                   0      7,632 K
svchost.exe                   3520 Services                   0     11,408 K
svchost.exe                   3724 Services                   0     20,584 K
svchost.exe                   3768 Services                   0     13,008 K
spoolsv.exe                   3796 Services                   0     17,308 K
svchost.exe                   3836 Services                   0     10,124 K
svchost.exe                   3844 Services                   0     23,756 K
svchost.exe                   3920 Services                   0      8,988 K
wlanext.exe                   3980 Services                   0     12,744 K
conhost.exe                   4188 Services                   0      9,492 K
svchost.exe                   4204 Services                   0     50,964 K
svchost.exe                   4212 Services                   0     11,636 K
svchost.exe                   4220 Services                   0     14,736 K
svchost.exe                   4228 Services                   0      7,552 K
svchost.exe                   4236 Services                   0     17,056 K
svchost.exe                   4244 Services                   0     12,352 K
nvcontainer.exe               4252 Services                   0     46,052 K
svchost.exe                   4268 Services                   0      6,292 K
WMIRegistrationService.ex     4276 Services                   0     14,644 K
svchost.exe                   4480 Services                   0      7,064 K
svchost.exe                   4560 Services                   0     10,284 K
jhi_service.exe               4712 Services                   0      7,192 K
Intel_PIE_Service.exe         4932 Services                   0     10,396 K
svchost.exe                   4456 Services                   0      8,768 K
rundll32.exe                  5324 Console                    1      7,068 K
AggregatorHost.exe            5436 Services                   0      8,564 K
svchost.exe                   6088 Services                   0      9,288 K
svchost.exe                   6148 Services                   0     14,988 K
ChsIME.exe                    6256 Console                    1      8,676 K
sihost.exe                    6328 Console                    1     28,900 K
svchost.exe                   6508 Console                    1     27,936 K
svchost.exe                   6532 Console                    1      8,920 K
svchost.exe                   6568 Console                    1     27,436 K
taskhostw.exe                 6636 Console                    1     19,832 K
MSIAfterburner.exe            6648 Console                    1      9,228 K
svchost.exe                   6724 Services                   0     20,736 K
svchost.exe                   6964 Services                   0     19,868 K
explorer.exe                  7152 Console                    1    276,548 K
svchost.exe                   7396 Console                    1     20,016 K
svchost.exe                   7444 Services                   0     10,160 K
svchost.exe                   7556 Services                   0     12,948 K
StartMenuExperienceHost.e     7792 Console                    1    122,144 K
Widgets.exe                   8024 Console                    1     46,440 K
RuntimeBroker.exe             8096 Console                    1     29,544 K
RuntimeBroker.exe             7344 Console                    1     34,824 K
svchost.exe                   8472 Console                    1      8,472 K
NVIDIA Web Helper.exe         8536 Console                    1     18,104 K
conhost.exe                   8568 Console                    1      1,552 K
dllhost.exe                   8760 Console                    1     16,044 K
ctfmon.exe                    7624 Console                    1     30,252 K
audiodg.exe                   1392 Services                   0     14,092 K
nvcontainer.exe               5460 Console                    1     36,120 K
nvcontainer.exe               3544 Console                    1     74,716 K
ChsIME.exe                    9572 Console                    1      8,976 K
smartscreen.exe               9940 Console                    1     11,608 K
SecurityHealthSystray.exe     9988 Console                    1     12,852 K
SecurityHealthService.exe    10008 Services                   0     20,980 K
RTSS.exe                      9256 Console                    1      4,532 K
EncoderServer.exe            10116 Console                    1      4,912 K
RTSSHooksLoader64.exe         3580 Console                    1      1,304 K
HipsTray.exe                 10252 Console                    1     22,344 K
nvsphelper64.exe             10984 Console                    1     16,768 K
NVIDIA Share.exe             10996 Console                    1     86,432 K
NVIDIA Share.exe             11288 Console                    1     57,716 K
SearchIndexer.exe            11360 Services                   0     33,448 K
NVIDIA Share.exe             11428 Console                    1     83,672 K
TextInputHost.exe            11976 Console                    1     78,376 K
cmd.exe                       1220 Console                    1      7,376 K
svchost.exe                   1276 Services                   0     15,340 K
conhost.exe                   2368 Console                    1     19,572 K
java.exe                      2964 Console                    1  2,534,476 K
taskhostw.exe                 7412 Console                    1      9,460 K
ApplicationFrameHost.exe      7360 Console                    1     39,104 K
svchost.exe                   1852 Console                    1     13,816 K
svchost.exe                   1668 Services                   0      8,368 K
svchost.exe                   1972 Services                   0     11,616 K
svchost.exe                   2248 Console                    1     10,296 K
svchost.exe                   3256 Services                   0     11,888 K
svchost.exe                   6344 Services                   0     14,840 K
svchost.exe                   9408 Services                   0     13,808 K
SearchHost.exe               11376 Console                    1    211,068 K
javaw.exe                    12168 Console                    1    192,184 K
svchost.exe                   1184 Services                   0     11,716 K
svchost.exe                  12472 Services                   0     13,164 K
svchost.exe                  12628 Console                    1     14,168 K
svchost.exe                  13212 Services                   0      7,484 K
java.exe                     10732 Console                    1  1,617,080 K
conhost.exe                   6940 Console                    1     10,984 K
SystemSettings.exe            6112 Console                    1     54,720 K
RuntimeBroker.exe            11700 Console                    1     24,204 K
svchost.exe                   2396 Services                   0     14,948 K
cmd.exe                       7316 Console                    1      5,384 K
conhost.exe                  11212 Console                    1     20,372 K
WMIADAP.exe                    972 Services                   0      9,376 K
ShellExperienceHost.exe       8672 Console                    1     75,616 K
RuntimeBroker.exe            10768 Console                    1     25,424 K
WidgetService.exe             8928 Console                    1     26,980 K
SystemSettingsBroker.exe      8320 Console                    1      7,000 K
msedgewebview2.exe            6664 Console                    1      2,556 K
msedgewebview2.exe            8308 Console                    1     10,104 K
msedgewebview2.exe            1860 Console                    1        984 K
msedgewebview2.exe            3888 Console                    1        480 K
msedgewebview2.exe            1628 Console                    1         72 K
msedgewebview2.exe           11008 Console                    1      1,116 K
msedge.exe                   11296 Console                    1    158,940 K
msedge.exe                   10208 Console                    1     10,632 K
msedge.exe                   12488 Console                    1     63,016 K
msedge.exe                    1292 Console                    1     41,108 K
msedge.exe                   10640 Console                    1     18,288 K
msedge.exe                    4328 Console                    1     15,024 K
msedge.exe                    2208 Console                    1     28,992 K
msedge.exe                    7288 Console                    1     59,516 K
identity_helper.exe           4364 Console                    1     37,204 K
svchost.exe                   5856 Console                    1     21,992 K
tasklist.exe                  4772 Console                    1      9,368 K
WmiPrvSE.exe                 12604 Services                   0     10,692 K

Is this it, I seem a little stupid, can you tell me what kind of information I should provide?
