### ISSUE TITLE
Endermite cannot attract Enderman through hatred

### ISSUE THREAD

**Issue by gary81013** [PaperSpigot/Paper#9708]
### Expected behavior

Endermite cannot attract Enderman through hatred

### Observed/Actual behavior

Endermite cannot attract Enderman through hatred

### Steps/models to reproduce

Endermite cannot attract Enderman through hatred

### Plugin and Datapack List

vanilla file/bukkit

### Paper version

paper-1.20.1-174

### Other

This problem only occurred after I upd

**Comment by Warriorrrr** [comment]
Please provide actual reproduction instructions, how are you summoning the endermite? Only ones spawned naturally will attract them

**Comment by gary81013** [comment]
> Please provide actual reproduction instructions, how are you summoning the endermite? Only ones spawned naturally will attract them

The Enderman monster spawning tower I originally used can be used normally.
When I update the paper version, it can no longer be used.
Monsters occur naturally
When I actually tested Endermite's hatred value, there was less than 10 blocks left.
The wiki says there is a 64-frame range

**Comment by Malfrador** [comment]
Very likely related to https://github.com/PaperMC/Paper/commit/72e87abc2db813ecd74a323c33a7b9c79b0c67b9
Simple replication build:
![TabTip_6TM5qyepDq](https://github.com/PaperMC/Paper/assets/6106558/f4ec24bf-de8d-4a1b-880c-fa0214979f9b)

On build 171, nearly all endermen instantly run towards the endermite in the minecart. On build 175, the vast majority of endermen just stand around idling on the platform on the left, not trying to attack the endermite.

**Comment by kennytv** [comment]
Fixed https://github.com/PaperMC/Paper/commit/517f8fbbac2467fb24fa87d6bd56ce5c1b9bc972
