### ISSUE TITLE
Player doesn't spawn at bed spawnpoint

### ISSUE THREAD

**Issue by eetnaviation** [PaperSpigot/Paper#9729]
### Expected behavior

When setting spawnpoint via bed or /spawnpoint player would spawn at the set spawnpoint.

### Observed/Actual behavior

Player spawns at world spawn.

### Steps/models to reproduce

.

### Plugin and Datapack List

![image](https://github.com/PaperMC/Paper/assets/117541874/ace21696-c5ec-4dac-9d06-32d79e3b6b5b)

### Paper version

This server is running Paper version git-Paper-163 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 6f30f08)
You are 20 version(s) behind
Download the new version at: https://papermc.io/downloads/paper

**Comment by Leguan16** [comment]
Hey!

Can you reproduce this without plugins? 

My guess would be EssentialsSpawn.

**Comment by lynxplay** [comment]
Closing this, as it is not replicable and, as @Leguan16 suggested, this *strongly* feels like a plugin.
If you can replicate this without plugins, feel free to comment here and we can reopen this.
