### ISSUE TITLE
Trade menu closed when i teleported

### ISSUE THREAD

**Issue by Gfortes985** [PaperSpigot/Paper#9730]
### Expected behavior

i open trade menu and push myself in ender gate using water and when i teleported to main island menu is still open 

### Observed/Actual behavior

i open trade menu and push myself in ender gate using water and when i teleported to main island menu is closed

### Steps/models to reproduce

1:Open trade menu
2:teleport away from the villager to unload him
3:Menu is closed(but it shouldn't be this way)

### Plugin and Datapack List

![image](https://github.com/PaperMC/Paper/assets/59264654/76643420-c0b3-435e-a3d1-d1721b90e80a)

### Paper version

This server is running Paper version git-Paper-183 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: eb60bff)
You are running the latest version
Previous version: git-Purpur-2047 (MC: 1.20.1)

**Comment by Gfortes985** [comment]
Is there any setting to fix this?

**Comment by lynxplay** [comment]
If you are referring to void trading, #6510 is fixed without a config option to re-enable.
Additionally you are not using paper.

**Comment by Machine-Maker** [comment]
For more context, this is a [confirmed vanilla issue](https://bugs.mojang.com/browse/MC-50614).
