### ISSUE TITLE
Reload command improvement

### ISSUE THREAD

**Issue by NonSwag** [PaperSpigot/Paper#9731]
### Is your feature request related to a problem?

For many years now, the `/bukkit:reload` command is the worst nightmare of every plugin developer.
It breaks everything and should not act as a way to "restart" the server while running.

### Describe the solution you'd like.

My proposal would be to drop the current behavior, and add a Plugin#onReload method or an event like velocity does.
This would probably be a good thing for the new paper plugins.

### Describe alternatives you've considered.

Another option would be adding the method or event and keeping the reload command as it is but add a new argument like `/reload configs` which would trigger a config reload for all plugins

**Comment by lynxplay** [comment]
Closing this in favour of #8859, generally the bukkit reload mechanic is flawed but touching it now that many people expect some form of broken behaviour seems troublesome.

I can 100% see a usecase for a better lifecycle (e.g. proposed in #4317) in paper plugins, but that can be discussed in the respective issue :+1:
