### ISSUE TITLE
'/team' is broken

### ISSUE THREAD

**Issue by wifi-left** [PaperSpigot/Paper#9732]
### Expected behavior

The server will read all the lines when it starts

### Observed/Actual behavior

All teams (66) are read normally on the first startup. But when it started up again after shutting down the server, there were only 7 teams left

### Steps/models to reproduce

1. Add as many teams as possible
2. Use `/team list` to check all teams
3. Stop server
4. Restart the server
5. Use `/team list`, and you can see that most of the teams were disappeared

### Plugin and Datapack List

```
> plugins
[12:30:12 INFO]: Server Plugins (0):

> datapack list
[12:30:25 INFO]: There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]
[12:30:25 INFO]: There are no more data packs available
```

### Paper version

```
 > version
[12:31:23 INFO]: Checking version, please wait...
[12:31:25 INFO]: This server is running Paper version git-Paper-193 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 581b683)
You are running the latest version
```

### Other

This only goes wrong on paper, it doesn't go wrong in spigot or the original

**Comment by Warriorrrr** [comment]
Did you add any players to the teams? Empty teams will not be saved by default, you can find the config option for it [here](https://docs.papermc.io/paper/reference/global-configuration#scoreboards_save_empty_scoreboard_teams).

**Comment by wifi-left** [comment]
> Did you add any players to the teams? Empty teams will not be saved by default, you can find the config option for it [here](https://docs.papermc.io/paper/reference/global-configuration#scoreboards_save_empty_scoreboard_teams).

No, I don't.
I don't think empty teams should be cleared
This is extremely important for map makers

**Comment by wifi-left** [comment]
Thank you for your answer
