### ISSUE TITLE
Adding an event for adding items to a player's inventory

### ISSUE THREAD

**Issue by Fisher2911** [PaperSpigot/Paper#9735]
### Is your feature request related to a problem?

An example problem would be if a plugin gives items to a player, but the player's inventory is full so the plugin drops the extra items on the ground, but the server has a feature where there is a collection box where the items should go to be collected.

### Describe the solution you'd like.

An event added to PlayerInventory that is called when items are added. This event would happen after items are given to the player, but before the items that could not be added were returned in the [Inventory#giveItem](https://jd.papermc.io/paper/1.20/org/bukkit/inventory/Inventory.html#addItem(org.bukkit.inventory.ItemStack...)) method. 
The event would have the following fields:
* Map<Integer, ItemStack> notGivenItems - the items that were not able to be given to the inventory.
This would allow other plugins to edit the items and handle them, and they can clear the map if they do not want the original plugin that added items to do anything with them.

### Describe alternatives you've considered.

There aren't really any alternatives that I have found.

### Other

I just wanted to make the issue to see if it's something Paper would consider adding if a PR was made for it.

**Comment by lynxplay** [comment]
There is https://jd.papermc.io/paper/1.20/io/papermc/paper/event/player/PlayerInventorySlotChangeEvent.html, should get you rather far.

I am not a fan of the rather niche event the issue proposes. Events *just* introduced for the API calls also seems questionable.
What is the actual XY here ? Plugins calling addItem should handle the returned items gracefully.
If your plugin needs to interface with that, it should be on the plugin to allow you to do that, not us.

**Comment by Fisher2911** [comment]
That makes sense, I just created the issue to see what the thoughts about it would be.
