### ISSUE TITLE
Painting loose its art/variant when the direction is changed once spawned

### ISSUE THREAD

**Issue by Lulu13022002** [PaperSpigot/Paper#9737]
### Expected behavior

Changing the direction of a painting should only change the direction of the painting

### Observed/Actual behavior

Changing the direction of a painting change the direction of the painting **AND** its art is reset to the default one (clientside)

### Steps/models to reproduce

Just a very simple plugin that change the direction of the painting once spawned later

### Plugin and Datapack List

This test plugin

### Paper version

3fd1502717e753405a74fbad4a16d2fd7a14187b

### Other

This is due to the variant metadata not being dirty and by the fact that the painting needs to be resend completely to the client once already spawned. A similar things happens to the item frame however they correctly resend their data. Ideally the entity data must be dirty only if not set to default and possibly not only DATA_PAINTING_VARIANT_ID but all the non default ones but i don't think it's really worth for the latter.

Do note that when the player quit/rejoin the server the painting is properly updated.

**Comment by Owen1212055** [comment]
```diff
@@ -1250,7 +1251,9 @@
             return;
         }
 
-        entityTracker.broadcast(this.getHandle().getAddEntityPacket());
+        for (ServerPlayerConnection playerConnection : entityTracker.seenBy) {
+            this.getHandle().getEntityData().resendPossiblyDesyncedEntity(playerConnection.getPlayer());
+        }
     }
 
     private static PermissibleBase getPermissibleBase() {
```
I think that updating the  ``protected void update()`` method in CraftEntity is the proper way to do this. The markDirty call in item frame should then be removed. This should be added into the `Properly resend entities ` patch.

**Comment by notTamion** [comment]
> can you assign me this issue

You don't have to ask to be assigned an issue, just start working on a fix and when done create a pr that mentions this issue.

**Comment by electronicboy** [comment]
We can't assign issues to outsiders, and fwiw, this has been resolved
