### ISSUE TITLE
New Minecraft 1.20.2 Update

### ISSUE THREAD

**Issue by nicdgonzalez** [PaperSpigot/Paper#9741]
### Is your feature request related to a problem?

Minecraft Java Edition released 1.20.2 a little over 2 hours ago. I'm unsure of the complexity that goes into updating the paper server so I just wanted to notify you all of the news and offer assistance in whatever way possible.

### Describe the solution you'd like.

For the PaperMC Downloads section to provide 1.20.2.

### Describe alternatives you've considered.

Official Minecraft website provides a 1.20.2 server.jar file.

### Other

Link to the article announcing 1.20.2 and outlining all of its changes:
https://www.minecraft.net/en-us/article/minecraft-java-edition-1-20-2

Minecraft's 1.20.2 server:
https://www.minecraft.net/en-us/download/server

If there is anything I can do to help move this along, please let me know.

**Comment by underscore11code** [comment]
Paper staff are aware of the update and are actively working on updating it as we speak (join our [discord](https://discord.gg/papermc) if you want to watch the update stream).
