### ISSUE TITLE
Fake players do not hold chunks (NMS serverplayer)

### ISSUE THREAD

**Issue by sjavi4** [PaperSpigot/Paper#9750]
### Expected behavior

In Spigot server, fake players can keep ticking chunks even if real players teleport far away.

But in Paper server, chunks will immediately unload when real players teleport far away.
(Need to turn off chunk loading in yml [It manually adding player ticket to load chunks]  )

### Observed/Actual behavior

**_entity.touchingUnloadedChunk();_**
- Always return False in Spigot server
- Return true in Paper server when real player leave.

**_/paper entity list minecraft:player_**
- Ticking when real players together with fake player
- Non-ticking when real players not with fake player

### Steps/models to reproduce

https://github.com/PaperMC/Paper/assets/72385460/0c07938b-b02f-468e-aea6-47e6a0cab55f

### Plugin and Datapack List

![image](https://github.com/PaperMC/Paper/assets/72385460/4163a79f-f188-4fff-9bb1-ce581d7051be)

### Paper version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Purpur-1996 (MC: 1.20.1)

### Other

Plugin: https://github.com/sjavi4/ShulkerBoxNBTCrafter

**Comment by lynxplay** [comment]
Given the plugin linked does not appear to have any straight forward replication code and you are dealing with internals, this is pretty much unsupported land, you are on your own.

Feel free to pop by our [discord](https://discord.gg/papermc) where people might be able to help you with this, but this is certainly not a straight forward paper issue as neither spigot nor paper promise you to be able to create a fake player, you are just hacking with internals.
