### ISSUE TITLE
Entity isn't hidden even if Player#hideEntity is called

### ISSUE THREAD

**Issue by Endxxr** [PaperSpigot/Paper#9752]
### Expected behavior

When Player#hideEntity(Plugin, Entity) is called, the passed entity should be hidden to the player.

### Observed/Actual behavior

Nothing happens with no errors in console.

### Steps/models to reproduce

```
//All given values are not null

ArmorStand armorStand = (ArmorStand) location.getWorld().spawnEntity(location, EntityType.ARMOR_STAND);
entityUUID = armorStand.getUniqueId();
armorStand.setInvisible(true);
armorStand.setInvulnerable(true);
armorStand.setGravity(false);
armorStand.setCustomNameVisible(true);
armorStand.setCanMove(false);
armorStand.customName(ChatUtils.colorizeComponent(configuration.getString("chests."+id+".hologram")));

player.hideEntity(instance, armorStand);
```

### Plugin and Datapack List

![immagine](https://github.com/PaperMC/Paper/assets/73839093/1ada95b2-4d87-4ffe-9fa7-4240da950493)

### Paper version

```
[13:23:23 INFO]: This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Purpur-1985 (MC: 1.19.4)
```

### Other

The only plugins which interface with HideEntity is mine (RadChest).

Player#showEntity works (only tested with Entity hidden by default).

**Comment by Endxxr** [comment]
Doesn't work in 1.19.4 too

**Comment by Jakush** [comment]
Do you really use Paper?

**Comment by Endxxr** [comment]
Nevermind, it was a client thing.
