### ISSUE TITLE
[1.20.2] When teleporting a player to another world in PlayerJoinEvent the server crashes

### ISSUE THREAD

**Issue by Brokkonaut** [PaperSpigot/Paper#9760]
### Expected behavior

no crash (it worked in 1.20.1)

### Observed/Actual behavior

crash: https://cpaste.de/uxababimog.properties

### Steps/models to reproduce

have a server with multiverse or probably some other multiworld plugin and teleport the player in PlayerJoinEvent to another world (the crash in the log was a teleport from a secondary world "xyz" to the main world "world")

### Plugin and Datapack List

No datapacks, Multiverse + some custom plugins

### Paper version

This server is running Paper version git-Paper-"298c478" (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 298c478)

**Comment by emilyy-dev** [comment]
Teleporting the player in the join event is largely unsupported, to change the join spawn location use the [`PlayerSpawnLocationEvent`](https://jd.papermc.io/paper/1.20/org/spigotmc/event/player/PlayerSpawnLocationEvent.html#setSpawnLocation(org.bukkit.Location)). If changing the spawn location in that event still ends in unexpected results open a new issue instead.

**Comment by Brokkonaut** [comment]
Thank you, that is working.

but even if it is unsupported to teleport players there (is there any documentation for that? we used it for years and never had any issues) i think it should not cause a hard crash of the server but either return false from the teleport method or throw an exception
