### ISSUE TITLE
/setworldspawn don't work

### ISSUE THREAD

**Issue by SHDocter** [PaperSpigot/Paper#9767]
### Expected behavior

When I set the world's spawning point, players can spawn in the correct place

### Observed/Actual behavior

When I set the world's spawning point, the place where the player revives after death is still the default spawning point on the map, and the player has not set home or bed. But /setspawn is work.

### Steps/models to reproduce

/setworldspawn
/suicide or /kill

### Plugin and Datapack List

CoreProtect, Essentials, EssentialsDiscord, EssentialsDiscordLink, Multiverse-Core, Multiverse-Portals, PluginManager, WorldEdit

### Paper version

This server is running Paper version git-Paper-"773dd72" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72 on HEAD)

**Comment by kennytv** [comment]
One of your plugins is overriding the spawn location.
