### ISSUE TITLE
Code working with spigot but not paper

### ISSUE THREAD

**Issue by xWil** [PaperSpigot/Paper#9768]
### Expected behavior

```
//1.20.1
ClientboundSystemChatPacket packet = new ClientboundSystemChatPacket(IChatBaseComponent.ChatSerializer.a(line), false);
(((CraftPlayer) player).getHandle()).c.a(packet);

//1.20.2
ClientboundSystemChatPacket packet = new ClientboundSystemChatPacket(IChatBaseComponent.ChatSerializer.fromJson(line), false);
(((CraftPlayer) player).getHandle()).connection.send(packet);
```
It should send a player a chat message with the json formatting.

Example when line = '{"text":"Testing","bold":true,"color":"red"}'

![example](https://github.com/PaperMC/Paper/assets/60199470/9df29369-348a-46bf-937f-92a1685d9403)

### Observed/Actual behavior

The 1.20.1 version of the code works perfectly fine, when testing the 1.20.2 version of the code, it worked as expected on a spigot server, however on a paper server I received this error in console

`java.lang.NoSuchMethodError: 'net.minecraft.network.chat.IChatMutableComponent net.minecraft.network.chat.IChatBaseComponent$ChatSerializer.fromJson(java.lang.String)'`

### Steps/models to reproduce

```
<dependency>
    <groupId>org.spigotmc</groupId>
    <artifactId>spigot</artifactId>
    <version>1.20.2-R0.1-SNAPSHOT</version>
    <scope>provided</scope>
</dependency>
```

This is my maven dependency for spigot 1.20.2
Add code to command or whatever you want as long as you have a Player object

### Plugin and Datapack List

Spigot Server:
CoreProtect, LuckPerms, InventoryRollbackPlus, OpenInv, PlaceholderAPI, truescoreboards, PlugManX
 
Paper Sever:
ChatInjector, ConditionalTextPlaceholders, CoreProtect, DiscordSRV, dynmap, Essentials, EssentialsChat, EssentialsSpawn, floodgate, Geyser-Spigot, GSit, InventoryRollbackPlus, LiteBans, LuckPerms, PlaceholderAPI, PlayerWarps, PlugmanX, ProtocolLib, QuickShop, RewardsListe, spark, Vault

### Paper version

This server is running Paper version git-Paper-203 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: fe54a13)
You are running the latest version
Previous version: git-Paper-201 (MC: 1.20.2)

**Comment by Owen1212055** [comment]
NMS compatibility is never promised, we make changes here.

**Comment by MiniDigger** [comment]
just use the api to send the message? using internals for this is just wrong.

**Comment by electronicboy** [comment]
Looks like spigot was also recently shipping mangled jars from his tooling recently in regards to mappings and such
