### ISSUE TITLE
Document that Player#getListeningPluginChannels does not contain BungeeCord

### ISSUE THREAD

**Issue by A248** [PaperSpigot/Paper#9771]
### Is your feature request related to a problem?

Due to its special status, "BungeeCord" will never appear in `Player#getListeningPluginChannels`. This is not mentioned in the javadoc, however, nor in the documentation for `Messenger`, nor on docs.papermc.io.

### Describe the solution you'd like.

Document that Player#getListeningPluginChannels does not return the BungeeCord channel.

### Describe alternatives you've considered.

Continue to leave this information buried in the depths of Bukkit-specific expertise.

**Comment by jake-brennan714** [comment]
I'm interested in working on this, if there's any way that I can help!

**Comment by notTamion** [comment]
If you wanna try to submit a pull request start off by reading the [Contributing Guidelines](https://github.com/PaperMC/Paper/blob/master/CONTRIBUTING.md), these will contain pretty much everything you need.

**Comment by jake-brennan714** [comment]
Took a deeper look at the code. This requires changes to Bukkit code as far as I can tell, which is out of scope for the PaperMC repo.

**Comment by powercasgamer** [comment]
> Took a deeper look at the code. This requires changes to Bukkit code as far as I can tell, which is out of scope for the PaperMC repo.

What?

**Comment by notTamion** [comment]
Also if you have any questions about the paper contributing process feel free to ask on the discord server.

**Comment by jake-brennan714** [comment]
> > Took a deeper look at the code. This requires changes to Bukkit code as far as I can tell, which is out of scope for the PaperMC repo.
> 
> What? This is just fine for Paper. Could probably be put in https://github.com/PaperMC/Paper/blob/master/patches/api/0056-Fix-upstream-javadocs.patch

Well I'm dumb. Lol, lemme go do that rq.

**Comment by jake-brennan714** [comment]
Just not used to this way of doing things, hence my thinking it'd be out of scope.
