### ISSUE TITLE
Attribute modifers not being applied to entities (1.20.2 Experimental) 

### ISSUE THREAD

**Issue by CodionCA** [PaperSpigot/Paper#9772]
### Expected behavior

Attribute modifiers previously worked by applying that modifier to entities that are holding an item. For example giving a horse ar
mour with a +15 health modifier applied with: _/give @p iron_horse_armor{AttributeModifiers:[{AttributeName:"generic.max_health",Name:"generic.max_health",Amount:15,Operation:0,UUID:[I;1449193714,-1470545029,-1967556178,-1026784851]}]} 1_

Previous behavior pictured below 1.20.1:
![Screenshot 2023-09-28 133911](https://github.com/PaperMC/Paper/assets/61989733/bfdb753f-2eaa-4e7e-acbb-4d4b0eba0d78)

### Observed/Actual behavior

Now attribute modifiers do not function at all for entities on the latest experimental builds, using that same command from above no attribute is applied to the horse. 

![Screenshot 2023-09-28 134712](https://github.com/PaperMC/Paper/assets/61989733/64b39daf-83ce-4b03-8f5b-86fbfdf22429)

This is also not visual as the horse still is at its original health: 
![Screenshot 2023-09-28 135049](https://github.com/PaperMC/Paper/assets/61989733/8591b7b3-bc5f-4307-8b79-cf9016e6993f)

### Steps/models to reproduce

1. Start a fresh server using PaperMC Build 203 on 1.20.2

2. Op yourself

3. Apply health/Movement Speed attribute modifier to an item that an entity can pick up or wear (Like horse armour or a zombie carrying a sword)

4. Observe health not changing with /data get entity @e[type=minecraft:horse,sort=nearest,limit=1] or visibly with no increase to movement speed/health display.

### Plugin and Datapack List

None

### Paper version

This server is running Paper version git-Paper-203 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: fe54a13)
You are running the latest version

### Other

There is also a problem of the horse armour not displaying to the player until re-logging but I am not sure if this is related the the issue or paper at all. Ill update here after more testing.

**Comment by Warriorrrr** [comment]
Can confirm this was an issue on build 203, this seems to have been fixed by upstream in build 205
