### ISSUE TITLE
Huge lag spikes (freezes and crashes) on sync chunk load

### ISSUE THREAD

**Issue by DevPGSV** [PaperSpigot/Paper#9777]
### Timings or Profile link

https://timings.aikar.co/dev/?id=6e5a232e57654669a5c168e0587c04ba

### Description of issue

We are having some lag spikes in our paper server that we have not been able to fix for several weeks.
The server can usually handle 30 players at the same time without issue (perhaps with some drops to 19 tps).
However, other times, even with 1 or 2 players, TPS go down, to the point of every player being disconnected. Sometimes this lag spikes end in a server reboot (I guess the server/watchdog detects something wrong and decides to reboot). Sometimes the server just crashes without a proper reboot, so we get a small "rollback" of the world (to the last time the world was saved to file, our players report rollbacks between 30 seconds up to around 10 minutes).

Sometimes the server is running with a lot of players for several hours without problems. Sometimes the server is struggling, and after it crashes (or we manually restart it) the server keeps struggling. It looks like the problem depends on what the players are doing, not on the amount of players, or the amount of time the server has been running.

Looking at the logs and the actions of our players, we believe the problem is sync chunk loading. After trying to optimize paper configs as much as possible, we don't know what else we could do to prevent this issue from happening again.
We've used chunky to pregenerate the worlds, and we've setup world borders to make sure players can not go chunks not yet generated. 

Our CPU usage is usually low. When this lag spikes happen, the CPU usage stays low.

I've never seen the RAM usage go near the max we have configured:
```
[09:22:28 INFO]: [Essentials] CONSOLE issued server command: /gc 
[09:22:28 INFO]: Tiempo encendido: 1 hora 9 minutos 50 segundos
[09:22:28 INFO]: Ticks por segundo = 20
[09:22:28 INFO]: Memoria máxima: 12,288 MB.
[09:22:28 INFO]: Memoria asignada: 12,288 MB.
[09:22:28 INFO]: Memoria libre: 7,025 MB.
[09:22:28 INFO]: World "world": 754 chunks, 226 entidades, 592 tiles.
[09:22:28 INFO]: Nether "world_nether": 529 chunks, 116 entidades, 3 tiles.
[09:22:28 INFO]: The End "world_the_end": 529 chunks, 24 entidades, 46 tiles.
```
(free memory) `Memoria libre: 7,025 MB. `. I've never seen the free memory go under 4,000MB (even during lag spikes).

The server is running on a debian machine. Monitoring the resources with `htop` while the lag spikes and crashes are happening shows nothing of interest. Looking at `iotop` never shows activity higher that 1 MB/s.
It is a dedicated machine, used only for the minecraft server. To rule out the possibility of ram damage, we've changed the ram stick with the sticks used in a different machine (a different minecraft server), but the problem persists.

Here are some logs when the lag spikes happen:

- https://paste.gg/p/DevPGSV/65cdf7c3c3704828b120961fd9ef3879
- https://paste.gg/p/DevPGSV/5f84fed423894554816dbeccdccdf44d
  - Looks like a player died, and trying to find where to respawn that player loaded chunks, and that caused the freeze
- https://paste.gg/p/DevPGSV/80af71a11f664359b475edae0ebb51db
  - I have anonymized the logs by changing the names of the players to Player[N]
  - Looks like a player use the nether portal, that loaded chunks, and that caused the freeze (all players were disconected)
- https://paste.gg/p/DevPGSV/bed1dee4d47c4acb8e99fed1c8b9d485
  - Looks like I joined, that loaded chunks, and that caused the freeze

The following aikar timings: "https://timings.aikar.co/dev/?id=6e5a232e57654669a5c168e0587c04ba" should include the timeframe of the previously mentioned 4 freezes.
If helpful, we can temporarily install spark and provide its reports.

Thank you for developing such an amazing project and for your time.

### Plugin and Datapack List

Server Plugins (39):
Paper Plugins:
  - MarriageMaster, PaperTweaks
 Bukkit Plugins:
  - AdvancedRegionMarket, AuthMe, Chunky, ChunkyBorder, Citizens, CMILib, CoreProtect, DecentHolograms, DeluxeMenus, Denizen, dynmap, Dynmap-Towny, Essentials, EssentialsSpawn, FastLogin, HeadDatabase, Jobs, LocketteX, LuckPerms, Multiverse-Core, NoChatReports, NoSignEdit, PlaceholderAPI, ProtocolLib, Quests, Shop, SkinsRestorer, SuperVanish, TAB,TerraformGenerator, Towny, TownyChat, TownyMenu, Vault, WorldEdit, WorldGuard, WorldGuard-Towny

### Server config files

- [bukkit.yml](https://paste.gg/p/DevPGSV/dca3766bbd62432d9974924683e0af99)
- [spigot.yml](https://paste.gg/p/DevPGSV/22511f1fa5f041e0a145f07c3ca2fd30)
- [paper-global.yml](https://paste.gg/p/DevPGSV/2e7961caa5174f01925c88b24acc572d)
  - No per-world configs
- [paper-world-defaults.yml](https://paste.gg/p/DevPGSV/bb434ced74c945c78d22efc279dbc2b0)
- [server.properties](https://paste.gg/p/DevPGSV/ea313199203e4ef59a19c25c834e8eac)

### Paper version

```
[09:11:17 INFO]: Checking version, please wait...
[09:11:18 INFO]: This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Paper-176 (MC: 1.20.1)
```

**Comment by Malfrador** [comment]
Thank you for your detailed report, but this is not a Paper issue.

A spawnpoint lookup is a slow process that needs to be done on the main server thread. EssentialsX seems to cause such a spawnpoint search on join, but it can also happen on respawn. Especially if the chunks are not pre-generated, which seems to be the case here (`currentGenStatus=null, requestedGenStatus=minecraft:full`), it will be very slow because suddenly a lot of chunks have to be generated on the main thread. 
This combined with your rather slow and/or overloaded hardware (i7-7700 with loadavg of 5.7 and timingcost of 340) will cause the lag you are experiencing. 

You can try using the [EssentialsX support discord](https://discord.gg/h8CnPSw), although your server seems to be running offline-mode, which I believe they don't support (just like Paper).

If you are running a supported setup in the future (aka not in offline mode), you can also use the [Paper Discord](https://discord.gg/papermc) for support on performance issuesbut the issue tracker is only intended to be used for issues with Paper itself.
