### ISSUE TITLE
Setting RawData for Barrel BlockState removes barrel from world

### ISSUE THREAD

**Issue by ZombieStriker** [PaperSpigot/Paper#9782]
### Expected behavior

Setting the raw data should apply data such as rotation and whether the barrel is open.

### Observed/Actual behavior

Upon setting the raw data for the barrel, and updating the block state, the barrel disappears from the world.

### Steps/models to reproduce

1. Place down a barrel block, either by code or manually
2. Get the block's state
3. Set the block's state's raw data equal to the raw data from getRawData()
4. Update the block
5. The barrel will now disappear

### Plugin and Datapack List

The test plugin used to test this behavior.

### Paper version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Paper-307 (MC: 1.19.2)

**Comment by Machine-Maker** [comment]
Haven't get/setRawData been deprecated for many years?

**Comment by ZombieStriker** [comment]
Most likely. However, it is useful for a plugin I'm making (The alternative being devising my own byte system for storing block data), which is how I found out about this behavior. 

I most likely will now need to devise my own byte system, in order to be backwards compatible, but in case someone wants to fix this bug, that would be helpful going forward.
