### ISSUE TITLE
Updating BlockState for Container clears inventory

### ISSUE THREAD

**Issue by ZombieStriker** [PaperSpigot/Paper#9784]
### Expected behavior

After getting the Container and the inventory, and after adding an item to the inventory, using the "BlockState#update(true,false)" method should update the blockstate, while preserving the new items in the inventory.

### Observed/Actual behavior

The inventory is cleared upon forcing an update

### Steps/models to reproduce

Container container = .....
container.getInventory().addItem(.....)
container.update(true,false)

This will clear the inventory of the new item added by addItem

### Plugin and Datapack List

The plugin used to test this

### Paper version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Paper-307 (MC: 1.19.2)

**Comment by Machine-Maker** [comment]
I think you have to use getSnapshotInventory instead of getInventory. getInventory is the live inventory, so calling update after it sets it back to whatever it was when you got the block state.

**Comment by electronicboy** [comment]
yes, if you wish to modify the snapshots inventory you need to explicitly get it, otherwise, modify the real inventory with getInventory without calling update

there is no tenable way to handle this otherwise which doesn't create its own set of issues
