### ISSUE TITLE
Failed to get system info for Microarchitecture

### ISSUE THREAD

**Issue by yinzixie** [PaperSpigot/Paper#9785]
### Stack trace

mc-survival  | Starting org.bukkit.craftbukkit.Main
mc-survival  | System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.8+7-alpine-r0) Host: Linux 5.15.0-1042-oracle (aarch64)
mc-survival  | Loading libraries, please wait...
mc-survival  | 2023-10-02 17:35:15,842 ServerMain WARN Advanced terminal features are not available in this environment
mc-survival  | [17:35:16 WARN]: [oshi.software.os.linux.LinuxOperatingSystem] Did not find udev library in operating system. Some features may not work.
mc-survival  | [17:35:16 WARN]: Failed to get system info for Microarchitecture
mc-survival  | java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "this.cpuVendor" is null
mc-survival  |  at oshi.hardware.CentralProcessor$ProcessorIdentifier.queryMicroarchitecture(CentralProcessor.java:825) ~[oshi-core-6.4.5.jar:6.4.5]
mc-survival  |  at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.5.jar:6.4.5]
mc-survival  |  at oshi.hardware.CentralProcessor$ProcessorIdentifier.getMicroarchitecture(CentralProcessor.java:816) ~[oshi-core-6.4.5.jar:6.4.5]
mc-survival  |  at net.minecraft.SystemReport.setDetail(SystemReport.java:62) ~[paper-1.20.2.jar:git-Paper-207]
mc-survival  |  at net.minecraft.SystemReport.putProcessor(SystemReport.java:153) ~[paper-1.20.2.jar:git-Paper-207]
mc-survival  |  at net.minecraft.SystemReport.lambda$putHardware$4(SystemReport.java:72) ~[paper-1.20.2.jar:git-Paper-207]
mc-survival  |  at net.minecraft.SystemReport.ignoreErrors(SystemReport.java:85) ~[paper-1.20.2.jar:git-Paper-207]
mc-survival  |  at net.minecraft.SystemReport.lambda$putHardware$4(SystemReport.java:72) ~[paper-1.20.2.jar:git-Paper-207]
mc-survival  |  at net.minecraft.SystemReport.lambda$new$2(SystemReport.java:47) ~[paper-1.20.2.jar:git-Paper-207]
mc-survival  |  at net.minecraft.SystemReport.ignoreErrors(SystemReport.java:85) ~[paper-1.20.2.jar:git-Paper-207]
mc-survival  |  at net.minecraft.SystemReport.lambda$new$2(SystemReport.java:47) ~[paper-1.20.2.jar:git-Paper-207]
mc-survival  |  at net.minecraft.CrashReport.<init>(CrashReport.java:32) ~[paper-1.20.2.jar:git-Paper-207]
mc-survival  |  at net.minecraft.CrashReport.preload(CrashReport.java:252) ~[paper-1.20.2.jar:git-Paper-207]
mc-survival  |  at net.minecraft.server.Main.main(Main.java:129) ~[paper-1.20.2.jar:git-Paper-207]
mc-survival  |  at org.bukkit.craftbukkit.Main.main(Main.java:324) ~[paper-1.20.2.jar:git-Paper-207]
mc-survival  |  at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
mc-survival  |  at java.lang.Thread.run(Thread.java:833) ~[?:?]
mc-survival  | [17:35:24 INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]

### Plugin and Datapack List

No

### Actions to reproduce (if known)

I run this in docker compose with velocity.
System is ubuntu 20, cpu is ARM.

### Paper version

This server is running Paper version git-Paper-207 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 38376f4)
You are running the latest version
Previous version: git-Paper-206 (MC: 1.20.2)

**Comment by cosmohdx** [comment]
You can add jna to your libs if its missing.
I had the same problem and added this as dependency (i use a launcher but you can use a plugin to download):

`net.java.dev.jna:jna:5.13.0
net.java.dev.jna:jna-platform:5.13.0`

**Comment by MiniDigger** [comment]
this is just a warning, right? the server starts and runs fine?

**Comment by yinzixie** [comment]
> this is just a warning, right? the server starts and runs fine?

Yes just warning.

**Comment by electronicboy** [comment]
We don't exactly support alpine environments, but, those logs are from oshi, the library mojang uses to get information about the OS

**Comment by MiniDigger** [comment]
> > this is just a warning, right? the server starts and runs fine?
> 
> Yes just warning.

Then it should prolly be raised with oshi instead

**Comment by yinzixie** [comment]
Okay thanks mates. I will close it.

**Comment by dbwiddis** [comment]
OSHI maintainer here. Found this bug introduced in version 6.4.5.   Fixed in 6.4.8.

**Comment by MiniDigger** [comment]
thanks! we don't include oshi ourselves, but we forwarded it to mojang so they can update it at their end
