### ISSUE TITLE
CraftPlayer#canSee() causing extreme MSPT increases / TPS drops

### ISSUE THREAD

**Issue by codeHusky** [PaperSpigot/Paper#9794]
### Timings or Profile link

https://spark.lucko.me/IIftkvHeLc

### Description of issue

The new Entity visibility API is causing significant performance issues since my server's upgrade from 1.19.2 to 1.20.2. We were previously able to handle around 50 online around 20tps most of the time.

Since updating to 1.20.2, we've been unable to achieve this same level of performance or anywhere close. CraftPlayer#canSee() is adding an extreme amount of tick time to the server with our entity and player count that makes the server essentially freeze with 100 players online, running poorly with 50. We haven't touched our plugins outside of updating for compatibility, so there haven't been any major changes in that regard.

### Plugin and Datapack List

```
[15:47:57 INFO]: Server Plugins (56):
[15:47:57 INFO]: Bukkit Plugins:
[15:47:57 INFO]:  - *Analyse, AreaShop, ChangeSlots, ChatItem, Chunky, ChunkyBorder, ClearLag, CMCEvents, CMCLinkManager, CoreProtect
[15:47:57 INFO]:  CrashClaim, CrashPayment, CreativeManager, DecentHolograms, dynmap, DynmapWaystones, Essentials, EssentialsSpawn, FancyWaystones, FastAsyncWorldEdit
[15:47:57 INFO]:  GSit, HatCosmetics, HeadDatabase, HeadHunter, helper, helper-sql, HubParkour, HuskyPatch, HuskyScreen, *HuskyTest
[15:47:57 INFO]:  ImageMaps, InventoryRollbackPlus, InvSeePlusPlus, LiteBans, LitebansAntiMuteBypass, LPC, LuckPerms, Multiverse-Core, Multiverse-NetherPortals, PlaceholderAPI
[15:47:57 INFO]:  PlasmoVoice, PlugManX, ProtocolLib, pv-addon-lavaplayer-lib, QSFindItemAddOn, QuickShop, ServerSigns, spark, SubserverTools, TAB
[15:47:57 INFO]:  UltimateAutoRestart, Vault, ViaVersion, VillagerTradeLimiter, WitherSound, WorldGuard

```

### Server config files

Configs are included in the spark profile - here's a DL to a zip with ours.
[cfg.zip](https://drive.google.com/file/d/18UiimwYTjOcUjzk3MF_wkngMqtXZ3jri/view?usp=sharing)

### Paper version

```
> ver
[15:50:56 INFO]: Checking version, please wait...
[15:50:57 INFO]: This server is running Paper version git-Paper-214 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 02cfaa8)
You are running the latest version
Previous version: git-Paper-212 (MC: 1.20.2)

```

### Other

Additional profile: https://spark.lucko.me/JnmFU5zTpF
Already reached out in #paper-help about this and it seemed best to report this here.
Worth note that simply asking everyone in the server to "stop moving" brought the TPS from 7 to 15.

**Comment by electronicboy** [comment]
I'd be interested in seeing a sample with a shorter interval, on the surface, there looks to be some issues here, the fact that hashmap is deferring to TreeNodes generally screams that the spread induced by hashCode is too small for what is going on, but, I'd wonder if you're using something that hides entities in a manner that might be causing a metric bunch in there?

**Comment by codeHusky** [comment]
@electronicboy here's my timings report as well: https://timings.aikar.co/dev/?id=213eede3faf64bc095977d70634f748c
If you've got a plugin I can load in to take some stats on the usage of the API lmk, would love to be able to provide a bit of info. I don't think we do have anything plugin-wise like that though, the closest would be CrashClaim but that uses packet-based invisible magma cubes.

**Comment by codeHusky** [comment]
Captured a VisualVM CPU profile since you wanted smthn with a shorter interval, this should be useful:
[snapshot-subserver-10-4-2023-1696450310430.nps](https://drive.google.com/file/d/1vPFQiK_8l5_HkfTjJt-hlkRHunxfaylv/view?usp=sharing)

**Comment by codeHusky** [comment]
May be worth note but we're using Essentials Vanish - that's probably(?) triggering parts of this?

**Comment by codeHusky** [comment]
During low TPS I took a dump of everything affecting that map, here's what I got: https://pastebin.com/GnssCRVK
Code used to create this: https://pastebin.com/x5Cexwp1
Profile from shortly after: https://spark.lucko.me/Inbl9KdI0T

It doesn't look like there's a massive amount of entries in the hashmap at all, seems to be more so that the methods being called an incredible amount of times per tick while players are active on the server.

**Comment by codeHusky** [comment]
I've replaced our Paper with a patched version of paper that replaces CraftPlayer#canSee with a simple `return true;`
Here are the timings from that experiment: https://spark.lucko.me/cxfJhAlvdn
It effectively accomplishes the same thing for us. Having these canSee checks execute on the main thread with the amount of calls they receive seems a bit non-ideal - even the `getHandle` call adds ms to the tick per entity type its iterating over. Not quite sure what the ideal solution would be since the full scope of what this is used for is unknown to me, but thought I'd share.

**Comment by codeHusky** [comment]
Another timings report, still an usual amount of tick time in PlayerConnectionUtils compared to 1.19.2 even with canSee patched out. Might be a larger issue?
https://spark.lucko.me/GgYLX0lnOb

**Comment by codeHusky** [comment]
@electronicboy I may have tracked down a large source of the lag, a lot of it being related to `ChunkMap$TrackedEntity#updatePlayer(Player player)` - as player count goes up, this was using drastically more and more ms to execute than it used to on 1.19. Doing some basic comparison work I found that this particular optimization was removed:

```java
// Paper start - remove allocation of Vec3D here
// Vec3 vec3d = player.position().subtract(this.entity.position());
double vec3d_dx = player.getX() - this.entity.getX();
double vec3d_dz = player.getZ() - this.entity.getZ();
// Paper end - remove allocation of Vec3D here
double d0 = (double) Math.min(this.getEffectiveRange(), io.papermc.paper.chunk.system.ChunkSystem.getSendViewDistance(player) * 16); // Paper - per player view distance
double d1 = vec3d_dx * vec3d_dx + vec3d_dz * vec3d_dz; // Paper
double d2 = d0 * d0;
boolean flag = d1 <= d2 && this.entity.broadcastToPlayer(player);
```
for the sake of avoiding repeated quick reboots to try and optimize multiple things, I also removed the `trackingRangeY` code as well as `&& ChunkMap.this.isChunkTracked(player, this.entity.chunkPosition().x, this.entity.chunkPosition().z);` since that seemed to be another pain point every single time the server would try and run updatePlayer. it seems like that check was introduced for trackingRangeY and runs for no reason when it's not enabled(?) which just hurts performance really bad

with these changes, you can see IAsyncTaskHandler is taking far less sync tick time than it was before (it was matching or more than tickChildren even with like 30-50 players online) vs the other profiles I've sent. 
https://spark.lucko.me/93lg1u8LqP

should be a good starting point to try and optimize things with a proper patch for anyone who wants to pursue that. I'm just trying to make my server run smoothly atm and have a few other things that need taking care of soon - if nobody else gets to it I'll try and tackle it a little more surgically than just deleting stuff that's killing the TPS that we aren't using on my server or don't seem to need

**Comment by Draghonir** [comment]
nice @codeHusky

**Comment by MrPowerGamerBR** [comment]
Can confirm the same issue on my server: https://spark.lucko.me/GouO2WV6Ux

**Comment by electronicboy** [comment]
afaik, the patch wasn't applicable because of upstreams changes here, my understanding is that restoring that patch *will* help as it should reduce the number of entities it tries, but, upstreams changes to the visability API are the real performance kicker here

**Comment by Brokkonaut** [comment]
For everyone who is able to build the server as long as this is not fixed:
In
src/main/java/net/minecraft/server/level/ChunkMap.java
replace
if (!player.getBukkitEntity().canSee(this.entity.getBukkitEntity())) {
with
if (flag && !player.getBukkitEntity().canSee(this.entity.getBukkitEntity())) {
That improved our servers performance a lot

And it might be worth to add it as a paper patch.

**Comment by electronicboy** [comment]
I've pushed that one in your name, issue here is that the lack of that above patch means that we're apparently considering *all* entities for tracking, I did have a quick 2 second hit of applying it, but, it failed tragically, so going to need more effort than I can muster right now

**Comment by MachineBreaker** [comment]
> I've pushed that one in your name, issue here is that the lack of that above patch means that we're apparently considering _all_ entities for tracking, I did have a quick 2 second hit of applying it, but, it failed tragically, so going to need more effort than I can muster right now

That patch was actually done in Gale discord by me. There are a lot of areas where canSee can be skipped with more faster checks. I'll try to open a PR for that if i get some free time

**Comment by codeHusky** [comment]
> For everyone who is able to build the server as long as this is not fixed: In src/main/java/net/minecraft/server/level/ChunkMap.java replace if (!player.getBukkitEntity().canSee(this.entity.getBukkitEntity())) { with if (flag && !player.getBukkitEntity().canSee(this.entity.getBukkitEntity())) { That improved our servers performance a lot
> 
> And it might be worth to add it as a paper patch.

This patch achieves similar MSPT performance improvements to my fork that just guts canSee entirely (at least when combined with skipping the isTrackedChunk check), so that's definitely a good start. Excited to see what MachineBreaker's canSee improvements will look like though.

**Comment by electronicboy** [comment]
See, the headache here is that it's in a stupidly hot area, and so reducing any calls will help
saving calls to that is good where possible, sadly not able to dig in too much because 0.6 eyes, but, there also looks to be a pretty severe binning issue here that we might want to see if we can look into

assuming by isTrackedChunk, you mean isChunkTracked, mojang got rid of that in .2, I did look into upgrading leafs patch but ended up with 0 entities, generally looks like a bunch of stuff was removed around so really need to have a bit of a look into what all changed

**Comment by codeHusky** [comment]
Yes I meant isChunkTracked. I'd removed it at one point to try and chase down as high TPS as possible at higher playercounts but it might just be a bit of a placebo change, haven't done much analysis on it. Server seems to be running quite well though with just the simple patch currently on master.

**Comment by StKillReal** [comment]
So, any news about the issue? Almost a month we have terrible perfomance without any ability to have more than 40 players online on 1.20.2 without drops to 10 tps

**Comment by electronicboy** [comment]
Still generally waiting on leaf, I tried porting the patch in my death but but it failed, needs deeper attention

**Comment by codeHusky** [comment]
@StKillReal are you on the latest Paper? One of the recent patches significantly improved performance for me and brought it up almost exactly to what I was able to get with my own changes. Can handle 50+ people on with a solid 20 TPS, albeit on my fairly well optimized server

**Comment by StKillReal** [comment]
@codeHusky yep, I've updated build. I suppose u mean build 242 about "Don't check if we can see non-visible entities". Now it looks better, but still works really worse than 1.20.1. Even now with 20 players online I have  +-40 MSPT

**Comment by electronicboy** [comment]
Yea, some blobs of that are applicable as-is, I just need to look into why I wasn't getting any entities at all after I'd tried to update the patch entirely

**Comment by codeHusky** [comment]
With the patches on my paper fork I'm getting pretty solid TPS with ~70 players
https://spark.lucko.me/r4qVDV3H0r
Here's my current patches: [HuskyPaper-TPSFixes Patches](https://github.com/codeHusky/HuskyPaper-TPSFixes/tree/c9d019838d18225bfb8c7f29311a6db0600e2476/patches/server)

**Comment by StKillReal** [comment]
So, month has passed, still waiting🤔

**Comment by electronicboy** [comment]
There is a linked pull request which restores the patch for this, feel free
to test it; I'm inclined to pull it soon however, I don't wanna hit the
merge button and not be around for any issues as in currently having health
issues
