### ISSUE TITLE
Player#getClientBrandName always returns null in 1.20.2

### ISSUE THREAD

**Issue by Rickyboy320** [PaperSpigot/Paper#9803]
### Expected behavior

In previous versions, this returned the client brand properly

### Observed/Actual behavior

Always returns null, regardless of how long I wait.
Debugger shows that the custom `BrandPayload` packet is received, and is assigned to this.clientBrandName in the `ServerCommonPacketListenerImpl`, but for some reason does not propagate to the player method.

### Steps/models to reproduce

1) Have a way to read out the brand of the player, for example using
```java
@EventHandler
    public void interact(PlayerInteractEvent event)
    {
        System.out.println(event.getPlayer().getClientBrandName());
    }
```

2) Log in

3) Trigger the readout, notice that it is always `null`.

### Plugin and Datapack List

None, except for the debug plugin as above.

### Paper version

This server is running Paper version git-Paper-217 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: cfe311d)
You are running the latest version
Previous version: git-Paper-207 (MC: 1.20.2)

**Comment by electronicboy** [comment]
Known issue, we basically need to save where the brand is stored, it's been on my todo list, but, yea...
