### ISSUE TITLE
Get Hidden Weaker Potion Effects

### ISSUE THREAD

**Issue by riazufila** [PaperSpigot/Paper#9811]
### Is your feature request related to a problem?

Yes. When a stronger potion effect overrides the weaker potion effect, the weaker potion effect remains, but is hidden. It returns after the stronger potion effect expires, if the weaker potion effect has a higher duration than the stronger potion effect.

However, from the API, using `LivingEntity#getActivePotionEffects()` doesn't return the hidden potion effects. There doesn't seem to be any way to get these hidden effects.

### Describe the solution you'd like.

Create a new overloading method for `LivingEntity#getActivePotionEffects()` to retrieve hidden potion effects as well. Maybe a boolean for the additional parameter to retrieve said hidden potion effects.

Or, a whole new method is also fine, whichever is better.

### Describe alternatives you've considered.

I've tried to add a Potion Effects tracker into my plugin, however, that seems like a whole load of extra codes when the feature is already in vanilla Minecraft.

**Comment by CodeByCam** [comment]
Cheers for the feature request! I feel like this valid given the language of the method on the [javadocs](https://jd.papermc.io/paper/1.20/org/bukkit/entity/LivingEntity.html#getActivePotionEffects()):
> Returns all currently active [PotionEffect](https://jd.papermc.io/paper/1.20/org/bukkit/potion/PotionEffect.html)s on the living entity.

Although potion effects don't stack, being able to list them all, including ones of a lower level of the same type, seems handy.
