### ISSUE TITLE
stop achievements in creative mode

### ISSUE THREAD

**Issue by seema84** [PaperSpigot/Paper#9812]
### Is your feature request related to a problem?

This is probably the only sensible way to prevent achievements from becoming meaningless on servers that use an additional creative world (besides the survival world) without bungee/waterfall.

It would also be good if you could deactivate achievements in creative mode (not only on special creative worlds, also on survival worlds in creative mode).

### Describe the solution you'd like.

Make PlayerAdvancementDoneEvent cancellable or another way to prevent achievements on one or more worlds.

### Describe alternatives you've considered.

I have tried to address it at spigot, but it has not been implemented for 6 years.
https://hub.spigotmc.org/jira/browse/SPIGOT-3556

**Comment by lynxplay** [comment]
[PlayerAdvancementCriterionGrantEvent ](https://jd.papermc.io/paper/1.20/com/destroystokyo/paper/event/player/PlayerAdvancementCriterionGrantEvent.html) exists already and should do exactly what you are after.
