### ISSUE TITLE
WorldGuard region bypass does not function properly with paper-222

### ISSUE THREAD

**Issue by MassaHex** [PaperSpigot/Paper#9813]
### Expected behavior

Ability to break blocks.
Same goes for /rg toggle-bypass

### Observed/Actual behavior

Hey You can't break that here.
java.lang.IllegalStateException: zip file closed after running /rg toggle-bypass

### Steps/models to reproduce

Run /rg toggle-bypass in worldguard or try to break blocks in a region.

### Plugin and Datapack List

![Screenshot_20231009_085441_Minecraft](https://github.com/PaperMC/Paper/assets/105466578/1b45792e-9cf8-4dee-8d3f-7e613198cd42)

### Paper version

Paper-222 1.20.2

### Other

I'm not sure if this is an issue on my end, an issue with paper, or an issue with worldguard that needs to be fixed. But I reported it here anyway hoping for better help.

**Comment by MassaHex** [comment]
But which one?

**Comment by electronicboy** [comment]
I can't tell you, advice would be to fix/remove plugins which failed to enable

**Comment by Owen1212055** [comment]
Please run /paper dumpplugins and paste it here
