### ISSUE TITLE
return value of "org.bukkit.event.world.LootGenerateEvent.getLootTable()" is null

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#9817]
### Expected behavior

loot table should not be null

### Observed/Actual behavior

java.lang.NullPointerException: Cannot invoke "org.bukkit.loot.LootTable.getKey()" because the return value of "org.bukkit.event.world.LootGenerateEvent.getLootTable()" is null

it is marked as not null

    /**
     * Get the loot table used to generate loot.
     *
     * @return the loot table
     */
    @NotNull
    public LootTable getLootTable() {
        return lootTable;
    }

### Steps/models to reproduce

Listen for loot table event

@EventHandler
    public void onLootGenerate(LootGenerateEvent event) {
        if (event.getInventoryHolder() instanceof Chest
                && event.getEntity() instanceof Player) {
            ...
            if (lootTables.containsKey(event.getLootTable().getKey().toString())) { <---- problematic line
             ...
            }
        }
    }
    
    loot table should never be null, either fix null loot table or mark it as nullable in API

### Plugin and Datapack List

Custom plugin with just this listener

### Paper version

This server is running Paper version git-Paper-"a2ba452" (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: a2ba452)
You are running the latest version
Previous version: git-Paper-"29d1c7b" (MC: 1.20.1)

**Comment by Machine-Maker** [comment]
Confirmed, I see the issue. will fix now
