### ISSUE TITLE
PlayerProfile#setId breaks after update to 1.20.2

### ISSUE THREAD

**Issue by kyngs** [PaperSpigot/Paper#9819]
### Expected behavior

I would expect the PlayerProfile#setId method to set the UUID of the PlayerProfile.

### Observed/Actual behavior

The UUID does not change.

### Steps/models to reproduce

1) Create a plugin and hook into the PlayerPreLoginEvent
2) Attempt to modify the UUID to some arbitrary value
3) Observe that the UUID does not change

Example snippet:
```java
@EventHandler(priority = EventPriority.LOWEST)
public void onPreLogin(AsyncPlayerPreLoginEvent event) {
    var existing = event.getPlayerProfile();
    var uuid = UUID.randomUUID();

    existing.setId(uuid);

    System.out.println(uuid);
    System.out.println(event.getUniqueId());
}
```

Logically, both lines should print the same thing. However, they do not.

### Plugin and Datapack List

None, only my test plugin.

### Paper version

```
[19:30:06 INFO]: Checking version, please wait...
[19:30:06 INFO]: This server is running Paper version git-Paper-226 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: a2ba452)
You are running the latest version
Previous version: git-Paper-100 (MC: 1.20.1)
```

### Other

*I do realize that the method is marked for removal, however unless it gets removed I expect it to work and not silently fail*

Perhaps this was a typo during the commit: https://github.com/PaperMC/Paper/commit/431e6418ab33ff0decd16f82238e9d50daf328f5

From CraftPlayerProfile.java after the commit:
```java
    @Override
    @Deprecated(forRemoval = true)
    public UUID setId(@Nullable UUID uuid) {
        final GameProfile previousProfile = this.profile;
        final UUID previousId = this.getId();
        this.profile = new GameProfile(previousProfile.getId(), previousProfile.getName());
        copyProfileProperties(previousProfile, this.profile);
        return previousId;
    }
```

From CraftPlayerProfile.java on 1.20.1:
```java
    @Override
    @Deprecated(forRemoval = true)
    public UUID setId(@Nullable UUID uuid) {
        GameProfile prev = this.profile;
        this.profile = new GameProfile(uuid, prev.getName());
        copyProfileProperties(prev, this.profile);
        return prev.getId();
    }
```

If this was intentional, please remove the method from the API.

**Comment by Machine-Maker** [comment]
> Perhaps this was a typo during the commit

Yeah, this seems correct.
