### ISSUE TITLE
Error deserializing the honey level data within a beehive or bee nest

### ISSUE THREAD

**Issue by Rairun** [PaperSpigot/Paper#9823]
### Stack trace

11.10 16:31:55 [Server] ERROR [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaItem$SerializableMeta for deserialization
11.10 16:31:55 [Server] INFO java.lang.IllegalArgumentException: BlockStateTag({
11.10 16:31:55 [Server] INFO honey_level: "5"
11.10 16:31:55 [Server] INFO }) is not a valid interface java.util.Map
11.10 16:31:55 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaItem$SerializableMeta.getObject(CraftMetaItem.java:241) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaItem.<init>(CraftMetaItem.java:547) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaBlockState.<init>(CraftMetaBlockState.java:164) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
11.10 16:31:55 [Server] INFO at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
11.10 16:31:55 [Server] INFO at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
11.10 16:31:55 [Server] INFO at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
11.10 16:31:55 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
11.10 16:31:55 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:205) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
11.10 16:31:55 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
11.10 16:31:55 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
11.10 16:31:55 [Server] INFO at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
11.10 16:31:55 [Server] INFO at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
11.10 16:31:55 [Server] INFO at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
11.10 16:31:55 [Server] INFO at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:49) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
11.10 16:31:55 [Server] INFO at java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1784) ~[?:?]
11.10 16:31:55 [Server] INFO at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733) ~[?:?]
11.10 16:31:55 [Server] INFO at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2157) ~[?:?]
11.10 16:31:55 [Server] INFO at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1721) ~[?:?]
11.10 16:31:55 [Server] INFO at java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2606) ~[?:?]
11.10 16:31:55 [Server] INFO at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2457) ~[?:?]
11.10 16:31:55 [Server] INFO at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2257) ~[?:?]
11.10 16:31:55 [Server] INFO at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733) ~[?:?]
11.10 16:31:55 [Server] INFO at java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2606) ~[?:?]
11.10 16:31:55 [Server] INFO at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2457) ~[?:?]
11.10 16:31:55 [Server] INFO at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2257) ~[?:?]
11.10 16:31:55 [Server] INFO at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733) ~[?:?]
11.10 16:31:55 [Server] INFO at java.io.ObjectInputStream.readObject(ObjectInputStream.java:509) ~[?:?]
11.10 16:31:55 [Server] INFO at java.io.ObjectInputStream.readObject(ObjectInputStream.java:467) ~[?:?]
11.10 16:31:55 [Server] INFO at me.imbuzz.dev.playerprofiles.utils.BukkitSerialization.itemStackArrayFromBase64(BukkitSerialization.java:54) ~[PlayerProfiles-1.1-SNAPSHOT.jar:?]
11.10 16:31:55 [Server] INFO at me.imbuzz.dev.playerprofiles.loaders.impl.FileLoader.loadProfiles(FileLoader.java:38) ~[PlayerProfiles-1.1-SNAPSHOT.jar:?]
11.10 16:31:55 [Server] INFO at me.imbuzz.dev.playerprofiles.listeners.EventListener.login(EventListener.java:19) ~[PlayerProfiles-1.1-SNAPSHOT.jar:?]
11.10 16:31:55 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor8.execute(Unknown Source) ~[?:?]
11.10 16:31:55 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
11.10 16:31:55 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
11.10 16:31:55 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
11.10 16:31:55 [Server] INFO at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:325) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:130) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:18) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
11.10 16:31:55 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
11.10 16:31:55 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
11.10 16:31:55 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
11.10 16:31:55 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
11.10 16:31:55 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
11.10 16:31:55 [Server] WARN java.io.IOException: Failed to deserialize object
11.10 16:31:55 [Server] WARN at org.bukkit.util.io.BukkitObjectInputStream.newIOException(BukkitObjectInputStream.java:59)
11.10 16:31:55 [Server] WARN at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:51)
11.10 16:31:55 [Server] WARN at java.base/java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1784)
11.10 16:31:55 [Server] WARN at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
11.10 16:31:55 [Server] WARN at java.base/java.io.ObjectInputStream.readArray(ObjectInputStream.java:2157)
11.10 16:31:55 [Server] WARN at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1721)
11.10 16:31:55 [Server] WARN at java.base/java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2606)
11.10 16:31:55 [Server] WARN at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2457)
11.10 16:31:55 [Server] WARN at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2257)
11.10 16:31:55 [Server] WARN at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
11.10 16:31:55 [Server] WARN at java.base/java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2606)
11.10 16:31:55 [Server] WARN at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2457)
11.10 16:31:55 [Server] WARN at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2257)
11.10 16:31:55 [Server] WARN at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
11.10 16:31:55 [Server] WARN at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
11.10 16:31:55 [Server] WARN at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
11.10 16:31:55 [Server] WARN at PlayerProfiles-1.1-SNAPSHOT.jar//me.imbuzz.dev.playerprofiles.utils.BukkitSerialization.itemStackArrayFromBase64(BukkitSerialization.java:54)
11.10 16:31:55 [Server] WARN at PlayerProfiles-1.1-SNAPSHOT.jar//me.imbuzz.dev.playerprofiles.loaders.impl.FileLoader.loadProfiles(FileLoader.java:38)
11.10 16:31:55 [Server] WARN at PlayerProfiles-1.1-SNAPSHOT.jar//me.imbuzz.dev.playerprofiles.listeners.EventListener.login(EventListener.java:19)
11.10 16:31:55 [Server] WARN at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor8.execute(Unknown Source)
11.10 16:31:55 [Server] WARN at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
11.10 16:31:55 [Server] WARN at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
11.10 16:31:55 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
11.10 16:31:55 [Server] WARN at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
11.10 16:31:55 [Server] WARN at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
11.10 16:31:55 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
11.10 16:31:55 [Server] WARN at net.minecraft.server.players.PlayerList.a(PlayerList.java:325)
11.10 16:31:55 [Server] WARN at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.a(ServerConfigurationPacketListenerImpl.java:130)
11.10 16:31:55 [Server] WARN at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:18)
11.10 16:31:55 [Server] WARN at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9)
11.10 16:31:55 [Server] WARN at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:53)
11.10 16:31:55 [Server] WARN at net.minecraft.server.TickTask.run(TickTask.java:18)
11.10 16:31:55 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
11.10 16:31:55 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
11.10 16:31:55 [Server] WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)
11.10 16:31:55 [Server] WARN at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
11.10 16:31:55 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
11.10 16:31:55 [Server] WARN at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)
11.10 16:31:55 [Server] WARN at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)
11.10 16:31:55 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
11.10 16:31:55 [Server] WARN at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1272)
11.10 16:31:55 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1160)
11.10 16:31:55 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
11.10 16:31:55 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
11.10 16:31:55 [Server] WARN Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(java.util.Map)" is null
11.10 16:31:55 [Server] WARN at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:49)
11.10 16:31:55 [Server] WARN ... 42 more
11.10 16:31:55 [Server] ERROR Could not pass event PlayerJoinEvent to PlayerProfiles v1.1-SNAPSHOT
11.10 16:31:55 [Server] INFO java.lang.NullPointerException: Cannot read the array length because "items" is null
11.10 16:31:55 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftInventory.setContents(CraftInventory.java:86) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at me.imbuzz.dev.playerprofiles.objects.profile.DataProfile.updatePlayer(DataProfile.java:84) ~[PlayerProfiles-1.1-SNAPSHOT.jar:?]
11.10 16:31:55 [Server] INFO at me.imbuzz.dev.playerprofiles.listeners.EventListener.login(EventListener.java:21) ~[PlayerProfiles-1.1-SNAPSHOT.jar:?]
11.10 16:31:55 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor8.execute(Unknown Source) ~[?:?]
11.10 16:31:55 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
11.10 16:31:55 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
11.10 16:31:55 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
11.10 16:31:55 [Server] INFO at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:325) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:130) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:18) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
11.10 16:31:55 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
11.10 16:31:55 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
11.10 16:31:55 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
11.10 16:31:55 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
11.10 16:31:55 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-217]
11.10 16:31:55 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
11.10 16:31:55 [Server] INFO Rairun joined the game

### Plugin and Datapack List

- BlueMap, Chunky, ChunkyBorder, eSaveItem, HarvestXP, PlaceholderAPI, *PlayerProfiles, *SmartInvs

### Actions to reproduce (if known)

I use a plugin called ✨Per-Player Profiles (Create Multiple Profiles) ✨ 1.1 (it allows you to have several 'characters' in the same server with separate inventories, ender chests, health, levels, spawn points etc). The way it works with inventories is that it serializes your inventory and saves it to a yml file, and when you login or switch profiles, it deserializes the data and overwrites your player data with that.

I've used this plugin for years now without any issues, but yesterday I found a beehive full with honey and bees in it. I took it with silk touch and logged off. Today, when I logged back in, my inventory was completely empty and the server logs showed the stack trace above.

It looks like there is a problem with the deserisaliation of the data within a beehive, specifically the honey level.

Giving yourself this item (a beehive with bees, but no honey level) does NOT cause any problems:

/give @s beehive{BlockEntityTag:{Bees:[{EntityData:{id:"minecraft:bee"}},{EntityData:{id:"minecraft:bee"}},{EntityData:{id:"minecraft:bee"}}]}}

Giving yourself this item (a beehive with bees, and a honey level of 5) DOES cause the deserialization issue:

/give @s beehive{BlockStateTag:{honey_level:"5"},BlockEntityTag:{Bees:[{EntityData:{id:"minecraft:bee"}},{EntityData:{id:"minecraft:bee"}},{EntityData:{id:"minecraft:bee"}}]}}

I've also tested this with bee nests as well as hives, and the same issue happens.

### Paper version

This server is running Paper version git-Paper-233 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 2f5bb7e)

### Other

I know the stack trace I provided says I'm running git-Paper-217, but I've now updated to the latest (git-Paper-233) and the issue is still there.

**Comment by lynxplay** [comment]
Known, to be resolved by the next upstream update.

**Comment by Brokkonaut** [comment]
[04:59:54] [Server thread/ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaItem$SerializableMeta for deserialization
java.lang.IllegalArgumentException: BlockStateTag({
    honey_level: "0"
}) is not a valid interface java.util.Map
	at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaItem$SerializableMeta.getObject(CraftMetaItem.java:241) ~[paper-1.20.2.jar:git-Paper-"4b0bc74"]
	at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaItem.<init>(CraftMetaItem.java:547) ~[paper-1.20.2.jar:git-Paper-"4b0bc74"]
	at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaBlockState.<init>(CraftMetaBlockState.java:164) ~[paper-1.20.2.jar:git-Paper-"4b0bc74"]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:205) ~[paper-1.20.2.jar:git-Paper-"4b0bc74"]
	at jdk.internal.reflect.GeneratedMethodAccessor28.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:58) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:576) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:210) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:552) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:597) ~[snakeyaml-2.2.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:49) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247) ~[snakeyaml-2.2.jar:?]
	at org.bukkit.configuration.file.YamlConstructor.construct(YamlConstructor.java:37) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:163) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:120) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at com.Acrobot.ChestShop.Metadata.ItemDatabase.decodeItemStack(ItemDatabase.java:183) ~[ChestShop.jar:?]
	at com.Acrobot.ChestShop.Metadata.ItemDatabase.upgrade(ItemDatabase.java:127) ~[ChestShop.jar:?]
	at com.Acrobot.ChestShop.ChestShop.handleMigrations(ChestShop.java:188) ~[ChestShop.jar:?]
	at com.Acrobot.ChestShop.ChestShop.onEnable(ChestShop.java:116) ~[ChestShop.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-"4b0bc74"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-"4b0bc74"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-"4b0bc74"]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-"4b0bc74"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-"4b0bc74"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-"4b0bc74"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-"4b0bc74"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-"4b0bc74"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-"4b0bc74"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
