### ISSUE TITLE
Tab completion breaks randomly after a while.

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#9832]
### Expected behavior

Tabbing commands should work no problem.

### Observed/Actual behavior

When the player joins, they can use command tab completion just fine, but after a few minutes it seems to break randomly

It seems from packet logging, the client IS being sent tab completion packets, but refusing to show them:

S2C
TAB_COMPLETE 
[a(int):0],
[b(com.mojang.brigadier.suggestion.Suggestions):Suggestions{range=StringRange{start=7, end=7}, suggestions=[Suggestion{range=StringRange{start=7, end=7}, text='test1', tooltip='null'}, Suggestion{range=StringRange{start=7, end=7}, text='test2', tooltip='null'}]}]

Also, the transaction id sent by the vanilla 1.20.2 client always seems to be zero, 

C2S
TAB_COMPLETE [a(int):0],[b(java.lang.String):/test te],

which makes no sense. Yet tab completion does function for the first few minutes of being online with this zero id.

### Steps/models to reproduce

public class Test implements TabExecutor {

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        return true;
    }

    @Override
    public List<String> onTabComplete(CommandSender sender, Command arg1, String arg2, String[] args) {
        return List.of("test1","test2");
    }
}

### Paper version

This server is running Paper version git-Paper-"f613437" (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: f613437)
You are running the latest version
Previous version: git-Paper-"a2ba452" (MC: 1.20.2)

**Comment by electronicboy** [comment]
the id is reset when it gets a matching response, race condition? er 🤷

**Comment by lynxplay** [comment]
I mean, potentially ? Not being able to replicate this on a plain server does point in the direction of a plugin.
Can you please try to narrow down which plugin might be causing this, e.g. via [binary search](https://docs.papermc.io/paper/basic-troubleshooting#binary-search) ?

Replication steps would be a requirement for us to keep this issue open 😅

**Comment by electronicboy** [comment]
Just listening in the event pipeline will have 0 implications, if those break it it's going to be down to some interactions on the packets or whatever, but, not our avenue
