### ISSUE TITLE
Erroneous Characters Inserted in motd for Non-Standard Characters

### ISSUE THREAD

**Issue by tomkimberlin** [PaperSpigot/Paper#9839]
### Expected behavior

I expect Paper not to insert any erroneous characters into the motd field of my server.properties file when using non-standard characters and starting the server.

### Observed/Actual behavior

When the motd in the server.properties file contains non-standard characters, Paper inserts erroneous characters before or after them. As a side effect, each time the server is restarted, additional erroneous characters are inserted, which can eventually cause the server.properties file to grow significantly in size.

### Steps/models to reproduce

1. Start a server with non-standard characters (e.g., "§", "Ã", etc.) in the motd of the server.properties file.
2. Observe that erroneous characters are inserted before or after these symbols upon server startup.
3. Optionally, restart the server to observe that additional erroneous characters are inserted, leading to a growth in the size of the server.properties file.

### Plugin and Datapack List

None

### Paper version

git-Paper-238

**Comment by CodeByCam** [comment]
Can reproduce.
Started with `motd=§aCamms §bTest §cWorld`, after restarting I got `motd=Â§aCamms Â§bTest Â§cWorld`. Tried again with `motd=ÃMy MOTD` and received `motd=ÃMy MOTD`.

**Comment by lynxplay** [comment]
I mean, it is writing the properties file using UTF-8.
I presume whatever you use to edit the file saves it using something *not* UTF-8 which at least explains the initial "insertion" characters.

I was not able to have the server repeatedly insert these characters, are you mutating the server.properties file between server restarts somehow ?

**Comment by MiniDigger** [comment]
the encoding of the file was changed to utf8 in 1.20, maybe OP just had an old file.

**Comment by electronicboy** [comment]
This is peak encoding issues, using any panel/server management software? ik some loves to mess with the server.properties file which could be inducing the repeating issues, as otherwise, it's already been "converted" (read: mangled) from ascii/microsofts weird encoding over to utf8, and shouldn't go through further manglement

**Comment by tomkimberlin** [comment]
> I mean, it is writing the properties file using UTF-8. I presume whatever you use to edit the file saves it using something _not_ UTF-8 which at least explains the initial "insertion" characters.
> 
> I was not able to have the server repeatedly insert these characters, are you mutating the server.properties file between server restarts somehow ?

My server.properties was already using UTF-8 when I noticed the issue and when I reproduced the issue.

> This is peak encoding issues, using any panel/server management software? ik some loves to mess with the server.properties file which could be inducing the repeating issues, as otherwise, it's already been "converted" (read: mangled) from ascii/microsofts weird encoding over to utf8, and shouldn't go through further manglement

I am not using any panel/server management software unless you consider Docker to be so.

**Comment by lynxplay** [comment]
[itzg/minecraft-server](https://hub.docker.com/r/itzg/minecraft-server) does read/write the server.properties files.

https://github.com/itzg/docker-minecraft-server/issues/2433 tracks this. This is not a paper issue, I am closing this.
