### ISSUE TITLE
The paper jar is 2mb smaller than before

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#9844]
### Is your feature request related to a problem?

since https://github.com/PaperMC/paper/commit/e57af7d01e509c747520cc1037169029256289bf
the paper jar has shrunk by 2mb, just letting you know, incase some shaded libraries may have accidentally been excluded.

### Describe the solution you'd like.

N/A

### Describe alternatives you've considered.

N/A

**Comment by LemonCaramel** [comment]
some unused netty dependencies in the paper have been removed.

**Comment by NoahvdAa** [comment]
As mentioned above, some unused dependencies [were removed](https://github.com/PaperMC/Paper/commit/e57af7d01e509c747520cc1037169029256289bf). Thanks for the concern though :)
