### ISSUE TITLE
Problematic frame - Need help

### ISSUE THREAD

**Issue by 7wOv6ySCjo** [PaperSpigot/Paper#9845]
### Stack trace

hs_err_pid78872.log
https://pastebin.com/raw/DbXvgCeD

Other hs_error_pid files
```
# Problematic frame:
# J 81333 c2 net.minecraft.world.entity.EntityLiving.h(Lnet/minecraft/world/phys/Vec3D;)V (1286 bytes) @ 0x00007f92d5d4a499 [0x00007f92d5d49d80+0x0000000000000719]

# Problematic frame:
# J 68260 c2 net.minecraft.server.level.ChunkProviderServer.a(Ljava/util/function/BooleanSupplier;Z)V (193 bytes) @ 0x00007fc13f939e38 [0x00007fc13f939e00+0x0000000000000038]

# Problematic frame:
# V  [libjvm.so+0x7034b0]  oopDesc::size_given_klass(Klass*)+0x0
```

### Plugin and Datapack List

Not necessary, happens with different Minecraft servers including proxy velocity.

### Paper version

> version
[20:59:36.500 INFO]: Checking version, please wait...
[20:59:37.130 INFO]: This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
You are running the latest version

### Other

Clarification: I fully understand that this is not a paper bug, I am posting this issue so that I can share it on Paper's discord and get help on what might be causing these problems.

They probably suggest it's a hardware problem.
Our host (ReliableSites) stopped the dedicated server for about 12 hours to run various tests on the hardware. The tests showed, according to the host, that the machine and its components are fine. There were no errors and everything was OK.

We moved on to a second instance: we reinstalled the operating system. 
It was a clean install of debian: debian-12.2.0-amd64-netinst.iso
The fresh install was well done because we read the full installation manual on debian.org to install the operating system correctly. 

The Java installation was done exactly according to this tutorial:
https://adoptium.net/es/installation/linux/#_deb_installation_on_debian_or_ubuntu

Despite all these solutions applied today our main server crashed 3 times! Not only it happens with our main server, it happened also with another server where only 5 people are logged in and it happened once with Velocity Proxy. We are totally lost as to what could cause this error and what could be the final solution. The host doesn't want us to replace the faulty machine.

**Comment by electronicboy** [comment]
Segmentation faults are pretty much a "we tried to access a memory address that we don't own", this is generally caused by software bugs (which would be inside of native code, i.e. in this instance, the JVM), or hardware faults.

We can't really aid with this stuff on the issue tracker, the fact that it happened with more than one pice of software would generally suggest a wider issue, all I could advise is to run your own memory tests or something, not really our avenue
