### ISSUE TITLE
World Archive Mode

### ISSUE THREAD

**Issue by ChickenSaysBak** [PaperSpigot/Paper#9850]
### Is your feature request related to a problem?

There are no straightforward options for admins that want to freeze a world in an unchanging state. Specifically, to prevent world files from being written to. The best we can do is disable auto-save (in conjunction with Bukkit#unloadWorld(world, false) on disable) which is problematic because all chunk data is retained until a save which eats up RAM until the server inevitably crashes.

Side note: ChunkUnloadEvent#setSaveChunk(false) doesn't do anything.

### Describe the solution you'd like.

It would be nice to have a boolean setting in paper-world.yml maybe called "archive" that prevents all file writing to that world.

### Describe alternatives you've considered.

Alternatively, it could be an option to immediately forget chunk data when chunks unload instead of retaining it indefinitely. This combined with disabling auto-save would achieve the desired result.

### Other

This would be beneficial for minigame maps that need to reset after the world is unloaded. It would also benefit those that want to allow players to tour a world without altering its original state in any way.

**Comment by electronicboy** [comment]
We've been asked this a handful of times over the years, and it's just that theres never been enough of a demand for us to deal with the effort involved in such a change, especially with mojangs lack of decoupling of level state meaning that we cannot exactly assure where data comes from without wider modification, it's just a whole bunch of diff & engineering effort for such a niche use-case

**Comment by ChickenSaysBak** [comment]
What about restoring the functionality of ChunkUnloadEvent#setSaveChunk(false), or is that subject to the same level of effort required? If anything, I feel like it should be marked as deprecated or have a note added about it.

**Comment by electronicboy** [comment]
> ChunkUnloadEvent#setSaveChunk(false),

This method works fine last I knew, but is highly caveated due to upstream not adopting the API to mojangs new chunk system, meaning that chunks are still saved to the disk even if they don't become to a level that bukkit considers "loaded"

**Comment by ChickenSaysBak** [comment]
> In a minigame context, you can call `Bukkit.unloadWorld(world, false)` in order to unload the world _without saving_. We use it in our minigames plugin's `onDisable()`, but you could call it whenever you needed to unload a minigame world.

Yeah I suppose it's suitable for minigames. I'm doing this already, but in my case I have several large worlds that remain loaded for a while, so it just eats up way too much ram. My solution now is to have a duplicate directory of all the worlds and it just runs **rsync** before the server starts to restore the worlds back to original form.

**Comment by Cryptite** [comment]
> > In a minigame context, you can call `Bukkit.unloadWorld(world, false)` in order to unload the world _without saving_. We use it in our minigames plugin's `onDisable()`, but you could call it whenever you needed to unload a minigame world.
> 
> Yeah I suppose it's suitable for minigames. I'm doing this already, but in my case I have several large worlds that remain loaded for a while, so it just eats up way too much ram. My solution now is to have a duplicate directory of all the worlds and it just runs `rsync` before the server starts to restore the worlds back to their original form.

Makes sense. FWIW the way we do it is we have 1 "Source/Parent World" and we copy it to, for example, "Minigame1, 2, 3 etc" and then load that world to create our instance. On server startup (or whenever you want), we just delete all Minigame# worlds that way we can be confident that the original world is never modified (we don't even load it in-game, just copy its files).
