### ISSUE TITLE
Players get stuck in world border

### ISSUE THREAD

**Issue by LaserSlime** [PaperSpigot/Paper#9859]
### Expected behavior

https://youtu.be/H6BfOt7zBjo

### Observed/Actual behavior

https://youtu.be/IMQO19HYNnU

### Steps/models to reproduce

1. Setup a fresh paper server
2. Give yourself op so you can make the worldborder small
3. Run against the world border
4. You will get rubberbanded and get stuck

### Plugin and Datapack List

Server Plugins (0):

### Paper version

This server is running Paper version git-Paper-243 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 3a5c6f8)

**Comment by Lulu13022002** [comment]
Can reproduce, this is related to the other world border collision issue, the collision of the border is completely different on Paper. And this will trigger the following check: https://github.com/PaperMC/Paper/blob/master/patches/server/0728-Optimise-collision-checking-in-player-move-packet-ha.patch#L138 even for legit player

**Comment by karkkijokeri** [comment]
Has happened to me too, It really makes it hard for us to use worldborders in minigames.

**Comment by LaserSlime** [comment]
> Has happened to me too, It really makes it hard for us to use worldborders in minigames.

True, I might try to fix this myself as no one from the core dev team seems to care about this since it's only relevant for minigames.

**Comment by electronicboy** [comment]
The hope was that the patch maintainer would look into this, given that he generally knows this stuff much more closely than the rest of the team, given my lack of eye sight, this is not a high priority for me, but it's false to say we don't care.

**Comment by karkkijokeri** [comment]
> > Has happened to me too, It really makes it hard for us to use worldborders in minigames.
> 
> True, I might try to fix this myself as no one from the core dev team seems to care about this since it's only relevant for minigames.

If you're gonna try to fix it yourself I can give you more info about the bug

**Comment by LaserSlime** [comment]
> > > Has happened to me too, It really makes it hard for us to use worldborders in minigames.
> > 
> > 
> > True, I might try to fix this myself as no one from the core dev team seems to care about this since it's only relevant for minigames.
> 
> If you're gonna try to fix it yourself, I can give you more info about the bug

That info being?

**Comment by Doc94** [comment]
For add a related bug if in survival worlds the portal generate in the border of worldborder the player is stuck in the portal and the worldborder like the video.

**Comment by Quared0** [comment]
Happens to me as well, and it's a big issue for my minigames network. Considering going back to 1.20.1 just because of this one issue.

**Comment by Rubriq007** [comment]
> Alright I've made a "fix" for this that simply ignores players when checking worldborder collision. I'm not sure if I should pr it since it's a rather suboptimal solution considering it allows people with cheats to just ignore the worldborder, but that is possible in vanilla/spigot too so idk. If anyone wants the fix it's here: https://github.com/LaserSlime/Paper/tree/fix/world-border-collision Just make sure that your anticheat prevents people from bypassing the world border if it's important to you.

Hey uhm how do you download this fix exactly?

**Comment by Quared0** [comment]
Issue still occurs when border is changing in size

**Comment by Owen1212055** [comment]
> Issue still occurs when border is changing in size

Could you perhaps show a video?

**Comment by Quared0** [comment]
> > Issue still occurs when border is changing in size
> 
> Could you perhaps show a video?

https://youtu.be/2BwdN58X_KQ

**Comment by CodeByCam** [comment]
Just noting that I can't replicate this in 1.20.4 Vanilla. Works fine: https://streamable.com/6jm35e

**Comment by Spottedleaf** [comment]
Please re-try with https://github.com/PaperMC/Paper/commit/0b952981e6e96157d2cea8322c04c0f69965f2bf

**Comment by Quared0** [comment]
> Please re-try with [0b95298](https://github.com/PaperMC/Paper/commit/0b952981e6e96157d2cea8322c04c0f69965f2bf)

Same issue. I figured out that the issue isn't just when the border is changing, it's also when it is partway through a block, instead of on the edge of one. e.g. on a non-even size.

Video: https://youtu.be/LwjgORKxYEY
