### ISSUE TITLE
The UUID set by the client.

### ISSUE THREAD

**Issue by phlita** [PaperSpigot/Paper#9866]
In the client launcher, set a UUID and add it to the whitelist before connecting to server. When connecting to the server, a new UUID is generated on the server side. Previously saved UUIDs in the whitelist are no longer used.

If Paper stops setting UUIDs and starts using the client's UUID, then the UUIDs whitelisted will work，

**Comment by Leguan16** [comment]
offline mode is not supported.

**Comment by electronicboy** [comment]
UUIDs are calculated by the server during login for offline mode players, as part of mojangs code, so, this is purely WAI
