### ISSUE TITLE
EntityEquipment drop chances docs are wrong or missing API

### ISSUE THREAD

**Issue by Machine-Maker** [PaperSpigot/Paper#9867]
The docs for the EntityEquipment drop chance-related methods all say 
> A drop chance of 1.0F will always drop

which is misleading/false. Setting the chance to 1.0F will make it always drop if a player is responsible for killing the entity. Setting it to 1.00001F (or anything above 1) will make it so that it will drop when killed by anything, not just a player. This either needs to be documented or API added to set guaranteed drops.

**Comment by Crimson-Alex** [comment]
@Machine-Maker how did you discover this? I.e. do you have a specific scenario in which this behavior is reproducable?
