### ISSUE TITLE
Using adventure components in conversion APIs

### ISSUE THREAD

**Issue by lijinhong11** [PaperSpigot/Paper#9877]
### Is your feature request related to a problem?

Prompt#getPromptText(ConversationContext) requires a return type of string, which is too old for me. I only create message handlers that only convert message to net.kyori.adventure.text.Component. I don't want to make another string converter.

### Describe the solution you'd like.

1. Change Prompt#getPromptText(ConversationContext)'s return type to net.kyori.adventure.text.Component.
2. Or create another basic prompt class to use net.kyori.adventure.text.Component

### Describe alternatives you've considered.

Create another class, but I don't know how the conversation system works. So, I have to give up.

**Comment by Owen1212055** [comment]
There was a similar issue to this opened in the past. In general, we are more set on deprecating this api.

**Comment by lijinhong11** [comment]
so when can it be true

**Comment by kashike** [comment]
The conversation API will not be expanded to support `Component`s - it will be deprecated entirely at some point.
