### ISSUE TITLE
zombie-villager-infection-chance not working since 1.20.2

### ISSUE THREAD

**Issue by Camillo82** [PaperSpigot/Paper#9896]
### Expected behavior

I am using latest build #260.
zombie-villager-infection-chance should be working but it is not

### Observed/Actual behavior

I have zombie-villager-infection-chance set to 10.0 but it is not working, villagers get infected 100% of a time (hard difficulty).
Before I updated the server from 1.20.1 it worked correctly.

### Steps/models to reproduce

set zombie-villager-infection-chance to 10.0
Spawn a villager and a zombie.
The villager always gets infected instead of dying 90% of a time.

### Plugin and Datapack List

Nothing that could affect villagers, nothing changed since 1.20.1.

### Paper version

#260

**Comment by Sytm** [comment]
If you want to have an infection rate of 10% you would need to use `0.1`, not `10`, because the range of possible values is from 0 to 1 (atleast on 1.20.2 where I can look at the source code).

The docs are outdated which can be seen that it uses `-1.0` as default and not `default`

**Comment by Camillo82** [comment]
I made it 0.1 instead of 10.0 and now it seems to working correctly! Thank you and sorry :)

**Comment by Machine-Maker** [comment]
@Camillo82 that is actually the wrong behavior, and will break when the fix for this is added. So make sure to change it back when this issue gets closed.
