### ISSUE TITLE
Intermittent Server Freezing

### ISSUE THREAD

**Issue by BourgeoisBear** [PaperSpigot/Paper#9903]
### Expected behavior

Smooth gameplay over the LAN.

### Observed/Actual behavior

On paper-1.20.1-196, I experience intermittent freezes (1-2 per hour), lasting for 5-10 seconds each.

### Steps/models to reproduce

Running with 3 players over a gigabit LAN, on a quad-core Xeon with 16GB of RAM.  Did not experience this nearly as often with paper-1.20.1-176.

### Plugin and Datapack List

No plugins or datapacks.

### Paper version

paper-1.20.1-196

**Comment by electronicboy** [comment]
Unsupported version, this is also more generally a support topic, rather than a bug report, which would generally be better discussed on discord
