### ISSUE TITLE
Issue Between Paper and Citizens Plugin

### ISSUE THREAD

**Issue by UPSOKen** [PaperSpigot/Paper#9912]
### Expected behavior

No errors.

### Observed/Actual behavior

Errors in console - and general issues with NPCs.

### Steps/models to reproduce

I will go over this in the "other" section.

### Plugin and Datapack List

**Plugins**

[15:55:27 INFO]: Server Plugins (1):
[15:55:27 INFO]: Bukkit Plugins:
[15:55:27 INFO]:  - Citizens

**Datapacks**

[15:55:01 INFO]: There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]
[15:55:01 INFO]: There are no more data packs available

### Paper version

[15:54:41 INFO]: This server is running Paper version git-Paper-279 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 274e54b)
You are running the latest version

### Other

I have an error I am getting ONLY with Paper and Citizens installed (Not happening with Spigot), and Citizens devs said to go to Paper to ask about it. I asked in paper Discord and was told to add it to the tracker, but then also was told that it likely wouldn't lead to anything because I'm the only one reporting it - and plugin support isn't offered, but Citizens devs present it as a bug with paper, not their plugin. I can replicate this across multiple computers on completely different hardware and OS. So, I don't know what to do at this point. Putting in here in hopes that someone can help me because I am losing my mind.

**After extensive testing for the last hour and 45 minutes:**

This appears to strictly be an issue with Paper servers.

Here's what I did:

- Made a complete copy of my server (50+ plugins). Then started the server, replicated the errors, shut off the server, removed ONE plugin, and then started over. I did this for every single plugin. Until I was down to Citizens only, still got the error.
- Tried several forks of paper (LightSpigot, Pufferfish) - all the same errors, with ONLY citizens installed.
- Tried latest paperMC - All the same errors.
- Tried latest spigot - no errors.

The errors are as follows:
- https://pastebin.com/ZtRnbdFm - This is what comes up whenever a player joins, or gets within render distance of an NPC. Appears randomly at the server start as well (But not every time).
- https://pastebin.com/TctfbQPy - This is what error happens whenever the player leaves the server and an NPC is currently rendered in. This happens every time a player is within render distance of an NPC (Player Entity NPC) and disconnects. Also appears to happen when they change worlds, or teleport away, outside of the render distance of the NPC.

**Comment by electronicboy** [comment]
2nd error is likely a side-effect of the first, looks like the logic there is busted and will just add in an illegal entry there
As for 1st, all we can generally see is that an entity is being added twice, I have no idea what citizens is doing here to induce this

**Comment by electronicboy** [comment]
2nd error has been patched by us, here: https://github.com/PaperMC/Paper/commit/4675152f4908431e0f944a7bf9fa3b2181a2dfd6
1st error appears to have been patched by citizens
