### ISSUE TITLE
PaperMC breaks the intended Vanilla behavior of emptying bundles.

### ISSUE THREAD

**Issue by buzzuppity** [PaperSpigot/Paper#9915]
### Expected behavior

When bundles have items inside them, and you right click drag to empty the bundle, after dragging your cursor away from the slot that was right clicked and then releasing RMB, the newest item added to the bundle's inventory will be placed. This is the behaviour using the vanilla Minecraft Server Jar.

### Observed/Actual behavior

Holding right click and dragging your cursor while emptying a bundle causes the bundle itself to be dropped into a slot.
This makes emptying bundles more difficult, as even the slightest movement while right clicking to remove an item from the bundle

### Steps/models to reproduce

Using vanilla Minecraft:
Obtain a bundle in any way, you can use /give commands: "/give @s minecraft:bundle 1"
Put any item inside, or any amount of items inside
Select the bundle with LMB
Try to hold right click on any inventory slot, then drag your cursor while holding RMB.
Release RMB. The newest item should be placed in the inventory slot that was selected.

To replicate the issue using PaperMC, repeat the steps above, and you should find that the bundle itself is dropped, and not the newest item, which is NOT the intended behaviour of Minecraft's bundles.

### Plugin and Datapack List

No plugins or datapacks applicable. Base PaperMC version was used in 1.20.2.

### Paper version

[09:40:31 INFO]: This server is running Paper version git-Paper-280 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 4675152)
You are running the latest version

**Comment by Machine-Maker** [comment]
Confirmed. This is a result of craftbukkit's mangling of the quickcraft/drag system. Basically it treats any mouse movement as a full drag, whereas in vanilla, its not a drag unless more than one slot was included in the drag. With the bundle, there is only 1 slot involved no matter how far you drag.
