### ISSUE TITLE
Opening an offline player's inventory using the OpenInv plugin will reset the player's world

### ISSUE THREAD

**Issue by KioProject123** [PaperSpigot/Paper#9928]
### Expected behavior

Players will spawn at the location where they last logged off

### Observed/Actual behavior

The player will spawn in the overworld, regardless of the world he was in before last offline

### Steps/models to reproduce

1、Player A goes to the Nether
2、Player A leaves the server
3、Player B uses the command `/openinv A` (Requires op permissions)
4、Player B closes the open GUI
5、Player A enters the server, will spawn in the overworld instead of the Nether

### Plugin and Datapack List

only OpenInv

### Paper version

This server is running Paper version git-Paper-280 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 4675152)
You are running the latest version

### Other

Spigot does not have this problem, but I will also feedback this issue to Openinv

**Comment by electronicboy** [comment]
Plugins accessing internals is not supported, this is likely a side-effect of: 

https://github.com/PaperMC/paper/commit/0cdce89d595a2c1c097c9e2a5ff96687977b3b25#diff-4cc9c08ffbbd0cd3194f84ba2456907e9a75b260a4e0a532a2762c762512b4edR93

basically, removing some legacy code from upstream which has been a fun source of problems for a few years now, issue is that they're not loading player data onto the player entity fully, and so, as a result, the world is being reset as they're not triggering the load of that data
