### ISSUE TITLE
Voxel planes planes are not properly replaced with resources.

### ISSUE THREAD

**Issue by mifjpn** [PaperSpigot/Paper#9932]
### Expected behavior

https://github.com/uran247/voxel-planes-datapack/releases/tag/v0.9.1
Paper 1.20.1 correctly replaced airplanes in resource packs. (light-resourcepack)
Parts are strange in 1.20.2.

### Observed/Actual behavior

Unfortunately, the donkey that seems to be used as the basis for resources also appears.
![2023-11-12_01 59 12](https://github.com/PaperMC/Paper/assets/7693274/1dcb22f6-ddcf-4f52-81f4-443404ae6a36)

### Steps/models to reproduce

https://github.com/uran247/voxel-planes-datapack/releases/tag/v0.9.1
I have inserted the data pack correctly according to the instructions. I summoned it with the same version of the Fabric-flavored client.

### Plugin and Datapack List

> datapack list
[02:19:46 INFO]: There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [file/voxel-planes.zip (world)]
[02:19:46 INFO]: There are no more data packs available

### Paper version

> version
[02:19:14 INFO]: Checking version, please wait...
[02:19:15 INFO]: This server is running Paper version git-Paper-280 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 4675152)
You are running the latest version

**Comment by Machine-Maker** [comment]
It doesn't look like that datapack has explicit support for 1.20.2? It's possible it needs to be updated. Can you try on vanilla 1.20.2 and see if you get the same issue?

**Comment by mifjpn** [comment]
I would like to give you the highest praise for your quick response to bugs.
However, since URAN is individually programmed, it is clear that many BUG certifications have not been achieved.
I submitted a bug report to URAN several version numbers ago.
At that time, airplanes, which were a resource, were not even displayed.
![2023-11-12_12 20 22](https://github.com/PaperMC/Paper/assets/7693274/abb537eb-1740-477c-8f43-44f741c2eae7)

However, it is displayed now.
So it's natural and inevitable to wonder if our response to this bug is having an effect.
Finally, I'll send you a screenshot of the results in the vanilla client you're looking for. The result is the same.
![2023-11-12_12 20 22](https://github.com/PaperMC/Paper/assets/7693274/abb537eb-1740-477c-8f43-44f741c2eae7)
Thank you in advance for your understanding.
