### ISSUE TITLE
First player spawn does not include yaw direction

### ISSUE THREAD

**Issue by vanquesh** [PaperSpigot/Paper#9933]
### Expected behavior

When players first join on my server they are facing the wrong direction. They are in the right location, but facing the wrong direction. I have set the world spawn location including the direction every possible way, using commands and the Paper API via a custom plugin but nothing is working.

### Observed/Actual behavior

When players first join they are in the right location but the yaw is 0 even though the world spawn location has yaw 180.

### Steps/models to reproduce

Change world spawn location to have non-zero yaw and join with a new player. The new player will not be facing in the same direction as the spawn location, even though their x y z coodinates are correct.

### Plugin and Datapack List

BlueMap, Core Protect, packetevents, ViaVersion, ViBackwards, Votifier, WorldEdit, and a custom plugin I made

### Paper version

This server is running Paper version git-Paper-280 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 4675152)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-261 (MC: 1.20.2)

**Comment by vanquesh** [comment]
I updated to the latest version but it's still broken:
```
This server is running Paper version git-Paper-288 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: aee3830)
You are running the latest version
Previous version: git-Paper-280 (MC: 1.20.2)
```

**Comment by Owen1212055** [comment]
Yaw is not saved with world spawn point. Intentional Minecraft behavior.

**Comment by TonytheMacaroni** [comment]
It is though? Specifically, the angle as mentioned [here](https://minecraft.wiki/w/Commands/setworldspawn#Arguments), and can be retrieved from `Level#getSharedSpawnAngle`/`LevelData#getSpawnAngle`?

**Comment by electronicboy** [comment]
The spawn command has an angle argument which lets you set that, so, it does exist as a thing

**Comment by electronicboy** [comment]
The way this is handled upstream looks kinda scuffed, theres generally a few areas where we get the levels spawn point but don't care about the angle, I'm guessing that this was a relatively recent addition that just wasn't handled by upstream?

**Comment by lynxplay** [comment]
![image](https://github.com/PaperMC/Paper/assets/32834385/8584c707-175f-4a93-adcc-a1e3d942b8af)
Caused by the recent changes on our end. We are fudging spawn position, however that thing resets yaw and pitch.
Idk who to blame here, hopefully not me.

**Comment by Owen1212055** [comment]
Tested on a vanilla server, this is intentional it seems like. However, when respawning it seems that vanilla doesn’t normally respect yaw? This needs to be looked into a bit.

**Comment by Machine-Maker** [comment]
Confirmed, this is a vanilla issue. The spawn angle is just ignored when the player's spawn location is "fudged". Even with a `spawnRadius` gamerule value of 0, the angle is ignored. There is an open [mojira](https://bugs.mojang.com/browse/MC-200092) report for it.

My concern is, that I don't exactly know what a clean fix is here. It doesn't immediately strike me that with a spawnRadius > 0, the yaw should always be respected. But I suppose that is the best option.
