### ISSUE TITLE
AdvancementDisplay Modifications violates Spigot API Compatibility

### ISSUE THREAD

**Issue by gmitch215** [PaperSpigot/Paper#9936]
### Is your feature request related to a problem?

Hello,
The modifications to `org.bukkit.advancement.Advancement` to return a Paper AdvancementDisplay that match different methods than those of its bukkit counterpart directly make Bukkit plugins (using the API) incompatible with Paper plugins.

### Describe the solution you'd like.

Either:
1. Make the Paper AdvancementDisplay extend the Bukkit One to create API compatibility
2. Copy (and maybe deprecate) the Bukkit methods to ensure Bukkit API Compatibility

### Describe alternatives you've considered.

None

**Comment by Machine-Maker** [comment]
@GamerCoder215 do you have an actual error that happens when a plugin compiled against spigot runs on Paper? We should be fixing this with bytecode rewriting at runtime.

**Comment by GamerCoder215** [comment]
```
[19:24:45 ERROR]: Error occurred while enabling StarCosmetics v1.3.0 (Is it up to date?)
java.lang.NoSuchMethodError: 'org.bukkit.advancement.AdvancementDisplay org.bukkit.craftbukkit.v1_20_R2.advancement.CraftAdvancement.getDisplay()'
```

Using Paper build 290 for 1.20.2
```
[19:25:16 INFO]: This server is running Paper version git-Paper-290 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: f186318)
You are running the latest version
```

**Comment by Machine-Maker** [comment]
Ok yeah, this is probably because you are calling the method on CraftAdvancement, whereas normal use with the API would call it on just Advancement. And the rewrite only checks for methods owned by Advancement.

**Comment by GamerCoder215** [comment]
> Ok yeah, this is probably because you are calling the method on CraftAdvancement, whereas normal use with the API would call it on just Advancement. And the rewrite only checks for methods owned by Advancement.

If you're rewriting the bytecode on the interface (I assume you then must rewrite the bytecode on the class), why does it matter?
Would this be fixed by not casting?

**Comment by electronicboy** [comment]
Because it rewrites method descriptors from the interface, not the impl class

**Comment by GamerCoder215** [comment]
> Because it rewrites method descriptors from the interface, not the impl class yes, not casting would resolve that

Worked.

**Comment by Machine-Maker** [comment]
Yeah, I think the solution here is for you to not call the method on CraftAdvancement, but just the Advancement interface. We can't really go around supporting every single implementation of every interface when we rewrite methods.
