### ISSUE TITLE
Trigger thrown_item_picked_up_by_entity work incorrectly

### ISSUE THREAD

**Issue by rumickon** [PaperSpigot/Paper#9947]
### Expected behavior

Advancement "Oh Shiny" obtain when player throw even one gold item and piglin pick it up.

### Observed/Actual behavior

Trigger "thrown_item_picked_up_by_entity" with "item" condition only triggers when player throws stack with two or more items in. Therefore, to get the advancement you need to throw out two gold items in the stack at the same time.

### Steps/models to reproduce

1. Revoke advancement by command `/advancement revoke @s only minecraft:nether/distract_piglin`
2. Take off the golden armor.
3. Drop one raw gold item near the piglin and wait for the piglin to pick it up. The advancement will not be obtained.
4. Drop two raw gold item the same time near the piglin and wait for the piglin to pick up one. The advancement will be obtained.

### Plugin and Datapack List

No plugins and only vanilla datapack.

### Paper version

This server is running Paper version git-Paper-291 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: ce7f068)
You are running the latest version
Previous version: git-Paper-196 (MC: 1.20.1)

**Comment by lynxplay** [comment]
Replicable, EntityPickupItemEvent fixes patch messes around and passes the item stack too late to the method
