### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by GoldenPonos** [PaperSpigot/Paper#9950]
### Stack trace

https://paste.gg/

### Plugin and Datapack List

Chunky
CoreProtect
FastAsyncWorldEdit-Bukkit
Geyser-Spigot
GSit-1.5.3
InvSee++
LibsDisguises
ProtocolLib
Skript
ViaBackwards
ViaRewind
ViaVersion

### Actions to reproduce (if known)

-start :start.bat"
-cmd starts
-crash

### Paper version

git-Paper-292 (MC: 1.20.20

### Other

it starts and after like 10 secends closes

**Comment by Warriorrrr** [comment]
You did not include any stack trace, please also use the discord for support.

**Comment by GoldenPonos** [comment]
what is stack trace?

**Comment by toinouH** [comment]
The logs of the crash @GoldenPonos
