### ISSUE TITLE
MaxNearbyEntities not obeyed by monster spawners

### ISSUE THREAD

**Issue by Brendon4496** [PaperSpigot/Paper#9966]
### Expected behavior

Only a certain amount of entities spawn within the range of the spawner (In the case of the video below, 5 entities)

### Observed/Actual behavior

MaxNearbyEntities is not obeyed by mob spawners and spawners will blow past the cap

### Steps/models to reproduce

https://github.com/PaperMC/Paper/assets/62525223/25113864-48a7-4d02-b17f-5902351039f5

### Plugin and Datapack List

None - Tested with only Paper

### Paper version

This server is running Paper version git-Paper-293 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: e5274ee)

### Other

I've confirmed that this isn't an issue with build 292, and happens on the latest build of Paper as well.

**Comment by TonytheMacaroni** [comment]
Issue is caused by this [part of the vanilla bugfixes patch](https://github.com/PaperMC/Paper/blob/master/patches/server/0856-Fix-a-bunch-of-vanilla-bugs.patch#L406-L421) implemented in #8945. The `clazz` parameter of the `tryCast` method shadows the `clazz` parameter of the `forExactClass` method.
