### ISSUE TITLE
Unsupported Java Detected even with "Paper.IgnoreJavaVersion"

### ISSUE THREAD

**Issue by GuardianLiarus** [PaperSpigot/Paper#9977]
### Expected behavior

Java version check should be ignored when starting the server

### Observed/Actual behavior

The version compatibility check runs anyway and stops the server's execution

### Steps/models to reproduce

Run an unsupported java version and try to run the server with "-paper.IgnoreJavaVersion=TRUE"

### Paper version

1.20.2 Build#307

### Other

I'd like to mention i was just trying to run Paper through Termux on my phone, which obviously isn't the intended usecase, but i came across this issue and couldn't figure out how to start the server even after [reading the documentation about system properties](https://docs.papermc.io/paper/reference/system-properties#paperignorejavaversion)

i have tried using "-DPaper.IgnoreJavaVersion=true" (which tells me it's not a recognized option)  as well as "-Paper.IgnoreJavaVersion=true" which just doesn't do anything at all

**I am using openjdk-17-internal**

**Comment by Warriorrrr** [comment]
What's the exact command line you're starting your server with?

> i have tried using "-DPaper.IgnoreJavaVersion=true" (which tells me it's not a recognized option) as well as "-Paper.IgnoreJavaVersion=true" which just doesn't do anything at all

Make sure you put that before the -jar, not after

**Comment by GuardianLiarus** [comment]
> What's the exact command line you're starting your server with?
> 
> > i have tried using "-DPaper.IgnoreJavaVersion=true" (which tells me it's not a recognized option) as well as "-Paper.IgnoreJavaVersion=true" which just doesn't do anything at all
> 
> Make sure you put that before the -jar, not after

That worked, thank you, sorry i didn't think the order of the command would matter, problem was between the chair and keyboard 😂
