### ISSUE TITLE
PlayerUUIDs for Offlineplayer

### ISSUE THREAD

**Issue by luchs888** [PaperSpigot/Paper#9986]
### Expected behavior

(Paper version #246)
In version #246, plugins were able to obtain PlayerUUIDs, even when the player is Offline. This was crucial for plugins to perform tasks like displaying Playerheads or generating Playerdatas.

### Observed/Actual behavior

(since Paper version #247+)
 However, starting from version #247, plugins are no longer able to retrieve the real UUIDs, and instead, fake UUIDs are generated when the Player is Offline. Especially in GUIs, the playerhead does not match to the skin (always shows default MC skins). This change appears to be associated with the GitHub modification: patches/server/0183-getPlayerUniqueId-API.patch.
(It still works in the latest Spigot version)

### Steps/models to reproduce

When running a Waterfall/BungeeCord server (or just paper) with Paper version #247 or newer and using a plugin that requires real UUIDs from the local server the plugins are impacted. This change, likely stemming from the mentioned GitHub patch, is implemented for efficiency reasons.

### Plugin and Datapack List

Bossshoppro, Spartan, VotingPlugin, vault, essentials, fawe, wordguard, votifier, Placeholderapi, premiumvanish, luckperms, Citizens, BlueMap, Dynmap, Craftbook, Protocollip, MyPet, LWC, 

### Paper version

Paper version git-Paper-309 (MC 1.20.2= (Implementing API version 1.20.2-R0.1-SNAPSHOP) (Git 2182d47)

### Other

Maby add a Config option to "fix" this. 

And Thanks for the hard work at Paper.

**Comment by lynxplay** [comment]
Can you provide some basic replication steps here in regards to what code fails to retrieve an offline player's uuid ?
