### ISSUE TITLE
option to enable giant ai

### ISSUE THREAD

**Issue by rudde0** [PaperSpigot/Paper#9997]
### Is your feature request related to a problem?

Giant's AI was removed long time ago.

[Purpur's Giant AI patch](https://github.com/PurpurMC/Purpur/blob/ver/1.20.2/patches/server/0024-Giants-AI-settings.patch) helps to adding giants as hostile mobs in the game.

Paper should have it either. Just a little gameplay feature that is small and harmless.

### Describe the solution you'd like.

This can be option and disabled as default to fit vanilla gameplay.

Like this,
- paper-world-defaults.yml
  - `entities.giant.ai.enabled` (bool)
  - `entities.giant.ai.also-hostile` (bool)

### Describe alternatives you've considered.

I tried to add several goals via Paper's MobGoals API but I can't manage it.

**Comment by rudde0** [comment]
> This is purpur territory, not paper

Why not?

**Comment by MiniDigger** [comment]
adding the mob goals can be done via a plugin and papers mob goal api
