### ISSUE TITLE
Equipping Armor

### ISSUE THREAD

**Issue by Navalke** [PaperSpigot/Paper#9999]
### Expected behavior

Hi. I have a plugin that blocks wearing netherite armor. When I uploaded this plugin to my Velocity proxy and spam to wear netherite armor , the plugin suddenly stop working without any error and I can wear armor (Actually plugin works if I try to wear it with right click while holding it or shift+click in inventory. It only doesnt work When I drag to armor bar and spam). here is my velocity.toml (https://pastebin.com/S90Nmb4T). Do you have any sugestion for me to find the problem's source. I'm sure it is because of velocity because plugin works in a paper server without velocity. To make you understand the plugin I ll attach a video that shows the problem 

### Observed/Actual behavior

Something blocking my plugin and my plugin cant block Netherite armor equipping

### Steps/models to reproduce

https://github.com/PaperMC/Paper/assets/109472441/e4645fa7-da51-4a0e-b6e6-44de95144886

### Plugin and Datapack List

Luckyperms and a custom rankup plugin which blocks equipping netherite armor

### Paper version

#318

**Comment by electronicboy** [comment]
> spam to wear

This is generally due to not handling the inventory drag event, velocity doesn't touch anything relating to this so is likely irrelevant. This is likely not a paper bug, at the very least, there is nothing reproducable to go off.
